// Real RaceClient/WebSocket interaction checks. Scene setup controls repeatability only.
export async function advanced545({api,open,start,sync,touch,shot,check,report}){
 const state=()=>api('state'),close=async p=>{await p.evaluate(()=>c.dispose());await p.close()},center=async(p,selector)=>{const r=await p.locator(selector).boundingBox();return{x:r.x+r.width/2,y:r.y+r.height/2}};
 report.layouts=[];
 if(!process.env.QA545_INPUTS)for(const kind of (process.env.QA545_LAYOUT_KIND?[process.env.QA545_LAYOUT_KIND]:['canal','hide','bomb','cart'])){
  console.log('responsive',kind);await api('reset',{kind});const p=await open();await start(p,kind);
  for(const [width,height]of [[320,568],[430,932],[844,390]]){
   await p.setViewportSize({width,height});await p.waitForTimeout(180);
   const q=await p.evaluate(k=>{const stage=document.querySelector(`[data-${{canal:'cn-stage496',hide:'hd-stage',bomb:'bb-stage',cart:'ct-stage'}[k]}]`),root=stage.closest('section'),controls=root.querySelector(k==='canal'?'[data-cn-action="burst"]':'footer'),r=stage.getBoundingClientRect(),f=controls.getBoundingClientRect();return {stage:r.toJSON(),footer:f.toJSON(),width:document.documentElement.scrollWidth,viewport:innerWidth,viewportHeight:innerHeight,error:c.error}},kind);
   check(q.stage.width>100&&q.stage.height>100,`${kind} field usable ${width}x${height}`);check(q.footer.width>0&&q.footer.height>0&&q.footer.bottom<=height+1,`${kind} controls clipped ${width}x${height}: ${q.footer.bottom}`);check(q.width<=width+1,`${kind} horizontal overflow`);check(!q.error,`${kind} client error`);report.layouts.push({kind,width,height,...q});if(width===844&&kind==='hide')await shot(p,'hide545-landscape');if(width===320)await shot(p,kind+'545-small');
  }
  await close(p);
 }
 if(process.env.QA545_LAYOUT_KIND&&!process.env.QA545_CONTINUE)return;
 if(!process.env.QA545_HIDE_ONLY){
 console.log('canal inputs / overlay / fallback');await api('reset',{kind:'canal'});let p=await open();await start(p,'canal');await api('canalSetup');await api('canalFeed');await p.waitForTimeout(100);
 const feed=await p.locator('.cn-feed496').boundingBox();check(feed.height<=25,'notification height bounded');await p.waitForTimeout(1200);check(await p.locator('.cn-feed496').isHidden(),'notification clears');
 const point=await p.evaluate(()=>{const r=document.querySelector('[data-cn-stage496]').getBoundingClientRect(),e=c.cnUI496.frameLayout.find(e=>e.kind!==3);return{x:r.left+e.x,y:r.top+e.y}}),t=await touch(p);await t.points([{id:1,...point}]);await t.up();await sync(p,100);check((await state()).players[0].lastSeq>0,'canal pointer input reaches server');
 await p.route('**/watermill.webp?qa-failure',r=>r.abort());await p.evaluate(()=>{delete c.cnUI496.background.dataset.fallback;c.cnUI496.background.src='./assets/canal545/watermill.webp?qa-failure'});await p.waitForFunction(()=>c.cnUI496.background.src.includes('shared-pond')&&c.cnUI496.background.naturalWidth>0);report.canalInteraction={boundedFeed:feed.height,pointerAccepted:true,fallbackLoaded:true};await close(p);
 console.log('bomb two-finger / keyboard / kick / peer');await api('reset',{kind:'bomb',humans:2});p=await open();let peer=await open(390,844,'p1');await start(p,'bomb',[p,peer]);await api('bombMoveScene');await p.waitForTimeout(200);let t2=await touch(p),canvas=await p.locator('[data-bb-canvas]').boundingBox(),finger={id:1,x:canvas.x+100,y:canvas.y+canvas.height*.65};await t2.points([finger]);finger={...finger,x:finger.x+42};await t2.move([finger]);await sync(p,150);let s=await state();check(s.players[0].x>2.5,'drag steers');const b=await center(p,'[data-bb-control="bomb"]');await t2.points([finger,{id:2,...b}]);await sync(p,150);s=await state();check(s.bombs.some(b=>b.planter===0),'second finger places while steering');check(s.players[0].steer545===1,'bomb action preserves steering');await t2.up([finger]);await t2.up();await sync(p,50);const stopped=(await state()).players[0].x;await sync(p,200);check((await state()).players[0].x===stopped,'lift stops');
 await api('bombMoveScene');await p.waitForTimeout(120);await p.locator('[data-bb-canvas]').focus();await p.keyboard.down('ArrowUp');await sync(p,150);check((await state()).players[0].y<4.5,'keyboard steers');await p.keyboard.up('ArrowUp');await sync(p,50);const y=(await state()).players[0].y;await sync(p,100);check((await state()).players[0].y===y,'key-up stops');
 await api('bombScene');await p.waitForTimeout(160);await p.locator('[data-bb-control="kick"]').tap();await sync(p,50);s=await state();check(s.bombs.some(b=>b.owner===0&&b.relay>=2),'kick transfers ownership');await peer.waitForFunction(()=>c.state.bomb.bombs.some(b=>b.owner===0&&b.relay>=2));check(await p.evaluate(()=>c.state.bomb.players[0].color499!==c.state.bomb.players[1].color499),'custom player colors remain distinct');
 await api('bombMoveScene');await p.waitForTimeout(100);t2=await touch(p);await t2.points([finger]);await t2.move([{...finger,y:finger.y-40}]);await sync(p,100);await t2.cancel();await sync(p,50);check((await state()).players[0].steer545==null,'touch cancel stops');report.bombInteraction={twoFingerPlace:true,liftStop:true,cancelStop:true,keyUpStop:true,kickPeerSync:true};await close(peer);await close(p);
 console.log('cart aim / hold release / peer');await api('reset',{kind:'cart',humans:2});p=await open();peer=await open(390,844,'p1');await start(p,'cart',[p,peer]);await api('cartAimScene');await p.waitForTimeout(150);const slider=p.locator('[data-ct-aim]');await slider.focus();await p.keyboard.press('Home');for(let i=0;i<28;i++)await p.keyboard.press('ArrowRight');await sync(p,50);check(Math.abs((await state()).players[0].aim545+7*Math.PI/180)<.001,'native slider reaches authority');
 await shot(p,'cart545-bank-aim');const push=await center(p,'[data-ct-control="push"]'),tc=await touch(p);await tc.points([{id:1,...push}]);await sync(p,50);await api('run',{running:true});await p.waitForTimeout(1000);await tc.up();await p.waitForTimeout(150);await api('run',{running:false});s=await state();check(s.players[0].launched&&s.players[0].vx<0,'angled release launches');check(s.players[0].power>.4&&s.players[0].power<.8,'hold determines strength');await peer.waitForFunction(()=>c.state.cart.players[0].launched);check(await slider.isDisabled(),'aim fixed after release');report.cartInteraction={aim:s.players[0].aim545,power:s.players[0].power,peerSync:true};
 await api('cartAimScene',{round:2});await p.waitForTimeout(120);const box=await p.locator('[data-ct-canvas]').boundingBox();await p.touchscreen.tap(box.x+box.width*.8,box.y+box.height*.45);await sync(p,50);check((await state()).players[0].aim545>0,'course tap changes aim');const q=await center(p,'[data-ct-control="push"]'),touchCancel=await touch(p);await touchCancel.points([{id:1,...q}]);await sync(p,50);await touchCancel.cancel();await sync(p,50);check(!(await state()).players[0].launched&&(await state()).players[0].chargeAt==null,'cart cancellation does not launch');await close(peer);await close(p);
 }
 let p;console.log('hide visibility and render cache');await api('reset',{kind:'hide'});p=await open();await start(p,'hide');await p.waitForTimeout(800);
 const spot=await api('hideSetup'),hg=await state(),kingSeat=hg.hunterSeat;await api('hidePlace',{players:[{seat:kingSeat,x:spot.x+205,y:spot.y}]});await p.waitForTimeout(300);const seen=await p.evaluate(()=>({authorized:Number.isFinite(c.state.hide.players[c.state.hide.hunterSeat].x),sample:c.hideUI536.renderer.visible545.get('king')}));check(seen.authorized&&seen.sample,'nearby hunter visible');await api('hidePlace',{players:[{seat:kingSeat,x:hg.map.width-200,y:hg.map.height-200}]});await p.waitForTimeout(45);const lost=await p.evaluate(()=>({hidden:!Number.isFinite(c.state.hide.players[c.state.hide.hunterSeat].x),sample:c.hideUI536.renderer.visible545.get('king')}));check(lost.hidden&&lost.sample&&Math.hypot(lost.sample.x-seen.sample.x,lost.sample.y-seen.sample.y)<1,'lost hunter freezes last authorized sample');await p.waitForTimeout(280);check(await p.evaluate(()=>!c.hideUI536.renderer.visible545.has('king')),'hunter fades out');await api('hidePlace',{players:[{seat:kingSeat,x:spot.x+205,y:spot.y}]});await p.waitForTimeout(2400);await shot(p,'hide545-hunter');report.hideVisibility={authorityRespected:true,freezeAtLastSeen:true,fadeExpires:true};
 report.hidePresentation=await p.evaluate(async()=>{const {paint536}=await import('/src/hide/Renderer536.js'),u=c.hideUI536,r=u.renderer,g=c.state.hide,before=r.terrainBuilds,miniBefore=r.miniBuilds,decor=r.decorNodes,values=[];for(let i=0;i<150;i++){const t=performance.now();paint536(r,g,c.transport.selfId,u,Date.now()+i*16.67,false);values.push(performance.now()-t)}values.sort((a,b)=>a-b);return {terrainBuildsBefore:before,terrainBuildsAfter:r.terrainBuilds,miniBuildsBefore:miniBefore,miniBuildsAfter:r.miniBuilds,decorCacheReused:r.decorNodes===decor,sceneObjects:g.map.decor.length+g.objects.length,visibleObjects:r.drawn545,medianMs:values[75],p95Ms:values[142],friendCount:g.players.filter(q=>!q.hunter&&q.alive&&q.playerId!==c.transport.selfId&&Number.isFinite(q.x)).length}});
 check(report.hidePresentation.terrainBuildsBefore===report.hidePresentation.terrainBuildsAfter&&report.hidePresentation.miniBuildsBefore===report.hidePresentation.miniBuildsAfter&&report.hidePresentation.decorCacheReused,'hide static caches reused');check(report.hidePresentation.friendCount===2,'all living teammates available');
 await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>{c.hideUI536.reduced=true});await p.locator('[data-hd-action="map"]').click();await p.waitForTimeout(200);await shot(p,'hide545-map');await close(p);
}
