import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const server=spawn(process.execPath,['--import',fileURLToPath(new URL('./catalog-fixture.mjs',import.meta.url)),fileURLToPath(new URL('./qa-server.mjs',import.meta.url))],{stdio:['ignore','pipe','pipe']});server.stderr.on('data',d=>process.stderr.write(d));await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(String(d).includes('listening'))resolve()});server.on('exit',code=>reject(Error('server exit '+code)))});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const base='http://127.0.0.1:8536',out=process.env.QA_OUT_DIR??fileURLToPath(new URL('../../docs/build538',import.meta.url)),doc=fileURLToPath(new URL('../../docs/build538',import.meta.url)),errors=[],baseAssetsMissing=[],results=[];await mkdir(out,{recursive:true});
const api=async(path,data={})=>{const r=await fetch(base+'/qa/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});return r.json()};
const check=(x,msg)=>{if(!x)throw Error(msg)};
async function open(width,height,self='p0'){const p=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400){if(new URL(r.url()).pathname==='/assets/cabbage484/kitchen.png')baseAssetsMissing.push('Historical checkout omits cabbage kitchen art');else errors.push(r.status()+' '+r.url())}});await p.goto(base+'/preview.html?self='+self);await p.waitForFunction(()=>window.qaReady);await p.evaluate(()=>document.fonts.ready);return p}
async function sync(p,ms=50){await p.waitForTimeout(35);await api('advance',{ms});await p.waitForTimeout(100)}
async function start(p){await p.locator('[data-party-action462="ready"]').click();await p.locator('[data-hd-action="start"]').click();await p.waitForFunction(()=>c.state.hide.phase==='hiding')}
async function tapWorld(p,x,y){const b=await p.locator('[data-hd-canvas]').boundingBox(),cam=await p.evaluate(()=>c.hideUI536.renderer.camera);await p.mouse.click(b.x+(x-cam.x)*cam.scale,b.y+(y-cam.y)*cam.scale)}
try{
 for(const [width,height]of [[320,568],[390,844],[430,932]]){
  console.log('viewport',width,height);await api('reset',{role:'hider'});const p=await open(width,height);if(width===390)await p.screenshot({path:out+'/hide538-lobby.png',fullPage:true});await start(p);await api('disableAI');
  check(await p.locator('[data-hd-prop]').count()===2,'two choices');const choice=await p.locator('[data-hd-prop]').nth(1).getAttribute('data-hd-prop');await p.locator('[data-hd-prop]').nth(1).click();await sync(p);check(await p.evaluate(()=>c.state.hide.players[0].kind)===Number(choice),'transform choice');
  const goal=await p.evaluate(async()=>{const M=await import('/src/hide/Map537.js'),g=c.state.hide,p=g.players[0];return M.nav537(g.map).find(q=>Math.hypot(q.x-p.x,q.y-p.y)>130&&Math.hypot(q.x-p.x,q.y-p.y)<190&&M.line537(g.map,p,q,24)&&M.line537(g.map,q,{x:q.x-130,y:q.y},24))});check(goal,'nearby walking spot');const before=await p.evaluate(()=>({x:c.state.hide.players[0].x,y:c.state.hide.players[0].y}));await tapWorld(p,goal.x,goal.y);await sync(p,700);check(await p.evaluate(b=>Math.hypot(c.state.hide.players[0].x-b.x,c.state.hide.players[0].y-b.y)>60,before),'tap movement');
  await p.locator('[data-hd-action="stop"]').click();await sync(p,50);await sync(p,20000);check(await p.evaluate(()=>c.state.hide.phase)==='play','play');check(await p.locator('[data-hd-prop]').first().isDisabled(),'disguise locked');
  const fit=await p.evaluate(()=>({width:document.body.scrollWidth,stop:document.querySelector('[data-hd-action="stop"]').getBoundingClientRect().toJSON(),stage:document.querySelector('[data-hd-stage]').getBoundingClientRect().toJSON(),scale:visualViewport.scale}));check(fit.width<=width,'horizontal overflow');check(fit.stop.bottom<=height+1,'clipped stop');check(fit.stage.height>220,'stage too short');
  check(await p.locator('[data-hd-stick]').count()===0,'stick removed');
  const canvas=await p.locator('[data-hd-canvas]').boundingBox();await p.mouse.move(canvas.x+canvas.width*.55,canvas.y+canvas.height*.55);await p.mouse.down();await p.mouse.move(canvas.x+canvas.width*.68,canvas.y+canvas.height*.5,{steps:8});await p.mouse.up();await sync(p,400);check(await p.evaluate(()=>c.hideUI536.destination!==null),'drag sets destination');await p.locator('[data-hd-action="stop"]').click();await sync(p,50);const stopped=await p.evaluate(()=>({x:c.state.hide.players[0].x,y:c.state.hide.players[0].y}));await sync(p,500);check(await p.evaluate(b=>Math.hypot(c.state.hide.players[0].x-b.x,c.state.hide.players[0].y-b.y)<1,stopped),'stop works');
  const elapsed=await p.evaluate(()=>c.state.hide.elapsed);await sync(p,30050-elapsed);check(await p.evaluate(()=>c.state.hide.objects.some(o=>o.owner==='p0'&&o.shaking)),'mandatory shake');if(width===390)await p.screenshot({path:out+'/hide538-hider.png'});
  await p.locator('[data-hd-action="map"]').click();await p.waitForTimeout(100);check(await p.evaluate(()=>c.hideUI536.mapOpen),'map opens');if(width===390)await p.screenshot({path:out+'/hide538-map.png'});await p.locator('[data-hd-action="map"]').click();
  await p.locator('[data-hd-canvas]').dblclick({position:{x:width/2,y:fit.stage.height/2}});await sync(p,50);check(await p.evaluate(()=>visualViewport.scale)===1,'double tap zoom');
  if(width===390){await p.locator('[data-hd-action="stop"]').click();await sync(p,50);const origin=await p.evaluate(async()=>{const M=await import('/src/hide/Map537.js');return M.nearest537(c.state.hide.map,{x:300,y:4050})});await api('position',{seat:0,x:origin.x,y:origin.y});await sync(p,50);const goal=await p.evaluate(async()=>{const M=await import('/src/hide/Map537.js'),g=c.state.hide,p=g.players[0];return M.nav537(g.map).sort((a,b)=>Math.hypot(b.x-p.x,b.y-p.y)-Math.hypot(a.x-p.x,a.y-p.y)).slice(0,100).find(q=>{const route=M.path537(g.map,p,q);let last=p,total=0;for(const n of route){total+=Math.hypot(n.x-last.x,n.y-last.y);last=n}return total>4700})});check(goal,'long journey for fatigue');await p.locator('[data-hd-action="map"]').click();await p.waitForTimeout(100);await tapWorld(p,goal.x,goal.y);await sync(p,16500);check(await p.evaluate(()=>c.state.hide.players[0].exhausted),'real walking exhausts stamina');check((await p.locator('[data-hd-staminalabel]').textContent()).includes('息切れ'),'fatigue HUD');await p.locator('[data-hd-action="stop"]').click();await sync(p,2200);check(await p.evaluate(()=>!c.state.hide.players[0].exhausted),'rest recovery');await api('position',{seat:0,x:4200,y:3700});await sync(p,100);await p.screenshot({path:out+'/hide538-garden.png'});}
  await sync(p,200000);await p.waitForSelector('.hd-result536');check(await p.evaluate(()=>c.state.hide.reason)==='time','timeout');check(await p.locator('.hd-standings536 article').count()===4,'four standings');check(await p.locator('[data-party-result490="again"]').isEnabled(),'replay');if(width===390)await p.screenshot({path:out+'/hide538-result.png',fullPage:true});check(await p.evaluate(()=>!document.querySelector('meta[name="viewport"]').content.includes('user-scalable=no')),'zoom restored');await p.locator('[data-party-result490="again"]').click();await p.waitForSelector('.hd-lobby536');await start(p);await api('disableAI');await sync(p,210000);await p.waitForSelector('.hd-result536');await p.locator('[data-party-result490="list"]').click();await p.waitForSelector('[data-party-game462="hide"]');
  results.push({width,height,twoChoices:true,tapMovement:true,dragDestinationAndStop:true,mandatoryShake:true,mapToggle:true,disguiseLocked:true,timeout:true,replay:true,returnToList:true,zoomRestored:true,fit});await p.close();
 }
 console.log('four websocket clients');await api('reset',{role:'hunter',humans:4});const pages=[];for(let i=0;i<4;i++)pages.push(await open(390,844,'p'+i));for(const p of pages)await p.locator('[data-party-action462="ready"]').click();await pages[0].locator('[data-hd-action="start"]').click();await pages[0].waitForFunction(()=>c.state.hide.phase==='hiding');check(await pages[0].evaluate(()=>c.state.hide.objects.length)===0,'prep concealment');await sync(pages[0],20500);const p=pages[0];check(await p.evaluate(()=>c.state.hide.players[1].x===undefined),'hunter private snapshot');check(await pages[1].evaluate(()=>Number.isFinite(c.state.hide.players[2].x)&&Number.isFinite(c.state.hide.players[3].x)),'allied positions shared');
 // Continuous frames must preserve the immutable map even without a full state broadcast.
 await api('run',{running:true});await p.waitForTimeout(450);await api('run',{running:false});check(await p.evaluate(()=>c.state.hide.map.rooms.length===9),'map lost in frames');
 let raw=await api('state');const room=raw.map.rooms.find(r=>r.theme===2)??raw.map.rooms[4];await api('position',{seat:0,x:room.cx,y:room.cy+230});await sync(p,3200);await p.screenshot({path:out+'/hide538-hunter.png'});
 const decoy=await p.evaluate(()=>c.state.hide.objects.find(o=>!o.shaking));check(decoy,'visible prop');await api('position',{seat:0,x:decoy.x,y:decoy.y+50});await sync(p,100);await tapWorld(p,decoy.x,decoy.y-30);await sync(p,100);check(await p.locator('[data-hd-attack]').isEnabled(),'decoy attack enabled');await p.locator('[data-hd-attack]').click();await sync(p,800);check(await p.evaluate(()=>c.state.hide.shots)===2,'miss cost');await sync(p,10100);check(await p.evaluate(()=>c.state.hide.shots)===3,'charge refills and caps');
 const spot=await p.evaluate(async()=>{const M=await import('/src/hide/Map537.js'),g=c.state.hide;return M.nav537(g.map).find(q=>M.free537(g.map,q.x-90,q.y)&&M.line537(g.map,q,{x:q.x-90,y:q.y},24)&&g.objects.every(o=>Math.hypot(o.x-q.x,o.y-q.y)>85)&&q.x>800&&q.x<2000&&q.y>800&&q.y<2000)});check(spot,'open capture scenario');for(let i=1;i<4;i++){await p.locator('[data-hd-action="stop"]').click();await sync(p,50);await api('position',{seat:i,x:spot.x,y:spot.y});await api('position',{seat:0,x:spot.x-90,y:spot.y});await sync(p,800);raw=await api('state');const t=raw.players[i];await tapWorld(p,t.x,t.y-30);await sync(p,150);check(await p.evaluate(id=>c.hideUI536.targetId===id,t.objectId),'selection human '+i);await p.locator('[data-hd-attack]').click();await sync(p,750);if(i===1)check(await pages[1].locator('[data-hd-caught]').isVisible(),'caught state')}

 await p.waitForSelector('.hd-result536');check(await p.evaluate(()=>c.state.hide.winningSide)==='hunter','hunter wins');check(await p.evaluate(()=>c.state.hide.shots)===0,'three capture costs');results.push({fourRealWebSocketClients:true,privateSnapshots:true,mapRetainedAcrossFrames:true,alliedPositionsShared:true,chargeRefill:true,missConsumesOne:true,captureAll:true,caughtControlsDisabled:true,hunterVictory:true});for(const p of pages)await p.close();
 check(!errors.length,errors.join('\n'));const report={engine:await browser.version(),viewportEmulation:'Chromium mobile touch; not physical iPhone Safari',baseCharacterCatalog:'QA-only placeholders for four historical base modules absent from checkout; hide rules/view/canvas/assets/coordinator and WebSocket frames are production code',results,errors,baseAssetsMissing:[...new Set(baseAssetsMissing)]};await writeFile(doc+'/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){const p=browser.contexts()[0]?.pages()[0];if(p){await p.screenshot({path:out+'/hide538-debug.png'});console.log('debug state',await p.evaluate(()=>({error:c.error,hide:c.state.hide?.phase,player:c.state.hide?.players[0],ui:{target:c.hideUI536?.targetId,steering:c.hideUI536?.steering}})))}console.log('errors',errors);throw e}finally{await browser.close();server.kill()}
