import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {speciesSource,heroSource,visualSource,monsterSource} from '../build529/catalog-fixture.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const game=fileURLToPath(new URL('../../',import.meta.url)),out=resolve(game,'docs/build534');await mkdir(out,{recursive:true});
const font=process.env.QA_FONT_DIR,fixtures={'/src/data/species.js':speciesSource,'/src/data/endgameCharacters.js':heroSource,'/src/ui/MonsterVisual.js':visualSource,'/src/models/Monster.js':monsterSource};
const server=createServer(async(req,res)=>{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(path==='/preview.html'){const css=['build524-fishing','build525-fishing','build526-fishing','build530-fishing','build531-fishing','build532-fishing','build534-fishing'];res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'+css.map(s=>'<link rel="stylesheet" href="/src/Styles/'+s+'.css">').join('')+(font?'<link rel="stylesheet" href="/font/400.css">':'')+'<style>*{box-sizing:border-box}html,body{margin:0;background:#09291f;color:#fff5d1;font-family:sans-serif}button,input{font:inherit}.qa-portrait{font-size:30px}'+(font?'*{font-family:"Noto Sans JP",sans-serif!important}':'')+'</style><main id="app"></main><script type="module" src="/tools/build534/preview.mjs"></script></html>');return}const isFont=path.startsWith('/font/'),root=isFont?font:game,relative=isFont?path.slice(5):path;try{const target=resolve(root,'.'+relative);if(!target.startsWith(resolve(root)+'/'))throw Error();const data=await readFile(target);res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml'})[extname(target)]??'application/octet-stream');res.end(data)}catch{if(fixtures[path]){res.setHeader('Content-Type','text/javascript');res.end(fixtures[path])}else{res.statusCode=404;res.end('missing '+path)}}});await new Promise(r=>server.listen(8534,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const errors=[],results=[];
try{for(const [width,height] of [[320,568],[390,700],[430,800]]){
 const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
 await page.goto('http://127.0.0.1:8534/preview.html');await page.waitForFunction(()=>window.qaReady);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(250);
 const fit=await page.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,bottom:r.bottom}};return{bodyWidth:document.body.scrollWidth,stage:rect('.fi-stage524'),deck:rect('.fi-deck524'),growth:rect('.fi-growth531')}});if(fit.bodyWidth>width||fit.deck.bottom>height+1||fit.stage.h<160)throw Error('layout '+JSON.stringify(fit));
 await page.evaluate(()=>{setPlayingQA(false);chooseQA('moonlure')});await page.waitForTimeout(80);
 await page.locator('[data-fi-baitbutton]').tap();await page.waitForTimeout(100);if(await page.evaluate(()=>modeQA())!=='aim')throw Error('not manual aim');if(await page.evaluate(()=>stateQA().players[0].rod)!==2)throw Error('rod training');
 const stage=page.locator('[data-fi-stage]'),b=await stage.boundingBox();await stage.tap({position:{x:b.width*.5,y:b.height*.24}});await page.waitForTimeout(100);const state=await page.evaluate(()=>stateQA());if(state.players[0].fish.id!=='moonray'||state.players[0].castBait530.id!=='moonlure')throw Error('lure catch');
 const castCount=await page.evaluate(()=>sent.filter(x=>x.cast).length);if(castCount!==1)throw Error('duplicate cast');
 const reel=await page.locator('[data-fi-reel]').boundingBox();await page.mouse.move(reel.x+reel.width/2,reel.y+reel.height/2);await page.mouse.down();await page.evaluate(()=>elapseQA(4000));await page.mouse.up();await page.waitForTimeout(100);if(await page.evaluate(()=>modeQA())!=='aim')throw Error('recovery');
 await page.evaluate(()=>chooseQA('moonray'));await page.waitForTimeout(100);if(width===390)await page.screenshot({path:out+'/special-catch.png'});
 await page.locator('[data-fi-keepbutton]').tap();if(!(await page.evaluate(()=>stateQA().players[0].score>0&&stateQA().players[0].rod===2)))throw Error('cashout or retained rod');
 if(await page.evaluate(()=>lordQA())!=='visible')throw Error('retry boss');await page.waitForTimeout(100);
 await page.evaluate(()=>chooseQA('tigerpuffer'));await page.waitForTimeout(100);if(!(await page.locator('[data-fi-learning]').textContent()).includes('食中毒'))throw Error('missing food danger');await page.evaluate(()=>chooseQA('stonefish'));await page.waitForTimeout(100);if(!(await page.locator('[data-fi-learning]').textContent()).includes('毒のあるトゲ'))throw Error('missing spine danger');if(width===390)await page.screenshot({path:out+'/danger-catch.png'});await page.evaluate(()=>chooseQA('barreleye'));await page.waitForTimeout(100);if(!(await page.locator('[data-fi-learning]').textContent()).includes('透明'))throw Error('new fish knowledge');if(width===390)await page.screenshot({path:out+'/barreleye-catch.png'});await page.evaluate(()=>chooseQA('oldtire'));await page.waitForTimeout(120);if(!(await page.locator('[data-fi-keepbutton]').textContent()).includes('回収'))throw Error('trash recovery label');if(await page.locator('[data-fi-baitbutton]').isVisible())throw Error('trash bait action visible');if(width===390)await page.screenshot({path:out+'/trash-catch.png'});const before=await page.evaluate(()=>stateQA().players[0].score);await page.locator('[data-fi-keepbutton]').tap();if(await page.evaluate(()=>stateQA().players[0].score)!==before+15)throw Error('cleanup reward');await page.evaluate(()=>chooseQA('rabbitfish'));await page.waitForTimeout(100);if(!(await page.locator('[data-fi-learning]').textContent()).includes('毒のあるトゲ'))throw Error('rabbitfish warning');await page.evaluate(()=>chooseQA('spottedknifejaw'));await page.waitForTimeout(100);if(!(await page.locator('[data-fi-learning]').textContent()).includes('食中毒'))throw Error('ciguatera warning');await page.evaluate(()=>lobbyQA());await page.locator('.fi-guide531 summary').tap();await page.locator('.fi-guide531').scrollIntoViewIfNeeded();const count=await page.locator('.fi-catalog531 article').count();if(count!==152)throw Error('catalog count');const allScroll=await page.locator('.fi-catalog531').evaluate(e=>{e.scrollTop=e.scrollHeight;return e.scrollTop>0});if(!allScroll)throw Error('catalog clipped');await page.waitForTimeout(200);if(width===390)await page.screenshot({path:out+'/catalog-lords.png'});
 for(const [filter,count] of [['market',24],['danger',14],['curio',4],['real',88],['new',32],['deep',5],['shore',24],['trash',8],['all',152]]){await page.locator('[data-fi-filter532="'+filter+'"]').tap();const shown=await page.locator('.fi-catalog531 article:not([hidden])').count();if(shown!==count)throw Error('filter '+filter+' '+shown);if(width===390&&['new','shore','trash','danger'].includes(filter))await page.screenshot({path:out+'/guide-'+filter+'.png'});}const art=await page.evaluate(async()=>Promise.all(['shore','finds'].map(async name=>{const img=new Image();img.src='/assets/fishing534/'+name+'.webp';await img.decode();return{name,width:img.naturalWidth,height:img.naturalHeight}})));results.push({width,height,fit,catalog:count,art,manualCast:true,recovery:true,rodRetained:true,lordRetry:true});await page.evaluate(()=>disposeQA());await page.close();
 }if(errors.length)throw Error(errors.join('\n'));await writeFile(out+'/browser-results.json',JSON.stringify({engine:'Chromium mobile emulation, production fishing view/rules/controls; QA-only absent base catalogs and character portraits',results,errors},null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close();server.close()}
