import {QUIZ513,symbol513} from './Rules513.js';
import {position514,moving514,side514,closeGate514} from './Movement514.js';
const clamp=n=>Math.max(0,Math.min(1,n));
export function quizSignature513(g){if(!g)return null;if(['lobby','result'].includes(g.phase))return g;return{id:g.id,phase:'play',members:g.members.map(p=>({playerId:p.playerId,name:p.name,choice:p.choice})),players:g.players.map(p=>({playerId:p.playerId,name:p.name,choice:p.choice,color499:p.color499,seat:p.seat}))}}
export function frame513(g,at,selfId,reduced=false){
 const elapsed=Math.max(0,at-g.phaseAt),remaining=Math.max(0,(g.deadline??at)-at),question=g.phase==='question',revealing=g.phase==='reveal',seconds=Math.ceil(remaining/1000),t=question?clamp(elapsed/QUIZ513.questionMs):g.phase==='lock'||revealing?1:0,fall=revealing?clamp((elapsed-450)/900):0,me=g.players.find(p=>p.playerId===selfId),canChoose=question&&remaining>0&&!!me?.alive,hasSurvivor=g.players.some(p=>p.alive),lift=revealing&&hasSurvivor?clamp((elapsed-2250)/650)*(1-clamp((elapsed-5500)/600)):0,ascent=revealing&&hasSurvivor?clamp((elapsed-2600)/3000):0;
 return{revealBeat:!revealing?null:elapsed<1300?'collapse':elapsed<2250?'magma':elapsed<5600&&hasSurvivor?'lift':'rest',seconds,remaining,progress:t,warning:question&&remaining>0&&remaining<=5000,urgent:question&&remaining>0&&remaining<=3000,canChoose,answer:g.reveal?.answer??null,fall,lift:reduced?0:lift,ascent:reduced?0:ascent,wallY:reduced?(t<1?-45:0):-45*(1-t),shaking:!reduced&&(question&&remaining>0&&remaining<=3000||lift>0&&ascent<1),count:g.phase==='countdown'?Math.max(1,Math.ceil(remaining/1000)):null,
 heading:g.phase==='countdown'?'床をタップして、歩こう。':g.phase==='lock'?(g.question?.text??'壁が閉じた。'):revealing?`正解は ${symbol513(g.reveal.answer)}`:g.question?.text??'',explanation:revealing?g.reveal.explanation:'',category:g.question?.category??g.reveal?.category??'SURVIVAL QUIZ',status:!me?'観戦中':!me.alive?'脱落 · 観戦中':question?(remaining===0?'壁が閉じた。足元で判定。':'床をタップして移動 · 壁が閉まる前に渡り切ろう'):revealing?(lift>0?'正解の足場で、さらに上へ。':''):'',
 rows:g.players.map(player=>{let p=player;if(question&&remaining===0&&p.alive){p=JSON.parse(JSON.stringify(p));closeGate514(p,g.deadline)}const hit=g.reveal?.rows.find(r=>r.seat===p.seat),justFell=revealing&&hit?.wasAlive&&!hit.correct,point=position514(p,reduced?Math.min(p.motion514?.until??at,g.deadline??at):at),drop=justFell?(reduced?1:fall):0,walking=!reduced&&moving514(p,at),side=side514(point),bumped=p.bumpAt514!=null&&at>=p.bumpAt514&&at<p.bumpAt514+400;
 return{...point,seat:p.seat,hidden:!p.alive&&!justFell||drop>=1,drop,lift:p.alive&&!reduced?lift:0,side,alive:p.alive,status:!p.alive?'脱落':bumped?'押し戻された！':`${symbol513(side)}${walking?'へ移動中':''}`,moving:walking,bumped}
 }),effects:['o','x'].map(side=>{const count=g.reveal?.rows.filter(r=>r.wasAlive&&!r.correct&&r.side===side).length??0,local=elapsed-1300;return{side,active:revealing&&count>0&&local>=0&&local<2200,burst:clamp(local/700),smoke:clamp((local-150)/1900),count}})}
}
export const animating513=(g,at,reduced=false)=>!reduced&&(['countdown','question'].includes(g.phase)&&at<g.deadline||g.phase==='reveal'&&at<g.phaseAt+5700||g.players.some(p=>p.alive&&moving514(p,at)));
