import {playerColor499} from '../party/PartyColors499.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
import {property506,style506} from '../gorilla/Performance506.js';
import {tapPoint514,spawn514,position514} from './Movement514.js';
import {symbol513} from './Rules513.js';
import {frame513,animating513} from './Presentation513.js';
import {unlock513,cue513,stop513,close513} from './Audio513.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.qUI513??={sound:true,search:'',limit:24,pending:null,seq:0,lastSend:0};
const clock=c=>Date.now()+(c.offset??0);
const portrait=(c,p)=>c.sgMonster463?.(p.choice?.speciesId??p.speciesId)??'';
const name=(c,p)=>p.playerId===c.transport.selfId?'あなた':esc(p.name);
const color=p=>playerColor499(p).hex;
const header=c=>`<header class="q-header513"><button data-party-action462="browse">‹ パーティー</button><div><small>LAST PLATFORM</small><b>〇×サバイバル</b></div><button data-q-action513="sound" aria-pressed="${ui(c).sound}" data-q-sound513>音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),p=c.state.party,me=g.members.find(m=>m.playerId===c.transport.selfId),pm=p.members.find(m=>m.playerId===c.transport.selfId),host=p.hostId===c.transport.selfId,all=c.roster().filter(m=>!u.search||c.sgSpeciesName463(m.raceSpeciesId??m.speciesId).includes(u.search));return`<section class="q513 q-lobby513">${header(c)}<div class="q-cover513"><span>正解の足場だけが、残る。</span><h1>〇×<br>サバイバル</h1><p>— 最後の足場 —</p><div class="q-cover-marks513"><b>〇</b><b>×</b></div></div><div class="q-body513"><div class="q-facts513"><b>4人対戦</b><b>1問12秒</b><b>間違えたら脱落</b></div><ol><li>床の好きな場所をタップ。相棒がそこまで歩くよ。</li><li>中央の壁が閉まる前に、〇か×へ渡り切ろう。</li><li>正解の台で上へ。不正解の台はマグマへ崩落！</li></ol><p class="q-note513">動物・食べ物・宇宙など12ジャンル、全120問から出題。最大20問。後半ほど難しくなるよ。全員が間違えると勝者なし、20問後に複数残れば同時優勝。締め切り時に立っている台で判定。壁に挟まれたら元の側へ押し戻されるよ。空席はAIが参加するよ。</p><h2>一緒に生き残る、相棒を選ぼう</h2><input name="quizSearch513" value="${esc(u.search)}" placeholder="魔物の名前で探す" aria-label="魔物の名前で探す"><div class="q-roster513">${all.slice(0,u.limit).map(m=>`<button data-q-monster513="${esc(m.id)}" aria-pressed="${m.id===me?.choice?.id}" ${!c.ready()||!me?'disabled':''}>${portrait(c,{speciesId:m.raceSpeciesId??m.speciesId})}<b>${esc(c.sgSpeciesName463(m.raceSpeciesId??m.speciesId))}</b></button>`).join('')||'<p>見つかりませんでした。</p>'}</div>${all.length>u.limit?'<button data-q-action513="more">もっと見る</button>':''}${partySeats462(c)}</div><footer class="q-lobby-actions513"><p role="alert" ${c.error?'':'hidden'}>${esc(c.error)}</p><button class="q-primary513" data-party-action462="ready" aria-pressed="${!!pm?.ready}" ${!c.ready()||!me?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="q-primary513" data-q-action513="start" ${!c.ready()||p.members.some(m=>!m.ready||!m.connected||m.atHome)?'disabled':''}>最後の足場へ！</button><button data-party-action462="lounge">ミニゲーム一覧へ戻る</button>`:'<p>部屋主が開始すると、4人で挑戦！</p>'}</footer></section>`}
function play(c,g){return`<section class="q513 q-play513">${header(c)}<div class="q-seats513">${g.players.map(p=>`<article data-q-card513="${p.seat}" style="--player:${color(p)}"><span>${portrait(c,p)}</span><b>${name(c,p)}</b><small data-q-status513="${p.seat}">待機</small></article>`).join('')}</div><div class="q-question513"><div><strong class="q-round514" data-q-round513></strong><span data-q-category513></span><span class="q-survival514" data-q-timer513></span></div><h1 data-q-question513></h1><p data-q-explain513></p><i class="q-timebar513"><i data-q-bar513></i></i></div><div class="q-stage513" data-q-stage513 tabindex="0" role="group" aria-label="床をタップして歩く。キーボードは左矢印で〇、右矢印で×。"><div class="q-scenery514" data-q-scenery513 aria-hidden="true"></div><div class="q-depth514" aria-hidden="true"></div><div class="q-warning513" data-q-warning513 hidden aria-hidden="true"></div><div class="q-floor513" data-q-floor513="o"><i></i><b>〇</b></div><div class="q-floor513" data-q-floor513="x"><i></i><b>×</b></div><div class="q-bridge513" data-q-bridge513></div><i class="q-destination514" data-q-destination513 hidden aria-hidden="true"></i>${g.players.map(p=>`<div class="q-pawn513" data-q-pawn513="${p.seat}" style="--player:${color(p)}"><div data-q-body513="${p.seat}">${portrait(c,p)}<b>${name(c,p)}</b></div></div>`).join('')}<div class="q-wall513" data-q-wall513><div class="q-wall-clock514"><small data-q-clocklabel513>閉鎖まで</small><strong data-q-wallclock513></strong></div></div>${['o','x'].map(side=>`<div class="q-eruption514" data-q-eruption513="${side}" hidden aria-hidden="true"><span class="q-splash514" data-q-splash513="${side}"></span>${Array.from({length:14},(_,i)=>`<i class="q-ember514" data-q-ember514="${side}-${i}"></i>`).join('')}${Array.from({length:5},(_,i)=>`<i class="q-smoke514" data-q-smoke514="${side}-${i}"></i>`).join('')}</div>`).join('')}<div class="q-countdown513" data-q-countdown513 hidden><small>壁が閉まる前に、渡り切れ。</small><b data-q-count513></b></div><div class="q-lock513" data-q-lock513 hidden>閉鎖</div></div><footer class="q-controls513"><p data-q-instruction513 role="status"></p><p class="q-error513" data-q-error513 role="alert" hidden></p><p class="q-network513" data-q-network513 hidden>再接続中… 受け付け済みの移動で判定されるよ。</p></footer><span class="q-reader513" data-q-reader513 aria-live="polite"></span></section>`}
function result(c,g){const winners=g.players.filter(p=>g.results.find(r=>r.playerId===p.playerId)?.winner),title=g.outcome==='all-out'?'全員、奈落へ。':winners.length>1?'生還者、同時優勝！':`${name(c,winners[0])}、生還！`;return`<section class="q513 q-result513">${header(c)}<div class="q-result-hero513"><small>${g.outcome==='all-out'?'NO SURVIVORS':'LAST SURVIVOR'}</small><h1>${title}</h1><p>${g.round}問目で決着${g.outcome==='all-out'?' · 勝者なし':''}</p><div class="q-survivors513">${(winners.length?winners:g.players).map(p=>`<div style="--player:${color(p)}" ${winners.length?'':'class="q-lost513"'}>${portrait(c,p)}<b>${name(c,p)}</b></div>`).join('')}</div></div>${resultActions490(c)}<div class="q-body513"><h2>最後の足場の記録</h2><div class="q-results513">${g.results.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<article style="--player:${color(p)}">${portrait(c,p)}<div><b>${name(c,p)}</b><small>${r.winner?'生還 · 優勝':`${r.eliminatedRound}問目で脱落`}</small></div><strong>${r.correct}<small>問正解</small></strong></article>`}).join('')}</div><details class="q-history513"><summary>答えと解説を振り返る</summary>${g.history.map(q=>`<article><small>第${q.round}問 · ${esc(q.category)}</small><h3>${esc(q.text)}</h3><strong>正解 ${symbol513(q.answer)}</strong><p>${esc(q.explanation)}</p><div>${q.rows.filter(r=>r.wasAlive).map(r=>`<span style="--player:${color(g.players[r.seat])}">${name(c,g.players[r.seat])} ${symbol513(r.side)} ${r.correct?'✓':'脱落'}</span>`).join('')}</div>${q.source?.url?`<a href="${esc(q.source.url)}" target="_blank" rel="noopener noreferrer">出典：${esc(q.source.label)}</a>`:'<small>出典：計算・文字列を直接検算</small>'}</article>`).join('')}</details></div></section>`}
export function quizView513(c){const g=c.state?.quiz;if(!g)return'';const u=ui(c);if(u.gameId!==g.id){u.gameId=g.id;u.pending=null;u.seq=0;u.round=0;u.lastSend=0;u.search='';u.limit=24;u.cue=null}return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
const put=(e,v)=>e&&property506(e,'textContent',String(v)),hide=(e,v)=>e&&property506(e,'hidden',!!v),attr=(e,k,v)=>{if(e&&e.getAttribute(k)!==String(v))e.setAttribute(k,String(v))},data=(e,k,v)=>{if(e&&e.dataset[k]!==String(v))e.dataset[k]=String(v)};
export function quizBefore513(c){const u=c.qUI513;if(!u)return;if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null;u.cleanup?.();u.cleanup=null;u.nodes=null;stop513(u)}
export function quizDispose513(c){quizBefore513(c);const u=c.qUI513;if(u){u.pending=null;close513(u)}}
export function quizAfter513(c){const root=c.root?.querySelector('.q513');if(!root)return;const u=ui(c);u.reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
 if(!u.warmed&&typeof Image==='function'){u.warmed=true;for(const path of ['quiz513/arena','quiz513/platforms','quiz514/divider','quiz514/question-frame']){const im=new Image();im.src=`./assets/${path}.png`;im.decode?.().catch(()=>{})}}
 if(!root.classList.contains('q-play513'))return;const q=id=>root.querySelector(`[data-q-${id}513]`);u.nodes={root};for(const id of ['sound','stage','wall','warning','bridge','round','category','timer','question','explain','bar','countdown','count','lock','instruction','error','network','reader','wallclock','clocklabel','scenery','destination'])u.nodes[id]=q(id);
 u.nodes.floors=['o','x'].map(side=>root.querySelector(`[data-q-floor513="${side}"]`));u.nodes.effects=['o','x'].map(side=>({root:root.querySelector(`[data-q-eruption513="${side}"]`),splash:root.querySelector(`[data-q-splash513="${side}"]`),embers:Array.from({length:14},(_,i)=>root.querySelector(`[data-q-ember514="${side}-${i}"]`)),smoke:Array.from({length:5},(_,i)=>root.querySelector(`[data-q-smoke514="${side}-${i}"]`))}));u.nodes.players=c.state.quiz.players.map(p=>Object.fromEntries(['pawn','body','card','status'].map(id=>[id,root.querySelector(`[data-q-${id}513="${p.seat}"]`)])));
 const resize=()=>{u.width=u.nodes?.stage?.clientWidth||390;u.height=u.nodes?.stage?.clientHeight||320};resize();const observer=typeof globalThis.ResizeObserver==='function'?new ResizeObserver(()=>{resize();quizTick513(c)}):null;observer?.observe(u.nodes.stage);
 const pointer=e=>{if(e.isPrimary===false||e.button!==0)return;const target=tapPoint514(e.clientX,e.clientY,u.nodes?.stage?.getBoundingClientRect());if(target){e.preventDefault();requestMove514(c,target)}};u.nodes.stage.addEventListener('pointerdown',pointer);
 const unlock=lockPlayZoom498(root),visibility=()=>{if(document.visibilityState==='hidden'){if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null;stop513(u)}else quizTick513(c)};document.addEventListener('visibilitychange',visibility);u.cleanup=()=>{u.nodes?.stage?.removeEventListener('pointerdown',pointer);observer?.disconnect();unlock?.();document.removeEventListener('visibilitychange',visibility)};quizTick513(c);
}
function sendPending(c,at){const u=ui(c),g=c.state?.quiz,p=u.pending;if(!p||!g||g.phase!=='question'||g.round!==p.round||at>=g.deadline){u.pending=null;return}if(at-u.lastSend<160||!c.ready())return;u.lastSend=at;c.raw('quiz513',{gameId:g.id,kind:'move',target:p.target,round:p.round,seq:p.seq})}
export function requestMove514(c,target){const u=ui(c),g=c.state?.quiz,at=clock(c),me=g?.players.find(p=>p.playerId===c.transport.selfId);if(!g||!c.ready()||g.phase!=='question'||!me?.alive||at>=g.deadline||!target||!Number.isFinite(target.x)||!Number.isFinite(target.y)||target.x<0||target.x>100||target.y<54||target.y>91)return false;unlock513(u);if(u.pending&&Math.hypot(u.pending.target.x-target.x,u.pending.target.y-target.y)<.2)return false;u.seq=Math.max(u.seq,me.seq??0)+1;u.pending={target:{x:target.x,y:target.y},round:g.round,seq:u.seq};sendPending(c,at);quizTick513(c);return true}
export function requestQuiz513(c,side){const me=c.state?.quiz?.players.find(p=>p.playerId===c.transport.selfId);return ['o','x'].includes(side)?requestMove514(c,spawn514(me?.seat??0,side)):false}
export function quizReceive513(c){const u=c.qUI513,g=c.state?.quiz;if(!u)return;if(!g||g.id!==u.gameId||g.phase!=='question'||u.round!==g.round){u.pending=null;u.seq=0;u.round=g?.round??0;u.lastSend=0}const me=g?.players.find(p=>p.playerId===c.transport.selfId);if(u.pending&&(me?.seq??0)>=u.pending.seq)u.pending=null;if(me)u.seq=Math.max(u.seq,me.seq??0)}
export function paintQuiz513(c,at=clock(c)){const u=ui(c),n=u.nodes,g=c.state?.quiz;if(!n||!g||globalThis.document?.visibilityState==='hidden')return;sendPending(c,at);const f=frame513(g,at,c.transport.selfId,u.reduced),me=g.players.find(p=>p.playerId===c.transport.selfId),ready=c.ready();
 data(n.root,'phase',g.phase);data(n.stage,'urgent',f.shaking);data(n.root,'reduced',u.reduced);put(n.round,g.round?`第 ${g.round} 問`:'READY');put(n.category,f.category);put(n.timer,g.phase==='reveal'?`生存 ${g.players.filter(p=>p.alive).length}人`:'全20問');put(n.wallclock,g.phase==='question'?f.seconds:g.phase==='countdown'?'12':'0');put(n.clocklabel,g.phase==='lock'||g.phase==='reveal'?'閉鎖':'閉鎖まで');put(n.question,f.heading);put(n.explain,f.explanation);data(n.timer,'warning',f.warning);style506(n.bar,'transform',`scaleX(${(1-f.progress).toFixed(4)})`);style506(n.wall,'transform',`translate3d(-50%,${(f.wallY*(u.height??320)/100).toFixed(2)}px,0)`);style506(n.wall,'opacity',String(1-f.ascent));style506(n.scenery,'transform',`translate3d(0,${(f.ascent*(u.height??320)).toFixed(2)}px,0)`);data(n.stage,'lifting',f.lift>0);data(n.wall,'warning',f.warning);data(n.stage,'interactive',f.canChoose&&ready);hide(n.warning,!f.warning);hide(n.countdown,g.phase!=='countdown');put(n.count,f.count??'');hide(n.lock,g.phase!=='lock');
 for(let i=0;i<2;i++){const side=i?'x':'o',wrong=g.phase==='reveal'&&side!==f.answer;data(n.floors[i],'broken',wrong&&f.fall>0);style506(n.floors[i],'transform',wrong&&!u.reduced?`translateY(${(f.fall*100).toFixed(2)}%) rotate(${(f.fall*(i?7:-7)).toFixed(2)}deg)`:`translateY(${(-18*f.lift).toFixed(2)}px)`);style506(n.floors[i],'opacity',wrong?String(u.reduced ? .15 : 1-f.fall):'1')}
 const dest=u.pending?.target??me?.destination514;hide(n.destination,!dest||!f.canChoose);if(dest)style506(n.destination,'transform',`translate3d(${(dest.x*(u.width??390)/100).toFixed(2)}px,${(dest.y*(u.height??320)/100).toFixed(2)}px,0) translate(-50%,-50%)`);
 for(let i=0;i<2;i++){const fx=f.effects[i],nodes=n.effects[i];hide(nodes.root,!fx.active||u.reduced);if(!fx.active||u.reduced)continue;style506(nodes.splash,'transform',`scale(${(.4+fx.burst*1.7).toFixed(3)},${(1.2-fx.burst*.6).toFixed(3)})`);style506(nodes.splash,'opacity',String(Math.max(0,1-fx.burst)));for(let j=0;j<nodes.embers.length;j++){const t=fx.burst,spread=(j-6.5)*13,v=100+(j*31%80),y=-v*4*t*(1-t)+t*50;style506(nodes.embers[j],'transform',`translate3d(${(spread*t).toFixed(2)}px,${y.toFixed(2)}px,0) rotate(${j*31+t*160}deg) scale(${1-t*.5})`);style506(nodes.embers[j],'opacity',String(1-t))}for(let j=0;j<nodes.smoke.length;j++){const t=fx.smoke;style506(nodes.smoke[j],'transform',`translate3d(${((j-2)*(15+t*13)).toFixed(2)}px,${(-t*(85+j*13)).toFixed(2)}px,0) scale(${(.5+t*1.8).toFixed(3)})`);style506(nodes.smoke[j],'opacity',String(Math.sin(t*Math.PI)*.75))}}
 hide(n.bridge,g.phase==='lock'||g.phase==='reveal'||g.phase==='question'&&f.remaining===0);for(const r of f.rows){const e=n.players[r.seat];hide(e.pawn,r.hidden);style506(e.pawn,'transform',`translate3d(${(r.x*(u.width??390)/100).toFixed(2)}px,${(r.y*(u.height??320)/100-18*r.lift).toFixed(2)}px,0) translate(-50%,-100%)`);style506(e.body,'transform',r.drop>0?`translateY(${(r.drop*220).toFixed(2)}px) rotate(${(r.drop*22).toFixed(2)}deg) scale(${(1-r.drop*.65).toFixed(3)})`:'none');style506(e.body,'opacity',String(1-r.drop));data(e.pawn,'moving',r.moving);data(e.pawn,'bumped',r.bumped);style506(e.pawn,'zIndex',String(5+Math.floor(r.y-63)));data(e.card,'dead',!r.alive);put(e.status,r.status)}
 put(n.instruction,u.pending?'足元の光へ移動中…':f.status||(g.phase==='reveal'?'次の足場を待とう。':g.phase==='lock'?'…':'〇か×。残るのは、どっちだ。'));hide(n.network,ready);hide(n.error,!c.error);put(n.error,c.error??'');put(n.sound,`音 ${u.sound?'ON':'OFF'}`);attr(n.sound,'aria-pressed',u.sound);
 const announce=g.id+':'+g.round+':'+g.phase;if(u.announcement!==announce){u.announcement=announce;put(n.reader,g.phase==='reveal'?`${f.heading}。${f.explanation}。生存${g.players.filter(p=>p.alive).length}人。`:g.phase==='question'?`第${g.round}問。${f.heading}。12秒以内に床をタップして〇か×へ渡り切ってください。`:'')}
 cue513(u,g,f);
}
export function quizTick513(c){const u=c.qUI513,g=c.state?.quiz;if(!u?.nodes||!g||globalThis.document?.visibilityState==='hidden')return;if(u.raf!=null)return;paintQuiz513(c);if(typeof requestAnimationFrame==='function'&&animating513(g,clock(c),u.reduced)){u.raf=requestAnimationFrame(()=>{u.raf=null;quizTick513(c)})}}
export function quizClick513(c,b){const g=c.state?.quiz;if(!g)return false;const d=b.dataset,u=ui(c);unlock513(u);if(d.qSide513){requestQuiz513(c,d.qSide513);return true}if(d.qMonster513){c.raw('quiz513',{gameId:g.id,kind:'select',monsterId:d.qMonster513});return true}if(!d.qAction513)return false;if(d.qAction513==='sound'){u.sound=!u.sound;if(u.sound)unlock513(u);else stop513(u);if(u.nodes)paintQuiz513(c);else c.render()}else if(d.qAction513==='more'){u.limit+=24;c.render()}else if(d.qAction513==='start'){unlock513(u);c.raw('quiz513',{gameId:g.id,kind:'start'})}return true}
export function quizInput513(c,e){if(e.name!=='quizSearch513')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function quizKey513(c,e){if(e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName??'')||e.ctrlKey||e.metaKey||e.altKey)return false;const side={ArrowLeft:'o',o:'o',O:'o','1':'o',ArrowRight:'x',x:'x',X:'x','2':'x'}[e.key];if(!side||!c.root?.querySelector('.q-play513'))return false;e.preventDefault();requestQuiz513(c,side);return true}
export function quizError513(c,m){if(m.op==='quiz513'&&c.qUI513)c.qUI513.pending=null}
