import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{tmpdir}from'node:os';
const{chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const dir=fs.mkdtempSync(path.join(tmpdir(),'race451-ws-')),env={...process.env,HOST:'127.0.0.1',PORT:'18871'};
for(const[name,file]of Object.entries({FRIEND_STATE_FILE:'friends',GUILD_STATE_FILE:'guilds',POWER_RANKING_STATE_FILE:'rankings',SETTLEMENT_STATE_FILE:'settlements',WORLD_RAID_STATE_FILE:'raids',RACE_STATE_FILE:'race'}))env[name]=path.join(dir,file+'.json');
const processes=[];let browser;const errors=[],checks=[];
function launch(file,cwd,env,ready){const proc=spawn(process.execPath,[file],{cwd,env,stdio:['ignore','pipe','pipe']});processes.push(proc);return new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('startup timeout '+out)),15000);proc.stdout.on('data',b=>{out+=b;if(out.includes(ready)){clearTimeout(timer);resolve(proc)}});proc.stderr.on('data',b=>out+=b);proc.on('exit',c=>{if(c){clearTimeout(timer);reject(Error(out))}})})}
try{
 let serverProcess=await launch('server.js',path.resolve('online-server'),env,'Local:');await launch('tools/build453/preview-server.mjs',process.cwd(),process.env,'Preview453 ready');
 const executable=path.resolve('../browser445-133/chromium');fs.chmodSync(executable,0o755);browser=await chromium.launch({executablePath:executable,args:['--no-sandbox','--disable-dev-shm-usage'],env:{...process.env,LD_LIBRARY_PATH:path.dirname(executable),FONTCONFIG_FILE:process.env.RACE_QA_FONTCONFIG||process.env.FONTCONFIG_FILE}});
 const pages=[];for(const name of['えなみ','りおん','より','ひで']){const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true});await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await context.routeWebSocket('**/*',route=>new URL(route.url()).hostname==='127.0.0.1'?route.connectToServer():route.close());const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message)});await page.goto('http://127.0.0.1:18451/?name='+encodeURIComponent(name));await page.waitForFunction(()=>window.qa451?.client.ready(),{},{timeout:20000});pages.push(page)}
 const host=pages[0];await host.bringToFront();await host.screenshot({path:'docs/build453/entry.png'});await host.locator('[data-race-action="create"]').click();await host.waitForFunction(()=>qa451.client.state?.room?.code);const code=await host.evaluate(()=>qa451.client.state.room.code);
 for(const p of pages.slice(1)){await p.locator('[name="roomCode"]').fill(code);await p.locator('[data-race-action="join"]').click();await p.waitForFunction(()=>qa451.client.state.room?.code)}
 for(const p of pages)await p.locator('[data-race-monster]').first().click();await host.locator('[data-race-action="start"]').click();await host.waitForFunction(()=>qa451.client.state.room?.phase==='parade');assert.equal(await host.evaluate(()=>qa451.client.state.room.racers.length),8);checks.push('four real authenticated clients enter one race');
 await host.locator('[data-parade-index="0"]').click();await host.evaluate(()=>{window.actorRef452=document.querySelector('.parade-actor452');qa451.client.refresh()});await host.waitForTimeout(350);assert.equal(await host.evaluate(()=>actorRef452.isConnected),true);checks.push('same-state polling preserves the parade animation DOM');for(const width of[320,393,709]){await host.setViewportSize({width,height:900});assert.equal(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow ${width}`)}await host.setViewportSize({width:393,height:852});await host.screenshot({path:'docs/build453/parade.png',fullPage:true});
 for(let i=0;i<pages.length;i++){const p=pages[i];await p.locator('[data-bet-pick="'+i+'"]').click();await p.locator('[name="betAmount"]').fill('1000');await p.locator('[data-race-action="bet"]').click();await p.waitForFunction(()=>qa451.client.state.room.members.find(m=>m.playerId===qa451.transport.selfId).ready);assert.equal(await p.evaluate(()=>qa451.save.state.player.gold),9000)}checks.push('all four purchases saved exactly once');
 const raceIdBeforeRestart=await host.evaluate(()=>qa451.client.state.room.id);const finishBeforeRestart=JSON.parse(fs.readFileSync(env.RACE_STATE_FILE,'utf8')).rooms[code].outcome;
 await pages[1].evaluate(()=>qa451.transport.ws.close(4000,'QA connection interrupted'));await pages[1].waitForFunction(()=>qa451.client.ready(),{},{timeout:25000});assert.equal(await pages[1].evaluate(()=>qa451.save.state.player.gold),9000);checks.push('real socket interruption reconnects without another debit');
 await new Promise(resolve=>{serverProcess.once('exit',resolve);serverProcess.kill('SIGTERM')});serverProcess=await launch('server.js',path.resolve('online-server'),env,'Local:');
 for(const p of pages)await p.waitForFunction(()=>qa451.client.ready()&&qa451.client.state.room?.members.some(m=>m.playerId===qa451.transport.selfId&&m.ready),{},{timeout:35000});
 assert.equal(await host.evaluate(()=>qa451.client.state.room.id),raceIdBeforeRestart);assert.deepEqual(JSON.parse(fs.readFileSync(env.RACE_STATE_FILE,'utf8')).rooms[code].outcome,finishBeforeRestart);for(const p of pages)assert.equal(await p.evaluate(()=>qa451.save.state.player.gold),9000);checks.push('all four clients recover after full server restart with same race and accepted tickets');
 await pages[2].reload();await pages[2].waitForFunction(()=>window.qa451?.client.state?.room?.members.some(m=>m.playerId===qa451.transport.selfId&&m.ready));assert.equal(await pages[2].evaluate(()=>qa451.save.state.player.gold),9000);checks.push('page reload resumes accepted ticket without debit');
 await host.bringToFront();console.log('four-player bets and reconnect passed; race running');await host.waitForFunction(()=>qa451.client.state.room?.phase==='countdown',{},{timeout:20000});await host.screenshot({path:'docs/build453/countdown.png'});
 await host.waitForFunction(()=>qa451.client.state.room?.phase==='race',{},{timeout:30000});await host.waitForTimeout(140);await host.screenshot({path:'docs/build453/start.png'});await pages[3].evaluate(()=>{qa451.client.unmount();qa451.transport.stopBackground({disconnect:true})});checks.push('one player leaves the screen and disconnects during the race');await host.waitForTimeout(6500);await host.screenshot({path:'docs/build453/race.png',fullPage:true});console.log('sprite geometry',await host.locator('.race-runner451 img').first().evaluate(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,maxWidth:getComputedStyle(e).maxWidth,maxHeight:getComputedStyle(e).maxHeight,natural:[e.naturalWidth,e.naturalHeight]})));for(const size of[{width:320,height:640},{width:393,height:852},{width:709,height:900}]){await host.setViewportSize(size);assert.equal(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await host.locator('.race-tickets451').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight+1),'race and tickets fit '+size.width)}await host.setViewportSize({width:393,height:852});await host.screenshot({path:'docs/build453/race.png',fullPage:true});const progress=await host.locator('[data-race-runner]').evaluateAll(es=>es.map(e=>parseFloat(e.style.left)));assert.ok(progress.some(x=>x>0&&x<100));await host.locator('[data-ticket-focus]').nth(1).click();assert.ok(await host.locator('.is-ticket-pick452').count()>0);checks.push('tap a player ticket highlights its selected runners');await host.waitForFunction(()=>qa451.client.state.room.phase==='race'&&Date.now()+qa451.client.offset-qa451.client.state.room.startAt>=15000);await host.screenshot({path:'docs/build453/spurt.png'});
 await host.waitForFunction(()=>qa451.client.state.room?.phase==='result',{},{timeout:35000});
 await pages[3].evaluate(()=>qa451.transport.startBackground());await pages[3].waitForFunction(()=>qa451.client.ready()&&qa451.client.state.room?.phase==='result'&&!qa451.client.bank().pending,{},{timeout:30000});assert.equal(await pages[3].evaluate(()=>qa451.client.root),null);checks.push('offline finisher receives saved GOLD and training in background after reconnect');await pages[3].evaluate(()=>qa451.client.mount(document.querySelector('#app')));
 for(const p of pages){await p.waitForFunction(()=>qa451.client.state.room?.phase==='result'&&!qa451.client.bank().pending);const row=await p.evaluate(()=>{const r=qa451.client.state.room.results.find(m=>m.playerId===qa451.transport.selfId);return{r,gold:qa451.save.state.player.gold,affection:qa451.save.state.monsters[0].affection}});assert.equal(row.gold,10000+row.r.net);assert.equal(row.affection,row.r.training.affection)}checks.push('all four wallets equal original GOLD plus published net and all gain affection');
 await host.locator('[data-race-action="skip452"]').click();await host.screenshot({path:'docs/build453/result.png',fullPage:true});const moneyBeforeReplay=await host.evaluate(()=>({gold:qa451.save.state.player.gold,affection:qa451.save.state.monsters[0].affection,applied:Object.keys(qa451.client.bank().applied)}));await host.locator('[data-race-action="replay452"]').click();await host.waitForTimeout(200);await host.locator('[data-race-action="skip452"]').click();assert.deepEqual(await host.evaluate(()=>({gold:qa451.save.state.player.gold,affection:qa451.save.state.monsters[0].affection,applied:Object.keys(qa451.client.bank().applied)})),moneyBeforeReplay);await host.evaluate(()=>{window.resultRef452=document.querySelector('.settlement-card452');qa451.client.refresh()});await host.waitForTimeout(300);assert.equal(await host.evaluate(()=>resultRef452.isConnected),true);checks.push('result replay/skip/poll leaves saved money, affection and receipts unchanged');assert.deepEqual(errors,[]);const after=await host.evaluate(()=>qa451.save.state.player.gold);await host.reload();await host.waitForFunction(()=>window.qa451?.client.ready());assert.equal(await host.evaluate(()=>qa451.save.state.player.gold),after);checks.push('settled result reload does not award twice');
 await host.locator('[data-race-action="leave"]').click();await host.waitForFunction(()=>!qa451.client.state.room);await host.locator('[data-race-action="create"]').click();await host.waitForFunction(()=>qa451.client.state.room);await host.locator('[data-race-monster]').first().click();await host.locator('[data-race-action="start"]').click();await host.waitForFunction(()=>qa451.client.state.room.phase==='parade');assert.equal(await host.evaluate(()=>qa451.client.state.room.members.filter(m=>m.ai).length),3);checks.push('solo lobby fills three AI seats automatically');
 fs.writeFileSync('docs/build453/browser-results.json',JSON.stringify({checks,errors,mobileWidths:[320,393,709],transport:'native OnlinePartyController over loopback real server',artAssets:process.env.RACE_QA_ASSETS?'55 original sprite frames from pinned base424':'existing sprite paths; base sprites not provided to QA'},null,2));console.log(JSON.stringify({checks,errors}));
}finally{await browser?.close();for(const p of processes)p.kill();fs.rmSync(dir,{recursive:true,force:true})}
