import{CABBAGE484 as RULES}from'./Rules484.js';
import{partySeats462}from'../party/PartyView462.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#a9e99a','#8bd8ff','#ffca82','#efa9cd'];
const assets='./assets/cabbage484/';
const portrait=(c,id)=>c.sgMonster463?.(id)??'<span>◆</span>';
const ui=c=>c.cbUI484??=( {gameId:null,pending:[],sequence:0,sound:true,particles:[],lastFlush:0} );
const clock=c=>Date.now()+(ui(c).clockOffset??c.offset);
const mine=c=>c.state?.cabbage?.players.find(p=>p.playerId===c.transport.selfId);
export function cabbageSignature484(c){const g=c.state?.cabbage;return g?{id:g.id,phase:g.phase,members:g.members,results:g.results}:null}
const btn=(action,label,disabled=false,cls='')=>`<button class="${cls}" data-cb-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
function header(c){return`<header class="cb-header"><button data-party-action462="browse" aria-label="パーティーへ">‹ パーティー</button><span>ABYSS KITCHEN<small>限界キャベツ千切り</small></span>${btn('sound',ui(c).sound?'音 ON':'音 OFF',false,'cb-sound')}</header>`}
function title(){return`<div class="cb-title"><span>45秒の、台所戦争。</span><h1><em>限界</em>キャベツ<br>千切り</h1><p>刻め。止まれ。まな板は守れ。</p></div>`}
function stage(c,choice,hero=false){return`<div class="cb-stage ${hero?'cb-hero':''}" data-cb-stage><img class="cb-kitchen" src="${assets}kitchen.png" alt="" draggable="false"><div class="cb-stage-shade"></div>${hero?title():''}<div class="cb-chef" data-cb-chef>${choice?portrait(c,choice.speciesId):''}<span class="cb-chef-tag">${hero?'本日の料理人':'あなたの相棒'}</span></div><div class="cb-food" data-cb-food><img src="${assets}cabbage.png" alt="千切りするキャベツ" draggable="false"></div><div class="cb-shreds" aria-hidden="true">${Array.from({length:16},(_,i)=>`<i style="--i:${i};left:${(i%5)*15}%;top:${(i%4)*20}%"></i>`).join('')}</div><div class="cb-knife" aria-hidden="true"><i></i><b></b></div><svg class="cb-crack" viewBox="0 0 300 130" aria-hidden="true"><path d="M0 25 60 38 77 26 109 63 150 58 169 84 193 70 231 95 300 92 M109 63 98 100 70 129 M169 84 174 30 196 0" fill="none" stroke="#26160a" stroke-width="8"/><path d="M0 21 60 34 77 22 109 59 150 54 169 80 193 66 231 91 300 88" fill="none" stroke="#f4c675" stroke-width="3"/></svg><canvas class="cb-particles" aria-hidden="true"></canvas><div class="cb-feedback" data-cb-feedback aria-live="polite"></div>${hero?'':`<div class="cb-signal" data-cb-signal role="status" aria-live="polite"><small data-cb-signal-en></small><strong data-cb-signal-main></strong><span data-cb-signal-note></span></div>`}</div>`}
function rules(){return`<div class="cb-rules"><div><b>01</b><span><strong>左 → 右 → 左 → 右</strong><small>交互に1回切ると10点。10コンボごとに＋5点。</small></span></div><div><b>02</b><span><strong>「切るな！」で、手を止めろ。</strong><small>止まれなければ、まな板粉砕で−80点！ 得点は0より下がりません。</small></span></div></div>`}
function lobby(c,g){const p=c.state.party,me=g.members.find(x=>x.playerId===c.transport.selfId),ready=p?.members.find(x=>x.playerId===c.transport.selfId)?.ready,host=g.hostId===c.transport.selfId,u=ui(c),roster=c.roster().filter(x=>!u.search||c.sgSpeciesName463(x.raceSpeciesId??x.speciesId).includes(u.search));return`<section class="cb-screen cb-lobby">${header(c)}${stage(c,me?.choice,true)}<div class="cb-lobby-body"><div class="cb-facts"><span>4人対戦</span><span>45秒</span><span>参加無料</span></div>${rules()}<div class="cb-section-heading"><span>MY CHEF</span><h2>料理人を選ぼう</h2><p>所持魔物から1匹。能力差なし、腕前で勝負。</p></div><label class="cb-search">魔物を探す<input name="cabbageSearch484" value="${esc(u.search??'')}" placeholder="魔物の名前" autocomplete="off"></label><div class="cb-roster">${roster.slice(0,u.limit??24).map(x=>{const id=x.raceSpeciesId??x.speciesId;return`<button data-cb-monster="${esc(x.id)}" class="${me?.choice?.id===x.id?'is-selected':''}" aria-pressed="${me?.choice?.id===x.id}" ${!c.ready()||!me?'disabled':''}>${portrait(c,id)}<b>${esc(c.sgSpeciesName463(id))}</b>${me?.choice?.id===x.id?'<i>✓</i>':''}</button>`}).join('')||'<p>該当する魔物がいません。</p>'}</div>${roster.length>(u.limit??24)?btn('more','もっと見る'):''}<div class="cb-section-heading"><span>KITCHEN CREW</span><h2>みんなで準備</h2></div>${partySeats462(c)}<p class="cb-note">空いている席にはAIの料理人が参加します。</p></div><footer class="cb-lobby-actions">${c.error?`<p class="cb-error" role="alert">${esc(c.error)}</p>`:''}<button data-party-action462="ready" aria-pressed="${!!ready}" class="cb-primary" ${!me?.choice||!c.ready()?'disabled':''}>${ready?'✓ 準備OK · 取り消す':'この魔物で準備OK'}</button>${host?btn('start','開店！ 4人で千切り開始',!c.ready()||p.members.some(m=>!m.ready||!m.connected||m.atHome),'cb-start'): '<small>全員の準備ができたら、部屋主が開始できます。</small>'}<button data-race-action="back">ホームへ戻る</button></footer></section>`}
function seats(c,g){return`<div class="cb-scoreboard">${g.players.map(p=>`<article class="cb-seat ${p.playerId===c.transport.selfId?'is-self':''}" style="--seat:${colors[p.seat]}" data-cb-seat="${p.seat}"><div class="cb-seat-avatar">${portrait(c,p.choice.speciesId)}</div><small>${p.playerId===c.transport.selfId?'あなた':p.ai?'AI '+esc(p.name):esc(p.name)}</small><b data-cb-score="${p.seat}">${p.score.toLocaleString()}<em>pt</em></b><span data-cb-place="${p.seat}"></span><i data-cb-online="${p.seat}" ${p.connected?'hidden':''}>再接続中</i></article>`).join('')}</div>`}
function play(c,g){const p=mine(c),u=ui(c);return`<section class="cb-screen cb-play">${header(c)}${seats(c,g)}<div class="cb-clockbar"><span>残り <b data-cb-time>45.0</b><small>秒</small></span><div class="cb-time-track"><i data-cb-progress></i></div><span class="cb-combo"><b data-cb-combo>0</b> COMBO</span></div>${stage(c,p?.choice??g.players[0]?.choice)}<div class="cb-action-area"><p class="cb-rhythm" data-cb-hint>左右交互で千切り！</p><div class="cb-pads"><button class="cb-pad cb-left" data-cb-side="left" aria-label="左で切る"><small>LEFT</small><b>左</b><span>A / ←</span></button><div class="cb-alternate" aria-hidden="true">⇄</div><button class="cb-pad cb-right" data-cb-side="right" aria-label="右で切る"><small>RIGHT</small><b>右</b><span>D / →</span></button></div><small class="cb-instruction">${p?'交互に10点 · 切るな！で止まる · 粉砕−80点':'観戦中 · 次の試合から参加できます'}</small></div><div class="cb-offline" data-cb-offline hidden role="status"><strong>再接続しています…</strong><span>対戦は進行中。接続すると戻れます。</span><button data-race-action="refresh">接続を確認</button><button data-race-action="back">ホームへ戻る</button></div></section>`}
function results(c,g){const rows=g.results.map(r=>({...g.players.find(p=>p.playerId===r.playerId),rank:r.rank})),best=rows[0],you=rows.find(p=>p.playerId===c.transport.selfId);return`<section class="cb-screen cb-result">${header(c)}<div class="cb-result-hero"><img src="${assets}kitchen.png" alt=""><span>THE CABBAGE CHAMPION</span><h1>${rows.filter(x=>x.rank===1).length>1?'同点優勝！':'千切り王、誕生。'}</h1><div class="cb-winner">${portrait(c,best.choice.speciesId)}<i>♛</i></div><b>${rows.filter(p=>p.rank===1).map(p=>esc(p.name)).join('・')}</b><strong>${best.score.toLocaleString()}<small>pt</small></strong></div><div class="cb-result-body">${you?`<div class="cb-your-result"><small>あなたの記録</small><b>${you.rank}位</b><span>${you.cuts}回の千切り · 最大${you.maxCombo}コンボ</span><em>${you.breaks?'まな板を'+you.breaks+'枚粉砕。次は守ろう。':'まな板、生還。お見事！'}</em></div>`:''}<div class="cb-ranking">${rows.map(p=>`<article class="${p.playerId===c.transport.selfId?'is-self':''}"><strong>${p.rank}</strong><span class="cb-rank-portrait">${portrait(c,p.choice.speciesId)}</span><span><b>${esc(p.name)}${p.ai?' · AI':''}</b><small>${p.cuts} CUTS · まな板粉砕 ${p.breaks}</small></span><em>${p.score.toLocaleString()}<small>pt</small></em></article>`).join('')}</div><p class="cb-note">参加無料。切った分だけ、みんなの思い出。</p>${g.hostId===c.transport.selfId?btn('again','もう一回！','', 'cb-primary'):'<p class="cb-note">部屋主が次の試合を選べます。</p>'}<button data-party-action462="browse">別のゲームを見る</button><button data-race-action="back">ホームへ戻る</button></div></section>`}
export function cabbageView484(c){const g=c.state.cabbage,u=ui(c);if(u.gameId!==g.id){u.gameId=g.id;u.pending=[];u.sequence=0;u.lastBreak=null;u.particles=[];u.lastSignal=null;u.comboTier=0;u.brokenUntil=0;u.search='';u.limit=24;u.bestRtt=null;u.clockOffset=null;u.clockSent=0}return g.phase==='lobby'?lobby(c,g):g.phase==='result'?results(c,g):play(c,g)}
export function cabbageBefore484(c){const u=c.cbUI484;u?.cleanup?.();if(u)u.cleanup=null}
export function cabbageDispose484(c){cabbageBefore484(c);const u=c.cbUI484;if(u){u.context?.close().catch(()=>{});u.context=null;u.pending=[];u.particles=[]}}
function tone(c,kind){const u=ui(c);if(!u.sound||globalThis.document?.visibilityState==='hidden')return;try{const Audio=globalThis.AudioContext??globalThis.webkitAudioContext;if(!Audio)return;u.context??=new Audio();if(u.context.state!=='running'){u.context.resume().catch(()=>{});return}const ctx=u.context,t=ctx.currentTime,o=ctx.createOscillator(),gain=ctx.createGain();o.type=kind==='cut'?'triangle':'square';o.frequency.setValueAtTime(kind==='cut'?240+Math.random()*130:kind==='break'?100:kind==='stop'?550:820,t);o.frequency.exponentialRampToValueAtTime(kind==='cut'?90:kind==='break'?35:kind==='stop'?280:500,t+.10);gain.gain.setValueAtTime(kind==='cut'?.045:.035,t);gain.gain.exponentialRampToValueAtTime(.001,t+.14);o.connect(gain);gain.connect(ctx.destination);o.start(t);o.stop(t+.15);o.onended=()=>{o.disconnect();gain.disconnect()}}catch{}}
export function cabbageClockReply484(c,m){const u=ui(c);if(m.selfId!==c.transport.selfId||m.clientSent!==u.clockSent||!Number.isFinite(m.serverNow))return;const rtt=Date.now()-m.clientSent;if(rtt<0||rtt>1500)return;if(u.bestRtt==null||rtt<=u.bestRtt+25){u.bestRtt=rtt;u.clockOffset=m.serverNow-(m.clientSent+Date.now())/2}}
function signal(c,g){const at=clock(c);if(at<g.startAt)return{kind:'countdown',until:g.startAt};if(at>=g.endAt)return{kind:'finish'};return g.windows.find(w=>at>=w.at&&at<w.until)??{kind:'waiting'}}
function feedback(c,text,broken=false){const stage=c.root?.querySelector('[data-cb-stage]'),el=c.root?.querySelector('[data-cb-feedback]');if(!stage||!el)return;el.textContent=text;el.classList.toggle('is-bad',broken);el.getAnimations?.().forEach(a=>a.cancel());if(!ui(c).reduced)el.animate?.([{opacity:1,transform:'translate(-50%,0)'},{opacity:0,transform:'translate(-50%,-28px)'}],{duration:broken?1100:450,fill:'forwards'});if(broken){stage.classList.add('is-broken');ui(c).brokenUntil=Date.now()+RULES.repair;tone(c,'break');if(!ui(c).reduced)stage.animate?.([{transform:'translateX(0)'},{transform:'translateX(-6px)'},{transform:'translateX(5px)'},{transform:'translateX(0)'}],{duration:240})}}
function chop(c,side){const u=ui(c),stage=c.root.querySelector('[data-cb-stage]');if(!stage)return;const knife=stage.querySelector('.cb-knife'),food=stage.querySelector('.cb-food'),chef=stage.querySelector('.cb-chef');knife.style.setProperty('--dir',side==='left'?-1:1);if(!u.reduced){chef.getAnimations?.().forEach(a=>a.cancel());chef.animate?.([{transform:'translateY(0)'},{transform:'translateY(-4px)'},{transform:'translateY(0)'}],{duration:150});knife.getAnimations?.().forEach(a=>a.cancel());knife.animate?.([{transform:`translateY(-22px) rotate(${side==='left'?-22:12}deg)`},{transform:'translateY(14px) rotate(-7deg)',offset:.5},{transform:'translateY(0) rotate(-15deg)'}],{duration:135});food.getAnimations?.().forEach(a=>a.cancel());food.animate?.([{transform:'scale(1)'},{transform:'scale(1.03,.94)'},{transform:'scale(1)'}],{duration:160});for(let i=0;i<7;i++)u.particles.push({x:.47,y:.69,vx:(Math.random()-.5)*.009,vy:-.007-Math.random()*.006,life:1,r:Math.random()*6.3,color:['#c9ee86','#8ebc43','#f3ffc5'][i%3]});if(u.particles.length>84)u.particles.splice(0,u.particles.length-84)}tone(c,'cut')}
export function cabbageTap484(c,side){const g=c.state?.cabbage,u=ui(c),p=mine(c);if(!g||!p||!c.ready()||globalThis.document?.visibilityState==='hidden'||!['countdown','playing'].includes(g.phase))return;const s=signal(c,g),now=Date.now();if(['countdown','finish','waiting'].includes(s.kind)||now-(u.lastTap??0)<RULES.minTap)return;u.lastTap=now;if(u.pending.length>=24)return;u.sequence=Math.max(u.sequence,p.lastSeq??0)+1;u.pending.push({seq:u.sequence,side,at:clock(c)});if(s.kind==='stop')feedback(c,'止まって！',false);else if(now<(u.brokenUntil??0))return;else{chop(c,side)}flush(c,true)}
function flush(c,force=false){const u=ui(c),g=c.state?.cabbage,now=Date.now();if(!g||!c.connected()||!u.pending.length||now-u.lastFlush<100)return;u.lastFlush=now;c.raw('cabbageTap484',{gameId:g.id,taps:u.pending.slice(0,8)})}
export function cabbageClick484(c,b,event){if(b.dataset.cbSide){if(event?.detail===0)cabbageTap484(c,b.dataset.cbSide);return true}if(b.dataset.cbMonster){c.raw('cabbage484',{gameId:c.state.cabbage.id,kind:'select',monsterId:b.dataset.cbMonster,roster:[...c.roster().filter(x=>x.id===b.dataset.cbMonster),...c.roster().filter(x=>x.id!==b.dataset.cbMonster)]});return true}const a=b.dataset.cbAction;if(!a)return false;const u=ui(c);if(a==='sound'){u.sound=!u.sound;if(!u.sound)u.context?.suspend().catch(()=>{});else tone(c,'cut');b.textContent=u.sound?'音 ON':'音 OFF';return true}if(a==='more'){u.limit=(u.limit??24)+24;c.render();return true}if(a==='again'){c.raw('partyGame462',{game:'cabbage'});return true}if(a==='start'){tone(c,'start');c.raw('cabbage484',{gameId:c.state.cabbage.id,kind:'start'});return true}return true}
export function cabbageInput484(c,e){if(e.name!=='cabbageSearch484')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function cabbageKey484(c,e){if(!c.root?.querySelector('.cb-play')||e.target.closest('input,textarea,select')||e.ctrlKey||e.metaKey||e.altKey)return false;const key=e.key.toLowerCase(),side=['a','arrowleft'].includes(key)?'left':['d','arrowright'].includes(key)?'right':null;if(!side)return false;e.preventDefault();if(!e.repeat)cabbageTap484(c,side);return true}
export function cabbageReceive484(c){const u=ui(c),p=mine(c);if(!p||u.gameId!==c.state.cabbage?.id)return;u.pending=u.pending.filter(t=>t.seq>p.lastSeq&&t.at>=clock(c)-1500);u.sequence=Math.max(u.sequence,p.lastSeq??0);const tier=Math.floor(p.combo/10);if(tier>(u.comboTier??0))feedback(c,`${tier*10} COMBO! ＋5`);u.comboTier=tier;const food=c.root?.querySelector('[data-cb-food] img');if(food)food.style.transform=`scale(${1-(p.cuts%20)*.008})`;const ev=p.lastEvent;if(ev?.kind==='break'&&u.lastBreak!==ev.at){u.lastBreak=ev.at;if(clock(c)-ev.at<1500)feedback(c,'まな板粉砕！ −80',true)}else if(ev?.kind==='same'&&u.lastSame!==ev.at){u.lastSame=ev.at;feedback(c,'左右交互に！')}cabbageTick484(c)}
export function cabbageAfter484(c){if(!c.root?.querySelector('.cb-screen'))return;const u=ui(c);u.lastSignal=null;u.reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;const down=e=>{const b=e.target.closest('[data-cb-side]');if(!b||b.disabled||e.button>0)return;e.preventDefault();cabbageTap484(c,b.dataset.cbSide)},menu=e=>{if(e.target.closest('[data-cb-side]'))e.preventDefault()};c.root.addEventListener('pointerdown',down,{passive:false});c.root.addEventListener('contextmenu',menu);const root=c.root;u.cleanup=()=>{root.removeEventListener('pointerdown',down);root.removeEventListener('contextmenu',menu)};cabbageTick484(c)}
export function cabbageTick484(c){const root=c.root,g=c.state?.cabbage;if(!root?.querySelector('.cb-play')||!g)return;const u=ui(c),p=mine(c),now=Date.now(),at=clock(c),s=signal(c,g),connected=c.ready(),stage=root.querySelector('[data-cb-stage]');flush(c);if(c.connected()&&now-(u.clockSent??0)>4000){u.clockSent=now;c.raw('cabbageClock484',{clientSent:now})}
 const remaining=Math.max(0,Math.min(45,(g.endAt-at)/1000));root.querySelector('[data-cb-time]').textContent=remaining.toFixed(1);root.querySelector('[data-cb-progress]').style.width=(remaining/45*100)+'%';root.querySelector('[data-cb-combo]').textContent=p?.combo??0;
 const sorted=[...g.players].sort((a,b)=>b.score-a.score);for(const x of g.players){const el=root.querySelector(`[data-cb-score="${x.seat}"]`);if(el&&el.dataset.score!==String(x.score)){el.dataset.score=String(x.score);el.innerHTML=`${x.score.toLocaleString()}<em>pt</em>`;}root.querySelector(`[data-cb-place="${x.seat}"]`).textContent=(sorted.findIndex(y=>y.score===x.score)+1)+'位';root.querySelector(`[data-cb-online="${x.seat}"]`).hidden=x.connected;}
 const count=Math.max(1,Math.min(3,Math.ceil((g.startAt-at)/1000))),label=s.kind==='countdown'?['READY?',String(count),'左右交互にタップするだけ！']:s.kind==='stop'?['HANDS OFF!','切るな！','両手を止めて、まな板を守れ。']:s.kind==='warning'?['CAUTION','そろそろ止まれ…','合図をよく見て！']:s.kind==='finish'?['TIME UP','そこまで！','みんなの千切りを集計中…']:s.kind==='waiting'?['CONNECTING','合図を確認中','少し待ってね']:['CHOP! CHOP!','切れ！','左 → 右 → 左 → 右'];
 const key=s.kind+':'+(s.kind==='countdown'?count:'');if(u.lastSignal!==key){root.querySelector('[data-cb-signal-en]').textContent=label[0];root.querySelector('[data-cb-signal-main]').textContent=label[1];root.querySelector('[data-cb-signal-note]').textContent=label[2];stage.dataset.signal=s.kind;if(u.lastSignal&&s.kind==='stop')tone(c,'stop');else if(u.lastSignal&&s.kind==='cut')tone(c,'start');u.lastSignal=key}
 stage.classList.toggle('is-broken',now<(u.brokenUntil??0));const hint=root.querySelector('[data-cb-hint]');hint.textContent=!p?'観戦中':s.kind==='stop'?'いまは触らない！':now<(u.brokenUntil??0)?'まな板を交換中…':p.lastSide==='left'?'次は 右！ →':p.lastSide==='right'?'← 次は 左！':'左右どちらからでもOK';
 for(const b of root.querySelectorAll('[data-cb-side]')){b.disabled=!connected||!p||['countdown','finish','waiting'].includes(s.kind);b.classList.toggle('is-next',s.kind!=='stop'&&!!p?.lastSide&&b.dataset.cbSide!==p.lastSide);b.classList.toggle('is-stop',s.kind==='stop')}
 root.querySelector('[data-cb-offline]').hidden=connected;
 const canvas=root.querySelector('canvas'),ctx=canvas?.getContext('2d');if(ctx){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(globalThis.devicePixelRatio??1,2);if(w&&h){if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const dt=Math.min(2,(now-(u.lastFrame??now))/33);u.lastFrame=now;for(const x of u.particles){x.x+=x.vx*dt;x.y+=x.vy*dt;x.vy+=.0008*dt;x.life-=.055*dt;ctx.save();ctx.globalAlpha=Math.max(0,x.life);ctx.translate(x.x*w,x.y*h);ctx.rotate(x.r+x.life*4);ctx.fillStyle=x.color;ctx.beginPath();ctx.ellipse(0,0,6,1.7,0,0,Math.PI*2);ctx.fill();ctx.restore()}u.particles=u.particles.filter(x=>x.life>0)}}
}
