// Loopback QA adapter. Real RaceClient + RaceCoordinator + WebSocket; fixture login/save.
// This is not a replacement for online-server/server.js and is never loaded by index.html.
import http from'node:http';import fs from'node:fs';import path from'node:path';import{createRequire}from'node:module';import{RaceCoordinator451}from'../../online-server/src/RaceCoordinator451.js';
const root=process.cwd(),require=createRequire(path.join(root,'online-server/package.json')),{WebSocketServer}=require('ws'),sessions=new Map(),sockets=new Map();
const coordinator=new RaceCoordinator451({sessions,send:(id,m)=>{const ws=sockets.get(id);if(ws?.readyState===1)ws.send(JSON.stringify(m))}});
const index=fs.readFileSync('index.html','utf8'),styles=[...index.matchAll(/<link[^>]+rel="stylesheet"[^>]*>/g)].map(x=>x[0]).filter(s=>{const href=s.match(/href="([^"]+)/)?.[1];return href&&fs.existsSync(href.split('?')[0])}).join('\n'),map=index.match(/<script type="importmap">[\s\S]*?<\/script>/)[0];
const fixture=`import{RaceClient451}from'/src/race/RaceClient451.js';import{botAction463}from'/src/sugoroku/Engine463.js';
const name=new URL(location.href).searchParams.get('name')||'p0';const save={state:{player:{gold:10000},monsters:['slime','ember_slime','wolf','goblin'].map((id,i)=>({id:'owned-'+i,speciesId:id,level:9,affection:500})),settings:{audioEnabled:false}},save:()=>true};
const transport={selfId:name,capabilities:new Set(['monsterRaceV1']),connectionReady:false,_send:(type,m)=>{if(transport.ws?.readyState===1){transport.ws.send(JSON.stringify({type,...m}));return true}return false},_handleMessage:()=>{},startBackground:()=>{if(!transport.ws||transport.ws.readyState>=2)connect()}};
const client=new RaceClient451({transport,save,displayName:()=>name,onBack:()=>{client.unmount();document.querySelector('#app').innerHTML='<button id="remount">パーティーに戻る</button>';document.querySelector('#remount').onclick=()=>client.mount(document.querySelector('#app'))}});
function connect(){const ws=transport.ws=new WebSocket('ws://127.0.0.1:18451/socket');ws.onopen=()=>{transport.connectionReady=true;ws.send(JSON.stringify({type:'fixtureLogin',id:name,key:'fixture-'+name}));client.refresh()};ws.onmessage=e=>transport._handleMessage(JSON.parse(e.data),ws);ws.onclose=()=>{if(transport.ws===ws){transport.connectionReady=false;client.render()}}}
window.qa451={client,save,transport};window.qaBot=()=>{const v=client.state.sugoroku,me=v.players.find(p=>p.playerId===transport.selfId),g={...v,queue:[],turn:v.players.findIndex(p=>p.playerId===v.turnPlayerId),cards:Object.fromEntries(v.hand.map(h=>[h.uid,h.cardId])),players:v.players.map(p=>({...p,hand:p.playerId===transport.selfId?v.hand.map(h=>h.uid):[],mods:v.ownMods,specialUsed:v.ownSpecialUsed})),usedSet:{},pending:v.pending?{...v.pending,data:{count:0}}:null};return botAction463(g,transport.selfId)};
client.mount(document.querySelector('#app'));connect();`;
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name==='/'){res.setHeader('content-type','text/html');return res.end('<!doctype html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'+styles+'<link rel="stylesheet" href="/qa-font.css"><style>body{margin:0;padding:0;background:#100d19}.sg-screen,.sg-screen *,.party-hub462{font-family:"Noto Sans JP",sans-serif!important}#app{max-width:1280px;margin:auto}</style>'+map+'</head><body><main id="app"></main><script type="module" src="/fixture.js"></script></body></html>')}
if(name==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(fixture)}
let file=path.resolve(root,'.'+name);if(name==='/qa-font.css')file=path.resolve(process.env.SG_FONT_DIR??'../qa-deps/node_modules/@fontsource/noto-sans-jp','400.css');if(name.startsWith('/files/'))file=path.resolve(process.env.SG_FONT_DIR??'../qa-deps/node_modules/@fontsource/noto-sans-jp','files',path.basename(name));
if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;return res.end('missing '+name)}res.setHeader('content-type',({'.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2'})[path.extname(file)]??'application/octet-stream');fs.createReadStream(file).pipe(res)});
const wss=new WebSocketServer({server,path:'/socket'});wss.on('connection',ws=>{let session;ws.on('message',bytes=>{const m=JSON.parse(bytes);if(m.type==='fixtureLogin'){if(!/^p[0-9]$/.test(m.id)||m.key!=='fixture-'+m.id)return ws.close();session=sessions.get(m.id)??{playerId:m.id,clientKey:m.key,profile:{displayName:m.id}};session.connected=true;sessions.set(m.id,session);sockets.set(m.id,ws);return}if(session&&m.type==='raceRequest451')coordinator.handle(session,m)});ws.on('close',()=>{if(session&&sockets.get(session.playerId)===ws)session.connected=false})});
const clock=setInterval(()=>coordinator.advance(),250);server.listen(18451,'127.0.0.1',()=>console.log('Isolated preview ready'));process.on('SIGTERM',()=>{clearInterval(clock);wss.close();server.close();process.exit(0)});
