import {MENU581,SUSHI581,fever582,validSushi581,reachable581,point581,wanted581,snatchTarget581} from './Rules581.js';
import {board581,resize581,paint581,diner581} from './Board581.js';
import {esc563 as esc,color563 as color,put563 as put,clock563 as clock,avatar563,header563,lobby563,result563,scoreCards563} from '../party/Arcade563.js';
import {unlock543,sound543} from '../cart/Audio543.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const game=c=>c.state?.sushi,ui=c=>c.sushiUI581??={seq:0,sound:true,seen:0,limit:24,search:''},me=c=>game(c)?.players.find(p=>p.playerId===c.transport.selfId);
const options={prefix:'su',title:'まわせ！魔王の回転寿司',sub:'SUSHI SCRAMBLE',cover:new URL('../../assets/sushi581/cover.webp',import.meta.url).href,hero:'その金皿、<br>いただきます！',rule:'自分の前の皿をタップ。注文３皿をそろえよう！',detail:'４人で回転寿司の取り合い！ 普通の皿は10点、注文ならさらに＋10点。３皿そろえると＋90点！ 金皿は40点で、どの注文にも使えるよ。激辛わさびは−40点＆1.5秒お休み。「のび〜る箸」は離れた注文皿を１枚ゲット、14秒で復活。注文５皿連続で６秒フィーバー、皿の得点が２倍（注文完成の＋90点はそのまま）！ 注文外の皿で連続数リセット、激辛でフィーバーも終了。逆回転は３秒前に予告、最後の15秒は金皿が増える！',players:'４人対戦 · 75秒 · 空席はAI',search:'sushiSearch581'};
const icon=(kind,extra='')=>`<i class="su-food581 ${extra}" style="background-position:${kind%4*100/3}% ${Math.floor(kind/4)*83}%" aria-hidden="true"></i>`;
function play(c,g){const p=me(c);return `<section class="arc563 arc-play563 su-play581 su-polish582">${header563(c,ui(c),'su',options.title,options.sub)}${scoreCards563(c,g)}<div class="arc-mission563"><div><small>４人で取り合い · 注文３皿でボーナス</small><b data-su-mission>自分の前の皿をタップ！</b></div><strong data-su-time></strong></div><div class="su-stage581" data-su-stage tabindex="0" role="group" aria-label="自分の前の皿を選んでEnter、Sキーでのび〜る箸"><canvas data-su-canvas aria-hidden="true"></canvas><canvas data-su-fx aria-hidden="true"></canvas><div class="su-pressure582"><b data-su-rank></b><span data-su-warning hidden></span></div><div class="su-dishes581">${Array.from({length:12},(_,slot)=>`<button class="su-dish581" data-su-slot="${slot}" disabled><i class="su-food581" aria-hidden="true"></i><small></small></button>`).join('')}</div><div class="su-diners581">${g.players.map(q=>`<div class="su-diner581" data-su-diner="${q.seat}" style="--player:${color(q)}">${avatar563(c,q)}<b>${q.playerId===c.transport.selfId?'あなた':esc(q.name)}</b><small data-su-reaction="${q.seat}"></small></div>`).join('')}</div><div class="su-call581" data-su-call role="status" aria-live="polite" hidden></div><div class="arc-count563" data-su-count hidden></div><div class="arc-network563" data-su-network hidden>再接続中 · AIが引き継いでいます</div></div><footer class="su-control581"><div class="su-ticket581"><div><b>あなたの注文</b><small>３皿で ＋90点</small></div><div class="su-order581">${[0,1,2].map(i=>`<div data-su-order="${i}">${icon(p?.order[i]??0)}<span></span><b aria-hidden="true">✓</b></div>`).join('')}</div></div><div class="su-actions581"><p data-su-help>光る皿が、いま取れる皿！</p><button class="arc-gold563" data-su-action="snatch"><b>のび〜る箸</b><small data-su-snatch>遠くの注文皿をゲット</small></button></div><div class="su-combo582" data-su-combobox><b data-su-combo>注文５連続でフィーバー</b><span aria-hidden="true"><i data-su-pip="0"></i><i data-su-pip="1"></i><i data-su-pip="2"></i><i data-su-pip="3"></i><i data-su-pip="4"></i></span><div class="su-feverbar582" data-su-feverbar hidden><i data-su-feverfill></i></div></div></footer></section>`;}
export function sushiView581(c){const g=game(c),u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,limit:24,search:'',notice:null,pending:null,localNext:0,pointerClickAt:-1000});if(g.rules581!==2)return '<section class="arc563">本体とサーバーをBuild582へ更新してください。</section>';return g.phase==='lobby'?lobby563(c,g,u,options):g.phase==='result'?result563(c,g,u,{...options,caption:g.winnerIds.includes(c.transport.selfId)?'ごちそうさま！':'本日の大食い王、決定！',stats:p=>`注文 ${p.sets}組 · 金皿 ${p.golds}枚 · フィーバー ${p.fevers??0}回`}):play(c,g);}
export function sushiReceive581(c){const g=game(c);if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.pending&&(p?.lastSeq>=u.pending.seq||clock(c)-u.pending.at>1200))u.pending=null;}
export function sushiFrame581(c,m){const n=m.sushi,g=game(c);if(m.selfId!==c.transport.selfId||!g||n?.id!==g.id||n.serverAt<g.serverAt)return;c.offset=m.serverNow-Date.now();c.state.sushi={...g,...n};sushiReceive581(c);if((g.phase==='result')!==(n.phase==='result'))c.render();}
function send(c,action,target){const g=game(c),u=ui(c),p=me(c),at=clock(c),m={action,target};if(!c.ready()||u.pending&&at-u.pending.at<300||at<(u.localNext??0)||!g||!validSushi581(g,p,m,at))return false;unlock543(u);const seq=++u.seq,sent=c.raw('sushiInput581',{gameId:g.id,seq,round:1,...m});if(sent!==false){u.pending={seq,at};u.localNext=at+150;}return sent!==false;}
function paint(c){
 const g=game(c),u=ui(c),p=me(c),n=u.nodes,at=clock(c);if(!g?.players.length)return;const wait=g.phase==='countdown',self=p?.seat??0,stunned=p&&at<p.stunUntil;
 paint581(u.renderer,g,c.transport.selfId,u,at);u.root.classList.toggle('is-rush',g.rush);const hot=fever582(p,at),reverseIn=Math.max(0,Math.ceil((g.nextReverse-at)/1000)),warning=!wait&&reverseIn>0&&reverseIn<=3;u.root.classList.toggle('is-fever',hot);n.warning.hidden=!warning;put(n.warning,`逆回転まで ${reverseIn}`);const rank=p?1+g.players.filter(q=>q.score>p.score).length:0,gap=p?Math.max(...g.players.map(q=>q.score))-p.score:0;put(n.rank,!p?'観戦中':rank===1?'１位！ この調子！':`${rank}位 · 首位まで${gap}点`);put(n.combo,hot?`皿の得点２倍！ あと${Math.max(0,(p.feverUntil-at)/1000).toFixed(1)}秒`:`注文 ${p?.combo??0} / ５連続でフィーバー`);n.combobox.classList.toggle('is-hot',hot);n.feverbar.hidden=!hot;n.feverfill.style.transform=`scaleX(${hot?Math.max(0,(p.feverUntil-at)/SUSHI581.feverMs):0})`;for(let i=0;i<5;i++)u.pips[i].classList.toggle('is-lit',hot||i<(p?.combo??0));put(n.time,Math.max(0,Math.ceil(((wait?g.startAt:g.deadline)-at)/1000))+'秒');put(n.mission,wait?'注文を見て、準備！':g.rush?'ラスト15秒！ 金皿ラッシュ！':'自分の前の皿をタップ！');
 for(const q of g.players){const pos=diner581(q.seat,self),el=u.diners[q.seat];el.style.left=Math.max(30,Math.min(u.renderer.w-30,pos.x*u.renderer.w))+'px';el.style.top=Math.max(31,Math.min(u.renderer.h-27,pos.y*u.renderer.h))+'px';el.classList.toggle('is-spicy',at<q.stunUntil);el.classList.toggle('is-eating',at-q.lastEatAt<420);el.classList.toggle('is-fever',fever582(q,at));u.cards[q.seat].classList.toggle('is-scoring',at-q.lastEatAt<350);u.cards[q.seat].classList.toggle('is-leading',q.score===Math.max(...g.players.map(v=>v.score))&&q.score>0);put(u.scores[q.seat],q.score);put(u.status[q.seat],fever582(q,at)?'★ フィーバー！':q.sets+'組 · '+(q.combo??0)+'連続'+(q.auto?' · AI':''));put(u.reactions[q.seat],at<q.stunUntil?'辛っ！':at-q.lastEatAt<700?'もぐもぐ':q.score+'点' );}
 for(let slot=0;slot<12;slot++){const b=u.dishes[slot],d=g.dishes.find(d=>d.slot===slot);b.hidden=!d;if(!d)continue;const pos=point581(g,d,self,at),want=p&&wanted581(p,d.kind)>=0,reach=reachable581(g,p,d,at);b.dataset.suDish=d.id;const born=Math.max(0,Math.min(1,(at-d.bornAt)/220));b.style.transform=`translate(${pos.x*u.renderer.w}px,${pos.y*u.renderer.h}px) translate(-50%,-50%) scale(${u.reduced?1:.7+.3*(1-(1-born)**3)})`;b.firstElementChild.style.backgroundPosition=`${d.kind%4*100/3}% ${Math.floor(d.kind/4)*83}%`;b.classList.toggle('is-reachable',reach);b.classList.toggle('is-wanted',!!want);b.classList.toggle('is-spicy',d.kind===7);b.classList.toggle('is-gold',d.kind===6);put(b.lastElementChild,d.kind===7?'激辛！':d.kind===6?(hot?'金皿×２':'金皿'):want?(hot?'注文×２':'注文'):(hot?'20点':'10点'));b.disabled=!c.ready()||at<(u.localNext??0)||!validSushi581(g,p,{action:'grab',target:d.id},at);b.setAttribute('aria-label',MENU581[d.kind].name+(want?'、注文の皿':'')+(reach?'、タップで取る':'、順番待ち'));}
 for(let i=0;i<3;i++){const el=u.orders[i],kind=p?.order[i]??0,done=p?.filled[i]??false;el.firstElementChild.style.backgroundPosition=`${kind%4*100/3}% ${Math.floor(kind/4)*83}%`;put(el.querySelector('span'),p?MENU581[kind].name:'—');el.classList.toggle('is-filled',done);el.setAttribute('aria-label',(p?MENU581[kind].name:'観戦中')+(done?'、達成':'、未達成'));}
 n.snatchButton.style.setProperty('--charge',`${p?Math.min(100,Math.max(0,1-(p.snatchAt-at)/SUSHI581.snatchMs)*100):0}%`);const remain=p?Math.max(0,Math.ceil((p.snatchAt-at)/1000)):0;n.snatchButton.disabled=!c.ready()||!validSushi581(g,p,{action:'snatch'},at);put(n.snatch,remain?'あと '+remain+'秒':p&&!snatchTarget581(g,p)?'注文皿を待ってね':'遠くの注文皿をゲット');put(n.help,!p?'観戦中 · 次の試合から参加':stunned?'辛〜い！ 少しお休み…':wait?'下の３皿を覚えよう！':hot?'いまがチャンス！ 金皿も２倍！':p?.combo>=3?'あと'+(5-p.combo)+'皿！ 注文を狙おう！':'光る皿をタップ！ 注文をつなごう' );n.count.hidden=!wait;if(wait)put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000)));
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(at-e.at>1400)continue;let message='',priority=1;if(e.type==='set'&&e.seat===p?.seat)message=(g.players[e.seat].playerId===c.transport.selfId?'あなた':g.players[e.seat].name)+'、注文完成！ ＋90';if(e.type==='reverse'){message='せーの！ 逆回転！';priority=3;}if(e.type==='rush'){message='金皿ラッシュ！ 取りまくれ！';priority=4;}if(e.type==='fever'&&e.seat===p?.seat){message='フィーバー！ 皿の得点２倍！';priority=3;}if(e.type==='start')message='いただきまーす！';if(message&&(!u.notice||at>u.notice.until||priority>=(u.notice.priority??0)))u.notice={message,priority,until:at+1200};if(['reverse','rush','start'].includes(e.type)||e.seat===p?.seat)sound543(u,({fever:'boost',set:'park',reverse:'spring',rush:'boost',start:'go',eat:'score',steal:'launch',spicy:'bump'})[e.type]);}
 n.call.hidden=!u.notice||at>u.notice.until;if(!n.call.hidden)put(n.call,u.notice.message);n.network.hidden=c.connected();
}
export function sushiBefore581(c){const u=c.sushiUI581;if(!u)return;u.cleanup?.();u.cleanup=null;cancelAnimationFrame(u.raf);u.raf=null;u.root=null;}
export function sushiDispose581(c){sushiBefore581(c);c.sushiUI581?.audio?.close()?.catch(()=>{});if(c.sushiUI581)c.sushiUI581.audio=null;}
export function sushiAfter581(c){const root=c.root?.querySelector('.su-play581');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;u.nodes=Object.fromEntries(['stage','canvas','fx','rank','warning','combo','combobox','feverbar','feverfill','mission','time','help','snatch','count','call','network'].map(k=>[k,root.querySelector(`[data-su-${k}]`)]));u.nodes.snatchButton=root.querySelector('[data-su-action="snatch"]');for(const [key,selector] of [['cards','[data-arc-card]'],['pips','[data-su-pip]'],['diners','[data-su-diner]'],['scores','[data-arc-score]'],['status','[data-arc-status]'],['reactions','[data-su-reaction]'],['dishes','[data-su-slot]'],['orders','[data-su-order]']])u[key]=[...root.querySelectorAll(selector)];u.renderer=board581(u.nodes.canvas,u.nodes.fx);const abort=new AbortController(),on=(el,type,fn)=>el.addEventListener(type,fn,{signal:abort.signal}),resize=()=>resize581(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const zoom=lockPlayZoom498(root);
 on(u.nodes.stage,'pointerdown',e=>{const b=e.target.closest('[data-su-dish]');if(!b||b.disabled||e.isPrimary===false||e.button>0)return;e.preventDefault();u.pointerClickAt=performance.now();send(c,'grab',Number(b.dataset.suDish));});
 const tick=()=>{if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick);};on(document,'visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{});}else{c.refresh?.();if(u.raf==null)tick();}});u.cleanup=()=>{abort.abort();observer.disconnect();zoom();};sushiReceive581(c);tick();}
export function sushiClick581(c,b){const d=b.dataset,g=game(c);if(!g||!Object.keys(d).some(k=>k.startsWith('su')))return false;const u=ui(c);unlock543(u);if(d.suMonster)c.raw('sushi581',{gameId:g.id,kind:'select',monsterId:d.suMonster});if(d.suAction==='start')c.raw('sushi581',{gameId:g.id,kind:'start'});if(d.suAction==='more'){u.limit+=24;c.render();}if(d.suAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock543(u);}if(d.suAction==='snatch')send(c,'snatch');if(d.suDish&&performance.now()-(u.pointerClickAt??-1000)>400)send(c,'grab',Number(d.suDish));return true;}
export function sushiInput581(c,e){if(e.name!=='sushiSearch581')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true;}
export function sushiKey581(c,e){if(!c.root?.querySelector('.su-play581')||/INPUT|TEXTAREA/.test(e.target?.tagName))return false;if(e.key.toLowerCase()==='s'){e.preventDefault();if(!e.repeat)send(c,'snatch');return true;}return false;}
