import{ATLAS504,HAIRS504,layout504,kingPose504,count504,toolColor504,blast504}from'./Presentation504.js';
const clamp=v=>Math.max(0,Math.min(1,v));
function cover(c,image,w,h){if(!image)return;const s=Math.max(w/image.width,h/image.height);c.drawImage(image,(w-image.width*s)/2,(h-image.height*s)*.57,image.width*s,image.height*s)}
function strand(c,h,stretch=0){const len=h.length*(1+stretch*.3),bend=h.bend*7;c.save();c.rotate(h.tilt);c.beginPath();c.moveTo(h.bump?-.6:-.38,0);c.bezierCurveTo(-2,-len*.35,bend+2,-len*.65,bend,-len);c.bezierCurveTo(bend+1,-len*.66,.35,-len*.28,h.bump?.6:.38,0);c.closePath();const ink=c.createLinearGradient(-2,0,3,0);ink.addColorStop(0,'#28180e');ink.addColorStop(.5,'#432716');ink.addColorStop(1,'#72513b');c.fillStyle=ink;c.shadowColor='#35160b55';c.shadowBlur=.65;c.shadowOffsetX=.65;c.fill();c.restore()}
function pore(c,h,pulled,tug){const radius=h.bump?2.8:1.05;c.save();if(tug>0){const rise=tug*(h.bump?7:5);c.beginPath();c.moveTo(-6,1);c.bezierCurveTo(-2,0,-2,-rise,0,-rise);c.bezierCurveTo(2,-rise,3,0,6,1);c.closePath();const skin=c.createLinearGradient(-5,0,5,0);skin.addColorStop(0,'#a86140aa');skin.addColorStop(.45,h.bump?'#ce8a70':'#d79c74');skin.addColorStop(1,'#985d3c66');c.fillStyle=skin;c.fill();c.translate(0,-rise)}const grad=c.createRadialGradient(-radius*.3,-radius*.4,.1,0,0,radius*1.7);grad.addColorStop(0,h.bump?'#d99a86':'#be8861');grad.addColorStop(.48,h.bump?'#ba7563':'#a96f4d');grad.addColorStop(1,'#8c4d3200');c.fillStyle=grad;c.beginPath();c.ellipse(0,0,radius*1.7,radius,0,0,Math.PI*2);c.fill();c.fillStyle=pulled?'#59312370':'#392211';c.beginPath();c.ellipse(0,-.35,h.bump?.6:.45,.35,0,0,Math.PI*2);c.fill();c.restore()}
function tweezers(c,closed,color){c.save();c.rotate(-.25);const metal=c.createLinearGradient(-10,0,10,0);metal.addColorStop(0,color.tint);metal.addColorStop(.30,color.hex);metal.addColorStop(.52,'#fff9e8');metal.addColorStop(.72,color.hex);metal.addColorStop(1,color.tint);c.strokeStyle=metal;c.lineWidth=2;c.shadowColor=color.hex;c.shadowBlur=1.2;c.lineCap='round';const gap=4*(1-closed)+.5;for(const side of[-1,1]){c.beginPath();c.moveTo(side*gap,0);c.lineTo(side*3.6,-24);c.quadraticCurveTo(side*4,-34,0,-37);c.stroke()}c.restore()}
function drawHair(c,h,g,at,u){const last=g.events.at(-1),selected=!u.reduced&&g.phase==='pluck'&&last?.hair===h.id,age=selected?Math.max(0,at-g.phaseAt503):0,removed=g.picked.includes(h.id),pending=u.pending?.kind==='pull'&&u.pending.hair===h.id&&!removed;
 const tug=selected&&age<530?Math.sin(clamp(age/530)*Math.PI/2):0,recoil=selected&&age>=530?Math.exp(-(age-530)/90)*Math.sin((age-530)/24):0;pore(c,h,removed&&!selected,Math.max(0,tug+recoil*.3));
 if(removed&&!selected)return;
 c.save();if(selected){if(age<530)c.translate(0,-tug*(h.bump?7:5));else{const fly=(age-530)/320;c.globalAlpha=1-clamp(fly);c.translate(fly*15,-10-fly*80);c.rotate(fly*.9)}}strand(c,h,tug);
 if(selected||pending){c.save();const arrive=selected?clamp(age/160):.5;const len=h.length*(1+tug*.3),bend=h.bend*7;c.translate(bend*Math.cos(h.tilt)+len*Math.sin(h.tilt),bend*Math.sin(h.tilt)-len*Math.cos(h.tilt)-(1-arrive)*14);c.globalAlpha*=arrive;if(h.y<56)c.rotate(h.x>50?-1.35:1.65);tweezers(c,selected?clamp((age-80)/140):.5,toolColor504(g));c.restore()}c.restore();
}
function tile(c,image,frame,l,asset){if(!image)return;const cell=image.width/2,[x,y,w,h]=ATLAS504[asset]?.[frame]??[0,0,cell,cell];c.drawImage(image,(frame%2)*cell+x,Math.floor(frame/2)*cell+y,w,h,l.x,l.y,l.size,l.size)}
function aura(c,w,h,age){const strength=clamp((age-600)/500)*clamp((4000-age)/1600);if(!strength)return;c.save();const glow=c.createRadialGradient(w*.5,h*.51,w*.05,w*.5,h*.55,h*.7);glow.addColorStop(0,'#ffc66300');glow.addColorStop(.5,'#f7802540');glow.addColorStop(1,'#710e12ed');c.globalAlpha=strength;c.fillStyle=glow;c.fillRect(0,0,w,h);c.restore()}
function shockwave(c,w,h,age){for(const origin of[1300,1600,1940]){const t=age-origin;if(t<0||t>1050)continue;const p=t/1050,r=24+p*w*1.15;c.save();c.globalAlpha=(1-p)*.9;c.strokeStyle=origin===1300?'#fff2bf':'#ffc66a';c.lineWidth=(1-p)*9+1;c.shadowColor='#ff9f47';c.shadowBlur=15;c.beginPath();c.ellipse(w/2,h*.7,r,r*.40,0,0,Math.PI*2);c.stroke();c.restore()}
 const t=(age-1300)/1500;if(t<0||t>1)return;c.save();for(let i=0;i<24;i++){const angle=i*2.39996,d=(30+t*w*.75)*(0.5+(i%5)/7),x=w*.5+Math.cos(angle)*d,y=h*.72+Math.sin(angle)*d*.62-t*h*.15; c.save();c.translate(x,y);c.rotate(angle+t*3);c.globalAlpha=(1-t)*.7;c.fillStyle=i%3===0?'#f7d481':i%3===1?'#7f994b':'#a87649';c.beginPath();c.moveTo(-3,-1);c.quadraticCurveTo(0,-6,6,-2);c.lineTo(2,3);c.closePath();c.fill();c.restore()}c.restore();
}
function pluckPop(c,l,g,at,u){const last=g.events.at(-1),hair=HAIRS504[last?.hair];if(!hair||u.reduced||g.phase!=='pluck')return;const age=at-g.phaseAt503;if(age<530)return;const t=clamp((age-530)/320),root=l.point(hair.x,hair.y);c.save();c.globalAlpha=1-t*.5;c.textAlign='center';c.font=`900 ${hair.bump?20:16}px system-ui`;c.lineWidth=4;c.strokeStyle='#351b15';const text=hair.bump?'痛さ ×2！':'ぷちっ！',x=Math.max(55,Math.min(l.w-55,root.x)),y=root.y-33-t*27;c.strokeText(text,x,y);c.fillStyle=hair.bump?'#ffbb9e':'#ffecb3';c.fillText(text,x,y);c.restore()}
export function draw504(canvas,g,assets,at,u={}){
 const w=canvas.clientWidth||canvas.width,h=canvas.clientHeight||canvas.height,c=canvas.getContext('2d'),ratio=canvas.width/w,l=layout504(w,h,g,at,u.reduced),blast=blast504(g,at,u.reduced);
 c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,w,h);c.save();if(blast?.shake)c.translate(Math.sin(blast.age*.071)*blast.shake,Math.cos(blast.age*.063)*blast.shake*.55);
 cover(c,assets.background,w,h);const shade=c.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#071d1780');shade.addColorStop(.25,'#071d1700');shade.addColorStop(1,'#071d1770');c.fillStyle=shade;c.fillRect(0,0,w,h);
 if(blast)aura(c,w,h,blast.age);
 const pose=kingPose504(g,at);c.save();c.translate(l.cx,l.cy+l.dy);c.scale(l.scale,l.scale);c.translate(-l.cx,-l.cy);
 if(blast?.scale!==undefined){c.translate(l.cx,l.y+l.size*.8);c.scale(blast.scale,blast.scale);c.translate(-l.cx,-l.y-l.size*.8)}
 c.save();c.shadowColor='#06150ba0';c.shadowBlur=12;c.shadowOffsetY=6;
 // High resolution, stable chest while selecting; accumulated expression on the full view.
 // Crossfade on the camera move, never teleport the skin beneath a tapping finger.
 const zoomBody=!['drum','blast'].includes(g.phase)?l.focus:0;
 if(zoomBody<1){c.globalAlpha=1-zoomBody;tile(c,assets[pose.asset],pose.frame,l,pose.asset)}
 if(zoomBody>0){c.globalAlpha=zoomBody;c.drawImage(assets.hero,l.x,l.y,l.size,l.size)}c.restore();
 for(const hair of HAIRS504){if(pose.asset==='rage'&&pose.frame>=2&&hair.y<66)continue;c.save();c.translate(l.x+l.size*hair.x/100,l.y+l.size*hair.y/100);c.scale(l.size/370,l.size/370);drawHair(c,hair,g,at,u);c.restore()}
 c.restore();
 if(blast&&!blast.judging&&!u.reduced)shockwave(c,w,h,blast.age);
 if(blast&&!blast.judging&&blast.age>=1300&&blast.age<2550){c.save();c.textAlign='center';c.font=`900 ${Math.min(34,w*.081)}px system-ui`;c.lineWidth=6;c.strokeStyle='#481609';c.shadowColor='#130a08';c.shadowBlur=10;const text='王、大激怒！！';c.strokeText(text,w/2,h*.85);c.fillStyle='#fff0b1';c.fillText(text,w/2,h*.85);c.restore()}
 c.restore();pluckPop(c,l,g,at,u);
 if(g.phase==='reaction'&&g.events.at(-1)?.mercy504){c.save();c.font='900 '+Math.min(35,w*.1)+'px system-ui';c.textAlign='center';c.lineWidth=5;c.strokeStyle='#193c29';c.strokeText('セーーーフ！！',w/2,h*.84);c.fillStyle='#c3ffb6';c.fillText('セーーーフ！！',w/2,h*.84);c.restore()}
 if(g.phase==='countdown')drawCountdown504(c,w,h,g,assets,at);
 return l;
}
export function drawCountdown504(c,w,h,g,assets,at){c.save();const shade=c.createRadialGradient(w/2,h*.48,0,w/2,h*.48,h*.7);shade.addColorStop(0,'#061e16ed');shade.addColorStop(1,'#061e1650');c.fillStyle=shade;c.fillRect(0,0,w,h);const sz=Math.min(w*.85,h*.68,360),x=(w-sz)/2,y=h*.43-sz*.5;if(assets.countdown)c.drawImage(assets.countdown,x,y,sz,sz);const write=(s,yy,size,color='#ffebb0',bold=false)=>{c.font=`${bold?'900 ':''}${size}px system-ui`;c.fillStyle=color;c.textAlign='center';c.fillText(s,w/2,yy)};write('王の胸毛に、挑め。',y+sz*.43,sz*.049,'#ddcf91',true);const number=count504(g,at);c.shadowColor='#9c7437';c.shadowOffsetY=3;write(number,y+sz*.66,number.length>1?sz*.17:sz*.29,'#fff1bc',true);c.shadowOffsetY=0;write('ドラミングしても、50％でセーフ。',y+sz+23,13,'#e5dfb9');write('油断したら、全員ぶっ飛ぶ。',y+sz+45,11,'#c8d9bd');c.restore()}
