import * as previous from './View503.js';
import * as legacy from './View502.js';
import{lockPlayZoom498}from'../cabbage/Zoom498.js';
import{playerColor499}from'../party/PartyColors499.js';
import{HAIRS505 as HAIRS503,SPOTS505,hit505,flight505 as flight503,hairTargets505 as hairTargets503,warning505 as warning503,count505 as count503,toolTag505}from'./Presentation505.js';
import{blastAudio504}from'./Audio504.js';
import{draw506 as draw503,release506}from'./Scene506.js';
import{property506,style506}from'./Performance506.js';
const modern=c=>c.state?.gorilla?.rules505===1,game=c=>c.state.gorilla,ui=legacy.gorillaUI502,clock=c=>Date.now()+(c.offset??0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art={hero:'gorilla503/king-closeup.png',patience:'gorilla504/patience.png',tension:'gorilla504/tension.png',rage:'gorilla504/rage.png',countdown:'gorilla503/countdown.png',original:'gorilla502/king-atlas.png',background:'gorilla502/court.png'};
const signature=g=>`${g.id}:${g.phase}:${g.turn}:${g.events.length}`;
export function prepareArt505(c){const u=ui(c);if(u.artReady503||u.artLoading503||u.artFailed||typeof Image==='undefined')return;u.artLoading503=true;Promise.all(Object.entries(art).map(([key,file])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=async()=>{try{await im.decode?.();resolve([key,im])}catch(e){reject(e)}};im.onerror=reject;im.src='./assets/'+file}))).then(rows=>{u.assets503=Object.fromEntries(rows);u.artReady503=true;u.artLoading503=false;if(modern(c)&&c.root)c.render()},()=>{u.artLoading503=false;u.artFailed=true;if(modern(c)&&c.root)c.render()})}
function play(c,g){return`<section class="gg502 gg503 gg504 gg505 gg-play503" style="--turn-color:${playerColor499(g.players[g.turnSeat]).hex}">${legacy.gorillaHeader502(c)}${legacy.gorillaPlayers502(c,g)}<div class="gg-stage503" data-gg-stage503><canvas data-gg-canvas503 aria-hidden="true"></canvas><div class="gg-targets503">${HAIRS503.map(h=>`<button data-gg-hair503="${h.id}" aria-label="毛を抜く ${h.id+1}" disabled></button>`).join('')}${SPOTS505.map(p=>`<button data-gg-spot505="${p.id}" aria-label="乳首をつまむ ${p.id+1}" disabled></button>`).join('')}</div><div class="gg-tool-tags504" aria-hidden="true">${g.players.map(p=>`<div class="gg-tool-tag504" data-gg-tool504="${p.seat}" hidden style="--player:${playerColor499(p).hex}">${c.sgMonster463?.(p.choice.speciesId)??''}<b>${p.playerId===c.transport.selfId?'あなた':esc(p.name)}</b></div>`).join('')}</div><div class="gg-pawns503">${g.players.map(p=>`<div class="gg-pawn502 gg-pawn503" data-gg-pawn503="${p.seat}" style="left:${12+p.seat*25.333}%;--player:${playerColor499(p).hex}"><i></i>${c.sgMonster463?.(p.choice.speciesId)??''}<b>${p.playerId===c.transport.selfId?'あなた':esc(p.name)}</b></div>`).join('')}</div><div class="gg-warning503" data-gg-warning503 hidden role="timer"><small>あと</small><strong data-gg-seconds503></strong><small>秒</small></div><div class="gg-art-status503" data-gg-art-status503 ${ui(c).artReady503?'hidden':''}>${ui(c).artFailed?'画像を読み込めませんでした。':'王の宮殿を準備中…'}${ui(c).artFailed?'<button data-gg-action="reloadArt">再読み込み</button>':''}</div><span class="gg-reader503" data-gg-count503 aria-live="polite"></span></div><footer class="gg-controls503"><div class="gg-turn-note503"><span data-gg-pulls503></span></div><p class="gg-pinch-warning528" data-gg-pinch-warning528 role="status"></p><div class="gg-decisions503" data-gg-decisions503 hidden><button data-gg-decision503="continue" class="gg-primary502">もう1本、抜く！</button><button data-gg-decision503="pass">次の人へ渡す →</button></div><p data-gg-error503 role="alert" ${c.error?'':'hidden'}>${esc(c.error)}</p></footer><div class="gg-offline502" data-gg-offline503 hidden role="status">再接続中… 時間切れはおまかせで進むよ。<button data-race-action="refresh">接続を確認</button></div></section>`}
export function gorillaView505(c){if(!modern(c))return previous.gorillaView503(c);const g=game(c),u=ui(c);if(u.gameId!==g.id){u.gameId=g.id;u.pending=null;u.limit=24;u.search='';u.seenEvent=null;u.soundBeat=null}if(g.phase==='lobby')return legacy.gorillaLobby502(c,g).replace('class="gg502 ', 'class="gg502 gg503 gg504 gg505 ');if(g.phase==='result')return legacy.gorillaResult502(c,g).replace('class="gg502 ', 'class="gg502 gg503 gg504 gg505 ');return play(c,g)}
export function requestGorilla505(c,kind,hair){if(!modern(c))return false;const g=game(c),u=ui(c),at=clock(c);if(!c.ready()||!u.artReady503||u.pending||g.players[g.turnSeat]?.playerId!==c.transport.selfId||g.deadline==null||at>=g.deadline)return false;
 if(kind==='pull'&&(g.phase!=='playing'||!Number.isInteger(hair)||hair<0||hair>=30||g.picked.includes(hair)))return false;if(kind==='pinch'&&(g.phase!=='playing'||![0,1].includes(hair)))return false;if(!['pull','pinch'].includes(kind)&&(!['continue','pass'].includes(kind)||g.phase!=='decision'))return false;
 legacy.gorillaAudio502(c,'click');u.pending={kind,hair,gameId:g.id,signature:signature(g),at:Date.now()};const payload={gameId:g.id,kind,turn:g.turn,...(kind==='pull'?{hair}:kind==='pinch'?{spot:hair,seq:g.events.length}:{seq:g.events.length})};const sent=c.raw('gorilla502',payload);if(sent===false){u.pending=null;c.error='送信できなかったよ。接続を確認してね。'}gorillaTick505(c);return sent!==false;
}
export function gorillaBefore505(c){const scene=c.ggUI502?.scene503;if(scene){if(scene.raf506!=null)globalThis.cancelAnimationFrame?.(scene.raf506);release506(scene.canvas)}previous.gorillaBefore503(c);const u=c.ggUI502;u?.cleanup503?.();if(u){u.cleanup503=null;u.scene503=null}}
export function gorillaDispose505(c){gorillaBefore505(c);previous.gorillaDispose503(c)}
export function gorillaAfter505(c){if(!modern(c))return previous.gorillaAfter503(c);prepareArt505(c);const root=c.root?.querySelector('.gg-play503');if(!root)return;const u=ui(c);u.reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;const stage=root.querySelector('[data-gg-stage503]'),canvas=root.querySelector('canvas');u.scene503={root,stage,canvas,targets:[...root.querySelectorAll('[data-gg-hair503]')],spots:[...root.querySelectorAll('[data-gg-spot505]')],pawns:[...root.querySelectorAll('[data-gg-pawn503]')],toolTags:[...root.querySelectorAll('[data-gg-tool504]')]};
 const mounted=u.scene503,lost=()=>{mounted.lost506=true;if(mounted.raf506!=null)globalThis.cancelAnimationFrame?.(mounted.raf506);mounted.raf506=null;release506(canvas)},restored=()=>{mounted.lost506=false;release506(canvas);gorillaTick505(c)};canvas.addEventListener?.('contextlost',lost);canvas.addEventListener?.('contextrestored',restored);
 const unlock=lockPlayZoom498(root),pick=(x,y)=>{if(!u.scene503?.layout)return;const rect=stage.getBoundingClientRect(),hit=hit505(u.scene503.layout,game(c),(x-rect.left)*stage.clientWidth/rect.width,(y-rect.top)*stage.clientHeight/rect.height);if(hit)requestGorilla505(c,hit.kind,hit.hair??hit.spot)},down=e=>{if(!stage.contains(e.target)||e.target.closest?.('[data-gg-action]')||e.button>0)return;e.preventDefault();u.pointerUntil505=Date.now()+700;pick(e.clientX,e.clientY)},touch=e=>{const t=e.changedTouches?.[0];if(!t||!stage.contains(t.target)||t.target.closest?.('[data-gg-action]'))return;e.preventDefault();u.pointerUntil505=Date.now()+700;pick(t.clientX,t.clientY)};if(globalThis.PointerEvent)root.addEventListener('pointerdown',down,{passive:false});else{root.addEventListener('touchstart',touch,{passive:false});root.addEventListener('mousedown',down,{passive:false})}u.cleanup503=()=>{canvas.removeEventListener?.('contextlost',lost);canvas.removeEventListener?.('contextrestored',restored);unlock();root.removeEventListener('pointerdown',down);root.removeEventListener('touchstart',touch);root.removeEventListener('mousedown',down)};gorillaTick505(c)
}
export function gorillaReceive505(c){if(!modern(c))return previous.gorillaReceive503(c);const u=c.ggUI502;if(u?.pending&&u.pending.signature!==signature(game(c)))u.pending=null}
export function gorillaError505(c,m){previous.gorillaError503(c,m)}
export function gorillaClick505(c,b,event){if(!modern(c))return previous.gorillaClick503(c,b);if(b.dataset.ggSpot505!==undefined){if(!event?.detail&&Date.now()>=(ui(c).pointerUntil505??0))requestGorilla505(c,'pinch',Number(b.dataset.ggSpot505));return true}if(b.dataset.ggHair503!==undefined){if(event?.detail||Date.now()<(ui(c).pointerUntil505??0))return true;requestGorilla505(c,'pull',Number(b.dataset.ggHair503));return true}if(b.dataset.ggDecision503){requestGorilla505(c,b.dataset.ggDecision503);return true}if(b.dataset.ggAction==='reloadArt'){ui(c).artFailed=false;prepareArt505(c);c.render();return true}return previous.gorillaClick503(c,b)}
export function gorillaInput505(c,e){return previous.gorillaInput503(c,e)}
export function gorillaKey505(c,e){if(!modern(c))return previous.gorillaKey503(c,e);if(e.target?.closest?.('input,select,textarea,[contenteditable="true"]'))return false;if(e.code==='Escape'&&game(c).phase==='decision'){e.preventDefault();if(!e.repeat)requestGorilla505(c,'pass');return true}return false}
export function gorillaTick505(c){if(!modern(c))return previous.gorillaTick503(c);const scene=c.ggUI502?.scene503;if(!scene)return;if(globalThis.document?.visibilityState==='hidden'){if(!scene.suspended506){if(scene.raf506!=null)globalThis.cancelAnimationFrame?.(scene.raf506);scene.raf506=null;release506(scene.canvas);scene.suspended506=true}return}scene.suspended506=false;if(scene.lost506)return;
 if(typeof globalThis.requestAnimationFrame!=='function')return paintGorilla506(c);
 if(scene.raf506!=null)return;scene.raf506=globalThis.requestAnimationFrame(()=>{scene.raf506=null;if(c.ggUI502?.scene503===scene&&globalThis.document?.visibilityState!=='hidden')paintGorilla506(c)});
}
function paintGorilla506(c){const u=ui(c),scene=u.scene503;if(!scene)return;const{root,stage,canvas,targets,spots,pawns,toolTags}=scene,g=game(c),at=clock(c),w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;const dpr=Math.min(2,globalThis.devicePixelRatio??1),px=Math.round(w*dpr),py=Math.round(h*dpr);if(canvas.width!==px||canvas.height!==py){canvas.width=px;canvas.height=py}const l=u.assets503?draw503(canvas,g,u.assets503,at,u):null;
 const mine=g.players[g.turnSeat]?.playerId===c.transport.selfId,can=mine&&c.ready()&&u.artReady503&&!u.pending&&g.phase==='playing'&&at<g.deadline,put=(q,t)=>{const el=root.querySelector(q);if(el&&el.textContent!==String(t))el.textContent=t};property506(root.dataset,'phase',g.phase);const color=playerColor499(g.players[g.turnSeat]).hex;if(scene.color506!==color){root.style.setProperty('--turn-color',color);scene.color506=color;}
 scene.layout=l;put('[data-gg-count503]',g.phase==='countdown'?count503(g,at):'');
 const positionKey=l?[l.w,l.h,l.size,l.scale,l.dy].join('|'):null;if(scene.positionKey506!==positionKey){scene.points506=l?hairTargets503(l):[];scene.positionKey506=positionKey}const points=scene.points506??[];targets.forEach((b,i)=>{property506(b,'disabled',!can);property506(b,'hidden',g.picked.includes(i)||!['focus','playing'].includes(g.phase));const p=points[i];if(p){style506(b,'left',p.x+'px');style506(b,'top',p.y+'px')}});
 for(const b of spots){property506(b,'disabled',!can);property506(b,'hidden',!['focus','playing'].includes(g.phase));const s=SPOTS505[Number(b.dataset.ggSpot505)],p=l?.point(s.x,s.y);if(p){style506(b,'left',p.x+'px');style506(b,'top',p.y+'px')}}
 const tag=l?toolTag505(g,l,at,u.pending):null;for(const el of toolTags){property506(el,'hidden',!tag||Number(el.dataset.ggTool504)!==tag.player?.seat);if(!el.hidden){style506(el,'left',tag.x+'px');style506(el,'top',tag.y+'px')}}
 const decision=root.querySelector('[data-gg-decisions503]');property506(decision,'hidden',g.phase!=='decision'||!mine);for(const b of decision.querySelectorAll('button'))property506(b,'disabled',!c.ready()||!!u.pending||at>=g.deadline);
 put('[data-gg-pulls503]',`この番 ${g.turnPulls503}/3回`);
 const pinched=g.events.at(-1)?.action505==='pinch';put('[data-gg-pinch-warning528]',g.phase==='blast'&&pinched?'そこはダメ！ 大王、激怒！！':g.phase==='reaction'&&pinched?'こらえた……！ もうつまむと危険。':'');
 const warn=warning503(g,at),warning=root.querySelector('[data-gg-warning503]');property506(warning,'hidden',warn===null);put('[data-gg-seconds503]',warn??'');
 for(const p of g.players){const card=root.querySelector(`[data-gg-seat="${p.seat}"]`);const active=g.turnSeat===p.seat&&g.phase!=='blast';if(card&&card.classList.contains('is-turn')!==active)card.classList.toggle('is-turn',active);put(`[data-gg-order="${p.seat}"]`,g.phase==='blast'?(p.playerId===g.loserId?'犯人！':'巻き添え'):g.turnSeat===p.seat?'いまの番':'待機中');const el=pawns[p.seat],f=flight503(g,p,at,w,h,u.reduced);style506(el,'opacity',String(g.phase==='countdown'?0:1-(l?.focus??0)));style506(el,'transform',`translate(calc(-50% + ${f.x.toFixed(1)}px),calc(-100% + ${f.y.toFixed(1)}px)) rotate(${f.rotate.toFixed(1)}deg) scale(${f.scale.toFixed(3)})`)}
 property506(root.querySelector('[data-gg-offline503]'),'hidden',c.connected());const error=root.querySelector('[data-gg-error503]');property506(error,'hidden',!c.error);put('[data-gg-error503]',c.error??'');blastAudio504(c,g,at);const last=g.events.at(-1),beat=last?`${g.id}:${last.seq}:${g.phase}`:'';if(last&&u.soundBeat!==beat){u.soundBeat=beat;if(g.phase==='reaction'&&at-g.phaseAt503<700)legacy.gorillaAudio502(c,'safe');if(['pluck','pinch'].includes(g.phase)&&at-g.phaseAt503<700)legacy.gorillaAudio502(c,'pluck')}
}
