// Native UI/functions with local fixtures. No external HTTP or WebSockets.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),server=spawn(process.execPath,['tools/build435/preview-server.mjs'],{stdio:['ignore','pipe','inherit']});let browser;const errors=[],missing=new Set(),checks=[],output='docs/build435';
try{
 await new Promise((r,j)=>{const timeout=setTimeout(()=>j(Error('preview timeout')),15000);server.stdout.on('data',b=>{if(String(b).includes('Preview http')){clearTimeout(timeout);r()}});server.on('exit',c=>j(Error('server '+c)));});
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:393,height:720},isMobile:true,hasTouch:true});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.routeWebSocket('**/*',ws=>ws.close());page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});page.on('response',r=>{if(r.status()===404)missing.add(new URL(r.url()).pathname)});
 await page.goto('http://127.0.0.1:8435');await page.waitForFunction(()=>window.ready435);
 const shot=async name=>page.screenshot({path:output+'/'+name+'.png'}),pause=()=>page.waitForTimeout(550);
 await page.evaluate(()=>qa435.mother());await pause();assert.equal(await page.locator('.campaign-key-counter').count(),0);const expanded=await page.locator('#toggleExplorePartyHud').getAttribute('aria-expanded');await page.locator('#toggleExplorePartyHud').click();assert.notEqual(await page.locator('#toggleExplorePartyHud').getAttribute('aria-expanded'),expanded);await pause();await shot('mother-room');checks.push('mother no key counter and working HUD toggle');
 const p=await page.evaluate(()=>qa435.motherPoint());await page.touchscreen.tap(p.x,p.y);await page.waitForSelector('.mother-challenge-modal433');assert.match(await page.locator('.mother-challenge-modal433').textContent(),/再戦する/);await page.locator('[data-mother-cancel433]').click();checks.push('mother body opens rematch before reading the ending');
 await page.evaluate(()=>{qa434.field();qa434.hero('myth_enami')});const count=await page.evaluate(()=>qa435.currentState.inventory.experienceItemsUltra??0);await page.locator('[data-royal-talk434]').click();await pause();assert.equal(await page.evaluate(()=>qa435.currentState.inventory.experienceItemsUltra??0),count);await shot('gift-before');await page.locator('.royal-gift435-modal [data-modal-dismiss]').click();assert.equal(await page.evaluate(()=>qa435.currentState.inventory.experienceItemsUltra??0),count);checks.push('dismissed gift reveal grants nothing');
 await page.locator('[data-royal-talk434]').click();await page.evaluate(()=>qa435.failSave(true));await page.locator('.royal-gift435-modal [data-modal-primary]').click();assert.equal(await page.evaluate(()=>qa435.currentState.inventory.experienceItemsUltra??0),count);await page.evaluate(()=>qa435.failSave(false));await page.locator('.royal-gift435-modal [data-modal-primary]').click();assert.equal(await page.evaluate(()=>qa435.currentState.inventory.experienceItemsUltra),count+3);await shot('gift-received');await page.locator('.royal-gift435-modal [data-modal-primary]').click();await page.locator('[data-royal-talk434]').click();await page.locator('.royal-gift435-modal [data-modal-primary]').click();assert.equal(await page.evaluate(()=>qa435.currentState.inventory.experienceItemsUltra),count+3);checks.push('gift save failure retries and subsequent reveal cannot duplicate');
 assert.match(await page.locator('[data-royal-solo434]').textContent(),/1,500/);await page.locator('[data-royal-solo434]').click();assert.equal(await page.evaluate(()=>qa435.activeBattle.enemies[0].level),1500);checks.push('personal challenge creates actual Lv1500 opponent');
 await page.evaluate(()=>qa435.rank());await pause();await shot('ranking');await page.locator('[data-power-ranking-player="player2"]').click();assert.equal(await page.evaluate(()=>window.selectedProfile435),'player2');assert.equal(await page.locator('.power-ranking-row').count(),7);checks.push('ranking native tabs, 7 real rows and portrait detail targets');
 await page.evaluate(()=>qa435.gacha());await pause();await shot('gacha');const crystals=await page.evaluate(()=>qa435.currentState.player.crystals);await page.locator('[data-gacha-category="monster"]').scrollIntoViewIfNeeded();await shot('gacha-banners');await page.locator('[data-gacha-category="monster"]').click();await page.waitForSelector('.gacha-count-modal');assert.equal(await page.evaluate(()=>qa435.currentState.player.crystals),crystals);await page.locator('.gacha-count-modal [data-modal-primary]').click();checks.push('generated summon banner opens native count picker without spending');
 for(const size of [{width:393,height:720},{width:375,height:540},{width:430,height:760},{width:1280,height:800}]){
  await page.setViewportSize(size);
  for(const [auto,menu] of [[true,false],[false,false],[false,true]]){
   await page.evaluate(({auto,menu})=>qa435.raid(auto,menu),{auto,menu});await pause();
   const m=await page.evaluate(()=>{const root=document.querySelector('.raid-scroll432'),arena=document.querySelector('.battle-arena').getBoundingClientRect();return{view:innerHeight,width:innerWidth,outerH:document.documentElement.scrollHeight,outerW:document.documentElement.scrollWidth,scroll:root.scrollHeight-root.clientHeight,arena:arena.height,arenaBottom:arena.bottom,retreat:document.querySelector('[data-world-retreat]').getBoundingClientRect().toJSON(),command:document.querySelector('.battle-command').getBoundingClientRect().toJSON(),cards:[...document.querySelectorAll('.side-unit-card')].map(e=>e.getBoundingClientRect().toJSON()),broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)}});
   await shot(`raid-${size.width}-${size.height}-${auto?'auto':menu?'skills':'manual'}`);assert.ok(m.outerH<=size.height+1&&m.outerW<=size.width+1,'outer overflow '+JSON.stringify(m));assert.ok(m.scroll<=1,'raid scroll '+JSON.stringify(m));assert.ok(m.retreat.bottom<=size.height+1,'interrupt outside viewport');assert.ok(m.cards.every(c=>c.top>=0&&c.bottom<=m.arenaBottom+1),'card outside arena '+JSON.stringify(m));assert.equal(m.cards.length,7);assert.deepEqual(m.broken,[]);await shot(`raid-${size.width}-${size.height}-${auto?'auto':menu?'skills':'manual'}`);checks.push(`raid ${size.width}x${size.height} ${auto?'auto':menu?'skills':'manual'} fits with 7 cards and interrupt`);
  }
 }
 await page.setViewportSize({width:393,height:720});for(const n of [3,2,1,0]){await page.evaluate(n=>qa435.lobby(n),n);assert.match(await page.locator('.raid-quota432').textContent(),new RegExp(n+' / 3回'));assert.equal(await page.locator('[data-raid-exchange432] .home-pixel-icon').count(),0);if(n===2)await shot('raid-lobby');}checks.push('raid lobby playable remaining 3 to 0 and fragment icon removed');
 assert.deepEqual(errors,[]);assert.deepEqual([...missing],[]);console.log(JSON.stringify({checks,errors,missing:[...missing]}));
}finally{fs.writeFileSync(output+'/browser-result.json',JSON.stringify({checks,errors,missing:[...missing]},null,2));await browser?.close();server.kill();}
