import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{tmpdir}from'node:os';
const{chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const dir=fs.mkdtempSync(path.join(tmpdir(),'race451-ws-')),env={...process.env,HOST:'127.0.0.1',PORT:'18871'};
for(const[name,file]of Object.entries({FRIEND_STATE_FILE:'friends',GUILD_STATE_FILE:'guilds',POWER_RANKING_STATE_FILE:'rankings',SETTLEMENT_STATE_FILE:'settlements',WORLD_RAID_STATE_FILE:'raids',RACE_STATE_FILE:'race'}))env[name]=path.join(dir,file+'.json');
const processes=[];let browser;const errors=[],checks=[];
function launch(file,cwd,env,ready){const proc=spawn(process.execPath,[file],{cwd,env,stdio:['ignore','pipe','pipe']});processes.push(proc);return new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('startup timeout '+out)),15000);proc.stdout.on('data',b=>{out+=b;if(out.includes(ready)){clearTimeout(timer);resolve(proc)}});proc.stderr.on('data',b=>out+=b);proc.on('exit',c=>{if(c){clearTimeout(timer);reject(Error(out))}})})}
try{
 await launch('server.js',path.resolve('online-server'),env,'Local:');await launch('tools/build452/preview-server.mjs',process.cwd(),process.env,'Preview452 ready');
 const executable=path.resolve('../browser445-133/chromium');fs.chmodSync(executable,0o755);browser=await chromium.launch({executablePath:executable,args:['--no-sandbox','--disable-dev-shm-usage'],env:{...process.env,LD_LIBRARY_PATH:path.dirname(executable),FONTCONFIG_FILE:process.env.RACE_QA_FONTCONFIG||process.env.FONTCONFIG_FILE}});
 const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true});
 await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await context.routeWebSocket('**/*',route=>new URL(route.url()).hostname==='127.0.0.1'?route.connectToServer():route.close());
 const host=await context.newPage();host.on('pageerror',e=>errors.push(e.message));await host.goto('http://127.0.0.1:18451/?name='+encodeURIComponent('えなみ'));await host.waitForFunction(()=>window.qa451?.client.ready());
 await host.locator('[data-race-action="create"]').click();await host.waitForFunction(()=>qa451.client.state?.room?.code);await host.locator('[data-race-monster]').first().click();await host.locator('[data-race-action="start"]').click();await host.waitForFunction(()=>qa451.client.state.room?.phase==='parade');
 await host.evaluate(()=>{const c=qa451.client;clearInterval(c.retryClock);c.raw=()=>false;c.receive=()=>{};qa451.save.state.settings.audioEnabled=true;c.audio.applySettings();c.state.room.racers.forEach((r,i)=>r.condition=i%5);c.render()});
 const moods=[];for(let i=0;i<5;i++){await host.locator('[data-parade-index="'+i+'"]').click();await host.waitForTimeout(80);moods.push(await host.locator('.parade-actor452 > .race-art451').evaluate(e=>getComputedStyle(e).animationName))}assert.equal(new Set(moods).size,5);checks.push({fiveConditionAnimations:moods});
 await host.evaluate(()=>{const c=qa451.client;clearInterval(c.animationClock);c.sound452.stop();c.sound452.play('start')});assert.ok(await host.evaluate(()=>qa451.client.sound452.nodes.size)>0,'native context plays cues');
 await host.locator('[data-race-action="sound452"]').click();assert.equal(await host.evaluate(()=>{qa451.client.sound452.play('win');return qa451.client.sound452.nodes.size}),0);await host.locator('[data-race-action="sound452"]').click();
 assert.equal(await host.evaluate(()=>{const c=qa451.client;c.sound452.stop();c.save.state.settings.audioEnabled=false;c.sound452.play('win');return c.sound452.nodes.size}),0);
 assert.equal(await host.evaluate(()=>{const c=qa451.client;c.save.state.settings.audioEnabled=true;const active=c.audio.pageIsActive;c.audio.pageIsActive=()=>false;c.sound452.play('win');const n=c.sound452.nodes.size;c.audio.pageIsActive=active;return n}),0);checks.push('native audio, local/global mute and inactive-page suppression');
 await host.evaluate(()=>{const c=qa451.client,r=c.state.room;window.nativeRoom452=structuredClone(r);r.phase='race';r.finishMs=Array.from({length:8},(_,i)=>21000+i*600);r.startAt=Date.now()+c.offset-7000;c.render();c.root.scrollTop=0;window.scrollTo(0,0)});
 assert.equal(await host.locator('.race-gate452').first().evaluate(e=>getComputedStyle(e).opacity),'0');checks.push('mid-race resume does not replay gate opening');
 for(const size of[{width:320,height:640},{width:393,height:852},{width:709,height:900}]){await host.setViewportSize(size);await host.waitForTimeout(50);assert.equal(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await host.locator('.race-tickets451').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight+1));checks.push({size,ticketsVisible:true})}
 await host.setViewportSize({width:393,height:852});
 await host.evaluate(()=>{const c=qa451.client,r=c.state.room;r.phase='result';r.phaseAt=Date.now()+c.offset;r.order=[0,1,2,3,4,5,6,7];r.results=r.members.map((m,i)=>({...m,won:i===0,prize:i===0?5000:0,ticket:i===3?null:{kind:i===0?'exact':'win',picks:i===0?[0,1]:[7],amount:1000000,odds:280},stake:i===3?0:1000000,payout:i===0?280000000:0,net:i===0?279005000:i===3?0:-1000000}));c.presentation452=null;c.render()});
 await host.locator('[data-race-action="skip452"]').click();
 assert.deepEqual(await host.locator('[data-podium-place], [data-result-row]').evaluateAll(es=>es.map(e=>getComputedStyle(e).opacity)),Array(7).fill('1'));assert.equal(await host.locator('[data-personal-net]').textContent(),'+279,005,000G');checks.push('skip instantly reveals all three podium places and four exact signed receipts');
 for(const width of[320,393,709]){await host.setViewportSize({width,height:852});assert.equal(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await host.locator('[data-net-value], .settlement-card452 dd').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth+1)),'large receipt amounts fit '+width)}
 await host.setViewportSize({width:393,height:852});await host.screenshot({path:'docs/build452/result-final.png',fullPage:true});
 await host.emulateMedia({reducedMotion:'reduce'});await host.locator('[data-race-action="replay452"]').click();assert.deepEqual(await host.locator('[data-podium-place], [data-result-row]').evaluateAll(es=>es.map(e=>getComputedStyle(e).opacity)),Array(7).fill('1'));assert.equal(await host.locator('[data-personal-net]').textContent(),'+279,005,000G');checks.push('reduced motion reveals complete result without animated count-up');
 await host.evaluate(()=>{const c=qa451.client;c.state.room=structuredClone(window.nativeRoom452);c.paradePinned=0;c.render()});assert.equal(await host.locator('.parade-actor452').evaluate(e=>getComputedStyle(e).animationName),'none');checks.push('reduced motion disables parade movement');
 assert.deepEqual(errors,[]);fs.writeFileSync('docs/build452/layout-results.json',JSON.stringify({checks,errors,fixture:'synthetic visual edge cases after native room setup; money and four-player live flow tested separately'},null,2));console.log(JSON.stringify({checks,errors}));
}finally{await browser?.close();for(const p of processes)p.kill();fs.rmSync(dir,{recursive:true,force:true})}
