import {spawn} from 'node:child_process';
import {writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE);
const out=fileURLToPath(new URL('../../docs/build550/',import.meta.url));await mkdir(out,{recursive:true});
const server=spawn(process.execPath,[fileURLToPath(new URL('./qa-server.mjs',import.meta.url))],{env:process.env,stdio:['ignore','pipe','pipe']});let serverErrors='';server.stderr.on('data',d=>serverErrors+=String(d));
await new Promise((ok,no)=>{server.stdout.on('data',d=>{if(String(d).includes('ready'))ok()});server.on('exit',n=>no(Error('QA server exited '+n+serverErrors)))});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const base='http://127.0.0.1:8550',errors=[],missing=[],report={engine:await browser.version(),scope:'Production Ricochet View/Input/Renderer, real RicochetCoordinator and production PartyCoordinator with unrelated game adapters stubbed; four local WebSocket clients; no live deployment or physical iPhone',checks:[],viewports:[]};
const check=(ok,text)=>{if(!ok)throw Error(text)};
const api=async(path,data={})=>{const r=await fetch(base+'/qa/'+path,{method:'POST',body:JSON.stringify(data)});if(!r.ok)throw Error(await r.text());return r.json()};
async function open(i=0,w=390,h=844){const p=await browser.newPage({viewport:{width:w,height:h},deviceScaleFactor:2,isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.stack));p.on('response',r=>{if(r.status()>=400&&!/assets\/(?:cart|bomb|tetra|hide|fishing|sumo|tower|quiz|luck|gorilla|canal|cabbage|party|sugoroku)/.test(r.url()))missing.push(r.status()+' '+r.url())});await p.goto(base+'/preview.html?self=p'+i);await p.waitForFunction(()=>window.qaReady);await p.evaluate(()=>document.fonts.ready);return p}
async function reset(pages,data={}){const {id}=await api('reset',data);for(const p of pages)await p.waitForFunction(id=>c.state.ricochet?.id===id,id);return id}
async function touch(p){const s=await p.context().newCDPSession(p);return{down:ps=>s.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:ps}),move:ps=>s.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:ps}),up:()=>s.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]}),cancel:()=>s.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]})}}
const point=(x,y,id=1)=>({x,y,id,radiusX:3,radiusY:3});async function anchor(p){const b=await p.locator('[data-rc-stage]').boundingBox();return{x:b.x+b.width*.55,y:b.y+b.height*.43}}
const shot=(p,name)=>p.screenshot({path:out+name+'.png'});
try{
 const pages=await Promise.all([0,1,2,3].map(i=>open(i))),p=pages[0],t=await touch(p);
 for(const mode of ['pinball','junkgp']){
  await reset(pages,{mode,phase:'lobby'});check(await p.locator('[data-rc-monster]').count()===4,'missing roster');await p.locator('[data-rc-rounds="16"]').click();await p.waitForFunction(()=>c.state.ricochet.rounds===16);await p.locator('[data-rc-rounds="8"]').click();await p.waitForFunction(()=>c.state.ricochet.rounds===8);for(const page of pages)await page.locator('[data-party-action462="ready"]').click();await p.locator('[data-rc-action="start"]').click();for(const page of pages)await page.waitForFunction(()=>c.state.ricochet.phase==='draft');
  await shot(p,mode+'-draft');for(const page of pages){check(await page.locator('[data-rc-pick]').count()===3,'three choices missing');check(await page.evaluate(()=>c.state.ricochet.players.filter(p=>p.playerId!==c.transport.selfId).every(p=>!('offers' in p))),'opponent choices leaked');await page.locator('[data-rc-pick]').first().click()}
  for(const page of pages)await page.waitForFunction(()=>c.state.ricochet.phase==='play');let a=await anchor(p);await t.down([point(a.x,a.y)]);await t.move([point(a.x+15,a.y+75)]);await p.waitForTimeout(100);const power=await p.evaluate(()=>c.ricochetUI550.pull.power);await p.waitForTimeout(700);check(await p.evaluate(()=>c.ricochetUI550.pull.power)===power,'hold time changed pull power');await shot(p,mode+'-pull');await t.up();for(const page of pages)await page.waitForFunction(()=>c.state.ricochet.players[0].launched);check((await api('state')).players[0].power===power,'released power not authoritative');report.checks.push(mode+': real lobby, ready, 8/16 settings, 4 humans draft privately, distance-based pull and shared release');
  const {id}=await api('push',{mode});for(const page of pages)await page.waitForFunction(id=>c.state.ricochet.id===id,id);a=await anchor(p);await t.down([point(a.x,a.y)]);await t.move([point(a.x,a.y+55)]);await pages[1].evaluate(()=>{const g=c.state.ricochet;c.raw('ricochetInput550',{gameId:g.id,round:g.round,seq:100,action:'shoot',angle:Math.PI/2,power:.35})});await p.waitForFunction(()=>c.state.ricochet.players[0].x>.24);check(await p.evaluate(()=>!c.state.ricochet.players[0].launched&&c.ricochetUI550.pull.active),'impact cancelled held shot');await t.up();for(const page of pages)await page.waitForFunction(()=>c.state.ricochet.players[0].launched);const launch=(await api('state')).events.find(e=>e.type==='launch'&&e.seat===0);check(launch?.carryX>1&&launch.vx===launch.carryX&&launch.vy>launch.carryY+3,'carry velocity lost '+JSON.stringify(launch));report.checks.push(mode+': peer pushes waiting player during pull; release preserves sideways carry on all four clients');
  await reset(pages,{mode,phase:'play',round:7,upgrades:true});for(let i=0;i<pages.length;i++)await pages[i].evaluate(i=>{const g=c.state.ricochet;c.raw('ricochetInput550',{gameId:g.id,round:g.round,seq:10,action:'shoot',angle:[.34,-.42,.5,-.32][i],power:.9})},i);await p.waitForTimeout(1600);await shot(p,mode+'-action');await api('pause',{value:true});await p.waitForTimeout(100);const totals=await Promise.all(pages.map(q=>q.evaluate(()=>JSON.stringify(c.state.ricochet.players.map(p=>[p.score,p.roundScore,p.parts,p.charge,p.launched])))));check(totals.every(s=>s===totals[0]),'four client state disagreement');
 }
 for(const mode of ['tap','return','cancel','blur','multi','round']){
  await reset(pages,{mode:'pinball'});const a=await anchor(p);await t.down([point(a.x,a.y)]);if(mode!=='tap')await t.move([point(a.x+15,a.y+70)]);if(mode==='return')await t.move([point(a.x+2,a.y+2)]);if(mode==='cancel')await t.cancel();else if(mode==='blur'){await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await t.up()}else if(mode==='multi'){await t.down([point(a.x+15,a.y+70),point(a.x-30,a.y+15,2)]);await t.up()}else if(mode==='round'){await reset(pages,{mode:'junkgp'});await t.up()}else await t.up();await p.waitForTimeout(120);check(!(await api('state')).players[0].launched,mode+' accidentally fired');check(await p.evaluate(()=>c.ricochetUI550.pull==null),mode+' retained pull')
 }
 report.checks.push('Tap, return to origin, native cancellation, blur, multitouch and round change all cancel without firing');
 await reset(pages,{mode:'pinball'});await p.locator('[data-rc-detail="0"]').first().click();check(await p.locator('[role="dialog"]').count()===1,'inventory missing');await p.keyboard.press('Escape');check(await p.locator('[role="dialog"]').count()===0,'inventory escape failed');await p.locator('[data-rc-canvas]').focus();await p.keyboard.press('ArrowUp');await p.keyboard.press('ArrowLeft');await p.keyboard.press('Enter');await p.waitForFunction(()=>c.state.ricochet.players[0].launched);report.checks.push('Inventory, Escape close and keyboard direction/power/release');
 for(const [w,h] of [[320,690],[390,664],[430,932],[844,390]]){
  await p.setViewportSize({width:w,height:h});for(const mode of ['pinball','junkgp'])for(const phase of ['draft','play','intermission','result']){
   await reset(pages,{mode,phase,round:6,upgrades:true});await api('pause',{value:true});await p.waitForTimeout(90);const bounds=await p.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,stage:document.querySelector('[data-rc-stage]')?.getBoundingClientRect().height??0,pawns:[...document.querySelectorAll('[data-rc-pawn]')].filter(e=>!e.hidden).length,offers:[...document.querySelectorAll('[data-rc-pick]')].map(e=>{const r=e.getBoundingClientRect();return{top:r.top,bottom:r.bottom}}),footer:document.querySelector('[data-rc-stage]')?.getBoundingClientRect().bottom??innerHeight}));check(bounds.width<=bounds.viewport+1,mode+' '+phase+' horizontal overflow '+w+'x'+h);if(phase==='draft')check(bounds.offers.every(b=>b.top>=40&&b.bottom<=bounds.footer),mode+' draft clipped '+w+'x'+h);if(phase==='intermission')check(bounds.pawns===0,'pawns above result');if(phase!=='result')check(bounds.stage>=120,'too little play space');await shot(p,mode+'-'+phase+'-'+w+'x'+h);
  }report.viewports.push({width:w,height:h,bothModes:['draft','play','intermission','result']});
 }
 await p.setViewportSize({width:390,height:844});await reset(pages,{mode:'junkgp',phase:'result'});const old=await p.evaluate(()=>c.state.ricochet.id);await p.locator('[data-party-result490="again"]').click();await p.waitForFunction(id=>c.state.ricochet.id!==id&&c.state.ricochet.phase==='lobby',old);await reset(pages,{mode:'pinball',phase:'result'});await p.locator('[data-party-result490="list"]').click();await p.waitForFunction(()=>!c.state.ricochet);check(await p.locator('[data-party-game462="pinball"]').count()===1,'pinball menu absent');check(await p.locator('[data-party-game462="junkgp"]').count()===1,'junkgp menu absent');report.checks.push('Result replay creates fresh game and list button closes game; both new menu entries present');
 await reset(pages,{mode:'junkgp',phase:'play'});await pages[1].evaluate(()=>window.dispose550());await api('advance',{ms:5000});check((await api('state')).players[1].launched,'disconnected player not automated');report.checks.push('Disconnected human is taken over by AI and still launches');
 await p.emulateMedia({reducedMotion:'reduce'});await reset([p],{mode:'pinball'});check(await p.evaluate(()=>c.ricochetUI550.reduced),'reduced motion ignored');await p.waitForTimeout(100);report.checks.push('Reduced motion skips trail/flash animation');
 report.errors=errors;report.missing=missing;report.serverErrors=serverErrors;check(!errors.length,'page errors '+errors.join('\n'));check(!missing.length,'missing assets '+missing.join('\n'));check(!serverErrors,'server errors '+serverErrors);await writeFile(out+'browser-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await browser.close();server.kill()}
