import {TETRA539 as C,clamp539,pad539,pose539,wave539,aim539,tip539} from './Rules539.js';
import {color499} from '../party/PartyColors499.js';
const TAU=Math.PI*2,images=new Map();
const art=name=>{if(!images.has(name)){const i=new Image();i.decoding='async';i.src=new URL(`../../assets/${'tetra541'}/${name}.webp`,import.meta.url).href;images.set(name,i)}return images.get(name)};
const ready=i=>i?.complete&&i.naturalWidth>0;
export function renderer539(canvas){return{canvas,ctx:canvas.getContext('2d',{alpha:false}),ocean:art('ocean'),pads:art('pads'),width:0,height:0,scale:1,cameraY:null,cameraX:0,points:[]}}
export function resize539(r,w,h,dpr=1){r.width=w;r.height=h;r.dpr=Math.min(1.5,dpr);r.canvas.width=Math.round(w*r.dpr);r.canvas.height=Math.round(h*r.dpr);r.scale=w/950;r.oceanCache=null}
export const worldPoint539=(r,x,y)=>({x:x/r.scale+r.cameraX,y:y/r.scale+r.cameraY});
export const screenPoint539=(r,x,y)=>({x:(x-r.cameraX)*r.scale,y:(y-r.cameraY)*r.scale});
function label(c,text,x,y,color='#fff3d7',size=10){c.font=`700 ${size}px "Noto Sans JP",sans-serif`;c.textAlign='center';c.textBaseline='middle';c.lineWidth=3;c.strokeStyle='#06333de8';c.strokeText(text,x,y);c.fillStyle=color;c.fillText(text,x,y)}
function ellipse(c,x,y,rx,ry,fill,stroke){c.beginPath();c.ellipse(x,y,rx,ry,0,0,TAU);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.stroke()}}
function ocean(r){if(!ready(r.ocean))return null;if(!r.oceanCache){const q=document.createElement('canvas');q.width=r.canvas.width;q.height=r.canvas.height+120;const c=q.getContext('2d'),s=Math.max(q.width/r.ocean.width,q.height/r.ocean.height);c.drawImage(r.ocean,(q.width-r.ocean.width*s)/2,0,r.ocean.width*s,r.ocean.height*s);r.oceanCache=q}return r.oceanCache}
export function paint539(r,g,selfId,u,at,reduced=false){const c=r.ctx,w=r.width,h=r.height;if(!w||!g.course)return;r.scale=w/(u.overview541?C.width:950);const elapsed=g.phase==='countdown'?Math.min(0,at-g.startAt):g.phase==='result'?g.elapsed:g.elapsed+Math.min(150,Math.max(0,at-g.serverAt)),p=g.players.find(p=>p.playerId===selfId)??g.players[0],pos=pose539(g,p,elapsed),previewAim=u.chargeStart!=null&&!p.flight&&p.fallAt==null?aim539(g,p,u.angle,u.power??0,elapsed):null;
 const viewW=w/r.scale,viewH=h/r.scale,aiming=previewAim&&previewAim.distance>=C.minJump;let camTarget=pos.y-viewH*.78;
 // Drag length is screen-relative, so the camera can keep both feet and landing visible.
 if(aiming)camTarget=clamp539(camTarget,Math.max(pos.y,previewAim.y)+160-viewH,Math.min(pos.y,previewAim.y)-160);
 camTarget=clamp539(camTarget,-100,Math.max(-100,C.height+300-viewH));const camX=u.overview541?0:clamp539((aiming?(pos.x+previewAim.x)/2:pos.x)-viewW*.5,-80,C.width+80-viewW),first=r.lastPaint==null,dt=Math.min(100,Math.max(0,at-(r.lastPaint??at-16.67))),blend=reduced?1:1-Math.exp(-dt/90);r.lastPaint=at;
 r.cameraX=first?camX:r.cameraX+(camX-r.cameraX)*blend;
 if(r.cameraY==null||Math.abs(r.cameraY-camTarget)>1000)r.cameraY=camTarget;else r.cameraY+=(camTarget-r.cameraY)*blend;
 c.setTransform(r.dpr,0,0,r.dpr,0,0);c.fillStyle='#075269';c.fillRect(0,0,w,h);const bg=ocean(r);if(bg){const pan=clamp539(r.cameraY/C.height,0,1)*100;c.drawImage(bg,0,pan,bg.width,r.canvas.height,0,0,w,h);c.fillStyle='#00394b2b';c.fillRect(0,0,w,h)}
 if(!reduced){c.strokeStyle='#baf6ee30';c.lineWidth=1;for(let i=0;i<14;i++){const x=(i*89+Math.sin(at/3400+i)*13)%w,y=((i*67+at/140-r.cameraY*r.scale*.23)%(h+20)+h+20)%(h+20);c.beginPath();c.moveTo(x,y);c.quadraticCurveTo(x+14,y-4,x+29,y);c.stroke()}}
 const wave=wave539(elapsed),visible=g.course.pads.filter(pad=>{const y=(pad.y-r.cameraY)*r.scale;return y>-140&&y<h+140&&pad.x>r.cameraX-200&&pad.x<r.cameraX+w/r.scale+200}).map(pad=>pad539(g,pad,elapsed)).sort((a,b)=>a.y-b.y);
 for(const pad of visible){const s=screenPoint539(r,pad.x,pad.y),size=pad.r*(pad.checkpoint!=null?2.28:2.50)*r.scale,cell=pad.checkpoint!=null?3:pad.kind==='low'?1:pad.kind==='slippery'?2:0;
  ellipse(c,s.x,s.y+size*.17,size*.42,size*.22,'#00253750');c.save();c.translate(s.x,s.y);c.rotate(pad.angle*.25);c.globalAlpha=pad.submerged?.24:1;
  if(ready(r.pads)){const cw=r.pads.width/2,ch=r.pads.height/2;c.drawImage(r.pads,cell%2*cw,Math.floor(cell/2)*ch,cw,ch,-size/2,-size*[.18,.28,.18,.54][cell],size,size)}else ellipse(c,0,0,pad.r*r.scale,pad.r*r.scale*.8,'#b2a990','#eedbb1');c.restore();
  if(pad.checkpoint!=null){c.lineWidth=1.6;ellipse(c,s.x,s.y,(pad.r-12)*r.scale,(pad.r-12)*r.scale,null,'#d8f2bc80');label(c,pad.kind==='finish'?'GOAL':pad.checkpoint===0?'START':`中継 ${pad.checkpoint}`,s.x,s.y+size*.40,'#fbefc4',10)}
  else{c.lineWidth=1;ellipse(c,s.x,s.y,pad.tip*r.scale,pad.tip*r.scale,pad.submerged?'#4bb3c13a':'#fff1b510',pad.submerged?'#9beaf066':'#fff3b999');if(pad.submerged||pad.tideWarning)label(c,pad.submerged?'水没':'まもなく水没',s.x,s.y+size*.39,pad.submerged?'#b6f8ff':'#ffcaa0',8)}
 }
 // A broad travelling crest, persistent raised water and multiple foam streaks.
 if(wave.active){const worldFront=C.height-wave.phase/950*C.height,front=(worldFront-r.cameraY)*r.scale,top=Math.max(0,front);if(top<h){c.fillStyle=wave.big?'#b0e9ef66':'#56c7de38';c.fillRect(0,top,w,h-top)}if(front>-120&&front<h+120){const grad=c.createLinearGradient(0,front-30,0,front+115);grad.addColorStop(0,'#b5f1ff00');grad.addColorStop(.22,'#eafffff0');grad.addColorStop(.38,'#b5ffffc0');grad.addColorStop(1,'#50b8d300');c.fillStyle=grad;c.fillRect(0,front-30,w,145);for(let row=0;row<5;row++){c.strokeStyle=row===0?'#ffffffef':'#e3ffff88';c.lineWidth=row===0?4:1.5;c.beginPath();for(let x=0;x<=w;x+=5){const y=front+row*10+Math.sin(x/18+elapsed/140+row)*5+Math.cos(x/41-row)*7;x?c.lineTo(x,y):c.moveTo(x,y)}c.stroke()}}}
 const charging=u.chargeStart!=null&&!p.flight&&p.fallAt==null&&p.finishedAt==null&&g.phase==='play';r.preview=null;
 if(charging){const a=previewAim??aim539(g,p,u.angle,u.power??0,elapsed),target=screenPoint539(r,a.x,a.y),origin=screenPoint539(r,pos.x,pos.y),valid=a.distance>=C.minJump&&a.pad&&!a.occupied,color=valid?(p.flow541>=3?'#a3f7ff':'#fff0a6'):'#ffac99';r.preview={...a,tx:a.x,ty:a.y,land:a.pad?.id??null};
  c.save();c.setLineDash([4,5]);c.strokeStyle=color;c.lineWidth=2;c.beginPath();c.moveTo(origin.x,origin.y);c.quadraticCurveTo((origin.x+target.x)/2,(origin.y+target.y)/2-35,target.x,target.y);c.stroke();c.setLineDash([]);ellipse(c,target.x,target.y,12,12,'#012c42a0',color);ellipse(c,target.x,target.y,3,3,color);label(c,a.distance<C.minJump?'戻してキャンセル':a.occupied?'先客がいる！':!a.pad?'着地できない':a.tip?(p.flow541>=3?'追い風ジャンプ！':'先端に着地'):'足場に着地',target.x,Math.max(18,target.y-23),color,10);
  if(u.drag){const b=u.drag;c.lineWidth=2;c.strokeStyle='#fff5c8aa';c.beginPath();c.moveTo(b.x,b.y);c.lineTo(b.cx,b.cy);c.stroke();ellipse(c,b.x,b.y,6,6,'#fff0b4');ellipse(c,b.cx,b.cy,24,24,'#062e45aa','#fff0b4');label(c,Math.round((u.power??0)*100)+'%',b.cx,b.cy,'#fff4c7',11)}c.restore()}
 for(const e of g.events){const age=elapsed-e.at;if(e.type!=='perfect541'||age<0||age>750)continue;const q=screenPoint539(r,e.x,e.y);c.save();c.globalAlpha=1-age/750;c.strokeStyle=e.flow>=3?'#a3f7ff':'#ffe29b';c.lineWidth=2;ellipse(c,q.x,q.y,12+age*.035,6+age*.016,null,c.strokeStyle);label(c,e.flow>=3?'追い風 READY':'PERFECT!',q.x,q.y-28-age*.04,c.strokeStyle,14);c.restore()}
 const points=[];for(const player of g.players){const point=pose539(g,player,elapsed),s=screenPoint539(r,point.x,point.y),fall=player.fallAt!=null?clamp539((elapsed-player.fallAt)/550,0,1):0;points.push({seat:player.seat,x:s.x,y:s.y-point.z*r.scale,visible:s.y>=-60&&s.y<=h+65,fall,scale:1+point.z/850});if(s.y<-50||s.y>h+50)continue;const color=color499(player.color499,player.seat).hex;c.globalAlpha=1-fall;ellipse(c,s.x,s.y+2,player.playerId===selfId?10:8,4,'#00263c88',color);c.globalAlpha=1}r.points=points;
 for(const e of g.events){const age=elapsed-e.at;if(e.type!=='splash'||age<0||age>1000)continue;const s=screenPoint539(r,e.x,e.y),t=age/1000;c.save();c.globalAlpha=1-t;c.lineWidth=2;ellipse(c,s.x,s.y,10+t*35,5+t*17,null,'#ecffff');if(!reduced)for(let i=0;i<8;i++){const a=i*TAU/8;ellipse(c,s.x+Math.cos(a)*t*40,s.y+Math.sin(a)*t*20-Math.sin(t*Math.PI)*23,2,4,'#dcffff')}c.restore()}
 const px=w-11,top=85,bottom=h-57;c.strokeStyle='#062537ba';c.lineWidth=5;c.beginPath();c.moveTo(px,top);c.lineTo(px,bottom);c.stroke();for(let i=0;i<6;i++)ellipse(c,px,bottom-(bottom-top)*i/5,3,3,'#e1c990');for(const player of g.players){const progress=clamp539((C.startY-(player.finishedAt!=null?C.goalY:pose539(g,player,elapsed).y))/(C.startY-C.goalY),0,1);ellipse(c,px+(player.seat%2?-3:3),bottom-progress*(bottom-top),player.playerId===selfId?5:3.5,player.playerId===selfId?5:3.5,color499(player.color499,player.seat).hex,player.playerId===selfId?'#fff3c7':null)}
 if(p.fallAt!=null){label(c,'より「イージー！」',w/2,h*.44,'#ffe4a7',20);label(c,'直前の中継ポイントから復帰',w/2,h*.44+27,'#ffffff',11)}if(p.finishedAt!=null){label(c,'GOAL!',w/2,h*.38,'#ffe5a6',36);label(c,'仲間のゴールを見守ろう',w/2,h*.38+37)}return{elapsed,wave,charging}
}
