// Build563: forgiving landing, tap-to-jump and recovery from the last safe foothold.
export const TETRA539=Object.freeze({width:1500,height:6500,startY:6100,goalY:300,step:50,countdown:4000,duration:150000,grace:20000,minJump:38,maxJump:520,respawn:800,waveEvery:12000,waveLife:2700,waveWarning:3500,bigEvery:36000,bigLife:3500,bigWarning:6500,body:45});
const C=TETRA539,copy=x=>structuredClone(x),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export const clamp539=(v,a,b)=>Math.max(a,Math.min(b,v));
const random=g=>{let n=g.seed|0;n^=n<<13;n^=n>>>17;n^=n<<5;g.seed=n>>>0||540;return g.seed/4294967296};
export function course539(seed=540){
 const rng={seed:seed||540},pads=[],checkpoints=[];const add=p=>{p.id=pads.length;pads.push(p);return p.id};
 for(let i=0;i<6;i++)checkpoints.push(add({x:i===0||i===5?750:530+random(rng)*440,y:C.startY-i*1160,r:180,tip:180,angle:0,kind:i===5?'finish':'refuge',checkpoint:i,section:Math.max(0,i-1)}));
 // Jitter both axes independently; no safe lane or prescribed shortcut.
 for(let row=1;row<31;row++)for(let col=0;col<6;col++){
  const x=125+col*250+(random(rng)-.5)*110,y=C.startY-row*190+(random(rng)-.5)*135,r=78+random(rng)*15;
  if(y<370||pads.some(p=>dist(p,{x,y})<p.r+r+16))continue;
  const draw=random(rng),kind=draw<.28?'low':draw<.58?'slippery':'stable';
  add({x,y,r,tip:30,angle:(random(rng)-.5)*.7,kind,section:Math.min(4,Math.floor((C.startY-y)/1160)),tideOffset:Math.floor(random(rng)*12000)});
 }
 // Validate connectivity and fill only unusually large gaps after random placement.
 for(let i=0;i<5;i++){const a=pads[checkpoints[i]],b=pads[checkpoints[i+1]];for(let j=1;j<=4;j++){const q={x:a.x+(b.x-a.x)*j/5,y:a.y+(b.y-a.y)*j/5};if(!pads.some(p=>dist(p,q)<180))add({...q,r:82,tip:30,angle:0,kind:j%2?'slippery':'low',section:i,tideOffset:Math.floor(random(rng)*12000)})}}
 for(const pad of pads)if(pad.checkpoint==null&&pad.section===0){pad.kind='stable';pad.r=Math.max(94,pad.r);pad.tip=44;}
 return{version:4,seed,width:C.width,height:C.height,pads,checkpoints};
}
export function wave539(at){const t=Math.max(0,at),bigPhase=t%C.bigEvery,phase=t%C.waveEvery,big=t>=C.bigEvery&&bigPhase<C.bigLife,bigWarning=!big&&bigPhase>=C.bigEvery-C.bigWarning,active=big||t>=C.waveEvery&&phase<C.waveLife;return{active,big,bigWarning,warning:bigWarning||!active&&phase>=C.waveEvery-C.waveWarning,next:bigWarning?C.bigEvery-bigPhase:C.waveEvery-phase,bigNext:C.bigEvery-bigPhase,phase:big?bigPhase:phase,life:big?C.bigLife:C.waveLife}}
// The crest sweeps up the whole course, then the water remains high until the wave recedes.
export function waveAt539(at,y){const wave=wave539(at),arrival=(C.height-y)/C.height*950;return{...wave,here:wave.active&&wave.phase>=arrival}}
export function pad539(g,p,at=g.elapsed){const wave=waveAt539(at,p.y),tide=(Math.max(0,at)+(p.tideOffset??0))%17000,submerged=p.kind==='low'&&(tide>13000||wave.here)||wave.here&&wave.big&&p.checkpoint==null&&p.section>0;return{...p,angle:p.angle??0,submerged,wet:wave.here,tide,tideWarning:p.kind==='low'&&tide>11200&&tide<=13000}}
export const maxJump541=p=>(p?.flow541??0)>=3?700:C.maxJump;
export const jumpDistance539=(power,p)=>maxJump541(p)*clamp539(power,0,1);
export const flightTime539=d=>Math.round(420+d*.7);
export function support539(p,x,y){const dx=x-p.x,dy=y-p.y;if(p.checkpoint!=null)return Math.hypot(dx,dy)<=p.r-12;if(Math.hypot(dx,dy)<=p.tip+17)return true;const co=Math.cos(p.angle??0),si=Math.sin(p.angle??0),xx=dx*co+dy*si,yy=-dx*si+dy*co;return Math.abs(xx)<=p.r*.84&&Math.abs(yy)<=p.r*.38||Math.abs(yy)<=p.r*.84&&Math.abs(xx)<=p.r*.38}
export const tip539=(pad,x,y)=>pad.checkpoint!=null||Math.hypot(x-pad.x,y-pad.y)<=pad.tip;
export function landing539(g,x,y,at=g.elapsed){return g.course.pads.map(p=>pad539(g,p,at)).filter(p=>!p.submerged&&support539(p,x,y)&&(!p.wet||tip539(p,x,y))).sort((a,b)=>dist(a,{x,y})-dist(b,{x,y}))[0]??null}
export function pose539(g,p,at=g.elapsed){if(p.flight){const f=p.flight,t=clamp539((at-f.at)/f.duration,0,1);return{x:f.x+(f.tx-f.x)*t,y:f.y+(f.ty-f.y)*t,z:Math.sin(t*Math.PI)*(100+f.distance*.45)}}return{x:p.x,y:p.y,z:0}}
export function occupied539(g,x,y,at,except){return g.players.some(p=>p.playerId!==except&&p.fallAt==null&&p.finishedAt==null&&(()=>{const q=pose539(g,p,at);return q.z<45&&Math.hypot(q.x-x,q.y-y)<C.body*2+3})())}
export function aim539(g,p,angle,power,at=g.elapsed){const from=pose539(g,p,at),d=jumpDistance539(power,p);let x=from.x+Math.cos(angle)*d,y=from.y+Math.sin(angle)*d;
 // Snapping is shown by the renderer and resolved by this same shared function.
 const tip=g.course.pads.filter(pad=>pad.checkpoint==null&&Math.hypot(pad.x-x,pad.y-y)<=(pad.section===0?80:62)&&dist(from,pad)<=maxJump541(p)&&!pad539(g,pad,at+flightTime539(dist(from,pad))).submerged&&!occupied539(g,pad.x,pad.y,at+flightTime539(dist(from,pad)),p.playerId)).sort((a,b)=>dist(a,{x,y})-dist(b,{x,y}))[0];if(tip){x=tip.x;y=tip.y}
 const distance=Math.hypot(x-from.x,y-from.y),arrival=at+flightTime539(distance),pad=landing539(g,x,y,arrival),occupied=occupied539(g,x,y,arrival,p.playerId);return{x,y,distance,arrival,pad,occupied,tip:!!pad&&tip539(pad,x,y)}}
const event=(g,type,extra={})=>{g.events.push({id:++g.eventSeq,at:g.elapsed,type,...extra});g.events=g.events.slice(-28)};
export function makeTetra539({id,code,partyId,hostId,members,now=0}){return{id,code,game:'tetra',rulesVersion:4,partyId462:partyId,hostId,members:copy(members),phase:'lobby',revision:0,createdAt:now,updatedAt:now,serverAt:now,lastAt:now,elapsed:0,players:[],events:[],eventSeq:0,results:[]}}
export function spawn539(g,p){const refuge=g.course.pads[g.course.checkpoints[p.checkpoint]],last=g.course.pads[p.safePad563],candidates=[...(last&&last.id!==refuge.id?[last]:[]),refuge];
 for(const raw of candidates){const pad=pad539(g,raw);if(pad.submerged)continue;const offsets=pad.checkpoint!=null?[[-65,55],[65,55],[-65,-55],[65,-55],[0,0],[-115,0],[115,0],[0,115],[0,-115]]:[[0,0]];
  for(let n=0;n<offsets.length;n++){const [x,y]=offsets[(p.seat+n)%offsets.length],q={x:pad.x+x,y:pad.y+y};if(!occupied539(g,q.x,q.y,g.elapsed,p.playerId)){Object.assign(p,{...q,padId:pad.id,ox:x,oy:y,fallAt:null,flight:null,chargeAt:null,landedAt:g.elapsed,recoverUntil563:g.elapsed+1100});return true;}}
 }return false;
}
const spawn=spawn539;
export function tapAim563(g,p,x,y){const from=pose539(g,p),pads=g.course.pads.filter(pad=>dist(pad,{x,y})<pad.r+24).sort((a,b)=>dist(a,{x,y})-dist(b,{x,y}));for(const pad of pads){const targets=pad.checkpoint!=null?[{x,y},...[[0,0],[-65,55],[65,55],[-65,-55],[65,-55]].map(([dx,dy])=>({x:pad.x+dx,y:pad.y+dy}))]:[pad];for(const q of targets){const d=dist(from,q);if(d<C.minJump||d>maxJump541(p))continue;const angle=Math.atan2(q.y-from.y,q.x-from.x),power=d/maxJump541(p),aim=aim539(g,p,angle,power);if(aim.pad?.id===pad.id&&!aim.occupied)return{angle,power};}}return null;}

export function startTetra539(g,now,seed=540){g.seed=seed||540;g.rulesVersion=4;g.course=course539(seed);g.padStates={};g.players=g.members.filter(m=>!m.departed).map((m,seat)=>({playerId:m.playerId,name:m.name,seat,ai:!!m.ai,speciesId:m.choice?.speciesId??'slime',color499:m.color499??['blue','green','pink','orange'][seat]}));while(g.players.length<4){const seat=g.players.length;g.players.push({playerId:`AI-${g.id}-${seat}`,name:['しぶき','しおかぜ','より','なみのり'][seat],seat,ai:true,speciesId:['myth_yori','wolf','myth_yori','slime'][seat],color499:g.aiColors500?.[seat]??['blue','green','pink','orange'][seat]})}
 Object.assign(g,{phase:'countdown',startAt:now+C.countdown,endAt:now+C.countdown+C.duration,lastAt:now,serverAt:now,elapsed:-C.countdown,firstFinish:null,events:[],eventSeq:0,results:[],waveCycle:0});
 for(const p of g.players)Object.assign(p,{x:0,y:0,padId:null,checkpoint:0,bestY:C.startY,falls:0,jumps:0,landings:0,flow541:0,perfect541:0,safePad563:null,lastFall563:null,lastSeq:0,chargeAt:null,power:0,aim:-Math.PI/2,flight:null,fallAt:-C.countdown,finishedAt:null,auto:p.ai,brain:{next:350+p.seat*280},landedAt:0});for(const p of g.players)spawn(g,p);g.updatedAt=now;g.revision++;return g}
export function fall539(g,p,reason='miss'){if(p.fallAt!=null||p.finishedAt!=null)return;const q=pose539(g,p);Object.assign(p,{x:q.x,y:q.y,padId:null,flight:null,chargeAt:null,fallAt:g.elapsed,falls:p.falls+1,flow541:0,lastFall563:reason});event(g,'splash',{seat:p.seat,x:p.x,y:p.y,reason})}
export function inputTetra539(g,p,a){if(g.phase!=='play'||p.finishedAt!=null||p.fallAt!=null||p.flight)return false;if(a.action==='cancel'){p.chargeAt=null;p.power=0;return true}if(!Number.isFinite(a.angle)||!Number.isFinite(a.power)||a.power<0||a.power>1||a.angle< -Math.PI||a.angle>Math.PI)return false;p.aim=a.angle;p.power=a.power;
 if(a.action==='begin'){if(p.chargeAt!=null)return false;p.chargeAt=g.elapsed;return true}if(a.action==='aim')return p.chargeAt!=null;if(a.action!=='release'||p.chargeAt==null)return false;p.chargeAt=null;if(jumpDistance539(p.power,p)<C.minJump)return false;
 const q=aim539(g,p,p.aim,p.power),from=pose539(g,p),boosted=(p.flow541??0)>=3,fromPad=p.padId;if(boosted)p.flow541=0;Object.assign(p,{flight:{fromPad,boosted,x:from.x,y:from.y,tx:q.x,ty:q.y,at:g.elapsed,distance:q.distance,duration:flightTime539(q.distance)},padId:null,jumps:p.jumps+1});event(g,'jump',{seat:p.seat,x:p.x,y:p.y,boosted});return true}
export function order539(g){return [...g.players].sort((a,b)=>a.finishedAt!=null&&b.finishedAt!=null?a.finishedAt-b.finishedAt||a.seat-b.seat:a.finishedAt!=null?-1:b.finishedAt!=null?1:b.checkpoint-a.checkpoint||a.bestY-b.bestY||a.falls-b.falls||a.seat-b.seat)}
export function finishTetra539(g,reason='time'){if(g.phase==='result')return;g.phase='result';g.reason=reason;let previous;g.results=order539(g).map((p,i)=>{const key=p.finishedAt!=null?'f'+p.finishedAt:`p${p.checkpoint}:${p.bestY}:${p.falls}`,rank=key===previous?.key?previous.rank:i+1;previous={key,rank};return{playerId:p.playerId,seat:p.seat,name:p.name,rank,finishedAt:p.finishedAt,progress:Math.round((C.startY-p.bestY)/(C.startY-C.goalY)*100),falls:p.falls,jumps:p.jumps,landings:p.landings,perfect541:p.perfect541}});g.players.forEach(p=>p.chargeAt=null);event(g,'finish');g.updatedAt=g.lastAt;g.revision++}
function land(g,p){const f=p.flight,x=f.tx,y=f.ty,pad=landing539(g,x,y);if(!pad||occupied539(g,x,y,g.elapsed,p.playerId)){p.x=x;p.y=y;p.flight=null;fall539(g,p,pad?'occupied':'miss');return}Object.assign(p,{x,y,ox:x-pad.x,oy:y-pad.y,padId:pad.id,flight:null,landedAt:g.elapsed,landings:p.landings+1,safePad563:pad.id});
 if(pad.checkpoint==null){if(tip539(pad,x,y)&&f.distance>=120&&f.fromPad!==pad.id){p.flow541=Math.min(3,(p.flow541??0)+1);p.perfect541=(p.perfect541??0)+1;event(g,'perfect541',{seat:p.seat,x,y,flow:p.flow541})}else p.flow541=0;}
 if(pad.checkpoint===p.checkpoint+1){p.checkpoint=pad.checkpoint;event(g,'checkpoint',{seat:p.seat,checkpoint:p.checkpoint})}if(pad.section<=p.checkpoint)p.bestY=Math.min(p.bestY,y);
 if(pad.kind==='finish'&&p.checkpoint===g.course.checkpoints.length-1){p.finishedAt=g.elapsed;p.bestY=C.goalY;if(g.firstFinish==null){g.firstFinish=g.elapsed;g.endAt=Math.min(g.endAt,g.startAt+g.elapsed+C.grace)}event(g,'goal',{seat:p.seat})}else event(g,'land',{seat:p.seat,x,y});p.brain.next=g.elapsed+1500+random(g)*1000}
function clearFlight539(g,p,target,distance){const duration=flightTime539(distance);for(let dt=50;dt<duration;dt+=50){const t=dt/duration,q={x:p.x+(target.x-p.x)*t,y:p.y+(target.y-p.y)*t,z:Math.sin(t*Math.PI)*(100+distance*.45)};for(const other of g.players){if(other===p||other.fallAt!=null||other.finishedAt!=null)continue;const v=pose539(g,other,g.elapsed+dt);if(dist(q,v)<C.body*2+4&&Math.abs(q.z-v.z)<42)return false}}return true}
function bot539(g,p){if(p.flight||p.fallAt!=null||p.finishedAt!=null||g.elapsed<p.brain.next)return;const target=g.course.pads[g.course.checkpoints[p.checkpoint+1]],current=g.course.pads[p.padId];if(!target)return;const wave=wave539(g.elapsed),bigSoon=wave.big||wave.bigNext<6000;if(current.checkpoint!=null&&bigSoon)return;
 const candidates=[];for(const pad of g.course.pads){if(pad.checkpoint!=null&&pad.checkpoint!==p.checkpoint+1)continue;if(pad.y<target.y-100||dist(p,pad)>maxJump541(p)+(pad.checkpoint!=null?pad.r:0)||pad.checkpoint==null&&dist(pad,target)>dist(p,target)-30)continue;const offsets=pad.checkpoint!=null?[[-65,55],[65,55],[-65,-55],[65,-55]]:[[0,0]];for(const [dx,dy]of offsets){const q={x:pad.x+dx,y:pad.y+dy},distance=dist(p,q);if(distance>maxJump541(p)||distance<C.minJump)continue;const arrival=g.elapsed+flightTime539(distance),land=landing539(g,q.x,q.y,arrival);if(!land||occupied539(g,q.x,q.y,arrival,p.playerId)||!clearFlight539(g,p,q,distance))continue;const score=dist(p,target)-dist(q,target)+(pad.checkpoint!=null?240:0)-(pad.kind==='low'?35:0)+random(g)*45;candidates.push({...q,distance,score})}}
 candidates.sort((a,b)=>b.score-a.score);const q=candidates[0];if(!q){p.brain.next=g.elapsed+200;return}const angle=Math.atan2(q.y-p.y,q.x-p.x),power=q.distance/maxJump541(p);inputTetra539(g,p,{action:'begin',angle,power});inputTetra539(g,p,{action:'release',angle,power})}
export function advanceTetra539(g,now,inputs=new Map(),auto=new Set()){if(!['countdown','play'].includes(g.phase))return;const steps=Math.min(200,Math.floor((now-g.lastAt)/C.step));for(let s=0;s<steps&&g.phase!=='result';s++){g.lastAt+=C.step;g.elapsed=g.lastAt-g.startAt;if(g.phase==='countdown'&&g.elapsed>=0){g.phase='play';g.revision++;event(g,'begin')}if(g.phase==='countdown')continue;
 const cycle=Math.floor(g.elapsed/C.waveEvery);if(cycle>g.waveCycle){g.waveCycle=cycle;event(g,'wave',{big:wave539(g.elapsed).big})}
 for(const p of g.players){const wasAuto=p.auto;p.auto=p.ai||auto.has(p.playerId);if(wasAuto!==p.auto){p.chargeAt=null;p.brain.next=g.elapsed+400;inputs.delete(p.playerId)}if(p.finishedAt!=null)continue;if(p.fallAt!=null){if(g.elapsed-p.fallAt>=C.respawn&&spawn(g,p)){p.brain.next=g.elapsed+400;event(g,'respawn',{seat:p.seat})}continue}
 const q=pose539(g,p),wave=waveAt539(g.elapsed,q.y),standing=p.padId!=null?g.course.pads[p.padId]:null;if(g.elapsed>=(p.recoverUntil563??0)&&wave.here&&!p.flight&&(!standing||standing.checkpoint==null&&standing.section>0&&(wave.big||!tip539(standing,q.x,q.y)))){fall539(g,p,'wave');continue}
 if(p.flight){if(g.elapsed-p.flight.at>=p.flight.duration)land(g,p);else{p.x=q.x;p.y=q.y}continue}
 const pad=pad539(g,standing);if(pad.submerged&&g.elapsed>=(p.recoverUntil563??0)){fall539(g,p,'tide');continue}
 if(pad.kind==='slippery'&&!tip539(pad,p.x,p.y)&&g.elapsed-p.landedAt>1000){const length=dist(p,pad)||1,x=p.x+(p.x-pad.x)/length*3.5,y=p.y+(p.y-pad.y)/length*3.5;if(!occupied539(g,x,y,g.elapsed,p.playerId)){p.x=x;p.y=y}if(!support539(pad,p.x,p.y)){fall539(g,p,'slip');continue}}
 if(p.chargeAt!=null&&g.elapsed-p.chargeAt>30000)p.chargeAt=null;
 if(p.auto){inputs.delete(p.playerId);bot539(g,p)}else{const actions=inputs.get(p.playerId)??[];while(actions.length&&actions[0].at<=g.elapsed)inputTetra539(g,p,actions.shift());if(!actions.length)inputs.delete(p.playerId)}
 }
 // Crossing jumps also collide when the bodies are at similar heights.
 for(let a=0;a<g.players.length;a++)for(let b=a+1;b<g.players.length;b++){const p=g.players[a],q=g.players[b];if(p.fallAt!=null||q.fallAt!=null||p.finishedAt!=null||q.finishedAt!=null||!p.flight&&!q.flight)continue;const u=pose539(g,p),v=pose539(g,q);if(dist(u,v)<C.body*1.2&&Math.abs(u.z-v.z)<28){if(p.flight)fall539(g,p,'collision');if(q.flight)fall539(g,q,'collision')}}
 if(g.players.every(p=>p.finishedAt!=null))finishTetra539(g,'all');else if(g.lastAt>=g.endAt)finishTetra539(g,g.firstFinish!=null?'grace':'time')}
 if(now>=g.endAt&&g.phase!=='result'){g.lastAt=now;g.elapsed=Math.min(C.duration,now-g.startAt);finishTetra539(g,g.firstFinish!=null?'grace':'time')}g.serverAt=now;g.updatedAt=now}
export function publicTetra539(g,viewerId,{frame=false}={}){return{id:g.id,code:g.code,game:'tetra',rulesVersion:4,hostId:g.hostId,phase:g.phase,revision:g.revision,serverAt:g.serverAt,elapsed:g.elapsed,startAt:g.startAt,endAt:g.endAt,firstFinish:g.firstFinish,...(!frame&&g.course?{course:copy(g.course)}:{}),padStates:{},members:g.members.map(m=>({playerId:m.playerId,name:m.name,departed:!!m.departed,choice:m.choice?{id:m.choice.id,speciesId:m.choice.speciesId}:null})),players:g.players.map(({brain,lastSeq,...p})=>({...copy(p),...(p.playerId===viewerId?{lastSeq}:{})})),events:copy(g.events),results:copy(g.results),reason:g.reason}}
export const signature539=g=>!g?null:g.phase==='lobby'?g:{id:g.id,phase:g.phase==='result'?'result':'play',members:g.members,results:g.phase==='result'?g.results:null};
