import {TETRA539 as C,clamp539,pose539,order539} from './Rules539.js';
import {renderer539,resize539,paint539,worldPoint539} from './Renderer539.js';
import {unlock539,sound539} from './Audio539.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
import {color499} from '../party/PartyColors499.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.tetraUI539??={seq:0,sound:true,seen:0,limit:24,search:'',angle:-Math.PI/2,chargeStart:null};
const me=c=>c.state?.tetra?.players.find(p=>p.playerId===c.transport.selfId),clock=c=>Date.now()+(c.offset??0);
const portrait=(c,p)=>c.sgMonster463?.(p.speciesId??p.choice?.speciesId)??'';
const head=c=>`<header class="tt-head539"><button data-party-action462="browse" aria-label="パーティーへ">‹</button><div><small>ABYSS · TETRAPOD CROSSING</small><b>因縁の決戦！テトラポット渡り</b></div><button data-tt-action="sound" aria-label="音の切り替え">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),party=c.state.party,member=g.members.find(m=>m.playerId===c.transport.selfId),pm=party?.members.find(m=>m.playerId===c.transport.selfId),host=g.hostId===c.transport.selfId,roster=c.roster().filter(m=>!u.search||(c.sgSpeciesName463?.(m.raceSpeciesId??m.speciesId)??'').includes(u.search));
 return`<section class="tt539 tt-lobby539">${head(c)}<div class="tt-cover539"><span class="tt-kicker539">より VS 因縁のテトラポット</span><h1>その一歩が、<br>因縁を越える。</h1><p>ためて、跳んで、ときどきドボン。</p><div class="tt-yori539"><span>${portrait(c,{speciesId:'myth_yori'})}</span><b>「イージー！」<small>より、懲りずに再挑戦。</small></b></div></div><div class="tt-body539"><div class="tt-facts539"><span>４人レース</span><span>最大150秒</span><span>空席はAI</span></div><div class="tt-rules539"><article><em>01</em><div><b>飛びたい方向で、長押し。</b><p>長くためるほど遠くへ。着地点の輪を合わせて、指を離すとジャンプ！</p></div></article><article><em>02</em><div><b>安全な外回り？ 危険な近道？</b><p>近道は傾く・回る・沈む足場。16秒ごとの大波では低い足場が水没！</p></div></article><article><em>03</em><div><b>落ちても、イージー！</b><p>２つの避難所を順に通ってゴールへ。落水は直前の避難所から復帰。最初のゴールから残り20秒！</p></div></article></div><h2>海を渡る相棒</h2><input name="tetraSearch539" placeholder="相棒の名前で探す" aria-label="相棒を探す" value="${esc(u.search)}"><div class="tt-roster539">${roster.slice(0,u.limit).map(m=>`<button data-tt-monster="${esc(m.id)}" aria-pressed="${member?.choice?.id===m.id}">${portrait(c,{speciesId:m.raceSpeciesId??m.speciesId})}<small>${esc(c.sgSpeciesName463?.(m.raceSpeciesId??m.speciesId)??m.speciesId)}</small></button>`).join('')}</div>${roster.length>u.limit?'<button data-tt-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="tt-error539" role="alert">${esc(c.error)}</p><button class="tt-gold539 tt-wide539" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="tt-gold539 tt-wide539" data-tt-action="start" ${!c.ready()||party.members.some(m=>!m.ready||!m.connected||m.atHome)?'disabled':''}>因縁の海へ、出発！</button>`:'<p>全員の準備ができたら、部屋主が開始します。</p>'}<p class="tt-note539">相棒の強さで速さは変わらないよ。通信切断・ホーム滞在中はAIが引き継ぎます。</p></div></section>`;
}
function play(c,g){return`<section class="tt539 tt-play539">${head(c)}<div class="tt-hud539"><div><small>あなたの順位</small><strong data-tt-rank>—<i>/ 4</i></strong></div><div class="tt-clock539"><small data-tt-timelabel>残り時間</small><strong data-tt-time>2:30</strong></div><div><small>避難所</small><strong data-tt-checkpoint>0<i>/ 2</i></strong></div></div><div class="tt-standings539">${g.players.map(p=>`<div data-tt-seat="${p.seat}" style="--seat:${color499(p.color499,p.seat).hex}"><span>${portrait(c,p)}</span><b>${esc(p.name)}<small data-tt-progress="${p.seat}">0%</small></b></div>`).join('')}</div><div class="tt-stage539" data-tt-stage><canvas data-tt-canvas role="img" aria-label="テトラポットの海。飛びたい方向で長押しして、指を離すとジャンプ。長く押すほど遠くへ跳びます。"></canvas><div class="tt-avatars539">${g.players.map(p=>`<div class="tt-runner539 ${p.playerId===c.transport.selfId?'is-self':''}" data-tt-runner="${p.seat}" style="--seat:${color499(p.color499,p.seat).hex}"><span>${portrait(c,p)}</span><b>${p.playerId===c.transport.selfId?'YOU':esc(p.name)}</b></div>`).join('')}</div><div class="tt-sea-label539"><span>THE RIVAL COAST</span><b data-tt-area>第一の海</b></div><div class="tt-wave539" data-tt-wave><span data-tt-wavetext>次の大波</span><b data-tt-waveclock>16秒</b></div><div class="tt-count539" data-tt-count><small>よりの因縁に、決着を。</small><strong data-tt-countnumber>3</strong><span>飛びたい方向で長押し → 離してジャンプ</span></div><div class="tt-notice539" data-tt-notice aria-live="polite" hidden></div><div class="tt-network539" data-tt-network hidden>再接続中… AIが引き継いでいるよ</div></div><footer class="tt-deck539"><div class="tt-charge-label539"><b data-tt-status>飛びたい方向で長押し</b><span data-tt-powertext>POWER 0%</span></div><div class="tt-powertrack539"><i data-tt-power></i><span></span><span></span></div><div class="tt-control539"><button class="tt-turn539" data-tt-action="left" aria-label="左へ照準を回す">↖</button><button class="tt-jump539" data-tt-jump><b>長押し → 離してジャンプ</b><small data-tt-tip>海の画面でも操作できるよ</small></button><button class="tt-turn539" data-tt-action="right" aria-label="右へ照準を回す">↗</button></div><p class="tt-bottom539"><span data-tt-advice>白い足場は安全 · 光る避難所で復帰地点を更新</span><button data-tt-action="cancel" aria-label="ためを取り消す">ため解除</button></p></footer></section>`}
function result(c,g){const win=g.results.filter(r=>r.rank===1),winner=g.players[win[0].seat],mine=g.results.find(r=>r.playerId===c.transport.selfId);return`<section class="tt539 tt-result539">${head(c)}<div class="tt-result-hero539"><small>THE RIVAL COAST · RESULT</small><h1>${winner.finishedAt!=null?'因縁を、越えた！':'荒波の決着！'}</h1><p>${winner.finishedAt!=null?esc(win.map(w=>w.name).join(' ＆ '))+' が１位でゴール！':'時間切れ。避難所・最遠到達地点・落水数で順位決定'}</p><div class="tt-podium539">${[1,0,2].map(index=>{const row=g.results[index],p=g.players[row.seat];return`<div class="tt-place539 tt-place-${index}"><span>${portrait(c,p)}</span><b>${esc(row.name)}</b><div><strong>${row.rank}</strong><small>${row.finishedAt!=null?(row.finishedAt/1000).toFixed(2)+'秒':row.progress+'%'}</small></div></div>`}).join('')}</div><div class="tt-result-ribbon539">${mine?.rank===1?'VICTORY · お見事！':mine?`あなたは ${mine.rank} 位！`:'４人の挑戦、決着！'} <span>より「イージー！」</span></div></div><div class="tt-body539">${resultActions490(c)}<div class="tt-results539">${g.results.map(row=>`<article class="${row.playerId===c.transport.selfId?'is-self':''}"><strong>${row.rank}</strong><span>${portrait(c,g.players[row.seat])}</span><div><b>${esc(row.name)}</b><small>成功 ${row.landings}回 · 落水 ${row.falls}回</small></div><b>${row.finishedAt!=null?(row.finishedAt/1000).toFixed(2)+'秒':row.progress+'%'}<small>${row.finishedAt!=null?'GOAL':'最遠到達'}</small></b></article>`).join('')}</div><p class="tt-note539">${g.reason==='grace'?'最初のゴールから20秒で終了。':g.reason==='all'?'全員がゴール！':'150秒で終了。'} 同タイムのゴールは同順位です。</p></div></section>`}
export function tetraView539(c){const g=c.state.tetra,u=ui(c);if(u.gameId!==g.id)Object.assign(u,{gameId:g.id,seq:0,seen:0,limit:24,search:'',angle:-Math.PI/2,chargeStart:null,notice:null,pendingRelease:null});return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
export function tetraReceive539(c){const p=me(c);if(!p)return;const u=ui(c);u.seq=Math.max(u.seq,p.lastSeq??0);if(p.flight||p.fallAt!=null||p.finishedAt!=null||p.auto||c.state.tetra.phase!=='play'){u.chargeStart=null;u.pendingRelease=null}if(u.pendingRelease&&((p.lastSeq??0)>=u.pendingRelease.seq||clock(c)-u.pendingRelease.at>1300))u.pendingRelease=null;if(p.chargeAt!=null&&u.chargeStart==null&&!u.pendingRelease&&!p.auto&&u.recoveredCharge!==p.chargeAt){u.recoveredCharge=p.chargeAt;send(c,'cancel')}}
export function tetraFrame539(c,m){if(m.selfId!==c.transport.selfId||!c.state?.tetra||m.tetra?.id!==c.state.tetra.id||m.tetra.serverAt<c.state.tetra.serverAt)return;const old=c.state.tetra;c.offset=m.serverNow-Date.now();c.state.tetra={...m.tetra,course:m.tetra.course??old.course};tetraReceive539(c);if((old.phase==='result')!==(m.tetra.phase==='result'))c.render()}
function send(c,action){const g=c.state?.tetra,u=ui(c);if(!g||g.phase!=='play'||!me(c)||!c.ready())return false;return c.raw('tetraInput539',{gameId:g.id,action,seq:++u.seq,angle:u.angle})}
function begin(c){const p=me(c),u=ui(c);if(!p||p.flight||p.fallAt!=null||p.finishedAt!=null||p.auto||u.chargeStart!=null||u.pendingRelease||c.state.tetra.phase!=='play'||!c.ready())return false;unlock539(u);u.chargeStart=clock(c);if(!send(c,'begin')){u.chargeStart=null;return false}return true}
function release(c){const u=ui(c);if(u.chargeStart==null)return;const held=clock(c)-u.chargeStart;u.chargeStart=null;if(held<60)send(c,'cancel');else if(send(c,'release'))u.pendingRelease={seq:u.seq,at:clock(c)};}
function cancel(c){const u=ui(c);if(u.chargeStart!=null){u.chargeStart=null;send(c,'cancel')}u.pointer=null;}
const put=(e,text)=>{if(e&&e.textContent!==String(text))e.textContent=String(text)};
function paint(c){const g=c.state.tetra,u=ui(c),n=u.nodes,p=me(c),at=clock(c),data=paint539(u.renderer,g,c.transport.selfId,u,at,u.reduced);if(!data)return;const {elapsed,wave,charging}=data,remaining=Math.max(0,Math.ceil((g.endAt-at)/1000)),rank=order539(g).findIndex(q=>q.playerId===c.transport.selfId)+1,power=charging?clamp539((at-u.chargeStart)/C.charge,0,1):0;
 put(n.rank,p?`${rank} / 4`:'観戦');put(n.time,g.phase==='countdown'?'—':`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`);put(n.timelabel,g.firstFinish!=null?'ゴール締切':'残り時間');put(n.checkpoint,`${Math.min(2,p?.checkpoint??0)} / 2`);put(n.area,['第一の海 · はじまりの波','第二の海 · 回る因縁','第三の海 · 最後の一跳び','因縁、決着！'][p?.checkpoint??0]);n.count.hidden=g.phase!=='countdown';put(n.countnumber,Math.max(1,Math.ceil((g.startAt-at)/1000)));n.network.hidden=c.connected();n.wave.classList.toggle('is-danger',wave.warning||wave.active);put(n.wavetext,wave.active?'大波！ 低い足場が水没':wave.warning?'大波が来る！':'次の大波');put(n.waveclock,wave.active?'高い足場へ':`${Math.ceil(wave.next/1000)}秒`);
 n.power.style.transform=`scaleX(${power})`;put(n.powertext,`POWER ${Math.round(power*100)}%`);n.jump.classList.toggle('is-charging',charging);n.jump.disabled=!p||!c.ready()||g.phase!=='play'||!!p.flight||p.fallAt!=null||p.finishedAt!=null||p.auto;
 put(n.status,!p?'４人のレースを観戦中':p.finishedAt!=null?'ゴール！ みんなを応援しよう':p.fallAt!=null?'ドボン！ 避難所からもう一度':p.flight?'ジャンプ！':charging?power>=1?'最大パワー！ 離すとジャンプ':'着地点の輪を足場に合わせよう':'飛びたい方向で長押し');put(n.tip,charging?'指を枠の外へ離すとキャンセル':'↖ ↗ で向き調整 · このボタンでも跳べる');put(n.advice,wave.active?'白い足場と避難所は、大波でも沈まないよ':wave.warning?'あと少しで水没！ 近道から高い足場へ':'白い足場は安全 · 光る避難所で復帰地点を更新');
 for(const player of g.players){const index=player.seat,point=u.renderer.points.find(q=>q.seat===index),runner=u.runners[index];if(point){runner.hidden=!point.visible||point.fall>=1;runner.style.transform=`translate(${point.x}px,${point.y}px) scale(${point.scale*(1-point.fall*.6)})`;runner.style.opacity=String(1-point.fall);runner.style.zIndex=String(Math.round(point.y+1000))}put(u.progress[index],player.finishedAt!=null?'GOAL':player.fallAt!=null?'ドボン！':`${Math.round((5400-player.bestY)/5040*100)}%`)}
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(elapsed-e.at>1400)continue;if(e.seat===p?.seat||['wave','begin','finish','goal'].includes(e.type))sound539(u,e.type);if(e.type==='checkpoint'&&e.seat===p?.seat)u.notice={text:`避難所 ${Math.min(2,e.checkpoint)} に到着！`,until:at+1600};if(e.type==='goal')u.notice={text:`${g.players[e.seat].name} がゴール！`,until:at+2200};if(e.type==='begin')u.notice={text:'より「イージー！ いくぞ！」',until:at+1600};}
 put(n.notice,u.notice&&at<u.notice.until?u.notice.text:'');n.notice.hidden=!n.notice.textContent;if(u.chargeStart!=null&&at-u.chargeStart>3400)cancel(c);
}
export function tetraBefore539(c){const u=c.tetraUI539;if(!u)return;u.cleanup?.();u.cleanup=null;if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.root=null;u.renderer=null;}
export function tetraDispose539(c){tetraBefore539(c);if(c.tetraUI539?.audio){c.tetraUI539.audio.close()?.catch(()=>{});c.tetraUI539.audio=null}}
export function tetraAfter539(c){const root=c.root?.querySelector('.tt-play539');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const q=k=>root.querySelector(`[data-tt-${k}]`);u.nodes=Object.fromEntries(['stage','canvas','rank','time','timelabel','checkpoint','area','count','countnumber','network','wave','wavetext','waveclock','power','powertext','jump','status','tip','advice','notice'].map(k=>[k,q(k)]));u.runners=[...root.querySelectorAll('[data-tt-runner]')];u.progress=[...root.querySelectorAll('[data-tt-progress]')];u.renderer=renderer539(u.nodes.canvas);const abort=new AbortController(),on=(el,name,fn,options={})=>el.addEventListener(name,fn,{...options,signal:abort.signal}),resize=()=>resize539(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const unlockZoom=lockPlayZoom498(root);let lastAim=0;
 const aim=e=>{const p=me(c);if(!p||!u.renderer)return;const b=u.nodes.canvas.getBoundingClientRect(),target=worldPoint539(u.renderer,e.clientX-b.left,e.clientY-b.top),pos=pose539(c.state.tetra,p);if(Math.hypot(target.x-pos.x,target.y-pos.y)>25)u.angle=Math.atan2(target.y-pos.y,target.x-pos.x)};
 for(const element of [u.nodes.canvas,u.nodes.jump]){on(element,'pointerdown',e=>{if(e.button!==0||u.pointer!=null)return;e.preventDefault();if(element===u.nodes.canvas)aim(e);if(begin(c)){u.pointer=e.pointerId;element.setPointerCapture(e.pointerId)}});on(element,'pointermove',e=>{if(e.pointerId!==u.pointer||element!==u.nodes.canvas)return;e.preventDefault();aim(e);if(Date.now()-lastAim>80){lastAim=Date.now();send(c,'aim')}});on(element,'pointerup',e=>{if(e.pointerId!==u.pointer)return;e.preventDefault();const b=element.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)cancel(c);else{if(element===u.nodes.canvas)aim(e);release(c)}u.pointer=null});on(element,'pointercancel',()=>cancel(c));on(element,'lostpointercapture',()=>{if(u.pointer!=null)cancel(c)});on(element,'contextmenu',e=>e.preventDefault())}
 on(document,'keyup',e=>{if(e.code==='Space'&&u.keyboard){e.preventDefault();u.keyboard=false;release(c)}});on(window,'blur',()=>{u.keyboard=false;cancel(c)});
 const tick=()=>{u.raf=null;if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick)};on(document,'visibilitychange',()=>{if(document.hidden){cancel(c);if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{})}else{c.refresh?.();if(u.raf==null)tick()}});
 u.cleanup=()=>{cancel(c);u.keyboard=false;abort.abort();observer.disconnect();unlockZoom()};tetraReceive539(c);tick();
}
export function tetraClick539(c,b){const d=b.dataset,g=c.state?.tetra;if(!g||!Object.keys(d).some(k=>k.startsWith('tt')))return false;const u=ui(c);unlock539(u);if(d.ttMonster)c.raw('tetra539',{gameId:g.id,kind:'select',monsterId:d.ttMonster});if(d.ttAction==='start')c.raw('tetra539',{gameId:g.id,kind:'start'});if(d.ttAction==='more'){u.limit+=24;c.render()}if(d.ttAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock539(u)}if(d.ttAction==='cancel')cancel(c);if(d.ttAction==='left'||d.ttAction==='right'){u.angle=clamp539(u.angle+(d.ttAction==='left'?-.15:.15),-Math.PI,0);if(u.chargeStart!=null)send(c,'aim')}return true}
export function tetraInput539(c,e){if(e.name!=='tetraSearch539')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function tetraKey539(c,e){if(!c.root?.querySelector('.tt-play539')||/INPUT|TEXTAREA/.test(e.target?.tagName))return false;const u=ui(c);if(e.code==='Space'){e.preventDefault();if(!e.repeat){u.keyboard=begin(c)}return true}if(e.key==='Escape'){cancel(c);return true}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();u.angle=clamp539(u.angle+(e.key==='ArrowLeft'?-.12:.12),-Math.PI,0);if(u.chargeStart!=null)send(c,'aim');return true}return false}
