import fs from 'node:fs';import assert from 'node:assert/strict';import{spawn}from'node:child_process';import path from 'node:path';
const{chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const server=spawn(process.execPath,['tools/build439/preview-server.mjs'],{stdio:['ignore','pipe','inherit']});let browser;const errors=[],missing=new Set(),checks=[],metrics={};
try{
 await new Promise((r,j)=>{const t=setTimeout(()=>j(Error('server timeout')),20000);server.stdout.on('data',b=>{if(String(b).includes('Preview http')){clearTimeout(t);r();}});server.on('exit',c=>j(Error('server exit '+c)));});
 const fonts=path.resolve('../browser432/fonts');browser=await chromium.launch({executablePath:path.resolve('../browser432/chromium'),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,FONTCONFIG_FILE:fonts+'/local.conf',FONTCONFIG_PATH:fonts}});
 const page=await browser.newPage({viewport:{width:393,height:720},isMobile:true,reducedMotion:'reduce'});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.routeWebSocket('**/*',s=>s.close());page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()===404)missing.add(new URL(r.url()).pathname)});await page.goto('http://127.0.0.1:8439');await page.waitForFunction(()=>window.ready439);
 const shot=async name=>page.screenshot({path:`docs/build439/${name}.png`});
 for(const size of [{width:393,height:720},{width:375,height:540},{width:430,height:760},{width:1280,height:800}]){
  await page.setViewportSize(size);
  for(const kind of ['growth','gacha','ranking','power','exchange','forge']){
   await page.evaluate(k=>qa439[k](),kind);await page.waitForTimeout(80);await page.evaluate(()=>document.fonts.ready);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,kind+' horizontal overflow');checks.push(`${kind}: no horizontal overflow at ${size.width}`);
   if(kind==='growth'){
    const layout=await page.evaluate(()=>{const sheet=[...document.styleSheets].find(s=>s.href?.includes('build439-growth'));const geo=()=>[...document.querySelectorAll('.monster-growth-screen .topbar,.monster-switcher,.monster-growth-screen .panel,.growth-quick-actions')].map(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,c:e.className};});const after=geo();document.querySelector('[data-capture-training439]').hidden=true;sheet.disabled=true;const before=geo();sheet.disabled=false;document.querySelector('[data-capture-training439]').hidden=false;return{before,after};});metrics['growth-'+size.width]=layout;assert.ok(layout.after.every((r,i)=>['x','y','w','h'].every(k=>Math.abs(r[k]-layout.before[i][k])<1)),JSON.stringify(layout));checks.push('growth frame geometry preserved at '+size.width);
    await page.locator('[data-capture-training439]').scrollIntoViewIfNeeded();const fit=await page.locator('[data-capture-training439]').evaluate(b=>{const r=b.getBoundingClientRect(),p=b.closest('.compact-affection-panel').getBoundingClientRect(),bar=b.closest('.compact-affection-panel').querySelector('.affection-meter').getBoundingClientRect();return{r:{top:r.top,bottom:r.bottom,left:r.left,right:r.right},barTop:bar.top,inside:r.left>=p.left&&r.right<=p.right&&r.bottom<=bar.top};});assert.ok(fit.inside,JSON.stringify(fit));checks.push('training button fits existing affection space at '+size.width);
   }
   if(kind==='ranking'){
    const fit=await page.locator('.raid-ranking-row439').evaluateAll(es=>es.map(e=>{const row=e.getBoundingClientRect(),num=e.querySelector('.power-ranking-position').getBoundingClientRect(),score=e.querySelector('strong').getBoundingClientRect(),name=e.querySelector('.power-ranking-identity').getBoundingClientRect();return{inside:num.left>=row.left&&num.right<=row.right&&num.top>=row.top&&num.bottom<=row.bottom,scoreFits:score.right<=row.right&&score.left>=name.right-1,overflow:e.scrollWidth>e.clientWidth+1};}));metrics['ranking-'+size.width]=fit;assert.ok(fit.every(x=>x.inside&&x.scoreFits&&!x.overflow),JSON.stringify(fit));checks.push('rank digits and 12-digit damage fit at '+size.width);
   }
   if(size.width===393){if(kind==='growth'){await shot('growth-training-entry-393');await page.locator('.monster-switcher').scrollIntoViewIfNeeded();await page.evaluate(()=>{document.querySelectorAll('*').forEach(e=>{if(e.scrollTop)e.scrollTop=0;});scrollTo(0,0);});}await shot(kind+'-393');}
  }
 }
 await page.setViewportSize({width:393,height:720});await page.evaluate(()=>qa439.gacha());assert.equal(await page.locator('#gachaCustomCount').getAttribute('max'),'234');await page.locator('#gachaCustomCount').fill('235');assert.ok(await page.locator('[data-gacha-custom]').isDisabled());await page.locator('#gachaCustomCount').fill('234');assert.equal(await page.locator('[data-gacha-custom]').isDisabled(),false);checks.push('input upper bound and invalid count disabled');
 for(const fail of [false,true]){const result=await page.evaluate(f=>qa439.summon(234,f),fail);if(fail)assert.equal(result.after,result.before,'gacha save failure rollback');else{assert.equal(result.drawn.length,234);assert.ok(result.drawn.every(r=>r.level>=1&&r.level<=150));assert.equal(JSON.parse(result.after).player.crystals,12);}checks.push(fail?'gacha save failure restores all costs and grants':'234 summons charge 10530 with levels 1–150');}
 await page.evaluate(()=>qa439.growth());await page.locator('[data-capture-training439]').click();await page.locator('.capture-training-modal439 [data-modal-primary]').click();assert.equal(await page.evaluate(()=>qa439.state().inventory.captureCrystals),1602);assert.equal(await page.evaluate(()=>qa439.state().monsters.at(-1).affection),20);await page.locator('[data-training-kind439="skill"]').click();await shot('training-393');await page.locator('.capture-training-modal439 [data-modal-primary]').click();assert.equal(await page.evaluate(()=>qa439.state().inventory.captureCrystals),1502);checks.push('affection and skill training spend through visible UI');
 await page.evaluate(()=>qa439.failSave(true));const prior=await page.evaluate(()=>JSON.stringify(qa439.state()));await page.locator('.capture-training-modal439 [data-modal-primary]').click();assert.equal(await page.evaluate(()=>JSON.stringify(qa439.state())),prior);checks.push('training save failure restores progression and crystal stock');
 await page.evaluate(()=>qa439.exchange());await page.locator('[data-floor-boss-exchange="weapon"]').click();await shot('exchange-confirm-393');await page.locator('.floor-boss-exchange-confirm-modal [data-modal-primary]').click();assert.equal(await page.evaluate(()=>qa439.state().inventory.abyssKeys),310);checks.push('floor weapon UI spends 5 keys');
 await page.evaluate(()=>qa439.exchange(4));assert.equal(await page.locator('[data-floor-boss-exchange]:disabled').count(),4);checks.push('key shortage disables every floor exchange');
 await page.evaluate(()=>qa439.roles());await page.locator('[data-role-guide436]').click();await page.locator('[data-role-detail436]').first().click();await shot('role-detail-393');const target=await page.evaluate(()=>document.querySelector('.role-detail436 header p').textContent);await page.locator('[data-role-equip439]').first().click();await page.locator('[data-role-slot439="0"]').click();assert.ok(await page.locator('.role-detail436 .role-ready436').filter({hasText:'スキル設定中'}).count());checks.push('recommendation sets a chosen skill slot and refreshes readiness');
 // Pick a reserve recommendation, then select exactly which party member leaves.
 await page.locator('.role-guide-modal436').last().locator('[data-modal-primary]').click();const reserveButton=page.locator('.role-result436').filter({hasNotText:'編成中'}).locator('[data-role-detail436]').first();await reserveButton.click();await page.locator('[data-role-party439]').click();const outgoing=await page.locator('[data-role-replace439]').first().getAttribute('data-role-replace439');await page.locator('[data-role-replace439]').first().click();assert.equal(await page.locator('[data-role-party439]').textContent(),'編成中');assert.equal(await page.evaluate(id=>qa439.state().party.includes(id),outgoing),false);assert.equal(await page.evaluate(()=>qa439.state().party.length),4);checks.push('reserve role candidate replaces the chosen member in a full party');
 await page.evaluate(()=>qa439.roles(true));await page.locator('[data-role-guide436]').click();await page.locator('[data-role-detail436]').first().click();assert.equal(await page.locator('[data-role-equip439],[data-role-party439]').count(),0);checks.push('exploration guide remains read-only');
 await page.evaluate(()=>qa439.power());assert.equal(await page.locator('button[data-power-record-tab="ranking"]').getAttribute('aria-selected'),'true');assert.ok(await page.evaluate(()=>window.requestedRank439));checks.push('power record opens ranking and requests current data');
 await page.evaluate(()=>qa439.results());await page.waitForTimeout(850);assert.equal(await page.locator('.gacha-result-card').count(),50);await page.locator('[data-summon-page439="1"]').click();assert.equal(await page.locator('.gacha-result-card').count(),50);await page.locator('[data-summon-page439="1"]').click();assert.equal(await page.locator('.gacha-result-card').count(),20);checks.push('large summon result list paginates all items');
 assert.deepEqual(errors,[]);assert.deepEqual([...missing],[]);console.log(JSON.stringify({checks:checks.length,errors,missing:[...missing]}));
}finally{fs.writeFileSync('docs/build439/browser-result.json',JSON.stringify({checks,errors,missing:[...missing],metrics},null,2));await browser?.close();server.kill();}
