import * as R from '../../src/fishing/Rules524.js';
import * as C from '../../src/fishing/Catches525.js';
import * as V from '../../src/fishing/View524.js';
const root=document.querySelector('#app'),members=['あなた','ちょ','追い風オオカミ','骨までラッキー'].map((name,i)=>({playerId:'p'+i,name,choice:{id:'m'+i,speciesId:['slime','goblin','wolf','skeleton'][i]},connected:true,ready:true}));
let g,playing=true;
const c=window.c={root,transport:{selfId:'p0'},state:{},offset:0,error:'',roster:()=>members.map(m=>m.choice),sgSpeciesName463:id=>id,sgMonster463:id=>`<span class="sg-monster qa-portrait">${({slime:'🔵',goblin:'👺',wolf:'🐺',skeleton:'💀'})[id]??'🔵'}</span>`,connected:()=>true,ready:()=>true,render(){V.fishingBefore524(c);root.innerHTML=V.fishingView524(c);V.fishingAfter524(c)},refresh(){sync()},raw(op,p){window.sent.push({op,...p});const me=g.players[0];if(op==='fishingInput524'){if(p.cast)R.cast524(g,me,p.cast.x,p.cast.y,p.cast.bait);if(p.choice)R.choose524(g,me,p.choice);me.reel=p.reel===true;sync()}return true}};
window.sent=[];
const sync=()=>{c.state.fishing=R.publicFishing524(g);c.state.party={id:'p',game:'fishing',hostId:'p0',members};c.offset=g.lastAt-Date.now();V.fishingReceive524(c)};
window.startQA=()=>{g=R.makeFishing524({id:'qa532',code:'QA532',hostId:'p0',partyId:'p',members});R.startFishing524(g,0,531);R.advanceFishing524(g,3000);g.lord526.at=30000;sync();c.render();return true};
window.chooseQA=(id='silver')=>{const p=g.players[0],f=C.catch525(id);Object.assign(p,{mode:'choice',fish:{...f,value:f.base,rhythm:0,chainDepth525:0},choiceUntil:g.elapsed+5000});sync()};
window.modeQA=()=>g.players[0].mode;
window.stateQA=()=>structuredClone(g);
window.elapseQA=ms=>{for(let end=g.lastAt+ms;g.lastAt<end&&g.phase==='play';)R.advanceFishing524(g,g.lastAt+50);sync()};
window.lordQA=()=>{g.lord526.at=g.elapsed+50;window.elapseQA(50);const p=g.players[0],s=g.shoals.find(s=>s.tier===4),pos=R.fishPose524(s,g.elapsed);p.mode='idle';R.cast524(g,p,pos.x,pos.y);while(p.mode==='waiting')window.elapseQA(50);p.progress=.3;p.tension=.9999;p.reel=true;R.fight524(g,p);sync();return g.lord526.phase};
window.lobbyQA=()=>{playing=false;g.phase='lobby';sync();c.render()};
window.setPlayingQA=v=>playing=v;
root.addEventListener('click',e=>{const b=e.target.closest('button');if(b)V.fishingClick524(c,b)});
window.disposeQA=()=>{playing=false;V.fishingDispose524(c)};
setInterval(()=>{if(!playing||g.phase!=='play')return;R.advanceFishing524(g,g.lastAt+50);sync()},50);
window.startQA();window.qaReady=true;
