import {ELEVATOR580,validElevator580} from '../elevator580/Rules580.js';
import {validLava580} from '../lava580/Rules580.js';
import {board580,resize580,paint580,PADS580} from './Board580.js';
import {esc563 as esc,color563 as color,put563 as put,clock563 as clock,avatar563,header563,lobby563,result563,scoreCards563} from '../party/Arcade563.js';
import {unlock543,sound543} from '../cart/Audio543.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const game=c=>c.state?.elevator??c.state?.lava,ui=c=>c.arcadeUI580??={seq:0,sound:true,seen:0,limit:24,search:''},me=c=>game(c)?.players.find(p=>p.playerId===c.transport.selfId);
const options={
 elevator:{prefix:'a580',title:'魔王のエレベーター',sub:'GREEDY ELEVATOR',cover:new URL('../../assets/elevator580/shaft.webp',import.meta.url).href,hero:'そのお宝、<br>持って帰れる？',rule:'左右になぞって拾う → 危なくなったら降りて確保！',detail:'落ちてくるお宝を取り合う３便勝負。金貨25点・宝石60点・金塊100点。拾うほどカゴが重くなり、きしみゲージが上昇！「降りて確保」で得点を持ち帰ろう。10階まで残れば＋200点。カゴが壊れると、その便の持ち分は０点。爆弾はカゴを揺らし、近くの人が最大40点ロスト！',players:'４人対戦 · ３便 · 空席はAI',search:'arcadeSearch580'},
 lava:{prefix:'a580',title:'ぐつぐつ！溶岩ステップ',sub:'LAVA STEP',cover:new URL('../../assets/lava580/caldera.webp',import.meta.url).href,hero:'どこへ跳ぶ？<br>欲ばる？ 逃げる？',rule:'足場をタップ。赤い２つのうち、１つが噴火！',detail:'５つの足場から１つを選ぼう。赤い「危険」２つのうち１つが噴火！ 安全な足場は100点、危険をくぐり抜ければ180点、お宝の足場ならさらに＋100点。同じ足場の人で得点を山分け。選択は締切まで自分だけに見えるよ。落ちても次の回に復帰。全８回、最後の２回は得点２倍！',players:'４人対戦 · ８回戦 · 空席はAI',search:'arcadeSearch580'}
};
function play(c,g){const o=options[g.game],elevator=g.game==='elevator';return `<section class="arc563 arc-play563 a580-play a580-${g.game}">${header563(c,ui(c),'a580',o.title,o.sub)}${scoreCards563(c,g)}<div class="a580-mission"><div><small data-a580-round></small><b data-a580-mission></b></div><strong data-a580-time></strong></div>${elevator?'<div class="a580-load"><span>カゴのきしみ</span><div role="meter" aria-label="カゴのきしみ" aria-valuemin="0" aria-valuemax="100" data-a580-meter><i data-a580-fill></i></div><b data-a580-load></b></div>':''}<div class="a580-stage" data-a580-stage tabindex="0" role="group" aria-label="${elevator?'左右キーで移動、スペースで得点確保':'１から５キーで足場を選択'}"><div class="a580-backdrop"></div>${!elevator?`<div class="a580-pads">${PADS580.map(([x,y],i)=>`<button class="a580-pad" data-a580-pad="${i}" style="left:${x*100}%;top:${y*100}%" aria-label="足場${i+1}"><small data-a580-risk="${i}"></small><b>${i+1}</b><span data-a580-value="${i}"></span><i data-a580-treasure="${i}" hidden>◆</i></button>`).join('')}</div>`:''}<canvas data-a580-canvas aria-hidden="true"></canvas><div class="a580-pawns">${g.players.map(p=>`<div class="a580-pawn" data-a580-pawn="${p.seat}" style="--player:${color(p)}"><span>${avatar563(c,p)}</span><b>${p.playerId===c.transport.selfId?'YOU':esc(p.name)}</b><small data-a580-haul="${p.seat}"></small></div>`).join('')}</div><div class="a580-call" data-a580-call role="status" aria-live="polite" hidden></div><div class="arc-count563" data-a580-count hidden></div><div class="arc-network563" data-a580-network hidden>再接続中 · AIが引き継いでいます</div></div><footer class="a580-control"><b data-a580-help></b>${elevator?'<div class="a580-bankrow"><label><span>← 左右になぞって拾う →</span><input data-a580-position name="elevatorPosition580" type="range" min="8" max="92" value="50" aria-label="カゴの中を左右に移動"></label><button class="arc-gold563" data-a580-action="bank">降りて確保！<strong data-a580-bank>0点</strong></button></div><small>金貨25 · 宝石60 · 金塊100 · 爆弾はよけよう</small>':'<div class="a580-choices" aria-label="足場を選ぶ">'+PADS580.map((_,i)=>`<button data-a580-choice="${i}" aria-pressed="false">${i+1}</button>`).join('')+'</div><small data-a580-selection>締切まで選び直せるよ。選択は自分だけに見えます。</small>'}</footer></section>`;}
export function arcadeView580(c){const g=game(c),u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,limit:24,search:'',previous:null,notice:null,pending:null,selection:null});const o=options[g.game];if(g.rules580!==1)return '<section class="arc563">本体とサーバーをBuild580へ更新してください。</section>';return g.phase==='lobby'?lobby563(c,g,u,o):g.phase==='result'?result563(c,g,u,{...o,caption:g.winnerIds.includes(c.transport.selfId)?'お宝、いただき！':'勝負あり！',stats:p=>g.game==='elevator'?`確保 ${p.escapes}便 · 最上階 ${p.tops}便 · 落下 ${p.falls}便`:`生還 ${p.survived}回 · お宝 ${p.treasures}回 · 落下 ${p.falls}回`}):play(c,g);}
export function arcadeReceive580(c){const g=game(c);if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.pending&&(p?.lastSeq>=u.pending.seq||clock(c)-u.pending.at>1200))u.pending=null;if(u.round!==g.round){u.round=g.round;u.selection=null;u.pending=null;}u.receivedAt=performance.now();}
export function arcadeFrame580(c,m){const n=m.elevator??m.lava,g=game(c);if(m.selfId!==c.transport.selfId||!g||n?.id!==g.id||n.serverAt<g.serverAt)return;ui(c).previous=g;c.offset=m.serverNow-Date.now();c.state[n.game]={...g,...n};arcadeReceive580(c);if((g.phase==='result')!==(n.phase==='result'))c.render();}
function send(c,action,target){const g=game(c),u=ui(c),p=me(c),m={action,target};if(!c.ready()||!g||!(g.game==='elevator'?validElevator580:validLava580)(g,p,m,clock(c)))return false;unlock543(u);const seq=++u.seq,sent=c.raw(g.game+'Input580',{gameId:g.id,seq,round:g.round,...m});if(sent!==false){u.pending={seq,at:clock(c)};if(action==='choose')u.selection=target;}return sent!==false;}
function paint(c){
 const g=game(c),u=ui(c),p=me(c),n=u.nodes,at=clock(c),elevator=g.game==='elevator';if(!g?.players.length)return;
 paint580(u.renderer,g,c.transport.selfId,u,at);
 const waiting=g.phase==='countdown',over=g.phase==='roundEnd',reveal=g.stage==='reveal',left=Math.max(0,(g.deadline-at)/1000);
 put(n.round,elevator?`第${g.round}便 / ３便 · ${g.floor}階`:`第${g.round}回 / ８回${g.multiplier===2?' · 得点２倍！':''}`);
 put(n.time,waiting?'出発！':over?'次の便へ':elevator?Math.ceil(left)+'秒':reveal?'噴火！':left.toFixed(1)+'秒');
 put(n.mission,elevator?(g.collapseAt?'壊れる！ 降りて確保！':g.floor>=8?'最上階なら＋200点！':'拾うほど重くなる！'):reveal?'運命のジャンプ！':'赤い２つのどちらかが噴火！');
 for(const player of g.players){const q=u.renderer.points.find(v=>v.seat===player.seat),el=u.pawns[player.seat];if(q){el.style.transform=`translate(${q.x}px,${q.y}px)`;el.classList.toggle('is-fallen',q.status==='fallen');el.classList.toggle('is-banked',q.status==='banked');}put(u.scores[player.seat],player.score+'点');put(u.status[player.seat],elevator?(player.status==='riding'?'持ち分 '+player.haul:player.status==='fallen'?'この便は０点':'確保 +'+player.banked):reveal?(player.out?'落下…次で復帰！':'+'+player.gain+'点'):(player.auto?'AI':'選択はひみつ'));put(u.hauls[player.seat],elevator?(player.status==='riding'?player.haul+'点':player.status==='fallen'?'落下！':'確保！'):reveal?(player.out?'あつっ！':'+'+player.gain):player.playerId===c.transport.selfId?'あなた':'');}
 if(elevator){const stress=Math.round(g.stress??0),riding=p?.status==='riding';n.fill.style.transform=`scaleX(${stress/100})`;n.meter.setAttribute('aria-valuenow',stress);put(n.load,stress>=75?'限界！':stress>=45?'重たい':'余裕');u.root.classList.toggle('is-danger',stress>=75);put(n.bank,p?.haul+'点');n.bankButton.disabled=!riding||g.phase!=='play'||!c.ready();n.position.disabled=n.bankButton.disabled;if(!u.pointer)n.position.value=(p?.target??.5)*100;put(n.help,!p?'観戦中 · 次の試合から参加':over?(g.reason==='collapse'?'カゴが落ちたー！':g.reason==='top'?'最上階に到着！ ＋200点':'全員、無事に脱出！'):!riding?'得点確保！ 仲間の運命を見届けよう':g.collapseAt?'今すぐ降りる？ 最後まで粘る？':'左右になぞって、お宝を取ろう！');}
 else{
  const selected=u.pending?u.selection:p?.target,enabled=g.phase==='play'&&g.stage==='choose'&&!!p&&c.ready();
  for(let i=0;i<5;i++){const danger=g.danger.includes(i),treasure=g.treasure===i,pad=u.pads[i];pad.disabled=!enabled;pad.classList.toggle('is-danger',danger);pad.classList.toggle('is-erupted',reveal&&g.eruption===i);pad.setAttribute('aria-pressed',selected===i);u.choices[i].disabled=!enabled;u.choices[i].setAttribute('aria-pressed',selected===i);u.choices[i].classList.toggle('is-danger',danger);put(u.risks[i],danger?'危険':'安全');const points=((danger?180:100)+(treasure?100:0))*g.multiplier;put(u.values[i],points+'点');u.treasures[i].hidden=!treasure;pad.setAttribute('aria-label',`足場${i+1}、${danger?'噴火の可能性あり':'安全'}、${points}点を人数で山分け${treasure?'、お宝あり':''}`);}
  put(n.help,!p?'観戦中 · 次の試合から参加':reveal?(p.out?'あつっ！ 次の回で取り返そう！':`生還！ ＋${p.gain}点`):selected==null?'足場を１つタップして選ぼう！':`足場${selected+1}を選択中 · 変更OK`);put(n.selection,reveal?'同じ足場の仲間と点を山分け。':g.multiplier===2?'ラスト２回は得点２倍。逆転を狙え！':'選択は締切まで自分だけに見えます。');
 }
 n.count.hidden=!waiting;if(waiting)put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000)));
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(at-e.at>1200)continue;const who=g.players[e.seat],name=who?.playerId===c.transport.selfId?'あなた':who?.name;let message='';if(e.type==='bank')message=name+'、'+e.value+'点を確保！';if(e.type==='alarm')message='カゴが壊れる！';if(e.type==='relief')message='軽くなった！ 持ちこたえた！';if(message)u.notice={message,until:at+1400};sound543(u,({catch:'score',bank:'park',blast:'bump',alarm:'edge',start:'go',roundEnd:'fall',eruption:'spring'})[e.type]);}
 n.call.hidden=!u.notice||at>u.notice.until;if(!n.call.hidden)put(n.call,u.notice.message);n.network.hidden=c.connected();
}
export function arcadeBefore580(c){const u=c.arcadeUI580;if(!u)return;u.cleanup?.();u.cleanup=null;cancelAnimationFrame(u.raf);u.raf=null;u.root=null;u.pointer=null;}
export function arcadeDispose580(c){arcadeBefore580(c);c.arcadeUI580?.audio?.close()?.catch(()=>{});if(c.arcadeUI580)c.arcadeUI580.audio=null;}
export function arcadeAfter580(c){
 const root=c.root?.querySelector('.a580-play');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 u.nodes=Object.fromEntries(['stage','canvas','round','time','mission','meter','fill','load','help','bank','position','selection','count','call','network'].map(k=>[k,root.querySelector(`[data-a580-${k}]`)]));u.nodes.bankButton=root.querySelector('[data-a580-action="bank"]');
 for(const [key,selector] of [['pawns','[data-a580-pawn]'],['scores','[data-arc-score]'],['status','[data-arc-status]'],['hauls','[data-a580-haul]'],['pads','[data-a580-pad]'],['choices','[data-a580-choice]'],['risks','[data-a580-risk]'],['values','[data-a580-value]'],['treasures','[data-a580-treasure]']])u[key]=[...root.querySelectorAll(selector)];
 u.renderer=board580(u.nodes.canvas);const abort=new AbortController(),on=(el,type,fn)=>el.addEventListener(type,fn,{signal:abort.signal}),resize=()=>resize580(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const zoom=lockPlayZoom498(root);
 if(game(c).game==='elevator'){
  const move=e=>{const box=u.nodes.stage.getBoundingClientRect(),target=Math.max(.08,Math.min(.92,(e.clientX-box.left)/box.width));if(performance.now()-(u.lastMove??0)>55||e.type!=='pointermove'){u.lastMove=performance.now();send(c,'move',target);}};
  on(u.nodes.stage,'pointerdown',e=>{if(e.isPrimary===false||e.button>0)return;e.preventDefault();u.pointer=e.pointerId;u.nodes.stage.setPointerCapture(e.pointerId);move(e);});
  on(u.nodes.stage,'pointermove',e=>{if(u.pointer===e.pointerId){e.preventDefault();move(e);}});
  on(u.nodes.stage,'pointerup',e=>{if(u.pointer===e.pointerId){move(e);u.pointer=null;}});on(u.nodes.stage,'pointercancel',()=>{u.pointer=null;});on(u.nodes.stage,'lostpointercapture',()=>{u.pointer=null;});
 }
 const tick=()=>{if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick);};on(document,'visibilitychange',()=>{u.pointer=null;if(document.hidden){cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{});}else{c.refresh?.();if(u.raf==null)tick();}});u.cleanup=()=>{abort.abort();observer.disconnect();zoom();};arcadeReceive580(c);tick();
}
export function arcadeClick580(c,b){const d=b.dataset,g=game(c);if(!g||!Object.keys(d).some(k=>k.startsWith('a580')))return false;const u=ui(c);unlock543(u);if(d.a580Monster)c.raw(g.game+'580',{gameId:g.id,kind:'select',monsterId:d.a580Monster});if(d.a580Action==='start')c.raw(g.game+'580',{gameId:g.id,kind:'start'});if(d.a580Action==='more'){u.limit+=24;c.render();}if(d.a580Action==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock543(u);}if(d.a580Action==='bank')send(c,'bank');const pad=d.a580Pad??d.a580Choice;if(pad!=null)send(c,'choose',Number(pad));return true;}
export function arcadeInput580(c,e){if(e.name==='elevatorPosition580'){send(c,'move',Number(e.value)/100);return true;}if(e.name!=='arcadeSearch580')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true;}
export function arcadeKey580(c,e){if(!c.root?.querySelector('.a580-play')||/INPUT|TEXTAREA/.test(e.target?.tagName))return false;const g=game(c),p=me(c);if(g.game==='lava'&&/^[1-5]$/.test(e.key)){e.preventDefault();send(c,'choose',Number(e.key)-1);return true;}if(g.game==='elevator'&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();send(c,'move',Math.max(.08,Math.min(.92,(p?.target??.5)+(e.key==='ArrowLeft'?-.1:.1))));return true;}if(g.game==='elevator'&&e.code==='Space'&&e.target?.tagName!=='BUTTON'){e.preventDefault();if(!e.repeat)send(c,'bank');return true;}return false;}
