import fs from 'node:fs';import{run}from'./native-harness.mjs';
export const comps={gods:['ten_time','ten_life','ten_fate','ten_end'],poison:['ch2_mirea','ch2_viola','ch2_nevia','ch2_elmina'],guard:['ch2_rostia','ch2_althea','ch2_ferne','ch2_clarisse'],finishers:['ch2_sephira','ch2_astrelle','ch2_nemesia','ch2_everia'],mixed:['ch2_sephira','ch2_astrelle','ten_time','ten_life'],unpaired:['ch2_sephira','ch2_everia','ch2_lunaria','ch2_vespera']};
export const scenarios={general:{ids:['ch2_balk','ch2_shelza','ch2_kororu','ch2_grant'],enemyHp:8,enemyPower:1.3},healing:{ids:['ch2_shion','ch2_suiren','ch2_lunaria','ch2_solaria'],enemyHp:1.5,enemyPower:.25},debuff:{ids:['ch2_mirea','ch2_viola','ch2_nevia','ch2_elmina'],enemyHp:4,enemyPower:.8},shield:{ids:['ch2_rostia','ch2_althea','ch2_dracia','ch2_rucie'],enemyHp:2,enemyPower:.3},burst:{ids:['ch2_calista','ch2_solenne','ch2_ryune','ch2_rose'],enemyHp:2,enemyPower:.5},boss:{ids:['ch2_aure'],enemyHp:25,enemyPower:1.5,boss:true}};
export async function batch({seeds=10,full=false,output='build409-work/calibration.json'}={}){const rows=[];let count=0;const start=Date.now();for(const level of full?[1500,3000]:[1500])for(const gear of full?[false,true]:[false])for(const circles of full?[false,true]:[false])for(const[scenario,enemy]of Object.entries(scenarios))for(const[comp,ids]of Object.entries(comps))for(const enabled of full?[false,true]:[true]){
 const iterations=level===1500&&!gear&&!circles?seeds:Math.min(seeds,20);const samples=[];for(let seed=1;seed<=iterations;seed++){const r=await run(ids,enemy.ids,{...enemy,level,gear,circles,pairEnabled:enabled,seed,maxRounds:30});samples.push({seed,...r});count++;}
 const wins=samples.filter(r=>r.won),median=a=>a.length?[...a].sort((a,b)=>a-b)[Math.floor(a.length/2)]:null,mean=k=>samples.reduce((s,r)=>s+(r.metrics[k]??0),0)/samples.length;
 const row={level,gear,circles,scenario,comp,enabled,n:iterations,wins:wins.length,losses:samples.filter(r=>r.lost).length,medianWinRound:median(wins.map(r=>r.rounds)),meanDamage:mean('damage'),meanTaken:mean('taken'),meanHealing:mean('healing'),meanMpSpent:mean('mpSpent'),meanMpDrained:mean('mpDrained'),meanShieldAbsorbed:mean('shieldAbsorbed'),meanActivations:samples.reduce((s,r)=>s+Object.entries(r.synergy).filter(([k])=>k.startsWith('ally:')).reduce((t,[,v])=>t+v.activations,0),0)/iterations};rows.push(row);
 if(!full)console.log(scenario,comp,`${row.wins}/${seeds}`,row.medianWinRound,'synergy',row.meanActivations);
 if(full&&count%1200===0)console.log('progress',count,Math.round((Date.now()-start)/1000)+'s');
 if(full)fs.appendFileSync(output+'.samples.jsonl',samples.map(r=>JSON.stringify({level,gear,circles,scenario,comp,enabled,...r})).join('\n')+'\n');
 }
 fs.writeFileSync(output,JSON.stringify({battleCount:count,seconds:(Date.now()-start)/1000,seeds,rows},null,2));return rows;}
