import{playerColor499}from'../party/PartyColors499.js';
import{partySeats462}from'../party/PartyView462.js';
import{resultActions490}from'../party/PartyResults490.js';
import{lockPlayZoom498}from'../cabbage/Zoom498.js';
import{property506,style506}from'../gorilla/Performance506.js';
import{raceFrame507,banner507,itemById507,delta507,paintKey507}from'./Presentation507.js';
import{sound507}from'./Audio507.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.lkUI507??={sound:true,pending:null,limit:24,search:'',artReady:false};
const clock=c=>Date.now()+(c.offset??0),portrait=(c,p)=>c.sgMonster463?.(p.choice?.speciesId??p.speciesId)??'',name=(c,p)=>p.playerId===c.transport.selfId?'あなた':esc(p.name);
export const art507=tile=>`<i class="lk-art507" data-tile="${tile}" aria-hidden="true"></i>`;
function header(c){return`<header class="lk-header507"><button data-party-action462="browse">‹ パーティー</button><div><small>LUCK ONLY GAMES</small><b>運だけ大運動会</b></div><button data-lk-action="sound" aria-pressed="${ui(c).sound}">音 ${ui(c).sound?'ON':'OFF'}</button></header>`}
function lobby(c,g){const u=ui(c),p=c.state.party,me=g.members.find(m=>m.playerId===c.transport.selfId),pm=p.members.find(m=>m.playerId===c.transport.selfId),host=p.hostId===c.transport.selfId,all=c.roster().filter(m=>!u.search||c.sgSpeciesName463(m.raceSpeciesId??m.speciesId).includes(u.search));return`<section class="lk507 lk-lobby507">${header(c)}<div class="lk-cover507"><div class="lk-cover-copy507"><small>勝つのは、いちばん運のいいやつ。</small><h1>運だけ<br><em>大運動会</em></h1><p>最後の一箱まで、わからない。</p></div><div class="lk-cover-props507">${art507(3)}${art507(0)}${art507(4)}</div></div><div class="lk-body507"><div class="lk-facts507"><b>全8ラウンド</b><b>完全運</b><b>4人・参加無料</b></div><ol class="lk-rules507"><li>3つの箱から、ひとつ選ぶ。</li><li>全員同時に開封。アイテムで前へ、後ろへ！</li><li>8ラウンド後、いちばん遠くにいた人が優勝。</li></ol><p class="lk-note507">ロケットは後ろからでも大逆転！ 能力差なし。時間切れはおまかせ。空席にはAIが参加するよ。</p><h2>運を託す、相棒を選ぼう</h2><input name="luckSearch507" class="lk-search507" value="${esc(u.search)}" placeholder="魔物の名前で探す" aria-label="魔物の名前で探す"><div class="lk-roster507">${all.slice(0,u.limit).map(m=>`<button data-lk-monster="${esc(m.id)}" aria-pressed="${m.id===me?.choice?.id}" ${!c.ready()||!me?'disabled':''}>${portrait(c,{speciesId:m.raceSpeciesId??m.speciesId})}<b>${esc(c.sgSpeciesName463(m.raceSpeciesId??m.speciesId))}</b></button>`).join('')||'<p>見つかりませんでした。</p>'}</div>${all.length>u.limit?'<button data-lk-action="more">もっと見る</button>':''}${partySeats462(c)}</div><footer class="lk-lobby-actions507"><p role="alert" ${c.error?'':'hidden'}>${esc(c.error)}</p><button class="lk-primary507" data-party-action462="ready" aria-pressed="${!!pm?.ready}" ${!c.ready()||!me?.choice||!u.artReady?'disabled':''}>${!u.artReady?'競技場を準備中…':pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${u.artFailed?'<button data-lk-action="reload">画像を再読み込み</button>':''}${host?`<button class="lk-primary507" data-lk-action="start" ${!c.ready()||!u.artReady||p.members.some(m=>!m.ready||!m.connected||m.atHome)?'disabled':''}>大運動会、開幕！</button><button data-party-action462="lounge">ミニゲーム一覧へ戻る</button>`:'<p>部屋主が開始すると、4人で出走！</p>'}</footer></section>`}
function players(c,g){return`<div class="lk-players507">${g.players.map(p=>`<article data-lk-seat="${p.seat}" style="--player:${playerColor499(p).hex}"><span>${portrait(c,p)}</span><b>${name(c,p)}</b><strong data-lk-score="${p.seat}">0<small>m</small></strong><small data-lk-state="${p.seat}">待機中</small></article>`).join('')}</div>`}
function play(c,g){return`<section class="lk507 lk-play507">${header(c)}${players(c,g)}<div class="lk-round507"><span data-lk-round>ROUND 1 / 8</span><div>${Array.from({length:8},(_,i)=>`<i data-lk-dot="${i+1}"></i>`).join('')}</div><b data-lk-timer></b></div><div class="lk-stage507" data-lk-stage><div class="lk-arena507"></div><div class="lk-stage-shade507"></div><div class="lk-announcement507"><strong data-lk-banner></strong><span data-lk-sub></span></div><div class="lk-distance-mark507"><span>0</span><span data-lk-range>80m</span></div><div class="lk-lanes507">${g.players.map(p=>`<div class="lk-runner507" data-lk-runner="${p.seat}" style="top:${[42,56,70,84][p.seat]}%;--player:${playerColor499(p).hex}"><div class="lk-trail507" data-lk-trail="${p.seat}" hidden></div><i class="lk-shadow507"></i><div class="lk-body-motion507" data-lk-body="${p.seat}"><div class="lk-prop507" data-lk-prop="${p.seat}" hidden>${art507(3)}</div>${portrait(c,p)}</div><b class="lk-runner-name507">${name(c,p)}</b><span class="lk-gain507" data-lk-gain="${p.seat}" hidden></span></div>`).join('')}</div><div class="lk-countdown507" data-lk-countdown hidden><div>${art507(2)}<small>運だけ大運動会</small><strong data-lk-count>3</strong><p>箱をひとつ。運で、ぶっ飛べ。</p></div></div><div class="lk-art-status507" data-lk-art-status ${ui(c).artReady?'hidden':''}>競技場を準備中…<button data-lk-action="reload" ${ui(c).artFailed?'':'hidden'}>画像を再読み込み</button></div></div><footer class="lk-controls507"><div class="lk-control-title507"><strong data-lk-instruction>箱をひとつ選んでね</strong><span data-lk-selected></span></div><div class="lk-boxes507" data-lk-boxes>${[0,1,2].map(i=>`<button class="lk-box507" data-lk-box="${i}" aria-label="${i+1}番の箱を選ぶ" aria-pressed="false" disabled>${art507(0)}<b>${['Ⅰ','Ⅱ','Ⅲ'][i]}</b><span>選ぶ</span></button>`).join('')}</div><div class="lk-reveals507" data-lk-reveals hidden>${g.players.map(p=>`<article data-lk-reveal="${p.seat}" style="--player:${playerColor499(p).hex}"><b>${name(c,p)}</b>${art507(0)}<strong data-lk-item="${p.seat}"></strong><span data-lk-delta="${p.seat}"></span></article>`).join('')}</div><p class="lk-control-note507" data-lk-note>時間切れは、おまかせで選ぶよ。</p><p class="lk-error507" data-lk-error role="alert" hidden></p></footer><div class="lk-offline507" data-lk-offline hidden role="status">再接続中… このラウンドはおまかせで進むよ。<button data-race-action="refresh">接続を確認</button></div><span class="lk-reader507" data-lk-reader aria-live="polite"></span></section>`}
function result(c,g){const winners=g.results.filter(r=>r.rank===1),winner=g.players.find(p=>p.playerId===winners[0].playerId);return`<section class="lk507 lk-result507">${header(c)}<div class="lk-victory507"><small>LUCK OF THE DAY</small><h1>${winners.length>1?'同着、優勝！':name(c,winner)+'、優勝！'}</h1>${art507(2)}<div class="lk-winners507">${winners.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<div style="--player:${playerColor499(p).hex}">${portrait(c,p)}<b>${name(c,p)}</b></div>`}).join('')}</div><strong>${winner.distance}<small> m</small></strong><p>今日の運、ぜんぶ持っていった。</p></div>${resultActions490(c)}<div class="lk-body507"><h2>最終順位</h2><div class="lk-results507">${g.results.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<article style="--player:${playerColor499(p).hex}"><b>${r.rank}<small>位</small></b>${portrait(c,p)}<span><strong>${name(c,p)}</strong><small>${p.ai?'AI':'PLAYER'}</small></span><em>${r.distance}<small>m</small></em></article>`}).join('')}</div><details class="lk-history507"><summary>8ラウンドの運だめしを振り返る</summary>${g.history.map(e=>`<div><b>ROUND ${e.round}</b><div>${e.rows.map(r=>{const p=g.players[r.seat],item=itemById507(r.item);return`<span style="--player:${playerColor499(p).hex}"><b>${name(c,p)}</b>${art507(item.tile)}<small>${esc(item.name)}</small><strong>${delta507(r.delta)}</strong></span>`}).join('')}</div></div>`).join('')}</details></div></section>`}
export function luckView507(c){const g=c.state?.luck;if(!g)return'';const u=ui(c);if(u.gameId!==g.id){u.gameId=g.id;u.pending=null;u.limit=24;u.search='';u.lastPaint=null;u.soundKey=null}return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
export function luckBefore507(c){const u=c.lkUI507;if(!u)return;if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null;u.cleanup?.();u.cleanup=null;u.nodes=null;u.lastPaint=null}
export function luckDispose507(c){luckBefore507(c);const u=c.lkUI507;if(u){u.pending=null;u.audio?.close().catch(()=>{});u.audio=null}}
function prepareArt(c,retry=false){const u=ui(c);if(u.loading||(u.artReady||u.artFailed)&&!retry||typeof globalThis.Image!=='function')return;u.loading=true;u.artFailed=false;const urls=['./assets/luck507/stadium.png','./assets/luck507/items.png'];Promise.all(urls.map(src=>new Promise(resolve=>{const im=new Image();let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);im.onload=im.onerror=null;resolve(ok)},timer=setTimeout(()=>finish(false),15000);im.onload=()=>finish(im.naturalWidth>0);im.onerror=()=>finish(false);im.src=src}))).then(ok=>{u.loading=false;u.artReady=ok.every(Boolean);u.artFailed=!u.artReady;u.lastPaint=null;if(c.root?.querySelector('.lk-lobby507'))c.render();else luckTick507(c)})}
export function luckAfter507(c){const root=c.root?.querySelector('.lk507');if(!root)return;const u=ui(c);u.reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;prepareArt(c);if(!root.classList.contains('lk-play507'))return;const unlock=lockPlayZoom498(root),q=s=>root.querySelector(s);u.nodes={root,stage:q('[data-lk-stage]'),round:q('[data-lk-round]'),timer:q('[data-lk-timer]'),range:q('[data-lk-range]'),banner:q('[data-lk-banner]'),sub:q('[data-lk-sub]'),countdown:q('[data-lk-countdown]'),count:q('[data-lk-count]'),boxes:q('[data-lk-boxes]'),reveals:q('[data-lk-reveals]'),instruction:q('[data-lk-instruction]'),selected:q('[data-lk-selected]'),note:q('[data-lk-note]'),error:q('[data-lk-error]'),offline:q('[data-lk-offline]'),art:q('[data-lk-art-status]'),reader:q('[data-lk-reader]'),dots:[...root.querySelectorAll('[data-lk-dot]')],buttons:[...root.querySelectorAll('[data-lk-box]')],players:c.state.luck.players.map(p=>({seat:p.seat,card:q(`[data-lk-seat="${p.seat}"]`),score:q(`[data-lk-score="${p.seat}"]`),status:q(`[data-lk-state="${p.seat}"]`),runner:q(`[data-lk-runner="${p.seat}"]`),body:q(`[data-lk-body="${p.seat}"]`),prop:q(`[data-lk-prop="${p.seat}"]`),propArt:q(`[data-lk-prop="${p.seat}"] .lk-art507`),trail:q(`[data-lk-trail="${p.seat}"]`),gain:q(`[data-lk-gain="${p.seat}"]`),reveal:q(`[data-lk-reveal="${p.seat}"]`),art:q(`[data-lk-reveal="${p.seat}"] .lk-art507`),item:q(`[data-lk-item="${p.seat}"]`),delta:q(`[data-lk-delta="${p.seat}"]`)}))};
 const size=()=>{const h=u.nodes?.stage?.clientHeight??360,v=Math.max(16,Math.min(62,h*.14-16)).toFixed(1)+'px';if(u.pawnSize!==v||root.style.getPropertyValue('--lk-pawn-size')!==v){u.pawnSize=v;root.style.setProperty('--lk-pawn-size',v)}};size();const observer=typeof globalThis.ResizeObserver==='function'?new ResizeObserver(size):null;observer?.observe(u.nodes.stage);const visible=()=>{if(globalThis.document?.visibilityState==='hidden'){if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null}else{u.lastPaint=null;luckTick507(c)}};globalThis.document?.addEventListener('visibilitychange',visible);u.cleanup=()=>{observer?.disconnect();unlock();globalThis.document?.removeEventListener('visibilitychange',visible)};luckTick507(c);
}
export function requestLuck507(c,box){const g=c.state?.luck,u=ui(c),me=g?.players.find(p=>p.playerId===c.transport.selfId);if(!g||g.phase!=='choose'||!me||me.locked||u.pending||!c.ready()||clock(c)>=g.deadline||!Number.isInteger(box)||box<0||box>2)return false;u.pending={gameId:g.id,round:g.round,box,at:Date.now()};c.error='';sound507(c,'pick');const sent=c.raw('luck507',{kind:'choose',gameId:g.id,round:g.round,box});if(sent===false){u.pending=null;c.error='送信できなかったよ。接続を確認してね。'}u.lastPaint=null;luckTick507(c);return sent!==false}
export function luckReceive507(c){const u=c.lkUI507,g=c.state?.luck;if(u?.pending&&(u.pending.gameId!==g?.id||u.pending.round!==g?.round||g.phase!=='choose'||g.ownBox!==null))u.pending=null}
export function luckError507(c,m){if(m.op==='luck507'&&c.lkUI507)c.lkUI507.pending=null}
export function luckClick507(c,b){const d=b.dataset;if(d.lkBox!==undefined){requestLuck507(c,Number(d.lkBox));return true}if(!d.lkAction&&d.lkMonster===undefined)return false;const g=c.state?.luck;if(!g)return true;const u=ui(c);if(d.lkAction==='sound'){u.sound=!u.sound;sound507(c,'pick');b.textContent='音 '+(u.sound?'ON':'OFF');b.setAttribute('aria-pressed',String(u.sound));return true}if(d.lkAction==='reload'){prepareArt(c,true);return true}if(d.lkAction==='more'){u.limit+=24;c.render();return true}sound507(c,'pick');c.error='';if(d.lkMonster!==undefined)c.raw('luck507',{gameId:g.id,kind:'select',monsterId:d.lkMonster});if(d.lkAction==='start')c.raw('luck507',{gameId:g.id,kind:'start'});return true}
export function luckInput507(c,e){if(e.name!=='luckSearch507')return false;ui(c).search=e.value;c.render();return true}
export function luckKey507(c,e){if(!c.state?.luck||c.partyBrowse462||e.target?.closest?.('input,select,textarea,[contenteditable="true"]')||!/^Digit[123]$|^Numpad[123]$/.test(e.code))return false;e.preventDefault();if(!e.repeat)requestLuck507(c,Number(e.code.at(-1))-1);return true}
const put=(el,text)=>el&&property506(el,'textContent',String(text)),hide=(el,v)=>el&&property506(el,'hidden',!!v),data=(el,k,v)=>{if(el&&el.dataset[k]!==String(v))el.dataset[k]=String(v)};
export function paintLuck507(c,at=clock(c)){
 const g=c.state?.luck,u=c.lkUI507,n=u?.nodes;if(!g||!n||['lobby','result'].includes(g.phase)||globalThis.document?.visibilityState==='hidden')return;
 if(u.pending&&Date.now()-u.pending.at>6000){u.pending=null;c.error='選択を確認できませんでした。もう一度選んでね。';c.refresh?.()}
 const key=paintKey507(g,at,c.ready(),u.pending,u.reduced)+':'+u.artReady+':'+u.artFailed+':'+(c.error??'');if(key===u.lastPaint)return;u.lastPaint=key;
 const me=g.players.find(p=>p.playerId===c.transport.selfId),selected=g.ownBox??u.pending?.box,choosing=g.phase==='choose',revealing=['reveal','run','settle'].includes(g.phase),cap=banner507(g,c.transport.selfId,at),frame=raceFrame507(g,at,u.reduced);
 data(n.root,'phase',g.phase);data(n.root,'reduced',u.reduced);put(n.round,(g.round===8?'FINAL ROUND':'ROUND '+g.round)+' / 8');put(n.timer,choosing?Math.max(0,Math.ceil((g.deadline-at)/1000))+'秒':'');for(let i=0;i<n.dots.length;i++)data(n.dots[i],'done',i<g.round);put(n.banner,cap.label);put(n.sub,cap.sub);hide(n.countdown,g.phase!=='countdown');put(n.count,cap.count??'');hide(n.boxes,revealing);hide(n.reveals,!revealing);
 put(n.instruction,choosing?(me?selected!=null?'この箱に、運を託した！':'箱をひとつ選んでね':'みんなの箱を見守ろう'):g.phase==='countdown'?'まもなく、開幕！':g.phase==='settle'?(g.round===8?'結果発表へ！':'次のラウンドへ…'):'みんなの運命');put(n.selected,choosing?g.players.filter(p=>p.locked).length+' / 4 人が選択':'ROUND '+g.round);put(n.note,choosing?'時間切れは、おまかせで選ぶよ。':g.phase==='countdown'?'魔物の強さも、選ぶ速さも関係なし。':'');
 for(let i=0;i<n.buttons.length;i++){const b=n.buttons[i];property506(b,'disabled',!choosing||!me||selected!=null||!c.ready()||at>=g.deadline);const chosen=selected===i;if(b.getAttribute('aria-pressed')!==String(chosen))b.setAttribute('aria-pressed',String(chosen));put(b.querySelector('span'),chosen?'選択済み':'選ぶ')}
 const d=frame.map(p=>p.distance);for(const p of g.players){const row=n.players.find(x=>x.seat===p.seat),f=frame.find(x=>x.seat===p.seat),event=g.event?.rows.find(r=>r.seat===p.seat),rank=1+d.filter(x=>x>f.distance).length;put(row.score,f.distance+'m');put(row.status,choosing?(p.locked?'✓ 選択済み':p.ai?'AI · 選択中':p.connected?'選択中':'おまかせ待ち'):rank+'位');data(row.card,'locked',p.locked);style506(row.runner,'transform',`translate3d(${f.x.toFixed(3)}%,0,0)`);style506(row.body,'transform',`translate3d(-50%,${f.y.toFixed(2)}px,0) rotate(${f.angle.toFixed(2)}deg) scale(${f.scale.toFixed(3)})`);style506(row.body,'opacity',f.opacity.toFixed(3));hide(row.prop,!f.prop);data(row.prop,'kind',f.item);data(row.propArt,'tile',f.tile);hide(row.trail,!f.trail);hide(row.gain,g.phase!=='settle');put(row.gain,event?delta507(event.delta):'');if(event){const item=itemById507(event.item);data(row.art,'tile',item.tile);put(row.item,item.name);put(row.delta,delta507(event.delta));data(row.reveal,'bad',event.delta<=0)}}
 put(n.range,(g.event&&['run','settle'].includes(g.phase)?g.event.toMax:g.scaleMax)+'m');hide(n.offline,c.ready());hide(n.error,!c.error);put(n.error,c.error??'');hide(n.art,u.artReady);if(u.artFailed){const b=n.art.querySelector('button');hide(b,false)}
 const soundKey=[g.id,g.round,g.phase,g.phase==='countdown'?cap.count:''].join(':');if(u.soundKey!==soundKey){u.soundKey=soundKey;if(g.phase==='reveal')sound507(c,'open');if(g.phase==='run')sound507(c,'launch');if(g.phase==='countdown')sound507(c,'count');if(g.phase==='settle'&&g.round===8)sound507(c,'finish');put(n.reader,cap.label+(g.phase==='settle'?g.players.map(p=>p.name+' '+p.distance+'メートル').join('、'):''))}
}
export function luckTick507(c){const u=c.lkUI507;if(!u?.nodes||globalThis.document?.visibilityState==='hidden')return;if(u.raf!=null)return;if(typeof globalThis.requestAnimationFrame!=='function'){paintLuck507(c);return}u.raf=globalThis.requestAnimationFrame(()=>{u.raf=null;paintLuck507(c)})}
