import {playerColor499} from '../party/PartyColors499.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
import {property506,style506 as ordinaryStyle511} from '../gorilla/Performance506.js';
import {ITEMS511,item511,LUCK511} from './Rules511.js';
import {raceFrame511,broadcastFrame511,banner511,paintKey511,delta511,equipment511,hitLabel511,distance511,fullDistance511,gearList511,courseOffsets511,markerLabel511,animating511,diceFrame511,buffStatus511} from './Presentation511.js';
import {sound511} from './Audio511.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style511=(el,key,value)=>{if(!el)return;if(key.startsWith('--')){if(el.style.getPropertyValue(key)!==value)el.style.setProperty(key,value)}else ordinaryStyle511(el,key,value)};
const ui=c=>c.lkUI511??={sound:true,pending:null,limit:24,search:'',artReady:false};
const clock=c=>Date.now()+(c.offset??0);
const portrait=(c,p)=>c.sgMonster463?.(p.choice?.speciesId??p.speciesId)??'';
const name=(c,p)=>p.playerId===c.transport.selfId?'あなた':esc(p.name);
const color=p=>playerColor499(p).hex;
export const art511=id=>`<i class="lk-art508" data-item="${id}" data-atlas="${item511(id).atlas}" style="--tile-x:${item511(id).tile%4};--tile-y:${Math.floor(item511(id).tile/4)}" aria-hidden="true"></i>`;
const oldArt=tile=>`<i class="lk-art507" data-tile="${tile}" aria-hidden="true"></i>`;
const header=c=>`<header class="lk-header507"><button data-party-action462="browse">‹ パーティー</button><div><small>LUCK ONLY GAMES</small><b>運だけ大運動会</b></div><button data-lk511-action="sound" aria-pressed="${ui(c).sound}">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),p=c.state.party,me=g.members.find(m=>m.playerId===c.transport.selfId),pm=p.members.find(m=>m.playerId===c.transport.selfId),host=p.hostId===c.transport.selfId,all=c.roster().filter(m=>!u.search||c.sgSpeciesName463(m.raceSpeciesId??m.speciesId).includes(u.search));return`<section class="lk507 lk508 lk509 lk511 lk-lobby508">${header(c)}<div class="lk-cover507"><div class="lk-cover-copy507"><small>運を引け。相手を読め。</small><h1>運だけ<br><em>大運動会</em></h1><p>積んで、育てて、ぶっ飛ばせ。</p></div><div class="lk-cover-props508">${art511('doubling')}${oldArt(0)}${art511('nova')}</div></div><div class="lk-body507"><div class="lk-facts507"><b>全8ラウンド</b><b>運 × 読み合い</b><b>4人・参加無料</b></div><ol class="lk-rules507"><li>4つの宝箱から1つ選ぶ。</li><li>中身はランダムな4アイテム。使う1つを選ぶ。</li><li>装備は残り、毎ターン自動発動。育てた倍率を、大技で解放！</li><li>8ラウンド後、いちばん遠くにいた人が優勝。</li></ol><p class="lk-note507">防御は先に発動。攻撃同士の順番は毎回ランダム。選ぶ速さや魔物の強さに差はないよ。選んだ継続装備は残る。大技とゲートは1回きり。最後の4枚には必ず大技が1枚以上。選ばなかった3枚は消え、次もランダムな4枚。装備は相手の欄をタップして確認できるよ。空席はAIが走るよ。</p><details class="lk-catalog508"><summary>40種類のアイテムを見る · 28種類は継続装備</summary><div>${ITEMS511.map(it=>`<article>${art511(it.id)}<b>${it.name}</b><p>${it.detail}</p></article>`).join('')}</div></details><h2>運を託す、相棒を選ぼう</h2><input name="luckSearch511" class="lk-search507" value="${esc(u.search)}" placeholder="魔物の名前で探す" aria-label="魔物の名前で探す"><div class="lk-roster507">${all.slice(0,u.limit).map(m=>`<button data-lk511-monster="${esc(m.id)}" aria-pressed="${m.id===me?.choice?.id}" ${!c.ready()||!me?'disabled':''}>${portrait(c,{speciesId:m.raceSpeciesId??m.speciesId})}<b>${esc(c.sgSpeciesName463(m.raceSpeciesId??m.speciesId))}</b></button>`).join('')||'<p>見つかりませんでした。</p>'}</div>${all.length>u.limit?'<button data-lk511-action="more">もっと見る</button>':''}${partySeats462(c)}</div><footer class="lk-lobby-actions507"><p role="alert" ${c.error?'':'hidden'}>${esc(c.error)}</p><button class="lk-primary507" data-party-action462="ready" aria-pressed="${!!pm?.ready}" ${!c.ready()||!me?.choice||!u.artReady?'disabled':''}>${!u.artReady?'競技場を準備中…':pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${u.artFailed?'<button data-lk511-action="reload">画像を再読み込み</button>':''}${host?`<button class="lk-primary507" data-lk511-action="start" ${!c.ready()||!u.artReady||p.members.some(m=>!m.ready||!m.connected||m.atHome)?'disabled':''}>大運動会、開幕！</button><button data-party-action462="lounge">ミニゲーム一覧へ戻る</button>`:'<p>部屋主が開始すると、4人で出走！</p>'}</footer></section>`}
function cards(c,g){return`<div class="lk-players507 lk-players508">${g.players.map(p=>`<article style="--player:${color(p)}"><span>${portrait(c,p)}</span><b>${name(c,p)}</b><strong data-score511="${p.seat}">${distance511(p.distance)}</strong><small data-status511="${p.seat}"></small><button class="lk-gear-button509" data-gear-seat511="${p.seat}" aria-label="${name(c,p)}の装備を確認"><span data-equip511="${p.seat}"></span></button></article>`).join('')}</div>`}
function runners(c,g){return g.players.map(p=>`<div class="lk-runner508" data-runner511="${p.seat}" style="--player:${color(p)};top:${[43.5,58,72.5,87][p.seat]}%"><div class="lk-trail508" data-trail511="${p.seat}" hidden></div><i class="lk-shadow508"></i><div class="lk-motion508" data-body511="${p.seat}"><div class="lk-vehicle508" data-vehicle511="${p.seat}" hidden>${art511('rocket')}</div><div class="lk-aura508" data-guard511="${p.seat}" hidden></div>${portrait(c,p)}</div><b>${name(c,p)}</b><span data-edge511="${p.seat}" class="lk-edge508"></span><em data-gain511="${p.seat}" hidden></em></div>`).join('')}
function broadcast(c,g){return`<div class="lk-broadcast508" data-cast511 hidden aria-label="全員共通の攻撃中継"><div class="lk-cast-top508"><b><i></i> LIVE</b><span data-cast-counter511></span><strong data-cast-title511></strong></div><div class="lk-cast-speed508"></div><div class="lk-volley509" data-volley511>${Array.from({length:9},()=>art511('shell')).join('')}</div><div class="lk-cast-who508" data-cast-who511></div><div class="lk-cast-actors508">${g.players.map(p=>`<div class="lk-cast-actor508" data-cast-actor511="${p.seat}" style="--player:${color(p)}"><i class="lk-cast-ring508" data-cast-ring511="${p.seat}" hidden></i><div class="lk-cast-sprite508" data-cast-body511="${p.seat}">${portrait(c,p)}</div><b>${name(c,p)}</b><strong data-cast-hit511="${p.seat}"></strong><i class="lk-thunder508" data-cast-bolt511="${p.seat}" hidden></i></div>`).join('')}</div>${g.players.map(p=>`<div class="lk-shot509" data-cast-shot511="${p.seat}" hidden>${art511('shell')}</div>`).join('')}<div class="lk-projectile508" data-projectile511>${art511('shell')}</div><div class="lk-return508" data-return511 hidden>${art511('shell')}</div><div class="lk-impact508" data-impact511 hidden></div><div class="lk-cast-bottom508" data-cast-bottom511></div></div>`}
function play(c,g){return`<section class="lk507 lk508 lk509 lk511 lk-play508" data-phase="${g.phase}">${header(c)}${cards(c,g)}<div class="lk-round507"><span data-round511></span><div>${Array.from({length:8},(_,i)=>`<i data-dot511="${i+1}"></i>`).join('')}</div><b data-timer511></b></div><div class="lk-minimap508" aria-label="全員のコース上の位置"><span>START</span><div>${g.players.map(p=>`<i data-mini511="${p.seat}" style="--player:${color(p)}" title="${esc(p.name)}">${p.seat+1}</i>`).join('')}</div><span data-map-end511></span></div><div class="lk-stage508" data-stage511><div class="lk-course508" data-ground511></div><div class="lk-course508 lk-horizon508" data-horizon511></div><div class="lk-near511" data-near511></div><div class="lk-markers508">${Array.from({length:7},(_,i)=>`<i data-mark511="${i}"><b></b></i>`).join('')}</div><div class="lk-speed508" data-speed511></div><div class="lk-banner508"><strong data-banner511></strong><span data-sub511></span></div>${runners(c,g)}${edgeIndicators(c,g)}<div class="lk-countdown508" data-countdown511 hidden>${oldArt(2)}<small>運を引け。相手を読め。</small><strong data-count511></strong></div>${broadcast(c,g)}${diceStage(c,g)}${gearPanel(c,g)}<div class="lk-art-status507" data-art-status511 ${ui(c).artReady?'hidden':''}>競技場を準備中…<button data-lk511-action="reload" ${ui(c).artFailed?'':'hidden'}>画像を再読み込み</button></div></div><footer class="lk-controls508"><div class="lk-control-title507"><strong data-instruction511></strong><span data-selected511></span></div><div class="lk-chests508" data-chests511>${[0,1,2,3].map(i=>`<button data-chest511="${i}" aria-label="${i+1}番の宝箱を選ぶ" aria-pressed="false" disabled>${oldArt(0)}<b>${['Ⅰ','Ⅱ','Ⅲ','Ⅳ'][i]}</b><span>選ぶ</span></button>`).join('')}</div><div class="lk-hand508" data-hand511 hidden>${[0,1,2,3].map(i=>`<button data-hand-pick511="${i}" aria-label="${i+1}枚目のアイテム" aria-pressed="false" disabled><span class="lk-item-type508"></span>${art511('dash')}<b></b><p></p><span class="lk-item-check508">✓ SET</span></button>`).join('')}</div><div class="lk-reveals508" data-reveals511 hidden>${g.players.map(p=>`<article style="--player:${color(p)}"><b>${name(c,p)}</b>${art511('dash')}<strong data-reveal-item511="${p.seat}"></strong><span data-reveal-gain511="${p.seat}"></span></article>`).join('')}</div><p class="lk-note508" data-note511></p><p class="lk-error507" data-error511 role="alert" hidden></p></footer><div class="lk-offline507" data-offline511 hidden role="status">再接続中… 未選択なら、おまかせで進むよ。<button data-race-action="refresh">接続を確認</button></div><span class="lk-reader507" data-reader511 aria-live="polite"></span></section>`}
function result(c,g){const winners=g.results.filter(r=>r.rank===1),winner=g.players.find(p=>p.playerId===winners[0].playerId);return`<section class="lk507 lk508 lk509 lk511 lk-result508">${header(c)}<div class="lk-victory507"><small>LUCK & THE LAST MOVE</small><h1>${winners.length>1?'同着、優勝！':name(c,winner)+'、優勝！'}</h1>${oldArt(2)}<div class="lk-winners507">${winners.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<div style="--player:${color(p)}">${portrait(c,p)}<b>${name(c,p)}</b></div>`}).join('')}</div><strong>${distance511(winner.distance)}</strong><p class="lk-exact509">${fullDistance511(winner.distance)}</p><p>育てた装備で、ここまで飛んだ。</p></div>${resultActions490(c)}<div class="lk-body507"><h2>最終順位</h2><div class="lk-results507">${g.results.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<article style="--player:${color(p)}"><b>${r.rank}<small>位</small></b>${portrait(c,p)}<span><strong>${name(c,p)}</strong><small>${equipment511(p)||'FINISH'}</small><small>${fullDistance511(r.distance)}</small></span><em>${distance511(r.distance)}</em></article>`}).join('')}</div><details class="lk-history507 lk-history508"><summary>8ラウンドの勝負を振り返る</summary>${g.history.map(e=>`<div><b>ROUND ${e.round}</b><div>${e.rows.map(r=>{const p=g.players[r.seat],it=item511(r.item);return`<span style="--player:${color(p)}"><b>${name(c,p)}</b>${art511(it.id)}<small>${it.name}</small><strong>${delta511(r.delta)}</strong></span>`}).join('')}</div></div>`).join('')}</details></div></section>`}
export function luckView511(c){const g=c.state?.luck;if(!g)return'';const u=ui(c);if(u.gameId!==g.id){u.gameId=g.id;u.pending=null;u.gearSeat=null;u.limit=24;u.search='';u.lastPaint=null;u.soundKey=null}return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
const put=(e,t)=>e&&property506(e,'textContent',String(t)),hide=(e,v)=>e&&property506(e,'hidden',!!v),data=(e,k,v)=>{if(e&&e.dataset[k]!==String(v))e.dataset[k]=String(v)},attr=(e,k,v)=>{if(e?.getAttribute(k)!==String(v))e?.setAttribute(k,String(v))};
const setArt=(e,id)=>{if(!e||e.dataset.item===id)return;const it=item511(id);data(e,'item',id);data(e,'atlas',it.atlas);style511(e,'--tile-x',String(it.tile%4));style511(e,'--tile-y',String(Math.floor(it.tile/4)))};
function prepareArt(c,retry=false){const u=ui(c);if(u.loading||(u.artReady||u.artFailed)&&!retry||typeof globalThis.Image!=='function')return;u.loading=true;u.artFailed=false;const urls=['./assets/luck507/stadium.png','./assets/luck507/items.png','./assets/luck508/items.png','./assets/luck508/course.png','./assets/luck509/items.png','./assets/luck511/items.png'];Promise.all(urls.map(src=>new Promise(resolve=>{const im=new Image();let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);im.onload=im.onerror=null;resolve(ok)},timer=setTimeout(()=>finish(false),15000);im.onload=()=>{if(im.decode)im.decode().then(()=>finish(im.naturalWidth>0)).catch(()=>finish(false));else finish(im.naturalWidth>0)};im.onerror=()=>finish(false);im.src=src}))).then(ok=>{u.loading=false;u.artReady=ok.every(Boolean);u.artFailed=!u.artReady;u.lastPaint=null;if(c.root?.querySelector('.lk-lobby508'))c.render();else luckTick511(c)})}
export function luckBefore511(c){const u=c.lkUI511;if(!u)return;if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null;u.cleanup?.();u.cleanup=null;u.nodes=null;u.lastPaint=null}
export function luckDispose511(c){luckBefore511(c);const u=c.lkUI511;if(u){u.pending=null;u.audio?.close().catch(()=>{});u.audio=null}}
export function luckAfter511(c){const root=c.root?.querySelector('.lk511');if(!root)return;const u=ui(c);u.reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;prepareArt(c);if(!root.classList.contains('lk-play508'))return;const unlock=lockPlayZoom498(root),q=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 u.nodes={root};for(const id of['dice-stage','dice-name','dice-counter','dice-formula','dice-power','dice-buffs','dice-caption','dice-focus','gear-status','gear-panel','gear-title','gear-list','volley','stage','round','timer','map-end','banner','sub','countdown','count','chests','hand','reveals','instruction','selected','note','error','offline','art-status','reader','ground','horizon','near','speed','cast','cast-counter','cast-title','cast-who','cast-bottom','projectile','return','impact'])u.nodes[id]=q(`[data-${id}511]`);
 const n=u.nodes;n.diceCubes=all('[data-dice-cube511]');n.diceLifts=all('[data-dice-lift511]');n.diceActors=all('[data-dice-actor511]');n.gearSlots=all('[data-gear-slot511]');n.volleyArts=all('[data-volley511] .lk-art508');n.dots=all('[data-dot511]');n.chestButtons=all('[data-chest511]');n.handButtons=all('[data-hand-pick511]');n.markers=all('[data-mark511]');n.revealArts=all('[data-reveals511] .lk-art508');
 n.players=c.state.luck.players.map(p=>{const row={seat:p.seat};for(const id of['score','status','equip','mini','runner','body','vehicle','guard','trail','edge','gain','locator','gap','pass','reveal-item','reveal-gain','cast-actor','cast-body','cast-ring','cast-hit','cast-bolt','cast-shot'])row[id]=q(`[data-${id}511="${p.seat}"]`);row.vehicleArt=row.vehicle?.querySelector('.lk-art508');row.passBody=row.pass?.querySelector('.lk-pass-body511');row.shotArt=row['cast-shot']?.querySelector('.lk-art508');return row});n.projectileArt=n.projectile?.querySelector('.lk-art508');n.returnArt=n.return?.querySelector('.lk-art508');
 const resize=()=>{const h=n.stage.clientHeight||320,w=n.stage.clientWidth||390;u.trackWidth=Math.max(w,h*3);u.stageWidth=w;style511(root,'--lk-stage-width508',w+'px');style511(root,'--lk-stage-height508',h+'px');style511(root,'--lk-pawn508',Math.max(28,Math.min(66,h*.145-10)).toFixed(1)+'px');style511(root,'--lk-cast-pawn508',Math.min(150,h*.38,w*.32).toFixed(1)+'px');style511(root,'--lk-track-width508',u.trackWidth.toFixed(1)+'px');u.lastPaint=null};resize();const observer=typeof globalThis.ResizeObserver==='function'?new ResizeObserver(resize):null;observer?.observe(n.stage);
 const visible=()=>{if(globalThis.document?.visibilityState==='hidden'){if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null}else{u.lastPaint=null;luckTick511(c)}};globalThis.document?.addEventListener('visibilitychange',visible);u.cleanup=()=>{observer?.disconnect();unlock();globalThis.document?.removeEventListener('visibilitychange',visible)};luckTick511(c);
}
export function requestLuck511(c,kind,index){const g=c.state?.luck,u=ui(c),me=g?.players.find(p=>p.playerId===c.transport.selfId);if(!g||!['chest','hand'].includes(kind)||g.phase!==kind||!me||me.locked||u.pending||!c.ready()||clock(c)>=g.deadline||!Number.isInteger(index)||index<0||index>3)return false;
 u.pending={gameId:g.id,round:g.round,kind,index,at:Date.now()};c.error='';sound511(c,'pick');const sent=c.raw('luck511',{kind,gameId:g.id,round:g.round,index});if(sent===false){u.pending=null;c.error='送信できなかったよ。接続を確認してね。'}u.lastPaint=null;luckTick511(c);return sent!==false;
}
export function luckReceive511(c){const u=c.lkUI511,g=c.state?.luck;if(u?.pending&&(u.pending.gameId!==g?.id||u.pending.round!==g?.round||g.phase!==u.pending.kind||(g.phase==='chest'?g.ownBox:g.ownPick)!==null))u.pending=null}
export function luckError511(c,m){if(['luck507','luck509','luck511'].includes(m.op)&&c.lkUI511)c.lkUI511.pending=null}
export function luckClick511(c,b){const d=b.dataset;if(d.gearSeat511!==undefined){ui(c).gearSeat=Number(d.gearSeat511);ui(c).lastPaint=null;luckTick511(c);return true}if(d.gearClose511!==undefined){ui(c).gearSeat=null;ui(c).lastPaint=null;luckTick511(c);return true}if(d.chest511!==undefined){requestLuck511(c,'chest',Number(d.chest511));return true}if(d.handPick511!==undefined){requestLuck511(c,'hand',Number(d.handPick511));return true}if(!d.lk511Action&&d.lk511Monster===undefined)return false;const g=c.state?.luck;if(!g)return true;const u=ui(c);if(d.lk511Action==='sound'){u.sound=!u.sound;sound511(c,'pick');b.textContent='音 '+(u.sound?'ON':'OFF');b.setAttribute('aria-pressed',String(u.sound));return true}if(d.lk511Action==='reload'){prepareArt(c,true);return true}if(d.lk511Action==='more'){u.limit+=24;c.render();return true}sound511(c,'pick');c.error='';if(d.lk511Monster!==undefined)c.raw('luck511',{gameId:g.id,kind:'select',monsterId:d.lk511Monster});if(d.lk511Action==='start')c.raw('luck511',{gameId:g.id,kind:'start'});return true}
export function luckInput511(c,e){if(e.name!=='luckSearch511')return false;ui(c).search=e.value;c.render();return true}
export function luckKey511(c,e){if(!c.state?.luck||c.partyBrowse462||e.target?.closest?.('input,select,textarea,[contenteditable="true"]')||!/^Digit[1234]$|^Numpad[1234]$/.test(e.code))return false;e.preventDefault();if(!e.repeat)requestLuck511(c,c.state.luck.phase,Number(e.code.at(-1))-1);return true}
function paintCast(c,g,n,u,at){const f=broadcastFrame511(g,at,u.reduced);hide(n.cast,!f);if(!f)return;const a=f.attack,source=g.players[a.source],target=a.targets[0],targetPlayer=target&&g.players[target.target];data(n.cast,'kind',a.item);data(n.cast,'beat',f.beat);data(n.cast,'all',f.all);put(n['cast-counter'],`${f.index+1} / ${g.event.attacks.length}`);put(n['cast-title'],a.volleys.length>1?'装備 '+a.volleys.length+'連発！':item511(a.item).name);for(let i=0;i<n.volleyArts.length;i++){hide(n.volleyArts[i],!a.volleys[i]);if(a.volleys[i])setArt(n.volleyArts[i],a.volleys[i].item)};put(n['cast-who'],`${source.name} → ${f.all?a.targets.length===3?'ほかの全員':a.targets.map(h=>g.players[h.target].name).join('・'):targetPlayer?.name??'ターゲットなし'}`);
 const sameTarget=g.players.filter(p=>p.seat!==a.source);
 for(const p of g.players){const row=n.players[p.seat],hit=a.targets.find(h=>h.target===p.seat),isSource=p.seat===a.source,visible=isSource||!!hit,x=f.all?(isSource?15:42+sameTarget.findIndex(t=>t.seat===p.seat)*23):(isSource?23:76);
  hide(row['cast-actor'],!visible);style511(row['cast-actor'],'left',x+'%');data(row['cast-actor'],'role',isSource?'source':'target');
  const returned=a.targets.find(h=>h.returned)?.returned,impact=hit&&f.impact,returnHit=isSource&&returned&&f.returned;
  const h=returnHit?returned:hit,bang=(impact||returnHit)&&h?.outcome==='hit'&&!u.reduced;
  let angle=bang?Math.sin((f.t-(returnHit ? .79 : .55))*29)*28:0,y=bang?-Math.abs(Math.sin((f.t-(returnHit ? .79 : .55))*18))*24:0;
  style511(row['cast-body'],'transform',`translate3d(0,${y.toFixed(2)}px,0) rotate(${angle.toFixed(2)}deg)`);
  hide(row['cast-ring'],!((impact||returnHit)&&['blocked','reflected'].includes(h?.outcome)));data(row['cast-ring'],'reflect',h?.outcome==='reflected');
  put(row['cast-hit'],impact||returnHit?(h?.hits?.length>1?h.hits.filter(x=>x.outcome==='hit').length+'発 命中':hitLabel511(h)):isSource?'発動！':'');
  const bolt=hit?.hits?.some(h=>h.kind==='lightning');hide(row['cast-bolt'],!(bolt&&f.t>=.48&&f.t<.76));const shot=hit?.hits?.find(h=>h.kind!=='lightning');hide(row['cast-shot'],!shot||f.t<.15||f.t>=.6);if(shot){setArt(row.shotArt,shot.kind);const sx=f.all?15:23;style511(row['cast-shot'],'left',(sx+(x-sx)*f.flight).toFixed(2)+'%');style511(row['cast-shot'],'transform',`translate(-50%,-50%) rotate(${shot.kind==='shell'?f.flight*720:0}deg)`)}
 }
 const miss=!a.targets.length;hide(n.projectile,true);setArt(n.projectileArt,a.item);style511(n.projectile,'left',(23+53*f.flight).toFixed(2)+'%');style511(n.projectile,'transform',`translate(-50%,-50%) rotate(${a.item==='shell'?f.flight*720:0}deg)`);
 const reflection=a.targets.find(h=>h.outcome==='reflected');hide(n.return,!reflection||f.t<.67||f.t>.86);setArt(n.returnArt,a.item);style511(n.return,'left',(76-53*Math.max(0,Math.min(1,(f.t-.67)/.16))).toFixed(2)+'%');
 hide(n.impact,!f.impact||f.t>.73||f.all||miss||u.reduced);style511(n.impact,'left','76%');
 put(n['cast-bottom'],miss?'相手はいなかった！':f.t<.55?'':a.targets.map(h=>`${g.players[h.target].name}：${h.hits?.map(hitLabel511).join(' / ')??hitLabel511(h)}${h.returned&&f.returned?' → '+source.name+' '+hitLabel511(h.returned):''}`).join('　'));
 const cue=`${a.id}:${f.beat}`;if(u.castSound!==cue){u.castSound=cue;if(f.beat==='launch')sound511(c,'attack');if(f.beat==='impact')sound511(c,reflection?'reflect':a.targets.some(h=>h.outcome==='hit')?'hit':'guard')}
}
export function paintLuck511(c,at=clock(c)){
 const g=c.state?.luck,u=c.lkUI511,n=u?.nodes;if(!g||!n||['lobby','result'].includes(g.phase)||globalThis.document?.visibilityState==='hidden')return;
 if(u.pending&&Date.now()-u.pending.at>6000){u.pending=null;c.error='選択を確認できませんでした。もう一度選んでね。';c.refresh?.()}
 const key=paintKey511(g,at,c.ready(),u.pending,u.reduced)+':'+u.artReady+':'+u.artFailed+':'+(c.error??'');if(key===u.lastPaint)return;u.lastPaint=key;
 const me=g.players.find(p=>p.playerId===c.transport.selfId),chest=g.phase==='chest',hand=g.phase==='hand',choosing=chest||hand,revealing=['reveal','dice','broadcast','run','settle'].includes(g.phase),selected=(chest?g.ownBox:g.ownPick)??u.pending?.index,cap=banner511(g,c.transport.selfId);
 data(n.root,'phase',g.phase);data(n.root,'reduced',u.reduced);put(n.round,(g.round===8?'FINAL ROUND':'ROUND '+g.round)+' / 8');put(n.timer,choosing?Math.max(0,Math.ceil((g.deadline-at)/1000))+'秒':'');n.dots.forEach((e,i)=>data(e,'done',i<g.round));
 put(n.banner,cap.title);put(n.sub,cap.sub);hide(n.countdown,g.phase!=='countdown');put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000))===4?'READY':Math.max(1,Math.ceil((g.startAt-at)/1000)));
 hide(n.chests,!chest&&g.phase!=='countdown');hide(n.hand,!hand||!me);hide(n.reveals,!revealing);put(n.instruction,chest?'宝箱を1つ':hand?me?selected!=null?'選択済み · 一斉公開を待とう':'装備を育てる？ 大技で飛ぶ？':'みんなの選択を待とう':g.phase==='dice'?'出目から、育てた力へ':g.phase==='broadcast'?'全員共通のレース中継':g.phase==='reveal'?'みんなの一手':g.phase==='countdown'?'まもなく開幕！':g.phase==='run'?'抜け、追いつけ、追い越せ！':g.round===8?'結果発表へ！':'次の宝箱へ');put(n.selected,choosing?g.players.filter(p=>p.locked).length+' / 4 人':'ROUND '+g.round);put(n.note,hand?g.round===8?'最後は必ず大技入り。貯めた力を解放しよう！':'自己バフは育ち続ける。倍率を重ねて、大技で解放！':chest?'見た目と確率は、4つとも同じ。':'');
 for(let i=0;i<4;i++){const b=n.chestButtons[i];property506(b,'disabled',!chest||!me||selected!=null||!c.ready()||at>=g.deadline);attr(b,'aria-pressed',chest&&selected===i);put(b?.querySelector('span'),chest&&selected===i?'✓':'選ぶ');const h=n.handButtons[i],it=item511(g.hand?.[i]);property506(h,'disabled',!hand||!me||selected!=null||!c.ready()||at>=g.deadline);attr(h,'aria-pressed',hand&&selected===i);if(g.hand){setArt(h.querySelector('.lk-art508'),it.id);put(h.querySelector('b'),it.name);put(h.querySelector('p'),it.detail);put(h.querySelector('.lk-item-type508'),it.type);data(h,'type',it.type);attr(h,'aria-label',it.name+'。'+it.detail)}}
 const frame=raceFrame511(g,at,c.transport.selfId,u.reduced),offsets=courseOffsets511(frame,u.stageWidth??390,u.trackWidth??960);data(n.root,'direction',frame.direction);style511(n.root,'--lk-velocity511',String(frame.speed));
 style511(n.ground,'transform',`translate3d(${-offsets.ground.toFixed(2)}px,0,0)`);style511(n.horizon,'transform',`translate3d(${-offsets.horizon.toFixed(2)}px,0,0)`);style511(n.near,'transform',`translate3d(${-offsets.near.toFixed(2)}px,0,0)`);style511(n.speed,'opacity',String(frame.speed*.85));
 for(let i=0;i<n.markers.length;i++){const e=n.markers[i],m=frame.marks[i];hide(e,m.hidden);style511(e,'transform',`translate3d(${m.x.toFixed(3)}%,0,0)`);put(e.querySelector('b'),markerLabel511(m.distance));attr(e,'title',fullDistance511(m.distance))}
 for(const p of g.players){const r=n.players[p.seat],f=frame.rows[p.seat],event=g.event?.rows[p.seat];put(r.score,distance511(f.exact));attr(r.score,'title',fullDistance511(f.exact));put(r.status,choosing?p.locked?'✓ セット':p.ai?'AI · 選択中':p.connected?'選択中':'おまかせ待ち':f.rank+'位');put(r.equip,equipment511(p));attr(r.equip,'title',equipment511(p));style511(r.mini,'left',f.mini.toFixed(2)+'%');style511(r.mini,'top',(p.seat*7)+'px');
  hide(r.runner,!f.visible);if(f.visible)style511(r.runner,'transform',`translate3d(${f.x.toFixed(4)}%,0,0)`);style511(r.body,'transform',`translate3d(-50%,${f.y.toFixed(2)}px,0) rotate(${f.angle.toFixed(2)}deg)`);hide(r.trail,!f.trail);hide(r.guard,!f.guard);hide(r.vehicle,!f.trail&&!(g.phase==='run'&&f.item==='spring'));setArt(r.vehicleArt,f.item);put(r.edge,f.offscreen==='left'?'◀':f.offscreen==='right'?'▶':'');data(r.runner,'offscreen',f.offscreen);data(r.runner,'focus',f.focus);data(r.runner,'moving',f.moving);data(r.runner,'direction',f.direction);hide(r.locator,!f.offscreen||!!f.afterimage);data(r.locator,'side',f.offscreen);put(r.gap,f.gapLabel);attr(r.locator,'aria-label',p.name+' '+f.gapLabel);hide(r.pass,!f.afterimage);if(f.afterimage){style511(r.pass,'transform',`translate3d(${f.afterimage.x.toFixed(3)}%,0,0)`);style511(r.pass,'opacity',f.afterimage.opacity.toFixed(3));data(r.pass,'direction',f.afterimage.direction)}hide(r.gain,g.phase!=='settle');put(r.gain,delta511(f.delta));
  if(event){const it=item511(event.item);setArt(n.revealArts[p.seat],it.id);put(r['reveal-item'],it.name);put(r['reveal-gain'],g.phase==='settle'?delta511(event.delta):it.type)}
 }
 put(n['map-end'],distance511(frame.domain));paintGear(c,g,n,u);paintCast(c,g,n,u,at);paintDice(c,g,n,u,at);hide(n.offline,c.ready());hide(n.error,!c.error);put(n.error,c.error??'');hide(n['art-status'],u.artReady);if(u.artFailed)hide(n['art-status']?.querySelector('button'),false);
 const cue=[g.id,g.round,g.phase,g.phase==='countdown'?n.count.textContent:''].join(':');if(u.soundKey!==cue){u.soundKey=cue;const kind={countdown:'count',hand:'open',reveal:'open',run:'launch',settle:g.round===8?'finish':'settle'}[g.phase];if(kind)sound511(c,kind);put(n.reader,cap.title+(g.phase==='settle'?g.players.map(p=>p.name+' '+p.distance+'メートル').join('、'):''))}
}
export function luckTick511(c){const u=c.lkUI511,g=c.state?.luck;if(!u?.nodes||!g||globalThis.document?.visibilityState==='hidden'||u.raf!=null)return;const at=clock(c),key=paintKey511(g,at,c.ready(),u.pending,u.reduced)+':'+u.artReady+':'+u.artFailed+':'+(c.error??'');if(key===u.lastPaint&&!animating511(g,at,u.reduced)&&!(u.pending&&Date.now()-u.pending.at>6000))return;if(typeof globalThis.requestAnimationFrame!=='function'){paintLuck511(c);return}u.raf=globalThis.requestAnimationFrame(()=>{u.raf=null;paintLuck511(c);if(u.nodes&&animating511(c.state?.luck,clock(c),u.reduced))luckTick511(c)})}

function gearPanel(c,g){return`<aside class="lk-gear-panel509" data-gear-panel511 hidden aria-label="装備一覧"><header><b data-gear-title511></b><button data-gear-close511="1" aria-label="装備一覧を閉じる">×</button></header><nav>${g.players.map(p=>`<button data-gear-seat511="${p.seat}" style="--player:${color(p)}">${name(c,p)}</button>`).join('')}</nav><p class="lk-buff-status511" data-gear-status511></p><div data-gear-list511>${Array.from({length:40},()=>`<article data-gear-slot511 hidden>${art511('dash')}<b></b><p></p></article>`).join('')}</div><p>選んだ手札は、一斉公開まで秘密。制限時間は進むよ。</p></aside>`}
function paintGear(c,g,n,u){const p=g.players[u.gearSeat];hide(n['gear-panel'],!p);if(!p)return;const revealed=['reveal','dice','broadcast','run'].includes(g.phase),source=revealed?{...p,...g.event.rows[p.seat]}:p,gears=gearList511(source);put(n['gear-status'],buffStatus511(source,g.round));put(n['gear-title'],p.name+' · '+equipment511(source).replace(' ▾',''));for(let i=0;i<n.gearSlots.length;i++){const e=n.gearSlots[i],gear=gears[i];hide(e,!gear);if(gear){const it=item511(gear.id);setArt(e.querySelector('.lk-art508'),it.id);put(e.querySelector('b'),it.name+' ×'+gear.count);put(e.querySelector('p'),it.detail)}}}

function edgeIndicators(c,g){return g.players.map(p=>`<div class="lk-locator511" data-locator511="${p.seat}" hidden style="--player:${color(p)};top:${[43.5,58,72.5,87][p.seat]}%"><i class="lk-locator-arrow511"></i><span class="lk-locator-portrait511">${portrait(c,p)}</span><small data-gap511="${p.seat}"></small></div><div class="lk-pass511" data-pass511="${p.seat}" hidden aria-hidden="true" style="--player:${color(p)};top:${[43.5,58,72.5,87][p.seat]}%"><div class="lk-pass-body511">${portrait(c,p)}</div><i></i></div>`).join('')}

// Exact pip layouts are code-native; the generated atlas is never used as a roll result.
export function diceCube511(index){const pips={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]};return `<div class="lk-die-lift511" data-dice-lift511="${index}"><div class="lk-die511" data-dice-cube511="${index}" role="img">${[1,2,3,4,5,6].map(face=>`<div class="lk-die-face511" data-face="${face}" aria-hidden="true">${pips[face].map(cell=>`<i style="grid-area:${Math.ceil(cell/3)}/${(cell-1)%3+1}"></i>`).join('')}</div>`).join('')}</div></div>`}
function diceStage(c,g){return `<section class="lk-dice-stage511" data-dice-stage511 hidden aria-label="全員共通のサイコロ中継"><header><span>LUCK ROLL</span><small data-dice-counter511></small></header><div class="lk-dice-owner511">${g.players.map(p=>`<span data-dice-actor511="${p.seat}" hidden style="--player:${color(p)}">${portrait(c,p)}<b>${name(c,p)}</b></span>`).join('')}</div><h2 data-dice-name511></h2><div class="lk-dice-table511">${[0,1,2].map(diceCube511).join('')}</div><p class="lk-dice-focus511" data-dice-focus511></p><strong class="lk-dice-formula511" data-dice-formula511></strong><p class="lk-dice-buffs511" data-dice-buffs511></p><div class="lk-dice-payoff511"><small data-dice-caption511></small><strong data-dice-power511></strong></div><i class="lk-dice-rays511" aria-hidden="true"></i></section>`}
function paintDice(c,g,n,u,at){const f=diceFrame511(g,at,u.reduced);hide(n['dice-stage'],!f);if(!f)return;data(n['dice-stage'],'done',f.done);data(n['dice-stage'],'impact',f.impact&&!u.reduced);put(n['dice-name'],item511(f.row.item).name);put(n['dice-counter'],`${f.index+1} / ${g.event.diceOrder.length}`);n.diceActors.forEach((e,i)=>hide(e,i!==f.seat));
 for(let i=0;i<3;i++){const d=f.dice[i],e=n.diceCubes[i];hide(n.diceLifts[i],!d);if(!d)continue;style511(n.diceLifts[i],'transform',`translateY(${d.lift.toFixed(2)}px)`);style511(e,'transform',`rotateX(${d.x.toFixed(2)}deg) rotateY(${d.y.toFixed(2)}deg) rotateZ(${d.z.toFixed(2)}deg)`);data(e,'landed',d.landed);attr(e,'aria-label',d.landed?`${d.value}の目`:'サイコロを振っています')}
 put(n['dice-formula'],f.formula);put(n['dice-buffs'],f.done?f.powers:'');put(n['dice-power'],f.power);attr(n['dice-power'],'title',f.done?fullDistance511(f.row.calculation.planned):'');put(n['dice-caption'],f.done?'バフ込みの発進パワー':'');put(n['dice-focus'],f.row.calculation.focus?'出目バフ +'+f.row.calculation.focus+'（最大6）':'');
 const cue=g.id+':'+g.round+':'+f.cue;if(u.diceSound!==cue){u.diceSound=cue;sound511(c,f.done?'jackpot':f.landed?'land':'roll');if(f.done)put(n.reader,g.players[f.seat].name+'、'+f.formula+'。バフ込みの発進パワー'+fullDistance511(f.row.calculation.planned))}
}
