import {playerColor499} from '../party/PartyColors499.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
import {property506,style506 as ordinaryStyle509} from '../gorilla/Performance506.js';
import {ITEMS509,item509,LUCK509} from './Rules509.js';
import {raceFrame509,broadcastFrame509,banner509,paintKey509,delta509,equipment509,hitLabel509,distance509,fullDistance509,formula509,gearList509} from './Presentation509.js';
import {sound509} from './Audio509.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style509=(el,key,value)=>{if(!el)return;if(key.startsWith('--')){if(el.style.getPropertyValue(key)!==value)el.style.setProperty(key,value)}else ordinaryStyle509(el,key,value)};
const ui=c=>c.lkUI509??={sound:true,pending:null,limit:24,search:'',artReady:false};
const clock=c=>Date.now()+(c.offset??0);
const portrait=(c,p)=>c.sgMonster463?.(p.choice?.speciesId??p.speciesId)??'';
const name=(c,p)=>p.playerId===c.transport.selfId?'あなた':esc(p.name);
const color=p=>playerColor499(p).hex;
export const art509=id=>`<i class="lk-art508" data-item="${id}" data-atlas="${item509(id).atlas}" style="--tile-x:${item509(id).tile%4};--tile-y:${Math.floor(item509(id).tile/4)}" aria-hidden="true"></i>`;
const oldArt=tile=>`<i class="lk-art507" data-tile="${tile}" aria-hidden="true"></i>`;
const header=c=>`<header class="lk-header507"><button data-party-action462="browse">‹ パーティー</button><div><small>LUCK ONLY GAMES</small><b>運だけ大運動会</b></div><button data-lk509-action="sound" aria-pressed="${ui(c).sound}">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),p=c.state.party,me=g.members.find(m=>m.playerId===c.transport.selfId),pm=p.members.find(m=>m.playerId===c.transport.selfId),host=p.hostId===c.transport.selfId,all=c.roster().filter(m=>!u.search||c.sgSpeciesName463(m.raceSpeciesId??m.speciesId).includes(u.search));return`<section class="lk507 lk508 lk509 lk-lobby508">${header(c)}<div class="lk-cover507"><div class="lk-cover-copy507"><small>運を引け。相手を読め。</small><h1>運だけ<br><em>大運動会</em></h1><p>積んで、育てて、ぶっ飛ばせ。</p></div><div class="lk-cover-props508">${art509('shell')}${oldArt(0)}${art509('turbo')}</div></div><div class="lk-body507"><div class="lk-facts507"><b>全8ラウンド</b><b>運 × 読み合い</b><b>4人・参加無料</b></div><ol class="lk-rules507"><li>4つの宝箱から1つ選ぶ。</li><li>中身はランダムな4アイテム。使う1つを選ぶ。</li><li>装備は残り、毎ターン自動発動。重ねると効果も成長！</li><li>8ラウンド後、いちばん遠くにいた人が優勝。</li></ol><p class="lk-note507">防御は先に発動。攻撃同士の順番は毎回ランダム。選ぶ速さや魔物の強さに差はないよ。選んだ継続装備は残る。大技とゲートは1回きり。選ばなかった3枚は消え、次もランダムな4枚。装備は相手の欄をタップして確認できるよ。空席はAIが走るよ。</p><details class="lk-catalog508"><summary>28種類のアイテムを見る · 20種類は継続装備</summary><div>${ITEMS509.map(it=>`<article>${art509(it.id)}<b>${it.name}</b><p>${it.detail}</p></article>`).join('')}</div></details><h2>運を託す、相棒を選ぼう</h2><input name="luckSearch509" class="lk-search507" value="${esc(u.search)}" placeholder="魔物の名前で探す" aria-label="魔物の名前で探す"><div class="lk-roster507">${all.slice(0,u.limit).map(m=>`<button data-lk509-monster="${esc(m.id)}" aria-pressed="${m.id===me?.choice?.id}" ${!c.ready()||!me?'disabled':''}>${portrait(c,{speciesId:m.raceSpeciesId??m.speciesId})}<b>${esc(c.sgSpeciesName463(m.raceSpeciesId??m.speciesId))}</b></button>`).join('')||'<p>見つかりませんでした。</p>'}</div>${all.length>u.limit?'<button data-lk509-action="more">もっと見る</button>':''}${partySeats462(c)}</div><footer class="lk-lobby-actions507"><p role="alert" ${c.error?'':'hidden'}>${esc(c.error)}</p><button class="lk-primary507" data-party-action462="ready" aria-pressed="${!!pm?.ready}" ${!c.ready()||!me?.choice||!u.artReady?'disabled':''}>${!u.artReady?'競技場を準備中…':pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${u.artFailed?'<button data-lk509-action="reload">画像を再読み込み</button>':''}${host?`<button class="lk-primary507" data-lk509-action="start" ${!c.ready()||!u.artReady||p.members.some(m=>!m.ready||!m.connected||m.atHome)?'disabled':''}>大運動会、開幕！</button><button data-party-action462="lounge">ミニゲーム一覧へ戻る</button>`:'<p>部屋主が開始すると、4人で出走！</p>'}</footer></section>`}
function cards(c,g){return`<div class="lk-players507 lk-players508">${g.players.map(p=>`<article style="--player:${color(p)}"><span>${portrait(c,p)}</span><b>${name(c,p)}</b><strong data-score509="${p.seat}">${distance509(p.distance)}</strong><small data-status509="${p.seat}"></small><button class="lk-gear-button509" data-gear-seat509="${p.seat}" aria-label="${name(c,p)}の装備を確認"><span data-equip509="${p.seat}"></span></button></article>`).join('')}</div>`}
function runners(c,g){return g.players.map(p=>`<div class="lk-runner508" data-runner509="${p.seat}" style="--player:${color(p)};top:${[43.5,58,72.5,87][p.seat]}%"><div class="lk-trail508" data-trail509="${p.seat}" hidden></div><i class="lk-shadow508"></i><div class="lk-motion508" data-body509="${p.seat}"><div class="lk-vehicle508" data-vehicle509="${p.seat}" hidden>${art509('rocket')}</div><div class="lk-aura508" data-guard509="${p.seat}" hidden></div>${portrait(c,p)}</div><b>${name(c,p)}</b><span data-edge509="${p.seat}" class="lk-edge508"></span><em data-gain509="${p.seat}" hidden></em></div>`).join('')}
function broadcast(c,g){return`<div class="lk-broadcast508" data-cast509 hidden aria-label="全員共通の攻撃中継"><div class="lk-cast-top508"><b><i></i> LIVE</b><span data-cast-counter509></span><strong data-cast-title509></strong></div><div class="lk-cast-speed508"></div><div class="lk-volley509" data-volley509>${Array.from({length:9},()=>art509('shell')).join('')}</div><div class="lk-cast-who508" data-cast-who509></div><div class="lk-cast-actors508">${g.players.map(p=>`<div class="lk-cast-actor508" data-cast-actor509="${p.seat}" style="--player:${color(p)}"><i class="lk-cast-ring508" data-cast-ring509="${p.seat}" hidden></i><div class="lk-cast-sprite508" data-cast-body509="${p.seat}">${portrait(c,p)}</div><b>${name(c,p)}</b><strong data-cast-hit509="${p.seat}"></strong><i class="lk-thunder508" data-cast-bolt509="${p.seat}" hidden></i></div>`).join('')}</div>${g.players.map(p=>`<div class="lk-shot509" data-cast-shot509="${p.seat}" hidden>${art509('shell')}</div>`).join('')}<div class="lk-projectile508" data-projectile509>${art509('shell')}</div><div class="lk-return508" data-return509 hidden>${art509('shell')}</div><div class="lk-impact508" data-impact509 hidden></div><div class="lk-cast-bottom508" data-cast-bottom509></div></div>`}
function play(c,g){return`<section class="lk507 lk508 lk509 lk-play508" data-phase="${g.phase}">${header(c)}${cards(c,g)}<div class="lk-round507"><span data-round509></span><div>${Array.from({length:8},(_,i)=>`<i data-dot509="${i+1}"></i>`).join('')}</div><b data-timer509></b></div><div class="lk-minimap508" aria-label="全員のコース上の位置"><span>START</span><div>${g.players.map(p=>`<i data-mini509="${p.seat}" style="--player:${color(p)}" title="${esc(p.name)}">${p.seat+1}</i>`).join('')}</div><span data-map-end509></span></div><div class="lk-stage508" data-stage509><div class="lk-course508" data-ground509></div><div class="lk-course508 lk-horizon508" data-horizon509></div><div class="lk-markers508">${Array.from({length:7},(_,i)=>`<i data-mark509="${i}"><b></b></i>`).join('')}</div><div class="lk-speed508" data-speed509></div><div class="lk-banner508"><strong data-banner509></strong><span data-sub509></span></div>${runners(c,g)}<div class="lk-countdown508" data-countdown509 hidden>${oldArt(2)}<small>運を引け。相手を読め。</small><strong data-count509></strong></div>${power(c,g)}${broadcast(c,g)}${gearPanel(c,g)}<div class="lk-art-status507" data-art-status509 ${ui(c).artReady?'hidden':''}>競技場を準備中…<button data-lk509-action="reload" ${ui(c).artFailed?'':'hidden'}>画像を再読み込み</button></div></div><footer class="lk-controls508"><div class="lk-control-title507"><strong data-instruction509></strong><span data-selected509></span></div><div class="lk-chests508" data-chests509>${[0,1,2,3].map(i=>`<button data-chest509="${i}" aria-label="${i+1}番の宝箱を選ぶ" aria-pressed="false" disabled>${oldArt(0)}<b>${['Ⅰ','Ⅱ','Ⅲ','Ⅳ'][i]}</b><span>選ぶ</span></button>`).join('')}</div><div class="lk-hand508" data-hand509 hidden>${[0,1,2,3].map(i=>`<button data-hand-pick509="${i}" aria-label="${i+1}枚目のアイテム" aria-pressed="false" disabled><span class="lk-item-type508"></span>${art509('dash')}<b></b><p></p><span class="lk-item-check508">✓ SET</span></button>`).join('')}</div><div class="lk-reveals508" data-reveals509 hidden>${g.players.map(p=>`<article style="--player:${color(p)}"><b>${name(c,p)}</b>${art509('dash')}<strong data-reveal-item509="${p.seat}"></strong><span data-reveal-gain509="${p.seat}"></span></article>`).join('')}</div><p class="lk-note508" data-note509></p><p class="lk-error507" data-error509 role="alert" hidden></p></footer><div class="lk-offline507" data-offline509 hidden role="status">再接続中… 未選択なら、おまかせで進むよ。<button data-race-action="refresh">接続を確認</button></div><span class="lk-reader507" data-reader509 aria-live="polite"></span></section>`}
function result(c,g){const winners=g.results.filter(r=>r.rank===1),winner=g.players.find(p=>p.playerId===winners[0].playerId);return`<section class="lk507 lk508 lk509 lk-result508">${header(c)}<div class="lk-victory507"><small>LUCK & THE LAST MOVE</small><h1>${winners.length>1?'同着、優勝！':name(c,winner)+'、優勝！'}</h1>${oldArt(2)}<div class="lk-winners507">${winners.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<div style="--player:${color(p)}">${portrait(c,p)}<b>${name(c,p)}</b></div>`}).join('')}</div><strong>${distance509(winner.distance)}</strong><p class="lk-exact509">${fullDistance509(winner.distance)}</p><p>育てた装備で、ここまで飛んだ。</p></div>${resultActions490(c)}<div class="lk-body507"><h2>最終順位</h2><div class="lk-results507">${g.results.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<article style="--player:${color(p)}"><b>${r.rank}<small>位</small></b>${portrait(c,p)}<span><strong>${name(c,p)}</strong><small>${equipment509(p)||'FINISH'}</small><small>${fullDistance509(r.distance)}</small></span><em>${distance509(r.distance)}</em></article>`}).join('')}</div><details class="lk-history507 lk-history508"><summary>8ラウンドの勝負を振り返る</summary>${g.history.map(e=>`<div><b>ROUND ${e.round}</b><div>${e.rows.map(r=>{const p=g.players[r.seat],it=item509(r.item);return`<span style="--player:${color(p)}"><b>${name(c,p)}</b>${art509(it.id)}<small>${it.name}</small><strong>${delta509(r.delta)}</strong></span>`}).join('')}</div></div>`).join('')}</details></div></section>`}
export function luckView509(c){const g=c.state?.luck;if(!g)return'';const u=ui(c);if(u.gameId!==g.id){u.gameId=g.id;u.pending=null;u.gearSeat=null;u.limit=24;u.search='';u.lastPaint=null;u.soundKey=null}return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
const put=(e,t)=>e&&property506(e,'textContent',String(t)),hide=(e,v)=>e&&property506(e,'hidden',!!v),data=(e,k,v)=>{if(e&&e.dataset[k]!==String(v))e.dataset[k]=String(v)},attr=(e,k,v)=>{if(e?.getAttribute(k)!==String(v))e?.setAttribute(k,String(v))};
const setArt=(e,id)=>{if(!e||e.dataset.item===id)return;const it=item509(id);data(e,'item',id);data(e,'atlas',it.atlas);style509(e,'--tile-x',String(it.tile%4));style509(e,'--tile-y',String(Math.floor(it.tile/4)))};
function prepareArt(c,retry=false){const u=ui(c);if(u.loading||(u.artReady||u.artFailed)&&!retry||typeof globalThis.Image!=='function')return;u.loading=true;u.artFailed=false;const urls=['./assets/luck507/stadium.png','./assets/luck507/items.png','./assets/luck508/items.png','./assets/luck508/course.png','./assets/luck509/items.png'];Promise.all(urls.map(src=>new Promise(resolve=>{const im=new Image();let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);im.onload=im.onerror=null;resolve(ok)},timer=setTimeout(()=>finish(false),15000);im.onload=()=>{if(im.decode)im.decode().then(()=>finish(im.naturalWidth>0)).catch(()=>finish(false));else finish(im.naturalWidth>0)};im.onerror=()=>finish(false);im.src=src}))).then(ok=>{u.loading=false;u.artReady=ok.every(Boolean);u.artFailed=!u.artReady;u.lastPaint=null;if(c.root?.querySelector('.lk-lobby508'))c.render();else luckTick509(c)})}
export function luckBefore509(c){const u=c.lkUI509;if(!u)return;if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null;u.cleanup?.();u.cleanup=null;u.nodes=null;u.lastPaint=null}
export function luckDispose509(c){luckBefore509(c);const u=c.lkUI509;if(u){u.pending=null;u.audio?.close().catch(()=>{});u.audio=null}}
export function luckAfter509(c){const root=c.root?.querySelector('.lk509');if(!root)return;const u=ui(c);u.reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;prepareArt(c);if(!root.classList.contains('lk-play508'))return;const unlock=lockPlayZoom498(root),q=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 u.nodes={root};for(const id of['power','gear-panel','gear-title','gear-list','volley','stage','round','timer','map-end','banner','sub','countdown','count','chests','hand','reveals','instruction','selected','note','error','offline','art-status','reader','ground','horizon','speed','cast','cast-counter','cast-title','cast-who','cast-bottom','projectile','return','impact'])u.nodes[id]=q(`[data-${id}509]`);
 const n=u.nodes;n.powerRows=all('[data-power-row509]');n.gearSlots=all('[data-gear-slot509]');n.volleyArts=all('[data-volley509] .lk-art508');n.dots=all('[data-dot509]');n.chestButtons=all('[data-chest509]');n.handButtons=all('[data-hand-pick509]');n.markers=all('[data-mark509]');n.revealArts=all('[data-reveals509] .lk-art508');
 n.players=c.state.luck.players.map(p=>{const row={seat:p.seat};for(const id of['score','status','equip','mini','runner','body','vehicle','guard','trail','edge','gain','reveal-item','reveal-gain','cast-actor','cast-body','cast-ring','cast-hit','cast-bolt','cast-shot'])row[id]=q(`[data-${id}509="${p.seat}"]`);row.vehicleArt=row.vehicle?.querySelector('.lk-art508');row.shotArt=row['cast-shot']?.querySelector('.lk-art508');return row});n.projectileArt=n.projectile?.querySelector('.lk-art508');n.returnArt=n.return?.querySelector('.lk-art508');
 const resize=()=>{const h=n.stage.clientHeight||320,w=n.stage.clientWidth||390;u.trackWidth=Math.max(w,h*3);u.stageWidth=w;style509(root,'--lk-stage-width508',w+'px');style509(root,'--lk-stage-height508',h+'px');style509(root,'--lk-pawn508',Math.max(28,Math.min(66,h*.145-10)).toFixed(1)+'px');style509(root,'--lk-cast-pawn508',Math.min(150,h*.38,w*.32).toFixed(1)+'px');style509(root,'--lk-track-width508',u.trackWidth.toFixed(1)+'px');u.lastPaint=null};resize();const observer=typeof globalThis.ResizeObserver==='function'?new ResizeObserver(resize):null;observer?.observe(n.stage);
 const visible=()=>{if(globalThis.document?.visibilityState==='hidden'){if(u.raf!=null)globalThis.cancelAnimationFrame?.(u.raf);u.raf=null}else{u.lastPaint=null;luckTick509(c)}};globalThis.document?.addEventListener('visibilitychange',visible);u.cleanup=()=>{observer?.disconnect();unlock();globalThis.document?.removeEventListener('visibilitychange',visible)};luckTick509(c);
}
export function requestLuck509(c,kind,index){const g=c.state?.luck,u=ui(c),me=g?.players.find(p=>p.playerId===c.transport.selfId);if(!g||!['chest','hand'].includes(kind)||g.phase!==kind||!me||me.locked||u.pending||!c.ready()||clock(c)>=g.deadline||!Number.isInteger(index)||index<0||index>3)return false;
 u.pending={gameId:g.id,round:g.round,kind,index,at:Date.now()};c.error='';sound509(c,'pick');const sent=c.raw('luck509',{kind,gameId:g.id,round:g.round,index});if(sent===false){u.pending=null;c.error='送信できなかったよ。接続を確認してね。'}u.lastPaint=null;luckTick509(c);return sent!==false;
}
export function luckReceive509(c){const u=c.lkUI509,g=c.state?.luck;if(u?.pending&&(u.pending.gameId!==g?.id||u.pending.round!==g?.round||g.phase!==u.pending.kind||(g.phase==='chest'?g.ownBox:g.ownPick)!==null))u.pending=null}
export function luckError509(c,m){if(['luck507','luck509'].includes(m.op)&&c.lkUI509)c.lkUI509.pending=null}
export function luckClick509(c,b){const d=b.dataset;if(d.gearSeat509!==undefined){ui(c).gearSeat=Number(d.gearSeat509);ui(c).lastPaint=null;luckTick509(c);return true}if(d.gearClose509!==undefined){ui(c).gearSeat=null;ui(c).lastPaint=null;luckTick509(c);return true}if(d.chest509!==undefined){requestLuck509(c,'chest',Number(d.chest509));return true}if(d.handPick509!==undefined){requestLuck509(c,'hand',Number(d.handPick509));return true}if(!d.lk509Action&&d.lk509Monster===undefined)return false;const g=c.state?.luck;if(!g)return true;const u=ui(c);if(d.lk509Action==='sound'){u.sound=!u.sound;sound509(c,'pick');b.textContent='音 '+(u.sound?'ON':'OFF');b.setAttribute('aria-pressed',String(u.sound));return true}if(d.lk509Action==='reload'){prepareArt(c,true);return true}if(d.lk509Action==='more'){u.limit+=24;c.render();return true}sound509(c,'pick');c.error='';if(d.lk509Monster!==undefined)c.raw('luck509',{gameId:g.id,kind:'select',monsterId:d.lk509Monster});if(d.lk509Action==='start')c.raw('luck509',{gameId:g.id,kind:'start'});return true}
export function luckInput509(c,e){if(e.name!=='luckSearch509')return false;ui(c).search=e.value;c.render();return true}
export function luckKey509(c,e){if(!c.state?.luck||c.partyBrowse462||e.target?.closest?.('input,select,textarea,[contenteditable="true"]')||!/^Digit[1234]$|^Numpad[1234]$/.test(e.code))return false;e.preventDefault();if(!e.repeat)requestLuck509(c,c.state.luck.phase,Number(e.code.at(-1))-1);return true}
function paintCast(c,g,n,u,at){const f=broadcastFrame509(g,at,u.reduced);hide(n.cast,!f);if(!f)return;const a=f.attack,source=g.players[a.source],target=a.targets[0],targetPlayer=target&&g.players[target.target];data(n.cast,'kind',a.item);data(n.cast,'beat',f.beat);data(n.cast,'all',f.all);put(n['cast-counter'],`${f.index+1} / ${g.event.attacks.length}`);put(n['cast-title'],a.volleys.length>1?'装備 '+a.volleys.length+'連発！':item509(a.item).name);for(let i=0;i<n.volleyArts.length;i++){hide(n.volleyArts[i],!a.volleys[i]);if(a.volleys[i])setArt(n.volleyArts[i],a.volleys[i].item)};put(n['cast-who'],`${source.name} → ${f.all?a.targets.length===3?'ほかの全員':a.targets.map(h=>g.players[h.target].name).join('・'):targetPlayer?.name??'ターゲットなし'}`);
 const sameTarget=g.players.filter(p=>p.seat!==a.source);
 for(const p of g.players){const row=n.players[p.seat],hit=a.targets.find(h=>h.target===p.seat),isSource=p.seat===a.source,visible=isSource||!!hit,x=f.all?(isSource?15:42+sameTarget.findIndex(t=>t.seat===p.seat)*23):(isSource?23:76);
  hide(row['cast-actor'],!visible);style509(row['cast-actor'],'left',x+'%');data(row['cast-actor'],'role',isSource?'source':'target');
  const returned=a.targets.find(h=>h.returned)?.returned,impact=hit&&f.impact,returnHit=isSource&&returned&&f.returned;
  const h=returnHit?returned:hit,bang=(impact||returnHit)&&h?.outcome==='hit'&&!u.reduced;
  let angle=bang?Math.sin((f.t-(returnHit ? .79 : .55))*29)*28:0,y=bang?-Math.abs(Math.sin((f.t-(returnHit ? .79 : .55))*18))*24:0;
  style509(row['cast-body'],'transform',`translate3d(0,${y.toFixed(2)}px,0) rotate(${angle.toFixed(2)}deg)`);
  hide(row['cast-ring'],!((impact||returnHit)&&['blocked','reflected'].includes(h?.outcome)));data(row['cast-ring'],'reflect',h?.outcome==='reflected');
  put(row['cast-hit'],impact||returnHit?(h?.hits?.length>1?h.hits.filter(x=>x.outcome==='hit').length+'発 命中':hitLabel509(h)):isSource?'発動！':'');
  const bolt=hit?.hits?.some(h=>h.kind==='lightning');hide(row['cast-bolt'],!(bolt&&f.t>=.48&&f.t<.76));const shot=hit?.hits?.find(h=>h.kind!=='lightning');hide(row['cast-shot'],!shot||f.t<.15||f.t>=.6);if(shot){setArt(row.shotArt,shot.kind);const sx=f.all?15:23;style509(row['cast-shot'],'left',(sx+(x-sx)*f.flight).toFixed(2)+'%');style509(row['cast-shot'],'transform',`translate(-50%,-50%) rotate(${shot.kind==='shell'?f.flight*720:0}deg)`)}
 }
 const miss=!a.targets.length;hide(n.projectile,true);setArt(n.projectileArt,a.item);style509(n.projectile,'left',(23+53*f.flight).toFixed(2)+'%');style509(n.projectile,'transform',`translate(-50%,-50%) rotate(${a.item==='shell'?f.flight*720:0}deg)`);
 const reflection=a.targets.find(h=>h.outcome==='reflected');hide(n.return,!reflection||f.t<.67||f.t>.86);setArt(n.returnArt,a.item);style509(n.return,'left',(76-53*Math.max(0,Math.min(1,(f.t-.67)/.16))).toFixed(2)+'%');
 hide(n.impact,!f.impact||f.t>.73||f.all||miss||u.reduced);style509(n.impact,'left','76%');
 put(n['cast-bottom'],miss?'相手はいなかった！':f.t<.55?'':a.targets.map(h=>`${g.players[h.target].name}：${h.hits?.map(hitLabel509).join(' / ')??hitLabel509(h)}${h.returned&&f.returned?' → '+source.name+' '+hitLabel509(h.returned):''}`).join('　'));
 const cue=`${a.id}:${f.beat}`;if(u.castSound!==cue){u.castSound=cue;if(f.beat==='launch')sound509(c,'attack');if(f.beat==='impact')sound509(c,reflection?'reflect':a.targets.some(h=>h.outcome==='hit')?'hit':'guard')}
}
export function paintLuck509(c,at=clock(c)){
 const g=c.state?.luck,u=c.lkUI509,n=u?.nodes;if(!g||!n||['lobby','result'].includes(g.phase)||globalThis.document?.visibilityState==='hidden')return;
 if(u.pending&&Date.now()-u.pending.at>6000){u.pending=null;c.error='選択を確認できませんでした。もう一度選んでね。';c.refresh?.()}
 const key=paintKey509(g,at,c.ready(),u.pending,u.reduced)+':'+u.artReady+':'+u.artFailed+':'+(c.error??'');if(key===u.lastPaint)return;u.lastPaint=key;
 const me=g.players.find(p=>p.playerId===c.transport.selfId),chest=g.phase==='chest',hand=g.phase==='hand',choosing=chest||hand,revealing=['reveal','power','broadcast','run','settle'].includes(g.phase),selected=(chest?g.ownBox:g.ownPick)??u.pending?.index,cap=banner509(g,c.transport.selfId);
 data(n.root,'phase',g.phase);data(n.root,'reduced',u.reduced);put(n.round,(g.round===8?'FINAL ROUND':'ROUND '+g.round)+' / 8');put(n.timer,choosing?Math.max(0,Math.ceil((g.deadline-at)/1000))+'秒':'');n.dots.forEach((e,i)=>data(e,'done',i<g.round));
 put(n.banner,cap.title);put(n.sub,cap.sub);hide(n.countdown,g.phase!=='countdown');put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000))===4?'READY':Math.max(1,Math.ceil((g.startAt-at)/1000)));
 hide(n.chests,!chest&&g.phase!=='countdown');hide(n.hand,!hand||!me);hide(n.reveals,!revealing);put(n.instruction,chest?'宝箱を1つ':hand?me?selected!=null?'選択済み · 一斉公開を待とう':'装備を育てる？ 大技で飛ぶ？':'みんなの選択を待とう':g.phase==='power'?'発進前のパワー · 攻撃で変わる！':g.phase==='broadcast'?'全員共通のレース中継':g.phase==='reveal'?'みんなの一手':g.phase==='countdown'?'まもなく開幕！':g.phase==='run'?'抜け、追いつけ、追い越せ！':g.round===8?'結果発表へ！':'次の宝箱へ');put(n.selected,choosing?g.players.filter(p=>p.locked).length+' / 4 人':'ROUND '+g.round);put(n.note,hand?'装備は毎回発動。大技は1回きり。重複は効果アップ。':chest?'見た目と確率は、4つとも同じ。':'');
 for(let i=0;i<4;i++){const b=n.chestButtons[i];property506(b,'disabled',!chest||!me||selected!=null||!c.ready()||at>=g.deadline);attr(b,'aria-pressed',chest&&selected===i);put(b?.querySelector('span'),chest&&selected===i?'✓':'選ぶ');const h=n.handButtons[i],it=item509(g.hand?.[i]);property506(h,'disabled',!hand||!me||selected!=null||!c.ready()||at>=g.deadline);attr(h,'aria-pressed',hand&&selected===i);if(g.hand){setArt(h.querySelector('.lk-art508'),it.id);put(h.querySelector('b'),it.name);put(h.querySelector('p'),it.detail);put(h.querySelector('.lk-item-type508'),it.type);data(h,'type',it.type);attr(h,'aria-label',it.name+'。'+it.detail)}}
 const frame=raceFrame509(g,at,c.transport.selfId,u.reduced);const scroll=frame.visualCamera/520*(u.stageWidth??390),width=u.trackWidth??960,offset=((scroll%width)+width)%width;
 style509(n.ground,'transform',`translate3d(${-offset.toFixed(2)}px,0,0)`);style509(n.horizon,'transform',`translate3d(${-(((scroll*.25)%width+width)%width).toFixed(2)}px,0,0)`);style509(n.speed,'opacity',String(frame.speed*(frame.boost ? .85 : .3)));
 for(let i=0;i<n.markers.length;i++){const e=n.markers[i],m=frame.marks[i];hide(e,m.distance<0);style509(e,'transform',`translate3d(${m.x.toFixed(3)}%,0,0)`);put(e.querySelector('b'),distance509(m.distance))}
 for(const p of g.players){const r=n.players[p.seat],f=frame.rows[p.seat],event=g.event?.rows[p.seat];put(r.score,distance509(f.exact));attr(r.score,'title',fullDistance509(f.exact));put(r.status,choosing?p.locked?'✓ セット':p.ai?'AI · 選択中':p.connected?'選択中':'おまかせ待ち':f.rank+'位');put(r.equip,equipment509(p));attr(r.equip,'title',equipment509(p));style509(r.mini,'left',f.mini.toFixed(2)+'%');style509(r.mini,'top',(p.seat*7)+'px');
  style509(r.runner,'transform',`translate3d(${f.x.toFixed(3)}%,0,0)`);style509(r.body,'transform',`translate3d(-50%,${f.y.toFixed(2)}px,0) rotate(${f.angle.toFixed(2)}deg)`);hide(r.trail,!f.trail);hide(r.guard,!f.guard);hide(r.vehicle,!f.trail&&!(g.phase==='run'&&f.item==='spring'));setArt(r.vehicleArt,f.item);put(r.edge,f.offscreen==='left'?'◀':f.offscreen==='right'?'▶':'');data(r.runner,'offscreen',f.offscreen);hide(r.gain,g.phase!=='settle');put(r.gain,delta509(f.delta));
  if(event){const it=item509(event.item);setArt(n.revealArts[p.seat],it.id);put(r['reveal-item'],it.name);put(r['reveal-gain'],g.phase==='settle'?delta509(event.delta):it.type)}
 }
 put(n['map-end'],distance509(Math.max(600,...frame.rows.map(r=>r.distance+100))));paintPower(c,g,n,u,at);paintGear(c,g,n,u);paintCast(c,g,n,u,at);hide(n.offline,c.ready());hide(n.error,!c.error);put(n.error,c.error??'');hide(n['art-status'],u.artReady);if(u.artFailed)hide(n['art-status']?.querySelector('button'),false);
 const cue=[g.id,g.round,g.phase,g.phase==='countdown'?n.count.textContent:''].join(':');if(u.soundKey!==cue){u.soundKey=cue;const kind={countdown:'count',hand:'open',reveal:'open',run:'launch',settle:g.round===8?'finish':'settle'}[g.phase];if(kind)sound509(c,kind);put(n.reader,cap.title+(g.phase==='settle'?g.players.map(p=>p.name+' '+p.distance+'メートル').join('、'):''))}
}
export function luckTick509(c){const u=c.lkUI509,g=c.state?.luck;if(!u?.nodes||!g||globalThis.document?.visibilityState==='hidden'||u.raf!=null)return;const key=paintKey509(g,clock(c),c.ready(),u.pending,u.reduced)+':'+u.artReady+':'+u.artFailed+':'+(c.error??'');if(key===u.lastPaint&&!(u.pending&&Date.now()-u.pending.at>6000))return;if(typeof globalThis.requestAnimationFrame!=='function'){paintLuck509(c);return}u.raf=globalThis.requestAnimationFrame(()=>{u.raf=null;paintLuck509(c)})}

function power(c,g){return `<div class="lk-power509" data-power509 hidden aria-label="全員の装備コンボ"><header><small>STACK & MULTIPLY</small><strong>積んだぶんだけ、ぶっ飛ぶ。</strong><span>発進前のパワー</span></header>${g.players.map(p=>`<article data-power-row509="${p.seat}" style="--player:${color(p)}"><div>${portrait(c,p)}</div><b>${name(c,p)}</b><i data-power-dice509></i><p data-power-formula509></p><strong data-power-total509></strong></article>`).join('')}</div>`}
function paintPower(c,g,n,u,at){hide(n.power,g.phase!=='power');if(g.phase!=='power')return;const age=at-g.phaseAt;for(const p of g.players){const row=n.powerRows[p.seat],r=g.event.rows[p.seat],calc=r.calculation,rolling=!u.reduced&&age<850,dice=calc.dice??(calc.jackpot?[calc.jackpot]:[]);put(row.querySelector('[data-power-dice509]'),dice.map((d,i)=>String.fromCodePoint(0x267f+(rolling?1+(Math.floor(age/80)+p.seat+i*3)%6:d))).join(' '));put(row.querySelector('[data-power-formula509]'),rolling&&dice.length?'ころころ…':formula509(calc));put(row.querySelector('[data-power-total509]'),rolling&&dice.length?'…':delta509(calc.planned));attr(row,'title',formula509(calc)+' = '+fullDistance509(calc.planned));data(row,'big',Number(calc.planned)>=10000)}}
function gearPanel(c,g){return`<aside class="lk-gear-panel509" data-gear-panel509 hidden aria-label="装備一覧"><header><b data-gear-title509></b><button data-gear-close509="1" aria-label="装備一覧を閉じる">×</button></header><nav>${g.players.map(p=>`<button data-gear-seat509="${p.seat}" style="--player:${color(p)}">${name(c,p)}</button>`).join('')}</nav><div data-gear-list509>${Array.from({length:28},()=>`<article data-gear-slot509 hidden>${art509('dash')}<b></b><p></p></article>`).join('')}</div><p>選んだ手札は、一斉公開まで秘密。制限時間は進むよ。</p></aside>`}
function paintGear(c,g,n,u){const p=g.players[u.gearSeat];hide(n['gear-panel'],!p);if(!p)return;const revealed=['reveal','power','broadcast','run'].includes(g.phase),source=revealed?{...p,...g.event.rows[p.seat]}:p,gears=gearList509(source);put(n['gear-title'],p.name+' · '+equipment509(source).replace(' ▾',''));for(let i=0;i<n.gearSlots.length;i++){const e=n.gearSlots[i],gear=gears[i];hide(e,!gear);if(gear){const it=item509(gear.id);setArt(e.querySelector('.lk-art508'),it.id);put(e.querySelector('b'),it.name+' ×'+gear.count);put(e.querySelector('p'),it.detail)}}}
