import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {writeFile,mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE),out=fileURLToPath(new URL('../../docs/build555/',import.meta.url));await mkdir(out,{recursive:true});
const server=spawn(process.execPath,[fileURLToPath(new URL('./qa-server.mjs',import.meta.url))],{env:process.env,stdio:['ignore','pipe','pipe']});let stderr='';server.stderr.on('data',b=>stderr+=b);await new Promise((ok,no)=>{server.stdout.on('data',b=>{if(String(b).includes('ready'))ok()});server.on('exit',()=>no(Error(stderr)))});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});const base='http://127.0.0.1:8550',api=(n,d={})=>fetch(base+'/qa/'+n,{method:'POST',body:JSON.stringify(d)}).then(r=>r.json()),errors=[],missing=[],report={checks:[],viewports:[]},check=(ok,m)=>{if(!ok)throw Error(m)};
async function open(i){const p=await browser.newPage({viewport:{width:390,height:664},deviceScaleFactor:2,isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.stack));p.on('response',r=>{if(r.status()>=400&&/ricochet|555|party-avatar/.test(r.url()))missing.push(r.url())});await p.goto(base+'/preview.html?self=p'+i);await p.waitForFunction(()=>window.qaReady);await p.evaluate(()=>document.fonts.ready);return p}
async function reset(pages,d={}){const {id}=await api('reset',d);for(const p of pages)await p.waitForFunction(id=>c.state.ricochet?.id===id,id);return id}
const same=async(pages,expression,message)=>{const x=await Promise.all(pages.map(p=>p.evaluate(expression)));check(x.every(v=>v===x[0]),message)};
try{
 const pages=await Promise.all([0,1,2,3].map(open)),p=pages[0],cdp=await p.context().newCDPSession(p),point=(x,y)=>({x,y,id:1,radiusX:3,radiusY:3});
 const touch=async(type,pts=[])=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:pts});
 const startDrag=async(dx=0,dy=70)=>{const b=await p.locator('[data-rc-stage]').boundingBox(),x=b.x+b.width*.5,y=b.y+b.height*.5;await touch('touchStart',[point(x,y)]);await touch('touchMove',[point(x+dx,y+dy)]);await p.waitForTimeout(80);};
 const endDrag=async()=>{await touch('touchEnd');await p.waitForTimeout(50);await api('advance',{ms:80});await p.waitForTimeout(60)};
 await reset(pages,{phase:'lobby'});await p.locator('[data-rc-duration="150"]').click();await p.waitForFunction(()=>c.state.ricochet.duration555===150000);await p.locator('[data-rc-duration="90"]').click();for(const q of pages)await q.locator('[data-party-action462="ready"]').click();await p.locator('[data-rc-action="start"]').click();for(const q of pages)await q.waitForFunction(()=>c.state.ricochet.phase==='play');await api('pause',{value:true});
 for(const q of pages){check(await q.locator('[data-rc-pick]').count()===3,'missing three choices');check(await q.evaluate(()=>c.state.ricochet.players.filter(q=>q.playerId!==c.transport.selfId).every(q=>!q.offers)),'private offers leaked');await q.locator('[data-rc-pick]').first().click();}await api('advance',{ms:80});await p.waitForFunction(()=>c.state.ricochet.players.every(p=>p.picked));
 await p.evaluate(()=>window.originalCanvas=document.querySelector('canvas'));await startDrag(-15,70);const power=await p.evaluate(()=>c.ricochetUI550.pull.power);await p.waitForTimeout(180);check(await p.evaluate(()=>c.ricochetUI550.pull.power)===power,'hold time adds power');await endDrag();for(const q of pages)await q.waitForFunction(()=>c.state.ricochet.players[0].shots555===1);await api('advance',{ms:2900});await startDrag(20,70);await endDrag();for(const q of pages)await q.waitForFunction(()=>c.state.ricochet.players[0].shots555===2);const launched=(await api('state')).events.filter(e=>e.type==='launch'&&e.seat===0).at(-1);check(Math.hypot(launched.carryX,launched.carryY)>1,'moving shot lost momentum');
 report.checks.push('Four actual browser clients: ready/start, 90/150 settings, private equipment, repeated touch shots after reload, carried momentum.');
 // Late packets from the prior shot cannot fire after a later reload.
 await api('advance',{ms:2900});await p.evaluate(()=>{const g=c.state.ricochet;c.raw('ricochetInput550',{gameId:g.id,round:1,seq:++c.ricochetUI550.seq,action:'shoot',shot:0,angle:0,power:1})});await api('advance',{ms:80});check((await api('state')).players[0].shots555===2,'stale shot fired');
 // Supply and peer picks must not rebuild the canvas or cancel a held gesture.
 let g=await api('state');await api('advance',{ms:Math.max(0,29800-g.elapsed)});await startDrag(15,65);await api('advance',{ms:300});await p.waitForFunction(()=>c.state.ricochet.session555.supplyCount===2);check(await p.evaluate(()=>c.ricochetUI550.pull?.active&&document.querySelector('canvas')===window.originalCanvas),'supply cancelled/rebuilt input');await touch('touchCancel');for(const q of pages)await q.locator('[data-rc-action="offer"]').click();await startDrag(); // offer drawers block lower controls, not board dragging
 await pages[1].locator('[data-rc-pick]').first().click();await api('advance',{ms:80});check(await p.evaluate(()=>c.ricochetUI550.pull?.active),'peer pick cancelled drag');await touch('touchCancel');await p.locator('[data-rc-pick]').first().click();await api('advance',{ms:80});
 report.checks.push('Stale shot tokens are rejected; 30-second supplies and peer equipment selections preserve the live canvas and held input.');
 // Deterministic contact fixture: real physics, transport and renderer remain production code.
 await reset(pages,{phase:'play'});await api('pause',{value:true});await api('position',{players:[{seat:0,x:2,y:7.8,vx:0,vy:28},{seat:1,x:-6,y:2,vx:0,vy:0},{seat:2,x:6,y:2,vx:0,vy:0},{seat:3,x:0,y:1,vx:0,vy:0}]});await api('advance',{ms:100});for(const q of pages)await q.waitForFunction(()=>Math.abs(c.state.ricochet.carnival552.rotor555.omega)>.01);await same(pages,()=>JSON.stringify(c.state.ricochet.carnival552.rotor555),'rotor mismatch');await pages[3].close();pages[3]=await open(3);await same(pages,()=>JSON.stringify(c.state.ricochet.carnival552.rotor555),'rotor reconnect mismatch');
 await api('position',{players:[{seat:0,x:0,y:12.8,vx:0,vy:25,gems552:7},{seat:1,x:-6,y:2,vx:0,vy:0,gems552:7}]});await api('advance',{ms:100});for(const q of pages)await q.waitForFunction(()=>c.state.ricochet.carnival552.pending553);check((await api('state')).players[1].gems552===7,'consumed other gems');for(const q of pages)check(await q.evaluate(()=>!('_tier553' in c.state.ricochet.carnival552.pending553)),'secret leaked');await api('advance',{ms:1000});await same(pages,()=>JSON.stringify(c.state.ricochet.events.filter(e=>e.type==='jackpot')),'payout mismatch');check(await p.locator('.rc-stage-overlay550,.rc-jackpot553').count()===0,'blocking win overlay');
 report.checks.push('Impact-driven rotor synchronizes across four clients and reconnect. Crown payout is private until reveal and identical for everyone; no blocking jackpot panel.');
 await api('position',{players:[{seat:0,x:1,y:2,vx:4,vy:1,launched:true,burstCharge553:100}]});await startDrag(-20,70);check(await p.evaluate(()=>c.ricochetUI550.pullMode==='burst'),'burst unavailable');await endDrag();for(const q of pages)await q.waitForFunction(()=>c.state.ricochet.players[0].bursts553===1);report.checks.push('Earned burst works with actual touch while moving and adds existing momentum.');
 await api('advance',{ms:90000-(await api('state')).elapsed});for(const q of pages)await q.waitForFunction(()=>c.state.ricochet.phase==='result');await same(pages,()=>JSON.stringify(c.state.ricochet.results),'result mismatch');await p.locator('[data-party-result490="again"]').click();await p.waitForFunction(()=>c.state.ricochet.phase==='lobby');await reset(pages,{phase:'result'});await p.locator('[data-party-result490="list"]').click();await p.waitForFunction(()=>!c.state.ricochet);check(await p.locator('[data-party-game462="pinball"]').count()===1,'pinball missing');check(await p.locator('[data-party-game462="junkgp"]').count()===0,'retired GP visible');report.checks.push('One final result agrees on four clients; replay and game list work; retired GP is absent.');
 for(const [width,height] of [[320,690],[390,664],[430,932],[844,390]]){await p.setViewportSize({width,height});for(const phase of ['choice','play','result']){await reset(pages,{phase});await api('pause',{value:true});await p.waitForTimeout(140);const m=await p.evaluate(()=>{const u=c.ricochetUI550;return{overflow:document.documentElement.scrollWidth-innerWidth,stage:u.renderer?.height,ratio:u.renderer?u.renderer.projection.scale*16.36/u.renderer.width:0,offers:[...document.querySelectorAll('[data-rc-pick]')].map(e=>e.getBoundingClientRect().toJSON())}});check(m.overflow<=1,'horizontal overflow '+width+phase);if(phase==='choice')check(m.offers.length===3&&m.offers.every(b=>b.top>=0&&b.bottom<=height+1&&b.width>=44&&b.height>=44),'choices clipped '+JSON.stringify(m));if(phase==='play'&&height>width)check(m.ratio>.90,'portrait board too narrow '+JSON.stringify(m));report.viewports.push({width,height,phase,...m});await p.screenshot({path:out+`qa-${phase}-${width}x${height}.png`});}}
 await p.setViewportSize({width:390,height:664});await reset(pages,{phase:'play'});await api('pause',{value:true});await p.locator('[data-rc-detail="0"]').first().click();check(await p.locator('[role="dialog"] .rc-art551').count()>0,'inventory image missing');await p.keyboard.press('Escape');await p.locator('canvas').focus();await p.keyboard.press('ArrowUp');await p.keyboard.press('Enter');await api('advance',{ms:80});check((await api('state')).players[0].shots555===1,'keyboard shot');
 await reset(pages,{phase:'play'});await api('pause',{value:true});for(const cancel of ['cancel','blur']){await startDrag();if(cancel==='cancel')await touch('touchCancel');else{await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await touch('touchEnd')}await api('advance',{ms:80});check((await api('state')).players[0].shots555===0,'cancel fired');}await p.emulateMedia({reducedMotion:'reduce'});await reset(pages,{phase:'play'});check(await p.evaluate(()=>c.ricochetUI550.reduced),'reduced motion ignored');
 report.checks.push('320–430px portrait and 844×390 landscape, inventory images, keyboard, touch cancel, blur and reduced motion verified.');report.errors=errors;report.missing=missing;report.serverErrors=stderr;check(!errors.length&&!missing.length&&!stderr,JSON.stringify({errors,missing,stderr}));await writeFile(out+'browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){await writeFile(out+'browser-failure.json',JSON.stringify({error:e.stack,report,errors,missing,stderr},null,2));throw e}finally{await browser.close();server.kill()}
