import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {createRequire} from 'node:module';
import {room566,flags} from '../tools/build566/wire-fixture.mjs';import {queueCrane566,craneSnapshot566} from '../online-server/src/CraneCoordinator566.js';import {finishCrane566} from '../src/crane566/Rules566.js';
test('crane: production coordinator advertises version, selects owned monster, gates ready/start and fills AI',()=>{const f=room566(3);assert.equal(f.c.view(f.sessions.get('p0')).craneVersion566,1);assert.throws(()=>f.dispatch('p1',{op:'crane566',kind:'start'}),/部屋主/);assert.throws(()=>f.dispatch('p0',{op:'crane566',kind:'select',monsterId:'not-owned'}),/所持/);assert.throws(()=>f.dispatch('p0',{op:'partyReady462',ready:true,craneVersion566:0}),/Build566/);f.ready();f.party().members[2].craneVersion566=0;assert.throws(()=>f.dispatch('p0',{op:'crane566',kind:'start'}),/Build566/);f.party().members[2].craneVersion566=1;f.start();assert.equal(f.g().phase,'play');assert.equal(f.g().players.filter(p=>p.ai).length,1);assert(f.c.active('p0'));assert.equal(f.c.view(f.sessions.get('p0')).room,null);assert.equal(f.c.view(f.sessions.get('p0')).crane.id,f.g().id);});
test('crane: authenticated queues reject stale game, round, version, sequence and NaN; persistence includes real score',()=>{const f=room566();f.start();const g=f.g(),m={...flags,gameId:g.id,round:1,action:'cast',shot:0,angle:-Math.PI/2,seq:1},s=f.sessions.get('p0');for(const bad of [{gameId:'stale'},{round:2},{craneVersion566:0},{angle:NaN},{shot:4},{seq:0}])assert(!queueCrane566(f.c,s,{...m,...bad}));assert(queueCrane566(f.c,s,m));assert(!queueCrane566(f.c,s,m));assert.equal(craneSnapshot566(f.c,f.saved()).players[0].lastSeq,1);f.tick(50);assert.equal(f.g().players[0].shots,1);f.tick(5000);assert(f.saved().players[0].shots===1);const saved=JSON.parse(JSON.stringify(f.saved()));f.c.craneRuntime566.clear();f.c.data.craneRooms566[saved.code]=saved;assert.equal(f.g().players[0].shots,1);});
test('crane: home/disconnection uses AI, reconnect restores input, rematch/list clear only this game',()=>{const f=room566(3);f.start();f.dispatch('p0',{op:'partyPresence462',atHome:true});f.tick(5000);assert(f.g().players[0].auto);assert(f.g().players[0].shots>0);f.dispatch('p0',{op:'partyPresence462',atHome:false});f.tick(100);assert(!f.g().players[0].auto);f.sessions.get('p1').connected=false;f.tick(3000);assert(f.g().players[1].auto);f.sessions.get('p1').connected=true;const old=f.g().id;finishCrane566(f.g());f.tick(50);assert.equal(f.saved().phase,'result');assert.throws(()=>f.dispatch('p1',{op:'partyResult490',partyId:f.party().id,gameId:old,kind:'again'}),/部屋主/);f.dispatch('p0',{op:'partyResult490',partyId:f.party().id,gameId:old,kind:'again'});assert.notEqual(f.g().id,old);assert.equal(f.g().phase,'lobby');assert(!f.c.craneRuntime566.has(old));f.dispatch('p0',{op:'partyLounge462'});assert.equal(f.party().game,null);assert.equal(Object.keys(f.c.data.craneRooms566).length,0);});
test('crane: four real WebSocket clients pass through the production coordinator and receive separate frames',async()=>{const req=createRequire(import.meta.url);let WebSocketServer,WebSocket;try{({WebSocketServer,WebSocket}=req('ws'));}catch{const bundle=req(req.resolve('playwright').replace(/playwright\/index\.js$/,'playwright-core/lib/utilsBundle.js'));WebSocketServer=bundle.wsServer;WebSocket=bundle.ws;}
 const sockets=new Map(),frames=new Map(),server=http.createServer(),wss=new WebSocketServer({server}),f=room566(4,(id,m)=>sockets.get(id)?.send(JSON.stringify(m))),clients=[];let serial=0;
 wss.on('connection',(socket,request)=>{const id=new URL(request.url,'http://local').searchParams.get('id');sockets.set(id,socket);socket.on('message',b=>{const m=JSON.parse(b);let error;try{f.dispatch(id,m);f.tick(50);}catch(e){error=e.message;}socket.send(JSON.stringify({ack:m.requestId,error}));});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{for(let i=0;i<4;i++){const id='p'+i,ws=new WebSocket('ws://127.0.0.1:'+server.address().port+'/?id='+id);clients.push(ws);ws.on('message',b=>{const m=JSON.parse(b);if(m.type==='craneFrame566')frames.set(id,m);});await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});}
 const send=(seat,m)=>new Promise((resolve,reject)=>{const requestId=++serial,ws=clients[seat],timer=setTimeout(()=>reject(Error('timeout')),2500),listener=b=>{const message=JSON.parse(b);if(message.ack!==requestId)return;clearTimeout(timer);ws.off('message',listener);message.error?reject(Error(message.error)):resolve();};ws.on('message',listener);ws.send(JSON.stringify({...m,requestId}));});
 for(let i=0;i<4;i++)await send(i,{op:'partyReady462',ready:true});await send(0,{op:'crane566',kind:'start'});f.tick(3100);
 for(let i=0;i<4;i++)await send(i,{op:'craneInput566',gameId:f.g().id,round:1,action:'cast',shot:0,seq:1,angle:[-Math.PI/2,Math.PI,Math.PI/2,0][i]});
 assert(f.g().players.every(p=>p.shots===1));f.tick(50);await new Promise(r=>setTimeout(r,25));assert.equal(frames.size,4);for(let i=0;i<4;i++){const frame=frames.get('p'+i);assert.equal(frame.selfId,'p'+i);assert.equal(frame.crane.id,f.g().id);assert.equal(frame.crane.players.length,4);assert(frame.crane.players.every(p=>Number.isFinite(p.score)));}
 await send(0,{op:'craneInput566',gameId:'stale',round:1,action:'cast',shot:1,seq:50,angle:0});assert.equal(f.g().players[0].shots,1);
 }finally{clients.forEach(c=>c.close());await new Promise(r=>wss.close(r));await new Promise(r=>server.close(r));}
});
