import test from 'node:test';
import assert from 'node:assert/strict';
import * as U from '../src/core/EndgameUltimateSystem.js';
import {ENDGAME_CHARACTERS} from '../src/data/endgameCharacters.js';
import {applyEnemyDamage,tickCooldowns} from '../src/battle/BattleRules.js';
function unit(id,owner,hp=1000){return{id,playerId:id,endgameBossId:owner,name:id,hp,maxHp:1000,mp:1000,maxMp:1000,stats:{hp:1000,mp:1000,atk:150,matk:100,def:50,mdef:50,spd:100,evasion:0,crit:0},effects:[],cooldowns:{},skills:[{id:'slash',name:'斬撃',type:'attack',kind:'attack',mp:20,power:1,damageClass:'physical',element:'fire'}]}}
function fixture(owner,side='ally'){const caster=unit('caster',owner),friend=unit('friend',null),foe=unit('foe',null),other=unit('other',null),b={round:4,players:{},enemies:[]};if(side==='ally'){b.players={caster,friend};b.enemies=[foe,other]}else{b.players={foe,other};b.enemies=[caster,friend]}U.prepareUltimateBattle(b);return{b,caster,friend,foe,other,id:U.ENDGAME_ULTIMATES[owner].id}}
const cast=f=>U.castEndgameUltimate(f.b,f.caster,f.id,{targetId:f.foe.id,random:()=>0});
const end=(b,r)=>{b.round=r;U.endUltimateRound(b)};
test('existing skills preserved; exactly one innate addition for all 17',()=>{assert.equal(Object.keys(U.ENDGAME_ULTIMATES).length,17);for(const [id,p]of Object.entries(ENDGAME_CHARACTERS)){assert.equal(p.skills.length,6,id);assert.equal(p.skills.filter(U.isEndgameUltimate).length,1,id);assert.equal(p.skills.at(-1).id,U.ENDGAME_ULTIMATES[id].id)}});
for(const owner of Object.keys(U.ENDGAME_ULTIMATES))test(`${owner}: shared cast, MP and protected CT`,()=>{const outputs=[];for(const side of ['ally','enemy']){const f=fixture(owner,side);f.friend.hp=0;f.foe.hp=300;f.caster.hp=800;U.afterUltimateOrdinary(f.b,f.foe,f.foe.skills[0]);f.b.round=3;assert.equal(cast(f).ok,false);f.b.round=4;assert.equal(cast(f).ok,true);assert.equal(cast(f).ok,false);f.caster.cooldowns={};tickCooldowns(f.b);assert.ok(U.ultimateRemaining(f.b,f.caster,f.id)>0);outputs.push({mp:f.caster.mp,hp:f.caster.hp,foe:f.foe.hp,friend:f.friend.hp,effects:f.b.ultimates358.effects.map(e=>e.kind)})}assert.deepEqual(outputs[0],outputs[1])});
test('doom survives JSON save and fires after ten complete rounds; forced death bypasses shield and rage',()=>{const f=fixture('ten_time');f.foe.shield=999999;cast(f);for(let r=4;r<14;r++)end(f.b,r);assert.equal(f.foe.hp,1000);const b=JSON.parse(JSON.stringify(f.b));U.prepareUltimateBattle(b);end(b,14);assert.equal(b.enemies[0].hp,0);assert.equal(b.enemies[1].hp,0);assert.equal(U.castEndgameUltimate({...b,round:100},b.players.caster,f.id).ok,false)});
test('caster death cancels doom and isolation without winning a living isolated side',()=>{const f=fixture('ten_space');cast(f);assert.equal(U.ultimateIsolated(f.b,f.foe),true);f.foe.hp=0;assert.equal(f.foe.hp,1000);assert.equal(U.beforeUltimateAction(f.b,f.foe),true);f.caster.hp=0;assert.equal(U.ultimateIsolated(f.b,f.foe),false);const d=fixture('ten_time');cast(d);d.caster.hp=0;end(d.b,14);assert.equal(d.foe.hp,1000)});
test('death register threshold and revival seal',()=>{const f=fixture('ten_death');cast(f);f.foe.hp=400;f.other.hp=401;end(f.b,7);assert.equal(f.foe.hp,0);assert.equal(f.other.hp,401);assert.ok(f.foe.effects.some(e=>e.kind==='reviveSeal'));const life=fixture('ten_life');life.friend.hp=0;life.friend.effects=[{kind:'reviveSeal',value:1,turns:3}];assert.equal(cast(life).ok,false)});
test('absolute wall exactly once; wrath expires and cannot heal; native HP writers obey rules',()=>{const f=fixture('ten_creation');cast(f);U.beginUltimateAction(f.b,f.foe,f.foe.skills[0]);f.friend.hp=0;assert.equal(f.friend.hp,1000);assert.equal(f.caster.hp,900);f.friend.hp=0;assert.equal(f.friend.hp,0);U.cleanupUltimateBattle(f.b);assert.equal(Object.getOwnPropertyDescriptor(f.caster,'hp').get,undefined);const r=fixture('abyss_wrath');r.caster.hp=200;cast(r);r.caster.hp=0;assert.equal(r.caster.hp,1);r.caster.hp=1000;assert.equal(r.caster.hp,1);end(r.b,5);r.caster.hp=0;assert.equal(r.caster.hp,0)});
test('furnace accumulates actual enemy HP loss, excludes friendly damage, releases once',()=>{const f=fixture('ten_end');cast(f);U.beginUltimateAction(f.b,f.friend,f.friend.skills[0]);f.foe.hp=600;assert.equal(f.b.ultimates358.effects[0].stored,200);f.friend.hp=800;assert.equal(f.b.ultimates358.effects[0].stored,200);end(f.b,7);assert.equal(f.foe.hp,500);assert.equal(f.other.hp,900);assert.equal(f.caster.hp,700);end(f.b,7);assert.equal(f.foe.hp,500)});
test('ordinary echoes pay MP, cannot echo twice or copy ultimates',()=>{const f=fixture('ten_divinity');cast(f);const before=f.foe.hp;U.afterUltimateOrdinary(f.b,f.friend,f.friend.skills[0],{random:()=>0});assert.ok(f.foe.hp<before);assert.equal(f.friend.mp,980);U.afterUltimateOrdinary(f.b,f.friend,f.friend.skills[0]);assert.equal(f.friend.mp,980);U.afterUltimateOrdinary(f.b,f.friend,U.ENDGAME_ULTIMATES.ten_time);assert.equal(f.friend.mp,980)});
test('possession respects immunity/cleanse and spends a normal action; pride has recovery window',()=>{const f=fixture('ten_dominion');cast(f);const before=f.other.hp;assert.equal(U.beforeUltimateAction(f.b,f.foe,{random:()=>0}),true);assert.ok(f.other.hp<before||f.foe.hp<1000);assert.equal(U.beforeUltimateAction(f.b,f.foe),false);const clean=fixture('ten_dominion');cast(clean);clean.foe.effects=[];assert.equal(U.beforeUltimateAction(clean.b,clean.foe),false);const immune=fixture('ten_dominion');immune.foe.statusProfile=immune.other.statusProfile={immune:['charm']};U.prepareUltimateBattle(immune.b);assert.equal(cast(immune).ok,false)});
test('greed borrows active circle only and restores on death and cleanup',()=>{const f=fixture('abyss_greed');f.foe.circleEffect='rage';f.foe.circleId='red';f.foe.circleLevel=10;f.caster.circleEffect='shield';f.caster.circleId='blue';f.caster.circleLevel=2;cast(f);assert.equal(f.caster.circleEffect,'rage');assert.equal(f.foe.circleEffect,'none');f.caster.hp=0;U.finishUltimateAction(f.b);assert.equal(f.caster.circleEffect,'shield');assert.equal(f.foe.circleEffect,'rage');const g=fixture('abyss_greed');g.foe.circleEffect='rage';g.caster.circleEffect='shield';cast(g);U.cleanupUltimateBattle(g.b);assert.equal(g.foe.circleEffect,'rage');assert.equal(g.caster.circleEffect,'shield')});
test('lust only diverts real healing, not overheal or revival; sloth suppresses extras',()=>{const f=fixture('abyss_lust');f.caster.hp=500;f.friend.hp=500;f.foe.hp=800;cast(f);f.foe.hp=1000;assert.equal(f.foe.hp,900);assert.equal(f.caster.hp+f.friend.hp,1100);const s=fixture('abyss_sloth');cast(s);assert.equal(U.ultimateExtraBlocked(s.b,s.foe),true);assert.equal(U.ultimateBasicOnly(s.b,s.caster),true);assert.equal(U.ultimateExtraBlocked(s.b,s.friend),false)});
