import test from 'node:test';import assert from 'node:assert/strict';
import * as R from '../src/tower/Rules517.js';
const make=()=>{const g=R.makeTower517({id:'529',code:'529',hostId:'p0',members:Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'P'+i,choice:{speciesId:'slime'}}))});g.roleMode='p0';R.startTower517(g,0,529);R.advanceTower517(g,3000);g.autoAt=1e8;g.players.slice(2).forEach(p=>p.alive=false);return g};
function falling(x,{side='right',blocks=[],cells=[[0,0]],y=.81}={}){const g=make(),p=g.players[1];p.x=x;g.board=blocks;g.falling={id:1,type:'O',x:4,y,land:0,cells};R.advanceFalling529(g,1/60);return{g,p}}
test('strictly less than half-width edge contacts slide out on both sides; half or greater crushes',()=>{
 for(const x of [5.299,5.1,5.001,3.701,3.9,3.999]){const{g,p}=falling(x);assert.ok(p.alive);assert.ok(!R.solid517(g,p.x,p.y));assert.ok(g.events.some(e=>e.type==='squeeze529'));assert.ok(Math.abs(p.x-x)<.3)}
 for(const x of [5,4.999,4.8,4.5,4,4.001]){const{p}=falling(x);assert.equal(p.alive,false,'x='+x)}
});
test('a blocked slide destination dies immediately; cannot pick the far side or teleport through a wall',()=>{for(const [x,bx]of [[5.1,5.4],[3.9,2.6]]){const{p}=falling(x,{blocks:[{x:bx,y:0,type:'O'}]});assert.equal(p.alive,false)}});
test('another falling cell at the slide destination also crushes immediately',()=>{const{p}=falling(5.1,{cells:[[0,1],[1,0]],y:1});p.y=1;const g=make();g.players[1].x=5.1;g.players[1].y=1;g.falling={id:1,type:'L',x:4,y:.81,land:0,cells:[[0,1],[1,0]]};R.advanceFalling529(g,1/60);assert.equal(g.players[1].alive,false)});
test('cell seams and stacked contacts use total covered width, never per-cell forgiveness',()=>{const a=falling(5,{cells:[[0,0],[1,0]]});assert.equal(a.p.alive,false);const b=falling(5.1,{cells:[[0,0],[0,1]]});assert.ok(b.p.alive);assert.ok(!R.solid517(b.g,b.p.x,b.p.y))});
test('safe downward displacement and support remain valid; only actual crushing kills deep contact',()=>{const{g,p}=falling(4.5,{y:2});p.y=.5;p.vy=0;R.advanceFalling529(g,.22);assert.equal(p.alive,true);assert.ok(p.y>=0);const s=falling(5.1,{blocks:[{x:5,y:-1,type:'O'}]});assert.ok(s.p.alive);assert.equal(s.p.y,0)});
test('super jump cooldown is 10000 ms; early repeat fails, ready repeat succeeds',()=>{const g=make(),p=g.players[1];g.elapsed=100;R.predictRunner517(g,p,{superJump:true},1/60);assert.equal(p.superReady,10100);p.y=0;p.vy=0;p.grounded=true;p.coyote=0;g.elapsed=10090;R.predictRunner517(g,p,{superJump:true},1/60);assert.equal(p.superReady,10100);p.y=0;p.vy=0;p.grounded=true;g.elapsed=10100;R.predictRunner517(g,p,{superJump:true},1/60);assert.equal(p.superReady,20100)});
test('three runners wait calmly on a safe flat floor for 30 seconds, no head hopping',()=>{const g=make();g.players.slice(1).forEach((p,i)=>{p.alive=true;p.x=4+i*.3});for(let i=0;i<1800;i++){const input=new Map(g.players.slice(1).map(p=>[p.playerId,R.botRunner517(g,p)]));R.advanceTower517(g,g.lastAt+R.TOWER517.step,input)}assert.equal(g.events.filter(e=>['jump','bounce','superJump'].includes(e.type)).length,0);assert.equal(g.eventSeq,0)});
test('old tower clients cannot send movement after the rules update',async()=>{const{queueTower517}=await import('../online-server/src/TowerCoordinator517.js');const g=make(),c={data:{towerRooms517:{a:g}},now:()=>3000},s={playerId:'p1'},m={gameId:g.id,kind:'move',seq:1,axis:1};assert.equal(queueTower517(c,s,{...m,towerVersion517:4}),false);assert.equal(queueTower517(c,s,{...m,towerVersion517:5}),true);assert.equal(R.publicTower517(g).rules517,5)});

test('calm AI still uses a ready super jump from the last four rows to escape',()=>{const g=make(),p=g.players[1];for(let x=0;x<10;x++)for(let y=0;y<16;y++)g.board.push({x,y,type:'O'});g.boardRevision++;p.y=16;p.x=4.5;for(let i=0;i<120&&g.phase==='play';i++)R.advanceTower517(g,g.lastAt+R.TOWER517.step,new Map([[p.playerId,R.botRunner517(g,p)]]));assert.equal(g.winner,'run');assert.ok(g.events.some(e=>e.type==='superJump'))});
