import test from'node:test';import assert from'node:assert/strict';
import{CANAL489 as R,makeCanal489,startCanal489,advanceCanal489,inputCanal489,sweep489,publicCanal489,lanes489,gates489,SPECIES489}from'../src/canal/Rules489.js';
import{bindCanal489,flushCanal489,acknowledgeCanal489,position489}from'../src/canal/Input489.js';
import{canalView489,canalSignature489,canalKey489,canalClick489}from'../src/canal/View489.js';
import{isPartyHub462,partyHub462}from'../src/party/PartyView462.js';
import{memberDialog485}from'../src/party/PartyMember485.js';
function setup(n=4,seed=31){const g=makeCanal489({id:'canal',code:'ABCDEF',partyId:'party',hostId:'p0',members:Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'Player '+i,choice:{id:'m'+i,speciesId:'wolf'},owned:[{id:'m'+i,speciesId:'wolf'}]})),now:1000,seed});startCanal489(g,1000);return g}
const input=(seq,lane,extra={})=>({seq,lane,held:false,pulse:true,burst:false,...extra});
function enemy(g,{id=1,lane=0,kind=0,hp=SPECIES489[kind].hp,progress=.5}={}){const at=g.startAt+4000,e={id,lane,kind,hp,maxHp:SPECIES489[kind].hp,spawnAt:at-10000*progress,travelMs:10000,wiggle:0};g.phase='playing';g.enemies.push(e);return at}

test('one to four owned monsters retain choices; only empty seats become AI and no main-game power applies',()=>{for(let n=1;n<=4;n++){const g=setup(n);assert.equal(g.players.length,4);assert.equal(g.players.filter(p=>p.ai).length,4-n);assert.deepEqual(g.players.slice(0,n).map(p=>p.choice.id),Array.from({length:n},(_,i)=>'m'+i));assert.equal(g.hp,100);assert.equal(g.endAt-g.startAt,60000)}});
test('unselected or oversized parties cannot start and a running game cannot reset',()=>{const g=makeCanal489({members:[{playerId:'p'}],now:0});assert.throws(()=>startCanal489(g,0));g.members=setup().members.concat({choice:{id:'too-many'}});assert.throws(()=>startCanal489(g,0));const a=setup();assert.equal(startCanal489(a,999),false);assert.equal(a.startAt,4000)});
test('each seat can protect itself and adjacent lanes, never the opposite side',()=>{for(let seat=0;seat<4;seat++){assert.equal(lanes489(seat).length,3);const g=setup(),p=g.players[seat],at=enemy(g,{lane:(seat+2)%4});assert.equal(inputCanal489(g,p,input(1,(seat+2)%4),at),false);assert.equal(g.captured,0);assert.equal(p.lastSeq,0);}});
test('ordinary net damages tough creatures; only one capture and one score when two players hit',()=>{const g=setup(),at=enemy(g,{kind:1});const p=g.players[0],q=g.players[1];sweep489(g,p,0,at);assert.equal(g.enemies[0].hp,2);sweep489(g,q,0,at);assert.equal(g.enemies[0].hp,1);sweep489(g,p,0,at+500);sweep489(g,q,0,at+500);assert.equal(g.captured,1);assert.equal(g.points,25);assert.equal(p.captured+q.captured,1)});
test('adjacent capture records a real assist; no duplicated sequence or spam earns extra captures',()=>{const g=setup(),at=enemy(g,{lane:1}),p=g.players[0];assert.equal(inputCanal489(g,p,input(1,1),at),true);assert.equal(p.assists,1);enemy(g,{id:2,lane:1});assert.equal(inputCanal489(g,p,input(1,1),at+1000),false);for(let seq=2;seq<60;seq++)inputCanal489(g,p,input(seq,1),at+10);assert.equal(p.captured,1);inputCanal489(g,p,input(60,1),at+500);assert.equal(p.captured,2)});
test('client timestamps and invalid types cannot accelerate attacks or move a net across the map',()=>{const g=setup(),at=enemy(g),p=g.players[0];inputCanal489(g,p,{...input(1,0),at:at+99999},at);enemy(g,{id:2});inputCanal489(g,p,{...input(2,0),at:at+999999},at+1);assert.equal(g.captured,1);for(const x of [input(NaN,0),input(3,.5),input(3,0,{held:'yes'}),input(R.maxSequence+1,0)])assert.equal(inputCanal489(g,p,x,at),false)});
test('big net damages every target on chosen lane and respects individual 12 second cooldown',()=>{const g=setup(),at=enemy(g,{id:1,kind:0}),p=g.players[0];enemy(g,{id:2,kind:1});enemy(g,{id:3,kind:3});enemy(g,{id:4,kind:0,lane:1});assert.equal(sweep489(g,p,0,at,true),true);assert.equal(g.captured,2);assert.equal(g.enemies.find(e=>e.id===3).hp,1);assert.equal(g.enemies.find(e=>e.id===4).hp,1);assert.equal(sweep489(g,p,0,at+11999,true),false);assert.equal(p.bursts,1);assert.equal(sweep489(g,p,0,at+12000,true),true)});
test('a held direction repeats without tap spam, and lost release expires rather than firing forever',()=>{const g=setup(),p=g.players[0];g.nextSpawnAt=Infinity;g.phase='playing';g.simAt=g.startAt;for(let i=0;i<10;i++)g.enemies.push({id:i,kind:0,lane:0,hp:1,maxHp:1,spawnAt:g.startAt-10000,travelMs:50000,wiggle:0});inputCanal489(g,p,input(1,0,{held:true}),g.startAt);advanceCanal489(g,g.startAt+3000);assert.equal(p.captured,3);assert.equal(p.nextFireAt,g.startAt+1500)});
test('every gate opens at 50 seconds and the finale brings a faster wave to all four directions',()=>{assert.equal(gates489(49999).length,2);assert.deepEqual(gates489(50000),[0,1,2,3]);const g=setup();advanceCanal489(g,g.startAt+49900,()=>false);const serial=g.enemySerial;advanceCanal489(g,g.startAt+50000,()=>false);const surge=g.enemies.filter(e=>e.id>serial);assert.equal(surge.length,4);assert.deepEqual(surge.map(e=>e.lane),[0,1,2,3]);assert.ok(surge.every(e=>e.travelMs<SPECIES489[e.kind].travelMs*.6));assert.ok(g.events.some(e=>e.kind==='flood'))});
test('fixed steps give exactly the same outcome with frequent ticks and one long restart catch-up',()=>{const a=setup(),b=setup();for(let t=a.startAt;t<=a.endAt;t+=100)advanceCanal489(a,t,()=>false);advanceCanal489(b,b.endAt+999999,()=>false);assert.deepEqual(a,b);assert.equal(b.phase,'result');assert.equal(b.finishedAt,b.endAt);assert.ok(b.enemies.length<=R.maxEnemies);assert.ok(b.events.length<=48)});
test('four idle humans lose together; coordinated protection survives with a shared result',()=>{const idle=setup();advanceCanal489(idle,idle.endAt,()=>true);assert.equal(idle.phase,'result');assert.equal(idle.success,false);assert.equal(idle.hp,0);const team=setup();advanceCanal489(team,team.endAt,()=>false);assert.equal(team.success,true);assert.equal(team.grade,'S');assert.ok(team.captured>100);const snapshot=JSON.stringify(team);advanceCanal489(team,team.endAt+100000);assert.equal(JSON.stringify(team),snapshot)});
test('disconnected player is covered by AI and returns to manual control on reconnect',()=>{const g=setup(),p=g.players[0];advanceCanal489(g,g.startAt+14000,id=>id!=='p0');assert.equal(p.auto,true);assert.ok(p.captured>0);const captures=p.captured;advanceCanal489(g,g.startAt+16000,()=>true);assert.equal(p.auto,false);assert.equal(p.captured,captures)});
test('public state strips owned rosters, RNG and other input sequence state, and is safe to mutate',()=>{const g=setup(),s=publicCanal489(g,'p1',5000);assert.equal(s.rng,undefined);assert.equal(s.members[0].owned,undefined);assert.equal(s.players[0].lastSeq,undefined);assert.equal(s.players[1].lastSeq,0);s.players[0].choice.speciesId='bad';assert.equal(g.players[0].choice.speciesId,'wolf')});
test('real species dominate the spawn mix; fictional general remains a rare visitor',()=>{let real=0,fake=0;for(let seed=1;seed<=20;seed++){const g=setup(4,seed),ids=new Set();for(let t=g.startAt;t<=g.endAt;t+=100){advanceCanal489(g,t,()=>false);for(const e of g.enemies)if(!ids.has(e.id)){ids.add(e.id);if(e.kind===3)fake++;else real++}}}assert.ok(real/(real+fake)>.90);assert.ok(fake>0)});

function target(){const events=new Map();return{events,addEventListener(n,f){if(!events.has(n))events.set(n,new Set());events.get(n).add(f)},removeEventListener(n,f){events.get(n)?.delete(f)},fire(n,e){for(const f of events.get(n)??[])f(e)}}}
test('two thumbs switch immediately, lift restores the other thumb, cancel and cleanup release the net',()=>{const surface=target(),win=target(),log=[];const cleanup=bindCanal489(surface,(l,p)=>log.push(['down',l,p]),()=>log.push(['up']),win,true);const button=lane=>({disabled:false,dataset:{cnLane:String(lane)},setPointerCapture(){}});const e=(id,l)=>({pointerId:id,button:0,target:{closest:()=>button(l)},preventDefault(){}});surface.fire('pointerdown',e(1,0));surface.fire('pointerdown',e(2,1));win.fire('pointerup',e(2,1));win.fire('pointercancel',e(1,0));assert.deepEqual(log,[['down',0,undefined],['down',1,undefined],['down',0,false],['up']]);cleanup();const n=log.length;surface.fire('pointerdown',e(3,0));assert.equal(log.length,n)});
test('touch fallback accepts concurrent changed touches and releases on blur',()=>{const surface=target(),win=target(),log=[];const clean=bindCanal489(surface,l=>log.push(l),()=>log.push('release'),win,false);surface.fire('touchstart',{changedTouches:[0,1].map(i=>({identifier:i,target:{closest:()=>({dataset:{cnLane:String(i)}})}})),preventDefault(){}});win.fire('blur',{});assert.deepEqual(log,[0,1,'release']);clean()});
test('input retransmissions keep fresh commands flowing and server ACK trims already processed inputs',()=>{const u={seq:30,lastFlush:0,pending:Array.from({length:30},(_,i)=>({...input(i+1,0),sentAt:i<24?100:undefined}))},sent=[];const c={connected:()=>true,raw:(op,m)=>sent.push(m)};flushCanal489(c,u,{id:'g'},300);assert.equal(sent[0].inputs[0].seq,25);assert.equal(sent[0].inputs.length,6);acknowledgeCanal489(u,{lastSeq:25});assert.equal(u.pending[0].seq,26);assert.equal(u.seq,30);});
test('lane positions stay in matching water channels from edge to central island',()=>{for(let l=0;l<4;l++){const start=position489(l,0),end=position489(l,1);assert.ok(Math.hypot(end.x-50,end.y-50)<Math.hypot(start.x-50,start.y-50));assert.equal(l%2?start.y:start.x,50);assert.equal(l%2?end.y:end.x,50)}});
function client(g){return{state:{canal:publicCanal489(g,'p0',g.startAt),party:{id:'party',code:'ABCDEF',hostId:'p0',members:g.members.map(m=>({...m,ready:true,connected:true,seatToken485:'seat'}))},canalVersion489:1,canalRules492:1,partyMemberActions485:1},transport:{selfId:'p0'},roster:()=>[{id:'m0',speciesId:'wolf'}],sgSpeciesName463:id=>id,sgMonster463:id=>`<span>${id}</span>`,ready:()=>true,connected:()=>true,connectionMessage:()=>'',draft:{},raw(){},render(){}}}
test('lobby, play and result render through the real new view with escaped player names and all four teammates',()=>{const g=setup();g.members[0].name='<script>alert(1)</script>';g.players[0].name=g.members[0].name;const c=client(g);c.state.canal.phase='lobby';let html=canalView489(c);assert.ok(html.includes('用水路防衛隊'));assert.ok(html.includes('data-cn-monster'));assert.ok(!html.includes('<script>'));c.state.canal.phase='playing';html=canalView489(c);assert.equal((html.match(/data-cn-lane=/g)||[]).length,3);assert.equal((html.match(/data-cn-gate=/g)||[]).length,4);advanceCanal489(g,g.endAt,()=>false);c.state.canal=publicCanal489(g,'p0',g.endAt);html=canalView489(c);assert.ok(html.includes('用水路、守り切った！'));assert.ok(html.includes('みんなで捕獲'));assert.ok(!html.includes('1位'));assert.ok(!html.includes('<script>'))});
test('live snapshots update canvas without replacing touch controls and party recognizes the active game',()=>{const g=setup(),c=client(g),sig=JSON.stringify(canalSignature489(c));c.state.canal.captured=55;c.state.canal.revision++;c.state.canal.serverNow++;assert.equal(JSON.stringify(canalSignature489(c)),sig);assert.equal(isPartyHub462(c),false);c.partyBrowse462=true;assert.equal(isPartyHub462(c),true);assert.ok(partyHub462(c).includes('用水路防衛隊'));});
test('member removal uses canal room identity and remains disabled during play',()=>{const g=setup(),c=client(g);c.partyMember485={partyId:'party',playerId:'p1',seatToken485:'seat'};assert.ok(memberDialog485(c).includes('対戦中は退場'));assert.match(memberDialog485(c),/data-party-member-action485="remove" disabled/)});
test('keyboard cannot target the opposite lane; burst is an explicit separate action',()=>{const g=setup(),c=client(g),sent=[];const nodes=new Map();const node=selector=>{if(!nodes.has(selector))nodes.set(selector,{style:{},classList:{toggle(){}},querySelector:node,setAttribute(){},getContext:()=>null});return nodes.get(selector)};c.root={querySelector:node,querySelectorAll:()=>[]};c.offset=g.startAt+1000-Date.now();c.raw=(op,m)=>{sent.push({op,m});return true};const ev=k=>({key:k,target:{closest:()=>null},preventDefault(){}});assert.equal(canalKey489(c,ev('ArrowDown')),true);assert.equal(sent.length,0);assert.equal(canalKey489(c,ev('ArrowUp')),true);assert.equal(sent[0].m.inputs[0].lane,0);assert.equal(sent[0].m.inputs[0].held,true);canalClick489(c,{dataset:{cnAction:'burst'}},{});assert.equal(c.cnUI489.pending.at(-1).burst,true)});
