import test from 'node:test';import assert from 'node:assert/strict';
import {RoomStore} from '../online-server/src/RoomStore.js';
import {TeamBattleCoordinator} from '../online-server/src/TeamBattleCoordinator.js';
import {RaidCoordinator} from '../online-server/src/RaidCoordinator.js';
import {ENDGAME_ULTIMATES,castEndgameUltimate,prepareUltimateBattle,endUltimateRound,ultimateIsolated} from '../src/core/EndgameUltimateSystem.js';
const make=(id,owner)=>({id,playerId:id,ownerPlayerId:id,speciesId:'slime',endgameBossId:owner,visualSpeciesId:owner,name:id,hp:10000,maxHp:10000,mp:1000,maxMp:1000,stats:{hp:10000,mp:1000,atk:1000,matk:1000,def:100,mdef:100,spd:100,accuracy:100,evasion:0,crit:0},effects:[],cooldowns:{},skills:owner?[ENDGAME_ULTIMATES[owner]]:[],metrics:{damage:0,damageTaken:0,healing:0,support:0},equipmentCombatEffects:{},itemCharges:2});
for(const mode of ['room','team','raid'])test(`${mode}: actual resolver casts canonical ultimate once, preserves MP and rejects early reuse`,()=>{const u=make('caster','ten_time'),foe=make('foe',null),b={round:4,players:{caster:u},enemies:[foe],contribution:{caster:{damage:0,healing:0}},progress:{hp:10000,maxHp:10000,totalDamage:0}},events=[],s=u.skills[0],action={kind:'skill',skillId:s.id,targetId:foe.id,enemyTargetId:foe.id};let run;if(mode==='room'){const store=new RoomStore();run=()=>store._resolvePlayerAction({},b,u,action,events,new Map())}if(mode==='team'){const team=new TeamBattleCoordinator({sessions:new Map()});u.side='sun';foe.side='moon';b.players.foe=foe;b.enemies=[];run=()=>team._resolveAction(b,u,action,events)}if(mode==='raid'){const raid=new RaidCoordinator({sessions:new Map()});b.boss=foe;b.minions=[];run=()=>raid._resolvePlayer({},b,u,action,null,events)}run();assert.equal(u.mp,400);assert.ok(events.some(e=>e.kind==='ultimateCast'));run();assert.equal(u.mp,400);b.round=14;endUltimateRound(b);assert.equal(foe.hp,0)});
test('RoomStore enemy AI cannot fire a new skill during opening and uses shared cast when ready',()=>{const store=new RoomStore({random:()=>.99}),enemy=make('enemy','ten_space'),ally=make('ally',null);delete enemy.playerId;enemy.atk=100;enemy.matk=100;enemy.def=100;enemy.spd=100;enemy.currentMp=1000;delete enemy.mp;const b={round:4,players:{ally},enemies:[enemy]},events=[];store._resolveEnemyActions(b,events,enemy);assert.ok(events.some(e=>e.kind==='ultimateCast'));assert.equal(enemy.currentMp,400);assert.equal(ultimateIsolated(b,ally),true);});
test('raid and 4v4 ordinary item recovery is intercepted by active enemy healing theft',()=>{for(const mode of ['team','raid']){const owner=make('enemy','abyss_lust'),u=make('ally',null);u.hp=1000;owner.hp=5000;const b={round:4,players:{ally:u},enemies:[owner],contribution:{ally:{damage:0,healing:0,mpHealing:0}},progress:{hp:5000,maxHp:10000,totalDamage:0}},events=[];if(mode==='team'){owner.side='moon';u.side='sun';b.players.enemy=owner;b.enemies=[]}else{b.boss=owner;b.minions=[]}prepareUltimateBattle(b);const core=ENDGAME_ULTIMATES.abyss_lust;const cast=mode==='team'?new TeamBattleCoordinator({sessions:new Map()}):new RaidCoordinator({sessions:new Map()});castEndgameUltimate(b,owner,core.id);if(mode==='team')cast._resolveAction(b,u,{kind:'item',targetId:u.id},events);else cast._resolvePlayer({},b,u,{kind:'item',targetId:u.id},null,events);assert.ok(owner.hp>5000);assert.ok(u.hp>1000&&u.hp<5000);}});
