import test from'node:test';import assert from'node:assert/strict';
import{makeCanal489,startCanal489,advanceCanal489,inputCanal489,publicCanal489}from'../src/canal/Rules489.js';
import{CANAL494,SPECIES494,sweep494}from'../src/canal/Rules494.js';
import{bindFocus494}from'../src/canal/Input494.js';
import{layout494,pressure494,draw494}from'../src/canal/Scene494.js';
import{view494,tick494,target494,switch494,receive494,click494,cooldown494}from'../src/canal/View494.js';
import{canalSignature489}from'../src/canal/View489.js';
function game(seed=47){const g=makeCanal489({id:'494',code:'A',partyId:'party',hostId:'p0',members:[{playerId:'p0',name:'あなた',choice:{id:'m',speciesId:'wolf'}}],now:0,seed});g.rules494=1;startCanal489(g,0);g.phase='playing';return g}
const enemy=(id,slot=0,lane=0,at=10000)=>({id,kind:0,lane,hp:1,maxHp:1,spawnAt:at-2000,travelMs:8000,visualSlot493:slot,wiggle:0,contributors:[]});
class E{constructor(doc){this.ownerDocument=doc;this.nodes=new Map();this.dataset={};this.style={};this.attrs={};this.children=[];this.listeners=new Map();this.classList={toggle(){}};this.clientWidth=375;this.clientHeight=460}addEventListener(n,f){const a=this.listeners.get(n)??new Set();a.add(f);this.listeners.set(n,a)}removeEventListener(n,f){this.listeners.get(n)?.delete(f)}emit(n,p={}){const e={preventDefault(){},button:0,target:this,pointerId:1,clientX:100,clientY:100,...p};for(const f of this.listeners.get(n)??[])f(e)}querySelector(q){return this.nodes.get(q)??null}querySelectorAll(q){return this.nodes.get(q)??[]}appendChild(x){this.children.push(x);x.parent=this}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this)}setAttribute(k,v){this.attrs[k]=v}getAttribute(k){return this.attrs[k]}getContext(){return null}closest(q){return q==='[data-cn-target494]'&&this.dataset.cnTarget494?this:null}}
function client(g){const doc={createElement:()=>new E(doc)},root=new E(doc),stage=new E(doc),host=new E(doc),canvas=new E(doc),sent=[];root.nodes.set('.cn494',stage);root.nodes.set('[data-cn-stage494]',stage);stage.nodes.set('canvas',canvas);root.nodes.set('[data-cn-targets494]',host);for(const q of ['[data-cn-alert494]','[data-cn-health494]','[data-cn-time494]','[data-cn-title494]'])root.nodes.set(q,new E(doc));const c={root,state:{canal:publicCanal489(g,'p0',10000),party:{hostId:'p0'}},transport:{selfId:'p0'},cnSound493:false,offset:0,ready:()=>true,connected:()=>true,raw:(op,m)=>{sent.push({op,m});return true},sgMonster463:()=>''};view494(c);return{c,root,stage,host,sent}}
test('tap is committed on release, while a swipe starting on a creature changes lanes without a capture',()=>{const s=new E(),w=new E(),b=new E();b.dataset.cnTarget494='7';const taps=[],swipes=[];const off=bindFocus494(s,{tap:id=>taps.push(id),swipe:d=>swipes.push(d)},w,true);s.emit('pointerdown',{target:b});assert.equal(taps.length,0);w.emit('pointerup');assert.deepEqual(taps,[7]);s.emit('pointerdown',{target:b});w.emit('pointermove',{clientX:30});w.emit('pointerup',{clientX:30});assert.deepEqual(taps,[7]);assert.deepEqual(swipes,[1]);off();s.emit('pointerdown',{target:b});w.emit('pointerup');assert.equal(taps.length,1)});
test('cancelled, multi-finger, vertical and out-and-back drags never capture',()=>{const s=new E(),w=new E(),b=new E();b.dataset.cnTarget494='1';let captures=0,swipes=0;bindFocus494(s,{tap:()=>captures++,swipe:()=>swipes++},w,true);s.emit('pointerdown',{target:b});w.emit('pointercancel');s.emit('pointerdown',{target:b});s.emit('pointerdown',{target:b,pointerId:2});w.emit('pointerup');w.emit('pointerup',{pointerId:2});s.emit('pointerdown',{target:b});w.emit('pointermove',{clientY:180});w.emit('pointerup',{clientY:180});s.emit('pointerdown',{target:b});w.emit('pointermove',{clientX:200});w.emit('pointerup');assert.equal(captures,0);assert.equal(swipes,0);s.emit('pointerdown',{target:b});w.emit('pointerup');assert.equal(captures,1)});
test('touch fallback handles swipes and cancellation with the same semantics',()=>{const s=new E(),w=new E(),b=new E();b.dataset.cnTarget494='9';const taps=[],swipes=[];bindFocus494(s,{tap:id=>taps.push(id),swipe:d=>swipes.push(d)},w,false);const touch=(x=100)=>({identifier:1,clientX:x,clientY:100,target:b});s.emit('touchstart',{changedTouches:[touch()]});w.emit('touchend',{changedTouches:[touch()]});s.emit('touchstart',{changedTouches:[touch()]});w.emit('touchend',{changedTouches:[touch(160)]});s.emit('touchstart',{changedTouches:[touch()]});w.emit('touchcancel',{changedTouches:[touch()]});assert.deepEqual(taps,[9]);assert.deepEqual(swipes,[-1])});
test('all four lanes can be aided; a stale target and repeated seq never redirect or duplicate a capture',()=>{const g=game(),p=g.players[0];g.enemies=[enemy(1,0,2),enemy(2,1,2)];const x={seq:1,lane:2,held:false,pulse:true,burst:false,targetId:1};assert.equal(inputCanal489(g,p,x,10000),true);assert.equal(p.assists,1);assert.equal(g.captured,1);assert.equal(inputCanal489(g,p,x,10300),false);assert.equal(sweep494(g,p,2,10300,false,1),false);assert.equal(g.enemies[0].id,2)});
test('holding is not an automatic attack in the new rule; old ongoing games retain their rule',()=>{const g=game(),p=g.players[0];g.enemies=[enemy(1)];assert.equal(inputCanal489(g,p,{seq:1,lane:0,held:true,pulse:true,burst:false},10000),false);assert.equal(g.captured,0);delete g.rules494;assert.equal(inputCanal489(g,p,{seq:1,lane:0,held:true,pulse:true,burst:false},10000),true);assert.equal(g.captured,1);assert.equal(p.held,true)});
test('breaches damage the shared house, snapshots expose HP, and lethal damage ends the game',()=>{const g=game();g.hp=10;for(const p of g.players)p.nextFireAt=20000;g.enemies=[{...enemy(1),spawnAt:1000,travelMs:2000}];g.simAt=9900;g.nextSpawnAt=20000;advanceCanal489(g,10000,()=>true);assert.equal(g.hp,0);assert.equal(g.phase,'result');assert.equal(g.success,false);assert.equal(g.events.at(-2).damage,SPECIES494[0].damage);const pub=publicCanal489(g,'p0',10000);assert.equal(pub.rules494,1);assert.equal(pub.hp,0);assert.equal(pub.enemies.length,0)});
test('resuming a durable snapshot is deterministic through the all-gates-open finale',()=>{const a=game(),b=JSON.parse(JSON.stringify(a));for(let at=a.startAt;at<=a.endAt;at+=100)advanceCanal489(a,at,()=>false);advanceCanal489(b,b.endAt,()=>false);assert.deepEqual(a,b)});
test('focused lane hit targets are large, stay in bounds, and never expose other lanes',()=>{for(const[w,h]of [[320,360],[375,460],[430,650],[620,280]]){const enemies=Array.from({length:6},(_,i)=>({...enemy(i+1,i),spawnAt:1000}));enemies.push(enemy(7,0,1));const a=layout494(enemies,0,8500,w,h);assert.equal(a.length,6);for(const e of a){assert.ok(e.size>=56);assert.ok(e.x-e.size/2>=0&&e.x+e.size/2<=w);assert.ok(e.y-e.size/2>=0&&e.y+e.size/2<h*.73)}for(const col of [0,1]){const list=a.filter(e=>e.visualSlot493%2===col);for(let i=1;i<list.length;i++)assert.ok(Math.abs(list[i].y-list[i-1].y)>list[i].size*.8)}}});
test('danger uses actual time to house, including the faster bass',()=>{const g={enemies:[{...enemy(1,0,1),spawnAt:1000,travelMs:10500},{...enemy(2,1,1),spawnAt:6000,travelMs:6200}]};assert.deepEqual(pressure494(g,0,10000),{count:0,eta:Infinity,danger:false,urgent:false});assert.equal(pressure494(g,1,10000).eta,1500);assert.equal(pressure494(g,1,10000).urgent,true)});
test('DOM buttons and production canvas share coordinates; switching hides old targets and preserves ACK queue',t=>{t.mock.method(Date,'now',()=>10000);const g=game();g.enemies=[enemy(1),enemy(2,0,2)];const{c,host,sent}=client(g);tick494(c);assert.equal(host.children.length,1);const e=c.cnUI494.frameLayout[0];assert.equal(host.children[0].style.left,e.x+'px');assert.equal(host.children[0].style.top,e.y+'px');assert.equal(target494(c,2),false);assert.equal(target494(c,1),true);switch494(c,2);assert.equal(c.cnUI494.pending.length,1);assert.equal(host.children.length,1);assert.equal(host.children[0].dataset.cnTarget494,'2');assert.equal(sent[0].m.inputs[0].targetId,1);assert.equal(sent[0].m.inputs[0].held,false)});
test('pointer-generated click cannot duplicate a released tap; keyboard click can capture',t=>{t.mock.method(Date,'now',()=>10000);const g=game();g.enemies=[enemy(1)];const{c,sent}=client(g);tick494(c);const b={dataset:{cnTarget494:'1'}};click494(c,b,{detail:1,pointerType:'touch'});assert.equal(sent.length,0);click494(c,b,{detail:0});assert.equal(sent.length,1);assert.equal(target494(c,1),false);assert.equal(cooldown494({nextFireAt:10000},{localFire:9900},10000,10000),120)});
test('offscreen urgency and hit direction are readable; countdown transition does not rebuild touch area',t=>{t.mock.method(Date,'now',()=>10000);const g=game();g.enemies=[{...enemy(1,0,1),spawnAt:3000}];const{c,root}=client(g);tick494(c);assert.match(root.querySelector('[data-cn-alert494]').textContent,/東が危険/);c.state.canal.events=[{id:1,kind:'breach',at:10000,lane:3,damage:17}];c.state.canal.hp=83;receive494(c);assert.match(root.querySelector('[data-cn-alert494]').textContent,/西から侵入.*17/);assert.equal(root.querySelector('[data-cn-health494]').attrs['aria-valuenow'],'83');c.state.canal.phase='countdown';const before=canalSignature489(c);c.state.canal.phase='playing';assert.deepEqual(canalSignature489(c),before)});
test('play footer has only the mega button; results keep the two clear common actions and no Home',()=>{const{c}=client(game());const html=view494(c),footer=html.match(/<footer[\s\S]*?<\/footer>/)[0];assert.equal((footer.match(/<button/g)||[]).length,1);assert.doesNotMatch(html,/data-cn-lane=/);assert.match(html,/左右スワイプ/);c.state.canal.phase='result';c.state.canal.grade='A';const result=view494(c);assert.equal((result.match(/data-party-result490=/g)||[]).length,2);assert.doesNotMatch(result,/ホームへ戻る/)});
test('replay restores own lane and clears transient visual and input state',()=>{const{c}=client(game());Object.assign(c.cnUI494,{lane:3,pending:[{seq:4}],preview:{enemyId:9},effects:[{}],localFire:9000,callout:{text:'old'}});c.state.canal.id='next';view494(c);assert.equal(c.cnUI494.lane,0);assert.deepEqual(c.cnUI494.pending,[]);assert.equal(c.cnUI494.preview,null);assert.equal(c.cnUI494.callout,null);assert.equal(c.cnUI494.localFire,0);assert.equal(c.cnSound493,false)});
test('drawing scales to rectangular playfield and renders house HP plus imminent impact seconds',()=>{const texts=[],ctx=new Proxy({fillText:t=>texts.push(t),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:()=>{}}),canvas={clientWidth:375,clientHeight:520,width:0,height:0,getContext:()=>ctx},g={phase:'playing',hp:24,enemies:[{...enemy(1),spawnAt:3000}]},u={lane:0,effects:[],reduced:true};draw494(canvas,g,u,10000,10000,layout494(g.enemies,0,10000,375,520));assert.equal(canvas.height,520);assert.ok(texts.some(x=>x.includes('24 / 100')));assert.ok(texts.some(x=>x.includes('あと1.0秒')))});
test('balance regression: idle human is not carried by AI; swiping with realistic delays and using the net can win',async()=>{const{run}=await import('./canal494-simulation.mjs');const idle=[],own=[],active=[];for(let seed=1;seed<=20;seed++){idle.push(run(seed,'idle'));own.push(run(seed,'own'));active.push(run(seed,'active'))}assert.equal(idle.filter(x=>x.win).length,0);assert.ok(active.filter(x=>x.win).length>=18);assert.ok(own.filter(x=>x.win).length<active.filter(x=>x.win).length);assert.ok(active.reduce((s,x)=>s+x.hp,0)/20<99);assert.ok(idle.every(x=>x.ended<60))});
