import test from 'node:test';import assert from 'node:assert/strict';import{mkdtempSync,readFileSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{expandedPower445,expandedPartyPower445}from'../src/core/PowerScale445.js';
import{monsterCombatPower,legacyMonsterCombatPower445,partyCombatPower,formatCombatPower,normalizeCombatPowerRecord,recordPartyCombatPower}from'../src/core/CombatPower.js';
import{createMonster,calculatedStats}from'../src/models/Monster.js';
import{PlayerPowerRanking,verifiedMonsterPower}from'../online-server/src/PlayerPowerRanking.js';
const session={playerId:'AD-ABCD-EFGH'},now=Date.parse('2026-09-15T10:00:00Z');
function snapshot(newScale=false){const monsters=[1,5,20,100].map(level=>createMonster('slime',{level}));const party=monsters.map((m,i)=>({slot:i+1,speciesId:'slime',name:'テスト',level:m.level,battleStats:calculatedStats(m),power:newScale?monsterCombatPower(m):legacyMonsterCombatPower445(m),equipment:[]}));return{displayName:'えなみ',maxFloor:100,party,power:party.reduce((s,m)=>s+m.power,0)};}
test('screenshot party is the sum of all four displayed ratings',()=>{assert.equal(expandedPartyPower445([5697,5408,6060,6487].map(power=>({power}))),1405071)});
test('growth contrast increases while preserving member order',()=>{assert.equal(expandedPower445(5000)/expandedPower445(1000),25);let last=0;for(let p=100;p<10000;p++){assert.ok(expandedPower445(p)>last);last=expandedPower445(p)}});
test('real stats are unchanged; party equals member sum',()=>{const m=createMonster('slime',{level:100}),s=calculatedStats(m),before=structuredClone(m);assert.equal(monsterCombatPower(m),expandedPower445(verifiedMonsterPower(s)));assert.deepEqual(m,before);assert.equal(partyCombatPower({monsters:[m],party:[m.id]}),monsterCombatPower(m))});
test('old high scores are preserved separately, migration is idempotent',()=>{const old={scaleVersion:4,highest:23652,previous:20000,history:[{power:23652,previous:20000,delta:3652,floor:100,at:'2026-09-14T00:00:00Z'}]};const m=createMonster('slime',{level:100}),state={records:{combatPower:structuredClone(old)},monsters:[m],party:[m.id],player:{maxFloor:100}};normalizeCombatPowerRecord(state);assert.equal(state.records.combatPower.legacyRecord445.highest,23652);assert.equal(state.records.combatPower.legacyRecord445.history[0].power,23652);recordPartyCombatPower(state);assert.equal(state.records.combatPower.highest,monsterCombatPower(m));const stable=structuredClone(state.records);recordPartyCombatPower(state);assert.deepEqual(state.records,stable)});
test('both old and new clients validate, old retry identity survives restart',()=>{const dir=mkdtempSync(join(tmpdir(),'power445-')),file=join(dir,'rank.json'),rank=new PlayerPowerRanking({now:()=>now,stateFile:file});const old=snapshot(),fresh=snapshot(true);assert.equal(rank.submit({...session},{requestId:'request-old-445',snapshot:old}).ok,true);const restarted=new PlayerPowerRanking({now:()=>now,stateFile:file});assert.equal(restarted.submit({...session},{requestId:'request-old-445',snapshot:old}).duplicate,true);assert.equal(restarted.submit({...session},{requestId:'request-new-445',snapshot:fresh}).ok,true);const row=restarted.list({...session}).message.entries[0];assert.equal(row.power,fresh.power);assert.equal(row.powerScaleVersion,5);assert.equal(JSON.parse(readFileSync(file)).records[0].power,old.power);const profile=restarted.profile({...session},{playerId:session.playerId}).message.profile;assert.equal(profile.party.reduce((s,m)=>s+m.power,0),row.power)});
test('existing disconnected players convert from persisted member scores exactly',()=>{const dir=mkdtempSync(join(tmpdir(),'old445-')),file=join(dir,'rank.json'),rank=new PlayerPowerRanking({now:()=>now,stateFile:file});rank.submit({...session},{requestId:'request-persisted-445',snapshot:snapshot()});const data=JSON.parse(readFileSync(file));data.records[0].party.forEach((m,i)=>m.power=[5697,5408,6060,6487][i]);data.records[0].power=23652;writeFileSync(file,JSON.stringify(data));const restored=new PlayerPowerRanking({now:()=>now,stateFile:file});assert.equal(restored.list({...session}).message.entries[0].power,1405071)});
test('forged scores rejected under either scale',()=>{const rank=new PlayerPowerRanking({now:()=>now}),s=snapshot(true);s.party[0].power*=7;s.power=s.party.reduce((a,m)=>a+m.power,0);assert.equal(rank.submit({...session},{requestId:'request-bad-445',snapshot:s}).code,'POWER_MISMATCH')});
test('compact labels stay short and never expose NaN/Infinity',()=>{for(const n of [0,1,5355,324558,999999,1405071,99999999,1e8,1e12,Number.MAX_SAFE_INTEGER,Infinity,NaN]){const label=formatCombatPower(n);assert.ok(label.length<=7,label);assert.ok(!/NaN|Infinity|e\+|,/.test(label),label)}assert.equal(formatCombatPower(1405071),'140.5万');assert.equal(formatCombatPower(324558),'324558')});
