// Keep the complete Build514 behavior checks: no rule/protocol change in this patch.
import './build514-quiz.test.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {effects515} from '../src/quiz/Effects515.js';
import {cue513} from '../src/quiz/Audio513.js';
const question=()=>({id:'quiz',round:3,phase:'question',phaseAt:1000,deadline:13000,players:[{alive:true},{alive:true}],reveal:null});
const reveal=()=>({...question(),phase:'reveal',phaseAt:13650,deadline:19850,reveal:{answer:'o',rows:[{wasAlive:true,correct:false,side:'x'},{wasAlive:true,correct:true,side:'o'}]}});
test('last visible 1 keeps a full sprite plus clearance across mobile/landscape sizes',()=>{for(const [height,pawnHeight] of [[205,43],[320,52],[600,65]]){const g=question();let previous=-Infinity;for(let at=g.phaseAt;at<g.deadline;at+=17){const f=effects515(g,at,{height,pawnHeight});assert.ok(f.wallPx>=previous-1e-9);previous=f.wallPx;assert.ok(.8*height+f.wallPx<=.7*height-pawnHeight-10+1e-6);assert.equal(f.landing,0)}const last=effects515(g,g.deadline-1,{height,pawnHeight});assert.equal(last.bigCount,1);assert.equal(last.closed,false)}});
test('zero triggers a 140ms slam, a finite impact and dust, independent of server lock arrival',()=>{const g=question(),options={height:320,pawnHeight:52},atZero=effects515(g,g.deadline,options),impact=effects515(g,g.deadline+140,options);assert.equal(atZero.closed,true);assert.equal(atZero.bigCount,null);assert.ok(atZero.wallPx<0);assert.equal(impact.wallPx,0);assert.equal(impact.dust,true);assert.equal(effects515(g,g.deadline+760,options).dust,false);const locked={...g,phase:'lock',phaseAt:g.deadline,deadline:g.deadline+650};assert.equal(effects515(locked,locked.phaseAt+140,options).wallPx,0)});
test('3 2 1 pulses stay readable and do not survive zero',()=>{const g=question();for(const [ms,number]of [[10000,3],[11000,2],[12000,1]]){const f=effects515(g,ms);assert.equal(f.bigCount,number);assert.equal(f.pulse,1)}assert.equal(effects515(g,13000).bigCount,null)});
test('old wall exits below with no alpha fade while next floor and divider arrive from above',()=>{const g=reveal(),height=350,start=effects515(g,g.phaseAt+4050,{height}),end=effects515(g,g.phaseAt+5600,{height});assert.ok(start.newFloorPx<0);assert.equal(end.newFloorPx,0);assert.ok(end.wallPx>height);assert.equal(end.arriving,true);assert.equal(end.incoming,1);assert.ok(start.newWallPx<end.newWallPx);assert.equal(end.newWallPx,effects515(question(),1000,{height}).wallPx);assert.equal(end.ascent,1)});
test('all-out, final question and last survivor never spawn a phantom next floor',()=>{for(const g of [{...reveal(),players:[]},{...reveal(),round:20},{...reveal(),players:[{alive:true}]}]){const f=effects515(g,g.phaseAt+5000);assert.equal(f.nextFloor,false);assert.equal(f.arriving,false);assert.equal(f.ascent,0)}});
test('reduced motion preserves closure and final position with no impact or camera animation',()=>{const g=reveal(),f=effects515(g,g.phaseAt+4700,{reduced:true});assert.equal(f.dust,false);assert.equal(f.shake,0);assert.equal(f.animate,false);assert.equal(f.arriving,false);assert.equal(f.ascent,0);assert.equal(effects515(question(),13000,{reduced:true}).wallPx,0)});
test('timeline retains frames through landing and lift settlement then becomes idle',()=>{const g=reveal();assert.equal(effects515(g,g.phaseAt+6000).animate,true);assert.equal(effects515(g,g.phaseAt+6200).animate,false);assert.equal(effects515({...question(),phase:'lock',phaseAt:13000},13150).animate,true)});
test('slam audio is deduplicated between predicted zero and server lock',()=>{const u={sound:false},g=question();cue513(u,g,{seconds:0,closed:true});const token=u.slam515;cue513(u,{...g,phase:'lock'},{closed:true});assert.equal(u.slam515,token);cue513(u,{...g,round:4,phase:'lock'},{closed:true});assert.notEqual(u.slam515,token)});
test('view uses separate opaque next-floor nodes and opaque old wall; marks are centered',()=>{const view=readFileSync(new URL('../src/quiz/View513.js',import.meta.url),'utf8'),css=readFileSync(new URL('../src/Styles/build515-quiz.css',import.meta.url),'utf8');assert.ok(view.includes('data-q-newfloor515'));assert.ok(view.includes("style506(n.wall,'opacity','1')"));assert.ok(!view.includes("String(1-f.ascent)"));assert.ok(css.includes('left:50%;right:auto;top:43%'));assert.ok(css.includes('translate(-50%,-50%)'));});
