import test from'node:test';import assert from'node:assert/strict';import{mkdtempSync,readFileSync,rmSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{RaceCoordinator451}from'../online-server/src/RaceCoordinator451.js';
import{RACE451,payout451,raceProfile451,drawRace451,ticketWins451,odds451,raceProgress451}from'../src/race/RaceRules451.js';
import{reserveRaceBet451,applyRaceDelivery451,raceBank451}from'../src/race/RaceWallet451.js';
import{createMonster,totalExperience}from'../src/models/Monster.js';
function harness(file=null){let time=100000;const sessions=new Map(),messages=new Map();for(let i=0;i<5;i++){const id='AD-RACE-000'+i;sessions.set(id,{playerId:id,clientKey:'fixture-key-long-enough-'+i,connected:true,profile:{displayName:'友達'+i}});messages.set(id,[])}const options={stateFile:file,sessions,send:(id,m)=>messages.get(id).push(structuredClone(m)),now:()=>time};let c=new RaceCoordinator451(options);return{get c(){return c},sessions,messages,s(i=0){return[...sessions.values()][i]},call(op,payload={},i=0){c.handle(this.s(i),{op,...payload})},state(i=0){return c.view(this.s(i))},restart(){c=new RaceCoordinator451(options)},advance(n){time+=n;c.advance()},roster:[{id:'m1',speciesId:'slime'},{id:'m2',speciesId:'myth_rion'}],make(humans=1){this.call('create',{roster:this.roster,displayName:'えなみ'});for(let i=1;i<humans;i++)this.call('join',{code:this.state().room.code,roster:this.roster},i);for(let i=0;i<humans;i++)this.call('select',{monsterId:'m1'},i);this.call('start');return this.state().room},bet(ticket={kind:'win',picks:[0]},amount=1000,i=0){const raceId=this.state(i).room.id;const packet={raceId,requestId:`${raceId}:${this.s(i).playerId}`,amount,ticket};this.call('bet',packet,i);return packet},finish(){this.advance(RACE451.betMs);this.advance(RACE451.countdownMs);this.advance(RACE451.raceMs)}}}
function wallet(){return{state:{player:{gold:10000},monsters:[{...createMonster('slime',{level:9}),id:'m1',affection:0}]},save:()=>true}}
test('four seats and eight entrants for 1–4 humans; foreign selection and fifth human rejected',()=>{for(let people=1;people<=4;people++){const h=harness(),r=h.make(people);assert.equal(r.members.length,4);assert.equal(r.racers.length,8);assert.equal(r.members.filter(m=>m.ai).length,4-people);assert.equal(r.system.length,4);assert.equal(r.phase,'parade');assert.equal(r.finishMs,null);assert.equal(r.order,null);assert.equal(JSON.stringify(r).includes('outcome'),false);h.call('join',{code:r.code,roster:h.roster},4);assert.equal(h.state(4).room,null)}const h=harness();h.call('create',{roster:h.roster});h.call('select',{monsterId:'unowned'});assert.equal(h.state().room.members[0].choice,null);h.call('start',{},1);assert.equal(h.state().room.phase,'lobby')});
test('race profiles ignore level/equipment, seeded result and animation agree with finishing order',()=>{const h=harness(),r=h.make();const a=drawRace451(r.racers,r.course,42),b=drawRace451(r.racers.map(x=>({...x,level:10000,rarity:'十神',equipment:{atk:99999999}})),r.course,42);assert.deepEqual(a,b);assert.deepEqual(a.order,[...a.order].sort((i,j)=>a.finishMs[i]-a.finishMs[j]));for(const [i,x]of r.racers.entries()){assert.equal(raceProgress451(x,a.finishMs[i],a.finishMs[i]),1);assert.ok(raceProgress451(x,a.finishMs[i]-1,a.finishMs[i])<1)}assert.deepEqual(raceProfile451('slime'),raceProfile451('slime'))});
test('all bet types, locked odds, ownership prize and ticket reward combine independently',()=>{for(const kind of['win','pair','exact']){const h=harness();h.make();const room=h.c.roomFor(h.s().playerId);room.outcome.order=[4,0,1,2,3,5,6,7];const ticket={kind,picks:kind==='win'?[4]:kind==='pair'?[0,4]:[4,0]},fixed=odds451(room.racers,room.course,ticket),p=h.bet(ticket);assert.equal(h.state().room.members[0].selfTicket.odds,fixed);assert.equal(h.state(1).room,null);h.finish();const entry=h.state().deliveries[0];assert.equal(entry.prize,5000);assert.equal(entry.payout,Math.floor(1000*fixed));assert.equal(entry.net,entry.payout+4000);assert.equal(entry.requestId,p.requestId);assert.equal(ticketWins451({kind:'exact',picks:[0,4]},room.outcome.order),false)}});
test('durable acceptance, no late redraw, duplicate bet and refund deliveries survive restart',()=>{const dir=mkdtempSync(join(tmpdir(),'race451-'));try{const h=harness(join(dir,'race.json'));h.make();const outcome=structuredClone(h.c.roomFor(h.s().playerId).outcome),p=h.bet();h.restart();h.call('bet',p);assert.deepEqual(h.c.roomFor(h.s().playerId).outcome,outcome);assert.equal(Object.keys(h.c.data.accounts[h.s().playerId].decisions).length,1);h.call('bet',{...p,amount:2000});assert.equal(h.state().room.members[0].selfTicket.amount,1000);h.finish();const results=structuredClone(h.state().deliveries);h.restart();assert.deepEqual(h.state().deliveries,results);h.call('ack',{ids:results.map(x=>x.id)});h.restart();assert.equal(h.state().deliveries.length,0);h.call('bet',p);assert.equal(h.state().deliveries.length,0);assert.ok(!readFileSync(join(dir,'race.json'),'utf8').includes(h.s().clientKey));}finally{rmSync(dir,{recursive:true,force:true})}});
test('late wager becomes a once-only refund; a non-buyer loses no GOLD',()=>{const h=harness();h.make();const r=h.state().room,p={raceId:r.id,requestId:`${r.id}:${h.s().playerId}`,ticket:{kind:'win',picks:[0]},amount:1000};h.call('pass');h.advance(RACE451.paradeMs);assert.equal(h.state().room.phase,'countdown');h.call('bet',p);h.call('bet',p);assert.equal(h.state().deliveries.length,1);assert.equal(h.state().deliveries[0].kind,'refund');h.finish();assert.equal(h.state().room.results[0].stake,0)});
test('selection deadline defaults to owned monster; disconnections finish without duplicate awards',()=>{const h=harness();h.call('create',{roster:h.roster});h.call('start');h.s().connected=false;h.advance(RACE451.entryMs);assert.equal(h.state().room.phase,'parade');assert.equal(h.state().room.members[0].choice.id,'m1');h.finish();assert.equal(h.state().room.phase,'result');const delivery=h.state().deliveries[0];h.advance(100000);assert.equal(h.state().deliveries.length,1);h.s().connected=true;h.call('status');assert.equal(h.state().deliveries[0].id,delivery.id)});
test('wallet debit, payout, EXP, affection, repeat receipt and rejected save are atomic',()=>{const h=harness();h.make();const r=h.state().room,hkey=`ws://localhost/party|${h.s().playerId}`,w=wallet(),p={raceId:r.id,requestId:`${r.id}:${h.s().playerId}`,ticket:{kind:'win',picks:[4]},amount:1000},beforeExp=totalExperience(w.state.monsters[0]);w.save=()=>false;assert.throws(()=>reserveRaceBet451(w,hkey,p));assert.equal(w.state.player.gold,10000);w.save=()=>true;reserveRaceBet451(w,hkey,p);assert.equal(w.state.player.gold,9000);assert.throws(()=>reserveRaceBet451(w,hkey,p));const entry={id:`result:${p.requestId}`,kind:'result',playerId:h.s().playerId,requestId:p.requestId,gold:12000,stake:1000,payout:7000,prize:5000,monsterId:'m1'};w.save=()=>false;assert.throws(()=>applyRaceDelivery451(w,hkey,entry));assert.equal(w.state.player.gold,9000);assert.equal(w.state.monsters[0].affection,0);w.save=()=>true;applyRaceDelivery451(w,hkey,entry);assert.equal(w.state.player.gold,21000);assert.equal(w.state.monsters[0].affection,5);assert.ok(totalExperience(w.state.monsters[0])>beforeExp);assert.equal(raceBank451(w.state,hkey).pending,null);applyRaceDelivery451(w,hkey,entry);assert.equal(w.state.player.gold,21000);assert.equal(w.state.monsters[0].affection,5)});
test('refund requires the exact local escrow; receipt remains retryable on save failure',()=>{const w=wallet(),key='ws://localhost/party|me',packet={raceId:'r451-1-12345678',requestId:'r451-1-12345678:me',amount:1000,ticket:{kind:'win',picks:[0]}},entry={id:'refund:'+packet.requestId,kind:'refund',requestId:packet.requestId,amount:1000,gold:1000};assert.throws(()=>applyRaceDelivery451(w,key,entry));reserveRaceBet451(w,key,packet);assert.throws(()=>applyRaceDelivery451(w,key,{...entry,amount:2000}));applyRaceDelivery451(w,key,entry);applyRaceDelivery451(w,key,entry);assert.equal(w.state.player.gold,10000)});
test('server persistence failure rolls back, corrupt state fails closed, account key cannot be replaced',()=>{const dir=mkdtempSync(join(tmpdir(),'race451-'));try{const path=join(dir,'blocked');writeFileSync(path,'file');const h=harness(path+'/race.json');h.call('create',{roster:h.roster});assert.equal(h.state().room,null);assert.equal(h.c.healthy(),false);writeFileSync(path,'{ broken');const corrupt=harness(path);corrupt.call('create',{roster:h.roster});assert.equal(corrupt.state().available,false);assert.equal(readFileSync(path,'utf8'),'{ broken');const good=harness();good.make();good.s().clientKey='different-client-key';good.call('status');assert.match(good.messages.get(good.s().playerId).at(-2).message,/本人確認/);}finally{rmSync(dir,{recursive:true,force:true})}});

test('GOLD payout uses integer tenths; special endgame monsters remain selectable',()=>{assert.equal(payout451(100,33.3),3330);const h=harness();h.call('create',{roster:[{id:'god',speciesId:'clockwork',raceSpeciesId:'ten_time'}]});h.call('select',{monsterId:'god'});h.call('start');assert.equal(h.state().room.racers[4].speciesId,'ten_time');assert.match(h.state().room.racers[4].name,/時間/)});
