import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import * as R from '../src/tower/Rules517.js';
import {impossible518,sealedRunners520} from '../src/tower/Reachability518.js';
import {layout520,camera520} from '../src/tower/Camera520.js';
import {bindDirections520} from '../src/tower/Controls520.js';
import {queueTower517} from '../online-server/src/TowerCoordinator517.js';
const C=R.TOWER517;
function make(){const g=R.makeTower517({id:'520',code:'520',hostId:'p0',members:Array.from({length:4},(_,i)=>({playerId:'p'+i,choice:{speciesId:'slime'}}))});g.roleMode='p0';R.startTower517(g,0,520);R.advanceTower517(g,3000);g.autoAt=1e8;return g}
function tick(g,ms,input=new Map()){for(let end=g.lastAt+ms;g.lastAt+17<end&&g.phase==='play';)R.advanceTower517(g,g.lastAt+50,input)}
function move(g,p,input={}){R.predictRunner517(g,p,input,1/60);g.elapsed+=C.step}
function cave(g){for(let y=0;y<3;y++)g.board.push({x:2,y,type:'O'});g.players[1].x=.5;g.players[2].x=5;g.players[3].x=8;g.boardRevision++}
test('super jump rises four cells with ordinary sideways movement; normal jump stays two',()=>{for(const [kind,low,high]of[['jump',2,2.2],['superJump',4,4.16]]){const g=make(),p=g.players[1];let peak=0;for(let i=0;i<110;i++){move(g,p,i===0?{[kind]:true,axis:.1}:{axis:.1});peak=Math.max(peak,p.y);assert.ok(Math.abs(p.vx)<=C.speed)}assert.ok(peak>=low&&peak<high,`${kind} peak ${peak}`);assert.equal(p.y,0)}});
test('boost is initially ready, spends cooldown on launch and becomes available at exactly 15 seconds',()=>{const g=make(),p=g.players[1];assert.equal(p.superReady,0);R.predictRunner517(g,p,{superJump:true},1/60);assert.equal(p.superReady,15000);for(const t of[1,100,14999]){p.y=0;p.vy=0;g.elapsed=t;R.predictRunner517(g,p,{superJump:true},1/60);assert.equal(p.superReady,15000);assert.equal(p.vy,0)}g.elapsed=15000;R.predictRunner517(g,p,{superJump:true},1/60);assert.ok(p.vy>13);assert.equal(p.superReady,30000)});
test('midair boost cannot reset velocity or consume cooldown; expired buffers cannot trigger later',()=>{const g=make(),p=g.players[1];p.y=8;p.vy=-1;p.grounded=false;p.coyote=-1;move(g,p,{superJump:true});assert.ok(p.vy<0);assert.equal(p.superReady,0);g.elapsed=200;p.y=0;p.vy=0;move(g,p);assert.equal(p.y,0);assert.equal(p.superReady,0)});
test('press just before landing buffers a single super jump',()=>{const g=make(),p=g.players[1];p.y=.05;p.vy=-4;p.grounded=false;p.coyote=-1;move(g,p,{superJump:true});move(g,p);assert.ok(p.vy>13);assert.ok(p.superReady>=15000);assert.equal(g.events.filter(e=>e.type==='superJump').length,1)});
test('super jump from a teammate head pushes an airborne lower teammate down and emits both cues',()=>{const g=make(),[lower,upper]=g.players.slice(1);lower.x=upper.x=5;lower.y=2;lower.vy=3;lower.grounded=false;upper.y=2+C.ph;upper.vy=0;move(g,upper,{superJump:true});assert.ok(upper.vy>13);assert.ok(lower.vy<0);assert.ok(g.events.some(e=>e.type==='bounce'));assert.ok(g.events.some(e=>e.type==='superJump'))});
test('boost cannot pass through a settled ceiling and old dash payloads grant no acceleration',()=>{const g=make(),p=g.players[1];p.x=4.5;g.board=[{x:4,y:2,type:'O'}];g.boardRevision++;let peak=0;for(let i=0;i<100;i++){move(g,p,i===0?{superJump:true}:{});peak=Math.max(peak,p.y);assert.ok(!R.solid517(g,p.x,p.y,false))}assert.ok(peak<2-C.ph+.01);move(g,p,{dash:true,axis:1});assert.equal(p.vx,C.speed)});
test('only the runner inside a newly sealed cavity dies; outside teammates keep playing',()=>{const g=make();cave(g);for(let x=0;x<3;x++)g.board.push({x,y:3,type:'I'});g.boardRevision++;assert.deepEqual(sealedRunners520(g).map(p=>p.playerId),['p1']);tick(g,50);assert.equal(g.players[1].alive,false);assert.equal(g.players[1].deathReason520,'sealed');assert.ok(g.players[2].alive&&g.players[3].alive);assert.equal(g.phase,'play');assert.equal(g.events.filter(e=>e.type==='sealed').length,1);tick(g,100);assert.equal(g.events.filter(e=>e.type==='sealed').length,1)});
test('a dropping roof is not a permanent seal until its landing tick',()=>{const g=make();cave(g);g.falling={id:1,type:'I',x:0,y:3.2,land:3,cells:R.shape517('I')};assert.equal(sealedRunners520(g).length,0);tick(g,50);assert.ok(g.players[1].alive);tick(g,100);assert.equal(g.players[1].alive,false);assert.equal(g.players[1].deathReason520,'sealed');assert.equal(g.phase,'play')});
test('all sealed runners lose in the same step, with no timeout or duplicate death events',()=>{const g=make();for(let x=0;x<10;x++)g.board.push({x,y:9,type:'I'});g.boardRevision++;tick(g,50);assert.equal(g.reason,'sealed');assert.equal(g.winner,'drop');assert.ok(g.players.slice(1).every(p=>!p.alive));assert.equal(g.events.filter(e=>e.type==='sealed').length,3);assert.ok(g.elapsed<100)});
test('one open column is not a complete seal even if a current jump cannot reach it',()=>{const g=make();for(let x=0;x<9;x++)g.board.push({x,y:13,type:'I'});g.boardRevision++;tick(g,100);assert.ok(g.players.slice(1).every(p=>p.alive));assert.equal(g.phase,'play')});
test('sole runner is allowed to wait for a four-cell boost when no hand can be placed',()=>{const g=make(),p=g.players[1];g.players.slice(2).forEach(p=>p.alive=false);for(let x=0;x<9;x++)g.board.push({x,y:C.height-1,type:'O'});g.board.push({x:9,y:C.height-5,type:'O'});g.boardRevision++;g.hand=['O','O','O','O'];p.x=9.5;p.y=C.height-4;p.vy=0;p.superReady=15000;assert.equal(impossible518(g),null);tick(g,100);assert.equal(g.phase,'play')});
test('saved Build519 active matches migrate once and persisted boost cooldown survives reloading',()=>{const g=make();g.rules517=2;for(const p of g.players){delete p.superReady;delete p.superUntil;p.dashReady=1000;p.dashUntil=100}tick(g,50);assert.equal(g.rules517,4);assert.equal(g.players[1].superReady,0);const p=g.players[1];move(g,p,{superJump:true});const ready=p.superReady,copy=JSON.parse(JSON.stringify(g));tick(copy,50);assert.equal(copy.players[1].superReady,ready);assert.equal(R.publicTower517(copy).players[1].superReady,ready)});
test('wire v4 merges simultaneous action edges but rejects stale v2 clients and duplicate packets',()=>{const g=make(),c={data:{towerRooms517:{room:g}},now:()=>1000},session={playerId:'p1'},p={gameId:g.id,towerVersion517:4,kind:'move',axis:1,seq:1};assert.equal(queueTower517(c,session,{...p,towerVersion517:2,superJump:true}),false);assert.ok(queueTower517(c,session,p));assert.ok(queueTower517(c,session,{...p,seq:2,jump:true}));assert.ok(queueTower517(c,session,{...p,seq:3,superJump:true}));assert.ok(queueTower517(c,session,{...p,seq:4,axis:0}));assert.equal(queueTower517(c,session,{...p,seq:4}),false);const rt=c.towerRuntime517.get(g.id),input=rt.inputs.get('p1');assert.equal(input.axis,0);assert.ok(input.jump&&input.superJump);R.advanceTower517(rt.g,rt.g.lastAt+50,rt.inputs);assert.ok(rt.g.players[1].superReady>0);assert.equal(input.superJump,false)});
test('AI uses the same four-cell boost to climb a high platform without mutating a live decision state',()=>{const g=make(),p=g.players[1];g.players.slice(2).forEach(p=>p.alive=false);p.x=3.5;for(let x=5;x<10;x++)for(let y=0;y<4;y++)g.board.push({x,y,type:'O'});g.boardRevision++;const before=structuredClone(g);R.botRunner517(g,p);assert.deepEqual(g,before);for(let i=0;i<240&&p.alive;i++)R.advanceTower517(g,g.lastAt+C.step,new Map([[p.playerId,R.botRunner517(g,p)]]));assert.ok(p.maxHeight>=4);assert.ok(p.superReady>0);assert.ok(p.y>=4);assert.equal(g.events.filter(e=>e.type==='superJump').length,1)});
test('camera uses all but 24 pixels of screen width and keeps a boosted runner in view',()=>{for(const w of[320,375,390,430,640])for(const h of[270,460,620]){const r={width:w,height:h,...layout520(w,h)},g=make(),p=g.players[1];assert.ok(Math.abs(r.cell*10-(w-24))<1e-6);camera520(r,g,p,0);for(let y=0;y<=C.height;y+=.1){p.y=y;camera520(r,g,p,1/60);const head=r.bottom-(y+1)*r.cell;assert.ok(head>=-1,`${w}/${h}/${y}/${head}`);assert.ok(r.cameraY>=0&&r.cameraY<=r.worldHeight-h+1e-6)}}});
test('overview contains every playable row; resize resets camera safely',()=>{for(const [w,h]of[[320,270],[390,500],[640,620]]){const r={width:w,height:h,overview520:true,...layout520(w,h,true)},g=make();camera520(r,g,g.players[0],0);assert.ok(r.top>=0);assert.ok(r.bottom<=h);assert.ok(r.left>=12)}});
test('touch directions support two fingers, sliding, cancellation and returning to the remaining thumb',()=>{const mk=(axis,left)=>({dataset:{twMove520:String(axis)},events:{},setPointerCapture(){},setAttribute(){},classList:{toggle(){}},getBoundingClientRect:()=>({left,right:left+80,top:0,bottom:90})});const buttons=[mk(-1,0),mk(1,88)],u={input:{axis:0},keys:{}},sends=[];const reset=bindDirections520(buttons,u,(b,t,f)=>b.events[t]=f,()=>sends.push(u.input.axis),()=>true,()=>{}),e=id=>({pointerId:id,preventDefault(){}});buttons[0].events.pointerdown(e(1));assert.equal(u.input.axis,-1);buttons[1].events.pointerdown(e(2));assert.equal(u.input.axis,1);buttons[1].events.pointerup(e(2));assert.equal(u.input.axis,-1);buttons[0].events.pointermove({...e(1),clientX:120,clientY:40});assert.equal(u.input.axis,1);buttons[0].events.pointercancel(e(1));assert.equal(u.input.axis,0);buttons[0].events.lostpointercapture(e(1));assert.equal(u.input.axis,0);buttons[1].events.pointerdown(e(3));reset();assert.equal(u.input.axis,0);assert.equal(u.moves520.size,0);assert.ok(sends.length>=6)});
test('native canvas caches remain unchanged during camera travel and rebuild only for size/board changes',async()=>{const require=createRequire(import.meta.url),{createCanvas}=require('@napi-rs/canvas'),old=globalThis.document;globalThis.document={createElement:()=>createCanvas(1,1)};try{const {makeRenderer517,resize517,paint517,follow520}=await import('../src/tower/Renderer517.js'),g=make(),r=makeRenderer517(createCanvas(390,500));resize517(r,390,500,3);const bg=r.background,tiles=r.settled,builds=r.cacheBuilds520;for(let i=0;i<60;i++){g.players[1].y=i/5;follow520(r,g,g.players[1],1/60);paint517(r,R.publicTower517(g),g.players,g.lastAt)}assert.equal(r.background,bg);assert.equal(r.settled,tiles);assert.equal(r.cacheBuilds520,builds);assert.equal(r.dpr,1.5);resize517(r,320,400,3);assert.equal(r.cacheBuilds520,builds+1)}finally{globalThis.document=old}});
