// Real coordinator integration. Only the two absent base-game catalogs use fixtures
// in a partial patch checkout. A complete checkout uses its real catalogs.
import test from 'node:test';
import assert from 'node:assert/strict';
import{registerHooks}from'node:module';
import{existsSync,mkdtempSync,rmSync,readFileSync}from'node:fs';
import{tmpdir}from'node:os';
import{join}from'node:path';
const fixtures={
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,context,next){const url=spec.startsWith('.')?new URL(spec,context.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,context)},load(url,context,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,context)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');hook.deregister();
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,canalVersion489:1,canalRules492:1,canalRules494:1,cabbageVersion484:1,cabbageScoring491:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function open(x,n=4){assert.deepEqual(x.send(0,'partyCreate462',{displayName:'Host',roster:[{id:'m0',speciesId:'wolf'}],game:'canal'}),[]);const p=Object.values(x.c.data.parties462)[0];for(let i=1;i<n;i++)assert.deepEqual(x.send(i,'partyJoin462',{code:p.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);const g=x.c.data.canalRooms489[p.code];for(let i=0;i<n;i++){assert.deepEqual(x.send(i,'canal489',{gameId:g.id,kind:'select',monsterId:'m'+i}),[]);assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[])}return{g,p}}
const inp=(seq,lane,held=true)=>({seq,lane,held,pulse:true,burst:false});
function start(x,g){assert.deepEqual(x.send(0,'canal489',{gameId:g.id,kind:'start'}),[])}
function seedEnemy(g,at,lane=0){g.enemies.push({id:++g.enemySerial,kind:0,lane,hp:1,maxHp:1,spawnAt:at-5000,travelMs:10000,wiggle:0})}
test('focused-lane protocol is required for ready/start and old clients cannot send new-game attacks',()=>{const x=setup(2),{g}=open(x,2);assert.equal(g.rules494,1);assert.equal(x.c.view(x.sessions.get('p0')).canalRules494,1);assert.ok(x.send(1,'partyReady462',{ready:true,canalRules494:0}).length);assert.ok(x.send(0,'canal489',{kind:'start',gameId:g.id,canalRules494:0}).length);start(x,g);x.time(g.startAt+1000);x.c.advance();x.send(0,'canalInput489',{gameId:g.id,canalRules494:0,inputs:[inp(1,0,false)]});assert.equal(x.c.canalQueue489?.size??0,0)});
test('swiping to the opposite waterway can aid through the authenticated queue without changing ownership',()=>{const x=setup(2),{g}=open(x,2);start(x,g);x.time(g.startAt+1000);x.c.advance();g.enemies=[];seedEnemy(g,x.now(),2);const target=g.enemies[0].id;x.send(0,'canalInput489',{gameId:g.id,inputs:[{...inp(1,2,false),targetId:target}]});x.time(x.now()+200);x.c.advance();assert.equal(g.players[0].assists,1);assert.equal(g.players[0].seat,0);assert.equal(g.players[0].lane,2);assert.equal(g.players[0].lastSeq,1);const p=x.c.view(x.sessions.get('p1')).canal.players[0];assert.equal(p.captured,1);assert.equal(p.lastSeq,undefined)});
test('old running Build492 room remains playable with its original protocol and coefficients',()=>{const x=setup(1),{g}=open(x,1);start(x,g);delete g.rules494;x.time(g.startAt+1000);x.c.advance();g.enemies=[];seedEnemy(g,x.now());x.send(0,'canalInput489',{gameId:g.id,canalRules494:0,inputs:[{...inp(1,0,true),targetId:g.enemies[0].id}]});x.time(x.now()+200);x.c.advance();assert.equal(g.players[0].captured,1);assert.equal(g.players[0].held,true);assert.equal(x.c.view(x.sessions.get('p0')).canal.rules494,undefined)});
test('new rule flag, house damage, shared net and input ACK persist across a server restart',()=>{const dir=mkdtempSync(join(tmpdir(),'canal494-'));try{const file=join(dir,'state.json'),x=setup(1,file),{g}=open(x,1);start(x,g);x.time(g.startAt+1000);x.c.advance();g.enemies=[];g.hp=55;seedEnemy(g,x.now(),2);const inputs=[{...inp(1,2,false),targetId:g.enemies[0].id}];x.send(0,'canalInput489',{gameId:g.id,inputs});x.time(x.now()+200);x.c.advance();const y=setup(1,file);y.time(x.now()+300);y.send(0,'canalInput489',{gameId:g.id,inputs});y.c.advance();const v=y.c.view(y.sessions.get('p0')).canal;assert.equal(v.rules494,1);assert.equal(v.hp,55);assert.equal(v.netEnergy,1);assert.equal(v.players[0].lastSeq,1);assert.equal(v.players[0].captured,1)}finally{rmSync(dir,{recursive:true,force:true})}});
