import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {WorldRaidCoordinator428} from '../online-server/src/WorldRaidCoordinator428.js';
import {worldRaidDay428,worldRaidReset428} from '../online-server/src/WorldRaidStore428.js';
import {WorldRaidBattle428} from '../online-server/src/WorldRaidBattle428.js';
import {sanitizeProfile} from '../online-server/src/RoomStore.js';

const profile=(power=20000)=>sanitizeProfile({displayName:'試験',monsterName:'試験スライム',speciesId:'slime',level:1000,battleStats:{hp:100000,mp:1000,atk:power,matk:power,def:5000,mdef:5000,spd:1000,accuracy:100,evasion:0,crit:0},skills:[]});
function fixture(options={}){let clock=Date.UTC(2026,8,13,10),messages=[];const sessions=new Map(),a={playerId:'AD-AAAA-AAAA',connected:true,profile:profile()},b={playerId:'AD-BBBB-BBBB',connected:true,profile:profile()};sessions.set(a.playerId,a);sessions.set(b.playerId,b);const c=new WorldRaidCoordinator428({sessions,now:()=>clock,random:()=>.5,send:(id,m)=>messages.push({id,...m}),...options});return {c,a,b,sessions,messages,now:()=>clock,setNow:n=>clock=n,tick:()=>{clock+=3000;c.advance();}};}
function start(f,who=f.a,key='request-0000000001'){const result=f.c.start(who,{requestId:key,campaignId:f.c.snapshot(who.playerId).campaign.id,profile:who.profile});assert.equal(result.ok,true,JSON.stringify(result));return f.c.snapshot(who.playerId).attempt;}
function command(f,who,kind='attack',target=null){const a=f.c.snapshot(who.playerId).attempt;return f.c.action(who,{attemptId:a.id,round:a.raid.round,actorId:who.playerId,kind,enemyTargetId:target??a.raid.boss.id});}
function manual(f,who){const a=f.c.snapshot(who.playerId).attempt;assert.equal(f.c.auto(who,{attemptId:a.id,round:a.raid.round,enabled:false}).ok,true);}

test('daily raid uses JST midnight; a boss change never refreshes the three daily entries',()=>{
 const f=fixture();assert.equal(worldRaidDay428(Date.UTC(2026,8,13,14,59,59)),'2026-09-13');assert.equal(worldRaidDay428(Date.UTC(2026,8,13,15)),'2026-09-14');assert.equal(worldRaidReset428(Date.UTC(2026,8,13,14)),Date.UTC(2026,8,13,15));
 for(let i=0;i<3;i++){const a=start(f,f.a,'daily-request-0000'+i);assert.equal(f.c.retreat(f.a,{attemptId:a.id,round:1}).ok,true);}
 const denied=f.c.start(f.a,{requestId:'daily-request-denied',campaignId:f.c.snapshot(f.a.playerId).campaign.id});assert.equal(denied.code,'WORLD_RAID_LIMIT');assert.equal(f.c.snapshot(f.a.playerId).remaining,0);
 f.setNow(Date.UTC(2026,8,13,15));assert.equal(f.c.snapshot(f.a.playerId).remaining,3);start(f,f.a,'next-day-request-0001');assert.equal(f.c.snapshot(f.a.playerId).remaining,2);
});

test('retry of a start receipt and active encounter rejection consume exactly one entry',()=>{const f=fixture(),a=start(f);const dup=f.c.start(f.a,{requestId:a.requestId,campaignId:a.campaignId});assert.equal(dup.duplicate,true);assert.equal(f.c.snapshot(f.a.playerId).remaining,2);assert.equal(f.c.start(f.a,{requestId:'another-start-000001',campaignId:a.campaignId}).code,'WORLD_RAID_ACTIVE');assert.equal(f.c.snapshot(f.a.playerId).remaining,2);});

test('two independent parties cumulatively damage one server HP; client damage fields are ignored',()=>{const f=fixture();start(f);start(f,f.b,'second-player-000001');manual(f,f.a);manual(f,f.b);const initial=f.c.snapshot(f.a.playerId).campaign.hp;const a=f.c.snapshot(f.a.playerId).attempt;assert.equal(f.c.action(f.a,{attemptId:a.id,round:1,kind:'attack',actorId:f.a.playerId,enemyTargetId:a.raid.boss.id,damage:999999999999999,hp:0}).ok,true);const da=f.c.snapshot(f.a.playerId).attempt.damage;assert.ok(da>0&&da<100000);assert.equal(command(f,f.b).ok,true);const db=f.c.snapshot(f.b.playerId).attempt.damage;assert.ok(db>0);assert.equal(f.c.snapshot(f.b.playerId).campaign.hp,initial-da-db);assert.equal(f.c.snapshot(f.a.playerId).campaign.hp,f.c.snapshot(f.b.playerId).campaign.hp);});

test('last hit advances exactly once, credits only remaining HP, and closes other old encounters',()=>{const f=fixture();f.c.ledger.state.current.hp=10;start(f);start(f,f.b,'second-kill-request');manual(f,f.a);manual(f,f.b);const old=f.c.snapshot(f.a.playerId).attempt;assert.equal(command(f,f.a).ok,true);const a=f.c.snapshot(f.a.playerId),b=f.c.snapshot(f.b.playerId);assert.equal(a.campaign.sequence,2);assert.equal(a.attempt.damage,10);assert.equal(a.attempt.report.result,'victory');assert.equal(b.attempt.report.result,'sharedVictory');assert.equal(f.c.ledger.state.history[0].killerId,f.a.playerId);assert.equal(f.c.ledger.state.history[0].contribution[f.a.playerId].damage,10);assert.equal(f.c.action(f.a,{attemptId:old.id,round:1,kind:'attack'}).ok,false);assert.equal(f.c.ledger.state.history.length,1);assert.equal(a.remaining,2);assert.equal(b.remaining,2);start(f,f.b,'next-boss-request-0001');assert.equal(f.c.snapshot(f.b.playerId).remaining,1);});

test('boss does not rotate by date and rejects a stale boss start without charging',()=>{const f=fixture(),original=f.c.snapshot(f.a.playerId).campaign.id;f.setNow(f.now()+14*86400000);assert.equal(f.c.snapshot(f.a.playerId).campaign.id,original);assert.equal(f.c.start(f.a,{requestId:'stale-boss-request01',campaignId:'old-world'}).code,'WORLD_RAID_CHANGED');assert.equal(f.c.snapshot(f.a.playerId).remaining,3);});

test('boss waits for five full rounds while level 100 minions act, then attacks in round six',()=>{const f=fixture();start(f);manual(f,f.a);for(let round=1;round<=6;round++){const before=f.messages.length;assert.equal(command(f,f.a,'guard').ok,true);const events=f.messages.slice(before).flatMap(m=>m.events??[]),a=f.c.snapshot(f.a.playerId).attempt;assert.ok(a.raid.minions.every(m=>m.level===100));assert.ok(events.some(e=>e.kind==='enemyDamage'&&e.actorId!==a.raid.boss.id));assert.equal(events.some(e=>e.kind==='enemyDamage'&&e.actorId===a.raid.boss.id),round===6);if(round<6)f.tick();}});

test('a surviving party finishes at ten rounds without resetting the campaign or issuing legacy rewards',()=>{const f=fixture();const attempt=start(f),actor=f.c.ledger.state.attempts[attempt.id].room.raid.players[f.a.playerId];actor.stats.def=1000000;actor.stats.mdef=1000000;manual(f,f.a);for(let round=1;round<=10;round++){assert.equal(command(f,f.a,'guard').ok,true);f.tick();}const s=f.c.snapshot(f.a.playerId);assert.equal(s.attempt.status,'ended');assert.equal(s.attempt.report.result,'limit');assert.equal(s.attempt.report.rounds,10);assert.equal(s.remaining,2);assert.equal(s.campaign.sequence,1);assert.equal(f.messages.some(m=>m.type==='onlineReward'),false);});

test('another player cannot operate the attempt and stale rounds cannot hit twice',()=>{const f=fixture();const a=start(f);manual(f,f.a);assert.equal(f.c.action(f.b,{attemptId:a.id,round:1,kind:'attack'}).ok,false);command(f,f.a);const hp=f.c.snapshot(f.a.playerId).campaign.hp;f.tick();assert.equal(f.c.action(f.a,{attemptId:a.id,round:1,kind:'attack'}).code,'WORLD_RAID_ROUND');assert.equal(f.c.snapshot(f.a.playerId).campaign.hp,hp);});

test('disconnect pauses the same battle and reconnect keeps its quota and damage',()=>{const f=fixture();start(f);manual(f,f.a);command(f,f.a);const before=f.c.snapshot(f.a.playerId);f.a.connected=false;for(let i=0;i<10;i++)f.tick();assert.equal(f.c.snapshot(f.a.playerId).attempt.raid.round,before.attempt.raid.round);const replacement={...f.a,connected:true};f.sessions.set(replacement.playerId,replacement);f.c.status(replacement);assert.equal(f.c.snapshot(replacement.playerId).attempt.id,before.attempt.id);assert.equal(f.c.snapshot(replacement.playerId).remaining,2);f.c.advance();assert.equal(f.c.snapshot(replacement.playerId).attempt.raid.round,2);});

test('server restart restores active battle, shared HP, receipt and daily count',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'world428-')),stateFile=path.join(dir,'world.json');try{const f=fixture({stateFile});const a=start(f);manual(f,f.a);command(f,f.a);const before=f.c.snapshot(f.a.playerId),c=new WorldRaidCoordinator428({sessions:f.sessions,now:f.now,stateFile});assert.equal(c.healthy(),true);const after=c.snapshot(f.a.playerId);assert.equal(after.campaign.hp,before.campaign.hp);assert.equal(after.attempt.damage,before.attempt.damage);assert.equal(after.attempt.raid.phase,before.attempt.raid.phase);assert.equal(after.attempt.id,a.id);assert.equal(after.remaining,2);assert.equal(c.start(f.a,{requestId:a.requestId,campaignId:a.campaignId}).duplicate,true);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('failed durable writes roll back entry, damage, actions and next-boss advancement',()=>{let writable=true;const f=fixture({persist:()=>writable});writable=false;assert.equal(f.c.start(f.a,{requestId:'failed-save-start01',campaignId:f.c.snapshot(f.a.playerId).campaign.id}).code,'WORLD_RAID_SAVE');assert.equal(f.c.snapshot(f.a.playerId).remaining,3);writable=true;f.c.ledger.state.current.hp=10;start(f);manual(f,f.a);const before=JSON.stringify(f.c.ledger.state);writable=false;assert.equal(command(f,f.a).code,'WORLD_RAID_SAVE');assert.equal(JSON.stringify(f.c.ledger.state),before);writable=true;assert.equal(command(f,f.a).ok,true);assert.equal(f.c.snapshot(f.a.playerId).campaign.sequence,2);});

test('invalid ledger cannot silently reset daily limits or shared HP',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'world428-bad-')),stateFile=path.join(dir,'world.json');try{fs.writeFileSync(stateFile,'corrupt');const f=fixture({stateFile});assert.equal(f.c.healthy(),false);assert.equal(f.c.start(f.a,{requestId:'broken-state-start1',campaignId:f.c.snapshot(f.a.playerId).campaign.id}).code,'WORLD_RAID_STORAGE');assert.equal(fs.readFileSync(stateFile,'utf8'),'corrupt');}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('current online room and trade block starting a separate raid',()=>{const f=fixture();f.a.roomId='room';assert.equal(f.c.start(f.a,{requestId:'busy-room-request01',campaignId:f.c.snapshot(f.a.playerId).campaign.id}).code,'WORLD_RAID_BUSY');assert.equal(f.c.snapshot(f.a.playerId).remaining,3);});

test('damage over time uses 1.6 million reference HP only on the world boss',()=>{
 const f=fixture(),a=start(f);manual(f,f.a);const b=f.c.ledger.state.attempts[a.id].room.raid;
 for(const enemy of [b.boss,b.minions[0]])enemy.effects.push({kind:'status:burn',name:'炎傷',value:.03,turns:3,sourcePlayerId:f.a.playerId});
 command(f,f.a,'guard');f.tick();const events=f.messages.flatMap(m=>m.events??[]).filter(e=>e.kind==='statusDamage');
 assert.ok(events.some(e=>e.targetId===b.boss.id&&e.value===48000));assert.ok(events.some(e=>e.targetId===b.minions[0].id&&e.value===375));
});

test('old completed battle payloads compact without losing their start receipts or reports',()=>{
 const f=fixture(),first=start(f);f.c.retreat(f.a,{attemptId:first.id,round:1});const second=start(f,f.a,'compact-request-0002');
 const old=f.c.ledger.state.attempts[first.id];assert.equal(old.room,undefined);assert.equal(old.profile,undefined);assert.equal(old.report.result,'retreat');
 assert.equal(f.c.start(f.a,{requestId:first.requestId,campaignId:first.campaignId}).duplicate,true);assert.equal(f.c.snapshot(f.a.playerId).remaining,1);assert.equal(f.c.snapshot(f.a.playerId).attempt.id,second.id);
});
