import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks,createRequire} from 'node:module';
import {existsSync,mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {makeLuck509,startLuck509,chooseLuck509,advanceLuck509,publicLuck509,drawPlan509,resolveRound509,aiPick509,ITEMS509,LUCK509,metres509,ranks509} from '../src/luck/Rules509.js';
import {makeLuck507,startLuck507,drawPlan507} from '../src/luck/Rules507.js';
import {raceFrame509,broadcastFrame509,paintKey509,distance509,fullDistance509,formula509} from '../src/luck/Presentation509.js';
const fixtures={
 [new URL('../src/ui/MonsterVisual.js',import.meta.url).href]:`export const monsterVisual=()=>'<i class="test-sprite"></i>';export const setMonsterVisualFrame=()=>{};`,
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,c,next){const url=spec.startsWith('.')?new URL(spec,c.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,c)},load(url,c,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,c)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');
const {luckView510,luckAfter510,luckBefore510,luckTick510,paintLuck510,requestLuck510,luckReceive510,luckClick510}=await import('../src/luck/View510.js');
const {raceDomSignature452}=await import('../src/race/RacePresentation452.js');
const {gorillaView502}=await import('../src/gorilla/View502.js');
hook.deregister();
const plan=()=>drawPlan509(n=>n-1);
function game(n=4){const g=makeLuck509({id:'luck-test',code:'ABC123',partyId:'party',hostId:'p0',members:Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'P'+i,color499:['orange','pink','green','blue'][i],owned:[{id:'m'+i,speciesId:'wolf'}],choice:{id:'m'+i,speciesId:'wolf'}}))});startLuck509(g,1000,plan());return g}
const begin=g=>{advanceLuck509(g,g.nextAt);return g.phaseAt};
function chooseAll(g,kind,order=[0,1,2,3]){for(const seat of order){const p=g.players[seat];if(!p.ai)chooseLuck509(g,p.playerId,kind,0,g.round,g.phaseAt+10)}advanceLuck509(g,g.nextAt);return g}
function readyItems(ids=['dash','rocket','shield','engine'],dist=[0,0,0,0]){const g=game();g.players.forEach((p,i)=>p.distance=dist[i]);g.plan509[0].seats.forEach((d,i)=>d.boxes[0]=[ids[i],...ITEMS509.filter(x=>x.id!==ids[i]).slice(0,3).map(x=>x.id)]);begin(g);chooseAll(g,'chest');chooseAll(g,'hand');assert.equal(g.phase,'reveal');return g}
function context(g,self='p0'){return{state:{luck:publicLuck509(g,self),party:{id:'party',hostId:'p0',members:g.members.map(m=>({...m,connected:true})),game:'luck',phase:g.phase},available:true,serverNow:g.phaseAt,partyResultActions490:1},transport:{selfId:self},offset:g.phaseAt-Date.now(),sgMonster463:()=>'<span class="sg-monster"><i></i></span>',sgSpeciesName463:id=>id,ready:()=>true,connected:()=>true,roster:()=>[{id:'m0',speciesId:'wolf'}],bank:()=>null,save:{state:{player:{gold:1000,crystals:0},settings:{audioEnabled:false},monsters:[]}},root:{querySelector:()=>null},draft:{code:'ABC123'},render(){},lkUI510:{gameId:g.id,artReady:true,sound:false}}}
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,luckVersion507:1,luckVersion508:1,luckVersion509:1,gorillaVersion502:1,gorillaRules503:1,gorillaRules504:1,gorillaRules505:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function start(x,n=x.sessions.size){assert.deepEqual(x.send(0,'partyCreate462',{game:'luck',roster:[{id:'m0',speciesId:'wolf'}]}),[]);const party=Object.values(x.c.data.parties462)[0],get=()=>x.c.data.luckRooms507[party.code];for(let i=1;i<n;i++){assert.deepEqual(x.send(i,'partyJoin462',{code:party.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);assert.deepEqual(x.send(i,'luck509',{gameId:get().id,kind:'select',monsterId:'m'+i}),[])}for(let i=0;i<n;i++)assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[]);assert.deepEqual(x.send(0,'luck509',{gameId:get().id,kind:'start'}),[]);return{party,get}}

function dom(g=game()){
 let mutations=0,serial=0;const queue=new Map(),listeners=new Map(),saved={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};
 function el(){const values={},attrs={},children=new Map();return{clientHeight:350,clientWidth:393,dataset:new Proxy({},{set(t,k,v){mutations++;t[k]=v;return true}}),style:new Proxy({setProperty(k,v){this[k]=v},getPropertyValue(k){return this[k]??''},getPropertyPriority(){return''}},{set(t,k,v){mutations++;t[k]=v;return true}}),classList:{contains:s=>s==='lk-play508'},getAttribute:k=>attrs[k]??null,setAttribute(k,v){mutations++;attrs[k]=v},addEventListener(){},removeEventListener(){},contains:()=>false,querySelector(q){if(!children.has(q))children.set(q,el());return children.get(q)},querySelectorAll:()=>[],get textContent(){return values.textContent},set textContent(v){mutations++;values.textContent=v},get disabled(){return values.disabled},set disabled(v){mutations++;values.disabled=v},get hidden(){return values.hidden},set hidden(v){mutations++;values.hidden=v}}}
 const root=el(),groups={'[data-gear-slot510]':28,'[data-volley510] .lk-art508':9,'[data-chest510]':4,'[data-hand-pick510]':4,'[data-dot510]':8,'[data-mark510]':7,'[data-reveals510] .lk-art508':4};for(const[k,v]of Object.entries(groups))groups[k]=Array.from({length:v},el);root.querySelectorAll=q=>groups[q]??[];
 globalThis.document={visibilityState:'visible',querySelector:()=>null,addEventListener:(n,fn)=>listeners.set(n,fn),removeEventListener:n=>listeners.delete(n)};globalThis.requestAnimationFrame=fn=>{const id=++serial;queue.set(id,fn);return id};globalThis.cancelAnimationFrame=id=>queue.delete(id);
 if(g.phase==='countdown')begin(g);const c=context(g);c.root={querySelector:()=>root};c.offset=g.phaseAt-Date.now();c.raw=()=>true;
 return{g,c,root,groups,queue,listeners,mutations:()=>mutations,reset:()=>mutations=0,flush(){const jobs=[...queue.values()];queue.clear();for(const f of jobs)f()},restore(){luckBefore510(c);for(const[k,v]of Object.entries(saved)){if(v===undefined)delete globalThis[k];else globalThis[k]=v}}}
}

import {raceFrame510,courseOffsets510,markerLabel510,passages510,paintKey510,animating510} from '../src/luck/Presentation510.js';
function scenario(from=[1000,6000,0,1200],to=from,items=['dash','dash','dash','dash']){const g=game();g.phase='run';g.phaseAt=10000;g.nextAt=14800;g.event={round:1,rows:g.players.map((p,i)=>({seat:i,playerId:p.playerId,from:from[i],to:to[i],delta:(BigInt(to[i])-BigInt(from[i])).toString(),gain:Math.max(0,Number(to[i])-Number(from[i])),item:items[i]})),attacks:[],castMs:0};g.players.forEach((p,i)=>p.distance=from[i]);return g}
const frame=(g,ms=0,self='p0',reduce=false)=>raceFrame510(g,g.phaseAt+ms,self,reduce);
test('camera is exactly self ±1000m and distant sprites are never pinned to the viewport',()=>{const g=scenario([5000,10000,3999,6001]);const f=frame(g);assert.equal(f.span,2000);assert.equal(f.rows[0].x,50);assert.equal(f.rows[1].x,300);assert.equal(f.rows[1].visible,false);assert.equal(f.rows[1].offscreen,'right');assert.equal(f.rows[1].gapLabel,'5,000m先');assert.equal(f.rows[2].offscreen,'left');assert.equal(f.rows[2].gapLabel,'1,001m後ろ');assert.equal(f.rows[3].offscreen,'right')});
test('window boundaries and all four personal camera views use the same physical gaps',()=>{const g=scenario([1000,0,2000,1500]);for(let seat=0;seat<4;seat++){const f=frame(g,0,'p'+seat);assert.equal(f.rows[seat].x,50);for(let j=0;j<4;j++){assert.equal(f.rows[j].gap,String(g.players[j].distance-g.players[seat].distance));assert.equal(f.rows[j].visible,Math.abs(g.players[j].distance-g.players[seat].distance)<=1000)}}assert.equal(frame(g).rows[1].x,0);assert.equal(frame(g).rows[2].x,100)});
test('a rival 5000m behind enters on the left, passes self, exits right; reciprocal view reverses',()=>{const g=scenario([5000,0,1000,1100],[5500,12000,1000,1100]);const seen=[];for(let ms=0;ms<=4800;ms+=8){const a=frame(g,ms),b=frame(g,ms,'p1');assert.equal(a.rows[1].q-a.rows[0].q,-(b.rows[0].q-b.rows[1].q));if(a.rows[1].visible)seen.push(a.rows[1].x)}assert.ok(seen.length>10);assert.ok(seen[0]<3);assert.ok(seen.at(-1)>97);assert.ok(seen.some(x=>x>48&&x<52));assert.equal(frame(g).rows[1].offscreen,'left');assert.equal(frame(g,4800).rows[1].offscreen,'right');assert.equal(frame(g,4800,'p1').rows[0].offscreen,'left')});
test('one-metre gaps stay exact even at 10^40m; window does not zoom out to fit everyone',()=>{const n=10n**40n,g=scenario([n.toString(),(n+1n).toString(),(n-5000n).toString(),(n+800n).toString()]);const f=frame(g);assert.equal(f.rows[1].gap,'1');assert.equal(f.rows[1].x,50.05);assert.equal(f.rows[2].gapLabel,'5,000m後ろ');assert.equal(f.rows[3].x,90);assert.equal(f.span,2000);assert.equal(f.rows[0].rank,3)});
test('ground, near layer, horizon and markers follow actual distance without the 6000m cap',()=>{const g=scenario([1000,0,100,200],[51000,0,100,200]);let previous=frame(g),travel=0;const width=400,tile=100000;let offset=courseOffsets510(previous,width,tile);for(let ms=8;ms<=4800;ms+=8){const f=frame(g,ms),next=courseOffsets510(f,width,tile);const delta=Number(f.cameraQ-previous.cameraQ)/1e6;assert.ok(Math.abs((next.ground-offset.ground)-delta/2000*width)<1e-6);assert.ok(Math.abs((next.horizon-offset.horizon)-delta/2000*width*.22)<1e-6);assert.ok(Math.abs((next.near-offset.near)-delta/2000*width*2.8)<1e-6);travel+=next.ground-offset.ground;previous=f;offset=next}assert.equal(travel,10000);assert.equal(frame(g,4800).rows[0].exact,'51000')});
test('labels and dashed lines have one transform and 500m spacing with subpixel interpolation',()=>{const g=scenario([1234,0,100,200],[6234,0,100,200]);for(let ms=0;ms<4800;ms+=17){const f=frame(g,ms);for(let i=1;i<f.marks.length;i++){assert.equal(BigInt(f.marks[i].distance)-BigInt(f.marks[i-1].distance),500n);assert.ok(Math.abs(f.marks[i].x-f.marks[i-1].x-25)<1e-8)}for(const m of f.marks)assert.ok(Math.abs(m.x-(Number(BigInt(m.distance)*1000000n-f.cameraQ)/1e6/20))<1e-8)}const a=frame(g,2300),b=frame(g,2301);assert.ok(b.marks[2].x<a.marks[2].x);assert.ok(a.marks[2].x-b.marks[2].x<1)});
test('negative start markers are hidden, giant absolute marker labels retain distinct last digits',()=>{const g=scenario([0,0,0,0]),f=frame(g);assert.deepEqual(f.marks.filter(m=>m.hidden).map(m=>m.distance),['-1000','-500']);assert.equal(markerLabel510('1500'),'1,500m');assert.notEqual(markerLabel510('10000000000001500'),markerLabel510('10000000000002000'))});
test('background modulo remains finite and within one tile at huge distances and viewport resizes',()=>{const g=scenario(['12345678901234567890123456789012345678901234567890',0,1,2]);for(const w of [320,393,709,1000])for(const tile of [500,950,1400]){const o=courseOffsets510(frame(g),w,tile);assert.ok(Object.values(o).every(x=>Number.isFinite(x)&&x>=0&&x<tile))}});
test('backward motion scrolls the world in the opposite direction, stationary players do not bob',()=>{const g=scenario([5000,0,100,200],[1000,0,100,200]);const a=frame(g,2200),b=frame(g,2300);assert.ok(b.cameraQ<a.cameraQ);assert.equal(b.direction,-1);assert.equal(b.rows[1].moving,false);assert.equal(b.rows[1].y,0);assert.equal(b.rows[1].trail,false)});
test('camera and scrolling are continuous at the run/settle and settle/next-round boundaries',()=>{const g=scenario([5000,0,100,200],[17000,20,100,200]);const end=frame(g,4800),a=courseOffsets510(end,393,1000);g.phase='settle';assert.deepEqual(courseOffsets510(frame(g),393,1000),a);g.players.forEach((p,i)=>p.distance=g.event.rows[i].to);g.phase='chest';g.event=null;assert.deepEqual(courseOffsets510(frame(g),393,1000),a)});
test('sub-frame passes have a bounded crossing afterimage while ordinary passes stay physical',()=>{const quick=scenario([500000,0,1,2],[500000,1000000,1,2]),p=passages510(quick.event,0);assert.equal(p.length,1);const cross=p[0];assert.equal(cross.direction,1);const f=frame(quick,cross.at);assert.ok(Math.abs(f.rows[1].afterimage.x-50)<.001);assert.equal(frame(quick,cross.at+200).rows[1].afterimage,null);const normal=scenario([5000,0,1,2],[5500,12000,1,2]);assert.equal(passages510(normal.event,0).length,0)});
test('reduced motion renders a stable final world and no residual crossing/animation',()=>{const g=scenario([500000,0,1,2],[500000,1000000,1,2]);const f=frame(g,100,'p0',true);assert.equal(f.rows[1].exact,'1000000');assert.ok(f.rows.every(r=>!r.moving&&!r.trail&&!r.afterimage));assert.equal(animating510(g,g.phaseAt+100,true),false)});
test('new production rooms skip the power phase for all 8 rounds; saves keep the same rolls and results',()=>{const x=setup(1),a=start(x);assert.equal(a.get().presentation510,1);const legacy=structuredClone(a.get());delete legacy.presentation510;const phases=new Set();while(a.get().phase!=='result'){x.time(a.get().nextAt);x.c.advance();phases.add(a.get().phase)}assert.ok(!phases.has('power'));advanceLuck509(legacy,1e7);assert.deepEqual(a.get().players,legacy.players);assert.deepEqual(a.get().results,legacy.results);assert.equal(legacy.resultAt-a.get().resultAt,8*3000);assert.deepEqual(a.get().plan509,legacy.plan509)});
test('old saved power phase still resumes safely but new view never creates the calculation panel',()=>{const g=readyItems();advanceLuck509(g,g.nextAt);assert.equal(g.phase,'power');const c=context(g);const html=luckView510(c);assert.doesNotMatch(html,/data-power|STACK & MULTIPLY|発進前のパワー|積んだぶんだけ/);advanceLuck509(g,1e7);assert.equal(g.phase,'result')});
test('new view renders four circular edge locators and labels without extra course image assets',()=>{const c=context(scenario());const html=luckView510(c);assert.equal((html.match(/data-locator510="/g)??[]).length,4);assert.equal((html.match(/data-gap510="/g)??[]).length,4);assert.equal((html.match(/data-near510/g)??[]).length,1);assert.doesNotMatch(html,/NaN|undefined|assets\/luck510/)});
test('actual DOM paint hides remote bodies and updates edge distance, then restores a passing rival',()=>{const d=dom(scenario([5000,0,1000,1100],[5500,12000,1000,1100]));try{luckAfter510(d.c);d.flush();d.c.lkUI510.lastPaint=null;paintLuck510(d.c,10000);const n=d.c.lkUI510.nodes;assert.equal(n.players[1].runner.hidden,true);assert.equal(n.players[1].locator.hidden,false);assert.equal(n.players[1].gap.textContent,'5,000m後ろ');assert.equal(n.players[1].locator.dataset.side,'left');let at=10000;while(at<14800&&!raceFrame510(d.c.state.luck,at,'p0').rows[1].visible)at+=8;paintLuck510(d.c,at);assert.equal(n.players[1].runner.hidden,false);assert.equal(n.players[1].locator.hidden,true);paintLuck510(d.c,14800);assert.equal(n.players[1].runner.hidden,true);assert.equal(n.players[1].locator.dataset.side,'right');assert.match(n.ground.style.transform,/translate3d/);assert.match(n.near.style.transform,/translate3d/);assert.doesNotMatch(n.ground.style.transform,/NaN|Infinity/)}finally{d.restore()}});
test('finite RAF chain keeps animating without a 33ms server/UI poll and stops when finished',()=>{const d=dom(scenario([1000,0,1,2],[2000,8000,1,2])),realNow=Date.now;let now=10000;Date.now=()=>now;d.c.offset=0;try{luckAfter510(d.c);assert.equal(d.queue.size,1);d.flush();assert.equal(d.queue.size,1);now+=17;d.flush();assert.equal(d.queue.size,1);now=14800;d.flush();assert.equal(d.queue.size,0);const k=paintKey510(d.c.state.luck,14800,true,null,false);assert.equal(k,paintKey510(d.c.state.luck,99999,true,null,false));d.reset();luckTick510(d.c);assert.equal(d.queue.size,0);assert.equal(d.mutations(),0)}finally{Date.now=realNow;d.restore()}});
test('hidden/unmounted screens cancel RAF and do not replay an old passing animation on return',()=>{const d=dom(scenario([500000,0,1,2],[500000,1000000,1,2])),realNow=Date.now;let now=12000;Date.now=()=>now;d.c.offset=0;try{luckAfter510(d.c);d.flush();document.visibilityState='hidden';d.listeners.get('visibilitychange')();assert.equal(d.queue.size,0);now=14500;document.visibilityState='visible';d.listeners.get('visibilitychange')();d.flush();assert.ok(d.c.lkUI510.nodes.players.every(p=>p.pass.hidden));luckBefore510(d.c);assert.equal(d.queue.size,0);assert.equal(d.listeners.size,0)}finally{Date.now=realNow;d.restore()}});
test('static choosing screens retain DOM and perform zero writes for repeated identical times',()=>{const d=dom();try{luckAfter510(d.c);d.flush();paintLuck510(d.c,d.g.phaseAt+20);d.reset();for(let i=0;i<1000;i++)paintLuck510(d.c,d.g.phaseAt+20);assert.equal(d.mutations(),0);assert.equal(d.queue.size,0);let sent=0;d.c.raw=(op)=>{assert.equal(op,'luck509');sent++;return true};for(let i=0;i<100;i++)requestLuck510(d.c,'chest',0);assert.equal(sent,1)}finally{d.restore()}});
test('500 seeded races preserve results with the new shorter timeline',()=>{for(let seed=1;seed<=500;seed++){let z=seed;const old=game(1);old.plan509=drawPlan509(n=>{z=(Math.imul(z,1664525)+1013904223)>>>0;return z%n});const modern=JSON.parse(JSON.stringify(old));modern.presentation510=1;advanceLuck509(old,1e7);advanceLuck509(modern,1e7);assert.deepEqual(modern.players,old.players);assert.deepEqual(modern.results,old.results);assert.equal(old.resultAt-modern.resultAt,24000);for(const event of modern.history){const g={...modern,phase:'run',phaseAt:0,event};for(let ms=0;ms<=4800;ms+=800){const f=raceFrame510(g,ms,'p0');assert.ok(f.rows.every(r=>Number.isFinite(r.x)));assert.ok(Object.values(courseOffsets510(f,393,1040)).every(Number.isFinite))}}}});
