import test from 'node:test';import assert from 'node:assert/strict';
import * as B from '../src/bomb/Rules542.js';
import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';
import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';
import {queueBomb542,liveBomb542} from '../online-server/src/BombCoordinator542.js';
import {readFileSync,readdirSync} from 'node:fs';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'player'+i,color499:['pink','orange','blue','green'][i],choice:{id:'m'+i,speciesId:['slime','wolf','goblin','skeleton'][i]},owned:[{id:'m'+i,speciesId:['slime','wolf','goblin','skeleton'][i]}]}));
function make(seed=5){const g=B.makeBomb542({id:'test',code:'ABC123',hostId:'p0',partyId:'party',members,now:0});B.startBomb542(g,0,seed);for(let t=50;t<=3500;t+=50)B.advanceBomb542(g,t);return g}
function flat(g){g.board=Array(99).fill(0);g.players.forEach((p,i)=>Object.assign(p,{x:[2.5,4.5,6.5,6.5][i],y:[4.5,4.5,8.5,2.5][i]}));return g}
function advance(g,ms){const end=g.lastAt+ms;while(g.lastAt<end&&g.phase!=='result')B.advanceBomb542(g,g.lastAt+50)}
test('four colors preserved, empty seats get selected AI colors',()=>{const g=make();assert.deepEqual(g.players.map(p=>p.color499),['pink','orange','blue','green']);const a=B.makeBomb542({id:'a',members:members.slice(0,1),now:0});a.aiColors500={1:'orange',2:'blue',3:'green'};B.startBomb542(a,0,1);assert.deepEqual(a.players.map(p=>p.color499),g.players.map(p=>p.color499));assert.equal(a.players.filter(p=>p.ai).length,3)});
test('place has strict capacity, cooldown, and finite fuse',()=>{const g=flat(make()),p=g.players[0];assert(B.place542(g,p));assert.equal(B.place542(g,p),false);p.x=1.5;g.elapsed+=501;assert(B.place542(g,p));p.x=.5;g.elapsed+=501;assert.equal(B.place542(g,p),false);assert.equal(g.bombs.length,2);assert.equal(g.bombs[0].explodeAt,2500)});
test('a return changes owner/range but never resets the fuse',()=>{const g=flat(make()),p=g.players[0];B.place542(g,p);p.x=1.5;const fuse=g.bombs[0].explodeAt;assert(B.kick542(g,p));assert.equal(g.bombs[0].explodeAt,fuse);assert.equal(g.bombs[0].range,3);g.elapsed+=400;g.bombs[0].x=3.5;g.bombs[0].dx=0;assert(B.kick542(g,g.players[1]));assert.equal(g.bombs[0].owner,1);assert.equal(g.bombs[0].range,4);assert.equal(g.bombs[0].explodeAt,fuse)});
test('columns stop blast, crates take the first hit and shelter behind',()=>{const g=flat(make());g.board[B.index542(3.5,4.5)]=1;g.board[B.index542(2.5,5.5)]=2;const cells=B.blastCells542(g,{x:2.5,y:4.5,range:4});assert(!cells.includes(B.index542(3.5,4.5)));assert(!cells.includes(B.index542(4.5,4.5)));assert(cells.includes(B.index542(2.5,5.5)));assert(!cells.includes(B.index542(2.5,6.5)))});
test('chain reactions terminate and shield consumes exactly once',()=>{const g=flat(make()),p=g.players[0];p.shield=true;g.bombs=[{id:1,x:2.5,y:4.5,owner:1,planter:1,range:2,relay:0,explodeAt:50,dx:0,dy:0,pass:[0]},{id:2,x:3.5,y:4.5,owner:2,planter:2,range:2,relay:0,explodeAt:2500,dx:0,dy:0,pass:[]}];advance(g,50);assert.equal(g.bombs.length,0);assert.equal(g.blasts.length,2);assert.equal(p.hp,2);assert(!p.shield);assert(g.events.some(e=>e.type==='guard'))});
test('tap routing avoids obstacles, collision stops overlap, inputs keep moving when placing',()=>{const g=flat(make()),p=g.players[0];g.board[B.index542(2.5,5.5)]=1;const route=B.path542(g,p,2.5,6.5);assert(route.length>2);assert(!route.some(q=>B.index542(q.x,q.y)===B.index542(2.5,5.5)));const inputs=new Map([['p0',[{action:'move',x:2.5,y:6.5},{action:'bomb'}]]]);B.advanceBomb542(g,3550,inputs);assert(g.bombs.length);assert(p.route.length);for(let t=3600;t<3900;t+=50)B.advanceBomb542(g,t);assert(Math.hypot(p.x-2.5,p.y-4.5)>.2)});
test('18/24 second collapse removes outer floor and eliminates exposed players',()=>{const g=flat(make());g.players[0].x=.5;g.players[0].y=.5;g.lastAt=g.roundAt+17950;g.elapsed=17950;advance(g,50);assert.equal(g.ring,1);assert(!g.players[0].alive);assert(!B.floor542(g,.5,.5));g.lastAt=g.roundAt+23950;g.elapsed=23950;advance(g,50);assert.equal(g.ring,2)});
test('three rounds, score, shared ties and all players return',()=>{const g=flat(make());for(let round=1;round<=3;round++){g.players.forEach(p=>Object.assign(p,{x:4.5,y:5.5,alive:true,hp:2}));g.ring=2;g.lastAt=g.roundAt+29950;g.elapsed=29950;advance(g,50);assert.equal(g.round,round);assert(g.players.every(p=>p.score===round*3));if(round<3){assert.equal(g.phase,'intermission');advance(g,6100);assert(g.players.every(p=>p.alive&&p.hp===2));g.board=Array(99).fill(0)}}assert.equal(g.phase,'result');assert(g.results.every(r=>r.rank===1));assert.equal(g.winnerIds.length,4)});
test('no private roster or other input counters in snapshot',()=>{const g=make(),snap=B.publicBomb542(g,'p0');assert.equal(snap.players[0].lastSeq,0);assert(!('lastSeq'in snap.players[1]));assert(!('owned'in snap.members[0]));assert(!('seed'in snap));assert(!('route'in snap.players[0]))});
test('deterministic bots finish 20 seeds with bounded state and legal numbers',()=>{for(let seed=1;seed<=20;seed++){const g=make(seed);const auto=new Set(members.map(p=>p.playerId));for(let t=3550;t<=115000&&g.phase!=='result';t+=50){B.advanceBomb542(g,t,new Map(),auto);assert(g.bombs.length<=8);assert(g.events.length<=64);for(const p of g.players){assert(Number.isFinite(p.x)&&Number.isFinite(p.y));assert(p.hp>=0&&p.hp<=2)}}assert.equal(g.phase,'result');assert(g.winnerIds.length>0);assert.equal(g.results.length,4)}});
test('server validates version, owner, sequence, finite targets, replay and lifecycle',()=>{let now=10000;const messages=[],sessions=new Map(members.map(m=>[m.playerId,{playerId:m.playerId,clientKey:m.playerId,connected:true,profile:{name:m.name}}]));const c=new RaceCoordinator451({now:()=>now,sessions,send:(id,m)=>messages.push({id,...m})});const request=(id,op,extra={})=>c.handle(sessions.get(id),{op,rulesVersion:8,bombVersion542:1,roster:members[0].owned,displayName:id,...extra});request('p0','partyCreate462',{game:'bomb'});let party=partyFor462(c,'p0'),g=partyRace462(c,party);request('p0','partyReady462',{ready:true});request('p0','bomb542',{gameId:g.id,kind:'start'});for(let i=0;i<71;i++){now+=50;c.advanceBomb542()}g=liveBomb542(c,g);assert.equal(g.phase,'play');const input={gameId:g.id,bombVersion542:1,seq:1,action:'move',x:2.5,y:.5};assert.equal(queueBomb542(c,sessions.get('p0'),{...input,x:NaN}),false);assert.equal(queueBomb542(c,sessions.get('p0'),{...input,bombVersion542:0}),false);assert.equal(queueBomb542(c,sessions.get('p1'),input),false);assert(queueBomb542(c,sessions.get('p0'),input));assert.equal(queueBomb542(c,sessions.get('p0'),input),false);assert.equal(c.active('p0'),true);for(let i=0;i<2400&&g.phase!=='result';i++){now+=50;c.advanceBomb542()}assert.equal(g.phase,'result');request('p0','partyResult490',{partyId:party.id,gameId:g.id,kind:'again'});const again=partyRace462(c,party);assert.equal(again.phase,'lobby');assert.notEqual(again.id,g.id);assert.equal(queueBomb542(c,sessions.get('p0'),{...input,seq:2}),false);assert.equal(messages.filter(m=>m.type==='raceError451').length,0)});
test('existing game mechanics and shared color assignment are byte-identical to Build541',()=>{const roots=['race','sugoroku','cabbage','canal','gorilla','luck','quiz','tower','sumo','fishing','hide','tetra'];let n=0;for(const dir of roots)for(const file of readdirSync(new URL('../src/'+dir+'/',import.meta.url)))if(/^(Rules|Engine|AI|Brains|Map|Heist|Team|Water|Physics|Geometry|Simulation).*\.js$/.test(file)){const current=new URL('../src/'+dir+'/'+file,import.meta.url),old=new URL('../../baseline541/src/'+dir+'/'+file,import.meta.url);assert.deepEqual(readFileSync(current),readFileSync(old),dir+'/'+file);n++}assert(n>=30);for(const file of ['PartyColors499.js','GameColors501.js'])assert.deepEqual(readFileSync(new URL('../src/party/'+file,import.meta.url)),readFileSync(new URL('../../baseline541/src/party/'+file,import.meta.url)))});
