import test from 'node:test';
import assert from 'node:assert/strict';
import {makeCanal489,startCanal489,advanceCanal489,publicCanal489} from '../src/canal/Rules489.js';
import {SPECIES492} from '../src/canal/Rules492.js';
import {layout492,draw492} from '../src/canal/Scene492.js';
import {smoothLayout493,cooldown493,sound493,lesson493} from '../src/canal/Feedback493.js';
import {view492,tick492,receive492,target492,click492} from '../src/canal/View492.js';
import {canalClick489} from '../src/canal/View489.js';
function game(){const g=makeCanal489({id:'493',code:'A',partyId:'party',hostId:'p0',members:[{playerId:'p0',name:'あなた',choice:{id:'m',speciesId:'wolf'}}],now:0,seed:47});g.rules492=1;startCanal489(g,0);g.phase='playing';return g}
function enemy(id,slot,progress=.5,lane=0){return{id,lane,kind:1,hp:3,maxHp:3,spawnAt:10000-progress*10000,travelMs:10000,visualSlot493:slot}}
class Element{constructor(doc){this.ownerDocument=doc;this.children=[];this.nodes=new Map();this.dataset={};this.style={};this.attrs={};this.textContent='';this.hidden=false;this.classList={toggle(){}}}querySelector(q){return this.nodes.get(q)??null}querySelectorAll(q){return this.nodes.get(q)??[]}appendChild(x){this.children.push(x);x.parent=this}remove(){this.parent.children=this.parent.children.filter(x=>x!==this)}setAttribute(k,v){this.attrs[k]=v}getAttribute(k){return this.attrs[k]}getContext(){return null}}
function client(g){const doc={createElement:()=>new Element(doc)},root=new Element(doc),surface=new Element(doc),host=new Element(doc),sent=[];for(const q of ['.cn-play','.cn492'])root.nodes.set(q,surface);root.nodes.set('[data-cn-lane]',[]);root.nodes.set('[data-cn-targets]',host);for(const q of ['[data-cn-hint]','[data-cn-net-state]','[data-cn-net-recharge]','[data-cn-callout]','[data-cn-callout-title]','[data-cn-callout-note]','[data-cn-callout-kicker]'])root.nodes.set(q,new Element(doc));const c={root,state:{canal:publicCanal489(g,'p0',10000),party:{hostId:'p0'}},transport:{selfId:'p0'},ready:()=>true,connected:()=>true,raw:(op,m)=>{sent.push({op,m});return true},sgMonster463:()=>''};view492(c);sound493(c,false);return{c,host,root,sent}}
test('removing a captured creature does not swap the remaining animals across the waterway',()=>{const enemies=[enemy(1,0,.7),enemy(2,1,.6),enemy(3,2,.5),enemy(4,3,.4)];const before=layout492(enemies,10000),after=layout492(enemies.slice(1),10000);for(const e of after)assert.equal(e.x,before.find(x=>x.id===e.id).x);const alone=layout492([enemies[1]],10000);assert.equal(alone[0].x,before.find(x=>x.id===2).x)});
test('spawn slots remain unique within each lane and survive public snapshots and save/restart',()=>{const g=game();advanceCanal489(g,20000,()=>true);for(let lane=0;lane<4;lane++){const slots=g.enemies.filter(e=>e.lane===lane).map(e=>e.visualSlot493);assert.equal(slots.length,new Set(slots).size);assert.ok(slots.every(n=>Number.isInteger(n)&&n>=0&&n<6))}const clone=JSON.parse(JSON.stringify(g));advanceCanal489(g,25000,()=>true);advanceCanal489(clone,25000,()=>true);assert.deepEqual(g,clone);const pub=publicCanal489(g,'p0',25000);assert.deepEqual(pub.enemies.map(e=>e.visualSlot493),g.enemies.map(e=>e.visualSlot493))});
test('crowd movement is continuous, removes stale positions, and respects reduced motion',()=>{const u={};smoothLayout493([{id:1,x:40,y:10},{id:2,x:60,y:20}],u,1000);const sample=smoothLayout493([{id:2,x:60,y:50}],u,1033);assert.ok(sample[0].y>20&&sample[0].y<50);assert.equal(u.motion493.has(1),false);const same=smoothLayout493([{id:2,x:60,y:50}],u,1033);assert.equal(same[0].y,sample[0].y);u.reduced=true;assert.equal(smoothLayout493([{id:2,x:60,y:50}],u,1040)[0].y,50)});
test('canvas and DOM use the exact same smoothed creature coordinates',t=>{const g=game();g.enemies=[enemy(1,0,.5),enemy(2,1,.6)];const {c,host}=client(g);t.mock.method(Date,'now',()=>10000);tick492(c);for(const button of host.children){const e=c.cnUI492.frameLayout.find(x=>x.id===Number(button.dataset.cnTarget492));assert.equal(button.style.left,e.x+'%');assert.equal(button.style.top,e.y+'%')}});
test('cooldown combines the latest server stroke with the local preview without going negative',()=>{assert.equal(cooldown493({nextFireAt:1200},{localFire:950},1000,1000),250);assert.equal(cooldown493({nextFireAt:1400},{localFire:900},1000,1000),300);assert.equal(cooldown493({nextFireAt:900},{localFire:500},1000,1000),0)});
test('rapid or server-cooling taps explain the delay and do not send a pretend stroke',t=>{const g=game();g.enemies=[enemy(1,0,.5)];g.players[0].nextFireAt=10200;const {c,root,sent}=client(g);let now=10000;t.mock.method(Date,'now',()=>now);assert.equal(target492(c,1),false);assert.equal(sent.length,0);assert.match(root.querySelector('[data-cn-hint]').textContent,/0.3秒/);now=10201;assert.equal(target492(c,1),true);assert.equal(sent.length,1);now=10300;assert.equal(target492(c,1),false);assert.equal(sent.length,1)});
test('mute persists from lobby into play, results and a new game',()=>{const c={cnUI489:{sound:true},state:{canal:{phase:'lobby'}}};canalClick489(c,{dataset:{cnAction:'sound'}});assert.equal(c.cnSound493,false);c.cnUI492={sound:true};assert.equal(sound493(c),false);click492(c,{dataset:{cnAction:'sound'}});assert.equal(c.cnUI489.sound,true);sound493(c,false);c.cnUI492={sound:true};assert.equal(sound493(c),false)});
test('replay clears the previous round net animation, warning, cooldown and shared-net pending state',()=>{const g=game(),{c}=client(g);Object.assign(c.cnUI492,{preview:{enemyId:99},feedback:{text:'old'},callout:{until:999999},burstPending:9999,localFire:9000});c.state.canal.id='new-round';view492(c);assert.equal(c.cnUI492.preview,null);assert.equal(c.cnUI492.feedback,null);assert.equal(c.cnUI492.callout,null);assert.equal(c.cnUI492.burstPending,0);assert.equal(c.cnUI492.localFire,0);assert.equal(c.cnUI492.sound,false)});
test('boss and final flood callouts identify the event and expire instead of blocking the controls',t=>{const g=game(),{c,root}=client(g);let now=10000;t.mock.method(Date,'now',()=>now);c.state.canal.events=[{id:1,kind:'boss',at:10000,lane:1}];receive492(c);assert.equal(root.querySelector('[data-cn-callout]').hidden,false);assert.match(root.querySelector('[data-cn-callout-note]').textContent,/東.*8回/);now=12100;c.state.canal.serverNow=now;tick492(c);assert.equal(root.querySelector('[data-cn-callout]').hidden,true);c.state.canal.events=[{id:2,kind:'flood',at:now}];receive492(c);assert.equal(root.querySelector('[data-cn-callout-title]').textContent,'全水門、開放！')});
test('results expose exactly two actions before the detailed statistics',()=>{const g=game(),{c}=client(g);c.state.canal.phase='result';c.state.canal.grade='S';c.state.canal.success=true;const html=view492(c);assert.equal((html.match(/data-party-result490=/g)||[]).length,2);assert.ok(html.indexOf('data-party-result490="again"')<html.indexOf('cn-result-stats'));assert.doesNotMatch(html,/ホームへ戻る/)});
test('an acknowledged local stroke draws one net and a mega catch never claims to recharge the meter',()=>{let nets=0;const texts=[];const ctx=new Proxy({measureText:t=>({width:t.length*10}),drawImage:(img,sx,sy)=>{if(img.tag==='props'&&sx===0&&sy===0)nets++},fillText:t=>texts.push(t)},{get:(o,k)=>k in o?o[k]:()=>{}});const canvas={clientWidth:400,width:400,height:400,getContext:()=>ctx},g={hp:100,enemies:[],players:[{lastAction:{at:10000,enemyId:1,lane:0,progress:.5}}]},u={props:{tag:'props',complete:true,naturalWidth:800,naturalHeight:800},preview:{at:10000,enemyId:1,lane:0,point:{x:43,y:30}},effects:[{kind:'catch',mega:true,kindIndex:0,lane:0,progress:.5,localAt:10000}]};draw492(canvas,g,u,10100,10100,0);assert.equal(nets,1);assert.ok(texts.includes('大網で捕獲！'));assert.ok(!texts.some(t=>t.includes('＋1')))});
test('step-by-step hints teach species hits and cooperation after the first capture',()=>{assert.match(lesson493(0,2,['北','東','南','西']),/南/);assert.match(lesson493(4,0,[]),/0.3秒/);assert.match(lesson493(8,0,[]),/協力.*＋2/)});
