import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks,createRequire} from 'node:module';import {existsSync,mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {QUIZ513,makeQuiz513,startQuiz513,chooseQuiz513,advanceQuiz513,publicQuiz513,seatPoint513,position513} from '../src/quiz/Rules513.js';
import {QUESTIONS513,drawQuestions513} from '../online-server/src/quiz/Questions513.js';
import {frame513,quizSignature513,animating513} from '../src/quiz/Presentation513.js';
const fixtures={
 [new URL('../src/ui/MonsterVisual.js',import.meta.url).href]:`export const monsterVisual=()=>'<i class="test-sprite"></i>';export const setMonsterVisualFrame=()=>{};`,
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,c,next){const url=spec.startsWith('.')?new URL(spec,c.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,c)},load(url,c,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,c)}});
const {RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');
const {quizView513,quizAfter513,quizBefore513,quizDispose513,quizTick513,paintQuiz513,requestQuiz513,quizReceive513,quizKey513}=await import('../src/quiz/View513.js');
const {raceDomSignature452}=await import('../src/race/RacePresentation452.js');
const {isPartyHub462,partyHub462}=await import('../src/party/PartyView462.js');
const {resultGame490}=await import('../src/party/PartyResults490.js');
const {PARTY_GAMES462}=await import('../src/party/PartyGames462.js');
hook.deregister();
const rng=seed=>{let z=seed;return n=>{z=(Math.imul(z,1664525)+1013904223)>>>0;return z%n}};
function game(n=4,seed=1){const g=makeQuiz513({id:'quiz',code:'ABC123',partyId:'party',hostId:'p0',members:Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'P'+i,choice:{id:'m'+i,speciesId:'wolf'},owned:[{id:'m'+i,speciesId:'wolf'}],color499:['orange','pink','green','blue'][i]}))}),r=rng(seed);startQuiz513(g,1000,drawQuestions513(r),r);return g}
const next=g=>{advanceQuiz513(g,g.nextAt);return g};
const begin=g=>{next(g);assert.equal(g.phase,'question');return g};
const correct=g=>g.deck513[g.round-1].answer?'o':'x';
function answer(g,seat=0,side=correct(g),seq=1,at=g.phaseAt+100){return chooseQuiz513(g,'p'+seat,side,g.round,seq,at)}
function resolved(g,sides=g.players.map(()=>correct(g))){sides.forEach((s,i)=>{if(s&&g.players[i].alive&&!g.players[i].ai)answer(g,i,s)});advanceQuiz513(g,g.deadline);assert.equal(g.phase,'lock');next(g);assert.equal(g.phase,'reveal');return g}
function context(g,self='p0'){return{state:{quiz:publicQuiz513(g,self),party:{id:'party',hostId:'p0',code:'ABC123',game:'quiz',phase:g.phase,members:g.members.map(m=>({...m,connected:true}))},available:true,partyResultActions490:1},transport:{selfId:self},offset:g.phaseAt-Date.now(),sgMonster463:()=>'<span class="sg-monster"><i></i></span>',sgSpeciesName463:id=>id,ready:()=>true,connected:()=>true,roster:()=>[{id:'m0',speciesId:'wolf'}],bank:()=>null,save:{state:{player:{gold:1000,crystals:0},settings:{audioEnabled:false},monsters:[]}},root:{querySelector:()=>null},draft:{code:'ABC123'},render(){},qUI513:{gameId:g.id,round:g.round,sound:false,seq:0,lastSend:0}}}
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,quizVersion513:1,luckVersion507:1,luckVersion508:1,luckVersion509:1,luckVersion511:1,gorillaVersion502:1,gorillaRules503:1,gorillaRules504:1,gorillaRules505:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function start(x,n=x.sessions.size){assert.deepEqual(x.send(0,'partyCreate462',{game:'quiz',roster:[{id:'m0',speciesId:'wolf'}]}),[]);const party=Object.values(x.c.data.parties462)[0],get=()=>x.c.data.quizRooms513[party.code];for(let i=1;i<n;i++){assert.deepEqual(x.send(i,'partyJoin462',{code:party.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);assert.deepEqual(x.send(i,'quiz513',{gameId:get().id,kind:'select',monsterId:'m'+i}),[])}for(let i=0;i<n;i++)assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[]);assert.deepEqual(x.send(0,'quiz513',{gameId:get().id,kind:'start'}),[]);return{party,get}}
function dom(g=begin(game())){let mutations=0,rafId=0;const queue=new Map(),listeners=new Map(),els=new Map(),saved={};const element=()=>new Proxy({dataset:{},style:{},hidden:false,textContent:'',attrs:{},getAttribute(k){return this.attrs[k]},setAttribute(k,v){if(this.attrs[k]!==v){this.attrs[k]=v;mutations++}},addEventListener(){},removeEventListener(){}},{set(o,k,v){if(o[k]!==v)mutations++;o[k]=v;return true}});const root=element();root.classList={contains:cl=>cl==='q-play513'};root.querySelector=s=>{if(!els.has(s))els.set(s,element());return els.get(s)};for(const k of ['document','requestAnimationFrame','cancelAnimationFrame','matchMedia'])saved[k]=globalThis[k];globalThis.document={querySelector:()=>null,visibilityState:'visible',addEventListener:(k,f)=>listeners.set(k,f),removeEventListener:k=>listeners.delete(k)};globalThis.requestAnimationFrame=f=>{queue.set(++rafId,f);return rafId};globalThis.cancelAnimationFrame=id=>queue.delete(id);globalThis.matchMedia=()=>({matches:false});const c=context(g);c.root={querySelector:s=>s==='.q513'||s==='.q-play513'?root:null};c.raw=()=>true;return{g,c,root,queue,listeners,mutations:()=>mutations,reset:()=>mutations=0,flush(){const jobs=[...queue.values()];queue.clear();jobs.forEach(f=>f())},restore(){quizDispose513(c);for(const[k,v]of Object.entries(saved)){if(v===undefined)delete globalThis[k];else globalThis[k]=v}}}}

test('120 unique authored questions cover 12 genres with true/false and three difficulties',()=>{assert.equal(QUESTIONS513.length,120);assert.equal(new Set(QUESTIONS513.map(q=>q.text)).size,120);const cats=new Set(QUESTIONS513.map(q=>q.category));assert.equal(cats.size,12);for(const cat of cats){const qs=QUESTIONS513.filter(q=>q.category===cat);assert.equal(qs.length,10);assert.equal(qs.filter(q=>q.answer).length,5);assert.deepEqual([...new Set(qs.map(q=>q.difficulty))],[1,2,3])}for(const q of QUESTIONS513){assert.ok(q.text.length<=40);assert.ok(q.explanation.length<=45);assert.ok(typeof q.answer==='boolean');if(!['算数','ことば・ひらめき'].includes(q.category))assert.match(q.source.url,/^https:\/\//)}});
test('direct numeric and word puzzles independently verify the stored answer',()=>{const math=[3*4+2===14,1000===100,.5===1/2,100*.8===90,0%2===0,3**2===6,true,false,-2>-5,60*.5===60];assert.deepEqual(QUESTIONS513.filter(q=>q.category==='算数').map(q=>q.answer),math);const reverse=s=>[...s].reverse().join(''),words=[reverse('しんぶんし')==='しんぶんし',reverse('たぬき')==='きたぬ','あいうえお'[2]==='う',[...'すもももももももものうち'].filter(c=>c==='も').length===7,reverse('とまと')==='とまと',reverse('あかさたな')[1]==='な',reverse('ABBA')==='ABBA','１２３４５'[1]==='１２３４５'.at(-2),[...'〇×〇×〇'].filter(c=>c==='〇').length===3,'かきくけこ'.replace('く','').length===3];assert.deepEqual(QUESTIONS513.filter(q=>q.category==='ことば・ひらめき').map(q=>q.answer),words)});
test('10-question draws do not repeat genres or recent 30 IDs and reach every question',()=>{const seen=new Set(),recent=[];for(let seed=1;seed<=1000;seed++){const deck=drawQuestions513(rng(seed),recent);assert.equal(new Set(deck.map(q=>q.category)).size,10);assert.equal(deck.length,10);for(const q of deck){assert.ok(!recent.includes(q.id));seen.add(q.id)}recent.push(...deck.map(q=>q.id));recent.splice(0,Math.max(0,recent.length-30))}assert.equal(seen.size,120)});
test('bad decks reject atomically before a game starts',()=>{const g=makeQuiz513({id:'x',members:[{playerId:'p',choice:{id:'m'}}]}),before=structuredClone(g);assert.throws(()=>startQuiz513(g,0,[QUESTIONS513[0]],rng(1)));assert.deepEqual(g,before)});
test('one through four humans fill exactly four seats with fixed colors',()=>{for(let n=1;n<=4;n++){const g=game(n);assert.equal(g.players.length,4);assert.equal(g.players.filter(p=>p.ai).length,4-n);assert.equal(new Set(g.players.map(p=>p.color499)).size,4);g.members[0].color499='green';assert.equal(g.players[0].color499,'orange')}});
test('full 12 seconds remain available even if all four already picked',()=>{const g=begin(game()),deadline=g.deadline;g.players.forEach((p,i)=>answer(g,i));assert.equal(g.phase,'question');assert.equal(g.nextAt,deadline);advanceQuiz513(g,deadline-1);assert.equal(g.phase,'question');advanceQuiz513(g,deadline);assert.equal(g.phase,'lock')});
test('choice can change, newer sequence wins, reordered and duplicate packets cannot undo it',()=>{const g=begin(game());answer(g,0,'o',1,g.phaseAt+100);answer(g,0,'x',3,g.phaseAt+300);assert.equal(answer(g,0,'o',2,g.phaseAt+500),false);assert.equal(answer(g,0,'o',3,g.phaseAt+600),false);assert.equal(g.players[0].side,'x');assert.equal(g.players[0].seq,3)});
test('server rejects invalid sides, sequence and spectators',()=>{const g=begin(game());for(const side of ['yes',true,0,null])assert.throws(()=>chooseQuiz513(g,'p0',side,1,1,g.phaseAt+100));for(const seq of [0,-1,1.5,2049,NaN])assert.throws(()=>answer(g,0,'o',seq));assert.throws(()=>chooseQuiz513(g,'viewer','o',1,1,g.phaseAt+100));assert.equal(g.players[0].side,null)});
test('deadline is strict and lock never reveals the answer',()=>{const g=begin(game());answer(g,0,'o',1,g.deadline-1);assert.equal(answer(g,0,'x',2,g.deadline),false);advanceQuiz513(g,g.deadline);const p=publicQuiz513(g,'p0');assert.equal(p.question.text,g.deck513[0].text);assert.equal(p.reveal,null);assert.equal(p.question.answer,undefined);assert.equal(answer(g,0,'x',3,g.phaseAt+100),false)});
test('unanswered players are eliminated; no human auto-answer is silently chosen',()=>{const g=begin(game());resolved(g,[correct(g),null,null,null]);assert.equal(g.players[0].alive,true);assert.ok(g.players.slice(1).every(p=>!p.alive&&p.side===null));next(g);assert.equal(g.outcome,'last');assert.equal(g.results.filter(r=>r.winner).length,1)});
test('all wrong ends with zero winners including rank-one ties',()=>{const g=begin(game()),wrong=correct(g)==='o'?'x':'o';resolved(g,Array(4).fill(wrong));next(g);assert.equal(g.outcome,'all-out');assert.ok(g.results.every(r=>r.winner===false&&r.rank===1))});
test('wrong floor falls only after lock, with full explanation time',()=>{const g=begin(game()),a=correct(g);resolved(g,[a,a,a==='o'?'x':'o',null]);assert.equal(g.nextAt-g.phaseAt,4800);assert.equal(g.reveal.answer,a);assert.equal(g.players.filter(p=>p.alive).length,2);advanceQuiz513(g,g.nextAt-1);assert.equal(g.phase,'reveal');next(g);assert.equal(g.round,2);assert.equal(g.phase,'question')});
test('dead players never move or resurrect in future questions',()=>{const g=begin(game());resolved(g,[correct(g),correct(g),null,null]);next(g);assert.throws(()=>answer(g,2));assert.equal(g.players[2].alive,false);assert.equal(g.players[2].eliminatedRound,1);resolved(g,[correct(g),correct(g),null,null]);assert.equal(g.players[2].correct,0)});
test('ten survivors questions produce joint winners and stop permanently',()=>{const g=begin(game());for(let i=1;i<=10;i++){assert.equal(g.round,i);resolved(g);next(g)}assert.equal(g.phase,'result');assert.equal(g.outcome,'survived');assert.ok(g.results.every(r=>r.winner&&r.correct===10));assert.equal(g.nextAt,null);assert.equal(advanceQuiz513(g,1e9),false)});
test('later eliminations outrank earlier ones without claiming all-out winner',()=>{const g=begin(game());resolved(g,[correct(g),correct(g),null,null]);next(g);resolved(g,[null,null,null,null]);next(g);assert.deepEqual(g.results.map(r=>r.rank),[1,1,3,3]);assert.equal(g.outcome,'all-out');assert.ok(g.results.every(r=>!r.winner))});
test('server restart or stall grants full next-question time instead of skipping it',()=>{const g=game();advanceQuiz513(g,1e8);assert.equal(g.phase,'question');assert.equal(g.deadline,1e8+12000);const clone=JSON.parse(JSON.stringify(g));advanceQuiz513(g,g.deadline);advanceQuiz513(clone,clone.deadline);assert.deepEqual(g,clone)});
test('private future questions, explanations and bot plans are absent in all live views',()=>{const g=begin(game(1));for(const id of ['p0','viewer','AI-quiz-1']){const v=publicQuiz513(g,id);assert.equal(v.question.answer,undefined);assert.equal(v.question.explanation,undefined);assert.deepEqual(v.history,[]);assert.doesNotMatch(JSON.stringify(v),/deck513|botPlan513|botStep|lastInputAt|"owned"/);assert.equal(v.reveal,null)}const before=publicQuiz513(g,'p0');g.deck513[1].text='FUTURE';g.botPlan513[0][1][0].side='x';assert.deepEqual(publicQuiz513(g,'p0'),before)});
test('each viewer sees identical accepted moves and reveal, own sequence only',()=>{const g=begin(game());answer(g,0,'o');const a=publicQuiz513(g,'p0'),b=publicQuiz513(g,'p1');assert.equal(a.players[0].seq,1);assert.equal(b.players[0].seq,undefined);assert.equal(a.players[0].side,b.players[0].side);resolved(g);assert.deepEqual(publicQuiz513(g,'p0').reveal,publicQuiz513(g,'observer').reveal)});
test('AI includes both right and wrong outcomes and cannot copy human last-second changes',()=>{let rights=0,wrongs=0,changes=0;for(let seed=1;seed<=200;seed++){const g=begin(game(1,seed)),plan=structuredClone(g.botPlan513);answer(g,0,correct(g)==='o'?'x':'o');assert.deepEqual(g.botPlan513,plan);while(g.nextAt<g.deadline)next(g);for(const p of g.players.filter(p=>p.ai)){if(p.side===correct(g))rights++;else wrongs++;if(g.botPlan513[0][p.seat].length>1)changes++}}assert.ok(rights>300&&wrongs>20&&changes>20)});
test('500 seeded games persist every phase and always terminate with valid history',()=>{for(let seed=1;seed<=500;seed++){const g=game(seed%4+1,seed),r=rng(seed+400);let steps=0;while(g.phase!=='result'){assert.ok(++steps<130);if(g.phase==='question')for(const p of g.players.filter(p=>!p.ai&&p.alive))answer(g,p.seat,r(2)?'o':'x',1,g.phaseAt+100);const clone=JSON.parse(JSON.stringify(g));next(g);next(clone);assert.deepEqual(g,clone)}assert.ok(g.round<=10&&g.history.length===g.round);assert.ok(g.results.every(p=>Number.isInteger(p.rank)&&p.rank>=1&&p.rank<=4))}});
test('mid-movement redirection is position-continuous and finishes exactly on its new floor',()=>{const g=begin(game());answer(g,0,'o',1,g.phaseAt+100);const at=g.phaseAt+240,pos=position513(g.players[0],at);answer(g,0,'x',2,at);assert.deepEqual(position513(g.players[0],at),pos);assert.deepEqual(position513(g.players[0],at+280),seatPoint513('x',0))});
test('wall approaches monotonically; question text does not move and countdown stops exactly',()=>{const raw=begin(game()),g=publicQuiz513(raw,'p0');let prev=0;for(let t=0;t<=12000;t+=10){const f=frame513(g,g.phaseAt+t,'p0');assert.ok(f.wallScale>=prev);prev=f.wallScale;assert.equal(f.heading,g.question.text)}assert.equal(frame513(g,g.deadline,'p0').canChoose,false);assert.equal(animating513(g,g.deadline),false);assert.equal(frame513(g,g.deadline-3001,'p0').shaking,false);assert.equal(frame513(g,g.deadline-2999,'p0').shaking,true)});
test('reduced motion makes movement/falls immediate and never starts an animation loop',()=>{const g=begin(game());answer(g,0);const f=frame513(g,g.phaseAt+100,'p0',true);assert.deepEqual({x:f.rows[0].x,y:f.rows[0].y},seatPoint513(g.players[0].side,0));assert.equal(f.shaking,false);assert.equal(animating513(g,g.phaseAt+100,true),false);resolved(g,[correct(g),null,null,null]);assert.equal(frame513(g,g.phaseAt,'p0',true).rows[1].hidden,true)});
test('play DOM signature ignores live movement, answer lock, floor collapse and connectivity',()=>{const g=begin(game()),c=context(g),sig=raceDomSignature452(c);answer(g,0);c.state.quiz=publicQuiz513(g,'p0');assert.equal(raceDomSignature452(c),sig);resolved(g);c.state.quiz=publicQuiz513(g,'p0');c.state.party.phase=g.phase;assert.equal(raceDomSignature452(c),sig);next(g);assert.equal(quizSignature513(g).phase,'play')});
test('party selection, result routing and UI work for quiz without disturbing other game entries',()=>{const g=begin(game()),c=context(g);assert.equal(isPartyHub462(c),false);assert.equal(resultGame490(c),c.state.quiz);assert.equal(PARTY_GAMES462.length,7);assert.equal(PARTY_GAMES462[0].id,'quiz');const html=quizView513(c);assert.equal((html.match(/data-q-side513=/g)||[]).length,2);assert.equal((html.match(/data-q-pawn513=/g)||[]).length,4);assert.ok(html.indexOf('q-question513')<html.indexOf('q-stage513'));assert.ok(quizView513(context({...g,phase:'lobby'})).includes('全120問'))});
test('results show no fake winner for an all-out and escape player-supplied HTML',()=>{const g=begin(game());g.players[0].name='<script>bad()</script>';resolved(g,Array(4).fill(null));next(g);const html=quizView513(context(g,'spectator'));assert.ok(html.includes('勝者なし'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>bad'));assert.ok(html.includes('出典：'));assert.equal((html.match(/data-party-result490=/g)||[]).length,2)});
test('one RAF at most, no hidden-tab writes, all event handlers cleaned on exit',()=>{const d=dom();try{quizAfter513(d.c);for(let i=0;i<20;i++)quizTick513(d.c);assert.equal(d.queue.size,1);document.visibilityState='hidden';d.listeners.get('visibilitychange')();assert.equal(d.queue.size,0);d.reset();quizTick513(d.c);assert.equal(d.mutations(),0);quizBefore513(d.c);assert.equal(d.listeners.size,0)}finally{d.restore()}});
test('after finite animations, repeated idle paint produces zero DOM property writes',()=>{const d=dom();try{resolved(d.g);d.c.state.quiz=publicQuiz513(d.g,'p0');quizAfter513(d.c);paintQuiz513(d.c,d.g.phaseAt+3000);d.reset();for(let i=0;i<1000;i++)paintQuiz513(d.c,d.g.phaseAt+3000);assert.equal(d.mutations(),0)}finally{d.restore()}});
test('rapid taps are coalesced and retry only the latest desired side',()=>{const d=dom();try{let sends=[];d.c.raw=(op,p)=>{sends.push(p);return true};d.c.offset=d.g.phaseAt+100-Date.now();for(let i=0;i<50;i++)requestQuiz513(d.c,i%2?'x':'o');assert.equal(sends.length,1);assert.equal(d.c.qUI513.pending.side,'x');quizAfter513(d.c);paintQuiz513(d.c,d.g.phaseAt+500);assert.equal(sends.length,2);assert.equal(sends[1].side,'x');answer(d.g,0,'x',sends[1].seq,d.g.phaseAt+500);d.c.state.quiz=publicQuiz513(d.g,'p0');quizReceive513(d.c);assert.equal(d.c.qUI513.pending,null)}finally{d.restore()}});
test('disconnected, spectator and dead controls cannot send choices',()=>{const d=dom();try{let sent=0;d.c.raw=()=>{sent++;return true};d.c.ready=()=>false;assert.equal(requestQuiz513(d.c,'o'),false);d.c.ready=()=>true;d.c.transport.selfId='viewer';assert.equal(requestQuiz513(d.c,'o'),false);d.c.transport.selfId='p0';d.c.state.quiz.players[0].alive=false;assert.equal(requestQuiz513(d.c,'o'),false);assert.equal(sent,0)}finally{d.restore()}});
test('keyboard does not steal typing, auto-repeat or modified shortcuts',()=>{const d=dom();try{let sent=0;d.c.raw=()=>{sent++;return true};assert.equal(quizKey513(d.c,{key:'x',target:{tagName:'INPUT'}}),false);assert.equal(quizKey513(d.c,{key:'x',ctrlKey:true}),false);assert.equal(quizKey513(d.c,{key:'ArrowLeft',repeat:true}),false);assert.equal(sent,0)}finally{d.restore()}});
test('production coordinator starts 1-4 people, advertises protocol, and marks active game',()=>{for(let n=1;n<=4;n++){const x=setup(n),a=start(x);assert.equal(a.get().phase,'countdown');assert.equal(a.get().players.length,4);assert.equal(x.c.view(x.sessions.get('p0')).quizVersion513,1);assert.equal(x.c.active('p0'),true);assert.equal(x.c.view(x.sessions.get('p0')).room,null)}});
test('production moves use authenticated sender, not playerId in payload',()=>{const x=setup(2),a=start(x);x.time(a.get().nextAt);x.c.advance();x.time(x.now()+100);assert.deepEqual(x.send(0,'quiz513',{gameId:a.get().id,kind:'answer',side:'o',round:1,seq:1,playerId:'p1'}),[]);assert.equal(a.get().players[0].side,'o');assert.equal(a.get().players[1].side,null)});
test('stale version, wrong room and non-host start are rejected without mutation',()=>{const x=setup(2),a=start(x);assert.equal(x.send(0,'quiz513',{gameId:a.get().id,kind:'answer',side:'o',round:1,seq:1,quizVersion513:0}).length,1);assert.equal(x.send(0,'quiz513',{gameId:'old',kind:'answer',side:'o',round:1,seq:1}).length,1);assert.equal(x.send(1,'quiz513',{gameId:a.get().id,kind:'start'}).length,1);assert.equal(a.get().phase,'countdown')});
test('active late joiners spectate and cannot answer but may join next game',()=>{const x=setup(2),a=start(x,1);assert.deepEqual(x.send(1,'partyJoin462',{code:a.party.code,roster:[{id:'m1',speciesId:'slime'}]}),[]);const v=x.c.view(x.sessions.get('p1'));assert.equal(v.party.members[1].spectating,true);assert.equal(v.quiz.players.some(p=>p.playerId==='p1'),false);assert.equal(x.send(1,'quiz513',{gameId:a.get().id,kind:'answer',side:'o',round:1,seq:1}).length,1)});
test('disconnect preserves accepted floor and reconnect does not change it',()=>{const x=setup(2),a=start(x);x.time(a.get().nextAt);x.c.advance();x.time(x.now()+100);x.send(0,'quiz513',{gameId:a.get().id,kind:'answer',side:correct(a.get()),round:1,seq:1});x.sessions.get('p0').connected=false;x.time(a.get().deadline);x.c.advance();x.time(a.get().nextAt);x.c.advance();assert.equal(a.get().players[0].alive,true);x.sessions.get('p0').connected=true;assert.equal(x.c.view(x.sessions.get('p0')).quiz.players[0].side,a.get().reveal.answer)});
test('sealed deck, AI moves, choices and recent questions survive server JSON reload',()=>{const dir=mkdtempSync(join(tmpdir(),'quiz513-'));try{const x=setup(2,join(dir,'state.json')),a=start(x);x.time(a.get().nextAt);x.c.advance();x.time(x.now()+100);x.send(0,'quiz513',{gameId:a.get().id,kind:'answer',side:'o',round:1,seq:1});const y=setup(2,join(dir,'state.json'));y.time(x.now());assert.deepEqual(y.c.data.quizRooms513[a.party.code],a.get());x.time(a.get().deadline);y.time(a.get().deadline);x.c.advance();y.c.advance();assert.deepEqual(y.c.data.quizRooms513[a.party.code],a.get())}finally{rmSync(dir,{recursive:true,force:true})}});
test('replay request is idempotent and old game choices cannot affect new room',()=>{const x=setup(),a=start(x);x.time(a.get().nextAt);x.c.advance();x.time(a.get().deadline);x.c.advance();x.time(a.get().nextAt);x.c.advance();x.time(a.get().nextAt);x.c.advance();assert.equal(a.get().phase,'result');const old=a.get().id,payload={partyId:a.party.id,gameId:old,kind:'again'};assert.deepEqual(x.send(0,'partyResult490',payload),[]);const fresh=a.get().id;assert.notEqual(fresh,old);assert.deepEqual(x.send(0,'partyResult490',payload),[]);assert.equal(a.get().id,fresh);assert.equal(x.send(0,'quiz513',{gameId:old,kind:'answer',side:'o',round:1,seq:1}).length,1);assert.equal(a.get().phase,'lobby')});
test('only revealed IDs enter replay avoidance; switching games and back cleans quiz rooms',()=>{const x=setup(),a=start(x);x.time(a.get().nextAt);x.c.advance();x.time(a.get().deadline);x.c.advance();assert.deepEqual(a.party.recentQuestionIds513??[],[]);x.time(a.get().nextAt);x.c.advance();assert.deepEqual(a.party.recentQuestionIds513,[a.get().reveal.id]);x.time(a.get().nextAt);x.c.advance();assert.deepEqual(x.send(0,'partyGame462',{game:'luck'}),[]);assert.equal(Object.keys(x.c.data.quizRooms513).length,0);assert.equal(x.c.view(x.sessions.get('p0')).quiz,null);assert.deepEqual(x.send(0,'partyGame462',{game:'quiz'}),[]);assert.equal(x.c.view(x.sessions.get('p0')).luck,null)});
test('new art fully decodes with alpha and all four platform cells have content',async()=>{const require=createRequire(import.meta.url),{loadImage,createCanvas}=require('@napi-rs/canvas');for(const id of ['arena','wall','platforms']){const im=await loadImage(new URL('../assets/quiz513/'+id+'.png',import.meta.url).pathname);assert.ok(im.width>=1200);if(id==='platforms'){assert.equal(im.width,im.height);const cv=createCanvas(im.width,im.height),ctx=cv.getContext('2d');ctx.drawImage(im,0,0);for(let i=0;i<4;i++){const bytes=ctx.getImageData(i%2*im.width/2,Math.floor(i/2)*im.height/2,im.width/2,im.height/2).data;assert.ok(bytes.some((v,j)=>j%4===3&&v===0));assert.ok(bytes.some((v,j)=>j%4===3&&v>200))}}}});
test('mixed-version ready gate cannot start a quiz with an old client',()=>{const x=setup(2);x.send(0,'partyCreate462',{game:'quiz',roster:[{id:'m0',speciesId:'wolf'}]});const p=Object.values(x.c.data.parties462)[0],g=x.c.data.quizRooms513[p.code];x.send(1,'partyJoin462',{code:p.code,quizVersion513:0,roster:[{id:'m1',speciesId:'wolf'}]});x.send(1,'quiz513',{gameId:g.id,kind:'select',monsterId:'m1'});assert.equal(x.send(1,'partyReady462',{ready:true,quizVersion513:0}).length,1);x.send(0,'partyReady462',{ready:true});assert.equal(x.send(0,'quiz513',{gameId:g.id,kind:'start'}).length,1);assert.equal(g.phase,'lobby')});
test('server write failure rolls back a choice without acknowledging a move that was not saved',()=>{const dir=mkdtempSync(join(tmpdir(),'quiz-failure-'));try{const x=setup(2),a=start(x);x.time(a.get().nextAt);x.c.advance();const before=structuredClone(a.get());x.time(x.now()+200);writeFileSync(join(dir,'block'),'file');x.c.stateFile=join(dir,'block','state.json');const errors=x.send(0,'quiz513',{gameId:a.get().id,kind:'answer',side:'o',round:1,seq:1});assert.ok(errors.length);assert.equal(a.get().players[0].side,before.players[0].side)}finally{rmSync(dir,{recursive:true,force:true})}});
