import test from'node:test';import assert from'node:assert/strict';import{mkdtempSync,rmSync}from'node:fs';import{join}from'node:path';import{tmpdir}from'node:os';
import{MAX_BET458,betLimit458,swipeDirection458,editPick458,rememberScroll458,restoreScroll458,panelKey458}from'../src/race/RaceUX458.js';
import{RACE451,payout451}from'../src/race/RaceRules451.js';import{reserveRaceBet451,applyRaceDelivery451}from'../src/race/RaceWallet451.js';import{RaceCoordinator451}from'../online-server/src/RaceCoordinator451.js';
function harness(file=null){let at=100000;const session={playerId:'p0',clientKey:'build458-fixture-key',connected:true},errors=[],opts={stateFile:file,sessions:new Map([['p0',session]]),send:(id,m)=>{if(m.type==='raceError451')errors.push(m)},now:()=>at};let c=new RaceCoordinator451(opts);return{get c(){return c},errors,call(op,payload={}){c.handle(session,{op,rulesVersion:6,...payload})},view(){return c.view(session)},step(ms){at+=ms;c.advance()},restart(){c=new RaceCoordinator451(opts)},start(version=6){this.call('create',{rulesVersion:version,roster:[{id:'m',speciesId:'slime'}]});this.call('select',{monsterId:'m'});this.call('start')}}}
test('MAX and integer payout cover actual55M balance and safe boundary, legacy rooms retain1M',()=>{assert.equal(betLimit458(55838554,6),55838554);assert.equal(betLimit458(55838554,5),1000000);assert.equal(betLimit458(0,6),0);assert.equal(betLimit458(Infinity,6),MAX_BET458);for(const amount of[1,100,55838554,MAX_BET458])for(const odds of[1.1,33.3,999.9,1000]){const expected=Number(BigInt(amount)*BigInt(Math.round(odds*10))/10n);assert.equal(payout451(amount,odds),expected);assert.ok(Number.isSafeInteger(expected));assert.ok(expected+8000<=Number.MAX_SAFE_INTEGER)}assert.equal(payout451(1.5,33.3),0)});
test('MAX debit and payout/refund remain atomic and once-only across server restart',()=>{const dir=mkdtempSync(join(tmpdir(),'race458-'));try{const h=harness(join(dir,'state.json'));h.start();const r=h.view().room,amount=55838554,packet={raceId:r.id,requestId:r.id+':p0',amount,ticket:{kind:'win',picks:[4]}},save={state:{player:{gold:amount},monsters:[]},save:()=>true},key='ws://local|p0';reserveRaceBet451(save,key,packet);assert.equal(save.state.player.gold,0);h.call('bet',packet);assert.equal(h.view().room.members[0].selfTicket.amount,amount);h.restart();h.call('bet',packet);assert.equal(Object.keys(h.c.data.accounts.p0.decisions).length,1);h.step(17000);h.step(4000);h.step(40000);h.step(3000);const receipt=h.view().deliveries.find(x=>x.kind==='result');assert.ok(receipt);assert.equal(receipt.stake,amount);save.save=()=>false;assert.throws(()=>applyRaceDelivery451(save,key,receipt));assert.equal(save.state.player.gold,0);save.save=()=>true;applyRaceDelivery451(save,key,receipt);assert.equal(save.state.player.gold,receipt.gold);applyRaceDelivery451(save,key,receipt);assert.equal(save.state.player.gold,receipt.gold);h.call('ack',{ids:[receipt.id]});h.call('again');assert.equal(h.view().room.phase,'lobby');h.call('leave');assert.equal(h.view().room,null)}finally{rmSync(dir,{recursive:true,force:true})}});
test('legacy over-limit packet refunds once, late max refund and unsupported clients are safe',()=>{for(const version of[5,6]){const h=harness();h.start(version);const id=h.view().room.id,packet={raceId:id,requestId:id+':p0',amount:55838554,ticket:{kind:'win',picks:[0]}};if(version===6){h.call('pass');h.step(17000)}h.call('bet',packet);h.call('bet',packet);assert.equal(h.view().deliveries.filter(x=>x.kind==='refund').length,1);assert.equal(h.view().deliveries[0].gold,55838554)}const h=harness();h.call('create',{roster:[{id:'m',speciesId:'slime'}]});const guest={playerId:'guest',clientKey:'guest-key458',connected:true};h.c.sessions.set(guest.playerId,guest);h.c.handle(guest,{op:'join',rulesVersion:5,code:h.view().room.code,roster:[{id:'m2',speciesId:'slime'}]});assert.equal(h.c.view(guest).room,null);assert.match(h.errors.at(-1).message,/更新版/)});
test('free participation at zero GOLD still settles prize and training without stake',()=>{const h=harness();h.start();h.call('pass');h.step(17000);h.step(4000);h.step(40000);h.step(3000);const receipt=h.view().deliveries[0];assert.equal(receipt.stake,0);assert.ok(receipt.training.affection>=5);const save={state:{player:{gold:0},monsters:[]},save:()=>true};applyRaceDelivery451(save,'ws://local|p0',receipt);assert.equal(save.state.player.gold,receipt.prize)});
test('swipes distinguish horizontal/vertical, direction and long drags',()=>{const s={x:200,y:200,at:0};assert.equal(swipeDirection458(s,{x:120,y:205,at:100}),1);assert.equal(swipeDirection458(s,{x:290,y:198,at:120}),-1);assert.equal(swipeDirection458(s,{x:208,y:350,at:120}),0);assert.equal(swipeDirection458(s,{x:160,y:250,at:120}),0);assert.equal(swipeDirection458(s,{x:120,y:200,at:1500}),0)});
test('ordered slot correction swaps duplicate picks and never loses the other picks',()=>{assert.deepEqual(editPick458({kind:'trifecta',picks:[1,3,7]},7,0),{kind:'trifecta',picks:[7,3,1]});assert.deepEqual(editPick458({kind:'exact',picks:[1,3]},5,0),{kind:'exact',picks:[5,3]});assert.deepEqual(editPick458({kind:'pair',picks:[1,3]},1),{kind:'pair',picks:[3]});assert.deepEqual(editPick458({kind:'trifecta',picks:[1]},3,2),{kind:'trifecta',picks:[1,3]})});
test('each panel remembers scroll and rerender restores current position',()=>{globalThis.scrollY=0;const root={scrollTop:430,querySelector:()=>null},c={root,state:{room:{id:'r',phase:'parade'}},predictionTab457:'bet'};c.renderKey458=panelKey458(c);rememberScroll458(c);root.scrollTop=0;restoreScroll458(c,panelKey458(c),c.renderKey458);assert.equal(root.scrollTop,430);c.predictionTab457='watch';restoreScroll458(c,panelKey458(c),c.renderKey458);root.scrollTop=120;rememberScroll458(c);c.predictionTab457='bet';restoreScroll458(c,panelKey458(c),c.renderKey458);assert.equal(root.scrollTop,430);c.predictionTab457='watch';restoreScroll458(c,panelKey458(c),c.renderKey458);assert.equal(root.scrollTop,120)});
