// Real coordinator integration. Only the two absent base-game catalogs use fixtures
// in a partial patch checkout. A complete checkout uses its real catalogs.
import test from 'node:test';
import assert from 'node:assert/strict';
import{registerHooks}from'node:module';
import{existsSync,mkdtempSync,rmSync,readFileSync}from'node:fs';
import{tmpdir}from'node:os';
import{join}from'node:path';
const fixtures={
 [new URL('../src/ui/MonsterVisual.js',import.meta.url).href]:`export const monsterVisual=()=>'<i class="test-sprite"></i>';export const setMonsterVisualFrame=()=>{};`,
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,context,next){const url=spec.startsWith('.')?new URL(spec,context.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,context)},load(url,context,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,context)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,canalVersion489:1,canalRules492:1,canalRules500:1,canalRules496:1,canalRules494:1,cabbageVersion484:1,cabbageScoring491:1,gorillaVersion502:1,gorillaRules503:1,gorillaRules504:1,gorillaRules505:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}

const {gorillaView503}=await import('../src/gorilla/View503.js');
hook.deregister();
function context(state){return{state,transport:{selfId:'p0'},offset:state.serverNow-Date.now(),sgMonster463:()=>'<i class="sg-monster"></i>',sgSpeciesName463:id=>id,ready:()=>true,connected:()=>true,roster:()=>[{id:'m0',speciesId:'wolf'}],bank:()=>null,save:{state:{player:{gold:10000},settings:{},monsters:[]}},root:{querySelector:()=>null},draft:{ticket:{kind:'win',picks:[0]},amount:1000},render(){},ggUI502:{artReady503:true,sound:false}}}
import{makeGorilla504,startGorilla504,pullGorilla504,advanceGorilla504,publicGorilla504}from'../src/gorilla/Rules504.js';
import{decideGorilla503,makeGorilla503,startGorilla503,advanceGorilla503}from'../src/gorilla/Rules503.js';
import{HAIRS504,STAGES504,pain504,painWeight504,stage504,layout504,hairTargets504,toolColor504,toolTag504,flight504,kingPose504,camera504,blast504}from'../src/gorilla/Presentation504.js';
function make(coin=0,bad=0){const g=makeGorilla504({id:'test504',code:'ABC123',hostId:'p0',seed:91,members:Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'P'+i,color499:['pink','orange','blue','green'][i],choice:{id:'m'+i,speciesId:'slime'}}))});startGorilla504(g,0,{badHair:bad,firstSeat:0,mercyCoins504:Array(30).fill(coin),trapOrder504:Array.from({length:30},(_,i)=>i)});return g}
function step(g){advanceGorilla504(g,g.nextAt);return g.phase}
function play(g){step(g);step(g);return g.thinkAt503}
function start(x,n=4){assert.deepEqual(x.send(0,'partyCreate462',{game:'gorilla',roster:[{id:'m0',speciesId:'wolf'}]}),[]);const party=Object.values(x.c.data.parties462)[0],get=()=>x.c.data.gorillaRooms502[party.code];for(let i=1;i<n;i++)assert.deepEqual(x.send(i,'partyJoin462',{code:party.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);for(let i=0;i<n;i++){assert.deepEqual(x.send(i,'gorilla502',{gameId:get().id,kind:'select',monsterId:'m'+i}),[]);assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[])}assert.deepEqual(x.send(0,'gorilla502',{gameId:get().id,kind:'start'}),[]);return{get,party}}
test('all 30 hairs can trigger the first-turn drum, both unbiased coin outcomes work without reaching a pain threshold',()=>{for(let hair=0;hair<30;hair++)for(const coin of[0,1]){const g=make(coin,hair),t=play(g);pullGorilla504(g,'p0',hair,0,t+10);assert.equal(pain504(g,t+10),0);assert.equal(g.events.at(-1).kind,'drum');assert.equal(step(g),'drum');assert.equal(g.loserId,null);advanceGorilla504(g,g.nextAt-1);assert.equal(g.phase,'drum');step(g);assert.equal(g.phase,coin?'reaction':'blast');assert.equal(g.loserId,coin?null:'p0');assert.equal(g.players[0].safePulls,coin);assert.equal(g.drumIndex504,1)}});
test('safe/out views are identical before the 50/50 reveal; hidden decks and coin index never cross the network',()=>{const a=make(0),b=make(1);for(const g of[a,b]){const t=play(g);pullGorilla504(g,'p0',0,0,t+10);step(g)}assert.deepEqual(publicGorilla504(a),publicGorilla504(b));for(const key of['mercyCoins504','trapOrder504','drumIndex504','badHair','seed','nextAt'])assert.equal(JSON.stringify(publicGorilla504(a)).includes('"'+key+'"'),false);step(a);step(b);assert.notDeepEqual(publicGorilla504(a),publicGorilla504(b));assert.equal(publicGorilla504(a).events[0].kind,'rage');assert.equal(publicGorilla504(b).events[0].kind,'safe')});
test('mercy keeps the pulled hair removed, carries time and pain, and picks the next trap from remaining hairs',()=>{const g=make(1),t=play(g);g.mercyCoins504[1]=0;pullGorilla504(g,'p0',0,0,t+10000);assert.equal(step(g),'drum');assert.equal(step(g),'reaction');assert.equal(g.remaining503,50000);assert.deepEqual(g.picked,[0]);assert.equal(g.badHair,1);assert.equal(g.loserId,null);assert.equal(step(g),'decision');decideGorilla503(g,'p0','continue',0,1,g.thinkAt503+5000);step(g);assert.equal(g.remaining503,45000);assert.equal(g.deadline-g.thinkAt503,45000);pullGorilla504(g,'p0',1,0,g.thinkAt503+5);step(g);step(g);assert.equal(g.phase,'blast');assert.equal(g.drumIndex504,2);step(g);assert.equal(g.phase,'result');assert.equal(g.results.filter(p=>p.blownFar).length,1)});
test('duplicate pulls and forbidden inputs during drumming cannot consume coins or alter outcomes',()=>{const g=make(1),t=play(g);pullGorilla504(g,'p0',0,0,t+1);assert.equal(pullGorilla504(g,'p0',0,0,t+2),false);step(g);for(let i=0;i<30;i++){assert.equal(pullGorilla504(g,'p0',0,0,g.phaseAt503+50),false);assert.throws(()=>pullGorilla504(g,'p0',1,0,g.phaseAt503+50));assert.throws(()=>decideGorilla503(g,'p0','pass',0,1,g.phaseAt503+50))}assert.equal(g.drumIndex504,0);step(g);assert.equal(g.drumIndex504,1)});
test('a lucky complete pluck ends as all-safe, rather than selecting from an empty set or hanging',()=>{const g=make(1);advanceGorilla504(g,10000000);assert.equal(g.phase,'result');assert.equal(g.picked.length,30);assert.equal(new Set(g.picked).size,30);assert.equal(g.allSafe504,true);assert.equal(g.loserId,null);assert.equal(g.players.reduce((n,p)=>n+p.safePulls,0),30);assert.ok(g.results.every(p=>!p.blownFar));assert.equal(g.nextAt,null)});
test('delayed ticks and restart checkpoints resolve the same precommitted coin even in the middle of drumming',()=>{for(const coin of[0,1]){const a=make(coin),t=play(a);pullGorilla504(a,'p0',0,0,t+1);step(a);const b=JSON.parse(JSON.stringify(a));for(let n=a.phaseAt503;n<3000000&&a.phase!=='result';n+=551)advanceGorilla504(a,n);advanceGorilla504(b,3000000);assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)))}});
test('8 nondecreasing expression levels: bumps are exactly double; picked history survives every handoff/reconnect',()=>{assert.equal(STAGES504.length,8);assert.equal(HAIRS504.filter(h=>h.bump).length,5);for(const h of HAIRS504)assert.equal(painWeight504(h.id),h.bump?2:1);const g=make(),seen=new Set([0]);let previous=0;for(let i=0;i<30;i++){g.picked.push(i);g.phase='decision';const s=stage504(g);assert.ok(s.index>=previous);previous=s.index;seen.add(s.index);const reconnected=publicGorilla504(g);assert.equal(stage504(reconnected).index,s.index);g.phase='handoff';assert.equal(stage504(g).index,s.index)}assert.equal(seen.size,8);assert.equal(pain504(g),35)});
test('relocated roots cluster centrally and 30 separate 44px targets fit small phones and the short landscape layout',()=>{const g=make(),t=play(g);assert.equal(HAIRS504.filter(h=>h.zone==='chest').length,15);assert.equal(HAIRS504.filter(h=>h.zone==='navel').length,15);assert.ok(HAIRS504.every(h=>h.x>37&&h.x<63));for(const[w,h]of[[320,344],[375,430],[390,460],[430,540],[620,350]]){const l=layout504(w,h,g,t),pts=hairTargets504(l);for(const p of pts){assert.ok(p.x-22>=0&&p.x+22<=w);assert.ok(p.y-22>=72,JSON.stringify({w,h,p}));assert.ok(p.y+22<=h)}for(let i=0;i<30;i++)for(let j=i+1;j<30;j++)assert.ok(Math.abs(pts[i].x-pts[j].x)>=44||Math.abs(pts[i].y-pts[j].y)>=44,'overlap')}});
test('tweezers use configured colors and current actor, including AI; monster badge stays inside the stage below the cue',()=>{const g=make(),t=play(g);for(let seat=0;seat<4;seat++){g.turnSeat=seat;g.phase='playing';assert.equal(toolColor504(g).id,['pink','orange','blue','green'][seat]);for(let id=0;id<30;id++){g.phase='pluck';g.events=[{hair:id,playerId:'p'+seat}];g.phaseAt503=t;const l=layout504(320,344,g,t),tag=toolTag504(g,l,t,null);assert.equal(tag.player.seat,seat);assert.ok(tag.x>=44&&tag.x<=276);assert.ok(tag.y-66>=80&&tag.y<=312)}}});
test('drumming has identical suspense visuals and no flights; only out launches, reduced motion removes shakes and flight',()=>{for(const coin of[0,1]){const g=make(coin),t=play(g);pullGorilla504(g,'p0',0,0,t+1);step(g);const at=g.drumAt504+1500;assert.equal(kingPose504(g,at).asset,'rage');assert.equal(flight504(g,g.players[0],at,390,500).y,0);assert.equal(blast504(g,at).judging,true);assert.equal(blast504(g,at,true).shake,0);step(g);if(coin){assert.equal(camera504(g,g.phaseAt503),0);assert.equal(flight504(g,g.players[0],g.phaseAt503+1000,390,500).y,0)}else{assert.equal(camera504(g,g.phaseAt503),0);assert.ok(flight504(g,g.players[0],g.blastAt+3000,390,500).y<-10);assert.equal(flight504(g,g.players[1],g.blastAt+3000,390,500).landed,true);assert.equal(flight504(g,g.players[0],g.blastAt+5000,390,500).landed,true);assert.equal(flight504(g,g.players[0],g.blastAt+3000,390,500,true).y,0)}}});
test('server start, four views, 504 capability guard and all-safe result buttons use the real coordinator',()=>{const x=setup(4),a=start(x);assert.equal(a.get().rules504,1);assert.equal(a.get().mercyCoins504.length,30);assert.equal(a.get().trapOrder504.length,30);assert.equal(x.c.view(x.sessions.get('p0')).gorillaRules504,1);a.get().mercyCoins504.fill(1);x.time(a.get().startAt+650);x.c.advance();let g=a.get();const seat=g.turnSeat;assert.equal(x.send(seat,'gorilla502',{gameId:g.id,kind:'pull',hair:g.badHair,turn:0,gorillaRules504:0}).length,1);g=a.get();assert.deepEqual(x.send(seat,'gorilla502',{gameId:g.id,kind:'pull',hair:g.badHair,turn:0}),[]);x.time(g.nextAt);x.c.advance();assert.equal(g.phase,'drum');for(let i=1;i<4;i++)assert.deepEqual(x.c.view(x.sessions.get('p0')).gorilla,x.c.view(x.sessions.get('p'+i)).gorilla);x.time(10000000);x.c.advance();assert.equal(g.allSafe504,true);const c=context(x.c.view(x.sessions.get('p0'))),html=gorillaView503(c);assert.match(html,/全員、許された/);assert.match(html,/data-party-result490="again"/);assert.match(html,/data-party-result490="list"/);assert.doesNotMatch(html,/undefined|ホームへ戻る|巻き添え/)});
test('existing 503 games remain deterministic on their original rule engine',()=>{const old=makeGorilla503({id:'old',code:'ABC',hostId:'p0',seed:99,members:[{playerId:'p0',name:'P0',choice:{id:'m0',speciesId:'wolf'}}]});startGorilla503(old,0,{badHair:10,firstSeat:0});const copy=structuredClone(old);advanceGorilla503(old,3000000);advanceGorilla504(copy,3000000);assert.deepEqual(copy,old);assert.equal(old.phase,'result')});
