import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {resizeCampaign440,WORLD_RAID_HP440} from '../src/worldRaid/WorldRaidBalance440.js';
import {newWorldRaidCampaign428} from '../online-server/src/WorldRaidStore428.js';
import {WorldRaidCoordinator440} from '../online-server/src/WorldRaidCoordinator440.js';
import {WorldRaidCoordinator437} from '../online-server/src/WorldRaidCoordinator437.js';
import {fixture430,reserve430,finish430} from '../tools/build430/offline-fixture.mjs';
import {sharedCircle432} from '../src/worldRaid/WorldRaidRules432.js';
import {worldRaidRanking429} from '../src/worldRaid/WorldRaidRewards429.js';
import {replayOffline430} from '../src/worldRaid/WorldRaidReplay430.js';
function oldCampaign(seq=1,damage=14_550_631){const c=newWorldRaidCampaign428(seq,1);delete c.balance440;c.maxHp=[100e9,120e9,140e9][seq-1];c.hp=c.maxHp-damage;c.contribution={a:{damage,attempts:3,name:'A'}};return c;}
test('all three newly spawned campaigns have exactly 50000000 HP',()=>{for(let i=1;i<=6;i++){const c=newWorldRaidCampaign428(i,1);assert.equal(c.maxHp,WORLD_RAID_HP440);assert.equal(c.hp,WORLD_RAID_HP440);}});
test('resize keeps actual 14550631 damage, ranking and contribution; it is idempotent',()=>{const c=oldCampaign(),rank=worldRaidRanking429(c),score=structuredClone(c.contribution);assert.ok(resizeCampaign440(c));assert.equal(c.hp,35_449_369);assert.deepEqual(c.contribution,score);assert.deepEqual(worldRaidRanking429(c),rank);const once=structuredClone(c);assert.equal(resizeCampaign440(c),false);assert.deepEqual(c,once);});
test('existing revival is not granted twice and damage can exhaust new HP',()=>{const c=oldCampaign(1,60e6);resizeCampaign440(c);assert.equal(c.circle432.reviveUsed,true);assert.equal(c.hp,25e6);const done=oldCampaign(1,90e6);resizeCampaign440(done);assert.equal(done.hp,0);const revived=oldCampaign();revived.circle432={...sharedCircle432(revived),reviveUsed:true};revived.hp=50e9;resizeCampaign440(revived);assert.equal(revived.hp,0);});
test('shield damage is retained, including damage beyond the new shield size',()=>{for(const damage of [14e6,60e6,110e6]){const c=oldCampaign(2,0);c.circle432={...sharedCircle432(c),shield:120e9-damage};resizeCampaign440(c);assert.equal(c.circle432.maxShield,50e6);assert.equal(c.circle432.shield,Math.max(0,50e6-damage));assert.equal(c.hp,Math.max(0,50e6-Math.max(0,damage-50e6)));}});
function diskFixture({damage=14_550_631,fail=false}={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'abyss440-')),stateFile=path.join(dir,'raid.json'),f=fixture430();
 f.c=new WorldRaidCoordinator437({sessions:f.sessions,now:f.now,stateFile,random:()=>.5,send:()=>{}});
 f.c.ledger.transact(s=>{const c=oldCampaign(1,damage);c.contribution={};s.current=c;return{ok:true};});
 const [ticket]=reserve430(f,f.b,1);assert.ok(ticket);f.c.start(f.a,{requestId:'online-migration-440',campaignId:f.c.ledger.state.current.id});
 f.c.ledger.transact(s=>{s.current.contribution[f.a.playerId].damage=damage;const a=Object.values(s.attempts)[0];a.damage=damage;return{ok:true};});
 const before=JSON.parse(fs.readFileSync(stateFile)),c=new WorldRaidCoordinator440({sessions:f.sessions,now:f.now,stateFile,random:()=>.5,send:()=>{},...(fail?{persist:()=>false}:{})});return{dir,stateFile,f,before,c,ticket};
}
test('restart migrates live battle without consuming attempts or changing issued offline tickets',()=>{
 const x=diskFixture();try{assert.ok(x.c.healthy());const s=x.c.ledger.state;assert.equal(s.current.hp,35_449_369);assert.deepEqual(s.days,x.before.days);assert.deepEqual(s.current.contribution,x.before.current.contribution);assert.deepEqual(s.offline430,x.before.offline430);const a=x.c.active(x.f.a.playerId);assert.equal(a.room.raid.boss.maxHp,50e6);assert.equal(a.room.raid.boss.hp,35_449_369);assert.equal(a.room.raid.progress.maxHp,50e6);assert.equal(a.damage,14_550_631);const prior=Object.values(x.before.attempts)[0].room.raid;assert.deepEqual(a.room.raid.players,prior.players);assert.deepEqual(a.room.raid.minions,prior.minions);assert.equal(a.room.raid.round,prior.round);const reboot=new WorldRaidCoordinator440({sessions:x.f.sessions,now:x.f.now,stateFile:x.stateFile});assert.deepEqual(reboot.ledger.state,s);}finally{fs.rmSync(x.dir,{recursive:true,force:true});}
});
test('failed migration preserves persisted ledger and disables changes until retry',()=>{const x=diskFixture({fail:true});try{assert.equal(x.c.healthy(),false);assert.deepEqual(JSON.parse(fs.readFileSync(x.stateFile)),x.before);const retry=new WorldRaidCoordinator440({sessions:x.f.sessions,now:x.f.now,stateFile:x.stateFile});assert.ok(retry.healthy());assert.equal(retry.ledger.state.current.hp,35_449_369);}finally{fs.rmSync(x.dir,{recursive:true,force:true});}});
test('already enough damage completes once, keeps pending ticket settlement and no invented final hitter',()=>{const x=diskFixture({damage:90e6});try{const s=x.c.ledger.state;assert.ok(x.c.healthy());assert.equal(s.history.length,1);assert.equal(s.current.sequence,2);assert.equal(s.current.maxHp,50e6);assert.equal(s.history[0].killerId,undefined);assert.ok(s.history[0].closing430);assert.equal(x.c.active(x.f.a.playerId),null);const replay=finish430(x.ticket),result=x.c.submit430(x.f.b,{ticketId:x.ticket.id,commands:replay.commands});assert.equal(result.ok,true);const settled=structuredClone(x.c.ledger.state);assert.equal(x.c.submit430(x.f.b,{ticketId:x.ticket.id,commands:replay.commands}).ok,true);assert.deepEqual(x.c.ledger.state,settled);assert.equal(settled.history[0].settlement429.rankedPlayers,2);}finally{fs.rmSync(x.dir,{recursive:true,force:true});}});
test('old issued replay records remain deterministic across resize',()=>{const x=diskFixture();try{const r=finish430(x.ticket),before=replayOffline430(x.ticket,r.commands).damage;const same=x.c._tickets430().find(t=>t.id===x.ticket.id);assert.deepEqual(same,JSON.parse(JSON.stringify(x.ticket)));assert.equal(replayOffline430(same,r.commands).damage,before);}finally{fs.rmSync(x.dir,{recursive:true,force:true});}});
