import {landingDuration526} from '../src/fishing/Water526.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../src/fishing/Catches525.js';
import * as R from '../src/fishing/Rules524.js';

const make=()=>{const g=R.makeFishing524({id:'525',code:'FISH',partyId:'p',hostId:'p0',members:Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'P'+i,choice:{speciesId:'slime'}}))});R.startFishing524(g,0,525);R.advanceFishing524(g,3000);return g};
const choice=(g,id,extra={})=>{const p=g.players[0],f=C.catch525(id);Object.assign(p,{mode:'choice',fish:{...f,value:f.base,rhythm:0,chainDepth525:0,...extra},choiceUntil:g.elapsed+5000});return p};
const step=(g,ms)=>{for(let end=g.lastAt+ms;g.lastAt<end;)R.advanceFishing524(g,g.lastAt+50)};
const land=(g,p)=>{p.mode='fight';p.hookedAt=g.elapsed;p.fish.rhythm=0;p.progress=.9999;p.tension=.05;p.reel=true;R.fight524(g,p);assert.equal(p.mode,'landing');step(g,landingDuration526(p.fish))};

test('32 unique catches have finite stats, distinct art slots, and only five chain-exclusive entries',()=>{assert.equal(C.CATCHES525.length,32);assert.equal(new Set(C.CATCHES525.map(x=>x.id)).size,32);assert.equal(new Set(C.CATCHES525.map(x=>x.art525.sheet+':'+x.art525.cell)).size,32);assert.equal(C.CATCHES525.filter(x=>x.exclusive525).length,5);for(const f of C.CATCHES525){assert.ok(f.base>=0&&f.kg>0&&f.difficulty>0);const a=C.atlasCSS525(f);assert.ok(!/NaN|undefined/.test(JSON.stringify(a)))}});
test('ordinary casts reach every normal entry, boot, lure, both bait-only catches, and no exclusive catch',()=>{let seed=718;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296},seen=new Set();for(let i=0;i<6000;i++){const f=C.selectCatch525(i%5,random);seen.add(f.id);assert.ok(!f.exclusive525)}assert.deepEqual([...seen].sort(),C.CATCHES525.filter(f=>!f.exclusive525).map(f=>f.id).sort());for(let i=0;i<600;i++){const f=C.selectCatch525(i%4,random,{bait:true});assert.ok(!f.item525&&!f.baitOnly525)}});
test('boot route consumes each previous catch, bonuses rise, and treasure banks once at the end',()=>{const g=make(),p=choice(g,'boot');p.chainTrail525=['boot'];const history=['boot'];let finalValue=0;for(let depth=1;depth<=6;depth++){assert.ok(R.choose524(g,p,'continue'));assert.equal(p.score,0);assert.equal(R.choose524(g,p,'continue'),false);assert.equal(p.fish.chainDepth525,depth);const f=p.fish;assert.equal(R.publicFishing524(g).players[0].fish,null);assert.ok(f.value>=Math.floor(f.base*.8*(1+depth*.12)));history.push(f.id);finalValue=f.value;land(g,p);if(f.terminal525)break}assert.equal(history[1],'hermit');assert.equal(history.at(-1),'treasure');assert.ok(history.includes('keyeel')&&history.includes('kingcrab'));assert.equal(p.score,finalValue);assert.equal(p.records.length,1);assert.equal(p.mode,'rest');assert.equal(p.records[0].id,'treasure');assert.equal(R.choose524(g,p,'keep'),false);assert.deepEqual(p.chainTrail525,history);assert.equal(p.bestChain525,history.length-1)});
test('all weighted recipe branches are reachable and every result exists',()=>{for(const [id,rows]of Object.entries(C.RECIPES525)){const seen=new Set();for(let n=0;n<1000;n++)seen.add(C.selectCatch525(0,()=>n/1000,{previous:C.catch525(id)}).id);assert.deepEqual([...seen].sort(),rows.map(x=>x[0]).sort());for(const [next]of rows)assert.ok(C.catch525(next))}});
test('lure always hooks a tier 2 or 3 catch, reduces fight difficulty, and does not consume stocked bait',()=>{const tiers=new Set();for(let seed=1;seed<=100;seed++){const g=make();g.seed=seed*31627;const p=choice(g,'lure');p.bait=3;assert.ok(R.choose524(g,p,'continue'));tiers.add(p.fish.tier);assert.ok(p.fish.tier>=2&&p.fish.tier<=3);assert.equal(p.fish.difficulty,C.catch525(p.fish.id).difficulty*.7);assert.equal(p.bait,3);assert.equal(p.score,0);assert.equal(p.fish.lureBoost525,true)}assert.deepEqual([...tiers].sort(),[2,3])});
test('bait-only catches reject points and automatically continue, including when bait stock is full',()=>{for(const id of ['crayfish','turtle']){const g=make(),p=choice(g,id);p.bait=3;assert.equal(R.choose524(g,p,'keep'),false);step(g,5000);assert.equal(p.mode,'waiting');assert.equal(p.score,0);assert.equal(p.bait,3);assert.ok(p.fish.chainDepth525===1);assert.ok(['catfish','sturgeon','keyeel'].includes(p.fish.id))}});
test('finished time recovers bait-only catch without points or an unending new cast',()=>{for(const id of ['crayfish','turtle']){const g=make(),p=choice(g,id);p.bait=3;g.elapsed=120000;assert.ok(R.choose524(g,p,'continue'));assert.equal(p.mode,'rest');assert.equal(p.bait,3);assert.equal(p.score,0);assert.ok(!g.events.some(e=>e.type==='chain'));R.finishFishing524(g);assert.equal(g.phase,'result')}});
test('ordinary chain can be cashed out; failure loses the wager and a new cast resets its trail',()=>{const g=make(),p=choice(g,'keyeel',{chainDepth525:3,value:277});p.chainTrail525=['boot','hermit','mimic','keyeel'];assert.ok(R.choose524(g,p,'keep'));assert.equal(p.score,277);assert.equal(p.records[0].chainDepth525,3);step(g,600);choice(g,'boot');assert.ok(R.choose524(g,p,'continue'));p.mode='fight';p.hookedAt=g.elapsed;p.progress=.3;p.tension=.999;p.reel=true;p.fish.rhythm=3500;R.fight524(g,p);assert.equal(p.mode,'rest');assert.equal(p.score,277);step(g,1100);assert.ok(R.cast524(g,p,.4,.4));assert.deepEqual(p.chainTrail525,[]);assert.equal(p.fish.chainDepth525,0)});
test('six-chain limit, terminal catches, invalid modes, and countdown cannot be chained',()=>{const g=make(),p=choice(g,'arowana',{chainDepth525:6});assert.equal(R.choose524(g,p,'continue'),false);for(const id of ['lord','treasure']){choice(g,id);assert.equal(R.choose524(g,p,'continue'),false)}choice(g,'boot');g.phase='countdown';assert.equal(R.choose524(g,p,'continue'),false);g.phase='play';p.mode='fight';assert.equal(R.choose524(g,p,'continue'),false);p.mode='choice';g.elapsed=120000;assert.equal(R.choose524(g,p,'continue'),false)});
test('golden fish is valuable; true lord is largest, worth most, and gets a longer landing',()=>{const lord=C.catch525('lord');assert.ok(lord.base>C.catch525('arowana').base&&lord.kg>=10*C.catch525('arowana').kg);const g=make(),p=choice(g,'lord');p.mode='fight';p.hookedAt=0;p.progress=.9999;p.tension=.1;p.reel=true;R.fight524(g,p);step(g,1200);assert.equal(p.mode,'landing');step(g,1600);assert.equal(p.mode,'rest');assert.equal(p.score,lord.base)});
test('saved Build524 match upgrades metadata without replacing an active hook or its score',()=>{const g=make(),p=choice(g,'ruby');g.rules524=1;delete p.chainTrail525;delete p.bestChain525;p.score=219;p.fish.value=106;const fish=p.fish;step(g,50);assert.equal(g.rules524,3);assert.equal(p.fish,fish);assert.equal(p.score,219);assert.deepEqual(p.chainTrail525,[]);assert.equal(p.bestChain525,0)});
