import test from 'node:test';
import assert from 'node:assert/strict';
import * as R from '../src/hide/Rules536.js';
import * as M from '../src/hide/Map537.js';
import {queueHide536,liveHide536} from '../online-server/src/HideCoordinator536.js';
import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';
import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'P'+i,owned:[{id:'m'+i,speciesId:'slime'}],choice:{id:'m'+i,speciesId:'slime'}}));
function make(role='hunter',count=4,seed=537){const g=R.makeHide536({id:'537',code:'ABC',partyId:'party',hostId:'p0',members:members.slice(0,count)});g.role=role;R.startHide536(g,0,seed);return g}
const advance=(g,ms,inputs=new Map(),auto=new Set())=>{const end=g.lastAt+ms;while(g.lastAt<end&&['play','hiding'].includes(g.phase))R.advanceHide536(g,Math.min(end,g.lastAt+50),inputs,auto)};
const play=()=>{const g=make();advance(g,20000);return g};
function together(g){const p=g.map.rooms[4],a=M.nearest537(g.map,{x:p.cx,y:p.cy});g.players.forEach((p,i)=>Object.assign(p,{x:a.x+i*25,y:a.y,route:[],goal:null}));}
test('100 seeded maps: connected room graph, loops, varied shapes and all 12 disguise lookalikes',()=>{const stamps=new Set();for(let seed=1;seed<=100;seed++){const m=M.makeMap537(seed),props=M.furniture537(m,seed);assert.equal(m.width,2900);assert.equal(m.rooms.length,9);assert.ok(m.links.length>=10);stamps.add(JSON.stringify(m.cells));for(const room of m.rooms){const path=M.path537(m,m.spawn,{x:room.cx,y:room.cy});assert.ok(path.length,'seed '+seed+' room '+room.index);let last=m.spawn;for(const q of path){assert.ok(M.line537(m,last,q,24));last=q}}assert.equal(new Set(props.map(p=>p.kind)).size,12);assert.ok(props.length>=130);assert.ok(props.every(p=>M.free537(m,p.x,p.y,32)));assert.deepEqual(m,M.makeMap537(seed))}assert.ok(stamps.size>95)});
test('one hunter, three hiders; every hider receives exactly two distinct options and starts in an open staging area',()=>{for(let count=1;count<=4;count++){const g=make('hunter',count);assert.equal(g.players.length,4);assert.equal(g.players.filter(p=>p.ai).length,4-count);assert.equal(g.players.filter(p=>p.hunter).length,1);for(const p of g.players){assert.equal(new Set(p.choices).size,2);assert.ok(p.choices.every(k=>k>=0&&k<12));assert.ok(M.free537(g.map,p.x,p.y));if(!p.hunter)assert.ok(!g.objects.some(o=>Math.hypot(o.x-p.x,o.y-p.y)<50))}}});
test('choose only from own two options during preparation, then lock; hunter stays blind and stationary',()=>{const g=make(),p=g.players[1],h=g.players[0],original={x:h.x,y:h.y};advance(g,50,new Map([['p1',{kind:p.choices[1]}],['p0',{target:g.map.spawn}]]));assert.equal(p.kind,p.choices[1]);advance(g,50,new Map([['p1',{kind:(p.kind+1)%12===p.choices[0]?(p.kind+2)%12:(p.kind+1)%12}]]));assert.equal(p.kind,p.choices[1]);assert.deepEqual({x:h.x,y:h.y},original);assert.deepEqual(R.publicHide536(g,'p0').objects,[]);advance(g,20000);advance(g,50,new Map([['p1',{kind:p.choices[0]}]]));assert.equal(p.kind,p.choices[1])});
test('equal cardinal and diagonal speed, no running bonus; stop and joystick expiry work',()=>{const g=play();together(g);const h=g.players[0],p=g.players[1],open=M.nav537(g.map).find(q=>M.line537(g.map,q,{x:q.x+160,y:q.y},24)&&M.line537(g.map,q,{x:q.x+120,y:q.y+120},24));Object.assign(h,{x:open.x,y:open.y});p.x=h.x;p.y=h.y;const start={x:h.x,y:h.y};const input=new Map([['p0',{steer:{x:1,y:0},receivedAt:g.lastAt}],['p1',{steer:{x:1,y:1},receivedAt:g.lastAt}]]);advance(g,500,input);assert.ok(Math.abs(h.distance-p.distance)<1e-6);assert.ok(Math.abs(h.distance-115)<1e-6);advance(g,1000,input);const after={x:h.x,y:h.y};advance(g,500,input);assert.deepEqual({x:h.x,y:h.y},after);assert.ok(h.x>start.x);advance(g,100,new Map([['p0',{target:null}]]));assert.deepEqual({x:h.x,y:h.y},after)});
test('tap navigation goes around sea and furniture without crossing blocked geometry',()=>{const g=play(),p=g.players[1],goal=g.map.rooms[0];const input=new Map([['p1',{target:{x:goal.cx,y:goal.cy}}]]);for(let i=0;i<1000;i++){advance(g,50,input);assert.ok(M.free537(g.map,p.x,p.y),'collision step '+i)}assert.ok(Math.hypot(p.x-goal.cx,p.y-goal.cy)<2)});
test('mandatory 30-second shake for moving and still hiders; bounded 2.4 seconds; no global location leak',()=>{const g=play();together(g);advance(g,29950);assert.equal(R.shaking537(g),false);advance(g,50,new Map([['p1',{steer:{x:1,y:0},receivedAt:g.lastAt}]]));assert.ok(g.players[1].moving);assert.ok(R.shaking537(g));assert.equal(R.objects536(g,'p0').filter(o=>o.shaking).length,3);assert.equal(g.events.filter(e=>e.type==='shake').length,1);assert.ok(g.events.filter(e=>e.type==='shake').every(e=>e.x===undefined&&e.seat===undefined));advance(g,2400);assert.equal(R.shaking537(g),false);advance(g,27600);assert.ok(R.shaking537(g));assert.equal(g.events.filter(e=>e.type==='shake').length,2)});
test('hunter has wider vision; walls and distance conceal opponent positions, names, options and routes',()=>{const g=play();together(g);const v=R.publicHide536(g,'p0');assert.ok(R.HIDE536.sight>R.HIDE536.hiderSight);for(const p of v.players.filter(p=>!p.hunter))for(const key of ['x','y','kind','choices','objectId','brain','route','goal'])assert.equal(p[key],undefined,key);for(const o of v.objects)for(const key of ['owner','seat','playerId','moving'])assert.equal(o[key],undefined);assert.equal(v.seed,undefined);assert.equal(v.map.objects,undefined);assert.equal(R.publicHide536(g,'p0',{frame:true}).map,undefined);const h=g.players[0],p=g.players[1];Object.assign(h,g.map.hunter);Object.assign(p,g.map.spawn);assert.ok(!R.objects536(g,'p0').some(o=>o.id===p.objectId));assert.equal(R.publicHide536(g,'p1').players[0].x,undefined)});
test('attacks validate role, sight, range, cooldown and duplicate; three catches may win on last shot',()=>{const g=play();together(g);const h=g.players[0];assert.equal(R.attackHide536(g,g.players[1],g.players[2].objectId),false);assert.equal(R.attackHide536(g,h,'invalid'),false);assert.equal(g.shots,12);g.shots=3;for(let i=1;i<4;i++){g.shotReadyAt=0;assert.ok(R.attackHide536(g,h,g.players[i].objectId));assert.equal(R.attackHide536(g,h,g.players[i].objectId),false)}assert.equal(g.phase,'result');assert.equal(g.winningSide,'hunter');assert.equal(g.shots,0)});
test('12 wrong objects lose, timeout needs only one surviving teammate, finish is idempotent',()=>{const g=play(),h=g.players[0];for(const o of g.objects.slice(0,12)){Object.assign(h,{x:o.x,y:o.y});g.shotReadyAt=0;assert.ok(R.attackHide536(g,h,o.id));g.shotReadyAt=0;assert.equal(R.attackHide536(g,h,o.id),false)}assert.equal(g.reason,'shots');const t=play();t.players[1].alive=false;t.players[2].alive=false;advance(t,150000);assert.equal(t.reason,'time');assert.equal(t.winnerIds.length,3);assert.equal(t.results.filter(p=>p.escaped).length,1);const frozen=structuredClone(t);R.finishHide536(t,'hunter','caught');R.advanceHide536(t,1e9);assert.deepEqual(t,frozen)});
test('packet validation includes new bounds, two-choice rules, finite analog controls and version gate',()=>{const g=play(),c={data:{hideRooms536:{ABC:g}},now:()=>20000},session={playerId:'p1'},base={gameId:g.id,hideVersion536:2,kind:'input',seq:1};for(const bad of [{target:{x:NaN,y:1}},{target:{x:2901,y:1}},{prop:12},{steer:{x:2,y:0}},{steer:{x:0,y:Infinity}},{seq:-1},{gameId:'old'},{hideVersion536:1}])assert.equal(queueHide536(c,session,{...base,...bad}),false);assert.ok(queueHide536(c,session,{...base,steer:{x:1,y:0}}));assert.equal(queueHide536(c,session,base),false);assert.ok(queueHide536(c,session,{...base,seq:2,target:{x:1000,y:1400}}));assert.equal(c.hideRuntime536.get(g.id).inputs.get('p1').steer,null)});
function rig(count=4){let now=100000;const messages=[],sessions=new Map(members.map(m=>[m.playerId,{playerId:m.playerId,clientKey:m.playerId,connected:true,profile:{name:m.name}}]));const c=new RaceCoordinator451({sessions,now:()=>now,send:(id,msg)=>messages.push({id,...msg})});const q=(i,op,extra={})=>{messages.length=0;c.handle(sessions.get('p'+i),{op,rulesVersion:8,hideVersion536:2,roster:members[i].owned,displayName:members[i].name,...extra});return messages.find(m=>m.type==='raceError451')};assert.equal(q(0,'partyCreate462',{game:'hide'}),undefined);const party=partyFor462(c,'p0');for(let i=1;i<count;i++)q(i,'partyJoin462',{code:party.code});return{c,q,sessions,messages,party,game:()=>partyRace462(c,partyFor462(c,'p0')),tick(ms){for(let k=0;k<ms;k+=50){now+=Math.min(50,ms-k);c.advanceHide536()}}}}
test('four-human coordinator: private frames omit terrain, reconnect full snapshot restores map, replay/list stay integrated',()=>{const t=rig(),{q,c}=t;let g=t.game();assert.match(q(1,'hide536',{gameId:g.id,kind:'role',role:'hunter'}).message,/部屋主/);q(0,'hide536',{gameId:g.id,kind:'role',role:'hunter'});assert.ok(q(0,'hide536',{gameId:g.id,kind:'start'}));for(let i=0;i<4;i++){q(i,'hide536',{gameId:g.id,kind:'select',monsterId:'m'+i});assert.equal(q(i,'partyReady462',{ready:true}),undefined);}assert.equal(q(0,'hide536',{gameId:g.id,kind:'start'}),undefined);t.tick(20500);g=liveHide536(c,t.game());assert.equal(g.phase,'play');const frame=t.messages.find(m=>m.type==='hideFrame536');assert.ok(frame);assert.equal(frame.hide.map,undefined);assert.equal(c.view(t.sessions.get('p0')).hide.map.rooms.length,9);assert.equal(c.view(t.sessions.get('p0')).hide.players[1].x,undefined);t.sessions.get('p0').connected=false;t.tick(50);assert.ok(g.players[0].auto);t.sessions.get('p0').connected=true;t.tick(50);assert.equal(g.players[0].auto,false);R.finishHide536(g,'hiders','time');t.tick(50);const id=g.id;assert.equal(q(0,'partyResult490',{partyId:t.party.id,gameId:id,kind:'again'}),undefined);assert.notEqual(t.game().id,id);assert.equal(t.game().role,'hunter');assert.equal(q(0,'partyLounge462'),undefined);assert.equal(c.view(t.sessions.get('p0')).hide,null)});
test('old active hide games return safely to a new lobby; other party state and roster persist',()=>{const t=rig(),g=t.game();g.rulesVersion=1;g.phase='play';g.map=undefined;t.party.members.forEach(m=>m.ready=true);t.tick(50);const next=t.game();assert.equal(next.phase,'lobby');assert.equal(next.rulesVersion,2);assert.equal(next.id,g.id);assert.equal(next.members.length,4);assert.ok(t.party.members.every(m=>!m.ready));assert.match(next.migrationNote,/更新/)});
test('AI navigates actual geometry and serialized restart is deterministic',()=>{let wins=0;for(const seed of [12,63,537,2048]){const g=make('random',1,seed);g.players.forEach(p=>p.ai=true);advance(g,49000);const b=JSON.parse(JSON.stringify(g));advance(g,130000);advance(b,130000);assert.deepEqual(g,b);assert.equal(g.phase,'result');assert.equal(g.results.length,4);assert.ok(g.shots>=0);assert.ok(g.players.every(p=>M.free537(g.map,p.x,p.y)));if(g.winningSide==='hunter')wins++}console.log('AI hunter wins / 4:',wins)});
