import {createHash} from 'node:crypto';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {makeLobby463,start463,action463,botAction463,current463,settle463,public463} from '../src/sugoroku/Engine463.js';
import {applyCrystal477} from '../src/sugoroku/CrystalRules477.js';
import {fund480,grant480,bonus480,finish480,validReceipt480} from '../src/sugoroku/Economy480.js';
import {reserveEntry474,applyCrystalDelivery474} from '../src/sugoroku/Wallet474.js';
import {handleSugoroku463,advanceSugoroku463} from '../online-server/src/SugorokuCoordinator463.js';
import {settleCrystals474} from '../online-server/src/SugorokuRewards474.js';
import {bindHand466,deferHandRender474} from '../src/sugoroku/HandOrder466.js';
import {photoFor468} from '../src/sugoroku/PhotoArt468.js';
import {CARD_BY_ID463} from '../src/sugoroku/Catalog463.js';
function game(seed=1,humans=1,fee=500){const members=Array.from({length:humans},(_,i)=>({playerId:'p'+i,name:'P'+i})),g=makeLobby463({id:'sg463-480-1234abcd',code:'ABCDEF',partyId:'party',hostId:'p0',members,seed});g.economy474={mode:'crystal',fee,entries:Object.fromEntries(members.map(m=>[m.playerId,{requestId:'request-'+m.playerId,amount:fee}]))};start463(g,1000);return g;}
function context(g){let now=2000;const accounts=Object.fromEntries(g.members.map(m=>[m.playerId,{sgDecisions474:{['request-'+m.playerId]:{status:'accepted'}}}])),p={id:'party',code:'ABCDEF',hostId:'p0',members:g.members.map(m=>({playerId:m.playerId,ready:true}))},c={data:{serial:480,boardRooms463:{ABCDEF:g},parties462:{party:p},accounts},sessions:new Map([['p0',{connected:true}]]),now:()=>now,transaction:fn=>fn(),broadcast(){},setNow:n=>now=n};return c;}
const request=(c,kind,id='p0',requestId=kind+'-request')=>{const g=c.data.boardRooms463.ABCDEF;return handleSugoroku463(c,{playerId:id},{op:'sg463',kind,gameId:g.id,revision:g.revision,rulesVersion:16,requestId})};
const total=g=>g.crystalReserve480+g.players.reduce((n,p)=>n+p.crystals474,0);
test('table gems circulate with bounded supply, including repeated loss/double/theft',()=>{const g=game(),base=total(g);assert.equal(base,2400);assert.ok(g.players.every(p=>p.crystals474===500));for(let i=0;i<1000;i++){const a=g.players[i%4],b=g.players[(i+1)%4];applyCrystal477(g,a,b,['steal','gain','double','half','lose'][i%5]);assert.equal(total(g),base);assert.ok(g.crystalReserve480>=0);for(const p of g.players){assert.ok(p.crystals474>=0&&p.crystals474<=2000);assert.equal(p.crystals474,p.crystalBase480+p.crystalShrines477+p.crystalEvents477);}}});
test('all four humans can finish positive while total new gems stays within 400',()=>{const g=game(1,4);for(const p of g.players)grant480(g,p,100);g.results=g.players.map((p,i)=>({playerId:p.playerId,place:i+1}));finish480(g);assert.deepEqual(g.results.map(r=>r.crystals474.net),[200,120,60,20]);assert.equal(g.results.reduce((s,r)=>s+r.crystals474.net,0),400);});
test('AI holdings never inflate a solo payout beyond fee plus 20 percent; receipts apply once',()=>{const g=game();g.players[0].crystals474=2000;for(const p of g.players.slice(1))p.crystals474=0;g.results=g.players.map((p,i)=>({playerId:p.playerId,place:i+1}));finish480(g);g.phase='result';const c=context(g);settleCrystals474(c,g);settleCrystals474(c,g);const receipt=c.data.accounts.p0.sgDeliveries474[0];assert.equal(c.data.accounts.p0.sgDeliveries474.length,1);assert.equal(receipt.crystals,600);assert.equal(validReceipt480(receipt),true);const save={state:{player:{crystals:5000}},save:()=>true},key='server|p0';reserveEntry474(save,key,{gameId:g.id,requestId:'request-p0',amount:500});assert.equal(applyCrystalDelivery474(save,key,receipt).duplicate,false);assert.equal(save.state.player.crystals,5100);assert.equal(applyCrystalDelivery474(save,key,receipt).duplicate,true);assert.equal(validReceipt480({...receipt,crystals:601}),false);});
test('detour bonus occurs immediately once, including when the roll skips all four spaces',()=>{const g=game(),p=g.players[0];p.pos='55';p.trail=['55'];g.step='ending';g.pending={id:1,playerId:p.playerId,kind:'fork',options:[{value:'56'},{value:'b55-0'}],data:{effect:{type:'move',actor:p.playerId,target:p.playerId,group:'fork-test',n:5,event:false}}};const count=p.hand.length;action463(g,p.playerId,{kind:'choice',value:'b55-0'},2000);while(g.pending)action463(g,g.pending.playerId,botAction463(g,g.pending.playerId),2100);assert.equal(p.crystals474,600);assert.deepEqual(p.detours480,['55']);assert.ok(p.hand.length>=count+3);p.pos='55';p.trail=['55'];g.pending={id:2,playerId:p.playerId,kind:'fork',options:[{value:'56'},{value:'b55-0'}],data:{effect:{type:'move',actor:p.playerId,target:p.playerId,group:'fork-repeat',n:5,event:false}}};action463(g,p.playerId,{kind:'choice',value:'b55-0'},3000);assert.equal(p.crystals474,600);});
test('paid solo pause survives reload, blocks AI, resumes and supports explicit zero-reward exit',()=>{let g=game(),c=context(g);request(c,'pause480');assert.equal(g.paused480,true);const before=JSON.stringify(g);c.setNow(900000);advanceSugoroku463(c);assert.equal(JSON.stringify(g),before);c.data=JSON.parse(JSON.stringify(c.data));g=c.data.boardRooms463.ABCDEF;request(c,'resume480');assert.equal(g.paused480,false);request(c,'quit480');assert.equal(c.data.boardRooms463.ABCDEF,undefined);const receipt=c.data.accounts.p0.sgDeliveries474[0];assert.equal(receipt.kind,'abandon480');assert.equal(receipt.crystals,0);const save={state:{player:{crystals:1000}},save:()=>true};reserveEntry474(save,'server|p0',{gameId:g.id,requestId:'request-p0',amount:500});applyCrystalDelivery474(save,'server|p0',receipt);assert.equal(save.state.player.crystals,500);});
test('multiplayer pause/quit cannot terminate others; autoplay and missing timer recovery work',()=>{const g=game(1,2),c=context(g);assert.throws(()=>request(c,'pause480'),/ひとり/);assert.throws(()=>request(c,'quit480'),/AI/);request(c,'auto480');assert.equal(g.players[0].auto480,true);delete g.nextAutoAt;delete g.deadline;c.setNow(100000);advanceSugoroku463(c);assert.ok(g.presentationSequence464>0);assert.ok(Number.isFinite(g.deadline));});
test('an orphan ending phase resumes without skipping pending choices',()=>{const g=game(),c=context(g);g.step='ending';g.queue=[];g.presentationUntil465=0;advanceSugoroku463(c);assert.equal(g.turn,1);assert.equal(g.step,'draw');g.pending={kind:'special',playerId:g.players[1].playerId,options:[{value:'swift'}],data:{old:null,next:'swift'}};const pending=g.pending;g.step='ending';c.setNow(g.nextAutoAt-1);advanceSugoroku463(c);assert.equal(g.pending,pending);});
test('complete 200 seeded matches preserve the pool and cap actual human payouts',()=>{for(let seed=1;seed<=200;seed++){const humans=seed%4+1,g=game(seed,humans,seed%5===0?1:500),initial=total(g);let steps=0;while(g.phase==='playing'&&steps<1500){const id=g.pending?.playerId??current463(g).playerId,m=botAction463(g,id);assert.ok(m,'seed '+seed);action463(g,id,m,2000+steps++);assert.equal(total(g),initial);}assert.equal(g.phase,'result','seed '+seed);const c=context(g);settleCrystals474(c,g);const receipts=Object.values(c.data.accounts).flatMap(a=>a.sgDeliveries474??[]);for(const e of receipts)assert.ok(validReceipt480(e),JSON.stringify(e));assert.ok(receipts.reduce((s,e)=>s+e.crystals,0)<=humans*g.economy474.fee+bonus480(g.economy474.fee,humans));}});
test('the replaced photo is the supplied river original',()=>{const url=photoFor468(CARD_BY_ID463['enami-1']);assert.equal(url,'./assets/sugoroku480/enami-river.jpeg');assert.equal(createHash('sha256').update(fs.readFileSync(new URL('../assets/sugoroku480/enami-river.jpeg',import.meta.url))).digest('hex'),'5000fbae95abedd477935a2014e5167aaab08c82c64fc9c757626c539585630e');});
function handRig(options={}){
 const saved=new Map(),timers=new Map(),frames=new Map(),originals={};let clock=1000,seq=0,renders=0;
 for(const key of ['setTimeout','clearTimeout','requestAnimationFrame','cancelAnimationFrame','window','localStorage'])originals[key]=globalThis[key];const oldNow=Date.now;
 globalThis.setTimeout=(fn,ms=0)=>{const id=++seq;timers.set(id,{fn,at:clock+ms});return id};globalThis.clearTimeout=id=>timers.delete(id);globalThis.requestAnimationFrame=fn=>{const id=++seq;frames.set(id,fn);return id};globalThis.cancelAnimationFrame=id=>frames.delete(id);Date.now=()=>clock;
 class Events{constructor(){this.events={}}addEventListener(n,f){(this.events[n]??=[]).push(f)}removeEventListener(n,f){this.events[n]=(this.events[n]??[]).filter(x=>x!==f)}emit(n,e={}){for(const f of [...this.events[n]??[]])f({type:n,cancelable:true,preventDefault(){this.prevented=true},stopImmediatePropagation(){this.stopped=true},...e})}}
 const win=new Events();globalThis.window=win;globalThis.localStorage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,v)};
 const cls=()=>{const set=new Set();return {add:x=>set.add(x),remove:x=>set.delete(x),contains:x=>set.has(x)}};
 const hand=new Events();Object.assign(hand,{children:[],classList:cls(),scrollLeft:0,scrollTop:0,getBoundingClientRect:()=>({left:0,right:420,top:100,bottom:310}),querySelectorAll:()=>hand.children,append(card){this.children=this.children.filter(x=>x!==card);this.children.push(card)},insertBefore(card,target){this.children=this.children.filter(x=>x!==card);this.children.splice(this.children.indexOf(target),0,card)}});
 Object.defineProperty(hand,'lastElementChild',{get:()=>hand.children.at(-1)});
 for(const [uid,ids]of [['a'],['b','b,b2'],['c']]){const props=new Map(),card={dataset:{uid,...(ids?{handIds:ids}:{})},classList:cls(),style:{setProperty:(k,v)=>props.set(k,v),removeProperty:k=>props.delete(k),getPropertyValue:k=>props.get(k)},closest:()=>card,getBoundingClientRect:()=>({left:hand.children.indexOf(card)*130-hand.scrollLeft,top:114,width:125,height:175})};Object.defineProperty(card,'nextElementSibling',{get:()=>hand.children[hand.children.indexOf(card)+1]});hand.children.push(card);}
 const u={order466:['a','b','b2','c'],orderKey466:'order',scrolls:{}},c={root:{querySelector:()=>hand},sgUI463:u,render:()=>{renders++}};
 const cleanup=bindHand466(c,u,options),advance=ms=>{clock+=ms;for(const [id,t] of [...timers])if(t.at<=clock){timers.delete(id);t.fn()}},frame=()=>{const pending=[...frames];frames.clear();for(const [,f]of pending)f()};
 return {u,c,hand,win,saved,advance,frame,get renders(){return renders},event:(target,x=30,y=190)=>({target,pointerId:1,pointerType:'touch',clientX:x,clientY:y,isPrimary:true,button:0}),close(){cleanup();for(const [k,v]of Object.entries(originals)){if(v===undefined)delete globalThis[k];else globalThis[k]=v;}Date.now=oldNow}};
}

test('upward release casts once; short, canceled, unavailable and horizontal gestures do not',()=>{let playable=true,plays=[];const r=handRig({canPlay:card=>playable?card.dataset.uid:null,onPlay:uid=>plays.push(uid)});try{const a=r.hand.children[0];const drag=(x,y,cancel=false)=>{r.hand.emit('pointerdown',r.event(a));r.advance(430);r.win.emit('pointermove',r.event(a,x,y));r.frame();r.win.emit(cancel?'pointercancel':'pointerup',r.event(a,x,y));r.advance(500)};drag(30,80);assert.deepEqual(plays,['a']);assert.deepEqual(r.u.order466,['a','b','b2','c']);drag(30,150);drag(30,80,true);playable=false;drag(30,80);playable=true;drag(395,190);assert.deepEqual(plays,['a']);assert.deepEqual(r.u.order466,['b','b2','c','a']);}finally{r.close()}});
test('legality is rechecked at release and abandoned holds expire',()=>{let playable=true,plays=[];const r=handRig({canPlay:c=>playable?c.dataset.uid:null,onPlay:uid=>plays.push(uid)});try{const a=r.hand.children[0];r.hand.emit('pointerdown',r.event(a));r.advance(430);r.win.emit('pointermove',r.event(a,30,80));r.frame();playable=false;r.win.emit('pointerup',r.event(a,30,80));assert.deepEqual(plays,[]);r.advance(500);r.hand.emit('pointerdown',r.event(a));r.advance(21000);assert.equal(r.u.handDragging466,false);assert.equal(r.u.handInteracting474,false);}finally{r.close()}});

test('the bonus is 20 percent at large fees, with no fixed per-player ceiling',()=>{assert.equal(bonus480(5000,1),1000);assert.equal(bonus480(5000,4),4000);const g=game(1,4,5000);assert.equal(total(g),24000);for(const p of g.players)grant480(g,p,1000);g.results=g.players.map((p,i)=>({playerId:p.playerId,place:i+1}));finish480(g);assert.equal(g.results.reduce((n,r)=>n+r.crystals474.net,0),4000);assert.ok(g.results.every(r=>r.crystals474.net>100));});

test('an animation boundary keeps its next frame when dragging defers the DOM render',async()=>{
 const {presentationAfter464}=await import('../src/sugoroku/Presentation464.js');const oldRAF=globalThis.requestAnimationFrame,oldCancel=globalThis.cancelAnimationFrame,frames=new Map();let seq=0,renders=0;
 globalThis.requestAnimationFrame=fn=>{frames.set(++seq,fn);return seq};globalThis.cancelAnimationFrame=id=>frames.delete(id);
 try{const g={id:'animation-test',hand:[],players:[],presentationSequence464:2,presentation464:[],step:'draw'},f={gameId:g.id,seen:2,positions:{},queue:[{id:2,kind:'effect',duration465:10}],active:{event:{id:1,kind:'effect'},duration:1,start:performance.now()-20},visual466:{hand:[],players:[]},seriesHand468:[],recent470:[]},c={state:{sugoroku:g},sgFX464:f,root:{querySelector:s=>s==='.sg-game'?{classList:{toggle(){}}}:null,querySelectorAll:()=>[]},connected:()=>true,transport:{selfId:'p0'},render:()=>{renders++}};
 presentationAfter464(c,()=>'',()=>'',()=>{});assert.equal(renders,1);assert.equal(frames.size,1,'the render was deferred, so a frame must still be scheduled');assert.equal(f.active.event.id,2);
 f.active.start=performance.now()-20;const frame=frames.values().next().value;frames.clear();frame();assert.equal(f.active,null);assert.equal(f.queue.length,0);assert.equal(renders,2);
 }finally{globalThis.requestAnimationFrame=oldRAF;globalThis.cancelAnimationFrame=oldCancel;}
});
