import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks,createRequire} from 'node:module';import {existsSync,readFileSync} from 'node:fs';
import * as R from '../src/sumo/Rules523.js';
const C=R.SUMO523;
function make(n=4,seed=523){const g=R.makeSumo523({id:'523',code:'SUMO',hostId:'p0',members:Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'P'+i,owned:[{id:'m'+i,speciesId:'slime'}],choice:{id:'m'+i,speciesId:'slime'}}))});R.startSumo523(g,0,seed);R.advanceSumo523(g,3000);return g}
function step(g,ms,inputs=new Map()){for(let end=g.lastAt+ms;g.lastAt<end-.1&&g.phase==='play';)R.advanceSumo523(g,g.lastAt+50,inputs)}
function strike(g,p,power=1){Object.assign(p,{charging:true,charge:power*1400,coolUntil:0,stunUntil:0});R.release523(g,p)}
test('1–4 humans always produce four seats, equal base stats, and 18 crystals',()=>{for(let n=1;n<=4;n++){const g=make(n);assert.equal(g.players.length,4);assert.equal(g.players.filter(p=>p.ai).length,4-n);assert.ok(g.players.every(p=>p.power===0));assert.equal(g.crystals.length,18)}});
test('diagonal movement normalizes and held charge slows movement without unlimited growth',()=>{const g=make(),p=g.players[0];R.motion523(g,p,{x:1,y:1});assert.ok(Math.abs(Math.hypot(p.vx,p.vy)-3.8)<1e-8);R.motion523(g,p,{x:1,y:0,press:true});assert.ok(p.charging);assert.ok(p.vx<1.7);for(let i=0;i<180;i++)R.motion523(g,p,{x:0,y:0});assert.equal(p.charge,1400);R.motion523(g,p,{release:true});assert.equal(p.charging,false);assert.ok(p.attackUntil>0);assert.ok(p.coolUntil>p.attackUntil)});
test('release respects cooldown; cancellation never fires a charge',()=>{const g=make(),p=g.players[0];R.motion523(g,p,{press:true});p.charge=1400;R.motion523(g,p,{cancel:true});assert.equal(p.attackSerial,0);strike(g,p);assert.equal(p.attackSerial,1);R.motion523(g,p,{press:true});assert.equal(p.charging,false);g.elapsed=p.coolUntil;R.motion523(g,p,{press:true});assert.equal(p.charging,true)});
test('crystals increase body and resistance but remain capped',()=>{const g=make(),p=g.players[0],size=R.body523(p);g.crystals=Array.from({length:40},(_,i)=>({id:i,x:p.x,y:p.y,value:3}));step(g,50);assert.equal(p.power,24);assert.ok(R.body523(p)>size);assert.ok(R.mass523(p)>1);assert.ok(g.events.some(e=>e.type==='grow'));assert.ok(g.crystals.length<=26)});
test('a strong small attacker can knock a max-size opponent sideways; one hit per charge',()=>{const g=make(),a=g.players[0],b=g.players[1];Object.assign(a,{x:0,y:0,fx:1,fy:0});Object.assign(b,{x:1,y:0,power:24,fx:0,fy:1});strike(g,a);R.collide523(g);assert.ok(b.kx>8);assert.equal(a.hits,1);b.x=a.x+1;R.collide523(g);assert.equal(a.hits,1);assert.equal(b.lastHit,a.playerId)});
test('simultaneous head-on charges trade impulses rather than granting first-seat priority',()=>{const g=make(),a=g.players[0],b=g.players[1];Object.assign(a,{x:-.3,y:0,fx:1,fy:0});Object.assign(b,{x:.3,y:0,fx:-1,fy:0});strike(g,a);strike(g,b);R.collide523(g);assert.equal(a.hits,1);assert.equal(b.hits,1);assert.ok(a.kx<0&&b.kx>0);assert.ok(Math.abs(a.kx+b.kx)<1e-8)});
test('ring out is immediate, one survivor wins, and a simultaneous wipe is a draw',()=>{const g=make();g.players.slice(1).forEach(p=>p.x=12);step(g,50);assert.equal(g.phase,'result');assert.deepEqual(g.winnerIds,['p0']);assert.ok(g.finaleUntil-g.lastAt===4600);const d=make();d.players.forEach(p=>p.x=12);step(d,50);assert.equal(d.reason,'draw');assert.equal(d.winnerIds.length,0);assert.ok(d.results.every(p=>p.rank===1))});
test('rings collapse at 45/60/75/85 seconds and complete within 90 seconds',()=>{assert.equal(R.radius523(44999),9);assert.equal(R.radius523(45000),7.5);assert.equal(R.radius523(60000),6);assert.equal(R.radius523(75000),4.5);assert.equal(R.radius523(85000),3);assert.ok(R.radius523(89999)<.21);const g=make();g.elapsed=89950;g.lastAt=g.startAt+g.elapsed;g.players.forEach((p,i)=>{p.x=i*.01;p.y=0});step(g,100);assert.equal(g.phase,'result')});
test('restart pauses unseen fatal time and snapshots hide roster and RNG',()=>{const g=make();R.advanceSumo523(g,90000);assert.ok(g.elapsed<200);const pub=R.publicSumo523(g);assert.equal(pub.seed,undefined);assert.equal(pub.members[0].owned,undefined);assert.equal(pub.players[0].hitIds,undefined);pub.players[0].x=999;assert.notEqual(g.players[0].x,999)});
test('100 AI matches terminate, all seats can win, physics stays finite and events remain bounded',()=>{const wins=[0,0,0,0];let draws=0,seconds=0,maxHits=0;for(let seed=1;seed<=100;seed++){const g=make(1,seed);const auto=new Set(['p0']);for(let t=3050;t<=96000&&g.phase==='play';t+=50){R.advanceSumo523(g,t,new Map(),auto);assert.ok(g.players.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.power<=24));assert.ok(g.events.length<=40);assert.ok(g.crystals.length<=26)}assert.equal(g.phase,'result');seconds+=g.elapsed/1000;if(!g.winnerIds.length)draws++;else g.winnerIds.forEach(id=>wins[g.players.find(p=>p.playerId===id).seat]++);maxHits=Math.max(maxHits,g.players.reduce((n,p)=>n+p.hits,0))}assert.ok(wins.every(v=>v>0));console.log('SUMO_AI_523',JSON.stringify({matches:100,wins,draws,meanSeconds:seconds/100,maxHits}))});
// Only inherited missing modules are fixtures; no production replacement files are written.
const fixtures={
 [new URL('../src/ui/MonsterVisual.js',import.meta.url).href]:`export const monsterVisual=()=>'<i class="test-sprite"></i>';export const setMonsterVisualFrame=()=>{};`,
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hooks=registerHooks({resolve(spec,c,next){const url=spec.startsWith('.')?new URL(spec,c.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,c)},load(url,c,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,c)}});
const {RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');
const {queueSumo523,liveSumo523}=await import('../online-server/src/SumoCoordinator523.js');
const {PARTY_GAMES462}=await import('../src/party/PartyGames462.js');
const {sumoView523,sumoAfter523,sumoBefore523,sumoDispose523,sumoFrame523}=await import('../src/sumo/View523.js');
function server(n=4){let now=10000;const sent=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true}]));const c=new RaceCoordinator451({sessions,now:()=>now,send:(id,m)=>sent.push({id,m})});const call=(i,op,payload={})=>c.handle(sessions.get('p'+i),{op,rulesVersion:18,sumoVersion523:1,towerVersion517:4,...payload});call(0,'partyCreate462',{game:'sumo',roster:[{id:'m0',speciesId:'slime'}]});const party=Object.values(c.data.parties462)[0];for(let i=1;i<n;i++)call(i,'partyJoin462',{code:party.code,roster:[{id:'m'+i,speciesId:'slime'}]});const g=()=>c.data.sumoRooms523[party.code];for(let i=0;i<n;i++){call(i,'sumo523',{gameId:g().id,kind:'select',monsterId:'m'+i});call(i,'partyReady462',{ready:true})}return{c,call,sent,party,g,advance:ms=>{for(let end=now+ms;now<end;){now+=50;c.advanceSumo523()}}}}
test('party creation/selection/readiness/start routes into sumo with old catalog intact',()=>{const s=server();s.call(1,'sumo523',{gameId:s.g().id,kind:'start'});assert.equal(s.g().phase,'lobby');s.call(0,'sumo523',{gameId:s.g().id,kind:'start'});s.advance(3100);assert.equal(s.c.view(s.c.sessions.get('p0')).sumo.phase,'play');assert.equal(s.c.view(s.c.sessions.get('p0')).room,null);assert.equal(s.c.view(s.c.sessions.get('p0')).tower,null);assert.ok(s.c.active('p0'));assert.deepEqual(PARTY_GAMES462.filter(x=>x.id!=='sumo'&&x.id!=='fishing').map(x=>x.id),['tower','quiz','luck','gorilla','canal','cabbage','race','sugoroku'])});
test('input rejects missing protocol, spectators, stale ids, forged coordinates and sequences',()=>{const s=server(1);s.call(0,'sumo523',{gameId:s.g().id,kind:'start'});s.advance(3100);const packet={gameId:s.g().id,kind:'move',sumoVersion523:1,seq:1,x:1,y:0},session=s.c.sessions.get('p0');assert.equal(queueSumo523(s.c,session,{...packet,sumoVersion523:0}),false);assert.equal(queueSumo523(s.c,{playerId:'intruder'},packet),false);assert.equal(queueSumo523(s.c,session,{...packet,x:NaN}),false);assert.equal(queueSumo523(s.c,session,{...packet,x:2}),false);assert.equal(queueSumo523(s.c,session,{...packet,gameId:'old'}),false);assert.ok(queueSumo523(s.c,session,packet));assert.equal(queueSumo523(s.c,session,packet),false)});
test('same-millisecond move/press/release packets merge; timeout cancels held input without firing',()=>{const s=server(1);s.call(0,'sumo523',{gameId:s.g().id,kind:'start'});s.advance(3100);const session=s.c.sessions.get('p0'),base={gameId:s.g().id,kind:'move',sumoVersion523:1,x:0,y:0};for(const [seq,extra]of[[1,{x:1}],[2,{press:true}],[3,{release:true}]])assert.ok(queueSumo523(s.c,session,{...base,...extra,seq}));const inp=s.c.sumoRuntime523.get(s.g().id).inputs.get('p0');assert.ok(inp.press&&inp.release);assert.ok(queueSumo523(s.c,session,{...base,seq:4,press:true,cancel:true}));s.advance(450);const p=liveSumo523(s.c,s.g()).players[0];assert.equal(p.charging,false);assert.equal(p.attackSerial,0)});
test('disconnect/home AI takeover and reconnect return control without persistent writes per input',()=>{const s=server(1);s.call(0,'sumo523',{gameId:s.g().id,kind:'start'});s.advance(3100);s.c.sessions.get('p0').connected=false;s.advance(100);assert.ok(liveSumo523(s.c,s.g()).players[0].auto);s.c.sessions.get('p0').connected=true;s.advance(100);assert.equal(liveSumo523(s.c,s.g()).players[0].auto,false);const rev=s.c.data.revision;for(let seq=1;seq<20;seq++)queueSumo523(s.c,s.c.sessions.get('p0'),{gameId:s.g().id,kind:'move',sumoVersion523:1,seq,x:0,y:0});assert.equal(s.c.data.revision,rev)});
test('frames stay party-scoped and replay/list clears only the completed sumo runtime',()=>{const s=server(1);s.c.sessions.set('other',{playerId:'other',connected:true});s.c.subscribers.add('other');s.call(0,'sumo523',{gameId:s.g().id,kind:'start'});s.advance(3100);s.sent.length=0;s.advance(200);assert.ok(s.sent.some(x=>x.m.type==='sumoFrame523'));assert.ok(s.sent.every(x=>x.id==='p0'));const g=liveSumo523(s.c,s.g());g.players.slice(1).forEach(p=>p.alive=false);R.finishSumo523(g);s.advance(50);s.call(0,'partyResult490',{partyId:s.party.id,gameId:g.id,kind:'again'});assert.equal(s.g().phase,'lobby');assert.notEqual(s.g().id,g.id);assert.equal(s.c.sumoRuntime523.has(g.id),false)});
test('old clients cannot ready/start sumo; owned-character validation is enforced',()=>{const s=server(1);s.call(0,'sumo523',{gameId:s.g().id,kind:'select',monsterId:'fake'});assert.equal(s.g().members[0].choice.id,'m0');s.call(0,'sumo523',{gameId:s.g().id,kind:'start',sumoVersion523:0});assert.equal(s.g().phase,'lobby');assert.ok(s.sent.some(x=>String(x.m.message).includes('Build523')))});
hooks.deregister();
// Native Canvas + DOM/event fixtures exercise the shipped code; this is not a real browser.
function viewFixture(g=make(),self='p0'){
 const{createCanvas}=createRequire(import.meta.url)('@napi-rs/canvas'),saved={},rafs=new Map(),elements=new Map(),listeners=new Map(),packets=[];let rid=0,time=1000;
 const element=()=>({style:{setProperty(k,v){this[k]=v}},dataset:{},attrs:{},classList:{toggle(){},add(){},remove(){}},hidden:false,disabled:false,events:new Map(),textContent:'',scrollTop:0,setAttribute(k,v){this.attrs[k]=v},getAttribute(k){return this.attrs[k]},addEventListener(k,f,o){this.events.set(k,f);o?.signal?.addEventListener('abort',()=>this.events.delete(k))},removeEventListener(k){this.events.delete(k)},setPointerCapture(){},contains(){return true},getBoundingClientRect(){return{left:0,top:0,width:124,height:124}}});
 const root=element();root.querySelector=key=>{if(!elements.has(key)){const el=key==='[data-sm-canvas]'?createCanvas(390,460):element();el.clientWidth=390;el.clientHeight=460;el.querySelector=s=>{el.children??={};return el.children[s]??=element()};elements.set(key,el)}return elements.get(key)};
 for(const k of['document','window','ResizeObserver','requestAnimationFrame','cancelAnimationFrame','matchMedia','devicePixelRatio','performance'])saved[k]=globalThis[k];globalThis.document={hidden:false,createElement:()=>createCanvas(1,1),querySelector:()=>null,addEventListener(k,f,o){listeners.set(k,f);o?.signal?.addEventListener('abort',()=>listeners.delete(k))},removeEventListener:k=>listeners.delete(k)};globalThis.window=element();globalThis.ResizeObserver=class{observe(){}disconnect(){}};globalThis.requestAnimationFrame=f=>{rafs.set(++rid,f);return rid};globalThis.cancelAnimationFrame=id=>rafs.delete(id);globalThis.matchMedia=()=>({matches:false});globalThis.devicePixelRatio=3;globalThis.performance={now:()=>time};
 const c={state:{sumo:R.publicSumo523(g),party:{id:'party',game:'sumo',hostId:'p0',members:g.members.map(m=>({...m,ready:true,connected:true}))}},transport:{selfId:self},offset:g.lastAt-Date.now(),root:{querySelector:s=>s==='.sm-play523'?root:null},roster:()=>[{id:'m0',speciesId:'slime'}],sgMonster463:()=>'<span class="sg-monster"></span>',sgSpeciesName463:id=>id,connected:()=>true,ready:()=>true,error:'',raw(op,p){packets.push({op,...p});return true},render(){c.renders=(c.renders??0)+1},refresh(){}};
 sumoView523(c);return{c,root,rafs,elements,listeners,packets,flush(ms=16){time+=ms;const f=[...rafs.values()];rafs.clear();f.forEach(fn=>fn())},restore(){sumoDispose523(c);for(const[k,v]of Object.entries(saved)){if(v===undefined)delete globalThis[k];else globalThis[k]=v}}};
}
const pointer=(pointerId,x=120,y=62)=>({pointerId,clientX:x,clientY:y,preventDefault(){}});
test('actual sumo view mounts one RAF, caps DPR, reuses DOM on frames and stops hidden/after disposal',()=>{const d=viewFixture();try{sumoAfter523(d.c);const u=d.c.sumoUI523;assert.equal(d.rafs.size,1);assert.equal(u.renderer.dpr,1.5);let queries=0;const q=d.root.querySelector;d.root.querySelector=(...args)=>{queries++;return q(...args)};for(let i=0;i<12;i++)d.flush();assert.equal(queries,0);assert.equal(d.rafs.size,1);assert.equal(d.c.renders,undefined);document.hidden=true;d.listeners.get('visibilitychange')();assert.equal(d.rafs.size,0);assert.equal(d.packets.at(-1).cancel,true);sumoBefore523(d.c);assert.equal(u.renderer,null);assert.equal(d.root.events.has('contextmenu'),false)}finally{d.restore()}});
test('two-thumb movement and charge/release stay independent; cancellation and blur never fire',()=>{const d=viewFixture();try{sumoAfter523(d.c);const pad=d.elements.get('[data-sm-pad]'),shot=d.elements.get('[data-sm-shot]'),u=d.c.sumoUI523;pad.events.get('pointerdown')(pointer(1));shot.events.get('pointerdown')(pointer(2));assert.equal(u.input.x,1);assert.ok(d.packets.at(-1).press);d.flush(140);shot.events.get('pointerup')(pointer(2));assert.ok(d.packets.at(-1).release);assert.equal(d.packets.at(-1).x,1);pad.events.get('pointercancel')(pointer(1));assert.equal(d.packets.at(-1).x,0);shot.events.get('pointerdown')(pointer(3));shot.events.get('pointercancel')(pointer(3));assert.ok(d.packets.at(-1).cancel);assert.equal(d.packets.at(-1).release,false);window.events.get('blur')();assert.ok(d.packets.at(-1).cancel);assert.equal(u.input.x,0)}finally{d.restore()}});
test('direction pad normalizes diagonals, avoids layout on moves and releases pointer ownership correctly',()=>{const d=viewFixture();try{sumoAfter523(d.c);const p=d.elements.get('[data-sm-pad]'),u=d.c.sumoUI523;let reads=0;const bounds=p.getBoundingClientRect;p.getBoundingClientRect=()=>{reads++;return bounds()};p.events.get('pointerdown')(pointer(1,120,5));assert.ok(Math.abs(Math.hypot(u.input.x,u.input.y)-1)<1e-9);for(let i=0;i<50;i++)p.events.get('pointermove')(pointer(1,120,5));assert.equal(reads,1);p.events.get('pointerdown')(pointer(2,1,62));assert.equal(u.input.x,-1);p.events.get('pointerup')(pointer(2));assert.ok(u.input.x>0);p.events.get('lostpointercapture')(pointer(1));assert.equal(u.input.x,0);assert.equal(u.input.y,0)}finally{d.restore()}});
test('disabled keyboard charge cannot retain ownership or interfere with a later touch release',()=>{const d=viewFixture();try{sumoAfter523(d.c);const s=d.elements.get('[data-sm-shot]'),u=d.c.sumoUI523;s.disabled=true;u.controls.keydown({key:' ',preventDefault(){}});s.disabled=false;s.events.get('pointerdown')(pointer(1));s.events.get('pointerup')(pointer(1));assert.ok(d.packets.at(-1).release);assert.equal(d.packets.filter(p=>p.press).length,1)}finally{d.restore()}});
test('copy/select/drag gestures are suppressed on sumo controls only',()=>{const d=viewFixture();try{sumoAfter523(d.c);for(const type of['contextmenu','selectstart','dragstart','touchstart','touchmove','touchend']){let count=0;const f=d.root.events.get(type);f({target:{closest:()=>true},preventDefault(){count++}});f({target:{closest:()=>null},preventDefault(){count++}});assert.equal(count,1)}}finally{d.restore()}});
test('stale or foreign frames cannot replace state; acknowledged direction and release remain predictable',()=>{const d=viewFixture();try{sumoAfter523(d.c);const g=d.c.state.sumo,pad=d.elements.get('[data-sm-pad]');for(const m of[{selfId:'other',sumo:g},{selfId:'p0',sumo:{...g,id:'other'}},{selfId:'p0',sumo:{...g,serverAt:g.serverAt-1}}]){sumoFrame523(d.c,m);assert.equal(d.c.state.sumo,g)}pad.events.get('pointerdown')(pointer(1));const seq=d.packets.at(-1).seq,f=structuredClone(g);f.serverAt+=10;f.players[0].lastSeq=seq;sumoFrame523(d.c,{selfId:'p0',serverNow:f.serverAt,sumo:f});d.flush(35);const u=d.c.sumoUI523;assert.ok(u.pred.players[0].x>f.players[0].x);pad.events.get('pointerup')(pointer(1));const x=u.pred.players[0].x;d.flush(35);assert.equal(u.pred.players[0].x,x)}finally{d.restore()}});
test('victory remains on arena for 4.6 seconds before results and replay controls',()=>{const g=make();g.players.slice(1).forEach(p=>p.alive=false);R.finishSumo523(g);const d=viewFixture(g);try{assert.match(sumoView523(d.c),/sm-finale523/);assert.doesNotMatch(sumoView523(d.c),/sm-resultrow523/);sumoAfter523(d.c);d.c.offset=g.finaleUntil+100-Date.now();const html=sumoView523(d.c);assert.match(html,/sm-resultrow523/);assert.match(html,/data-party-result490="again"/);d.flush();assert.equal(d.c.renders,1)}finally{d.restore()}});
test('character selection remount preserves nested roster, host, ancestor and window scroll',()=>{const d=viewFixture();const oldY=globalThis.scrollY,oldTo=globalThis.scrollTo;try{d.c.state.sumo.phase='lobby';const list={scrollTop:80},lobby={querySelector:()=>list},parent={scrollTop:450};d.c.root={scrollTop:150,parentElement:parent,querySelector:s=>s==='.sm-lobby523'?lobby:null};globalThis.scrollY=100;globalThis.scrollTo=(x,y)=>globalThis.scrollY=y;sumoBefore523(d.c);list.scrollTop=0;parent.scrollTop=0;d.c.root.scrollTop=0;globalThis.scrollY=0;sumoAfter523(d.c);d.flush();assert.equal(list.scrollTop,80);assert.equal(parent.scrollTop,450);assert.equal(d.c.root.scrollTop,150);assert.equal(globalThis.scrollY,100)}finally{d.restore();globalThis.scrollY=oldY;globalThis.scrollTo=oldTo}});
test('native Canvas renderer preserves floor/background caches for stationary-size frames and fits 320–430 widths',async()=>{const{createRenderer523,resize523,paint523,project523}=await import('../src/sumo/Renderer523.js');const d=viewFixture();try{const{createCanvas}=createRequire(import.meta.url)('@napi-rs/canvas'),g=make();for(const[w,h]of[[320,280],[375,420],[390,460],[430,620]]){const r=createRenderer523(createCanvas(w,h));resize523(r,w,h,3);paint523(r,R.publicSumo523(g),g.players,g.lastAt);const cache=r.floor.toBuffer('image/png');resize523(r,w,h,3);paint523(r,R.publicSumo523(g),g.players,g.lastAt+200);assert.deepEqual(r.floor.toBuffer('image/png'),cache);assert.equal(r.dpr,1.5);assert.ok(project523(r,-9,0).x>=10);assert.ok(project523(r,9,0).x<w-10);assert.ok(project523(r,0,-9).y>0);assert.ok(project523(r,0,9).y<h)}}finally{d.restore()}});
