import {pairVm409} from './helpers/pair409-vm.mjs';
import {previewRelicRefine395,refineChapterTwoRelics395} from '../src/chapterTwo/ChapterTwoRefining395.js';
import {relicRefinePrice394,relicRefineCandidates394,refineChapterTwoRelic394} from '../src/chapterTwo/ChapterTwoRefining394.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import * as C from '../src/chapterTwo/ChapterTwoSystem.js';
import {CHAPTER_TWO_RELICS394 as relics,CHAPTER_TWO_CIRCLES394 as circles,relicItemText394} from '../src/data/chapterTwoRelics394.js';
import {createChapterTwoRelic394} from '../src/chapterTwo/ChapterTwoRewards394.js';
import {aggregateRelics394,relicDamageMultiplier394,relicIncomingMultiplier394} from '../src/battle/ChapterTwoRelicCombat394.js';
import {applyEnemyDamage,processEnemyStatuses} from '../src/battle/BattleRules.js';
import {equipmentAffixesWithSeries} from '../src/core/EquipmentAffixSystem.js';
import {MAGIC_CIRCLES,magicCircleLevelEffect,normalizeMagicCircleState,createMagicCircleInstance,equipMagicCircle,buyOrUpgradeMagicCircle,equippedMagicCircle,rollEnemyMagicCircle} from '../src/core/MagicCircleSystem.js';
import {chapterTwoElitePanel393} from '../src/chapterTwo/ChapterTwoElitePanel393.js';
import {relicLoadout394,relicRewardMarkup394} from '../src/ui/ChapterTwoRelics394.js';
import {FormationScreen} from '../src/ui/screens/FormationScreen.js';
import {createMonster,calculatedStats} from '../src/models/Monster.js';
import {SaveService} from '../src/services/SaveService.js';
const main=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
function fixture(area=0){const mem=new Map();globalThis.localStorage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};const save=new SaveService(),s=save.state;s.player.maxFloor=100;s.campaign100.finalCompleted=true;const p=C.chapterTwoState(s);p.introComplete=true;for(let a=0;a<5;a++){p.areaClears378[a]=1;C.beginChapterTwoRun(s,{area:a});p.run.defeated=C.CHAPTER_TWO_AREAS[a].keys.slice();C.chapterTwoState(s);}p.run=p.runs378[area];return{save,s,p,r:p.run};}
function battle(){const a={id:'a',speciesId:'ch2_ryune',currentHp:1000,equipment:{},_chapterTwoRelics394:{}},partner={id:'b',speciesId:'ch2_rose',currentHp:1000},e={id:'e',hp:10000,maxHp:10000},f={id:'f',hp:10000,maxHp:10000};return{party:[a,partner],enemies:[e,f],turn:1,enemyStatuses:{},enemyEffects:{},allyEffects:{},guards:{},magicCircleProfiles:{}};}
const item=(index,plus=12)=>{const i=createChapterTwoRelic394(relics[index],1000,1);i.plus=plus;return i;};
const hit=(b,source=b.party[0],target=b.enemies[0],options={})=>applyEnemyDamage(b,target,100,{sourceId:source.id,damageClass:'physical',...options});

test('15 squad-specific relics and five regional circles are outside generic equipment and enemy circle rolls',()=>{
 assert.equal(relics.length,15);assert.equal(new Set(relics.map(r=>r.encounter)).size,15);assert.equal(circles.length,5);assert.equal(MAGIC_CIRCLES[0].id,'none');
 for(const r of relics){assert.ok(C.ENCOUNTERS[r.encounter].elite393);assert.equal(C.ENCOUNTERS[r.encounter].area,r.area);assert.equal(C.ENCOUNTERS[r.encounter].room,r.room);assert.ok(r.hint.length>15);assert.ok(Object.values(r.effects).every(v=>v>0));}
 for(let i=0;i<=100;i++)assert.ok(!circles.some(c=>c.id===rollEnemyMagicCircle(9999,{force:true,random:()=>i/101}).id));
 for(const c of circles){assert.ok(fs.existsSync(new URL('../'+c.asset,import.meta.url)));const svg=fs.readFileSync(new URL('../'+c.asset,import.meta.url),'utf8');assert.match(svg,/viewBox="0 0 512 512"/);assert.doesNotMatch(svg,/<script|<foreignObject|https?:\/\/(?!www.w3.org)/);}
});
test('all 45 elite victories pay the authored item, all 15 sweeps grant the right circle and preserve the prior bonus',()=>{
 for(let area=0;area<5;area++){const {s}=fixture(area);for(let tier=1;tier<=3;tier++){assert.ok(C.beginChapterTwoElite393(s,area,tier).ok);for(const room of [1,3,4]){const r=C.chapterTwoState(s).run;r.room=room;const a=C.beginChapterTwoEncounter(s,`roam${area}_${room}`),result=C.settleChapterTwoEncounter(s,a.token,{won:true}),spoils=result.spoils394,def=relics.find(d=>d.area===area&&d.room===room);assert.equal(spoils.relic.definition,def.id);assert.equal(spoils.relic.rarity,tier===1?'LR':'神話');assert.equal(spoils.relic.plus,[0,12,18,24][tier]);assert.equal(!!spoils.circle,room===4);assert.equal(!!result.equipment,room===4);if(room===4){assert.equal(spoils.circle.id,circles[area].id);assert.equal(spoils.circle.level,[0,5,15,30][tier]);assert.ok(s.magicCircles.unlocked[spoils.circle.id]);}const count=s.equipment.length;assert.equal(C.settleChapterTwoEncounter(s,a.token,{won:true}).ok,false);assert.equal(s.equipment.length,count);assert.match(relicRewardMarkup394(spoils),new RegExp(def.name));}}}
});
test('ordinary encounters and defeat do not grant new trophies; full storage never sells a trophy',()=>{
 const {s,r}=fixture();r.room=1;let a=C.beginChapterTwoEncounter(s,'roam0_1');assert.equal(C.settleChapterTwoEncounter(s,a.token,{won:true}).spoils394,null);
 C.beginChapterTwoElite393(s,0);r.room=1;a=C.beginChapterTwoEncounter(s,'roam0_1');const count=s.equipment.length;C.settleChapterTwoEncounter(s,a.token,{won:false});assert.equal(s.equipment.length,count);
 s.equipment=Array.from({length:500},()=>({}));s.reserveEquipment=Array.from({length:30},()=>({}));a=C.beginChapterTwoEncounter(s,'roam0_1');const result=C.settleChapterTwoEncounter(s,a.token,{won:true});assert.equal(s.bossEquipmentVault.at(-1).chapterTwoRelic394,relics[0].id);assert.match(result.spoils394.relic.receipt,/王装保管庫/);
});
test('failed victory save rolls back both new rewards and unlock, then one retry survives a full reload',()=>{
 const {save,s}=fixture();C.beginChapterTwoElite393(s,0);for(const room of [1,3]){C.chapterTwoState(s).run.room=room;const a=C.beginChapterTwoEncounter(s,`roam0_${room}`);C.settleChapterTwoEncounter(s,a.token,{won:true});}C.chapterTwoState(s).run.room=4;const a=C.beginChapterTwoEncounter(s,'roam0_4');const before=JSON.stringify({gear:s.equipment,circles:s.magicCircles});const original=save.save.bind(save);save.save=()=>false;
 const scope={save,game:null,showToast(){}};vm.createContext(Object.assign(scope,{...pairVm409,...scope}));vm.runInContext(main.slice(main.indexOf('function chapterTwoCommit('),main.indexOf('let chapterTwoIntroTimer=')),scope);assert.equal(scope.chapterTwoCommit(()=>C.settleChapterTwoEncounter(save.state,a.token,{won:true})).saveFailed,true);assert.equal(JSON.stringify({gear:save.state.equipment,circles:save.state.magicCircles}),before);assert.equal(C.chapterTwoState(save.state).run.pending.token,a.token);
 save.save=original;assert.ok(scope.chapterTwoCommit(()=>C.settleChapterTwoEncounter(save.state,a.token,{won:true})).ok);const loaded=new SaveService();assert.ok(loaded.state.equipment.some(i=>i.chapterTwoRelic394===relics[2].id));assert.ok(loaded.state.magicCircles.instances.some(i=>i.circleId===circles[0].id));assert.equal(C.settleChapterTwoEncounter(loaded.state,a.token,{won:true}).ok,false);
});
test('relic plus growth is capped; duplicate authorities use the strongest copy, including fixed generic bonuses',()=>{
 const weak=item(1,0),strong=item(1,30),overflow=item(1,99999),a=aggregateRelics394([weak,strong]);assert.deepEqual(a,aggregateRelics394([strong]));assert.deepEqual(a,aggregateRelics394([overflow]));assert.equal(a.chain,.2);assert.equal(aggregateRelics394([strong],.5).chain,.1);
 const flowers=item(2);flowers.affixes=[];assert.equal(equipmentAffixesWithSeries([flowers,{...flowers,id:'duplicate'}],{}).healPower,12);assert.match(relicItemText394(strong),/20%/);assert.match(relicItemText394(weak),/16%/);
});
test('sleep, poison, burn, freeze, general ailments, enemy buffs and execution check current target state',()=>{
 for(const [index,status] of [[2,'poison'],[3,'poison'],[4,'sleep'],[5,'burn'],[6,'curse'],[11,'freeze']]){const b=battle(),a=b.party[0],e=b.enemies[0];a._chapterTwoRelics394=aggregateRelics394([item(index)]);assert.equal(hit(b).damage,100);b.enemyStatuses.e=[{id:status,turns:1}];assert.ok(hit(b).damage>100);b.enemyStatuses.e[0].turns=0;assert.equal(hit(b).damage,100);}
 const b=battle();b.party[0]._chapterTwoRelics394=aggregateRelics394([item(8)]);b.enemyEffects.e=[{kind:'atkUp',turns:1}];assert.ok(hit(b).damage>100);b.enemyEffects.e=[];assert.equal(hit(b).damage,100);b.party[0]._chapterTwoRelics394=aggregateRelics394([item(13)]);b.enemies[0].hp=3501;assert.equal(hit(b).damage,100);assert.ok(hit(b).damage>100);
});
test('successful same-target hits enable chain, shields and periodic damage do not, and resume preserves the round',()=>{
 const b=battle(),a=b.party[0],e=b.enemies[0];a._chapterTwoRelics394=aggregateRelics394([item(1)]);e._floorBossHpShield=1000;assert.equal(hit(b).damage,0);delete e._floorBossHpShield;assert.equal(hit(b).damage,100);assert.ok(hit(b).damage>100);assert.equal(hit(b,a,b.enemies[1]).damage,100);
 const resumed=JSON.parse(JSON.stringify(b));assert.ok(hit(resumed).damage>100);resumed.turn++;assert.equal(hit(resumed).damage,100);
 const periodic=battle();periodic.party[0]._chapterTwoRelics394=a._chapterTwoRelics394;periodic.enemyStatuses.e=[{id:'poison',turns:2,power:.01,sourceMonsterId:'a'}];processEnemyStatuses(periodic);assert.equal(periodic.enemies[0].hp,9900);assert.equal(hit(periodic).damage,100);
 assert.ok(main.includes('relicHits394:battle.relicHits394??null'));assert.ok(main.includes('battle={...data,'));
});
test('circle and equipment bonuses multiply once; percentage and echo damage stay excluded',()=>{
 const b=battle();b.party[0]._chapterTwoRelics394=aggregateRelics394([item(4,0)]);b.magicCircleProfiles.a={id:circles[1].id,level:99};b.enemyStatuses.e=[{id:'sleep',turns:1}];assert.equal(hit(b).damage,198);assert.equal(hit(b,undefined,undefined,{relicKind394:'excluded'}).damage,100);assert.equal(hit(b,undefined,undefined,{damageClass:null}).damage,100);
 assert.match(main,/percentDamage,\{[^\n]*relicKind394:"excluded"/);assert.match(main,/damageClass:echo.damageClass\?\?"physical",relicKind394:"excluded"/);
});
test('pair bonuses require an actual living partner and only affect pair damage; counter boosts require counter tags',()=>{
 const b=battle(),a=b.party[0];a._chapterTwoRelics394=aggregateRelics394([item(0,0)]);b.magicCircleProfiles.a={id:circles[2].id,level:99};assert.equal(hit(b).damage,100);assert.equal(hit(b,undefined,undefined,{relicKind394:'pair'}).damage,159);b.party[1].currentHp=0;assert.equal(hit(b,undefined,undefined,{relicKind394:'pair'}).damage,100);b.party[1].currentHp=1;b.party[1].captured=true;assert.equal(hit(b,undefined,undefined,{relicKind394:'pair'}).damage,100);
 a._chapterTwoRelics394=aggregateRelics394([item(10,0)]);b.magicCircleProfiles={};assert.equal(hit(b).damage,100);assert.equal(hit(b,undefined,undefined,{relicKind394:'counter'}).damage,130);assert.match(main,/relicKind394:pair.reaction390\?"pairCounter":"pair"/);
});
test('guard reduction combines gear and circle, expires with guard, and never gives passive immunity',()=>{
 const b=battle(),a=b.party[0];a._chapterTwoRelics394=aggregateRelics394([item(7,0),item(10,0)]);b.magicCircleProfiles.a={id:circles[3].id,level:99};assert.equal(relicIncomingMultiplier394(b,a),1);b.guards.a=true;assert.ok(Math.abs(relicIncomingMultiplier394(b,a)-.608)<1e-9);b.guards.a=false;b.allyEffects.a=[{kind:'guard',turns:1}];assert.ok(relicIncomingMultiplier394(b,a)<1);b.allyEffects.a[0].turns=0;assert.equal(relicIncomingMultiplier394(b,a),1);
});
test('new circle growth is real and bounded, with separate instances and the existing gold upgrade path',()=>{
 const {s}=fixture();s.player.gold=1e12;const a=createMonster('ch2_ryune',{level:1500}),b=createMonster('ch2_rose',{level:1500});s.monsters=[a,b];s.party=[a.id,b.id];for(const c of circles){const l1=magicCircleLevelEffect(c.id,1),l99=magicCircleLevelEffect(c.id,99);assert.notEqual(l1.summary,l99.summary);assert.deepEqual(magicCircleLevelEffect(c.id,999),l99);normalizeMagicCircleState(s);s.magicCircles.unlocked[c.id]=true;const first=createMagicCircleInstance(s,c.id,{level:5}),second=createMagicCircleInstance(s,c.id,{level:15});assert.ok(equipMagicCircle(s,a,first.instanceId).ok);assert.equal(equipMagicCircle(s,b,first.instanceId).ok,false);assert.ok(equipMagicCircle(s,b,second.instanceId).ok);assert.equal(equippedMagicCircle(a,s).level,5);const before=s.player.gold,upgrade=buyOrUpgradeMagicCircle(s,first.instanceId);assert.ok(upgrade.ok);assert.equal(upgrade.level,6);assert.equal(s.player.gold,before-upgrade.price);assert.equal(equippedMagicCircle(b,s).level,15);}
});
test('formation derives current gear and circle effects, explains missing partner, and updates immediately on unequip',()=>{
 const {s}=fixture(),a=createMonster('ch2_ryune',{level:1500}),b=createMonster('ch2_rose',{level:1500}),gear=item(0);s.monsters=[a,b];s.party=[a.id];s.equipment=[gear];a.equipment={weaponRight:gear.id};let html=relicLoadout394(s,a);assert.match(html,/ロゼを同じ部隊/);s.party.push(b.id);assert.match(relicLoadout394(s,a),/相方を編成済み/);assert.match(FormationScreen(s),/第二章装備・魔法陣の組み合わせ/);a.equipment={};assert.equal(relicLoadout394(s,a),'');
 for(let area=0;area<5;area++){const {s}=fixture(area),html=chapterTwoElitePanel393(s,area);for(const r of relics.filter(r=>r.area===area))assert.ok(html.includes(r.name));assert.ok(html.includes(circles[area].name));assert.match(html,/確定入手/);}
});

test('actual enemy-hit function applies relic guard before shields and preserves the existing damage path',async()=>{
 async function damage(equipped){const b=battle(),a=b.party[0],e=b.enemies[0];b.guards.a=true;Object.assign(e,{atk:100,matk:100,def:0,crit:0});if(equipped){a._chapterTwoRelics394=aggregateRelics394([item(7,0)]);b.magicCircleProfiles.a={id:circles[3].id,level:1};}
 const c={battle:b,relicIncomingMultiplier394,ultimateIsolated:()=>false,ultimateExtraBlocked:()=>false,beginUltimateAction(){},calculatedStats:()=>({hp:1000,atk:10,def:0,mdef:0,evasion:0}),hasCircleEffect:()=>false,circleEffectNumber:()=>0,hasEffect:()=>false,effectValue:()=>0,syncInvincibleAllianceState(){},attackHits:()=>true,signatureResonance:()=>null,allyAilment:()=>null,affixValue:()=>0,elementalResistance:()=>0,SPECIES:{},enemyAttackFactor:()=>1,allyDefenseFactor:()=>1,enemyDamageAfterDefense:a=>a,attributeDamageMultiplier:()=>1,abyssBattleMultiplier:()=>1,absorbSignatureShield:(_u,d)=>d,absorbMagicCircleShield:(_u,d)=>d,mitigateHeroDamage:(_b,_s,_u,d)=>d,tryHeroLastStand(){},recordBattleTaken(){},tryUnyielding:()=>false,addBattleLog(){},displayName:()=>'',flushMagicCircleEvents:async()=>{},animateHit:async()=>{},floatText:async()=>{},queuePairCounter390(){},tryGuardianPassive:async()=>{},flushHeroReactions348:async()=>{}};
 vm.createContext(Object.assign(c,{...pairVm409,...c}));vm.runInContext(main.slice(main.indexOf('async function dealEnemyHit('),main.indexOf('function floorBossDomainActionMultiplier(')),c);return c.dealEnemyHit(e,a,1,'',0);}
 assert.equal(await damage(false),45);assert.equal(await damage(true),35);
});
test('real battle checkpoint writes the chain counter, and SaveService reload keeps it without resetting a pending fight',()=>{
 const {s,save}=fixture();const a=createMonster('ch2_ryune',{level:1500}),partner=createMonster('ch2_rose',{level:1500});a.currentHp=calculatedStats(a).hp;partner.currentHp=calculatedStats(partner).hp;s.monsters=[a,partner];s.party=[a.id,partner.id];C.beginChapterTwoElite393(s,0);C.chapterTwoState(s).run.room=1;const pending=C.beginChapterTwoEncounter(s,'roam0_1'),b=battle();b.party=[a,partner];a._chapterTwoRelics394=aggregateRelics394([item(1)]);b.enemies.forEach(e=>e.speciesId='ch2_ryune');Object.assign(b,{specialBattle:true,specialBattleType:'chapterTwo',chapterTwoToken:pending.token,chapterTwoEncounter:pending.encounter});hit(b,a);assert.ok(hit(b,a).damage>100);
 b.pairSynergy409=pairVm409.createPairState409({version:1,used:{'ally:mirrors':{round:1,count:1}},marks:{'ally:mirrors':{round:1,targets:{ch2_ryune:'e'}}}});
 const c={save,battle:b,sanitizeBattleParty(){},syncPersistentAilments(){}};vm.createContext(Object.assign(c,{...pairVm409,...c}));vm.runInContext(main.slice(main.indexOf('function saveBattleCheckpoint('),main.indexOf('function clearBattleCheckpoint(')),c);c.saveBattleCheckpoint();const loaded=new SaveService();assert.deepEqual(loaded.state.activeBattle.relicHits394,b.relicHits394);assert.deepEqual(loaded.state.activeBattle.pairSynergy409,pairVm409.snapshotPairs409(b));assert.equal(C.chapterTwoState(loaded.state).run.pending.token,pending.token);
});

test('relic refining consumes exactly one chosen unprotected duplicate and gold, preserves level/affixes, and stops at 30',()=>{
 const {s}=fixture(),target=item(4,29),material=item(4),unrelated=item(0);material.locked=false;s.equipment=[target,material,unrelated];s.player.gold=1e9;const old={level:target.level,affixes:structuredClone(target.affixes),gold:s.player.gold},price=relicRefinePrice394(target);
 assert.equal(refineChapterTwoRelic394(s,target.id,target.id).ok,false);assert.ok(refineChapterTwoRelic394(s,target.id,material.id).ok);assert.equal(s.player.gold,old.gold-price);assert.equal(target.plus,30);assert.equal(target.level,old.level);assert.deepEqual(target.affixes,old.affixes);assert.equal(s.equipment.length,2);assert.equal(refineChapterTwoRelic394(s,target.id,material.id).ok,false);assert.equal(target.plus,30);
 for(const field of ['locked','favorite','equippedBy']){const t=item(0),m=item(0);m.locked=false;m[field]=true;s.equipment=[t,m];assert.equal(refineChapterTwoRelic394(s,t.id,m.id).ok,false);}const t=item(0),m=item(0);m.locked=false;s.equipment=[t,m];s.player.inRun=true;assert.equal(refineChapterTwoRelic394(s,t.id,m.id).ok,false);s.player.inRun=false;s.player.gold=0;assert.equal(refineChapterTwoRelic394(s,t.id,m.id).ok,false);assert.equal(s.equipment.length,2);
});
test('failed refine save restores material, plus and gold; successful retry is atomic',()=>{
 const {save,s}=fixture(),t=item(12),m=item(12);m.locked=false;s.equipment=[t,m];s.player.gold=1e9;const original=JSON.stringify(s.equipment),gold=s.player.gold,saveFn=save.save.bind(save);save.save=()=>false;const c={save,game:null,showToast(){}};vm.createContext(Object.assign(c,{...pairVm409,...c}));vm.runInContext(main.slice(main.indexOf('function chapterTwoCommit('),main.indexOf('let chapterTwoIntroTimer=')),c);
 assert.equal(c.chapterTwoCommit(()=>refineChapterTwoRelic394(save.state,t.id,m.id)).saveFailed,true);assert.equal(JSON.stringify(save.state.equipment),original);assert.equal(save.state.player.gold,gold);save.save=saveFn;assert.ok(c.chapterTwoCommit(()=>refineChapterTwoRelic394(save.state,t.id,m.id)).ok);const loaded=new SaveService();assert.equal(loaded.state.equipment.find(i=>i.id===t.id).plus,13);assert.equal(loaded.state.equipment.some(i=>i.id===m.id),false);
});
test('refining dialog requires selecting the displayed material and a second press cannot spend twice',()=>{
 const {s}=fixture(),t=item(0),m=item(0);m.locked=false;s.equipment=[t,m];s.player.gold=1e9;let removed=0,rendered=0,html;const primary={},selection={},button={dataset:{relicMaterial:m.id},textContent:m.name,setAttribute(){}},modal={querySelector:q=>q==='[data-modal-primary]'?primary:selection,querySelectorAll:()=>[button],remove(){removed++}};
 const c={escapeAttribute:s=>s,previewRelicRefine395,refineChapterTwoRelics395,save:{state:s},battle:null,relicRefinePrice394,relicRefineCandidates394,refineChapterTwoRelic394,showToast(){},chapterTwoCommit:f=>f(),app:{insertAdjacentHTML(_p,s){html=s}},Modal:(_t,body)=>body,topModal:()=>modal,render(){rendered++}};vm.createContext(Object.assign(c,{...pairVm409,...c}));vm.runInContext(main.slice(main.indexOf('function openRelicRefine394('),main.indexOf('function enhanceEquipment(')),c);c.openRelicRefine394(t.id);assert.equal(primary.disabled,true);primary.onclick();assert.equal(s.equipment.length,2);assert.ok(html.includes(m.name));button.onclick();assert.equal(primary.disabled,false);primary.onclick();primary.onclick();assert.equal(t.plus,13);assert.equal(s.equipment.length,1);assert.equal(removed,1);assert.equal(rendered,1);
});
