import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';
import{COURSES459,course459,coursePoint459,temperament459,appendHistory459,monsterHistory459}from'../src/race/RaceCourse459.js';
import{raceProfile451,RACE451}from'../src/race/RaceRules451.js';
import{createSimulation456,advanceSimulation456,boost456,publicSimulation456,forecastSimulation456}from'../src/race/RaceSimulation456.js';
import{boostPower457}from'../src/race/RaceBoost457.js';
import{RaceCoordinator451}from'../online-server/src/RaceCoordinator451.js';
import{applyRaceDelivery451}from'../src/race/RaceWallet451.js';
import{createMonster}from'../src/models/Monster.js';
const all=Array.from({length:8},(_,i)=>i);
const racers=(distance,bond=0)=>['wolf','slime','goblin','skeleton','ember_gecko','myth_rion','myth_yori','myth_hide'].map(speciesId=>({speciesId,profile:raceProfile451(speciesId),rulesVersion:7,track459:course459(distance),condition:2,fatigue455:0,bond459:bond}));
test('all four courses finish, preserve distance and deterministic restart on turf/sand',()=>{for(const c of COURSES459)for(const ground of['芝','砂']){const rs=racers(c.distance),one=createSimulation456(rs,ground,42),chunks=createSimulation456(rs,ground,42);advanceSimulation456(one,rs,90000,all);for(let time=600;time<=90000;time+=600){advanceSimulation456(chunks,rs,time,all);Object.assign(chunks,JSON.parse(JSON.stringify(chunks)))}assert.equal(one.order.length,8);assert.ok(one.runners.every(x=>x.distance===c.distance&&x.finishMs<90000));assert.deepEqual(chunks,one)}});
test('500m and3000m change winners and odds; course and bond are included in Monte Carlo',()=>{const short=forecastSimulation456(racers(500),'芝',256),long=forecastSimulation456(racers(3000),'芝',256);assert.equal(short.triples.reduce((a,b)=>a+b,0),256);assert.equal(long.triples.reduce((a,b)=>a+b,0),256);assert.notDeepEqual(short.triples,long.triples);const low=racers(1600),high=racers(1600,1000);assert.notDeepEqual(forecastSimulation456(low,'砂',256).triples,forecastSimulation456(high,'砂',256).triples)});
test('oval is continuous, corners exist, two laps return to finish, straight stays straight',()=>{const track=course459(3000);assert.deepEqual(coursePoint459(0,track),coursePoint459(.5,track));assert.deepEqual(coursePoint459(0,track),coursePoint459(1,track));let previous=coursePoint459(0,track),corners=0;for(let i=1;i<=1000;i++){const p=coursePoint459(i/1000,track);assert.ok(Math.hypot(p.x-previous.x,p.y-previous.y)<1);assert.ok(p.x>=-2.01&&p.x<=102.01&&p.y>=23.99&&p.y<=76.01);corners+=p.corner;previous=p}assert.ok(corners>300);assert.equal(coursePoint459(.3,course459(500)).corner,false)});
test('low bond delays only first command600ms, accepts burst, persists, costs once, hides random roll',()=>{assert.deepEqual([temperament459(0).chance,temperament459(200).chance,temperament459(600).chance],[.15,.05,0]);const rs=racers(1000);let s;for(let seed=1;seed<100;seed++){s=createSimulation456(rs,'芝',seed);if(s.runners[0].hesitate459)break}assert.ok(s.runners[0].hesitate459);for(let seq=1;seq<=5;seq++)boost456(s,0,seq);assert.equal(s.runners[0].stamina,50);assert.equal(s.runners[0].pendingBoost459.length,1);assert.equal(s.events.filter(x=>x.type==='hesitate').length,1);assert.equal(boostPower457(s.runners[0],0),1.72);s=JSON.parse(JSON.stringify(s));assert.equal(boost456(s,0,5),false);advanceSimulation456(s,rs,800);assert.equal(s.runners[0].pendingBoost459.length,0);assert.equal(s.events.filter(x=>x.type==='obey').length,1);assert.equal(boostPower457(s.runners[0],800),1.9);assert.throws(()=>boost456(s,0,6));const pub=JSON.stringify(publicSimulation456(s));assert.ok(!/hesitate459|luck|rng/.test(pub));for(let seed=1;seed<=100;seed++)assert.ok(createSimulation456(racers(1000,1000),'芝',seed).runners.every(x=>!x.hesitate459))});
function harness(file){let time=100000;const sessions=new Map([['p0',{playerId:'p0',clientKey:'long-key459',connected:true}],['p1',{playerId:'p1',clientKey:'second-key459',connected:true}]]),errors=[],options={sessions,stateFile:file,now:()=>time,send:(id,m)=>{if(m.type==='raceError451')errors.push(m)}};let c=new RaceCoordinator451(options);return{get c(){return c},errors,call(op,payload={},i=0){c.handle(sessions.get('p'+i),{op,rulesVersion:7,...payload})},view(i=0){return c.view(sessions.get('p'+i))},step(ms){time+=ms;c.advance()},restart(){c=new RaceCoordinator451(options)},create(version=7){this.call('create',{rulesVersion:version,roster:[{id:'pet',speciesId:'slime',bond459:1000}]});this.call('select',{monsterId:'pet'})}}}
test('host distance validation, locked snapshot, history and reward once after restart; legacy unchanged',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'race459-'));try{const h=harness(path.join(dir,'race.json'));h.create();const code=h.view().room.code;h.call('join',{code,roster:[{id:'pet1',speciesId:'wolf',bond459:0}]},1);h.call('select',{monsterId:'pet1'},1);h.call('distance459',{distance:3000},1);assert.equal(h.view().room.track459.distance,1000);h.call('distance459',{distance:999});assert.equal(h.view().room.track459.distance,1000);h.call('distance459',{distance:3000});assert.equal(h.view().room.track459.distance,3000);assert.equal(h.view().room.system[0].condition,null);h.call('start');assert.equal(h.view().room.phase,'parade');const r=h.view().room;assert.equal(r.racers[4].bond459,1000);assert.equal(r.racers[5].bond459,0);assert.equal(r.racers[0].track459.distance,3000);h.call('distance459',{distance:500});assert.equal(h.view().room.track459.distance,3000);h.call('pass');h.call('pass',{},1);h.step(17000);h.step(3000);h.step(10000);h.restart();h.step(90000);assert.equal(h.view().room.phase,'result');const history=h.view().history459;assert.equal(history.length,1);assert.equal(history[0].distance,3000);assert.equal(history[0].place,h.view().room.results[0].place);assert.equal(h.view().deliveries[0].history459.raceId,r.id);h.restart();h.step(1000);assert.deepEqual(h.view().history459,history);const entry=h.view().deliveries[0],save={state:{player:{gold:0},monsters:[createMonster('slime',{id:'pet'})]},save:()=>true};save.state.monsters[0].id='pet';applyRaceDelivery451(save,'server|p0',entry);const after=structuredClone(save.state);assert.equal(applyRaceDelivery451(save,'server|p0',entry).duplicate,true);assert.deepEqual(save.state,after);assert.equal(save.state.race451.accounts['server|p0'].history459.length,1);for(let i=0;i<2;i++)h.call('ack',{ids:h.view(i).deliveries.map(x=>x.id)},i);h.call('again');assert.equal(h.view().room.track459.distance,3000);assert.equal(h.view().history459.length,1);const legacy=harness();legacy.create(6);legacy.call('distance459',{distance:500});assert.equal(legacy.view().room.track459,undefined);legacy.call('start');assert.equal(legacy.view().room.racers[4].bond459,undefined);assert.equal(legacy.view().room.rulesVersion,6)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('history separates same-species individuals, bounds retained records and never duplicates receipts',()=>{let rows=[];for(let i=0;i<35;i++)rows=appendHistory459(rows,{raceId:'r'+i,monsterId:i%2?'a':'b',place:i%8+1});assert.equal(monsterHistory459(rows,'a').length,17);rows=appendHistory459(rows,rows[0]);assert.equal(rows.length,35);for(let i=35;i<400;i++)rows=appendHistory459(rows,{raceId:'r'+i,monsterId:'a',place:1});assert.equal(monsterHistory459(rows,'a').length,20);assert.equal(monsterHistory459(rows,'b').length,18)});
