import test from'node:test';import assert from'node:assert/strict';
import{makeLobby463,start463,action463,public463,settle463}from'../src/sugoroku/Engine463.js';
import{CARDS463}from'../src/sugoroku/Catalog463.js';import{RANKS466}from'../src/sugoroku/CardRanks466.js';import{schedule465}from'../src/sugoroku/Pacing465.js';import{orderedHand466}from'../src/sugoroku/HandOrder466.js';
const game=()=>{const g=makeLobby463({id:'466',seed:73,members:[0,1,2,3].map(i=>({playerId:'p'+i,name:'P'+i}))});start463(g,100);g.step='pre';return g};
function take(g,id){const uid=Object.keys(g.cards).find(u=>g.cards[u]===id);g.deck=g.deck.filter(u=>u!==uid);g.discard=g.discard.filter(u=>u!==uid);for(const p of g.players)p.hand=p.hand.filter(u=>u!==uid);return uid}
function play(g,id){const uid=take(g,id);g.players[0].hand.push(uid);action463(g,'p0',{kind:'play',uid},200)}
function draw(g,ids){const drawn=ids.map(id=>take(g,id));g.deck.push(...drawn.reverse());g.queue.push({type:'draw',actor:'p0',target:'p0',n:ids.length,group:'drawtest',source:'card',cardId:'yori-11'});settle463(g)}
test('all 116 cards have known ranks and concise readable summaries',()=>{assert.equal(CARDS463.length,116);assert.deepEqual(RANKS466,['N','R','SR','SSR','UR','LR','神話','深淵','十神']);for(const c of CARDS463){assert.ok(RANKS466.includes(c.rank466),c.id);assert.ok(c.summary466.length<=22,c.id);assert.ok(c.note466.length<=25,c.id)}assert.ok(CARDS463.find(c=>c.id==='yori-4').rankIndex466>CARDS463.find(c=>c.id==='yori-3').rankIndex466)});
test('two draws interleave instant activation before the second draw',()=>{const g=game();g.discard.push(...g.players[0].hand);g.players[0].hand=[];draw(g,['poison','nothing']);const events=public463(g,'p0').presentation464;assert.deepEqual(events.filter(e=>e.kind==='draw').map(e=>[e.ordinal466,e.total466]),[[1,2],[2,2]]);const first=events.findIndex(e=>e.kind==='draw'),instant=events.findIndex(e=>e.kind==='card'),second=events.findIndex(e=>e.kind==='draw'&&e.ordinal466===2);assert.ok(first<instant&&instant<second);assert.equal(events[instant].activation466,'instant');assert.ok(events.slice(instant,second).some(e=>e.kind==='effect'))});
test('ordinary, curse and set draws remain private for opponents and spectators',()=>{for(const id of ['nothing','curse-heavy','dark-0','face-0']){const g=game();const uid=take(g,id);g.deck.push(uid);g.queue.push({type:'draw',actor:'p0',target:'p0',n:1,source:'turn',group:'secret'});settle463(g);const mine=public463(g,'p0').presentation464.find(e=>e.kind==='draw');assert.equal(mine.drawCardId466,id);for(const who of ['p1','p2','spectator']){const view=public463(g,who);for(const e of view.presentation464){assert.equal(e.private466,undefined);assert.equal(e.privateDraw466,undefined);assert.equal(e.after466?.private466,undefined);assert.equal(e.drawCardId466,undefined)}const json=JSON.stringify(view.presentation464);assert.ok(!json.includes('"'+uid+'"'));assert.ok(!json.includes('"'+id+'"'));}}});
test('hacker-held instant is private; public activation has explicit cause',()=>{const g=game();g.players[0].special='hacker';draw(g,['thunder']);assert.ok(!public463(g,'p1').presentation464.some(e=>e.kind==='card'));assert.equal(public463(g,'p0').presentation464.find(e=>e.kind==='draw').drawCardId466,'thunder');assert.ok(!JSON.stringify(public463(g,'p1').presentation464).includes('thunder'))});
test('per-event hands and counts reflect one draw at a time',()=>{const g=game();draw(g,['nothing','curse-heavy']);const es=public463(g,'p0').presentation464.filter(e=>e.kind==='draw');assert.equal(es[1].after466.hand466.length,es[0].after466.hand466.length+1);for(const e of es)assert.equal(e.after466.status465[0].handCount,e.after466.hand466.length);assert.ok(es[0].after466.hand466.every(h=>h.cardId!=='curse-heavy'))});
test('steal exposes opaque back slots and advances remaining count one by one',()=>{const g=game();g.players[1].hand.forEach(u=>g.discard.push(u));g.players[1].hand=['nothing','curse-heavy','treasure'].map(id=>take(g,id));play(g,'rion-9');action463(g,'p0',{kind:'choice',value:'p1'},201);assert.equal(g.pending.kind,'steal');let v=public463(g,'p0');assert.equal(v.pending.remaining466,2);assert.ok(v.pending.options.every(o=>!o.cardId&&!o.uid&&/^\d+$/.test(o.value)));action463(g,'p0',{kind:'choice',value:'0'},202);assert.equal(g.pending.data.remaining,1);assert.equal(public463(g,'p0').pending.total466,2);action463(g,'p0',{kind:'choice',value:'0'},203);const events=public463(g,'p0').presentation464.filter(e=>e.kind==='draw');assert.deepEqual(events.map(e=>e.ordinal466),[1,2]);assert.ok(events.every(e=>e.fromPlayerId466==='p1'));assert.ok(public463(g,'p2').presentation464.filter(e=>e.kind==='draw').every(e=>!e.drawCardId466))});
test('awakening occurs only for acquired special, with full pacing budget',()=>{const g=game();g.specialDeck=['drunk'];g.queue.push({type:'special',actor:'p0',target:'p0',source:'tile',tile:'19',group:'s1'});settle463(g);assert.equal(g.presentation464.filter(e=>e.kind==='awaken').length,1);g.specialDeck=['hacker'];g.queue.push({type:'special',actor:'p0',target:'p0',source:'tile',tile:'19',group:'s2'});settle463(g);assert.equal(g.pending.kind,'special');assert.equal(g.presentation464.filter(e=>e.kind==='awaken').length,1);action463(g,'p0',{kind:'choice',value:'drunk'},300);assert.equal(g.presentation464.filter(e=>e.kind==='awaken').length,1);g.specialDeck=['hacker'];g.queue.push({type:'special',actor:'p0',target:'p0',source:'tile',tile:'19',group:'s3'});settle463(g);action463(g,'p0',{kind:'choice',value:'hacker'},400);const es=public463(g,'p2').presentation464.filter(e=>e.kind==='awaken');assert.deepEqual(es.map(e=>e.specialId466),['drunk','hacker']);schedule465(g,500,0);assert.equal(g.presentation464.find(e=>e.kind==='awaken').duration465,5800);assert.ok(g.deadline>g.presentationUntil465)});
test('local order keeps duplicate card instances distinct and appends newly drawn cards',()=>{globalThis.localStorage={getItem:()=>null,setItem:()=>{}};const u={},g={id:'order',hand:[{uid:'a',cardId:'same'},{uid:'b',cardId:'same'},{uid:'c',cardId:'other'}]};orderedHand466(u,g,'p0');u.order466=['c','b','a'];assert.deepEqual(orderedHand466(u,g,'p0').map(h=>h.uid),['c','b','a']);g.hand=g.hand.filter(h=>h.uid!=='b');g.hand.push({uid:'d',cardId:'same'});assert.deepEqual(orderedHand466(u,g,'p0').map(h=>h.uid),['c','a','d']);delete globalThis.localStorage});
