// Real coordinator integration. Only the two absent base-game catalogs use fixtures
// in a partial patch checkout. A complete checkout uses its real catalogs.
import test from 'node:test';
import assert from 'node:assert/strict';
import{registerHooks}from'node:module';
import{existsSync,mkdtempSync,rmSync,readFileSync}from'node:fs';
import{tmpdir}from'node:os';
import{join}from'node:path';
const fixtures={
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,context,next){const url=spec.startsWith('.')?new URL(spec,context.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,context)},load(url,context,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,context)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');hook.deregister();
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,canalVersion489:1,canalRules492:1,canalRules496:1,canalRules494:1,cabbageVersion484:1,cabbageScoring491:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function open(x,n=4){assert.deepEqual(x.send(0,'partyCreate462',{displayName:'Host',roster:[{id:'m0',speciesId:'wolf'}],game:'canal'}),[]);const p=Object.values(x.c.data.parties462)[0];for(let i=1;i<n;i++)assert.deepEqual(x.send(i,'partyJoin462',{code:p.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);const g=x.c.data.canalRooms489[p.code];for(let i=0;i<n;i++){assert.deepEqual(x.send(i,'canal489',{gameId:g.id,kind:'select',monsterId:'m'+i}),[]);assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[])}return{g,p}}
const inp=(seq,lane,held=true)=>({seq,lane,held,pulse:true,burst:false});
// Current protocol integration exercises the real coordinator and durable store.
function start(x,g){assert.deepEqual(x.send(0,'canal489',{gameId:g.id,kind:'start'}),[])}
function seedEnemy(g,at,lane=0){g.enemies.push({id:++g.enemySerial,kind:0,lane,hp:1,maxHp:1,spawnAt:at-5000,travelMs:10000,wiggle:0})}
test('shared pond requires current ready/start/input capability; stale clients do not inject strokes',()=>{const x=setup(2),{g}=open(x,2);assert.equal(g.rules496,1);assert.equal(x.c.view(x.sessions.get('p0')).canalRules496,1);assert.ok(x.send(1,'partyReady462',{ready:true,canalRules496:0}).length);assert.ok(x.send(0,'canal489',{gameId:g.id,kind:'start',canalRules496:0}).length);start(x,g);x.time(g.startAt+1000);x.c.advance();x.send(0,'canalInput489',{gameId:g.id,canalRules496:0,inputs:[inp(1,0,false)]});assert.equal(x.c.canalQueue489?.size??0,0)});
test('two authenticated players combine nets in the same pond and every client sees the same route',()=>{const x=setup(2),{g}=open(x,2);start(x,g);x.time(g.startAt+1000);x.c.advance();g.enemies=[];g.nextSpawnAt=g.endAt;for(const p of g.players.filter(p=>p.ai))p.nextFireAt=g.endAt;seedEnemy(g,x.now(),3);const e=g.enemies[0];Object.assign(e,{kind:2,hp:2,maxHp:2,routeX:.72,routeEnd:.53,curve:-.06});x.send(0,'canalInput489',{gameId:g.id,inputs:[{...inp(1,3,false),targetId:e.id,playerId:'p1'}]});x.time(x.now()+200);x.c.advance();assert.equal(g.players[0].hits,1);assert.equal(g.players[1].hits,0);const first=x.c.view(x.sessions.get('p0')).canal.enemies[0],second=x.c.view(x.sessions.get('p1')).canal.enemies[0];assert.deepEqual(first,second);assert.equal(first.snareSeat,0);x.send(1,'canalInput489',{gameId:g.id,inputs:[{...inp(1,3,false),targetId:e.id}]});x.time(x.now()+200);x.c.advance();assert.equal(g.teamCatches,1);assert.equal(g.netEnergy,2);assert.equal(g.players[1].captured,1);assert.equal(g.players[0].teamwork,1);assert.equal(g.players[1].teamwork,1)});
test('slow-motion anchors, routes and ACK survive restart; retry cannot apply a hit twice',()=>{const dir=mkdtempSync(join(tmpdir(),'canal496-'));try{const file=join(dir,'state.json'),x=setup(1,file),{g}=open(x,1);start(x,g);x.time(g.startAt+1000);x.c.advance();g.nextSpawnAt=g.endAt;g.enemies=[];for(const p of g.players.filter(p=>p.ai))p.nextFireAt=g.endAt;seedEnemy(g,x.now(),2);const e=g.enemies[0];Object.assign(e,{kind:1,hp:3,maxHp:3,routeX:.29,routeEnd:.5,curve:.04});const inputs=[{...inp(1,2,false),targetId:e.id}];x.send(0,'canalInput489',{gameId:g.id,inputs});x.time(x.now()+200);x.c.advance();const expected={...x.c.view(x.sessions.get('p0')).canal.enemies[0]};const y=setup(1,file);y.time(x.now()+200);y.send(0,'canalInput489',{gameId:g.id,inputs});y.c.advance();const v=y.c.view(y.sessions.get('p0')).canal;assert.deepEqual(v.enemies[0],expected);assert.equal(v.rules496,1);assert.equal(v.players[0].lastSeq,1);assert.equal(v.players[0].hits,1);assert.equal(v.enemies[0].hp,2)}finally{rmSync(dir,{recursive:true,force:true})}});
test('stored Build494 session keeps its own motion and accepts the old input capability after upgrade',()=>{const x=setup(1),{g}=open(x,1);start(x,g);delete g.rules496;g.netMax=18;x.time(g.startAt+1000);x.c.advance();g.enemies=[];g.nextSpawnAt=g.endAt;for(const p of g.players.filter(p=>p.ai))p.nextFireAt=g.endAt;seedEnemy(g,x.now(),2);x.send(0,'canalInput489',{gameId:g.id,canalRules496:0,inputs:[{...inp(1,2,false),targetId:g.enemies[0].id}]});x.time(x.now()+200);x.c.advance();const v=x.c.view(x.sessions.get('p0')).canal;assert.equal(v.rules496,undefined);assert.equal(v.netMax,18);assert.equal(v.players[0].captured,1);assert.equal(v.players[0].assists,1)});
