import test from 'node:test';import assert from 'node:assert/strict';
import * as R from '../src/tower/Rules517.js';
import {runner518,dropper518} from './fixtures/tower-ai518.mjs';
import {quizPlans519} from '../src/quiz/AI519.js';
import {makeQuiz513,startQuiz513,publicQuiz513} from '../src/quiz/Rules513.js';
import {rememberLobby519,restoreLobby519,disposeLobby519} from '../src/tower/LobbyScroll519.js';
const rng=seed=>n=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)%n};
const make=()=>{const g=R.makeTower517({id:'test519',code:'TEST',hostId:'p0',members:Array.from({length:4},(_,i)=>({playerId:'p'+i,choice:{speciesId:'slime'}}))});g.roleMode='p0';R.startTower517(g,0,9);R.advanceTower517(g,3000);g.autoAt=1e8;g.players.slice(2).forEach(p=>p.alive=false);return g};
function play(g,bot,ms=12000){const end=g.lastAt+ms;while(g.phase==='play'&&g.lastAt<end){const inputs=new Map(g.players.filter(p=>p.role==='run'&&p.alive).map(p=>[p.playerId,bot(g,p)]));R.advanceTower517(g,g.lastAt+R.TOWER517.step,inputs)}return g}
function stairs(g){g.players[1].x=1.5;for(let x=2;x<10;x++)for(let y=0;y<(x-1)*2;y++)g.board.push({x,y,type:'I'});g.boardRevision++}
test('new runner clears identical two-block stairs in less than 60% of baseline time',()=>{const old=make(),g=make();stairs(old);stairs(g);play(old,runner518);play(g,R.botRunner517);assert.equal(g.winner,'run');assert.equal(old.winner,'run');assert.ok(g.elapsed<old.elapsed*.6);console.log('Stairs ms:',Math.round(old.elapsed),'->',Math.round(g.elapsed))});
test('runner evades a visible falling block using normal movement after dash removal',()=>{const g=make();g.players[1].x=.5;g.elapsed=45000;g.lastAt=g.startAt+g.elapsed;g.falling={id:1,x:0,y:18,land:0,type:'I',cells:R.shape517('I')};play(g,R.botRunner517,1700);assert.ok(g.players[1].x>4);play(g,R.botRunner517,1500);assert.equal(g.players[1].alive,true)});
test('runners cooperate through head jumps to pass a three-block wall',()=>{const setup=g=>{g.players[1].x=3.5;g.players[1].y=12;g.players[2].alive=true;g.players[2].x=3.5;g.players[2].y=12;for(let x=0;x<10;x++)for(let y=0;y<12;y++)g.board.push({x,y,type:'O'});for(let x=5;x<10;x++)for(let y=12;y<15;y++)g.board.push({x,y,type:'O'});g.boardRevision++};const old=make(),g=make();setup(old);setup(g);for(const p of g.players)p.superReady=15000;play(old,runner518);play(g,R.botRunner517);assert.notEqual(old.winner,'run');assert.equal(g.winner,'run');assert.ok(g.events.some(e=>e.type==='bounce'));assert.equal(g.results.filter(p=>p.winner).length,3)});
test('AI search never changes the actual board, hand, actors, random seed or result',()=>{const g=make();stairs(g);const before=structuredClone(g);R.botRunner517(g,g.players[1]);R.chooseDrop517(g);assert.deepEqual(g,before);assert.doesNotMatch(JSON.stringify(R.publicTower517(g)),/releaseAt|plan|trial|memory/)});
test('an unavoidable impact still kills the AI; no immunity or extra jump power',()=>{const g=make();g.players[1].x=.5;g.elapsed=135000;g.lastAt=g.startAt+g.elapsed;g.falling={id:1,x:0,y:3,land:0,type:'I',cells:R.shape517('I')};play(g,R.botRunner517,1000);assert.equal(g.players[1].alive,false);assert.equal(g.reason,'crushed')});
test('dropper covers a narrow escape pocket instead of filling unrelated low ground',()=>{const g=make();g.players[1].x=4.5;g.players[1].y=0;for(const x of[3,6])for(let y=0;y<4;y++)g.board.push({x,y,type:'O'});g.hand=['I','O','O','O'];g.boardRevision++;const best=R.chooseDrop517(g);assert.ok(best);const cells=R.shape517(g.hand[best.slot],best.rotation);assert.ok(cells.some(([dx])=>best.x+dx===4));assert.ok(cells.some(([dx])=>best.x+dx===5));assert.ok(best.sealed)});
test('dropper returns a legal choice across rotated hands and high stacks',()=>{for(let seed=1;seed<=20;seed++){const g=make();const r=rng(seed);for(let x=0;x<10;x++)for(let y=0,h=r(14);y<h;y++)g.board.push({x,y,type:'I'});g.boardRevision++;const choice=R.chooseDrop517(g);assert.ok(choice);assert.ok(R.fits517(g,R.shape517(g.hand[choice.slot],choice.rotation),choice.x));assert.ok(choice.slot>=0&&choice.slot<4)}});
const players=[{ai:false},...Array.from({length:3},()=>({ai:true}))];const deck=Array.from({length:20},(_,i)=>({id:'q'+i,text:'問'+i,category:'a',difficulty:i<6?1:i<13?2:3,answer:i%2===0,explanation:'解説'}));
test('each quiz AI independently guesses once every two to four questions',()=>{let different=false;for(let seed=1;seed<=300;seed++){const p=quizPlans519(deck,players,rng(seed));for(let seat=1;seat<4;seat++){const rounds=p.flatMap((row,i)=>row[seat][0].blind519?[i+1]:[]);assert.ok(rounds[0]>=2&&rounds[0]<=4);for(let i=1;i<rounds.length;i++)assert.ok(rounds[i]-rounds[i-1]>=2&&rounds[i]-rounds[i-1]<=4);assert.ok(20-rounds.at(-1)<=3)}different||=p.some(row=>row[1][0].blind519!==row[2][0].blind519);assert.ok(p.every(row=>row[0].length===0))}assert.ok(different)});
test('blind choices are independent of the correct answer, including hesitation',()=>{for(let seed=1;seed<=500;seed++){const a=quizPlans519(deck,players,rng(seed)),b=quizPlans519(deck.map(q=>({...q,answer:!q.answer})),players,rng(seed));for(let i=0;i<20;i++)for(let seat=1;seat<4;seat++)if(a[i][seat][0].blind519)assert.deepEqual(a[i][seat],b[i][seat])}});
test('quiz blind choices are approximately 50:50 and reduce all three difficulty accuracies',()=>{let blind=0,circles=0;const counts=Array.from({length:4},()=>({n:0,right:0}));for(let seed=1;seed<=3000;seed++){const plans=quizPlans519(deck,players,rng(seed));for(let i=0;i<20;i++)for(let seat=1;seat<4;seat++){const steps=plans[i][seat],last=steps.at(-1),c=counts[deck[i].difficulty];c.n++;c.right+=(last.side==='o')===deck[i].answer;if(last.blind519){blind++;circles+=last.side==='o'}}}assert.ok(circles/blind>.48&&circles/blind<.52);for(let d=1;d<=3;d++)assert.ok(counts[d].right/counts[d].n<[0,.84,.77,.68][d]);console.log('Quiz planned accuracy:',counts.slice(1).map(c=>(c.right/c.n*100).toFixed(2)), 'blind O%',(circles/blind*100).toFixed(2))});
test('quiz guessing schedule stays private and persisted plans survive serialization',()=>{const g=makeQuiz513({id:'q519',code:'Q519',hostId:'p0',members:[{playerId:'p0',choice:{id:'m',speciesId:'slime'}}]});startQuiz513(g,0,deck,rng(17));const restored=JSON.parse(JSON.stringify(g));assert.deepEqual(restored.botPlan513,g.botPlan513);assert.doesNotMatch(JSON.stringify(publicQuiz513(g,'p0')),/blind519|botPlan513|nextBlind/) });
function scrollFixture(){const saved=Object.fromEntries(['requestAnimationFrame','cancelAnimationFrame','scrollX','scrollY','scrollTo'].map(k=>[k,globalThis[k]])),frames=new Map();let id=0;globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id};globalThis.cancelAnimationFrame=n=>frames.delete(n);globalThis.scrollX=0;globalThis.scrollY=135;globalThis.scrollTo=(x,y)=>{globalThis.scrollX=x;globalThis.scrollY=y};let lobby={},roster={scrollTop:170};const parent={scrollTop:24,scrollLeft:0,scrollHeight:1000,clientHeight:600},root={scrollTop:710,scrollLeft:0,scrollHeight:1600,clientHeight:640,parentElement:parent,querySelector:s=>s==='.tw-lobby517'?lobby:s==='.tw-roster517'?roster:null};const c={root,towerUI517:{gameId:'same'},state:{tower:{id:'same',phase:'lobby'}}};return{c,root,parent,frames,rebuild(){lobby={};roster={scrollTop:0};root.scrollTop=0;parent.scrollTop=0;globalThis.scrollY=0},roster:()=>roster,flush(){const f=[...frames.values()];frames.clear();f.forEach(fn=>fn())},end(){disposeLobby519(c);for(const[k,v]of Object.entries(saved))if(v===undefined)delete globalThis[k];else globalThis[k]=v}}}
test('lobby selection preserves page, app, ancestor and roster scroll through rebuild/layout',()=>{const f=scrollFixture();try{rememberLobby519(f.c);f.rebuild();restoreLobby519(f.c);assert.equal(f.root.scrollTop,710);assert.equal(f.roster().scrollTop,170);assert.equal(f.parent.scrollTop,24);assert.equal(globalThis.scrollY,135);f.root.scrollTop=0;f.flush();assert.equal(f.root.scrollTop,710);assert.equal(f.frames.size,0)}finally{f.end()}});
test('scroll restoration cannot drag a different game or a started match back to its lobby',()=>{for(const mode of['id','phase']){const f=scrollFixture();try{rememberLobby519(f.c);f.rebuild();restoreLobby519(f.c);f.c.state.tower[mode]=mode==='id'?'new':'play';f.root.scrollTop=0;f.flush();assert.equal(f.root.scrollTop,0)}finally{f.end()}}});
test('scroll snapshot refreshes from the current position and pending callback is cleaned up',()=>{const f=scrollFixture();try{rememberLobby519(f.c);f.rebuild();restoreLobby519(f.c);assert.equal(f.frames.size,1);f.root.scrollTop=900;f.roster().scrollTop=210;rememberLobby519(f.c);assert.equal(f.frames.size,0);f.rebuild();restoreLobby519(f.c);assert.equal(f.root.scrollTop,900);assert.equal(f.roster().scrollTop,210);disposeLobby519(f.c);assert.equal(f.frames.size,0)}finally{f.end()}});
