// Real coordinator integration. Only the two absent base-game catalogs use fixtures
// in a partial patch checkout. A complete checkout uses its real catalogs.
import test from 'node:test';
import assert from 'node:assert/strict';
import{registerHooks}from'node:module';
import{existsSync,mkdtempSync,rmSync,readFileSync}from'node:fs';
import{tmpdir}from'node:os';
import{join}from'node:path';
const fixtures={
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,context,next){const url=spec.startsWith('.')?new URL(spec,context.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,context)},load(url,context,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,context)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');hook.deregister();
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,canalVersion489:1,canalRules492:1,canalRules494:1,cabbageVersion484:1,cabbageScoring491:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function open(x,n=4){assert.deepEqual(x.send(0,'partyCreate462',{displayName:'Host',roster:[{id:'m0',speciesId:'wolf'}],game:'canal'}),[]);const p=Object.values(x.c.data.parties462)[0];for(let i=1;i<n;i++)assert.deepEqual(x.send(i,'partyJoin462',{code:p.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);const g=x.c.data.canalRooms489[p.code];for(let i=0;i<n;i++){assert.deepEqual(x.send(i,'canal489',{gameId:g.id,kind:'select',monsterId:'m'+i}),[]);assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[])}return{g,p}}
const inp=(seq,lane,held=false)=>({seq,lane,held,pulse:true,burst:false});
function start(x,g){assert.deepEqual(x.send(0,'canal489',{gameId:g.id,kind:'start'}),[])}
function seedEnemy(g,at,lane=0){g.enemies.push({id:++g.enemySerial,kind:0,lane,hp:1,maxHp:1,spawnAt:at-5000,travelMs:10000,wiggle:0})}
test('full authenticated route: create, join, choose owned monsters, ready, cooperate, result and switch to every existing game',()=>{const x=setup(),{g,p}=open(x);assert.equal(x.c.view(x.sessions.get('p0')).canal.phase,'lobby');assert.equal(x.c.view(x.sessions.get('p0')).room,null);start(x,g);assert.equal(x.c.active('p0'),true);x.time(g.startAt+1000);x.c.advance();for(let i=0;i<4;i++){seedEnemy(g,x.now(),i);x.send(i,'canalInput489',{gameId:g.id,inputs:[inp(1,i)]})}x.time(x.now()+250);x.c.advance();assert.deepEqual(g.players.map(p=>p.captured),[1,1,1,1]);for(const s of x.sessions.values())s.connected=false;x.time(g.endAt);x.c.advance();assert.equal(g.phase,'result');assert.equal(x.c.active('p0'),false);for(const s of x.sessions.values())s.connected=true;assert.deepEqual(x.send(0,'partyGame462',{game:'canal'}),[]);assert.notEqual(x.c.data.canalRooms489[p.code].id,g.id);assert.ok(p.members.every(m=>!m.ready));for(const next of ['cabbage','sugoroku','race']){assert.deepEqual(x.send(0,'partyGame462',{game:next}),[]);const view=x.c.view(x.sessions.get('p0'));assert.equal(view.canal,null);assert.equal((view.cabbage??view.sugoroku??view.room).phase,'lobby')}assert.equal(x.c.healthy(),true)});
test('host, owned selection, ready status and new client version are checked before start',()=>{const x=setup(),{g}=open(x);assert.ok(x.send(1,'canal489',{gameId:g.id,kind:'start'}).length);assert.ok(x.send(0,'canal489',{gameId:g.id,kind:'select',monsterId:'stolen'}).length);assert.ok(x.send(0,'canal489',{gameId:g.id,kind:'select',monsterId:'m0',canalVersion489:0}).length);x.send(2,'partyReady462',{ready:false});assert.ok(x.send(0,'canal489',{gameId:g.id,kind:'start'}).length);x.send(2,'partyReady462',{ready:true});x.c.data.parties462[g.code].members[2].canalVersion489=0;assert.ok(x.send(0,'canal489',{gameId:g.id,kind:'start'}).length);assert.equal(x.c.data.canalRooms489[g.code].phase,'lobby')});
test('offline seat can be removed from unchanged party flow and the vacant seat receives an AI',()=>{const x=setup(2),{g,p}=open(x,2);x.sessions.get('p1').connected=false;assert.deepEqual(x.send(0,'partyKick485',{partyId:p.id,gameId:g.id,playerId:'p1',seatToken485:p.members[1].seatToken485}),[]);start(x,g);assert.equal(g.players.filter(p=>p.ai).length,3);assert.equal(g.members.length,1);assert.equal(x.c.view(x.sessions.get('p1')).party,null)});
test('spectators see the current game but cannot drive another player net, and join the next lobby',()=>{const x=setup(),{g,p}=open(x,1);start(x,g);assert.deepEqual(x.send(1,'partyJoin462',{code:p.code,roster:[{id:'m1',speciesId:'slime'}]}),[]);assert.equal(x.c.view(x.sessions.get('p1')).party.members[1].spectating,true);x.time(g.startAt+1000);x.send(1,'canalInput489',{gameId:g.id,playerId:'p0',inputs:[inp(1,0)]});assert.equal(x.c.canalQueue489?.size??0,0);assert.ok(x.send(1,'canal489',{gameId:g.id,kind:'select',monsterId:'m1'}).length);x.time(g.endAt);x.c.advance();x.send(0,'partyGame462',{game:'canal'});assert.equal(x.c.data.canalRooms489[p.code].members.length,2)});
test('disconnect/home transfer is temporary and rejoining preserves captures and sequence',()=>{const x=setup(),{g}=open(x);start(x,g);x.sessions.get('p0').connected=false;x.time(g.startAt+12000);x.c.advance();assert.equal(g.players[0].auto,true);assert.ok(g.players[0].captured>0);const old=g.players[0].captured;x.sessions.get('p0').connected=true;x.time(x.now()+250);x.c.advance();assert.equal(g.players[0].auto,false);assert.equal(g.players[0].captured,old);x.send(0,'partyPresence462',{atHome:true});x.time(x.now()+250);x.c.advance();assert.equal(g.players[0].auto,true);x.send(0,'partyPresence462',{atHome:false});x.time(x.now()+250);x.c.advance();assert.equal(g.players[0].auto,false)});
test('queued inputs are bounded and deduplicated; each press avoids a disk write or broadcast',()=>{const x=setup(1),{g}=open(x,1);start(x,g);x.time(g.startAt+1000);const rev=x.c.data.revision,n=x.packets.length;for(let i=0;i<200;i++)x.send(0,'canalInput489',{gameId:g.id,inputs:[inp(i+1,0)]});const q=[...x.c.canalQueue489.values()][0];assert.equal(q.length,96);assert.equal(x.c.data.revision,rev);assert.equal(x.packets.length,n);x.send(0,'canalInput489',{gameId:'stale',inputs:[inp(1000,0)]});assert.equal(q.length,96);x.c.advance();assert.equal(x.c.canalQueue489.size,0);assert.equal(g.players[0].lastSeq,96)});
test('durable restart restores game, rejects duplicate input and can finish after a long outage',()=>{const dir=mkdtempSync(join(tmpdir(),'canal489-'));try{const file=join(dir,'state.json'),x=setup(1,file),{g}=open(x,1);start(x,g);x.time(g.startAt+1000);x.c.advance();seedEnemy(g,x.now());x.send(0,'canalInput489',{gameId:g.id,inputs:[inp(1,0,false)]});x.time(x.now()+250);x.c.advance();const saved=JSON.parse(readFileSync(file));assert.equal(saved.canalRooms489[g.code].players[0].captured,1);const y=setup(1,file);y.time(x.now()+250);y.send(0,'canalInput489',{gameId:g.id,inputs:[inp(1,0,false)]});y.c.advance();assert.equal(y.c.data.canalRooms489[g.code].players[0].captured,1);assert.equal(y.c.view(y.sessions.get('p0')).canal.players[0].lastSeq,1);y.sessions.get('p0').connected=false;y.time(g.endAt+3600000);y.c.advance();assert.equal(y.c.data.canalRooms489[g.code].phase,'result');assert.equal(y.c.healthy(),true)}finally{rmSync(dir,{recursive:true,force:true})}});
test('failed durable commit keeps queued input available for a successful retry',()=>{const x=setup(1),{g}=open(x,1);start(x,g);x.time(g.startAt+1000);x.c.advance();seedEnemy(g,x.now());x.send(0,'canalInput489',{gameId:g.id,inputs:[inp(1,0,false)]});x.time(x.now()+250);const transaction=x.c.transaction.bind(x.c);x.c.transaction=fn=>{const before=structuredClone(x.c.data);fn();x.c.data=before;throw Error('disk unavailable')};x.c.advance();assert.equal(x.c.canalQueue489.size,1);assert.equal(x.c.data.canalRooms489[g.code].players[0].captured,0);x.c.transaction=transaction;x.c.advance();assert.equal(x.c.data.canalRooms489[g.code].players[0].captured,1);assert.equal(x.c.canalQueue489.size,0)});
test('active game blocks kick, leave and switch; result clears queues and supports normal leave',()=>{const x=setup(2),{g,p}=open(x,2);start(x,g);assert.ok(x.send(0,'partyKick485',{partyId:p.id,gameId:g.id,playerId:'p1',seatToken485:p.members[1].seatToken485}).length);assert.ok(x.send(1,'partyLeave462').length);assert.ok(x.send(0,'partyGame462',{game:'cabbage'}).length);x.time(g.endAt);x.c.advance();assert.deepEqual(x.send(1,'partyLeave462'),[]);assert.deepEqual(x.send(0,'partyLounge462'),[]);assert.equal(x.c.view(x.sessions.get('p0')).canal,null);assert.equal(x.c.view(x.sessions.get('p0')).party.game,null);assert.equal(Object.keys(x.c.data.canalRooms489).length,0)});
test('no currency delivery or main-game reward is minted by cooperative defense',()=>{const x=setup(1),{g}=open(x,1);start(x,g);x.time(g.endAt);x.c.advance();const a=x.c.data.accounts.p0;assert.deepEqual(a.deliveries,[]);assert.equal(a.sgDeliveries474,undefined);assert.deepEqual(a.decisions,{})});
