import test from'node:test';import assert from'node:assert/strict';
import{makeCanal489,startCanal489,advanceCanal489,inputCanal489,publicCanal489}from'../src/canal/Rules489.js';
import{CANAL496,sweep496,progress496,remaining496}from'../src/canal/Rules496.js';
import{layout496,stable496,draw496}from'../src/canal/Scene496.js';
import{view496,tick496,target496,receive496,click496}from'../src/canal/View496.js';
import{bindFocus496}from'../src/canal/Input496.js';
import{canalSignature489}from'../src/canal/View489.js';
import{readFileSync}from'node:fs';
function game(seed=73,humans=2){const g=makeCanal489({id:'496',code:'A',partyId:'party',hostId:'p0',members:Array.from({length:humans},(_,i)=>({playerId:'p'+i,name:'Player'+i,choice:{id:'m'+i,speciesId:'wolf'}})),now:0,seed});g.rules496=1;startCanal489(g,0);g.phase='playing';return g}
const enemy=(id,kind=0,lane=0)=>({id,kind,lane,hp:[1,3,2,8][kind],maxHp:[1,3,2,8][kind],spawnAt:6000,travelMs:10000,routeX:.2+lane*.15,routeEnd:.4+lane*.05,curve:.03,wiggle:0,contributors:[]});
const input=(seq,id,lane=0)=>({seq,targetId:id,lane,held:false,pulse:true,burst:false});
class E{constructor(doc){this.ownerDocument=doc;this.nodes=new Map();this.dataset={};this.style={};this.attrs={};this.children=[];this.listeners=new Map();this.classList={toggle(){}};this.clientWidth=375;this.clientHeight=490}addEventListener(n,f){const a=this.listeners.get(n)??new Set();a.add(f);this.listeners.set(n,a)}removeEventListener(n,f){this.listeners.get(n)?.delete(f)}emit(n,p={}){const e={preventDefault(){},button:0,target:this,pointerId:1,clientX:100,clientY:100,...p};for(const f of this.listeners.get(n)??[])f(e)}querySelector(q){return this.nodes.get(q)??null}querySelectorAll(q){return this.nodes.get(q)??[]}appendChild(x){this.children.push(x);x.parent=this}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this)}setAttribute(k,v){this.attrs[k]=v}getContext(){return null}closest(q){return q==='[data-cn-target496]'&&this.dataset.cnTarget496?this:null}}
function client(g){const doc={createElement:()=>new E(doc)},root=new E(doc),stage=new E(doc),host=new E(doc),canvas=new E(doc),sent=[];root.nodes.set('.cn496',stage);root.nodes.set('[data-cn-stage496]',stage);stage.nodes.set('canvas',canvas);root.nodes.set('[data-cn-targets496]',host);for(const q of ['[data-cn-alert496]','[data-cn-health496]','[data-cn-time496]','[data-cn-feed496]'])root.nodes.set(q,new E(doc));const c={root,state:{canal:publicCanal489(g,'p0',10000),party:{hostId:'p0'}},transport:{selfId:'p0'},cnSound493:false,offset:0,ready:()=>true,connected:()=>true,raw:(op,m)=>{sent.push({op,m});return true},sgMonster463:()=>''};view496(c);return{c,root,stage,host,sent}}
test('capturing or spawning neighbors cannot move a surviving enemy, at any viewport size',()=>{const a=enemy(1,1),b=enemy(2,2,3);for(const [w,h]of[[320,390],[375,490],[430,670],[620,230]]){const point=layout496([a,b],10000,w,h).find(x=>x.id===2);assert.deepEqual(layout496([b],10000,w,h)[0],point);assert.deepEqual(layout496([enemy(3),b,enemy(4)],10000,w,h).find(x=>x.id===2),point);assert.ok(point.size<=80);assert.ok(point.touchSize>=52);assert.ok(point.x-point.touchSize/2>=0&&point.x+point.touchSize/2<=w)}});
test('snare anchors are continuous on impact and expiry, and expose meaningful ETA',()=>{const g=game(),e=enemy(1,1);g.enemies=[e];const before=progress496(e,10000);sweep496(g,g.players[0],0,10000,false,1);assert.equal(progress496(e,10000),before);assert.ok(Math.abs(progress496(e,10850)-(before+.0255))<1e-10);assert.ok(progress496(e,10851)>progress496(e,10850));assert.ok(remaining496(e,10000)>6000);assert.equal(e.snareSeat,0);assert.equal(e.slowUntil,10850);const saved=JSON.parse(JSON.stringify(e));assert.equal(progress496(saved,11000),progress496(e,11000))});
test('same enemy + another player awards one teamwork capture, bonus meter and contributor credit',()=>{const g=game(),e=enemy(1,2,2);g.enemies=[e];inputCanal489(g,g.players[0],input(1,1,2),10000);inputCanal489(g,g.players[1],input(1,1,2),10200);assert.equal(g.captured,1);assert.equal(g.teamCatches,1);assert.equal(g.netEnergy,2);assert.equal(g.players[0].teamwork,1);assert.equal(g.players[1].teamwork,1);assert.deepEqual(g.events.at(-1).helpers,[0]);assert.equal(inputCanal489(g,g.players[1],input(1,1),10500),false);assert.equal(g.captured,1)});
test('expired helpers and self-only hits cannot fake teamwork; close captures count a rescue',()=>{const g=game(),e=enemy(1,2,3);g.enemies=[e];sweep496(g,g.players[0],3,10000,false,1);sweep496(g,g.players[1],3,14500,false,1);assert.equal(g.teamCatches,0);assert.equal(g.players[1].rescues,0);g.enemies=[{...enemy(2),spawnAt:1500}];sweep496(g,g.players[0],0,10250,false,2);assert.equal(g.players[0].rescues,1);assert.equal(g.events.at(-1).rescue,true)});
test('global mega is atomic, draws all four seats, and cannot replenish itself',()=>{const g=game();g.enemies=Array.from({length:4},(_,i)=>enemy(i+1,1,i));g.netEnergy=CANAL496.netMax;assert.equal(sweep496(g,g.players[0],0,10000,true),true);assert.equal(sweep496(g,g.players[1],1,10000,true),false);assert.equal(g.netEnergy,0);assert.equal(g.captured,4);assert.deepEqual(g.events.find(e=>e.kind==='mega').seats,[0,1,2,3]);assert.equal(g.megaCount,1)});
test('spawn positions and cadence vary, remain deterministic and survive persisted resume',()=>{const a=game(67,4),b=JSON.parse(JSON.stringify(a));for(const p of a.players)p.nextFireAt=100000;for(const p of b.players)p.nextFireAt=100000;for(let at=a.startAt;at<a.startAt+7000;at+=100)advanceCanal489(a,at);advanceCanal489(b,a.startAt+6900);assert.deepEqual(a,b);assert.ok(new Set(a.enemies.map(e=>e.routeX)).size>=5);const gaps=a.enemies.slice(1).map((e,i)=>Math.round(e.spawnAt-a.enemies[i].spawnAt));assert.ok(new Set(gaps).size>3);const restored=JSON.parse(JSON.stringify(a));advanceCanal489(a,a.endAt);advanceCanal489(restored,restored.endAt);assert.deepEqual(a,restored)});
test('render corrections never rewind and cap forward catch-up instead of teleporting',()=>{const u={},e=enemy(1);let a=stable496(layout496([e],10000,375,490),u,10000,375,490)[0];const old=a.progress;const slowed={...e,motionAt:9500,motionProgress:.35,slowUntil:11000};a=stable496(layout496([slowed],10016,375,490),u,10016,375,490)[0];assert.equal(a.progress,old);const next=stable496(layout496([e],12500,375,490),u,10032,375,490)[0];assert.ok(next.progress-old<=16/10000*1.5+.0001);assert.ok(next.y>=a.y)});
test('snapshot contains fixed routes and shared counters, not private contributors or other input ACKs',()=>{const g=game();g.enemies=[enemy(1,1)];inputCanal489(g,g.players[0],input(1,1),10000);const v=publicCanal489(g,'p1',10000);assert.equal(v.rules496,1);assert.equal(v.enemies[0].routeX,.2);assert.equal(v.enemies[0].contributors,undefined);assert.equal(v.players[0].lastSeq,undefined);assert.equal(v.players[1].lastSeq,0);assert.equal(v.rng,undefined)});
test('all enemies are visible and targetable; canvas and enlarged touch buttons have identical centers',t=>{t.mock.method(Date,'now',()=>10000);const g=game();g.enemies=[enemy(1),enemy(2,1,1),enemy(3,2,2),enemy(4,0,3)];const{c,host,sent}=client(g);tick496(c);assert.equal(host.children.length,4);for(const b of host.children){const e=c.cnUI496.frameLayout.find(x=>String(x.id)===b.dataset.cnTarget496);assert.equal(b.style.left,e.x+'px');assert.equal(b.style.top,e.y+'px');assert.equal(b.style.width,e.touchSize+'px')}assert.equal(target496(c,3),true);assert.equal(sent[0].m.inputs[0].targetId,3);assert.equal(sent[0].m.inputs[0].lane,2);assert.equal(sent[0].m.inputs[0].held,false);assert.equal(target496(c,3),false)});
test('teammate captures, snares and rescue feedback identify actors and escape player names',t=>{t.mock.method(Date,'now',()=>10000);const g=game(),{c,root}=client(g);c.state.canal.players[1].name='<img>';c.state.canal.events=[{id:1,at:10000,kind:'catch',seat:1,enemyId:2,teamwork:true,helpers:[0]}];receive496(c);assert.match(root.querySelector('[data-cn-feed496]').innerHTML,/あなた.*&lt;img&gt;.*連携捕獲/);c.state.canal.events.push({id:2,at:10000,kind:'catch',seat:1,rescue:true});receive496(c);assert.match(root.querySelector('[data-cn-feed496]').innerHTML,/ナイス救援/);assert.equal(c.cnUI496.effects.length,2);receive496(c);assert.equal(c.cnUI496.effects.length,2)});
test('four fixed crew, no lane switches, one bottom button, stable countdown DOM and bounded result title',()=>{const{c}=client(game());const html=view496(c);assert.equal((html.match(/data-cn-helper496=/g)||[]).length,4);assert.doesNotMatch(html,/スワイプ|data-cn-view|data-cn-lane=/);assert.equal((html.match(/<footer[\s\S]*?<\/footer>/)[0].match(/<button/g)||[]).length,1);c.state.canal.phase='countdown';const signature=canalSignature489(c);c.state.canal.phase='playing';assert.deepEqual(canalSignature489(c),signature);c.state.canal.phase='result';c.state.canal.grade='再出動';const result=view496(c);assert.match(result,/cn-award492 is-word/);assert.match(result,/もう一度/);assert.match(result,/ミニゲーム一覧へ戻る/);assert.doesNotMatch(result,/ホームへ戻る/);const css=readFileSync(new URL('../src/Styles/build496-canal-team.css',import.meta.url),'utf8');assert.match(css,/\.cn-award492.is-word b\{[^}]*white-space:nowrap/)});
test('pointer and touch fallback each send one released tap; dragging, cancel and multi-touch send none',()=>{for(const pointer of[true,false]){const s=new E(),w=new E(),b=new E();b.dataset.cnTarget496='7';const taps=[];const off=bindFocus496(s,{tap:id=>taps.push(id)},w,pointer);if(pointer){s.emit('pointerdown',{target:b});w.emit('pointerup');s.emit('pointerdown',{target:b});w.emit('pointermove',{clientX:150});w.emit('pointerup',{clientX:150});s.emit('pointerdown',{target:b});w.emit('pointercancel');s.emit('pointerdown',{target:b});s.emit('pointerdown',{target:b,pointerId:2});w.emit('pointerup');w.emit('pointerup',{pointerId:2})}else{const t={identifier:1,clientX:100,clientY:100,target:b};s.emit('touchstart',{changedTouches:[t]});w.emit('touchend',{changedTouches:[t]});s.emit('touchstart',{changedTouches:[t]});w.emit('touchcancel',{changedTouches:[t]})}assert.deepEqual(taps,[7]);off()}});
test('synthetic click does not duplicate touch, and replay clears scene/feedback/pending input state',t=>{t.mock.method(Date,'now',()=>10000);const g=game();g.enemies=[enemy(1)];const{c,sent}=client(g);click496(c,{dataset:{cnTarget496:'1'}},{detail:1,pointerType:'touch'});assert.equal(sent.length,0);click496(c,{dataset:{cnTarget496:'1'}},{detail:0});assert.equal(sent.length,1);c.cnUI496.feed=[{text:'old'}];c.cnUI496.motion.set(1,{progress:1});c.state.canal.id='next';view496(c);assert.deepEqual(c.cnUI496.pending,[]);assert.deepEqual(c.cnUI496.feed,[]);assert.equal(c.cnUI496.motion.size,0)});
test('production canvas renders shared health, snare and mega from all four origins',()=>{const text=[],ctx=new Proxy({fillText:t=>text.push(t),createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:()=>{}}),canvas={clientWidth:375,clientHeight:490,getContext:()=>ctx},g=game();g.hp=24;g.enemies=[{...enemy(1,1),slowUntil:10800,snareSeat:1}];const u={effects:[{kind:'mega',localAt:9800}],reduced:true};draw496(canvas,g,u,10000,10000,layout496(g.enemies,10000,375,490));assert.ok(text.some(t=>t.includes('24 / 100')));assert.ok(text.includes('足止め中'));assert.ok(text.includes('4人で、一網打尽！'))});
test('seeded balance: idle fails, coordinated taps + net can win, ignoring the net is risky',async()=>{const{run}=await import('./canal496-simulation.mjs');const a=Array.from({length:30},(_,i)=>run(i+1,450,1,true)),idle=Array.from({length:30},(_,i)=>run(i+1,0)),noNet=Array.from({length:30},(_,i)=>run(i+1,450,1,false));assert.equal(idle.filter(x=>x.win).length,0);assert.ok(a.filter(x=>x.win).length>=24);assert.ok(noNet.filter(x=>x.win).length<10);assert.ok(a.every(x=>x.team>0));assert.ok(a.reduce((s,x)=>s+x.hp,0)/30<95)});
