import test from 'node:test';
import assert from 'node:assert/strict';
import {make550,start550,advance550,pick550,launch550,input550,physics550,public550,layout550,finishRound550,RICOCHET550 as C} from '../src/ricochet550/Rules550.js';
import {ITEMS550} from '../src/ricochet550/Catalog550.js';
import {sample550} from '../src/ricochet550/Input550.js';
import {createRicochet550,handleRicochet550,queueRicochet550,advanceRicochets550,liveRicochet550,ricochetSnapshot550} from '../online-server/src/RicochetCoordinator550.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'選手'+i,owned:[{id:'m'+i,speciesId:['slime','goblin','wolf','skeleton'][i]}],choice:{id:'m'+i,speciesId:['slime','goblin','wolf','skeleton'][i]},color499:['orange','green','pink','blue'][i]}));
function make(mode='pinball',rounds=8){const g=make550({id:'test',code:'ABC',partyId:'party',hostId:'p0',now:0,members,mode});g.rounds=rounds;start550(g,0,12345);return g}
function play(mode='pinball'){const g=make(mode);g.phase='play';g.roundAt=0;g.simAt=0;g.deadline=C.play;g.elapsed=0;g.players.forEach(p=>{p.picked=p.offers[0];p.parts={}});return g}
function controller(mode='pinball'){let now=0;const sent=[],party={id:'party',code:'ABC',hostId:'p0',members:members.map(m=>({...m,ready:true,ricochetVersion550:2}))};const c={data:{serial:0,parties462:{ABC:party}},now:()=>now,sessions:new Map(members.map(m=>[m.playerId,{playerId:m.playerId,connected:true}])),subscribers:new Set(members.map(m=>m.playerId)),isBusy:()=>false,transaction:fn=>fn(),send:(id,m)=>sent.push({id,m}),push(){},broadcast(){}};const g=createRicochet550(c,party,members,mode);c.data.ricochetRooms550={ABC:g};return{c,g,party,sent,time:n=>now=n}}
const command=(g,p,seq,action,extra={})=>({gameId:g.id,ricochetVersion550:2,round:g.round,seq,action,...extra});
test('both games offer three distinct upgrades, private to each owner',()=>{for(const mode of Object.keys(ITEMS550)){const g=make(mode);assert.equal(g.players.length,4);assert.equal(new Set(g.players[0].offers).size,3);const s=public550(g,'p0');assert.equal(s.players[0].offers.length,3);assert(!('offers' in s.players[1]));assert(!('seed' in s));assert(!('botAt' in s.players[0]));assert(!('owned' in s.members[0]))}});
test('draft rejects forged choices and repeat selections',()=>{const g=make(),p=g.players[0];assert(!pick550(g,p,'forged'));const id=p.offers[0];assert(pick550(g,p,id));assert.equal(p.parts[id],1);assert(!pick550(g,p,p.offers[1]));assert.equal(Object.values(p.parts).reduce((a,b)=>a+b,0),1)});
test('new start resets score, parts, charge; rounds kept at 8 or 16',()=>{const g=make('junkgp',16);g.players[0].parts.cell=4;g.players[0].charge=50;g.players[0].score=1234;start550(g,100,90);assert.equal(g.rounds,16);assert.deepEqual(g.players[0].parts,{});assert.equal(g.players[0].charge,0);assert.equal(g.players[0].score,0)});
test('waiting bodies stay still until a real impact',()=>{for(const mode of Object.keys(ITEMS550)){const g=play(mode),before=g.players.map(p=>[p.x,p.y]);for(let i=0;i<100;i++)physics550(g);assert.deepEqual(g.players.map(p=>[p.x,p.y]),before)}});
test('both modes collide with unlaunched opponents without spending their shot',()=>{for(const mode of Object.keys(ITEMS550)){const g=play(mode),a=g.players[0],b=g.players[1];Object.assign(a,{x:-1,y:4,vx:35,vy:0,launched:true});Object.assign(b,{x:.4,y:4});const x=b.x;for(let i=0;i<4;i++){g.simAt+=20;physics550(g)}assert(b.x>x+.1);assert(b.vx>5);assert.equal(b.launched,false);const vx=b.vx;assert(launch550(g,b,.6,0));assert.equal(b.vx,vx);assert(b.vy>10)}});
test('release adds momentum, cancel keeps it, repeat shots are rejected',()=>{const g=play(),p=g.players[0];Object.assign(p,{vx:6,vy:3});assert(input550(g,p,{seq:1,round:1,action:'pull',power:.6,angle:0}));assert(input550(g,p,{seq:2,round:1,action:'cancel'}));assert.equal(p.vx,6);assert.equal(p.vy,3);assert(launch550(g,p,.6,0));assert.equal(p.vx,6);assert(p.vy>3);assert(!launch550(g,p,1,0));assert(!input550(g,p,{seq:2,round:1,action:'cancel'}))});
test('maximum opposing speeds do not tunnel through bodies or rails',()=>{const g=play(),a=g.players[0],b=g.players[1];Object.assign(a,{x:-1,y:4,vx:95});Object.assign(b,{x:1,y:4,vx:-95});physics550(g,.02);assert(a.vx<0);assert(b.vx>0);for(let i=0;i<300;i++){g.simAt+=20;physics550(g);for(const p of g.players){assert(Number.isFinite(p.x+p.y+p.vx+p.vy));assert(Math.abs(p.x)<=C.width/2-p.r+.002);assert(p.y>=p.r-.002);assert(p.y<=C.height-p.r+.002);assert(Math.hypot(p.vx,p.vy)<=C.maxSpeed+.001)}}});
test('pinball gold pin awards points and a chest has one owner',()=>{const g=play(),p=g.players[0],b=g.layout.bumpers[0];Object.assign(p,{x:b.x,y:b.y-b.r-p.r-.02,vy:14});physics550(g);assert(p.roundScore>0);const chest=g.layout.chests[0];Object.assign(p,{x:chest.x,y:chest.y,vx:0,vy:0});physics550(g);assert.equal(chest.claimed,p.seat);const before=p.roundScore;physics550(g);assert.equal(p.roundScore,before)});
test('bank invests later, abilities stack and persist across rounds',()=>{const g=play(),p=g.players[0];p.parts={bank:2,cell:1};p.charge=30;finishRound550(g,100);assert.equal(p.score,24);assert.equal(g.history[0].rows[0].investment,24);for(let now=120;now<4500;now+=20)advance550(g,now);assert.equal(g.round,2);assert.equal(p.parts.bank,2);assert.equal(p.charge,30)});
test('capacitor charges from impacts and is consumed only at launch',()=>{const g=play(),p=g.players[0];p.parts.cell=2;Object.assign(p,{x:5.45,y:4,vx:20});physics550(g);assert(p.charge>0);const bank=p.charge;p.vx=p.vy=0;launch550(g,p,.5,0);assert.equal(p.charge,0);assert(Math.abs(p.vy-(7+13*.5+21*.5**3+bank*.16))<.001)});
test('heavy armor makes a cart harder to accelerate and harder to push',()=>{const a=play('junkgp'),b=play('junkgp');const p=a.players[0],q=b.players[0];q.parts.armor=3;q.mass=2.8;launch550(a,p,.7,0);launch550(b,q,.7,0);assert(q.vy<p.vy*.7)});
test('rocket is a delayed impulse; once-only belt boosts cannot be farmed',()=>{const g=play('junkgp'),p=g.players[0];p.parts.rocket=2;launch550(g,p,.5,0);for(let now=20;now<=1400;now+=20)advance550(g,now);assert(p.rocketFired);assert(g.events.some(e=>e.type==='boost'&&e.text==='ロケット点火！'));const belt=g.layout.belts[0];p.x=belt.x;p.y=belt.from+.2;p.vy=5;physics550(g);assert(p.usedBelts.includes(belt.id));const before=p.usedBelts.length;p.x=belt.x;p.y=belt.from+.2;p.vy=5;physics550(g);assert.equal(p.usedBelts.length,before);assert(p.vy<5)});
test('draft timeout and unattended launch finish full 8/16-round games with finite results',()=>{for(const mode of Object.keys(ITEMS550))for(const rounds of [8,16]){const g=make(mode,rounds);const auto=new Set(g.players.map(p=>p.playerId));for(let now=20;now<rounds*35000&&g.phase!=='result';now+=20)advance550(g,now,[],auto);assert.equal(g.phase,'result',mode+' '+rounds);assert.equal(g.history.length,rounds);assert.equal(g.results.length,4);assert(g.players.every(p=>Number.isSafeInteger(p.score)&&p.score>0));assert(g.players.every(p=>Object.values(p.parts).reduce((a,b)=>a+b,0)===rounds));assert(g.players.every(p=>Object.values(p.parts).every(n=>n<=4)));assert(g.winnerIds.length>=1)}});
test('ties receive the same rank',()=>{const g=play();g.round=g.rounds;g.players.forEach(p=>{p.score=20;p.roundScore=0});finishRound550(g,100);assert(g.results.every(r=>r.rank===1));assert.equal(g.winnerIds.length,4)});
test('pull depends on distance, not hold time; all directions are allowed',()=>{assert(!sample550({x:100,y:100},{x:102,y:103},390,500).active);const p=sample550({x:100,y:100},{x:100,y:200},390,500);assert(p.power>.9);assert.equal(p.angle,0);assert(Math.abs(sample550({x:100,y:100},{x:100,y:0},390,500).angle)===Math.PI)});
test('coordinator enforces host, readiness, version, roster ownership, and 8/16 setting',()=>{const {c,g,party}=controller(),p0=c.sessions.get('p0'),p1=c.sessions.get('p1');assert.throws(()=>handleRicochet550(c,p1,{op:'ricochet550',gameId:g.id,ricochetVersion550:2,kind:'start'}));assert.throws(()=>handleRicochet550(c,p0,{op:'ricochet550',gameId:g.id,ricochetVersion550:2,kind:'select',monsterId:'forged'}));assert.throws(()=>handleRicochet550(c,p0,{op:'ricochet550',gameId:g.id,kind:'start'}));handleRicochet550(c,p0,{op:'ricochet550',gameId:g.id,ricochetVersion550:2,kind:'rounds',rounds:16});assert.equal(g.rounds,16);assert(party.members.every(p=>!p.ready));assert.throws(()=>handleRicochet550(c,p0,{op:'ricochet550',gameId:g.id,ricochetVersion550:2,kind:'start'}));party.members.forEach(p=>p.ready=true);handleRicochet550(c,p0,{op:'ricochet550',gameId:g.id,ricochetVersion550:2,kind:'start'});assert.equal(g.phase,'play')});
test('input queue rejects NaN, spoofed IDs, old rounds, duplicates, and other players offers',()=>{const {c,g,time}=controller();start550(g,0,33);const s=c.sessions.get('p0'),offer=g.players[0].offers[0];assert(!queueRicochet550(c,s,command(g,s,1,'pick',{item:'forged'})));assert(!queueRicochet550(c,s,{...command(g,s,1,'pick',{item:offer}),gameId:'wrong'}));assert(queueRicochet550(c,s,command(g,s,1,'pick',{item:offer})));assert(!queueRicochet550(c,s,command(g,s,1,'pick',{item:offer})));time(20);advanceRicochets550(c);assert.equal(liveRicochet550(c,g).players[0].picked,offer);const rt=liveRicochet550(c,g);rt.phase='play';rt.roundAt=20;rt.elapsed=0;assert(!queueRicochet550(c,s,command(rt,s,2,'shoot',{angle:NaN,power:1})));assert(!queueRicochet550(c,s,command(rt,s,2,'shoot',{angle:0,power:2})));assert(!queueRicochet550(c,s,{...command(rt,s,2,'shoot',{angle:0,power:1}),round:0}));assert(queueRicochet550(c,s,command(rt,s,2,'shoot',{angle:0,power:1})));time(40);advanceRicochets550(c);assert(rt.players[0].launched);assert(!queueRicochet550(c,s,command(rt,s,3,'shoot',{angle:0,power:1})))});
test('empty seats fill with AI and reconnection keeps parts, charge and sequence',()=>{const {c,g,time}=controller('junkgp');g.members=g.members.slice(0,1);start550(g,0,89);assert.equal(g.players.filter(p=>p.ai).length,3);g.players[0].parts.cell=1;g.players[0].charge=22;g.players[0].lastSeq=9;c.sessions.get('p0').connected=false;for(let n=20;n<2400;n+=20){time(n);advanceRicochets550(c)}c.sessions.get('p0').connected=true;const s=ricochetSnapshot550(c,g,'p0');assert(s.players[0].picked);assert.equal(s.players[0].parts.cell,1+(s.players[0].picked==='cell'?1:0));assert(Number.isFinite(s.players[0].charge));assert.equal(s.players[0].lastSeq,9)});

test('a round boundary preserves position, velocity, max distance, charge, belt history and parts',()=>{for(const mode of ['pinball','junkgp']){const g=play(mode),p=g.players[0];Object.assign(p,{x:1.2,y:mode==='junkgp'?314:12.4,vx:8,vy:-3,maxY:mode==='junkgp'?319:18.4,charge:27,usedBelts:[0,3,4],parts:{cell:1,bank:2},wallMult:3.1});const before=structuredClone(p);finishRound550(g,C.play);for(const k of ['x','y','vx','vy','maxY','charge','wallMult'])assert.equal(p[k],before[k],mode+' resets '+k);assert.deepEqual(p.parts,before.parts);assert.deepEqual(p.usedBelts,before.usedBelts);assert.equal(g.phase,'play');assert.equal(g.round,2);assert.equal(p.launched,false);assert.equal(p.picked,null);assert.equal(p.offers.length,3);assert.equal(g.history.length,1)}});
test('coasting continues through choosing and selected players can launch without waiting for others',()=>{const g=play('junkgp'),p=g.players[0];Object.assign(p,{x:4,y:100,vx:1,vy:14,maxY:100});finishRound550(g,0);const y=p.y;g.simAt=0;advance550(g,100);assert(p.y>y);assert(g.players.every(q=>!q.picked));assert(pick550(g,p,p.offers[0]));const carry=p.vy;assert(launch550(g,p,.5,0));assert(p.vy>carry);assert(g.players.slice(1).every(q=>!q.picked))});
test('distance is counted once along one world, including backward motion',()=>{const g=play('junkgp'),p=g.players[0];Object.assign(p,{x:4,y:100,maxY:100,vx:0,vy:0});physics550(g);assert.equal(p.roundScore,980);finishRound550(g,0);assert.equal(p.score,980);assert.equal(p.roundScore,0);p.y=80;physics550(g);assert.equal(p.score+p.roundScore,980);p.y=110;physics550(g);assert.equal(p.roundScore,100);finishRound550(g,0);assert.equal(p.score,1080)});
test('world posts and rollers never shift between rounds; far reaches generate new chunks',()=>{const g=play('junkgp'),before=structuredClone(g.layout);finishRound550(g,0);assert.deepEqual(g.layout,before);g.players.forEach(p=>{p.y=5000;p.x=4;p.maxY=5000});physics550(g);assert(g.layout.posts.some(b=>b.y>5000));assert(g.layout.belts.some(b=>b.from>5000));assert(g.layout.posts.length<100)});
test('a roller requires the correct lane, and remains spent after the next shot',()=>{const g=play('junkgp'),p=g.players[0],b=g.layout.belts[0];Object.assign(p,{x:4,y:b.from+.3,vx:0,vy:4});physics550(g);assert(!p.usedBelts.includes(b.id));p.x=b.x;physics550(g);assert(p.usedBelts.includes(b.id));finishRound550(g,0);Object.assign(p,{x:b.x,y:b.from+.3,vx:0,vy:4});physics550(g);assert(p.vy<4);assert.equal(p.usedBelts.filter(n=>n===b.id).length,1)});
test('a capsule is shared, charges once and does not respawn at round boundary',()=>{const g=play('junkgp'),p=g.players[0],b=g.layout.pickups[0];Object.assign(p,{x:b.x,y:b.y,vx:0,vy:0});physics550(g);assert.equal(p.charge,18);assert.equal(g.claimed551[b.id],0);finishRound550(g,0);physics550(g);assert.equal(p.charge,18);assert.equal(g.layout.pickups.find(q=>q.id===b.id).claimed,0)});
test('catch-up wind acts through velocity and never drags fresh unlaunched players',()=>{const g=play('junkgp'),a=g.players[0],b=g.players[1];Object.assign(a,{x:4,y:200,vy:20,racing:true});Object.assign(b,{x:4,y:150,vy:0,racing:false});physics550(g);assert.equal(b.y,150);assert.equal(b.vy,0);b.racing=true;physics550(g);assert(b.vy>0);assert(b.y<150.1);assert(b.tailwind>0)});
test('old version 1 launch commands are rejected under the new continuous contract',()=>{const {c,g}=controller();start550(g,0,42);assert(!queueRicochet550(c,c.sessions.get('p0'),{...command(g,null,1,'pick',{item:g.players[0].offers[0]}),ricochetVersion550:1}))});
test('all 8/16 rounds remain in play, and only the final shot produces a result screen',()=>{for(const mode of ['pinball','junkgp'])for(const rounds of [8,16]){const g=make(mode,rounds),auto=new Set(g.players.map(p=>p.playerId));const phases=new Set([g.phase]);let old=1;for(let at=20;at<=rounds*C.play;at+=20){const y=g.players.map(p=>p.y);advance550(g,at,[],auto);phases.add(g.phase);if(g.round!==old){assert(g.players.every((p,i)=>Math.abs(p.y-y[i])<2.2));assert(g.players.every(p=>!p.launched));old=g.round}}assert.deepEqual([...phases],['play','result']);assert.equal(g.history.length,rounds);if(mode==='junkgp')for(const p of g.players)assert.equal(p.score,Math.round((p.maxY-2)*10))}});
test('saved pre-update games return safely to a fresh ready lobby instead of mixing rule versions',()=>{const {c,g,party}=controller('junkgp');start550(g,0,81);g.rules550=1;g.phase='intermission';advanceRicochets550(c);assert.equal(g.rules550,2);assert.equal(g.phase,'lobby');assert.equal(g.players.length,0);assert(party.members.every(p=>!p.ready));assert(g.notice551.includes('連続コース'))});
