import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import * as R from '../src/cart/Rules543.js';
import {COURSES544,GOLD544,parkingBonus544} from '../src/cart/Courses544.js';
import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';
import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'player '+i,choice:{id:'m'+i,speciesId:'slime'}}));
function game(round=1){const g=R.makeCart543({id:'test',code:'ABC',partyId:'p',hostId:'p0',now:0,members});R.startCart543(g,0,8);g.round=round;g.multiplier=round===5?2:1;g.phase='play';g.roundAt=0;g.lastAt=0;return g}
function roll(g,ms){for(let i=0;i<ms;i+=25){g.elapsed+=25;R.physics543(g)}}
function advance(g,ms){const end=g.lastAt+ms;while(g.lastAt<end&&g.phase!=='result')R.advanceCart543(g,g.lastAt+25)}
test('same power has visibly different outcomes on regular, wax, rug and boost floors',()=>{const positions=[1,2,3,4].map(round=>{const g=game(round);g.players=g.players.slice(0,1);R.launch543(g,g.players[0],.5);roll(g,14000);return g.players[0].y});assert(positions[1]>positions[0]+6);assert(positions[2]<positions[0]-3);assert(positions[3]>positions[0]+5)});
test('each of five courses has reachable golden parking from all four starts',()=>{const powers=[.66,.42,.88,.5,.43];for(let round=1;round<=5;round++)for(let seat=0;seat<4;seat++){const g=game(round),p=g.players[seat];g.players=[p];R.launch543(g,p,powers[round-1]);roll(g,14000);assert.equal(parkingBonus544(p),50,`round ${round}, seat ${seat}, y ${p.y}`)}});
test('boost applies once, requires forward motion, and cannot farm more speed by reentry',()=>{const g=game(4),p=g.players[0];g.players=[p];Object.assign(p,{launched:true,y:12.1,vx:0,vy:3});roll(g,25);assert(p.vy>4.5);assert(p.boosted);assert.equal(g.events.filter(e=>e.type==='boost').length,1);Object.assign(p,{y:12.1,vy:3});roll(g,25);assert(p.vy<3);assert.equal(g.events.filter(e=>e.type==='boost').length,1);p.boosted=false;p.vy=-2;roll(g,25);assert.equal(p.boosted,false);p.vy=0;roll(g,25);assert.equal(p.boosted,false)});
test('gold bonus requires the whole footprint, stationary, launched and still on the course',()=>{const p={launched:true,fallenAt:null,vx:0,vy:0,y:28.1};assert.equal(parkingBonus544(p),50);assert.equal(parkingBonus544({...p,y:GOLD544.from+.58-.0001}),0);assert.equal(parkingBonus544({...p,y:GOLD544.to-.58+.0001}),0);assert.equal(parkingBonus544({...p,vy:.1}),0);assert.equal(parkingBonus544({...p,launched:false}),0);assert.equal(parkingBonus544({...p,fallenAt:0}),0)});
test('park message and provisional gold do not bank points; collision removes the bonus immediately',()=>{const g=game(),a=g.players[0],b=g.players[1];Object.assign(a,{launched:true,x:0,y:28.1,vx:0,vy:0});roll(g,500);assert.equal(R.score543(a),143);assert.equal(a.score,0);assert.equal(g.events.filter(e=>e.type==='park'&&e.seat===0).length,1);roll(g,500);assert.equal(g.events.filter(e=>e.type==='park'&&e.seat===0).length,1);Object.assign(b,{launched:true,x:0,y:26.7,vx:0,vy:6});roll(g,100);assert(g.events.some(e=>e.type==='bump'));assert.equal(parkingBonus544(a),0);assert.equal(a.score,0)});
test('five-round scoring banks each gold once and doubles base plus bonus only in final',()=>{const g=game();for(let round=1;round<=5;round++){g.players.forEach((p,i)=>Object.assign(p,{launched:true,x:(i-1.5)*2.2,y:28.1,vx:0,vy:0}));advance(g,1050);const h=g.history.at(-1);assert.equal(h.round,round);assert(h.results.every(r=>r.base===93&&r.bonus===50&&r.points===143*(round===5?2:1)));if(round<5)advance(g,7300)}assert(g.players.every(p=>p.score===858&&p.perfects===5));assert.equal(g.winnerIds.length,4)});
test('isolated hold preview matches rolling physics for every floor and does not mutate match state',()=>{for(let round=1;round<=5;round++)for(const power of [.2,.43,.5,.66,.88,1]){const g=game(round),before=structuredClone(g),expected=R.forecast544(g,g.players[0],power);assert.deepEqual(g,before);g.players=g.players.slice(0,1);const p=g.players[0];R.launch543(g,p,power);roll(g,15000);assert(Math.abs(expected.y-p.y)<.0001);assert.equal(expected.fallen,p.fallenAt!=null);assert.equal(expected.perfect,parkingBonus544(p)>0)}});
test('AI aims vary with surface and golden bonus never exceeds bounded totals',()=>{const stats=COURSES544.map(c=>({id:c.id,gold:0,falls:0,total:0}));for(let seed=1;seed<=60;seed++){const g=game();R.startCart543(g,0,seed);const auto=new Set(members.map(p=>p.playerId));for(let i=0;i<6600&&g.phase!=='result';i++)R.advanceCart543(g,g.lastAt+25,new Map(),auto);assert.equal(g.phase,'result');for(const h of g.history)for(const r of h.results){stats[h.round-1].gold+=r.bonus>0;stats[h.round-1].falls+=r.fallen;stats[h.round-1].total+=r.points}assert(g.players.every(p=>p.score>=0&&p.score<=900))}console.log('course stats',stats);for(const s of stats){assert(s.gold>0,s.id+' gold attainable by AI');assert(s.total>0,s.id+' not an all-fall trap');assert(s.falls>0,s.id+' still risky')}});
test('old rules reset active match safely; old client cannot ready and updated lobby can start',()=>{let now=10000;const sent=[],sessions=new Map([['p0',{playerId:'p0',clientKey:'p0',connected:true,profile:{name:'a'}}]]),c=new RaceCoordinator451({now:()=>now,sessions,send:(id,m)=>sent.push(m)});const request=(op,payload={})=>c.handle(sessions.get('p0'),{op,cartVersion543:2,roster:[{id:'m',speciesId:'slime'}],...payload});request('partyCreate462',{game:'cart'});const party=partyFor462(c,'p0');let g=partyRace462(c,party);g.rules543=1;g.phase='play';g.players=[];party.members[0].ready=true;c.advanceCart543();g=partyRace462(c,party);assert.equal(g.rules543,2);assert.equal(g.phase,'lobby');assert.equal(party.members[0].ready,false);request('partyReady462',{ready:true,cartVersion543:1});assert.equal(party.members[0].ready,false);assert(sent.some(m=>m.type==='raceError451'&&m.message.includes('Build544')));g=partyRace462(c,partyFor462(c,'p0'));g.rules543=1;request('partyReady462',{ready:true});request('cart543',{gameId:g.id,kind:'start'});g=partyRace462(c,partyFor462(c,'p0'));assert.equal(g.rules543,2,JSON.stringify(sent.filter(m=>m.type==='raceError451')));assert.equal(g.phase,'countdown')});
test('all preexisting game mechanics and styles remain byte-identical to Build543',()=>{for(const dir of ['sugoroku','cabbage','canal','gorilla','luck','quiz','tower','sumo','fishing','hide','tetra','bomb'])for(const name of readdirSync(new URL('../src/'+dir+'/',import.meta.url)))assert.deepEqual(readFileSync(new URL('../src/'+dir+'/'+name,import.meta.url)),readFileSync(new URL('../../baseline543/src/'+dir+'/'+name,import.meta.url)),dir+'/'+name);for(const name of readdirSync(new URL('../../baseline543/src/Styles/',import.meta.url)))assert.deepEqual(readFileSync(new URL('../src/Styles/'+name,import.meta.url)),readFileSync(new URL('../../baseline543/src/Styles/'+name,import.meta.url)),name)});
