import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createMonster,calculatedStats} from '../src/models/Monster.js';import {learnedSkills,maxMp} from '../src/battle/SkillSystem.js';import{legacyMonsterCombatPower445,monsterCombatPower}from'../src/core/CombatPower.js';
import{normalizeDuel450,makeDuelEnemy450,duelReady450}from'../src/practice/PracticeSnapshot450.js';import{registerDuelSkills450,chooseDuelAction450,duelActionInfo450,commitDuelAction450}from'../src/practice/PracticeAI450.js';
import{PlayerPowerRanking}from'../online-server/src/PlayerPowerRanking.js';import{normalizePowerRankingSnapshot,normalizePowerRankingProfile,normalizePowerRankingState}from'../src/online/OnlinePartyClient.js';import{SPECIES}from'../src/data/species.js';import{heroAuthoredSkills}from'../src/core/HeroAllianceSystem.js';
import {ENDGAME_ULTIMATES} from '../src/data/endgameUltimates.js';
import {specialActionMultiplier} from '../src/battle/EnemyAI.js';
import {prepareDuelCircles450,duelOffense450} from '../src/practice/PracticeCombat450.js';
import {magicCircleById,magicCircleLevelEffect} from '../src/core/MagicCircleSystem.js';
import {applyEnemyDamage,createBattleRulesState} from '../src/battle/BattleRules.js';
const unit=(id='myth_rion',level=7)=>{const m=createMonster(id,{level,rank:4,plus:50,affection:1000}),stats=calculatedStats(m);return{slot:1,speciesId:id,name:SPECIES[id].name,rarity:SPECIES[id].rarity,level,power:monsterCombatPower(m),battleStats:stats,equipment:[],equipmentStatus:'complete',duel:normalizeDuel450({version:1,stats,maxMp:maxMp(m),skills:learnedSkills(m),plus:m.plus,rank:m.rank,affection:m.affection,element:SPECIES[id].element})};};
const session={playerId:'AD-ABCD-EFGH'},now=Date.now();
test('snapshot survives client/server/restart/profile; canonical ranking power unchanged',()=>{const file=join(mkdtempSync(join(tmpdir(),'practice450-')),'rank.json'),m=unit(),packet=normalizePowerRankingSnapshot({displayName:'より',maxFloor:2,party:[m],power:m.power});let r=new PlayerPowerRanking({stateFile:file,now:()=>now});assert.equal(r.submit(session,{requestId:'practice450-save-001',snapshot:packet}).ok,true);const stored=JSON.parse(readFileSync(file));assert.equal(stored.records[0].party[0].duel.plus,50);assert.equal(stored.records[0].party[0].power,1962);r=new PlayerPowerRanking({stateFile:file,now:()=>now});const profile=normalizePowerRankingProfile(r.profile(session,{playerId:session.playerId}).message.profile);assert.equal(profile.party[0].duel.plus,50);assert.deepEqual(profile.party[0].duel.stats,m.duel.stats);assert.equal(profile.party[0].power,5159);const list=normalizePowerRankingState(r.list(session).message);assert.equal(list.entries[0].duelReady450,true);assert.equal(r.submit(session,{requestId:'practice450-save-001',snapshot:packet}).duplicate,true);});
test('old records remain readable and do not invent duel data',()=>{const m=unit();delete m.duel;const r=new PlayerPowerRanking({now:()=>now});assert.equal(r.submit(session,{requestId:'practice450-old-data',snapshot:{maxFloor:2,displayName:'old',party:[m],power:m.power}}).ok,true);assert.equal(r.list(session).message.entries[0].duelReady450,false);assert.equal(r.profile(session,{playerId:session.playerId}).message.profile.party[0].duel,null);});
test('all four party slots round trip; snapshot is bounded and does not contain save/account data',()=>{const party=['myth_rion','myth_yori','myth_hide','myth_enami'].map((id,i)=>({...unit(id,10000),slot:i+1})),r=new PlayerPowerRanking({now:()=>now});assert.equal(r.submit(session,{requestId:'practice450-four-members',snapshot:{maxFloor:100,party,power:party.reduce((s,m)=>s+m.power,0)}}).ok,true);assert.ok(duelReady450(r.profile(session,{playerId:session.playerId}).message.profile.party));const s=normalizeDuel450({...party[0].duel,inventory:{gold:99},sessionToken:'secret',settings:{}});assert.equal(s.inventory,undefined);assert.equal(s.sessionToken,undefined);assert.ok(JSON.stringify(s).length<14000);});
test('invalid stats / oversized payload and prototype keys are rejected or removed',()=>{const s=unit().duel;assert.equal(normalizeDuel450({...s,stats:{...s.stats,hp:NaN}}),null);assert.equal(normalizeDuel450({...s,skills:Array(5).fill({})}),null);assert.equal(normalizeDuel450({...s,blob:'x'.repeat(14001)}),null);const clean=normalizeDuel450({...s,affixes:JSON.parse('{"__proto__":{"polluted":true},"damageReduction":10}')});assert.equal(Object.hasOwn(clean.affixes,'__proto__'),false);const m=unit();m.duel.stats.atk+=1000;assert.equal(new PlayerPowerRanking({now:()=>now}).submit(session,{requestId:'practice450-mismatch',snapshot:{party:[m],power:m.power}}).code,'POWER_DUEL_INVALID');});
test('opponent preserves captured stats, circle and identity without floor buffs',()=>{const m=unit(),original=structuredClone(m),circle={id:'test',level:7};const e=makeDuelEnemy450(m,2,{species:SPECIES[m.speciesId],circle});assert.equal(e.hp,m.duel.stats.hp);assert.equal(e.atk,m.duel.stats.atk);assert.equal(e.maxMp,m.duel.maxMp);assert.equal(e.plus,50);assert.equal(e.uncapturable,true);assert.deepEqual(e.enemyMagicCircle,circle);assert.deepEqual(m,original);assert.deepEqual(heroAuthoredSkills(e),m.duel.skills);});
test('AI heals/revives situationally, respects MP and cooldown, falls back safely',()=>{const m=unit('slime'),e=makeDuelEnemy450(m,0,{species:SPECIES.slime,circle:null});e.duel450.skills=[{id:'hit',name:'攻撃',type:'attack',power:2,mp:2,cooldown:2},{id:'heal',name:'回復',type:'allHeal',heal:.4,power:.4,mp:5},{id:'revive',name:'蘇生',type:'revive',power:.3,mp:5}];registerDuelSkills450(e);const b={turn:1},opp=[{currentHp:100}];let a=chooseDuelAction450(e,{allies:[e],opponents:opp,battle:b});assert.equal(duelActionInfo450(a).id,'hit');commitDuelAction450(e,a,1);assert.equal(chooseDuelAction450(e,{allies:[e],opponents:opp,battle:b}),'attack');e.hp=1;a=chooseDuelAction450(e,{allies:[e],opponents:opp,battle:b});assert.equal(duelActionInfo450(a).id,'heal');a=chooseDuelAction450(e,{allies:[e,{hp:0,maxHp:100}],opponents:opp,battle:b});assert.equal(duelActionInfo450(a).id,'revive');e.currentMp=0;assert.equal(chooseDuelAction450(e,{allies:[e],opponents:opp,battle:b}),'guard');});
test('guard expires and ultimate cannot bypass its dedicated availability checks',()=>{
 const e=makeDuelEnemy450(unit('slime'),0,{species:SPECIES.slime,circle:null});
 e.duel450.skills=[ENDGAME_ULTIMATES.ten_time];registerDuelSkills450(e);e.guard=true;
 assert.equal(chooseDuelAction450(e,{allies:[e],battle:{turn:1}}),'attack');assert.equal(e.guard,false);
 e.duel450.skills=[{id:'power-test',name:'威力確認',power:3.25,mp:1,type:'attack'}];registerDuelSkills450(e);
 assert.equal(specialActionMultiplier(chooseDuelAction450(e,{allies:[e],battle:{turn:1}})),3.25);
});
test('captured raid shield and chapter-II MP circle use their actual levels',()=>{
 const profile=id=>{const c=magicCircleById(id);return{...c,level:7,levelEffect:magicCircleLevelEffect(c,7)}};
 const e=makeDuelEnemy450(unit('slime'),0,{species:SPECIES.slime,circle:profile('raid_zero_sovereign')}),other=makeDuelEnemy450(unit('slime'),1,{species:SPECIES.slime,circle:null});
 const b={specialBattleType:'practice450',enemies:[e,other],party:[]};prepareDuelCircles450(b);
 assert.equal(other._floorBossHpShield,Math.floor(other.maxHp*e.enemyMagicCircle.levelEffect.shieldRate));assert.ok(duelOffense450(b,e,null)>1);
 e.enemyMagicCircle=profile('ch2_reserve398');e.currentMp=e.maxMp;const high=duelOffense450(b,e,null);e.currentMp=0;assert.ok(high>duelOffense450(b,e,null));
});
test('native damage resolves a captured revival once without negative damage',()=>{
 const c=magicCircleById('reincarnation'),e=makeDuelEnemy450(unit('slime'),0,{species:SPECIES.slime,circle:{...c,level:1,levelEffect:magicCircleLevelEffect(c,1)}}),b={...createBattleRulesState([]),party:[],enemies:[e],turn:1};e.hp=1;
 const first=applyEnemyDamage(b,e,e.maxHp*10);assert.ok(first.damage>=0);assert.ok(e.hp>1);assert.equal(b.reviveCount,1);
 applyEnemyDamage(b,e,e.maxHp*10);assert.equal(e.hp,0);assert.equal(b.reviveCount,1);
});
test('native practice flow ends at the round limit before another action',async()=>{
 const {run}=await import('../tools/build430/native-harness.mjs');const{b,context,nativeContinue}=await run(['slime'],['slime'],{inspect:true,battleOptions:{specialBattle:true,specialBattleType:'practice450'}});
 b.turn=101;let outcome=null;context.finishPractice450=result=>{outcome=result};await nativeContinue();assert.equal(outcome,'引き分け');
});
