import{CABBAGE484 as RULES486}from'../src/cabbage/Rules484.js';
// Real coordinator integration. Only the two absent base-game catalogs use fixtures
// in a partial patch checkout. A complete checkout uses its real catalogs.
import test from 'node:test';
import assert from 'node:assert/strict';
import{registerHooks}from'node:module';
import{existsSync,mkdtempSync,rmSync,readFileSync}from'node:fs';
import{tmpdir}from'node:os';
import{join}from'node:path';
const fixtures={
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,context,next){const url=spec.startsWith('.')?new URL(spec,context.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,context)},load(url,context,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,context)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');hook.deregister();
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,cabbageVersion484:1,cabbageScoring491:1,...extra});const errors=packets.slice(before).filter(p=>p.m.type==='raceError451');return errors};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function open(x,n=4){assert.deepEqual(x.send(0,'partyCreate462',{displayName:'Host',roster:[{id:'m0',speciesId:'wolf'}],game:'cabbage'}),[]);const p=Object.values(x.c.data.parties462)[0];for(let i=1;i<n;i++)assert.deepEqual(x.send(i,'partyJoin462',{code:p.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);const g=x.c.data.cabbageRooms484[p.code];for(let i=0;i<n;i++){assert.deepEqual(x.send(i,'cabbage484',{gameId:g.id,kind:'select',monsterId:'m'+i}),[]);assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[])}return{g,p}}

test('real party route: 4 people create/join/select/ready/start/input/result/rematch/switch games',()=>{const x=setup(),{g,p}=open(x);assert.equal(x.c.view(x.sessions.get('p0')).cabbage.phase,'lobby');assert.equal(x.c.view(x.sessions.get('p0')).room,null);assert.deepEqual(x.send(0,'cabbage484',{gameId:g.id,kind:'start'}),[]);assert.equal(x.c.active('p0'),true);x.time(g.startAt+200);for(let i=0;i<4;i++)x.send(i,'cabbageTap484',{gameId:g.id,taps:[{seq:1,side:'left',at:x.now()}]});x.time(g.startAt+500);x.c.advance();assert.deepEqual(g.players.map(p=>p.score),[10,10,10,10]);assert.equal(x.c.healthy(),true);x.time(g.endAt+RULES486.maxAge+250);x.c.advance();assert.equal(g.phase,'result');assert.equal(x.c.active('p0'),false);assert.equal(x.c.view(x.sessions.get('p2')).cabbage.results.length,4);assert.deepEqual(x.send(0,'partyGame462',{game:'cabbage'}),[]);const next=x.c.data.cabbageRooms484[p.code];assert.notEqual(next.id,g.id);assert.equal(next.members.length,4);assert.ok(p.members.every(m=>!m.ready));assert.deepEqual(x.send(0,'partyGame462',{game:'sugoroku'}),[]);assert.equal(x.c.view(x.sessions.get('p0')).sugoroku.phase,'lobby');assert.equal(x.c.view(x.sessions.get('p0')).cabbage,null);assert.deepEqual(x.send(0,'partyGame462',{game:'race'}),[]);assert.equal(x.c.view(x.sessions.get('p0')).room.phase,'lobby');assert.equal(x.c.data.cabbageRooms484[p.code],undefined)});
test('spectator joins midgame, receives score view, cannot tap and participates next game',()=>{const x=setup(),{g,p}=open(x,1);x.send(0,'cabbage484',{gameId:g.id,kind:'start'});assert.deepEqual(x.send(1,'partyJoin462',{code:p.code,roster:[{id:'m1',speciesId:'slime'}]}),[]);assert.equal(x.c.view(x.sessions.get('p1')).party.members[1].spectating,true);x.time(g.startAt+200);x.send(1,'cabbageTap484',{gameId:g.id,taps:[{seq:1,side:'left',at:x.now()}]});assert.equal(g.players.some(p=>p.playerId==='p1'),false);x.time(g.endAt+RULES486.maxAge+250);x.c.advance();x.send(0,'partyGame462',{game:'cabbage'});assert.equal(x.c.data.cabbageRooms484[p.code].members.length,2)});
test('durable restart restores scores and sequence ACK; duplicate old input cannot earn again',()=>{const dir=mkdtempSync(join(tmpdir(),'cabbage484-'));try{const file=join(dir,'state.json'),x=setup(1,file),{g}=open(x,1);x.send(0,'cabbage484',{kind:'start',gameId:g.id});x.time(g.startAt+200);const taps=[{seq:1,side:'left',at:x.now()}];x.send(0,'cabbageTap484',{gameId:g.id,taps});x.time(g.startAt+300);x.c.advance();assert.equal(JSON.parse(readFileSync(file)).cabbageRooms484[g.code].players[0].score,10);const y=setup(1,file);y.time(g.startAt+400);y.send(0,'cabbageTap484',{gameId:g.id,taps});y.time(g.startAt+600);y.c.advance();assert.equal(y.c.data.cabbageRooms484[g.code].players[0].score,10);assert.equal(y.c.view(y.sessions.get('p0')).cabbage.players[0].lastSeq,1);y.time(g.endAt+RULES486.maxAge+250);y.c.advance();assert.equal(y.c.view(y.sessions.get('p0')).cabbage.phase,'result')}finally{rmSync(dir,{recursive:true,force:true})}});
test('clock sync has authenticated identity and queue inputs do not broadcast or write per tap',()=>{const x=setup(1),{g}=open(x,1);x.send(0,'cabbage484',{gameId:g.id,kind:'start'});x.time(g.startAt+100);const revision=x.c.data.revision,count=x.packets.length;x.send(0,'cabbageTap484',{gameId:g.id,taps:[{seq:1,side:'right',at:x.now()}]});assert.equal(x.c.data.revision,revision);assert.equal(x.packets.length,count);x.send(0,'cabbageClock484',{clientSent:999});assert.deepEqual(x.packets.at(-1).m,{type:'cabbageClock484',selfId:'p0',clientSent:999,serverNow:x.now()})});
