import test from 'node:test';import assert from 'node:assert/strict';
import * as R from '../src/hide/Rules536.js';import * as M from '../src/hide/Map537.js';
import {queueHide536,liveHide536} from '../online-server/src/HideCoordinator536.js';import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'P'+i,owned:[{id:'m'+i,speciesId:'slime'}],choice:{id:'m'+i,speciesId:'slime'}}));
function make(seed=538){const g=R.makeHide536({id:'538',code:'ABC',partyId:'party',hostId:'p0',members});g.role='hunter';R.startHide536(g,0,seed);return g}
const advance=(g,ms,inputs=new Map())=>{const end=g.lastAt+ms;while(g.lastAt<end&&g.phase!=='result')R.advanceHide536(g,Math.min(end,g.lastAt+50),inputs)};
const play=()=>{const g=make();advance(g,20000);return g};
test('100 estates: 4800×4400 continuous grounds, connected manor and exits, all 12 props, contextual placement',()=>{const layouts=new Set();for(let seed=1;seed<=100;seed++){const m=M.makeMap537(seed),objects=M.furniture537(m,seed);assert.equal(m.width,4800);assert.equal(m.height,4400);assert.equal(m.rooms.length,9);const nodes=M.nav537(m),by=new Map(nodes.map(p=>[p.i,p])),start=M.nearest537(m,m.spawn),seen=new Set([start.i]),queue=[start.i];for(let n=0;n<queue.length;n++){const p=by.get(queue[n]);for(const d of [-48,48,-1,1]){const q=by.get(p.i+d);if(!q||seen.has(q.i)||Math.hypot(q.x-p.x,q.y-p.y)>101||!M.line537(m,p,q,24))continue;seen.add(q.i);queue.push(q.i)}}assert.equal(seen.size,nodes.length,'all navigation cells reachable seed '+seed);layouts.add(JSON.stringify(m.cells));for(const p of [...m.rooms.map(r=>({x:r.cx,y:r.cy})),m.hunter,{x:650,y:3550},{x:4250,y:3650}])assert.ok(M.path537(m,m.spawn,p).length,'map '+seed+JSON.stringify(p));assert.equal(new Set(objects.map(o=>o.kind)).size,12);assert.ok(objects.length<100);assert.ok(objects.every(o=>o.zone&&o.zone!=='木漏れ日の森'));assert.ok(objects.filter(o=>o.kind===8).every(o=>o.zone==='石造りの厨房'));assert.ok(objects.filter(o=>o.kind===1).every(o=>o.zone==='食料貯蔵庫'));assert.ok(m.decor.some(d=>d.kind===9)&&m.decor.some(d=>d.kind===7))}assert.ok(layouts.size>95)});
test('three-charge capacity: zero does not end match; ten-second replenishment cannot bank beyond three',()=>{const g=play(),h=g.players[0];for(let i=0;i<3;i++){const o=g.objects[i];Object.assign(h,{x:o.x,y:o.y});g.shotReadyAt=0;assert.ok(R.attackHide536(g,h,o.id))}assert.equal(g.shots,0);assert.equal(g.phase,'play');assert.equal(g.rechargeAt,10000);advance(g,9950);assert.equal(g.shots,0);advance(g,50);assert.equal(g.shots,1);advance(g,20000);assert.equal(g.shots,3);assert.equal(g.rechargeAt,0);advance(g,30000);assert.equal(g.shots,3);Object.assign(h,g.objects[4]);g.shotReadyAt=0;assert.ok(R.attackHide536(g,h,g.objects[4].id));assert.equal(g.rechargeAt,g.elapsed+10000);advance(g,9950);assert.equal(g.shots,2);advance(g,50);assert.equal(g.shots,3)});
test('15 seconds of actual movement exhausts hider; half speed then stop-to-recover; hunter has no fatigue',()=>{const g=play(),p=g.players[1],h=g.players[0],q=M.nav537(g.map).find(q=>M.line537(g.map,q,{x:q.x+180,y:q.y},24));Object.assign(p,{x:q.x,y:q.y});Object.assign(h,{x:q.x,y:q.y});const inputs=new Map();function walk(ms){for(let t=0;t<ms;t+=50){const sign=Math.floor(g.elapsed/400)%2?-1:1;for(const who of [h,p])inputs.set(who.playerId,{steer:{x:sign,y:0},receivedAt:g.lastAt});advance(g,50,inputs)}}
 // Start far enough into the clear segment for alternating movement in both directions.
 p.x+=80;h.x+=80;walk(14950);assert.equal(p.stamina,50);assert.equal(p.exhausted,false);walk(50);assert.equal(p.stamina,0);assert.ok(p.exhausted);const hd=h.distance,pd=p.distance;walk(2000);assert.ok(Math.abs(h.distance-hd-460)<.001);assert.ok(Math.abs(p.distance-pd-230)<.001);advance(g,550);assert.equal(p.stamina,0);advance(g,1500);assert.equal(p.exhausted,false);assert.ok(p.stamina>=4500);advance(g,4000);assert.equal(p.stamina,15000)});
test('standing at a wall does not drain stamina; preparation permits movement without consuming it',()=>{const g=make(),p=g.players[1],q=M.nav537(g.map).find(q=>M.line537(g.map,q,{x:q.x+180,y:q.y},24));Object.assign(p,{x:q.x,y:q.y});advance(g,500,new Map([['p1',{target:{x:q.x+100,y:q.y}}]]));assert.equal(p.stamina,15000);assert.ok(p.distance>0);advance(g,20000);p.stamina=5000;advance(g,1500);assert.ok(p.stamina>5000)});
test('two distinct disguise candidates lock at start; 30-second shake includes moving hiders',()=>{const g=make(),p=g.players[1];assert.equal(new Set(p.choices).size,2);advance(g,50,new Map([['p1',{kind:p.choices[1]}]]));assert.equal(p.kind,p.choices[1]);advance(g,19950);advance(g,50,new Map([['p1',{kind:p.choices[0]}]]));assert.equal(p.kind,p.choices[1]);advance(g,29900);assert.equal(R.shaking537(g),false);advance(g,50);assert.ok(R.shaking537(g));const events=g.events.filter(e=>e.type==='shake');assert.equal(events.length,1);assert.equal(events[0].x,undefined);advance(g,2400);assert.equal(R.shaking537(g),false)});
test('all allied positions shared at any distance, never leaked to hunter; map/frame and prop schemas conceal identity',()=>{const g=play();Object.assign(g.players[1],g.map.spawn);Object.assign(g.players[2],g.map.hunter);assert.ok(R.HIDE536.sight<R.HIDE536.hiderSight);const ally=R.publicHide536(g,'p1'),hunt=R.publicHide536(g,'p0');assert.ok(Number.isFinite(ally.players[2].x));for(const p of hunt.players.filter(p=>!p.hunter))for(const k of ['x','y','kind','objectId','choices','stamina','brain','route'])assert.equal(p[k],undefined,k);for(const o of hunt.objects){assert.equal(o.zone,undefined);assert.equal(o.owner,undefined);assert.equal(o.seat,undefined)}assert.equal(R.publicHide536(g,'p1',{frame:true}).map,undefined);assert.equal(hunt.map.width,4800)});
test('attack checks role, range, walls, repeat and cooldown; zero final charge can capture the third hider',()=>{const g=play(),h=g.players[0],q=M.nav537(g.map).find(q=>M.line537(g.map,q,{x:q.x+100,y:q.y},24));Object.assign(h,{x:q.x,y:q.y});g.players.slice(1).forEach((p,i)=>Object.assign(p,{x:q.x+55+i*15,y:q.y}));assert.equal(R.attackHide536(g,g.players[1],g.players[2].objectId),false);assert.equal(R.attackHide536(g,h,'invalid'),false);for(let i=1;i<4;i++){g.shotReadyAt=0;assert.ok(R.attackHide536(g,h,g.players[i].objectId));assert.equal(R.attackHide536(g,h,g.players[i].objectId),false)}assert.equal(g.shots,0);assert.equal(g.winningSide,'hunter')});
test('tap path stays out of walls and furniture across indoor/outdoor travel',()=>{const g=play(),p=g.players[1],goal=g.map.hunter,input=new Map([['p1',{target:goal}]]);for(let t=0;t<80000&&Math.hypot(p.x-goal.x,p.y-goal.y)>2;t+=50){advance(g,50,input);assert.ok(M.free537(g.map,p.x,p.y))}assert.ok(Math.hypot(p.x-goal.x,p.y-goal.y)<2)});
function rig(){let now=100000;const messages=[],sessions=new Map(members.map(m=>[m.playerId,{playerId:m.playerId,clientKey:m.playerId,connected:true,profile:{name:m.name}}]));const c=new RaceCoordinator451({sessions,now:()=>now,send:(id,msg)=>messages.push({id,...msg})}),q=(i,op,extra={})=>{messages.length=0;c.handle(sessions.get('p'+i),{op,rulesVersion:8,hideVersion536:3,roster:members[i].owned,displayName:members[i].name,...extra});return messages.find(m=>m.type==='raceError451')};q(0,'partyCreate462',{game:'hide'});const party=partyFor462(c,'p0');for(let i=1;i<4;i++)q(i,'partyJoin462',{code:party.code});return{c,q,party,sessions,messages,game:()=>partyRace462(c,party),tick(ms){for(let t=0;t<ms;t+=50){now+=50;c.advanceHide536()}}}}
test('coordinator integration, reconnect, old-version gate, private frames and replay',()=>{const t=rig(),g=t.game();t.q(0,'hide536',{gameId:g.id,kind:'role',role:'hunter'});for(let i=0;i<4;i++){t.q(i,'hide536',{gameId:g.id,kind:'select',monsterId:'m'+i});assert.equal(t.q(i,'partyReady462',{ready:true}),undefined)}assert.equal(t.q(0,'hide536',{gameId:g.id,kind:'start'}),undefined);t.tick(20100);const live=liveHide536(t.c,t.game());assert.equal(live.phase,'play');assert.equal(queueHide536(t.c,t.sessions.get('p1'),{gameId:g.id,hideVersion536:2,kind:'input',seq:1}),false);assert.equal(t.c.view(t.sessions.get('p0')).hide.players[1].x,undefined);assert.ok(t.c.view(t.sessions.get('p1')).hide.players[2].x);assert.equal(t.messages.find(m=>m.type==='hideFrame536').hide.map,undefined);t.sessions.get('p1').connected=false;t.tick(100);assert.ok(live.players[1].auto);t.sessions.get('p1').connected=true;t.tick(100);assert.equal(live.players[1].auto,false);R.finishHide536(live,'hiders','time');t.tick(50);assert.equal(t.q(0,'partyResult490',{partyId:t.party.id,gameId:g.id,kind:'again'}),undefined);assert.equal(t.game().phase,'lobby')});
test('Build537 active matches migrate to lobby, preserving membership and choices',()=>{const t=rig(),g=t.game();g.rulesVersion=2;g.phase='play';t.tick(50);assert.equal(t.game().rulesVersion,3);assert.equal(t.game().phase,'lobby');assert.equal(t.game().members.length,4)});
test('AI matches and serialized restart preserve stamina/recharge and reach a valid result',()=>{for(const seed of [14,538,973]){const g=make(seed);g.players.forEach(p=>p.ai=true);advance(g,55000);const b=JSON.parse(JSON.stringify(g));advance(g,155000);advance(b,155000);assert.deepEqual(g,b);assert.equal(g.phase,'result');assert.equal(g.results.length,4);assert.ok(g.shots>=0&&g.shots<=3);assert.ok(g.players.every(p=>M.free537(g.map,p.x,p.y)));assert.ok(g.players.every(p=>p.stamina>=0&&p.stamina<=15000))}});
