import test from'node:test';import assert from'node:assert/strict';import{mkdtempSync,rmSync,readFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{RaceCoordinator451}from'../online-server/src/RaceCoordinator451.js';
import{raceProfile451,raceForecast455,drawRace451,odds451,RACE451}from'../src/race/RaceRules451.js';
import{nextFatigue455}from'../src/race/RaceStrategy455.js';
function fixture(file=null){let at=100000;const sessions=new Map(Array.from({length:4},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key-455-long-'+i,connected:true}])),errors=[],options={stateFile:file,sessions,now:()=>at,send:(id,m)=>{if(m.type==='raceError451')errors.push(m)}};let c=new RaceCoordinator451(options);const f={get c(){return c},sessions,errors,call(op,payload={},i=0){c.handle(sessions.get('p'+i),{op,rulesVersion:3,...payload})},view(i=0){return c.view(sessions.get('p'+i))},step(n){at+=n;c.advance()},restart(){c=new RaceCoordinator451(options)},roster:[{id:'a',speciesId:'slime'},{id:'b',speciesId:'slime'},{id:'c',speciesId:'wolf'}],create(humans=1,version=3){this.call('create',{roster:this.roster,rulesVersion:version});for(let i=1;i<humans;i++)this.call('join',{code:this.view().room.code,roster:this.roster,rulesVersion:version},i)},start(humans=1){for(let i=0;i<humans;i++)this.call('select',{monsterId:'a'},i);this.call('start')},finish(){this.step(120001);this.step(RACE451.countdownMs);this.step(RACE451.raceMs)},ack(){for(let i=0;i<4;i++)if(c.data.accounts['p'+i])this.call('ack',{ids:this.view(i).deliveries.map(e=>e.id)},i)}};return f}
function unique(room){const humans=new Set(room.members.filter(m=>!m.ai).map(m=>m.playerId)),playerSpecies=new Set(room.racers.filter(r=>humans.has(r.ownerId)).map(r=>r.speciesId)),others=room.racers.filter(r=>!humans.has(r.ownerId)).map(r=>r.speciesId);assert.equal(new Set(others).size,others.length);assert.ok(others.every(id=>!playerSpecies.has(id)));assert.equal(room.racers.length,8)}
test('1–4 humans may duplicate, every AI/system entrant remains different (400 rooms)',()=>{for(let humans=1;humans<=4;humans++)for(let n=0;n<100;n++){const h=fixture();h.create(humans);h.start(humans);const r=h.view().room;assert.equal(r.phase,'parade');assert.equal(r.rulesVersion,3);unique(r);assert.equal(r.racers.filter(x=>x.speciesId==='slime').length,humans);assert.deepEqual(h.errors,[])}});
test('late human choice replaces both conflicting provisional system and AI picks before odds lock',()=>{const h=fixture();h.create(2);h.call('select',{monsterId:'a'});h.call('start');assert.equal(h.view().room.phase,'entry');const r=h.c.roomFor('p0'),id=r.system[0].speciesId;r.members.find(m=>m.ai).choice.speciesId=id;h.call('select',{monsterId:'late',roster:[{id:'late',speciesId:id}]},1);unique(h.view().room);assert.equal(h.view().room.members[1].choice.speciesId,id);assert.deepEqual(h.errors,[])});
test('selection timeout uses owned creature and deduplicates the full field',()=>{const h=fixture();h.create();h.call('start');const r=h.c.roomFor('p0');r.system[0]=h.c.entrant('slime',null,null,3);h.step(RACE451.entryMs);unique(h.view().room)});
test('fatigue advances once per completed race, rests one step, persists across rooms/restart and copies',()=>{const dir=mkdtempSync(join(tmpdir(),'race455-'));try{const h=fixture(join(dir,'r.json'));h.create();h.start();assert.equal(h.view().room.racers[4].fatigue455,0);assert.deepEqual(h.view().fatigue455,{});h.finish();assert.equal(h.view().fatigue455.slime,1);h.step(5);h.restart();assert.equal(h.view().fatigue455.slime,1);h.ack();h.call('again');h.call('select',{monsterId:'b'});h.call('start');assert.equal(h.view().room.racers[4].fatigue455,1);h.finish();assert.equal(h.view().fatigue455.slime,2);h.ack();h.call('leave');h.create();h.call('select',{monsterId:'c'});h.call('start');assert.equal(h.view().room.racers[4].fatigue455,0);h.finish();assert.equal(h.view().fatigue455.slime,1);assert.equal(h.view().fatigue455.wolf,1);assert.deepEqual(h.errors,[])}finally{rmSync(dir,{recursive:true,force:true})}});
test('fatigue never exceeds three; old values recover and identical species share a key',()=>{let f={};for(let i=0;i<20;i++)f=nextFatigue455(f,'slime');assert.deepEqual(f,{slime:3});f=nextFatigue455(f,'wolf');assert.deepEqual(f,{slime:2,wolf:1});f=nextFatigue455(f,'wolf');assert.deepEqual(f,{slime:1,wolf:2});f=nextFatigue455(f,'wolf');assert.deepEqual(f,{wolf:3})});
test('fatigue and all results roll back together when persistence fails',()=>{const h=fixture();h.create();h.start();h.step(120001);h.step(RACE451.countdownMs);const old=h.c.stateFile;h.c.stateFile='/dev/null/race.json';h.step(RACE451.raceMs);assert.equal(h.view().room.phase,'race');assert.deepEqual(h.view().fatigue455,{});h.c.stateFile=old;h.step(1);assert.equal(h.view().room.phase,'result');assert.equal(h.view().fatigue455.slime,1);assert.equal(h.view().deliveries.length,1)});
test('v3 bets lock published odds; restart neither redraws nor reveals result before finish',()=>{const dir=mkdtempSync(join(tmpdir(),'race455-'));try{const h=fixture(join(dir,'r.json'));h.create();h.start();const r=h.view().room,f=raceForecast455(r.racers,r.course),t={kind:'win',picks:[f.find(x=>x.rank===1).index]},odds=odds451(r.racers,r.course,t),packet={raceId:r.id,requestId:r.id+':p0',amount:1000,ticket:t};h.call('bet',packet);const outcome=structuredClone(h.c.roomFor('p0').outcome);h.restart();h.call('bet',packet);assert.deepEqual(h.c.roomFor('p0').outcome,outcome);assert.equal(h.view().room.members[0].selfTicket.odds,odds);assert.equal(h.view().room.order,null);assert.equal(h.view().room.finishMs,null);assert.equal(h.view().room.members[1].ticket,null);h.finish();const row=h.view().room.results[0];assert.equal(row.ticket.odds,odds);h.step(1);assert.equal(h.view().deliveries.length,1);assert.equal(h.view().fatigue455.slime,1)}finally{rmSync(dir,{recursive:true,force:true})}});
test('older rooms keep their accepted outcome/odds/rules and cannot be joined by incompatible clients',()=>{const h=fixture();h.create(1,2);h.start();const old=structuredClone(h.c.roomFor('p0').outcome);h.call('bet',{raceId:h.view().room.id,requestId:h.view().room.id+':p0',amount:1000,ticket:{kind:'win',picks:[0]}});h.finish();assert.equal(h.view().room.rulesVersion,2);assert.deepEqual(h.c.roomFor('p0').outcome,old);assert.deepEqual(h.view().fatigue455,{});h.ack();h.call('again');assert.equal(h.view().room.rulesVersion,2);const fresh=fixture();fresh.create();fresh.call('join',{rulesVersion:2,roster:fresh.roster,code:fresh.view().room.code},1);assert.equal(fresh.view(1).room,null);assert.match(fresh.errors.at(-1).message,/更新/)});
test('same conditions are a genuine 8-way tie; fatigue reduces chance without eliminating a runner',()=>{const racers=Array.from({length:8},()=>({rulesVersion:3,speciesId:'slime',profile:raceProfile451('slime'),condition:2,fatigue455:0}));const first=raceForecast455(racers,'砂');assert.ok(first.every(x=>x.rank===1&&x.probability===.125));racers[0].fatigue455=3;const tired=raceForecast455(racers,'砂');assert.ok(tired[0].probability>0&&tired[0].probability<.125);const extreme=racers.map((x,i)=>({...x,condition:i?0:4,fatigue455:i?3:0}));assert.ok(Math.max(...raceForecast455(extreme,'砂').map(x=>x.probability))<=.800000001)});
