import test from 'node:test';import assert from 'node:assert/strict';import{mkdtempSync,readFileSync,rmSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{RaceCoordinator451}from'../online-server/src/RaceCoordinator451.js';
import{RACE451,payout451,raceProfile451,drawRace451,ticketWins451,odds451,raceProgress451,raceWeight451}from'../src/race/RaceRules451.js';
import{activeRaceSkill453,trainingReward453}from'../src/race/RaceTraits453.js';
import{reserveRaceBet451,applyRaceDelivery451,raceBank451}from'../src/race/RaceWallet451.js';
import{createMonster,totalExperience,expNeedFor}from'../src/models/Monster.js';
import{SPECIES}from'../src/data/species.js';import{ENDGAME_CHARACTERS}from'../src/data/endgameCharacters.js';
import{raceDomSignature452}from'../src/race/RacePresentation452.js';
function harness(file=null){let time=100000;const sessions=new Map(),messages=new Map();for(let i=0;i<5;i++){const id='AD-RACE-000'+i;sessions.set(id,{playerId:id,clientKey:'fixture-key-long-enough-'+i,connected:true,profile:{displayName:'友達'+i}});messages.set(id,[])}const options={stateFile:file,sessions,send:(id,m)=>messages.get(id).push(structuredClone(m)),now:()=>time};let c=new RaceCoordinator451(options);return{get c(){return c},sessions,messages,s(i=0){return[...sessions.values()][i]},call(op,payload={},i=0){c.handle(this.s(i),{op,rulesVersion:2,...payload})},state(i=0){return c.view(this.s(i))},restart(){c=new RaceCoordinator451(options)},advance(n){time+=n;c.advance()},roster:[{id:'m1',speciesId:'slime'},{id:'m2',speciesId:'myth_rion'}],make(humans=1){this.call('create',{roster:this.roster,displayName:'えなみ'});for(let i=1;i<humans;i++)this.call('join',{code:this.state().room.code,roster:this.roster},i);for(let i=0;i<humans;i++)this.call('select',{monsterId:'m1'},i);this.call('start');return this.state().room},bet(ticket={kind:'win',picks:[0]},amount=1000,i=0){const raceId=this.state(i).room.id;const packet={raceId,requestId:`${raceId}:${this.s(i).playerId}`,amount,ticket};this.call('bet',packet,i);return packet},finish(){this.advance(RACE451.betMs);this.advance(RACE451.countdownMs);this.advance(RACE451.raceMs)}}}
function wallet(){return{state:{player:{gold:10000},monsters:[{...createMonster('slime',{level:9}),id:'m1',affection:0}]},save:()=>true}}
test('all 334 creature identities use 210 points and no combat progression multiplier',()=>{const ids=[...Object.keys(SPECIES),...Object.keys(ENDGAME_CHARACTERS)];for(const id of ids){const p=raceProfile451(id);assert.equal(p.speed+p.stamina+p.technique,210,id);assert.equal(p.version,2);assert.ok(p.skillDescription.length>8);assert.ok(['芝','砂'].includes(p.ground))}assert.notEqual(raceProfile451('slime').skill,raceProfile451('ten_time').skill);assert.equal(raceProfile451('myth_rion').style,'逃げ')});
test('every skill trajectory is monotonic, finishes exactly once and has a real acceleration window',()=>{for(const id of [...Object.keys(SPECIES),...Object.keys(ENDGAME_CHARACTERS)]){const r={profile:raceProfile451(id)},finish=21000;let last=0;for(let t=0;t<=28000;t+=50){const p=raceProgress451(r,t,finish);assert.ok(p>=last-1e-9,id+' '+t);assert.ok(p>=0&&p<=1);if(t<finish)assert.ok(p<1,id+' early finish');last=p}const t=r.profile.skillAt+1200;assert.equal(activeRaceSkill453(r,t),true);assert.ok(raceProgress451(r,t,finish)>Math.pow(t/finish,r.profile.curve));assert.equal(activeRaceSkill453(r,0),false)}});
test('new rooms use unique system picks, equal-point traits and version negotiation',()=>{const h=harness(),r=h.make(4);assert.equal(r.rulesVersion,2);assert.equal(new Set(r.system.map(x=>x.speciesId)).size,4);assert.ok(r.racers.every(x=>x.profile.version===2));assert.equal(h.state().rulesVersion,6);assert.equal(r.finishMs,null);assert.equal(r.order,null)});
test('older game clients cannot join a room with new rules, but can continue legacy rooms',()=>{const h=harness();h.call('create',{roster:h.roster});h.c.handle(h.s(1),{op:'join',code:h.state().room.code,roster:h.roster});assert.equal(h.state(1).room,null);assert.match(h.messages.get(h.s(1).playerId).at(-2).message,/更新/);const legacy=harness();legacy.c.handle(legacy.s(),{op:'create',roster:legacy.roster});assert.equal(legacy.state().room.rulesVersion,1);assert.ok(legacy.state().room.system.every(r=>r.profile.version!==2));legacy.call('select',{monsterId:'m1'});legacy.call('start');const room=legacy.c.roomFor(legacy.s().playerId);room.outcome.order=[4,0,1,2,3,5,6,7];legacy.call('pass');legacy.finish();assert.equal(legacy.state().deliveries[0].prize,5000);assert.deepEqual(legacy.state().deliveries[0].training,{affection:5,expRate:.02})});
test('podium prizes and scaled training are fixed before delivery and independent from betting',()=>{const h=harness();h.make(4);h.c.roomFor(h.s().playerId).outcome.order=[4,5,6,7,0,1,2,3];h.bet({kind:'exact',picks:[4,5]},1000);for(let i=1;i<4;i++)h.call('pass',{},i);h.finish();for(let i=0;i<4;i++){const e=h.state(i).deliveries[0];assert.equal(e.place,i+1);assert.equal(e.prize,[8000,3000,1000,0][i]);assert.deepEqual(e.training,trainingReward453(i+1));const w=wallet(),key='ws://localhost/party|'+h.s(i).playerId,expBefore=totalExperience(w.state.monsters[0]),expected=Math.max(10,Math.floor(expNeedFor(w.state.monsters[0])*e.training.expRate));if(i===0)reserveRaceBet451(w,key,{raceId:h.state(i).room.id,requestId:e.requestId,amount:1000,ticket:e.ticket});applyRaceDelivery451(w,key,e);assert.equal(w.state.player.gold,10000+e.net);assert.equal(w.state.monsters[0].affection,e.training.affection);assert.equal(totalExperience(w.state.monsters[0])-expBefore,expected);const saved=structuredClone(w.state);applyRaceDelivery451(w,key,e);assert.deepEqual(w.state,saved)}});
test('reward save failure rolls back new training and allows exactly one retry',()=>{const h=harness();h.make();h.c.roomFor(h.s().playerId).outcome.order=[4,0,1,2,3,5,6,7];h.call('pass');h.finish();const e=h.state().deliveries[0],w=wallet(),key='ws://localhost/party|'+h.s().playerId;w.save=()=>false;const before=structuredClone(w.state);assert.throws(()=>applyRaceDelivery451(w,key,e));assert.equal(w.state.player.gold,before.player.gold);assert.equal(w.state.monsters[0].affection,0);w.save=()=>true;applyRaceDelivery451(w,key,e);applyRaceDelivery451(w,key,e);assert.equal(w.state.player.gold,18000);assert.equal(w.state.monsters[0].affection,8)});
test('all pending new payouts and trajectories survive server restart unchanged',()=>{const dir=mkdtempSync(join(tmpdir(),'race453-'));try{const h=harness(join(dir,'race.json'));h.make(4);const outcome=structuredClone(h.c.roomFor(h.s().playerId).outcome),profiles=structuredClone(h.state().room.racers);const p=h.bet();h.restart();h.call('bet',p);assert.deepEqual(h.c.roomFor(h.s().playerId).outcome,outcome);assert.deepEqual(h.state().room.racers,profiles);h.finish();const receipts=[0,1,2,3].map(i=>h.state(i).deliveries);h.restart();assert.deepEqual([0,1,2,3].map(i=>h.state(i).deliveries),receipts)}finally{rmSync(dir,{recursive:true,force:true})}});
test('unconfirmed offline purchase after the deadline refunds escrow once with result training intact',()=>{const h=harness();h.make();const w=wallet(),key='ws://localhost/party|'+h.s().playerId,r=h.state().room,p={raceId:r.id,requestId:r.id+':'+h.s().playerId,amount:1000,ticket:{kind:'win',picks:[0]}};reserveRaceBet451(w,key,p);h.s().connected=false;h.finish();h.s().connected=true;h.call('bet',p);h.call('bet',p);const list=h.state().deliveries;assert.equal(list.filter(e=>e.kind==='refund').length,1);for(const e of list)applyRaceDelivery451(w,key,e);const prize=list.find(e=>e.kind==='result').prize;assert.equal(w.state.player.gold,10000+prize);assert.equal(raceBank451(w.state,key).pending,null);const state=structuredClone(w.state);for(const e of list)applyRaceDelivery451(w,key,e);assert.deepEqual(w.state,state)});
test('host handoff waits thirty seconds, preserves choices and cancels when host returns',()=>{const h=harness();h.call('create',{roster:h.roster});h.call('join',{code:h.state().room.code,roster:h.roster},1);h.call('select',{monsterId:'m2'},1);const original=h.s().playerId;h.s().connected=false;h.advance(1);h.advance(29999);assert.equal(h.state(1).room.hostId,original);h.s().connected=true;h.advance(1);assert.equal(h.c.roomFor(original).hostMissingAt,undefined);h.s().connected=false;h.advance(1);h.advance(30000);assert.equal(h.state(1).room.hostId,h.s(1).playerId);assert.equal(h.state(1).room.members[1].choice.id,'m2');h.call('start',{},1);assert.equal(h.state(1).room.phase,'entry')});
test('offline finisher does not block next race; their earlier receipt remains recoverable',()=>{const h=harness();h.make(4);h.s(3).connected=false;h.finish();const old=h.state().room.id,receipt=structuredClone(h.state(3).deliveries[0]);for(let i=0;i<3;i++)h.call('ack',{ids:h.state(i).deliveries.map(e=>e.id)},i);h.call('again');assert.notEqual(h.state().room.id,old);assert.equal(h.state().room.members.length,3);h.s(3).connected=true;h.call('status',{},3);assert.equal(h.state(3).room,null);assert.deepEqual(h.state(3).deliveries[0],receipt);const w=wallet(),key='ws://localhost/party|'+h.s(3).playerId;applyRaceDelivery451(w,key,receipt);assert.equal(w.state.player.gold,10000+receipt.prize)});
test('server rules-version changes invalidate an otherwise identical lobby render',()=>{const c={state:{room:null,available:true,rulesVersion:1},save:{state:{player:{gold:10}}},connected:()=>true,bank:()=>({})};const old=raceDomSignature452(c);c.state.rulesVersion=2;assert.notEqual(raceDomSignature452(c),old)});
