import test from'node:test';import assert from'node:assert/strict';
import{makeLobby463,start463,action463,public463,settle463,automaticAction464}from'../src/sugoroku/Engine463.js';
import{CARDS463,CARD_BY_ID463,DECK_COUNT463}from'../src/sugoroku/Catalog463.js';import{BOARD463}from'../src/sugoroku/Board463.js';import{BOARD465,roadPoint467,WORLD465}from'../src/sugoroku/Adventure467.js';
const game=()=>{const g=makeLobby463({id:'467',seed:92,members:[{playerId:'p0',name:'P0'}]});start463(g,0);g.step='pre';return g};
function give(g,p,id){const uid=Object.keys(g.cards).find(u=>g.cards[u]===id&&!p.hand.includes(u));g.deck=g.deck.filter(u=>u!==uid);g.discard=g.discard.filter(u=>u!==uid);for(const q of g.players)q.hand=q.hand.filter(u=>u!==uid);p.hand.push(uid);return uid}
test('five-card adjustment has only one copy in the 333-card deck',()=>{assert.equal(CARD_BY_ID463.forest.copies,1);assert.equal(DECK_COUNT463,333);assert.equal(CARDS463.filter(c=>c.effects.some(e=>e.type==='handSize')).length,1);const g=game();assert.equal(Object.values(g.cards).filter(id=>id==='forest').length,1)});
test('human waits to tap dice even with no playable cards; AI and empty post turn progress',()=>{const g=game(),p=g.players[0];g.discard.push(...p.hand);p.hand=[];assert.equal(automaticAction464(g),null);g.turn=1;g.discard.push(...g.players[1].hand);g.players[1].hand=[];assert.deepEqual(automaticAction464(g),{kind:'roll'});g.turn=0;g.step='post';assert.deepEqual(automaticAction464(g),{kind:'end'})});
test('all main nodes sit on the traced painted road, board rules and 3 detours preserved',()=>{assert.equal(BOARD465.length,92);for(const n of BOARD465){const old=BOARD463.find(o=>o.id===n.id);const{x,y,...rule}=n,{x:ox,y:oy,...original}=old;assert.deepEqual(rule,original);assert.ok(x>=40&&x<=WORLD465.width-40);assert.ok(y>=50&&y<=WORLD465.height-50);if(!n.detour)assert.deepEqual({x,y},roadPoint467(n.index/79))}assert.equal(BOARD465.filter(n=>n.fork).length,3)});
test('batch discard exactly selected cards in one command, including discard-trigger movement',()=>{const g=game(),p=g.players[0];g.discard.push(...p.hand);p.hand=[];const a=give(g,p,'phoenix'),b=give(g,p,'nothing'),keep=give(g,p,'treasure');g.queue.push({type:'discard',n:2,select:true,target:'p0',actor:'p0',source:'tile',tile:'10',group:'batch'});settle463(g);const q=public463(g,'p0').pending;assert.equal(q.required467,2);action463(g,'p0',{kind:'choice',values:[a,b]},10);assert.equal(g.pending,null);assert.deepEqual(p.hand,[keep]);assert.ok(g.discard.includes(a)&&g.discard.includes(b));assert.equal(p.pos,'2')});
test('invalid duplicate, stale, wrong count and foreign batch choices reject without changing state',()=>{for(const type of ['duplicate','foreign','few','many']){const g=game(),p=g.players[0];g.queue.push({type:'discard',n:2,select:true,target:'p0',actor:'p0',group:'batch'});settle463(g);const [a,b,c]=p.hand,values=type==='duplicate'?[a,a]:type==='foreign'?[a,g.players[1].hand[0]]:type==='few'?[a]:[a,b,c];const snapshot=JSON.stringify(g);assert.throws(()=>action463(g,'p0',{kind:'choice',values},g.updatedAt));assert.equal(JSON.stringify(g),snapshot)}});
test('adjust hand to five with greed preserves exactly five; batch requires excess count',()=>{const g=game(),p=g.players[0];p.special='greed';for(const id of ['nothing','treasure','curse-heavy','rion-0','rion-1','rion-2','rion-3','rion-4'])give(g,p,id);g.queue.push({type:'handSize',n:5,actor:'p0',target:'p0',group:'size',source:'instant',cardId:'forest'});settle463(g);const excess=p.hand.length-5;assert.equal(public463(g,'p0').pending.required467,excess);action463(g,'p0',{kind:'choice',values:p.hand.slice(0,excess)},20);assert.equal(p.hand.length,5)});
test('bad instant publicly reveals only when activated; ordinary held curse stays concealed',()=>{for(const [id,hacker]of[['poison',false],['poison',true],['curse-heavy',false]]){const g=game(),p=g.players[0];if(hacker)p.special='hacker';const uid=give(g,p,id);p.hand=p.hand.filter(u=>u!==uid);g.deck.push(uid);g.step='draw';action463(g,'p0',{kind:'draw'},1);const other=public463(g,g.players[1].playerId);const publicCard=other.presentation464.find(e=>e.kind==='card'&&e.cardId===id);assert.equal(!!publicCard,id==='poison'&&!hacker);if(publicCard)assert.equal(publicCard.activation466,'instant');else assert.ok(!JSON.stringify(other.presentation464).includes(id))}});
