import test from 'node:test';import assert from 'node:assert/strict';
import * as R from '../src/crane566/Rules566.js';
const members=(count=4)=>Array.from({length:count},(_,seat)=>({playerId:'p'+seat,name:'魔物'+seat,choice:{id:'m'+seat,speciesId:['slime','goblin','wolf','skeleton'][seat]},color499:['orange','blue','green','pink'][seat]}));
function game(count=4,seed=566){const g=R.makeCrane566({id:'test',code:'TEST',partyId:'p',hostId:'p0',members:members(count),now:1000});R.startCrane566(g,1000,seed);tick(g,3000);return g;}
function tick(g,ms){for(let t=g.lastAt+25,end=g.lastAt+ms;t<=end;t+=25)R.advanceCrane566(g,t);}
function single(g,kind='chest',x=0,y=0){g.loot=[];g.nextSpawn=g.nextCrown=Infinity;const v=R.spawnLoot566(g,kind);Object.assign(v,{x,y,a:Math.atan2(y,x),r:Math.hypot(x,y),turn:0});return v;}
const cast=(g,seat,angle=-Math.PI/2,seq=1)=>R.inputCrane566(g,g.players[seat],{action:'cast',shot:g.players[seat].shots,angle,seq});

test('crane: 3 humans plus 1 AI, stable colours, immutable source roster and readable public snapshot',()=>{const people=members(3),before=structuredClone(people),g=R.makeCrane566({id:'c',code:'C',partyId:'p',hostId:'p0',members:people,now:0});R.startCrane566(g,0);assert.deepEqual(people,before);assert.equal(g.players.length,4);assert.equal(g.players.filter(p=>p.ai).length,1);assert.equal(new Set(g.players.map(p=>p.color499)).size,4);const s=R.publicCrane566(g);assert(!('seed'in s));assert(s.players.every(p=>!('botAt'in p)));assert(s.members.every(p=>!('owned'in p)));});
test('crane: money is credited only at the dock, and reloading prevents a second claw',()=>{const g=game();single(g);assert(cast(g,0));assert(!cast(g,0));tick(g,450);assert.equal(g.players[0].score,0);assert.equal(g.loot[0].owner,0);tick(g,4000);assert.equal(g.players[0].score,7);assert.equal(g.players[0].caught,1);assert.equal(g.players[0].hook,null);});
test('crane: a returning treasure can be stolen and only the final owner gets paid',()=>{const g=game(),v=single(g,'crown',0,-1),old=g.players[2];v.owner=2;old.hook={x:0,y:-1,phase:'back',itemId:v.id,angle:0,travel:8};assert(cast(g,0));tick(g,650);assert.equal(v.owner,0);assert.equal(old.hook?.itemId??null,null);assert.equal(g.players[0].steals,1);assert.equal(old.robbed,1);tick(g,6000);assert.equal(g.players[0].score,12);assert.equal(old.score,0);assert(g.events.some(e=>e.type==='steal'));});
test('crane: stealing a mimic backfires, cannot make the score negative, and briefly locks the crane',()=>{for(const score of [2,10]){const g=game(),v=single(g,'mimic',0,5),p=g.players[0];p.score=score;assert(cast(g,0));while(!p.bites&&g.elapsed<10000)tick(g,25);assert.equal(p.score,Math.max(0,score-4));assert.equal(p.bites,1);assert(!R.canCast566(g,p));tick(g,1200);assert(R.canCast566(g,p));assert.equal(g.loot.some(q=>q.id===v.id),false);}});
test('crane: ray hits the first body, not the highest value beyond it',()=>{const g=game(),bad=single(g,'mimic',0,4),good=R.spawnLoot566(g,'crown');Object.assign(good,{x:0,y:0,a:0,r:0,turn:0});cast(g,0);tick(g,350);assert.equal(g.players[0].hook.itemId,bad.id);assert.equal(good.owner,null);});
test('crane: simultaneous contacts produce one owner, consistent links and no duplicated reward',()=>{const g=game(),v=single(g,'gem');cast(g,0);cast(g,2,Math.PI/2);tick(g,450);const owner=v.owner;assert([0,2].includes(owner));assert.equal(g.players.filter(p=>p.hook?.itemId===v.id).length,1);tick(g,4000);assert.equal(g.players.reduce((n,p)=>n+p.score,0),3);});
test('crane: swept contact catches a small target crossed within one step',()=>{assert(R.contact566({x:0,y:5},{x:0,y:-5},{x:0,y:0},{x:0,y:0},.2)>0);assert.equal(R.contact566({x:4,y:5},{x:4,y:-5},{x:0,y:0},{x:0,y:0},.2),null);});
test('crane: NaN, forged action, stale shot and input outside play are rejected',()=>{const g=game(),p=g.players[0];for(const m of [{action:'cast',shot:0,angle:NaN},{action:'cast',shot:0,angle:Infinity},{action:'cast',shot:0,angle:4},{action:'bank',shot:0,angle:0},{action:'cast',shot:99,angle:0}])assert(!R.inputCrane566(g,p,m));g.phase='resolve';assert(!cast(g,0));});
test('crane: 90-second cutoff permits committed cargo to settle, rejects new shots, ties share rank',()=>{const g=game();single(g,'gem',0,8.2);g.players.forEach(p=>p.score=10);g.elapsed=89975;g.lastAt=g.deadline-25;cast(g,0);tick(g,25);assert(['resolve','result'].includes(g.phase));assert(!cast(g,1));tick(g,5000);assert.equal(g.phase,'result');assert(g.results.length===4);assert(g.results.every(r=>r.rank===1+g.results.filter(v=>v.score>r.score).length));});
test('crane: disconnect takeover releases control on reconnect and JSON restart preserves an active claw',()=>{const g=game();const auto=new Set(['p0']);for(let i=0;i<80;i++)R.advanceCrane566(g,g.lastAt+25,new Map(),auto);assert(g.players[0].shots>0);const restored=JSON.parse(JSON.stringify(g));for(let i=0;i<160;i++){R.advanceCrane566(g,g.lastAt+25);R.advanceCrane566(restored,restored.lastAt+25);}assert.deepEqual(restored,g);assert.equal(g.players[0].auto,false);const shots=g.players[0].shots;tick(g,3000);assert.equal(g.players[0].shots,shots);});
test('crane: 64 seeded AI matches finish, preserve ownership invariants and create steals and mishaps',()=>{let steals=0,bites=0,catches=0;const wins=[0,0,0,0];for(let seed=1;seed<=64;seed++){const g=game(0,seed);while(g.phase!=='result'){tick(g,50);assert(g.loot.length<=14);for(const v of g.loot){assert(Number.isFinite(v.x)&&Number.isFinite(v.y));if(v.owner!=null)assert.equal(g.players[v.owner].hook?.itemId,v.id);}assert(g.elapsed<=100000);}assert(g.results.length===4);for(const p of g.players){steals+=p.steals;bites+=p.bites;catches+=p.caught;assert(p.score>=0&&Number.isFinite(p.score));assert(p.shots>10);}g.results.filter(p=>p.rank===1).forEach(p=>wins[p.seat]++);}assert(steals>1000);assert(bites>100);assert(catches>2000);assert(wins.every(n=>n>0));console.log(JSON.stringify({craneAIMatches:64,steals,bites,catches,wins}));});
