import test from 'node:test';import assert from 'node:assert/strict';
import {makeTower517,startTower517,advanceTower517,TOWER517 as C,predictRunner517,shape517,fits517,publicTower517} from '../src/tower/Rules517.js';
import {sealedRunners520,impossible518} from '../src/tower/Reachability518.js';
const make=()=>{const g=makeTower517({id:'521',code:'521',hostId:'p0',members:Array.from({length:4},(_,i)=>({playerId:'p'+i,choice:{speciesId:'slime'}}))});g.roleMode='p0';startTower517(g,0,521);advanceTower517(g,3000);g.autoAt=1e8;return g};
function launch(height,kind){const g=make(),p=g.players[1];p.x=4.5;p.y=height;for(let y=0;y<height;y++)g.board.push({x:4,y,type:'O'});g.boardRevision++;for(let i=0;i<120&&g.phase==='play';i++){g.elapsed+=C.step;g.lastAt+=C.step;predictRunner517(g,p,i===0?{[kind]:true}:{},1/60)}return g}
test('Build521 exit is 20: boosting from 15 is insufficient, from 16 wins, normal jump from 18 wins',()=>{assert.equal(C.height,20);const early=launch(15,'superJump');assert.equal(early.phase,'play');assert.ok(early.players[1].maxHeight>19&&early.players[1].maxHeight<20);for(const [height,kind] of [[16,'superJump'],[18,'jump']]){const g=launch(height,kind);assert.equal(g.winner,'run');assert.equal(g.results.filter(r=>r.winner).length,3)}});
test('Build521 all 200 cells participate in sealing, including the upper four new rows',()=>{const g=make();g.players[1].y=18;for(let x=0;x<9;x++)g.board.push({x,y:19,type:'I'});g.boardRevision++;assert.equal(sealedRunners520(g).length,0);g.board.push({x:9,y:19,type:'I'});g.boardRevision++;assert.equal(impossible518(g),'sealed');assert.equal(sealedRunners520(g).length,3);advanceTower517(g,g.lastAt+50);assert.equal(g.reason,'sealed')});
test('Build521 blocks fit up to row 20 without overflowing the new ceiling',()=>{const g=make();g.board.push({x:0,y:18,type:'O'});g.boardRevision++;assert.ok(fits517(g,shape517('I'),0));assert.equal(fits517(g,shape517('I',1),0),false)});
test('Build521 migration from Build520 preserves an existing boost cooldown',()=>{const g=make();g.rules517=3;g.players[1].superReady=9876;advanceTower517(g,g.lastAt+50);assert.equal(g.rules517,5);assert.equal(g.players[1].superReady,9876);assert.equal(publicTower517(g).rules517,5)});
test('Build521 three initially stacked runners cannot instantly clear by using all boosts together',()=>{const g=make(),runners=g.players.slice(1);runners.forEach((p,i)=>{p.x=5;p.y=i*C.ph});for(let i=0;i<120;i++){g.elapsed+=C.step;for(const p of [...runners].reverse())predictRunner517(g,p,i===0?{superJump:true}:{},1/60)}assert.equal(g.phase,'play');assert.equal(g.events.filter(e=>e.type==='superJump').length,3);assert.ok(runners.every(p=>p.maxHeight<6&&p.superReady>0))});
test('Build521 rejects the actual previous Build520 wire capability while accepting the new one',async()=>{const {queueTower517}=await import('../online-server/src/TowerCoordinator517.js'),g=make(),c={data:{towerRooms517:{room:g}},now:()=>1000},session={playerId:'p1'},packet={gameId:g.id,kind:'move',seq:1,axis:0,superJump:true};assert.equal(queueTower517(c,session,{...packet,towerVersion517:3}),false);assert.equal(queueTower517(c,session,{...packet,towerVersion517:5}),true)});
