import {pairVm409} from './helpers/pair409-vm.mjs';
import {CHAPTER_TWO_PAIRS386} from '../src/data/chapterTwoPairs386.js';
import {chapterTwoSprite383} from '../src/ui/ChapterTwoSprite383.js';
import {monsterVisual} from '../src/ui/MonsterVisual.js';
import {tickBattleEffects} from '../src/battle/BattleRules.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {SPECIES} from '../src/data/species.js';
import {CHAPTER_TWO_SPECIES386} from '../src/data/chapterTwoSpecies386.js';
import {chapterTwoCaptureChance383} from '../src/data/chapterTwoSpecies383.js';
import {CHAPTER_TWO_ACTIONS386} from '../src/chapterTwo/ChapterTwoMonsters386.js';
import {CHAPTER_TWO_SPRITES386} from '../src/data/chapterTwoSprites386.js';
import {chapterTwoFrame383,chapterTwoCanvasFrame383} from '../src/ui/ChapterTwoSprite383.js';
import {createMonster,calculatedStats,displayName} from '../src/models/Monster.js';
import {learnedSkills,allSpeciesSkills,maxMp,skillDamage,chooseAutoBattleDecision} from '../src/battle/SkillSystem.js';
import {createEnemyBattleState,chooseEnemyAction,specialActionInfo,enemyActionMpCost} from '../src/battle/EnemyAI.js';
import {applyEnemyDamage,applyBattleEffect,hasEffect,effectValue} from '../src/battle/BattleRules.js';
import {ENCOUNTERS,chapterTwoEnemyEntries,tuneChapterTwoEnemy,CHAPTER_TWO_AREAS} from '../src/chapterTwo/ChapterTwoSystem.js';
import {eligibleEncounterSpecies} from '../src/core/EncounterPoolSystem.js';
import {SaveService} from '../src/services/SaveService.js';
import {TWIN_PAIRS385,twinPair385,twinReady385,reserveTwin385,resolveTwin385} from '../src/battle/TwinResonance385.js';
import {twinStatus385,twinCodex385} from '../src/ui/TwinStatus385.js';
import {BattleScreen} from '../src/ui/screens/BattleScreen.js';
const roster=Object.values(CHAPTER_TWO_SPECIES386),main=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
function monster(key){const m=createMonster('ch2_'+key,{level:1500});m.currentHp=calculatedStats(m).hp;m.currentMp=maxMp(m);return m;}
function encounter(id){return chapterTwoEnemyEntries(id).map((e,i)=>{const u=createEnemyBattleState(SPECIES[e.speciesId],{...e,id:'e'+i,combatRarity:SPECIES[e.speciesId].rarity},100);tuneChapterTwoEnemy(u,id,i);return u;});}
function state(keys=['ryune','rose']){return {party:keys.map(monster),enemies:[{id:'e',hp:1e10,maxHp:1e10,def:100,mdef:100,element:'neutral'}],turn:1,allyEffects:{},enemyEffects:{},enemyStatuses:{},allyAilments:{},circleShields:{}};}
function simpleEnv(b){const calls={hits:[],heals:[],shields:[],cues:[],weakens:[]};return {calls,blocked:()=>false,opponents:()=>b.enemies.filter(e=>e.hp>0),cue:async p=>calls.cues.push(p.pair.id),hit:async(s,t,p)=>{calls.hits.push([s.id,t.id,p.power]);t.hp-=1;return 1;},heal:async(u,r)=>calls.heals.push([u.id,r]),shield:(u,r)=>calls.shields.push([u.id,r]),weaken:(u,e)=>calls.weakens.push([u.id,e.kind])};}
function runtime(b){const logs=[],floats=[],hits=[];const c={battle:b,save:{state:{equipment:[]}},SPECIES,resolveTwin385,calculatedStats,displayName,skillDamage,applyEnemyDamage,applyBattleEffect,effectValue,hasEffect,allyAilment:(u,id)=>(b.allyAilments[u.id]??[]).find(s=>s.id===id),aliveEnemies:x=>x.enemies.filter(e=>e.hp>0),ultimateIsolated:(_b,u)=>!!u.isolated,ultimateExtraBlocked:(_b,u)=>!!u.blocked,convertedAttackStats:s=>s,attackHits:()=>true,allyAttackFactor:id=>1+effectValue(b,id,'atkUp')-effectValue(b,id,'atkDown'),enemyDefenseFactor:id=>1+effectValue(b,id,'defUp','enemy')-effectValue(b,id,'defDown','enemy'),attributeDamageMultiplier:()=>1,abyssBattleMultiplier:()=>1,enemyDamageMultiplier:()=>1,endgameIncomingDamageMultiplier:()=>1,weaponMasteryDamageMultiplier:()=>1,magicCircleDamageMultiplier:()=>1,affixValue:()=>0,addBattleLog:(_b,s)=>logs.push(s),battleBanner:async()=>{},animateAttack:async()=>{},animateHit:async()=>{},floatText:async(...a)=>floats.push(a),recordBattleDamage(){},registerWeaponFinisher(){},recordBattleHealing(){},flushBattleRecoveries:async()=>{},queueBattleRecovery(){},heroOverheal(){},dealEnemyHit:async(e,t,p,label,crit,element,rules)=>{hits.push({e,t,p,element,rules});t.currentHp=Math.max(0,t.currentHp-10);return 10;}};
 const start=main.indexOf('async function resolveTwinResonance385('),end=main.indexOf('async function triggerInvincibleAlliance(',start);assert.ok(start>0&&end>start);vm.createContext(Object.assign(c,{...pairVm409,...c}));vm.runInContext(main.slice(start,end),c);
 const recoveryStart=main.indexOf('function recoverBattleHp('),recoveryEnd=main.indexOf('function storeFloorBossManaNocturne(',recoveryStart);vm.runInContext(main.slice(recoveryStart,recoveryEnd),c);return{c,logs,floats,hits};}

test('fourth installment adds seven ranks, 28 shared skills, seven captures and six pair members',()=>{
 assert.deepEqual(roster.map(s=>s.rarity),['N','R','SR','SSR','UR','LR','神話']);assert.equal(Object.keys(CHAPTER_TWO_ACTIONS386).length,28);assert.equal(CHAPTER_TWO_PAIRS386.length,3);assert.equal(new Set(CHAPTER_TWO_PAIRS386.flatMap(p=>p.members)).size,6);
 const ordinary=new Set(eligibleEncounterSpecies(SPECIES,999999).map(s=>s.id));for(const s of roster){const m=monster(s.key);assert.equal(allSpeciesSkills(s.id).length,4);assert.equal(learnedSkills(m).length,4);assert.equal(chapterTwoCaptureChance383(s.id,.99),s.captureCap383);assert.equal(ordinary.has(s.id),false);assert.equal(s.gachaExcluded,true);for(const k of s.authoredSkills){assert.equal(specialActionInfo(k.id).power,k.power);assert.equal(enemyActionMpCost({},k.id),k.mp);}}
});
test('repeatable habitats contain all new species and pairs together with real appropriate equipment',()=>{
 const seen=new Set();for(const id of ['roam0_3','roam1_1','roam3_1','roam4_1']){const e=ENCOUNTERS[id];assert.ok(e.roaming);const units=encounter(id);for(const u of units){seen.add(u.speciesId);if(!SPECIES[u.speciesId].chapterTwoSet386)continue;assert.equal(u.uncapturable,false);assert.equal(u.enemyGear.length,6);assert.ok(u.enemyMagicCircle?.id);assert.ok(u.enemyMagicCircle.level>0);assert.ok(u.enemyEquipmentLevel>0);for(const k of ['maxHp','maxMp','atk','matk','def','mdef','spd'])assert.ok(Number.isFinite(u[k])&&u[k]>0);const s=SPECIES[u.speciesId],magic=s.authoredSkills.filter(k=>k.power>0).every(k=>k.damageClass==='magic');for(const w of u.enemyGear.slice(0,2))assert.ok((w.stats[magic?'matk':'atk']??0)>0);const room=CHAPTER_TWO_AREAS[e.area].rooms.find(r=>r.id===e.room);assert.ok(s.habitat383.includes(room.name));}}
 for(const s of roster)assert.ok(seen.has(s.id));for(const p of CHAPTER_TWO_PAIRS386)assert.ok(Object.values(ENCOUNTERS).some(e=>e.roaming&&p.members.every(id=>e.species.includes(id))));
});
test('all seven new captures survive SaveService with learned skills and depleted resources',()=>{
 const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};const save=new SaveService();for(const s of roster){const m=monster(s.key);m.currentHp=0;m.currentMp=2;save.state.monsters.push(m);}save.save();const loaded=new SaveService();for(const s of roster){const m=loaded.state.monsters.find(u=>u.speciesId===s.id);assert.equal(m.currentHp,0);assert.equal(m.currentMp,2);assert.equal(learnedSkills(m).length,4);assert.equal(m.enemyGear,undefined);}
});
test('poison and fox enemy AI establish their status then focus the prepared enemy',()=>{
 for(const [room,key,status,setup,strike] of [['roam1_1','viola','poison','pollen','distill'],['roam3_1','kagura','burn','flame','crescent']]){const enemies=encounter(room),u=enemies.find(e=>e.speciesId==='ch2_'+key),b=state(),context={allies:enemies,opponents:[{id:'clean',currentHp:100,_maxHp:100},{id:'marked',currentHp:100,_maxHp:100}],battle:b};assert.equal(chooseEnemyAction(u,context),`ch2_${key}__${setup}`);b.allyAilments.marked=[{id:status,turns:3}];assert.equal(chooseEnemyAction(u,context),`ch2_${key}__${strike}`);assert.equal(u.chapterTwoFocus382,'marked');u.currentMp=0;assert.equal(chooseEnemyAction(u,context),'attack');}
});
test('garden scales each target separately and heals only the living allies',async()=>{
 const b=state(['mirea','viola','ticta']);b.party[2].currentHp=0;b.enemies.push({...b.enemies[0],id:'clean'});const env=simpleEnv(b);env.hasStatus=t=>t.id==='e';await resolveTwin385(b,b.party[0],'ally',env);assert.deepEqual(env.calls.hits.map(h=>h[2]),[3,2]);assert.equal(env.calls.heals.length,2);assert.ok(env.calls.heals.every(h=>h[1]===.15));b.turn++;env.hasStatus=()=>false;await resolveTwin385(b,b.party[0],'ally',env);assert.deepEqual(env.calls.hits.slice(-2).map(h=>h[2]),[2,2]);
});
test('fox checks fire on every retargeted hit and applies a bounded two-turn party accuracy buff',async()=>{
 const b=state(['kagura','sayo','ticta']);b.enemies[0].hp=1;b.enemies.push({id:'clean',hp:100});const env=simpleEnv(b);env.hasStatus=t=>t.id==='e';env.boost=(u,e)=>applyBattleEffect(b,u.id,e);await resolveTwin385(b,b.party[0],'ally',env);assert.deepEqual(env.calls.hits.map(h=>h[2]),[1.15*1.45,1.15,1.15]);await resolveTwin385(b,b.party[1],'ally',env);for(const u of b.party){assert.equal(effectValue(b,u.id,'accuracyUp'),.18);assert.equal(b.allyEffects[u.id].filter(e=>e.sourceKey==='pair:foxmoon').length,1);}tickBattleEffects(b);tickBattleEffects(b);for(const u of b.party)assert.equal(effectValue(b,u.id,'accuracyUp'),0);
});
test('star pair finishes on its second different member, in either order, and resets per round',async()=>{
 for(const keys of [['celes','lumina'],['lumina','celes']]){const b=state(keys),env=simpleEnv(b);await resolveTwin385(b,b.party[0],'ally',env);assert.equal(env.calls.hits[0][2],1.6);assert.ok(env.calls.shields.every(x=>x[1]===.08));await resolveTwin385(b,b.party[1],'ally',env);assert.equal(env.calls.hits[1][2],4.2);assert.ok(env.calls.shields.slice(2).every(x=>x[1]===.22));assert.equal(await resolveTwin385(b,b.party[0],'ally',env),false);b.turn++;await resolveTwin385(b,b.party[1],'ally',env);assert.equal(env.calls.hits[2][2],1.6);}
});
test('star finisher quota persists through JSON, duplicates, death and revival without touching pair definitions',()=>{
 let b=state(['celes','lumina']);assert.equal(reserveTwin385(b,b.party[0]).pair.power,1.6);b.party.push({...b.party[0],id:'copy'});assert.equal(reserveTwin385(b,b.party[2]),null);b=JSON.parse(JSON.stringify(b));b.party[1].currentHp=0;assert.equal(reserveTwin385(b,b.party[1]),null);b.party[1].currentHp=10;const final=reserveTwin385(b,b.party[1]);assert.equal(final.pair.name,'星幕・終演のアリア');assert.equal(final.pair.defenseIgnore,.45);assert.equal(twinPair385('ch2_celes').power,1.6);assert.equal(twinPair385('ch2_celes').name,'星糸のデュエット');
});
test('star ally and enemy quotas stay independent, and a missing/captured partner blocks the finisher',()=>{
 const b=state(['celes','lumina']);b.enemies=encounter('roam4_1');assert.equal(reserveTwin385(b,b.party[0]).pair.power,1.6);assert.equal(reserveTwin385(b,b.enemies[0],'enemy').pair.power,1.6);b.party[1].captured=true;assert.equal(reserveTwin385(b,b.party[1]),null);assert.equal(reserveTwin385(b,b.enemies[1],'enemy').pair.power,4.2);delete b.party[1].captured;b.party.pop();assert.equal(reserveTwin385(b,b.party[0]),null);
});
test('actual garden runtime uses enemy poison and normal recovery suppression, not resurrection',async()=>{
 const b=state(['mirea','viola','ticta']);b.enemies.push({...b.enemies[0],id:'clean'});b.enemyStatuses.e=[{id:'poison',turns:3}];b.party.forEach(u=>u.currentHp=1);b.party[2].currentHp=0;applyBattleEffect(b,b.party[0].id,{kind:'healDown',value:.5,turns:2});const {c}=runtime(b),before=b.enemies[0].hp;await c.resolveTwinResonance385(b.party[0]);const poisoned=before-b.enemies[0].hp,clean=before-b.enemies[1].hp;assert.ok(poisoned>clean*1.4);assert.equal(b.party[0].currentHp,1+Math.floor(Math.floor(calculatedStats(b.party[0]).hp*.15)*.5)+Math.floor(Math.floor(calculatedStats(b.party[0]).hp*.08)*.5));assert.equal(b.party[2].currentHp,0);
});
test('actual enemy garden and fox use ally status and ordinary enemy damage rules',async()=>{
 for(const [room,status,power] of [['roam1_1','poison',3],['roam3_1','burn',1.15*1.45]]){const b=state(['ticta']);b.enemies=encounter(room);b.allyAilments[b.party[0].id]=[{id:status,turns:3}];const {c,hits}=runtime(b);await c.resolveTwinResonance385(b.enemies[0],'enemy');assert.ok(hits.length);assert.ok(hits.every(h=>h.p===power));if(status==='burn'){assert.equal(hits.length,3);for(const u of b.enemies)assert.equal(effectValue(b,u.id,'accuracyUp','enemy'),.18);}b.turn++;b.allyAilments={};hits.length=0;await c.resolveTwinResonance385(b.enemies[0],'enemy');assert.ok(hits.every(h=>h.p===(status==='poison'?2:1.15)));}
});
test('actual star finisher uses stronger ATK/MATK, all targets, 45% defense ignore and 22% shield',async()=>{
 const b=state(['celes','lumina','ticta']);b.enemies.push({...b.enemies[0],id:'e2'});b.enemies.forEach(e=>{e.def=e.mdef=1000;});const {c,logs}=runtime(b);c.calculatedStats=u=>({...calculatedStats(u),atk:100,matk:1000});let before=b.enemies[0].hp;await c.resolveTwinResonance385(b.party[0]);const first=before-b.enemies[0].hp;before=b.enemies[0].hp;await c.resolveTwinResonance385(b.party[1]);assert.ok(before-b.enemies[0].hp>first*2.5);assert.equal(b.enemies[0].hp,b.enemies[1].hp);assert.ok(logs.some(l=>l.includes('星幕・終演のアリア')));for(const u of b.party)assert.equal(b.circleShields[u.id],Math.floor(calculatedStats(u).hp*.22));
});
test('new pair UI names the partner, shows the approaching finisher and keeps enemy names overhead',()=>{
 const b=state(['celes','lumina']);assert.match(twinStatus385([b.party[0]]),/ルミナを編成で発動/);reserveTwin385(b,b.party[0]);assert.match(twinStatus385(b.party,{battle:b,compact:true}),/次は星幕・終演のアリア/);for(const p of CHAPTER_TWO_PAIRS386)for(const id of p.members)assert.ok(twinCodex385(id).includes(p.name));b.enemies=encounter('roam4_1');b.turnQueue=[];const html=BattleScreen(b,{},{});for(const e of b.enemies){const start=html.indexOf(`data-enemy-target="${e.id}"`),end=html.indexOf('side-unit-sprite',start);assert.ok(html.slice(start,end).includes(e.name));assert.ok(html.slice(start,end).includes('combat-rank-badge'));}assert.ok(html.includes('星糸のデュエット'));
});
test('new right-facing and old left-facing atlases both turn correctly in the actual exploration draw function',()=>{
 const start=main.indexOf('function drawExplorationMonster('),end=main.indexOf('function drawExplorationTileAsset(',start),scales=[];const context={SPECIES,chapterTwoSprite383,calculatedStats,performance:{now:()=>0},TILE:88,explorationSpriteImage:()=>({width:256,height:256}),game:{player:{path:[],x:0,y:0},camera:{z:1,world:(x,y)=>({x,y})},ctx:{save(){},restore(){},translate(){},scale:(...v)=>scales.push(v),drawImage(){}}}};vm.createContext(Object.assign(context,{...pairVm409,...context}));vm.runInContext(main.slice(start,end),context);for(const [key,sourceFacing] of [['mirea','right'],['celes','right'],['ryune','left']]){for(const facing of ['left','right']){scales.length=0;context.drawExplorationMonster({x:0,y:0,moving341:false,facing},monster(key));assert.equal(scales.length,Number(facing!==sourceFacing));}assert.match(monsterVisual('ch2_'+key),new RegExp(`data-source-facing="${sourceFacing}"`));}
 const css=fs.readFileSync(new URL('../src/Styles/build386-pair-art.css',import.meta.url),'utf8');assert.match(css,/side-party[^}]+data-source-facing="right"[^}]+transform:none!important/);assert.match(css,/side-enemies[^}]+data-source-facing="right"[^}]+transform:scaleX\(-1\)!important/);
});
test('56 true RGBA new poses fit 256px and the gallery has all motion controls and pair descriptions',()=>{
 const oldDoc=globalThis.document,oldImage=globalThis.Image;let draws=0;globalThis.Image=class{set src(v){this.onload();}};globalThis.document={createElement:()=>({getContext:()=>({translate(){},scale(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},clip(rule){assert.equal(rule,'evenodd');},drawImage(){draws++;}})})};try{for(const s of roster){const atlas=CHAPTER_TWO_SPRITES386[s.id],bytes=fs.readFileSync(new URL('../'+atlas.url.split('?')[0],import.meta.url));assert.equal(bytes[25],6);assert.equal(atlas.facing,'right');assert.equal(Object.keys(atlas.frames).length,8);for(const frame of Object.keys(atlas.frames)){const f=chapterTwoFrame383(s.id,frame);assert.ok(f.x>=0&&f.y>=0&&f.x+f.width<=256&&f.y+f.height<=256);assert.equal(chapterTwoCanvasFrame383(s.id,frame).width,256);}}}finally{globalThis.document=oldDoc;globalThis.Image=oldImage;}assert.equal(draws,56);const html=fs.readFileSync(new URL('../artifacts/build386/monsters.html',import.meta.url),'utf8');for(const frame of ['idle1','idle2','idle3','walk1','walk2','attack','damage','down'])assert.ok(html.includes(`data-motion="${frame}"`));for(const p of CHAPTER_TWO_PAIRS386)assert.ok(html.includes(p.description));
});
test('player auto prepares and follows pair conditions while recovery and a missing partner retain priority',()=>{
 for(const [keys,index,setup,mark,follow] of [[['mirea','viola'],1,'pollen','poison','distill'],[['kagura','sayo'],0,'flame','burn','crescent'],[['celes','lumina'],0,'thread','evasionDown','needle']]){
 const b=state(keys);b.party.forEach(m=>m._maxHp=calculatedStats(m).hp);const m=b.party[index];assert.equal(chooseAutoBattleDecision(m,b).skill?.id,`${m.speciesId}__${setup}`);if(mark==='evasionDown')applyBattleEffect(b,'e',{kind:mark,value:.18,turns:2},'enemy');else b.enemyStatuses.e=[{id:mark,turns:3}];assert.equal(chooseAutoBattleDecision(m,b).skill?.id,`${m.speciesId}__${follow}`);b.party[1-index].currentHp=0;assert.notEqual(chooseAutoBattleDecision(m,b).reason,'pair-prepared');}
 const b=state(['mirea','viola']);b.party.forEach(m=>{m._maxHp=calculatedStats(m).hp;m.currentHp=1;});b.enemyStatuses.e=[{id:'poison',turns:3}];assert.equal(chooseAutoBattleDecision(b.party[0],b).skill?.id,'ch2_mirea__elixir');
});
