import test from 'node:test';
import assert from 'node:assert/strict';
import * as R from '../src/cart/Rules543.js';
import {queueCart543,advanceCarts543,liveCart543} from '../online-server/src/CartCoordinator543.js';
function game(n=4){const members=Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'プレイヤー'+i,choice:{speciesId:'slime'}}));const g=R.makeCart543({id:'g549',code:'CODE',partyId:'p',hostId:'p0',now:1000,members});R.startCart543(g,1000,549);g.phase='play';g.roundAt=1000;g.lastAt=1000;g.players=g.players.slice(0,n);return g}
function ticks(g,n){for(let i=0;i<n;i++){g.elapsed+=25;R.physics543(g)}}
const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('MAX is exactly three times the previous top launch speed; low power remains controllable',()=>{near(R.launchSpeed549(1),36);assert(R.launchSpeed549(.25)<6.5);for(let p=.08;p<1;p+=.04)assert(R.launchSpeed549(p+.01)>R.launchSpeed549(p));for(const v of [6,8,10,12,25,36])near(R.launchSpeed549(R.powerForSpeed549(v)),v)});
test('untouched starting carts do not drift or acquire a launch state',()=>{const g=game(),before=g.players.map(p=>[p.x,p.y]);ticks(g,200);assert.deepEqual(g.players.map(p=>[p.x,p.y]),before);assert(g.players.every(p=>!p.launched&&p.vx===0&&p.vy===0))});
test('a launched cart hits and displaces an unreleased neighbor without consuming its shot',()=>{const g=game(2),[a,b]=g.players;a.x=-2.5;b.x=-.7;a.y=b.y=4;R.input543(g,a,'shoot',0,Math.PI/2,.4);const start=b.x;ticks(g,12);assert(b.x>start+.3);assert(!b.launched);assert(b.vx>0);assert(g.events.some(e=>e.type==='bump'));assert(R.input543(g,b,'pull',g.elapsed,0,.3));assert.equal(b.pullPower547,.3)});
test('a release adds a vector to the current momentum, including sideways and reverse carries',()=>{for(const [vx,vy,angle]of [[5,4,0],[8,-3,Math.PI/2],[-6,7,-.8]]){const g=game(1),p=g.players[0];p.vx=vx;p.vy=vy;const speed=R.launchSpeed549(.65);assert(R.input543(g,p,'shoot',0,angle,.65));near(p.vx,vx+Math.sin(angle)*speed);near(p.vy,vy+Math.cos(angle)*speed);assert.equal(R.input543(g,p,'shoot',0,angle,1),false)}});
test('cancelling a pull does not erase momentum from a collision',()=>{const g=game(1),p=g.players[0];p.vx=4;p.vy=2;R.input543(g,p,'pull',0,0,.6);R.input543(g,p,'cancel',50);near(p.vx,4);near(p.vy,2);assert(!p.launched);near(p.pullPower547,0)});
test('opposing fast carts cannot pass through each other in one server tick',()=>{const g=game(2),[a,b]=g.players;a.x=-1;b.x=1;a.y=b.y=5;a.vx=75;b.vx=-75;ticks(g,1);assert(a.x<b.x);assert(a.vx<0&&b.vx>0);assert(g.events.some(e=>e.type==='bump'));assert(Math.hypot(a.vx,a.vy)<=75);assert(Math.hypot(b.vx,b.vy)<=75)});
test('fast carts repeatedly ricochet from walls without leaving bounds or gaining energy',()=>{const g=game(1),p=g.players[0];p.x=0;p.y=5;p.vx=36;p.launched=true;let energy=36;for(let i=0;i<160;i++){ticks(g,1);const v=Math.hypot(p.vx,p.vy);assert(v<=energy+1e-7);energy=v;assert(Math.abs(p.x)<=R.CART543.width/2-R.CART543.radius+1e-6)}assert(g.events.filter(e=>e.type==='wall').length>=5)});
test('an unreleased cart pushed into the sea loses its turn and does not block round completion',()=>{const g=game(1),p=g.players[0];p.y=29.3;p.vy=12;ticks(g,2);assert(p.fallenAt!=null);assert(!p.launched);assert.equal(R.input543(g,p,'shoot',50,0,1),false);for(let i=0;i<50;i++)R.advanceCart543(g,g.lastAt+25);assert.equal(g.phase,'intermission');assert.equal(g.history[0].results[0].points,0)});
test('a fast pushed cart is blocked by freight crates',()=>{const g=game(1),p=g.players[0];g.round=3;p.x=0;p.y=8;p.vy=72;ticks(g,4);assert(p.y<8.8);assert(g.events.some(e=>e.type==='block'));assert(p.vy<0)});
test('crossing a conveyor while unreleased accelerates once and keeps the shot available',()=>{const g=game(1),p=g.players[0];g.round=4;p.x=0;p.y=11.9;p.vy=8;ticks(g,20);assert(p.boosted);assert(!p.launched);assert.equal(g.events.filter(e=>e.type==='boost').length,1);assert(R.input543(g,p,'shoot',500,0,.2))});
test('all five rounds settle with AI using the recalibrated pull curve',()=>{const g=game();g.phase='countdown';g.roundAt=4500;g.players.forEach(p=>p.ai=true);for(let i=0;i<7000&&g.phase!=='result';i++)R.advanceCart543(g,g.lastAt+25);assert.equal(g.phase,'result');assert.equal(g.history.length,5);assert(g.players.every(p=>Number.isFinite(p.score)));assert(g.players.some(p=>p.score>0))});
test('saved v4 live rooms migrate to lobby before v5 physics is applied',()=>{const g=game();g.rules543=4;const party={id:'p',members:[{ready:true}]};const c={data:{cartRooms543:{CODE:g},parties462:{p:party}},now:()=>1000,sessions:new Map(),transaction:f=>f(),broadcast(){}};advanceCarts543(c);assert.equal(c.data.cartRooms543.CODE.phase,'lobby');assert.equal(c.data.cartRooms543.CODE.rules543,5);assert.equal(party.members[0].ready,false)});
