import test from 'node:test';
import assert from 'node:assert/strict';
import * as R from '../src/hide/Rules536.js';
import {queueHide536,liveHide536} from '../online-server/src/HideCoordinator536.js';
import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';
import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'P'+i,owned:[{id:'m'+i,speciesId:'slime'}],choice:{id:'m'+i,speciesId:'slime'}}));
function make(role='hunter',count=4){const g=R.makeHide536({id:'536',code:'ABC',partyId:'party',hostId:'p0',members:members.slice(0,count)});g.role=role;R.startHide536(g,0,536);return g}
const advance=(g,ms,inputs=new Map(),auto=new Set())=>{const end=g.lastAt+ms;while(g.lastAt<end&&['play','hiding'].includes(g.phase))R.advanceHide536(g,Math.min(end,g.lastAt+50),inputs,auto)};
const play=()=>{const g=make();advance(g,8000);return g};
const targetNear=(g,id=1)=>{const p=g.players[id],h=g.players[g.hunterSeat];h.x=p.x;h.y=p.y+100;return p};
test('one hunter, three hiders, six disguises and exactly four seats, with 0–3 AI fillers',()=>{for(let n=1;n<=4;n++){const g=make('hunter',n);assert.equal(g.players.length,4);assert.equal(g.players.filter(p=>p.ai).length,4-n);assert.equal(g.players.filter(p=>p.hunter).length,1);assert.equal(g.objects.length,32);assert.equal(R.objects536(g,g.players[1].playerId).length,35);assert.equal(new Set(R.objects536(g,g.players[1].playerId).map(o=>o.id)).size,35)}});
test('hunter cannot memorize hiding phase; hiders can move and transform during eight seconds',()=>{const g=make(),p=g.players[1],x=p.x;assert.deepEqual(R.publicHide536(g,'p0').objects,[]);assert.equal(R.publicHide536(g,'p0').players[1].x,undefined);advance(g,1000,new Map([['p1',{target:{x:x+120,y:p.y},kind:4}]]));assert.equal(p.kind,4);assert.ok(p.x>x);assert.equal(g.phase,'hiding');advance(g,7000);assert.equal(g.phase,'play');assert.ok(R.publicHide536(g,'p0').objects.length>0&&R.publicHide536(g,'p0').objects.length<35)});
test('hunter snapshot cannot link names, player IDs, AI state, or owners to furniture',()=>{const g=play(),v=R.publicHide536(g,'p0');assert.equal(v.seed,undefined);for(const p of v.players.filter(p=>!p.hunter))for(const k of ['x','y','objectId','kind','anchor','brain','lastSeq'])assert.equal(p[k],undefined,k);for(const o of v.objects)for(const k of ['owner','seat','playerId','moving'])assert.equal(o[k],undefined);assert.ok(R.publicHide536(g,'p1').objects.some(o=>o.owner==='p1'));assert.equal(R.publicHide536(g,'spectator').players[1].x,undefined)});
test('invalid, distant, duplicate, out-of-cooldown and non-hunter attacks do not spend charges',()=>{const g=play(),h=g.players[0],p=targetNear(g);assert.equal(R.attackHide536(g,g.players[2],p.objectId),false);assert.equal(R.attackHide536(g,h,'wrong'),false);h.x=900;h.y=1240;p.x=130;p.y=230;assert.equal(R.attackHide536(g,h,p.objectId),false);assert.equal(g.shots,12);targetNear(g);assert.equal(R.attackHide536(g,h,p.objectId),true);assert.equal(g.shots,11);assert.equal(R.attackHide536(g,h,p.objectId),false);assert.equal(g.shots,11)});
test('all three captures end once, while the final shot can still win',()=>{const g=play();g.shots=3;for(let i=1;i<4;i++){targetNear(g,i);g.shotReadyAt=0;assert.ok(R.attackHide536(g,g.players[0],g.players[i].objectId))}assert.equal(g.phase,'result');assert.equal(g.winningSide,'hunter');assert.equal(g.shots,0);const snapshot=structuredClone(g);R.finishHide536(g,'hiders','time');R.advanceHide536(g,1e9);assert.deepEqual(g,snapshot)});
test('twelve misses lose, checked furniture cannot consume extra shots',()=>{const g=play(),h=g.players[0];for(let i=0;i<12;i++){const o=g.objects[i];h.x=o.x;h.y=o.y;g.shotReadyAt=0;assert.ok(R.attackHide536(g,h,o.id));g.shotReadyAt=0;assert.equal(R.attackHide536(g,h,o.id),false)}assert.equal(g.reason,'shots');assert.equal(g.winnerIds.length,3)});
test('one survivor at timeout gives the entire hiding team the win',()=>{const g=play();g.players[1].alive=false;g.players[2].alive=false;advance(g,90000);assert.equal(g.reason,'time');assert.equal(g.winnerIds.length,3);assert.equal(g.results.filter(p=>p.escaped).length,1)});
test('small jiggles do not reset the 20 second reveal; meaningful relocation does',()=>{const g=play(),p=g.players[1];advance(g,20500);assert.ok(p.revealUntil>g.elapsed);p.x+=20;advance(g,50);assert.ok(p.stillMs>=20000);const dest={x:p.x<700?p.x+130:p.x-130,y:p.y};advance(g,900,new Map([['p1',{target:dest}]]));assert.ok(p.stillMs<1000);assert.equal(p.revealUntil,0)});
test('smoke hides all nearby furniture from hunter, blocks stale ID attacks, and expires',()=>{const g=play(),p=targetNear(g),h=g.players[0];advance(g,50,new Map([['p1',{smoke:true}]]));assert.equal(p.smokes,1);assert.ok(!R.objects536(g,'p0').some(o=>o.id===p.objectId));assert.ok(R.objects536(g,'p1').some(o=>o.id===p.objectId));assert.equal(R.attackHide536(g,h,p.objectId),false);advance(g,3600);assert.ok(R.objects536(g,'p0').some(o=>o.id===p.objectId));assert.ok(R.attackHide536(g,h,p.objectId))});
test('sonar gives anonymous nearby clues only and has two uses plus cooldown',()=>{const g=play(),p=targetNear(g),inputs=new Map([['p0',{pulse:true}]]);advance(g,50,inputs);assert.equal(g.pulseCharges,1);const clue=g.events.filter(e=>e.type==='noise').at(-1);assert.ok(clue);assert.equal(clue.seat,undefined);inputs.set('p0',{pulse:true});advance(g,50,inputs);assert.equal(g.pulseCharges,1)});
test('malformed/stale/cross-game packets reject; queues preserve one-shot actions',()=>{const g=play(),c={data:{hideRooms536:{ABC:g}},now:()=>8000},s={playerId:'p1'},base={gameId:g.id,hideVersion536:1,kind:'input',seq:1};for(const bad of[{target:{x:NaN,y:1}},{target:{x:1001,y:1}},{prop:9},{seq:-1},{gameId:'old'},{hideVersion536:0}])assert.equal(queueHide536(c,s,{...base,...bad}),false);assert.ok(queueHide536(c,s,{...base,smoke:true}));assert.equal(queueHide536(c,s,base),false);assert.ok(queueHide536(c,s,{...base,seq:2,target:{x:300,y:400}}));assert.equal(c.hideRuntime536.get(g.id).inputs.get('p1').smoke,true);assert.equal(queueHide536(c,{playerId:'stranger'},base),false)});
function rig(count=4){let now=100000;const messages=[],sessions=new Map(members.map(m=>[m.playerId,{playerId:m.playerId,clientKey:m.playerId,connected:true,profile:{name:m.name}}]));const c=new RaceCoordinator451({sessions,now:()=>now,send:(id,msg)=>messages.push({id,...msg})});const q=(i,op,extra={})=>{messages.length=0;c.handle(sessions.get('p'+i),{op,rulesVersion:8,hideVersion536:1,roster:members[i].owned,displayName:members[i].name,...extra});return messages.find(m=>m.type==='raceError451')};assert.equal(q(0,'partyCreate462',{game:'hide'}),undefined);const party=partyFor462(c,'p0');for(let i=1;i<count;i++)q(i,'partyJoin462',{code:party.code});const game=()=>partyRace462(c,partyFor462(c,'p0'));return{c,q,sessions,messages,party,game,tick(ms){for(let k=0;k<ms;k+=50){now+=Math.min(50,ms-k);c.advanceHide536()}}}}
test('real coordinator: four humans, selection, role authority, ready gate, private frames and result replay/list',()=>{const t=rig(),{q,c}=t;let g=t.game();assert.match(q(1,'hide536',{gameId:g.id,kind:'role',role:'hunter'}).message,/部屋主/);assert.equal(q(0,'hide536',{gameId:g.id,kind:'role',role:'hunter'}),undefined);assert.ok(q(0,'hide536',{gameId:g.id,kind:'start'}));for(let i=0;i<4;i++){q(i,'hide536',{gameId:g.id,kind:'select',monsterId:'m'+i});assert.equal(q(i,'partyReady462',{ready:true}),undefined)}assert.equal(q(0,'hide536',{gameId:g.id,kind:'start'}),undefined);t.tick(9000);g=liveHide536(c,t.game());assert.equal(g.phase,'play');assert.equal(c.view(t.sessions.get('p0')).hide.players[1].x,undefined);assert.ok(c.view(t.sessions.get('p1')).hide.players[1].x);assert.ok(t.messages.some(m=>m.type==='hideFrame536'));assert.equal(c.active('p0'),true);R.finishHide536(g,'hiders','time');t.tick(50);assert.equal(t.game().phase,'result');const id=g.id;assert.equal(q(0,'partyResult490',{partyId:t.party.id,gameId:id,kind:'again'}),undefined);assert.notEqual(t.game().id,id);assert.equal(t.game().role,'hunter');assert.equal(q(0,'partyResult490',{partyId:t.party.id,gameId:id,kind:'again'}),undefined);assert.equal(t.game().phase,'lobby');assert.equal(q(0,'partyLounge462'),undefined);assert.equal(c.view(t.sessions.get('p0')).hide,null);assert.equal(t.party.code,partyFor462(c,'p0').code)});
test('disconnect/home takeover resumes human control without losing identity or sequence',()=>{const t=rig(1),{q,c}=t;const g=t.game();q(0,'partyReady462',{ready:true});q(0,'hide536',{gameId:g.id,kind:'start'});t.sessions.get('p0').connected=false;t.tick(9000);assert.equal(liveHide536(c,t.game()).players[0].auto,true);t.sessions.get('p0').connected=true;t.tick(100);assert.equal(liveHide536(c,t.game()).players[0].auto,false);assert.equal(c.view(t.sessions.get('p0')).hide.id,g.id)});
test('serialization/restart and full AI matches terminate with valid scores and finite positions',()=>{let hunters=0;for(let seed=1;seed<=30;seed++){const g=make('random',1);R.startHide536(g,0,seed);g.players.forEach(p=>p.ai=true);advance(g,25000);const b=JSON.parse(JSON.stringify(g));advance(g,80000);advance(b,80000);assert.deepEqual(g,b);assert.equal(g.phase,'result');assert.equal(g.results.length,4);assert.ok(g.shots>=0&&g.shots<=12);if(g.winningSide==='hunter')hunters++;assert.ok(g.players.every(p=>Number.isFinite(p.x)&&p.x>=100&&p.x<=900&&p.y>=185&&p.y<=1240))}console.log('AI hunter wins / 30:',hunters)});
