import test from 'node:test';
import assert from 'node:assert/strict';
import {makeLobby463,start463,settle463,action463,public463} from '../src/sugoroku/Engine463.js';
import {NODES463} from '../src/sugoroku/Board463.js';
import {CARDS463} from '../src/sugoroku/Catalog463.js';
import {setSpecial528,markGreedTurn528,greedLeft528} from '../src/sugoroku/Greed528.js';
import {moveRoutes528,stopNotice528,gateBadge528} from '../src/sugoroku/Stops528.js';
import {makeGorilla505,startGorilla505,pinchGorilla505,advanceGorilla505,publicGorilla505,pinchRisk528,discomfort505} from '../src/gorilla/Rules505.js';
import {decideGorilla503} from '../src/gorilla/Rules503.js';
import {pullGorilla504} from '../src/gorilla/Rules504.js';
import {makeLuck511,startLuck511,drawPlan511,chooseLuck511,advanceLuck511,publicLuck511,rounds528,ITEMS511,resolveRound511} from '../src/luck/Rules511.js';
import {BIG511} from '../src/luck/Items511.js';
import {handleLuck511} from '../online-server/src/LuckCoordinator511.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'Player '+i,owned:[{id:'m'+i,speciesId:['slime','goblin','wolf','skeleton'][i]}],choice:{id:'m'+i,speciesId:['slime','goblin','wolf','skeleton'][i]}}));
function sg(){const g=makeLobby463({id:'sg',code:'ABC',partyId:'party',hostId:'p0',members,seed:987});start463(g,1000);g.step='pre';g.players.forEach(p=>{p.hand=[];p.special=null;p.visited469=[]});g.deck=g.deck.filter(u=>{const c=CARDS463.find(c=>c.id===g.cards[u]);return c.kind==='good'&&c.timing!=='instant'});setSpecial528(g,g.players[0],'greed');return g}
function effect(g,type,n=1,extra={}){g.queue.push({type,n,actor:'p0',target:'p0',source:'test',group:'test'+g.effectId++,...extra});settle463(g)}
function grant(g,p,count){const c=CARDS463.find(c=>c.timing==='pre'&&c.kind==='good'&&!c.onDiscard);for(let i=0;i<count;i++){const u='test'+Object.keys(g.cards).length;g.cards[u]=c.id;p.hand.push(u)}}
function choose(g,value){action463(g,g.pending.playerId,{kind:'choice',value},1001)}
const gates=Object.values(NODES463).filter(n=>n.kind==='gate').map(n=>n.id);
test('greed doubles extra dice, caps at five, and amplifies roll and bonus exactly once',()=>{const g=sg(),p=g.players[0];p.visited469=[...gates];effect(g,'dice',1);assert.equal(p.mods.dice,4);effect(g,'dice',1);assert.equal(p.mods.dice,5);effect(g,'bonus',3);assert.equal(p.mods.bonus,6);action463(g,'p0',{kind:'roll'},1001);assert.equal(g.lastRoll.total,g.lastRoll.dice.reduce((a,b)=>a+b,0)*2+6);assert.equal(g.lastRoll.greed528,true)});
test('greed +10 card becomes 20, including exact remaining distance through forks',()=>{const g=sg(),p=g.players[0];p.visited469=[...gates];const expected=moveRoutes528(p,20);effect(g,'direct',10);while(g.pending){assert.equal(g.pending.kind,'fork');choose(g,g.pending.options[0].value)}assert.equal(p.pos,expected[0].id);assert.equal(p.trail.length,21);assert.equal(p.mods.noRoll,true)});
test('normal roll never doubles a second time after selecting a fork',()=>{for(let seed=1;seed<20;seed++){const g=sg(),p=g.players[0];g.seed=seed;p.visited469=[...gates];action463(g,'p0',{kind:'roll'},1001);const rolled=g.lastRoll.total;while(g.pending&&g.pending.kind==='fork')choose(g,g.pending.options[0].value);const movement=g.presentation464.filter(e=>e.kind==='move'&&e.actorId==='p0').reduce((n,e)=>n+e.path465.length-1,0);assert.ok(movement>=rolled);assert.equal(g.presentation464.find(e=>e.kind==='dice').total,rolled)}});
test('unvisited gates stop +10/greed before wasting remainder; preview matches authority',()=>{const g=sg(),p=g.players[0];p.pos='5';p.trail=['0','1','2','3','4','5'];const card={effects:[{type:'direct',n:10}]},preview=moveRoutes528(p,20)[0];assert.equal(preview.id,'8');assert.equal(preview.steps,3);assert.equal(preview.left,17);assert.match(stopNotice528(p,card),/20マス進む → 3〜7マス先.*繰り越さない/s);effect(g,'direct',10);if(g.pending?.kind==='fork')choose(g,g.pending.options[0].value);assert.equal(p.pos,'8');assert.ok(p.visited469.includes('8'));assert.match(gateBadge528(p,NODES463['8']),/通過 OK/);assert.ok(public463(g,'p0').players[0].visited469.includes('8'))});
test('visited gates are passable and preview shows the next first-visit stop',()=>{const g=sg(),p=g.players[0];p.pos='5';p.visited469=['8'];assert.ok(moveRoutes528(p,10).every(r=>r.id!=='8'));assert.doesNotMatch(stopNotice528(p),/あと3マス/)});
test('negative movement and discards double; payment costs and fixed effects do not',()=>{const g=sg(),p=g.players[0];p.trail=Array.from({length:8},(_,i)=>String(i));p.pos='7';effect(g,'move',-2);assert.equal(p.pos,'3');grant(g,p,10);effect(g,'discard',2);assert.equal(p.hand.length,6);effect(g,'discard',1,{cost:true});assert.equal(p.hand.length,5);effect(g,'bonus',2,{noGreed:true});assert.equal(p.mods.bonus,2);effect(g,'skip',1);assert.equal(p.skip,2)});
test('draw/recover/steal amplify once, and the receiver greed does not multiply incoming theft again',()=>{const g=sg(),[p,q]=g.players;effect(g,'draw',1,{mode:'hold'});assert.equal(p.hand.length,2);grant(g,q,5);effect(g,'steal',1,{target:'p1'});assert.equal(g.pending.data.remaining,2);choose(g,'0');choose(g,g.pending.options[0].value);assert.equal(p.hand.length,4);assert.equal(q.hand.length,3);effect(g,'discard',1);effect(g,'recover',1);assert.equal(g.pending.data.remaining,2)});
test('greed expires after two playable own turns, and skipped turns do not spend it',()=>{const g=sg(),p=g.players[0];for(let i=0;i<2;i++){g.turn=0;g.step='pre';p.mods={bonus:0,dice:2};markGreedTurn528(g,p);g.step='ending';settle463(g);assert.equal(p.special,i===0?'greed':null);if(!i)assert.equal(greedLeft528(p),1)}const h=sg(),q=h.players[0];h.step='draw';delete q.greedActiveTurn528;q.skip=1;action463(h,'p0',{kind:'draw'});assert.equal(q.greedTurns528,2)});
test('greed acquired after movement keeps two future turns; transfer preserves remaining lifetime',()=>{const g=sg(),[p,q]=g.players;g.step='ending';setSpecial528(g,p,'greed');assert.equal(p.greedActiveTurn528,undefined);settle463(g);assert.equal(p.greedTurns528,2);g.turn=1;g.step='pre';setSpecial528(g,p,'greed',1);effect(g,'swapSpecial',1,{actor:'p1',target:'p0'});assert.equal(q.special,'greed');assert.equal(q.greedTurns528,1);assert.equal(p.special,null)});
function gorilla(coin=0,badHair=29){const g=makeGorilla505({id:'gg',code:'ABC',partyId:'party',hostId:'p0',members,seed:91});startGorilla505(g,0,{badHair,firstSeat:0,mercyCoins504:Array(30).fill(coin),trapOrder504:Array.from({length:30},(_,i)=>i)});advanceGorilla505(g,g.startAt+650);assert.equal(g.phase,'playing');return g}
const ggstep=g=>advanceGorilla505(g,g.nextAt);
test('pinch rage probability escalates with shared anger: 25 / 55 / 80 percent',()=>{for(const [anger,expected]of[[0,25],[12,55],[24,80]]){let rage=0,near=0;for(let r=0;r<100;r++){const g=gorilla();g.painOffset505=anger;assert.equal(pinchRisk528(g,'p0'),expected);pinchGorilla505(g,'p0',0,0,0,g.thinkAt503+1,()=>r);ggstep(g);if(g.phase==='blast')rage++;else if(discomfort505(g)>=24)near++;assert.ok(discomfort505(g)>=anger+4)}assert.equal(rage,expected);assert.ok(near>=Math.floor((100-expected)*.8))}});
test('three consecutive pinches cannot escape: third always loses, even RNG 99',()=>{const g=gorilla();for(let i=0;i<3;i++){pinchGorilla505(g,'p0',i%2,0,i,g.thinkAt503+1,()=>99);ggstep(g);if(i<2){assert.equal(g.phase,'reaction');ggstep(g);decideGorilla503(g,'p0','continue',0,i+1,g.thinkAt503+1);ggstep(g)}}assert.equal(g.phase,'blast');assert.equal(g.loserId,'p0');ggstep(g);assert.equal(g.phase,'result');assert.ok(g.results.find(p=>p.playerId==='p0').blownFar)});
test('pending pinch outcome survives serialization, stays private, and duplicate input does not reroll',()=>{const g=gorilla();let rolls=0;const args=['p0',0,0,0,g.thinkAt503+1,()=>{rolls++;return 0}];assert.equal(pinchGorilla505(g,...args),true);assert.equal(pinchGorilla505(g,...args),false);assert.equal(rolls,1);const pub=publicGorilla505(g);assert.equal(pub.pendingRage528,undefined);assert.equal(pub.loserId,null);assert.equal(pub.events[0].kind,'safe');const copy=JSON.parse(JSON.stringify(g));ggstep(copy);ggstep(g);assert.deepEqual(copy,g)});
test('wrong actor / expired / stale pinch rejects before RNG draw',()=>{for(const mode of['wrong','expired','stale']){const g=gorilla();let draws=0;assert.throws(()=>pinchGorilla505(g,mode==='wrong'?'p1':'p0',0,mode==='stale'?1:0,0,mode==='expired'?g.deadline:g.thinkAt503+1,()=>{draws++;return 0}));assert.equal(draws,0)}});
test('ordinary hair still uses the original mercy coin even at maximum anger',()=>{for(const coin of[0,1]){const g=gorilla(coin,0);g.painOffset505=80;pullGorilla504(g,'p0',0,0,g.thinkAt503+1);ggstep(g);assert.equal(g.phase,'drum');ggstep(g);assert.equal(g.phase,coin?'reaction':'blast')}});
const plan=n=>drawPlan511(k=>k-1,n);
function luck(n=8,count=4){const g=makeLuck511({id:'lk',code:'ABC',partyId:'party',hostId:'p0',members:members.slice(0,count)});g.rounds=n;startLuck511(g,0,plan(n));return g}
test('8/16 plans have unique hands and a finisher in every final box; mismatched plans reject',()=>{for(const n of[8,16]){const p=plan(n);assert.equal(p.length,n);for(const r of p)for(const s of r.seats)for(const h of s.boxes)assert.equal(new Set(h).size,4);for(const s of p.at(-1).seats)for(const h of s.boxes)assert.ok(h.some(i=>BIG511.includes(i)));const g=luck(n);g.phase='lobby';assert.throws(()=>startLuck511(g,0,plan(n===8?16:8)));}assert.throws(()=>drawPlan511(k=>0,12))});
test('complete 8/16-round matches with four humans and with three AI reach results exactly once',()=>{for(const n of[8,16])for(const count of[1,4]){const g=luck(n,count);let steps=0;const seen=new Set();while(g.phase!=='result'&&steps++<1000){seen.add(g.round);if(['chest','hand'].includes(g.phase))for(const p of g.players.filter(p=>!p.ai))chooseLuck511(g,p.playerId,g.phase,0,g.round,g.phaseAt+1);advanceLuck511(g,g.nextAt)}assert.equal(g.phase,'result');assert.equal(g.round,n);assert.equal(g.history.length,n);assert.equal(seen.size,n);assert.equal(g.results.length,4);assert.equal(publicLuck511(g,'p0').rounds,n);assert.equal(advanceLuck511(g,1e9),false)}});
test('crown fires on round16 only; round8 is an ordinary turn in a 16-round match',()=>{for(const r of[8,16]){const g=luck(16);g.round=r;g.players[0].loadout=[{id:'crown',round:1}];g.boxes511=[0,0,0,0];g.items511=[0,0,0,0];g.auto511=[false,false,false,false];for(const s of g.plan511[r-1].seats)s.boxes[0]=['rocket','dash','shield','engine'];const result=resolveRound511(g,100);const row=result.rows[0];assert.equal(row.gain,r===16?3000:600)}});
test('round16 preserves exact enormous distances and other player hands stay secret',()=>{const g=luck(16);g.round=16;g.players[0].distance='999999999999999999999999999999999999';g.boxes511=[0,0,0,0];g.items511=[0,0,0,0];g.auto511=[false,false,false,false];for(const s of g.plan511[15].seats)s.boxes[0]=['rocket','dash','shield','engine'];const e=resolveRound511(g,100);assert.equal(BigInt(e.rows[0].to),BigInt(g.players[0].distance)+500n);g.phase='hand';const pub=publicLuck511(g,'p0');assert.equal(pub.plan511,undefined);assert.equal(pub.players[1].hand,undefined);const old=luck();delete old.rounds;assert.equal(rounds528(old),8)});
function coordinator(){const g=makeLuck511({id:'lk',code:'ABC',partyId:'party',hostId:'p0',members}),party={id:'party',code:'ABC',hostId:'p0',members:members.map(m=>({...m,ready:true,luckVersion511:1,minigamesVersion528:1}))};const sessions=new Map(members.map(m=>[m.playerId,{playerId:m.playerId,connected:true}]));const c={data:{parties462:{ABC:party},luckRooms507:{ABC:g}},sessions,now:()=>1000,isBusy:()=>false};const send=(kind,extra={},id='p0')=>handleLuck511(c,sessions.get(id),{op:'luck511',gameId:g.id,kind,luckVersion511:1,minigamesVersion528:1,...extra});return{g,party,c,send}}
test('host round selection validates phase/value, resets ready only on a change, and starts chosen length',()=>{const {g,party,send}=coordinator();assert.throws(()=>send('rounds',{rounds:16},'p1'),/部屋主/);assert.throws(()=>send('rounds',{rounds:12}));send('rounds',{rounds:8});assert.ok(party.members.every(m=>m.ready));send('rounds',{rounds:16});assert.ok(party.members.every(m=>!m.ready));assert.throws(()=>send('start'),/準備/);party.members.forEach(m=>m.ready=true);send('start');assert.equal(g.plan511.length,16);assert.throws(()=>send('rounds',{rounds:8}),/開始前/)});
test('mixed old/new clients cannot start a changed minigame',()=>{const {party,send}=coordinator();party.members[2].minigamesVersion528=0;assert.throws(()=>send('start'),/Build528/)});
