import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {run,monster} from '../tools/build422/native-harness.mjs';
import {calculatedStats} from '../src/models/Monster.js';
import {trialTier415,prepareTrial415,cleanupTrial415} from '../src/battle/TrialAdaptation415.js';
import {motherState422,motherUnlocked422,beginMother422,settleMother422} from '../src/primordial/State422.js';
import {MOTHER_ID422,MOTHER_ENEMY422,MOTHER_SPECIES422,MOTHER_ATLAS422,tuneMother422} from '../src/primordial/Mother422.js';
import {MOTHER_STORIES422} from '../src/primordial/Story422.js';
import {RESONANCE_PAIRS385,resolveTwin385} from '../src/battle/TwinResonance385.js';
import {SaveService} from '../src/services/SaveService.js';
import {BattleScreen} from '../src/ui/screens/BattleScreen.js';
import {chapterTwoAtlasHtml383} from '../src/ui/ChapterTwoSprite383.js';
const ids=['ch2_seria','ch2_carmia','ch2_rostia','ch2_althea'];
function state(){const s=new SaveService().state;s.player.inRun=false;s.player.maxFloor=100;s.player.currentFloor=100;s.campaign100.finalCompleted=true;s.chapterTwo376={areaClears378:{4:1}};s.monsters=ids.map(id=>monster(id,4200));s.party=s.monsters.map(m=>m.id);return s;}
test('fresh second chapter and mother battles use natural stats for every party size',()=>{for(const type of ['chapterTwo','mother422'])for(const count of [1,2,3,4]){const party=ids.slice(0,count).map(id=>monster(id,3000)),before=party.map(calculatedStats),b={party,specialBattleType:type};assert.equal(trialTier415(b),null);assert.equal(prepareTrial415(b,calculatedStats),false);assert.deepEqual(party.map(calculatedStats),before);}});
test('cleared second chapter unlocks the sanctum without replaying or changing chapter one',()=>{const s=state(),before=JSON.stringify(s.campaign100);assert.equal(motherUnlocked422(s),true);assert.equal(motherState422(s).phase,'approach');assert.equal(JSON.stringify(s.campaign100),before);s.chapterTwo376.areaClears378[4]=0;assert.equal(motherUnlocked422(s),false);assert.equal(beginMother422(s).ok,false);});
test('attempt IDs, defeat, retreat-equivalent settlement and first rewards are idempotent',()=>{const s=state();s.inventory.potions=12;const gold=s.player.gold,crystals=s.player.crystals;const a=beginMother422(s);assert.equal(a.ok,true);assert.equal(beginMother422(s).ok,false);s.inventory.potions=2;assert.equal(settleMother422(s,false).won,false);assert.equal(s.inventory.potions,12);assert.equal(s.player.gold,gold);const b=beginMother422(s);assert.notEqual(a.id,b.id);assert.equal(settleMother422(s,true).first,true);assert.equal(s.player.gold,gold+300000);assert.equal(s.player.crystals,crystals+1000);assert.equal(settleMother422(s,true).duplicate,true);assert.equal(beginMother422(s).ok,true);assert.equal(settleMother422(s,true).first,false);assert.equal(s.player.gold,gold+300000);assert.equal(s.primordial422.wins,2);});
test('dead parties cannot begin; partial dialogue and independent progression survive actual save reload',()=>{const s=state();s.monsters.forEach(m=>m.currentHp=0);assert.equal(beginMother422(s).ok,false);const r=motherState422(s);r.dialogues.ending={index:4,complete:false};r.cleared=true;r.phase='victory';const db=new Map();globalThis.localStorage={getItem:k=>db.get(k)??null,setItem:(k,v)=>db.set(k,v),removeItem:k=>db.delete(k)};const service=new SaveService();service.state=s;assert.equal(service.save(),true);const restored=new SaveService().state;assert.equal(restored.primordial422.dialogues.ending.index,4);assert.equal(restored.primordial422.phase,'victory');assert.equal(restored.campaign100.finalCompleted,true);});
test('both enemy and allied glass pairs use two followups, 10% healing and the same round reset',async()=>{const pair=RESONANCE_PAIRS385.find(p=>p.id==='glassaria'),f=await run(pair.members,pair.members,{inspect:true,circles:false,battleOptions:{specialBattleType:'chapterTwo'}});const b=f.b;try{for(const side of ['ally','enemy']){const roster=side==='ally'?b.party:b.enemies;let heals=[],hits=0;const env={...f.context.pairBattleEnvironment385(roster[0],side),alive:(u,s)=>s==='enemy'?u.hp>0:u.currentHp>0,cue:async()=>{},hit:async()=>{hits++;return 1},heal:async(u,rate)=>heals.push(rate),weaken:()=>{},effects:()=>[],hasEffect:()=>false,hasStatus:()=>false,stats:u=>({hp:u.maxHp??100})};assert.equal(await resolveTwin385(b,roster[0],side,env),true);assert.equal(await resolveTwin385(b,roster[1],side,env),true);assert.equal(await resolveTwin385(b,roster[0],side,env),false);assert.ok(heals.every(r=>r===.1));assert.ok(hits>0);}b.turn++;assert.equal(await resolveTwin385(b,b.enemies[0],'enemy',{...f.context.pairBattleEnvironment385(b.enemies[0],'enemy'),cue:async()=>{},hit:async()=>1,heal:async()=>{}}),true);}finally{cleanupTrial415(b);}});
test('mother uses registered native authored skills, complete atlas frames and existing battle markup',async()=>{const f=await run(ids,['slime'],{inspect:true,battleOptions:{specialBattleType:'mother422',specialBattle:true}});const enemy=tuneMother422(f.context.makeBattleEnemy(MOTHER_ENEMY422));assert.equal(enemy.speciesId,MOTHER_ID422);assert.equal(enemy.uncapturable,true);assert.equal(MOTHER_SPECIES422.authoredSkills.length,5);for(const frame of ['idle1','idle2','idle3','walk1','walk2','attack','damage','down']){assert.match(chapterTwoAtlasHtml383(MOTHER_ID422,frame,'idle'),/ionea422.png/);const [l,t,r,b]=MOTHER_ATLAS422.frames[frame].box;assert.ok(l>=0&&t>=0&&r<=1254&&b<=1254&&r>l&&b>t);}f.b.enemies=[enemy];f.b.enemy=enemy;const html=BattleScreen(f.b,{},f.context.save.state.settings,100);assert.match(html,/mother-battle422/);assert.match(html,/combat-rank-badge/);assert.match(html,/原母イオネア/);assert.match(html,/enemy-card-meta/);});
test('all mother dialogue is authored, ending stays replayable and leaves an optional continuation',()=>{for(const [key,lines]of Object.entries(MOTHER_STORIES422)){assert.ok(lines.length>=2,key);assert.ok(lines.every(l=>l.speaker&&l.text));}const text=MOTHER_STORIES422.ending.map(l=>l.text).join('');assert.match(text,/世界の檻/);assert.match(text,/こちらにも、朝/);assert.doesNotMatch(text,/第三章へ進む|第3章へ進む/);});
test('mother native command reaches real enemy AI and can finish without a progress stall',async()=>{const f=await run(ids,['slime'],{inspect:true});const enemy=tuneMother422(f.context.makeBattleEnemy(MOTHER_ENEMY422));const result=await run(ids,[],{level:4200,gear:true,circles:true,enemyUnits:[enemy],seed:7,maxRounds:40,battleOptions:{specialBattleType:'mother422',specialBattle:true}});assert.ok(result.won||result.lost);assert.ok(result.rounds>1&&result.rounds<40);assert.ok(result.metrics.taken>0);});

test('native mother result persists restored supplies/vitals before revealing contribution and cannot award twice',async()=>{
 const f=await run(ids,['slime'],{inspect:true,battleOptions:{specialBattle:true,specialBattleType:'mother422'}}),c=f.context,s=c.save.state;
 delete s.primordial422;s.player.inRun=false;s.chapterTwo376={areaClears378:{4:1}};s.inventory.potions=5;beginMother422(s);f.b.priorVitals=Object.fromEntries(f.party.map(u=>[u.id,{hp:u.currentHp,mp:u.currentMp,ailments:[]}]));f.party[0].currentHp=1;s.inventory.potions=0;
 let saved,html='',revealed=false;const primary={},modal={querySelector:()=>primary,remove(){},classList:{add(){}}};
 c.save.save=()=>{saved=JSON.parse(JSON.stringify(c.save.state));return true};c.topModal=()=>modal;c.app.insertAdjacentHTML=(_,v)=>html=v;c.render=()=>{};c.audio={setScene(){},sfx(){}};c.openBattleContributionReport=(_,reveal)=>{revealed=true;reveal()};c.showToast=()=>{};
 const gold=s.player.gold;c.finishMotherBattle422(true);assert.equal(saved.inventory.potions,5);assert.equal(saved.monsters[0].currentHp,f.b.priorVitals[f.party[0].id].hp);assert.equal(s.player.gold,gold+300000);assert.equal(revealed,true);assert.match(html,/戦闘結果/);assert.equal(c.battle,null);c.finishMotherBattle422(true);assert.equal(s.player.gold,gold+300000);
});
test('native mother save checkpoint resumes in sanctum with its attempt and action commit preserved',async()=>{
 const f=await run(ids,['slime'],{inspect:true,battleOptions:{specialBattle:true,specialBattleType:'mother422'}}),c=f.context,s=c.save.state;s.player.inRun=false;s.chapterTwo376={areaClears378:{4:1}};
 const attempt=beginMother422(s);f.b.battleId=attempt.id;f.b.actionCommitted=true;f.b.specialReturnScreen='primordial422';c.save.save=()=>true;f.nativeSave();assert.equal(s.activeBattle.battleId,attempt.id);c.battle=null;let finished=0;c.renderBattle=()=>{};c.finishCurrentAction=()=>finished++;c.setTimeout=fn=>{fn();return 0};assert.equal(f.nativeResume(),true);assert.equal(c.screen,'primordial422');assert.equal(finished,1);assert.equal(c.battle.skillMenu,false);assert.equal(s.primordial422.attempt.id,attempt.id);
});
test('native mother dialogue preserves index on dismiss and only completes after final confirmation',async()=>{
 const f=await run(ids,['slime'],{inspect:true}),c=f.context;supply();function supply(){c.save.state.player.inRun=false;c.save.state.chapterTwo376={areaClears378:{4:1}};c.save.save=()=>true;c.campaignStoryPresenting=false;c.screen='home';c.showToast=()=>{};}
 const nodes=new Map(),node=key=>{if(!nodes.has(key))nodes.set(key,{textContent:''});return nodes.get(key)},modal={querySelector:node,remove(){},classList:{add(){}}};c.topModal=()=>modal;c.app.insertAdjacentHTML=()=>{};
 c.showMotherStory422('introduction');node('[data-modal-primary]').onclick();assert.equal(motherState422(c.save.state).dialogues.introduction.index,1);modal._onDismiss();assert.equal(c.campaignStoryPresenting,false);assert.equal(motherState422(c.save.state).introRead,false);
 c.showMotherStory422('introduction');assert.match(node('[data-mother-page]').textContent,/2 \/ 4/);for(let i=0;i<3;i++)node('[data-modal-primary]').onclick();assert.equal(motherState422(c.save.state).introRead,true);assert.equal(c.campaignStoryPresenting,false);
});
