import {pairVm409} from './helpers/pair409-vm.mjs';
import {CHAPTER_TWO_PAIRS387} from '../src/data/chapterTwoPairs387.js';
import {chapterTwoSprite383} from '../src/ui/ChapterTwoSprite383.js';
import {monsterVisual} from '../src/ui/MonsterVisual.js';
import {tickBattleEffects} from '../src/battle/BattleRules.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {SPECIES} from '../src/data/species.js';
import {CHAPTER_TWO_SPECIES387} from '../src/data/chapterTwoSpecies387.js';
import {chapterTwoCaptureChance383} from '../src/data/chapterTwoSpecies383.js';
import {CHAPTER_TWO_ACTIONS387} from '../src/chapterTwo/ChapterTwoMonsters387.js';
import {CHAPTER_TWO_SPRITES387} from '../src/data/chapterTwoSprites387.js';
import {chapterTwoFrame383,chapterTwoCanvasFrame383} from '../src/ui/ChapterTwoSprite383.js';
import {createMonster,calculatedStats,displayName} from '../src/models/Monster.js';
import {learnedSkills,allSpeciesSkills,maxMp,skillDamage,chooseAutoBattleDecision} from '../src/battle/SkillSystem.js';
import {createEnemyBattleState,chooseEnemyAction,specialActionInfo,enemyActionMpCost} from '../src/battle/EnemyAI.js';
import {applyEnemyDamage,applyBattleEffect,hasEffect,effectValue} from '../src/battle/BattleRules.js';
import {ENCOUNTERS,chapterTwoEnemyEntries,tuneChapterTwoEnemy,CHAPTER_TWO_AREAS} from '../src/chapterTwo/ChapterTwoSystem.js';
import {eligibleEncounterSpecies} from '../src/core/EncounterPoolSystem.js';
import {SaveService} from '../src/services/SaveService.js';
import {TWIN_PAIRS385,twinPair385,twinReady385,reserveTwin385,resolveTwin385} from '../src/battle/TwinResonance385.js';
import {twinStatus385,twinCodex385} from '../src/ui/TwinStatus385.js';
import {BattleScreen} from '../src/ui/screens/BattleScreen.js';
const roster=Object.values(CHAPTER_TWO_SPECIES387),main=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
function monster(key){const m=createMonster('ch2_'+key,{level:1500});m.currentHp=calculatedStats(m).hp;m.currentMp=maxMp(m);return m;}
function encounter(id){return chapterTwoEnemyEntries(id).map((e,i)=>{const u=createEnemyBattleState(SPECIES[e.speciesId],{...e,id:'e'+i,combatRarity:SPECIES[e.speciesId].rarity},100);tuneChapterTwoEnemy(u,id,i);return u;});}
function state(keys=['ryune','rose']){return {party:keys.map(monster),enemies:[{id:'e',hp:1e10,maxHp:1e10,def:100,mdef:100,element:'neutral'}],turn:1,allyEffects:{},enemyEffects:{},enemyStatuses:{},allyAilments:{},circleShields:{}};}
function simpleEnv(b){const calls={hits:[],heals:[],shields:[],cues:[],weakens:[]};return {calls,blocked:()=>false,opponents:()=>b.enemies.filter(e=>e.hp>0),cue:async p=>calls.cues.push(p.pair.id),hit:async(s,t,p)=>{calls.hits.push([s.id,t.id,p.power]);t.hp-=1;return 1;},heal:async(u,r)=>calls.heals.push([u.id,r]),shield:(u,r)=>calls.shields.push([u.id,r]),weaken:(u,e)=>calls.weakens.push([u.id,e.kind])};}
function runtime(b){const logs=[],floats=[],hits=[];const c={battle:b,save:{state:{equipment:[]}},SPECIES,resolveTwin385,calculatedStats,displayName,POSITIVE_ENEMY_EFFECTS:new Set(['atkUp','defUp','spdUp','accuracyUp','evasionUp','guard']),skillDamage,applyEnemyDamage,applyBattleEffect,effectValue,hasEffect,allyAilment:(u,id)=>(b.allyAilments[u.id]??[]).find(s=>s.id===id),aliveEnemies:x=>x.enemies.filter(e=>e.hp>0),ultimateIsolated:(_b,u)=>!!u.isolated,ultimateExtraBlocked:(_b,u)=>!!u.blocked,convertedAttackStats:s=>s,attackHits:()=>true,allyAttackFactor:id=>1+effectValue(b,id,'atkUp')-effectValue(b,id,'atkDown'),enemyDefenseFactor:id=>1+effectValue(b,id,'defUp','enemy')-effectValue(b,id,'defDown','enemy'),attributeDamageMultiplier:()=>1,abyssBattleMultiplier:()=>1,enemyDamageMultiplier:()=>1,endgameIncomingDamageMultiplier:()=>1,weaponMasteryDamageMultiplier:()=>1,magicCircleDamageMultiplier:()=>1,affixValue:()=>0,addBattleLog:(_b,s)=>logs.push(s),battleBanner:async()=>{},animateAttack:async()=>{},animateHit:async()=>{},floatText:async(...a)=>floats.push(a),recordBattleDamage(){},registerWeaponFinisher(){},recordBattleHealing(){},flushBattleRecoveries:async()=>{},queueBattleRecovery(){},heroOverheal(){},dealEnemyHit:async(e,t,p,label,crit,element,rules)=>{hits.push({e,t,p,element,rules});t.currentHp=Math.max(0,t.currentHp-10);return 10;}};
 const start=main.indexOf('async function resolveTwinResonance385('),end=main.indexOf('async function triggerInvincibleAlliance(',start);assert.ok(start>0&&end>start);vm.createContext(Object.assign(c,{...pairVm409,...c}));vm.runInContext(main.slice(start,end),c);
 const recoveryStart=main.indexOf('function recoverBattleHp('),recoveryEnd=main.indexOf('function storeFloorBossManaNocturne(',recoveryStart);vm.runInContext(main.slice(recoveryStart,recoveryEnd),c);return{c,logs,floats,hits};}

test('all current releases retain an equal rank roster and complete capturable pairs',()=>{
 const all=Object.values(SPECIES).filter(s=>s.chapterTwoOnly),seen=new Set();assert.equal(all.length,70);for(const rank of ['N','R','SR','SSR','UR','LR','神話'])assert.equal(all.filter(s=>s.rarity===rank).length,10);assert.equal(Object.keys(CHAPTER_TWO_ACTIONS387).length,28);assert.equal(CHAPTER_TWO_PAIRS387.length,3);
 const ordinary=new Set(eligibleEncounterSpecies(SPECIES,999999).map(s=>s.id));for(const s of all){assert.equal(ordinary.has(s.id),false);assert.equal(s.gachaExcluded,true);assert.equal(allSpeciesSkills(s.id).length,4);}
 for(const [id,e] of Object.entries(ENCOUNTERS).filter(([,e])=>e.roaming&&!e.elite393))for(const u of encounter(id)){seen.add(u.speciesId);assert.equal(u.uncapturable,false);}
 for(const s of all)assert.ok(seen.has(s.id),s.id);const pairs=new Set(all.map(s=>twinPair385(s.id)?.id).filter(Boolean));assert.equal(pairs.size,24);for(const s of roster){assert.equal(chapterTwoCaptureChance383(s.id,.99),s.captureCap383);for(const k of s.authoredSkills){assert.equal(specialActionInfo(k.id).power,k.power);assert.equal(enemyActionMpCost({},k.id),k.mp);}}
});
test('all new habitats match the codex, use six real gear slots and keep each pair together',()=>{
 for(const id of ['roam0_1','roam1_4','roam2_1','roam4_3']){const e=ENCOUNTERS[id],units=encounter(id);assert.ok(e.roaming);for(const u of units){const s=SPECIES[u.speciesId];if(!s.chapterTwoSet387)continue;assert.equal(u.enemyGear.length,6);assert.ok(u.enemyEquipmentLevel>0);assert.ok(u.enemyMagicCircle.id);for(const k of ['maxHp','maxMp','atk','matk','def','mdef','spd'])assert.ok(Number.isFinite(u[k])&&u[k]>0);const magic=s.authoredSkills.filter(k=>k.power>0).every(k=>k.damageClass==='magic');assert.ok(u.enemyGear.slice(0,2).every(w=>(w.stats[magic?'matk':'atk']??0)>0));assert.ok(s.habitat383.includes(CHAPTER_TWO_AREAS[e.area].rooms.find(r=>r.id===e.room).name));}}
 for(const p of CHAPTER_TWO_PAIRS387)assert.ok(Object.values(ENCOUNTERS).some(e=>e.roaming&&p.members.every(id=>e.species.includes(id))));assert.equal(ENCOUNTERS.roam4_4.species[0],'ch2_ordia');assert.equal(ENCOUNTERS.roam4_3.species[0],'ch2_luxion');
});
test('the seven new captures preserve four learned skills, depleted HP/MP and pair identity across SaveService',()=>{
 const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k)};const save=new SaveService();for(const s of roster){const m=monster(s.key);m.currentHp=0;m.currentMp=3;save.state.monsters.push(m);}save.save();const loaded=new SaveService();for(const s of roster){const m=loaded.state.monsters.find(u=>u.speciesId===s.id);assert.equal(m.currentHp,0);assert.equal(m.currentMp,3);assert.equal(learnedSkills(m).length,4);assert.equal(twinPair385(m)?.id,twinPair385(s.id)?.id);assert.equal(m.enemyGear,undefined);}
});
test('rabbit rescue triggers at 35 percent on a living sister, not on an unrelated ally or a dead sister',async()=>{
 const b=state(['rikka','rinne','pipia']),env=simpleEnv(b);env.hpRatio=u=>u.currentHp/calculatedStats(u).hp;b.party[2].currentHp=1;await resolveTwin385(b,b.party[0],'ally',env);assert.equal(env.calls.hits[0][2],2.2);assert.equal(env.calls.heals.length,0);b.turn++;b.party[0].currentHp=Math.floor(calculatedStats(b.party[0]).hp*.35);await resolveTwin385(b,b.party[0],'ally',env);assert.equal(env.calls.hits[1][2],3.1);assert.equal(env.calls.heals.length,3);assert.ok(env.calls.heals.every(h=>h[1]===.18));assert.ok(env.calls.shields.slice(-3).every(h=>h[1]===.18));b.turn++;b.party[0].currentHp=0;assert.equal(await resolveTwin385(b,b.party[1],'ally',env),false);
});
test('rescue threshold uses fresh HP and does not mutate normal pair data or reset quota on JSON reload',async()=>{
 let b=state(['rikka','rinne']);const env=simpleEnv(b);env.hpRatio=()=>.35;await resolveTwin385(b,b.party[0],'ally',env);assert.equal(twinPair385('ch2_rikka').power,2.2);b=JSON.parse(JSON.stringify(b));assert.equal(reserveTwin385(b,b.party[0]),null);const env2=simpleEnv(b);env2.hpRatio=()=>.351;await resolveTwin385(b,b.party[1],'ally',env2);assert.equal(env2.calls.hits[0][2],2.2);assert.equal(env2.calls.heals.length,0);
});
test('actual rabbit rescue applies recovery suppression and bounded shields without resurrection',async()=>{
 const b=state(['rikka','rinne','pipia']);b.party.forEach(u=>u.currentHp=1);b.party[2].currentHp=0;applyBattleEffect(b,b.party[0].id,{kind:'healDown',value:.5,turns:2});const {c,logs}=runtime(b);await c.resolveTwinResonance385(b.party[0]);assert.ok(logs.some(l=>l.includes('繕命の奇跡')));assert.equal(b.party[0].currentHp,1+Math.floor(Math.floor(calculatedStats(b.party[0]).hp*.18)*.5));assert.equal(b.party[2].currentHp,0);for(const u of b.party.slice(0,2))assert.equal(b.circleShields[u.id],Math.floor(calculatedStats(u).hp*.18));assert.equal(b.circleShields[b.party[2].id],undefined);
});
test('glass duet requires BOTH effects per target, and expires when either mark clears',async()=>{
 const b=state(['seria','carmia']);b.enemies.push({...b.enemies[0],id:'half'},{...b.enemies[0],id:'clean'});const env=simpleEnv(b);env.hasEffect=(t,kind)=>t.id==='e'||t.id==='half'&&kind==='spdDown';await resolveTwin385(b,b.party[0],'ally',env);assert.deepEqual(env.calls.hits.map(h=>h[2]),[2.2*1.65,2.2,2.2]);b.turn++;env.hasEffect=(_t,kind)=>kind==='spdDown';await resolveTwin385(b,b.party[0],'ally',env);assert.ok(env.calls.hits.slice(3).every(h=>h[2]===2.2));
});
test('glass enemy AI prepares the missing second mark before spending the first-mark bonus strike',()=>{
 const enemies=encounter('roam2_1'),b=state(),context={allies:enemies,opponents:[{id:'p',currentHp:100,_maxHp:100}],battle:b};assert.equal(chooseEnemyAction(enemies[0],context),'ch2_seria__note');applyBattleEffect(b,'p',{kind:'spdDown',value:.18,turns:2});assert.equal(chooseEnemyAction(enemies[1],context),'ch2_carmia__string');applyBattleEffect(b,'p',{kind:'evasionDown',value:.18,turns:2});assert.equal(chooseEnemyAction(enemies[1],context),'ch2_carmia__forte');assert.equal(chooseEnemyAction(enemies[0],context),'ch2_seria__aria');enemies[1].currentMp=0;assert.equal(chooseEnemyAction(enemies[1],context),'attack');
});
test('player auto prepares both duet marks before normal stances and then switches to the strong skill',()=>{
 const b=state(['seria','carmia']);b.party.forEach(u=>u._maxHp=calculatedStats(u).hp);assert.equal(chooseAutoBattleDecision(b.party[0],b).skill?.id,'ch2_seria__note');applyBattleEffect(b,'e',{kind:'spdDown',value:.18,turns:2},'enemy');assert.equal(chooseAutoBattleDecision(b.party[1],b).skill?.id,'ch2_carmia__string');applyBattleEffect(b,'e',{kind:'evasionDown',value:.18,turns:2},'enemy');assert.equal(chooseAutoBattleDecision(b.party[1],b).skill?.id,'ch2_carmia__forte');b.party[0].currentHp=0;assert.notEqual(chooseAutoBattleDecision(b.party[1],b).reason,'pair-dual-setup');
});
test('actual glass runtime uses enemy effects on ally attacks and ally effects on enemy attacks',async()=>{
 const b=state(['seria','carmia']);b.enemies.push({...b.enemies[0],id:'clean'});for(const kind of ['spdDown','evasionDown'])applyBattleEffect(b,'e',{kind,value:.18,turns:2},'enemy');const {c}=runtime(b),before=b.enemies[0].hp;await c.resolveTwinResonance385(b.party[0]);assert.ok(before-b.enemies[0].hp>(before-b.enemies[1].hp)*1.6);
 const other=state(['pipia']);other.enemies=encounter('roam2_1');for(const kind of ['spdDown','evasionDown'])applyBattleEffect(other,other.party[0].id,{kind,value:.18,turns:2});const {c:enemy,hits}=runtime(other);await enemy.resolveTwinResonance385(other.enemies[0],'enemy');assert.equal(hits[0].p,2.2*1.65);tickBattleEffects(other);tickBattleEffects(other);other.turn++;await enemy.resolveTwinResonance385(other.enemies[0],'enemy');assert.equal(hits.at(-1).p,2.2);
});
test('crown removes one initial buff and one on the first retarget',async()=>{
 const b=state(['aeriel','vespera']);b.enemies[0].hp=1;b.enemies.push({id:'other',hp:100});const order=[],env=simpleEnv(b),hit=env.hit;env.dispel=t=>order.push(['dispel',t.id]);env.hit=async(...args)=>{order.push(['hit',args[1].id]);return hit(...args);};await resolveTwin385(b,b.party[0],'ally',env);assert.deepEqual(order,[['dispel','e'],['hit','e'],['dispel','other'],['hit','other'],['hit','other']]);assert.ok(env.calls.hits.every(h=>h[2]===1.25));assert.equal(env.calls.heals.length,2);
});
test('actual crown clears only one positive effect on the selected target and preserves negatives and shields',async()=>{
 const b=state(['aeriel','vespera']);b.enemies.push({...b.enemies[0],id:'other'});b.enemyEffects.e=[{kind:'defDown',value:.2,turns:3},{kind:'defUp',value:.2,turns:3},{kind:'atkUp',value:.2,turns:3}];b.enemyEffects.other=[{kind:'defUp',value:.2,turns:3}];b.enemies[0]._floorBossHpShield=1e9;const {c}=runtime(b);await c.resolveTwinResonance385(b.party[0]);assert.ok(hasEffect(b,'e','defDown','enemy'));assert.equal(hasEffect(b,'e','defUp','enemy'),false);assert.ok(hasEffect(b,'e','atkUp','enemy'));assert.ok(hasEffect(b,'other','defUp','enemy'));assert.ok(b.enemies[0]._floorBossHpShield>0);
});
test('enemy crown uses the actual ally-buff removal path and 35 percent defense penetration',async()=>{
 const b=state(['pipia']);b.enemies=encounter('roam4_3');const actor=b.enemies.find(e=>e.speciesId==='ch2_aeriel');b.allyEffects[b.party[0].id]=[{kind:'atkDown',value:.1,turns:2},{kind:'guard',value:.3,turns:2},{kind:'accuracyUp',value:.2,turns:2}];const {c,hits}=runtime(b);await c.resolveTwinResonance385(actor,'enemy');assert.equal(hits.length,3);assert.ok(hits.every(h=>h.p===1.25&&h.rules.defenseIgnore===.35&&h.rules.damageClass==='hybrid'));assert.ok(hasEffect(b,b.party[0].id,'atkDown'));assert.equal(hasEffect(b,b.party[0].id,'guard'),false);assert.ok(hasEffect(b,b.party[0].id,'accuracyUp'));
});
test('new pairs stop when one member dies during the cue, and same-species copies cannot give extra activations',async()=>{
 for(const p of CHAPTER_TWO_PAIRS387){const b=state(p.members.map(id=>id.slice(4))),env=simpleEnv(b);env.hpRatio=()=>1;env.dispel=()=>{};env.cue=async()=>{b.party[1].currentHp=0;};await resolveTwin385(b,b.party[0],'ally',env);assert.equal(env.calls.hits.length,0);assert.equal(env.calls.heals.length,0);b.party[1].currentHp=100;b.party.push({...b.party[0],id:'copy'});assert.equal(reserveTwin385(b,b.party[2]),null);}
});
test('the new pair requirements and all enemy names/ranks appear in live battle markup',()=>{
 for(const p of CHAPTER_TWO_PAIRS387){const b=state(p.members.map(id=>id.slice(4)));assert.match(twinStatus385([b.party[0]]),/を編成で発動/);assert.match(twinStatus385(b.party),/共鳴中/);for(const id of p.members)assert.ok(twinCodex385(id).includes(p.description));}
 const b=state(['aeriel','vespera']);b.enemies=encounter('roam4_3');b.turnQueue=[];const html=BattleScreen(b,{},{});for(const e of b.enemies){const start=html.indexOf(`data-enemy-target="${e.id}"`),end=html.indexOf('side-unit-sprite',start);assert.ok(html.slice(start,end).includes(e.name));assert.ok(html.slice(start,end).includes('combat-rank-badge'));}assert.ok(html.includes('終始・双冠の断罪'));
});
test('all 56 new poses are true RGBA, right-facing and within the 256px live renderer bounds',()=>{
 const oldDoc=globalThis.document,oldImage=globalThis.Image;let draws=0;globalThis.Image=class{set src(v){this.onload();}};globalThis.document={createElement:()=>({getContext:()=>({translate(){},scale(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},clip(rule){assert.equal(rule,'evenodd');},drawImage(){draws++;}})})};try{for(const s of roster){const atlas=CHAPTER_TWO_SPRITES387[s.id],bytes=fs.readFileSync(new URL('../'+atlas.url.split('?')[0],import.meta.url));assert.equal(bytes[25],6);assert.equal(atlas.facing,'right');assert.equal(Object.keys(atlas.frames).length,8);assert.match(monsterVisual(s.id),/data-source-facing="right"/);for(const frame of Object.keys(atlas.frames)){const f=chapterTwoFrame383(s.id,frame);assert.ok(f.x>=0&&f.y>=0&&f.x+f.width<=256&&f.y+f.height<=256);assert.equal(chapterTwoCanvasFrame383(s.id,frame).width,256);}}}finally{globalThis.document=oldDoc;globalThis.Image=oldImage;}assert.equal(draws,56);
});
