import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as C from '../src/cart/Rules543.js';
import {parkingBonus544} from '../src/cart/Courses544.js';
import {pair545,surface545} from '../src/cart/Collisions545.js';
import * as B from '../src/bomb/Rules542.js';
import * as H from '../src/hide/Rules536.js';
import {sampleObjects545,marker545} from '../src/hide/Presentation545.js';
import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';
import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';
import {queueCart543,liveCart543} from '../online-server/src/CartCoordinator543.js';
import {queueBomb542,liveBomb542} from '../online-server/src/BombCoordinator542.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'仲間'+i,choice:{id:'m',speciesId:'slime'},owned:[{id:'m',speciesId:'slime'}]}));
function cart(round=1){const g=C.makeCart543({id:'c',members,hostId:'p0'});C.startCart543(g,0,545);g.round=round;g.phase='play';g.elapsed=0;g.roundAt=0;g.lastAt=0;return g}
function bomb(){const g=B.makeBomb542({id:'b',members,hostId:'p0'});B.startBomb542(g,0,545);g.phase='play';g.roundAt=0;g.lastAt=0;g.elapsed=0;g.board=Array(99).fill(0);g.players.forEach((p,i)=>Object.assign(p,{x:[2.5,6.5,6.5,2.5][i],y:[4.5,4.5,8.5,8.5][i]}));return g}
function roll(g){for(let n=0;n<600;n++){g.elapsed+=25;C.physics543(g)}}
function step(g,n=1,inputs=new Map()){for(let i=0;i<n;i++)B.advanceBomb542(g,g.lastAt+50,inputs)}
function room(kind){let now=0;const messages=[],sessions=new Map(members.map(m=>[m.playerId,{playerId:m.playerId,clientKey:m.playerId,connected:true,profile:{name:m.name}}])),c=new RaceCoordinator451({now:()=>now,sessions,send:(id,m)=>messages.push(m)}),call=(op,extra={})=>c.handle(sessions.get('p0'),{op,cartVersion543:5,bombVersion542:2,roster:members[0].owned,...extra});call('partyCreate462',{game:kind});const party=partyFor462(c,'p0'),saved=partyRace462(c,party);return{c,sessions,call,saved,party,messages,start(){call('partyReady462',{ready:true});call(kind==='cart'?'cart543':'bomb542',{gameId:saved.id,kind:'start'});for(let i=0;i<72;i++){now+=50;kind==='cart'?c.advanceCart543():c.advanceBomb542()}return kind==='cart'?liveCart543(c,saved):liveBomb542(c,saved)},tick(){now+=50;kind==='cart'?c.advanceCart543():c.advanceBomb542()}}}
test('cart pull angle is independent of strength and fixed after release',()=>{const g=cart(),p=g.players[0];C.input543(g,p,'pull',0,-.4,.5);g.elapsed=900;C.input543(g,p,'shoot',900,-.4,.5);assert.equal(p.power,.5);assert(p.vx<0&&p.vy>0);assert(Math.abs(Math.hypot(p.vx,p.vy)-8.25)<1e-9);assert.equal(C.input543(g,p,'pull',900,.5,.6),false);assert.equal(p.aim545,-.4)});
test('central crates block a straight shot; all four lanes have a real wall-bounce gold route',()=>{for(let lane=0;lane<4;lane++){const g=cart(3),p=g.players[lane];g.players=[p];p.lane=lane;p.x=(lane-1.5)*1.8;p.aim545=0;C.launch543(g,p,.8);roll(g);assert(p.y<10,`straight lane ${lane} blocked`);const f=cart(3),q=f.players[lane];f.players=[q];q.lane=lane;q.x=(lane-1.5)*1.8;q.aim545=(lane<2?-1:1)*(lane===0||lane===3?.12:.32);const power=lane===0||lane===3?.69:.79,preview=C.forecast544(f,q,power);C.launch543(f,q,power);roll(f);assert.equal(parkingBonus544(q),50,`lane ${lane}: ${q.y}`);assert(!f.events.some(e=>e.type==='block'));assert(Math.abs(q.x-preview.x)<1e-8&&Math.abs(q.y-preview.y)<1e-8);const xs=preview.trace.map(t=>t.x);assert(lane<2?Math.min(...xs)<-3.6:Math.max(...xs)>3.6)}});
test('oblique collision transfers momentum and generates finite spin without creating energy',()=>{const a={x:0,y:0,vx:1,vy:6,spin545:0},b={x:.65,y:.8,vx:0,vy:0,spin545:0},energy=p=>.5*(p.vx**2+p.vy**2)+.25*.58**2*p.spin545**2,before=energy(a)+energy(b),momentum={x:a.vx+b.vx,y:a.vy+b.vy};assert(pair545(a,b)>0);assert(Math.abs(a.vx+b.vx-momentum.x)<1e-8);assert(Math.abs(a.vy+b.vy-momentum.y)<1e-8);assert(energy(a)+energy(b)<=before+1e-8);assert(Math.abs(a.spin545)>0);assert(b.vx!==0&&b.vy>0);assert(Math.hypot(a.x-b.x,a.y-b.y)>=1.16)});
test('settled surface contacts do not add speed or repeated bounces',()=>{const p={x:3.82,y:12,vx:0,vy:0,spin545:0};for(let i=0;i<20;i++)surface545(p,-1,0,0);assert.equal(p.vx,0);assert.equal(p.vy,0);assert.equal(p.spin545,0)});
test('cart wire rejects malformed power and angles and accepts ordered pull updates',()=>{const r=room('cart'),g=r.start(),session=r.sessions.get('p0'),base={gameId:g.id,round:1,cartVersion543:5,seq:1,action:'pull',power:.4};for(const angle of [NaN,Infinity,-3.15,3.15,'0'])assert.equal(queueCart543(r.c,session,{...base,angle}),false);assert.equal(queueCart543(r.c,session,{...base,angle:.3,power:1.1}),false);assert(queueCart543(r.c,session,{...base,angle:.3}));assert(queueCart543(r.c,session,{...base,seq:2,angle:.3,power:.5}));r.tick();assert.equal(g.players[0].aim545,.3);assert.equal(g.players[0].pullPower547,.5);assert(!g.players[0].launched);assert.equal(g.players[0].power,null)});
test('steering and bomb action coexist; lifting or a lost input lease stops movement',()=>{const g=bomb(),p=g.players[0],input=new Map([['p0',[{action:'steer',dir:1},{action:'bomb'}]]]);step(g,1,input);assert(g.bombs.length===1);assert(p.x>2.5);step(g,3);assert(p.x>2.8);step(g,1,new Map([['p0',[{action:'steer',dir:-1}]]]));const x=p.x;step(g,4);assert.equal(p.x,x);step(g,1,new Map([['p0',[{action:'steer',dir:2}]]]));step(g,15);const pos=[p.x,p.y];step(g,10);assert.deepEqual([p.x,p.y],pos)});
test('steering cannot walk into a pillar or an already-open hole',()=>{const g=bomb(),p=g.players[0];g.board[B.index542(3.5,4.5)]=1;step(g,10,new Map([['p0',[{action:'steer',dir:1}]]]));assert.equal(p.x,2.5);g.board.fill(0);g.cracks=[{i:B.index542(3.5,4.5),at:0,until:99999}];step(g,10,new Map([['p0',[{action:'steer',dir:1}]]]));assert.equal(p.x,2.5);assert(p.alive)});
test('kick reach is usable at 1.4 cells and blocked directions cannot light the kick affordance',()=>{const g=bomb(),p=g.players[0];g.bombs=[{id:1,x:3.9,y:4.5,owner:1,planter:1,range:2,relay:0,explodeAt:2500,dx:0,dy:0,pass:[]}];assert(B.nearestBomb542(g,p));assert(B.kick542(g,p));assert.equal(g.bombs[0].owner,0);assert.equal(g.bombs[0].explodeAt,2500);g.board[B.index542(4.9,4.5)]=1;assert.equal(B.nearestBomb542(g,p),null)});
test('relay knockouts score two once; ordinary knockouts still score one',()=>{for(const relay of [0,1,3]){const g=bomb(),p=g.players[1];Object.assign(p,{x:4.5,y:4.5,hp:1});g.bombs=[{id:1,x:4.5,y:4.5,owner:0,planter:0,range:2,relay,explodeAt:50,dx:0,dy:0,pass:[]}];step(g);assert(!p.alive);assert.equal(g.players[0].score,relay?2:1);step(g,4);assert.equal(g.players[0].score,relay?2:1)}});
test('crack warning preserves floor until deadline; shield never protects from falling',()=>{const g=bomb(),p=g.players[0],i=B.index542(p.x,p.y);g.cracks=[{i,at:1400,until:3800}];p.shield=true;assert(B.floor542(g,p.x,p.y,1399));assert(!B.floor542(g,p.x,p.y,1400));assert(B.floor542(g,p.x,p.y,3800));step(g,28);assert(!p.alive);assert.equal(p.hp,0)});
test('bomb protocol rejects malformed directions and safely migrates old active matches',()=>{const r=room('bomb');r.saved.phase='play';r.saved.rules542=1;r.party.members[0].ready=true;r.c.advanceBomb542();const saved=partyRace462(r.c,r.party);assert.equal(saved.phase,'lobby');assert.equal(saved.rules542,2);assert(!r.party.members[0].ready);r.call('partyReady462',{ready:true,bombVersion542:1});assert(!r.party.members[0].ready);r.call('partyReady462',{ready:true});r.call('bomb542',{gameId:saved.id,kind:'start'});for(let i=0;i<72;i++)r.tick();const g=liveBomb542(r.c,saved),m={gameId:g.id,bombVersion542:2,seq:1,action:'steer',dir:0};for(const dir of [-2,4,1.5,NaN,'1'])assert.equal(queueBomb542(r.c,r.sessions.get('p0'),{...m,dir}),false);assert(queueBomb542(r.c,r.sessions.get('p0'),m));r.tick();assert.equal(g.players[0].steer545,0)});
test('lost visibility fades at last authorized location, never predicts through walls, and expires',()=>{const r={};sampleObjects545(r,[{id:'king',x:30,y:40,moving:true}],0);sampleObjects545(r,[{id:'king',x:30,y:40,moving:true}],140);const a=sampleObjects545(r,[],220)[0];assert(a.alpha>0&&a.alpha<1);assert.equal(a.x,30);assert.equal(a.y,40);assert(!a.moving);assert.equal(sampleObjects545(r,[],361).length,0);assert.equal(r.visible545.size,0)});
test('visibility boundary flicker reuses its smooth sample; reduced motion skips fading',()=>{const r={};sampleObjects545(r,[{id:'x',x:100,y:200}],0);sampleObjects545(r,[{id:'x',x:100,y:200}],120);sampleObjects545(r,[],180);const back=sampleObjects545(r,[{id:'x',x:120,y:200}],210)[0];assert(back.alpha>.5);assert(back.x>100&&back.x<120);assert.equal(sampleObjects545(r,[],230,true).length,0)});
test('teammate labels remain within safe canvas edges and separate co-located labels',()=>{for(const [w,h] of [[320,280],[390,470],[430,560]]){const used=[],a=marker545(-500,-500,w,h,65,used),b=marker545(-500,-500,w,h,65,used);assert(a.x-a.width/2>=0&&a.x+a.width/2<=w);assert(a.y-25>=0&&b.y<h-5);assert(Math.abs(a.y-b.y)>=29)}const occupied=[{x:160,y:184,width:80,height:85}],q=marker545(160,180,494,350,65,occupied);assert(Math.abs(q.y-184)>=57)});
test('hunter still receives no hider identity or coordinates; all hider teammates stay shared',()=>{const g=H.makeHide536({id:'h',members,hostId:'p0'});g.role='hunter';H.startHide536(g,0,545);g.phase='play';const h=H.publicHide536(g,'p0'),friend=H.publicHide536(g,'p1');for(const p of h.players.filter(p=>!p.hunter)){assert.equal(p.x,undefined);assert.equal(p.objectId,undefined)}assert(h.objects.every(o=>!o.owner&&!o.seat));for(const p of friend.players.filter(p=>!p.hunter))assert(Number.isFinite(p.x)&&Number.isFinite(p.y))});
test('canal and hide gameplay rules are unchanged by presentation repairs',()=>{for(const name of ['canal/Rules489.js','canal/Rules496.js','canal/Rules500.js','canal/Team541.js','hide/Rules536.js','hide/Heist541.js'])assert.deepEqual(readFileSync(new URL('../src/'+name,import.meta.url)),readFileSync(new URL('../../baseline544/src/'+name,import.meta.url)))});
