import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {run} from '../tools/build430/native-harness.mjs';
import {SaveService} from '../src/services/SaveService.js';
import {ROYAL_HEROES434,royalVisits434,claimRoyalGift434,beginRoyalSolo434,settleRoyalSolo434,royalSoloCheckpoint434} from '../src/core/RoyalHero434.js';
import {royalState,beginRoyalAttempt,settleRoyalAttempt} from '../src/core/RoyalChamberSystem.js';
import {memoryProgress} from '../src/core/RoyalMemory379.js';
import {royalHeroHitBounds434,pickRoyalHero434,nearestRoyalHero434} from '../src/ui/RoyalHeroHit434.js';
const ids=Object.keys(ROYAL_HEROES434);
async function fixture(){const f=await run(['ten_life','ten_time','abyss_wrath','abyss_gluttony'],['slime'],{inspect:true});const c=f.context;c.battle=null;c.save.state.player.inRun=false;c.save.state.campaign100.finalCompleted=true;delete c.save.state.campaign100.royalVisits434;delete c.save.state.activeBattle;c.save.save=()=>true;royalState(c.save.state);return f;}
function ui(c){c.audio={sfx(){}};let html='',m;const nodes=new Map(),node=k=>{if(!nodes.has(k))nodes.set(k,{focus(){}});return nodes.get(k);};m={isConnected:true,querySelector:node,setAttribute(){},classList:{add(){}},remove(){this.isConnected=false;}};c.app.insertAdjacentHTML=(_,s)=>html=s;c.topModal=()=>m;c.requestAnimationFrame=()=>{};c.showToast=()=>{};return{m,node,html:()=>html};}
test('four first conversation gifts survive real save reload and do not depend on group stages',async()=>{
 const f=await fixture(),s=f.context.save.state;for(const id of ids){const before=s.inventory.experienceItemsUltra??0;assert.equal(claimRoyalGift434(s,id).first,true);assert.equal(s.inventory.experienceItemsUltra,before+3);assert.equal(claimRoyalGift434(s,id).first,false);}
 const service=new SaveService();service.state=s;assert.ok(service.save());const reloaded=new SaveService();for(const id of ids)assert.equal(claimRoyalGift434(reloaded.state,id).first,false);assert.equal(royalVisits434(reloaded.state).attempt,undefined);assert.equal(reloaded.state.inventory.experienceItemsUltra,s.inventory.experienceItemsUltra);
});
test('locked heroes, missing party, another battle and concurrent group attempts cannot grant or start',async()=>{
 const {context:c}=await fixture(),s=c.save.state;s.campaign100.finalCompleted=false;assert.equal(claimRoyalGift434(s,ids[0]).ok,false);assert.equal(beginRoyalSolo434(s,ids[0]).ok,false);s.campaign100.finalCompleted=true;assert.equal(beginRoyalSolo434(s,'slime').ok,false);s.party.pop();assert.equal(beginRoyalSolo434(s,ids[0]).ok,false);
 const f=await fixture(),state=f.context.save.state;assert.ok(beginRoyalAttempt(state,{}, {memory:true,stage:1}));assert.equal(beginRoyalSolo434(state,ids[0]).ok,false);assert.equal(claimRoyalGift434(state,ids[0]).ok,false);
});
test('each personal opponent uses its real skills and six equipment slots at fixed level; first campaign roster is untouched',async()=>{
 const {context:c}=await fixture(),before=JSON.stringify(c.campaignHeroLedger());
 for(const id of ids){const a=beginRoyalSolo434(c.save.state,id);assert.ok(a.ok);const e=c.makeBattleEnemy({...c.campaignHeroBattleEntry(id),royalSolo434:true},0);assert.equal(e.campaignHeroId,id);assert.equal(e.level,1000);assert.equal(e.enemyGear.length,6);assert.equal(e.campaignHeroFinal,false);assert.ok(e.maxHp>0&&e.uncapturable&&e.noItemDrops);const data={specialBattleType:'royalSolo434',battleId:a.id,enemies:[e]};assert.ok(royalSoloCheckpoint434(c.save.state,data));assert.equal(royalSoloCheckpoint434(c.save.state,{...data,battleId:'stale'}),false);assert.equal(royalSoloCheckpoint434(c.save.state,{...data,enemies:[{...e,campaignHeroId:ids[(ids.indexOf(id)+1)%4]}]}),false);settleRoyalSolo434(c.save.state,{id:a.id});}
 assert.equal(JSON.stringify(c.campaignHeroLedger()),before);
});
test('win, defeat and interrupted start restore supplies and vitals; only first win gives its own signature',async()=>{
 const {context:c}=await fixture(),s=c.save.state;s.inventory.potions=7;s.player.gold=12345;s.monsters.find(m=>m.id===s.party[0]).currentHp=37;const before=JSON.stringify(s.campaign100.heroEncounters310),progress=memoryProgress(s);
 for(const id of ids){for(const [won,abandoned]of [[false,false],[false,true],[true,false],[true,false]]){const a=beginRoyalSolo434(s,id);assert.ok(a.ok);assert.equal(beginRoyalSolo434(s,id).ok,false);s.inventory.potions=0;s.player.gold=0;s.monsters.find(m=>m.id===s.party[0]).currentHp=0;const first=won&&!royalVisits434(s).victories[id],result=settleRoyalSolo434(s,{id:a.id,won,abandoned});assert.equal(result.first,first);assert.equal(Boolean(result.reward),first);assert.equal(s.inventory.potions,7);assert.equal(s.player.gold,12345);assert.equal(s.monsters.find(m=>m.id===s.party[0]).currentHp,37);assert.equal(settleRoyalSolo434(s,{id:a.id,won}).ok,false);}}
 assert.equal(s.equipment.filter(x=>x.obtainedMethod==='royalSolo434').length,4);assert.deepEqual(memoryProgress(s),progress);assert.equal(JSON.stringify(s.campaign100.heroEncounters310),before);for(const id of ids)assert.equal(claimRoyalGift434(s,id).first,true);
});
test('full inventory and reserve send the unique weapon to the vault, without selling it',async()=>{
 const {context:c}=await fixture(),s=c.save.state;s.equipment=Array.from({length:500},(_,i)=>({id:'f'+i}));s.reserveEquipment=Array.from({length:30},(_,i)=>({id:'r'+i}));const a=beginRoyalSolo434(s,ids[0]),r=settleRoyalSolo434(s,{id:a.id,won:true});assert.equal(r.reward.location,'bossVault');assert.ok(s.bossEquipmentVault.some(x=>x.id==='royal434:myth_enami:first-weapon'));
});
test('native menu displays the chosen hero; failed gift save rolls back and can retry exactly once',async()=>{
 const {context:c}=await fixture(),s=c.save.state,u=ui(c);c.game={royal:true};c.openRoyalHero434(ids[0]);assert.match(u.html(),/えなみ/);assert.match(u.html(),/個人戦に挑む/);assert.doesNotMatch(u.html(),/輪廻|転生/);const close=u.node('[data-modal-primary]').onclick,before=s.inventory.experienceItemsUltra??0;c.save.save=()=>false;u.node('[data-royal-talk434]').onclick();u.node('[data-modal-primary]').onclick();assert.equal(c.save.state.inventory.experienceItemsUltra??0,before);assert.equal(royalVisits434(c.save.state).gifts[ids[0]],undefined);c.save.save=()=>true;u.node('[data-modal-primary]').onclick();u.node('[data-modal-primary]').onclick();u.node('[data-modal-primary]').onclick();assert.equal(c.save.state.inventory.experienceItemsUltra,before+3);close();assert.equal(c.game.paused,false);
});
test('native start passes the selected single hero, saved attempt ID and return destination; double click cannot start twice',async()=>{
 for(const id of ids){const {context:c}=await fixture(),u=ui(c);let starts=[];c.startSpecialBattle=(entries,options)=>starts.push({entries,options});c.openRoyalHero434(id);u.node('[data-royal-solo434]').onclick();u.node('[data-royal-solo434]').onclick();assert.equal(starts.length,1);assert.equal(starts[0].entries.length,1);assert.equal(starts[0].entries[0].campaignHeroId,id);assert.equal(starts[0].options.type,'royalSolo434');assert.equal(starts[0].options.battleId,royalVisits434(c.save.state).attempt.id);assert.equal(starts[0].options.returnScreen,'campaignFinalFloor');}
});
test('native terminal dispatch uses personal settlement, supports retry on save failure, then shows contribution before reward',async()=>{
 const {context:c,b}=await fixture(),u=ui(c);const a=beginRoyalSolo434(c.save.state,ids[0]);Object.assign(b,{specialBattle:true,specialBattleType:'royalSolo434',battleId:a.id,priorVitals:a.vitals});c.battle=b;const order=[];c.openBattleContributionReport=(snapshot,next)=>{order.push('contribution');next();};c.app.insertAdjacentHTML=()=>order.push('result');c.render=()=>{};c.save.save=()=>false;c.finishSpecialBattle(true);assert.ok(royalVisits434(c.save.state).attempt);assert.equal(royalVisits434(c.save.state).victories[ids[0]],undefined);c.save.save=()=>true;order.length=0;u.node('[data-modal-primary]').onclick();assert.equal(c.battle,null);assert.deepEqual(order,['contribution','result']);assert.equal(royalVisits434(c.save.state).victories[ids[0]],true);
});
test('group rematches remain available from all four heroes; throne only replays the recorded ending',async()=>{
 for(const id of ids){const {context:c}=await fixture(),u=ui(c);let count=0;c.openRoyalMemory379=()=>count++;c.openRoyalHero434(id);u.node('[data-royal-party434]').onclick();assert.equal(count,1);}
 const {context:c}=await fixture();const l=c.campaignHeroLedger();l.finalArena.lastEnding='narrow';let scenes=[];c.showCampaignStoryReplaySequence=x=>scenes=x;c.openRoyalMemory379=()=>assert.fail('throne started group rematch');c.openRoyalThrone360();assert.equal(scenes[0].id,'ending-narrow');
 assert.ok(beginRoyalAttempt(c.save.state,l,{memory:true,stage:1}));settleRoyalAttempt(c.save.state,{won:true,resultId:'still-group'});assert.equal(memoryProgress(c.save.state).unlocked,2);assert.deepEqual(royalVisits434(c.save.state).victories,{});
});
test('tap overlap selects the nearest hero, while walking contact preserves identity at all four positions',()=>{
 for(const z of [.2,.4,1,2]){const camera={z,world:(x,y)=>({x:x*z,y:y*z})},heroes=ids.map((id,i)=>({id,x:7+i*2,y:9})),targets=heroes.map(hero=>({...royalHeroHitBounds434({camera,TILE:88,actor:{position:hero},nameBounds:{left:(hero.x+.5)*88*z-20,right:(hero.x+.5)*88*z+20,top:880*z,bottom:880*z+15},padding:6}),hero}));for(const hero of heroes){const x=(hero.x+.5)*88*z;assert.equal(pickRoyalHero434(targets,{x,y:hero.y*88*z-20*z}).id,hero.id);assert.equal(pickRoyalHero434(targets,{x,y:880*z+5}).id,hero.id);assert.equal(nearestRoyalHero434(heroes,{x:hero.x+.2,y:9.2}).id,hero.id);}assert.equal(pickRoyalHero434(targets,{x:-100,y:-100}),null);}
});
test('434 boot maps updated modules and retains 433 mother CSS and frozen offline raid runtime',()=>{
 const html=fs.readFileSync('index.html','utf8'),map=JSON.parse(html.match(/<script type="importmap">([\s\S]*?)<\/script>/)[1]).imports;for(const path of ['src/main.js','src/core/RoyalHero434.js','src/ui/RoyalHeroHit434.js','src/ui/RoyalChamberField.js','src/ui/screens/CampaignFinalFloorScreen.js'])assert.ok(Object.entries(map).filter(([k])=>k.split('?')[0]==='./'+path).every(([,v])=>v.endsWith(path==='src/main.js'?'3.1.116-build437':'3.1.114-build435')));assert.match(html,/build433-mother.css/);assert.match(html,/world-raid-offline437-sw/);assert.ok(!Object.keys(map).some(k=>k.includes('/runtime430/')));
});
test('native checkpoint resumes the same single opponent and attempt after a real save reload',async()=>{
 const f=await fixture(),c=f.context,s=c.save.state,a=beginRoyalSolo434(s,ids[1]),enemy=c.makeBattleEnemy({...c.campaignHeroBattleEntry(ids[1]),royalSolo434:true},0);Object.assign(f.b,{specialBattle:true,specialBattleType:'royalSolo434',battleId:a.id,priorVitals:a.vitals,enemies:[enemy],enemy});c.battle=f.b;enemy.hp=1234;f.nativeSave();assert.ok(royalSoloCheckpoint434(s,s.activeBattle));const store=new SaveService();store.state=s;assert.ok(store.save());c.save.state=new SaveService().state;c.battle=null;assert.equal(f.nativeResume(),true);assert.equal(c.battle.battleId,a.id);assert.equal(c.battle.enemies.length,1);assert.equal(c.battle.enemies[0].hp,1234);assert.equal(c.screen,'campaignFinalFloor');
});
test('stale personal checkpoints cannot resume or pay rewards, and retreat restores the original supplies',async()=>{
 const f=await fixture(),c=f.context,s=c.save.state;s.inventory.potions=9;const a=beginRoyalSolo434(s,ids[2]);s.inventory.potions=0;s.activeBattle={specialBattleType:'royalSolo434',battleId:'stale',enemies:[{campaignHeroId:ids[2]}]};assert.equal(f.nativeResume(),false);assert.equal(s.inventory.potions,9);assert.equal(s.activeBattle,undefined);assert.equal(royalVisits434(s).victories[ids[2]],undefined);
 const b=beginRoyalSolo434(s,ids[2]);Object.assign(f.b,{specialBattle:true,specialBattleType:'royalSolo434',battleId:b.id,priorVitals:b.vitals});c.battle=f.b;s.inventory.potions=0;ui(c);c.render=()=>{};c.retreatSpecialBattle();assert.equal(c.battle,null);assert.equal(s.inventory.potions,9);assert.equal(royalVisits434(s).victories[ids[2]],undefined);
});
