import test from 'node:test';import assert from 'node:assert/strict';
import {game,gear,resolve,commit,select} from '../tools/build562/fixture.mjs';
import {advanceLuck511,LUCK511} from '../src/luck/Rules511.js';
import {factors575,rewardProgress575} from '../src/luck/Progress575.js';
const next=(g,e)=>{commit(g,e);advanceLuck511(g,g.nextAt);select(g,['echo','echo','echo','echo']);};
test('single leader multiplies existing gear; ties and newly equipped flags do not',()=>{const g=game({distance:[5000,3000,2000,0]});g.players[0].loadout=gear('regalia',2);assert.equal(resolve(g).rows[0].calculation.factors.regalia,16);g.players[1].distance=5000;assert.equal(resolve(g).rows[0].calculation.factors.regalia,1);g.players[1].distance=3000;g.players[0].loadout=gear('regalia',1,g.round);assert.equal(resolve(g).rows[0].calculation.factors.regalia,1)});
test('podium medals are awarded after attacks, start next round and remain in second half',()=>{const g=game({round:4,items:['podium','echo','echo','echo'],distance:[5000,3000,2000,0]});let e=resolve(g);assert.equal(e.rows[0].calculation.factors.podium,1);assert.equal(e.rows[0].loadout[0].medals575,1);next(g,e);e=resolve(g);assert.equal(e.rows[0].calculation.factors.podium,2);assert.equal(e.rows[0].loadout[0].medals575,1)});
test('early distance awakening can be earned by this run, applies later and survives retreat',()=>{const g=game({round:3,items:['rocket','echo','echo','echo'],distance:[9600,1000,0,0]});g.players[0].loadout=gear('frontier');let e=resolve(g);assert.equal(e.rows[0].calculation.factors.frontier,1);assert(e.rows[0].loadout[0].awake575);next(g,e);g.players[0].distance=0;e=resolve(g);assert.equal(e.rows[0].calculation.factors.frontier,8)});
test('late distance and podium do not gain rewards, in both 8 and 16 rounds',()=>{for(const rounds of [8,16]){const g=game({round:rounds/2+1,rounds,distance:[100000,0,0,0]});g.players[0].loadout=[...gear('frontier'),...gear('podium')];const r=resolve(g).rows[0];assert(!r.loadout[0].awake575);assert(!r.loadout[1].medals575)}});
test('usurper rewards one actual rank takeover after attacks and never pays twice',()=>{const g=game({round:3,items:['nova','echo','echo','echo'],distance:[1000,3000,2000,0]});g.players[0].loadout=gear('usurper',2);let e=resolve(g);assert.equal(e.rows[0].beforeRank,3);assert.equal(e.rows[0].afterRank,1);assert.equal(e.rows[0].suns,6);assert.equal(e.rows[0].calculation.spent.suns,0);next(g,e);g.players[0].distance=1000;select(g,['nova','echo','echo','echo']);e=resolve(g);assert.equal(e.rows[0].calculation.factors.solar,729);assert.equal(e.rows[0].suns,0)});
test('tied first cannot claim usurper, top-two ties can earn medals',()=>{const rows=[0,1].map(seat=>({seat,beforeRank:3,afterRank:1,to:1000,suns:0,loadout:[...gear('usurper'),...gear('podium')]}));rewardProgress575(rows,2,8);for(const r of rows){assert.equal(r.suns,0);assert.equal(r.loadout[1].medals575,1)}});
test('blocked flight and final position decide reward; unachieved projected distance is insufficient',()=>{const g=game({round:3,items:['mega','lightning','echo','echo'],distance:[9500,12000,15000,0]});g.players[0].loadout=[...gear('frontier'),...gear('usurper')];const r=resolve(g).rows[0];assert(r.stopped);assert(!r.loadout[0].awake575);assert.equal(r.suns,0)});
test('doubling preserves per-copy achievement history and does not reopen claimed solar awards',()=>{const g=game({round:3,items:['resonance','echo','echo','echo'],distance:[20000,0,0,0]});g.players[0].loadout=[{id:'podium',round:1,medals575:2},{id:'frontier',round:1,awake575:true},{id:'usurper',round:1,claimed575:true}];const r=resolve(g).rows[0];assert.equal(r.calculation.factors.podium,16);assert.equal(r.calculation.factors.frontier,64);assert.equal(r.suns,0);assert.equal(r.loadout[0].medals575,3);const saved=JSON.parse(JSON.stringify(r.loadout));assert.equal(factors575(saved,4,false).podium,64n)});

test('achievement records and notices survive JSON commit and public state',async()=>{const {publicLuck511}=await import('../src/luck/Rules511.js');const {rewardLabel575}=await import('../src/luck/Presentation571.js');const g=game({round:3,items:['nova','echo','echo','echo'],distance:[1000,3000,2000,0]});g.players[0].loadout=['podium','frontier','usurper'].flatMap(id=>gear(id));const e=resolve(g);assert.deepEqual(e.rows[0].rewards575,{medals:1,awaken:1,suns:3});assert.match(rewardLabel575(e.rows[0]),/星図1個が覚醒/);commit(g,e);const state=publicLuck511(JSON.parse(JSON.stringify(g)),'p0');assert(state.players[0].loadout.find(x=>x.id==='frontier').awake575);assert.equal(state.itemRules575,1);assert.equal(state.players[0].suns,3)});
test('new modules, atlas, rules and offline cache are versioned together',async()=>{const {readFile}=await import('node:fs/promises'),read=p=>readFile(new URL('../'+p,import.meta.url),'utf8'),html=await read('index.html'),imports=JSON.parse(html.match(/<script type="importmap">([\s\S]*?)<\/script>/)[1]).imports,assets=JSON.parse(await read('world-raid-offline575-assets.json'));for(const p of ['src/luck/Items575.js','src/luck/Progress575.js','src/luck/Items511.js','src/luck/Rules511.js','src/luck/Buffs571.js','src/luck/Presentation571.js','src/luck/View511.js','src/race/RaceClient451.js','src/party/PartyView462.js']){const target='./'+p+'?v=3.1.254-build575';assert.equal(imports['./'+p],target);assert(assets.includes(target))}assert(assets.includes('./assets/luck575/items.webp'));assert(html.includes('build571-luck.css?v=3.1.254-build575'));assert(html.includes('register("./world-raid-offline575-sw.js"'))});
