import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks,createRequire} from 'node:module';
import {existsSync,mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {makeLuck508,startLuck508,chooseLuck508,advanceLuck508,publicLuck508,drawPlan508,resolveRound508,aiPick508,ITEMS508,LUCK508} from '../src/luck/Rules508.js';
import {makeLuck507,startLuck507,drawPlan507} from '../src/luck/Rules507.js';
import {raceFrame508,broadcastFrame508,paintKey508} from '../src/luck/Presentation508.js';
const fixtures={
 [new URL('../src/ui/MonsterVisual.js',import.meta.url).href]:`export const monsterVisual=()=>'<i class="test-sprite"></i>';export const setMonsterVisualFrame=()=>{};`,
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,c,next){const url=spec.startsWith('.')?new URL(spec,c.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,c)},load(url,c,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,c)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');
const {luckView508,luckAfter508,luckBefore508,luckTick508,paintLuck508,requestLuck508,luckReceive508}=await import('../src/luck/View508.js');
const {raceDomSignature452}=await import('../src/race/RacePresentation452.js');
const {gorillaView502}=await import('../src/gorilla/View502.js');
hook.deregister();
const plan=()=>drawPlan508(n=>n-1);
function game(n=4){const g=makeLuck508({id:'luck-test',code:'ABC123',partyId:'party',hostId:'p0',members:Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'P'+i,color499:['orange','pink','green','blue'][i],owned:[{id:'m'+i,speciesId:'wolf'}],choice:{id:'m'+i,speciesId:'wolf'}}))});startLuck508(g,1000,plan());return g}
const begin=g=>{advanceLuck508(g,g.nextAt);return g.phaseAt};
function chooseAll(g,kind,order=[0,1,2,3]){for(const seat of order){const p=g.players[seat];if(!p.ai)chooseLuck508(g,p.playerId,kind,0,g.round,g.phaseAt+10)}advanceLuck508(g,g.nextAt);return g}
function readyItems(ids=['dash','rocket','shield','engine'],dist=[0,0,0,0]){const g=game();g.players.forEach((p,i)=>p.distance=dist[i]);g.plan508[0].seats.forEach((d,i)=>d.boxes[0]=[ids[i],...ITEMS508.filter(x=>x.id!==ids[i]).slice(0,3).map(x=>x.id)]);begin(g);chooseAll(g,'chest');chooseAll(g,'hand');assert.equal(g.phase,'reveal');return g}
function context(g,self='p0'){return{state:{luck:publicLuck508(g,self),party:{id:'party',hostId:'p0',members:g.members.map(m=>({...m,connected:true})),game:'luck',phase:g.phase},available:true,serverNow:g.phaseAt,partyResultActions490:1},transport:{selfId:self},offset:g.phaseAt-Date.now(),sgMonster463:()=>'<span class="sg-monster"><i></i></span>',sgSpeciesName463:id=>id,ready:()=>true,connected:()=>true,roster:()=>[{id:'m0',speciesId:'wolf'}],bank:()=>null,save:{state:{player:{gold:1000,crystals:0},settings:{audioEnabled:false},monsters:[]}},root:{querySelector:()=>null},draft:{code:'ABC123'},render(){},lkUI508:{gameId:g.id,artReady:true,sound:false}}}
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,luckVersion507:1,luckVersion508:1,gorillaVersion502:1,gorillaRules503:1,gorillaRules504:1,gorillaRules505:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function start(x,n=x.sessions.size){assert.deepEqual(x.send(0,'partyCreate462',{game:'luck',roster:[{id:'m0',speciesId:'wolf'}]}),[]);const party=Object.values(x.c.data.parties462)[0],get=()=>x.c.data.luckRooms507[party.code];for(let i=1;i<n;i++){assert.deepEqual(x.send(i,'partyJoin462',{code:party.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);assert.deepEqual(x.send(i,'luck508',{gameId:get().id,kind:'select',monsterId:'m'+i}),[])}for(let i=0;i<n;i++)assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[]);assert.deepEqual(x.send(0,'luck508',{gameId:get().id,kind:'start'}),[]);return{party,get}}

test('each of 128 chests holds four distinct random items; all random bounds are valid',()=>{let seed=171,calls=0;const p=drawPlan508(n=>{assert.ok(n>0);calls++;seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n});assert.equal(p.length,8);assert.equal(p.flatMap(r=>r.seats.flatMap(s=>s.boxes)).length,128);assert.ok(p.every(r=>new Set(r.order).size===4));assert.ok(p.every(r=>r.seats.every(s=>s.boxes.every(b=>new Set(b).size===4))));assert.ok(calls>1900);assert.equal(new Set(p.flatMap(r=>r.seats.flatMap(s=>s.boxes.flat()))).size,16)});
test('malformed entropy cannot partially start; one to four people preserve monster/color and fill AI seats',()=>{for(let n=1;n<=4;n++){const g=game(n);assert.equal(g.players.length,4);for(let i=0;i<n;i++){assert.deepEqual(g.players[i].choice,g.members[i].choice);assert.equal(g.players[i].color499,g.members[i].color499)}}const g=game();g.phase='lobby';const bad=plan();bad[1].seats[2].boxes[0]=['dash','dash','dash','dash'];const before=structuredClone(g);assert.throws(()=>startLuck508(g,1000,bad));assert.deepEqual(g,before)});
test('box and hand choices are separately private; no future random outcomes leak to another player or spectator',()=>{const g=game();begin(g);chooseLuck508(g,'p0','chest',0,1,g.phaseAt+10);assert.equal(publicLuck508(g,'p1').ownBox,null);assert.equal(publicLuck508(g,'p0').ownBox,0);assert.equal(publicLuck508(g,'p0').hand,null);chooseAll(g,'chest');chooseLuck508(g,'p0','hand',2,1,g.phaseAt+10);const v=publicLuck508(g,'p1');assert.equal(v.ownPick,null);assert.equal(v.event,null);assert.equal(v.hand.length,4);assert.equal(publicLuck508(g,'watch').hand,null);assert.doesNotMatch(JSON.stringify(v),/plan508|items508|boxes508|autoItem|autoBox|waitItem|"coin"|"order"/);const before=publicLuck508(g,'p1');g.plan508[7].seats[0].coin=0;g.plan508[0].seats[0].boxes[1].reverse();assert.deepEqual(publicLuck508(g,'p1'),before);v.hand[0]='fake';assert.notEqual(publicLuck508(g,'p1').hand[0],'fake')});
test('duplicate choice bursts cannot reroll or change choices; stale phase, range, seat and deadline reject',()=>{const g=game();begin(g);const t=g.phaseAt;for(const args of[['p0','hand',0,1,t],['p0','chest',4,1,t],['p0','chest',-1,1,t],['p0','chest',.5,1,t],['p0','chest',0,2,t],['p0','chest',0,1,t-1],['p0','chest',0,1,g.deadline],['p1','chest',0,1,NaN],['watch','chest',0,1,t]])assert.throws(()=>chooseLuck508(g,...args));assert.equal(chooseLuck508(g,'p0','chest',1,1,t+2),true);const copy=structuredClone(g);for(let i=0;i<100;i++)assert.equal(chooseLuck508(g,'p0','chest',1,1,t+3),false);assert.throws(()=>chooseLuck508(g,'p0','chest',2,1,t+3));assert.deepEqual(g,copy)});
test('simultaneous reveal and attack order are independent of client input order',()=>{const a=game(),b=game();begin(a);begin(b);chooseAll(a,'chest');chooseAll(b,'chest',[3,1,0,2]);chooseAll(a,'hand');chooseAll(b,'hand',[2,0,3,1]);assert.deepEqual(a.event,b.event);assert.equal(a.history.length,1)});
test('AI decisions ignore opponents hidden boxes, selected items and future entropy',()=>{const g=game(1);begin(g);advanceLuck508(g,g.deadline);assert.equal(g.phase,'hand');const p=g.players[2],before=aiPick508(g,p);g.items508=[3,2,null,1];g.plan508[0].seats[0].boxes.forEach(b=>b.reverse());g.plan508[7].seats.forEach(s=>s.coin=0);assert.equal(aiPick508(g,p),before)});
test('shell hits the round-start leader, deals exactly -100m, and shows authenticated source and target',()=>{const g=readyItems(['shell','dash','dash','dash'],[0,700,200,100]);const a=g.event.attacks[0];assert.equal(a.source,0);assert.equal(a.targets[0].target,1);assert.equal(a.targets[0].amount,100);assert.equal(g.event.rows[1].to,820)});
test('lightning halves only this round forward movement and never the accumulated distance',()=>{const g=readyItems(['lightning','rocket','dash','shield'],[1000,1000,1000,1000]);assert.equal(g.event.rows[1].to,1250);assert.equal(g.event.rows[2].to,1110);assert.equal(g.event.rows[3].to,1160);assert.equal(g.event.attacks[0].targets.find(x=>x.target===3).outcome,'blocked')});
test('external hit fizzles +1000m turbo, while unhit turbo advances +1000m',()=>{const a=readyItems(['shell','turbo','dash','dash'],[0,500,0,0]),b=readyItems(['dash','turbo','dash','dash']);assert.equal(a.event.rows[1].gain,0);assert.equal(a.event.rows[1].to,400);assert.equal(b.event.rows[1].delta,1000)});
test('shield blocks every external attack, including position swap, and preserves base movement',()=>{const g=readyItems(['shell','lightning','swap','shield'],[0,100,200,1000]);assert.equal(g.event.rows[3].to,1160);assert.ok(g.event.attacks.every(a=>a.targets.filter(h=>h.target===3).every(h=>h.outcome==='blocked')))});
test('mirror returns first attack, accepts later attacks, never recursively bounces',()=>{const g=readyItems(['shell','lightning','mirror','dash'],[0,100,1000,0]);const a=g.event.attacks;assert.equal(a[0].targets[0].outcome,'reflected');assert.equal(a[0].targets[0].returned.target,0);assert.equal(a[0].targets[0].returned.source,2);assert.equal(a[1].targets.find(x=>x.target===2).outcome,'hit');assert.equal(g.event.rows[0].knockback,100)});
test('spring jumps banana/pit traps but remains vulnerable to lightning',()=>{const g=readyItems(['banana','pit','spring','lightning'],[100,300,200,0]);const hits=g.event.attacks.flatMap(a=>a.targets).filter(h=>h.target===2);assert.deepEqual(hits.map(x=>x.outcome),['blocked','blocked','hit']);assert.equal(g.event.rows[2].gain,175)});
test('engines stack from the following round; charge doubles one round, including engine, then expires',()=>{const g=readyItems(['engine','battery','dash','dash']);advanceLuck508(g,g.nextAt);advanceLuck508(g,g.nextAt);assert.equal(g.players[0].engines,1);assert.equal(g.players[1].charged,true);advanceLuck508(g,g.nextAt);g.plan508[1].seats.forEach(s=>s.boxes[0]=['engine','dash','shield','rocket']);chooseAll(g,'chest');chooseAll(g,'hand');assert.equal(g.event.rows[0].gain,160);assert.equal(g.event.rows[0].engines,2);assert.equal(g.event.rows[1].gain,120);assert.equal(g.event.rows[1].charged,false)});
test('magnet steals bounded movement and swap exchanges starting positions before movement',()=>{const a=readyItems(['magnet','rocket','dash','dash'],[0,1000,0,0]);assert.equal(a.event.rows[0].gain,370);assert.equal(a.event.rows[1].gain,250);const b=readyItems(['swap','rocket','dash','dash'],[0,1000,0,0]);assert.equal(b.event.rows[0].to,1080);assert.equal(b.event.rows[1].to,500)});
test('gamble has two sealed outcomes; comet catchup is bounded; distance never becomes negative',()=>{const g=readyItems(['dice','dice','comet','dash'],[100,100,0,10000]);g.plan508[0].seats[0].coin=0;g.plan508[0].seats[1].coin=1;const e=resolveRound508(g,g.phaseAt);assert.equal(e.rows[0].to,0);assert.equal(e.rows[1].delta,1400);assert.equal(e.rows[2].delta,1250)});
test('no target is a visible miss, not an implicit attack on self',()=>{const g=readyItems(['shell','banana','pit','dash'],[100,100,0,0]);assert.equal(g.event.attacks[0].targets[0].target,1);assert.equal(g.event.attacks[1].targets.length,0);assert.equal(g.event.attacks[2].targets.length,0)});
test('all 256 item pairs resolve with finite, nonnegative distances and correct recipient ids',()=>{for(const a of ITEMS508)for(const b of ITEMS508){const g=readyItems([a.id,b.id,'mirror','shield'],[300,600,900,0]);assert.ok(g.event.rows.every(r=>Number.isFinite(r.to)&&r.to>=0));for(const h of g.event.attacks.flatMap(x=>x.targets)){assert.notEqual(h.source,h.target);assert.ok(h.source>=0&&h.target<4)}}});
test('500 complete random games finish with eight rounds, ties supported, JSON restart exactly deterministic',()=>{let seed=19;const random=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n};for(let i=0;i<500;i++){const a=game(1+i%4);a.plan508=drawPlan508(random);const b=structuredClone(a);advanceLuck508(a,1e7);while(b.phase!=='result')advanceLuck508(b,b.nextAt);assert.deepEqual(a,b);assert.equal(a.history.length,8);assert.ok(a.resultAt-a.createdAt<560000);assert.ok(a.players.every(p=>p.distance>=0&&p.engines<=8))}const g=game();g.plan508.forEach(r=>r.seats.forEach(s=>s.autoItem=0));advanceLuck508(g,1e7);assert.ok(g.results.every(x=>x.rank===1))});
test('broadcast timing and target outcomes match for every viewer and survive reconnect halfway through',()=>{const g=readyItems(['lightning','shell','mirror','shield'],[0,1000,500,100]);advanceLuck508(g,g.nextAt);assert.equal(g.phase,'broadcast');for(let ms=0;ms<g.event.castMs;ms+=100){const frames=g.players.map(p=>broadcastFrame508(publicLuck508(g,p.playerId),g.phaseAt+ms));frames.forEach(f=>assert.deepEqual(f,frames[0]));assert.deepEqual(broadcastFrame508(JSON.parse(JSON.stringify(g)),g.phaseAt+ms),frames[0])}const end=g.nextAt;advanceLuck508(g,end);assert.equal(g.phase,'run');assert.equal(g.phaseAt,end)});
test('run camera follows self while ground traverses real distance; minimap retains distant rivals',()=>{const g=readyItems(['turbo','dash','dash','dash'],[0,2000,300,800]);advanceLuck508(g,g.nextAt);const a=raceFrame508(g,g.phaseAt,'p0'),b=raceFrame508(g,g.phaseAt+LUCK508.runMs,'p0');assert.equal(b.camera-a.camera,1000);assert.ok(Math.abs(b.rows[0].x-a.rows[0].x)<1e-9);assert.ok(b.rows.some(r=>r.offscreen==='right'));assert.ok(b.rows.every(r=>r.mini>=4&&r.mini<=96));for(let ms=0;ms<4800;ms+=32){const f=raceFrame508(g,g.phaseAt+ms,'p0');assert.ok(f.rows.every(r=>Number.isFinite(r.x)&&r.x>=7&&r.x<=93))}const r=raceFrame508(g,g.phaseAt+100,'p0',true);assert.ok(r.rows.every((x,i)=>x.y===0&&x.angle===0&&x.distance===g.event.rows[i].to))});
test('four production clients see only their own hand, then the identical attack broadcast',()=>{const x=setup(),a=start(x);assert.equal(a.get().rules508,1);x.time(a.get().nextAt);x.c.advance();for(let i=0;i<4;i++)assert.deepEqual(x.send(i,'luck508',{gameId:a.get().id,kind:'chest',index:i,round:1}),[]);x.time(a.get().nextAt);x.c.advance();assert.equal(a.get().phase,'hand');for(let i=0;i<4;i++){const v=x.c.view(x.sessions.get('p'+i)).luck;assert.deepEqual(v.hand,a.get().plan508[0].seats[i].boxes[i]);assert.deepEqual(x.send(i,'luck508',{gameId:a.get().id,kind:'hand',index:i,round:1}),[])}x.time(a.get().nextAt);x.c.advance();for(let i=1;i<4;i++)assert.deepEqual(x.c.view(x.sessions.get('p0')).luck,x.c.view(x.sessions.get('p'+i)).luck);assert.equal(x.c.view(x.sessions.get('p0')).room,null)});
test('server restart persists private hand and selected item; duplicate replay is harmless',()=>{const dir=mkdtempSync(join(tmpdir(),'luck508-'));try{const file=join(dir,'race.json'),x=setup(2,file),a=start(x);x.time(a.get().nextAt);x.c.advance();x.time(a.get().deadline);x.c.advance();assert.equal(a.get().phase,'hand');assert.deepEqual(x.send(0,'luck508',{gameId:a.get().id,kind:'hand',index:2,round:1}),[]);const y=setup(2,file);y.time(x.now());assert.deepEqual(y.c.data.luckRooms507[a.party.code],a.get());assert.deepEqual(y.send(0,'luck508',{gameId:a.get().id,kind:'hand',index:2,round:1}),[]);x.time(1e7);y.time(1e7);x.c.advance();y.c.advance();assert.deepEqual(y.c.data.luckRooms507[a.party.code],a.get());assert.equal(a.get().phase,'result')}finally{rmSync(dir,{recursive:true,force:true})}});
test('old clients, forged player ids, changing game/color, and nonhost start are rejected',()=>{const x=setup(2);x.send(0,'partyCreate462',{game:'luck',roster:[{id:'m0',speciesId:'wolf'}]});const p=Object.values(x.c.data.parties462)[0],g=x.c.data.luckRooms507[p.code];assert.equal(x.send(0,'partyReady462',{ready:true,luckVersion508:0}).length,1);assert.equal(x.send(0,'luck508',{kind:'start',gameId:g.id,luckVersion508:0}).length,1);x.send(1,'partyJoin462',{code:p.code,roster:[{id:'m1',speciesId:'slime'}]});x.send(1,'luck508',{kind:'select',gameId:g.id,monsterId:'m1'});for(let i=0;i<2;i++)x.send(i,'partyReady462',{ready:true});assert.equal(x.send(1,'luck508',{kind:'start',gameId:g.id}).length,1);assert.deepEqual(x.send(0,'luck508',{kind:'start',gameId:g.id}),[]);x.time(x.c.data.luckRooms507[p.code].nextAt);x.c.advance();assert.deepEqual(x.send(0,'luck508',{kind:'chest',gameId:g.id,round:1,index:2,playerId:'p1'}),[]);assert.equal(x.c.data.luckRooms507[p.code].boxes508[0],2);assert.equal(x.c.data.luckRooms507[p.code].boxes508[1],null);assert.equal(x.send(0,'partyGame462',{game:'gorilla'}).length,1);assert.equal(x.send(0,'partyMemberColor500',{partyId:p.id,playerId:'p1',color499:'green',seatToken485:x.c.data.parties462[p.code].members[1].seatToken485}).length,1)});
test('legacy match saved by Build507 completes after upgrade without rule changes',()=>{const x=setup(1),a=start(x);const old=makeLuck507({...a.get(),partyId:a.party.id,members:a.get().members});startLuck507(old,x.now(),drawPlan507(n=>n-1));x.c.data.luckRooms507[a.party.code]=old;x.time(old.nextAt);x.c.advance();assert.equal(old.phase,'choose');assert.deepEqual(x.send(0,'luck507',{kind:'choose',gameId:old.id,round:1,box:2}),[]);x.time(1e7);x.c.advance();assert.equal(old.phase,'result');assert.equal(old.rules508,undefined);assert.equal(x.c.view(x.sessions.get('p0')).luck.rules507,1)});
test('spectator join, reconnect next round, and result replay all preserve party membership',()=>{const x=setup(2),a=start(x,1);assert.deepEqual(x.send(1,'partyJoin462',{code:a.party.code,roster:[{id:'m1',speciesId:'slime'}]}),[]);assert.equal(x.c.view(x.sessions.get('p1')).luck.hand,null);assert.equal(x.send(1,'luck508',{kind:'chest',gameId:a.get().id,round:1,index:0}).length,1);x.sessions.get('p0').connected=false;x.time(a.get().nextAt);x.c.advance();x.time(a.get().deadline);x.c.advance();x.time(a.get().deadline);x.c.advance();assert.equal(a.get().event.rows[0].automatic,true);while(a.get().phase!=='chest'){x.time(a.get().nextAt);x.c.advance()}x.sessions.get('p0').connected=true;assert.deepEqual(x.send(0,'luck508',{kind:'chest',gameId:a.get().id,round:2,index:0}),[]);x.time(1e7);x.c.advance();const old=a.get().id;assert.deepEqual(x.send(Number(x.c.data.parties462[a.party.code].hostId.slice(1)),'partyResult490',{partyId:a.party.id,gameId:old,kind:'again'}),[]);assert.equal(a.get().phase,'lobby');assert.equal(a.get().members.length,2);assert.equal(a.get().rules508,1);assert.notEqual(a.get().id,old)});
test('failed persistence rolls back item choice rather than accepting unrecorded action',()=>{const dir=mkdtempSync(join(tmpdir(),'luck508-write-'));try{const x=setup(1),a=start(x);x.time(a.get().nextAt);x.c.advance();x.time(a.get().deadline);x.c.advance();const before=structuredClone(a.get()),file=join(dir,'file');writeFileSync(file,'not a directory');x.c.stateFile=join(file,'state.json');assert.equal(x.send(0,'luck508',{gameId:a.get().id,kind:'hand',index:2,round:1}).length,1);assert.deepEqual(a.get(),before);assert.equal(x.c.healthy(),false)}finally{rmSync(dir,{recursive:true,force:true})}});
test('new view has four actual chest buttons and four labeled item buttons; no hand values in another seat markup',()=>{const g=game(),c=context(g);const h=luckView508(c);assert.equal((h.match(/data-chest508="/g)??[]).length,4);assert.equal((h.match(/data-hand-pick508="/g)??[]).length,4);assert.equal((h.match(/data-cast-actor508="/g)??[]).length,4);assert.doesNotMatch(h,/undefined|NaN/)});
test('updates preserve play DOM signature through all phases and rebuild on result',()=>{const g=game(),c=context(g),before=raceDomSignature452(c);advanceLuck508(g,g.nextAt);c.state.luck=publicLuck508(g,'p0');c.state.party.phase=g.phase;assert.equal(raceDomSignature452(c),before);advanceLuck508(g,1e7);c.state.luck=publicLuck508(g,'p0');assert.notEqual(raceDomSignature452(c),before)});
test('paint cadence is bounded and stops when a timed animation has finished',()=>{const g=game();begin(g);const keys=new Set();for(let ms=0;ms<10000;ms+=33)keys.add(paintKey508(g,g.phaseAt+ms,true,null,false));assert.equal(keys.size,10);g.phase='run';assert.equal(paintKey508(g,g.phaseAt+5000,true,null,false),paintKey508(g,g.phaseAt+50000,true,null,false))});
function dom(g=game()){
 let mutations=0,serial=0;const queue=new Map(),listeners=new Map(),saved={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};
 function el(){const values={},attrs={},children=new Map();return{clientHeight:350,clientWidth:393,dataset:new Proxy({},{set(t,k,v){mutations++;t[k]=v;return true}}),style:new Proxy({setProperty(k,v){this[k]=v},getPropertyValue(k){return this[k]??''},getPropertyPriority(){return''}},{set(t,k,v){mutations++;t[k]=v;return true}}),classList:{contains:s=>s==='lk-play508'},getAttribute:k=>attrs[k]??null,setAttribute(k,v){mutations++;attrs[k]=v},addEventListener(){},removeEventListener(){},contains:()=>false,querySelector(q){if(!children.has(q))children.set(q,el());return children.get(q)},querySelectorAll:()=>[],get textContent(){return values.textContent},set textContent(v){mutations++;values.textContent=v},get disabled(){return values.disabled},set disabled(v){mutations++;values.disabled=v},get hidden(){return values.hidden},set hidden(v){mutations++;values.hidden=v}}}
 const root=el(),groups={'[data-chest508]':4,'[data-hand-pick508]':4,'[data-dot508]':8,'[data-mark508]':7,'[data-reveals508] .lk-art508':4};for(const[k,v]of Object.entries(groups))groups[k]=Array.from({length:v},el);root.querySelectorAll=q=>groups[q]??[];
 globalThis.document={visibilityState:'visible',querySelector:()=>null,addEventListener:(n,fn)=>listeners.set(n,fn),removeEventListener:n=>listeners.delete(n)};globalThis.requestAnimationFrame=fn=>{const id=++serial;queue.set(id,fn);return id};globalThis.cancelAnimationFrame=id=>queue.delete(id);
 if(g.phase==='countdown')begin(g);const c=context(g);c.root={querySelector:()=>root};c.offset=g.phaseAt-Date.now();c.raw=()=>true;
 return{g,c,root,groups,queue,listeners,mutations:()=>mutations,reset:()=>mutations=0,flush(){const jobs=[...queue.values()];queue.clear();for(const f of jobs)f()},restore(){luckBefore508(c);for(const[k,v]of Object.entries(saved)){if(v===undefined)delete globalThis[k];else globalThis[k]=v}}}
}
test('coalesced frames and unchanged state perform zero DOM writes; custom CSS properties are applied correctly',()=>{const d=dom();try{luckAfter508(d.c);for(let i=0;i<50;i++)luckTick508(d.c);assert.equal(d.queue.size,1);d.flush();assert.ok(d.groups['[data-chest508]'].every(b=>!b.disabled));assert.ok(d.root.style.getPropertyValue('--lk-pawn508').endsWith('px'));paintLuck508(d.c,d.g.phaseAt+20);d.reset();for(let i=0;i<1800;i++)paintLuck508(d.c,d.g.phaseAt+20);assert.equal(d.mutations(),0)}finally{d.restore()}});
test('chest then hand double-tap bursts send only one message per choice without rebuilding DOM',()=>{const d=dom();try{luckAfter508(d.c);d.flush();const sent=[];d.c.raw=(op,m)=>{sent.push({op,m});return true};for(let i=0;i<50;i++)requestLuck508(d.c,'chest',0);assert.equal(sent.length,1);d.flush();assert.ok(d.groups['[data-chest508]'].every(b=>b.disabled));chooseAll(d.g,'chest');d.c.state.luck=publicLuck508(d.g,'p0');d.c.offset=d.g.phaseAt-Date.now();luckReceive508(d.c);paintLuck508(d.c,d.g.phaseAt+10);assert.equal(d.c.lkUI508.pending,null);assert.ok(d.groups['[data-hand-pick508]'].every(b=>!b.disabled));for(let i=0;i<100;i++)requestLuck508(d.c,'hand',2);assert.equal(sent.length,2);assert.equal(sent[1].m.index,2);assert.equal(sent[1].m.kind,'hand');assert.equal(sent[1].op,'luck508');d.flush();assert.equal(d.groups['[data-hand-pick508]'][2].getAttribute('aria-pressed'),'true')}finally{d.restore()}});
test('actual paint code updates every attack, reflected result and run frame without null nodes or NaNs',()=>{for(const ids of[['shell','mirror','shield','lightning'],['banana','pit','swap','magnet'],['dice','spring','turbo','comet']]){const d=dom(readyItems(ids,[0,1200,600,200]));try{luckAfter508(d.c);d.flush();const nodes=d.c.lkUI508.nodes;advanceLuck508(d.g,d.g.nextAt);d.c.state.luck=publicLuck508(d.g,'p0');if(d.g.phase==='broadcast'){for(let ms=0;ms<d.g.event.castMs;ms+=32)paintLuck508(d.c,d.g.phaseAt+ms);assert.equal(nodes.cast.hidden,false);advanceLuck508(d.g,d.g.nextAt);d.c.state.luck=publicLuck508(d.g,'p0')}for(let ms=0;ms<=5000;ms+=32)paintLuck508(d.c,d.g.phaseAt+ms);assert.equal(nodes.cast.hidden,true);assert.equal(d.c.lkUI508.nodes,nodes);assert.doesNotMatch(nodes.ground.style.transform,/NaN/);assert.ok(nodes.players.every(r=>!String(r.body.style.transform).includes('NaN')))}finally{d.restore()}}});
test('private hand descriptions and item atlas positions update when hand changes, without exposing another hand',()=>{const d=dom();try{chooseAll(d.g,'chest');d.c.state.luck=publicLuck508(d.g,'p0');luckAfter508(d.c);d.flush();for(let i=0;i<4;i++){const it=ITEMS508.find(x=>x.id===d.c.state.luck.hand[i]),b=d.groups['[data-hand-pick508]'][i];assert.equal(b.querySelector('b').textContent,it.name);assert.equal(b.querySelector('p').textContent,it.detail);assert.equal(b.querySelector('.lk-art508').style.getPropertyValue('--tile-x'),String(it.tile%4));assert.match(b.getAttribute('aria-label'),new RegExp(it.name))}}finally{d.restore()}});
test('hidden/unmounted views cancel frames and clean listeners; failed send releases input and reports error',()=>{const d=dom();try{luckAfter508(d.c);document.visibilityState='hidden';d.listeners.get('visibilitychange')();assert.equal(d.queue.size,0);d.reset();for(let i=0;i<100;i++)luckTick508(d.c);assert.equal(d.mutations(),0);document.visibilityState='visible';d.listeners.get('visibilitychange')();d.flush();d.c.raw=()=>false;assert.equal(requestLuck508(d.c,'chest',0),false);d.flush();assert.equal(d.c.lkUI508.pending,null);assert.equal(d.c.lkUI508.nodes.error.hidden,false);luckBefore508(d.c);assert.equal(d.queue.size,0);assert.equal(d.listeners.size,0)}finally{d.restore()}});
test('all-safe gorilla hero displays four actual survivors and no empty loser panel',()=>{const g=game();const c=context(g);c.state.gorilla={id:'gg',phase:'result',players:g.players,allSafe504:true,events:[],picked:[],rules503:1};const html=gorillaView502(c);const hero=html.slice(html.indexOf('gg-result-hero502'),html.indexOf('party-result-actions490'));assert.match(hero,/gg-survivors508/);assert.doesNotMatch(hero,/gg-result-pawn502|みんなセーフ！/);assert.equal((hero.match(/class="sg-monster"/g)??[]).length,4)});
test('both new image assets decode completely; item sheet has alpha and sixteen occupied cells',async()=>{const require=createRequire(import.meta.url),{loadImage,createCanvas}=require('@napi-rs/canvas');const items=await loadImage(new URL('../assets/luck508/items.png',import.meta.url).pathname),course=await loadImage(new URL('../assets/luck508/course.png',import.meta.url).pathname);assert.equal(items.width,items.height);assert.ok(course.width/course.height>2.9);const canvas=createCanvas(items.width,items.height),ctx=canvas.getContext('2d');ctx.drawImage(items,0,0);const raw=ctx.getImageData(0,0,canvas.width,canvas.height).data;let transparent=0;for(let i=3;i<raw.length;i+=4)if(raw[i]===0)transparent++;assert.ok(transparent>canvas.width*canvas.height*.15);for(let cell=0;cell<16;cell++){const x=Math.floor(cell%4*items.width/4),y=Math.floor(Math.floor(cell/4)*items.height/4),d=ctx.getImageData(x,y,Math.floor(items.width/4),Math.floor(items.height/4)).data;assert.ok(d.some((v,i)=>i%4===3&&v>200))}});
