import {resolveJackpot553} from '../src/ricochet550/Rush553.js';
import {event550} from '../src/ricochet550/Rules550.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {make550,start550,physics550,advance550,finishRound550,launch550,RICOCHET550 as C,public550} from '../src/ricochet550/Rules550.js';
import {CARNIVAL552,rotorAngle552,rotorContact552,chainMultiplier552} from '../src/ricochet550/Carnival552.js';
import {projection550} from '../src/ricochet550/Renderer550.js';
const game=()=>{const g=make550({id:'C',code:'C',partyId:'P',hostId:'h',now:0,members:[],mode:'pinball'});start550(g,0,552);g.players.forEach(p=>{p.ai=false;p.parts={};p.picked='spring'});return g};
function strike(g,p,b){g.simAt+=500;Object.assign(p,{x:b.x,y:b.y-b.r-p.r-.01,vx:0,vy:12});physics550(g);}
test('three different jewels unlock crown jackpot; duplicates never complete a set',()=>{
 const g=game(),p=g.players[0];strike(g,p,g.layout.bumpers[0]);assert.equal(p.gems552,1);strike(g,p,g.layout.bumpers[3]);assert.equal(p.gems552,1);
 strike(g,p,g.layout.bumpers[1]);assert.equal(p.gems552,3);strike(g,p,g.layout.bumpers[2]);assert.equal(p.gems552,7);assert(g.events.some(e=>e.type==='ready'&&e.seat===0));
 const before=p.roundScore,pot=g.carnival552.pot;g.players[1].gems552=7;strike(g,p,g.layout.bumpers[6]);assert.equal(p.gems552,0);assert.equal(g.players[1].gems552,7);assert.equal(p.jackpots552,1);assert.equal(p.roundScore,before);assert(g.carnival552.pending553);g.simAt=g.carnival552.pending553.revealAt;resolveJackpot553(g,event550);assert(p.roundScore-before>=pot);assert.equal(g.carnival552.wins,1);assert(g.events.some(e=>e.type==='jackpot'&&e.value>=pot));
});
test('a locked crown awards an ordinary hit without paying the pot',()=>{const g=game(),p=g.players[0],pot=g.carnival552.pot;strike(g,p,g.layout.bumpers[6]);assert.equal(p.jackpots552,0);assert.equal(g.carnival552.pot,pot);assert(p.roundScore>0);assert(!g.events.some(e=>e.type==='jackpot'))});
test('crown recharge stops double claims, retains waiting gems, and opens after six seconds',()=>{const g=game(),a=g.players[0],b=g.players[1];a.gems552=b.gems552=7;strike(g,a,g.layout.bumpers[6]);const until=g.carnival552.lockUntil;assert.equal(until,g.simAt+6000);a.x=-4;a.y=2;a.vx=a.vy=0;strike(g,b,g.layout.bumpers[6]);assert.equal(b.gems552,7);assert.equal(b.jackpots552,0);g.simAt=until-500;strike(g,b,g.layout.bumpers[6]);assert.equal(b.jackpots552,1);assert.equal(b.gems552,0)});
test('bank interest is awarded once per shot and compounds with actual earned points',()=>{const g=game(),p=g.players[0];p.parts.bank=2;p.roundScore=1000;finishRound550(g,0);assert.equal(p.score,1324);assert.equal(g.history[0].rows[0].investment,324);assert.equal(p.roundScore,0);finishRound550(g,0);assert.equal(p.score,1420)});
test('MAX retains a threefold burst compared with a gentle shot',()=>{const a=game(),b=game();launch550(a,a.players[0],1,0);launch550(b,b.players[0],.4,0);assert(a.players[0].vy/b.players[0].vy>3);assert.equal(a.players[0].vy,41)});
test('36 shared gem hits start exactly five seconds of double points',()=>{
 const g=game();for(let i=0;i<CARNIVAL552.feverHits;i++)strike(g,g.players[i%4],g.layout.bumpers[0]);assert.equal(g.carnival552.heat,0);assert.equal(g.carnival552.feverUntil,g.simAt+5000);assert.equal(g.events.filter(e=>e.type==='fever').length,1);
 const n=game();n.carnival552.feverUntil=5000;const p=n.players[0];strike(n,p,n.layout.bumpers[0]);assert.equal(p.roundScore,120);n.simAt=6000;p.comboAt=-1e6;const before=p.roundScore;strike(n,p,n.layout.bumpers[0]);assert.equal(p.roundScore-before,60);
});
test('chain acceleration and score multiplier expire after the real impact window',()=>{const g=game(),p=g.players[0];for(let i=0;i<6;i++)strike(g,p,g.layout.bumpers[i]);assert.equal(p.combo,6);assert.equal(p.bestCombo552,6);assert.equal(chainMultiplier552(p),1.5);assert.equal(g.events.filter(e=>e.type==='combo').length,2);Object.assign(p,{x:4,y:2,vx:0,vy:0});g.simAt+=2301;physics550(g);assert.equal(p.combo,0);assert.equal(chainMultiplier552(p),1);assert.equal(p.bestCombo552,6)});
test('round boundaries preserve every carnival mechanism and the exact physical state',()=>{const g=game(),p=g.players[0];g.simAt=1000;g.carnival552.heat=7;g.carnival552.feverUntil=4500;p.gems552=5;p.combo=4;p.comboAt=900;p.wallMult=2.4;p.charge=20;p.x=2;p.y=7;p.vx=-4;p.vy=12;g.layout.chests[0].claimed=1;g.layout.chests[0].respawnAt552=8500;const state=structuredClone(g),angle=rotorAngle552(g);finishRound550(g,1000);assert.equal(g.phase,'play');for(const k of ['x','y','vx','vy','gems552','combo','comboAt','wallMult','charge'])assert.equal(p[k],state.players[0][k]);assert.deepEqual(g.layout,state.layout);assert.deepEqual(g.carnival552,state.carnival552);assert.equal(rotorAngle552(g),angle)});
test('chests respawn on elapsed time, never merely on a round change',()=>{const g=game(),p=g.players[0],b=g.layout.chests[0];Object.assign(p,{x:b.x,y:b.y,vx:0,vy:0});physics550(g);assert.equal(b.claimed,0);const deadline=b.respawnAt552;p.x=0;p.y=2;finishRound550(g,0);assert.equal(b.claimed,0);g.simAt=deadline-20;physics550(g);assert.equal(b.claimed,0);g.simAt=deadline;physics550(g);assert.equal(b.claimed,null)});
test('rotating capsule transfers signed surface velocity to an unlaunched body',()=>{const g=game(),p=g.players[0];Object.assign(p,{x:1.5,y:CARNIVAL552.rotorY+CARNIVAL552.rotorRadius+p.r-.02,vx:0,vy:0,launched:false});let hits=0;rotorContact552(g,p,{hit:()=>hits++,event:()=>{},cool:()=>true});assert(p.vy>2);assert.equal(p.launched,false);assert.equal(hits,1);const carried=p.vy;launch550(g,p,.5,0);assert(p.vy>carried);assert.equal(g.events.at(-1).carryY,carried)});
test('MAX speed crosses moving rotor without tunneling or nonfinite state',()=>{const g=game(),p=g.players[0];Object.assign(p,{x:1.4,y:7.6,vx:0,vy:95});physics550(g);assert(p.vy<0);for(let at=20;at<=5000;at+=20){g.simAt=at;physics550(g);for(const q of g.players){assert(Number.isFinite(q.x+q.y+q.vx+q.vy));assert(Math.abs(q.x)<=6-q.r+.002);assert(q.y>=q.r-.002&&q.y<=C.height-q.r+.002);assert(Math.hypot(q.vx,q.vy)<=95.001)}}});
test('pinball projection never changes when a player selects or reaches the next round',()=>{for(const [width,height] of [[320,375],[390,330],[430,552],[609,350]]){const g=game(),p=g.players[0],r={width,height};p.picked=null;const before=projection550(r,g,p);p.picked='cell';assert.deepEqual(projection550(r,g,p),before);finishRound550(g,0);assert.deepEqual(projection550(r,g,p),before)}});
test('stall recovery shifts mechanism clocks together and snapshots remain private',()=>{const g=game();g.carnival552.feverUntil=5000;g.layout.chests[0].claimed=1;g.layout.chests[0].respawnAt552=10000;const oldAngle=rotorAngle552(g);advance550(g,10000);assert(Math.abs(rotorAngle552(g)-oldAngle-.5*CARNIVAL552.rotorOmega)<.01);assert.equal(g.carnival552.feverUntil-g.simAt,4500);const s=public550(g,g.players[0].playerId,{frame:true});assert(s.carnival552);assert(!('offers' in s.players[1]));assert(!('seed' in s))});
