import {cleanupSingles410} from '../src/battle/SingleTraits410.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import * as C from '../src/chapterTwo/ChapterTwoSystem.js';
import {CHAPTER_TWO_RELICS394 as relics,CHAPTER_TWO_CIRCLES394 as circles} from '../src/data/chapterTwoRelics394.js';
import {createChapterTwoRelic394} from '../src/chapterTwo/ChapterTwoRewards394.js';
import {chapterTwoCollection395,normalizeChapterTwoCollection395} from '../src/chapterTwo/ChapterTwoCollection395.js';
import {chapterTwoCollectionMarkup395} from '../src/ui/ChapterTwoCollection395.js';
import {previewRelicRefine395,refineChapterTwoRelics395} from '../src/chapterTwo/ChapterTwoRefining395.js';
import {chapterTwoRepeatTicket395,repeatChapterTwoElite395} from '../src/chapterTwo/ChapterTwoRepeat395.js';
import {RESONANCE_PAIRS385,twinActionBlocked395,twinReady385,resolveTwin385} from '../src/battle/TwinResonance385.js';
import {twinStatus385} from '../src/ui/TwinStatus385.js';
import {createMagicCircleInstance} from '../src/core/MagicCircleSystem.js';import {SaveService} from '../src/services/SaveService.js';
const main=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
function fixture(area=0){const mem=new Map();globalThis.localStorage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};const save=new SaveService(),s=save.state;s.player.maxFloor=100;s.campaign100.finalCompleted=true;const p=C.chapterTwoState(s);p.introComplete=true;for(let a=0;a<5;a++){p.areaClears378[a]=1;C.beginChapterTwoRun(s,{area:a});p.run.defeated=C.CHAPTER_TWO_AREAS[a].keys.slice();p.run.keys380=p.run.defeated.slice(1,3);C.chapterTwoState(s);}p.run=p.runs378[area];s.monsters.forEach(m=>{m.currentHp=23;m.currentMp=5});return{save,s,p};}
function sweep(s){const results=[];for(const room of [1,3,4]){const r=C.chapterTwoState(s).run;r.room=room;const a=C.beginChapterTwoEncounter(s,`roam${r.area}_${room}`);assert.ok(a.ok);results.push(C.settleChapterTwoEncounter(s,a.token,{won:true}));}return results;}
function items(s,plus=12,n=3){const target=createChapterTwoRelic394(relics[0],1000,1);target.plus=plus;const mats=Array.from({length:n},()=>{const m=createChapterTwoRelic394(relics[0],1000,1);m.locked=false;return m});s.equipment=[target,...mats];s.player.gold=1e9;return{target,mats};}
function pairBattle(pair,side){const members=pair.members.map((speciesId,i)=>({id:'p'+i,speciesId,currentHp:1000,hp:1000})),foes=[{id:'foe',hp:100000,currentHp:100000}];return{party:side==='ally'?members:foes,enemies:side==='enemy'?members:foes,turn:1,allyAilments:{},enemyStatuses:{},allyEffects:{},enemyEffects:{}};}
function envFor(b,side){const own=side==='ally'?b.party:b.enemies,foes=side==='ally'?b.enemies:b.party,calls={hits:0,support:0};return{calls,blocked:()=>false,opponents:()=>foes,cue:async()=>{},hit:async()=>{calls.hits++;return 1},heal:async()=>calls.support++,restoreMp:async()=>calls.support++,shield:()=>calls.support++,cleanse:()=>calls.support++,boost:()=>calls.support++,weaken(){},dispel(){},hpRatio:()=>1,opponentHpRatio:()=>1};}
test('all 24 pairs on both sides stop for six active control ailments and resume without spending blocked quota',async()=>{
 for(const pair of RESONANCE_PAIRS385)for(const side of ['ally','enemy'])for(const status of ['sleep','freeze','paralysis','charm','confusion','fear']){const b=pairBattle(pair,side),own=side==='ally'?b.party:b.enemies,store=side==='ally'?b.allyAilments:b.enemyStatuses,env=envFor(b,side);store.p1=[{id:status,turns:1}];assert.equal(twinReady385(b,own[0],side),null,pair.id);assert.equal(await resolveTwin385(b,own[0],side,env),false);assert.equal(b.twinResonance385,undefined);store.p1[0].turns=0;assert.ok(await resolveTwin385(b,own[0],side,env));assert.equal(await resolveTwin385(b,own[0],side,env),false);}
});
test('control rechecks after cue and between hits stop followups and support, while poison and expired stun do not',async()=>{
 for(const side of ['ally','enemy']){const b=pairBattle(RESONANCE_PAIRS385[0],side),own=side==='ally'?b.party:b.enemies,store=side==='ally'?b.allyEffects:b.enemyEffects,env=envFor(b,side);env.cue=async()=>store.p1=[{kind:'stun',turns:1}];await resolveTwin385(b,own[0],side,env);assert.equal(env.calls.hits,0);assert.equal(env.calls.support,0);
 b.turn++;store.p1=[{kind:'stun',turns:0}];env.cue=async()=>{};env.hit=async()=>{env.calls.hits++;store.p1=[{kind:'status:freeze',turns:1}];return 1};await resolveTwin385(b,own[0],side,env);assert.equal(env.calls.hits,1);assert.equal(env.calls.support,0);}
 const b=pairBattle(RESONANCE_PAIRS385[0],'ally');b.allyAilments.p1=[{id:'poison',turns:3}];assert.ok(twinReady385(b,b.party[0]));b.enemyStatuses.p1=[{id:'sleep',turns:3}];assert.ok(twinReady385(b,b.party[0]),'opposing status store is not used');
});
test('healthy cleanse pair can still cure sleeping third-party allies and UI reports incapacitated pairs',async()=>{
 const pair=RESONANCE_PAIRS385.find(p=>p.cleanse391),b=pairBattle(pair,'ally');b.party.push({id:'third',currentHp:200});b.allyAilments.third=[{id:'sleep',turns:1}];const env=envFor(b,'ally');let cured=false;env.cleanse=u=>{if(u.id==='third')cured=true};await resolveTwin385(b,b.party[0],'ally',env);assert.equal(cured,true);
 b.allyAilments.p1=[{id:'freeze',turns:1}];assert.match(twinStatus385(b.party,{battle:b}),/行動不能/);assert.doesNotMatch(twinStatus385(b.party,{battle:b}),/共鳴中/);
});
test('collection counts deduplicated owned gear across three stores and circles, without inventing historical losses',()=>{
 const {s}=fixture(),{target,mats}=items(s);s.equipment=[target];s.reserveEquipment=[mats[0],target];s.bossEquipmentVault=[mats[1]];const c=createMagicCircleInstance(s,circles[0].id,{level:15});s.magicCircles.instances.push({...c});const x=chapterTwoCollection395(s);assert.equal(x.relics[0].count,3);assert.deepEqual(x.relics[0].locations,['所持品','予備倉庫','王装保管庫']);assert.equal(x.circles[0].count,1);assert.equal(x.circles[0].highestLevel,15);assert.equal(x.relicCount,1);assert.equal(x.relics[1].acquired,false);
});
test('discovery survives consuming all copies and SaveService reload; malformed discovery is bounded to valid definitions',()=>{
 const {s,save}=fixture();items(s);normalizeChapterTwoCollection395(s);s.equipment=[];s.chapterTwoCollection395.relics.push('fake');save.save();const loaded=new SaveService(),x=chapterTwoCollection395(loaded.state);assert.equal(x.relics[0].acquired,true);assert.equal(x.relics[0].count,0);assert.equal(loaded.state.chapterTwoCollection395.relics.includes('fake'),false);loaded.state.chapterTwoCollection395={relics:{invalid:true},circles:42};assert.doesNotThrow(()=>normalizeChapterTwoCollection395(loaded.state));
});
test('all 45 elite loot receipts update discovery and return reports show four gear plus one circle without granting twice',()=>{
 for(let area=0;area<5;area++){const {s}=fixture(area);for(let tier=1;tier<=3;tier++){assert.ok(C.beginChapterTwoElite393(s,area,tier).ok);sweep(s);const x=chapterTwoCollection395(s);assert.equal(x.relics.filter(r=>r.area===area&&r.acquired).length,3);assert.ok(x.circles[area].acquired);const gear=s.equipment.length,report=C.takeChapterTwoSummary380(s);assert.equal(report.equipment.length,4);assert.equal(report.circles395.length,1);assert.equal(s.equipment.length,gear);assert.equal(C.takeChapterTwoSummary380(s).equipment.length,0);}}
});
test('collection filters cover all 20 sources, distinguish acquired/owned, and locked areas cannot be selected',()=>{
 const {s}=fixture();items(s);normalizeChapterTwoCollection395(s);s.equipment=[];let html=chapterTwoCollectionMarkup395(s);assert.equal((html.match(/data-collection-id=/g)??[]).length,20);assert.match(html,/入手済み・現在所持なし/);assert.equal((chapterTwoCollectionMarkup395(s,{filter:'missing'}).match(/data-collection-id=/g)??[]).length,19);assert.match(chapterTwoCollectionMarkup395(s,{filter:'owned'}),/該当する品はありません/);
 for(let area=0;area<5;area++){html=chapterTwoCollectionMarkup395(s,{area});assert.equal((html.match(/data-collection-id=/g)??[]).length,4);assert.equal((html.match(new RegExp(`data-collection-source="${area}"`,'g'))??[]).length,4);}
 s.chapterTwo376.areaClears378={};assert.match(chapterTwoCollectionMarkup395(s),/data-collection-source="0" disabled/);
});
test('batch refine sums each successive price, consumes exactly selected materials and preserves all growth and protections',()=>{
 const {s}=fixture(),{target,mats}=items(s,26,5),ids=mats.slice(0,3).map(m=>m.id),original=structuredClone(target),gold=s.player.gold;const plan=previewRelicRefine395(s,target.id,ids);assert.equal(plan.after,29);assert.equal(plan.price,25000*(27+28+29));assert.ok(plan.affordable);const result=refineChapterTwoRelics395(s,target.id,ids);assert.ok(result.ok);assert.deepEqual(result.consumed,ids);assert.equal(target.plus,29);assert.equal(s.equipment.length,3);assert.equal(s.player.gold,gold-plan.price);for(const k of ['level','exp','affixes','locked','favorite','stats'])assert.deepEqual(target[k],original[k]);assert.equal(chapterTwoCollection395(s).relicCount,1);
});
test('batch refine rejects overcap, duplicate IDs, stale protection, equipped orphan IDs and low gold atomically',()=>{
 for(const invalid of ['overcap','duplicate','lock','favorite','equipped','gold','battle','run']){const {s}=fixture(),{target,mats}=items(s,28),ids=mats.slice(0,2).map(m=>m.id);if(invalid==='overcap')ids.push(mats[2].id);if(invalid==='duplicate')ids[1]=ids[0];if(invalid==='lock')mats[1].locked=true;if(invalid==='favorite')mats[1].favorite=true;if(invalid==='equipped')s.monsters[0].equipment={weaponRight:mats[1].id};if(invalid==='gold')s.player.gold=1;if(invalid==='battle')s.activeBattle={};if(invalid==='run')s.player.inRun=true;const before=JSON.stringify(s);assert.equal(refineChapterTwoRelics395(s,target.id,ids).ok,false,invalid);assert.equal(JSON.stringify(s),before,invalid);}
});
test('batch refine save rollback restores full material set and gold then retries once',()=>{
 const {s,save}=fixture(),{target,mats}=items(s),ids=mats.map(m=>m.id),before=JSON.stringify(s),fn=save.save.bind(save);save.save=()=>false;const c={save,game:null,showToast(){}};vm.createContext(c);vm.runInContext(main.slice(main.indexOf('function chapterTwoCommit('),main.indexOf('let chapterTwoIntroTimer=')),c);assert.equal(c.chapterTwoCommit(()=>refineChapterTwoRelics395(save.state,target.id,ids)).saveFailed,true);assert.equal(JSON.stringify(save.state),before);save.save=fn;assert.ok(c.chapterTwoCommit(()=>refineChapterTwoRelics395(save.state,target.id,ids)).ok);assert.equal(new SaveService().state.equipment.find(i=>i.id===target.id).plus,15);
});
test('same-tier replay preserves vitals, story, storage and rewards while renewing all three patrol tokens',()=>{
 for(let area=0;area<5;area++){const {s,p}=fixture(area);assert.ok(C.beginChapterTwoElite393(s,area).ok);const results=sweep(s),ticket=chapterTwoRepeatTicket395(s),old=p.run,keys=[...old.keys380],hp=s.monsters.map(m=>[m.currentHp,m.currentMp]),gold=s.player.gold,gear=s.equipment.length;assert.ok(repeatChapterTwoElite395(s,ticket).ok);assert.notEqual(p.run,old);assert.equal(p.run.eliteTier393,1);assert.equal(p.run.visit380,ticket.visit+1);assert.deepEqual(p.run.roaming380,[]);assert.equal(p.run.room,0);assert.equal(p.run.auto377,false);assert.deepEqual(p.run.keys380,keys);assert.deepEqual(s.monsters.map(m=>[m.currentHp,m.currentMp]),hp);assert.equal(s.player.gold,gold);assert.equal(s.equipment.length,gear);assert.equal(repeatChapterTwoElite395(s,ticket).ok,false);assert.equal(C.settleChapterTwoEncounter(s,results[2].token,{won:true}).ok,false);}
});
test('replay rejects incomplete, all-down and pending runs; save failure restores the completed visit for retry',()=>{
 const {s,save}=fixture();C.beginChapterTwoElite393(s,0);assert.equal(chapterTwoRepeatTicket395(s),null);sweep(s);const ticket=chapterTwoRepeatTicket395(s);s.monsters.forEach(m=>m.currentHp=0);assert.equal(repeatChapterTwoElite395(s,ticket).ok,false);s.monsters[0].currentHp=23;const before=JSON.stringify(s),fn=save.save.bind(save);save.save=()=>false;const c={save,game:null,showToast(){}};vm.createContext(c);vm.runInContext(main.slice(main.indexOf('function chapterTwoCommit('),main.indexOf('let chapterTwoIntroTimer=')),c);assert.equal(c.chapterTwoCommit(()=>repeatChapterTwoElite395(save.state,ticket)).saveFailed,true);assert.equal(JSON.stringify(save.state),before);save.save=fn;assert.ok(c.chapterTwoCommit(()=>repeatChapterTwoElite395(save.state,ticket)).ok);const loaded=new SaveService();assert.equal(C.chapterTwoState(loaded.state).run.visit380,ticket.visit+1);C.chapterTwoState(loaded.state).run.pending={token:'pending'};assert.equal(chapterTwoRepeatTicket395(loaded.state),null);
});
test('real replay controller detaches old field before dispose and cannot process a second click',()=>{
 const {s}=fixture();C.beginChapterTwoElite393(s,0);sweep(s);const old=s.chapterTwo376.run,ticket=chapterTwoRepeatTicket395(s);let removed=0,started=0;const c={save:{state:s},battle:null,game:{chapterTwo:true},chapterTwoCommit:f=>f(),repeatChapterTwoElite395,stopGame(){old.position={x:999,y:999};assert.equal(c.game.discardChapterTwoSave,true)},snapshot:{},showToast(){},go(){started++}};vm.createContext(c);vm.runInContext(main.slice(main.indexOf('function startChapterTwoRepeat395('),main.indexOf('function openChapterTwoDestinations(')),c);const modal={remove(){removed++}};c.startChapterTwoRepeat395(ticket,modal);c.startChapterTwoRepeat395(ticket,modal);assert.notEqual(s.chapterTwo376.run.position.x,999);assert.equal(removed,1);assert.equal(started,1);
});

test('multi-material dialog previews exact total, supports deselection, and commits only the displayed selection',()=>{
 const {s}=fixture(),{target,mats}=items(s,26),buttons=mats.map(m=>({dataset:{relicMaterial:m.id},setAttribute(k,v){this[k]=v}})),primary={},selection={};let rendered=0,removed=0;
 const modal={querySelector:q=>q==='[data-modal-primary]'?primary:selection,querySelectorAll:()=>buttons,remove(){removed++}};
 const c={save:{state:s},battle:null,relicRefineCandidates394:(_s,_t)=>mats,previewRelicRefine395,refineChapterTwoRelics395,escapeAttribute:s=>s,showToast(){},chapterTwoCommit:f=>f(),app:{insertAdjacentHTML(){}},Modal:()=>'',topModal:()=>modal,render(){rendered++}};
 vm.createContext(c);vm.runInContext(main.slice(main.indexOf('function openRelicRefine394('),main.indexOf('function enhanceEquipment(')),c);c.openRelicRefine394(target.id);buttons.forEach(b=>b.onclick());assert.match(selection.textContent,/素材 3個/);assert.match(selection.textContent,/2,100,000G/);buttons[1].onclick();assert.match(selection.textContent,/素材 2個/);assert.match(selection.textContent,/1,375,000G/);assert.match(selection.textContent,/＋26 → ＋28/);assert.equal(buttons[1]['aria-pressed'],'false');primary.onclick();primary.onclick();assert.equal(target.plus,28);assert.deepEqual(s.equipment.map(i=>i.id),[target.id,mats[1].id]);assert.equal(rendered,1);assert.equal(removed,1);
});

test('completed elite victory keeps contribution before receipt and disables auto-dismiss until replay is explicitly chosen',()=>{
 const {s}=fixture();C.beginChapterTwoElite393(s,0);for(const room of [1,3]){C.chapterTwoState(s).run.room=room;const a=C.beginChapterTwoEncounter(s,`roam0_${room}`);C.settleChapterTwoEncounter(s,a.token,{won:true});}C.chapterTwoState(s).run.room=4;const a=C.beginChapterTwoEncounter(s,'roam0_4'),primary={},repeat={},modal={classList:{add(){}},querySelector:q=>q==='[data-repeat-elite395]'?repeat:primary,remove(){}};let reveal,auto,replays=0;
 const c={save:{state:s,save:()=>true},battle:{specialBattleType:'chapterTwo',chapterTwoToken:a.token,chapterTwoEncounter:a.encounter,party:s.monsters,auto:true},battleContributionSnapshot:()=>({}),syncPersistentAilments(){},clearPartySynergy(){},settleChapterTwoEncounter:C.settleChapterTwoEncounter,chapterTwoState:C.chapterTwoState,chapterTwoRepeatTicket395,cleanupSingles410,cleanupUltimateBattle(){},document:{querySelector:()=>null},render(){},audio:{sfx(){}},chapterTwoRewardBody:()=>'',app:{insertAdjacentHTML(){}},Modal:()=>'',topModal:()=>modal,showChapterTwoProgress(){},openBattleContributionReport:(_c,fn)=>reveal=fn,chapterTwoAutoModal380:(_m,_fn,enabled)=>auto=enabled,startChapterTwoRepeat395:(ticket,m)=>{assert.equal(ticket.area,0);assert.equal(ticket.tier,1);assert.equal(m,modal);replays++},CHAPTER_TWO_ENCOUNTERS:C.ENCOUNTERS};
 vm.createContext(c);vm.runInContext(main.slice(main.indexOf('function finishChapterTwoBattle('),main.indexOf('function openExploreFloorSelector(')),c);c.finishChapterTwoBattle(true);assert.equal(modal.hidden,true);assert.equal(replays,0);reveal();assert.equal(modal.hidden,false);assert.equal(auto,false);assert.equal(replays,0);repeat.onclick();assert.equal(replays,1);
});
