import test from 'node:test';import assert from 'node:assert/strict';
import * as T from '../src/tetra/Rules539.js';import * as H from '../src/hide/Rules536.js';import * as E from '../src/hide/Heist541.js';import * as C from '../src/canal/Rules500.js';import {makeCanal489} from '../src/canal/Rules489.js';import {validStroke541} from '../src/canal/Team541.js';import {route500} from '../src/canal/Motion500.js';
const members=Array.from({length:4},(_,i)=>({playerId:'p'+i,name:'仲間'+i,choice:{id:'m'+i,speciesId:'slime'}}));
const tetra=()=>{const g=T.makeTetra539({id:'t',code:'T',partyId:'p',hostId:'p0',members});T.startTetra539(g,0,541);T.advanceTetra539(g,4000);return g};
const hide=()=>{const g=H.makeHide536({id:'h',code:'H',partyId:'p',hostId:'p0',members});g.role='hunter';H.startHide536(g,0,541);g.phase='play';g.lastAt=g.startAt;g.elapsed=0;return g};
const canal=()=>{const g=makeCanal489({id:'c',code:'C',partyId:'p',hostId:'p0',members,now:0,seed:541});g.rules541=1;C.start500(g,0);g.phase='playing';g.simAt=g.startAt;g.nextSpawnAt=1e9;return g};
const advance=(g,ms,fn)=>{for(let i=0;i<ms;i+=50)fn(g,g.lastAt+Math.min(50,ms-i))};
function jump(g,p,q){const angle=Math.atan2(q.y-p.y,q.x-p.x),power=Math.hypot(q.x-p.x,q.y-p.y)/T.maxJump541(p);T.inputTetra539(g,p,{action:'begin',angle,power});const aim=T.aim539(g,p,angle,power);assert.equal(T.inputTetra539(g,p,{action:'release',angle,power}),true);assert.equal(p.flight.tx,aim.x);advance(g,1000,T.advanceTetra539);return p;}
function enemy(g,{id=g.enemies.length+1,x=.5,progress=.45,hp=1,kind=0}={}){const e={id,path500:1,path541:1,kind,lane:0,routeX:x,routeEnd:x,curve:0,wiggle:0,hp,maxHp:hp,spawnAt:g.startAt,travelMs:1e6,motionAt:g.startAt,motionProgress:progress,contributors:[],slowUntil:0,nextShotAt:1e9};g.enemies.push(e);return e;}
function stroke(g,p,path,at=g.startAt){return C.input500(g,p,{seq:p.lastSeq+1,lane:0,held:false,pulse:false,burst:false,stroke541:path},at)}
test('three precise tips unlock one longer jump; prediction equals server endpoint',()=>{const g=tetra(),p=g.players[0];g.players.slice(1).forEach(p=>p.finishedAt=0);const pads=[0,1,2,3].map((n)=>({id:n,x:500,y:5500-n*260,r:90,tip:30,angle:0,kind:'stable',section:0}));g.course.pads=pads;Object.assign(p,{x:500,y:5500,padId:0});for(let i=1;i<4;i++){jump(g,p,pads[i]);assert.equal(p.flow541,i)}assert.equal(T.maxJump541(p),700);const q={id:4,x:500,y:4100,r:90,tip:30,angle:0,kind:'stable',section:0};g.course.pads.push(q);jump(g,p,q);assert.equal(p.padId,4);assert.equal(p.flow541,1);assert.equal(p.perfect541,4);assert.equal(T.maxJump541(p),520)});
test('same-pad hop cannot farm charge; water resets charge',()=>{const g=tetra(),p=g.players[0];g.players.slice(1).forEach(p=>p.finishedAt=0);const pad=g.course.pads.find(p=>p.kind==='stable');Object.assign(p,{x:pad.x+60,y:pad.y,padId:pad.id,flow541:2});jump(g,p,pad);assert.equal(p.flow541,0);p.flow541=3;T.fall539(g,p);assert.equal(p.flow541,0)});
test('big waves still sweep tips and spare checkpoints',()=>{const g=tetra(),p=g.players[0],pad=g.course.pads.find(p=>p.kind==='stable');Object.assign(p,{x:pad.x,y:pad.y,padId:pad.id});g.elapsed=37500;g.lastAt=g.startAt+37500;T.advanceTetra539(g,g.lastAt+50);assert.notEqual(p.fallAt,null);assert.equal(g.players[1].fallAt,null)});
test('seal requires stopping, decays after leaving, then opens exit; one escape wins team',()=>{const g=hide(),p=g.players[1],s=g.heist541.seals[0];Object.assign(p,{x:s.x,y:s.y,moving:true});E.tickHeist541(g,2400,H.finishHide536);assert.equal(s.progress,0);p.moving=false;E.tickHeist541(g,1000,H.finishHide536);assert.equal(s.progress,1000);p.x=100;E.tickHeist541(g,1000,H.finishHide536);assert.equal(s.progress,700);for(const s of g.heist541.seals){Object.assign(p,{x:s.x,y:s.y,moving:false});E.tickHeist541(g,2400,H.finishHide536);assert.equal(s.done,true)}assert.equal(g.phase,'play');Object.assign(p,g.heist541.exit);E.tickHeist541(g,50,H.finishHide536);assert.equal(g.reason,'escape');assert.equal(g.winnerIds.length,3)});
test('waiting for timeout now wins for hunter',()=>{const g=hide();g.elapsed=179950;g.lastAt=g.startAt+g.elapsed;H.advanceHide536(g,g.endAt);assert.equal(g.reason,'locked');assert.equal(g.winningSide,'hunter')});
test('decoy preserves an ordinary target and swaps identity; cooldown prevents spam',()=>{const g=hide(),h=g.players[0],p=g.players[1];Object.assign(h,{x:p.x,y:p.y});const old=p.objectId,kind=p.kind,stamina=p.stamina;assert.equal(E.ability541(g,p,()=> 'new-id'),true);assert.notEqual(p.kind,kind);assert.equal(p.stamina,stamina);assert.equal(E.ability541(g,p,()=> 'other'),false);const view=H.publicHide536(g,h.playerId);assert.equal(view.players[1].x,undefined);assert.equal(view.players[1].objectId,undefined);assert.ok(view.objects.some(o=>o.id===old&&!o.owner));assert.equal(H.attackHide536(g,h,old),true);assert.equal(p.alive,true);assert.equal(g.shots,2)});
test('sense is private and only exposes a distance band; seal progress stays private',()=>{const g=hide(),h=g.players[0];E.ability541(g,h,()=> 'x');const a=H.publicHide536(g,'p0'),b=H.publicHide536(g,'p1');assert.deepEqual(Object.keys(a.players[0].sense541).sort(),['level','until']);assert.equal(b.players[0].sense541,undefined);assert.equal(a.heist541.seals[0].progress,undefined);assert.equal(b.heist541.seals[0].progress,0)});
test('rescue succeeds once per hider; nearby hunter blocks rescue',()=>{const g=hide(),p=g.players[1],helper=g.players[2],h=g.players[0];p.alive=false;Object.assign(helper,g.heist541.cage,{moving:false});Object.assign(h,g.heist541.cage);E.tickHeist541(g,2800,H.finishHide536);assert.equal(p.alive,false);Object.assign(h,{x:3000,y:1000});E.tickHeist541(g,2800,H.finishHide536);assert.equal(p.alive,true);assert.equal(p.rescued541,true);p.alive=false;E.tickHeist541(g,3000,H.finishHide536);assert.equal(p.alive,false)});
test('stroke validates length, bounds and finite points before consuming sequence',()=>{const g=canal(),p=g.players[0];for(const path of [[],[{x:NaN,y:.5}],[{x:1.1,y:0}],Array(33).fill({x:.5,y:.5}),[{x:0,y:0},{x:1,y:1},{x:0,y:0}]]){assert.equal(validStroke541(path),false);assert.equal(stroke(g,p,path),false);assert.equal(p.lastSeq,0)}});
test('stroke hits only crossed enemies, caps at six, and shares cooldown',()=>{const g=canal(),p=g.players[0];for(let i=0;i<8;i++)enemy(g,{id:i+1,x:.2+i*.04});const away=enemy(g,{id:9,x:.95});const path=[{x:.17,y:.4},{x:.55,y:.4}];assert.equal(stroke(g,p,path),true);assert.equal(g.captured,6);assert.ok(g.enemies.includes(away));stroke(g,p,path,g.startAt+100);assert.equal(g.captured,6);stroke(g,p,path,g.startAt+320);assert.equal(g.captured,8);assert.equal(p.bestSweep541,6)});
test('eight consecutive catches trigger eight-second fever; subsequent catch doubles score',()=>{const g=canal(),p=g.players[0];for(let i=0;i<8;i++){const at=g.startAt+i*350,e=enemy(g,{id:i+1});stroke(g,p,[route500(e,C.progress500(e,at))],at)}assert.equal(g.combo541,8);assert.equal(g.fever541Until,g.startAt+7*350+8000);const e=enemy(g,{id:9,hp:2}),at=g.startAt+2800;stroke(g,p,[route500(e,C.progress500(e,at))],at);assert.equal(g.captured,9);assert.equal(g.points,100)});
test('two contributors BREAK boss, extend snare and increase following damage',()=>{const g=canal(),e=enemy(g,{kind:3,hp:20}),at=g.startAt;C.sweep500(g,g.players[0],0,at,false,e.id);C.sweep500(g,g.players[1],0,at+100,false,e.id);assert.equal(e.hp,17);assert.equal(e.breakUntil541,at+3600);assert.equal(e.slowUntil,at+3600);C.sweep500(g,g.players[0],0,at+350,false,e.id);assert.equal(e.hp,14);assert.equal(e.slowUntil,at+3600)});
test('rally accepts each seat once; four-player net clears enemies and heals',()=>{const g=canal();g.netEnergy=32;g.hp=50;enemy(g,{hp:8});for(const p of g.players)assert.equal(C.sweep500(g,p,0,g.startAt,true),true);assert.equal(C.sweep500(g,g.players[0],0,g.startAt,true),false);C.advance500(g,g.startAt+100);assert.equal(g.megaCount,1);assert.equal(g.captured,1);assert.equal(g.hp,58);assert.equal(g.rally541,null)});
test('solo rally fires at deadline without forcing absent humans to join',()=>{const g=canal();g.netEnergy=32;const e=enemy(g,{hp:8});C.sweep500(g,g.players[0],0,g.startAt,true);C.advance500(g,g.startAt+1800);assert.equal(e.hp,5);assert.equal(g.megaCount,1);assert.equal(g.events.find(e=>e.kind==='mega').strength541,1)});
test('AI joins rally and saved-round continuation is deterministic',()=>{const g=canal();g.players.slice(1).forEach(p=>p.ai=true);g.netEnergy=32;C.sweep500(g,g.players[0],0,g.startAt,true);const loaded=JSON.parse(JSON.stringify(g));C.advance500(g,g.startAt+1500);C.advance500(loaded,loaded.startAt+1500);assert.deepEqual(g,loaded);assert.equal(g.events.find(e=>e.kind==='mega').strength541,4)});
import {line537,free537} from '../src/hide/Map537.js';
test('continuous furniture collision rejects corner cuts missed by sampled paths',()=>{const m={width:400,height:400,cells:Array(16).fill(5),decor:[{x:205,y:195,w:2,h:2}]},a={x:100,y:300},b={x:300,y:100};assert.equal(free537(m,a.x,a.y,0),true);assert.equal(free537(m,b.x,b.y,0),true);assert.equal(line537(m,a,b,0),false)});
test('hide AI navigates furniture, opens seals and reaches escape instead of corner-stalling',()=>{const g=H.makeHide536({id:'ai',code:'A',hostId:'p0',members:[members[0]]});g.role='hunter';H.startHide536(g,0,540);g.players.forEach(p=>p.ai=true);for(let at=50;at<=200000&&g.phase!=='result';at+=50)H.advanceHide536(g,at);assert.equal(g.winningSide,'hiders');assert.equal(g.reason,'escape');assert.equal(g.heist541.seals.filter(s=>s.done).length,3)});
import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';import {liveHide536,queueHide536} from '../online-server/src/HideCoordinator536.js';import {liveTetra539,queueTetra539} from '../online-server/src/TetraCoordinator539.js';import {queueCanal489} from '../online-server/src/CanalCoordinator489.js';
const versions={tetraVersion539:3,hideVersion536:5,canalVersion489:1,canalRules492:1,canalRules494:1,canalRules496:1,canalRules500:1,canalRules541:1};
function room(kind){let now=0;const messages=[],sessions=new Map(members.map(m=>[m.playerId,{playerId:m.playerId,clientKey:m.playerId,connected:true}])),c=new RaceCoordinator451({sessions,now:()=>now,send:(id,m)=>messages.push({id,...m})}),call=(id,op,p={})=>c.handle(sessions.get(id),{op,...versions,roster:[{id:'m',speciesId:'slime'}],...p});call('p0','partyCreate462',{game:kind});const party=partyFor462(c,'p0');for(let i=1;i<4;i++)call('p'+i,'partyJoin462',{code:party.code});const saved=partyRace462(c,party),op={tetra:'tetra539',hide:'hide536',canal:'canal489'}[kind];if(kind==='hide')call('p0',op,{gameId:saved.id,kind:'role',role:'hunter'});for(const m of members){call(m.playerId,op,{gameId:saved.id,kind:'select',monsterId:'m'});call(m.playerId,'partyReady462',{ready:true})}return{c,sessions,call,party,saved,op,messages,time(t){now=t;c.advance()}}}
test('coordinator rejects old tetra protocol and applies current input to authenticated seat',()=>{const r=room('tetra');r.call('p0',r.op,{gameId:r.saved.id,kind:'start',tetraVersion539:2});assert.equal(r.saved.phase,'lobby');r.call('p0',r.op,{gameId:r.saved.id,kind:'start'});r.time(4000);const g=liveTetra539(r.c,r.saved),m={gameId:g.id,tetraVersion539:3,seq:1,action:'begin',angle:-1.5,power:.5};assert.equal(queueTetra539(r.c,r.sessions.get('p0'),{...m,tetraVersion539:2}),false);assert.equal(queueTetra539(r.c,r.sessions.get('p0'),{...m,playerId:'p1'}),true);assert.equal(queueTetra539(r.c,r.sessions.get('p0'),m),false);queueTetra539(r.c,r.sessions.get('p0'),{...m,action:'release',seq:2});r.time(4050);assert.ok(g.players[0].flight);assert.equal(g.players[1].flight,null)});
test('hide ability and steering share input; old protocol cannot move new match',()=>{const r=room('hide');r.call('p0',r.op,{gameId:r.saved.id,kind:'start'});r.time(10000);r.time(20000);const g=liveHide536(r.c,r.saved),p=g.players[1],old=p.objectId,m={gameId:g.id,hideVersion536:5,kind:'input',seq:1,ability541:true,steer:{x:1,y:0}};assert.equal(queueHide536(r.c,r.sessions.get('p1'),{...m,hideVersion536:4}),false);assert.equal(queueHide536(r.c,r.sessions.get('p1'),m),true);r.time(20050);assert.notEqual(p.objectId,old);assert.equal(p.abilityReady541,18050);assert.equal(H.publicHide536(g,'p0').players[1].x,undefined)});
test('canal wire validates stroke, deduplicates sequence and uses authenticated contributor',()=>{const r=room('canal');r.call('p0',r.op,{gameId:r.saved.id,kind:'start'});r.time(5000);const g=partyRace462(r.c,r.party),p=g.players[1];assert.equal(g.rules541,1);g.enemies=[];const e=enemy(g,{id:100,x:.5}),q=route500(e,C.progress500(e,5000)),input={seq:1,lane:0,held:false,pulse:false,burst:false,stroke541:[q]};queueCanal489(r.c,r.sessions.get('p1'),{...versions,gameId:g.id,inputs:[input,input],playerId:'p0'});assert.equal(r.c.canalQueue489.get(g.id+':p1').length,1);r.time(5300);const saved=partyRace462(r.c,r.party);assert.equal(saved.players[1].bestSweep541,1);assert.equal(saved.players[0].bestSweep541,0);queueCanal489(r.c,r.sessions.get('p1'),{...versions,canalRules541:0,gameId:g.id,inputs:[{...input,seq:2}]});assert.equal(r.c.canalQueue489.get(g.id+':p1')?.length??0,0)});
