import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {TETRA539 as C,makeTetra539,startTetra539,advanceTetra539,inputTetra539,course539,pad539,pose539,wave539,jumpDistance539,landing539,fall539,finishTetra539,publicTetra539} from '../src/tetra/Rules539.js';
import {RaceCoordinator451} from '../online-server/src/RaceCoordinator451.js';
import {partyFor462,partyRace462} from '../online-server/src/PartyCoordinator462.js';
import {liveTetra539,queueTetra539} from '../online-server/src/TetraCoordinator539.js';
const member=(i=0)=>({playerId:'p'+i,name:'player'+i,color499:['blue','green','pink','orange'][i],owned:[{id:'m'+i,speciesId:'slime'}],choice:{id:'m'+i,speciesId:'slime'}});
function game(seed=539){const g=makeTetra539({id:'test',code:'CODE',partyId:'party',hostId:'p0',members:Array.from({length:4},(_,i)=>member(i)),now:0});startTetra539(g,0,seed);advance(g,4000);return g}
function advance(g,ms,inputs=new Map(),auto=new Set()){const end=g.lastAt+ms;while(g.lastAt<end&&g.phase!=='result')advanceTetra539(g,Math.min(end,g.lastAt+50),inputs,auto);}
function place(g,p,pad){Object.assign(p,{x:pad.x,y:pad.y,padId:pad.id,ox:0,oy:0,flight:null,fallAt:null,chargeAt:null,landedAt:g.elapsed});}
function jumpTo(g,p,pad){const a=pose539(g,p),d=Math.hypot(pad.x-a.x,pad.y-a.y),angle=Math.atan2(pad.y-a.y,pad.x-a.x),hold=(d-C.minJump)/(C.maxJump-C.minJump)*C.charge;assert.ok(d<=C.maxJump);inputTetra539(g,p,{action:'begin',angle});advance(g,Math.round(hold/50)*50);inputTetra539(g,p,{action:'release',angle});advance(g,950)}
test('100 seeded courses have reachable safe and shortcut routes with two checkpoints',()=>{for(let seed=1;seed<=100;seed++){const c=course539(seed);assert.deepEqual(c,course539(seed));assert.equal(c.pads.length,37);assert.equal(c.checkpoints.length,4);for(const route of [...c.safeRoutes,...c.shortRoutes])for(let i=1;i<route.length;i++){const a=c.pads[route[i-1]],b=c.pads[route[i]],d=Math.hypot(b.x-a.x,b.y-a.y);assert.ok(d<C.maxJump-40);assert.ok(d>C.minJump)}for(const route of c.safeRoutes)for(const id of route)assert.equal(c.pads[id].low,false)}assert.notDeepEqual(course539(1),course539(2));});
test('charge is bounded; short taps cancel; release starts a single ballistic flight',()=>{const g=game(),p=g.players[0];assert.equal(jumpDistance539(-1),C.minJump);assert.equal(jumpDistance539(1e9),C.maxJump);assert.equal(inputTetra539(g,p,{action:'release',angle:0}),false);inputTetra539(g,p,{action:'begin',angle:0});assert.equal(inputTetra539(g,p,{action:'release',angle:0}),false);assert.equal(p.jumps,0);inputTetra539(g,p,{action:'begin',angle:0});advance(g,1500);assert.equal(inputTetra539(g,p,{action:'release',angle:0}),true);assert.equal(p.flight.distance,C.maxJump);assert.equal(inputTetra539(g,p,{action:'release',angle:0}),false);advance(g,950);assert.equal(p.falls,1);advance(g,1600);assert.equal(p.padId,g.course.checkpoints[0]);assert.equal(p.fallAt,null);});
test('a player can actually charge and jump the complete safe course with checkpoint recovery',()=>{const g=game(),p=g.players[0];for(let section=0;section<3;section++){for(const id of g.course.safeRoutes[section].slice(1)){jumpTo(g,p,g.course.pads[id]);assert.equal(p.padId,id,'landed on intended pad');assert.equal(p.falls,section===0?0:1)}assert.equal(p.checkpoint,section+1);if(section===0){fall539(g,p);advance(g,C.respawn);assert.equal(p.padId,g.course.checkpoints[1]);assert.equal(p.checkpoint,1)}}assert.notEqual(p.finishedAt,null);assert.equal(g.firstFinish,p.finishedAt);assert.equal(g.endAt,g.startAt+p.finishedAt+C.grace);advance(g,C.grace);assert.equal(g.phase,'result');assert.equal(g.results[0].playerId,p.playerId);});
test('waves warn for 3sec and submerge only low pads for 3.2sec every16sec',()=>{assert.equal(wave539(0).active,false);assert.equal(wave539(12999).warning,false);assert.equal(wave539(13000).warning,true);assert.equal(wave539(16000).active,true);assert.equal(wave539(19199).active,true);assert.equal(wave539(19200).active,false);const g=game(),low=g.course.pads.find(p=>p.low),high=g.course.pads.find(p=>p.kind==='stable');assert.equal(pad539(g,low,16000).submerged,true);assert.equal(pad539(g,high,16000).submerged,false);g.elapsed=16000;assert.equal(landing539(g,low.x,low.y),null);place(g,g.players[0],low);g.lastAt=g.startAt+15950;advance(g,50);assert.equal(g.players[0].falls,1);});
test('tilting slides the player off; spinning moves the pad; sinking resets after4.8sec',()=>{const g=game(),p=g.players[0],tilt=g.course.pads.find(p=>p.kind==='tilt'),spin=g.course.pads.find(p=>p.kind==='spin'),sink=g.course.pads.find(p=>p.kind==='sink');place(g,p,tilt);g.padStates[tilt.id]={tiltAt:0,direction:1};advance(g,2300);assert.equal(p.falls,1);g.padStates[spin.id]={spinAt:0};assert.notEqual(pad539(g,spin,1000).x,spin.x);g.padStates[sink.id]={sinkAt:0};assert.equal(pad539(g,sink,2199).submerged,false);assert.equal(pad539(g,sink,2200).submerged,true);assert.equal(pad539(g,sink,4800).submerged,false);});
test('midair wave dodge, missed goal without checkpoints and tie-safe results',()=>{const g=game(),p=g.players[0],low=g.course.pads.find(p=>p.low);place(g,p,low);g.elapsed=15800;g.lastAt=g.startAt+15800;inputTetra539(g,p,{action:'begin',angle:0});g.elapsed=15950;g.lastAt=g.startAt+15950;inputTetra539(g,p,{action:'release',angle:0});advance(g,50);assert.ok(p.flight);assert.equal(p.falls,0);place(g,p,g.course.pads[g.course.checkpoints[3]]);p.y+=160;p.oy+=160;jumpTo(g,p,g.course.pads[g.course.checkpoints[3]]);assert.equal(p.finishedAt,null);assert.equal(p.checkpoint,0);g.players[0].finishedAt=50000;g.players[1].finishedAt=50000;finishTetra539(g);assert.deepEqual(g.results.slice(0,2).map(r=>r.rank),[1,1]);const saved=JSON.stringify(g.results);finishTetra539(g);assert.equal(JSON.stringify(g.results),saved);});
test('5 seeded AI races complete, serialize deterministically and use real jump physics',()=>{for(const seed of [1,42,539,777,999]){const g=game(seed);g.players.forEach(p=>p.ai=true);advance(g,17300);const clone=JSON.parse(JSON.stringify(g));advance(g,140000);advance(clone,140000);assert.equal(g.phase,'result');assert.deepEqual(g,clone);assert.ok(g.players.some(p=>p.finishedAt!=null));assert.ok(g.players.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.jumps>5));}});
function rig(humans=4,stateFile=null){let now=100000;const sent=[],sessions=new Map(Array.from({length:5},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{name:'p'+i}}]));let c=new RaceCoordinator451({stateFile,sessions,now:()=>now,send:(id,m)=>sent.push({id,...m})});const q=(i,op,extra={})=>{sent.length=0;c.handle(sessions.get('p'+i),{op,rulesVersion:8,tetraVersion539:1,roster:member(i).owned,...extra});return sent.find(x=>x.type==='raceError451')};q(0,'partyCreate462',{game:'tetra'});const party=()=>partyFor462(c,'p0'),g=()=>liveTetra539(c,partyRace462(c,party()));for(let i=1;i<humans;i++)q(i,'partyJoin462',{code:party().code});for(let i=0;i<humans;i++){q(i,'tetra539',{gameId:g().id,kind:'select',monsterId:'m'+i});q(i,'partyReady462',{ready:true})}const tick=ms=>{for(let n=0;n<ms;n+=50){now+=50;c.advanceTetra539()}};return{get c(){return c},sent,sessions,q,party,g,tick,start:()=>q(0,'tetra539',{gameId:g().id,kind:'start'}),restart:()=>{c=new RaceCoordinator451({stateFile,sessions,now:()=>now,send:(id,m)=>sent.push({id,...m})})}};}
test('coordinator enforces ready, version and host gates; handles private ack and invalid/replayed input',()=>{const r=rig();assert.ok(r.q(1,'tetra539',{gameId:r.g().id,kind:'start'}));r.q(2,'partyReady462',{ready:false});assert.ok(r.start());assert.ok(r.q(2,'partyReady462',{ready:true,tetraVersion539:0}));r.q(2,'partyReady462',{ready:true});assert.equal(r.start(),undefined);r.tick(4100);const g=r.g(),session=r.sessions.get('p0'),a={gameId:g.id,tetraVersion539:1,seq:1,action:'begin',angle:-Math.PI/2};for(const bad of [{...a,angle:NaN},{...a,angle:9},{...a,seq:-1},{...a,gameId:'bad'},{...a,tetraVersion539:0},{...a,action:'teleport'}])assert.equal(queueTetra539(r.c,session,bad),false);assert.equal(queueTetra539(r.c,session,a),true);assert.equal(queueTetra539(r.c,session,a),false);r.tick(650);assert.equal(queueTetra539(r.c,session,{...a,seq:2,action:'release',power:999999}),true);r.tick(50);assert.ok(g.players[0].flight.distance<C.maxJump);const view=publicTetra539(g,'p1');assert.equal(view.players[0].lastSeq,undefined);assert.equal(view.players[0].brain,undefined);assert.equal(view.players[1].lastSeq,0);assert.ok(r.sent.some(m=>m.type==='tetraFrame539'));assert.equal(r.c.view(session).room,null);assert.equal(r.c.active('p0'),true);});
test('disconnect/home takeover and reconnect cancel stale charges; restart resumes; replay/list are idempotent',()=>{const dir=mkdtempSync(join(tmpdir(),'tetra539-'));try{const r=rig(1,join(dir,'state.json'));r.start();r.tick(4100);const id=r.g().id;r.q(0,'tetraInput539',{gameId:id,action:'begin',seq:1,angle:0});r.tick(50);assert.notEqual(r.g().players[0].chargeAt,null);r.sessions.get('p0').connected=false;r.tick(100);assert.equal(r.g().players[0].auto,true);assert.equal(r.g().players[0].chargeAt,null);r.tick(2500);r.sessions.get('p0').connected=true;r.tick(100);assert.equal(r.g().players[0].auto,false);r.q(0,'partyPresence462',{atHome:true});r.tick(100);assert.equal(r.g().players[0].auto,true);r.q(0,'partyPresence462',{atHome:false});r.tick(2100);r.restart();assert.equal(r.g().id,id);r.tick(150000);assert.equal(r.g().phase,'result');const partyId=r.party().id;assert.equal(r.q(0,'partyResult490',{partyId,gameId:id,kind:'again'}),undefined);const next=r.g().id;assert.notEqual(next,id);assert.equal(r.g().phase,'lobby');r.q(0,'partyResult490',{partyId,gameId:id,kind:'again'});assert.equal(r.g().id,next);r.q(0,'partyReady462',{ready:true});r.start();r.tick(154100);assert.equal(r.g().phase,'result');const last=r.g().id;r.q(0,'partyResult490',{partyId,gameId:last,kind:'list'});assert.equal(r.g(),null);assert.equal(r.party().id,partyId);assert.equal(r.c.tetraRuntime539.size,0);}finally{rmSync(dir,{recursive:true,force:true})}});
