import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root=new URL('../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8'),main=read('src/main.js');
const block=(from,to)=>{const a=main.indexOf(from),b=main.indexOf(to,a);assert.ok(a>=0&&b>a);return main.slice(a,b)};
function equipment(){
 const c=vm.createContext({equipmentDisplayRarity:i=>i.rarity??'N'});
 for(const p of ['src/services/EquipmentProtection404.js','src/services/EquipmentEnhancement.js'])vm.runInContext(read(p).replace(/^import.*;\s*$/gm,'').replace(/^export /gm,''),c);
 const state={equipment:[{id:'base',name:'base',level:1},{id:'favorite',name:'f',favorite:true,locked:false,level:1},{id:'lock',name:'l',locked:true,level:1},{id:'worn',name:'w',favorite:true},{id:'permanent',name:'p',favorite:true,ruleOverrides:{unsellable:true}},{id:'owner',name:'o',equippedBy:'hero',favorite:true}],monsters:[{equipment:{weaponRight:'worn'}}]};
 return {c,state};
}
test('favorite-only gear is visible in protection filter after lock removal',()=>{const {c,state}=equipment();const entries=c.equipmentLockEntries404(state,{status:'protected',targetId:'base'});assert.ok(entries.some(i=>i.id==='favorite'));assert.equal(c.equipmentMaterialSummary404(state,'base').usable,0)});
test('explicit combined release makes eligible materials available, retaining equipped/permanent protection',()=>{const {c,state}=equipment();const r=c.applyEquipmentProtection404(state,state.equipment.map(i=>i.id),false,{clearFavorites:true,excludeId:'base',persist:()=>true});assert.equal(r.ok,true);assert.deepEqual(Array.from(c.enhancementMaterialCandidates(state,'base'),i=>i.id).sort(),['favorite','lock']);assert.equal(c.equipmentMaterialSummary404(state,'base').usable,2);assert.equal(state.equipment.length,6);assert.equal(state.equipment[4].ruleOverrides.unsellable,true);assert.equal(state.monsters[0].equipment.weaponRight,'worn')});
test('lock-only release keeps favorites; failed combined release restores exact flags',()=>{const {c,state}=equipment();c.applyEquipmentProtection404(state,['favorite','lock'],false);assert.equal(state.equipment[1].favorite,true);const before=JSON.stringify(state);assert.equal(c.applyEquipmentProtection404(state,['favorite','permanent'],false,{clearFavorites:true,persist:()=>false}).ok,false);assert.equal(JSON.stringify(state),before)});
test('released material can be consumed once; selected base and protected items survive',()=>{const {c,state}=equipment();c.applyEquipmentProtection404(state,['favorite'],false,{clearFavorites:true});assert.equal(c.consumeEquipmentMaterials(state,'base',['favorite']).ok,true);assert.equal(c.consumeEquipmentMaterials(state,'base',['favorite']).ok,false);for(const id of ['worn','permanent','owner','lock'])assert.equal(c.consumeEquipmentMaterials(state,'base',[id]).ok,false);assert.equal(state.equipment.find(i=>i.id==='base').exp,20)});
function battleFixture(){
 const a={id:'hero',speciesId:'hero',currentHp:50,currentMp:40},b={party:[a],enemies:[{id:'enemy',hp:100}],busy:false,auto:false,turn:1,queueIndex:0,actionCommitted:false};
 const forbidden=()=>{throw Error('action hook ran while opening menu')};let rendered=0;
 const c=vm.createContext({battle:b,save:{state:{settings:{autoBattle:false},inventory:{potions:2}}},actor:()=>a,currentTurnEntry:()=>({type:'ally',id:a.id}),sanitizeBattleParty(){},ultimateBasicOnly:()=>false,completeContextGuide(){},renderBattle(){rendered++},prepareBattleUltimates358:forbidden,runSingleNatural410:forbidden,beginUltimateAction:forbidden,reserveHeroAction:forbidden,hasCircleEffect:forbidden,finishCurrentAction:forbidden});
 vm.runInContext(block('async function command(','function chooseEnemyTarget('),c);
 return {a,b,c,rendered:()=>rendered};
}
for(const type of ['skill','item'])test(`${type} menu opens repeatedly without random-circle, hero quota or turn hooks`,async()=>{const {a,b,c,rendered}=battleFixture();for(let i=0;i<10;i++){await c.command(type);assert.equal(b[type+'Menu'],true);b[type+'Menu']=false;}assert.equal(rendered(),10);assert.equal(a.currentMp,40);assert.equal(a.currentHp,50);assert.equal(b.turn,1);assert.equal(b.queueIndex,0);assert.equal(b.actionCommitted,false);assert.equal(b.busy,false);assert.equal(c.save.state.inventory.potions,2)});
for(const flag of ['busy','auto','actionCommitted'])test(`picker rejects ${flag} battle state`,async()=>{const {b,c,rendered}=battleFixture();b[flag]=true;await c.command('skill');await c.command('item');assert.equal(rendered(),0)});
test('enemy turn and intro block menu; switching pickers closes the other one',async()=>{const {b,c,rendered}=battleFixture();c.currentTurnEntry=()=>({type:'enemy'});await c.command('item');assert.equal(rendered(),0);c.currentTurnEntry=()=>({type:'ally'});b.guideReady=false;await c.command('skill');assert.equal(rendered(),0);b.guideReady=true;await c.command('skill');await c.command('item');assert.equal(b.itemMenu,true);assert.equal(b.skillMenu,false)});
test('actual submitted skill and attack still enter action pipeline',async()=>{for(const [type,id] of [['skill','chosen'],['attack',null]]){const {c}=battleFixture();await assert.rejects(c.command(type,id),/action hook ran/)} });
function summonFixture(campaign='standard'){
 const timers=new Map();let seq=0,opened=0,saves=0,home=0;const el=()=>({hidden:false,disabled:false,classList:{add(){}},innerHTML:'',onclick:null,onkeydown:null});
 const next=el(),nodes=Object.fromEntries(['[data-gacha-results]','[data-gacha-premium]','.gacha-reveal-stage','[data-gacha-skip]','[data-modal-primary]','[data-modal-dismiss]'].map(k=>[k,el()]));nodes['[data-gacha-premium]'].querySelector=()=>next;
 const modal={isConnected:true,querySelector:q=>nodes[q],remove(){this.isConnected=false}};
 const results=[{type:'equipment',rarity:'SSR',name:'first',item:{id:'1'}},{type:'equipment',rarity:'LR',name:'second',item:{id:'2'}}];
 const state={player:{crystals:100},equipment:results.map(r=>r.item)};
 const c=vm.createContext({save:{state,save(){saves++}},markNewMonsterForGuide(){},app:{insertAdjacentHTML(){}},Modal:()=>'',document:{querySelectorAll:()=>[]},topModal:()=>modal,closeTopModal(){},RARITY_ORDER:{SSR:4,LR:6},rarityCssClass:s=>s,monsterVisual:()=>'',equipmentVisual:()=>'',pixelIcon:()=>'',audio:{sfx(){}},setTimeout(fn){timers.set(++seq,fn);return seq},clearTimeout:id=>timers.delete(id),openGacha(){opened++},openChapterTwoGacha397(){opened++},go(){home++},requestAnimationFrame:fn=>fn(),window:{scrollTo(){}}});
 vm.runInContext(block('function showSummonResults(','function openAchievementLedger('),c);c.showSummonResults(results,false,{campaign});
 return {c,nodes,next,modal,timers,state,counts:()=>({opened,saves,home}),tick(){const pending=[...timers.values()];timers.clear();pending.forEach(fn=>fn())}};
}
for(const selector of ['[data-modal-primary]','[data-modal-dismiss]'])for(const phase of ['intro','premium','transition','complete'])test(`summon ${selector} closes during ${phase} and preserves all rewards`,()=>{const f=summonFixture();if(phase!=='intro')f.tick();if(['transition','complete'].includes(phase))f.next.onclick();if(phase==='complete'){f.tick();f.next.onclick();f.tick();}const snapshot=JSON.stringify(f.state);assert.equal(f.nodes[selector].disabled,false);f.nodes[selector].onclick();assert.equal(f.modal.isConnected,false);assert.equal(f.timers.size,0);f.tick();f.nodes[selector].onclick();assert.equal(f.counts().opened,1);assert.equal(f.counts().saves,1);assert.equal(JSON.stringify(f.state),snapshot)});
for(const campaign of ['beginner','chapterTwo397'])test(`${campaign} early dismissal uses correct return destination`,()=>{const f=summonFixture(campaign);f.modal._onDismiss();assert.equal(f.counts().home,campaign==='beginner'?1:0);assert.equal(f.counts().opened,campaign==='beginner'?0:1);assert.equal(f.timers.size,0)});
test('boot cache retains operation modules and the current config target',()=>{const html=read('index.html'),map=JSON.parse(html.match(/<script type="importmap">([\s\S]*?)<\/script>/)[1]).imports;for(const p of ['src/core/config.js','src/services/EquipmentProtection404.js','src/ui/EquipmentLockManager404.js']){const version=p==='src/core/config.js'?'3.1.101-build422':'3.1.92-build412';assert.ok(map['./'+p].endsWith(version));for(const [k,v] of Object.entries(map))if(k.split('?')[0]==='./'+p)assert.ok(v.endsWith(version));}assert.match(html,/await import\(`\.\/src\/main.js\?v=\$\{CACHE_VERSION\}`\)/);assert.match(read('src/core/config.js'),/SAVE_SCHEMA_VERSION=84/)});
test('item selection commits one inventory item and hero action; duplicate taps and invalid targets consume nothing',async()=>{
 const {a,b,c}=battleFixture();let quota=0,turns=0,starts=0;b.itemMenu=true;b.itemTargetType='potions';b.itemTargetActorId=a.id;
 Object.assign(c,{prepareBattleUltimates358(){},ultimateIsolated:()=>false,runSingleNatural410:async()=>false,isHeroResonanceSpecies:()=>true,reserveHeroAction(){quota++;return true},beginUltimateAction(){starts++},calculatedStats:()=>({hp:100}),scaledRecovery:()=>10,recoverBattleHp(m,n){m.currentHp+=n;return n},recordBattleHealing(){},displayName:()=>'',addBattleLog(){},flushBattleRecoveries:async()=>{},saveBattleCheckpoint(){},wait:async()=>{},finishCurrentAction:async()=>{turns++}});
 vm.runInContext(block('async function useBattleItem(','function showBattleMonsterDetail('),c);
 await c.useBattleItem('potions','missing');assert.equal(quota,0);assert.equal(c.save.state.inventory.potions,2);
 await Promise.all([c.useBattleItem('potions',a.id),c.useBattleItem('potions',a.id)]);
 assert.equal(c.save.state.inventory.potions,1);assert.equal(a.currentHp,60);assert.equal(quota,1);assert.equal(starts,1);assert.equal(turns,1);
});
test('protection manager renders an explicit combined release and favorites filter',()=>{const {c,state}=equipment();Object.assign(c,{equipmentRarityColor:()=>'',equipmentVisual:()=>'',equipmentLockBadge404:()=>'',esc:String,EQUIPMENT_LOCK_ART404:''});vm.runInContext(read('src/ui/EquipmentLockManager404.js').replace(/^import.*;\s*$/gm,'').replace(/^export /gm,''),c);const html=c.equipmentLockManagerBody404(state,{status:'protected',slot:'all',rarity:'all',targetId:'base',selected:new Set(['favorite']),clearFavorites:false});assert.match(html,/data-lock-item404="favorite"/);assert.match(html,/data-lock-apply404="unlock" >ロック・お気に入りを解除/);assert.match(main,/clearFavorites:button.dataset.lockApply404==="unlock"/);});
