import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {run} from '../tools/build430/native-harness.mjs';
import {BattleScreen} from '../src/ui/screens/BattleScreen.js';
import {MOTHER_ENEMY422,tuneMother422,MOTHER_ID422} from '../src/primordial/Mother422.js';
import {motherShieldCapacity425,rememberMotherShield425} from '../src/primordial/Shield425.js';
import {motherArtScale425} from '../src/ui/BattleBossLayout.js';
import {motherPortraitStyle425,motherDialText425,motherDialIndex425,motherDialMotion425,motherDialExpansion425,playMotherDial425} from '../src/ui/MotherDial425.js';
import {motherLaw424} from '../src/primordial/Dial424.js';
const ids=['ch2_seria','ch2_carmia','ch2_rostia','ch2_althea'];
async function fixture(){const f=await run(ids,['slime'],{inspect:true,level:6000});const e=tuneMother422(f.context.makeBattleEnemy(MOTHER_ENEMY422));f.b.enemies=[e];f.b.enemy=e;f.b.specialBattleType='mother422';f.b.targetEnemyId=e.id;return {...f,e};}
function stage(){const values=new Map(),style={setProperty:(k,v)=>values.set(k,v),removeProperty:k=>values.delete(k)},wheel={style},result={textContent:''};const circle={style,dataset:{},querySelector:()=>wheel,getBoundingClientRect:()=>({left:220,top:250,width:150,height:150})};const arena={getBoundingClientRect:()=>({left:10,top:100,width:380,height:550})};return{values,circle,wheel,result,root:{querySelector:s=>s.includes('data-mother-unit')?circle:s==='.battle-arena'?arena:s==='.side-enemies'?null:result}};}
function clock(){let time=0,id=0,callback;const timers=[];return{now:()=>time,raf:fn=>{callback=fn;return ++id;},cancel:()=>callback=null,delay:ms=>new Promise(resolve=>timers.push({ms,resolve})),tick:ms=>{time+=ms;const fn=callback;callback=null;fn?.();},timers};}
const flush=async()=>{await Promise.resolve();await Promise.resolve();};
test('HP barrier reuses the shield meter, remembers capacity after absorption, and preserves zero',async()=>{const {b,e,context:c}=await fixture();e._floorBossHpShield=96000;rememberMotherShield425(e);e._floorBossHpShield=36000;const html=BattleScreen(b,{},c.save.state.settings);assert.match(html,/battle-shield-gauge mother-hp-shield425/);assert.match(html,/HP障壁 36,000\/96,000/);assert.match(html,/aria-valuemax="96000" aria-valuenow="36000"/);assert.doesNotMatch(html,/mother-shield423/);e._floorBossHpShield=0;assert.match(BattleScreen(b,{},c.save.state.settings),/HP障壁 0\/96,000/);e._floorBossHpShield=288000;rememberMotherShield425(e);assert.equal(motherShieldCapacity425(JSON.parse(JSON.stringify(e))),288000);});
test('native mother shield grants remember the full value before it can be consumed',async()=>{const {b,e,context:c}=await fixture();await c.resolveEnemySpecialAction(e,'ch2_ionea__veil');assert.ok(e._floorBossHpShield>0);assert.equal(e._floorBossHpShieldMax425,e._floorBossHpShield);const capacity=e._floorBossHpShieldMax425;e._floorBossHpShield=1;assert.equal(motherShieldCapacity425(e),capacity);const other={speciesId:'ten_life',_floorBossHpShield:999};const before=JSON.stringify(other);rememberMotherShield425(other);assert.equal(JSON.stringify(other),before);});
test('mother art seeks triple ordinary size, respecting width and card/status headroom',()=>{for(const viewport of [320,390,430,768]){const normal=Math.max(54,Math.min(88,viewport*.16)),slot=viewport*.46;const params={width:70,height:100,slotWidth:slot,headroom:360,normalSize:normal},scale=motherArtScale425(params);assert.ok(scale*100>=normal*2);assert.ok(scale*100<=normal*3+.001);assert.ok(scale*70<=slot-16+.001);}assert.ok(motherArtScale425({width:70,height:100,slotWidth:180,headroom:60,normalSize:62})*100<=60);});
test('challenge center uses visible atlas bounds and the battle supplies a dedicated solo mother target',async()=>{const {b,context:c}=await fixture();assert.match(motherPortraitStyle425(),/--mother-portrait-x425:50%/);const html=BattleScreen(b,{},c.save.state.settings);assert.equal((html.match(/data-mother-unit425/g)||[]).length,1);assert.equal((html.match(/class="mother-halo423/g)||[]).length,1);assert.doesNotMatch(html,/mother-dial-cue424/);});
test('upcoming result is absent until stopping, including a new round after checkpoint resume',()=>{const b={turn:3,motherDial424:{lastRound:2,index:0}};const law=motherLaw424(3);assert.doesNotMatch(motherDialText425(b),new RegExp(law.name));assert.equal(motherDialIndex425(b),0);b._motherDialPresentation425={round:3,index:law.index,phase:'spinning'};assert.equal(motherDialText425(b),'十律輪が回転中…');assert.equal(motherDialIndex425(b),0);b._motherDialPresentation425.phase='revealed';assert.ok(motherDialText425(b).includes(law.name));assert.equal(motherDialIndex425(b),law.index);b.motherDial424={lastRound:3,index:law.index};delete b._motherDialPresentation425;assert.ok(motherDialText425(b).includes('発動済み'));b.turn=4;assert.equal(motherDialText425(b),'十律輪 ／ ラウンド開始時に作動');});
test('all ten stops point to the selected numeral after multiple full revolutions',()=>{for(let previous=0;previous<10;previous++)for(let index=0;index<10;index++){const start=motherDialMotion425({index,previousIndex:previous,progress:0}),end=motherDialMotion425({index,previousIndex:previous,progress:1});assert.ok(end.angle-start.angle>=1080);assert.ok(Math.abs(((end.angle+index*36)%360+360)%360)<1e-8);}});
test('expanded dial stays inside the arena at narrow and wide viewports',()=>{for(const width of [300,360,750]){const arena={left:10,top:100,width,height:450},circle={left:width*.65,top:110,width:width*.32,height:width*.32},e=motherDialExpansion425(circle,arena),r=circle.width*e.scale/2,cx=circle.left+circle.width/2+e.dx,cy=circle.top+circle.height/2+e.dy;assert.ok(cx-r>=arena.left);assert.ok(cx+r<=arena.left+width);assert.ok(cy-r>=arena.top);assert.ok(cy+r<=arena.top+arena.height);}});
for(const speed of [1,2,4])test(`in-arena spin at x${speed} reveals only at stop, then releases the existing backdrop`,async()=>{const scene=stage(),t=clock(),phases=[],law=motherLaw424(3),p=playMotherDial425({getRoot:()=>scene.root,law,previousIndex:0,speed,onPhase:v=>phases.push(v),...t});const spin=t.timers.shift();t.tick(spin.ms*.6);assert.equal(scene.result.textContent,'十律輪が回転中…');assert.ok(Number(scene.values.get('--dial-grow425'))>1);assert.deepEqual(phases,['spinning']);t.tick(spin.ms*.4);spin.resolve();await flush();assert.deepEqual(phases,['spinning','revealed']);assert.ok(scene.result.textContent.includes(law.name));const hold=t.timers.shift();t.tick(hold.ms);hold.resolve();await flush();const shrink=t.timers.shift();t.tick(shrink.ms);shrink.resolve();await p;assert.equal(scene.circle.dataset.dialPhase425,undefined);assert.equal(scene.values.has('--dial-grow425'),false);assert.equal(scene.values.get('transform'),`rotate(${-law.index*36}deg)`);});
test('rerender during spin joins the same elapsed animation without a result preview',async()=>{let scene=stage();const first=scene,t=clock(),law=motherLaw424(4),p=playMotherDial425({getRoot:()=>scene.root,law,...t});const spin=t.timers.shift();t.tick(600);scene=stage();t.tick(300);assert.equal(scene.result.textContent,'十律輪が回転中…');assert.ok(scene.values.has('--dial-grow425'));spin.resolve();await flush();t.timers.shift().resolve();await flush();t.timers.shift().resolve();await p;assert.equal(first.values.has('--dial-grow425'),false);assert.equal(scene.values.has('--dial-grow425'),false);});
test('reduced motion does not rotate before reveal; interrupted battles clean up without revealing',async()=>{for(const interrupted of [false,true]){const scene=stage(),t=clock(),phases=[];let valid=true;const p=playMotherDial425({getRoot:()=>scene.root,law:motherLaw424(4),previousIndex:0,reducedMotion:true,isCurrent:()=>valid,onPhase:x=>phases.push(x),...t});const spin=t.timers.shift();t.tick(60);assert.equal(scene.values.get('transform'),'rotate(0deg)');if(interrupted)valid=false;spin.resolve();await flush();if(!interrupted)t.timers.shift().resolve();await p;assert.equal(scene.values.has('--dial-grow425'),false);assert.deepEqual(phases,interrupted?['spinning']:['spinning','revealed']);}});
