import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks,createRequire} from 'node:module';
import {existsSync,mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {makeLuck509,startLuck509,chooseLuck509,advanceLuck509,publicLuck509,drawPlan509,resolveRound509,aiPick509,ITEMS509,LUCK509,metres509,ranks509} from '../src/luck/Rules509.js';
import {makeLuck507,startLuck507,drawPlan507} from '../src/luck/Rules507.js';
import {raceFrame509,broadcastFrame509,paintKey509,distance509,fullDistance509,formula509} from '../src/luck/Presentation509.js';
const fixtures={
 [new URL('../src/ui/MonsterVisual.js',import.meta.url).href]:`export const monsterVisual=()=>'<i class="test-sprite"></i>';export const setMonsterVisualFrame=()=>{};`,
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,c,next){const url=spec.startsWith('.')?new URL(spec,c.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,c)},load(url,c,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,c)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');
const {luckView509,luckAfter509,luckBefore509,luckTick509,paintLuck509,requestLuck509,luckReceive509,luckClick509}=await import('../src/luck/View509.js');
const {raceDomSignature452}=await import('../src/race/RacePresentation452.js');
const {gorillaView502}=await import('../src/gorilla/View502.js');
hook.deregister();
const plan=()=>drawPlan509(n=>n-1);
function game(n=4){const g=makeLuck509({id:'luck-test',code:'ABC123',partyId:'party',hostId:'p0',members:Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'P'+i,color499:['orange','pink','green','blue'][i],owned:[{id:'m'+i,speciesId:'wolf'}],choice:{id:'m'+i,speciesId:'wolf'}}))});startLuck509(g,1000,plan());return g}
const begin=g=>{advanceLuck509(g,g.nextAt);return g.phaseAt};
function chooseAll(g,kind,order=[0,1,2,3]){for(const seat of order){const p=g.players[seat];if(!p.ai)chooseLuck509(g,p.playerId,kind,0,g.round,g.phaseAt+10)}advanceLuck509(g,g.nextAt);return g}
function readyItems(ids=['dash','rocket','shield','engine'],dist=[0,0,0,0]){const g=game();g.players.forEach((p,i)=>p.distance=dist[i]);g.plan509[0].seats.forEach((d,i)=>d.boxes[0]=[ids[i],...ITEMS509.filter(x=>x.id!==ids[i]).slice(0,3).map(x=>x.id)]);begin(g);chooseAll(g,'chest');chooseAll(g,'hand');assert.equal(g.phase,'reveal');return g}
function context(g,self='p0'){return{state:{luck:publicLuck509(g,self),party:{id:'party',hostId:'p0',members:g.members.map(m=>({...m,connected:true})),game:'luck',phase:g.phase},available:true,serverNow:g.phaseAt,partyResultActions490:1},transport:{selfId:self},offset:g.phaseAt-Date.now(),sgMonster463:()=>'<span class="sg-monster"><i></i></span>',sgSpeciesName463:id=>id,ready:()=>true,connected:()=>true,roster:()=>[{id:'m0',speciesId:'wolf'}],bank:()=>null,save:{state:{player:{gold:1000,crystals:0},settings:{audioEnabled:false},monsters:[]}},root:{querySelector:()=>null},draft:{code:'ABC123'},render(){},lkUI509:{gameId:g.id,artReady:true,sound:false}}}
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,luckVersion507:1,luckVersion508:1,luckVersion509:1,gorillaVersion502:1,gorillaRules503:1,gorillaRules504:1,gorillaRules505:1,...extra});return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function start(x,n=x.sessions.size){assert.deepEqual(x.send(0,'partyCreate462',{game:'luck',roster:[{id:'m0',speciesId:'wolf'}]}),[]);const party=Object.values(x.c.data.parties462)[0],get=()=>x.c.data.luckRooms507[party.code];for(let i=1;i<n;i++){assert.deepEqual(x.send(i,'partyJoin462',{code:party.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);assert.deepEqual(x.send(i,'luck509',{gameId:get().id,kind:'select',monsterId:'m'+i}),[])}for(let i=0;i<n;i++)assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[]);assert.deepEqual(x.send(0,'luck509',{gameId:get().id,kind:'start'}),[]);return{party,get}}

function dom(g=game()){
 let mutations=0,serial=0;const queue=new Map(),listeners=new Map(),saved={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};
 function el(){const values={},attrs={},children=new Map();return{clientHeight:350,clientWidth:393,dataset:new Proxy({},{set(t,k,v){mutations++;t[k]=v;return true}}),style:new Proxy({setProperty(k,v){this[k]=v},getPropertyValue(k){return this[k]??''},getPropertyPriority(){return''}},{set(t,k,v){mutations++;t[k]=v;return true}}),classList:{contains:s=>s==='lk-play508'},getAttribute:k=>attrs[k]??null,setAttribute(k,v){mutations++;attrs[k]=v},addEventListener(){},removeEventListener(){},contains:()=>false,querySelector(q){if(!children.has(q))children.set(q,el());return children.get(q)},querySelectorAll:()=>[],get textContent(){return values.textContent},set textContent(v){mutations++;values.textContent=v},get disabled(){return values.disabled},set disabled(v){mutations++;values.disabled=v},get hidden(){return values.hidden},set hidden(v){mutations++;values.hidden=v}}}
 const root=el(),groups={'[data-power-row509]':4,'[data-gear-slot509]':28,'[data-volley509] .lk-art508':9,'[data-chest509]':4,'[data-hand-pick509]':4,'[data-dot509]':8,'[data-mark509]':7,'[data-reveals509] .lk-art508':4};for(const[k,v]of Object.entries(groups))groups[k]=Array.from({length:v},el);root.querySelectorAll=q=>groups[q]??[];
 globalThis.document={visibilityState:'visible',querySelector:()=>null,addEventListener:(n,fn)=>listeners.set(n,fn),removeEventListener:n=>listeners.delete(n)};globalThis.requestAnimationFrame=fn=>{const id=++serial;queue.set(id,fn);return id};globalThis.cancelAnimationFrame=id=>queue.delete(id);
 if(g.phase==='countdown')begin(g);const c=context(g);c.root={querySelector:()=>root};c.offset=g.phaseAt-Date.now();c.raw=()=>true;
 return{g,c,root,groups,queue,listeners,mutations:()=>mutations,reset:()=>mutations=0,flush(){const jobs=[...queue.values()];queue.clear();for(const f of jobs)f()},restore(){luckBefore509(c);for(const[k,v]of Object.entries(saved)){if(v===undefined)delete globalThis[k];else globalThis[k]=v}}}
}
function nextRound(g){while(!['chest','result'].includes(g.phase))advanceLuck509(g,g.nextAt);return g}
function playRound(g,ids){if(g.phase!=='chest')nextRound(g);g.plan509[g.round-1].seats.forEach((d,i)=>d.boxes[0]=[ids[i],...ITEMS509.filter(x=>x.id!==ids[i]).slice(0,3).map(x=>x.id)]);chooseAll(g,'chest');chooseAll(g,'hand');return g.event}
const equip=(g,seat,ids,round=1)=>g.players[seat].loadout=ids.map(id=>({id,round}));
const row=(g,seat=0)=>g.event.rows[seat];
test('28 items include 20 permanent, stackable pieces; 128 chests uniformly draw all 28 and seal both dice',()=>{assert.equal(ITEMS509.length,28);assert.equal(ITEMS509.filter(x=>x.persistent).length,20);let seed=71;const p=drawPlan509(n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n});assert.equal(new Set(p.flatMap(r=>r.seats.flatMap(s=>s.boxes.flat()))).size,28);for(const r of p){assert.equal(new Set(r.order).size,4);for(const s of r.seats){assert.ok(s.dice.every(x=>x>=1&&x<=6));assert.ok(s.jackpot>=1&&s.jackpot<=6);for(const b of s.boxes)assert.equal(new Set(b).size,4)}}});
test('invalid dice fail before mutating the lobby',()=>{const g=game();g.phase='lobby';const p=plan();p[0].seats[0].dice=[7,1];const before=structuredClone(g);assert.throws(()=>startLuck509(g,0,p));assert.deepEqual(g,before)});
test('persistent movement keeps firing on subsequent picks and duplicates add together',()=>{const g=game();playRound(g,['dash','dash','dash','dash']);assert.equal(row(g).gain,220);nextRound(g);playRound(g,['dash','dash','dash','dash']);assert.equal(row(g).gain,440);nextRound(g);playRound(g,['rocket','rocket','rocket','rocket']);assert.equal(row(g).gain,940);assert.equal(row(g).loadout.length,2)});
test('36 products all compute die 1 × die 2 × 100; extrema are 100 and 3600',()=>{for(let a=1;a<=6;a++)for(let b=1;b<=6;b++){const g=game();g.plan509[0].seats[0].dice=[a,b];playRound(g,['product','dash','dash','dash']);assert.equal(row(g).gain,a*b*100);assert.deepEqual(row(g).calculation.dice,[a,b])}});
test('product, turbines, coils and permanent chargers multiply with no hidden small cap',()=>{const g=game();g.round=4;equip(g,0,['turbine','turbine','battery']);g.players[0].coils=2;playRound(g,['product','dash','dash','dash']);assert.equal(row(g).gain,(3600+100)*2.25*4*2);assert.equal(row(g).coils,0);assert.match(formula509(row(g).calculation),/6 × 6 × 100/)});
test('seed doubles each later turn; periodic rockets arrive every second turn and keep repeating',()=>{const g=game();playRound(g,['seed','bond','dash','dash']);assert.equal(row(g).gain,0);nextRound(g);playRound(g,['rocket','rocket','dash','dash']);assert.equal(row(g).calculation.seed,100);assert.equal(row(g,1).calculation.bond,0);nextRound(g);playRound(g,['rocket','rocket','dash','dash']);assert.equal(row(g).calculation.seed,200);assert.equal(row(g,1).calculation.bond,2400);nextRound(g);playRound(g,['rocket','rocket','dash','dash']);assert.equal(row(g,1).calculation.bond,0);nextRound(g);playRound(g,['rocket','rocket','dash','dash']);assert.equal(row(g,1).calculation.bond,2400)});
test('coil factories produce next turn; banking persists and the next big move consumes all coils',()=>{const g=game();playRound(g,['coil','dash','dash','dash']);assert.equal(row(g).coils,0);nextRound(g);playRound(g,['coil','dash','dash','dash']);assert.equal(row(g).coils,1);nextRound(g);playRound(g,['engine','dash','dash','dash']);assert.equal(row(g).coils,3);nextRound(g);playRound(g,['product','dash','dash','dash']);assert.equal(row(g).calculation.coils,5);assert.equal(row(g).gain,3700*32);assert.equal(row(g).coils,0)});
test('permanent attacks fire together in one bounded broadcast per source every turn',()=>{const g=game();g.round=5;equip(g,0,['shell','lightning','banana','pit','magnet','breaker','sniper','wrench']);g.players[1].distance=5000;playRound(g,['rocket','mega','dash','dash']);assert.equal(g.event.attacks.length,1);assert.equal(g.event.attacks[0].volleys.length,8);assert.equal(g.event.castMs,3200);assert.ok(row(g,1).hit);nextRound(g);playRound(g,['rocket','rocket','rocket','rocket']);assert.equal(g.event.attacks[0].volleys.length,8)});
test('guards refresh every turn, stack by count, and one guard does not block a whole volley',()=>{const g=game();g.round=3;g.players[1].distance=1000;equip(g,0,['shell','lightning']);equip(g,1,['shield']);playRound(g,['rocket','rocket','dash','dash']);const v=g.event.attacks[0].volleys;assert.equal(v[0].targets[0].outcome,'blocked');assert.equal(v[1].targets.find(h=>h.target===1).outcome,'hit');nextRound(g);playRound(g,['rocket','shield','dash','dash']);assert.equal(g.event.attacks[0].volleys[1].targets.find(h=>h.target===1).outcome,'blocked')});
test('spring immunity, limited reflections and persistent wards resolve without reflection loops',()=>{const g=game();g.round=3;g.players.map((p,i)=>p.distance=i*1000);equip(g,0,['banana','shell','lightning']);equip(g,1,['spring']);equip(g,2,['ward']);equip(g,3,['mirror']);playRound(g,['rocket','rocket','rocket','rocket']);const a=g.event.attacks[0];assert.equal(a.volleys.find(x=>x.item==='banana').targets[0].outcome,'blocked');assert.equal(a.volleys.find(x=>x.item==='shell').targets[0].outcome,'reflected');assert.equal(row(g,2).wards,0);assert.ok(JSON.stringify(g.event).length<20000)});
test('revenge equipment converts successful hits into future coils; blocked hits give none',()=>{const g=game();g.round=3;g.players[1].distance=1000;equip(g,0,['shell','lightning']);equip(g,1,['revenge','revenge','shield']);playRound(g,['rocket','rocket','dash','dash']);assert.equal(row(g,1).coils,2);assert.equal(row(g,1).calculation.coils,0)});
test('mega boost fizzles on a hit, while shielding lets it survive',()=>{for(const defended of [false,true]){const g=game();g.players[1].distance=1000;if(defended)equip(g,1,['shield'],0);playRound(g,['shell','mega','dash','dash']);assert.equal(row(g,1).gain,defended?6160:0)}});
test('jackpot is sealed 1 in 6; miss still receives passive income and consumes loaded coils',()=>{for(let roll=1;roll<=6;roll++){const g=game();equip(g,0,['engine'],0);g.players[0].coils=1;g.plan509[0].seats[0].jackpot=roll;playRound(g,['jackpot','dash','dash','dash']);assert.equal(row(g).gain,(roll===6?20100:100)*2);assert.equal(row(g).coils,0)}});
test('sniper reads planned speed, not secret choices, and zeros the fastest qualifying opponent',()=>{const g=game();playRound(g,['sniper','mega','product','dash']);assert.equal(g.event.attacks[0].targets[0].target,1);assert.equal(row(g,1).gain,0);assert.equal(row(g,2).gain,3600);const miss=readyItems(['sniper','dash','dash','dash']);assert.equal(miss.event.attacks[0].targets.length,0)});
test('breaker removes 30% per stacked copy of initial cumulative metres with exact rounding',()=>{const g=game();g.round=3;g.players[1].distance=10001;equip(g,0,['breaker']);playRound(g,['breaker','rocket','dash','dash']);assert.equal(row(g,1).knockback,5101);assert.equal(row(g,1).to,5400)});
test('wrench transfers existing gear for next round, conserves pieces and respects guards',()=>{const g=game();g.round=3;equip(g,1,['turbine','engine']);playRound(g,['wrench','rocket','dash','dash']);assert.ok(row(g).loadout.some(x=>x.id==='turbine'));assert.equal(row(g).calculation.turbines,0);assert.equal(row(g,1).calculation.turbines,1);assert.ok(!row(g,1).loadout.some(x=>x.id==='turbine'));const total=g.event.rows.reduce((n,r)=>n+r.loadout.length,0);assert.equal(total,5);nextRound(g);playRound(g,['rocket','rocket','rocket','rocket']);assert.equal(row(g).calculation.turbines,1)});
test('huge exact distances survive JSON, ranking distinguishes adjacent integers above 2^53',()=>{const g=game();g.players[0].coils=80;playRound(g,['product','dash','dash','dash']);const wanted=3600n*2n**80n;assert.equal(row(g).to,wanted.toString());assert.deepEqual(JSON.parse(JSON.stringify(g.event)),g.event);assert.equal(ranks509([{playerId:'a',distance:wanted.toString()},{playerId:'b',distance:(wanted+1n).toString()}])[0].playerId,'b');assert.equal(fullDistance509(wanted.toString()),wanted.toLocaleString('en-US')+'m');assert.ok(distance509(wanted.toString()).length<13)});
test('opponent choices, sealed dice and future boxes remain private until reveal',()=>{const g=game();begin(g);chooseAll(g,'chest');chooseLuck509(g,'p0','hand',2,1,g.phaseAt+10);const a=publicLuck509(g,'p1');assert.equal(a.ownPick,null);assert.equal(publicLuck509(g,'watch').hand,null);assert.doesNotMatch(JSON.stringify(a),/plan509|boxes509|items509|"dice"|jackpot|"coin"|autoItem/);g.plan509[0].seats[0].dice=[1,1];assert.deepEqual(publicLuck509(g,'p1'),a)});
test('AI decision never reads sealed rolls or rival hands',()=>{const g=game(1);begin(g);advanceLuck509(g,g.deadline);const p=g.players[1],a=aiPick509(g,p);g.plan509[0].seats[1].dice=[1,1];g.plan509[0].seats[1].jackpot=1;g.plan509[0].seats[0].boxes[0].reverse();g.items509[0]=3;assert.equal(aiPick509(g,p),a)});
test('all 784 item pairs resolve; no negative inventory or distance and at most four broadcasts',()=>{for(const a of ITEMS509)for(const b of ITEMS509){const g=readyItems([a.id,b.id,a.id,b.id],[0,5000,2000,1000]);assert.ok(g.event.rows.every(r=>metres509(r.to)>=0n&&r.coils>=0&&r.wards>=0));assert.ok(g.event.attacks.length<=4)}});
test('1000 seeded complete races match after JSON restart, retain gear and remain bounded in duration',()=>{for(let seed=1;seed<=1000;seed++){let z=seed;const g=game(1);g.plan509=drawPlan509(n=>{z=(Math.imul(z,1664525)+1013904223)>>>0;return z%n});const other=JSON.parse(JSON.stringify(g));advanceLuck509(g,1e7);advanceLuck509(other,1e7);assert.deepEqual(g,other);assert.equal(g.phase,'result');assert.equal(g.history.length,8);assert.ok(g.resultAt<650000);assert.ok(g.players.every(p=>metres509(p.distance)>=0n));assert.ok(g.history.every(e=>e.attacks.length<=4&&e.castMs<=12800))}});
test('power and volley timeline is identical to every viewer and bounded after end',()=>{const g=readyItems(['lightning','shell','mirror','shield'],[0,1000,500,100]);advanceLuck509(g,g.nextAt);assert.equal(g.phase,'power');advanceLuck509(g,g.nextAt);assert.equal(g.phase,'broadcast');for(let ms=0;ms<g.event.castMs;ms+=99){const all=g.players.map(p=>broadcastFrame509(publicLuck509(g,p.playerId),g.phaseAt+ms));all.forEach(x=>assert.deepEqual(x,all[0]))}assert.equal(paintKey509(g,g.phaseAt+20000,true,null,false),paintKey509(g,g.phaseAt+50000,true,null,false))});
test('huge movement preserves finite camera geometry, caps visual travel and ends on exact distance',()=>{const g=game();g.players[0].coils=80;playRound(g,['product','dash','dash','dash']);while(g.phase!=='run')advanceLuck509(g,g.nextAt);const a=raceFrame509(g,g.phaseAt,'p0'),b=raceFrame509(g,g.nextAt,'p0');assert.ok(Math.abs(b.visualCamera-a.visualCamera)<=6000.001);assert.equal(b.rows[0].exact,row(g).to);for(let ms=0;ms<=4800;ms+=32){const f=raceFrame509(g,g.phaseAt+ms,'p0');assert.ok(f.rows.every(r=>Number.isFinite(r.x)&&r.x>=7&&r.x<=93));assert.ok(f.marks.every(m=>Number.isFinite(m.x)))}});
test('production clients negotiate version, preserve private state on disk and reject old clients',()=>{const dir=mkdtempSync(join(tmpdir(),'luck509-'));try{const x=setup(2,join(dir,'state.json')),a=start(x);assert.equal(a.get().rules509,1);x.time(a.get().nextAt);x.c.advance();x.time(a.get().deadline);x.c.advance();assert.equal(a.get().phase,'hand');assert.deepEqual(x.send(0,'luck509',{gameId:a.get().id,kind:'hand',index:2,round:1}),[]);const y=setup(2,join(dir,'state.json'));y.time(x.now());assert.deepEqual(y.c.data.luckRooms507[a.party.code],a.get());assert.equal(y.send(1,'luck509',{gameId:a.get().id,kind:'hand',index:2,round:1,luckVersion509:0}).length,1);x.time(1e7);y.time(1e7);x.c.advance();y.c.advance();assert.deepEqual(y.c.data.luckRooms507[a.party.code],a.get())}finally{rmSync(dir,{recursive:true,force:true})}});
test('four clients, forged ids, duplicates, and stale phases follow authenticated server choices',()=>{const x=setup(),a=start(x);x.time(a.get().nextAt);x.c.advance();assert.deepEqual(x.send(0,'luck509',{gameId:a.get().id,kind:'chest',index:2,round:1,playerId:'p1'}),[]);assert.equal(a.get().boxes509[0],2);assert.equal(a.get().boxes509[1],null);assert.deepEqual(x.send(0,'luck509',{gameId:a.get().id,kind:'chest',index:2,round:1}),[]);assert.equal(x.send(0,'luck509',{gameId:a.get().id,kind:'chest',index:1,round:1}).length,1);assert.equal(x.send(1,'luck509',{gameId:a.get().id,kind:'hand',index:0,round:1}).length,1)});
test('loadout details show public gear, hand has four choices, and idle DOM makes zero writes',()=>{const d=dom();try{luckAfter509(d.c);d.flush();const html=luckView509(d.c);assert.equal((html.match(/data-hand-pick509="/g)??[]).length,4);assert.equal((html.match(/data-power-row509="/g)??[]).length,4);paintLuck509(d.c,d.g.phaseAt+20);d.reset();for(let i=0;i<1000;i++)paintLuck509(d.c,d.g.phaseAt+20);assert.equal(d.mutations(),0);luckClick509(d.c,{dataset:{gearSeat509:'1'}});d.flush();assert.equal(d.c.lkUI509.nodes['gear-panel'].hidden,false);luckClick509(d.c,{dataset:{gearClose509:'1'}});d.flush();assert.equal(d.c.lkUI509.nodes['gear-panel'].hidden,true)}finally{d.restore()}});
test('actual DOM painting covers growth calculation, all volleys, huge race, and both image atlases',()=>{const g=game();g.round=4;equip(g,0,['shell','lightning','wrench']);equip(g,1,['mirror','turbine']);g.players[2].coils=60;g.players[1].distance=5000;playRound(g,['product','mega','jackpot','ward']);const d=dom(g);try{luckAfter509(d.c);d.flush();while(!['chest','result'].includes(g.phase)){d.c.state.luck=publicLuck509(g,'p0');for(let ms=0;ms<Math.min(15000,g.nextAt-g.phaseAt);ms+=80)paintLuck509(d.c,g.phaseAt+ms);assert.doesNotMatch(d.c.lkUI509.nodes.ground.style.transform,/NaN|Infinity/);advanceLuck509(g,g.nextAt)}const n=d.c.lkUI509.nodes;assert.equal(n.players[0].score.textContent,distance509(g.players[0].distance));assert.ok(n.volleyArts.some(e=>e.dataset.atlas==='509'));assert.ok(n.volleyArts.some(e=>e.dataset.atlas==='508'))}finally{d.restore()}});
test('touch bursts send one choice, visibility pauses paint and cleanup releases every listener',()=>{const d=dom();try{luckAfter509(d.c);d.flush();let sent=0;d.c.raw=()=>{sent++;return true};for(let i=0;i<100;i++)requestLuck509(d.c,'chest',0);assert.equal(sent,1);document.visibilityState='hidden';d.listeners.get('visibilitychange')();assert.equal(d.queue.size,0);d.reset();luckTick509(d.c);assert.equal(d.mutations(),0);luckBefore509(d.c);assert.equal(d.listeners.size,0)}finally{d.restore()}});
test('new transparent 4 by 3 item atlas fully decodes with 12 occupied cells',async()=>{const require=createRequire(import.meta.url),{loadImage,createCanvas}=require('@napi-rs/canvas');const im=await loadImage(new URL('../assets/luck509/items.png',import.meta.url).pathname);assert.equal(im.width/4,im.height/3);const cv=createCanvas(im.width,im.height),ctx=cv.getContext('2d');ctx.drawImage(im,0,0);for(let i=0;i<12;i++){const raw=ctx.getImageData(i%4*362,Math.floor(i/4)*362,362,362).data;assert.ok(raw.some((v,j)=>j%4===3&&v===0));assert.ok(raw.some((v,j)=>j%4===3&&v>200))}});
