import test from'node:test';
import assert from'node:assert/strict';
import{registerHooks}from'node:module';
import{existsSync,mkdtempSync,rmSync,readFileSync,writeFileSync}from'node:fs';
import{join}from'node:path';import{tmpdir}from'node:os';
import{makeLuck507,startLuck507,chooseLuck507,advanceLuck507,publicLuck507,drawPlan507,item507,ranks507,LUCK507}from'../src/luck/Rules507.js';
import{raceFrame507,luckSignature507,paintKey507}from'../src/luck/Presentation507.js';
const fixtures={
 [new URL('../src/ui/MonsterVisual.js',import.meta.url).href]:`export const monsterVisual=()=>'<i class="test-sprite"></i>';export const setMonsterVisualFrame=()=>{};`,
 [new URL('../src/data/species.js',import.meta.url).href]:`export const SPECIES=Object.fromEntries(['slime','goblin','wolf','skeleton','ember_gecko','glacier_queen','myth_rion','myth_yori','myth_hide','myth_enami'].map(id=>[id,{id,name:id,race:id==='slime'?'slime':'beast',rarity:'R'}]));`,
 [new URL('../src/data/endgameCharacters.js',import.meta.url).href]:`export const ENDGAME_CHARACTERS={};export const canonicalEndgameId=id=>id;`
};
const hook=registerHooks({resolve(spec,c,next){const url=spec.startsWith('.')?new URL(spec,c.parentURL).href:spec;if(fixtures[url]&&!existsSync(new URL(url)))return{url,shortCircuit:true};return next(spec,c)},load(url,c,next){if(fixtures[url]&&!existsSync(new URL(url)))return{format:'module',source:fixtures[url],shortCircuit:true};return next(url,c)}});
const{RaceCoordinator451}=await import('../online-server/src/RaceCoordinator451.js');
const{luckView507,luckAfter507,luckBefore507,luckTick507,paintLuck507,requestLuck507,luckReceive507,luckClick507}=await import('../src/luck/View507.js');
const{raceDomSignature452}=await import('../src/race/RacePresentation452.js');
const{isPartyHub462,partyHub462}=await import('../src/party/PartyView462.js');
const{resultGame490}=await import('../src/party/PartyResults490.js');
hook.deregister();
const plan=()=>drawPlan507(n=>n===100?30:0);
function game(n=4){const g=makeLuck507({id:'luck-test',code:'ABC123',partyId:'party',hostId:'p0',members:Array.from({length:n},(_,i)=>({playerId:'p'+i,name:'P'+i,color499:['orange','pink','green','blue'][i],owned:[{id:'m'+i,speciesId:'wolf'}],choice:{id:'m'+i,speciesId:'wolf'}}))});startLuck507(g,1000,plan());return g}
const begin=g=>{advanceLuck507(g,g.nextAt);return g.phaseAt};
function picked(g,boxes=[0,0,0,0]){const at=begin(g);for(const p of g.players)if(!p.ai)chooseLuck507(g,p.playerId,boxes[p.seat],g.round,at+10);advanceLuck507(g,at+3200);assert.equal(g.phase,'reveal');return g}
function setup(n=4,stateFile=null){let now=10000;const packets=[],sessions=new Map(Array.from({length:n},(_,i)=>['p'+i,{playerId:'p'+i,clientKey:'key'+i,connected:true,profile:{displayName:'Player'+i}}]));const c=new RaceCoordinator451({sessions,stateFile,send:(id,m)=>packets.push({id,m:structuredClone(m)}),now:()=>now});const send=(i,op,extra={})=>{const before=packets.length;c.handle(sessions.get('p'+i),{op,rulesVersion:18,luckVersion507:1,gorillaVersion502:1,gorillaRules503:1,gorillaRules504:1,gorillaRules505:1,...extra});/* Seed a persisted Build507 lobby: new rooms now use Build508. */if(op==='partyCreate462'&&extra.game==='luck'){const party=Object.values(c.data.parties462)[0],room=c.data.luckRooms507[party.code];c.data.luckRooms507[party.code]=makeLuck507({...room,partyId:party.id,members:room.members,now});}return packets.slice(before).filter(p=>p.m.type==='raceError451')};return{c,sessions,packets,send,time:t=>now=t,now:()=>now}}
function start(x,n=x.sessions.size){assert.deepEqual(x.send(0,'partyCreate462',{game:'luck',roster:[{id:'m0',speciesId:'wolf'}]}),[]);const party=Object.values(x.c.data.parties462)[0],get=()=>x.c.data.luckRooms507[party.code];for(let i=1;i<n;i++){assert.deepEqual(x.send(i,'partyJoin462',{code:party.code,roster:[{id:'m'+i,speciesId:'slime'}]}),[]);assert.deepEqual(x.send(i,'luck507',{gameId:get().id,kind:'select',monsterId:'m'+i}),[])}for(let i=0;i<n;i++)assert.deepEqual(x.send(i,'partyReady462',{ready:true}),[]);assert.deepEqual(x.send(0,'luck507',{gameId:get().id,kind:'start'}),[]);return{party,get}}
function context(g,self='p0'){return{state:{luck:publicLuck507(g,self),party:{id:'party',hostId:'p0',members:g.members.map(m=>({...m,connected:true})),game:'luck',phase:g.phase},available:true,serverNow:g.phaseAt,partyResultActions490:1},transport:{selfId:self},offset:g.phaseAt-Date.now(),sgMonster463:()=>'<span class="sg-monster"><i></i></span>',sgSpeciesName463:id=>id,ready:()=>true,connected:()=>true,roster:()=>[{id:'m0',speciesId:'wolf'}],bank:()=>null,save:{state:{player:{gold:1000,crystals:0},settings:{audioEnabled:false},monsters:[]}},root:{querySelector:()=>null},draft:{code:'ABC123'},render(){},lkUI507:{gameId:g.id,artReady:true,sound:false}}}

test('all 100 random values map to intended probabilities; boxes share identical distribution',()=>{const counts={};for(let n=0;n<100;n++)counts[item507(n).id]=(counts[item507(n).id]??0)+1;assert.deepEqual(counts,{walk:20,dash:22,spring:18,rocket:14,banana:14,pit:8,meteor:4});for(const n of[-1,100,NaN,1.5,'3'])assert.throws(()=>item507(n));let calls=0;const p=drawPlan507(n=>{calls++;return n-1});assert.equal(calls,160);assert.equal(p.length,8);assert.ok(p.flat().every(x=>x.boxes.length===3&&x.boxes.every(y=>y===99)&&x.auto===2&&x.wait===3100))});
test('1–4 humans get exactly four entrants and preserve chosen monsters, human and AI colors',()=>{for(let n=1;n<=4;n++){const g=game(n);assert.equal(g.players.length,4);assert.equal(g.players.filter(p=>!p.ai).length,n);for(let i=0;i<n;i++){assert.deepEqual(g.players[i].choice,g.members[i].choice);assert.equal(g.players[i].color499,g.members[i].color499)}}});
test('invalid sealed draws cannot start or partially mutate a game',()=>{const g=game();g.phase='lobby';const before=structuredClone(g),bad=plan();bad[0][0].boxes=[-1,2,3];assert.throws(()=>startLuck507(g,500,bad));assert.deepEqual(g,before)});
test('public state conceals the sealed plan, other choices and future outcomes',()=>{const g=game(),at=begin(g);chooseLuck507(g,'p0',2,1,at+5);for(const id of['p0','p1','observer']){const v=publicLuck507(g,id);assert.equal(v.ownBox,id==='p0'?2:null);assert.equal(v.players[0].locked,true);assert.equal(v.event,null);assert.deepEqual(v.history,[]);assert.doesNotMatch(JSON.stringify(v),/plan507|choices507|auto507|"boxes"|"wait"|lastChoiceAt/)}const before=publicLuck507(g,'p1');g.plan507[7][3].boxes[2]=99;assert.deepEqual(publicLuck507(g,'p1'),before)});
test('rapid duplicate input acknowledges once; changing a locked box cannot reroll',()=>{const g=game(),at=begin(g);assert.equal(chooseLuck507(g,'p0',1,1,at+10),true);const frozen=structuredClone(g);for(let n=0;n<80;n++)assert.equal(chooseLuck507(g,'p0',1,1,at+11),false);assert.throws(()=>chooseLuck507(g,'p0',2,1,at+11));assert.deepEqual(g,frozen)});
test('invalid, stale, early, late and spectator inputs do not mutate the draw',()=>{const g=game(),at=begin(g),before=structuredClone(g);for(const args of[['p0',-1,1,at],['p0',3,1,at],['p0',1.5,1,at],['p0',1,0,at],['p0',1,2,at],['p0',1,1,at-1],['p0',1,1,g.deadline],['p0',1,1,NaN],['other',1,1,at]])assert.throws(()=>chooseLuck507(g,...args));assert.deepEqual(g,before)});
test('all four choices reveal simultaneously after minimum time, without input-order advantage',()=>{const a=game(),b=game(),at=begin(a);begin(b);const boxes=[0,2,1,2];for(const i of[0,1,2,3])chooseLuck507(a,'p'+i,boxes[i],1,at+10);for(const i of[3,2,1,0])chooseLuck507(b,'p'+i,boxes[i],1,at+10);advanceLuck507(a,at+1999);assert.equal(a.phase,'choose');advanceLuck507(a,at+2000);advanceLuck507(b,at+2000);assert.equal(a.phase,'reveal');assert.deepEqual(a.event,b.event);assert.equal(a.event.rows.length,4)});
test('AI and absent humans use their sealed automatic choice; late human cannot replace it',()=>{const g=game(1),at=begin(g);advanceLuck507(g,at+1300);assert.equal(g.phase,'choose');assert.deepEqual(g.choices507,[null,0,0,0]);advanceLuck507(g,g.deadline);assert.equal(g.phase,'reveal');assert.ok(g.event.rows.every(r=>r.automatic));assert.equal(chooseLuck507(g,'p0',0,1,g.phaseAt+1),false);assert.throws(()=>chooseLuck507(g,'p0',2,1,g.phaseAt+1))});
test('banana cannot produce negative distance; a pit loses the round but never freezes the race',()=>{const g=game();g.plan507[0][0].boxes[0]=80;g.plan507[0][1].boxes[0]=94;picked(g);assert.equal(g.event.rows[0].item,'banana');assert.equal(g.event.rows[0].to,0);assert.equal(g.event.rows[1].item,'pit');advanceLuck507(g,1e6);assert.equal(g.phase,'result');assert.equal(g.history.length,8)});
test('last place can leap into first with a rocket; catch-up is bounded and computed before movement',()=>{const g=game();[90,85,80,50].forEach((d,i)=>g.players[i].distance=d);g.scaleMax=120;for(let i=0;i<3;i++)g.plan507[0][i].boxes[0]=92;g.plan507[0][3].boxes[0]=70;picked(g);const row=g.event.rows[3];assert.equal(row.beforeRank,4);assert.equal(row.afterRank,1);assert.equal(row.delta,89);assert.equal(row.to,139);assert.ok(g.event.rows.slice(0,3).every(r=>r.delta===0))});
test('equal distances are shared ranks, including a four-way winner',()=>{const g=game();advanceLuck507(g,1e6);assert.ok(g.results.every(r=>r.rank===1));assert.deepEqual(ranks507([{playerId:'a',distance:12},{playerId:'b',distance:12},{playerId:'c',distance:0},{playerId:'d',distance:0}]).map(r=>r.rank),[1,1,3,3])});
test('delayed ticks and JSON restart recover exactly the same eight-round outcome',()=>{const a=game(2),b=JSON.parse(JSON.stringify(a));advanceLuck507(a,1e6);for(let i=0;i<200&&b.phase!=='result';i++)advanceLuck507(b,b.nextAt);assert.deepEqual(a,b);assert.equal(a.history.length,8);const final=structuredClone(a);advanceLuck507(a,2e6);assert.deepEqual(a,final)});
test('all sampled full games finish within 158 seconds and distances stay bounded',()=>{let seed=9827;const rand=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n};for(let i=0;i<300;i++){const g=game(1+i%4);g.plan507=drawPlan507(rand);advanceLuck507(g,1e6);assert.equal(g.phase,'result');assert.equal(g.history.length,8);assert.ok(g.resultAt-g.createdAt<=158000);assert.ok(g.players.every(p=>p.distance>=0&&p.distance<=1280));assert.ok(g.results.every(r=>r.rank>=1&&r.rank<=4))}});
test('production coordinator runs four clients with matching public events and no base-race room',()=>{const x=setup(),a=start(x);assert.equal(x.c.active('p0'),true);assert.equal(x.c.view(x.sessions.get('p0')).room,null);x.time(a.get().nextAt);x.c.advance();for(let i=0;i<4;i++)assert.deepEqual(x.send(i,'luck507',{gameId:a.get().id,kind:'choose',box:i%3,round:1}),[]);x.time(a.get().nextAt);x.c.advance();for(let i=1;i<4;i++)assert.deepEqual(x.c.view(x.sessions.get('p0')).luck,x.c.view(x.sessions.get('p'+i)).luck);assert.equal(a.get().phase,'reveal');assert.equal(Object.keys(x.c.data.rooms).length,0)});
test('server restart preserves sealed choices, pending phase and replayed selections',()=>{const dir=mkdtempSync(join(tmpdir(),'luck507-'));try{const file=join(dir,'race.json'),x=setup(2,file),a=start(x);x.time(a.get().nextAt);x.c.advance();assert.deepEqual(x.send(0,'luck507',{gameId:a.get().id,kind:'choose',box:2,round:1}),[]);const y=setup(2,file);y.time(x.now());const other=()=>y.c.data.luckRooms507[a.party.code];assert.deepEqual(other(),a.get());assert.deepEqual(y.send(0,'luck507',{gameId:a.get().id,kind:'choose',box:2,round:1}),[]);x.time(1e6);y.time(1e6);x.c.advance();y.c.advance();assert.deepEqual(other(),a.get());assert.equal(a.get().phase,'result')}finally{rmSync(dir,{recursive:true,force:true})}});
test('disconnects auto-select; reconnects can participate next round without reset',()=>{const x=setup(),a=start(x);x.time(a.get().nextAt);x.c.advance();x.sessions.get('p2').connected=false;x.time(a.get().deadline);x.c.advance();assert.equal(a.get().event.rows[2].automatic,true);while(a.get().phase!=='choose'){x.time(a.get().nextAt);x.c.advance()}x.sessions.get('p2').connected=true;assert.equal(a.get().round,2);assert.deepEqual(x.send(2,'luck507',{gameId:a.get().id,kind:'choose',box:1,round:2}),[]);assert.equal(x.c.view(x.sessions.get('p2')).luck.ownBox,1)});
test('joining a running game is spectator-only; replay adds that person as a player',()=>{const x=setup(2),a=start(x,1);assert.deepEqual(x.send(1,'partyJoin462',{code:a.party.code,roster:[{id:'m1',speciesId:'slime'}]}),[]);assert.equal(x.c.view(x.sessions.get('p1')).party.members.find(p=>p.playerId==='p1').spectating,true);assert.equal(x.send(1,'luck507',{gameId:a.get().id,kind:'choose',box:0,round:1}).length,1);x.time(1e6);x.c.advance();const old=a.get().id;assert.deepEqual(x.send(0,'partyResult490',{partyId:a.party.id,gameId:old,kind:'again'}),[]);assert.equal(a.get().phase,'lobby');assert.equal(a.get().members.length,2);assert.notEqual(a.get().id,old);assert.deepEqual(x.send(0,'partyResult490',{partyId:a.party.id,gameId:old,kind:'again'}),[]);assert.equal(a.get().phase,'lobby')});
test('result can return to party catalog and switch to existing gorilla game',()=>{const x=setup(1),a=start(x);x.time(1e6);x.c.advance();assert.deepEqual(x.send(0,'partyResult490',{partyId:a.party.id,gameId:a.get().id,kind:'list'}),[]);assert.equal(x.c.view(x.sessions.get('p0')).luck,null);assert.deepEqual(x.send(0,'partyGame462',{game:'gorilla'}),[]);assert.equal(x.c.view(x.sessions.get('p0')).gorilla.phase,'lobby');assert.equal(x.c.view(x.sessions.get('p0')).luck,null)});
test('host-only start, readiness and protocol guards reject outdated clients',()=>{const x=setup(2);x.send(0,'partyCreate462',{game:'luck',roster:[{id:'m0',speciesId:'wolf'}]});const p=Object.values(x.c.data.parties462)[0],g=x.c.data.luckRooms507[p.code];assert.equal(x.send(0,'luck507',{gameId:g.id,kind:'start'}).length,1);assert.equal(x.send(0,'partyReady462',{ready:true,luckVersion507:0}).length,1);assert.equal(x.send(0,'luck507',{gameId:g.id,kind:'select',monsterId:'m0',luckVersion507:0}).length,1);x.send(1,'partyJoin462',{code:p.code,roster:[{id:'m1',speciesId:'slime'}]});assert.equal(x.send(1,'luck507',{gameId:g.id,kind:'start'}).length,1);assert.equal(x.send(0,'luck507',{gameId:'stale',kind:'start'}).length,1);assert.equal(g.phase,'lobby')});
test('foreign player id cannot choose for another seat; live switching and color changes are blocked',()=>{const x=setup(),a=start(x);x.time(a.get().nextAt);x.c.advance();assert.deepEqual(x.send(0,'luck507',{gameId:a.get().id,kind:'choose',box:1,round:1,playerId:'p3'}),[]);assert.equal(a.get().choices507[0],1);assert.equal(a.get().choices507[3],null);assert.equal(x.send(0,'partyGame462',{game:'gorilla'}).length,1);assert.equal(x.send(0,'partyMemberColor500',{partyId:a.party.id,playerId:'p1',color499:'green',seatToken485:a.party.members[1].seatToken485}).length,1)});
test('host transfer and stale result cleanup retain party correctness',()=>{const x=setup(2),a=start(x);x.sessions.get('p0').connected=false;x.c.advance();x.time(x.now()+30001);x.c.advance();assert.equal(a.party.hostId,'p1');assert.equal(a.get().hostId,'p1');x.time(1e6);x.c.advance();assert.equal(a.get().phase,'result');x.sessions.get('p1').connected=false;x.time(1e6+86400001);x.c.advance();assert.equal(a.get(),undefined);assert.equal(a.party.game,null)});
test('failed persistence rolls back choices instead of accepting an unrecorded draw',()=>{const dir=mkdtempSync(join(tmpdir(),'luck507-write-'));try{const x=setup(1),a=start(x);x.time(a.get().nextAt);x.c.advance();const before=structuredClone(a.get());const file=join(dir,'file');writeFileSync(file,'not a directory');x.c.stateFile=join(file,'state.json');assert.equal(x.send(0,'luck507',{gameId:a.get().id,kind:'choose',box:2,round:1}).length,1);assert.deepEqual(a.get(),before);assert.equal(x.c.healthy(),false)}finally{rmSync(dir,{recursive:true,force:true})}});
test('play markup includes exactly three real buttons, four colored runners, accessible labels and result ties',()=>{const g=game(),c=context(g);for(const phase of['countdown','choose','reveal','run','settle']){c.state.luck.phase=phase;const html=luckView507(c);assert.equal((html.match(/data-lk-box="/g)??[]).length,3);assert.equal((html.match(/data-lk-runner="/g)??[]).length,4);assert.match(html,/aria-label="1番の箱を選ぶ"/);assert.doesNotMatch(html,/undefined|NaN/)}advanceLuck507(g,1e6);c.state.luck=publicLuck507(g,'p0');assert.match(luckView507(c),/同着、優勝/);assert.equal(resultGame490(c).id,g.id);assert.equal(isPartyHub462(c),false)});
test('phase and score updates keep the play DOM signature while game, roster and result changes rebuild',()=>{const g=game(),c=context(g),before=raceDomSignature452(c);begin(g);c.state.luck=publicLuck507(g,'p0');c.state.party.phase='choose';assert.equal(raceDomSignature452(c),before);picked({...game()});chooseLuck507(g,'p0',0,1,g.phaseAt+1);c.state.luck=publicLuck507(g,'p0');assert.equal(raceDomSignature452(c),before);advanceLuck507(g,1e6);c.state.luck=publicLuck507(g,'p0');assert.notEqual(raceDomSignature452(c),before)});
test('every motion stays inside the track, starts/ends exactly and honors reduced motion',()=>{for(const roll of[0,25,45,65,80,92,99]){const g=game();g.players.forEach((p,i)=>p.distance=60+i*10);g.scaleMax=120;g.plan507[0].forEach(p=>p.boxes.fill(roll));picked(g);advanceLuck507(g,g.nextAt);for(let ms=0;ms<=4000;ms+=40){const f=raceFrame507(g,g.phaseAt+ms);assert.ok(f.every(p=>Number.isFinite(p.x)&&p.x>=12&&p.x<=88&&p.opacity>=0&&p.opacity<=1));if(ms===0)f.forEach((p,i)=>assert.equal(p.distance,g.event.rows[i].from));if(ms>=3800)f.forEach((p,i)=>assert.equal(p.distance,g.event.rows[i].to))}assert.ok(raceFrame507(g,g.phaseAt+900,true).every(p=>p.y===0&&p.angle===0&&p.scale===1));assert.ok(raceFrame507(g,g.phaseAt+900,true).every((p,i)=>p.distance===g.event.rows[i].to))}});
test('selection updates only once per second, running updates at bounded frame cadence',()=>{const g=game();begin(g);const keys=new Set();for(let i=0;i<300;i++)keys.add(paintKey507(g,g.phaseAt+i*33,true,null,false));assert.equal(keys.size,10);picked({...game()});g.phase='run';const moving=new Set();for(let i=0;i<1000;i++)moving.add(paintKey507(g,g.phaseAt+i,true,null,false));assert.ok(moving.size<=32)});
function dom(){let mutations=0,serial=0;const queue=new Map(),listeners=new Map(),saved={document:globalThis.document,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};
 function el(){const values={},attrs={},children=new Map();return{dataset:new Proxy({},{set(t,k,v){mutations++;t[k]=v;return true}}),style:new Proxy({setProperty(k,v){this[k]=v},getPropertyValue(k){return this[k]??''},getPropertyPriority(){return''}},{set(t,k,v){mutations++;t[k]=v;return true}}),classList:{contains:s=>s==='lk-play507'},getAttribute:k=>attrs[k]??null,setAttribute(k,v){mutations++;attrs[k]=v},addEventListener(){},removeEventListener(){},contains:()=>false,querySelector(q){if(!children.has(q))children.set(q,el());return children.get(q)},querySelectorAll:()=>[],...Object.defineProperties({},{}),get textContent(){return values.textContent},set textContent(v){mutations++;values.textContent=v},get disabled(){return values.disabled},set disabled(v){mutations++;values.disabled=v},get hidden(){return values.hidden},set hidden(v){mutations++;values.hidden=v}}}
 const root=el(),buttons=[el(),el(),el()],dots=Array.from({length:8},el);root.querySelectorAll=q=>q==='[data-lk-box]'?buttons:q==='[data-lk-dot]'?dots:[];
 globalThis.document={visibilityState:'visible',querySelector:()=>null,addEventListener:(n,fn)=>listeners.set(n,fn),removeEventListener:n=>listeners.delete(n)};globalThis.requestAnimationFrame=fn=>{const n=++serial;queue.set(n,fn);return n};globalThis.cancelAnimationFrame=n=>queue.delete(n);
 const g=game(),at=begin(g),c=context(g);c.root={querySelector:()=>root};c.offset=at-Date.now();c.raw=()=>true;
 return{g,c,root,buttons,queue,listeners,mutations:()=>mutations,reset:()=>mutations=0,flush(){const jobs=[...queue.values()];queue.clear();for(const fn of jobs)fn()},restore(){luckBefore507(c);for(const[k,v]of Object.entries(saved)){if(v===undefined)delete globalThis[k];else globalThis[k]=v}}}
}
test('40 ticks coalesce to one frame; unchanged state causes zero DOM mutations',()=>{const d=dom();try{luckAfter507(d.c);for(let i=0;i<40;i++)luckTick507(d.c);assert.equal(d.queue.size,1);d.flush();assert.ok(d.buttons.every(b=>b.disabled===false));const at=d.g.phaseAt+20;paintLuck507(d.c,at);d.reset();for(let i=0;i<1800;i++)paintLuck507(d.c,at);assert.equal(d.mutations(),0)}finally{d.restore()}});
test('click bursts send one request and mark the selected box without replacing DOM',()=>{const d=dom();try{luckAfter507(d.c);d.flush();const sent=[];d.c.raw=(op,m)=>sent.push({op,m});for(let i=0;i<50;i++)requestLuck507(d.c,1);d.flush();assert.equal(sent.length,1);assert.deepEqual(sent[0],{op:'luck507',m:{kind:'choose',gameId:d.g.id,round:1,box:1}});assert.ok(d.buttons.every(b=>b.disabled));assert.equal(d.buttons[1].getAttribute('aria-pressed'),'true');chooseLuck507(d.g,'p0',1,1,d.g.phaseAt+10);d.c.state.luck=publicLuck507(d.g,'p0');luckReceive507(d.c);assert.equal(d.c.lkUI507.pending,null);assert.equal(requestLuck507(d.c,2),false)}finally{d.restore()}});
test('the same play nodes update across reveal, run, settle and next-round choice',()=>{const d=dom();try{luckAfter507(d.c);d.flush();const nodes=d.c.lkUI507.nodes;for(const p of d.g.players)chooseLuck507(d.g,p.playerId,0,1,d.g.phaseAt+10);for(const phase of['reveal','run','settle','choose']){advanceLuck507(d.g,d.g.nextAt);d.c.state.luck=publicLuck507(d.g,'p0');luckReceive507(d.c);paintLuck507(d.c,d.g.phaseAt+5);assert.equal(d.g.phase,phase);assert.equal(d.c.lkUI507.nodes,nodes);assert.equal(d.root.dataset.phase,phase);assert.equal(nodes.boxes.hidden,['reveal','run','settle'].includes(phase))}assert.ok(d.buttons.every(b=>!b.disabled));assert.equal(d.g.round,2)}finally{d.restore()}});
test('hidden tabs queue no frames; unmount cancels outstanding work and listeners',()=>{const d=dom();try{luckAfter507(d.c);assert.equal(d.queue.size,1);document.visibilityState='hidden';d.listeners.get('visibilitychange')();assert.equal(d.queue.size,0);d.reset();for(let i=0;i<100;i++)luckTick507(d.c);assert.equal(d.mutations(),0);document.visibilityState='visible';d.listeners.get('visibilitychange')();assert.equal(d.queue.size,1);luckBefore507(d.c);assert.equal(d.queue.size,0);assert.equal(d.c.lkUI507.nodes,null);assert.equal(d.listeners.size,0)}finally{d.restore()}});
test('failed sends release the input lock and display a recoverable error',()=>{const d=dom();try{luckAfter507(d.c);d.flush();d.c.raw=()=>false;assert.equal(requestLuck507(d.c,0),false);d.flush();assert.equal(d.c.lkUI507.pending,null);assert.ok(d.buttons.every(b=>!b.disabled));assert.equal(d.c.lkUI507.nodes.error.hidden,false);d.c.ready=()=>false;paintLuck507(d.c,d.g.phaseAt+1);assert.ok(d.buttons.every(b=>b.disabled));assert.equal(d.c.lkUI507.nodes.offline.hidden,false)}finally{d.restore()}});
test('generated assets load completely, are correctly dimensioned and contain genuine alpha',async()=>{const {loadImage}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas/index.js');const bg=await loadImage(new URL('../assets/luck507/stadium.png',import.meta.url).pathname),items=await loadImage(new URL('../assets/luck507/items.png',import.meta.url).pathname);assert.equal(bg.width,1536);assert.equal(bg.height,1024);assert.equal(items.width,items.height);assert.equal(items.width%3,0)});
