import {mode584,decision584,motion584,score584,recap584} from './Polish584.js';
import {CHAIRS583,validChairs583,chairPoint583,orbit583,chairLocation584,chairValue584,chairOpen584} from './Rules583.js';
import {chairArt583,board583,resize583,paintBoard583} from './Board583.js';
import {music583,stopMusic583,unlock583} from './Audio583.js';
import {esc563 as esc,color563 as color,put563 as put,clock563 as clock,avatar563,header563,lobby563,result563,scoreCards563} from '../party/Arcade563.js';
import {sound543} from '../cart/Audio543.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const game=c=>c.state?.chairs,ui=c=>c.chairsUI583??={seq:0,sound:true,seen:0,limit:24,search:''},me=c=>game(c)?.players.find(p=>p.playerId===c.transport.selfId);
const options={prefix:'ch',title:'早押し！魔王のイス取り',sub:'THE LAST THRONE',cover:new URL('../../assets/chairs583/cover.webp',import.meta.url).href,hero:'その玉座、<br>先にいただき！',rule:'音楽が止まったら、空いているイスをタップ！',detail:'音楽が止まった瞬間、空席をタップ！ 普通席100点、金席200点。金の解禁待ちはありません。取られたらすぐ別の席へ！ 連続着席は25点ずつ追加（最大75点）。フライングはその回お休み。全８回、毎回全員復帰。最後の２回は得点２倍！',players:'４人対戦 · 全８回 · 空席はAI',search:'chairsSearch583'};
function play(c,g){return `<section class="arc563 arc-play563 ch-play583 ch-polish584">${header563(c,ui(c),'ch',options.title,options.sub)}${scoreCards563(c,g)}<div class="ch-roundbar583"><b data-ch-round>１回戦</b><div class="ch-rounds583" aria-label="全８回戦">${Array.from({length:8},(_,i)=>`<i data-ch-dot="${i}"></i>`).join('')}</div><strong data-ch-prize></strong></div><div class="ch-mode584" data-ch-mode></div><div class="ch-stage583" data-ch-stage role="group" aria-label="音楽が止まったら空席をタップ。キーボードは１から３キー" tabindex="0"><div class="ch-signal583" data-ch-signal role="status" aria-live="assertive"><span class="ch-equalizer583" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span><small data-ch-signal-sub>耳と目をすませて</small><b data-ch-signal-title>まだ、待って！</b><span data-ch-decision></span></div><div class="ch-chairs583">${[0,1,2].map(i=>`<button class="ch-chair583" data-ch-chair="${i}" hidden><em data-ch-badge></em>${chairArt583(i)}<i class="ch-lock584" data-ch-lock aria-hidden="true">待</i><span class="ch-growth584" aria-hidden="true"><i data-ch-growth></i></span><strong data-ch-points></strong><small data-ch-seatnote></small></button>`).join('')}</div><div class="ch-pawns583" aria-hidden="true">${g.players.map(p=>`<div class="ch-pawn583" data-ch-pawn="${p.seat}" style="--player:${color(p)}"><i class="ch-shadow583"></i><span class="ch-monster583">${avatar563(c,p)}</span><b>${p.playerId===c.transport.selfId?'あなた':esc(p.name)}</b><small data-ch-reaction="${p.seat}"></small></div>`).join('')}</div><canvas data-ch-fx aria-hidden="true"></canvas><div class="ch-round-result583" data-ch-result hidden><small data-ch-result-small></small><b data-ch-result-title></b><span data-ch-result-detail></span></div><div class="ch-toast583" data-ch-toast role="status" aria-live="polite" hidden></div><div class="arc-count563" data-ch-count hidden></div><div class="arc-network563" data-ch-network hidden>再接続中 · AIが引き継いでいます</div></div><footer class="ch-footer583"><div class="ch-self583" data-ch-self></div><div><b data-ch-help>音楽が止まったらイスをタップ！</b><p data-ch-hint>早押しは、その回お休み！</p></div><span class="ch-rank583" data-ch-rank></span></footer></section>`;}
export function chairsView583(c){const g=game(c),u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,limit:24,search:'',pending:null,notice:null,openedRound:0,maxRound:0,motion:{},scoreTweens:{},pointerClickAt:-1000});if(g.rules583!==4)return '<section class="arc563">本体とサーバーをBuild598へ更新してください。</section>';return g.phase==='lobby'?lobby563(c,g,u,options):g.phase==='result'?result563(c,g,u,{...options,caption:g.winnerIds.includes(c.transport.selfId)?'玉座は、いただいた！':'今夜の玉座の主、決定！',stats:p=>`着席 ${p.sits}回 · 金のイス ${p.golds}回 · フライング ${p.faults}回`}).replace('arc-result563','arc-result563 ch-finale584').replace('</section>',recap584(c,g)+'</section>'):play(c,g);}
export function chairsReceive583(c){const g=game(c);if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.pending&&(p?.lastSeq>=u.pending.seq||g.round!==u.pending.round||clock(c)-u.pending.at>1000))u.pending=null;}
export function chairsFrame583(c,m){const n=m.chairs,g=game(c);if(m.selfId!==c.transport.selfId||!g||n?.id!==g.id||n.serverAt<g.serverAt)return;c.offset=m.serverNow-Date.now();c.state.chairs={...g,...n};chairsReceive583(c);if((g.phase==='result')!==(n.phase==='result'))c.render();}
function send(c,target){const g=game(c),u=ui(c),p=me(c),at=clock(c);if(!c.ready()||!c.connected()||u.pending&&at-u.pending.at<(u.pending.target===target?250:90)||!g||!validChairs583(g,p,{action:'sit',target},at))return false;unlock583(u);const seq=++u.seq,sent=c.raw('chairsInput583',{gameId:g.id,seq,round:g.round,action:'sit',target});if(sent!==false){u.pending={seq,at,round:g.round,target};u.press={target,until:at+140};}return sent!==false;}
function update(c){
 const g=game(c),u=ui(c),n=u.nodes,p=me(c),at=clock(c);if(!g?.players.length)return;
 const wait=g.phase==='countdown',dance=g.stage==='dance',grab=g.stage==='grab',reveal=g.stage==='reveal';
 u.root.dataset.stage=wait?'ready':g.stage;u.root.classList.toggle('is-double',g.multiplier===2);if(c.connected())music583(u,g,at);else stopMusic583(u);paintBoard583(u.renderer,g,u,at);
 if(grab&&g.chairs.some(ch=>ch.gold&&ch.owner==null&&chairOpen584(g,ch,at))&&u.openedRound!==g.round){u.openedRound=g.round;sound543(u,'spring');}
 put(n.mode,mode584(g));put(n.decision,decision584(g,at));
 put(n.round,`${g.round} / ８回戦`);put(n.prize,wait?'４人で争奪':g.multiplier===2?'得点２倍！':`イスは${g.chairs.length}つ`);
 for(let i=0;i<8;i++){u.dots[i].classList.toggle('is-current',i===g.round-1);u.dots[i].classList.toggle('is-done',i<g.round-1);const gain=p?g.history[i]?.gains[p.seat]:null;u.dots[i].classList.toggle('is-win',gain>0);u.dots[i].classList.toggle('is-miss',gain===0);u.dots[i].setAttribute('aria-label',`${i+1}回戦 ${gain==null?'':gain+'点'}`);}
 put(n.signalTitle,wait?'準備はいい？':dance?'まだ、待って！':grab?'座れ！！':'勝負あり！');
 put(n.signalSub,wait?'止まったら、イスをタップ':dance?'音楽が止まるまで…':grab?'空いているイスを奪え！':'次の回は、全員復帰');
 n.count.hidden=!wait;if(wait)put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000)));
 const top=Math.max(...g.players.map(q=>q.score));
 for(const q of g.players){
  const isSelf=q.playerId===c.transport.selfId,claimed=q.chair!=null,pos=claimed?chairLocation584(g,q.chair):orbit583(q.seat,g,dance?at:g.stage==='grab'?g.phaseAt:g.phaseAt-200,u.reduced),pawn=u.pawns[q.seat];
  let x=pos.x,y=pos.y;if(grab&&!claimed&&!q.out)x=pos.x<.5?.10:.90;if(q.out&&!claimed){x=.14+q.seat*.24;y=.88;}
  if(claimed)y+=(u.chairHeight??120)*.20/u.renderer.h;
  const moving=motion584(u,q,{x,y},g,at);pawn.style.transform=`translate3d(${moving.x*u.renderer.w}px,${moving.y*u.renderer.h}px,0) translate(-50%,-70%)`;pawn.classList.toggle('is-diving',moving.landing);pawn.classList.toggle('is-flying',moving.flying);pawn.classList.toggle('is-crowned',q.score===top&&top>0);pawn.style.zIndex=String(Math.round(y*100));pawn.classList.toggle('is-self',isSelf);pawn.classList.toggle('is-seated',claimed);pawn.classList.toggle('is-out',q.out&&!claimed);pawn.classList.toggle('is-bump',at-q.bumpAt<350&&q.bumpAt>0);pawn.classList.toggle('is-dancing',dance&&!q.out);pawn.style.setProperty('--bob-delay',(-q.seat*.13)+'s');
  put(u.reactions[q.seat],q.fault?'早すぎた！':claimed?`＋${q.gain}`:q.out?'次こそ！':at-q.bumpAt<600&&q.bumpAt>0?'取られた！':'');
  put(u.scores[q.seat],score584(u,q.seat,q.score,at));put(u.status[q.seat],q.fault?'フライング':claimed?`＋${q.gain}点！`:q.auto?'AI':'');u.cards[q.seat].classList.toggle('is-leading',q.score===top&&top>0);u.cards[q.seat].classList.toggle('is-out',q.out&&!claimed);
 }
 for(let i=0;i<3;i++){
  const b=u.chairs[i],ch=g.chairs[i];b.hidden=!ch;if(!ch)continue;const pos=chairLocation584(g,i),value=chairValue584(g,ch,at),open=chairOpen584(g,ch,at),locked=grab&&ch.gold&&!open;b.style.left=`${pos.x*100}%`;b.style.top=`${pos.y*100}%`;b.style.zIndex=String(Math.round(pos.y*100)-1);b.classList.toggle('is-gold',ch.gold);b.classList.toggle('is-taken',ch.owner!=null);b.classList.toggle('is-pressing',u.press?.target===i&&at<u.press.until);b.classList.toggle('is-open',grab&&open&&ch.owner==null);b.classList.toggle('is-locked',locked);b.classList.toggle('is-max',ch.gold&&value>=200*g.multiplier);b.querySelector('[data-ch-lock]').hidden=!locked;const progress=ch.gold&&grab?Math.max(0,Math.min(1,(at-ch.openAt)/1800)):0;b.querySelector('[data-ch-growth]').style.transform=`scaleX(${progress})`;if(ch.owner!=null)b.style.setProperty('--owner',color(g.players[ch.owner]));
  put(b.querySelector('[data-ch-badge]'),ch.gold?(g.mode==='goldrush'?'黄金祭！':'金のイス'):'イス');put(b.querySelector('[data-ch-points]'),value+'点');put(b.querySelector('[data-ch-seatnote]'),ch.owner!=null?'確保！':dance?'♪':grab?'タップ！':'');
  b.disabled=!c.ready()||!c.connected()||wait||ch.owner!=null||!validChairs583(g,p,{action:'sit',target:i},at);b.setAttribute('aria-label',`${i+1}番、${ch.gold?'金のイス':'イス'}、${value}点、${locked?'金の解禁待ち、':''}${ch.owner!=null?'確保済み':dance?'音楽中、まだ待って':'空席'}`);
 }
 n.result.hidden=!reveal;
 if(reveal){put(n.resultSmall,g.round===8?'FINAL ROUND':`ROUND ${g.round}`);put(n.resultTitle,!p?'勝負あり！':p.gain?`${p.gain>=275*g.multiplier?'MAX獲得！':'確保！'} ＋${p.gain}点`:p.fault?'あっ！ フライング！':'惜しい、満席！');put(n.resultDetail,g.round===8?'合計得点を集計中…':p?.gain?(p.chair!=null&&g.chairs[p.chair].gold?'金の玉座をゲット！':'先に確保！ 堅実に得点を積もう'): '大丈夫、次の回はすぐ復帰！');}
 if(p){put(n.help,wait?'音楽が止まったらイスをタップ！':p.fault?'早すぎた！ 次の回でリベンジ！':p.chair!=null?'イスを確保！':dance?'「座れ！」の合図まで待って':grab?'空いているイスを奪え！':'次の回も、４人で勝負！');put(n.hint,g.round===8?'最後の１席！ 得点２倍＋連続ボーナス':at-p.bumpAt<600&&p.bumpAt>0?'取られた！ ほかのイスへ！':g.multiplier===2?'得点２倍＋連続ボーナス':'普通100点 ／ 金200点＋連続ボーナス');const rankHTML=`${1+g.players.filter(q=>q.score>p.score).length}位<small>${p.score===top?'首位！':'首位まで'+(top-p.score)+'点'}</small>`;if(n.rank.innerHTML!==rankHTML)n.rank.innerHTML=rankHTML;}else{put(n.help,'観戦中 · 次の試合から参加');put(n.hint,'空いているイスを早い者勝ち！');put(n.rank,'観戦');}
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(at-e.at>1300)continue;if(e.type==='stop'){stopMusic583(u);sound543(u,'go');}if(e.type==='sit'&&e.seat===p?.seat)sound543(u,e.gold?'edge':'park');if(e.type==='fault'&&e.seat===p?.seat){sound543(u,'fall');u.notice={text:'フライング！ 次の回で復帰',until:at+1600};}if(e.type==='miss'&&e.seat===p?.seat){sound543(u,'bump');u.notice={text:e.margin<=180?'僅差！ '+g.players[e.winner].name+'が先！':'取られた！ 別の空席へ！',until:at+1100};}if(e.type==='shuffle'){u.notice={text:'シャッフル！ 金の席を追え！',until:at+850};}if(e.type==='dance'){u.notice=null;if(e.multiplier===2)u.notice={text:e.round===8?'最終回！ 最大550点の１席！':'ここから得点２倍！',until:at+1600};}}
 n.toast.hidden=!u.notice||at>u.notice.until;if(!n.toast.hidden)put(n.toast,u.notice.text);n.network.hidden=c.connected();
}
export function chairsBefore583(c){const u=c.chairsUI583;if(!u)return;u.cleanup?.();u.cleanup=null;cancelAnimationFrame(u.raf);u.raf=null;u.root=null;stopMusic583(u);}
export function chairsDispose583(c){chairsBefore583(c);c.chairsUI583?.audio?.close()?.catch(()=>{});if(c.chairsUI583)c.chairsUI583.audio=null;}
export function chairsAfter583(c){
 const root=c.root?.querySelector('.ch-play583');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const attrs={mode:'mode',decision:'decision',stage:'stage',fx:'fx',round:'round',prize:'prize',signalTitle:'signal-title',signalSub:'signal-sub',count:'count',result:'result',resultSmall:'result-small',resultTitle:'result-title',resultDetail:'result-detail',toast:'toast',network:'network',help:'help',hint:'hint',self:'self',rank:'rank'};
 u.nodes=Object.fromEntries(Object.entries(attrs).map(([k,v])=>[k,root.querySelector(`[data-ch-${v}]`)]));for(const [key,sel] of [['chairs','[data-ch-chair]'],['pawns','[data-ch-pawn]'],['reactions','[data-ch-reaction]'],['dots','[data-ch-dot]'],['cards','[data-arc-card]'],['scores','[data-arc-score]'],['status','[data-arc-status]']])u[key]=[...root.querySelectorAll(sel)];
 const p=me(c);if(p){u.nodes.self.innerHTML=avatar563(c,p);u.nodes.self.style.setProperty('--player',color(p));}
 u.renderer=board583(u.nodes.fx);const abort=new AbortController(),on=(el,type,fn)=>el.addEventListener(type,fn,{signal:abort.signal}),resize=()=>{resize583(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);u.chairHeight=parseFloat(getComputedStyle(u.chairs[0]).height)||120;};resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const zoom=lockPlayZoom498(root);
 on(u.nodes.stage,'pointerdown',e=>{const b=e.target.closest('[data-ch-chair]');if(!b||b.disabled||e.isPrimary===false||e.button>0)return;e.preventDefault();u.pointerClickAt=performance.now();send(c,Number(b.dataset.chChair));});
 const tick=()=>{if(!u.root||document.hidden)return;update(c);u.raf=requestAnimationFrame(tick);};
 on(document,'visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(u.raf);u.raf=null;stopMusic583(u);u.audio?.suspend()?.catch(()=>{});}else{c.refresh?.();if(u.raf==null)tick();}});
 u.cleanup=()=>{abort.abort();observer.disconnect();zoom();};chairsReceive583(c);tick();
}
export function chairsClick583(c,b){const d=b.dataset,g=game(c);if(!g||!Object.keys(d).some(k=>k.startsWith('ch')))return false;const u=ui(c);unlock583(u);if(d.chMonster)c.raw('chairs583',{gameId:g.id,kind:'select',monsterId:d.chMonster});if(d.chAction==='start')c.raw('chairs583',{gameId:g.id,kind:'start'});if(d.chAction==='more'){u.limit+=24;c.render();}if(d.chAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound){stopMusic583(u);u.audio?.suspend()?.catch(()=>{});}else unlock583(u);}if(d.chChair!=null&&performance.now()-(u.pointerClickAt??-1000)>400)send(c,Number(d.chChair));return true;}
export function chairsInput583(c,e){if(e.name!=='chairsSearch583')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true;}
export function chairsKey583(c,e){if(!c.root?.querySelector('.ch-play583')||/INPUT|TEXTAREA/.test(e.target?.tagName))return false;if(/^[123]$/.test(e.key)){e.preventDefault();if(!e.repeat)send(c,Number(e.key)-1);return true;}return false;}
