import {escapeOnlineHtml as esc} from '../ui/screens/OnlinePartyScreen.js';
const expires=t=>new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
export function worldRaidOfflineView430(bridge,state){
 const bank=bridge.bank(),ready=bridge.ready(),entries=Object.values(bank.tickets),available=bridge.available(),pending=entries.filter(e=>e.phase==='pending'&&e.ticket.ledgerId===bank.ledgerId&&e.ticket.expiresAt>bridge.time()),expired=entries.filter(e=>['ready','playing','pending'].includes(e.phase)&&e.ticket.expiresAt<=bridge.time()),active=bridge.active(),remaining=state?.remaining??0;
 return `<section class="world-offline430"><h2>持ち出し挑戦権</h2><p>今の部隊を保存して、通信なしで挑戦できます。取得から24時間以内に結果を送信してください。</p><p>1日3回の枠から、あとで遊ぶ分を保存します。保存した分も「今日の残り」に含まれます。</p>${ready&&remaining>0?`<div class="world-ticket-buttons430">${Array.from({length:remaining},(_,i)=>`<button data-world-reserve430="${i+1}" ${bank.pendingReserve||bridge.preparing||active||state?.attempt?.status==='active'?'disabled':''}>${i+1}回分を保存</button>`).join('')}</div>`:!ready?'<p>新しい挑戦権は、サーバー接続中に取得できる。</p>':''}${bridge.preparing?'<p>オフライン用データを保存中…</p>':''}${bank.pendingReserve?'<p>挑戦権の取得を確認中… 再接続時も同じ受付を確認します。</p>':''}
 ${active?`<button data-world-ticket430="${esc(active.ticket.id)}">途中の挑戦を再開</button>`:''}${available.map(e=>`<article><b>第${e.ticket.sequence}戦・${esc(e.ticket.campaign.boss.name)}</b><small>期限 ${expires(e.ticket.expiresAt)}（日本時間）</small><button data-world-ticket430="${esc(e.ticket.id)}" ${active||state?.attempt?.status==='active'?'disabled':''}>この部隊で挑戦</button></article>`).join('')}
 ${!available.length&&!active?'<p>使用できる挑戦権：0枚</p>':''}${expired.length?`<p>期限切れ：${expired.length}件。これから届く結果は集計対象外です。</p>`:''}${pending.length?`<p>送信待ち：${pending.length}件。接続時に自動で反映する。</p>`:''}
 ${entries.filter(e=>e.receipt).slice(-3).reverse().map(e=>`<p>${e.ticket.sequence}戦目：${e.receipt.status==='accepted'?`${e.receipt.damage} ダメージを受付済み`:'期限切れ・集計対象外'}</p>`).join('')}
 ${bridge.error?`<p role="alert">${esc(bridge.error)}</p>`:''}<p>討伐後に届いた結果は元のボスの順位へ加算。次ボスには加算しない。順位報酬は全件受付または有効期限で確定する。</p><button data-world-sync430 ${!ready?'disabled':''}>送信状況を更新</button></section>`;
}
