const count=v=>Math.max(0,Math.floor(Number(v)||0));
const n=v=>count(v).toLocaleString('ja-JP');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function contributionBody437(snapshot,{portrait=()=>'',name=m=>m.onlineName??m.nickname??m.speciesId}={}){
 const rows=(snapshot?.party??[]).map(monster=>{const p=snapshot.performance?.[monster.id]??{},row=Object.fromEntries(['damage','taken','healing','revives','kills'].map(k=>[k,count(p[k])]));return {monster,row,score:row.damage+row.healing*1.15+row.kills*10000+row.revives*20000};});
 const best=Math.max(0,...rows.map(r=>r.score)),sum=key=>rows.reduce((s,r)=>s+r.row[key],0),damage=sum('damage');
 if(!rows.length)return '<p class="contribution-empty437">この挑戦の活躍記録はありません。</p>';
 return `<section class="contribution437" aria-label="今回の活躍表"><header><h3>今回の活躍表</h3><span>部隊 ${rows.length}体</span></header><div class="contribution-totals437"><span>与ダメージ合計<b>${n(damage)}</b></span><span>回復合計<b>${n(sum('healing'))}</b></span></div><div class="contribution-rows437">${rows.map(({monster,row,score})=>`<article class="contribution-row437 ${best>0&&score===best?'mvp437':''}"><div class="contribution-face437">${portrait(monster)}</div><div class="contribution-unit437"><strong>${esc(name(monster))}</strong><small>Lv.${n(monster.level)}${best>0&&score===best?' <b>最高殊勲</b>':''}</small></div><div class="contribution-numbers437"><span>与ダメージ <b>${n(row.damage)}</b></span><span>回復 <b>${n(row.healing)}</b></span></div><div class="contribution-meter437" aria-hidden="true"><i style="width:${damage?row.damage/damage*100:0}%"></i></div></article>`).join('')}</div><details class="contribution-detail437"><summary>被ダメージ・蘇生・撃破の内訳</summary><div class="contribution-table437"><table><thead><tr><th>仲間</th><th>被ダメージ</th><th>蘇生</th><th>撃破</th></tr></thead><tbody>${rows.map(({monster,row})=>`<tr><th>${esc(name(monster))}</th><td>${n(row.taken)}</td><td>${n(row.revives)}</td><td>${n(row.kills)}</td></tr>`).join('')}</tbody></table></div><p>最高殊勲は与ダメージ・回復・蘇生・撃破の総合評価です。</p></details></section>`;
}
