import {equipmentDisplayRarity,equipmentRarityColor} from '../data/equipment.js?v=3.1.55-build375';
import {equipmentLockEntries404,equippedEquipmentIds404,equipmentProtection404} from '../services/EquipmentProtection404.js?v=3.1.84-build404';
import {equipmentVisual} from './components/EquipmentVisual.js?v=3.1.61-build381';
import {equipmentLockBadge404,equipmentEscape404 as esc,EQUIPMENT_LOCK_ART404} from './components/EquipmentDetails404.js?v=3.1.84-build404';

export function equipmentLockManagerBody404(state,ui){
 const entries=equipmentLockEntries404(state,ui),equipped=equippedEquipmentIds404(state);
 const options=(pairs,current)=>pairs.map(([id,label])=>`<option value="${esc(id)}" ${current===id?'selected':''}>${esc(label)}</option>`).join('');
 return `<section class="equipment-lock-manager404"><div class="equipment-lock-controls404"><div class="equipment-lock-filters404"><label>種類<select data-lock-filter404="slot">${options([['all','すべて'],['weapon','武器'],['armor','防具'],['accessory','アクセ']],ui.slot)}</select></label><label>状態<select data-lock-filter404="status">${options([['all','すべて'],['locked','ロック中'],['unlocked','ロックなし']],ui.status)}</select></label><label>レア度<select data-lock-filter404="rarity">${options(['all','N','R','SR','SSR','UR','LR','神話','深淵','十神'].map(x=>[x,x==='all'?'すべて':x]),ui.rarity)}</select></label></div><div class="equipment-lock-presets404"><button type="button" data-lock-preset404="all">表示中を全選択</button><button type="button" data-lock-preset404="low">N・R</button>${ui.targetId?'<button type="button" data-lock-preset404="same">同名</button>':''}<button type="button" data-lock-preset404="none">選択解除</button></div><small data-lock-count404>表示 ${entries.length}個・選択 ${ui.selected.size}個</small></div><div class="equipment-lock-list404" tabindex="0" aria-label="ロックを管理する装備">${entries.map(item=>{const p=equipmentProtection404(state,item,equipped),marks=[p.locked?'ロック中':'ロックなし',p.equipped?'装備中':'',p.favorite?'お気に入り':'',p.permanent?'素材使用不可':''].filter(Boolean);return `<label class="equipment-lock-row404"><input type="checkbox" data-lock-item404="${esc(item.id)}" ${ui.selected.has(item.id)?'checked':''}><span class="equipment-lock-art404">${equipmentVisual(item,{label:esc(item.name)})}${equipmentLockBadge404(item)}</span><span><b style="color:${equipmentRarityColor(item)}">[${esc(equipmentDisplayRarity(item))}] ${esc(item.name)}</b><small>Lv.${item.level??1}${item.plus?` ＋${item.plus}`:''}</small><small>${marks.join('・')}</small></span></label>`;}).join('')||'<p class="equipment-empty404">この条件の装備はありません。</p>'}</div><footer class="equipment-lock-footer404"><label class="equipment-lock-favorites404"><input type="checkbox" data-lock-favorites404 ${ui.clearFavorites?'checked':''}>解除時にお気に入りも解除する</label><div><button type="button" data-lock-apply404="lock" ${ui.selected.size?'':'disabled'}><img src="${EQUIPMENT_LOCK_ART404}" alt="">選択をロック</button><button type="button" data-lock-apply404="unlock" ${ui.selected.size?'':'disabled'}>選択のロック解除</button></div><small>装備中・素材使用不可の装備は、ロックを解除しても素材にできません。</small></footer></section>`;
}
