export function createBattleRulesState(party){return{cooldowns:Object.fromEntries(party.map(m=>[m.id,{}])),enemyStatuses:{},allyEffects:{},enemyEffects:{},log:["戦闘開始"],lastStatusTurn:0}}
export function cooldownRemaining(battle,monsterId,skillId){return battle.cooldowns?.[monsterId]?.[skillId]??0}
export function setSkillCooldown(battle,monsterId,skill){if(!skill?.cooldown)return;battle.cooldowns[monsterId]??={};battle.cooldowns[monsterId][skill.id]=skill.cooldown+1}
export function tickCooldowns(battle){Object.values(battle.cooldowns??{}).forEach(map=>Object.keys(map).forEach(id=>{map[id]=Math.max(0,map[id]-1);if(map[id]===0)delete map[id]}))}
export function addBattleLog(battle,text){battle.log??=[];battle.log.unshift(text);battle.log=battle.log.slice(0,6)}
export function enemyStatusesFor(battle,enemyId){battle.enemyStatuses??={};if(Array.isArray(battle.enemyStatuses))battle.enemyStatuses={};battle.enemyStatuses[enemyId]??=[];return battle.enemyStatuses[enemyId]}
export function applyEnemyStatus(battle,status,enemyId=battle.targetEnemyId){if(!status||!enemyId)return false;const enemy=(battle.enemies??[battle.enemy]).filter(Boolean).find(entry=>entry.id===enemyId),resistance=Math.max(0,Math.min(.9,Number(enemy?.bossStatusResist)||0));if(resistance&&Math.random()<resistance)return false;const statuses=enemyStatusesFor(battle,enemyId),existing=statuses.find(s=>s.id===status.id);if(existing){existing.turns=Math.max(existing.turns,status.turns);existing.power=Math.max(existing.power,status.power)}else statuses.push({...status});return true}
export function processEnemyStatuses(battle){const results=[];(battle.enemies??[battle.enemy]).filter(Boolean).forEach(enemy=>{const statuses=enemyStatusesFor(battle,enemy.id);battle.enemyStatuses[enemy.id]=statuses.filter(status=>{let damage=0;if(status.id==="poison"||status.id==="burn")damage=Math.max(1,Math.floor(enemy.maxHp*status.power));if(damage){const beforeHp=enemy.hp;enemy.hp=Math.max(0,enemy.hp-damage);results.push({enemy,id:status.id,name:status.name,damage,beforeHp,sourceMonsterId:status.sourceMonsterId??null})}status.turns--;return status.turns>0&&enemy.hp>0})});return results}
export function statusLabel(status){return`${status.name} ${status.turns}T`}
function effectMap(battle,key,id){battle[key]??={};battle[key][id]??=[];return battle[key][id]}
export function allyEffectsFor(battle,id){return effectMap(battle,"allyEffects",id)}
export function enemyEffectsFor(battle,id){return effectMap(battle,"enemyEffects",id)}
export function applyBattleEffect(battle,targetId,effect,targetType="ally"){
 if(!effect||!targetId)return false;
 const target=targetType==="enemy"?(battle.enemies??[battle.enemy]).filter(Boolean).find(entry=>entry.id===targetId):(battle.party??[]).find(entry=>entry.id===targetId);
 const resistance=targetType==="enemy"?Math.max(0,Math.min(.9,Number(target?.bossStatusResist)||0)):Math.max(0,Math.min(.9,(Number(target?._equipmentAffixes?.statusResistance)||0)/100));
 const chance=effect.chance==null?1:Math.max(0,Math.min(1,Number(effect.chance)||0));
 if((effect.chance!=null||["stun","spdDown","atkDown","defDown"].includes(effect.kind))&&Math.random()>=chance*(1-resistance))return false;
 const list=targetType==="enemy"?enemyEffectsFor(battle,targetId):allyEffectsFor(battle,targetId),existing=list.find(e=>e.kind===effect.kind);if(existing){existing.turns=Math.max(existing.turns,effect.turns??1);existing.value=Math.max(existing.value??0,effect.value??0)}else list.push({...effect,turns:effect.turns??1});return true
}
export function effectValue(battle,targetId,kind,targetType="ally"){const list=targetType==="enemy"?enemyEffectsFor(battle,targetId):allyEffectsFor(battle,targetId);return list.filter(e=>e.kind===kind).reduce((m,e)=>Math.max(m,e.value??1),0)}
export function hasEffect(battle,targetId,kind,targetType="ally"){return(targetType==="enemy"?enemyEffectsFor(battle,targetId):allyEffectsFor(battle,targetId)).some(e=>e.kind===kind)}
export function clearNegativeAllyEffects(battle,id){battle.allyEffects??={};battle.allyEffects[id]=(battle.allyEffects[id]??[]).filter(e=>!["atkDown","defDown","spdDown","poison","burn","stun","vulnerable"].includes(e.kind))}
export function tickBattleEffects(battle){for(const key of["allyEffects","enemyEffects"]){for(const[id,list]of Object.entries(battle[key]??{}))battle[key][id]=list.filter(e=>{e.turns--;return e.turns>0})}}
export function processAllyEffects(battle,statsFor){const results=[];for(const m of battle.party??[]){if(m.currentHp<=0)continue;const list=allyEffectsFor(battle,m.id),max=statsFor(m).hp;for(const e of list){if(e.kind==="regen"){const amount=Math.max(1,Math.floor(max*(e.value??.1))),before=m.currentHp;m.currentHp=Math.min(max,m.currentHp+amount);results.push({monster:m,kind:"heal",amount:m.currentHp-before})}if(e.kind==="poison"||e.kind==="burn"){const abyssTaken=Math.max(0,1+(Number(m._abyssSkillEffects?.partyDamageTakenRate)||0)),equipmentTaken=1-Math.max(0,Math.min(.75,(Number(m._equipmentAffixes?.damageReduction)||0)/100)),amount=Math.max(1,Math.floor(max*(e.value??.04)*abyssTaken*equipmentTaken));m.currentHp=Math.max(0,m.currentHp-amount);results.push({monster:m,kind:e.kind,amount})}}}return results}
