import {createRequire} from 'node:module';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {createServer} from '../build571/preview.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={errors:[],failed:[],cases:[],nativeIPhone:false};
try{browser=await chromium.launch({headless:true,executablePath:'/tmp/chromium',args:['--no-sandbox']});const page=await browser.newPage({isMobile:true,hasTouch:true,viewport:{width:390,height:740}});page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.failed.push(r.url())});
await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready&&c.lkUI511.artReady);await page.evaluate(()=>document.fonts.ready);
for(const size of [{width:390,height:740},{width:320,height:568}]){await page.setViewportSize(size);for(const [world,distance,index] of [['moon','1'+'0'.repeat(25),10],['venus','1'+'0'.repeat(27),11],['sun','1'+'0'.repeat(29),12],['graveyard','1'+'0'.repeat(32),13],['rebirth','1'+'0'.repeat(40),14]]){
 await page.evaluate(d=>{load('hand');c.state.luck.phase='chest';c.state.luck.players[0].distance=d;c.render()},distance);await page.waitForFunction(i=>c.lkUI511.sceneryLoader.status(i)==='ready',index);await page.evaluate(()=>at(0));
 assert.equal(await page.locator('[data-world-slot512="0"]').getAttribute('data-world512'),world);
 const metrics=await page.evaluate(()=>{const root=document.querySelector('.lk511'),el=document.querySelector('[data-world-slot512="0"] .lk-course508'),css=getComputedStyle(el);return{width:innerWidth,page:document.documentElement.scrollWidth,size:css.backgroundSize,repeat:css.backgroundRepeat,transform:css.transform,height:el.clientHeight,horizon:getComputedStyle(document.querySelector('[data-world-slot512="0"] .lk-horizon508')).display}});assert(metrics.page<=size.width);assert.equal(metrics.horizon,'none');assert.equal(metrics.size,'cover');assert.equal(metrics.repeat,'no-repeat');assert.equal(metrics.transform,'none');report.cases.push({world,viewport:size,...metrics});if(size.width===390)await page.screenshot({path:'docs/build573/'+world+'.png'});
}}
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{load('hand');c.state.luck.players[0].distance='1'+'0'.repeat(40);c.render()});assert.match(await page.locator('[data-world-label512]').textContent(),/宇宙の再誕/);assert.deepEqual(report.errors,[]);assert.deepEqual(report.failed,[]);
}finally{await browser?.close();await new Promise(r=>server.close(r));await writeFile('docs/build573/browser.json',JSON.stringify(report,null,2)+'\n')};console.log(JSON.stringify(report));
