import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{tmpdir}from'node:os';
const{chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const dir=fs.mkdtempSync(path.join(tmpdir(),'race451-ws-')),env={...process.env,HOST:'127.0.0.1',PORT:'18871'};
for(const[name,file]of Object.entries({FRIEND_STATE_FILE:'friends',GUILD_STATE_FILE:'guilds',POWER_RANKING_STATE_FILE:'rankings',SETTLEMENT_STATE_FILE:'settlements',WORLD_RAID_STATE_FILE:'raids',RACE_STATE_FILE:'race'}))env[name]=path.join(dir,file+'.json');
const processes=[];let browser;const errors=[],checks=[];
function launch(file,cwd,env,ready){const proc=spawn(process.execPath,[file],{cwd,env,stdio:['ignore','pipe','pipe']});processes.push(proc);return new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('startup timeout '+out)),15000);proc.stdout.on('data',b=>{out+=b;if(out.includes(ready)){clearTimeout(timer);resolve(proc)}});proc.stderr.on('data',b=>out+=b);proc.on('exit',c=>{if(c){clearTimeout(timer);reject(Error(out))}})})}
try{
 let serverProcess=await launch('server.js',path.resolve('online-server'),env,'Local:');await launch('tools/build457/preview-server.mjs',process.cwd(),process.env,'Preview457 ready');
 const executable=path.resolve('../browser445-133/chromium');fs.chmodSync(executable,0o755);browser=await chromium.launch({executablePath:executable,args:['--no-sandbox','--disable-dev-shm-usage'],env:{...process.env,LD_LIBRARY_PATH:path.dirname(executable),FONTCONFIG_FILE:process.env.RACE_QA_FONTCONFIG||process.env.FONTCONFIG_FILE}});
 const pages=[];for(const name of['えなみ','りおん','より','ひで']){const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true});await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await context.routeWebSocket('**/*',route=>new URL(route.url()).hostname==='127.0.0.1'?route.connectToServer():route.close());const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message)});await page.goto('http://127.0.0.1:18451/?name='+encodeURIComponent(name));await page.waitForFunction(()=>window.qa451?.client.ready(),{},{timeout:20000});pages.push(page)}
 const host=pages[0];await host.bringToFront();await host.locator('[data-race-action="create"]').click();await host.waitForFunction(()=>qa451.client.state?.room?.code);const code=await host.evaluate(()=>qa451.client.state.room.code);
 for(const p of pages.slice(1)){await p.locator('[name="roomCode"]').fill(code);await p.locator('[data-race-action="join"]').click();await p.waitForFunction(()=>qa451.client.state.room?.code)}
 await host.locator('[data-race-course="砂"]').click();await host.waitForFunction(()=>qa451.client.state.room.course==='砂');await host.screenshot({path:'docs/build457/sand-lobby.png'});await host.locator('[data-race-course="芝"]').click();await host.waitForFunction(()=>qa451.client.state.room.course==='芝');
 for(const p of pages)await p.locator('[data-race-monster]').first().click();await host.locator('[data-race-action="start"]').click();await host.waitForFunction(()=>qa451.client.state.room?.phase==='parade');assert.equal(await host.evaluate(()=>qa451.client.state.room.racers.length),8);assert.equal(JSON.parse(fs.readFileSync(env.RACE_STATE_FILE,'utf8')).rooms[code].outcome,null);checks.push('four authenticated clients, selectable turf/sand, no predetermined outcome');
 await host.locator('[data-race-action="pauseParade456"]').click();assert.equal(await host.locator('[data-prediction-panel]:visible').count(),1);await host.locator('[data-race-detail="news"]').click();assert.ok(await host.locator('.race-news456').isVisible());assert.equal(await host.locator('[data-bet-kind]').count(),7);await host.locator('.race-news456').screenshot({path:'docs/build457/article.png'});
 for(const width of[320,393,709,1280]){await host.setViewportSize({width,height:852});assert.ok(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const selector of['.race-news456'])assert.equal(await host.locator(selector).evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+1).length),0,selector+' '+width)}await host.setViewportSize({width:393,height:852});await host.locator('.parade-panel452').screenshot({path:'docs/build457/parade.png'});checks.push('per-monster article opens in place; pause/resume and compact observation fit 320–1280px');await host.locator('[data-race-detail="news"]').click();const heights={};for(const tab of['watch','compare','bet']){await host.locator('[data-prediction-tab="'+tab+'"]').first().click();heights[tab]=await host.evaluate(()=>document.querySelector('#app').scrollHeight);await host.screenshot({path:'docs/build457/'+tab+'.png'});assert.ok(heights[tab]<1100,tab+' height '+heights[tab]);for(const width of[320,393,709,1280]){await host.setViewportSize({width,height:740});assert.ok(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await host.locator('[data-prediction-panel="'+tab+'"] button').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+2).length),0,tab+' '+width)}await host.setViewportSize({width:393,height:740})}console.log('Panel heights',heights);fs.writeFileSync('docs/build457/panel-heights.json',JSON.stringify(heights));
 const bets=[['trifecta',[0,1,2]],['place',[4]],['wide',[5,6]],['trio',[0,4,7]]];for(let i=0;i<pages.length;i++){const p=pages[i],[kind,picks]=bets[i];await p.locator('[data-prediction-tab="bet"]').first().click();await p.locator('[data-bet-kind="'+kind+'"]').click();for(const pick of picks)await p.locator('[data-bet-pick="'+pick+'"]').click();await p.locator('[name="betAmount"]').fill('1000');assert.match(await p.locator('[data-race-quote]').textContent(),/倍/);if(i===0)await p.screenshot({path:'docs/build457/trifecta.png'});await p.locator('[data-race-action="bet"]').click();await p.waitForFunction(()=>qa451.client.state.room.members.find(m=>m.playerId===qa451.transport.selfId).ready);assert.equal(await p.evaluate(()=>qa451.save.state.player.gold),9000)}checks.push('four new ticket kinds purchased once, including three ordered selections');
 const raceId=await host.evaluate(()=>qa451.client.state.room.id);await host.waitForFunction(()=>qa451.client.state.room?.phase==='race',{},{timeout:35000});await host.evaluate(()=>window.runner456=document.querySelector('[data-race-runner]'));
 await host.locator('[data-race-action="boost456"]').click();await host.waitForFunction(()=>qa451.client.state.room.live456.runners[4].boosts===1);assert.equal(await host.locator('[data-race-action="boost456"]').isEnabled(),true);const simBefore=JSON.parse(fs.readFileSync(env.RACE_STATE_FILE,'utf8')).rooms[code].sim456;assert.equal(simBefore.runners[4].boosts,1);assert.equal(await host.evaluate(()=>qa451.client.state.room.finishMs),null);assert.equal(await host.evaluate(()=>runner456.isConnected),true);
 await new Promise(resolve=>{serverProcess.once('exit',resolve);serverProcess.kill('SIGTERM')});const frozen=JSON.parse(fs.readFileSync(env.RACE_STATE_FILE,'utf8')).rooms[code];serverProcess=await launch('server.js',path.resolve('online-server'),env,'Local:');for(const p of pages)await p.waitForFunction(()=>qa451.client.ready()&&qa451.client.state.room?.live456?.runners[4].boosts===1,{},{timeout:25000});assert.equal(await host.evaluate(()=>qa451.client.state.room.id),raceId);assert.equal(frozen.outcome,null);for(const p of pages)assert.equal(await p.evaluate(()=>qa451.save.state.player.gold),9000);checks.push('mid-race server restart preserves rapid-control windows, tickets, secret RNG and race ID');console.log('Restart OK');
 await host.evaluate(()=>qa451.client.raw('boost',{raceId:qa451.client.state.room.id,seq:1}));await host.waitForTimeout(250);assert.equal(await host.evaluate(()=>qa451.client.state.room.live456.runners[4].boosts),1);checks.push('repeated control packet does not consume a second use');
 await pages[3].evaluate(()=>{qa451.client.unmount();qa451.transport.stopBackground({disconnect:true})});
 await host.bringToFront();await host.locator('[data-race-track]').scrollIntoViewIfNeeded();const progress=await host.locator('[data-race-runner]').evaluateAll(es=>es.map(e=>parseFloat(e.style.left)));assert.ok(progress.some(x=>x>0&&x<100));const bg=await host.locator('.race-track-panel451').evaluate(e=>getComputedStyle(e).getPropertyValue('--arena452'));assert.match(bg,/race456\/turf.webp/);assert.ok(await host.evaluate(async()=>{const i=new Image();i.src='/assets/race456/turf.webp';await i.decode();return i.naturalWidth>0}));
 const burst=await host.evaluate(()=>{const before=performance.now(),b=document.querySelector('[data-race-action="boost456"]');for(let n=0;n<4;n++)b.click();return{ms:performance.now()-before,pending:qa451.client.boostPending456?.seq,label:document.querySelector('[data-boost-left]').textContent}});assert.equal(burst.pending,5);assert.ok(burst.ms<200);await host.waitForFunction(()=>qa451.client.state.room.live456.runners[4].boosts===5);await host.screenshot({path:'docs/build457/race.png',fullPage:true});console.log('Immediate burst',burst);assert.equal(await host.locator('[data-race-action="boost456"]').isDisabled(),true);checks.push('rapid four-tap burst responds under200ms without ack lock; fifth cap, stamina and turf art verified');
 for(const size of[{width:320,height:640},{width:393,height:852},{width:709,height:900}]){await host.setViewportSize(size);assert.ok(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await host.locator('.ticket-owner452,.ticket-selection452,.ticket-money452').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+1).length),0);await host.locator('[data-race-action="boost456"]').scrollIntoViewIfNeeded();const b=await host.locator('[data-race-action="boost456"]').boundingBox();assert.ok(b.y>=0&&b.y+b.height<=size.height+1)}await host.setViewportSize({width:393,height:852});await host.screenshot({path:'docs/build457/race-five-uses.png',fullPage:true});checks.push('three-number tickets and reachable control fit small touch screens');console.log('Burst controls and mobile layout OK');
 await host.waitForFunction(()=>qa451.client.state.room?.phase==='result',{},{timeout:40000});await pages[3].evaluate(()=>qa451.transport.startBackground());await pages[3].waitForFunction(()=>qa451.client.ready()&&qa451.client.state.room?.phase==='result'&&!qa451.client.bank().pending,{},{timeout:30000});assert.equal(await pages[3].evaluate(()=>qa451.client.root),null);await pages[3].evaluate(()=>qa451.client.mount(document.querySelector('#app')));
 for(const p of pages){await p.waitForFunction(()=>qa451.client.state.room?.phase==='result'&&!qa451.client.bank().pending);const row=await p.evaluate(()=>{const r=qa451.client.state.room.results.find(m=>m.playerId===qa451.transport.selfId);return{r,gold:qa451.save.state.player.gold,affection:qa451.save.state.monsters[0].affection}});assert.equal(row.gold,10000+row.r.net);assert.equal(row.affection,row.r.training.affection);assert.equal(await p.evaluate(()=>qa451.client.state.fatigue455.slime),1)}checks.push('offline player receives one payout/training/fatigue after reconnect; all wallets match published net');
 await host.locator('[data-race-action="skip452"]').click();await host.screenshot({path:'docs/build457/result.png',fullPage:true});const before=await host.evaluate(()=>JSON.stringify({gold:qa451.save.state.player.gold,applied:qa451.client.bank().applied}));await host.locator('[data-race-action="replay452"]').click();await host.locator('[data-race-action="skip452"]').click();assert.equal(await host.evaluate(()=>JSON.stringify({gold:qa451.save.state.player.gold,applied:qa451.client.bank().applied})),before);checks.push('result replay never pays twice');console.log('Four settlements OK');
 await host.locator('[data-race-action="again"]').click();await host.waitForFunction(()=>qa451.client.state.room?.phase==='lobby');assert.equal(await host.evaluate(()=>qa451.client.state.room.course),'砂');await host.locator('[data-race-action="start"]').click();await host.waitForFunction(()=>qa451.client.state.room.phase==='parade');for(const p of pages){await p.locator('[data-prediction-tab="bet"]').first().click();await p.locator('[data-race-action="pass"]').click();}await host.waitForFunction(()=>qa451.client.state.room.phase==='race',{},{timeout:35000});assert.match(await host.locator('.race-track-panel451').evaluate(e=>getComputedStyle(e).getPropertyValue('--arena452')),/race453\/sand.png/);await host.screenshot({path:'docs/build457/sand-race.png',fullPage:true});checks.push('next race automatically alternates to sand with distinct track artwork');
 assert.deepEqual(errors,[]);fs.writeFileSync('docs/build457/browser-results.json',JSON.stringify({checks,errors,mobileWidths:[320,393,709],transport:'native authenticated OnlinePartyController / real local server',limitations:'Physical iPhone Safari and missing unchanged base monster sprites not re-audited'},null,2));console.log(JSON.stringify({checks,errors}));
}finally{await browser?.close();for(const p of processes)p.kill();fs.rmSync(dir,{recursive:true,force:true})}
