import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{tmpdir}from'node:os';
const{chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const dir=fs.mkdtempSync(path.join(tmpdir(),'race451-ws-')),env={...process.env,HOST:'127.0.0.1',PORT:'18871'};
for(const[name,file]of Object.entries({FRIEND_STATE_FILE:'friends',GUILD_STATE_FILE:'guilds',POWER_RANKING_STATE_FILE:'rankings',SETTLEMENT_STATE_FILE:'settlements',WORLD_RAID_STATE_FILE:'raids',RACE_STATE_FILE:'race'}))env[name]=path.join(dir,file+'.json');
const processes=[];let browser;const errors=[],checks=[];
function launch(file,cwd,env,ready){const proc=spawn(process.execPath,[file],{cwd,env,stdio:['ignore','pipe','pipe']});processes.push(proc);return new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('startup timeout '+out)),15000);proc.stdout.on('data',b=>{out+=b;if(out.includes(ready)){clearTimeout(timer);resolve(proc)}});proc.stderr.on('data',b=>out+=b);proc.on('exit',c=>{if(c){clearTimeout(timer);reject(Error(out))}})})}
try{
 let serverProcess=await launch('server.js',path.resolve('online-server'),env,'Local:');await launch('tools/build457/preview-server.mjs',process.cwd(),process.env,'Preview457 ready');
 const executable=path.resolve('../browser445-133/chromium');fs.chmodSync(executable,0o755);browser=await chromium.launch({executablePath:executable,args:['--no-sandbox','--disable-dev-shm-usage'],env:{...process.env,LD_LIBRARY_PATH:path.dirname(executable),FONTCONFIG_FILE:process.env.RACE_QA_FONTCONFIG||process.env.FONTCONFIG_FILE}});

 const context=await browser.newContext({viewport:{width:393,height:740},isMobile:true,hasTouch:true});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.routeWebSocket('**/*',r=>new URL(r.url()).hostname==='127.0.0.1'?r.connectToServer():r.close());const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:18451/');await page.waitForFunction(()=>window.qa451?.client.ready());
 await page.locator('[data-race-action="create"]').click();await page.waitForFunction(()=>qa451.client.state.room);await page.locator('[data-race-monster]').first().click();await page.waitForFunction(()=>qa451.client.state.room.members[0].choice);
 const cdp=await context.newCDPSession(page);async function swipe(){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:5,y:600}]});for(let i=1;i<=12;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:5,y:600-i*35}]});await page.waitForTimeout(18)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(900)}
 await page.evaluate(()=>document.querySelector('#app').scrollTop=0);for(let i=0;i<8;i++){const b=await page.locator('[data-race-action="start"]').boundingBox();if(b.y>=0&&b.y+b.height<=740)break;await swipe()}
 const start=await page.locator('[data-race-action="start"]').boundingBox();assert.ok(start.y>=0&&start.y+start.height<=740);assert.equal(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.closest('button')?.dataset.raceAction,{x:start.x+start.width/2,y:start.y+start.height/2}),'start');await page.touchscreen.tap(start.x+start.width/2,start.y+start.height/2);await page.waitForFunction(()=>qa451.client.state.room.phase==='parade');checks.push('touch scroll still reaches start with fatigue labels');
 await page.locator('[data-race-detail="news"]').click();assert.ok(await page.locator('.race-news456').isVisible());assert.ok(await page.evaluate(()=>qa451.client.paradePinned!==null));await page.locator('[data-race-detail="stats"]').click();assert.ok(await page.locator('.detail-body457').isVisible());assert.match(await page.locator('.detail-body457').textContent(),/待ち時間なし/);const observed=await page.evaluate(()=>qa451.client.paradePinned);
 await page.locator('[data-prediction-tab="bet"]').first().click();await page.locator('[data-bet-kind="trifecta"]').click();for(const i of[1,3,7])await page.locator('[data-bet-pick="'+i+'"]').click();await page.locator('[name="betAmount"]').fill('1234');await page.locator('[data-prediction-tab="compare"]').first().click();assert.equal(await page.locator('.race-form-row455:visible').count(),8);await page.locator('.race-form-row455').nth(2).click();assert.ok(await page.locator('[data-prediction-panel="watch"]').isVisible());await page.locator('[data-prediction-tab="bet"]').first().click();assert.deepEqual(await page.evaluate(()=>qa451.client.draft.ticket),{kind:'trifecta',picks:[1,3,7]});assert.equal(await page.locator('[name="betAmount"]').inputValue(),'1234');checks.push('all observation details available; comparison row opens monster; ticket kind, order and amount survive tab switches');
 const bounds=await page.locator('.race457>header button,.prediction-tabs457 button').evaluateAll(es=>es.map(e=>({text:e.textContent.trim(),x:e.getBoundingClientRect().x,right:e.getBoundingClientRect().right})));assert.ok(bounds.every(x=>x.x>=0&&x.right<=393),JSON.stringify(bounds));await page.locator('[data-race-action="bet"]').scrollIntoViewIfNeeded();const purchase=await page.locator('[data-race-action="bet"]').boundingBox();assert.ok(purchase.y>=0&&purchase.y+purchase.height<=740);await page.touchscreen.tap(purchase.x+purchase.width/2,purchase.y+purchase.height/2);await page.waitForFunction(()=>qa451.client.state.room.members[0].ready);await page.waitForFunction(()=>qa451.client.state.room.phase==='race',{},{timeout:30000});
 await page.waitForFunction(()=>qa451.client.state.room.live456?.elapsed>=3000);const before=await page.locator('[data-race-runner]').evaluateAll(es=>es.map(e=>e.style.left));await page.locator('[data-race-camera="follow"]').click();assert.ok(await page.locator('.is-follow457').count());const after=await page.locator('[data-race-runner]').evaluateAll(es=>es.map(e=>e.style.left));assert.notDeepEqual(after,before);assert.equal(await page.locator('[data-order-runner457]').count(),8);await page.screenshot({path:'docs/build457/follow-camera.png'});await page.locator('[data-race-camera="full"]').click();assert.equal(await page.locator('.is-follow457').count(),0);assert.equal(await page.evaluate(()=>qa451.client.state.room.live456.runners[4].boosts),0);checks.push('full/follow camera changes only presentation, retains eight ranks and never uses a boost');
 await page.locator('[data-race-action="boost456"]').scrollIntoViewIfNeeded();const control=await page.locator('[data-race-action="boost456"]').boundingBox();for(let n=0;n<5;n++)await page.touchscreen.tap(control.x+control.width/2,control.y+control.height/2);await page.waitForFunction(()=>qa451.client.state.room.live456.runners[4].boosts===5);assert.equal(await page.locator('[data-race-action="boost456"]').isDisabled(),true);assert.match(await page.locator('[data-boost-left]').textContent(),/残り 0/);checks.push('five real touchscreen taps are accepted without a cooldown; the sixth is disabled');
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('[data-race-runner]').first().evaluate(e=>getComputedStyle(e,':after').animationName),'none');checks.push('reduced-motion preference disables added burst loops');assert.deepEqual(errors,[]);
 fs.writeFileSync('docs/build457/touch-results.json',JSON.stringify({checks,bounds,errors,font:'Noto Sans CJK JP',browser:'Chromium mobile touch; physical iPhone Safari not tested'},null,2));console.log(JSON.stringify({checks,errors}));

}finally{await browser?.close();for(const p of processes)p.kill();fs.rmSync(dir,{recursive:true,force:true})}
