// Local UI fixtures exercise production renderer/engine; not shipped as game runtime.
import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';import{spawn}from'node:child_process';import fs from'node:fs';import assert from'node:assert/strict';
const server=spawn(process.execPath,['tools/build463/isolated-preview.mjs'],{env:{...process.env,SG_FONT_DIR:process.env.SG_FONT_DIR??'../qa-deps/node_modules/@fontsource/noto-sans-jp'},stdio:['ignore','pipe','pipe']});await new Promise((r,j)=>{server.stdout.on('data',b=>{if(String(b).includes('Isolated preview ready'))r()});server.stderr.on('data',b=>j(Error(String(b))))});
const browser=await chromium.launch({executablePath:process.env.QA_CHROMIUM??'../qa-deps/runtime/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[],checks=[];let page;
try{
 page=await browser.newPage({viewport:{width:393,height:694},isMobile:true,hasTouch:true});page.on('pageerror',e=>errors.push(e.stack));await page.goto('http://127.0.0.1:18451/?name=p4');await page.waitForFunction(()=>window.qa451?.client.ready());await page.evaluate(()=>document.fonts.ready);
 await page.evaluate(async()=>{const E=await import('/src/sugoroku/Engine463.js'),c=qa451.client;window.E465=E;qa451.transport.ws.onmessage=()=>{};c.refresh=()=>{};c.connected=()=>true;c.offset=0;const g=E.makeLobby463({id:'show465',seed:3,members:[{playerId:'p4',name:'あなた'}]});E.start463(g,Date.now());g.step='pre';g.players.forEach((p,i)=>{p.choice={speciesId:['slime','wolf','ember_slime','goblin'][i]};p.name=['あなた','月影の狼','火花のスライム','いたずら悪魔'][i];p.pos=''+(10+i*2);p.trail=Array.from({length:11+i*2},(_,n)=>''+n)});const p=g.players[0];g.discard.push(...p.hand);p.hand=[];for(const id of ['yori-0','rion-6','guard','treasure','curse-heavy']){const uid=Object.keys(g.cards).find(u=>g.cards[u]===id);if(!uid)continue;g.deck=g.deck.filter(x=>x!==uid);g.discard=g.discard.filter(x=>x!==uid);g.players.forEach(x=>x.hand=x.hand.filter(x=>x!==uid));p.hand.push(uid)}window.g465=g;window.show465=()=>{c.state.sugoroku=E.public463(g,'p4');c.state.party={id:'party465',code:'SHOW65',hostId:'p4',members:g.members};c.partyBrowse462=false;c.render()};window.idle465=()=>{if(c.sgFX464?.raf)cancelAnimationFrame(c.sgFX464.raf);c.sgFX464=null;g.pending=null;c.sgUI463.modal=null;show465()};show465();});
 await page.waitForTimeout(500);const sizes=await page.evaluate(()=>({board:document.querySelector('.sg-viewport').getBoundingClientRect().height,hand:document.querySelector('.sg-hand-section').getBoundingClientRect().height,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth}));assert.ok(sizes.board>=sizes.height*.39,JSON.stringify(sizes));assert.equal(sizes.overflow,false);await page.screenshot({path:'docs/build467/mobile-adventure.png',fullPage:true});checks.push({layout:sizes});
 await page.evaluate(()=>{E465.present464(g465,'card',{actorId:g465.players[1].playerId,cardId:'rion-6'});show465()});await page.waitForTimeout(250);let box=await page.locator('.sg-flip464').boundingBox();assert.ok(box.width>=120&&box.height>=180,JSON.stringify(box));await page.screenshot({path:'docs/build467/card-back-mobile.png',fullPage:true});await page.waitForTimeout(1800);await page.screenshot({path:'docs/build467/card-face-mobile.png',fullPage:true});assert.ok(await page.locator('.sg-caster465 .sg-monster').count());const start=await page.evaluate(()=>qa451.client.sgFX464.active.start);await page.evaluate(()=>show465());assert.equal(await page.evaluate(()=>qa451.client.sgFX464.active.start),start);box=await page.locator('.sg-flip464').boundingBox();assert.ok(box.width>=120&&box.height>=180);checks.push('nonzero card back/front at 393px including rerender; caster portrait visible');
 await page.evaluate(()=>idle465());await page.evaluate(()=>{E465.present464(g465,'effect',{actorId:g465.players[1].playerId,targetIds:['p4'],cardId:'rion-6',effectType:'move',n:-2,harmful:true});show465()});await page.waitForTimeout(200);assert.equal(await page.locator('.sg-effect-people465 .sg-event-pawn465').count(),2);assert.ok(await page.locator('.sg-seat.sg-target464').count());await page.screenshot({path:'docs/build467/attack-mobile.png',fullPage:true});checks.push('attacker and target characters / names / arrow / effect visible');
 await page.evaluate(()=>idle465());await page.evaluate(()=>{g465.players[0].pos='7';g465.pending={id:81,playerId:'p4',kind:'fork',prompt:'どちらの道を進む？',options:[{value:'8',label:'近道を進む'},{value:'b7-0',label:'宝庫へ寄り道'}],data:{}};show465()});await page.waitForTimeout(400);assert.equal(await page.locator('.sg-route465').count(),2);await page.screenshot({path:'docs/build467/fork-mobile.png',fullPage:true});checks.push('illustrated branch choice with lengths and upcoming rewards');
 await page.evaluate(()=>idle465());await page.evaluate(()=>{g465.pending={id:82,playerId:'p4',kind:'discard',prompt:'捨てるカードを2枚選ぶ',options:g465.players[0].hand.map(u=>({value:u,label:E465.definition463(g465,u).name,cardId:g465.cards[u]})),data:{remaining:1,effect:{actor:'p4',target:'p4',source:'tile',tile:'10'}}};show465()});await page.locator('[data-sg-action="discardPick467"]').nth(1).click();assert.ok(await page.locator('.sg-choice-card465.is-picked').count());assert.equal(await page.locator('.sg-choice-confirm465 button').isDisabled(),false);await page.screenshot({path:'docs/build467/discard-mobile.png',fullPage:true});checks.push('discard is a physical card selection then confirmation');
 await page.evaluate(()=>idle465());await page.locator('[data-sg-action="gameMenu465"]').click();await page.locator('[data-sg-action="restartConfirm465"]').click();await page.screenshot({path:'docs/build467/restart-mobile.png',fullPage:true});assert.ok(await page.locator('[data-sg-action="restartSolo465"]').isVisible());checks.push('solo restart confirmation reachable from header');
 await page.evaluate(()=>idle465());await page.locator('[data-sg-action="mapWide"]').click();await page.waitForTimeout(400);assert.equal(await page.locator('.sg-hand-section').isVisible(),false);await page.screenshot({path:'docs/build467/map-expanded-mobile.png',fullPage:true});await page.locator('[data-sg-action="mapWide"]').click();
 await page.setViewportSize({width:320,height:667});await page.evaluate(()=>show465());await page.waitForTimeout(450);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>{E465.present464(g465,'card',{actorId:g465.players[1].playerId,cardId:'rion-6'});show465()});await page.waitForTimeout(1700);box=await page.locator('.sg-flip464').boundingBox();assert.ok(box.width>=120&&box.height>=180);await page.screenshot({path:'docs/build467/narrow-card.png',fullPage:true});
 await page.evaluate(()=>idle465());await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>show465());await page.waitForTimeout(450);await page.screenshot({path:'docs/build467/desktop-adventure.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{idle465();E465.present464(g465,'card',{actorId:g465.players[1].playerId,cardId:'rion-6'});show465()});await page.waitForTimeout(200);assert.equal(await page.locator('.sg-flip-inner464').evaluate(el=>getComputedStyle(el).animationName),'none');assert.ok((await page.locator('.sg-flip464').boundingBox()).height>=180);assert.deepEqual(errors,[]);checks.push('320px, 393px and desktop; reduced motion remains readable');fs.writeFileSync('docs/build467/visual-results.json',JSON.stringify({checks,errors,scope:'Production renderer and public engine in isolated local fixture. Physical iPhone Safari not available.'},null,2));console.log('visual checks passed',checks);
}catch(e){console.log('page errors',errors);await page?.screenshot({path:'docs/build467/failure.png',fullPage:true});throw e}finally{await browser.close();server.kill()}
