import {endgameCharacter} from '../data/endgameCharacters.js';
import {chapterTwoRepeatTicket395} from './ChapterTwoRepeat395.js?v=3.1.82-build402';
import {relicDropPreview394,circleDropPreview394} from '../ui/ChapterTwoRelics394.js?v=3.1.78-build398';
import {CHAPTER_TWO_ELITE_SQUADS393,CHAPTER_TWO_ELITE_TIERS393,chapterTwoEliteUnlockedTier393,chapterTwoEliteTier393} from './ChapterTwoElite393.js?v=3.1.73-build393';
import {chapterTwoEnemyEntries,ENCOUNTERS} from './ChapterTwoSystem.js?v=3.1.82-build402';
import {SPECIES} from '../data/species.js';
import {monsterVisual} from '../ui/MonsterVisual.js?v=3.1.82-build402';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function chapterTwoElitePanel393(state,area){
 const p=state.chapterTwo376,unlocked=chapterTwoEliteUnlockedTier393(p,area);if(!unlocked)return '';
 const r=p.runs378?.[area],canStart=!!r?.completed,tier=unlocked,current=chapterTwoEliteTier393(r),cleared=Math.max(0,Math.min(3,Number(p.eliteClears393?.[area])||0));
 const squads=CHAPTER_TWO_ELITE_SQUADS393.filter(s=>s.area===area).map(s=>({...s,...ENCOUNTERS[s.id]}));
 return `<details class="elite393-panel"><summary>精鋭再探索 <span>3部隊の連携に挑戦</span></summary><p>各部隊から固有装備を確定入手。3部隊制圧で専用魔法陣と追加装備を獲得し、次の段階が解放されます。第二章の魔物は捕獲できます。深淵・十神の指揮官は捕獲できません。</p>${chapterTwoRepeatTicket395(state)?.area===area?`<button type="button" data-depart-repeat395>段階${current}・${CHAPTER_TWO_ELITE_TIERS393[current].name}でもう一度（3部隊を再配置）</button>`:''}${current?`<button type="button" data-depart-elite-resume>段階${current}・${CHAPTER_TWO_ELITE_TIERS393[current].name}を再開（${r.roaming380.length}/3部隊討伐）</button>`:''}<div class="elite393-tiers">${[1,2,3].map(t=>`<button type="button" data-depart-elite="${t}" ${!canStart||t>unlocked?'disabled':''}><b>${t}・${CHAPTER_TWO_ELITE_TIERS393[t].name}${cleared>=t?' ✓':''}</b><small>${t>unlocked?'前段階の3部隊討伐で解放':`GOLD・経験値 ×${CHAPTER_TWO_ELITE_TIERS393[t].reward} ／ ${t===1?'LR':'神話'}装備＋${CHAPTER_TWO_ELITE_TIERS393[t].plus}`}</small></button>`).join('')}</div>${canStart?'':'<p>進行中のこの地域を踏破すると挑戦できます。</p>'}<p>開始すると精鋭の3部隊を再配置します。HP・MPは引き継ぎます。途中で帰還しても「再開」で討伐状況を続けられます。</p>${circleDropPreview394(area)}<small>部隊紹介：段階${tier}・${CHAPTER_TWO_ELITE_TIERS393[tier].name}</small><div class="elite393-squads">${squads.map(s=>{const units=chapterTwoEnemyEntries(s.id,{eliteTier393:tier});return `<article><h4>${esc(s.name)}</h4><div class="elite393-members">${units.map(u=>`<div>${monsterVisual(u,'✦',{className:'elite393-portrait'})}<b>${esc(endgameCharacter(u.endgameBossId)?.name??SPECIES[u.speciesId].name)}</b><small>${esc(u.faction==='tenGod'?'十神':u.faction==='abyss'?'深淵':SPECIES[u.speciesId].rarity)}・Lv.${u.level.toLocaleString()}</small><small>${esc(u.enemyMagicCircle.name)} Lv.${u.enemyMagicCircle.level}</small></div>`).join('')}</div><p>${esc(s.hint)}</p>${relicDropPreview394(s.id,tier)}<details><summary>装備の組み合わせを見る</summary>${units.map(u=>`<div class="elite393-gear"><b>${esc(endgameCharacter(u.endgameBossId)?.name??SPECIES[u.speciesId].name)}</b><small>${esc(u.enemyEquipmentRarity)}・装備Lv.${u.enemyEquipmentLevel.toLocaleString()} ＋${u.enemyGear[0].plus}</small><p>${u.enemyGear.map(g=>esc(g.name)).join(' ／ ')}</p></div>`).join('')}</details></article>`;}).join('')}</div></details>`;
}
