import {chapterTwoState,ROOMS,ENCOUNTERS} from './ChapterTwoSystem.js?v=3.1.56-build376';
import {monsterVisual} from '../ui/MonsterVisual.js?v=3.1.48-build368';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function ChapterTwoScreen(state,{field=false}={}){
 const p=chapterTwoState(state);if(!p)return '';
 const r=p.run,room=r?ROOMS[r.room]:ROOMS[0],seals=r?['west','east'].filter(id=>r.defeated.includes(id)).length:0;
 const header=`<header class="chapter-two-header"><button type="button" data-ch2-home>‹ 魔王城へ</button><div><small>ABYSS DOMINION / CHAPTER II</small><h1>理の外に生きる者たち</h1></div></header>`;
 if(!field||!r)return`<section class="chapter-two-screen">${header}<main class="chapter-two-hub"><section class="chapter-two-hero"><small>第二章・序章</small><h2>境界の森</h2><p>勇者を退けた世界に、黒い根が伸びる。<br>旧魔王と勇者、それぞれが守るもののために。</p><div class="chapter-two-cast">${['slime','myth_enami','myth_yori','myth_hide','myth_rion'].map(speciesId=>monsterVisual({speciesId},'',{className:'chapter-two-portrait'})).join('')}</div></section><section class="chapter-two-panel"><h3>${p.introComplete?'森への道が開いた':'勝利の、その先へ'}</h3><button type="button" data-ch2-story="intro">${p.introComplete?'序章を読み返す':'序章を読む'}</button><p>6区画を探索し、2つの封印樹を解放して最深部へ。各戦闘で経験値とGOLDを獲得できます。</p><small>部隊Lv.1000以上が目安。回復役の護衛を先に倒すと攻略しやすくなります。</small><button type="button" class="chapter-two-primary" data-ch2-enter ${p.introComplete?'':'disabled'}>${r?'探索を再開する':'森へ出発する'}</button>${r?`<button type="button" data-ch2-new>新しく再探索する</button><small>この森の敵・宝箱・封印が再配置されます。</small>`:''}<button type="button" data-ch2-formation>部隊を整える</button></section>${p.clears?`<section class="chapter-two-panel"><h3>境界の森・解放済み</h3><p>踏破 ${p.clears}回。再探索でも戦闘報酬を獲得できます。</p><button type="button" data-ch2-story="epilogue">${p.epilogueComplete?'森の結末を読み返す':'森の結末を読む'}</button><small>今回遊べる物語はここまで。次の舞台へ続きます。</small></section>`:''}</main></section>`;
 return`<section class="chapter-two-screen chapter-two-field">${header}<div class="chapter-two-room"><div><small>境界の森・${r.room+1}/6区画</small><h2>${room.name}</h2></div><b>封印解放 ${seals}/2</b><button type="button" data-ch2-center aria-label="部隊を画面中央へ">中央へ</button></div><div class="chapter-two-map">${ROOMS.map(v=>`<span class="${v.id===r.room?'current':''} ${r.visited.includes(v.id)?'visited':''}">${v.id+1} ${v.name}</span>`).join('')}</div><div class="chapter-two-stage"><canvas id="chapterTwoCanvas" aria-label="移動先をタップして探索。矢印キーでも移動できます。" tabindex="0"></canvas></div><footer class="chapter-two-field-footer"><b>${r.completed?'侵食を鎮めた。魔王城で森の結末を読めます。':room.hint}</b><small>行き先をタップで移動／ドラッグで視点移動／2本指で拡大</small><div>${Object.entries(room.links).map(([direction,id])=>`<button type="button" data-ch2-door="${direction}">${{north:'北',south:'南',east:'東',west:'西'}[direction]}：${ROOMS[id].name}</button>`).join('')}</div></footer></section>`;
}
export function chapterTwoDialogueMarkup(line,index,total){const [name,speciesId,text]=line;return`<div class="chapter-two-dialogue">${speciesId?monsterVisual({speciesId},'',{className:'chapter-two-speaker'}):''}<small>${index+1} / ${total}</small><h3>${esc(name)}</h3><p>${esc(text)}</p></div>`;}
