import * as B from '../../src/bomb/View542.js';import {signature542} from '../../src/bomb/Rules542.js';import{applyPlayerColors542}from '../../src/party/PlayerColors542.js';
import * as C from '../../src/canal/View489.js';import * as T from '../../src/tetra/View539.js';import * as H from '../../src/hide/View536.js';import * as F from '../../src/fishing/View524.js';import * as G from '../../src/gorilla/View505.js';import * as L from '../../src/luck/View511.js';
import {signature539} from '../../src/tetra/Rules539.js';import{signature536}from '../../src/hide/Rules536.js';import{signature524}from '../../src/fishing/Rules524.js';
import {partyHub462,partyClick462} from '../../src/party/PartyView462.js';import {resultClick490,resultReceive490,resultError490} from '../../src/party/PartyResults490.js';import {monsterVisual} from '../../src/ui/MonsterVisual.js';
const configs={bomb:[B,'bomb','542'],canal:[C,'canal','489'],tetra:[T,'tetra','539'],hide:[H,'hide','536'],fishing:[F,'fishing','524'],gorilla:[G,'gorilla','505'],luck:[L,'luck','511']};const root=document.querySelector('#app'),selfId=new URL(location.href).searchParams.get('self')??'p0',roster=['slime','wolf','goblin','skeleton'].map((speciesId,i)=>({id:'m'+i,speciesId}));
const kind=()=>Object.keys(configs).find(k=>c.state[k]),action=(what,...args)=>{const a=configs[kind()];return a?.[0][a[1]+what+a[2]]?.(c,...args)};
const c=window.c={root,transport:{selfId},state:{},offset:0,error:'',draft:{code:''},partyBrowse462:false,selectedGame462:'tetra',roster:()=>roster,sgSpeciesName463:id=>({slime:'スライム',wolf:'ウルフ',goblin:'ゴブリン',skeleton:'スケルトン'})[id]??id,sgMonster463:id=>'<span class="sg-monster">'+monsterVisual({speciesId:id})+'</span>',displayName:()=>['えなみ','りおん','より','ひで'][Number(selfId.slice(1))],connected:()=>socket.readyState===1,ready:()=>socket.readyState===1,connectionMessage:()=>'',toast:()=>{},
 render(){for(const [module,k,v]of Object.values(configs))module[k+'Before'+v]?.(c);root.innerHTML=kind()&&!c.partyBrowse462?action('View'):partyHub462(c);applyPlayerColors542(c);if(kind()&&!c.partyBrowse462)action('After')},refresh(){c.raw('status')},
 raw(op,p={}){(window.qaSent??=[]).push({op,...p,at:Date.now()+c.offset});if(socket.readyState!==1)return false;socket.send(JSON.stringify({op,bombVersion542:1,rulesVersion:8,tetraVersion539:3,hideVersion536:5,fishingFrames540:1,canalVersion489:1,canalRules492:1,canalRules494:1,canalRules496:1,canalRules500:1,canalRules541:1,minigamesVersion528:1,fishingVersion524:8,sumoVersion523:3,towerVersion517:5,quizVersion514:1,luckVersion511:1,luckVersion509:1,luckVersion508:1,luckVersion507:1,gorillaVersion502:1,gorillaRules503:1,gorillaRules504:1,gorillaRules505:1,roster,...p}));return true}};
let signature='';const socket=new WebSocket(location.origin.replace('http','ws')+'/socket?self='+selfId);window.socketQA=socket;
socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='bombFrame542'){B.bombFrame542(c,m);return}if(m.type==='tetraFrame539'){T.tetraFrame539(c,m);return}if(m.type==='hideFrame536'){H.hideFrame536(c,m);return}if(m.type==='fishingFrame524'){F.fishingFrame524(c,m);return}if(m.type==='raceError451'){resultError490(c,m);c.error=m.message;c.render();return}if(m.type!=='raceState451')return;const old=c.state[kind()]?.id;c.offset=m.serverNow-Date.now();c.state=m;const k=kind(),g=m[k];if(old!==g?.id)c.partyBrowse462=false;c.selectedGame462=k;action('Receive');resultReceive490(c);const sig=k==='bomb'?signature542(g):k==='tetra'?signature539(g):k==='hide'?signature536(g):k==='fishing'?signature524(g):g?{id:g.id,phase:g.phase,members:g.members}:null;const party=m.party?{...m.party,phase:g&&!['lobby','result'].includes(g.phase)?'play':m.party.phase}:null;const next=JSON.stringify({g:sig,p:party,error:c.error});if(next!==signature){signature=next;c.render()}window.qaReady=true};
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(resultClick490(c,b)||action('Click',b,e)||partyClick462(c,b))return});root.addEventListener('input',e=>action('Input',e.target));root.addEventListener('keydown',e=>action('Key',e));
const tick=()=>{action('Tick');requestAnimationFrame(tick)};tick();window.disposeQA=()=>{for(const [m,k,v]of Object.values(configs))m[k+'Dispose'+v]?.(c);socket.close()};
