import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
const root=resolve(new URL('../../',import.meta.url).pathname);
export const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>${process.env.QA_FONT?"@font-face{font-family:'Noto Sans JP';src:url('/qa-font.ttf')}":''}body{margin:0;background:#082d32;color:#fff1cf;font-family:'Noto Sans JP',sans-serif}button,input{font:inherit}.sg-monster{display:inline-block;width:40px;height:40px}button{cursor:pointer}</style><link rel="stylesheet" href="/src/Styles/build563-arcade.css"><link rel="stylesheet" href="/src/Styles/build566-crane.css"><main id="root"></main><script type="module">
import * as rules from '/src/crane566/Rules566.js';import * as view from '/src/crane566/View566.js';import {screen566} from '/src/crane566/Board566.js';import {members} from '/tools/build563/fixture.mjs';
window.c={root:document.querySelector('#root'),state:{},transport:{selfId:'p0'},offset:0,error:'',ready:()=>true,connected:()=>true,roster:()=>members().map(p=>p.choice),sgSpeciesName463:x=>({slime:'スライム',goblin:'ゴブリン',wolf:'ウルフ',skeleton:'スケルトン'}[x]??x),refresh:()=>{}};
let timer;window.sent=[];window.rules=rules;
c.raw=(op,m)=>{sent.push({op,...m});if(op==='craneInput566'){const p=rawGame.players.find(p=>p.playerId===c.transport.selfId);const ok=rules.inputCrane566(rawGame,p,m);sync();return ok;}if(m.kind==='select'){rawGame.members.find(p=>p.playerId===c.transport.selfId).choice=c.roster().find(p=>p.id===m.monsterId);sync();c.render();}return true;};
c.render=()=>{view.craneBefore566(c);c.root.innerHTML=view.craneView566(c);view.craneAfter566(c);};c.root.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.disabled)view.craneClick566(c,b)});c.root.addEventListener('keydown',e=>view.craneKey566(c,e));c.root.addEventListener('input',e=>view.craneInput566(c,e.target));
window.sync=()=>{const old=c.state.crane?.phase;c.craneUI566??={seq:0,sound:false,seen:0,limit:24,search:''};c.craneUI566.previous=c.state.crane;c.state.crane=rules.publicCrane566(rawGame);view.craneReceive566(c);if(old&&old!==rawGame.phase)c.render();};
window.freeze=()=>clearInterval(timer);
window.run=()=>{freeze();timer=setInterval(()=>{rules.advanceCrane566(rawGame,Date.now());sync();},25);};
window.load=(phase='play',self=0,count=1)=>{freeze();view.craneBefore566(c);c.transport.selfId='p'+self;c.offset=0;window.sent=[];const people=members().slice(0,count);window.rawGame=rules.makeCrane566({id:'preview-'+Date.now(),code:'TEST',partyId:'party',hostId:'p0',members:people,now:Date.now()-3000});c.state.party={id:'party',hostId:'p0',members:people.map(p=>({...p,ready:true,connected:true}))};if(phase!=='lobby'){rules.startCrane566(rawGame,Date.now()-3000,566);for(let t=rawGame.lastAt+25;t<=Date.now();t+=25)rules.advanceCrane566(rawGame,t);}sync();c.render();if(phase==='play')run();};
window.advance=ms=>{const until=rawGame.lastAt+ms;for(let t=rawGame.lastAt+25;t<=until;t+=25)rules.advanceCrane566(rawGame,t);c.offset=rawGame.lastAt-Date.now();sync();};
window.targetPoint=(x,y)=>{const rect=document.querySelector('[data-cr-canvas]').getBoundingClientRect(),q=screen566(c.craneUI566.renderer,x,y,rawGame.players.find(p=>p.playerId===c.transport.selfId)?.seat??0);return{x:q.x+rect.x,y:q.y+rect.y};};
window.finish=()=>{freeze();rules.finishCrane566(rawGame);sync();};
// A deterministic presentation fixture: all motion, captures and scoring run through production rules.
window.stealDemo=(mimic=false)=>{load('play',0,4);freeze();rawGame.players.forEach((p,i)=>{p.score=[11,14,23,16][i];p.ai=false;});rawGame.loot=rawGame.loot.filter(v=>Math.abs(v.x)>2.4);const v=rules.spawnLoot566(rawGame,mimic?'mimic':'crown');Object.assign(v,{x:0,y:-1,owner:2,lockUntil:0});rawGame.players[2].hook={x:0,y:-1,phase:'back',itemId:v.id,angle:Math.PI/2,travel:7};rawGame.lastAt=Date.now();rawGame.deadline=Date.now()+61000;sync();c.render();};
load(new URLSearchParams(location.search).get('phase')??'play');window.ready=true;
</script></html>`;
export function createServer(){return http.createServer(async(req,res)=>{try{const p=new URL(req.url,'http://local').pathname;if(p==='/'){res.setHeader('Content-Type','text/html');return res.end(html);}if(p==='/favicon.ico'){res.writeHead(204);return res.end();}if(p==='/src/party/PartyView462.js'){res.setHeader('Content-Type','text/javascript');return res.end('export const partySeats462=()=>"";');}const file=p==='/qa-font.ttf'?process.env.QA_FONT:resolve(root,p.slice(1));if(p!=='/qa-font.ttf'&&!file.startsWith(root+'/'))throw Error('bad path');const bytes=await readFile(file);res.setHeader('Content-Type',{'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.ttf':'font/ttf'}[extname(file)]??'application/octet-stream');res.end(bytes);}catch(e){res.writeHead(404);res.end(String(e));}});}
if(process.argv.includes('--serve'))createServer().listen(8566,'127.0.0.1',()=>console.log('http://127.0.0.1:8566'));
