import{rivalContent460,enhanceBroadcast460,placeCourseRunners460}from'./RaceExperience460.js';
import{COURSES459,course459,courseLabel459,coursePoint459,distance459,bond459,temperament459,monsterHistory459}from'./RaceCourse459.js';
import{monsterVisual,setMonsterVisualFrame}from'../ui/MonsterVisual.js';
import{tactic456}from'./RaceSimulation456.js';
import{fatigueLabel455}from'./RaceStrategy455.js';
import{LANE_COLORS452}from'./RacePresentation452.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=x=>monsterVisual({speciesId:x.speciesId,visualSpeciesId:x.speciesId},'◆',{className:'race-art451'});
export function courseSelector459(r,c){if(r.rulesVersion<7)return'<p class="course-note459">新しい部屋では距離・周回を選べます。</p>';const track=course459(r.track459);return`<div class="distance-select459 distance-compact460" aria-label="レース距離">${COURSES459.map(x=>`<button data-race-distance459="${x.distance}" aria-label="${x.distance}m・${x.shape==='oval'?x.laps+'周':'直線'}" aria-pressed="${x.distance===track.distance}" ${r.phase==='lobby'&&r.hostId===c.transport.selfId?'':'disabled'}><b>${x.distance}<small>m</small></b><small>${x.shape==='oval'?x.laps+'周':'直線'}</small></button>`).join('')}</div><p class="course-note459"><b>${track.name}</b> · ${track.hint}</p>`}
export function historySummary459(rows){if(!rows?.length)return'<span class="form-empty459">出走記録なし</span>';const x=rows[0];return`<span class="form-last459">前走 <b>${x.place}着</b> <small>${esc(x.course)} ${x.distance}m</small></span><span class="form-five459">近走 ${rows.slice(0,5).map((v,i)=>`<b title="${i+1}走前：${esc(v.course)} ${v.distance}m" class="place-${v.place}">${v.place}</b>`).join('')}<small>←新</small></span>`}
export function historyDetails459(rows,key){if(!rows?.length)return'<p class="form-empty459">記録は今回の出走から残ります。</p>';const groups=new Map();for(const x of rows){const k=x.course+'・'+x.distance+'m';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)}return`<details class="history-detail459" data-detail-key="${esc(key)}"><summary>近走・条件別の成績を見る <small>${rows.length}走分</small></summary><p>新しい順。保存された直近${rows.length}走で集計。</p><div class="form-conditions459">${[...groups].map(([k,rs])=>`<span><b>${esc(k)}</b>${rs.length}走 ／ ${rs.filter(x=>x.place===1).length}勝 ／ 3着以内${rs.filter(x=>x.place<=3).length}回</span>`).join('')}</div><ol>${rows.map(x=>`<li><b>${x.place}着</b><span>${esc(x.course)} ${x.distance}m · ${x.shape==='oval'?'周回':'直線'}<small>調子 ${['落ち着かない','やや重め','平常','好調','絶好調'][x.condition]??'記録なし'} · ${fatigueLabel455(x.fatigue)}</small></span><time>${(x.finishMs/1000).toFixed(2)}秒</time></li>`).join('')}</ol></details>`}
export function ownedForm459(c,m){return historySummary459(monsterHistory459(c.state?.history459??c.bank()?.history459,m.id))}
export function bondNote459(value){const t=temperament459(value);return`<span class="bond-note459">♥ なつき度 ${bond459(value)} ／ ${t.label}<small>${t.chance?`1レース${t.chance*100}％で最初の指示が0.6秒遅れる`:'指示にすぐ応える'} · 最大1回</small></span>`}
export function ownedDetails459(r,c,chosen){const m=c.save.state.monsters.find(x=>x.id===chosen.id),rows=monsterHistory459(c.state?.history459??c.bank()?.history459,chosen.id);return`${historySummary459(rows)}${r.rulesVersion>=7?bondNote459(m?.affection??m?.bond):''}${historyDetails459(rows,'owned-'+chosen.id)}`}
export function rivalDialog459(r,c){const i=c.systemDetail459;if(!Number.isInteger(i)||!r.system[i])return'';const x=r.system[i],rows=x.history459??[];return`<div class="rival-overlay459"><button class="rival-backdrop459" data-race-action="closeSystem459" aria-label="詳細を閉じる" tabindex="-1"></button><section role="dialog" aria-modal="true" aria-labelledby="rival-title459" class="rival-dialog459 rival-dialog460" data-system-dialog459><header><span>出走予定・魔物名鑑</span><button data-race-action="closeSystem459" aria-label="詳細を閉じる">×</button></header>${rivalContent460(r,x,rows.length?historySummary459(rows)+historyDetails459(rows,'system-'+i):'<p class="form-empty459">初出走 · 今回から記録されます</p>')}<button class="race-primary451" data-race-action="closeSystem459">選択画面へ戻る</button></section></div>`}
export function paradeExtra459(r,x){if(r.rulesVersion<7)return'';return`<div class="parade-form459">${historySummary459(x.history459)}${bondNote459(x.bond459)}${historyDetails459(x.history459,'parade-'+x.speciesId+'-'+(x.monsterId??'system'))}</div>`}
export function paceNews459(r){if(r.rulesVersion<7)return'';const front=r.racers.filter(x=>x.profile.style==='逃げ').length,c=course459(r.track459);return`<p class="pace-news459"><b>展開予想：${front>=3?'逃げ争い・前半は速め':front===0?'先頭争いは穏やか':'自分のペースを作れるか'}</b><span>${front>=3?'逃げ型が多く、序盤の消耗が増える。差し・追込は終盤に注目。':front===0?'逃げ型がいない一戦。誰が先に仕掛けるかがカギ。':'逃げの魔物が先頭を取りやすい構成。余力を残して追えるか。'}${c.shape==='oval'?'コーナーの器用さも比べよう。':''}</span></p>`}
const stadium459=`<svg class="circuit-svg459" viewBox="0 0 120 100" preserveAspectRatio="none" aria-hidden="true"><defs><pattern id="circuit-turf459" patternUnits="userSpaceOnUse" width="6" height="6"><rect width="6" height="6" fill="#41623b"/><path d="M1 1l.2-.5M3 4l.3-.7M5 2l-.2-.5M1 5h.3" stroke="#b1bc68" stroke-width=".15" opacity=".7"/><path d="M2 2h1M4 5h1" stroke="#274831" stroke-width=".4"/></pattern><pattern id="circuit-sand459" patternUnits="userSpaceOnUse" width="5" height="5"><rect width="5" height="5" fill="#8a6e44"/><path d="M0 1h2M2 3h2" stroke="#b19460" stroke-width=".3"/><circle cx="1" cy="4" r=".13" fill="#3c2d24"/><circle cx="4" cy="1" r=".2" fill="#d4b078"/></pattern><linearGradient id="track459" x2="0" y2="1"><stop stop-color="#dbc68a"/><stop offset="1" stop-color="#755b2e"/></linearGradient><pattern id="finish459" width="2" height="2" patternUnits="userSpaceOnUse"><rect width="2" height="2" fill="#f7eac5"/><path d="M0 0h1v1H0zM1 1h1v1H1z" fill="#211727"/></pattern></defs><path d="M34 24H86A26 26 0 0 1 86 76H34A26 26 0 0 1 34 24Z" class="circuit-rail459"/><path d="M34 24H86A26 26 0 0 1 86 76H34A26 26 0 0 1 34 24Z" class="circuit-ground459"/><path d="M34 24H86A26 26 0 0 1 86 76H34A26 26 0 0 1 34 24Z" class="circuit-centre459"/><rect x="59" y="67" width="2" height="18" fill="url(#finish459)"/><text x="60" y="91" text-anchor="middle">START / FINISH →</text></svg>`;
export function courseBroadcast459(r,c,html){if(r.rulesVersion<7)return html;const course=course459(r.track459);html=html.replace('1000m',course.distance+'m');if(course.shape!=='oval')return enhanceBroadcast460(html,c);const own=r.racers.find(x=>x.ownerId===c.transport.selfId);return enhanceBroadcast460(html.replace('class="race-track451 track452"','class="race-track451 track452 circuit459"').replace('<div class="race-track-glint452">',stadium459+'<div class="circuit-centre-label459"><small>王庭サーキット</small><b data-course-lap459>1 / '+course.laps+'周</b><span data-course-section459>スタートを待とう</span></div><div class="race-track-glint452">').replace('先頭を追う</button>','相棒を追う</button>').replace('先頭周辺を拡大。全員の順位は上に表示','相棒の姿と現在位置を表示').replace('最後の直線</b>','勝負の終盤</b>').replace('<div class="distance457">',`<section class="course-focus459" data-course-focus459 ${c.camera457==='follow'?'':'hidden'}>${own?art(own):''}<span><small>相棒カメラ</small><b>${esc(own?.name)}</b><em data-own-section459>ゲートイン</em></span><strong data-own-gap459></strong></section><div class="distance457">`),c)}
export function updateCourseView459(c,r,frame,p){if(r.rulesVersion<7)return;const track=course459(r.track459),put=(s,t)=>{const el=c.root.querySelector(s);if(el&&el.textContent!==t)el.textContent=t},length=track.distance;
 put('[data-remaining457]',frame.allFinished?'全匹ゴール':`先頭 残り${Math.max(0,Math.ceil((1-(frame.leader?.p??0))*length))}m`);
 const ownIndex=r.racers.findIndex(x=>x.ownerId===c.transport.selfId),own=frame.positions.find(x=>x.i===ownIndex),live=r.live456,x=live?.runners[ownIndex];
 if(x?.pendingBoost459?.length)put('[data-boost-status]','いうことを聞かない…！ 少し遅れて加速');
 if(track.shape!=='oval')return;
 const map=c.root.querySelector('[data-race-track]');map?.classList.remove('is-follow457');
 const close=frame.allFinished&&Math.abs(live.runners[frame.finished[0].i].finishMs-live.runners[frame.finished[1].i].finishMs)<650,t=Math.min(1,Math.max(0,(Date.now()-(p.photoAt456??Date.now()))/1800)),replay=close&&t<1&&!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches&&live.history.length>1;
 const projected460=[];for(const el of c.root.querySelectorAll('[data-race-runner]')){const i=Number(el.dataset.raceRunner),pos=frame.positions.find(a=>a.i===i);if(!pos)continue;let progress=pos.p;if(replay){const at=t*(live.history.length-1),a=Math.floor(at),b=Math.min(a+1,live.history.length-1);progress=(live.history[a][i]*(1-at+a)+live.history[b][i]*(at-a))/length}const point=coursePoint459(progress,track),lane=(i-3.5)*1.7,angle=(point.angle+90)*Math.PI/180;let number=el.querySelector('.runner-number459');if(!number){number=document.createElement('b');number.className='runner-number459';el.append(number)}number.textContent=String(i+1);projected460.push({i,x:(point.x+10+Math.cos(angle)*lane)/120*100,y:point.y+Math.sin(angle)*lane});el.style.setProperty('--facing459',Math.abs(point.angle)%360>90&&Math.abs(point.angle)%360<270?-1:1);el.classList.toggle('is-own458',i===ownIndex);el.classList.toggle('is-ticket459',!!r.members.find(m=>m.playerId===(c.watchPlayer452??c.transport.selfId))?.ticket?.picks.includes(i))}
 placeCourseRunners460(c,r,projected460);const lp=frame.leader?.p??0,ownPoint=coursePoint459(own?.p??0,track);put('[data-course-lap459]',frame.allFinished?'全匹ゴール':`${Math.min(track.laps,Math.floor(lp*track.laps)+1)} / ${track.laps}周`);put('[data-course-section459]',frame.allFinished?'着順確定':coursePoint459(lp,track).corner?'コーナー勝負':'直線で加速');put('[data-own-section459]',own?.finished?'ゴール！':`${ownPoint.corner?'コーナー':'直線'} · 残り${Math.max(0,Math.ceil((1-(own?.p??0))*length))}m`);put('[data-own-gap459]',`${frame.positions.findIndex(a=>a.i===ownIndex)+1}位`);
 const focus=c.root.querySelector('[data-course-focus459]');if(focus){focus.hidden=c.camera457!=='follow';if(!focus.hidden)setMonsterVisualFrame(focus,own?.finished?'idle1':Math.floor(Date.now()/170)%2?'walk1':'walk2')}
}
