import{course459}from'./RaceCourse459.js';
import{monsterVisual}from'../ui/MonsterVisual.js';
import{tactic456}from'./RaceSimulation456.js';
import{LANE_COLORS452}from'./RacePresentation452.js';
import{fitCamera460,separateRunners460}from'./RaceCamera460.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=x=>monsterVisual({speciesId:x.speciesId,visualSpeciesId:x.speciesId},'◆',{className:'race-art451'});
export const arrow460=direction=>`<svg class="plain-arrow460" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="${direction<0?'M17 4L5 12l12 8Z':'M7 4l12 8-12 8Z'}" fill="currentColor"/></svg>`;
export function stats460(p,bars=false){return`<dl class="stats460 ${bars?'with-bars460':''}">${[['speed','速さ'],['stamina','持久'],['technique','器用']].map(([key,label])=>`<div><dt>${label}</dt><dd>${p[key]}</dd>${bars?`<i aria-hidden="true"><b style="width:${Math.max(0,Math.min(100,p[key]))}%"></b></i>`:''}</div>`).join('')}</dl>`}
export function rivalCard460(x,i){const p=x.profile;return`<article class="rival-card460">${art(x)}<div><b>${esc(x.name)}</b><small>${esc(p.style)} · ${esc(p.ground)}向き</small></div>${stats460(p)}<button data-system-detail459="${i}" aria-label="${esc(x.name)}の詳細記事">詳細記事を読む</button></article>`}
export function rivalContent460(r,x,history){const p=x.profile,t=tactic456(x),course=course459(r.track459),point=course.distance===3000?`持久力${p.stamina}と終盤の余力`:course.shape==='oval'?`器用さ${p.technique}とコーナーの走り`:`速さ${p.speed}と仕掛けのタイミング`;return`<div class="rival-hero460"><div class="rival-portrait459">${art(x)}</div><div><small>RIVAL PROFILE</small><h2 id="rival-title459">${esc(x.name)}</h2><div class="rival-tags459"><b>${esc(p.style)}</b><b>${esc(p.ground)}向き</b></div></div></div>${stats460(p,true)}<div class="rival-course460"><span>今回の舞台 <b>${esc(r.course)}・${course.distance}m</b></span><strong>${p.ground===r.course?'得意な馬場':'展開がカギ'}</strong></div><article class="rival-article459"><small>魔物競走新聞 · 出走前の紹介</small><h3>${p.ground===r.course?'得意の舞台で持ち味を生かす':'走る展開を見極めたい'}</h3><p>${esc(p.skillDescription??'脚質を生かして走る魔物。')}</p><p class="rival-key460"><b>注目ポイント</b>${point}</p></article><section class="rival-skill460"><small>レース特技</small><b>${esc(t.name)}</b><p>${esc(t.description.replace('100m以内',r.rulesVersion>=7?'コース全長の10％以内':'100m以内'))}</p></section><section class="rival-history460"><h3>近走の記録</h3>${history}</section><p class="rival-caution459">仮エントリーです。重複時は交代します。調子・人気・倍率は出走確定後のパレードで発表。</p>`}
export function enhanceBroadcast460(html,c){return html.replace('class="race-camera457"','class="race-camera457 cameras460"').replace('aria-label="レースカメラ">','aria-label="レースカメラ"><span class="camera-legend460"><b>金枠：自分の魔物</b><small>点と線：走っている位置</small></span>').replace('相棒を追う</button>','自動拡大</button>').replace('title="相棒の姿と現在位置を表示"','title="全8匹を画面に収めて拡大"').replace('<div class="race-grandstand452">',`<div class="race-grandstand452"><button class="expand-race460" data-race-action="expand460" aria-pressed="${!!c.expanded460}">${c.expanded460?'通常表示':'拡大表示'}</button>`).replace('<div class="circuit-centre-label459">','<svg class="runner-tethers460" aria-hidden="true"></svg><div class="circuit-centre-label459">')}
export function placeCourseRunners460(c,r,points){
 const map=c.root.querySelector('.circuit459');if(!map)return;
 const width=map.clientWidth,height=map.clientHeight,large=c.expanded460,size=large?Math.max(28,Math.min(60,width*.115,height*.12)):Math.max(29,Math.min(46,width*.11));
 const raw=points.map(p=>({...p,x:p.x*width/100,y:p.y*height/100})),camera=fitCamera460(raw,width,height,c.camera457==='follow');
 const anchors=raw.map(p=>({...p,x:p.x*camera.scale+camera.x,y:p.y*camera.scale+camera.y}));
 const positions=separateRunners460(anchors,width,height,size);
 map.style.setProperty('--portrait-size460',size+'px');
 const svg=map.querySelector('.circuit-svg459');svg.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.scale})`;svg.style.transformOrigin='0 0';
 map.classList.toggle('is-auto460',c.camera457==='follow');
 const lines=map.querySelector('.runner-tethers460');if(lines){lines.setAttribute('viewBox',`0 0 ${width} ${height}`);if(!lines.children.length)lines.innerHTML=r.racers.map((_,i)=>`<g stroke="${LANE_COLORS452[i]}" fill="${LANE_COLORS452[i]}"><path fill="none"/><circle r="3"/></g>`).join('')}
 for(const p of positions){const el=map.querySelector(`[data-race-runner="${p.i}"]`);if(!el)continue;el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.zIndex=String(Math.round(p.y)+10);el.setAttribute('aria-label',`${p.i+1}番 ${r.racers[p.i].name}`);const g=lines?.children[p.i];if(g){g.children[0].setAttribute('d',`M${p.anchorX},${p.anchorY}L${p.x},${p.y+size*.35}`);g.children[1].setAttribute('cx',p.anchorX);g.children[1].setAttribute('cy',p.anchorY)}}
}
export function toggleExpanded460(c,force){const next=force??!c.expanded460;if(next===!!c.expanded460)return;if(next)c.expandedScroll460=c.root.scrollTop;c.expanded460=next;const screen=c.root.querySelector('.is-racing451');screen?.classList.toggle('expanded-race460',next);const button=screen?.querySelector('[data-race-action=expand460]');if(button){button.textContent=next?'通常表示':'拡大表示';button.setAttribute('aria-pressed',String(next));button.focus({preventScroll:true})}if(!next)c.root.scrollTop=c.expandedScroll460??0;}
