import{ticketColor501}from'../party/GameColors501.js';
import{resultActions490}from'../party/PartyResults490.js';
import{boostLimit462}from'./RaceRules462.js';
import{rivalCard460,arrow460}from'./RaceExperience460.js';
import{courseLabel459}from'./RaceCourse459.js';
import{courseSelector459,ownedForm459,ownedDetails459,rivalDialog459,paradeExtra459,paceNews459,courseBroadcast459}from'./RaceExperience459.js';
import{monsterVisual}from'../ui/MonsterVisual.js';
import{raceSpecies451,ownedRaceIdentity451}from'./RaceCatalog451.js';
import{raceProfile451,payout451,odds451,validTicket451}from'./RaceRules451.js';
import{fatigueLabel455,fatigueLevel455}from'./RaceStrategy455.js';
import{forecastPanel455,forecastDetail455}from'./RaceForecastView455.js';
import{forecastRows456,BET_NAMES456,pickCount456,ordered456,betHint456,odds456}from'./RaceTickets456.js';
import{condition452,ownerName452,LANE_COLORS452,paradeIndex452}from'./RacePresentation452.js';
import{paradeStage457,broadcast457}from'./RaceLayout457.js';
import{boostIntent457}from'./RaceBoost457.js';
import{betLimit458}from'./RaceUX458.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>Math.floor(Number(x)||0).toLocaleString(),signed=x=>`${x>=0?'+':''}${n(x)}`;
const art=x=>monsterVisual({speciesId:x.speciesId,visualSpeciesId:x.speciesId},'◆',{className:'race-art451'});
const quote=(r,t)=>r.rulesVersion>=4?odds456(r.forecast456,t):odds451(r.racers,r.course,t);
const chips=t=>t?t.picks.map((i,k)=>`${k?`<i>${ordered456(t.kind)?'→':'＋'}</i>`:''}<b style="--lane:${LANE_COLORS452[i]}">${i+1}</b>`).join(''):'<small>応援</small>';
const title=(step,label)=>`<div class="section-title458"><small>${step}</small><h2>${label}</h2><i>◆</i></div>`;
const stateClass=x=>x>0?'is-profit':x<0?'is-loss':'is-even';
export function room458(r,c){return`<div class="room-bar458"><span><small>合言葉</small><b>${esc(r.code)}</b></span><span>${esc(courseLabel459(r))}</span><button data-race-action="copy" aria-label="合言葉をコピー">コピー</button></div><div class="seats458">${Array.from({length:4},(_,i)=>{const m=r.members[i];return`<div class="${m?.playerId===c.transport.selfId?'is-you':''}"><i class="${m?.ready?'ready':''}">${i+1}</i><span><b title="${esc(m?.name??'空き席')}">${esc(m?.name??'AI参加予定')}</b><small>${!m?'開始時に参加':!m.connected&&!m.ai?'再接続待ち':r.phase==='lobby'?m.choice?esc(m.choice.name):'魔物を選択中':m.ready?'準備OK':'予想中'}</small></span></div>`}).join('')}</div>`}
export function lobby458(r,c){const self=c.transport.selfId,host=r.hostId===self,own=r.members.find(m=>m.playerId===self),q=c.draft.search.trim(),sort=c.sort458??'owned',owned=(c.save.state.monsters??[]).map((m,index)=>{const id=ownedRaceIdentity451(m),sp=raceSpecies451(id);return sp?{m,index,id,sp,p:raceProfile451(id,r.rulesVersion),fatigue:fatigueLevel455(c.state?.fatigue455?.[id])}:null}).filter(x=>x&&(!q||String(x.m.nameOverride??x.sp.name).includes(q))&&(!c.styleFilter453||x.p.style===c.styleFilter453));if(sort==='course')owned.sort((a,b)=>Number(b.p.ground===r.course)-Number(a.p.ground===r.course)||a.fatigue-b.fatigue||a.index-b.index);if(sort==='fresh')owned.sort((a,b)=>a.fatigue-b.fatigue||a.index-b.index);
 const chosen=own?.choice,profile=chosen?raceProfile451(chosen.speciesId,r.rulesVersion):null;
 return`${room458(r,c)}<section class="race-panel451 course-panel458">${title('01 / COURSE','今回の舞台')}<div class="course-cards458">${['芝','砂'].map(course=>`<button data-race-course="${course}" class="course-${course==='芝'?'turf':'sand'}458 ${r.course===course?'is-picked':''}" aria-pressed="${r.course===course}" ${host&&r.phase==='lobby'?'':'disabled'}><b>${course==='芝'?'翠緑の王庭':'黄昏の砂塵'}</b><span>${course}コース</span><small>${course==='芝'?'速さ・器用さがカギ':'持久力がカギ'}</small>${r.course===course?'<i>今回のコース</i>':''}</button>`).join('')}</div>${courseSelector459(r,c)}<small>次回は${r.course==='芝'?'砂':'芝'}。部屋主は開始前に変更できます。</small></section>
 <section class="race-panel451 roster-panel458">${title('02 / ENTRY','相棒を選ぼう')}<p class="note458">${r.rulesVersion>=7?'レベル・装備は走力に影響しません。距離・近走・なつき度も見て選ぼう。':'育成度は走力に影響しません。適性と疲労を見て選ぼう。'}</p><div class="roster-tools458"><label><span class="sr458">魔物の名前で検索</span><input name="monsterSearch" placeholder="魔物の名前で検索" value="${esc(q)}"></label><select name="raceSort" aria-label="魔物の並び順"><option value="owned" ${sort==='owned'?'selected':''}>所持順</option><option value="course" ${sort==='course'?'selected':''}>今回のコース向き</option><option value="fresh" ${sort==='fresh'?'selected':''}>疲労が少ない順</option></select></div><div class="race-style-tabs453">${['','逃げ','先行','差し','追込'].map(style=>`<button data-race-style="${style}" aria-pressed="${(c.styleFilter453??'')===style}" class="${(c.styleFilter453??'')===style?'is-picked':''}">${style||'すべて'}</button>`).join('')}</div><small class="roster-count458">${owned.length}匹 · タップで選択・詳細を見る</small><div class="race-roster451">${owned.slice(0,c.rosterLimit453??24).map(x=>`<button data-race-monster="${esc(x.m.id)}" class="${chosen?.id===x.m.id?'is-picked':''}" aria-pressed="${chosen?.id===x.m.id}">${art({speciesId:x.id})}<b>${esc(x.m.nameOverride??x.sp.name)}</b><small>${esc(x.p.style)} <em class="${x.p.ground===r.course?'good458':''}">${x.p.ground}向き</em></small><span class="race-fatigue455 ${x.fatigue?'tired458':''}">${fatigueLabel455(x.fatigue)}</span><span class="roster-form459">${ownedForm459(c,x.m)}</span>${chosen?.id===x.m.id?'<i>出走</i>':''}</button>`).join('')}</div>${owned.length>(c.rosterLimit453??24)?'<button class="more458" data-race-action="more453">さらに24匹を表示</button>':''}${!owned.length?'<p>該当する魔物がいません。検索条件を変えてみてね。</p>':''}
 ${chosen?`<section class="selected-detail458"><b>${esc(chosen.name)} <small>出走選択中</small></b><div class="mini-stats458"><span>速さ <b>${profile.speed}</b></span><span>持久 <b>${profile.stamina}</b></span><span>器用 <b>${profile.technique}</b></span></div><strong>${esc(profile.skill)}</strong><p>${esc(profile.skillDescription??'脚質を生かして走ります。')}</p>${ownedDetails459(r,c,chosen)}</section>`:''}</section>
 <section class="race-panel451 system-panel458">${title('RIVALS','システム出走')}<div class="race-system451">${r.system.map(rivalCard460).join('')}</div><details data-detail-key="system"><summary>仮エントリーについて</summary><p>プレイヤーが選んだ魔物と重なった場合は、パレード前に別の魔物へ交代します。</p></details></section>
 <div class="action-dock458 lobby-dock458"><div class="dock-choice458">${chosen?art(chosen):'<span class="empty458">？</span>'}<span><small>あなたの出走魔物</small><b>${esc(chosen?.name??'魔物を選んでね')}</b>${chosen?`<small>${profile.style} · ${profile.ground}向き · ${fatigueLabel455(c.state?.fatigue455?.[chosen.speciesId])}</small>`:''}</span>${chosen?`<button data-race-action="rosterDetail458" aria-expanded="${!!c.rosterDetail458}">詳細 ${c.rosterDetail458?'−':'＋'}</button>`:''}</div>${chosen&&c.rosterDetail458?`<div class="dock-detail458"><b>${esc(profile.skill)}</b><span>速さ ${profile.speed} · 持久 ${profile.stamina} · 器用 ${profile.technique}</span><p>${esc(profile.skillDescription??'脚質を生かして走ります。')}</p></div>`:''}<div class="dock-buttons458"><button class="dock-exit458" data-race-action="leave">退出</button>${r.phase==='entry'?'<span>選択待ち <b data-race-timer></b>秒</span>':host?`<button class="race-primary451" data-race-action="start" ${chosen&&c.ready()?'':'disabled'}>出走準備へ <small>不足席はAIが参加</small></button>`:'<span>部屋主の開始を待っています</span>'}</div><small class="action-feedback458" data-action-feedback aria-live="polite"></small></div>${rivalDialog459(r,c)}`}
export function prediction458(r,c,bet){let compare=forecastPanel455(r).replace('<details class="race-compare456"><summary>全8匹の人気・倍率を比較する</summary>','').replace(/<\/details>$/,'');compare=compare.replace(/(<button data-parade-index="(\d+)"[^>]*>)/g,(_,tag,i)=>tag+art(r.racers[Number(i)]));compare=paceNews459(r)+compare;const tab=c.predictionTab457??'watch';return`<div class="prediction-hub457">${room458(r,c)}<nav class="prediction-tabs457" aria-label="予想画面">${[['watch','◈ 観察'],['compare','▤ 出走表'],['bet','▣ 馬券']].map(([key,label])=>`<button data-prediction-tab="${key}" aria-pressed="${tab===key}">${label}</button>`).join('')}<small>締切<b data-race-timer></b>秒</small></nav><div data-prediction-panel="watch" ${tab==='watch'?'':'hidden'}><section class="race-panel451 parade-panel452"><div class="parade-toolbar457"><b>出走パレード</b><button data-race-action="pauseParade456">${c.paradePinned==null?'Ⅱ 自動紹介を停止':'▶ 自動紹介を再開'}</button></div><div class="race-parade-nav451">${r.racers.map((x,i)=>`<button data-parade-index="${i}" style="--lane:${LANE_COLORS452[i]}" aria-label="${i+1}番 ${esc(x.name)}を観察"><b>${i+1}</b>${art(x)}</button>`).join('')}</div><div data-parade-stage></div><div class="watch-actions458"><button data-parade-step="-1" aria-label="前の魔物">‹</button><button class="race-primary451" data-race-action="candidate458">${r.members.find(m=>m.playerId===c.transport.selfId)?.ready?'確定した馬券を見る':'この魔物を馬券候補に'}</button><button data-parade-step="1" aria-label="次の魔物">›</button></div></section></div><div data-prediction-panel="compare" ${tab==='compare'?'':'hidden'}>${compare}</div><div data-prediction-panel="bet" ${tab==='bet'?'':'hidden'}>${bet}</div></div>`}
export function parade458(r,i,c){return paradeStage457(r,i,c).replace('class="parade-scene452 ', 'data-parade-swipe class="parade-scene452 ').replace('<div class="parade-spotlight452">','<button class="parade-arrow459 is-prev" data-parade-step="-1" aria-label="前の魔物">'+arrow460(-1)+'</button><button class="parade-arrow459 is-next" data-parade-step="1" aria-label="次の魔物">'+arrow460(1)+'</button><div class="parade-spotlight452">').replace('<div class="parade-information452">','<small class="swipe-hint458">左右のタップ・スワイプで切り替え</small><div class="parade-information452">').replace('<button class="race-fold457" data-race-detail="news"',paradeExtra459(r,r.racers[i])+'<button class="race-fold457" data-race-detail="news"')}
export function bet458(r,c){const me=r.members.find(m=>m.playerId===c.transport.selfId),pending=c.bank()?.pending,t=c.draft.ticket,limit=betLimit458(c.save.state.player.gold,r.rulesVersion);if(me?.ready){const ticket=me.selfTicket;return`<section class="race-panel451 bet-sealed458">${title('TICKET / CONFIRMED',ticket?'馬券を受け付けました':'今回は応援')}<article class="paper-ticket458"><span class="ticket-seal458">${ticket?'購入確定':'応援参加'}</span><div class="sealed-monsters458">${ticket?ticket.picks.map((i,j)=>`<div>${art(r.racers[i])}<b>${ordered456(ticket.kind)?j+1+'着：':''}${i+1}番</b><small>${esc(r.racers[i].name)}</small></div>`).join(''):art(r.racers.find(x=>x.ownerId===c.transport.selfId)??r.racers[0])}</div><h3>${ticket?BET_NAMES456[ticket.kind]:'出走賞金と育成報酬を目指そう'}</h3>${ticket?`<dl><div><dt>購入額</dt><dd>${n(ticket.amount)}G</dd></div><div><dt>的中払戻</dt><dd>${n(payout451(ticket.amount,ticket.odds))}G</dd></div></dl><small>倍率 ${ticket.odds.toFixed(1)}倍 · 払戻は購入額を含みます</small>`:''}</article><div class="waiting458"><b>${r.members.filter(m=>m.ready).length} / 4 人 準備OK</b><span>${r.members.filter(m=>!m.ready).map(m=>esc(m.name)).join('・')||'全員'}${r.members.every(m=>m.ready)?'の準備ができました':'の予想を待っています'}</span></div><button data-prediction-tab="watch">パレードを見ながら待つ</button></section>`}
 if(pending)return`<section class="race-panel451 waiting458"><b>馬券の受付を確認中…</b><p>${n(pending.amount)}Gを確保しました。通信が戻ると自動で確認します。</p><button data-race-action="refresh">接続を確認</button><button data-prediction-tab="watch">観察に戻る</button></section>`;
 return`<section class="race-panel451 race-bet-panel452">${title('03 / PREDICTION','あなたの1枚')}<div class="race-bet-tabs451">${Object.entries(BET_NAMES456).filter(([k])=>r.rulesVersion>=4||['win','pair','exact'].includes(k)).map(([key,label])=>`<button data-bet-kind="${key}" class="${t.kind===key?'is-picked':''}" aria-pressed="${t.kind===key}">${label}</button>`).join('')}</div><p class="bet-hint458">${betHint456(t.kind)}を選んでください。</p><div class="pick-slots458">${Array.from({length:pickCount456(t.kind)},(_,slot)=>{const i=t.picks[slot];return`<button data-pick-slot="${slot}" class="${c.pickSlot458===slot?'is-editing':''}" aria-pressed="${c.pickSlot458===slot}"><small>${ordered456(t.kind)?slot+1+'着':'選択 '+(slot+1)}</small>${i==null?'<b>＋</b><span>魔物を選ぶ</span>':`${art(r.racers[i])}<b style="color:${LANE_COLORS452[i]}">${i+1}番</b><span>${esc(r.racers[i].name)}</span>`}</button>`}).join('')}</div><div class="race-picks451">${r.racers.map((x,i)=>{const f=r.rulesVersion>=4?forecastRows456(r.forecast456)[i]:null;return`<button data-bet-pick="${i}" class="${t.picks.includes(i)?'is-picked':''}" style="--lane:${LANE_COLORS452[i]}" aria-pressed="${t.picks.includes(i)}"><strong>${i+1}</strong>${art(x)}<small>${esc(x.name)}</small><em>${condition452(x.condition).label} · ${esc(x.profile.style)}</em><span class="race-forecast-badge455">${f?`${f.rank}番人気 · ${f.odds.toFixed(1)}倍`:''}</span>${t.picks.includes(i)?`<i>${ordered456(t.kind)?t.picks.indexOf(i)+1+'着':'選択'}</i>`:''}</button>`}).join('')}</div>
 <section class="amount-panel458"><label>購入金額 <small>所持 ${n(c.save.state.player.gold)}G</small><input name="betAmount" type="number" inputmode="numeric" min="1" max="${limit}" value="${esc(c.draft.amount)}"></label><div class="race-amounts453">${[100,1000,10000].map(v=>`<button data-bet-amount="${v}">${n(v)}G</button>`).join('')}<button data-bet-fraction="half">半分</button><button class="max-bet458" data-bet-fraction="max">MAX</button></div><small>MAXは所持GOLDを入力します。購入ボタンで確定。</small>${limit<Math.floor(c.save.state.player.gold)?`<small>この部屋の購入上限：${n(limit)}G</small>`:''}${!limit?'<p>GOLDがなくても無料出走できます。賞金を目指そう！</p>':''}</section>
 <article class="paper-ticket458 draft-ticket458"><small>馬券プレビュー</small><div class="ticket-chips452">${chips(t)}</div><b>${BET_NAMES456[t.kind]}</b><div data-quote458></div></article><button class="pass458" data-race-action="pass">購入せずに応援する</button>
 <div class="action-dock458 bet-dock458"><div><span>${BET_NAMES456[t.kind]} <b>${t.picks.map(i=>i+1).join(ordered456(t.kind)?' → ':' ＋ ')||'未選択'}</b></span><strong data-bet-total458></strong><small data-bet-net458></small></div><button class="race-primary451" data-race-action="bet">この馬券を購入</button><small data-bet-validation458 aria-live="polite"></small></div></section>`}
export function broadcast458(r,c,track,control,tickets){track=track.replace('<div class="race-track-glint452">','<div class="race-track-glint452">');control=control.replace('<meter data-race-stamina','<div class="boost-pips458" aria-label="残りの叩ける回数">'+(r.rulesVersion>=8?'<progress class="boost-uses462" data-boost-uses462 value="'+boostLimit462(r)+'" max="'+boostLimit462(r)+'" aria-label="残りの指示回数"></progress>':Array.from({length:5},(_,i)=>`<i data-boost-pip="${i}">◆</i>`).join(''))+'</div><meter data-race-stamina');return courseBroadcast459(r,c,broadcast457(r,c,track,control,tickets)).replace('<div class="race-camera457"','<div class="track-legend458"><span>✦ 自分の魔物</span><span>◆ 応援中の馬券</span></div><div class="race-camera457"').replace(/<\/div>$/,`<div class="ticket-detail458" data-ticket-detail458 hidden></div></div>`)}
export function result458(r,c){const mine=r.results.find(x=>x.playerId===c.transport.selfId),saved=c.bank()?.applied?.[`result:${r.id}:${c.transport.selfId}`];return`<div class="race-results452 result458"><div class="race-result-heading452"><span>MONSTER GRAND PRIX / RESULT</span><h1>栄光のゴール</h1><p>${r.order.slice(0,3).map(i=>i+1).join(' → ')}</p><button data-race-action="skip452">演出スキップ</button></div><div class="race-podium452">${[1,0,2].map(place=>{const i=r.order[place],x=r.racers[i];return`<div class="podium-monster452 place-${place+1}" data-podium-place="${place}"><span class="podium-laurel452">${place===0?'♛':'◆'}</span>${art(x)}<strong>${i+1}番</strong><b>${esc(x.name)}</b><small>${esc(ownerName452(r,x))}</small><em>${place+1}</em></div>`}).join('')}</div><div class="race-confetti452" aria-hidden="true">${Array.from({length:18},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><section class="race-personal452 ${stateClass(mine?.net??0)}"><small>あなたの収支</small><strong data-personal-net>${signed(mine?.net??0)}G</strong><b>${mine?.won?'馬券的中！':mine?.place?`相棒は${mine.place}着！`:'レース終了'}</b><dl class="personal-breakdown458"><div><dt>購入</dt><dd>${n(mine?.stake)}G</dd></div><div><dt>払戻</dt><dd>${n(mine?.payout)}G</dd></div><div><dt>出走賞金</dt><dd>${n(mine?.prize)}G</dd></div></dl><p class="training458">${saved?`保存済み · EXP ＋${n(saved.exp)} · なつき度 ＋${saved.affection}`:'育成報酬を保存中…'}${mine?.training?`<small>EXP ${mine.training.expRate*100}％（最低10）</small>`:''}</p></section>${title('SETTLEMENT','みんなの馬券と収支')}<div class="race-settlements452">${r.results.map((row,i)=>`<article class="settlement-card452 ${stateClass(row.net)} ${row.playerId===c.transport.selfId?'is-you':''}" data-color501="${ticketColor501(r,row).id}" style="--player501:${ticketColor501(r,row).hex}" data-result-row="${i}"><div class="settlement-owner452"><b title="${esc(row.name)}">${esc(row.name)}${row.ai?' · AI':''}</b><span class="result-stamp452 ${row.won?'is-hit':''}">${row.won?'的中':row.ticket?'不的中':'応援'}</span></div><div class="settlement-ticket452"><span class="ticket-chips452">${chips(row.ticket)}</span><span>${row.ticket?BET_NAMES456[row.ticket.kind]:'見送り'}</span><strong data-net-value="${i}">${signed(row.net)}G</strong></div><div class="result-place458">${row.place?`出走 ${row.place}着`:''}</div><details data-detail-key="settlement-${i}"><summary>購入・払戻・賞金</summary><dl><div><dt>購入</dt><dd>${n(row.stake)}G</dd></div><div><dt>払戻</dt><dd>${n(row.payout)}G</dd></div><div><dt>賞金</dt><dd>${n(row.prize)}G</dd></div></dl></details></article>`).join('')}</div><div class="race-result-footer452"><details data-detail-key="finish"><summary>全8匹の着順を見る</summary><ol>${r.order.map(i=>`<li>${art(r.racers[i])}<b>${i+1}番 ${esc(r.racers[i].name)}</b><span>${(r.finishMs[i]/1000).toFixed(2)}秒</span></li>`).join('')}</ol></details><button data-race-action="replay452">発表演出をもう一度</button></div>${resultActions490(c)}</div>`}
export function updateExperience458(c){const r=c.state?.room;if(!c.root||!r)return;const put=(s,text)=>{const el=c.root.querySelector(s);if(el&&el.textContent!==text)el.textContent=text};
 const pending=c.actionPending458;if(pending&&Date.now()-pending.at>8000){c.actionPending458=null;c.actionNote458='応答を確認できませんでした。接続を確認してもう一度押してください。'}for(const b of c.root.querySelectorAll('[data-race-action="start"],[data-race-action="again"]')){const wait=c.actionPending458?.op===b.dataset.raceAction;b.disabled=wait||!c.ready()||(b.dataset.raceAction==='start'&&!r.members.find(m=>m.playerId===c.transport.selfId)?.choice);b.setAttribute('aria-busy',String(wait))}put('[data-action-feedback]',c.actionPending458?({start:'出走準備を受付中…',again:'次のレースを準備中…',leave:'退出しています…'}[c.actionPending458.op]):c.actionNote458||(!c.ready()?'再接続を待っています。退出してホームへ戻れます。':''));
 if(r.phase==='parade'){const t=c.draft.ticket,odds=quote(r,t),amount=Number(c.draft.amount),limit=betLimit458(c.save.state.player.gold,r.rulesVersion),valid=validTicket451(t)&&odds>0&&Number.isSafeInteger(amount)&&amount>=1&&amount<=limit;const payout=valid?payout451(amount,odds):0,remaining=Math.max(0,Math.floor(Number(c.save.state.player.gold)||0)-(Number.isSafeInteger(amount)?amount:0));put('[data-bet-total458]',`${n(amount)}G`);put('[data-bet-net458]',valid?`的中払戻 ${n(payout)}G`:'魔物・金額を選ぼう');put('[data-quote458]',valid?`${odds.toFixed(1)}倍 · 購入 ${n(amount)}G\n的中払戻 ${n(payout)}G ／ 的中時利益 ＋${n(payout-amount)}G\n購入後の残高 ${n(remaining)}G（出走賞金は別途）`:'選んだ魔物・金額から払戻と利益を表示します');const expired=Date.now()+c.offset>=r.deadline,button=c.root.querySelector('[data-race-action="bet"]');if(button)button.disabled=!valid||!c.ready()||expired||!!c.bank()?.pending;put('[data-bet-validation458]',expired?'締切を迎えました':!c.ready()?'再接続中':!validTicket451(t)?'上の選択枠を完成させてね':!Number.isSafeInteger(amount)||amount<1?'1G以上の整数を入力':amount>limit?'所持GOLDまたは購入上限を超えています':remaining===0?'購入後の残高：0G':`購入後の残高：${n(remaining)}G`)}
 if(['race','countdown'].includes(r.phase)){const v=boostIntent457(r,c.transport.selfId,c.boostPending456);const uses=c.root.querySelector('[data-boost-uses462]');if(uses&&uses.value!==Math.max(0,boostLimit462(r)-v.wanted))uses.value=Math.max(0,boostLimit462(r)-v.wanted);c.root.querySelectorAll('[data-boost-pip]').forEach(el=>el.classList.toggle('is-used',Number(el.dataset.boostPip)<v.wanted));for(const el of c.root.querySelectorAll('[data-race-runner]')){const i=Number(el.dataset.raceRunner),live=r.live456?.runners[i];let fx=el.querySelector('.runner-fx458');if(!fx){fx=document.createElement('span');fx.className='runner-fx458';el.append(fx)}const at=r.live456?.elapsed??0,label=live?.finishMs!=null?'':live?.restUntil462>at?'休憩…':live?.surgeUntil462>at?'大暴走！':live?.loyalUntil462>at?'息ぴったり':live?.slowUntil>at?'妨害':live?.windUntil>at?'追い風':live?.draftUntil>at?'吸い付き':live?.boostUntil>at?'加速':live?.guard?'障壁':'';if(fx.textContent!==label)fx.textContent=label;if(fx.dataset.effect!==label)fx.dataset.effect=label;el.classList.toggle('is-own458',i===v.index)}const detail=c.root.querySelector('[data-ticket-detail458]');if(detail&&c.ticketExpanded458){const m=r.members.find(x=>x.playerId===c.ticketExpanded458);if(m){detail.hidden=false;const t=m.ticket;detail.textContent=`${m.name}：${t?`${BET_NAMES456[t.kind]} ${t.picks.map(i=>i+1).join(ordered456(t.kind)?' → ':' ＋ ')} ／ 購入 ${n(t.amount)}G ／ 的中払戻 ${n(payout451(t.amount,t.odds))}G`:'購入せず応援中'}。該当レーンを紫の目印で表示中。`}}}
}
