import{distance459}from'./RaceCourse459.js';
import{SIM456,tactic456}from'./RaceSimulation456.js';
import{forecastRows456}from'./RaceTickets456.js';
import{fatigueLabel455}from'./RaceStrategy455.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function article456(r,i){const x=r.racers[i],f=forecastRows456(r.forecast456)[i],t=tactic456(x),front=r.racers.filter(v=>v.profile.style==='逃げ').length,headline=f.rank===1?'本命・勝ち負けを期待':f.rank<=3?'対抗・上位を狙える一頭':'穴候補・展開を待ちたい';const mood=x.condition>=3?'足取りは軽く、調子は良い。':x.condition<=1?'今日は足取りが重く、調子に不安が残る。':'調子は平常。いつもの走りに期待。',ground=x.profile.ground===r.course?`得意の${r.course}で持ち味を出しやすい。`:`得意は${x.profile.ground}。今回の${r.course}では適性面で割引。`,fatigue=x.fatigue455?`連戦の疲労は${['','小','中','大'][x.fatigue455]}。終盤の余力に注意。`:'疲労がなく、余力は十分。',pace=x.profile.style==='逃げ'?front>=3?'逃げ型が多く、序盤の先頭争いは激しくなりそう。':'序盤で前へ出て、逃げ切りを狙いたい。':['差し','追込'].includes(x.profile.style)?'前半は力を残し、後半の加速に叩くタイミングを合わせたい。':'好位置を保ち、無理な連打を避けたい。';return`<article class="race-news456"><header><small>魔物競走新聞</small><b>${headline}</b></header><p>${mood}${ground}</p><p>${fatigue}${pace}</p><div class="race-tactic456"><b>魔物特技：${t.name}</b><span>${t.description.replace('100m以内',r.rulesVersion>=7?'コース全長の10％以内':'100m以内')}</span></div><small class="race-estimate456">人気・勝率は標準の5回操作を想定した事前予測。実際の操作と特技で変わります。</small></article>`}
export function control456(r,c){if(!(r.rulesVersion>=4))return'';return`<div class="race-control456"><div><b data-boost-owner>自分の魔物を応援</b><span data-boost-status>スタートを待とう</span><meter data-race-stamina min="0" max="100" value="100" aria-label="スタミナ"></meter></div><button data-race-action="boost456" disabled><b>ケツを叩く！</b><small data-boost-left>残り5回</small></button></div>`}
export function frame456(room,at){const s=room.live456,elapsed=Math.max(0,at-room.startAt),age=Math.min(600,Math.max(0,elapsed-(s?.elapsed??0))),positions=(room.racers??[]).map((r,i)=>{const x=s?.runners[i];return{i,p:x?x.finishMs!==null?1:Math.min(.998,(x.distance+x.velocity*age/1000)/distance459(room)):0,finished:x?.finishMs!=null}}).sort((a,b)=>b.p-a.p||((s?.runners[a.i].finishMs??Infinity)-(s?.runners[b.i].finishMs??Infinity))||a.i-b.i);const finished=(s?.order??[]).map(i=>positions.find(x=>x.i===i)),leader=positions[0],late=leader?.p>=.65,close=late&&!finished.length&&positions[0].p-positions[1].p<.04;return{elapsed,positions,finished,leader,late,close,allFinished:finished.length===8,section:finished.length===8?'finish':late?'spurt':elapsed<1400?'start':elapsed<7000?'opening':'middle'}}
export function updateVisual456(c,r,frame,p){if(r.rulesVersion<4)return;const at=Date.now()+c.offset,live=r.live456,index=r.racers.findIndex(x=>x.ownerId===c.transport.selfId),x=live?.runners[index],button=c.root.querySelector('[data-race-action="boost456"]'),set=(selector,text)=>{const e=c.root.querySelector(selector);if(e&&e.textContent!==text)e.textContent=text};
 const wait=r.rulesVersion>=5?0:x?Math.max(0,SIM456.cooldown-(live.elapsed-x.lastBoost)):0,stale=r.phase==='race'&&at-r.startAt-(live?.elapsed??0)>2500;
 if(button)button.disabled=!c.ready()||r.phase!=='race'||!x||x.finishMs!==null||x.boosts>=5||wait>0||x.stamina<10||(r.rulesVersion<5&&!!c.boostPending456)||stale;
 set('[data-boost-owner]',r.racers[index]?.name??'自分の魔物');set('[data-boost-left]',`残り ${5-(x?.boosts??0)} / 5回`);set('[data-boost-status]',c.boostPending456?'操作を送信中…':stale?'通信を確認中…':x?.finishMs!=null?'ゴール！':r.phase==='countdown'?'スタートを待とう':wait>0?`あと ${(wait/1000).toFixed(1)}秒`:x?.stamina<10?'スタミナ不足':x?.boosts>=5?'5回使い切った！':'加速 ＋18％・スタミナ −10');const meter=c.root.querySelector('[data-race-stamina]');if(meter)meter.value=x?.stamina??100;
 c.root.querySelectorAll('[data-race-runner]').forEach(e=>{const i=Number(e.dataset.raceRunner),v=live?.runners[i];for(const [cls,field]of[['is-boost456','boostUntil'],['is-slow456','slowUntil'],['is-wind456','windUntil'],['is-draft456','draftUntil']])e.classList.toggle(cls,!!v&&v[field]>live.elapsed&&v.finishMs===null);e.classList.toggle('is-guard456',!!v?.guard&&v.finishMs===null)});
 const events=live?.events??[],last=events.at(-1);if(last&&live.elapsed-last.at<2000){const names={boost:'猛ダッシュ！',wind:'追い風！',mud:'ぬかるみ！',shield:'障壁で防いだ！',draft:'吸い付き走法！',hesitate:'いうことを聞かない…！',obey:'気を取り直して加速！'},label=`${last.i+1}番 ${names[last.type]}`;set('[data-commentary]',label);if(!p.seen.has('v4-'+last.id)){p.seen.add('v4-'+last.id);c.sound452?.play(last.type==='boost'?'spurt':'parade')}}
 const track=c.root.querySelector('[data-race-track]');track?.classList.toggle('is-moving456',r.phase==='race'&&!frame.allFinished);if(frame.allFinished&&live?.history.length>1){p.photoAt456??=Date.now();const t=Math.min(1,(Date.now()-p.photoAt456)/1800),reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches,finish=r.finishMs??live.runners.map(v=>v.finishMs),close=finish&&Math.abs(finish[frame.finished[0].i]-finish[frame.finished[1].i])<650;const replay=close&&!reduced&&t<1;track?.classList.toggle('is-photo456',replay);if(replay){const pos=t*(live.history.length-1),a=Math.floor(pos),b=Math.min(a+1,live.history.length-1);c.root.querySelectorAll('[data-race-runner]').forEach(e=>{const i=Number(e.dataset.raceRunner);e.style.left=(live.history[a][i]*(1-pos+a)+live.history[b][i]*(pos-a))/distance459(r)*100+'%'});set('[data-commentary]','接戦！ゴール前をスロー再生')}}
}
