import{temperament462}from'./RaceRules462.js';
import{rivalContent460}from'./RaceExperience460.js';
import{COURSES459,course459,bond459,temperament459,monsterHistory459}from'./RaceCourse459.js';
import{monsterVisual}from'../ui/MonsterVisual.js';
import{fatigueLabel455}from'./RaceStrategy455.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=x=>monsterVisual({speciesId:x.speciesId,visualSpeciesId:x.speciesId},'◆',{className:'race-art451'});
export function courseSelector459(r,c){if(r.rulesVersion<7)return'<p class="course-note459">新しい部屋では距離・周回を選べます。</p>';const track=course459(r.track459);return`<div class="distance-select459 distance-compact460" aria-label="レース距離">${COURSES459.map(x=>`<button data-race-distance459="${x.distance}" aria-label="${x.distance}m・${x.shape==='oval'?x.laps+'周':'直線'}" aria-pressed="${x.distance===track.distance}" ${r.phase==='lobby'&&r.hostId===c.transport.selfId?'':'disabled'}><b>${x.distance}<small>m</small></b><small>${x.shape==='oval'?x.laps+'周':'直線'}</small></button>`).join('')}</div><p class="course-note459"><b>${track.name}</b> · ${track.hint}</p>`}
export function historySummary459(rows){if(!rows?.length)return'<span class="form-empty459">出走記録なし</span>';const x=rows[0];return`<span class="form-last459">前走 <b>${x.place}着</b> <small>${esc(x.course)} ${x.distance}m</small></span><span class="form-five459">近走 ${rows.slice(0,5).map((v,i)=>`<b title="${i+1}走前：${esc(v.course)} ${v.distance}m" class="place-${v.place}">${v.place}</b>`).join('')}<small>←新</small></span>`}
export function historyDetails459(rows,key){if(!rows?.length)return'<p class="form-empty459">記録は今回の出走から残ります。</p>';const groups=new Map();for(const x of rows){const k=x.course+'・'+x.distance+'m';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)}return`<details class="history-detail459" data-detail-key="${esc(key)}"><summary>近走・条件別の成績を見る <small>${rows.length}走分</small></summary><p>新しい順。保存された直近${rows.length}走で集計。</p><div class="form-conditions459">${[...groups].map(([k,rs])=>`<span><b>${esc(k)}</b>${rs.length}走 ／ ${rs.filter(x=>x.place===1).length}勝 ／ 3着以内${rs.filter(x=>x.place<=3).length}回</span>`).join('')}</div><ol>${rows.map(x=>`<li><b>${x.place}着</b><span>${esc(x.course)} ${x.distance}m · ${x.shape==='oval'?'周回':'直線'}<small>調子 ${['落ち着かない','やや重め','平常','好調','絶好調'][x.condition]??'記録なし'} · ${fatigueLabel455(x.fatigue)}</small></span><time>${(x.finishMs/1000).toFixed(2)}秒</time></li>`).join('')}</ol></details>`}
export function ownedForm459(c,m){return historySummary459(monsterHistory459(c.state?.history459??c.bank()?.history459,m.id))}
export function bondNote459(value,version=7){if(version>=8){const t=temperament462(value);return `<span class="bond-note459 bond462">♥ なつき度 ${bond459(value)} ／ ${t.label}<small>${t.ignore?`指示無視 ${Math.round(t.ignore*100)}％（最大2回） · 休憩 ${Math.round(t.rest*100)}％ · 猛加速 ${Math.round(t.surge*100)}％`:'指示は必ず届く · 安定した走りで基本速度＋3％'}</small><small>${t.ignore?'休憩は1秒、猛加速は1.4秒。各レース最大1回。':'育てた絆が、仕掛けたい瞬間の力になる。'}</small></span>`}const t=temperament459(value);return`<span class="bond-note459">♥ なつき度 ${bond459(value)} ／ ${t.label}<small>${t.chance?`1レース${t.chance*100}％で最初の指示が0.6秒遅れる`:'指示にすぐ応える'} · 最大1回</small></span>`}
export function ownedDetails459(r,c,chosen){const m=c.save.state.monsters.find(x=>x.id===chosen.id),rows=monsterHistory459(c.state?.history459??c.bank()?.history459,chosen.id);return`${historySummary459(rows)}${r.rulesVersion>=7?bondNote459(m?.affection??m?.bond,r.rulesVersion):''}${historyDetails459(rows,'owned-'+chosen.id)}`}
export function rivalDialog459(r,c){const i=c.systemDetail459;if(!Number.isInteger(i)||!r.system[i])return'';const x=r.system[i],rows=x.history459??[];return`<div class="rival-overlay459"><button class="rival-backdrop459" data-race-action="closeSystem459" aria-label="詳細を閉じる" tabindex="-1"></button><section role="dialog" aria-modal="true" aria-labelledby="rival-title459" class="rival-dialog459 rival-dialog460" data-system-dialog459><header><span>出走予定・魔物名鑑</span><button data-race-action="closeSystem459" aria-label="詳細を閉じる">×</button></header>${r.rulesVersion>=8?bondNote459(x.bond459,r.rulesVersion):''}${rivalContent460(r,x,rows.length?historySummary459(rows)+historyDetails459(rows,'system-'+i):'<p class="form-empty459">初出走 · 今回から記録されます</p>')}<button class="race-primary451" data-race-action="closeSystem459">選択画面へ戻る</button></section></div>`}
export function paradeExtra459(r,x){if(r.rulesVersion<7)return'';return`<div class="parade-form459">${historySummary459(x.history459)}${bondNote459(x.bond459,r.rulesVersion)}${historyDetails459(x.history459,'parade-'+x.speciesId+'-'+(x.monsterId??'system'))}</div>`}
export function paceNews459(r){if(r.rulesVersion<7)return'';const front=r.racers.filter(x=>x.profile.style==='逃げ').length,c=course459(r.track459);return`<p class="pace-news459"><b>展開予想：${front>=3?'逃げ争い・前半は速め':front===0?'先頭争いは穏やか':'自分のペースを作れるか'}</b><span>${front>=3?'逃げ型が多く、序盤の消耗が増える。差し・追込は終盤に注目。':front===0?'逃げ型がいない一戦。誰が先に仕掛けるかがカギ。':'逃げの魔物が先頭を取りやすい構成。余力を残して追えるか。'}${c.shape==='oval'?'コーナーの器用さも比べよう。':''}</span></p>`}
export{broadcast461 as courseBroadcast459,updateWorld461 as updateCourseView459}from'./RaceWorld461.js';
