// Presentation state is kept separately from authoritative room/game state.
export const LEGACY_BET458=1000000;
export const MAX_BET458=Math.floor((Number.MAX_SAFE_INTEGER-8000)/1000);
export function betLimit458(gold,version=6){return Math.max(0,Math.min(Math.floor(Number(gold)||0),version>=6?MAX_BET458:LEGACY_BET458))}
export function panelKey458(c){if(c.state?.ricochet&&!c.partyBrowse462)return `rc550-${c.state.ricochet.id}:${c.state.ricochet.phase}`;if(c.state?.cart&&!c.partyBrowse462)return `c543-${c.state.cart.id}:${['lobby','result'].includes(c.state.cart.phase)?c.state.cart.phase:'play'}`;if(c.state?.bomb&&!c.partyBrowse462)return `b542-${c.state.bomb.id}:${['lobby','result'].includes(c.state.bomb.phase)?c.state.bomb.phase:'play'}`;if(c.state?.tetra&&!c.partyBrowse462)return `t539-${c.state.tetra.id}:${['lobby','result'].includes(c.state.tetra.phase)?c.state.tetra.phase:'play'}`;if(c.state?.hide&&!c.partyBrowse462)return `h536-${c.state.hide.id}:${['lobby','result'].includes(c.state.hide.phase)?c.state.hide.phase:'play'}`;if(c.state?.fishing&&!c.partyBrowse462)return `f524-${c.state.fishing.id}:${['lobby','result'].includes(c.state.fishing.phase)?c.state.fishing.phase:'play'}`;if(c.state?.sumo&&!c.partyBrowse462)return `s523-${c.state.sumo.id}:${['lobby','result'].includes(c.state.sumo.phase)?c.state.sumo.phase:'play'}`;if(c.state?.tower&&!c.partyBrowse462)return `t517-${c.state.tower.id}:${['lobby','result'].includes(c.state.tower.phase)?c.state.tower.phase:'play'}`;if(c.state?.quiz&&!c.partyBrowse462)return `q513-${c.state.quiz.id}:${['lobby','result'].includes(c.state.quiz.phase)?c.state.quiz.phase:'play'}`;if(c.state?.luck&&!c.partyBrowse462)return `lk507-${c.state.luck.id}:${['lobby','result'].includes(c.state.luck.phase)?c.state.luck.phase:'play'}`;if(c.state?.gorilla&&!c.partyBrowse462)return `gg502-${c.state.gorilla.id}:${c.state.gorilla.phase==='lobby'?'lobby':c.state.gorilla.phase==='result'?'result':'play'}`;if(c.state?.canal&&!c.partyBrowse462)return `cn489-${c.state.canal.id}:${c.state.canal.phase}`;if(c.state?.cabbage&&!c.partyBrowse462)return `cb484-${c.state.cabbage.id}:${c.state.cabbage.phase}`;if(c.state?.sugoroku&&!c.partyBrowse462)return `sg463-${c.state.sugoroku.id}:${c.state.sugoroku.phase}`;const r=c.state?.room;if(c.partyBrowse462||!r)return `party:${c.state?.party?.id??'catalog'}:hub`;return `${r?.id??'home'}:${r?.phase??'home'}:${r?.phase==='parade'?(c.predictionTab457??'watch'):''}`}
export function rememberScroll458(c){if(!c.root)return;c.scroll458??={};if(c.renderKey458)c.scroll458[c.renderKey458]={top:c.root.scrollTop,window:globalThis.scrollY??0,roster:c.root.querySelector('.race-roster451')?.scrollTop??0}}
export function restoreScroll458(c,key,oldKey){const samePhase=key.split(':').slice(0,2).join(':')===oldKey?.split(':').slice(0,2).join(':');const v=c.scroll458?.[key]??(samePhase?c.scroll458?.[oldKey]:null)??{top:0,window:0,roster:0};c.root.scrollTop=v.top;const roster=c.root.querySelector('.race-roster451');if(roster)roster.scrollTop=v.roster;if(globalThis.scrollY!==v.window)globalThis.scrollTo?.(0,v.window);c.renderKey458=key}
export function swipeDirection458(start,end){const dx=end.x-start.x,dy=end.y-start.y;return end.at-start.at<=1000&&Math.abs(dx)>=38&&Math.abs(dx)>Math.abs(dy)*1.4?(dx<0?1:-1):0}
export function editPick458(ticket,index,slot=null){const sizes={win:1,place:1,pair:2,wide:2,exact:2,trio:3,trifecta:3},max=sizes[ticket.kind]??1,picks=[...ticket.picks],at=picks.indexOf(index);if(Number.isInteger(slot)&&slot>=0&&slot<max){if(at>=0&&at!==slot){const old=picks[slot];picks[slot]=index;if(old===undefined)picks.splice(at,1);else picks[at]=old}else if(slot<picks.length)picks[slot]=index;else picks.push(index)}else if(at>=0)picks.splice(at,1);else if(picks.length<max)picks.push(index);else if(max===1)picks[0]=index;else picks[max-1]=index;return{kind:ticket.kind,picks}}
