import {SPECIES524,fishPose524,mood524,clamp524} from './Rules524.js';
import {playerColor499} from '../party/PartyColors499.js';
import {artSpec525,artFrame525} from './Catches525.js';
const art={};
function image524(name){if(art[name]||typeof Image==='undefined')return art[name];const img=new Image();img.decoding='async';img.src=`./assets/fishing524/${name}.webp`;art[name]=img;return img}
function image525(name){const key='525/'+name;if(art[key]||typeof Image==='undefined')return art[key];const img=new Image();img.decoding='async';img.src=`./assets/fishing525/${name}.webp`;art[key]=img;return img}
export function renderer524(canvas){return{canvas,ctx:canvas.getContext('2d',{alpha:false}),background:document.createElement('canvas'),pond:image524('pond'),atlas:image524('fish-atlas'),atlases525:Object.fromEntries(['river','rare','oddities','lord'].map(n=>[n,image525(n)])),width:0,height:0,artReady:false}}
export function resize524(r,w,h,dpr=1){const d=Math.min(1.5,dpr),ready=!!(r.pond?.complete&&r.pond?.naturalWidth),key=[w,h,d,ready].join(':');if(r.key===key)return;r.key=key;Object.assign(r,{width:w,height:h,dpr:d,artReady:ready});for(const c of[r.canvas,r.background]){c.width=Math.max(1,Math.round(w*d));c.height=Math.max(1,Math.round(h*d))}const b=r.background.getContext('2d');b.setTransform(d,0,0,d,0,0);b.fillStyle='#143f35';b.fillRect(0,0,w,h);if(ready)b.drawImage(r.pond,0,0,w,h);else{const grad=b.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#536e44');grad.addColorStop(.25,'#205c4b');grad.addColorStop(.75,'#0e594e');grad.addColorStop(1,'#4a3826');b.fillStyle=grad;b.fillRect(0,0,w,h);b.fillStyle='#755f3d';b.fillRect(0,h*.8,w,h*.2)}const shade=b.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#041b1b33');shade.addColorStop(.65,'#02191600');shade.addColorStop(1,'#0a1c1844');b.fillStyle=shade;b.fillRect(0,0,w,h);r.cacheBuilds=(r.cacheBuilds??0)+1}
export const dock524=(r,seat)=>({x:r.width*(.13+seat*.2467),y:r.height*.91});
export function bobber524(r,p,t){const dock=dock524(r,p.seat),progress=p.mode==='fight'?p.progress:0,wiggle=p.mode==='fight'?Math.sin(t/160+p.seat)*(mood524(p,t)==='surge'?12:4):Math.sin(t/500+p.seat)*2;return{x:r.width*p.castX*(1-progress*.63)+dock.x*progress*.63+wiggle,y:r.height*(p.castY*(1-progress*.63)+.78*progress*.63)}}
export function drawFish524(c,atlas,tier,x,y,size,angle=0,alpha=1){c.save();c.translate(x,y);c.rotate(angle);c.globalAlpha=alpha;if(atlas?.complete&&atlas.naturalWidth){const cell=atlas.naturalWidth/3;c.drawImage(atlas,(tier%3)*cell,Math.floor(tier/3)*cell,cell,cell,-size/2,-size/2,size,size)}else{c.fillStyle=SPECIES524[tier].color;c.beginPath();c.ellipse(0,0,size*.4,size*.18,0,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(size*.3,0);c.lineTo(size*.55,-size*.2);c.lineTo(size*.55,size*.2);c.fill()}c.restore()}
export function drawCatch525(c,r,fish,x,y,size,angle=0,alpha=1){
 const a=artSpec525(fish),atlas=a.sheet==='legacy'?r.atlas:r.atlases525?.[a.sheet];
 if(!atlas?.complete||!atlas.naturalWidth){drawFish524(c,r.atlas,fish.tier??0,x,y,size,angle,alpha);return}
 const uv=artFrame525(fish),iw=atlas.naturalWidth,ih=atlas.naturalHeight,cw=uv.w*iw,ch=uv.h*ih,dh=size*ch/cw;
 c.save();c.globalAlpha=alpha;c.translate(x,y);c.rotate(angle);c.drawImage(atlas,uv.x*iw,uv.y*ih,cw,ch,-size/2,-dh/2,size,dh);c.restore();
}
function lordWake525(c,x,y,size,t){
 c.save();c.translate(x,y);c.rotate(Math.sin(t/1100)*.07);c.fillStyle='#032b26b0';c.beginPath();c.ellipse(0,0,size*.46,size*.18,0,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(-size*.32,0,size*.24,size*.22,0,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(size*.32,0);c.lineTo(size*.65,-size*.22);c.lineTo(size*.6,size*.22);c.fill();c.strokeStyle='#bbcb9670';c.lineWidth=1.4;
 for(const sign of[-1,1]){c.beginPath();c.moveTo(-size*.46,sign*size*.07);c.quadraticCurveTo(-size*.65,sign*size*.31,-size*.14,sign*size*.33);c.stroke()}c.restore();ripple(c,x,y,size*.63,.22);ripple(c,x,y,size*(.55+(t%1600)/8000),.14);
}
function goldSpark525(c,x,y,size,t){c.save();c.fillStyle='#fff1a8';for(let i=0;i<8;i++){const a=i*Math.PI/4+t/1700,rr=size*(.42+(i%3)*.04),sx=x+Math.cos(a)*rr,sy=y+Math.sin(a)*rr*.6;c.globalAlpha=.35+(1+Math.sin(t/120+i))*.3;c.fillRect(sx-1,sy-4,2,8);c.fillRect(sx-4,sy-1,8,2)}c.restore()}
function ripple(c,x,y,size,alpha=.6){c.strokeStyle=`rgba(212,255,239,${alpha})`;c.lineWidth=1;c.beginPath();c.ellipse(x,y,size,size*.32,0,0,Math.PI*2);c.stroke()}
function spray(c,x,y,age,scale=1){const t=age/900;if(t<0||t>1)return;c.fillStyle=`rgba(225,255,243,${1-t})`;for(let i=0;i<12;i++){const a=i*Math.PI/6,xx=x+Math.cos(a)*t*45*scale,yy=y+Math.sin(a)*t*12*scale-Math.sin(t*Math.PI)*30*scale;c.fillRect(xx,yy,2+(i%2),3+(i%3))}ripple(c,x,y,8+t*45*scale,(1-t)*.8)}
export function paint524(r,g,t,reduced=false,selfId=null){if(!r.width)return;resize524(r,r.width,r.height,r.dpr);const c=r.ctx,w=r.width,h=r.height,elapsed=g.phase==='result'?g.elapsed+Math.max(0,t-(g.finaleUntil-5200)):Math.max(0,t-g.startAt);c.setTransform(1,0,0,1,0,0);c.drawImage(r.background,0,0);c.setTransform(r.dpr,0,0,r.dpr,0,0);
 // Thin moving highlights and ripples; the large background stays decoded and cached.
 c.save();c.beginPath();c.rect(w*.08,h*.20,w*.84,h*.53);c.clip();if(!reduced){for(let i=0;i<16;i++){const x=(i*61+Math.sin(t/2000+i)*9)%w,y=h*(.23+(i*.079)% .47);c.strokeStyle=`rgba(236,246,181,${.09+(1+Math.sin(t/600+i))*.06})`;c.lineWidth=1;c.beginPath();c.moveTo(x,y);c.quadraticCurveTo(x+9,y-2,x+22,y);c.stroke()}}
 for(const s of g.shoals){if(s.readyAt>elapsed)continue;const p=fishPose524(s,elapsed),size=s.tier===4?w*.45:12+SPECIES524[s.tier].size*14;
 if(s.tier===4){lordWake525(c,p.x*w,p.y*h,size,reduced?0:elapsed);continue}
 c.save();c.translate(p.x*w,p.y*h);c.rotate(Math.sin(elapsed/3700+s.id)*.2);c.fillStyle='#052c2880';c.beginPath();c.ellipse(0,0,size*.5,size*.17,0,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(size*.35,0);c.lineTo(size*.7,-size*.16);c.lineTo(size*.66,size*.17);c.fill();c.restore();if(s.tier>=3)ripple(c,p.x*w,p.y*h+4,size*.5,.15)}c.restore();
 for(const p of g.players){const dock=dock524(r,p.seat),color=playerColor499(p).hex;c.fillStyle='#00150c66';c.beginPath();c.ellipse(dock.x,dock.y+2,w*.051,4,0,0,Math.PI*2);c.fill();c.strokeStyle=color;c.lineWidth=p.playerId===selfId?2:1;c.beginPath();c.ellipse(dock.x,dock.y+2,w*.053,5,0,0,Math.PI*2);c.stroke();
  if(['waiting','fight'].includes(p.mode)){let float=bobber524(r,p,elapsed);const castT=clamp524((elapsed-p.castAt)/650,0,1);if(castT<1){float={x:dock.x+(float.x-dock.x)*castT,y:dock.y+(float.y-dock.y)*castT-Math.sin(castT*Math.PI)*h*.20}}
   if(p.mode==='fight'&&p.fish?.tier===4)lordWake525(c,float.x,float.y+12,w*.48,reduced?0:elapsed);
   const fighting=p.mode==='fight',mood=mood524(p,elapsed),tension=fighting?p.tension:.05,tip={x:dock.x+(float.x-dock.x)*.23,y:dock.y-h*.19+tension*h*.065};c.strokeStyle='#1d2217';c.lineWidth=4;c.beginPath();c.moveTo(dock.x+7,dock.y-14);c.quadraticCurveTo(dock.x-8,dock.y-h*.26,tip.x,tip.y);c.stroke();c.strokeStyle=p.rod>=5?'#fff0ac':p.rod>=3?'#e8d299':'#c3a76b';c.lineWidth=1.4+p.rod*.18;c.stroke();c.lineWidth=fighting?1.35:1;c.strokeStyle=tension>.78?'#ffb192':color+'c9';c.beginPath();c.moveTo(tip.x,tip.y);c.quadraticCurveTo((tip.x+float.x)/2,(tip.y+float.y)/2+(1-tension)*12,float.x,float.y);c.stroke();if(fighting&&mood==='surge')spray(c,float.x,float.y,(elapsed-p.hookedAt)%700,p.fish?.tier===4?1.5:.7);ripple(c,float.x,float.y+3,5+(elapsed%1000)/100, .48);c.fillStyle=color;c.beginPath();c.ellipse(float.x,float.y,3,fighting&&mood==='surge'?2:6,0,0,Math.PI*2);c.fill();c.fillStyle='#fff7d2';c.fillRect(float.x-1,float.y-7,2,3);
   if(fighting&&mood==='warn'){c.fillStyle='#ffe4a0';c.textAlign='center';c.font='bold 18px sans-serif';c.fillText('!',float.x,float.y-15)}
  }
 }
 for(const e of g.events){const age=elapsed-e.at;if(age<0)continue;if(e.type==='cast'||e.type==='bite'){if(age<1000)spray(c,w*e.x,h*e.y,age,e.type==='bite'?1:.6)}
 if(e.type==='chain'&&age<1050){const d=dock524(r,e.seat),f=clamp524(age/800,0,1),x=d.x+(e.x*w-d.x)*f,y=d.y+(e.y*h-d.y)*f-Math.sin(f*Math.PI)*h*.24;if(f<1)drawCatch525(c,r,e.from,x,y,w*.18*(1-f*.5),f*Math.PI*.7);else spray(c,e.x*w,e.y*h,age-800,.7);if(e.from.lure525)goldSpark525(c,x,y,w*.2,elapsed)}
 if(e.type==='land'&&age<(e.fish.tier===4?2050:1350)){const d=dock524(r,e.seat),boss=e.fish.tier===4,f=clamp524(age/(boss?1850:1150),0,1),x=e.x*w+(d.x-e.x*w)*f,y=e.y*h+(d.y-e.y*h)*f-Math.sin(f*Math.PI)*h*(boss?.4:.28),size=w*(boss?.93:.22+e.fish.tier*.035);drawCatch525(c,r,e.fish,boss?clamp524(x,w*.43,w*.57):x,y,size,Math.sin(f*Math.PI)*-.45);if(e.fish.golden525||e.fish.id==='treasure')goldSpark525(c,x,y,size,elapsed);spray(c,e.x*w,e.y*h,age,boss?3:1)}
 if(e.type==='escape'&&age<900){const d=dock524(r,e.seat);c.fillStyle='#fff0c9';c.font='bold 12px sans-serif';c.textAlign='center';c.globalAlpha=1-age/900;c.fillText(e.reason==='snap'?'糸が切れた！':'逃げられた…',d.x,d.y-40-age*.018);c.globalAlpha=1}
 if(e.type==='lord'&&age<2200){const q=age/2200;c.fillStyle=`rgba(4,30,26,${Math.sin(q*Math.PI)*.18})`;c.fillRect(0,0,w,h);ripple(c,w*.5,h*.38,20+q*w*.45,(1-q)*.6)}
 }
 if(g.phase==='result'){const age=t-(g.finaleUntil-5200),rows=g.results??[];for(const row of rows){const p=g.players.find(p=>p.playerId===row.playerId),d=dock524(r,p.seat);if(row.biggest){const winner=row.rank===1,size=winner?w*.53/(1+(g.winnerIds.length-1)*.5):w*.18,progress=clamp524(age/1500,0,1),x=winner?d.x+(w*(g.winnerIds.indexOf(p.playerId)+1)/(g.winnerIds.length+1)-d.x)*progress:d.x,y=winner?d.y+(h*.45-d.y)*progress:d.y-40;drawCatch525(c,r,row.biggest,x,y,row.biggest.tier===4&&winner?size*1.5:size,Math.sin(t/400+p.seat)*.06);}}}
}
