import {FISH524,mood524,rod524,clamp524,fishPose524} from './Rules524.js';
import {renderer524,resize524,paint524,dock524} from './Renderer524.js';
import {receiveMotion522,motionTime522,style522,class522,prop522,attr522} from '../tower/Presentation522.js';
import {controls524} from './Controls524.js';
import {unlock524,cue524} from './Audio524.js';
import {playerColor499} from '../party/PartyColors499.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.fishingUI524??={sound:true,limit:24,search:'',seq:0,input:{reel:false},useBait:true,lastSend:0,seen:0};
const me=(c,g=c.state?.fishing)=>g?.players.find(p=>p.playerId===c.transport.selfId);
const clock=c=>c.state?.fishing?.phase==='play'&&ui(c).timeline522?motionTime522(ui(c),performance.now()):Date.now()+(c.offset??0);
const pic=(c,p)=>c.sgMonster463?.(p.speciesId??p.choice?.speciesId)??'';
const fishPic=f=>f?`<i class="fi-fish524" style="background-position:${(f.tier%3)*50}% ${Math.floor(f.tier/3)*100}%" role="img" aria-label="${esc(f.name)}"></i>`:'';
const title=c=>`<header class="fi-head524"><button data-party-action462="browse" aria-label="パーティーへ戻る">‹</button><div><small>ABYSS · EMERALD LAKE</small><b>ぬし釣り大騒動</b></div><button data-fi-action="sound">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
const put=(e,s)=>{if(e&&e.textContent!==String(s))e.textContent=String(s)};
function lobby(c,g){const u=ui(c),party=c.state.party,member=g.members.find(p=>p.playerId===c.transport.selfId),pm=party.members.find(p=>p.playerId===c.transport.selfId),host=party.hostId===c.transport.selfId,list=c.roster().filter(m=>!u.search||c.sgSpeciesName463(m.raceSpeciesId??m.speciesId).includes(u.search));return`<section class="fi524 fi-lobby524">${title(c)}<div class="fi-cover524"><small>のほほん。ときどき、大騒ぎ。</small><h1>その一匹が、<br>伝説になる。</h1></div><div class="fi-body524"><div class="fi-facts524"><b>４人で釣り対決</b><b>２分＋取り込み</b><b>空席はAI</b></div><p>魚影の近くをタップして投げよう。魚が掛かったら<strong>長押しで巻く、離して緩める</strong>。暴れる予兆が出たら休んで、糸が切れないように！</p><p>釣るほど竿が成長。釣果を<strong>得点にするか、大物用のエサにするか</strong>選ぼう。エサは次の投げ入れで１個使い、大物を釣りやすくするよ。</p><p>最後の30秒で巨大なぬしが出現！ 合計得点の高い人が勝ち。同点は同率１位。終了時に掛かっている魚は最大10秒だけ取り込みを続けられるよ。</p><small>持ち込むキャラの能力差はなし。エサ・竿・釣果はこの対戦内だけ。切断・ホーム滞在時はAIが代わりに操作します。</small><h2>相棒を選ぼう</h2><input name="fishingSearch524" aria-label="魔物を探す" placeholder="魔物の名前で探す" value="${esc(u.search)}"><div class="fi-roster524">${list.slice(0,u.limit).map(m=>`<button data-fi-monster="${esc(m.id)}" aria-pressed="${member?.choice?.id===m.id}">${pic(c,{speciesId:m.raceSpeciesId??m.speciesId})}<small>${esc(c.sgSpeciesName463(m.raceSpeciesId??m.speciesId))}</small></button>`).join('')}</div>${list.length>u.limit?'<button data-fi-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="fi-error524">${esc(c.error)}</p><button class="fi-gold524" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="fi-gold524" data-fi-action="start" ${party.members.some(m=>!m.ready||!m.connected||m.atHome)||!c.ready()?'disabled':''}>のんびり釣りに出かける</button>`:'<p>部屋主が開始すると、釣りが始まるよ。</p>'}</div></section>`}
function play(c,g){return`<section class="fi524 fi-play524">${title(c)}<div class="fi-score524"><span data-fi-rod>竿 Lv.1</span><strong data-fi-time>2:00</strong><span data-fi-season>ぬしは残り30秒から</span></div><div class="fi-seats524">${g.players.map(p=>`<div style="--fi-color:${playerColor499(p).hex}">${pic(c,p)}<span><b>${esc(p.name)}</b><small data-fi-score="${p.seat}">0点</small></span></div>`).join('')}</div><div class="fi-stage524" data-fi-stage><canvas data-fi-canvas aria-label="魚影を狙って水面をタップすると投げ入れます"></canvas>${g.players.map(p=>`<div class="fi-pawn524 ${p.playerId===c.transport.selfId?'is-self':''}" data-fi-pawn="${p.seat}" style="--fi-color:${playerColor499(p).hex}"><span>${p.playerId===c.transport.selfId?'▼ あなた':esc(p.name)}</span><div class="fi-sprite524">${pic(c,p)}</div></div>`).join('')}<div class="fi-notice524" data-fi-notice></div><div class="fi-count524" data-fi-count></div><div class="fi-network524" data-fi-network hidden>再接続中… AIが引き継ぐよ</div><div class="fi-catch524" data-fi-catch hidden><small>FRESH CATCH</small><strong data-fi-catchname></strong><span data-fi-catchsize></span></div><div class="fi-finale524" data-fi-finale hidden><small>EMERALD LAKE · FISHING CHAMPION</small><h1 data-fi-winner></h1><p data-fi-ending></p></div></div><div class="fi-deck524"><div class="fi-instruction524"><strong data-fi-status>魚影の近くをタップ</strong><span data-fi-tip>大きな影には大物の予感。</span></div><div class="fi-meters524" data-fi-meters><label>取り込み<span><i data-fi-progress></i></span></label><label>糸の張り<span><i data-fi-tension></i><b></b></span></label></div><div class="fi-choice524" data-fi-choice hidden><button class="fi-gold524" data-fi-action="keep"><b data-fi-keep>得点にする</b><small>５秒で自動確保</small></button><button data-fi-action="bait" data-fi-baitbutton><b data-fi-baitchoice>エサにする</b><small>得点を手放して次に投資</small></button></div><div class="fi-controls524" data-fi-controls><button class="fi-ease524" data-fi-ease><svg viewBox="0 0 40 32" aria-hidden="true"><path d="M6 8h28M6 16h28M6 24h28"/></svg><b>緩める</b><small>暴れたら休もう</small></button><button class="fi-reel524" data-fi-reel><svg viewBox="0 0 40 32" aria-hidden="true"><path d="M30 9A12 12 0 1 0 32 21M23 9h9V1"/></svg><b>巻く</b><small>長押し · 離すと緩める</small></button></div><div class="fi-bottom524"><button data-fi-action="baitToggle" data-fi-baittoggle>エサ 0個</button><span data-fi-total>0匹 · 0点</span><button data-fi-action="cast" data-fi-cast>近くへ投げる</button></div></div></section>`}
function result(c,g){return`<section class="fi524 fi-result524">${title(c)}<div class="fi-result-hero524"><small>EMERALD LAKE · RESULT</small><h1>${g.winnerIds.includes(c.transport.selfId)?'本日の釣り名人！':'本日の釣果！'}</h1><div>${g.results.filter(r=>r.rank===1).map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<article>${pic(c,p)}${fishPic(r.biggest)}<b>${esc(p.name)}</b><strong>${r.score}点</strong></article>`}).join('')}</div></div>${resultActions490(c)}<div class="fi-body524">${g.results.map(r=>{const p=g.players.find(p=>p.playerId===r.playerId);return`<article class="fi-resultrow524"><strong>${r.rank}位</strong>${pic(c,p)}<span><b>${esc(p.name)} · ${r.score}点</b><small>${r.caught}匹釣り上げ${r.biggest?` · 最大 ${r.biggest.kg}kg`:''}${r.boss?' · ぬし '+r.boss+'匹':''}</small></span>${fishPic(r.biggest)}</article>`}).join('')}</div></section>`}
export function fishingView524(c){const g=c.state.fishing,u=ui(c);if(u.gameId!==g.id)Object.assign(u,{gameId:g.id,seq:0,input:{reel:false},seen:0,lastSend:0,timeline522:null,limit:24,search:'',useBait:true,notice:null});return g.phase==='lobby'?lobby(c,g):g.phase==='result'&&clock(c)>=g.finaleUntil?result(c,g):play(c,g)}
export function fishingReceive524(c){const g=c.state?.fishing;if(!g)return;const u=ui(c);receiveMotion522(u,g,performance.now());u.seq=Math.max(u.seq,me(c,g)?.lastSeq??0)}
export function fishingFrame524(c,m){if(m.selfId!==c.transport.selfId||!c.state?.fishing||m.fishing?.id!==c.state.fishing.id||m.fishing.serverAt<c.state.fishing.serverAt)return;const phase=c.state.fishing.phase;c.offset=m.serverNow-Date.now();c.state.fishing=m.fishing;fishingReceive524(c);if(phase!==m.fishing.phase&&(phase==='result'||m.fishing.phase==='result'))c.render()}
function send(c,force=false){const u=ui(c),g=c.state?.fishing,at=clock(c);if(g?.phase!=='play'||!me(c)||!c.ready()||!force&&at-u.lastSend<100)return;const packet={gameId:g.id,kind:'input',seq:++u.seq,reel:u.input.reel,...(u.input.cast?{cast:u.input.cast}:{}),...(u.input.choice?{choice:u.input.choice}:{})};if(c.raw('fishingInput524',packet))u.lastSend=at;delete u.input.cast;delete u.input.choice}
function cast(c,x,y){const g=c.state?.fishing,u=ui(c),p=me(c);if(g?.phase!=='play'||p?.mode!=='idle'||clock(c)-g.startAt>=120000)return;u.input.cast={x,y,bait:u.useBait};send(c,true)}
export function fishingBefore524(c){const u=c.fishingUI524;if(!u)return;if(u.scrollRaf!=null)cancelAnimationFrame(u.scrollRaf);u.scrollRaf=null;const lobby=c.root?.querySelector('.fi-lobby524');if(lobby&&c.state?.fishing?.phase==='lobby'){u.scroll={id:c.state.fishing.id,root:c.root,top:c.root.scrollTop,windowY:globalThis.scrollY??0,roster:lobby.querySelector('.fi-roster524')?.scrollTop??0,ancestors:[]};for(let e=c.root.parentElement;e;e=e.parentElement)u.scroll.ancestors.push([e,e.scrollTop])}else u.scroll=null;if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.cleanup?.();u.cleanup=null;u.root=null;u.renderer=null}
export function fishingDispose524(c){fishingBefore524(c);const u=c.fishingUI524;if(u?.scrollRaf!=null)cancelAnimationFrame(u.scrollRaf);if(u?.audio){u.audio.close()?.catch(()=>{});u.audio=null}}
export function fishingAfter524(c){const u=ui(c),g=c.state?.fishing;if(!g)return;const lobby=c.root?.querySelector('.fi-lobby524'),saved=u.scroll;if(lobby&&saved?.id===g.id&&saved.root===c.root){const apply=()=>{if(c.state?.fishing?.id!==saved.id||c.root?.querySelector('.fi-lobby524')!==lobby)return;c.root.scrollTop=saved.top;for(const[e,top]of saved.ancestors??[])e.scrollTop=top;const list=lobby.querySelector('.fi-roster524');if(list)list.scrollTop=saved.roster;if(globalThis.scrollY!==saved.windowY)globalThis.scrollTo?.(globalThis.scrollX??0,saved.windowY)};apply();u.scrollRaf=requestAnimationFrame(apply)}
 const root=c.root?.querySelector('.fi-play524');if(!root)return;u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const q=k=>root.querySelector(`[data-fi-${k}]`);u.nodes=Object.fromEntries(['stage','canvas','time','rod','season','notice','count','network','finale','winner','ending','status','tip','meters','progress','tension','choice','controls','reel','ease','baittoggle','total','cast','catch','catchname','catchsize','keep','baitchoice','baitbutton'].map(k=>[k,q(k)]));u.pawns=g.players.map(p=>root.querySelector(`[data-fi-pawn="${p.seat}"]`));u.sprites=u.pawns.map(p=>p.querySelector('.fi-sprite524'));u.scores=g.players.map(p=>root.querySelector(`[data-fi-score="${p.seat}"]`));u.renderer=renderer524(u.nodes.canvas);
 const abort=new AbortController(),on=(el,name,fn,options={})=>el?.addEventListener(name,fn,{...options,signal:abort.signal});u.controls=controls524(root,on,u.input,()=>send(c,true),()=>c.state?.fishing?.phase==='play'&&!!me(c)&&c.ready(),()=>unlock524(u),(x,y)=>cast(c,x,y));
 const resize=()=>resize524(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const unlockZoom=lockPlayZoom498(root);
 const tick=()=>{if(!u.root||document.hidden)return;u.raf=null;paint(c);if(u.root&&!document.hidden)u.raf=requestAnimationFrame(tick)};
 on(document,'visibilitychange',()=>{if(document.hidden){u.controls.clear();if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{})}else{u.timeline522=null;c.refresh?.();if(u.raf==null)tick()}});
 u.cleanup=()=>{u.controls.clear();abort.abort();observer.disconnect();unlockZoom();u.controls=null};fishingReceive524(c);tick();
}
function paint(c){const u=ui(c),g=c.state.fishing,n=u.nodes,r=u.renderer,p=me(c,g),at=clock(c),elapsed=g.phase==='result'?g.elapsed:Math.max(0,at-g.startAt);if(at-u.lastSend>=100)send(c);paint524(r,g,at,u.reduced,c.transport.selfId);
 for(const player of g.players){const dock=dock524(r,player.seat),mood=mood524(player,elapsed),fight=player.mode==='fight',pull=fight?player.tension*12+(mood==='surge'&&!u.reduced?Math.sin(at/55)*3:0):0,size=r.width*.115,landing=player.mode==='landing'?Math.sin(clamp524((elapsed-player.landedAt)/1100,0,1)*Math.PI)*12:0,node=u.pawns[player.seat];style522(node,'width',size+'px');style522(node,'height',size+'px');style522(node,'transform',`translate3d(${dock.x-size/2}px,${dock.y-size-pull-landing}px,0)`);style522(u.sprites[player.seat],'transform',`rotate(${fight?(player.reel?-8:8):Math.sin(at/900+player.seat)*(u.reduced?0:2)}deg)`);class522(node,'is-pulling',fight&&mood==='surge');put(u.scores[player.seat],player.score+'点'+(player.auto?' · AI':''))}
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(elapsed-e.at>900)continue;cue524(u,e.type);if(e.type==='lord')u.notice={text:'水面が揺れる… ぬし、出現！',until:at+2600};if(e.type==='land'&&e.fish.tier===4)u.notice={text:g.players[e.seat].name+' が、ぬしを釣り上げた！',until:at+2000}}
 put(n.notice,u.notice&&at<u.notice.until?u.notice.text:'');prop522(n.count,'hidden',g.phase!=='countdown');put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000)));prop522(n.network,'hidden',c.connected());const left=Math.max(0,Math.ceil((120000-elapsed)/1000));put(n.time,g.phase==='result'?'終了':elapsed>=120000?'取り込み中':`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`);put(n.season,g.phase==='result'?'釣果をお披露目':elapsed>=120000?'あと '+Math.max(0,Math.ceil((130000-elapsed)/1000))+'秒':g.boss?'ぬし、出現中！':'ぬしまで '+Math.max(0,Math.ceil((90000-elapsed)/1000))+'秒');
 if(p&&p.mode!=='fight'&&u.input.reel)u.controls.clear();if(p){const mode=p.mode,mood=mood524(p,elapsed),fight=mode==='fight',choice=mode==='choice',status=mode==='idle'?elapsed>=120000?'みんなの取り込みを見届けよう':'魚影の近くをタップ':mode==='waiting'?'浮きが沈むのを待とう…':fight?mood==='surge'?'暴れてる！ 緩めよう！':mood==='warn'?'暴れる予兆！ 巻く手を休めて':mood==='tired'?'今がチャンス！ 巻こう！':'長押しで巻こう！':mode==='landing'?'釣れた！':choice?'得点にする？ 次のエサにする？':'次の一投を準備中';put(n.status,status);class522(n.status,'is-danger',fight&&['warn','surge'].includes(mood));put(n.tip,fight?p.tension>.78?'糸が限界！ 指を離そう！':'糸の張りに注意 · 離すと緩まる':mode==='idle'?'水面タップで狙えるよ。':'釣るほど竿が強くなる');class522(n.meters,'is-muted',!fight);style522(n.progress,'transform',`scaleX(${p.progress??0})`);style522(n.tension,'transform',`scaleX(${p.tension??0})`);class522(n.tension,'is-danger',p.tension>.7);prop522(n.choice,'hidden',!choice);prop522(n.controls,'hidden',choice);prop522(n.reel,'disabled',!fight||g.phase!=='play');prop522(n.ease,'disabled',!fight||g.phase!=='play');prop522(n.cast,'disabled',mode!=='idle'||elapsed>=120000||g.phase!=='play');put(n.rod,'竿 Lv.'+rod524(p));put(n.total,p.caught+'匹 · '+p.score+'点');put(n.baittoggle,'エサ '+p.bait+'個 · '+(u.useBait?'使う':'温存'));attr522(n.baittoggle,'aria-pressed',u.useBait);class522(n.baittoggle,'is-on',u.useBait&&p.bait>0);prop522(n['catch'],'hidden',!['landing','choice'].includes(mode));if(p.fish){put(n.catchname,p.fish.name);put(n.catchsize,p.fish.kg+'kg · '+p.fish.value+'点');put(n.keep,'＋'+p.fish.value+'点で確保');put(n.baitchoice,p.bait>=3?'エサ満タン':'エサ ＋'+Math.min(3-p.bait,p.fish.tier>=2?2:1)+'個');prop522(n.baitbutton,'disabled',p.bait>=3)}
 }
 if(!p){put(n.status,'観戦中 · 次の対戦から参加できるよ');put(n.tip,'みんなの釣果を見届けよう');put(n.rod,'観戦中');for(const el of[n.reel,n.ease,n.cast,n.baittoggle])prop522(el,'disabled',true);prop522(n.choice,'hidden',true);class522(n.meters,'is-muted',true)}
 if(g.phase==='result'){const age=at-(g.finaleUntil-5200);prop522(n.finale,'hidden',age<1200);put(n.winner,g.winnerIds.length>1?'みんな釣り名人！':'本日の釣り名人！');put(n.ending,g.winnerIds.map(id=>g.players.find(p=>p.playerId===id).name).join('・'));if(at>=g.finaleUntil)c.render()}
}
export function fishingClick524(c,b){const d=b.dataset,g=c.state?.fishing;if(!g||!Object.keys(d).some(k=>k.startsWith('fi')))return false;const u=ui(c);unlock524(u);if(d.fiMonster)c.raw('fishing524',{gameId:g.id,kind:'select',monsterId:d.fiMonster});if(d.fiAction==='more'){u.limit+=24;c.render()}if(d.fiAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock524(u)}if(d.fiAction==='start')c.raw('fishing524',{gameId:g.id,kind:'start'});if(d.fiAction==='baitToggle')u.useBait=!u.useBait;if(['keep','bait'].includes(d.fiAction)&&me(c)?.mode==='choice'){u.input.choice=d.fiAction;send(c,true)}if(d.fiAction==='cast'){const p=me(c);if(!p)return true;const ready=g.shoals.filter(s=>s.readyAt<=g.elapsed),s=ready.sort((a,b)=>Math.abs(a.x-(.13+p.seat*.2467))-Math.abs(b.x-(.13+p.seat*.2467)))[0];const pos=s?fishPose524(s,g.elapsed):{x:.13+p.seat*.2467,y:.56};cast(c,pos.x,pos.y)}return true}
export function fishingInput524(c,e){if(!c.state?.fishing||e.name!=='fishingSearch524')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function fishingKey524(c,e){return ui(c).controls?.keydown(e)??false}
