import{NODES465 as NODES,region465}from'./Adventure467.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function arrivalText472(node,hasSpecial=false){if(node?.effects.some(e=>e.type==='shrine469'))return hasSpecial?'覚醒済み：安全に1枚 ＋ 未所持の絵柄1種':'神殿の報酬：覚醒能力 ＋ 未所持の絵柄1種';return node?.text??'';}
// Only public movement information. Stop at the same gate / next junction as the engine.
export function traceChoice472(rootId,nextId,remaining,visited=[]){const path=[rootId];let next=nextId,n=remaining,forced=false;while(n>0&&next){const node=NODES[next];if(!node)break;path.push(next);n--;if(node.kind==='gate'&&!visited.includes(next)){forced=true;break;}if(node.next.length>1||node.kind==='goal')break;next=node.next[0];}return{path,last:NODES[path.at(-1)],forced,remaining:n};}
export function forkView472(q,owner,disabled=false){
 const info=q.fork472??{nodeId:owner.pos,remaining:1,visitedGateIds:[]},root=NODES[info.nodeId],direct=NODES[root.next[0]],detour=[root,...Array.from({length:4},(_,i)=>NODES[`b${root.id}-${i}`]),direct],all=[root,direct,...detour];
 const pad=95,x=Math.max(0,Math.min(...all.map(n=>n.x))-pad),y=Math.max(0,Math.min(...all.map(n=>n.y))-pad),w=Math.max(...all.map(n=>n.x))-x+pad,h=Math.max(...all.map(n=>n.y))-y+pad;
 const line=ns=>ns.map(n=>`${n.x},${n.y}`).join(' '),text=(n,label,dy)=>`<text x="${n.x}" y="${n.y+dy}" text-anchor="middle">${esc(label)}</text>`;
 return`<div class="sg-fork472"><div class="sg-fork-position472"><span>現在地 · ${esc(region465(root).name)}</span><b>${root.index}番マスの分岐</b><small>ここから進路を選びます · 残り ${info.remaining} マス</small></div><svg class="sg-fork-map472" viewBox="${x} ${y} ${w} ${h}" role="img" aria-label="現在の盤面の拡大図。金色が近道、青色が寄り道"><image href="./assets/sugoroku467/world.png" width="1600" height="3200"/><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#090e18" opacity=".22"/><polyline class="is-treasure" points="${line(detour)}"/><polyline class="is-short" points="${line([root,direct])}"/>${detour.slice(1,-1).map((n,i)=>`<circle class="is-treasure" cx="${n.x}" cy="${n.y}" r="7"/>`).join('')}<circle class="is-short" cx="${direct.x}" cy="${direct.y}" r="18"/>${text(direct,direct.name,-28)}<circle class="is-current" cx="${root.x}" cy="${root.y}" r="21"/>${text(root,'現在地',41)}</svg><div class="sg-fork-legend472"><span>● 近道</span><span>● 寄り道（4マス長い）</span></div><div class="sg-fork-options472">${q.options.map((o,i)=>{const prediction=traceChoice472(root.id,o.value,info.remaining,info.visitedGateIds),end=prediction.last;return`<button class="${i?'is-treasure':'is-short'}" data-sg-action="choice" data-value="${esc(o.value)}" ${disabled?'disabled':''}><span>${i?'02 · カードを集める':'01 · ゴールへ最短'}</span><b>${esc(o.label)} <i>›</i></b><strong>${prediction.forced?'必ず停止':'この出目の行き先'}：${esc(end.name)}</strong><small>${end.next.length>1&&!prediction.forced&&prediction.remaining>0?'次の分岐で、もう一度進路を選びます':esc(arrivalText472(end,!!owner.special))}</small>${i?'<em>寄り道：① 安全に2枚 → ② 1枚捨て3枚 → ③ 特殊獲得 → ④ 浄化</em>':''}</button>`}).join('')}</div><p class="sg-fork-note472">マスの効果は、止まった場所だけで発動。<br>神殿は初めて通ると必ず停止し、報酬を受け取ります。</p></div>`;
}
