import{bonus480}from'./Economy480.js';
import{prizeSlots474,checkpointAmount474,rewardMode474}from'./Rewards474.js';
const num=n=>Number(n??0).toLocaleString('ja-JP'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function economyLobby474(c,g){const e=g.economy474;if(!e)return'';const host=c.state.party?.hostId===c.transport.selfId,fee=e.fee,paid=rewardMode474(g),limit=c.state.party?.minimumCrystals474??0;const draftKey=g.id+':'+(e.epoch??0),draft=c.sgUI463?.feeDraft474?.key===draftKey?c.sgUI463.feeDraft474.value:String(fee);return`<section class="sg-economy474"><div class="sg-economy-head474"><span>CRYSTAL CHALLENGE</span><b>${paid?'💎 報酬戦':'無料練習'}</b></div>${host?`<div class="sg-fee-controls474"><label>1人あたりの参加費<input name="sgFee474" type="number" inputmode="numeric" min="1" max="${limit}" step="1" value="${esc(draft)}" aria-label="1人あたりの参加費"></label><button data-sg-action="fee474" ${limit<1?'disabled':''}>この金額で報酬戦</button><button data-sg-action="practice474">無料練習</button></div>`:''}<p>参加メンバーの所持💎の最少額：<b>${num(limit)}</b><br>${host?'この範囲で部屋主が参加費を設定。':'部屋主が参加費を設定。'}変更時は参加費を返金し、全員が再確認。</p>${paid?`<strong class="sg-entry-fee474">参加費 💎${num(fee)} / 人</strong><p>参加費をそのまま対戦用の持ち金に。奪取は相手から移動、損失分は共有の宝庫へ戻ります。<br>泉・神殿・寄り道・2倍は宝庫から獲得。終了時に各自から最大20％を集め、順位順に50％・30％・15％・5％で分配。</p><p>本編へ戻る総額の上限：実プレイヤーの参加費合計 ＋ 追加分（合計の20％まで）。<br>あなた1人＋AIなら受取上限💎${num(fee+bonus480(fee,1))}。超過時は実プレイヤー間で比例調整。AIから奪っても上限は同じ。</p><small>保存して中断・再開できます。途中終了は参加費返金・報酬なし。</small>`:'<p>💎の支払・報酬なしで、同じルールを練習できます。対戦中の仮想💎も表示されます（参加費500相当）。</p>'}</section>`}
export function entryLabel474(c,g,ready){if(ready)return'✓ 準備OK · 取り消す';if(!rewardMode474(g))return'準備OK';return g.economy474.entries?.includes(c.transport.selfId)?'参加費受付済み · 準備OK':`💎${num(g.economy474.fee)}を払って参加`}
export function rewardResult474(c,g){const row=g.results?.find(r=>r.playerId===c.transport.selfId),r=row?.crystals474;if(!r)return g.economy474?.mode==='practice'?'<p class="sg-practice474">無料練習 · 💎の増減なし</p>':'';
 const key=c.key?.(),bank=key?c.save?.state.sugoroku474?.accounts?.[key]:null,received=Object.values(bank?.applied??{}).some(e=>e.gameId===g.id&&e.kind==='result');return`<section class="sg-crystal-result474"><small>あなたの冒険の報酬</small><div class="sg-crystal-icon474" aria-hidden="true">◆</div><strong>💎 ${num(r.total)}</strong><b class="${r.net>=0?'is-profit':'is-loss'}">収支 ${r.net>0?'+':''}${num(r.net)} 💎</b><dl><div><dt>順位報酬 · ${row.place}位</dt><dd>+${num(r.prize)}</dd></div><div><dt>対戦中の持ち金</dt><dd>+${num(r.journey)}</dd></div>${r.economy480?`<div><dt>供給上限による調整</dt><dd>−${num(r.adjustment480)}</dd></div>`:''}<div><dt>参加費</dt><dd>−${num(r.fee)}</dd></div></dl><p role="status">${c.rewardError?esc(c.rewardError):received?'✓ 本編の所持💎に受取済み':'💎の受取を保存しています。再接続しても二重には受け取りません。'}</p></section>`}
export const journeyLabel474=(g,id)=>rewardMode474(g)?`<span class="sg-journey474">💎${num(g.players.find(p=>p.playerId===id)?.crystals474)}<small> 終了時に精算</small></span>`:'';
export function rewardRow474(p){const r=p.crystals474;return r?`<small class="sg-reward-row474">💎${num(r.total)} · 収支 ${r.net>0?'+':''}${num(r.net)}</small>`:''}
