import{rankStyle466}from'./CardRanks466.js';
import{orderedHand466,bindHand466}from'./HandOrder466.js';
import{tileLabel464,cardState464,presentationBusy464,presentationAfter464,visualGame466}from'./Presentation464.js';
import{CARDS463,CARD_BY_ID463,SPECIAL_BY_ID463,TIMING463,DECK_COUNT463}from'./Catalog463.js';
import{ATTRS463,distance463}from'./Board463.js';
import{BOARD465 as BOARD463,NODES465 as NODES463,WORLD465 as BOARD_SIZE463,REGIONS465,region465,path465,tileArt465,tileSvg467,bridgeSvg467}from'./Adventure467.js';
import{partySeats462}from'../party/PartyView462.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#68b4ff','#79dda9','#ffb367','#ef91ca'];
const ui=c=>c.sgUI463??=( {filter:'all',sort:'received',follow:true,zoom:.72,x:0,y:0,modal:null,scrolls:{}} );
export const art463=(n,cls='')=>`<span class="sg-art ${cls}" style="background-position:${(n%4)*100/3}% ${Math.floor(n/4)*100/3}%" aria-hidden="true"></span>`;
const cardArt=c=>c.set==='dark'?`<span class="sg-art" style="background-size:800% 800%;background-position:${(2+c.part%2)*100/7}% ${(4+Math.floor(c.part/2))*100/7}%" aria-hidden="true"></span>`:art463(c.art);
const attr=c=>c.attrs.length===4?'全属性':c.attrs.length?c.attrs.map(a=>ATTRS463.find(x=>x.id===a)?.name).join('・'):'無属性';
const token=(c,p)=>c.sgMonster463?.(p.choice?.speciesId)??art463(12+(p.seat??0)%4);
const button=(action,text,disabled=false,cls='')=>`<button class="${cls}" data-sg-action="${action}" ${disabled?'disabled':''}>${text}</button>`;
function cardFace(card,{uid='',small=false,usable=false,ward=false,action='card',state='',angle=0,value=''}={}){return`<button class="sg-card sg-${card.kind}${usable?' is-usable':uid?' is-unavailable':''}${small?' sg-card-small':''}" style="${rankStyle466(card)};--card-angle:${angle}deg;--card-accent:${ATTRS463.find(a=>a.id===card.attrs[0])?.color??'#dfc38e'}" data-sg-action="${action}" data-value="${esc(value)}" data-card="${esc(card.id)}" data-uid="${esc(uid)}" aria-label="${esc(card.name)}、${esc(state||TIMING463[card.timing])}。タップして詳細"><span class="sg-card-top"><span><i class="sg-rank466">${esc(card.rank466)}</i> ${esc(TIMING463[card.timing])}</span><b>${card.points>0?'+':''}${card.points}<small>pt</small></b></span>${cardArt(card)}<strong>${esc(card.name)}</strong><span class="sg-attrs">${card.attrs.length?card.attrs.map(a=>`<i style="--attr:${ATTRS463.find(x=>x.id===a)?.color}">${esc(ATTRS463.find(x=>x.id===a)?.name)}</i>`).join(''):'<i class="sg-neutral">無</i>'}</span><span class="sg-card-caption">${esc(card.summary466??card.text)}</span><span class="sg-card-note466">${esc(card.note466??'')}</span>${uid?`<span class="sg-card-state464">${usable?'✦ ':''}${esc(state|| (ward?'攻撃時に防御':'詳細を見る'))}</span>`:''}</button>`}
function specialFace(id){const s=SPECIAL_BY_ID463[id];return s?`<div class="sg-special-detail">${art463(s.art)}<div><small>特殊カード · 公開</small><h2>${esc(s.name)} <b>${s.points>0?'+':''}${s.points}pt</b></h2><p>${esc(s.text)}</p></div></div>`:'<p>特殊カードはまだありません。</p>'}
function header(c,g){return`<header class="sg-header">${button('browse','‹ パーティー')}<div><small>ABYSS DOMINION</small><b>カードすごろく</b></div>${button(g.phase==='playing'?'gameMenu465':'rules',g.phase==='playing'?'メニュー':'遊び方')}</header>${!c.connected()?'<div class="sg-notice" role="status">再接続中… 手札と盤面を保持しています。</div>':''}${c.error?`<div class="sg-notice sg-error" role="alert">${esc(c.error)} ${button('refresh','更新')}</div>`:''}`}
function lobby(c,g){const p=c.state.party,id=c.transport.selfId,me=g.members.find(m=>m.playerId===id),ready=p.members.find(m=>m.playerId===id)?.ready,host=p.hostId===id,roster=c.roster(),q=ui(c).search??'',rows=roster.filter(m=>(c.sgSpeciesName463?.(m.speciesId)??m.speciesId).includes(q)),limit=ui(c).rosterLimit??24;return`<section class="sg-screen sg-lobby">${header(c,g)}<div class="sg-lobby-hero"><img src="./assets/sugoroku463/cover.png" alt="魔物たちとカードが集う星の回廊"><div><span>星砕きの回廊</span><h1>運命は、手札の中に。</h1><p>先にゴールするか。最後まで切り札を隠すか。</p><b>4人対戦 · 足りない席はAI · 目安20〜40分</b></div></div><div class="sg-lobby-body"><div class="sg-room-code"><span>合言葉 <b>${esc(p.code)}</b></span><button data-party-action462="copy">コピー</button><button data-party-action462="invite">招待リンク</button></div>${partySeats462(c)}<div class="sg-lobby-summary"><span><b>${CARDS463.length}種類</b>山札${DECK_COUNT463}枚</span><span><b>16種類</b>公開の特殊カード</span><span><b>3つの分岐</b>カードが集まる寄り道</span></div><div class="sg-section-line"><h2>コマにする魔物を選ぶ</h2><small>強さによる有利・不利はありません</small></div><input name="sgSearch463" type="search" placeholder="魔物の名前で探す" value="${esc(q)}" aria-label="コマにする魔物を検索"><div class="sg-roster" data-sg-scroll="roster">${rows.slice(0,limit).map(m=>`<button data-sg-action="select" data-monster="${esc(m.id)}" class="${me?.choice?.id===m.id?'is-selected':''}">${token(c,{choice:m})}<b>${esc(c.sgSpeciesName463?.(m.speciesId)??m.speciesId)}</b><small>${me?.choice?.id===m.id?'✓ 選択中':'コマにする'}</small></button>`).join('')||'<p>該当する魔物がいません。</p>'}</div>${rows.length>limit?button('more','さらに表示'):''}<div class="sg-lobby-actions"><button data-party-action462="ready" aria-pressed="${!!ready}" ${!me?.choice||!c.ready()?'disabled':''}>${ready?'✓ 準備OK':'準備OK'}</button>${host?button('start','冒険をはじめる',!c.ready()||p.members.some(m=>!m.ready||!m.connected||m.atHome),'sg-primary'):'<p>全員の準備ができたら、部屋主が開始します。</p>'}</div><p class="sg-muted">3人目のゴールで終了。手札＋特殊カード＋到着ボーナスの合計点で勝負！</p></div>${modal(c,g)}</section>`}
function board(c,g){const u=ui(c);return`<div class="sg-board-wrap"><div class="sg-board-tools"><span>${esc(region465(NODES463[g.players.find(p=>p.playerId===g.turnPlayerId)?.pos]).name)} <small>マスをタップで説明</small></span><div>${button('overview','全体')}${button('follow',u.follow?'追尾中':'手番へ',false,u.follow?'is-active':'')}</div></div><div class="sg-viewport" aria-label="すごろく盤。ドラッグで移動、ピンチで拡大"><div class="sg-world is-restoring466" style="transform:translate(${u.x}px,${u.y}px) scale(${u.zoom});width:${BOARD_SIZE463.width}px;height:${BOARD_SIZE463.height}px"><svg class="sg-map" viewBox="0 0 ${BOARD_SIZE463.width} ${BOARD_SIZE463.height}" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="sgPath463"><stop stop-color="#6d5185"/><stop offset="1" stop-color="#dbb975"/></linearGradient></defs><g class="sg-paths">${BOARD463.flatMap(n=>n.next.map(id=>{const end=NODES463[id];return n.detour||end.detour?bridgeSvg467(n,end):''})).join('')}</g>${BOARD463.map(n=>`<g class="sg-tile sg-tone-${n.tone}" transform="translate(${n.x},${n.y})" role="button" tabindex="0" aria-label="${esc(n.name)}。${esc(n.text)}" data-sg-tile="${n.id}">${tileSvg467(n,esc(tileLabel464(n)))}</g>`).join('')}</svg>${g.players.map(p=>{const n=NODES463[p.pos],stack=g.players.filter(x=>x.pos===p.pos),i=stack.indexOf(p),x=n.x+(i-(stack.length-1)/2)*25,y=n.y-48;return`<div class="sg-token${p.playerId===g.turnPlayerId?' is-current':''}${p.finished?' is-finished':''}" data-sg-token="${esc(p.playerId)}" style="left:${x}px;top:${y}px;--seat:${colors[p.seat]}">${token(c,p)}<b>${esc(p.name)}${p.finished?' · '+p.finished.place+'着':''}</b></div>`}).join('')}</div><div class="sg-board-vignette"></div>${phaseStrip466(c,g)}${turnPrompt466(c,g)}<div class="sg-presentation464" aria-live="polite" aria-atomic="true"></div><div class="sg-roll-display" aria-live="off">${g.lastRoll?`<small>${esc(g.players.find(p=>p.playerId===g.lastRoll.playerId)?.name)}の出目</small><div>${g.lastRoll.dice.map(n=>`<i>${['⚀','⚁','⚂','⚃','⚄','⚅'][n-1]}</i>`).join('')}<b>${g.lastRoll.total}<small>マス</small></b></div>`:'<small>カードを引いて、冒険のはじまり。</small>'}</div></div></div>`}
function phaseStrip466(c,g){const step=g.pending?'card':g.step==='draw'?'draw':g.step==='pre'?'card':g.step==='post'?'end':'move';return`<div class="sg-phase466" aria-label="手番の流れ">${[['draw','引く'],['card','カード'],['move','移動'],['tile','マス効果'],['end','終了']].map(([id,name])=>`<span data-phase466="${id}" class="${id===step?'is-current':''}">${name}</span>`).join('')}${g.pending?.kind==='defense'?'<b>防御の割り込み</b>':''}</div>`}
function turnPrompt466(c,g){const u=ui(c),busy=presentationBusy464(c,g)||Date.now()+c.offset<(g.presentationUntil465??0);if(busy||g.pending||u.modal||g.turnPlayerId!==c.transport.selfId||g.phase!=='playing')return'';const draw=g.step==='draw',pre=g.step==='pre',action=draw?'draw':pre?'roll':'end',label=draw?'1枚引く':pre?(g.ownMods?.noRoll?'移動を確定':'サイコロを振る'):'手番を終える',count=g.hand.filter(h=>h.playable).length;if(pre&&!g.ownMods?.noRoll)return`<div class="sg-turn-prompt466 sg-dice-prompt467"><div><small>あなたの番</small><button data-sg-action="roll" class="sg-tap-dice467" aria-label="サイコロをタップして振る" ${!c.connected()||u.inFlight?'disabled':''}><img src="./assets/sugoroku467/dice.png" alt="金の縁取りのサイコロ" draggable="false"></button><b>タップして振る</b><span>${count?`先に使える手札 ${count}枚`:'準備ができたらサイコロをタップ'}</span></div></div>`;return`<div class="sg-turn-prompt466"><div><small>あなたの番 · ${draw?'まずはドロー':pre?'移動前':'移動後'}</small>${button(action,label,!c.connected()||!!u.inFlight,'sg-primary')}<span>${draw?'山札から運命の1枚を':count?`先に使える手札 ${count}枚`:g.autoAdvance464?'できることがないため自動で進みます':'準備ができたら進もう'}</span></div></div>`}
function seats(c,g){return`<div class="sg-seats">${g.players.map(p=>`<button data-sg-action="player" data-player="${esc(p.playerId)}" class="sg-seat${p.playerId===g.turnPlayerId&&!p.finished?' is-turn':''}${p.playerId===c.transport.selfId?' is-self':''}${p.special?' is-awakened466':''}" style="--seat:${colors[p.seat]}"><span class="sg-seat-pawn465">${token(c,p)}</span><span class="sg-seat-name">${p.ai?'AI ':''}${esc(p.name)}</span><b>${p.finished?p.finished.place+'着 · '+p.finished.total+'点':'残'+distance463(p.pos)+'マス'}</b><small>手札 ${p.handCount}枚${p.skip?' · 休'+p.skip:''}</small>${p.special?`<em>✦ ${esc(SPECIAL_BY_ID463[p.special]?.name)}</em>`:''}</button>`).join('')}</div>`}
function hand(c,g){const u=ui(c),own=g.players.find(p=>p.playerId===c.transport.selfId);if(!own)return'<div class="sg-observer">今回は観戦中。次のゲームから参加できます。</div>';let cards=(u.sort==='manual'?orderedHand466(u,g,c.transport.selfId):(orderedHand466(u,g,c.transport.selfId),g.hand)).map(h=>({...h,c:CARD_BY_ID463[h.cardId]}));if(u.filter==='play')cards=cards.filter(h=>h.playable);else if(u.filter==='curse')cards=cards.filter(h=>h.c.kind==='curse');else if(u.filter!=='all')cards=cards.filter(h=>h.c.attrs.includes(u.filter));if(u.sort==='points')cards.sort((a,b)=>b.c.points-a.c.points);const sets=['heroes','dark'].map(set=>({set,n:new Set(g.hand.map(h=>CARD_BY_ID463[h.cardId]).filter(c=>c.set===set).map(c=>c.part)).size})).filter(x=>x.n);
return`<section class="sg-hand-section${u.handTools?' has-tools465':''}"><div class="sg-hand-heading"><h2>あなたの手札 <b>${g.hand.length}</b></h2><span>現在 ${g.ownScore?.total??0}pt <small>＋到着ボーナス</small></span>${button('handSize',u.handOpen?'縮める':'広げる')}${button('handTools',u.handTools?'閉じる':'整理')}${button('log','履歴')}<select name="sgSort463" aria-label="手札の並び順"><option value="manual" ${u.sort==='manual'?'selected':''}>手動順</option><option value="received" ${u.sort==='received'?'selected':''}>入手順</option><option value="points" ${u.sort==='points'?'selected':''}>得点順</option></select></div><div class="sg-hand-hint464">${g.hand.filter(h=>h.playable).length?`✦ 光るカードが使える · ${g.hand.filter(h=>h.playable).length}枚`:'タップで詳細 · 長押しで並び替え'}</div><div class="sg-filters" data-sg-scroll="filters">${[['all','すべて'],['play','使える'],...ATTRS463.map(a=>[a.id,a.name]),['curse','呪い']].map(([id,name])=>`<button data-sg-action="filter" data-filter="${id}" class="${u.filter===id?'is-active':''}" aria-pressed="${u.filter===id}">${name}</button>`).join('')}${sets.map(x=>`<span class="sg-set-progress ${x.n===4?'is-complete':''}">${x.set==='heroes'?'四勇者':'闇の絵柄'} ${x.n}/4</span>`).join('')}</div><div class="sg-hand" data-sg-scroll="hand">${cards.map((h,i)=>cardFace(h.c,{uid:h.uid,usable:h.playable,ward:h.ward,small:true,state:cardState464(h.c,h,g,c.transport.selfId),angle:Math.max(-3,Math.min(3,(i-(cards.length-1)/2)*2))})).join('')||'<p class="sg-hand-empty">この条件のカードはありません。</p>'}</div></section>`}
function controls(c,g){const me=g.players.find(p=>p.playerId===c.transport.selfId),turn=g.turnPlayerId===c.transport.selfId,actor=g.players.find(p=>p.playerId===g.turnPlayerId),q=g.pending,disabled=!c.connected()||!!ui(c).inFlight||presentationBusy464(c,g)||Date.now()+c.offset<(g.presentationUntil465??0);let text=me?.finished?'ゴール済み · 得点確定':!me?'観戦中':turn?g.step==='draw'?'あなたの番 · 1枚引く':g.step==='pre'?'あなたの番 · 移動前':'あなたの番 · 移動後':`${actor?.name??'相手'}の手番`;if(q)text=q.playerId===c.transport.selfId?'あなたの選択を待っています':`${g.players.find(p=>p.playerId===q.playerId)?.name??'相手'}が選択中`;
 const specials=!!g.ownSpecialPlayable464;if(turn&&!q&&g.autoAdvance464)text=g.autoAdvance464==='roll'?'自動でサイコロへ':g.autoAdvance464==='draw'?'1回休み · 自動進行':'次の手番へ進みます';
 if(presentationBusy464(c,g)||Date.now()+c.offset<(g.presentationUntil465??0))text='演出を確認中';return`<div class="sg-action-dock"><div class="sg-turn-label"><i class="${turn?'is-you':''}"></i><b>${esc(text)}</b><small data-sg-timer></small></div><div class="sg-action-buttons">${q?.playerId===c.transport.selfId?button('choiceOpen','選択を開く',disabled,'sg-primary'):!q&&turn&&!me?.finished?`${specials&&g.step!=='draw'?button('special','✦ 特殊能力',disabled):''}`:'<span class="sg-waiting">相手の冒険を見守ろう</span>'}${me?.special?button('mine',esc(SPECIAL_BY_ID463[me.special].name)):''}</div></div>`}
function results(c,g){const host=c.state.party?.hostId===c.transport.selfId;return`<section class="sg-screen sg-result">${header(c,g)}<div class="sg-result-hero"><small>星砕きの回廊 · 結果</small><h1>${esc(g.results[0].name)}</h1><p>得点1位 <b>${g.results[0].total}<small>pt</small></b></p>${token(c,g.players.find(p=>p.playerId===g.results[0].playerId))}</div><div class="sg-results-table" data-sg-scroll="results"><table><thead><tr><th>順位 / プレイヤー</th><th>到着</th><th>手札</th><th>特殊</th><th>加点</th><th>合計</th></tr></thead><tbody>${g.results.map((p,i)=>`<tr class="${p.playerId===c.transport.selfId?'is-self':''}"><th><button data-sg-action="player" data-player="${esc(p.playerId)}"><b>${i+1}</b> ${esc(p.name)}</button></th><td>${p.place}着<br><small>＋${p.bonus}</small></td><td>${p.hand}</td><td>${p.special}</td><td>${p.affinity}</td><td><b>${p.total}</b></td></tr>`).join('')}</tbody></table></div><p class="sg-muted">得点が同じ場合は、先に到着した人が上位。<br>プレイヤー名から、最後の手札を確認できます。</p><div class="sg-result-actions">${host?button('again','同じメンバーでもう一度',!c.connected(),'sg-primary'):button('browse','パーティーに戻る',false,'sg-primary')}${host?'<button data-party-action462="lounge">別のゲームを選ぶ</button>':''}<button data-race-action="back">ホームへ戻る</button></div>${modal(c,g)}</section>`}
function rules(){return`<div class="sg-rules"><h2>手札を残して、得点を競う。</h2><p>手札の点数＋特殊カードの点数＋到着ボーナスが最終得点。3人目がゴールした時点で終了し、残る1人を4着として精算します。</p><div class="sg-bonus-row"><b>1着 ＋40</b><b>2着 ＋20</b><b>3着 ＋10</b><b>4着 ＋5</b></div><h3>自分の手番</h3><ol><li>カードを1枚引く。速攻はすぐに発動。</li><li>移動前のカードを好きなだけ使う。</li><li>サイコロを振り、進んだマスのイベントを処理。</li><li>移動後のカードや特殊能力を使って、手番を終える。</li></ol><p>自分のサイコロは画面のサイコロをタップして振ります。移動後にできることがなければ、自動で次の手番へ進みます。防御・対象・分岐の選択は自分で行います。</p><p>「合計出目＋2」は2マス分加算。「サイコロ＋2個」は通常の1個と合わせて3個を振ります（最大5個）。</p><h3>カードと属性</h3><p>最初の手札は速攻以外の3枚。枚数制限なし。手札は自分だけが見られます。青＝より、緑＝りおん、橙＝えなみ、桃＝ひで。複数属性はそれぞれに該当し、全属性は4属性、無属性はそのどれにも該当しません。</p><p>カードを使うと捨て札へ。捨て札を回収したカードは同じ手番では再使用できません。絵柄4種は隠して温存し、自分の移動前に任意発動。各セットにつき1人1回です。</p><h3>妨害と防御</h3><p>「自分のターン」は相手の手番に使えません。ただし攻撃や悪いマスへの防御は割り込めます。防御はそのカード1枚・マス1つによる自分への残りの効果を無効化。反射は1回だけで連鎖しません。</p><p>呪いは持っている間ずっと影響します。相手に手札を引かせると、呪いも渡せます。ハッカーは速攻を手札に隠せるので、さらに危険なババ抜きに！</p><h3>移動とゴール</h3><p>追加移動した先のマスは原則発動しません。「マス効果も発動」と書いたカードだけは例外です。「必ず止まる」門は前進中に必ず止まり、イベントを行います。</p><p>ゴールは出目が超えてもOK。到着した人の手番と得点は確定し、以後は攻撃・交換の対象外になります。特殊カードは公開で1枚だけ。新たに得たら残す1枚を選べます。</p><h3>待ち時間と長期戦</h3><p>選択に75秒かかるとAIが一時代行。切断中は30秒後から代行し、接続が戻れば操作できます。85手番を超える長期戦では少しずつ移動を加速します。追加ターンは連続2手番までです。</p><p>このゲームのカード・点数は対戦専用です。育成や所持GOLDを使わずに遊べます。</p></div>`}
function modal(c,g){const u=ui(c);if(u.choiceId465!==g.pending?.id){u.choiceId465=g.pending?.id;u.choicePick465=null;u.discardPicks467=[]}const q=g.pending?.playerId===c.transport.selfId?g.pending:null,m=u.modal??(q&&u.dismissChoice!==q.id&&!presentationBusy464(c,g)?{kind:'choice'}:null);if(!m)return'';let body='',title='',close=true;
 if(m.kind==='gameMenu465'){const solo=g.players.filter(p=>!p.ai).length===1&&g.players.find(p=>!p.ai)?.playerId===c.transport.selfId&&c.state.party?.members.length===1;title='ゲームメニュー';body=`<div class="sg-game-menu465">${button('rules','遊び方を見る')}${solo?`<p>自分＋AIの対戦です。育成データやGOLDに影響せず、やり直せます。</p>${button('restartConfirm465','最初からやり直す',false,'sg-primary')}${button('exitConfirm465','ゲームを終了してパーティーへ')}`:'<p>他のプレイヤーが参加しているため、この対戦は中断できません。</p>'}</div>`}
 if(m.kind==='restartConfirm465'||m.kind==='exitConfirm465'){const restart=m.kind==='restartConfirm465';title=restart?'最初からやり直す？':'このゲームを終了する？';body=`<div class="sg-game-menu465"><p>${restart?'現在の対戦を終了し、同じ魔物で最初から始めます。手札・マップ位置はリセットされます。':'現在の対戦を終了して、同じパーティーのゲーム一覧に戻ります。'}</p><p>メインゲームの育成・GOLDはそのままです。</p>${button(restart?'restartSolo465':'exitSolo465',restart?'やり直す':'終了して戻る',!c.connected()||!!u.inFlight,'sg-primary')}${button('gameMenu465','戻る')}</div>`}
 if(m.kind==='rules'){title='遊び方';body=rules()}
 if(m.kind==='tile'){const n=NODES463[m.id];title=n.name;body=`<div class="sg-tile-detail sg-tone-${n.tone}"><b>${n.icon}</b><p>${esc(n.text)}</p>${n.fork?'<p>ここから分岐。近道と、カードを集める寄り道を選べます。</p>':''}</div>`}
 if(m.kind==='card'){const card=CARD_BY_ID463[m.id],owned=g.hand?.find(h=>h.uid===m.uid),isSet=!!card.set,parts=isSet?new Set(g.hand.map(h=>CARD_BY_ID463[h.cardId]).filter(x=>x.set===card.set).map(x=>x.part)).size:0;title=card.name;body=`<div class="sg-inspect" style="${rankStyle466(card)}"><small class="sg-rank466">${esc(card.rank466)} ランク</small>${cardArt(card)}<div class="sg-inspect-meta"><b>${card.points>0?'+':''}${card.points}pt</b><span>${esc(attr(card))} · ${TIMING463[card.timing]}</span></div><p>${esc(card.text)}</p>${isSet?`<p>そろった絵柄：${parts}/4種類。発動すると4枚を消費。各セットにつき1人1回。</p>`:''}${owned?.playable?`<button class="sg-primary" data-sg-action="play" data-uid="${esc(m.uid)}" ${!c.connected()||u.inFlight?'disabled':''}>${isSet?'4枚を使って切り札を発動':'このカードを使う'}</button>`:`<div class="sg-muted">${owned?.ward?'自分への攻撃時に防御として使えます。':card.timing==='reaction'?'攻撃を受けた時に、防御として選べます。':!owned?'カードの効果を確認中':card.timing==='passive'?'持っている間、効果が適用されます。':'今は使えるタイミングではありません。'}</div>`}</div>`}
 if(m.kind==='special'){title='公開の特殊カード';body=specialFace(m.id)}
 if(m.kind==='player'){const p=g.players.find(x=>x.playerId===m.id);title=p.name;body=`${specialFace(p.special)}<p>手札 ${p.handCount}枚 / ${p.finished?p.finished.place+'着・'+p.finished.total+'点確定':'ゴールまで残り'+distance463(p.pos)+'マス'}</p>${p.finished?`<div class="sg-card-grid">${p.finished.handCards.map(id=>cardFace(CARD_BY_ID463[id],{small:true})).join('')}</div>`:p.playerId===c.transport.selfId?'<p>自分の手札は画面下にあります。</p>':'<p class="sg-muted">相手の手札の中身は秘密です。</p>'}`}
 if(m.kind==='log'){title='冒険の記録';body=`<div class="sg-log">${[...g.log].reverse().map(e=>`<p><small>${e.turn}手番</small>${esc(e.text)}${e.cardId?`<button data-sg-action="card" data-card="${e.cardId}">カードを見る</button>`:''}</p>`).join('')}</div><p class="sg-muted">山札 ${g.deckCount}枚 / 捨て札 ${g.discardCount}枚</p>${button('discard','捨て札を見る')}`}
 if(m.kind==='discard'){title=`捨て札 ${g.discardCount}枚`;body=`<div class="sg-card-grid">${[...(g.discardCards??[])].reverse().map(id=>cardFace(CARD_BY_ID463[id],{small:true})).join('')}</div>`}
 if(m.kind==='choice'&&q){title=q.prompt;const ctx=q.context465??q.context464,source=ctx?.cardId?CARD_BY_ID463[ctx.cardId]:ctx?.tile?NODES463[ctx.tile]:null,owner=g.players.find(p=>p.playerId===q.playerId),actor=g.players.find(p=>p.playerId===ctx?.actorId);const disabled=!c.connected()||u.inFlight;
 body=`${source?`<div class="sg-incoming465"><div class="sg-choice-pawn465">${token(c,owner)}<small>${esc(owner?.name)}</small></div><div><small>${ctx?.tile?'マスの効果':esc(actor?.name??'相手')+'のカード'}</small><b>${esc(source.name)}</b><p>${esc(source.text)}</p></div></div>`:''}`;
 if(q.kind==='fork'){const branch=NODES463[owner.pos];body=`<div class="sg-crossroads465"><div class="sg-crossroads-pawn465">${token(c,owner)}<b>${esc(owner.name)}、どちらへ進む？</b></div><div class="sg-route-choices465">${q.options.map((o,i)=>`<button data-sg-action="choice" data-value="${esc(o.value)}" ${disabled?'disabled':''} class="sg-route465 ${i?'is-treasure':'is-short'}"><span class="sg-route-scenery465"></span><span class="sg-route-caption465"><small>${i?'宝庫を巡る道':'最短ルート'}</small><b>${esc(o.label)}</b><em>${i?'4マス長い':'ゴールを目指す'}</em><span>${i?'安全に2枚 → 手札交換ではなく補充 → 特殊獲得 → 浄化':'次のマス：'+esc(tileLabel464(NODES463[o.value]))}</span></span></button>`).join('')}</div></div>`;body=body.replace('安全に2枚 → 手札交換ではなく補充 → 特殊獲得 → 浄化','安全に2枚 → 1枚捨て3枚 → 特殊獲得 → 浄化');}
 else if(q.kind==='discard'){const selected=u.discardPicks467??=[],required=q.required467??1;body+=`<p class="sg-choice-hint465">捨てるカードを ${required} 枚選ぼう。まとめて確定できます。</p><div class="sg-discard-count467">${selected.length} / ${required} 枚選択</div><div class="sg-choices sg-card-choices465" data-sg-scroll="choices">${q.options.map(o=>`<div class="sg-choice-card465 ${selected.includes(o.value)?'is-picked':''}">${cardFace(CARD_BY_ID463[o.cardId],{small:true,action:'discardPick467',value:o.value})}<button class="sg-choice-inspect" data-sg-action="card" data-card="${esc(o.cardId)}">詳しく見る</button></div>`).join('')}</div><div class="sg-choice-confirm465"><small>${selected.length===required?'このカードをまとめて捨てる':`あと ${required-selected.length} 枚選んでね`}</small><button class="sg-primary" data-sg-action="discardBatch467" ${disabled||selected.length!==required?'disabled':''}>${selected.length}枚を捨てる</button></div>`;}
 else if(q.kind==='steal'){const target=g.players.find(p=>p.playerId===q.targetId466);body=`<div class="sg-steal-owner466">${token(c,target??owner)}<b>${esc(target?.name??'相手')}の手札</b><span>あと ${q.remaining466??1} 枚選ぼう</span></div><div class="sg-steal-fan466" data-sg-scroll="choices">${q.options.map((o,i)=>`<button class="sg-steal-back466" data-sg-action="choice" data-value="${esc(o.value)}" aria-label="裏向きのカード ${i+1}を選ぶ" style="--fan:${Math.max(-12,Math.min(12,(i-(q.options.length-1)/2)*6))}deg" ${disabled?'disabled':''}><span>ABYSS</span><b>✦</b><span>DOMINION</span></button>`).join('')}</div><p class="sg-choice-hint465">${esc(source?.name??'カードを奪う')} · 中身は引いてからのお楽しみ</p>`;}
 else{body+=`<p class="sg-choice-hint465">${q.kind==='defense'?'防御札を選ぶか、そのまま受けるかを選ぼう。':q.kind==='steal'?'裏向きのカードを1枚選ぼう。':q.kind==='discard'?'捨てるカードを選んで確定。効果もこの場で読めます。':q.kind==='target'?'効果をかける相手を選ぼう。':'カードを選んで確定しよう。'}</p><div class="sg-choices ${q.kind==='steal'?'sg-concealed':''} ${q.options.some(o=>o.cardId)?'sg-card-choices465':''}" data-sg-scroll="choices">${q.options.map(o=>{const p=g.players.find(p=>p.playerId===o.value);if(o.cardId){const selected=u.choicePick465===o.value;return`<div class="sg-choice-card465 ${selected?'is-picked':''}">${cardFace(CARD_BY_ID463[o.cardId],{small:true,action:'choicePick',value:o.value})}<button class="sg-choice-inspect" data-sg-action="card" data-card="${o.cardId}">詳しく見る</button></div>`}return`<div><button data-sg-action="choice" data-value="${esc(o.value)}" ${disabled?'disabled':''}>${p?`<span class="sg-target-pawn465">${token(c,p)}</span>`:o.special?art463(SPECIAL_BY_ID463[o.special].art):q.kind==='steal'?'<span class="sg-card-back">✦</span>':''}<b>${esc(o.label)}</b>${o.special?`<p>${esc(SPECIAL_BY_ID463[o.special].text)}</p><small>${SPECIAL_BY_ID463[o.special].points}pt</small>`:''}${o.note?`<small>${esc(o.note)}</small>`:''}</button></div>`}).join('')}</div>${q.options.some(o=>o.cardId)?`<div class="sg-choice-confirm465"><small>${q.options.find(o=>o.value===u.choicePick465)?.label??'カードを1枚選んでね'}</small><button class="sg-primary" data-sg-action="choice" data-value="${esc(u.choicePick465??'')}" ${disabled||!q.options.some(o=>o.value===u.choicePick465)?'disabled':''}>${q.kind==='discard'?'このカードを捨てる':q.kind==='defense'?'このカードで防御':'このカードを選ぶ'}</button></div>`:''}`}
 }
 if(!body)return'';return`<div class="sg-modal-backdrop"><section class="sg-modal sg-modal-${m.kind}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><b>${esc(title)}</b>${button('close','閉じる ×')}</header><div class="sg-modal-body" data-sg-scroll="modal">${body}</div></section></div>`}
export function sugorokuView463(c){const raw=c.state.sugoroku;if(!raw)return'';const g=visualGame466(c,raw),u=ui(c);if(u.gameId!==g.id){u.gameId=g.id;u.follow=true;u.zoom=.72;u.cameraKey=null;u.modal=null;u.dismissChoice=null;u.choiceId465=null;u.choicePick465=null;u.previousHand=null;u.animationRevision=null;u.scrolls={};u.inFlight=null}if(g.phase==='lobby')return lobby(c,g);if(g.phase==='result'&&!presentationBusy464(c,raw))return results(c,g);return`<section class="sg-screen sg-game${u.handOpen?' hand-open465':''}${u.mapWide?' map-wide465':''}">${header(c,g)}${seats(c,g)}${board(c,g)}${controls(c,g)}<div class="sg-hand-toggle467">${button('mapWide',u.mapWide?'手札カードを開く ▲':'手札カードを閉じる ▼')}</div>${hand(c,g)}${modal(c,g)}</section>`}
export function sugorokuBefore463(c){const u=ui(c);for(const el of c.root?.querySelectorAll('[data-sg-scroll]')??[])u.scrolls[el.dataset.sgScroll]={x:el.scrollLeft,y:el.scrollTop};u.positions={};for(const el of c.root?.querySelectorAll('[data-sg-token]')??[])u.positions[el.dataset.sgToken]={left:el.style.left,top:el.style.top};u.cleanup?.();u.cleanup=null;u.dragging=false}
function send(c,payload){const g=c.state.sugoroku,u=ui(c);if(!c.connected()||u.inFlight&&Date.now()-u.inFlight<4000||!['restartSolo465','exitSolo465'].includes(payload.kind)&&g.phase==='playing'&&(presentationBusy464(c,g)||Date.now()+c.offset<(g.presentationUntil465??0)))return;u.inFlight=Date.now();c.error='';u.modal=null;const requestId=(globalThis.crypto?.randomUUID?.()??`${Date.now()}_${Math.random().toString(36).slice(2)}`).replace(/[^a-zA-Z0-9_-]/g,'');c.raw('sg463',{rulesVersion:9,gameId:g.id,revision:g.revision,choiceId:g.pending?.id,requestId,...payload});c.render()}
export function sugorokuClick463(c,b){if(!b.dataset.sgAction)return false;const a=b.dataset.sgAction,u=ui(c),g=c.state?.sugoroku;if(!g)return true;
 if(a==='browse'){c.partyBrowse462=true;c.render();return true}if(a==='refresh'){c.refresh();return true}
 if(a==='zoomIn'||a==='zoomOut'||a==='overview'||a==='follow'){cameraButton(c,a);return true}
 if(a==='select'){send(c,{kind:'select',monsterId:b.dataset.monster,roster:c.roster()});return true}
 if(['start','draw','roll','end','special','restartSolo465','exitSolo465'].includes(a)){send(c,{kind:a});return true}
 if(a==='play'){send(c,{kind:'play',uid:b.dataset.uid});return true}
 if(a==='discardPick467'){const q=g.pending,required=q?.required467??1;u.discardPicks467??=[];const at=u.discardPicks467.indexOf(b.dataset.value);if(at>=0)u.discardPicks467.splice(at,1);else if(u.discardPicks467.length<required)u.discardPicks467.push(b.dataset.value);c.render();return true}
 if(a==='discardBatch467'){send(c,{kind:'choice',values:[...(u.discardPicks467??[])]});return true}
 if(a==='choicePick'){u.choicePick465=b.dataset.value;c.render();return true}
 if(a==='handSize'||a==='handTools'||a==='mapWide'){const key=a==='handSize'?'handOpen':a==='handTools'?'handTools':'mapWide';if(a==='mapWide'){const v=c.root.querySelector('.sg-viewport');if(v)u.resizeCenter467={x:(v.clientWidth/2-u.x)/u.zoom,y:(v.clientHeight/2-u.y)/u.zoom}}u[key]=!u[key];c.render();return true}
 if(a==='choice'){send(c,{kind:'choice',value:b.dataset.value});return true}
 if(a==='again'){c.raw('partyGame462',{game:'sugoroku'});return true}
 if(a==='filter')u.filter=b.dataset.filter;else if(a==='more')u.rosterLimit=(u.rosterLimit??24)+24;
 else if(a==='card'){u.modal={kind:'card',id:b.dataset.card,uid:b.dataset.uid};u.scrolls.modal={x:0,y:0}}
 else if(a==='mine')u.modal={kind:'special',id:g.players.find(p=>p.playerId===c.transport.selfId)?.special};else if(a==='player')u.modal={kind:'player',id:b.dataset.player};
 else if(a==='close'){if(u.modal?.kind==='card'&&g.pending?.playerId===c.transport.selfId){u.modal={kind:'choice'};u.dismissChoice=null}else{u.modal=null;u.dismissChoice=g.pending?.id}}
 else if(a==='choiceOpen'){u.dismissChoice=null;u.modal={kind:'choice'}}else if(['rules','log','discard','gameMenu465','restartConfirm465','exitConfirm465'].includes(a))u.modal={kind:a};c.render();return true;
}
export function sugorokuInput463(c,e){if(e.name==='sgSort463'){ui(c).sort=e.value;c.render();return true}if(e.name==='sgSearch463'){ui(c).search=e.value;ui(c).rosterLimit=24;c.render();return true}return false}
function applyCamera(c){const u=ui(c),el=c.root?.querySelector('.sg-world'),v=el?.parentElement;if(v){const w=BOARD_SIZE463.width*u.zoom,h=BOARD_SIZE463.height*u.zoom;u.x=w<v.clientWidth?(v.clientWidth-w)/2:Math.min(0,Math.max(v.clientWidth-w,u.x));u.y=h<v.clientHeight?(v.clientHeight-h)/2:Math.min(0,Math.max(v.clientHeight-h,u.y))}if(el)el.style.transform=`translate(${u.x}px,${u.y}px) scale(${u.zoom})`}
function follow(c){const u=ui(c),g=visualGame466(c,c.state.sugoroku),p=g.players.find(p=>p.playerId===g.turnPlayerId),n=NODES463[p?.pos],v=c.root.querySelector('.sg-viewport');if(!n||!v)return;u.x=v.clientWidth/2-n.x*u.zoom;u.y=v.clientHeight*.5-n.y*u.zoom;applyCamera(c)}
function zoom(c,z,cx,cy){const u=ui(c),v=c.root.querySelector('.sg-viewport');if(!v)return;cx??=v.clientWidth/2;cy??=v.clientHeight/2;z=Math.max(.16,Math.min(1.6,z));u.x=cx-(cx-u.x)*z/u.zoom;u.y=cy-(cy-u.y)*z/u.zoom;u.zoom=z;applyCamera(c)}
function cameraButton(c,a){const u=ui(c),v=c.root.querySelector('.sg-viewport');if(!v)return;if(a==='follow'){u.follow=true;u.zoom=.72;follow(c)}else if(a==='overview'){u.follow=false;u.zoom=Math.min(v.clientWidth/BOARD_SIZE463.width,v.clientHeight/BOARD_SIZE463.height)*.96;u.x=(v.clientWidth-BOARD_SIZE463.width*u.zoom)/2;u.y=(v.clientHeight-BOARD_SIZE463.height*u.zoom)/2;applyCamera(c)}else{u.follow=false;zoom(c,u.zoom*(a==='zoomIn'?1.25:.8))}const b=c.root.querySelector('[data-sg-action="follow"]');b?.classList.toggle('is-active',u.follow);if(b)b.textContent=u.follow?'追尾中':'手番へ'}
export function sugorokuAfter463(c){const g=c.state?.sugoroku,u=ui(c);if(!g||c.partyBrowse462)return;for(const el of c.root.querySelectorAll('[data-sg-scroll]')){const s=u.scrolls[el.dataset.sgScroll];if(s){el.scrollLeft=s.x;el.scrollTop=s.y}}
 if(u.lastRevision!==g.revision){u.inFlight=null;u.lastRevision=g.revision}const v=c.root.querySelector('.sg-viewport');if(v){const view=visualGame466(c,g),p=view.players.find(p=>p.playerId===view.turnPlayerId),key=`${view.turnPlayerId}:${p?.pos}:${v.clientWidth}:${v.clientHeight}`;if(u.resizeCenter467){u.x=v.clientWidth/2-u.resizeCenter467.x*u.zoom;u.y=v.clientHeight/2-u.resizeCenter467.y*u.zoom;u.resizeCenter467=null;u.cameraKey=key;applyCamera(c)}else if(u.follow&&key!==u.cameraKey){follow(c);u.cameraKey=key}else applyCamera(c);
 const points=new Map();let last=null,moved=false,start=null;
 const down=e=>{if(e.button>0||e.target.closest('button,.sg-turn-prompt466,.sg-phase466'))return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});v.setPointerCapture?.(e.pointerId);last=measure(points);start={x:e.clientX,y:e.clientY};moved=false;u.dragging=true};
 const motion=e=>{if(!points.has(e.pointerId))return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});const next=measure(points);if(last){if(Math.hypot(e.clientX-(start?.x??0),e.clientY-(start?.y??0))>5)moved=true;u.x+=next.x-last.x;u.y+=next.y-last.y;if(next.d&&last.d){const r=v.getBoundingClientRect();zoom(c,u.zoom*next.d/last.d,next.x-r.left,next.y-r.top)}if(moved)u.follow=false;applyCamera(c)}last=next};
 const up=e=>{if(!points.has(e.pointerId))return;points.delete(e.pointerId);last=measure(points);if(!points.size){u.dragging=false;if(!moved){const tile=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-sg-tile]');if(tile){u.modal={kind:'tile',id:tile.dataset.sgTile};u.scrolls.modal={x:0,y:0}}}c.render()}};
 const wheel=e=>{e.preventDefault();u.follow=false;const r=v.getBoundingClientRect();zoom(c,u.zoom*Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)};
 v.addEventListener('pointerdown',down);v.addEventListener('pointermove',motion);v.addEventListener('pointerup',up);v.addEventListener('pointercancel',up);v.addEventListener('wheel',wheel,{passive:false});let size466=`${v.clientWidth}:${v.clientHeight}`;const resizeWatcher=new ResizeObserver(()=>{const size=`${v.clientWidth}:${v.clientHeight}`;if(size===size466)return;size466=size;if(u.follow)follow(c);else applyCamera(c)});resizeWatcher.observe(v);u.cleanup=()=>{resizeWatcher.disconnect();v.removeEventListener('pointerdown',down);v.removeEventListener('pointermove',motion);v.removeEventListener('pointerup',up);v.removeEventListener('pointercancel',up);v.removeEventListener('wheel',wheel)};
 }
 if(u.animationRevision!==g.revision){
  if(g.phase==='result'&&u.previousPhase!=='result')c.sound452?.play(g.results?.[0]?.playerId===c.transport.selfId?'win':'finish');
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&u.previousHand)for(const b of c.root.querySelectorAll('.sg-hand [data-uid]'))if(!u.previousHand.has(b.dataset.uid))b.animate([{transform:'translateY(55px) rotateY(70deg)',opacity:.2},{transform:'translateY(0) rotateY(0)',opacity:1}],{duration:450,easing:'ease-out'});
  u.previousHand=new Set((g.hand??[]).map(h=>h.uid));u.previousPhase=g.phase;u.animationRevision=g.revision;
 }
 presentationAfter464(c,art463,p=>token(c,p),pos=>{if(!u.follow)return;const n=NODES463[pos],v=c.root.querySelector('.sg-viewport');if(n&&v){u.x=v.clientWidth/2-n.x*u.zoom;u.y=v.clientHeight*.5-n.y*u.zoom;applyCamera(c)}});

 const cleanupMap=u.cleanup,cleanupHand=bindHand466(c,u);u.cleanup=()=>{cleanupMap?.();cleanupHand()};const world=c.root.querySelector('.sg-world');requestAnimationFrame(()=>requestAnimationFrame(()=>world?.classList.remove('is-restoring466')));
 const dialog=c.root.querySelector('.sg-modal');if(dialog&&!dialog.contains(document.activeElement))dialog.querySelector('button')?.focus({preventScroll:true});
}
function measure(points){const a=[...points.values()];if(!a.length)return null;return{x:a.reduce((n,p)=>n+p.x,0)/a.length,y:a.reduce((n,p)=>n+p.y,0)/a.length,d:a.length>1?Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y):0}}
export function sugorokuTick463(c){const el=c.root?.querySelector('[data-sg-timer]'),g=c.state?.sugoroku;if(el&&g){const s=Math.max(0,Math.ceil((g.deadline-Date.now()-c.offset)/1000));el.textContent=s?`${s}秒`:'処理中'}const waiting465=Date.now()+c.offset<(g?.presentationUntil465??0);if(ui(c).waiting465!==waiting465){ui(c).waiting465=waiting465;if(g&&c.root&&!ui(c).dragging&&!ui(c).handDragging466)c.render()}if(ui(c).inFlight&&Date.now()-ui(c).inFlight>5000){ui(c).inFlight=null;c.refresh();c.render()}}
export function sugorokuKey463(c,e){if(e.key==='Escape'&&c.root.querySelector('.sg-modal')){e.preventDefault();c.root.querySelector('[data-sg-action="close"]')?.click();return true}const tile=e.target.closest('[data-sg-tile]');if(tile&&['Enter',' '].includes(e.key)){e.preventDefault();ui(c).modal={kind:'tile',id:tile.dataset.sgTile};c.render();return true}const dialog=c.root.querySelector('.sg-modal');if(dialog&&e.key==='Tab'){const nodes=[...dialog.querySelectorAll('button,select,input,[tabindex="0"]')].filter(e=>!e.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}return false}
