import{validReceipt480}from'./Economy480.js';
import{validFee474,checkpointAmount474,prizeSlots474}from'./Rewards474.js';
export function crystalBank474(state,key){if(!key)throw Error('接続先とプレイヤーを確認しています');state.sugoroku474??={accounts:{}};return state.sugoroku474.accounts[key]??={pending:null,applied:{}}}
function commit(save,fn){const before=structuredClone(save.state);try{const value=fn();if(save.save()!==true)throw Error('💎の記録を保存できませんでした。再接続後に再試行します');return value}catch(e){save.state=before;throw e}}
export function reserveEntry474(save,key,packet){const bank=crystalBank474(save.state,key);if(bank.pending)throw Error('前の参加費・報酬の精算を確認しています');if(!validFee474(packet.amount)||!/^sg463-\d+-[a-f0-9]{8}$/.test(packet.gameId)||!/^[\w-]{8,100}$/.test(packet.requestId))throw Error('参加情報が不正です');const balance=save.state.player.crystals;if(!Number.isSafeInteger(balance)||balance<packet.amount)throw Error(`参加には💎${packet.amount.toLocaleString()}必要です。無料練習も選べます`);return commit(save,()=>{save.state.player.crystals-=packet.amount;crystalBank474(save.state,key).pending=structuredClone(packet);return packet})}
export function applyCrystalDelivery474(save,key,e){const b=crystalBank474(save.state,key);if(b.applied[e.id])return{duplicate:true};const p=b.pending;
 if(!p||e.playerId!==key.split('|').at(-1)||p.gameId!==e.gameId||p.requestId!==e.requestId||e.fee!==p.amount||!['refund','result','abandon480'].includes(e.kind)||e.id!==`sg474:${e.requestId}`)throw Error('💎の参加記録と受取が一致しません。参加したセーブで再接続してください');
 if(e.kind==='abandon480'&&e.crystals!==0)throw Error('途中終了の精算額が不正です');
 const cap=e.economy480===1?p.amount*5:e.crystalRules477===1?p.amount*4:checkpointAmount474(p.amount)*3;
 if(!Number.isSafeInteger(e.crystals)||e.crystals<0||e.crystals>p.amount*3+cap)throw Error('💎受取額が不正です');
 if(e.kind==='refund'&&e.crystals!==p.amount)throw Error('参加費の返金額が一致しません');
 if(e.kind==='result'&&e.economy480===1&&!validReceipt480(e))throw Error('対戦の💎精算が一致しません');
 if(e.kind==='result'&&e.economy480!==1&&(!Number.isInteger(e.place)||e.place<1||e.place>4||!Number.isInteger(e.tied)||e.tied<1||e.place+e.tied>5||e.prize!==Math.floor(prizeSlots474(p.amount).slice(e.place-1,e.place-1+e.tied).reduce((a,b)=>a+b,0)/e.tied)||!Number.isInteger(e.journey)||e.journey<0||e.journey>cap||(e.crystalRules477===1?(!Number.isSafeInteger(e.shrines477)||e.shrines477<0||e.shrines477>checkpointAmount474(p.amount)*3||!Number.isSafeInteger(e.events477)||e.journey!==e.shrines477+e.events477):!Array.from({length:4},(_,i)=>i*checkpointAmount474(p.amount)).includes(e.journey))||!Number.isInteger(e.prize)||e.prize<0||e.prize>p.amount*3||e.crystals!==e.prize+e.journey))throw Error('報酬の内訳が一致しません');
 return commit(save,()=>{const bank=crystalBank474(save.state,key),balance=save.state.player.crystals;if(!Number.isSafeInteger(balance)||balance<0||balance>Number.MAX_SAFE_INTEGER-e.crystals)throw Error('所持💎の上限を確認してください');save.state.player.crystals+=e.crystals;bank.pending=null;bank.applied[e.id]={gameId:e.gameId,crystals:e.crystals,kind:e.kind,at:Date.now()};return{duplicate:false,crystals:e.crystals,kind:e.kind}})
}
export function retryEntry474(c){const key=c.key();if(!key||!c.connected()||c.state?.rulesVersion<17)return;const pending=crystalBank474(c.save.state,key).pending;if(pending&&!(c.state.entryDecisions474??[]).some(e=>e.requestId===pending.requestId))c.raw('sgEntry474',{...pending,rulesVersion:17})}
export function prepareEntry474(c){const g=c.state.sugoroku,key=c.key(),b=crystalBank474(c.save.state,key);if(c.state.rulesVersion<17)throw Error('報酬戦には本体とサーバーのBuild482が必要です');if(g.economy474?.entries?.includes(c.transport.selfId)){c.raw('partyReady462',{ready:true,rulesVersion:17});return}if(b.pending){retryEntry474(c);throw Error('参加費の受付・精算を確認しています')}
 const packet={gameId:g.id,requestId:globalThis.crypto.randomUUID(),amount:g.economy474.fee,epoch:g.economy474.epoch??0};reserveEntry474(c.save,key,packet);c.raw('sgEntry474',{...packet,rulesVersion:17});c.render()}

export function availableCrystals474(c){const key=c.key?.(),pending=key?c.save.state.sugoroku474?.accounts?.[key]?.pending:null;return Math.min(Number.MAX_SAFE_INTEGER,Math.max(0,Number(c.save.state.player.crystals)||0)+(pending?.amount??0))}
