import{randomBytes}from"node:crypto";

const ROOM_ALPHABET="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const FACING=new Set(["up","down","left","right"]);
const SOCIAL_IDS=Object.freeze({chat:new Set(["hello","ready","follow","thanks"]),emote:new Set(["wave","cheer","heart","surprise"])});
const MAX_FLOOR=10_000;

function token(bytes=18){return randomBytes(bytes).toString("base64url")}
function roomCode(){const bytes=randomBytes(6);return Array.from(bytes,value=>ROOM_ALPHABET[value%ROOM_ALPHABET.length]).join("")}
function text(value,max=32){return String(value??"").replace(/[\u0000-\u001f\u007f]/g,"").trim().slice(0,max)}
function number(value,min,max,fallback=min){const parsed=Number(value);return Number.isFinite(parsed)?Math.max(min,Math.min(max,parsed)):fallback}
function integer(value,min,max,fallback=min){return Math.round(number(value,min,max,fallback))}
function bool(value){return Boolean(value)}
function pointKey(point){return`${point.x},${point.y}`}
function hashText(value){let hash=2166136261;for(const char of String(value))hash=Math.imul(hash^char.charCodeAt(0),16777619);return hash>>>0}
function seededRandom(seed){let state=seed>>>0;return()=>{state+=0x6D2B79F5;let value=state;value=Math.imul(value^value>>>15,value|1);value^=value+Math.imul(value^value>>>7,value|61);return((value^value>>>14)>>>0)/4294967296}}
function shuffle(list,rng){for(let index=list.length-1;index>0;index--){const swap=Math.floor(rng()*(index+1));[list[index],list[swap]]=[list[swap],list[index]]}return list}

function sanitizeEquipment(items){
 return(Array.isArray(items)?items:[]).slice(0,6).map(item=>({slot:text(item?.slot,24),label:text(item?.label,8),name:text(item?.name,48),rarity:text(item?.rarity,12),level:integer(item?.level,0,99_999_999,0),plus:integer(item?.plus,0,9999,0)}));
}
export function sanitizeProfile(source={}){
 const speciesId=/^[a-zA-Z0-9_-]{1,80}$/.test(String(source.speciesId??""))?String(source.speciesId):"slime",visualSpeciesId=/^[a-zA-Z0-9_-]{1,80}$/.test(String(source.visualSpeciesId??""))?String(source.visualSpeciesId):null,endgameBossId=/^[a-zA-Z0-9_-]{1,80}$/.test(String(source.endgameBossId??""))?String(source.endgameBossId):null;
 return{displayName:text(source.displayName,16)||"冒険者",monsterId:text(source.monsterId,80)||null,speciesId,visualSpeciesId,endgameBossId,monsterName:text(source.monsterName,32)||"魔物",fallbackEmoji:text(source.fallbackEmoji,8)||"魔",level:integer(source.level,1,99_999_999,1),stars:integer(source.stars,1,99,1),plus:integer(source.plus,0,9999,0),power:integer(source.power,0,Number.MAX_SAFE_INTEGER,0),maxFloor:integer(source.maxFloor,1,MAX_FLOOR,1),attribute:text(source.attribute,20)||"neutral",circleId:/^[a-zA-Z0-9_-]{1,80}$/.test(String(source.circleId??""))?String(source.circleId):"none",circleName:text(source.circleName,32)||"魔法陣なし",circleLevel:integer(source.circleLevel,0,99,0),equipment:sanitizeEquipment(source.equipment)};
}
function publicMember(session){return{playerId:session.playerId,leader:bool(session.leader),connected:bool(session.connected),ready:bool(session.ready),autoPilot:!session.connected,joinedAt:session.joinedAt,position:{...session.position},dungeonPosition:session.dungeonPosition?{...session.dungeonPosition}:null,profile:{...session.profile,equipment:session.profile.equipment.map(item=>({...item}))}}}

function carveDungeon(roomId,floor,runId,now){
 const cols=17,rows=17,rng=seededRandom(hashText(`${roomId}:${floor}:${runId}`)),grid=Array.from({length:rows},()=>Array(cols).fill("#")),rooms=[];
 const carve=(x,y)=>{if(x>0&&y>0&&x<cols-1&&y<rows-1)grid[y][x]="."};
 for(let attempt=0;attempt<90&&rooms.length<7;attempt++){
  const width=3+Math.floor(rng()*3),height=3+Math.floor(rng()*3),x=1+Math.floor(rng()*(cols-width-2)),y=1+Math.floor(rng()*(rows-height-2)),candidate={x,y,width,height};
  if(rooms.some(other=>x<=other.x+other.width&&x+width>=other.x-1&&y<=other.y+other.height&&y+height>=other.y-1))continue;
  rooms.push(candidate);for(let row=y;row<y+height;row++)for(let column=x;column<x+width;column++)carve(column,row);
 }
 if(rooms.length<3){rooms.length=0;rooms.push({x:1,y:1,width:4,height:4},{x:11,y:2,width:4,height:4},{x:6,y:11,width:5,height:4});for(const room of rooms)for(let y=room.y;y<room.y+room.height;y++)for(let x=room.x;x<room.x+room.width;x++)carve(x,y)}
 const center=room=>({x:Math.floor(room.x+room.width/2),y:Math.floor(room.y+room.height/2)});
 const connect=(from,to)=>{let x=from.x,y=from.y;const horizontalFirst=rng()<.5;const horizontal=()=>{while(x!==to.x){carve(x,y);x+=Math.sign(to.x-x)}carve(x,y)},vertical=()=>{while(y!==to.y){carve(x,y);y+=Math.sign(to.y-y)}carve(x,y)};if(horizontalFirst){horizontal();vertical()}else{vertical();horizontal()}};
 for(let index=1;index<rooms.length;index++)connect(center(rooms[index-1]),center(rooms[index]));if(rooms.length>3)connect(center(rooms[0]),center(rooms.at(-1)));
 const start=center(rooms[0]),walkable=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)if(grid[y][x]===".")walkable.push({x,y});
 const distances=new Map([[pointKey(start),0]]),queue=[start];for(let cursor=0;cursor<queue.length;cursor++){const current=queue[cursor],distance=distances.get(pointKey(current));for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const next={x:current.x+dx,y:current.y+dy},key=pointKey(next);if(grid[next.y]?.[next.x]!=="."||distances.has(key))continue;distances.set(key,distance+1);queue.push(next)}}
 const exit=[...walkable].sort((a,b)=>(distances.get(pointKey(b))??0)-(distances.get(pointKey(a))??0))[0]??start,candidates=shuffle(walkable.filter(point=>pointKey(point)!==pointKey(start)&&pointKey(point)!==pointKey(exit)&&(distances.get(pointKey(point))??0)>=3),rng),objects=[];
 const addObject=(type,index)=>{const point=candidates.pop();if(point)objects.push({id:`${type}-${index}`,type,...point,resolved:false})};for(let index=1;index<=3;index++)addObject("chest",index);for(let index=1;index<=2;index++)addObject("bone",index);addObject("shrine",1);objects.push({id:"exit",type:"exit",...exit,resolved:false});
 return{id:runId,floor,cols,rows,tiles:grid.map(row=>row.join("")),start,exit,objects,discoveries:0,totalDiscoveries:objects.filter(object=>["chest","bone","shrine"].includes(object.type)).length,exitReached:false,returnVotes:new Set(),startedAt:now,eventCount:0,lastEvent:null};
}

function expeditionSnapshot(expedition){if(!expedition)return null;return{id:expedition.id,floor:expedition.floor,cols:expedition.cols,rows:expedition.rows,tiles:[...expedition.tiles],start:{...expedition.start},exit:{...expedition.exit},objects:expedition.objects.map(object=>({...object})),discoveries:expedition.discoveries,totalDiscoveries:expedition.totalDiscoveries,exitReached:expedition.exitReached,returnVotes:[...expedition.returnVotes],startedAt:expedition.startedAt,lastEvent:expedition.lastEvent?{...expedition.lastEvent}:null}}
export function createSharedDungeon({roomId="ROOM",floor=1,runId="RUN",now=Date.now()}={}){return expeditionSnapshot(carveDungeon(roomId,integer(floor,1,MAX_FLOOR,1),runId,now))}

export class RoomStore{
 constructor({maxMembers=4,reconnectGraceMs=15_000,now=()=>Date.now(),randomRoomCode=roomCode,random=Math.random}={}){this.maxMembers=maxMembers;this.reconnectGraceMs=reconnectGraceMs;this.now=now;this.randomRoomCode=randomRoomCode;this.random=random;this.sessions=new Map();this.rooms=new Map()}

 hello(connection,{friendId,clientKey,resumeToken,profile}={}){
  const playerId=text(friendId,20).toUpperCase(),secret=text(clientKey,128);if(!/^AD-[A-Z2-9]{4}-[A-Z2-9]{4}$/.test(playerId))return{ok:false,code:"BAD_FRIEND_ID",message:"フレンドIDの形式が正しくありません"};if(secret.length<24)return{ok:false,code:"BAD_CLIENT_KEY",message:"端末キーが正しくありません"};
  let session=this.sessions.get(playerId),resumed=false;if(session&&!session.connected&&session.expiresAt&&session.expiresAt<this.now()){this.leaveRoom(session,{notifySelf:false});this.sessions.delete(playerId);session=null}
  if(session){if(session.clientKey!==secret)return{ok:false,code:"ID_IN_USE",message:"同じフレンドIDが別の端末で使用されています"};if(session.connected&&session.connection!==connection)try{session.connection.close?.(4001,"replaced by reconnect")}catch{}resumed=Boolean(session.roomId&&(!session.expiresAt||session.expiresAt>=this.now()));session.connection=connection;session.connected=true;session.expiresAt=0;session.resumeToken=token();session.profile=sanitizeProfile(profile??session.profile);session.lastSeen=this.now();session.pendingRewards??=[]}
  else{session={playerId,clientKey:secret,resumeToken:token(),connection,connected:true,roomId:null,leader:false,ready:false,joinedAt:this.now(),lastSeen:this.now(),expiresAt:0,position:{x:50,y:76,facing:"down"},dungeonPosition:null,pendingRewards:[],profile:sanitizeProfile(profile)};this.sessions.set(playerId,session)}
  connection.session=session;const room=session.roomId?this.rooms.get(session.roomId):null;if(!room&&session.roomId)session.roomId=null;if(room)this._broadcastRoom(room);return{ok:true,playerId,resumeToken:session.resumeToken,resumed:Boolean(resumed&&room),room:room?this.roomSnapshot(room):null};
 }

 createRoom(session){if(!session)return{ok:false,code:"NOT_READY",message:"先に接続してください"};this.leaveRoom(session,{notifySelf:false});let id;do{id=this.randomRoomCode()}while(this.rooms.has(id));const room={roomId:id,createdAt:this.now(),leaderId:session.playerId,members:new Set([session.playerId]),phase:"lobby",selectedFloor:Math.max(1,Math.min(session.profile.maxFloor,session.profile.maxFloor||1)),expedition:null};this.rooms.set(id,room);session.roomId=id;session.leader=true;session.ready=false;session.joinedAt=this.now();session.position={x:50,y:76,facing:"down"};session.dungeonPosition=null;this._broadcastRoom(room);return{ok:true,room:this.roomSnapshot(room)}}

 joinRoom(session,rawRoomId){if(!session)return{ok:false,code:"NOT_READY",message:"先に接続してください"};const roomId=text(rawRoomId,6).toUpperCase(),room=this.rooms.get(roomId);if(!room)return{ok:false,code:"ROOM_NOT_FOUND",message:"そのルームIDは見つかりません"};if(session.roomId===roomId)return{ok:true,room:this.roomSnapshot(room)};if(room.phase==="expedition")return{ok:false,code:"EXPEDITION_ACTIVE",message:"この部屋は共闘探索中です。帰還するまで待ってください"};if(room.members.size>=this.maxMembers)return{ok:false,code:"ROOM_FULL",message:"この部屋は4人で満員です"};this.leaveRoom(session,{notifySelf:false});room.members.add(session.playerId);session.roomId=roomId;session.leader=false;session.ready=false;session.joinedAt=this.now();session.position=this._spawnPosition(room.members.size);session.dungeonPosition=null;this._broadcastRoom(room);return{ok:true,room:this.roomSnapshot(room)}}

 leaveRoom(session,{notifySelf=true}={}){const room=session?.roomId?this.rooms.get(session.roomId):null;if(!session||!room){if(session)session.roomId=null;return{ok:true}};room.members.delete(session.playerId);session.roomId=null;session.leader=false;session.ready=false;session.dungeonPosition=null;if(notifySelf)this._send(session,{type:"leftRoom"});if(!room.members.size){this.rooms.delete(room.roomId);return{ok:true}}if(room.leaderId===session.playerId){const next=[...room.members].map(id=>this.sessions.get(id)).filter(Boolean).sort((a,b)=>a.joinedAt-b.joinedAt)[0];room.leaderId=next?.playerId??[...room.members][0]}for(const id of room.members){const member=this.sessions.get(id);if(member)member.leader=id===room.leaderId}if(room.expedition)room.expedition.returnVotes.delete(session.playerId);this._broadcastRoom(room);return{ok:true}}

 updateProfile(session,profile){if(!session)return{ok:false};session.profile=sanitizeProfile(profile);const room=session.roomId?this.rooms.get(session.roomId):null;if(room?.phase==="lobby")session.ready=false;if(room)this._broadcastRoom(room);return{ok:true}}
 move(session,position){if(!session?.roomId)return{ok:false,code:"NOT_IN_ROOM",message:"部屋に参加していません"};const room=this.rooms.get(session.roomId);if(room?.phase==="expedition")return{ok:false,code:"EXPEDITION_MOVE_ONLY",message:"共闘探索用の移動を使用してください"};const next={x:number(position?.x,5,95,session.position.x),y:number(position?.y,15,96,session.position.y),facing:FACING.has(position?.facing)?position.facing:session.position.facing},distance=Math.hypot(next.x-session.position.x,next.y-session.position.y);if(distance>8){const scale=8/distance;next.x=session.position.x+(next.x-session.position.x)*scale;next.y=session.position.y+(next.y-session.position.y)*scale}session.position=next;session.lastSeen=this.now();if(room)this._broadcast(room,{type:"memberMoved",playerId:session.playerId,position:{...next}},{except:session.playerId});return{ok:true,position:next}}
 social(session,{kind,id}={}){if(!session?.roomId)return{ok:false,code:"NOT_IN_ROOM",message:"部屋に参加していません"};if(!SOCIAL_IDS[kind]?.has(id))return{ok:false,code:"BAD_SOCIAL",message:"そのリアクションは使用できません"};const room=this.rooms.get(session.roomId);if(room)this._broadcast(room,{type:"social",playerId:session.playerId,kind,id,duration:3600});return{ok:true}}

 setReady(session,ready){const room=session?.roomId?this.rooms.get(session.roomId):null;if(!room)return{ok:false,code:"NOT_IN_ROOM",message:"部屋に参加していません"};if(room.phase!=="lobby")return{ok:false,code:"EXPEDITION_ACTIVE",message:"共闘探索中です"};session.ready=Boolean(ready);this._broadcastRoom(room);return{ok:true,room:this.roomSnapshot(room)}}
 setFloor(session,value){const room=session?.roomId?this.rooms.get(session.roomId):null;if(!room)return{ok:false,code:"NOT_IN_ROOM",message:"部屋に参加していません"};if(room.leaderId!==session.playerId)return{ok:false,code:"LEADER_ONLY",message:"挑戦階層を変更できるのはリーダーだけです"};if(room.phase!=="lobby")return{ok:false,code:"EXPEDITION_ACTIVE",message:"共闘探索中は階層を変更できません"};room.selectedFloor=integer(value,1,Math.min(MAX_FLOOR,session.profile.maxFloor),room.selectedFloor);for(const id of room.members){const member=this.sessions.get(id);if(member)member.ready=false}this._broadcastRoom(room);return{ok:true,room:this.roomSnapshot(room)}}

 startExpedition(session){const room=session?.roomId?this.rooms.get(session.roomId):null;if(!room)return{ok:false,code:"NOT_IN_ROOM",message:"部屋に参加していません"};if(room.leaderId!==session.playerId)return{ok:false,code:"LEADER_ONLY",message:"出発できるのはリーダーだけです"};if(room.phase!=="lobby")return{ok:false,code:"EXPEDITION_ACTIVE",message:"すでに共闘探索中です"};const members=[...room.members].map(id=>this.sessions.get(id)).filter(Boolean);if(members.some(member=>!member.connected))return{ok:false,code:"MEMBER_OFFLINE",message:"再接続待ちの仲間がいます"};if(members.some(member=>!member.ready))return{ok:false,code:"NOT_ALL_READY",message:"全員の準備完了を待っています"};room.phase="expedition";room.expedition=carveDungeon(room.roomId,room.selectedFloor,token(7),this.now());const spawns=this._dungeonSpawnCells(room.expedition,members.length);members.forEach((member,index)=>{member.ready=false;member.dungeonPosition={...spawns[index],facing:index%2?"right":"down"}});this._broadcast(room,{type:"expeditionStarted",room:this.roomSnapshot(room)});this._broadcastRoom(room);return{ok:true,room:this.roomSnapshot(room)}}

 moveExpedition(session,position){const room=session?.roomId?this.rooms.get(session.roomId):null,expedition=room?.expedition;if(!room||room.phase!=="expedition"||!expedition)return{ok:false,code:"NO_EXPEDITION",message:"共闘探索は開始されていません"};const current=session.dungeonPosition??expedition.start,next={x:integer(position?.x,0,expedition.cols-1,current.x),y:integer(position?.y,0,expedition.rows-1,current.y),facing:FACING.has(position?.facing)?position.facing:current.facing};if(Math.abs(next.x-current.x)+Math.abs(next.y-current.y)>1)return{ok:false,code:"MOVE_TOO_FAR",message:"一度に移動できるのは1マスです"};if(expedition.tiles[next.y]?.[next.x]!==".")return{ok:false,code:"BLOCKED",message:"そこは通れません"};session.dungeonPosition=next;session.lastSeen=this.now();this._broadcast(room,{type:"expeditionMoved",playerId:session.playerId,position:{...next}});this._resolveLanding(room,session);this._moveDisconnectedFollowers(room);return{ok:true,position:next}}

 requestReturn(session){const room=session?.roomId?this.rooms.get(session.roomId):null,expedition=room?.expedition;if(!room||room.phase!=="expedition"||!expedition)return{ok:false,code:"NO_EXPEDITION",message:"共闘探索は開始されていません"};if(expedition.returnVotes.has(session.playerId))expedition.returnVotes.delete(session.playerId);else expedition.returnVotes.add(session.playerId);const connected=[...room.members].map(id=>this.sessions.get(id)).filter(member=>member?.connected),connectedIds=new Set(connected.map(member=>member.playerId));for(const id of expedition.returnVotes)if(!connectedIds.has(id))expedition.returnVotes.delete(id);const needed=Math.max(1,Math.ceil(connected.length/2)),voteCount=expedition.returnVotes.size;if(room.leaderId===session.playerId||voteCount>=needed){const completed=Boolean(expedition.exitReached);this._finishExpedition(room,{completed,reason:room.leaderId===session.playerId?"leader":"vote"});return{ok:true,ended:true,completed}}this._broadcast(room,{type:"expeditionEvent",event:{id:`vote-${this.now()}`,kind:"vote",title:"帰還投票",message:`${session.profile.displayName}が帰還を提案（${voteCount}/${needed}）`,actorId:session.playerId}});this._broadcastRoom(room);return{ok:true,ended:false}}
 completeExpedition(session){const room=session?.roomId?this.rooms.get(session.roomId):null,expedition=room?.expedition;if(!room||room.phase!=="expedition"||!expedition)return{ok:false,code:"NO_EXPEDITION",message:"共闘探索は開始されていません"};if(room.leaderId!==session.playerId)return{ok:false,code:"LEADER_ONLY",message:"踏破を確定できるのはリーダーだけです"};if(!expedition.exitReached)return{ok:false,code:"EXIT_NOT_FOUND",message:"先に出口を発見してください"};this._finishExpedition(room,{completed:true,reason:"cleared"});return{ok:true,ended:true,completed:true}}

 ackReward(session,rewardId){if(!session)return{ok:false};const id=text(rewardId,160);session.pendingRewards=(session.pendingRewards??[]).filter(entry=>entry.rewardId!==id);return{ok:true}}
 deliverPendingRewards(session){for(const entry of session?.pendingRewards??[])this._send(session,{type:"onlineReward",...entry})}
 disconnect(session){if(!session)return;session.connected=false;session.connection=null;session.expiresAt=this.now()+this.reconnectGraceMs;const room=session.roomId?this.rooms.get(session.roomId):null;if(room)this._broadcastRoom(room)}
 pruneExpired(){for(const session of this.sessions.values()){if(session.connected||!session.expiresAt||session.expiresAt>this.now())continue;this.leaveRoom(session,{notifySelf:false});this.sessions.delete(session.playerId)}}
 roomSnapshot(room){return{roomId:room.roomId,leaderId:room.leaderId,maxMembers:this.maxMembers,phase:room.phase,selectedFloor:room.selectedFloor,expedition:expeditionSnapshot(room.expedition),members:[...room.members].map(id=>this.sessions.get(id)).filter(Boolean).map(publicMember)}}

 _resolveLanding(room,session){const expedition=room.expedition,object=expedition.objects.find(entry=>entry.x===session.dungeonPosition.x&&entry.y===session.dungeonPosition.y&&!entry.resolved);if(!object)return;if(object.type==="exit"){object.resolved=true;expedition.exitReached=true;const event={id:`${expedition.id}:exit`,kind:"exit",title:"出口発見",message:`${session.profile.displayName}が次元門を発見！`,actorId:session.playerId};expedition.lastEvent=event;this._broadcast(room,{type:"expeditionEvent",event});this._broadcastRoom(room);return}object.resolved=true;expedition.discoveries++;const labels={chest:["共闘宝箱","黒鉄の宝箱を開いた！"],bone:["古い遺骨","仲間と遺骨を調べた。"],shrine:["共鳴祭壇","全員の魔法陣が共鳴した！"]},[title,message]=labels[object.type]??["探索発見","何かを発見した。"],event={id:`${expedition.id}:${object.id}`,kind:object.type,title,message,actorId:session.playerId};expedition.lastEvent=event;if(object.type!=="shrine")for(const id of room.members){const member=this.sessions.get(id);if(!member)continue;const reward=this._rewardFor(expedition.floor,object.type),rewardId=`${event.id}:${id}`;this._queueReward(member,{rewardId,reward,source:{kind:object.type,floor:expedition.floor,title}})}this._broadcast(room,{type:"expeditionEvent",event});this._broadcastRoom(room)}
 _rewardFor(floor,kind){const variance=.85+this.random()*.3;if(kind==="bone")return{gold:Math.max(20,Math.round((40+floor*5)*variance)),captureCrystals:this.random()<.22?1:0};if(kind==="completion")return{gold:Math.max(300,Math.round((300+floor*35)*variance)),captureCrystals:floor>=100?1:0};return{gold:Math.max(100,Math.round((120+floor*14)*variance)),captureCrystals:floor>=50&&this.random()<.12?1:0}}
 _queueReward(session,entry){if((session.pendingRewards??=[]).some(item=>item.rewardId===entry.rewardId))return;session.pendingRewards.push(entry);this._send(session,{type:"onlineReward",...entry})}
 _finishExpedition(room,{completed=false,reason="return"}={}){const expedition=room.expedition;if(!expedition)return;if(completed)for(const id of room.members){const member=this.sessions.get(id);if(!member)continue;this._queueReward(member,{rewardId:`${expedition.id}:completion:${id}`,reward:this._rewardFor(expedition.floor,"completion"),source:{kind:"completion",floor:expedition.floor,title:"共闘踏破報酬"}})}const summary={id:expedition.id,floor:expedition.floor,completed,reason,discoveries:expedition.discoveries,totalDiscoveries:expedition.totalDiscoveries};this._broadcast(room,{type:"expeditionEnded",summary});room.phase="lobby";room.expedition=null;for(const id of room.members){const member=this.sessions.get(id);if(!member)continue;member.ready=false;member.dungeonPosition=null}this._broadcastRoom(room)}

 _dungeonSpawnCells(expedition,count){const result=[{...expedition.start}],seen=new Set([pointKey(expedition.start)]),queue=[expedition.start];for(let cursor=0;cursor<queue.length&&result.length<count;cursor++){const current=queue[cursor];for(const [dx,dy]of[[1,0],[0,1],[-1,0],[0,-1]]){const next={x:current.x+dx,y:current.y+dy},key=pointKey(next);if(seen.has(key)||expedition.tiles[next.y]?.[next.x]!==".")continue;seen.add(key);queue.push(next);result.push(next);if(result.length>=count)break}}while(result.length<count)result.push({...expedition.start});return result}
 _moveDisconnectedFollowers(room){const expedition=room.expedition,leader=this.sessions.get(room.leaderId);if(!expedition||!leader?.dungeonPosition)return;for(const id of room.members){const member=this.sessions.get(id);if(!member||member.connected||!member.dungeonPosition||this.now()-(member.lastAiMove??0)<300)continue;const current=member.dungeonPosition,target=leader.dungeonPosition;if(Math.abs(target.x-current.x)+Math.abs(target.y-current.y)<=2)continue;const options=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:current.x+dx,y:current.y+dy,facing:dx<0?"left":dx>0?"right":dy<0?"up":"down"})).filter(point=>expedition.tiles[point.y]?.[point.x]===".").sort((a,b)=>(Math.abs(a.x-target.x)+Math.abs(a.y-target.y))-(Math.abs(b.x-target.x)+Math.abs(b.y-target.y)));if(!options.length)continue;member.dungeonPosition=options[0];member.lastAiMove=this.now();this._broadcast(room,{type:"expeditionMoved",playerId:member.playerId,position:{...member.dungeonPosition},autoPilot:true})}}
 _spawnPosition(count){const positions=[{x:50,y:76,facing:"down"},{x:36,y:67,facing:"right"},{x:64,y:67,facing:"left"},{x:50,y:55,facing:"down"}];return{...(positions[Math.max(0,count-1)]??positions[0])}}
 _send(session,message){if(!session?.connected||!session.connection)return;try{session.connection.send(JSON.stringify(message))}catch{}}
 _broadcast(room,message,{except=null}={}){for(const id of room.members){if(id===except)continue;this._send(this.sessions.get(id),message)}}
 _broadcastRoom(room){this._broadcast(room,{type:"roomState",room:this.roomSnapshot(room)})}
}
