// Original generated atlases are sampled intact; no image processing at runtime.
export const asset551=name=>new URL('../../assets/ricochet551/'+name+'.png',import.meta.url).href;
const maps={junkgp:['rocket','spring','armor','turbo','cell','wheels','engine','hook','bank','dice','bumper','coil'],pinball:['spring','echo','cell','crown','link','dice','magnet','chest','comet','bank','mirror','spark']};
export function itemArt551(mode,id){const n=Math.max(0,maps[mode].indexOf(id));return `<span class="rc-art551" aria-hidden="true" style="--item-art:url('${asset551(mode+'-items')}');--item-x:${n%4/3*100}%;--item-y:${Math.floor(n/4)/2*100}%"></span>`}
export const short551={spring:'バネ',echo:'反響の王冠',cell:'仕返し電池',crown:'王冠の勲章',link:'友情コイル',dice:'運命のダイス',magnet:'宝探し磁石',chest:'強欲の宝袋',comet:'三段ロケット',bank:'先行投資',mirror:'反射のよろい',spark:'金粉まみれ',rocket:'後付けロケット',armor:'鉄板よろい',turbo:'追突ターボ',wheels:'つるつる車輪',engine:'増設エンジン',hook:'ちゃっかり牽引',bumper:'特大バンパー',coil:'おかわり噴射'};
export function effect551(mode,id,lv=1){const pin={spring:`発射 +${15*lv}%`,echo:`壁→次の得点 +${25*lv}%`,cell:`衝突で充電 ×${lv}`,crown:`王冠の得点 +${25*lv}%`,link:`衝突後の得点 ×${1+lv}`,dice:`出目で倍率アップ`,magnet:`宝箱へ吸引 Lv.${lv}`,chest:`宝箱 +${80*lv}%`,comet:`３衝突で噴射 +${5*lv}`,bank:`利息 ${15*lv}% ＋ 配当`,mirror:`減速 ${Math.round((1-.9**lv)*100)}% 軽減`,spark:`ピンの得点 +${25*lv}%`};const gp={rocket:`1.2秒後 噴射 +${5*lv}`,spring:`壁反射で加速 +${8*lv}%`,armor:`重さ +${60*lv}%・発射↓`,turbo:`追突で加速 +${3*lv}`,cell:`衝突で充電 ×${lv}`,wheels:`減速 ${Math.round((1-.8**lv)*100)}% 軽減`,engine:`発射 ×${(1.16**lv).toFixed(2)}`,hook:`前の車に引かれる`,bank:`発射 +回数×${(.7*lv).toFixed(1)}`,dice:`出目で勢いが変化`,bumper:`反発↑・重さ +${15*lv}%`,coil:`３衝突で噴射 +${6*lv}`};return(pin&&mode==='pinball'?pin:gp)[id]??''}
const pictures=new Map();
export function image551(name){let im=pictures.get(name);if(!im){im=new Image();im.src=asset551(name);pictures.set(name,im)}return im}
export function drawArt551(c,name,x,y,w,h){const im=image551(name);if(!im.complete||!im.naturalWidth)return false;c.save();c.translate(x,y);c.scale(1,-1);c.drawImage(im,-w/2,-h/2,w,h);c.restore();return true}
export function prop551(c,index,x,y,w,h=w){const im=image551('track-props');if(!im.complete||!im.naturalWidth)return false;const sw=im.naturalWidth/2,sh=im.naturalHeight/2;c.save();c.translate(x,y);c.scale(1,-1);c.drawImage(im,(index%2)*sw,Math.floor(index/2)*sh,sw,sh,-w/2,-h/2,w,h);c.restore();return true}
export function atlas551(c,mode,id,x,y,w,h=w){const im=image551(mode+'-items'),i=maps[mode].indexOf(id);if(i<0||!im.complete||!im.naturalWidth)return false;const sw=im.naturalWidth/4,sh=im.naturalHeight/3;c.save();c.translate(x,y);c.scale(1,-1);c.drawImage(im,(i%4)*sw,Math.floor(i/4)*sh,sw,sh,-w/2,-h/2,w,h);c.restore();return true}
