import {HOCKEY564 as C, TEAM564} from './Hockey564.js';
import {color563} from '../party/Arcade563.js';
const TAU=Math.PI*2,images=new Map();
function image(path){if(!images.has(path)){const im=new Image();im.src=new URL('../../assets/'+path,import.meta.url).href;images.set(path,im);}return images.get(path);}
export const board564=canvas=>({canvas,c:canvas.getContext('2d'),width:1,height:1,sx:1,sy:1,pad:8,points:[]});
export function resize564(r,w,h,dpr=1){r.width=Math.max(1,w);r.height=Math.max(1,h);r.canvas.width=Math.round(w*Math.min(dpr,2));r.canvas.height=Math.round(h*Math.min(dpr,2));r.dpr=Math.min(dpr,2);r.sx=(w-16)/C.width;r.sy=(h-16)/C.height;}
export const point564=(r,p)=>({x:r.width/2+p.x*r.sx,y:r.height-r.pad-p.y*r.sy});
function circle(c,x,y,r,fill,stroke,width=1){c.beginPath();c.arc(x,y,r,0,TAU);if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
function text(c,s,x,y,size,color='#fff0c4'){c.font=`800 ${size}px "Noto Sans JP",sans-serif`;c.textAlign='center';c.textBaseline='middle';c.lineWidth=3;c.strokeStyle='#071d18';c.strokeText(s,x,y);c.fillStyle=color;c.fillText(s,x,y);}
function jewel(c,x,y,size,at,hot){c.save();c.translate(x,y);if(hot){c.shadowColor='#ffe8a1';c.shadowBlur=18;}const grad=c.createLinearGradient(-size,-size,size,size);grad.addColorStop(0,'#fff7cc');grad.addColorStop(.35,'#77ffea');grad.addColorStop(.6,'#20bdb9');grad.addColorStop(1,'#076467');c.beginPath();c.moveTo(0,-size);c.lineTo(size*.8,-size*.25);c.lineTo(size*.62,size*.65);c.lineTo(0,size);c.lineTo(-size*.75,size*.5);c.lineTo(-size*.8,-size*.25);c.closePath();c.fillStyle=grad;c.fill();c.strokeStyle='#ecffe1';c.lineWidth=1.5;c.stroke();c.shadowBlur=0;c.beginPath();c.moveTo(0,-size);c.lineTo(-size*.22,-size*.1);c.lineTo(size*.62,size*.65);c.moveTo(-size*.8,-size*.25);c.lineTo(-size*.22,-size*.1);c.lineTo(0,size);c.moveTo(-size*.22,-size*.1);c.lineTo(size*.8,-size*.25);c.strokeStyle='#eeffdbb0';c.lineWidth=1;c.stroke();c.restore();}
export function paintBoard564(r,g,self,u,at){const c=r.c,s=Math.min(r.sx,r.sy),w=r.width,h=r.height;c.setTransform(r.dpr,0,0,r.dpr,0,0);c.clearRect(0,0,w,h);const floor=image('ricochet555/arena-floor.png');if(floor.complete&&floor.naturalWidth)c.drawImage(floor,0,0,w,h);else{c.fillStyle='#0b3b32';c.fillRect(0,0,w,h);}c.fillStyle='#03271b3a';c.fillRect(0,0,w,h);const border=c.createLinearGradient(0,0,w,h);border.addColorStop(0,'#f9e7a0');border.addColorStop(.32,'#856137');border.addColorStop(.65,'#eac887');border.addColorStop(1,'#745229');c.strokeStyle=border;c.lineWidth=5;c.strokeRect(4,4,w-8,h-8);c.strokeStyle='#ffe7a066';c.lineWidth=1;c.strokeRect(9,9,w-18,h-18);
 for(let y=21;y<h-15;y+=29)for(const x of [4,w-4])circle(c,x,y,1.5,at%1300<400?'#ffebae':'#a97c36');
 // Goal line and posts use the authoritative solver coordinates.
 const selfPlayer=g.players.find(p=>p.playerId===self);
 for(const goal of g.goals){const t=TEAM564[goal.team],front=point564(r,{x:0,y:goal.y}),back=point564(r,{x:0,y:goal.team===0?0:C.height}),left=point564(r,{x:-goal.halfWidth,y:goal.y}),right=point564(r,{x:goal.halfWidth,y:goal.y}),top=Math.min(front.y,back.y),depth=Math.abs(front.y-back.y),mine=selfPlayer?.team564===goal.team;
  c.fillStyle=t.color+'26';c.fillRect(left.x,top,right.x-left.x,depth);c.save();c.beginPath();c.rect(left.x,top,right.x-left.x,depth);c.clip();c.strokeStyle=t.color+'55';c.lineWidth=.8;for(let x=left.x-depth;x<right.x+depth;x+=9){c.beginPath();c.moveTo(x,top);c.lineTo(x+depth,top+depth);c.stroke();c.beginPath();c.moveTo(x,top+depth);c.lineTo(x+depth,top);c.stroke();}c.restore();
  c.strokeStyle=t.color;c.lineWidth=3;c.shadowColor=t.color;c.shadowBlur=u.reduced?0:8;c.beginPath();c.moveTo(left.x,front.y);c.lineTo(right.x,front.y);c.stroke();c.shadowBlur=0;
  for(const x of [left.x,right.x])circle(c,x,front.y,C.postRadius*s+1,'#fff2c4',t.color,2);
  const labelY=front.y+(goal.team===0?-1:1)*15;text(c,(mine?'守る ':'狙う ')+t.mark+' '+t.name,front.x,labelY,Math.min(11,w/36),t.color);
  if(g.lastGoal?.defendingTeam===goal.team&&at-g.lastGoal.at>=0&&at-g.lastGoal.at<850){c.save();c.globalAlpha=(1-(at-g.lastGoal.at)/850)*.6;c.fillStyle='#fff4bb';c.fillRect(left.x,top,right.x-left.x,depth);c.restore();}
 }
 const mid=point564(r,{x:0,y:C.height/2});c.strokeStyle='#ead39a33';c.setLineDash([6,6]);c.lineWidth=1;c.beginPath();c.moveTo(r.pad,mid.y);c.lineTo(w-r.pad,mid.y);c.stroke();c.setLineDash([]);
 const center=point564(r,{x:0,y:C.height/2}),rotor=image('ricochet555/impact-rotor.png');c.save();c.translate(center.x,center.y);c.scale(r.sx,r.sy);c.rotate(-g.rotor.angle);c.shadowColor='#001b13';c.shadowBlur=6;c.shadowOffsetY=3;if(rotor.complete&&rotor.naturalWidth)c.drawImage(rotor,22,383,1493,256,-2.7,-.46,5.4,.92);else{c.fillStyle=border;c.beginPath();c.roundRect(-2.5,-.2,5,.4,.2);c.fill();}c.restore();
 const dt=Math.max(0,Math.min(.04,(at-g.serverAt)/1000));r.points=[];
 for(const p of g.players){const q=point564(r,{x:p.x+p.vx*dt,y:p.y+p.vy*dt}),radius=p.r*s,mine=p.playerId===self;circle(c,q.x+2,q.y+4,radius+3,'#00161199');circle(c,q.x,q.y,radius+6,null,TEAM564[p.team564].color,2);text(c,TEAM564[p.team564].mark,q.x+radius+5,q.y-radius-1,9,TEAM564[p.team564].color);const metal=c.createRadialGradient(q.x-4,q.y-5,2,q.x,q.y,radius+2);metal.addColorStop(0,'#eecc88');metal.addColorStop(.55,'#916535');metal.addColorStop(.8,'#e5bf70');metal.addColorStop(1,'#573c27');circle(c,q.x,q.y,radius+2,metal,color563(p),2);circle(c,q.x,q.y,radius-3,'#173e33',mine?'#fff5ba':color563(p),mine?2:1);r.points.push({...q,seat:p.seat,size:Math.max(25,radius*2.2)});}
 if(g.gem){const q=point564(r,g.gem);circle(c,q.x,q.y,C.gemRadius*s+5,'#54ecd91f');jewel(c,q.x,q.y,C.gemRadius*s+3,at,true);text(c,g.gem.value===2?'２点パック':'パック',q.x,q.y-23,10,g.gem.value===2?'#ffe3a2':'#c8fff2');}
 for(const e of g.events){const age=at-e.at;if(age<0||age>450||e.x==null||!['gemHit','hit','rotor','wall','goal'].includes(e.type))continue;const q=point564(r,e),t=age/450;c.save();c.globalAlpha=1-t;const rays=u.reduced?0:e.type==='goal'?18:7;for(let i=0;i<rays;i++){const a=i*TAU/rays+e.id,d=8+t*(e.type==='goal'?80:25);c.strokeStyle=i%2?'#fff2bb':'#8af5da';c.lineWidth=2;c.beginPath();c.moveTo(q.x+Math.cos(a)*d,q.y+Math.sin(a)*d);c.lineTo(q.x+Math.cos(a)*(d+5),q.y+Math.sin(a)*(d+5));c.stroke();}c.restore();}
 const p=g.players.find(p=>p.playerId===self),q=r.points.find(p=>p.seat===g.players.find(v=>v.playerId===self)?.seat);if(p&&q&&u.pull){const dx=Math.sin(u.pull.angle),dy=-Math.cos(u.pull.angle),len=20+u.pull.power*55;c.save();c.strokeStyle='#fce3a0';c.lineWidth=5;c.lineCap='round';c.shadowBlur=7;c.shadowColor='#ffd37b';c.beginPath();c.moveTo(q.x-dx*(15+u.pull.power*30),q.y-dy*(15+u.pull.power*30));c.lineTo(q.x,q.y);c.stroke();c.lineWidth=3;c.beginPath();c.moveTo(q.x+dx*20,q.y+dy*20);c.lineTo(q.x+dx*len,q.y+dy*len);c.stroke();c.translate(q.x+dx*len,q.y+dy*len);c.rotate(Math.atan2(dy,dx));c.beginPath();c.moveTo(7,0);c.lineTo(-5,-5);c.lineTo(-5,5);c.closePath();c.fillStyle='#fff1c4';c.fill();c.restore();}
}
