import {assignColors499} from '../party/PartyColors499.js';
export const PINBALL563=Object.freeze({version:7,width:16,height:18.4,step:20,radius:.58,gemRadius:.52,reload:1250,maxSpeed:46,goalRadius:1.18,countdown:2800});
const C=PINBALL563,copy=x=>structuredClone(x),cap=(x,a,b)=>Math.max(a,Math.min(b,x)),TAU=Math.PI*2;
export const goals563=()=>[[-6.05,2.05],[6.05,2.05],[6.05,16.35],[-6.05,16.35]].map(([x,y],seat)=>({seat,x,y,r:C.goalRadius}));
export function random563(g){let n=g.seed|0;n^=n<<13;n^=n>>>17;n^=n<<5;g.seed=n>>>0||563;return g.seed/4294967296;}
export function event563(g,type,data={}){g.events.push({id:++g.eventId,type,at:g.simAt,...data});g.events=g.events.slice(-55);}
export function makeGoal563({id,code,partyId,hostId,now=0,members,mode='pinball'}){if(mode!=='pinball')throw Error('このゲームは終了しました');return{id,code,game:'pinball',rules550:7,partyId462:partyId,hostId,members:copy(members),phase:'lobby',round:1,rounds:1,duration555:90000,revision:0,createdAt:now,updatedAt:now,serverAt:now,simAt:now,players:[],events:[],eventId:0,results:[],history:[],winnerIds:[]};}
function spawnGem(g){const angle=(g.gemSerial%4)*Math.PI/2+Math.PI/4;g.gemSerial++;g.gem={x:Math.cos(angle)*3.0,y:C.height/2+Math.sin(angle)*3.0,vx:-Math.cos(angle)*1.8,vy:-Math.sin(angle)*1.8,r:C.gemRadius,mass:.65,lastTouch:null,serial:g.gemSerial,value:g.deadline-g.simAt<=15000?2:1};g.gemReadyAt=0;event563(g,'gem',{x:g.gem.x,y:g.gem.y,value:g.gem.value});}
export function startGoal563(g,now,seed=563){g.rules550=7;g.seed=seed||563;g.duration555=g.duration555===150000?150000:90000;g.players=g.members.filter(m=>!m.departed).map((m,seat)=>({playerId:m.playerId,seat,name:m.name,speciesId:m.choice?.speciesId??'slime',color499:m.color499,ai:!!m.ai}));
 while(g.players.length<4){const seat=g.players.length;g.players.push({playerId:`AI-${g.id}-${seat}`,seat,name:['カンカン丸','よくばりゴブ','より','ホネスピン'][seat],speciesId:['slime','goblin','wolf','skeleton'][seat],ai:true});}assignColors499(g.players,g.aiColors500??{});
 Object.assign(g,{phase:'countdown',phaseAt:now,startAt:now+C.countdown,deadline:now+C.countdown+g.duration555,roundAt:now+C.countdown,simAt:now,serverAt:now,elapsed:0,events:[],eventId:0,results:[],history:[],winnerIds:[],contacts:{},rotor:{angle:0,omega:0,lastTouch:null},goals:goals563(),gem:null,gemSerial:Math.floor(random563(g)*4),gemReadyAt:now+C.countdown,lastGoal:null,finalCue:false});
 const starts=[[-3.5,5],[3.5,5],[3.5,13.4],[-3.5,13.4]];
 for(const p of g.players)Object.assign(p,{x:starts[p.seat][0],y:starts[p.seat][1],vx:0,vy:0,r:C.radius,mass:1.2,score:0,roundScore:0,hits:0,goals:0,saves:0,shots555:0,lastSeq:0,pulling:false,power:0,angle:0,nextShotAt563:g.startAt,botAt:g.startAt+600+random563(g)*1100});g.updatedAt=now;g.revision++;return g;
}
export const canShoot563=(g,p,at=g.simAt)=>g.phase==='play'&&!!p&&at>=p.nextShotAt563&&at<g.deadline;
export function limit563(p){const v=Math.hypot(p.vx,p.vy);if(v>C.maxSpeed){p.vx*=C.maxSpeed/v;p.vy*=C.maxSpeed/v;}}
export function launch563(g,p,power,angle){if(!canShoot563(g,p)||!Number.isFinite(power)||power<.08||power>1||!Number.isFinite(angle)||Math.abs(angle)>Math.PI)return false;const carryX=p.vx,carryY=p.vy,speed=7+15*power+13*power*power;p.vx+=Math.sin(angle)*speed;p.vy+=Math.cos(angle)*speed;limit563(p);p.nextShotAt563=g.simAt+C.reload;p.shots555++;p.pulling=false;p.power=0;event563(g,'launch',{seat:p.seat,x:p.x,y:p.y,carryX,carryY,vx:p.vx,vy:p.vy});return true;}
export function inputGoal563(g,p,m){if(!p||!Number.isSafeInteger(m.seq)||m.seq<=p.lastSeq||m.round!==1||m.shot!==p.shots555||!canShoot563(g,p)||!['pull','shoot','cancel'].includes(m.action))return false;
 if(m.action==='cancel'){p.pulling=false;p.power=0;p.lastSeq=m.seq;return true;}
 if(!Number.isFinite(m.power)||m.power<0||m.power>1||!Number.isFinite(m.angle)||Math.abs(m.angle)>Math.PI)return false;
 if(m.action==='shoot'){if(!launch563(g,p,m.power,m.angle))return false;}else{p.pulling=m.power>0;p.power=m.power;p.angle=m.angle;}p.lastSeq=m.seq;return true;
}
function cool(g,key,ms=110){if(g.simAt-(g.contacts[key]??-1e6)<ms)return false;g.contacts[key]=g.simAt;return true;}
function wall(g,p,nx,ny,depth){p.x+=nx*depth;p.y+=ny*depth;const v=p.vx*nx+p.vy*ny;if(v<0){p.vx-=1.9*v*nx;p.vy-=1.9*v*ny;if(-v>3&&cool(g,'w'+(p.seat??'gem')))event563(g,'wall',{seat:p.seat,x:p.x,y:p.y,strength:-v});}}
export function pairGoal563(g,a,b){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),r=a.r+b.r;if(d>=r)return 0;const nx=d>1e-7?dx/d:1,ny=d>1e-7?dy/d:0,ia=1/a.mass,ib=1/b.mass,over=r-d+.00001;a.x-=nx*over*ia/(ia+ib);a.y-=ny*over*ia/(ia+ib);b.x+=nx*over*ib/(ia+ib);b.y+=ny*over*ib/(ia+ib);const v=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(v>=0)return 0;const j=-1.88*v/(ia+ib);a.vx-=j*nx*ia;a.vy-=j*ny*ia;b.vx+=j*nx*ib;b.vy+=j*ny*ib;
 if(b===g.gem){b.lastTouch=a.seat;a.hits++;if(cool(g,'gem'+a.seat,130))event563(g,'gemHit',{seat:a.seat,x:b.x,y:b.y,strength:-v});}else if(cool(g,'p'+a.seat+':'+b.seat,170))event563(g,'hit',{seat:a.seat,other:b.seat,x:(a.x+b.x)/2,y:(a.y+b.y)/2,strength:-v});return -v;
}
export function rotorGoal563(g,p){const o=g.rotor,co=Math.cos(o.angle),si=Math.sin(o.angle),rx=p.x,ry=p.y-C.height/2,t=cap(rx*co+ry*si,-2.5,2.5),x=co*t,y=C.height/2+si*t,dx=p.x-x,dy=p.y-y,d=Math.hypot(dx,dy),r=p.r+.2;if(d>=r)return;const nx=d>1e-7?dx/d:-si,ny=d>1e-7?dy/d:co;p.x+=nx*(r-d+.00001);p.y+=ny*(r-d+.00001);const armX=x,armY=y-C.height/2,vx=-o.omega*armY,vy=o.omega*armX,v=(p.vx-vx)*nx+(p.vy-vy)*ny;if(v>=0)return;const cross=armX*ny-armY*nx,inertia=5.8,j=-(1+.84)*v/(1/p.mass+cross*cross/inertia);p.vx+=j*nx/p.mass;p.vy+=j*ny/p.mass;o.omega=cap(o.omega-j*cross/inertia,-13,13);if(p.seat!=null)o.lastTouch=p.seat;if(-v>1.5&&cool(g,'rotor'+(p.seat??'g'),150))event563(g,'rotor',{seat:p.seat,x,y,strength:-v,omega:o.omega});}
function goal(g,seat){const value=g.deadline-g.simAt<=15000?2:1,p=g.players[seat],gem=g.gem;p.score+=value;p.goals++;g.lastGoal={seat,value,at:g.simAt};event563(g,'goal',{seat,value,x:gem.x,y:gem.y,lastTouch:gem.lastTouch});g.gem=null;g.gemReadyAt=g.simAt+950;g.revision++;}
export function physicsGoal563(g,dt=C.step/1000){let left=dt;while(left>1e-9){const bodies=[...g.players,...(g.gem?[g.gem]:[])],speed=Math.max(1,...bodies.map(p=>Math.hypot(p.vx,p.vy))),h=Math.min(left,.12/(speed+Math.abs(g.rotor.omega)*2.5+1));left-=h;g.rotor.angle=(g.rotor.angle+g.rotor.omega*h)%TAU;g.rotor.omega*=Math.exp(-.35*h);
  for(const p of bodies){const drag=p===g.gem ? .52 : .78;p.vx*=Math.exp(-drag*h);p.vy*=Math.exp(-drag*h);p.x+=p.vx*h;p.y+=p.vy*h;}
  for(let pass=0;pass<3;pass++){for(const p of bodies){const w=C.width/2-p.r;if(p.x< -w)wall(g,p,1,0,-w-p.x);if(p.x>w)wall(g,p,-1,0,p.x-w);if(p.y<p.r)wall(g,p,0,1,p.r-p.y);if(p.y>C.height-p.r)wall(g,p,0,-1,p.y-C.height+p.r);rotorGoal563(g,p);}for(let i=0;i<g.players.length;i++)for(let j=i+1;j<g.players.length;j++)pairGoal563(g,g.players[i],g.players[j]);if(g.gem)for(const p of g.players)pairGoal563(g,p,g.gem);}
  for(const p of bodies)limit563(p);if(g.gem){const target=g.goals.find(q=>Math.hypot(q.x-g.gem.x,q.y-g.gem.y)<q.r);if(target)goal(g,target.seat);}
 }}
export function botGoal563(g,p){const gem=g.gem;if(!gem)return;const goal=g.goals[p.seat],dx=goal.x-gem.x,dy=goal.y-gem.y,d=Math.hypot(dx,dy)||1,behind={x:gem.x-dx/d*1.8,y:gem.y-dy/d*1.8},near=Math.hypot(behind.x-p.x,behind.y-p.y)<1.7,target=near?{x:gem.x+gem.vx*.08,y:gem.y+gem.vy*.08}:behind;return{angle:Math.atan2(target.x-p.x,target.y-p.y)+(random563(g)-.5)*.16,power:near?.6+random563(g)*.3:cap(Math.hypot(target.x-p.x,target.y-p.y)/20,.17,.47)};}
export function finishGoal563(g,at){if(g.phase==='result')return;g.phase='result';g.phaseAt=at;for(const p of g.players){p.pulling=false;p.vx=p.vy=0;}g.results=[...g.players].sort((a,b)=>b.score-a.score||a.seat-b.seat).map(p=>({playerId:p.playerId,seat:p.seat,name:p.name,score:p.score,goals:p.goals,rank:1+g.players.filter(q=>q.score>p.score).length}));g.winnerIds=g.results.filter(p=>p.rank===1).map(p=>p.playerId);g.revision++;event563(g,'finish');}
export function advanceGoal563(g,now,inputs=[],auto=new Set()){if(['lobby','result'].includes(g.phase)){g.serverAt=now;inputs.length=0;return;}
 if(now-g.simAt>2000){const shift=now-g.simAt-500;for(const k of ['simAt','phaseAt','startAt','roundAt','deadline','gemReadyAt'])g[k]+=shift;for(const p of g.players){p.nextShotAt563+=shift;p.botAt+=shift;}g.events=[];g.contacts={};}
 while(g.simAt+C.step<=now){g.simAt+=C.step;g.elapsed=Math.max(0,g.simAt-g.startAt);if(g.phase==='countdown'){inputs.length=0;if(g.simAt>=g.startAt){g.phase='play';g.phaseAt=g.simAt;spawnGem(g);event563(g,'start');g.revision++;}continue;}
  if(g.simAt>=g.deadline){finishGoal563(g,g.simAt);inputs.length=0;break;}
  if(!g.finalCue&&g.deadline-g.simAt<=15000){g.finalCue=true;if(g.gem)g.gem.value=2;event563(g,'final');}
  if(!g.gem&&g.simAt>=g.gemReadyAt)spawnGem(g);
  while(inputs.length&&inputs[0].at<=g.simAt){const m=inputs.shift(),p=g.players.find(q=>q.playerId===m.playerId);if(!auto.has(p?.playerId)&&!p?.ai)inputGoal563(g,p,m);}
  for(const p of g.players)if((p.ai||auto.has(p.playerId))&&g.simAt>=p.botAt&&canShoot563(g,p)){const aim=botGoal563(g,p);if(aim)launch563(g,p,aim.power,aim.angle);p.botAt=g.simAt+1400+random563(g)*1000;}physicsGoal563(g);
 }g.serverAt=now;g.updatedAt=now;
}
export function publicGoal563(g,id,{frame=false}={}){const s=copy(g);delete s.seed;delete s.contacts;s.members=s.members.map(({playerId,name,choice,ai,departed})=>({playerId,name,choice,ai:!!ai,departed:!!departed}));for(const p of s.players){delete p.botAt;if(p.playerId===id){p.appliedSeq563=p.lastSeq;p.lastSeq=Math.max(p.lastSeq??0,p.inputSeq563??0);}else delete p.lastSeq;delete p.inputSeq563;}if(frame){delete s.history;delete s.members;}return s;}
export const signatureGoal563=g=>!g?null:g.phase==='lobby'?[g.id,g.phase,g.revision,g.duration555]:[g.id,g.rules550,g.phase==='result'?'result':'play',g.phase==='result'?g.results:null];
