import {RICOCHET550 as C} from './Rules550.js';
import {clamp550 as clamp} from './Catalog550.js';
import {unlock543} from '../cart/Audio543.js';
const me=c=>c.state?.ricochet?.players.find(p=>p.playerId===c.transport.selfId);
export const canPull550=c=>{const g=c.state?.ricochet,p=me(c);return !!(g?.phase==='play'&&p&&!p.launched&&c.connected()&&Date.now()+(c.offset??0)<g.roundAt+C.launch&&c.ricochetUI550?.detail==null)};
export function sample550(start,end,w,h){const dx=end.x-start.x,dy=end.y-start.y,distance=Math.hypot(dx,dy),limit=Math.max(68,Math.min(112,w*.27,h*.35));return{active:distance>11,distance,power:distance>11?clamp((distance-11)/(limit-11),.08,1):0,angle:distance>11?(Math.atan2(-dx,dy)||0):0}}
export function send550(c,action,extra={}){const u=c.ricochetUI550,g=c.state.ricochet;if(!u||!g)return false;return c.raw('ricochetInput550',{gameId:g.id,round:g.round,seq:++u.seq,action,...extra})}
export function cancel550(c,notify=true){const u=c.ricochetUI550;if(!u)return;clearTimeout(u.flush);u.flush=null;if(notify&&u.pull&&canPull550(c))send550(c,'cancel');u.pull=null;u.pointer=null;u.origin=null}
export function bind550(c,root,signal){const u=c.ricochetUI550,stage=root.querySelector('[data-rc-stage]');
 const move=e=>{if(e.pointerId!==u.pointer||!u.origin)return;if(!canPull550(c)){cancel550(c,false);return}e.preventDefault();u.pull=sample550(u.origin,{x:e.clientX,y:e.clientY},stage.clientWidth,stage.clientHeight);clearTimeout(u.flush);const transmit=()=>{u.flush=null;if(u.pull&&canPull550(c))send550(c,'pull',{power:u.pull.power,angle:u.pull.angle})};const lag=Math.max(0,55-(performance.now()-(u.sentAt??0)));u.flush=setTimeout(()=>{u.sentAt=performance.now();transmit()},lag)};
 const up=e=>{if(e.pointerId!==u.pointer)return;e.preventDefault();move(e);clearTimeout(u.flush);const pull=u.pull;if(pull?.active&&canPull550(c)){send550(c,'shoot',{power:pull.power,angle:pull.angle});u.pending=Date.now()}else if(canPull550(c))send550(c,'cancel');cancel550(c,false)};
 const down=e=>{if(e.target.closest('button,a,input,summary,dialog'))return;if(u.pointer!=null){cancel550(c);return}if(e.isPrimary===false||e.button!==0||!canPull550(c))return;e.preventDefault();unlock543(u);u.pointer=e.pointerId;u.origin={x:e.clientX,y:e.clientY};u.pull={active:false,power:0,angle:0};try{e.target.setPointerCapture(e.pointerId)}catch{}};
 const on=(e,k,f,opts={})=>e.addEventListener(k,f,{signal,...opts});root.querySelectorAll('[data-rc-sling]').forEach(el=>on(el,'pointerdown',down));on(window,'pointermove',move,{passive:false});on(window,'pointerup',up,{passive:false});on(window,'pointercancel',e=>{if(e.pointerId===u.pointer)cancel550(c)});on(window,'blur',()=>cancel550(c));on(document,'visibilitychange',()=>{if(document.hidden)cancel550(c)});return()=>cancel550(c);
}
export function key550(c,e){if(!c.state?.ricochet||e.target.closest('button,input,select,textarea')||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' ','Escape'].includes(e.key))return false;if(!canPull550(c))return false;e.preventDefault();const u=c.ricochetUI550;unlock543(u);if(e.key==='Escape'){cancel550(c);return true}u.pull??={active:true,power:.5,angle:0};const p=u.pull;if(e.key==='ArrowLeft')p.angle=Math.max(-Math.PI,p.angle-.12);if(e.key==='ArrowRight')p.angle=Math.min(Math.PI,p.angle+.12);if(e.key==='ArrowUp')p.power=clamp(p.power+.08,.08,1);if(e.key==='ArrowDown')p.power=clamp(p.power-.08,.08,1);if(['Enter',' '].includes(e.key)&&!e.repeat){send550(c,'shoot',{power:p.power,angle:p.angle});u.pending=Date.now();cancel550(c,false)}else send550(c,'pull',{power:p.power,angle:p.angle});return true}
