import {ARENA555,canShoot555,final555} from './Arena555.js';
import {canBurst553,overdrive553,RUSH553} from './Rush553.js';
import {asset552,gemArt552} from './Art552.js';
import {emblem553,rushHud553} from './Art553.js';
import {affinity552,chainMultiplier552} from './Carnival552.js';
import {sound552} from './Audio552.js';
import {itemArt551,short551,effect551} from './Art551.js';
import {MODES550,item550,format550 as fmt} from './Catalog550.js';
import {signature550} from './Rules550.js';
import {renderer550,resize550,paint550} from './Renderer550.js';
import {icon550} from './Icons550.js';
import {bind550,cancel550,key550,send550,shotMode553,gestureValid555} from './Input550.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {playerColor499} from '../party/PartyColors499.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
import {unlock543} from '../cart/Audio543.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.ricochetUI550??={seq:0,sound:true,seen:0,limit:24,search:''},me=c=>c.state?.ricochet?.players.find(p=>p.playerId===c.transport.selfId),color=p=>playerColor499(p).hex,clock=c=>Date.now()+(c.offset??0),cover=asset552('carnival-poster');
export function avatar550(c,p){const sp=p.speciesId??p.choice?.speciesId??'slime',i=['slime','wolf','goblin','skeleton'].indexOf(sp);return i<0?c.sgMonster463?.(sp)??'':`<span class="sg-monster rc-avatar550" role="img" aria-label="${['スライム','ウルフ','ゴブリン','スケルトン'][i]}" style="background-position:${i%2*100}% ${Math.floor(i/2)*100}%"></span>`;}
function head(c){return `<header class="rc-head550"><button data-party-action462="browse" aria-label="ミニゲーム一覧へ">‹</button><div><small>ABYSS · IMPACT CARNIVAL</small><b>人間ピンボール</b></div><button data-rc-action="sound">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;}
function lobby(c,g){const u=ui(c),pm=c.state.party?.members.find(p=>p.playerId===c.transport.selfId),member=g.members.find(p=>p.playerId===c.transport.selfId),host=g.hostId===c.transport.selfId,list=c.roster().filter(p=>!u.search||(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??p.speciesId).includes(u.search));return `<section class="rc550 rc-lobby550" data-mode="pinball">${head(c)}<div class="rc-hero550" style="--cover:url('${cover}')"><small>狙って回せ。３色から、王冠へ。</small><h1>人間ピンボール<br>大運動会</h1><p>一撃で盤面を動かす、${g.duration555/1000}秒の得点勝負。</p></div><div class="rc-body550">${g.notice551?`<p class="rc-note550">${esc(g.notice551)}</p>`:''}<div class="rc-facts550"><span>４人対戦</span><span>空席はAI</span><span>能力６種</span></div><ol class="rc-rules550"><li><b>３色 → 上の王冠で大当たり。</b><p>赤・青・緑を集め、王冠にぶつける。まだ持っていない色が光るよ。王冠は×1・×3・×7！</p></li><li><b>外周レーンで３色まとめ取り。</b><p>左右の入口から上へ、３つの印を順に通過。完走点をもらって、そのまま王冠へ！</p></li><li><b>棒を叩いて、フィーバーを起こす。</b><p>端に当てるほど勢いよく回る。回転した分だけ充填、満タンで７秒間は全員得点２倍！ 起動した人には1,000点。</p></li></ol><div class="rc-round-choice550"><b>何秒で勝負？</b>${[90,150].map(n=>`<button data-rc-duration="${n}" aria-pressed="${g.duration555===n*1000}" ${host?'':'disabled'}>${n}秒</button>`).join('')}</div><h2>今日の相棒</h2><input name="ricochetSearch550" aria-label="相棒を探す" placeholder="相棒の名前で探す" value="${esc(u.search)}"><div class="rc-roster550">${list.slice(0,u.limit).map(p=>`<button data-rc-monster="${esc(p.id)}" aria-pressed="${member?.choice?.id===p.id}">${avatar550(c,{speciesId:p.raceSpeciesId??p.speciesId})}<span>${esc(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??p.speciesId)}</span></button>`).join('')}</div>${list.length>u.limit?'<button data-rc-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="rc-error550" role="alert">${esc(c.error)}</p><button class="rc-gold550 rc-wide550" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="rc-gold550 rc-wide550" data-rc-action="start" ${!c.ready()||c.state.party?.members.some(p=>!p.ready||!p.connected||p.atHome)?'disabled':''}>カーニバル開幕！</button>`:'<p>全員の準備ができたら、部屋主が開始します。</p>'}<p class="rc-note550">2.8秒ごとに引いて再発射。接触で満タンなら限界突破、4.2秒間は自分の得点２倍。押された勢いも上乗せするよ。ラウンド分けや位置リセットなし。能力は最初と30秒ごとに３択、７秒で自動選択。王冠は×1（60%）・×3（32%）・×7（8%）、残り15秒は王冠さらに２倍。切断中はAIが代行。同点は同順位。</p></div></section>`;}
function offer(c,g){const p=me(c),u=ui(c);if(!p?.offers?.length||!u.offerOpen555)return'';return `<section class="rc-dock551" aria-label="能力を選ぶ" data-rc-draft><header><b>${p.picked?'能力が届いた！':'最初の能力を選ぼう'}</b><span>あと <strong data-rc-picktime></strong>秒</span>${p.picked?'<button data-rc-action="offer-close" aria-label="能力選択を閉じる">×</button>':''}</header><div class="rc-offers551">${p.offers.map(id=>{const t=item550('pinball',id),lv=p.parts[id]??0;return `<button data-rc-pick="${id}" data-rc-offer="${p.offerId555}" class="rc-card551 rarity-${t.rarity}" aria-label="${esc(t.name)}。${esc(t.desc)}"><small>${affinity552(p,id)} <em>Lv.${lv+1}</em></small>${itemArt551('pinball',id)}<b>${short551[id]}</b><span>${effect551('pinball',id,lv+1)}</span></button>`;}).join('')}</div></section>`;}
function inventory(c,g){const p=g.players.find(p=>p.seat===ui(c).detail);if(!p)return'';return `<div class="rc-dialog-shade550"><section class="rc-dialog550" role="dialog" aria-modal="true" aria-label="${esc(p.name)}の能力"><header><h2>${esc(p.name)}の能力</h2><button data-rc-action="close" aria-label="閉じる">×</button></header><p>発射 ${p.shots555}回 · 限界突破 ${p.bursts553}回</p><div>${Object.entries(p.parts).map(([id,lv])=>{const t=item550('pinball',id);return `<article><i>${itemArt551('pinball',id)}</i><span><b>${t.name} ×${lv}</b><p>${t.desc}</p></span></article>`;}).join('')||'<p>画面下の３枚から選ぼう。</p>'}</div></section></div>`;}
function play(c,g){const p=me(c);return `<section class="rc550 rc-play550 rc-pinball552 rc-impact555" data-mode="pinball" data-phase="play">${head(c)}<div class="rc-players550">${g.players.map(q=>`<button data-rc-detail="${q.seat}" style="--player:${color(q)}"><span class="rc-player-top550">${avatar550(c,q)}<b>${q===p?'あなた':esc(q.name)}</b></span><strong data-rc-score="${q.seat}">0<small>点</small></strong><span data-rc-status="${q.seat}" class="rc-status550"></span></button>`).join('')}</div><div class="rc-mission555"><div class="rc-collection552" data-rc-collection><span>${[0,1,2].map(n=>gemArt552(n,false)).join('')}<i class="rc-crown552"></i></span><b data-rc-goal>３色を集めて、上の王冠へ</b></div><div class="rc-fever-strip555" data-rc-feverstrip><span data-rc-feverlabel>回転で FEVER</span><i><b data-rc-feverfill></b></i><strong data-rc-fevercount>0%</strong></div><div class="rc-clock555"><small data-rc-period>残り時間</small><strong data-rc-time></strong></div></div><div class="rc-stage550" data-rc-stage data-rc-sling><canvas data-rc-canvas tabindex="0" role="img" aria-label="人間ピンボール。飛ばす方向と逆へ引いて発射。2.8秒ごとに再発射。赤・青・緑から王冠へ。左右キーで方向、上下で強さ、Enterで発射。"></canvas><div class="rc-pawns550">${g.players.map(q=>`<div data-rc-pawn="${q.seat}" class="rc-pawn550 ${q===p?'is-self555':''}" style="--player:${color(q)}"><span>${avatar550(c,q)}</span><b>${q===p?'あなた':esc(q.name)}</b></div>`).join('')}</div><div class="rc-network550" data-rc-network hidden>再接続中… AIが代行中</div></div><footer class="rc-controls550" data-rc-sling><div><b data-rc-help>能力を選んで、引いて発射。</b><span data-rc-power></span></div><div class="rc-meter550" data-rc-meter role="meter" aria-label="発射の強さ" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i data-rc-fill></i><span>そっと</span><span>しっかり</span><span>全力</span></div>${rushHud553()}<div class="rc-buildbar550"><span data-rc-buildstats>狙って、もう一撃。</span><button data-rc-action="offer" data-rc-offerbutton hidden>能力が届いた！</button><button data-rc-detail="${p?.seat??0}"><span class="rc-equipped551" data-rc-equipped></span>能力</button></div><div data-rc-dock>${offer(c,g)}</div></footer>${inventory(c,g)}</section>`;}
function result(c,g){return `<section class="rc550 rc-result550" data-mode="pinball">${head(c)}<div class="rc-result-hero550" style="--cover:url('${cover}')"><small>THE GRAND FINALE</small><h1>本日の、跳ね王。</h1><div class="rc-champions550">${g.results.filter(r=>r.rank===1).map(r=>{const p=g.players[r.seat];return `<div style="--player:${color(p)}">${icon550('crown')}<span>${avatar550(c,p)}</span><b>${esc(p.name)}</b><strong>${fmt(p.score)}<small>点</small></strong></div>`;}).join('')}</div></div><div class="rc-body550">${resultActions490(c)}<div class="rc-finalrows550">${g.results.map(r=>{const p=g.players[r.seat];return `<article style="--player:${color(p)}"><em>${r.rank}</em><span>${avatar550(c,p)}</span><div><b>${esc(p.name)}</b><small>王冠 ${p.jackpots552}回 · レーン ${p.lanes555}回 · 回転起動 ${p.spinWins555}回</small></div><strong>${fmt(p.score)}<small>点</small></strong></article>`;}).join('')}</div><details class="rc-history550"><summary>何で稼いだ？ 得点の内訳</summary><div><table><thead><tr><th>得点源</th>${g.players.map(p=>`<th>${esc(p.name)}</th>`).join('')}</tr></thead><tbody>${[['pin','ピン'],['lane','外周レーン'],['spinner','回転起動'],['jackpot','王冠']].map(([key,name])=>`<tr><th>${name}</th>${g.players.map(p=>`<td>${fmt(p.breakdown555[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details><p class="rc-note550">${g.duration555/1000}秒間の合計得点。同点は同順位。次の試合は全員まっさらな能力からスタート。</p></div></section>`;}
export function ricochetView550(c){const g=c.state.ricochet,u=ui(c);if(u.id!==g.id){cancel550(c,false);Object.assign(u,{id:g.id,seq:0,seen:0,limit:24,search:'',detail:null,previous:null,notice:null,pending:null,pendingMode:null,offerSeen555:0,offerOpen555:true});}return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g);}
export function ricochetReceive550(c){const g=c.state?.ricochet;if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(g.phase!=='play'||u.pullMode&&!gestureValid555(c))cancel550(c,false);if(u.pendingMode==='normal'&&(p?.shots555??0)>(u.pendingShot555??0)||u.pendingMode==='burst'&&(p?.bursts553??0)>(u.pendingShot555??0)){u.pending=null;u.pendingMode=null;}if(p&&u.offerSeen555!==p.offerId555){u.offerSeen555=p.offerId555;u.offerOpen555=!p.picked;u.dockKey=null;}if(!p?.offers?.length)u.offerOpen555=false;u.receivedAt=performance.now();}
export function ricochetFrame550(c,m){const old=c.state?.ricochet,n=m.ricochet;if(m.selfId!==c.transport.selfId||!old||n?.id!==old.id||n.serverAt<old.serverAt)return;const u=ui(c);u.previous=old;c.offset=m.serverNow-Date.now();c.state.ricochet={...old,...n,members:n.members??old.members,history:n.history??old.history};ricochetReceive550(c);if(old.phase!==n.phase)c.render();}
const put=(n,s)=>{if(n&&n.textContent!==String(s))n.textContent=String(s);};
function sync555(c){const g=c.state.ricochet,u=ui(c),p=me(c),n=u.nodes,key=[p?.offerId555,p?.offers?.join(','),u.offerOpen555,Object.values(p?.parts??{}).join(',')].join(':');if(u.dockKey===key)return;u.dockKey=key;n.dock.innerHTML=offer(c,g);n.equipped.innerHTML=Object.keys(p?.parts??{}).map(id=>itemArt551('pinball',id)).join('');n.offerbutton.hidden=!p?.picked||!p.offers.length;u.root.dataset.picking=u.offerOpen555&&p?.offers.length?'true':'false';}
function tick550(c){const g=c.state.ricochet,u=ui(c),n=u.nodes,p=me(c),at=clock(c);if(!g||g.phase!=='play')return;sync555(c);paint550(u.renderer,g,c.transport.selfId,u,at);const left=Math.max(0,(g.deadline-at)/1000),final=final555(g,at);put(n.time,`${Math.floor(Math.ceil(left)/60)}:${String(Math.ceil(left)%60).padStart(2,'0')}`);put(n.period,final?'王冠２倍！':'残り時間');u.root.dataset.final=final?'true':'false';put(n.dock.querySelector('[data-rc-picktime]'),Math.max(0,Math.ceil(((p?.offerUntil555??at)-at)/1000)));
 for(const q of g.players){const e=u.scores[q.seat],value=fmt(q.score+q.roundScore);if(e.dataset.value!==value){e.dataset.value=value;e.replaceChildren(document.createTextNode(value),Object.assign(document.createElement('small'),{textContent:'点'}));e.style.fontSize=value.length>6?'15px':'';}const rank=1+g.players.filter(z=>z.score+z.roundScore>q.score+q.roundScore).length;put(u.statuses[q.seat],rank+'位 · '+(q.gems552===7?'王冠へ！':`${[0,1,2].filter(k=>q.gems552&(1<<k)).length}/3色`));}
 for(const pos of u.renderer.positions){const e=u.pawns[pos.seat];e.hidden=!pos.visible;e.style.transform=`translate(${pos.x}px,${pos.y}px)`;e.style.setProperty('--pawn-size',pos.size+'px');e.dataset.labelAbove=pos.y+pos.size*.85>u.renderer.height?'true':'false';}
 const pow=u.pull?.power??0,active=!!u.pull?.active,ready=canBurst553(g,p,at),rush=overdrive553(p??{},at),shoot=canShoot555(g,p,at),reload=Math.max(0,((p?.nextShotAt555??at)-at)/1000);n.fill.style.transform=`scaleX(${active?pow:shoot?0:Math.max(0,1-reload/2.8)})`;n.meter.setAttribute('aria-valuenow',String(Math.round(pow*100)));put(n.power,active?(pow>.9?'MAX！':Math.round(pow*100)+'%'):shoot||ready?'発射OK':`装填 ${reload.toFixed(1)}秒`);
 put(n.help,!p?'みんなの試合を観戦中':!p.picked?'能力を１つ選ぼう。':active?(u.pullMode==='burst'?'離して、限界突破！':'離して、狙った方向へ！'):ready?'満タン！ 引いて限界突破！':shoot?'狙いを決めて、引いて発射。':'次はどこを狙う？');
 put(n.buildstats,p?`連鎖 ×${chainMultiplier552(p).toFixed(1)} · 発射 ${p.shots555}回`:'');n.network.hidden=c.connected();
 const gems=p?.gems552??0,rest=Math.max(0,Math.ceil((g.carnival552.lockUntil-at)/1000)),missing=[0,1,2].filter(k=>!(gems&(1<<k))).map(k=>['赤','青','緑'][k]);n.collection.querySelectorAll('[data-gem]').forEach(e=>e.classList.toggle('is-lit',!!(gems&(1<<Number(e.dataset.gem)))));n.collection.classList.toggle('is-ready',gems===7);
 let goal=gems===7?(rest?`王冠まで ${rest}秒 · ３色は保持`:`上の王冠へ！ 基本 ${fmt(g.carnival552.pot)}点`):`あと${missing.join('・')} → 上の王冠へ`;
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(at-e.at>1000)continue;const local=e.seat===p?.seat;if(local||['fever','jackpot'].includes(e.type)){if(at-(u.lastSound??0)>70||['jackpot','burst','ready'].includes(e.type)){sound552(u,e);u.lastSound=at;}}
  if(local&&['ready','laneComplete'].includes(e.type))u.notice={text:e.text,until:at+1350};if(e.type==='fever')u.notice={text:e.text,until:at+1400};if(e.type==='jackpot'){u.notice={text:`${local?'あなた':g.players[e.seat].name} · 王冠 ×${e.tier} ＋${fmt(e.value)}点`,until:at+(local?2200:1300),big:true};if(local)u.impact553={at,strength:e.tier===7?2:1.2};}if(e.type==='burst'&&local){u.notice={text:'限界突破！ 4.2秒、自分の得点２倍',until:at+1000};u.impact553={at,strength:1.3};}
 }
 if(u.notice&&at<u.notice.until)goal=u.notice.text;put(n.goal,goal);u.root.dataset.celebrate=u.notice?.big&&at<u.notice.until?'true':'false';
 const f=Math.max(0,(g.carnival552.feverUntil-at)/1000);u.root.dataset.fever=f>0?'true':'false';put(n.feverlabel,f>0?'FEVER · 全員 ×2':'回転で FEVER');put(n.fevercount,f>0?f.toFixed(1)+'秒':Math.floor(g.carnival552.heat)+'%');n.feverfill.style.transform=`scaleX(${f>0?f/7:g.carnival552.heat/100})`;
 const charge=p?.burstCharge553??0;u.root.dataset.rush=rush?'active':ready?'ready':'charging';n.rush.setAttribute('aria-valuenow',String(Math.round(charge)));n.rushfill.style.transform=`scaleX(${rush?Math.max(0,(p.overdriveUntil553-at)/RUSH553.duration):charge/100})`;put(n.rushlabel,rush?'限界突破 ×2':ready?'限界突破 READY':'接触で限界突破');put(n.rushvalue,rush?Math.max(0,(p.overdriveUntil553-at)/1000).toFixed(1)+'秒':ready?'発射OK':Math.floor(charge)+'%');
}
export function ricochetBefore550(c){const u=c.ricochetUI550;if(!u)return;u.cleanup?.();u.cleanup=null;cancelAnimationFrame(u.raf);u.raf=null;u.root=null;}
export function ricochetDispose550(c){ricochetBefore550(c);c.ricochetUI550?.audio?.close()?.catch(()=>{});if(c.ricochetUI550)c.ricochetUI550.audio=null;}
export function ricochetAfter550(c){const root=c.root?.querySelector('.rc-play550');if(!root)return;const u=ui(c);u.root=root;u.dockKey=null;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;u.nodes=Object.fromEntries(['stage','canvas','time','period','help','power','meter','fill','buildstats','network','dock','equipped','offerbutton','collection','goal','feverlabel','fevercount','feverfill','rush','rushlabel','rushfill','rushvalue'].map(k=>[k,root.querySelector(`[data-rc-${k}]`)]));u.scores=[...root.querySelectorAll('[data-rc-score]')];u.statuses=[...root.querySelectorAll('[data-rc-status]')];u.pawns=[...root.querySelectorAll('[data-rc-pawn]')];u.renderer=renderer550(u.nodes.canvas);const abort=new AbortController(),resize=()=>{const s=u.nodes.stage;if(u.renderer.width===s.clientWidth&&u.renderer.height===s.clientHeight)return;cancel550(c);resize550(u.renderer,s.clientWidth,s.clientHeight,devicePixelRatio||1);};resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const zoom=lockPlayZoom498(root),unbind=bind550(c,root,abort.signal);
 const tick=()=>{u.raf=null;if(!u.root||document.hidden)return;tick550(c);u.raf=requestAnimationFrame(tick);};document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{});}else{c.refresh?.();if(u.raf==null)tick();}},{signal:abort.signal});u.cleanup=()=>{unbind();observer.disconnect();abort.abort();zoom();};ricochetReceive550(c);tick();root.querySelector('[role="dialog"] button')?.focus({preventScroll:true});}
export function ricochetClick550(c,b){if(!c.state?.ricochet||!Object.keys(b.dataset).some(k=>k.startsWith('rc')))return false;const u=ui(c),g=c.state.ricochet,d=b.dataset;unlock543(u);if(d.rcMonster)c.raw('ricochet550',{gameId:g.id,kind:'select',monsterId:d.rcMonster});if(d.rcDuration)c.raw('ricochet550',{gameId:g.id,kind:'duration',seconds:Number(d.rcDuration)});if(d.rcPick)send550(c,'pick',{item:d.rcPick,offerId:Number(d.rcOffer)});if(d.rcDetail!=null){cancel550(c);u.detail=Number(d.rcDetail);c.render();}if(d.rcAction==='close'){u.detail=null;c.render();}if(d.rcAction==='offer'||d.rcAction==='offer-close'){cancel550(c);u.offerOpen555=d.rcAction==='offer';u.dockKey=null;sync555(c);}if(d.rcAction==='start')c.raw('ricochet550',{gameId:g.id,kind:'start'});if(d.rcAction==='more'){u.limit+=24;c.render();}if(d.rcAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});}return true;}
export function ricochetInput550(c,e){if(e.name!=='ricochetSearch550')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true;}
export function ricochetKey550(c,e){const u=c.ricochetUI550;if(u?.detail!=null&&e.key==='Escape'){u.detail=null;c.render();return true;}if(u?.detail!=null&&e.key==='Tab'){e.preventDefault();c.root.querySelector('.rc-dialog550 button')?.focus();return true;}return key550(c,e);}
