import {PINBALL563 as C,canShoot563} from './Goals563.js';
import {board563,resize563,paintBoard563} from './Board563.js';
import {esc563 as esc,color563 as color,put563 as put,clock563 as clock,avatar563,header563,lobby563,result563,scoreCards563} from '../party/Arcade563.js';
import {unlock543} from '../cart/Audio543.js';
import {sound552} from './Audio552.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const ui=c=>c.ricochetUI550??={seq:0,sound:true,seen:0,limit:24,search:''},me=c=>c.state?.ricochet?.players.find(p=>p.playerId===c.transport.selfId);
const options={prefix:'rc',title:'人間ピンボール',sub:'TREASURE GOAL',cover:new URL('../../assets/ricochet552/carnival-poster.png',import.meta.url).href,hero:'その宝石、<br>こっちのゴールへ！',rule:'引いて、離す。宝石を自分の色のゴールへ。',detail:'宝石を入れたゴールの持ち主に１点。相手の横取りも、体当たりで阻止！ 最後の15秒は２点の宝石。中央の棒は、ぶつけた勢いで回ります。',search:'ricochetSearch550'};
export const avatar550=avatar563;
function play(c,g){return `<section class="arc563 arc-play563 pb-play563">${header563(c,ui(c),'rc',options.title,options.sub)}${scoreCards563(c,g)}<div class="arc-mission563"><div><small>TREASURE GOAL</small><b>宝石を、自分のゴールへ！</b></div><strong data-rc-time>90<small>秒</small></strong></div><div class="pb-stage563" data-rc-stage><canvas data-rc-canvas tabindex="0" role="img" aria-label="引いて離すと発射。宝石をあなたの色のゴールへ弾き込むと得点。矢印キーで方向、スペースを離すと発射。"></canvas><div class="pb-pawns563">${g.players.map(p=>`<div class="pb-pawn563" data-rc-pawn="${p.seat}" style="--player:${color(p)}"><span>${avatar563(c,p)}</span><b>${p.playerId===c.transport.selfId?'YOU':esc(p.name)}</b></div>`).join('')}</div><div class="arc-count563" data-rc-count hidden></div><div class="pb-goal563" data-rc-goal role="status" hidden></div><div class="arc-network563" data-rc-network hidden>再接続中 · AIが引き継いでいます</div></div><footer class="pb-control563"><div><b data-rc-help>画面を引いて、離す！</b><span data-rc-ready>発射OK</span></div><div class="arc-meter563"><i data-rc-meter></i></div><p data-rc-tip>飛ばしたい向きの逆へ引く · 今いる場所から発射</p></footer></section>`;}
export function ricochetView550(c){const g=c.state.ricochet,u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,limit:24,search:'',previous:null,pull:null,pending:null});return g.phase==='lobby'?lobby563(c,g,u,options):g.phase==='result'?result563(c,g,u,{...options,caption:g.winnerIds.includes(c.transport.selfId)?'お宝、いただき！':'ゴール争奪、決着！',stats:p=>`宝石 ${p.goals}個 · ${p.hits}回アタック`}):play(c,g);}
export function ricochetReceive550(c){const g=c.state?.ricochet;if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.pending&&(p?.shots555>u.pending.shot||clock(c)-u.pending.at>1600))u.pending=null;if(g.phase!=='play'||!canShoot563(g,p,clock(c)))u.pull=null;u.receivedAt=performance.now();}
export function ricochetFrame550(c,m){const g=c.state?.ricochet,n=m.ricochet;if(m.selfId!==c.transport.selfId||!g||n?.id!==g.id||n.serverAt<g.serverAt)return;ui(c).previous=g;c.offset=m.serverNow-Date.now();c.state.ricochet={...g,...n,members:n.members??g.members};ricochetReceive550(c);if((g.phase==='result')!==(n.phase==='result'))c.render();}
function send(c,action,extra={}){const g=c.state.ricochet,p=me(c);if(!c.ready()||!canShoot563(g,p,clock(c)))return false;return c.raw('ricochetInput550',{gameId:g.id,seq:++ui(c).seq,round:1,shot:p.shots555,action,...extra});}
function cancel(c,notify=true){const u=ui(c);if(u.pull&&notify)send(c,'cancel');u.pull=null;u.pointer=null;u.keyDown=null;}
function fire(c){const u=ui(c),p=me(c),pull=u.pull;if(pull?.power>=.08&&!u.pending&&send(c,'shoot',{power:pull.power,angle:pull.angle})!==false){u.pending={shot:p.shots555,at:clock(c)};}else if(pull)send(c,'cancel');cancel(c,false);}
function paint(c){const u=ui(c),g=c.state.ricochet,p=me(c),n=u.nodes,at=clock(c);if(!g?.goals)return;if(u.pending&&at-u.pending.at>1600)u.pending=null;if(u.keyDown&&u.pull)u.pull.power=Math.min(1,(performance.now()-u.keyDown)/700);paintBoard563(u.renderer,g,c.transport.selfId,u,at);const left=Math.max(0,Math.ceil((g.deadline-at)/1000)),ready=canShoot563(g,p,at)&&!u.pending;put(n.time,left+'秒');n.time.classList.toggle('is-hot',left<=15);put(n.help,g.phase==='countdown'?'宝石をあなたのゴールへ':u.pull?'離して、ぶつけろ！':ready?'画面を引いて、離す！':'次の一撃を準備中…');put(n.ready,u.pull?Math.round(u.pull.power*100)+'%':ready?'発射OK':Math.max(0,(p?.nextShotAt563-at)/1000).toFixed(1)+'秒');n.meter.style.transform=`scaleX(${u.pull?.power??(ready?1:Math.max(0,1-((p?.nextShotAt563??at)-at)/C.reload))})`;put(n.tip,left<=15?'ラスト15秒！ 宝石１個で２点！':'飛ばしたい向きの逆へ引く · 今いる場所から発射');
 for(const player of g.players){const q=u.renderer.points.find(q=>q.seat===player.seat),el=u.pawns[player.seat];if(q&&el){el.style.transform=`translate(${q.x}px,${q.y}px)`;el.style.setProperty('--size',q.size+'px');el.style.zIndex=String(Math.round(q.y));}put(u.scores[player.seat],player.score+'点');put(u.statuses[player.seat],`${player.seat+1}番ゴール · ${player.goals}個`);}
 n.count.hidden=g.phase!=='countdown';if(!n.count.hidden)put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000)));const goal=g.lastGoal,show=goal&&at-goal.at<1500&&at>=goal.at;n.goal.hidden=!show;if(show){n.goal.style.setProperty('--player',color(g.players[goal.seat]));put(n.goal,`${goal.seat===p?.seat?'あなた':g.players[goal.seat].name}　GOAL ＋${goal.value}`);}n.network.hidden=c.connected();
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(Math.abs(at-e.at)>1000)continue;sound552(u,{...e,type:e.type==='goal'?'jackpot':e.type==='gemHit'?'pin':e.type==='final'?'ready':e.type});}
}
export function ricochetBefore550(c){const u=c.ricochetUI550;if(!u)return;u.cleanup?.();u.cleanup=null;cancelAnimationFrame(u.raf);u.raf=null;u.root=null;cancel(c,false);}
export function ricochetDispose550(c){ricochetBefore550(c);c.ricochetUI550?.audio?.close()?.catch(()=>{});if(c.ricochetUI550)c.ricochetUI550.audio=null;}
export function ricochetAfter550(c){const root=c.root?.querySelector('.pb-play563');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;u.nodes=Object.fromEntries(['stage','canvas','time','count','goal','network','help','ready','meter','tip'].map(k=>[k,root.querySelector(`[data-rc-${k}]`)]));u.pawns=[...root.querySelectorAll('[data-rc-pawn]')];u.scores=[...root.querySelectorAll('[data-arc-score]')];u.statuses=[...root.querySelectorAll('[data-arc-status]')];u.renderer=board563(u.nodes.canvas);const abort=new AbortController(),on=(e,k,fn)=>e.addEventListener(k,fn,{signal:abort.signal}),resize=()=>{cancel(c);resize563(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);};resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const zoom=lockPlayZoom498(root);let last=0;
 const move=e=>{if(u.pointer!==e.pointerId||!u.pull)return;const dx=u.origin.x-e.clientX,dy=e.clientY-u.origin.y;u.pull.angle=Math.atan2(dx/u.renderer.sx,dy/u.renderer.sy);u.pull.power=Math.min(1,Math.hypot(dx,dy)/Math.min(125,u.renderer.width*.33));if(clock(c)-last>85){send(c,'pull',u.pull);last=clock(c);}};
 on(u.nodes.canvas,'pointerdown',e=>{const g=c.state.ricochet;if(e.button!==0||u.pointer!=null||u.pending||!canShoot563(g,me(c),clock(c)))return;e.preventDefault();unlock543(u);u.nodes.canvas.focus({preventScroll:true});u.pointer=e.pointerId;u.origin={x:e.clientX,y:e.clientY};u.pull={power:0,angle:0};u.nodes.canvas.setPointerCapture(e.pointerId);});on(u.nodes.canvas,'pointermove',move);on(u.nodes.canvas,'pointerup',e=>{if(e.pointerId!==u.pointer)return;e.preventDefault();move(e);fire(c);});on(u.nodes.canvas,'pointercancel',()=>cancel(c));on(u.nodes.canvas,'lostpointercapture',()=>{if(u.pointer!=null)cancel(c);});on(u.nodes.canvas,'contextmenu',e=>e.preventDefault());on(window,'blur',()=>cancel(c));on(window,'keyup',e=>{if(e.code==='Space'&&u.keyDown){e.preventDefault();fire(c);}});
 const tick=()=>{u.raf=null;if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick);};on(document,'visibilitychange',()=>{cancel(c);if(document.hidden){cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{});}else{c.refresh?.();if(u.raf==null)tick();}});u.cleanup=()=>{cancel(c);abort.abort();observer.disconnect();zoom();};ricochetReceive550(c);tick();}
export function ricochetClick550(c,b){const d=b.dataset;if(!c.state?.ricochet||!Object.keys(d).some(k=>k.startsWith('rc')))return false;const u=ui(c),g=c.state.ricochet;unlock543(u);if(d.rcMonster)c.raw('ricochet550',{gameId:g.id,kind:'select',monsterId:d.rcMonster});if(d.rcDuration)c.raw('ricochet550',{gameId:g.id,kind:'duration',seconds:Number(d.rcDuration)});if(d.rcAction==='start')c.raw('ricochet550',{gameId:g.id,kind:'start'});if(d.rcAction==='more'){u.limit+=24;c.render();}if(d.rcAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock543(u);}return true;}
export function ricochetInput550(c,e){if(e.name!=='ricochetSearch550')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true;}
export function ricochetKey550(c,e){if(!c.root?.querySelector('.pb-play563')||/INPUT|TEXTAREA/.test(e.target?.tagName))return false;const u=ui(c);if(e.key==='Escape'){cancel(c);return true;}const directions={ArrowUp:0,ArrowRight:Math.PI/2,ArrowDown:Math.PI,ArrowLeft:-Math.PI/2};if(directions[e.key]!=null){e.preventDefault();u.keyAngle=directions[e.key];if(u.pull)u.pull.angle=u.keyAngle;return true;}if(e.code==='Space'){e.preventDefault();if(!e.repeat&&!u.pending&&canShoot563(c.state.ricochet,me(c),clock(c))){unlock543(u);u.keyDown=performance.now();u.pull={power:.08,angle:u.keyAngle??0};}return true;}return false;}
