import {course589} from './Courses589.js';
import {courseLobby589,coopResult589} from './Presentation589.js';
import {section587} from './Level587.js';
import {rank588} from './Feel588.js';
import {signature587} from './Rules587.js';
import {active587,predict587,stop587,bind587,key587,controlsTick587} from './Controls587.js';
import {board587,resize587,paint587} from './Board587.js';
import {esc563 as esc,color563 as color,put563 as put,clock563 as clock,avatar563,header563,lobby563} from '../party/Arcade563.js';
import {resultActions490} from '../party/PartyResults490.js';
import {sound543,unlock543} from '../cart/Audio543.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const game=c=>c.state?.runners,ui=c=>c.runnersUI587??={seq:0,sound:true,seen:0,limit:24,search:'',keys:new Set(),pointers:new Map()},me=c=>game(c)?.players.find(p=>p.playerId===c.transport.selfId),seconds=n=>(Math.max(0,n??0)/1000).toFixed(2);
const options={prefix:'ru',title:'とびだせ！魔界ランナーズ',sub:'RUN · JUMP · ADVENTURE',cover:new URL('../../assets/runners587/cover.webp',import.meta.url).href,hero:'駆け抜けろ、<br>魔界の向こうへ。',rule:'左右で走る。ジャンプで、先へ！',detail:'左下の◀▶を押したまま走り、指を左右に滑らせると向きを切り替えられるよ。右下のジャンプで飛ぼう！ 短く押すと低く、長く押すと高く跳べるよ。甲虫は上から踏めば倒せる。バネは大ジャンプ、緑の宝石は2.6秒のスピードアップ！ 浮遊足場を使った上のルートもあるよ。最初の上段にある宝石を取ると、穴を大きく飛び越えて加速できる！穴に落ちたり、敵の横にぶつかるとハートが１つ減り、旗のチェックポイントから再開。ハートは３つ、なくなったら脱落！ 制限時間75秒、最初のゴールから残り16秒。ゴールした順に順位が決まるよ。',players:'４人競走 · 空席はAI · 点数なし',search:'runnersSearch587',note:'相棒の能力差やプレイヤー同士の押し合いはありません。未ゴールの人は最も進んだ距離で順位が決まります。同着は同順位。切断・離席中はAIに交代。PCは←→／A・Dで移動、スペース／↑でジャンプ。'};
function cards(c,g){return `<div class="ru-players587">${g.players.map(p=>`<button data-ru-watch="${p.seat}" data-ru-card="${p.seat}" style="--player:${color(p)}" aria-label="${esc(p.name)}の状況"><span class="ru-card-avatar587">${avatar563(c,p)}</span><span><b>${p.playerId===c.transport.selfId?'あなた':esc(p.name)}</b><small data-ru-status="${p.seat}">♥ ♥ ♥</small></span><i data-ru-rank="${p.seat}">—</i></button>`).join('')}</div>`;}
function play(c,g){const course=course589(g);return `<section class="arc563 arc-play563 ru-play587 ru-polish588 ru-gimmicks589 ${course.mode==='coop'?'ru-coop589':''}">${header563(c,ui(c),'ru',options.title,options.sub)}${cards(c,g)}<div class="ru-brief587"><div><small>WORLD <span data-ru-world>01</span> / 03</small><b data-ru-section>こもれびの森</b></div><div class="ru-timer587"><small>TIME LEFT</small><b data-ru-time>75<span>秒</span></b></div></div><div class="ru-route587" aria-label="コース全体の進み具合"><span>START</span><div class="ru-track587">${course.sections.slice(1).map(s=>`<i style="left:${s.x/course.goal*100}%"></i>`).join('')}${g.players.map(p=>`<b data-ru-dot="${p.seat}" style="--player:${color(p)};left:0%">${p.seat+1}</b>`).join('')}</div><span>GOAL</span></div><div class="ru-field587" data-ru-field tabindex="0" role="group" aria-label="横スクロールコース。左右移動とジャンプでゴールへ"><canvas data-ru-canvas aria-hidden="true"></canvas><div class="ru-stage587"><small data-ru-stage>FOREST RUN</small><b data-ru-hint>ジャンプは、長押しで高く！</b></div><div class="ru-boost588" data-ru-boost hidden><span>◆</span><b>加速中 <em data-ru-boost-time></em></b><i><u data-ru-boost-bar></u></i></div><div class="ru-rivals588" data-ru-rivals aria-hidden="true"></div><div class="ru-mission589" data-ru-mission ${course.mode==='coop'?'':'hidden'}><div>${course.switches.map(s=>`<i data-ru-switch="${s.id}">${s.label}</i>`).join('')}</div><b data-ru-mission-text>対岸スイッチで、みんなの橋を開こう</b></div><div class="ru-pawns587" aria-hidden="true">${g.players.map(p=>`<div class="ru-pawn587" data-ru-pawn="${p.seat}" style="--player:${color(p)}"><mark>▼</mark><b>${p.playerId===c.transport.selfId?'あなた':String(p.seat+1)+'P'}</b><span class="ru-sprite587">${avatar563(c,p)}</span><i></i></div>`).join('')}</div><div class="ru-toast587" data-ru-toast hidden role="status" aria-live="polite"></div><div class="ru-count587" data-ru-count role="status" aria-live="assertive"></div><div class="ru-message587" data-ru-message hidden role="status"></div><div class="ru-network587" data-ru-network hidden>再接続中 · AIが走っています</div><div class="ru-watch587" data-ru-watch-label hidden></div></div><footer class="ru-footer587"><div class="ru-help587"><b data-ru-help>左右で走る ＋ ジャンプ</b><span data-ru-note>短押しで低く · 長押しで高く</span></div><div class="ru-controls587"><div class="ru-directions587"><button data-ru-control="left" aria-label="左へ移動"><b>◀</b><small>LEFT</small></button><button data-ru-control="right" aria-label="右へ移動"><b>▶</b><small>RIGHT</small></button></div><span class="ru-controls-note587"><b>◆</b><span data-ru-progress>0%</span><small>ゴールまで</small></span><button class="ru-jump587" data-ru-control="jump" aria-label="ジャンプ、長押しで高く跳ぶ"><b>↑</b><strong>ジャンプ</strong><small>HOLD TO JUMP HIGH</small></button></div></footer></section>`;}
function result(c,g){if(course589(g).mode==='coop')return coopResult589(c,g,ui(c),options);const won=g.winnerIds.includes(c.transport.selfId),anyGoal=g.players.some(p=>p.finishTime!=null);return `<section class="arc563 ru-result587">${header563(c,ui(c),'ru',options.title,options.sub)}<div class="arc-cover563 ru-finale587" style="--cover:url('${options.cover}')"><small>ADVENTURE COMPLETE</small><h1>${won?'１位、おめでとう！':anyGoal?'魔界を、駆け抜けた！':'冒険の記録！'}</h1><div class="arc-champions563">${g.results.filter(r=>r.rank===1).map(r=>{const p=g.players[r.seat];return `<div style="--player:${color(p)}">${avatar563(c,p)}<b>${esc(p.name)}</b><strong>${p.finishTime==null?r.distance+'%':seconds(p.finishTime)+'秒'}<small>${p.finishTime==null?'到達':'GOAL'}</small></strong></div>`}).join('')}</div></div><div class="arc-body563">${resultActions490(c)}<div class="ru-results587">${g.results.map(r=>{const p=g.players[r.seat];return `<article style="--player:${color(p)}"><em>${r.rank}<small>位</small></em>${avatar563(c,p)}<div><b>${esc(p.name)}</b><small>${p.finishTime!=null?'ゴール！':p.alive?'時間切れ':'ハートがなくなった'} · 敵を${p.stomps}体撃破</small></div><strong>${p.finishTime!=null?seconds(p.finishTime)+'秒':r.distance+'%'}<small>${p.finishTime!=null?'GOAL TIME':'最も進んだ距離'}</small></strong></article>`}).join('')}</div><p class="arc-note563">ゴールした人が上位！ 未ゴールの人は最も進んだ距離で順位が決まります。同着は同順位。もう一度挑んで、走りを磨こう！</p></div></section>`;}
export function runnersView587(c){const g=game(c),u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,keys:new Set(),pointers:new Map(),intent:{axis:0,jump:false},sentJump:false,pendingJump:null,notice:null,limit:24,search:'',lastSent:-9999,watch:null,section:-1});if(g.rules587!==3)return '<section class="arc563">本体とサーバーをBuild589へ更新してください。</section>';return g.phase==='lobby'?lobby563(c,g,u,courseLobby589(c,g,options)):g.phase==='result'?result(c,g):play(c,g);}
export function runnersReceive587(c){const g=game(c);if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(p&&(!p.alive||p.auto||p.respawnAt||p.finishTime!=null))stop587(c,{send:false});}
export function runnersFrame587(c,m){const n=m.runners,g=game(c);if(m.selfId!==c.transport.selfId||!g||n?.id!==g.id||n.serverAt<g.serverAt)return;c.offset=m.serverNow-Date.now();c.state.runners={...g,...n};runnersReceive587(c);if(signature587(g).phase!==signature587(n).phase)c.render();}
const rankOf=rank588;
function update(c){const g=game(c),course=course589(g),u=ui(c),n=u.nodes,p=me(c),at=clock(c);if(!g.players.length)return;const watch=!p||!p.alive||p.finishTime!=null,live=g.players.filter(p=>p.alive&&p.finishTime==null),focus=watch?(live.find(p=>p.seat===u.watch)??[...live].sort((a,b)=>b.x-a.x)[0]??p??g.players[0]):p;
 const positions=g.players.map(q=>predict587(c,q,at)),fp=positions[focus.seat],section=section587(fp.x,course),sectionIndex=course.sections.indexOf(section),busy=g.phase==='countdown',finish=g.stage==='finish',remaining=Math.max(0,Math.ceil((g.deadline-at)/1000));
 paint587(u.renderer,g,u,positions,fp,at);const r=u.renderer;
 put(n.section,section.name);put(n.world,String(sectionIndex+1).padStart(2,'0'));put(n.time,String(busy?course.duration/1000:remaining)+'秒');n.time.classList.toggle('is-urgent',remaining<=10);put(n.stage,course.en);put(n.hint,p?.wallSide?'ジャンプを押し直して、壁キック！':section.sub);put(n.progress,Math.max(0,100-Math.floor(fp.furthest/course.goal*100))+'%');n.boost.hidden=!(focus.boostUntil>at);if(!n.boost.hidden){put(n.boostTime,((focus.boostUntil-at)/1000).toFixed(1)+'秒');n.boostBar.style.transform='scaleX('+Math.max(0,(focus.boostUntil-at)/2600)+')';}
 for(const q of g.players){const pos=positions[q.seat],pawn=u.pawns[q.seat],x=(pos.x-r.camera)*r.scale,y=pos.y*r.scale+r.offsetY;const hidden=!q.alive||!!q.respawnAt||q.finishTime!=null||x<-55||x>r.width+55;const overlap=g.players.filter(other=>other.seat<q.seat&&Math.abs(other.x-q.x)<40&&Math.abs(other.y-q.y)<40).length;
  pawn.hidden=hidden;pawn.style.left=x+'px';pawn.style.top=y+'px';pawn.style.setProperty('--sprite',Math.max(33,48*r.scale)+'px');pawn.style.setProperty('--label-lift',overlap*13+'px');pawn.style.setProperty('--facing',q.facing);pawn.style.zIndex=q.playerId===c.transport.selfId?'8':String(q.seat+1);pawn.classList.toggle('is-self',q.playerId===c.transport.selfId);pawn.classList.toggle('is-air',!pos.grounded);pawn.classList.toggle('is-wall',!!q.wallSide&&!q.grounded);pawn.classList.toggle('is-assisted',!u.reduced&&g.events.some(e=>e.type==='buddy'&&e.helper===q.seat&&at-e.at<300));pawn.classList.toggle('is-rising',pos.vy<-60);const landing=g.events.findLast(e=>e.type==='land'&&e.seat===q.seat);pawn.classList.toggle('is-landing',!!landing&&at-landing.at<120&&!u.reduced);pawn.classList.toggle('is-running',pos.grounded&&Math.abs(pos.vx)>20&&!u.reduced);pawn.classList.toggle('is-safe',q.invincibleUntil>at);pawn.classList.toggle('is-boost',q.boostUntil>at);u.cards[q.seat].classList.toggle('is-out',!q.alive);u.cards[q.seat].classList.toggle('is-goal',q.finishTime!=null);u.cards[q.seat].classList.toggle('is-watched',watch&&q.seat===focus.seat);u.cards[q.seat].disabled=!watch;
  put(u.status[q.seat],q.finishTime!=null?'GOAL!':!q.alive?(course.mode==='coop'?'救助待ち':'脱落'):q.respawnAt?'再スタート…':'♥'.repeat(q.lives)+'♡'.repeat(3-q.lives));put(u.ranks[q.seat],course.mode==='coop'?(q.finishTime!=null?'✓':'仲間'):rankOf(g,q)+'位');u.dots[q.seat].style.left=Math.min(100,q.furthest/course.goal*100)+'%';u.dots[q.seat].classList.toggle('is-out',!q.alive);
 }
 const rivals=g.players.filter(q=>q.playerId!==focus.playerId&&q.alive&&q.finishTime==null&&Math.abs(q.x-fp.x)>r.width/r.scale*.6).sort((a,b)=>b.x-a.x);const rivalHTML=rivals.map(q=>'<span style="--player:'+color(q)+'"><b>'+String(q.seat+1)+'P</b> '+(q.x>fp.x?'先行 ▶':'◀ 後方')+'</span>').join('');if(n.rivals.innerHTML!==rivalHTML)n.rivals.innerHTML=rivalHTML;n.rivals.hidden=busy||finish;
 if(course.mode==='coop'){for(const chip of n.mission.querySelectorAll('[data-ru-switch]'))chip.classList.toggle('is-open',g.switches.includes(chip.dataset.ruSwitch));put(n['mission-text'],'橋 '+g.switches.length+'/3 · ゴール '+g.players.filter(q=>q.finishTime!=null).length+'/4');}
 n.count.hidden=!busy;if(busy)n.count.innerHTML=`<small>READY TO RUN?</small><b>${Math.max(1,Math.ceil((g.startAt-at)/1000))}</b><span>◀ ▶ で移動 ＋ ジャンプ</span>`;
 const miss=g.events.findLast(e=>e.seat===p?.seat&&['miss','out'].includes(e.type)),waiting=p?.respawnAt>at;u.root.classList.toggle('is-hit',!!miss&&at-miss.at<280&&!u.reduced);n.message.hidden=!waiting&&!finish;if(waiting)n.message.innerHTML=`<small>あと ${p.lives} 回！</small><b>旗から、もう一度！</b><span>${miss?.cause==='steam'?'蒸気が止まるのを待つか、上を跳ぼう':miss?.cause==='enemy'?'敵は横から触れず、上から踏もう':'穴は長押しジャンプで越えよう'}</span>`;else if(finish)n.message.innerHTML='<small>FINISH!</small><b>冒険、おつかれさま！</b><span>結果を集計中…</span>';
 n.watchLabel.hidden=!watch;if(watch)put(n.watchLabel,`${p?.finishTime!=null?'ゴール！ ':p?(course.mode==='coop'?'救助待ち · ':'脱落 · '):''}${focus.name} を観戦中 · 上の顔で切り替え`);
 n.network.hidden=c.connected()&&at-g.serverAt<750;const can=active587(c);for(const b of u.buttons)b.disabled=!can;
 put(n.help,watch?'走る仲間を見届けよう！':p?.respawnAt?'チェックポイントから再開！':p?.wallSide?'壁に触れた！ ジャンプを押し直そう':'指を滑らせて左右 ＋ ジャンプ');put(n.note,watch?'上のプレイヤーを押すと観戦を切り替え':p?.boostUntil>at?'宝石の効果中 · いまが追い抜くチャンス！':'仲間を踏むと高く跳べる · 壁キックもOK');
 controlsTick587(c);
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(at-e.at>800)continue;const own=e.seat===p?.seat;if(e.type==='start'){sound543(u,'go');u.notice={text:'GO! 魔界を駆け抜けろ！',until:at+1200};}if(own){if(e.type==='jump')sound543(u,'launch');if(e.type==='wallkick'){sound543(u,'spring');u.notice={text:'壁キック！',until:at+650};}if(e.type==='buddy'){sound543(u,'spring');u.notice={text:'仲間ジャンプ！',until:at+1000};}if(e.type==='stomp'){sound543(u,'bump');u.notice={text:'ナイス踏みつけ！',until:at+900};}if(e.type==='spring')sound543(u,'spring');if(e.type==='boost'){sound543(u,'boost');u.notice={text:'スピードアップ！',until:at+1300};}if(e.type==='checkpoint'){sound543(u,'park');u.notice={text:'チェックポイント！',until:at+1400};}if(['miss','out'].includes(e.type))sound543(u,'fall');if(e.type==='respawn')u.renderer.snap=true;}if(e.type==='switch'){sound543(u,'park');u.notice={text:g.players[e.seat].name+' が橋をつないだ！',until:at+2000};}if(e.type==='rescue'){sound543(u,'park');u.notice={text:g.players[e.seat].name+' を救助！',until:at+1600};}if(e.type==='goal'){sound543(u,'edge');u.notice={text:(own?'あなた':g.players[e.seat].name)+' ゴール！ '+seconds(e.time)+'秒',until:at+2300};}}
 n.toast.hidden=!u.notice||at>u.notice.until||busy||waiting||finish;if(!n.toast.hidden)put(n.toast,u.notice.text);
}
export function runnersBefore587(c){const u=c.runnersUI587;if(!u)return;stop587(c);u.cleanup?.();u.cleanup=null;cancelAnimationFrame(u.raf);u.raf=null;u.root=null;}
export function runnersDispose587(c){runnersBefore587(c);c.runnersUI587?.audio?.close()?.catch(()=>{});if(c.runnersUI587)c.runnersUI587.audio=null;}
export function runnersAfter587(c){const root=c.root?.querySelector('.ru-play587');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;u.nodes=Object.fromEntries(['mission','mission-text','boost','boost-time','boost-bar','rivals','progress','field','canvas','world','section','time','stage','hint','count','message','network','toast','help','note','watch-label'].map(k=>[k,root.querySelector('[data-ru-'+k+']')]));u.nodes.watchLabel=u.nodes['watch-label'];u.nodes.boostTime=u.nodes['boost-time'];u.nodes.boostBar=u.nodes['boost-bar'];for(const [k,sel]of [['pawns','pawn'],['cards','card'],['status','status'],['ranks','rank'],['dots','dot']])u[k]=[...root.querySelectorAll('[data-ru-'+sel+']')];
 const abort=new AbortController(),on=(el,type,fn)=>el.addEventListener(type,fn,{signal:abort.signal}),zoom=lockPlayZoom498(root);u.renderer=board587(u.nodes.canvas);u.renderer.snap=true;const resize=()=>resize587(u.renderer,u.nodes.field.clientWidth,u.nodes.field.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.field);bind587(c,on);
 const tick=()=>{if(!u.root||document.hidden)return;update(c);u.raf=requestAnimationFrame(tick);};on(document,'visibilitychange',()=>{if(document.hidden){stop587(c);cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{});}else{c.refresh?.();if(u.raf==null)tick();}});u.cleanup=()=>{abort.abort();observer.disconnect();zoom();};runnersReceive587(c);tick();
}
export function runnersClick587(c,b){const d=b.dataset,g=game(c);if(!g||!Object.keys(d).some(k=>k.startsWith('ru')))return false;const u=ui(c);unlock543(u);if(d.ruCourse)c.raw('runners587',{gameId:g.id,kind:'course',courseId:d.ruCourse});if(d.ruMonster)c.raw('runners587',{gameId:g.id,kind:'select',monsterId:d.ruMonster});if(d.ruAction==='start')c.raw('runners587',{gameId:g.id,kind:'start'});if(d.ruAction==='more'){u.limit+=24;c.render();}if(d.ruWatch!=null){u.watch=Number(d.ruWatch);if(u.renderer)u.renderer.snap=true;}if(d.ruAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(u.sound)unlock543(u);else u.audio?.suspend()?.catch(()=>{});}return true;}
export function runnersInput587(c,e){if(e.name!=='runnersSearch587')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true;}
export const runnersKey587=key587;
