import {TOWER517 as C,shape517,landing517,BLOCK_COLORS517,fallSpeed517} from './Rules517.js';
export function block517(c,x,y,size,type,alpha=1){
 const color=BLOCK_COLORS517[type]??'#8ccab2',q=size/32;c.save();c.globalAlpha=alpha;c.translate(x,y);c.scale(q,q);
 c.fillStyle='#07120f';c.fillRect(0,0,32,32);let metal=c.createLinearGradient(0,0,32,32);metal.addColorStop(0,'#fff0b2');metal.addColorStop(.25,'#977544');metal.addColorStop(.65,'#463622');metal.addColorStop(1,'#d6b776');c.fillStyle=metal;c.fillRect(1,1,30,30);
 let face=c.createLinearGradient(4,3,28,30);face.addColorStop(0,color);face.addColorStop(.48,'#284442');face.addColorStop(1,'#0b2224');c.fillStyle=face;c.fillRect(4,4,24,24);
 c.fillStyle=color;c.globalAlpha=alpha*.36;c.beginPath();c.moveTo(4,4);c.lineTo(28,4);c.lineTo(23,9);c.lineTo(9,9);c.lineTo(9,23);c.lineTo(4,28);c.closePath();c.fill();c.globalAlpha=alpha;
 c.strokeStyle=color;c.lineWidth=1.1;c.beginPath();c.moveTo(16,9);c.lineTo(22,16);c.lineTo(16,23);c.lineTo(10,16);c.closePath();c.stroke();c.fillStyle='#e7ffff';c.fillRect(15,14,2,4);
 c.fillStyle='#ffedb9';for(const [a,b] of [[2,2],[28,2],[2,28],[28,28]])c.fillRect(a,b,2,2);c.fillStyle='#ffffff4c';c.fillRect(5,4,22,1);c.restore();
}
export function preview517(type,rotation=0){const cells=shape517(type,rotation),w=Math.max(...cells.map(c=>c[0]))+1,h=Math.max(...cells.map(c=>c[1]))+1,s=Math.min(19,44/h),color=BLOCK_COLORS517[type];return`<svg viewBox="0 0 88 48" aria-hidden="true">${cells.map(([x,y])=>{const a=(88-w*s)/2+x*s,b=(48-h*s)/2+(h-y-1)*s;return`<g><rect x="${a}" y="${b}" width="${s-1}" height="${s-1}" rx="1.5" fill="#183c36" stroke="#d3b77b" stroke-width="1"/><path d="M${a+2} ${b+2}h${s-5}l-3 3h-${s-11}v${s-8}l-3 2z" fill="${color}"/><rect x="${a+s*.34}" y="${b+s*.34}" width="${s*.3}" height="${s*.3}" fill="${color}"/></g>`}).join('')}</svg>`}
export function makeRenderer517(canvas){const ctx=canvas.getContext('2d',{alpha:false}),background=document.createElement('canvas'),bg=background.getContext('2d'),settled=document.createElement('canvas'),sc=settled.getContext('2d');const r={canvas,ctx,background,bg,settled,sc,width:0,height:0,boardRevision:-1,tiles:new Map()};if(typeof Image!=='undefined'){r.art=new Image();r.art.onload=()=>{if(!r.disposed&&r.width)resize517(r,r.width,r.height,r.dpr)};r.art.src=new URL('../../assets/tower518/arena.webp',import.meta.url).href}return r}
export function resize517(r,width,height,dpr=1){r.width=width;r.height=height;r.dpr=Math.min(1.5,dpr);for(const c of[r.canvas,r.background,r.settled]){c.width=Math.round(width*r.dpr);c.height=Math.round(height*r.dpr)}r.cell=Math.min((width-54)/C.width,(height-72)/C.height);r.left=(width-r.cell*C.width)/2;r.bottom=height-14;r.top=r.bottom-C.height*r.cell;const{bg:b}=r;b.setTransform(r.dpr,0,0,r.dpr,0,0);const gr=b.createLinearGradient(0,0,0,height);gr.addColorStop(0,'#204846');gr.addColorStop(.4,'#0d2425');gr.addColorStop(1,'#071212');b.fillStyle=gr;b.fillRect(0,0,width,height);if(r.art?.complete&&r.art.naturalWidth){b.drawImage(r.art,r.left-28,0,r.cell*10+56,height);b.fillStyle='#00120d55';b.fillRect(r.left,r.top,r.cell*10,r.cell*16)}
 const light=b.createRadialGradient(width*.5,0,0,width*.5,0,width*.8);light.addColorStop(0,'#b8e3c245');light.addColorStop(1,'#112c2300');b.fillStyle=light;b.fillRect(0,0,width,height);b.strokeStyle='#bfddab16';b.lineWidth=.8;
 for(let y=0;y<C.height;y++){const py=r.bottom-y*r.cell;b.beginPath();b.moveTo(r.left,py);b.lineTo(width-r.left,py);b.stroke();for(let x=0;x<C.width;x++){b.beginPath();b.moveTo(r.left+x*r.cell,py);b.lineTo(r.left+x*r.cell,py-r.cell);b.stroke()}}
 for(const x of[r.left-12,width-r.left+1]){const g=b.createLinearGradient(x,0,x+11,0);g.addColorStop(0,'#4e3823');g.addColorStop(.45,'#d0b073');g.addColorStop(.6,'#695936');g.addColorStop(1,'#2a2118');b.fillStyle=g;b.fillRect(x,r.top,11,height-r.top);for(let y=r.top;y<height;y+=r.cell*2){b.fillStyle='#e9ce8a';b.fillRect(x-2,y,15,4);b.fillStyle='#101f1c';b.fillRect(x+3,y+10,4,4)}}
 b.fillStyle='#745d37';b.fillRect(r.left-13,r.bottom,width-2*r.left+26,11);b.fillStyle='#e7c883';b.fillRect(r.left-13,r.bottom,width-2*r.left+26,2);
 b.save();b.setLineDash([4,5]);b.strokeStyle='#a7edd8aa';b.beginPath();b.moveTo(r.left,r.top);b.lineTo(width-r.left,r.top);b.stroke();b.restore();b.textAlign='center';b.font='700 10px sans-serif';b.fillStyle='#d8f5df';b.fillText('—  SKY GATE  /  脱出  —',width/2,r.top-10);r.boardRevision=-1;r.tiles.clear()}
function tile(r,type){if(!r.tiles.has(type)){const c=document.createElement('canvas'),d=r.dpr,s=r.cell;c.width=Math.ceil(s*d);c.height=Math.ceil(s*d);const ctx=c.getContext('2d');ctx.scale(d,d);block517(ctx,0,0,s,type);r.tiles.set(type,c)}return r.tiles.get(type)}
export function paint517(r,g,players,at,reduced=false){const{ctx:c,width:w,height:h,cell:s,left:l,bottom:b}=r;if(!w)return;c.setTransform(1,0,0,1,0,0);c.drawImage(r.background,0,0);if(r.boardRevision!==g.boardRevision){r.sc.setTransform(1,0,0,1,0,0);r.sc.clearRect(0,0,r.settled.width,r.settled.height);r.sc.setTransform(r.dpr,0,0,r.dpr,0,0);for(const t of g.board)r.sc.drawImage(tile(r,t.type),l+t.x*s,b-(t.y+1)*s,s,s);r.boardRevision=g.boardRevision}c.drawImage(r.settled,0,0);c.setTransform(r.dpr,0,0,r.dpr,0,0);
 const f=g.falling,aim=g.aim,cells=f?.cells??shape517(g.hand[aim?.slot??0],aim?.rotation??0),x=f?.x??aim?.x??0,land=f?.land??landing517(g,cells,x);if(g.phase==='play'||g.phase==='countdown'){c.fillStyle=f?'#ecb66710':'#cbe8cc0a';const cols=new Set(cells.map(v=>v[0]));for(const dx of cols)c.fillRect(l+(x+dx)*s,r.top,s,b-r.top);for(const[dx,dy]of cells){c.fillStyle='#f0d4a31a';c.fillRect(l+(x+dx)*s,b-(land+dy+1)*s,s,s);c.strokeStyle=f?'#e8bb7288':'#9cbcaf66';c.setLineDash([3,3]);c.strokeRect(l+(x+dx)*s+1,b-(land+dy+1)*s+1,s-2,s-2);c.setLineDash([])}}
 if(!f&&g.phase==='play'){c.globalAlpha=.65;const a=g.aim,shape=shape517(g.hand[a.slot],a.rotation);for(const [dx,dy] of shape)c.drawImage(tile(r,g.hand[a.slot]),l+(a.x+dx)*s,b-(16.15+dy+1)*s,s,s);c.globalAlpha=1}
 if(f){const lead=g.phase==='result'?0:Math.min(.1,Math.max(0,(at-g.serverAt)/1000)),speed=fallSpeed517(g.elapsed),y=Math.max(f.land,f.y-lead*speed);for(const[dx,dy]of f.cells){const px=l+(f.x+dx)*s,py=b-(y+dy+1)*s;if(!reduced){c.fillStyle=BLOCK_COLORS517[f.type]+'48';const tail=s*(.35+speed/15);c.fillRect(px+5,py-tail,s-10,tail);c.fillStyle='#fff5';c.fillRect(px+2,py-tail*.6,1,tail*.6)}c.drawImage(tile(r,f.type),px,py,s,s)}}
 for(const e of g.events){const age=g.elapsed+Math.max(0,at-g.serverAt)-e.at;if(age<0||age>850)continue;const t=age/850,x=l+(e.x??5)*s,y=b-(e.y??0)*s;if(e.type==='slam'||e.type==='crush'||e.type==='bounce'){c.globalAlpha=1-t;c.strokeStyle=e.type==='crush'?'#f7e5ca':e.type==='bounce'?'#abeddd':'#e8bb79';c.lineWidth=2*(1-t);c.beginPath();c.ellipse(x,y,(.15+t*1.9)*s,(.07+t*.4)*s,0,0,Math.PI*2);c.stroke();if(!reduced)for(let i=0;i<8;i++){const angle=i*Math.PI/4;c.fillStyle=i%2?'#ceb286':'#91bcac';c.fillRect(x+Math.cos(angle)*t*s*2,y-Math.abs(Math.sin(angle))*t*s*1.4+t*t*s,3*(1-t)+1,3*(1-t)+1)}c.globalAlpha=1}}
 if(!reduced){c.fillStyle='#fce9a54d';for(let i=0;i<9;i++){const x=l+((i*37)%100)/100*C.width*s,y=(h-((at/70+i*71)%h));c.fillRect(x,y,1.5,1.5)}}
 return{cell:s,left:l,bottom:b};}
