// Server-authoritative, fixed-step platformer. Units are one square block; y points up.
import {impossible518} from './Reachability518.js';
import {freezeColors501} from '../party/GameColors501.js';
export const TOWER517=Object.freeze({width:10,height:16,duration:150000,step:1000/60,gravity:25,jump:Math.sqrt(2*25*2.16),pw:.60,ph:.82,speed:3.7,dashSpeed:8.2,dashMs:180,dashCooldown:1150,autoDrop:2200,countdown:3000});
export const SHAPES517=Object.freeze({I:[[0,0],[1,0],[2,0],[3,0]],O:[[0,0],[1,0],[0,1],[1,1]],T:[[0,0],[1,0],[2,0],[1,1]],L:[[0,0],[1,0],[2,0],[2,1]],J:[[0,0],[1,0],[2,0],[0,1]],S:[[0,0],[1,0],[1,1],[2,1]],Z:[[1,0],[2,0],[0,1],[1,1]]});
export const BLOCK_COLORS517={I:'#73ceda',O:'#e4b663',T:'#bb94e7',L:'#f29a64',J:'#799feb',S:'#80cf9d',Z:'#e58295'};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const overlap=(a,b,c,d)=>a<d-1e-6&&b>c+1e-6;
export function shape517(type,rotation=0){let cells=(SHAPES517[type]??SHAPES517.O).map(c=>[...c]);for(let i=0;i<((rotation%4)+4)%4;i++){cells=cells.map(([x,y])=>[-y,x]);const minX=Math.min(...cells.map(c=>c[0])),minY=Math.min(...cells.map(c=>c[1]));cells=cells.map(([x,y])=>[x-minX,y-minY])}return cells}
export function random517(g,n){let x=g.seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;g.seed=x>>>0;return g.seed%n}
const draw=g=>Object.keys(SHAPES517)[random517(g,7)];
export function makeTower517({id,code,partyId,hostId,members,now=0}){return{id,code,game:'tower',rules517:2,partyId462:partyId,hostId,phase:'lobby',revision:0,createdAt:now,updatedAt:now,members:members.map(m=>({...m,preference:'random'})),roleMode:'preference',players:[],board:[],events:[],eventSeq:0,boardRevision:0,elapsed:0,seed:1}}
export function startTower517(g,now,seed=1){if(g.phase!=='lobby')return false;g.seed=seed>>>0||1;while(g.members.length<4){const seat=g.members.length,sp=['slime','wolf','goblin','skeleton'][seat];g.members.push({playerId:`AI-${g.id}-${seat}`,name:`AI ${seat+1}`,ai:true,choice:{id:'ai-'+seat,speciesId:sp},preference:'random'})}freezeColors501(g.members,[],g.aiColors500??{});
 let candidates=g.members.filter(m=>m.playerId===g.roleMode);if(g.roleMode==='ai')candidates=g.members.filter(m=>m.ai);if(!candidates.length&&g.roleMode==='preference'){candidates=g.members.filter(m=>m.preference==='drop');if(!candidates.length)candidates=g.members.filter(m=>m.preference!=='run')}if(!candidates.length)candidates=g.members;
 g.dropperId=candidates[random517(g,candidates.length)].playerId;let runner=0;g.players=g.members.map((m,seat)=>({playerId:m.playerId,name:m.name,seat,ai:!!m.ai,color499:m.color499,speciesId:m.choice.speciesId,role:m.playerId===g.dropperId?'drop':'run',alive:true,escaped:false,x:m.playerId===g.dropperId?5:2+runner++*3,y:0,vx:0,vy:0,facing:1,grounded:true,support:null,coyote:0,jumpUntil:0,dashUntil:0,dashReady:0,lastSeq:0,maxHeight:0,auto:!!m.ai}));g.hand=Array.from({length:4},()=>draw(g));g.aim={slot:0,rotation:0,x:3};g.board=[];g.boardRevision=0;g.events=[];g.eventSeq=0;g.falling=null;g.dropSerial=0;g.elapsed=0;g.startAt=now+TOWER517.countdown;g.deadline=g.startAt+TOWER517.duration;g.lastAt=now;g.phaseAt=now;g.phase='countdown';g.nextDropAt=0;g.autoAt=TOWER517.autoDrop;g.revision++;return true}
export function aim517(g,slot,rotation,x){if(!Number.isInteger(slot)||slot<0||slot>3||!Number.isInteger(rotation)||!Number.isFinite(x))return false;const cells=shape517(g.hand[slot],rotation),width=1+Math.max(...cells.map(c=>c[0]));g.aim={slot,rotation:((rotation%4)+4)%4,x:clamp(Math.round(x),0,TOWER517.width-width)};return true}
export function landing517(g,cells,x){let y=0;for(const [dx,dy]of cells)for(const b of g.board)if(b.x===x+dx)y=Math.max(y,b.y+1-dy);return Math.max(0,y)}
function event(g,type,data={}){g.events.push({id:++g.eventSeq,type,at:g.elapsed,...data});if(g.events.length>32)g.events.shift()}
export const fallSpeed517=elapsed=>3.5+20.5*Math.pow(clamp(elapsed/TOWER517.duration,0,1),1.65);
export const dropGap518=elapsed=>450-270*clamp(elapsed/TOWER517.duration,0,1);
export const aimTime518=elapsed=>2200-1100*clamp(elapsed/TOWER517.duration,0,1);
export function fits517(g,cells,x){const y=landing517(g,cells,x);return cells.every(([,dy])=>y+dy+1<=TOWER517.height)}
function autoDrop517(g){if(drop517(g))return true;const start=g.aim.slot;for(let i=0;i<4;i++)for(let rot=0;rot<4;rot++){const slot=(start+i)%4,cells=shape517(g.hand[slot],rot),w=1+Math.max(...cells.map(c=>c[0]));for(let x=0;x<=10-w;x++)if(fits517(g,cells,x)){aim517(g,slot,rot,x);return drop517(g)}}g.autoAt=g.elapsed+500;return false}
export function drop517(g){if(g.phase!=='play'||g.falling||g.elapsed<g.nextDropAt)return false;aim517(g,g.aim.slot,g.aim.rotation,g.aim.x);const {slot,rotation,x}=g.aim,type=g.hand[slot],cells=shape517(type,rotation),land=landing517(g,cells,x);if(!fits517(g,cells,x))return false;g.falling={id:++g.dropSerial,type,rotation,x,y:Math.max(TOWER517.height+2,land+3),land,cells};g.hand[slot]=draw(g);aim517(g,slot,0,x);event(g,'release',{x:x+1,y:g.falling.y});return true}
export function solid517(g,x,y,includeFalling=true){if(x-TOWER517.pw/2<0||x+TOWER517.pw/2>TOWER517.width||y<-.001)return true;const left=x-TOWER517.pw/2,right=x+TOWER517.pw/2,top=y+TOWER517.ph;for(const b of g.board)if(overlap(left,right,b.x,b.x+1)&&overlap(y,top,b.y,b.y+1))return true;if(includeFalling&&g.falling)for(const [dx,dy]of g.falling.cells){const bx=g.falling.x+dx,by=g.falling.y+dy;if(overlap(left,right,bx,bx+1)&&overlap(y,top,by,by+1))return true}return false}
function surface(g,p,x=p.x){let height=0,support=null;const left=x-TOWER517.pw/2,right=x+TOWER517.pw/2;for(const b of g.board)if(overlap(left,right,b.x,b.x+1)&&b.y+1<=p.y+.035&&b.y+1>height)height=b.y+1;
 for(const o of g.players)if(o!==p&&o.role==='run'&&o.alive&&!o.escaped&&overlap(left,right,o.x-TOWER517.pw/2,o.x+TOWER517.pw/2)&&o.y+TOWER517.ph<=p.y+.045&&o.y+TOWER517.ph>height){height=o.y+TOWER517.ph;support=o.playerId}return{height,support}}
export function kill517(g,p){if(!p.alive)return;p.alive=false;p.vx=0;p.vy=0;p.deadAt=g.elapsed;event(g,'crush',{playerId:p.playerId,x:p.x,y:p.y+.4})}
export function finish517(g,winner,reason){if(g.phase==='result')return;g.phase='result';g.winner=winner;g.reason=reason;g.phaseAt=g.lastAt;g.finale518={at:g.lastAt,until:g.lastAt+5400,escapeId:g.players.find(p=>p.escaped)?.playerId??null};g.results=g.players.map(p=>({playerId:p.playerId,winner:p.role===winner,role:p.role,escaped:p.escaped,alive:p.alive,maxHeight:p.maxHeight}));g.revision++;event(g,'finish',{winner})}
function moveRunner(g,p,input,dt){const C=TOWER517;if(!p.alive||p.escaped)return;const prevY=p.y;const s=surface(g,p);p.grounded=Math.abs(p.y-s.height)<.05&&p.vy<=0;p.support=p.grounded?s.support:null;if(p.grounded)p.coyote=g.elapsed+100;
 if(input?.jump)p.jumpUntil=g.elapsed+160;
 if(input?.dash&&g.elapsed>=p.dashReady){p.dashUntil=g.elapsed+C.dashMs;p.dashReady=g.elapsed+C.dashCooldown;event(g,'dash',{playerId:p.playerId,x:p.x,y:p.y})}
 if(p.jumpUntil>=g.elapsed&&p.jumpUntil>0&&(p.grounded||p.coyote>=g.elapsed)){if(p.support){const under=g.players.find(o=>o.playerId===p.support);if(under&&!under.grounded){under.vy=Math.min(under.vy,-2.4);under.coyote=-1}event(g,'bounce',{playerId:p.playerId,x:p.x,y:p.y})}else event(g,'jump',{playerId:p.playerId,x:p.x,y:p.y});p.vy=C.jump;p.jumpUntil=0;p.coyote=-1;p.grounded=false;p.support=null}
 const axis=clamp(Number(input?.axis)||0,-1,1);if(Math.abs(axis)>.1)p.facing=Math.sign(axis);p.vx=g.elapsed<p.dashUntil?p.facing*C.dashSpeed:axis*C.speed;
 const nx=clamp(p.x+p.vx*dt,C.pw/2,C.width-C.pw/2);if(!solid517(g,nx,p.y))p.x=nx;else if(p.grounded&&!solid517(g,nx,p.y+.20)){p.x=nx;p.y+=.20}else p.vx=0;
 p.vy-=C.gravity*dt;const ny=p.y+p.vy*dt;
 if(p.vy<=0){const ground=surface(g,p);if(ny<=ground.height&&p.y>=ground.height-.04){p.y=ground.height;p.vy=0;p.grounded=true;p.support=ground.support;p.coyote=g.elapsed+100}else if(!solid517(g,p.x,ny)){p.y=ny;p.grounded=false}else{p.vy=0}}
 else if(!solid517(g,p.x,ny)){p.y=ny;p.grounded=false}else{p.vy=0;p.coyote=-1}
 p.y=Math.max(0,p.y);p.maxHeight=Math.max(p.maxHeight,p.y);if(p.y>=C.height){p.escaped=true;p.alive=true;event(g,'escape',{playerId:p.playerId,x:p.x,y:p.y});finish517(g,'run','escape')}
 if(!Number.isFinite(p.y)||Math.abs(p.y-prevY)>2){p.y=Math.max(0,prevY);p.vy=0}
}
function fallStep(g,dt){const f=g.falling;if(!f)return;const oldY=f.y;f.y=Math.max(f.land,f.y-fallSpeed517(g.elapsed)*dt);
 // Swept underside contact: push down only by actual travel, then kill only if solid space is exhausted.
 for(const p of g.players){if(p.role!=='run'||!p.alive||p.escaped)continue;let ceiling=Infinity;
  for(const[dx,dy]of f.cells){const x=f.x+dx,oldBottom=oldY+dy,newBottom=f.y+dy;if(overlap(p.x-TOWER517.pw/2,p.x+TOWER517.pw/2,x,x+1)&&p.y<oldBottom&&p.y+TOWER517.ph>newBottom+1e-6)ceiling=Math.min(ceiling,newBottom-TOWER517.ph)}
  if(ceiling<Infinity){if(ceiling<-.0001||solid517(g,p.x,ceiling,false))kill517(g,p);else{p.y=ceiling;p.vy=Math.min(0,p.vy);p.coyote=-1}}
 }
 if(f.y===f.land){for(const[dx,dy]of f.cells)g.board.push({x:f.x+dx,y:f.land+dy,type:f.type});g.boardRevision++;event(g,'slam',{x:f.x+1.5,y:f.land});g.falling=null;g.nextDropAt=g.elapsed+dropGap518(g.elapsed);g.autoAt=g.nextDropAt+aimTime518(g.elapsed);for(const p of g.players)if(p.role==='run'&&p.alive&&solid517(g,p.x,p.y,false))kill517(g,p)}
}
export function botRunner517(g,p){if(!p.alive)return{axis:0};const danger=g.falling?.cells.filter(([dx])=>Math.abs(g.falling.x+dx+.5-p.x)<1.1)??[];if(danger.length&&g.falling.y<p.y+4){const f=g.falling,center=f.x+(Math.max(...f.cells.map(c=>c[0]))+1)/2;const axis=p.x<center?(p.x>.6?-1:1):(p.x<9.4?1:-1);return{axis,dash:g.falling.y<p.y+3,jump:p.grounded&&solid517(g,p.x+axis*.45,p.y,false)}}
 if(g.elapsed>=(p.botNext??0)){p.botNext=g.elapsed+350;const options=[];for(let x=.5;x<10;x++){const q={...p,y:p.y+2.12},s=surface(g,q,x);if(s.height<=p.y+2.12&&Math.abs(x-p.x)<3.8&&!solid517(g,x,s.height,false)){let blocked=false;for(let probe=p.x;Math.abs(probe-x)>.2;probe+=Math.sign(x-p.x)*.2){if(solid517(g,probe,p.y+2.02,false)){blocked=true;break}}if(blocked)continue;const dangerX=g.falling?.cells.some(([dx])=>Math.abs(g.falling.x+dx+.5-x)<.8);options.push({x,h:s.height,score:s.height*3-Math.abs(x-p.x)*.28-(dangerX?7:0)+(random517(g,10)/35)})}}options.sort((a,b)=>b.score-a.score);p.botTarget=options[0]?.x??p.x}
 const axis=Math.abs((p.botTarget??p.x)-p.x)>.15?Math.sign(p.botTarget-p.x):0;const target=surface(g,{...p,y:p.y+2.12},p.botTarget??p.x).height;const wall=solid517(g,p.x+axis*.42,p.y,false);return{axis,jump:p.grounded&&(target>p.y+.1||wall||g.elapsed>(p.botJump??0)&&(p.botJump=g.elapsed+900+random517(g,800))),dash:false}}
function botDrop(g){if(g.falling||g.elapsed<g.nextDropAt)return;if(g.elapsed<(g.botDropAt??0))return;const alive=g.players.filter(p=>p.role==='run'&&p.alive);const target=alive[random517(g,Math.max(1,alive.length))];if(!target)return;let best=null;for(let slot=0;slot<4;slot++)for(let rot=0;rot<4;rot++){const cells=shape517(g.hand[slot],rot),w=Math.max(...cells.map(c=>c[0]))+1;for(let x=0;x<=10-w;x++){const land=landing517(g,cells,x);if(!fits517(g,cells,x))continue;const near=cells.some(([dx])=>Math.abs(x+dx+.5-target.x)<.7),score=(near?2.2:0)-Math.abs(x+w/2-target.x)*.15-land*.70+random517(g,100)/45;if(!best||score>best.score)best={slot,rot,x,score}}}if(!best){g.botDropAt=g.elapsed+500;return}aim517(g,best.slot,best.rot,best.x);drop517(g);g.botDropAt=g.elapsed+1800-900*clamp(g.elapsed/TOWER517.duration,0,1)}
export function advanceTower517(g,now,inputs=new Map(),autoIds=new Set()){
 if(!['countdown','play'].includes(g.phase))return false;if(now<g.startAt){g.lastAt=now;return false}if(g.phase==='countdown'){g.phase='play';g.lastAt=g.startAt;g.revision++}
 // Stall/restart pauses, rather than simulating unseen fatal seconds.
 if(now-g.lastAt>500){const delay=now-g.lastAt-100;g.startAt+=delay;g.deadline+=delay;g.lastAt+=delay}
 let steps=0;while(g.lastAt+TOWER517.step<=now+.001&&g.phase==='play'&&steps++<30){g.lastAt+=TOWER517.step;g.elapsed=g.lastAt-g.startAt;
  for(const p of g.players){p.auto=p.ai||autoIds.has(p.playerId);if(p.role==='run'){const input=p.auto?botRunner517(g,p):inputs.get(p.playerId);moveRunner(g,p,input,TOWER517.step/1000);if(input&&!p.auto){input.jump=false;input.dash=false}}}
  if(g.phase==='result')break;fallStep(g,TOWER517.step/1000);const blocked=impossible518(g);if(blocked){finish517(g,'drop',blocked);break}const dp=g.players.find(p=>p.role==='drop');if(dp.auto)botDrop(g);if(!g.falling&&g.elapsed>=g.autoAt)autoDrop517(g);
  if(g.players.filter(p=>p.role==='run').every(p=>!p.alive))finish517(g,'drop','crushed');else if(g.elapsed>=TOWER517.duration)finish517(g,'drop','timeout');
 }
 g.updatedAt=now;return steps>0;
}
export function publicTower517(g,connected=()=>true){const simple=p=>{const{botNext,botTarget,botJump,...out}=p;return out};return{id:g.id,code:g.code,game:'tower',rules517:2,hostId:g.hostId,partyId462:g.partyId462,phase:g.phase,revision:g.revision,roleMode:g.roleMode,dropperId:g.dropperId,members:g.members.map(m=>({playerId:m.playerId,name:m.name,ai:!!m.ai,color499:m.color499,choice:m.choice,preference:m.preference,connected:m.ai||!!connected(m.playerId),departed:!!m.departed})),players:g.players.map(simple),board:g.board.map(b=>({...b})),boardRevision:g.boardRevision,hand:g.hand?[...g.hand]:[],aim:g.aim?{...g.aim}:null,falling:g.falling?{...g.falling,cells:g.falling.cells.map(c=>[...c])}:null,elapsed:g.elapsed,startAt:g.startAt,deadline:g.deadline,nextDropAt:g.nextDropAt,autoAt:g.autoAt,dropSerial:g.dropSerial,events:g.events.map(e=>({...e})),winner:g.winner,reason:g.reason,finale518:g.finale518?{...g.finale518}:null,results:g.results,serverAt:g.lastAt}}
export function towerSignature517(g){if(!g)return null;return['lobby','result'].includes(g.phase)?g:{id:g.id,phase:'play',players:g.players.map(p=>[p.playerId,p.speciesId,p.role,p.color499])}}
// Also used for local movement prediction; authoritative outcomes remain server-only.
export {moveRunner as predictRunner517};
