import {parking557} from './Parking557.js';
import {COURSES556,courseById556} from './Courses556.js';
import {CART543 as C,clamp543,score543} from './Rules543.js';
import {course544,parkingBonus544} from './Courses544.js';
import {renderer543,resize543,paint543} from './Renderer543.js';
import {unlock543,sound543} from './Audio543.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {playerColor499} from '../party/PartyColors499.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
import {bindSling547,cancelPull547,slingKey547} from './Controls547.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.cartUI543??={seq:0,sound:true,seen:0,limit:24,search:''};
const me=c=>c.state?.cart?.players.find(p=>p.playerId===c.transport.selfId),clock=c=>Date.now()+(c.offset??0),color=p=>playerColor499(p).hex;
function pic(c,p){const species=p.speciesId??p.choice?.speciesId,i=['slime','wolf','goblin','skeleton'].indexOf(species);return i<0?c.sgMonster463?.(species)??'':`<span class="sg-monster ct-avatar543" role="img" aria-label="${['スライム','ウルフ','ゴブリン','スケルトン'][i]}" style="background-position:${i%2*100}% ${Math.floor(i/2)*100}%"></span>`}
const head=c=>`<header class="ct-head543"><button data-party-action462="browse" aria-label="パーティーへ">‹</button><div><small>ABYSS · RUNAWAY CARTS</small><b>暴走ショッピングカート</b></div><button data-ct-action="sound">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),party=c.state.party,pm=party?.members.find(p=>p.playerId===c.transport.selfId),member=g.members.find(p=>p.playerId===c.transport.selfId),host=g.hostId===c.transport.selfId,list=c.roster().filter(p=>!u.search||(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??'').includes(u.search));
 return`<section class="ct543 ct-lobby543">${head(c)}<div class="ct-cover543"><span>止まったからって、安心するな。</span><h1>帰ってこい！<br>暴走カート。</h1><p>ブレーキ？ ついてません。<br>押したあとは、祈るだけ。</p></div><div class="ct-body543"><div class="ct-facts543"><span>４人で大事故</span><span>全５回 · コース毎回抽選</span><span>空席はAI</span></div><h2>完璧な駐車に、後ろから誰か。</h2><div class="ct-rules543"><article><em>01</em><div><b>引いて、離して発進！</b><p>コースのどこからでも、飛ばしたい方向と逆へ引こう。引く長さで強さが決まり、離すと発進！ 左右の壁で反射して荷物をよけよう。元の位置へ戻せばキャンセル。方向と力加減を見て、止まる場所は自分の感覚で狙おう。8.5秒で自動発進。</p></div></article><article><em>02</em><div><b>12コースから、毎回ランダム！</b><p>奥ほど基本点UP、金枠に収まれば＋50点！ その先も＋50点を維持し、崖に近づくほどさらに最大＋50点。通常回は最大200点、最終回は最大400点！ 海へはみ出したら、その回は０点。海辺・氷の港・蒸気工場・夜の市場。12種類から５コースを抽選し、同じ試合では被らない。滑る床、横向き・逆向きベルト、ばね樽で狙い方が変わる！</p></div></article><article><em>03</em><div><b>その神駐車、まだ仮です。</b><p>発進前の車にもぶつかる！ 押されている最中も引いて離せば、その勢いに加速を上乗せ！ MAXは大暴走。止まった車にも追突する！ 押し戻されれば減点、落とされれば０点！ 全車が止まってから採点。全５回の合計で勝負、最後の回は得点２倍。同点は同順位。</p></div></article></div><details class="ct-courses556"><summary>12コースを見る</summary><div>${COURSES556.map(q=>`<article style="--course:${q.color}"><b>${esc(q.name)}</b><p>${esc(q.hint)}</p></article>`).join('')}</div></details><h2>今日の運転手</h2><input name="cartSearch543" placeholder="相棒の名前で探す" aria-label="相棒を探す" value="${esc(u.search)}"><div class="ct-roster543">${list.slice(0,u.limit).map(p=>`<button data-ct-monster="${esc(p.id)}" aria-pressed="${member?.choice?.id===p.id}">${pic(c,{speciesId:p.raceSpeciesId??p.speciesId})}<small>${esc(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??p.speciesId)}</small></button>`).join('')}</div>${list.length>u.limit?'<button data-ct-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="ct-error543" role="alert">${esc(c.error)}</p><button class="ct-gold543 ct-wide543" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="ct-gold543 ct-wide543" data-ct-action="start" ${!c.ready()||party.members.some(p=>!p.ready||!p.connected||p.atHome)?'disabled':''}>いざ、ノーブレーキ！</button>`:'<p>全員の準備ができたら、部屋主が開始します。</p>'}<p class="ct-note543">相棒による性能差なし。全５回、最後は得点２倍。スタート位置は毎回交代。時間切れは自動発進。切断・ホーム滞在中はAIが代わりに押します。</p></div></section>`;
}
function play(c,g){return`<section class="ct543 ct-play543 ct-play547 ct-play548 ct-play549 ct-play556 ct-play557">${head(c)}<div class="ct-players543">${g.players.map(p=>`<article data-ct-seat="${p.seat}" style="--player:${color(p)}"><span>${pic(c,p)}</span><b>${p.playerId===c.transport.selfId?'▼ あなた':esc(p.name)}</b><strong data-ct-score="${p.seat}">0<small>点</small></strong><small data-ct-status="${p.seat}">発進待ち</small></article>`).join('')}</div><div class="ct-round543"><span data-ct-round>ROUND 1 / 5</span><div data-ct-dots>${'<i></i>'.repeat(5)}</div><strong data-ct-time>8.5<small>秒</small></strong></div><div class="ct-stage543" data-ct-stage data-ct-sling><canvas data-ct-canvas tabindex="0" role="img" aria-label="海辺のマーケット。金枠で50点ボーナス。その先は崖へ近づくほど増え、合計最大200点。12コースから重複なしで毎回抽選。床やベルト、障害物を見て狙ってください。海へ落ちると０点。全車が止まるまで得点は仮です。"></canvas><div class="ct-stage-title543"><small data-ct-course-label>SUNSHINE MARKET</small><b data-ct-danger>はじめての坂</b><em data-ct-course-hint>金枠でピタッと ＋50点</em></div><div class="ct-pawns543">${g.players.map(p=>`<div class="ct-pawn543" data-ct-pawn="${p.seat}" style="--player:${color(p)}"><span>${pic(c,p)}</span><b>${p.playerId===c.transport.selfId?'YOU':esc(p.name)}</b></div>`).join('')}</div><div class="ct-overlay543" data-ct-overlay><small data-ct-overlaylabel>ブレーキ、ありません。</small><strong data-ct-overlaytitle>3</strong><span data-ct-overlaysub>引いて → 離して発進！</span><div class="ct-round-results543" data-ct-roundresults></div></div><div class="ct-notice543" data-ct-notice aria-live="polite" hidden></div><div class="ct-network543" data-ct-network hidden>再接続中… AIが代わりに押すよ</div></div><footer class="ct-controls543 ct-sling-controls547" data-ct-sling tabindex="0" role="group" aria-label="引っ張り操作。飛ばしたい方向と逆へ引き、離すと発進。元の位置へ戻すとキャンセル。キーボードは上下で強さ、左右で方向、Enterで発進。"><div class="ct-power-title543"><b data-ct-help>引いて、離して発進！</b><span data-ct-power>力加減</span></div><div class="ct-meter543" data-ct-meter role="meter" aria-label="引っ張る強さ" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i data-ct-fill></i><span>そっと</span><span>引き加減</span><span>全力</span></div><p data-ct-footnote>画面のどこでも、飛ばす方向と逆へ引く</p></footer></section>`}
function result(c,g){const winners=g.results.filter(r=>r.rank===1);return`<section class="ct543 ct-result543">${head(c)}<div class="ct-result-hero543"><small>RUNAWAY CARTS · FINAL PARKING</small><h1>${g.winnerIds.includes(c.transport.selfId)?'駐車の神、降臨。':'全員、よく帰ってきた。'}</h1><div class="ct-winners543">${winners.map(r=>{const p=g.players[r.seat];return`<div style="--player:${color(p)}">${pic(c,p)}<b>${esc(p.name)}</b><strong>${p.score}<small>点</small></strong></div>`}).join('')}</div><p>カートは、所定の場所へお戻しください。</p></div><div class="ct-body543">${resultActions490(c)}<div class="ct-results543">${g.results.map(r=>{const p=g.players[r.seat];return`<article style="--player:${color(p)}"><strong>${r.rank}</strong><span>${pic(c,p)}</span><div><b>${esc(r.name)}</b><small>金枠 ${r.perfects??0}回 · キワ ${r.edgeParks557??0}回 · 接触 ${r.bumps}回 · 場外 ${r.falls}回</small></div><b>${r.score}<small>点</small></b></article>`}).join('')}</div><div class="ct-history543"><h2>本日の駐車記録</h2><ol class="ct-course-history556">${g.history.map(h=>`<li><span>${h.round===5?'⑤ ×2':h.round+'回'}</span>${esc(courseById556(h.courseId556)?.name??'旧コース')}</li>`).join('')}</ol><table><thead><tr><th>運転手</th>${g.history.map(h=>`<th>${h.round===5?'⑤×2':h.round+'回'}</th>`).join('')}</tr></thead><tbody>${g.players.map(p=>`<tr style="--player:${color(p)}"><th>${esc(p.name)}</th>${g.history.map(h=>{const r=h.results.find(r=>r.seat===p.seat);return`<td>${r.fallen?'場外':(r.parking557==='edge'?'◆ ':r.bonus?'★ ':'')+r.points}</td>`}).join('')}</tr>`).join('')}</tbody></table></div><p class="ct-note543">５回の合計点で順位決定。同点なら同順位。★は金枠、◆はキワ停め。点数はボーナス込み。場外でも、前の回の得点は残るよ。</p></div></section>`}
export function cartView543(c){const g=c.state.cart,u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,search:'',limit:24,previous:null,notice:null,pull547:null,pointer547:null,pending547:null,round:null});return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
export function cartReceive543(c){const g=c.state?.cart;if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.round!==g.round){cancelPull547(c,false);u.round=g.round;u.aim545=p?.aim545??0;u.pending547=null;u.previous=null;u.roundResultKey=null;u.notice=null}if(p?.launched||p?.fallenAt!=null||g.phase!=='play'){cancelPull547(c,false);u.pending547=null}u.receivedAt=performance.now()}
export function cartFrame543(c,m){const g=c.state?.cart;if(m.selfId!==c.transport.selfId||!g||m.cart?.id!==g.id||m.cart.serverAt<g.serverAt)return;ui(c).previous=g;c.offset=m.serverNow-Date.now();c.state.cart=m.cart;cartReceive543(c);if((g.phase==='result')!==(m.cart.phase==='result'))c.render()}
function putScore549(e,value){if(e.dataset.value===String(value))return;e.dataset.value=String(value);e.replaceChildren(document.createTextNode(String(value)),Object.assign(document.createElement('small'),{textContent:'点'}))}
const put=(e,s)=>{if(e&&e.textContent!==String(s))e.textContent=String(s)};
function paint(c){const u=ui(c),g=c.state.cart,p=me(c),n=u.nodes,at=clock(c),data=paint543(u.renderer,g,c.transport.selfId,u,at);if(!data)return;const elapsed=data.elapsed,left=Math.max(0,(C.launchWindow-elapsed)/1000);put(n.round,`ROUND ${g.round} / 5${g.multiplier===2?' · ２倍':''}`);put(n.time,g.phase==='play'?(g.players.every(p=>p.launched||p.fallenAt!=null)?'見守れ！':left.toFixed(1)+'秒'):'');[...n.dots.children].forEach((e,i)=>e.classList.toggle('is-on',i<g.round));
 const pull=u.pull547,percent=clamp543((p?.launched?p.power:u.pending547?.power??pull?.power??0)*100||0,0,100);put(n.power,percent===0?'力加減':percent<32?'そっと':percent<70?'しっかり':'全力');n.fill.style.transform=`scaleX(${percent/100})`;n.meter.setAttribute('aria-valuenow',Math.round(percent));n.meter.classList.toggle('is-full',percent>=97);
 u.root.classList.toggle('is-summary549',g.phase==='intermission');u.root.classList.toggle('is-countdown549',g.phase==='countdown');
 u.root.classList.toggle('is-pulling547',!!pull?.active);u.root.style.setProperty('--pull-color',p?color(p):'#ffe6a4');
 if(g.phase==='intermission')put(n.help,p?`今回 ＋${p.roundScore}点`:'採点完了');else if(p?.fallenAt!=null)put(n.help,'場外！ この回は０点');else if(p?.launched)put(n.help,p.fallenAt!=null?'場外！ この回は０点😂':Math.hypot(p.vx,p.vy)<.06?`${parking557(p).kind==='edge'?'◆ キワ停め！ ':parkingBonus544(p)?'★ 金枠！ ':''}仮 ${score543(p)*g.multiplier}点。`:'発進！ あとは見守れ！');
 else put(n.help,u.pending547?'発進中…':!p?'観戦中':pull?.active?'離して、勝負。':pull?'そのまま引いてみよう':Math.hypot(p?.vx??0,p?.vy??0)>.1?'押されていても発射できる！':'引いて、離す。');
 const course=course544(g);put(n.danger,course.name);put(n['course-label'],course.label);put(n['course-hint'],course.hint);n.danger.parentElement.style.setProperty('--course',course.color);put(n.footnote,g.phase==='intermission'?'全車停止。今回の得点が確定！':p?.launched?`金枠＋${50*g.multiplier} · 崖際ほど最大${200*g.multiplier}点 · 落下０点`:pull?'元の位置へ戻すとキャンセル':'飛ばす方向と逆へ引く · 止める場所は感覚で' );
 for(const player of g.players){const v=u.renderer.points.find(q=>q.seat===player.seat),node=u.pawns[player.seat];if(v){node.hidden=!v.visible;node.style.transform=`translate(${v.x}px,${v.y}px) rotate(${v.angle}rad) scale(${v.scale})`;node.style.opacity=v.alpha;node.style.zIndex=String(Math.round(v.y+1000));node.style.setProperty('--size',clamp543(u.renderer.width*.10,27,45)+'px')}putScore549(u.scores[player.seat],player.score);put(u.statuses[player.seat],player.fallenAt!=null?'場外！':g.phase==='intermission'?`＋${player.roundScore}点`:player.launched?Math.hypot(player.vx,player.vy)<.06?`${parking557(player).kind==='edge'?'◆ ':parkingBonus544(player)?'★ ':''}仮 ${score543(player)*g.multiplier}点`:'暴走中！':player.playerId===c.transport.selfId&&u.pending547?'発進中…':player.charging||player.playerId===c.transport.selfId&&u.pull547?.active?'引いてる…':Math.hypot(player.vx,player.vy)>.1?'押されてる！':'発進待ち');u.cards[player.seat].classList.toggle('is-out',player.fallenAt!=null);u.cards[player.seat].classList.toggle('is-perfect',parkingBonus544(player)>0);u.cards[player.seat].classList.toggle('is-edge557',parking557(player).kind==='edge')}
 n.overlay.hidden=g.phase==='play';n.roundresults.hidden=g.phase!=='intermission';if(g.phase==='countdown'){put(n.overlaylabel,`ROUND ${g.round} · ${course.name}${g.round===5?' · 得点２倍！':''}`);put(n.overlaytitle,Math.max(1,Math.ceil((g.roundAt-at)/1000)));put(n.overlaysub,course.hint)}
 if(g.phase==='intermission'){put(n.overlaylabel,'PARKING COMPLETE');put(n.overlaytitle,'停車完了！');put(n.overlaysub,`金枠＋${50*g.multiplier}。その先は、崖に近いほど高得点！`);if(u.roundResultKey!==g.round){u.roundResultKey=g.round;n.roundresults.innerHTML=g.players.map(q=>`<div class="${parkingBonus544(q)?'is-gold':''}" style="--player:${color(q)}"><b>${esc(q.name)}</b><strong>＋${q.roundScore}<small>点</small></strong><span>${q.fallenAt!=null?'場外😂':parking557(q).kind==='edge'?`◆ キワ停め ＋${parkingBonus544(q)*g.multiplier}点！`:parkingBonus544(q)?`★ 金枠 ＋${50*g.multiplier}点！`:q.roundScore/g.multiplier>=90?'ギリギリ生還！':'無事、生還。'}</span></div>`).join('')}}n.network.hidden=c.connected();
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(Math.abs(elapsed-e.at)>1300)continue;sound543(u,e.type==='park'&&e.parking557==='edge'?'edge':e.type);if(e.type==='bump')u.notice={text:e.strength>3?'お客様！ カートをぶつけないで！':'押すなって！ 押すなって！',until:at+1300};if(e.type==='park'&&e.perfect)u.notice={text:e.parking557==='edge'?`${g.players[e.seat].name}、キワ停め ${e.points*g.multiplier}点！ まだ仮！`:`${g.players[e.seat].name}、金枠停車！ まだ押されるぞ…`,until:at+1700};if(e.type==='block')u.notice={text:'荷物にゴツン！ 次は壁で回り込もう。',until:at+1500};if(e.type==='boost')u.notice={text:e.direction==='back'?'逆回転！ 奥で減速！':e.direction==='left'||e.direction==='right'?'ベルトに横取りされた！':'速達便、止まりませーん！',until:at+1200};if(e.type==='fall'){const who=g.players[e.seat];u.notice={text:who.name.includes('より')?'より「イージー！」（場外）':`${who.name}「帰れません！」`,until:at+2000}}if(e.type==='launch'&&g.players[e.seat].name.includes('より'))u.notice={text:'より「イージー！ どいてどいて！」',until:at+1600}}
 put(n.notice,u.notice&&at<u.notice.until?u.notice.text:'');n.notice.hidden=!n.notice.textContent||g.phase!=='play';
}
export function cartBefore543(c){const u=c.cartUI543;if(!u)return;u.cleanup?.();u.cleanup=null;if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.root=null;u.renderer=null}
export function cartDispose543(c){cartBefore543(c);c.cartUI543?.audio?.close()?.catch(()=>{});if(c.cartUI543)c.cartUI543.audio=null}
export function cartAfter543(c){const root=c.root?.querySelector('.ct-play543');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const q=k=>root.querySelector(`[data-ct-${k}]`);u.nodes=Object.fromEntries(['stage','canvas','course-label','course-hint','round','time','dots','danger','power','fill','meter','help','footnote','overlay','overlaylabel','overlaytitle','overlaysub','roundresults','notice','network'].map(k=>[k,q(k)]));u.pawns=[...root.querySelectorAll('[data-ct-pawn]')];u.cards=[...root.querySelectorAll('[data-ct-seat]')];u.scores=[...root.querySelectorAll('[data-ct-score]')];u.statuses=[...root.querySelectorAll('[data-ct-status]')];u.renderer=renderer543(u.nodes.canvas);
 const abort=new AbortController(),on=(e,k,fn)=>e.addEventListener(k,fn,{signal:abort.signal}),resize=()=>{const w=u.nodes.stage.clientWidth,h=u.nodes.stage.clientHeight;if(u.renderer.width===w&&u.renderer.height===h)return;cancelPull547(c);resize543(u.renderer,w,h,devicePixelRatio||1)};resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const unlockZoom=lockPlayZoom498(root),unbind=bindSling547(c,root,abort.signal);
 const tick=()=>{u.raf=null;if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick)};
 on(document,'visibilitychange',()=>{if(document.hidden){cancelPull547(c);if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{})}else{c.refresh?.();if(u.raf==null)tick()}});
 u.cleanup=()=>{unbind();abort.abort();observer.disconnect();unlockZoom()};cartReceive543(c);tick();
}
export function cartClick543(c,b){if(!c.state?.cart||!Object.keys(b.dataset).some(k=>k.startsWith('ct')))return false;const u=ui(c),g=c.state.cart,d=b.dataset;unlock543(u);if(d.ctMonster)c.raw('cart543',{gameId:g.id,kind:'select',monsterId:d.ctMonster});if(d.ctAction==='start')c.raw('cart543',{gameId:g.id,kind:'start'});if(d.ctAction==='more'){u.limit+=24;c.render()}if(d.ctAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock543(u)}return true}
export function cartInput543(c,e){if(e.name!=='cartSearch543')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function cartKey543(c,e){return slingKey547(c,e)}
