import {CART543 as C,clamp543,score543} from './Rules543.js';
import {course544,parkingBonus544} from './Courses544.js';
import {renderer543,resize543,paint543} from './Renderer543.js';
import {unlock543,sound543} from './Audio543.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {playerColor499} from '../party/PartyColors499.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.cartUI543??={seq:0,sound:true,seen:0,limit:24,search:''};
const me=c=>c.state?.cart?.players.find(p=>p.playerId===c.transport.selfId),clock=c=>Date.now()+(c.offset??0),color=p=>playerColor499(p).hex;
function pic(c,p){const species=p.speciesId??p.choice?.speciesId,i=['slime','wolf','goblin','skeleton'].indexOf(species);return i<0?c.sgMonster463?.(species)??'':`<span class="sg-monster ct-avatar543" role="img" aria-label="${['スライム','ウルフ','ゴブリン','スケルトン'][i]}" style="background-position:${i%2*100}% ${Math.floor(i/2)*100}%"></span>`}
const head=c=>`<header class="ct-head543"><button data-party-action462="browse" aria-label="パーティーへ">‹</button><div><small>ABYSS · RUNAWAY CARTS</small><b>暴走ショッピングカート</b></div><button data-ct-action="sound">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),party=c.state.party,pm=party?.members.find(p=>p.playerId===c.transport.selfId),member=g.members.find(p=>p.playerId===c.transport.selfId),host=g.hostId===c.transport.selfId,list=c.roster().filter(p=>!u.search||(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??'').includes(u.search));
 return`<section class="ct543 ct-lobby543">${head(c)}<div class="ct-cover543"><span>止まったからって、安心するな。</span><h1>帰ってこい！<br>暴走カート。</h1><p>ブレーキ？ ついてません。<br>押したあとは、祈るだけ。</p></div><div class="ct-body543"><div class="ct-facts543"><span>４人で大事故</span><span>全５回 · 最後は２倍</span><span>空席はAI</span></div><h2>完璧な駐車に、後ろから誰か。</h2><div class="ct-rules543"><article><em>01</em><div><b>長押し → 離して発進！</b><p>押すほど勢いアップ。最大まで1.8秒。白い輪は衝突しない場合の停車目安。8.5秒以内なら好きなタイミングで！ 離したあとは操作なし。</p></div></article><article><em>02</em><div><b>５つの坂と、金の駐車枠。</b><p>奥ほど１〜100点、金枠にピタッと停まれば＋50点！ 海へはみ出したら、その回は０点。滑る床や加速ベルトで、毎回ちがう力加減に。</p></div></article><article><em>03</em><div><b>その神駐車、まだ仮です。</b><p>止まった車にも追突する！ 金枠から押し出されるとボーナスも消える！ 全車が止まってから採点。全５回の合計で勝負、最後の回は得点２倍。同点は同順位。</p></div></article></div><h2>今日の運転手</h2><input name="cartSearch543" placeholder="相棒の名前で探す" aria-label="相棒を探す" value="${esc(u.search)}"><div class="ct-roster543">${list.slice(0,u.limit).map(p=>`<button data-ct-monster="${esc(p.id)}" aria-pressed="${member?.choice?.id===p.id}">${pic(c,{speciesId:p.raceSpeciesId??p.speciesId})}<small>${esc(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??p.speciesId)}</small></button>`).join('')}</div>${list.length>u.limit?'<button data-ct-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="ct-error543" role="alert">${esc(c.error)}</p><button class="ct-gold543 ct-wide543" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="ct-gold543 ct-wide543" data-ct-action="start" ${!c.ready()||party.members.some(p=>!p.ready||!p.connected||p.atHome)?'disabled':''}>いざ、ノーブレーキ！</button>`:'<p>全員の準備ができたら、部屋主が開始します。</p>'}<p class="ct-note543">相棒による性能差なし。スタート位置は毎回交代。時間切れは自動発進。切断・ホーム滞在中はAIが代わりに押します。</p></div></section>`;
}
function play(c,g){return`<section class="ct543 ct-play543">${head(c)}<div class="ct-players543">${g.players.map(p=>`<article data-ct-seat="${p.seat}" style="--player:${color(p)}"><span>${pic(c,p)}</span><b>${p.playerId===c.transport.selfId?'▼ あなた':esc(p.name)}</b><strong data-ct-score="${p.seat}">0<small>点</small></strong><small data-ct-status="${p.seat}">発進待ち</small></article>`).join('')}</div><div class="ct-round543"><span data-ct-round>ROUND 1 / 5</span><div data-ct-dots>${'<i></i>'.repeat(5)}</div><strong data-ct-time>8.5<small>秒</small></strong></div><div class="ct-stage543" data-ct-stage><canvas data-ct-canvas role="img" aria-label="海辺のマーケット。金枠で停車すると50点ボーナス。床や加速ベルトは回ごとに変わります。海へ落ちると０点。全車が止まるまで得点は仮です。"></canvas><div class="ct-stage-title543"><small data-ct-course-label>SUNSHINE MARKET</small><b data-ct-danger>はじめての坂</b><em data-ct-course-hint>金枠でピタッと ＋50点</em></div><div class="ct-pawns543">${g.players.map(p=>`<div class="ct-pawn543" data-ct-pawn="${p.seat}" style="--player:${color(p)}"><span>${pic(c,p)}</span><b>${p.playerId===c.transport.selfId?'YOU':esc(p.name)}</b></div>`).join('')}</div><div class="ct-overlay543" data-ct-overlay><small data-ct-overlaylabel>ブレーキ、ありません。</small><strong data-ct-overlaytitle>3</strong><span data-ct-overlaysub>長押し → 離して発進！</span><div class="ct-round-results543" data-ct-roundresults></div></div><div class="ct-notice543" data-ct-notice aria-live="polite" hidden></div><div class="ct-network543" data-ct-network hidden>再接続中… AIが代わりに押すよ</div></div><footer class="ct-controls543"><div class="ct-power-title543"><b data-ct-help>勢いを決めよう。</b><span data-ct-power>POWER 0%</span></div><div class="ct-meter543" data-ct-meter role="meter" aria-label="押す強さ" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i data-ct-fill></i><span>そっと</span><span>ほどほど</span><span>全力！</span></div><button class="ct-push543" data-ct-control="push" aria-label="長押しして離すと発進。キーボードはスペースキー長押し。"><b data-ct-button>長押し → 離して発進！</b><small data-ct-subbutton>８.５秒以内なら、いつ押してもOK</small></button><p data-ct-footnote>止まっても、後ろから来るぞ。</p></footer></section>`}
function result(c,g){const winners=g.results.filter(r=>r.rank===1);return`<section class="ct543 ct-result543">${head(c)}<div class="ct-result-hero543"><small>RUNAWAY CARTS · FINAL PARKING</small><h1>${g.winnerIds.includes(c.transport.selfId)?'駐車の神、降臨。':'全員、よく帰ってきた。'}</h1><div class="ct-winners543">${winners.map(r=>{const p=g.players[r.seat];return`<div style="--player:${color(p)}">${pic(c,p)}<b>${esc(p.name)}</b><strong>${p.score}<small>点</small></strong></div>`}).join('')}</div><p>カートは、所定の場所へお戻しください。</p></div><div class="ct-body543">${resultActions490(c)}<div class="ct-results543">${g.results.map(r=>{const p=g.players[r.seat];return`<article style="--player:${color(p)}"><strong>${r.rank}</strong><span>${pic(c,p)}</span><div><b>${esc(r.name)}</b><small>神駐車 ${r.perfects??0}回 · 接触 ${r.bumps}回 · 場外 ${r.falls}回</small></div><b>${r.score}<small>点</small></b></article>`}).join('')}</div><div class="ct-history543"><h2>本日の駐車記録</h2><table><thead><tr><th>運転手</th>${g.history.map(h=>`<th>${h.round===5?'⑤×2':h.round+'回'}</th>`).join('')}</tr></thead><tbody>${g.players.map(p=>`<tr style="--player:${color(p)}"><th>${esc(p.name)}</th>${g.history.map(h=>{const r=h.results.find(r=>r.seat===p.seat);return`<td>${r.fallen?'場外':(r.bonus?'★ ':'')+r.points}</td>`}).join('')}</tr>`).join('')}</tbody></table></div><p class="ct-note543">５回の合計点で順位決定。同点なら同順位。★は金枠ボーナス込み。場外でも、前の回の得点は残るよ。</p></div></section>`}
export function cartView543(c){const g=c.state.cart,u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,search:'',limit:24,previous:null,notice:null,localCharge:null,pointer:null,round:null});return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
export function cartReceive543(c){const g=c.state?.cart;if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.round!==g.round){u.round=g.round;u.localCharge=null;u.pointer=null;u.previous=null;u.roundResultKey=null;u.notice=null}if(p?.launched||g.phase!=='play'){u.localCharge=null;u.pointer=null}u.receivedAt=performance.now()}
export function cartFrame543(c,m){const g=c.state?.cart;if(m.selfId!==c.transport.selfId||!g||m.cart?.id!==g.id||m.cart.serverAt<g.serverAt)return;ui(c).previous=g;c.offset=m.serverNow-Date.now();c.state.cart=m.cart;cartReceive543(c);if((g.phase==='result')!==(m.cart.phase==='result'))c.render()}
function send(c,action){const g=c.state?.cart,p=me(c);if(g?.phase!=='play'||!p||p.launched||!c.ready())return false;return c.raw('cartInput543',{gameId:g.id,round:g.round,seq:++ui(c).seq,action})}
function hold(c){const u=ui(c);if(u.localCharge!=null)return;unlock543(u);if(send(c,'hold'))u.localCharge=performance.now()}
function release(c,cancel=false){const u=ui(c);if(u.localCharge!=null||me(c)?.chargeAt!=null)send(c,cancel?'cancel':'release');u.localCharge=null;u.pointer=null;u.keyHeld=false}
const put=(e,s)=>{if(e&&e.textContent!==String(s))e.textContent=String(s)};
function paint(c){const u=ui(c),g=c.state.cart,p=me(c),n=u.nodes,at=clock(c),data=paint543(u.renderer,g,c.transport.selfId,u,at);if(!data)return;const elapsed=data.elapsed,left=Math.max(0,(C.launchWindow-elapsed)/1000);put(n.round,`ROUND ${g.round} / 5${g.multiplier===2?' · ２倍':''}`);put(n.time,g.phase==='play'?(g.players.every(p=>p.launched)?'見守れ！':left.toFixed(1)+'秒'):'');[...n.dots.children].forEach((e,i)=>e.classList.toggle('is-on',i<g.round));
 const percent=clamp543(u.localCharge!=null?(performance.now()-u.localCharge)/C.chargeTime*100:p?.chargeAt!=null?(elapsed-p.chargeAt)/C.chargeTime*100:p?.power*100||0,0,100);put(n.power,`POWER ${Math.round(percent)}%`);n.fill.style.transform=`scaleX(${percent/100})`;n.meter.setAttribute('aria-valuenow',Math.round(percent));n.meter.classList.toggle('is-full',percent>=97);
 const controllable=g.phase==='play'&&p&&!p.launched&&left>0&&c.ready();n.push.disabled=!controllable;n.push.classList.toggle('is-holding',u.localCharge!=null);put(n.button,!p?'観戦中':p.launched?'発進済み。祈れ！':u.localCharge!=null?'離すと、この強さで発進！':'長押し → 離して発進！');put(n.subbutton,p?.launched?'全車停止まで、まだ確定じゃない。':percent>=97?'全力は飛びすぎ注意！':'強さは1.8秒で最大 · 発進後の操作なし');
 put(n.help,p?.fallenAt!=null?'場外！ この回は０点😂':p?.launched?(Math.hypot(p.vx,p.vy)<.06?`${parkingBonus544(p)?'★ 神駐車！ ':''}仮 ${score543(p)*g.multiplier}点。`:'止まれ、止まれ、止まれ…'):u.localCharge!=null?'押しすぎ注意！':'勢いを決めよう。');const course=course544(g);put(n.danger,course.name);put(n['course-label'],course.label);put(n['course-hint'],course.hint);n.danger.parentElement.style.setProperty('--course',course.color);put(n.footnote,g.phase==='intermission'?'全車停止。今回の得点が確定！':u.localCharge!=null?'白い輪は衝突なしの目安 · 実際は他のカートに注意！':'金枠で停車 ＋50点 · 押し出されたら無効！');
 for(const player of g.players){const v=u.renderer.points.find(q=>q.seat===player.seat),node=u.pawns[player.seat];if(v){node.hidden=!v.visible;node.style.transform=`translate(${v.x}px,${v.y}px) rotate(${v.angle}rad) scale(${v.scale})`;node.style.opacity=v.alpha;node.style.zIndex=String(Math.round(v.y+1000));node.style.setProperty('--size',clamp543(u.renderer.width*.10,27,45)+'px')}put(u.scores[player.seat],player.score+'点');put(u.statuses[player.seat],player.fallenAt!=null?'場外！':g.phase==='intermission'?`＋${player.roundScore}点`:player.launched?Math.hypot(player.vx,player.vy)<.06?`${parkingBonus544(player)?'★ ':''}仮 ${score543(player)*g.multiplier}点`:'暴走中！':player.charging?'押してる…':'発進待ち');u.cards[player.seat].classList.toggle('is-out',player.fallenAt!=null);u.cards[player.seat].classList.toggle('is-perfect',parkingBonus544(player)>0)}
 n.overlay.hidden=g.phase==='play';n.roundresults.hidden=g.phase!=='intermission';if(g.phase==='countdown'){put(n.overlaylabel,g.round===5?'FINAL ROUND · 最後は得点２倍！':`ROUND ${g.round} · ${course.name}`);put(n.overlaytitle,Math.max(1,Math.ceil((g.roundAt-at)/1000)));put(n.overlaysub,course.hint)}
 if(g.phase==='intermission'){put(n.overlaylabel,'PARKING COMPLETE');put(n.overlaytitle,'停車完了！');put(n.overlaysub,'金枠で止まった人は、さらに＋50点！');if(u.roundResultKey!==g.round){u.roundResultKey=g.round;n.roundresults.innerHTML=g.players.map(q=>`<div class="${parkingBonus544(q)?'is-gold':''}" style="--player:${color(q)}"><b>${esc(q.name)}</b><strong>＋${q.roundScore}<small>点</small></strong><span>${q.fallenAt!=null?'場外😂':parkingBonus544(q)?'★ 金枠 ＋50点！':q.roundScore/g.multiplier>=90?'ギリギリ生還！':'無事、生還。'}</span></div>`).join('')}}n.network.hidden=c.connected();
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(Math.abs(elapsed-e.at)>1300)continue;sound543(u,e.type);if(e.type==='bump')u.notice={text:e.strength>3?'お客様！ カートをぶつけないで！':'押すなって！ 押すなって！',until:at+1300};if(e.type==='park'&&e.perfect)u.notice={text:`${g.players[e.seat].name}、神駐車！ まだ押し出されるぞ…`,until:at+1700};if(e.type==='boost')u.notice={text:'速達便、止まりませーん！',until:at+1200};if(e.type==='fall'){const who=g.players[e.seat];u.notice={text:who.name.includes('より')?'より「イージー！」（場外）':`${who.name}「帰れません！」`,until:at+2000}}if(e.type==='launch'&&g.players[e.seat].name.includes('より'))u.notice={text:'より「イージー！ どいてどいて！」',until:at+1600}}
 put(n.notice,u.notice&&at<u.notice.until?u.notice.text:'');n.notice.hidden=!n.notice.textContent||g.phase!=='play';
}
export function cartBefore543(c){const u=c.cartUI543;if(!u)return;u.cleanup?.();u.cleanup=null;if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.root=null;u.renderer=null}
export function cartDispose543(c){cartBefore543(c);c.cartUI543?.audio?.close()?.catch(()=>{});if(c.cartUI543)c.cartUI543.audio=null}
export function cartAfter543(c){const root=c.root?.querySelector('.ct-play543');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const q=k=>root.querySelector(`[data-ct-${k}]`);u.nodes=Object.fromEntries(['stage','canvas','course-label','course-hint','round','time','dots','danger','power','fill','meter','help','button','subbutton','footnote','overlay','overlaylabel','overlaytitle','overlaysub','roundresults','notice','network'].map(k=>[k,q(k)]));u.nodes.push=root.querySelector('[data-ct-control="push"]');u.pawns=[...root.querySelectorAll('[data-ct-pawn]')];u.cards=[...root.querySelectorAll('[data-ct-seat]')];u.scores=[...root.querySelectorAll('[data-ct-score]')];u.statuses=[...root.querySelectorAll('[data-ct-status]')];u.renderer=renderer543(u.nodes.canvas);
 const abort=new AbortController(),on=(e,k,fn)=>e.addEventListener(k,fn,{signal:abort.signal}),resize=()=>resize543(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const unlockZoom=lockPlayZoom498(root),b=u.nodes.push;
 on(b,'pointerdown',e=>{if(e.button!==0||b.disabled||u.pointer!=null)return;e.preventDefault();u.pointer=e.pointerId;b.setPointerCapture(e.pointerId);hold(c)});
 on(b,'pointerup',e=>{if(e.pointerId!==u.pointer)return;e.preventDefault();release(c)});
 on(b,'pointercancel',()=>release(c,true));on(b,'lostpointercapture',()=>{if(u.pointer!=null)release(c,true)});on(b,'contextmenu',e=>e.preventDefault());on(b,'click',e=>{if(e.detail===0&&!u.keyHeld){if(u.localCharge!=null)release(c);else hold(c)}});
 on(window,'keyup',e=>{if(e.code==='Space'&&u.keyHeld){e.preventDefault();release(c)}});on(window,'blur',()=>release(c,true));
 const tick=()=>{u.raf=null;if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick)};
 on(document,'visibilitychange',()=>{if(document.hidden){release(c,true);if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{})}else{c.refresh?.();if(u.raf==null)tick()}});
 u.cleanup=()=>{release(c,true);abort.abort();observer.disconnect();unlockZoom()};cartReceive543(c);tick();
}
export function cartClick543(c,b){if(!c.state?.cart||!Object.keys(b.dataset).some(k=>k.startsWith('ct')))return false;const u=ui(c),g=c.state.cart,d=b.dataset;unlock543(u);if(d.ctMonster)c.raw('cart543',{gameId:g.id,kind:'select',monsterId:d.ctMonster});if(d.ctAction==='start')c.raw('cart543',{gameId:g.id,kind:'start'});if(d.ctAction==='more'){u.limit+=24;c.render()}if(d.ctAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock543(u)}return true}
export function cartInput543(c,e){if(e.name!=='cartSearch543')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function cartKey543(c,e){if(!c.root?.querySelector('.ct-play543')||/INPUT|TEXTAREA/.test(e.target?.tagName)||e.code!=='Space')return false;e.preventDefault();if(!e.repeat){ui(c).keyHeld=true;hold(c)}return true}
