import {assignColors499} from '../party/PartyColors499.js';
export const RELAY563=Object.freeze({version:3,step:20,rounds:3,countdown:2600,roundCountdown:1600,intermission:1800,hold:650,travel:160,blast:1050});
const C=RELAY563,copy=x=>structuredClone(x);
const random=g=>{let n=g.seed|0;n^=n<<13;n^=n>>>17;n^=n<<5;g.seed=n>>>0||563;return g.seed/4294967296;};
const event=(g,type,extra={})=>{g.events.push({id:++g.eventId,type,at:g.lastAt,...extra});g.events=g.events.slice(-40);};
export function makeRelay563({id,code,partyId,hostId,now=0,members}){return{id,code,game:'bomb',rules542:3,partyId462:partyId,hostId,members:copy(members),players:[],phase:'lobby',revision:0,createdAt:now,updatedAt:now,lastAt:now,serverAt:now,round:0,elapsed:0,events:[],eventId:0,bombSerial:0,results:[],winnerIds:[]};}
function setup(g,at){g.round++;g.phase='countdown';g.phaseAt=at;g.startAt=at+(g.round===1?C.countdown:C.roundCountdown);g.roundAt=g.startAt;g.bomb=null;g.flight=null;g.explosion=null;g.exploded=0;g.roundWinners=[];for(const p of g.players)Object.assign(p,{alive:true,holder:false,canPassAt:0,receivedAt:0,outAt:null,botAt:0});event(g,'round',{round:g.round});}
export function startRelay563(g,at,seed=563){g.rules542=3;g.seed=seed||563;g.players=g.members.filter(m=>!m.departed).map((m,seat)=>({playerId:m.playerId,seat,name:m.name,speciesId:m.choice?.speciesId??'slime',color499:m.color499,ai:!!m.ai}));while(g.players.length<4){const seat=g.players.length;g.players.push({playerId:`AI-${g.id}-${seat}`,seat,name:['ボム丸','お返しゴブ','より','ホネパス'][seat],speciesId:['slime','goblin','wolf','skeleton'][seat],ai:true});}assignColors499(g.players,g.aiColors500??{});for(const p of g.players)Object.assign(p,{score:0,wins:0,passes:0,lastSeq:0});Object.assign(g,{round:0,lastAt:at,serverAt:at,events:[],eventId:0,bombSerial:0,results:[],winnerIds:[],starter:Math.floor(random(g)*4)});setup(g,at);g.updatedAt=at;g.revision++;return g;}
function light(g){const alive=g.players.filter(p=>p.alive),initial=g.exploded===0,seat=initial?(g.starter+g.round-1)%4:alive[Math.floor(random(g)*alive.length)].seat,fuse=[9500,8000,6500][g.exploded];g.bomb={id:++g.bombSerial,holder:seat,from:null,litAt:g.lastAt,explodeAt:g.lastAt+fuse,fuse,passes:0};const p=g.players[seat];p.canPassAt=g.lastAt+C.hold;p.receivedAt=g.lastAt;p.botAt=p.canPassAt+180+random(g)*650;g.flight=null;g.explosion=null;event(g,'light',{seat,bombId:g.bomb.id});}
export function canPass563(g,p,at=g.lastAt){return g.phase==='play'&&!!p?.alive&&g.bomb?.holder===p.seat&&at>=p.canPassAt&&at<g.bomb.explodeAt-C.travel;}
export function pass563(g,p,target,at=g.lastAt){if(!canPass563(g,p,at)||!Number.isInteger(target)||target===p.seat||!g.players[target]?.alive)return false;const b=g.bomb,to=g.players[target];b.from=p.seat;b.holder=target;b.passes++;p.passes++;g.flight={from:p.seat,to:target,at,until:at+C.travel};to.receivedAt=at+C.travel;to.canPassAt=at+C.travel+C.hold;to.botAt=to.canPassAt+180+random(g)*650;event(g,'pass',{seat:p.seat,target,bombId:b.id});return true;}
export function inputRelay563(g,p,m){if(!p||!Number.isSafeInteger(m.seq)||m.seq<=p.lastSeq||m.round!==g.round||m.bombId!==g.bomb?.id||m.action!=='pass')return false;if(!pass563(g,p,m.target))return false;p.lastSeq=m.seq;return true;}
function finish(g){g.phase='result';g.phaseAt=g.lastAt;g.bomb=null;g.results=[...g.players].sort((a,b)=>b.score-a.score||a.seat-b.seat).map(p=>({playerId:p.playerId,seat:p.seat,name:p.name,score:p.score,passes:p.passes,wins:p.wins,rank:1+g.players.filter(q=>q.score>p.score).length}));g.winnerIds=g.results.filter(r=>r.rank===1).map(r=>r.playerId);g.revision++;event(g,'finish');}
function explode(g){const b=g.bomb,victim=g.players[b.holder];victim.alive=false;victim.outAt=g.lastAt;g.explosion={seat:victim.seat,at:g.lastAt,bombId:b.id,passes:b.passes};g.bomb=null;g.flight=null;g.exploded++;for(const p of g.players)if(p.alive)p.score++;event(g,'blast',{seat:victim.seat,passes:b.passes});g.nextBombAt=g.lastAt+C.blast;const survivors=g.players.filter(p=>p.alive);if(survivors.length===1){survivors[0].wins++;g.roundWinners=[survivors[0].seat];g.phase='intermission';g.phaseAt=g.lastAt;event(g,'roundEnd',{seat:survivors[0].seat});g.revision++;}}
export function advanceRelay563(g,now,inputs=new Map(),auto=new Set()){if(['lobby','result'].includes(g.phase)){inputs.clear();g.serverAt=now;return false;}
 if(now-g.lastAt>2000){const shift=now-g.lastAt-500;for(const k of ['lastAt','phaseAt','startAt','roundAt','nextBombAt'])if(Number.isFinite(g[k]))g[k]+=shift;if(g.bomb){g.bomb.litAt+=shift;g.bomb.explodeAt+=shift;}if(g.flight){g.flight.at+=shift;g.flight.until+=shift;}if(g.explosion)g.explosion.at+=shift;for(const p of g.players){p.canPassAt+=shift;p.receivedAt+=shift;p.botAt+=shift;if(p.outAt!=null)p.outAt+=shift;}g.events=[];}
 while(g.lastAt+C.step<=now&&!['lobby','result'].includes(g.phase)){g.lastAt+=C.step;g.elapsed=Math.max(0,g.lastAt-g.roundAt);
  if(g.phase==='countdown'){inputs.clear();if(g.lastAt>=g.startAt){g.phase='play';g.phaseAt=g.lastAt;light(g);g.revision++;}continue;}
  if(g.phase==='intermission'){inputs.clear();if(g.lastAt>=g.phaseAt+C.intermission){if(g.round>=C.rounds)finish(g);else setup(g,g.lastAt);}continue;}
  if(g.bomb&&g.lastAt>=g.bomb.explodeAt){explode(g);inputs.clear();continue;}
  if(!g.bomb){inputs.clear();if(g.lastAt>=g.nextBombAt)light(g);continue;}
  for(const p of g.players){p.auto=p.ai||auto.has(p.playerId);const actions=inputs.get(p.playerId)??[];if(!p.auto)while(actions.length&&(actions[0].at??g.lastAt)<=g.lastAt)inputRelay563(g,p,actions.shift());if(p.auto||!actions.length)inputs.delete(p.playerId);}
  const p=g.players[g.bomb.holder];if((p.ai||auto.has(p.playerId))&&g.lastAt>=p.botAt&&canPass563(g,p)){const targets=g.players.filter(q=>q.alive&&q.seat!==p.seat);const back=targets.find(q=>q.seat===g.bomb.from),target=back&&random(g)<.38?back:targets[Math.floor(random(g)*targets.length)];pass563(g,p,target.seat);}
 }g.serverAt=now;g.updatedAt=now;return true;
}
export function publicRelay563(g,selfId){const s=copy(g);delete s.seed;delete s.starter;s.members=s.members.map(({playerId,name,choice,color499,departed})=>({playerId,name,choice,color499,departed}));for(const p of s.players){delete p.botAt;if(p.playerId===selfId){p.appliedSeq563=p.lastSeq;p.lastSeq=Math.max(p.lastSeq??0,p.inputSeq563??0);}else delete p.lastSeq;delete p.inputSeq563;}return s;}
export const signatureRelay563=g=>!g?null:g.phase==='lobby'?[g.id,g.phase,g.revision]:[g.id,g.rules542,g.phase==='result'?'result':'play',g.phase==='result'?g.results:null];
