import {assignColors499} from '../party/PartyColors499.js';
export const RELAY569=Object.freeze({version:4,step:20,rounds:3,countdown:2600,roundCountdown:1600,intermission:2200,hold:500,travel:180,visible:6000,hiddenMin:4000,hiddenRange:4000,survival:30});
const C=RELAY569,copy=x=>structuredClone(x);
const random=g=>{let n=g.seed|0;n^=n<<13;n^=n>>>17;n^=n<<5;g.seed=n>>>0||569;return g.seed/4294967296;};
const event=(g,type,extra={})=>{g.events.push({id:++g.eventId,type,at:g.lastAt,...extra});g.events=g.events.slice(-40);};
const alias=g=>{g.bomb=g.bombs[0]??null;g.flight=g.bomb?.flight??null;};
export function makeRelay569({id,code,partyId,hostId,now=0,members}){return{id,code,game:'bomb',rules542:4,partyId462:partyId,hostId,members:copy(members),players:[],bombs:[],bomb:null,phase:'lobby',revision:0,createdAt:now,updatedAt:now,lastAt:now,serverAt:now,round:0,elapsed:0,events:[],eventId:0,bombSerial:0,results:[],winnerIds:[]};}
function setup(g,at){g.round++;Object.assign(g,{phase:'countdown',phaseAt:at,startAt:at+(g.round===1?C.countdown:C.roundCountdown),bombs:[],explosion:null,explosions:[],roundWinners:[]});g.roundAt=g.startAt;for(const p of g.players)Object.assign(p,{alive:true,roundScore:0,roundHeldMs:0,outAt:null,canPassAt:0,receivedAt:0});alias(g);event(g,'round',{round:g.round});}
export function startRelay569(g,at,seed=569){g.rules542=4;g.seed=seed||569;g.players=g.members.filter(m=>!m.departed).slice(0,4).map((m,seat)=>({playerId:m.playerId,seat,name:m.name,speciesId:m.choice?.speciesId??'slime',color499:m.color499,ai:!!m.ai}));while(g.players.length<4){const seat=g.players.length;g.players.push({playerId:`AI-${g.id}-${seat}`,seat,name:['ボム丸','お返しゴブ','より','ホネパス'][seat],speciesId:['slime','goblin','wolf','skeleton'][seat],ai:true});}assignColors499(g.players,g.aiColors500??{});for(const p of g.players)Object.assign(p,{score:0,bank:0,wins:0,passes:0,heldMs:0,starts:0,lastSeq:0});Object.assign(g,{round:0,lastAt:at,serverAt:at,events:[],eventId:0,bombSerial:0,results:[],winnerIds:[],starter:Math.floor(random(g)*4)});setup(g,at);g.updatedAt=at;g.revision++;return g;}
function fair(g,excluded=new Set()){return g.players.filter(p=>p.alive&&!excluded.has(p.seat)).sort((a,b)=>a.heldMs-b.heldMs||a.starts-b.starts||(a.seat-g.starter+4)%4-(b.seat-g.starter+4)%4)[0];}
function receive(g,b,p,from=null){const at=g.lastAt;b.from=from;b.holder=p.seat;b.flight=from==null?null:{from,to:p.seat,at,until:at+C.travel};b.receivedAt=at+(from==null?0:C.travel);b.readyAt=b.receivedAt+C.hold;b.botAt=b.readyAt+450+random(g)*1300;p.canPassAt=b.readyAt;p.receivedAt=b.receivedAt;}
function light(g){const used=new Set();for(let i=0;i<g.round;i++){const p=fair(g,used);used.add(p.seat);p.starts++;const b={id:++g.bombSerial,number:i+1,litAt:g.lastAt,veilAt:g.lastAt+C.visible,explodeAt:null,passes:0};receive(g,b,p);g.bombs.push(b);event(g,'light',{seat:p.seat,bombId:b.id});}alias(g);}
export function owned569(g,p){return p?g.bombs.filter(b=>b.holder===p.seat):[];}
export function canPass569(g,p,at=g.lastAt,bombId){const b=bombId==null?owned569(g,p)[0]:g.bombs.find(b=>b.id===bombId);return g.phase==='play'&&!!p?.alive&&b?.holder===p.seat&&at>=b.readyAt&&(b.explodeAt==null||at<b.explodeAt-C.travel);}
export function pass569(g,p,target,at=g.lastAt,bombId){const b=bombId==null?owned569(g,p)[0]:g.bombs.find(b=>b.id===bombId);if(!b||!canPass569(g,p,at,b.id)||!Number.isInteger(target)||target===p.seat||!g.players[target]?.alive)return false;receive(g,b,g.players[target],p.seat);b.passes++;p.passes++;alias(g);event(g,'pass',{seat:p.seat,target,bombId:b.id});return true;}
export function inputRelay569(g,p,m){if(!p||!Number.isSafeInteger(m.seq)||m.seq<=p.lastSeq||m.round!==g.round||m.action!=='pass'||!Number.isInteger(m.bombId))return false;if(!pass569(g,p,m.target,g.lastAt,m.bombId))return false;p.lastSeq=m.seq;return true;}
function finish(g){g.phase='result';g.phaseAt=g.lastAt;g.results=[...g.players].sort((a,b)=>b.score-a.score||a.seat-b.seat).map(p=>({playerId:p.playerId,seat:p.seat,name:p.name,score:p.score,passes:p.passes,wins:p.wins,rank:1+g.players.filter(q=>q.score>p.score).length}));g.winnerIds=g.results.filter(r=>r.rank===1).map(r=>r.playerId);g.revision++;event(g,'finish');}
function endRound(g){g.roundWinners=g.players.filter(p=>p.alive).map(p=>p.seat);for(const p of g.players){if(p.alive){p.wins++;p.roundScore+=C.survival;}p.bank+=p.roundScore;p.score=p.bank;}g.bombs=[];alias(g);g.phase='intermission';g.phaseAt=g.lastAt;g.revision++;event(g,'roundEnd',{seats:g.roundWinners});}
function explode(g,due){const victims=new Set(due.map(b=>b.holder));for(const seat of victims){const p=g.players[seat];p.alive=false;p.outAt=g.lastAt;p.roundScore=0;p.score=p.bank;}g.explosions=due.map(b=>({seat:b.holder,at:g.lastAt,bombId:b.id}));g.explosion=g.explosions[0];for(const b of due)event(g,'blast',{seat:b.holder,bombId:b.id});const gone=new Set(due.map(b=>b.id));g.bombs=g.bombs.filter(b=>!gone.has(b.id));if(g.players.filter(p=>p.alive).length<=1||!g.bombs.length){endRound(g);return;}for(const b of g.bombs)if(!g.players[b.holder].alive){const p=fair(g);receive(g,b,p,b.holder);event(g,'pass',{seat:b.from,target:p.seat,bombId:b.id});}alias(g);}
export function advanceRelay569(g,now,inputs=new Map(),auto=new Set()){
 if(['lobby','result'].includes(g.phase)){inputs.clear();g.serverAt=now;return false;}
 if(now-g.lastAt>2000){const shift=now-g.lastAt-500;for(const k of ['lastAt','phaseAt','startAt','roundAt'])if(Number.isFinite(g[k]))g[k]+=shift;for(const b of g.bombs){for(const k of ['litAt','veilAt','explodeAt','receivedAt','readyAt','botAt'])if(Number.isFinite(b[k]))b[k]+=shift;if(b.flight){b.flight.at+=shift;b.flight.until+=shift;}}for(const p of g.players){p.canPassAt+=shift;p.receivedAt+=shift;if(p.outAt!=null)p.outAt+=shift;}for(const e of g.explosions??[])e.at+=shift;g.events=[];}
 while(g.lastAt+C.step<=now&&!['lobby','result'].includes(g.phase)){g.lastAt+=C.step;g.elapsed=Math.max(0,g.lastAt-g.roundAt);
  if(g.phase==='countdown'){inputs.clear();if(g.lastAt>=g.startAt){g.phase='play';g.phaseAt=g.lastAt;light(g);g.revision++;}continue;}
  if(g.phase==='intermission'){inputs.clear();if(g.lastAt>=g.phaseAt+C.intermission){if(g.round>=C.rounds)finish(g);else setup(g,g.lastAt);}continue;}
  for(const b of g.bombs){if(g.lastAt>=b.veilAt&&b.explodeAt==null){b.explodeAt=b.veilAt+C.hiddenMin+Math.floor(random(g)*(C.hiddenRange+1));event(g,'veil',{bombId:b.id});}const p=g.players[b.holder];const held=Math.max(0,g.lastAt-Math.max(g.lastAt-C.step,b.receivedAt));p.heldMs+=held;p.roundHeldMs+=held;p.roundScore=Math.floor(p.roundHeldMs/100);p.score=p.bank+p.roundScore;}
  const due=g.bombs.filter(b=>b.explodeAt!=null&&g.lastAt>=b.explodeAt);if(due.length){explode(g,due);if(g.phase!=='play'){inputs.clear();continue;}}
  for(const p of g.players){p.auto=p.ai||auto.has(p.playerId);const actions=inputs.get(p.playerId)??[];if(!p.auto)while(actions.length&&(actions[0].at??g.lastAt)<=g.lastAt)inputRelay569(g,p,actions.shift());if(p.auto||!actions.length)inputs.delete(p.playerId);}
  for(const b of g.bombs){const p=g.players[b.holder];if((p.ai||auto.has(p.playerId))&&g.lastAt>=b.botAt&&canPass569(g,p,g.lastAt,b.id)){const targets=g.players.filter(q=>q.alive&&q.seat!==p.seat);pass569(g,p,targets[Math.floor(random(g)*targets.length)].seat,g.lastAt,b.id);}}
 }alias(g);g.serverAt=now;g.updatedAt=now;return true;
}
export function publicRelay569(g,selfId){const s=copy(g);delete s.seed;delete s.starter;delete s.bomb;delete s.flight;s.members=s.members.map(({playerId,name,choice,color499,departed})=>({playerId,name,choice,color499,departed}));for(const b of s.bombs){b.hidden=g.lastAt>=b.veilAt;delete b.explodeAt;delete b.botAt;}for(const p of s.players){if(p.playerId===selfId){p.appliedSeq563=p.lastSeq;p.lastSeq=Math.max(p.lastSeq??0,p.inputSeq563??0);}else delete p.lastSeq;delete p.inputSeq563;}s.bomb=s.bombs[0]??null;s.flight=s.bomb?.flight??null;return s;}
export const signatureRelay569=g=>!g?null:g.phase==='lobby'?[g.id,g.phase,g.revision]:[g.id,g.rules542,g.phase==='result'?'result':'play',g.phase==='result'?g.results:null];
