import {BOMB542 as C,cell542,index542,floor542,blastCells542,nearestBomb542,kickDirection545,clamp542} from './Rules542.js';
import {playerColor499} from '../party/PartyColors499.js';
const images={};function art(name){if(!images[name]){const i=new Image();i.decoding='async';i.src=`./assets/${name==='readability'?'bomb545':'bomb542'}/${name}.webp`;images[name]=i}return images[name]}
const ready=i=>i?.complete&&i.naturalWidth;
function circle(c,x,y,r,fill,stroke){c.beginPath();c.arc(x,y,r,0,Math.PI*2);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.stroke()}}
function label(c,text,x,y,color='#fff0c9',size=11){c.font=`700 ${size}px "Noto Sans JP",sans-serif`;c.textAlign='center';c.textBaseline='middle';c.lineWidth=3;c.strokeStyle='#100d23';c.strokeText(text,x,y);c.fillStyle=color;c.fillText(text,x,y)}
export function renderer542(canvas){return{canvas,ctx:canvas.getContext('2d',{alpha:false}),width:0,height:0,dpr:1,atlas:art('atlas'),readability:art('readability'),abyss:art('abyss'),terrain:document.createElement('canvas'),points:[],cacheBuilds:0}}
export function resize542(r,w,h,dpr=1){r.width=w;r.height=h;r.dpr=Math.min(1.5,dpr);r.canvas.width=Math.round(w*r.dpr);r.canvas.height=Math.round(h*r.dpr);r.s=Math.min((w-20)/C.cols,(h-96)/C.rows);r.left=(w-r.s*C.cols)/2;r.top=48+(h-96-r.s*C.rows)/2;r.key=null}
export const point542=(r,x,y)=>({x:r.left+x*r.s,y:r.top+y*r.s});
export const world542=(r,x,y)=>({x:(x-r.left)/r.s,y:(y-r.top)/r.s});
function sprite(r,c,id,x,y,size){if(!ready(r.atlas))return false;const cw=r.atlas.naturalWidth/2,ch=r.atlas.naturalHeight/2;c.drawImage(r.atlas,(id%2)*cw,Math.floor(id/2)*ch,cw,ch,x-size/2,y-size*.56,size,size);return true}
function clearSprite545(r,c,id,x,y,size){if(!ready(r.readability))return false;const sw=r.readability.naturalWidth/2,sh=r.readability.naturalHeight/2;c.drawImage(r.readability,id%2*sw,Math.floor(id/2)*sh,sw,sh,x-size/2,y-size/2,size,size);return true}
function background(r,g){const key=[r.width,r.height,r.dpr,!!ready(r.atlas),!!ready(r.readability),!!ready(r.abyss),g.board.join(''),g.ring].join(':');if(r.key===key)return;r.key=key;r.cacheBuilds++;const c=r.terrain.getContext('2d');r.terrain.width=r.canvas.width;r.terrain.height=r.canvas.height;c.setTransform(r.dpr,0,0,r.dpr,0,0);c.fillStyle='#16182b';c.fillRect(0,0,r.width,r.height);if(ready(r.abyss))c.drawImage(r.abyss,0,0,r.width,r.height);c.fillStyle='#06051935';c.fillRect(0,0,r.width,r.height);const s=r.s;
 for(let y=g.ring;y<C.rows-g.ring;y++)for(let x=g.ring;x<C.cols-g.ring;x++){const p=point542(r,x+.5,y+.5),i=index542(x,y);c.fillStyle=(x+y)%2?'#2d343a':'#343c40';c.fillRect(p.x-s/2,p.y-s/2,s,s);c.strokeStyle='#b69a5940';c.lineWidth=.6;c.strokeRect(p.x-s/2,p.y-s/2,s,s);c.globalAlpha=.4;sprite(r,c,0,p.x,p.y,s*1.15);c.globalAlpha=1;if((i+g.round)%7===0){c.strokeStyle='#d9ab6b90';c.beginPath();c.moveTo(p.x-s*.25,p.y-s*.2);c.lineTo(p.x+s*.05,p.y);c.lineTo(p.x-s*.1,p.y+s*.26);c.stroke()}}
 c.strokeStyle='#d9b878aa';c.lineWidth=2;c.strokeRect(r.left+g.ring*s,r.top+g.ring*s,(C.cols-g.ring*2)*s,(C.rows-g.ring*2)*s);
}
export function paint542(r,g,selfId,u,at){if(!r.width||!r.height||!g.board?.length)return;const c=r.ctx,s=r.s,elapsed=g.phase==='play'?clamp542(g.elapsed+Math.min(150,Math.max(0,at-g.serverAt)),0,C.roundTime):g.elapsed,own=g.players.find(p=>p.playerId===selfId);background(r,g);c.setTransform(r.dpr,0,0,r.dpr,0,0);c.drawImage(r.terrain,0,0,r.width,r.height);const next=elapsed<18000?18000:elapsed<24000?24000:0;
 if(next&&next-elapsed<4500){c.fillStyle=u.reduced?'#ed7b4955':`rgba(255,110,70,${.17+(1+Math.sin(at/180))*.10})`;const edge=g.ring;for(let y=edge;y<C.rows-edge;y++)for(let x=edge;x<C.cols-edge;x++)if(x===edge||y===edge||x===C.cols-edge-1||y===C.rows-edge-1)c.fillRect(r.left+x*s,r.top+y*s,s,s)}
 for(const q of g.cracks??[]){const p=point542(r,...Object.values(cell542(q.i)));if(elapsed>=q.until)continue;if(elapsed>=q.at){if(!clearSprite545(r,c,0,p.x,p.y,s*1.12)){c.fillStyle='#0b0822';c.beginPath();c.ellipse(p.x,p.y,s*.43,s*.4,0,0,Math.PI*2);c.fill()}label(c,'穴',p.x,p.y+s*.30,'#ffe1ba',Math.max(8,s*.2))}else{clearSprite545(r,c,3,p.x,p.y,s*1.08);label(c,'崩れる！',p.x,p.y,'#fff0bb',Math.max(8,s*.19))}}
 for(const b of g.bombs){if(b.explodeAt-elapsed>1200)continue;c.fillStyle=b.explodeAt-elapsed<550?'#ffb23b78':'#fdd78030';for(const i of blastCells542(g,b)){const p=cell542(i);c.fillRect(r.left+(p.x-.5)*s+2,r.top+(p.y-.5)*s+2,s-4,s-4);c.strokeStyle=b.explodeAt-elapsed<550?'#ffe6a8':'#ffc888aa';c.lineWidth=1.2;c.strokeRect(r.left+(p.x-.5)*s+3,r.top+(p.y-.5)*s+3,s-6,s-6)}}
 for(let i=0;i<g.board.length;i++){if(!g.board[i])continue;const q=cell542(i);if(q.x<g.ring||q.y<g.ring||q.x>=C.cols-g.ring||q.y>=C.rows-g.ring)continue;const p=point542(r,q.x,q.y);if(!sprite(r,c,g.board[i]===1?1:2,p.x,p.y-s*.06,s*1.08)){c.fillStyle=g.board[i]===1?'#5a6171':'#976741';c.fillRect(p.x-s*.4,p.y-s*.4,s*.8,s*.8)}}
 for(const q of g.items??[]){if(q.available>elapsed)continue;const p=cell542(q.i),v=point542(r,p.x,p.y);circle(c,v.x,v.y+s*.22,s*.34,'#36f2eb44','#c6fff6');clearSprite545(r,c,1,v.x,v.y-s*.05,s*.87);label(c,'盾',v.x,v.y+s*.35,'#d7fff8',Math.max(9,s*.22))}
 const destination=u.destination??own?.destination;if(destination&&own?.alive){const p=point542(r,destination.x,destination.y);c.lineWidth=1.5;circle(c,p.x,p.y,s*.18,null,playerColor499(own).hex);c.fillStyle=playerColor499(own).hex;c.fillRect(p.x-2,p.y-2,4,4)}
 const near=own?.alive?nearestBomb542(g,own):null;if(near){const d=kickDirection545(g,own,near),a=point542(r,near.x,near.y),b=point542(r,near.x+d.dx*1.4,near.y+d.dy*1.4);c.strokeStyle='#bffff2';c.lineWidth=3;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();label(c,['↑','→','↓','←'][d.d],b.x,b.y,'#e2fff3',17)}for(const b of g.bombs){const p=point542(r,b.x,b.y),left=Math.max(0,(b.explodeAt-elapsed)/1000),color=playerColor499(g.players[b.owner]).hex,pulse=!u.reduced&&left<.8?1+Math.sin(at/55)*.06:1;c.lineWidth=b.id===near?.id?2.5:1.5;circle(c,p.x,p.y+s*.05,s*.31,null,b.id===near?.id?'#fffad1':color);if(!sprite(r,c,3,p.x,p.y,s*.88*pulse))circle(c,p.x,p.y,s*.3,'#302532',color);label(c,left.toFixed(1),p.x,p.y-s*.44,left<.8?'#ffca85':'#fff8d9',Math.max(9,s*.25));if(b.relay)label(c,'↗ '+b.relay,p.x,p.y+s*.36,color,9)}
 for(const b of g.blasts){const life=clamp542((b.until-elapsed)/450,0,1);c.save();c.globalAlpha=life;for(const i of b.cells){const q=cell542(i),p=point542(r,q.x,q.y);c.fillStyle='#f5914c66';c.fillRect(p.x-s*.49,p.y-s*.49,s*.98,s*.98);if(!clearSprite545(r,c,2,p.x,p.y,s*1.25)){circle(c,p.x,p.y,s*.43,'#ff9b45');circle(c,p.x,p.y,s*.23,'#fff2bb')}}c.restore()}
 r.points=[];for(const p of g.players){const old=u.previous?.round===g.round?u.previous.players.find(q=>q.seat===p.seat):null,mix=clamp542((performance.now()-(u.receivedAt??0))/100,0,1),x=old?.alive&&p.alive?old.x+(p.x-old.x)*mix:p.x,y=old?.alive&&p.alive?old.y+(p.y-old.y)*mix:p.y,v=point542(r,x,y),fall=p.fallenAt==null?0:clamp542((elapsed-p.fallenAt)/650,0,1),col=playerColor499(p).hex;r.points.push({...v,seat:p.seat,visible:p.alive||fall<1,scale:1-fall*.8,opacity:1-fall});if(p.alive){c.save();c.lineWidth=p.playerId===selfId?2.5:1.5;c.fillStyle='#07091288';c.beginPath();c.ellipse(v.x,v.y+s*.17,s*.29,s*.13,0,0,Math.PI*2);c.fill();c.strokeStyle=col;c.stroke();if(p.shield){c.lineWidth=1.3;circle(c,v.x,v.y-s*.13,s*.43,'#9bf7fb18','#acfafa')}if(p.invulnerable>elapsed){c.strokeStyle=col;c.globalAlpha=.45;c.beginPath();c.arc(v.x,v.y-s*.1,s*.45,at/250,at/250+Math.PI*1.3);c.stroke()}c.restore()}}
 for(const e of g.events){const age=elapsed-e.at;if(age<0||age>950||!['kick','out','guard','shield'].includes(e.type))continue;const p=point542(r,e.x,e.y);c.save();c.globalAlpha=1-age/950;label(c,({kick:e.relay>1?'返した！ ×'+e.relay:'KICK!',out:'ドカーン！',guard:'GUARD',shield:'シールド'})[e.type],p.x,p.y-s*.8-age*.018,playerColor499(g.players[e.seat]).hex,12);c.restore()}
 if(u.stick545){const a=u.stick545;c.save();c.globalAlpha=.85;circle(c,a.x,a.y,30,'#12152688','#cfebda99');circle(c,a.x+a.dx,a.y+a.dy,12,'#ffe5aa','#fff6d4');c.restore()}
 return{elapsed,next,nearest:near};
}
