import {assignColors499} from '../party/PartyColors499.js';

export const BOMB542=Object.freeze({cols:9,rows:11,step:50,speed:3.6,radius:.23,fuse:2500,range:2,roundTime:30000,rounds:3,countdown:3500,breakTime:2600});
const C=BOMB542,dirs=[[0,-1],[1,0],[0,1],[-1,0]],copy=x=>structuredClone(x);
export const clamp542=(x,a,b)=>Math.max(a,Math.min(b,x));
export const index542=(x,y)=>Math.floor(y)*C.cols+Math.floor(x);
export const cell542=i=>({x:i%C.cols+.5,y:Math.floor(i/C.cols)+.5});
const inside=(x,y)=>x>=0&&y>=0&&x<C.cols&&y<C.rows;
function random(g){let n=g.seed|0;n^=n<<13;n^=n>>>17;n^=n<<5;g.seed=n>>>0||542;return g.seed/4294967296}
function event(g,type,extra={}){g.events.push({id:++g.eventId,type,at:g.elapsed,...extra});g.events=g.events.slice(-64)}
export function makeBomb542({id,code,partyId,hostId,now,members}){return{id,code,game:'bomb',rules542:1,partyId462:partyId,hostId,createdAt:now,updatedAt:now,serverAt:now,revision:0,phase:'lobby',members:copy(members),players:[],board:[],bombs:[],blasts:[],events:[],eventId:0,bombId:0,elapsed:0,round:0,results:[]}}
function arena(g){const board=Array(C.cols*C.rows).fill(0);for(let y=1;y<C.rows;y+=2)for(let x=1;x<C.cols;x+=2)board[index542(x,y)]=1;
 // Rotational pairs give all four starts the same amount of space. Each round changes the middle.
 for(let i=0;i<board.length/2;i++){const p=cell542(i),edgeX=Math.min(p.x,C.cols-p.x),edgeY=Math.min(p.y,C.rows-p.y);if(board[i]||edgeX+edgeY<4)continue;const kind=random(g)<.45?2:0;board[i]=board[board.length-1-i]=kind}
 // Keep a continuous ring and both central avenues open from every spawn.
 for(let y=0;y<C.rows;y++)for(let x=0;x<C.cols;x++)if((x===0||y===0||x===C.cols-1||y===C.rows-1||x===4||y===4||y===6)&&board[index542(x,y)]!==1)board[index542(x,y)]=0;
 return board;
}
function setup(g,now){g.round++;g.roundAt=now+C.countdown;g.startAt=g.roundAt;g.endAt=g.roundAt+C.roundTime;g.phase='countdown';g.phaseAt=now;g.elapsed=0;g.ring=0;g.board=arena(g);g.cracks=[];g.items=[];g.bombs=[];g.blasts=[];g.events=[];g.roundWinners=[];
 const spawns=[[.5,.5],[8.5,10.5],[8.5,.5],[.5,10.5]];for(const p of g.players)Object.assign(p,{x:spawns[p.seat][0],y:spawns[p.seat][1],hp:2,alive:true,shield:false,invulnerable:0,move:null,route:[],face:p.seat%2?0:2,placedAt:-1000,kickAt:-1000,botAt:0,auto:p.ai,fallenAt:null,hitAt:null});event(g,'round',{round:g.round});}
export function startBomb542(g,now,seed=542){g.seed=seed||542;g.players=g.members.filter(m=>!m.departed).map((m,seat)=>({playerId:m.playerId,name:m.name,seat,ai:!!m.ai,color499:m.color499,speciesId:m.choice?.speciesId??'slime',score:0,kos:0,kicks:0,wins:0,lastSeq:0}));
 while(g.players.length<4){const seat=g.players.length;g.players.push({playerId:'AI-'+g.id+'-'+seat,name:['ボム丸','けり返し隊長','火花のより','逃げ足コトコト'][seat],seat,ai:true,speciesId:['slime','goblin','wolf','skeleton'][seat],score:0,kos:0,kicks:0,wins:0,lastSeq:0})}assignColors499(g.players,g.aiColors500??{});g.lastAt=now;setup(g,now);g.updatedAt=now;g.revision++;}
export function solid542(g,x,y,{bombs=true}={}){if(!inside(x,y))return true;const i=index542(x,y);return g.board[i]===1||g.board[i]===2||(bombs&&g.bombs.some(b=>index542(b.x,b.y)===i))}
export function floor542(g,x,y,at=g.elapsed){if(!inside(x,y))return false;const i=index542(x,y),cx=Math.floor(x),cy=Math.floor(y);return cx>=g.ring&&cy>=g.ring&&cx<C.cols-g.ring&&cy<C.rows-g.ring&&!g.cracks.some(q=>q.i===i&&at>=q.at&&at<q.until)}
export function path542(g,p,x,y){const start=index542(p.x,p.y),target=index542(x,y);if(!inside(x,y)||solid542(g,x,y)||!floor542(g,x,y))return[];const prev=new Int16Array(C.cols*C.rows).fill(-2),queue=[start];prev[start]=-1;for(let k=0;k<queue.length;k++){const i=queue[k];if(i===target)break;const q=cell542(i);for(const[dx,dy]of dirs){const nx=q.x+dx,ny=q.y+dy,j=index542(nx,ny);if(!inside(nx,ny)||prev[j]!==-2||solid542(g,nx,ny)||!floor542(g,nx,ny))continue;prev[j]=i;queue.push(j)}}if(prev[target]===-2)return[];const route=[];for(let i=target;i!==start;i=prev[i])route.push(cell542(i));return route.reverse();}
export function blastCells542(g,b){const cells=[index542(b.x,b.y)],center=cell542(cells[0]);for(const[dx,dy]of dirs)for(let d=1;d<=b.range;d++){const x=center.x+dx*d,y=center.y+dy*d;if(!inside(x,y))break;const i=index542(x,y);if(g.board[i]===1)break;cells.push(i);if(g.board[i]===2)break}return cells}
export function nearestBomb542(g,p){return g.bombs.filter(b=>Math.hypot(b.x-p.x,b.y-p.y)<1.2).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y)||a.id-b.id)[0]??null}
export function place542(g,p){if(!p.alive||g.phase!=='play'||g.elapsed-p.placedAt<500||g.bombs.filter(b=>b.planter===p.seat).length>=2||!floor542(g,p.x,p.y)||solid542(g,p.x,p.y))return false;const q=cell542(index542(p.x,p.y));g.bombs.push({id:++g.bombId,...q,owner:p.seat,planter:p.seat,range:C.range,relay:0,explodeAt:g.elapsed+C.fuse,dx:0,dy:0,pass:[p.seat]});p.placedAt=g.elapsed;event(g,'place',{seat:p.seat,...q});return true}
export function kick542(g,p){if(!p.alive||g.phase!=='play'||g.elapsed-p.kickAt<320)return false;const b=nearestBomb542(g,p);if(!b)return false;const vx=b.x-p.x,vy=b.y-p.y;let d=Math.hypot(vx,vy)<.25?p.face:Math.abs(vx)>Math.abs(vy)?(vx>0?1:3):(vy>0?2:0);const[dx,dy]=dirs[d];if(solid542(g,b.x+dx,b.y+dy)||!floor542(g,b.x+dx,b.y+dy))return false;
 b.dx=dx;b.dy=dy;b.owner=p.seat;b.relay++;b.range=Math.min(4,C.range+b.relay);b.pass=[];p.kickAt=g.elapsed;p.kicks++;event(g,'kick',{seat:p.seat,x:b.x,y:b.y,relay:b.relay});return true}
function damage(g,p,owner,x,y,fall=false){if(!p.alive||!fall&&g.elapsed<p.invulnerable)return;if(p.shield&&!fall){p.shield=false;p.invulnerable=g.elapsed+700;event(g,'guard',{seat:p.seat,x:p.x,y:p.y});return}p.hp--;p.hitAt=g.elapsed;p.invulnerable=g.elapsed+1400;p.route=[];p.move=null;
 if(p.hp<=0||fall){p.hp=0;p.alive=false;p.fallenAt=g.elapsed;if(owner!=null&&owner!==p.seat){const attacker=g.players[owner];attacker.score++;attacker.kos++}event(g,'out',{seat:p.seat,owner,x:p.x,y:p.y});return}
 // A blast pushes the survivor one cell. A ledge can turn a hit into a knockout.
 let dx=p.x-x,dy=p.y-y;if(Math.hypot(dx,dy)<.1)[dx,dy]=dirs[p.face];const horizontal=Math.abs(dx)>Math.abs(dy),nx=p.x+(horizontal?Math.sign(dx)*.85:0),ny=p.y+(horizontal?0:Math.sign(dy)*.85);if(!solid542(g,nx,ny,{bombs:false})){p.x=nx;p.y=ny;if(!floor542(g,nx,ny))damage(g,p,owner,nx,ny,true)}event(g,'hit',{seat:p.seat,owner,x:p.x,y:p.y});}
function explode(g,b,queue){const cells=blastCells542(g,b);g.bombs=g.bombs.filter(q=>q.id!==b.id);g.blasts.push({id:b.id,cells,owner:b.owner,at:g.elapsed,until:g.elapsed+450,relay:b.relay});event(g,'blast',{seat:b.owner,x:b.x,y:b.y,relay:b.relay});
 for(const i of cells){if(g.board[i]===2){g.board[i]=0;if(random(g)<.28)g.items.push({i,kind:'shield',available:g.elapsed+600})}const q=cell542(i);if((i+g.round)%7===0&&!g.cracks.some(c=>c.i===i))g.cracks.push({i,at:g.elapsed+650,until:g.elapsed+3600});for(const other of g.bombs)if(index542(other.x,other.y)===i&&!queue.some(q=>q.id===other.id))queue.push(other);for(const p of g.players)if(index542(p.x,p.y)===i)damage(g,p,b.owner,b.x,b.y)}
}
function collision(g,p,x,y){const r=C.radius;for(const[dx,dy]of[[-r,-r],[r,-r],[r,r],[-r,r]]){if(!inside(x+dx,y+dy))return true;const i=index542(x+dx,y+dy);if(g.board[i]===1||g.board[i]===2||g.bombs.some(b=>index542(b.x,b.y)===i&&!b.pass.includes(p.seat)))return true}return g.players.some(q=>q!==p&&q.alive&&Math.hypot(x-q.x,y-q.y)<r*1.65)}
function move(g,p,dt){const q=p.route[0];if(!q)return;const dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy),speed=C.speed*dt;if(d<.035){p.route.shift();return}p.face=Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0;const nx=p.x+dx/d*Math.min(d,speed),ny=p.y+dy/d*Math.min(d,speed);if(!collision(g,p,nx,ny)){p.x=nx;p.y=ny}else{p.route=[];p.move=null}if(d<=speed)p.route.shift()}
function safeRoute(g,p,danger){const queue=[{...cell542(index542(p.x,p.y)),route:[]}],seen=new Set([index542(p.x,p.y)]);for(let k=0;k<queue.length;k++){const q=queue[k],i=index542(q.x,q.y);if(q.route.length&&!danger.has(i))return q.route;for(const[dx,dy]of dirs){const x=q.x+dx,y=q.y+dy,j=index542(x,y);if(!inside(x,y)||seen.has(j)||solid542(g,x,y)||!floor542(g,x,y))continue;seen.add(j);queue.push({x,y,route:[...q.route,{x,y}]})}}return[]}
function bot(g,p){if(g.elapsed<p.botAt)return;p.botAt=g.elapsed+220+p.seat*35;const danger=new Set(g.bombs.flatMap(b=>blastCells542(g,b)));for(const b of g.blasts)if(b.until>g.elapsed)b.cells.forEach(i=>danger.add(i));for(const q of g.cracks)danger.add(q.i);const ringSoon=g.elapsed>=13500&&g.elapsed<18000?1:g.elapsed>=20500?2:g.ring;for(let y=0;y<C.rows;y++)for(let x=0;x<C.cols;x++)if(x<ringSoon||y<ringSoon||x>=C.cols-ringSoon||y>=C.rows-ringSoon)danger.add(index542(x,y));
 if(danger.has(index542(p.x,p.y))){p.route=safeRoute(g,p,danger);if(!p.route.length&&nearestBomb542(g,p))kick542(g,p);return}
 if(p.route.length)return;const foes=g.players.filter(q=>q!==p&&q.alive).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y));const near=foes[0];if(!near)return;
 const trial={x:p.x,y:p.y,range:C.range},rays=blastCells542(g,trial);if((rays.includes(index542(near.x,near.y))||rays.some(i=>g.board[i]===2))&&g.elapsed-p.placedAt>1700){const added=new Set([...danger,...rays]),escape=safeRoute(g,p,added);if(escape.length&&place542(g,p)){p.route=escape;return}}
 const choices=dirs.map(([dx,dy])=>({x:Math.floor(p.x)+.5+dx,y:Math.floor(p.y)+.5+dy})).filter(q=>inside(q.x,q.y)&&!solid542(g,q.x,q.y)&&floor542(g,q.x,q.y)&&!danger.has(index542(q.x,q.y)));choices.sort((a,b)=>Math.hypot(a.x-near.x,a.y-near.y)-Math.hypot(b.x-near.x,b.y-near.y));if(choices.length)p.route=[choices[random(g)<.78?0:Math.floor(random(g)*choices.length)]];
}
function roundEnd(g,now){const survivors=g.players.filter(p=>p.alive),best=Math.max(0,...survivors.map(p=>p.hp));g.roundWinners=survivors.filter(p=>p.hp===best).map(p=>p.seat);for(const s of g.roundWinners){g.players[s].score+=3;g.players[s].wins++}g.phase=g.round>=C.rounds?'result':'intermission';g.phaseAt=now;event(g,'roundEnd',{winners:g.roundWinners});
 if(g.phase==='result'){const ordered=[...g.players].sort((a,b)=>b.score-a.score||b.wins-a.wins||b.kos-a.kos||a.seat-b.seat);g.results=ordered.map((p,i)=>({playerId:p.playerId,name:p.name,seat:p.seat,score:p.score,kos:p.kos,kicks:p.kicks,wins:p.wins,rank:1+ordered.filter(q=>q.score>p.score||q.score===p.score&&q.wins>p.wins||q.score===p.score&&q.wins===p.wins&&q.kos>p.kos).length}));g.winnerIds=g.results.filter(r=>r.rank===1).map(r=>r.playerId)}
}
function step(g,now,inputs,auto){g.elapsed=Math.max(0,now-g.roundAt);g.cracks=g.cracks.filter(q=>q.until>g.elapsed);g.blasts=g.blasts.filter(q=>q.until>g.elapsed);const ring=g.elapsed>=24000?2:g.elapsed>=18000?1:0;if(ring>g.ring){g.ring=ring;event(g,'collapse',{ring});for(let i=0;i<g.board.length;i++){const q=cell542(i);if(!floor542(g,q.x,q.y))g.board[i]=0}}
 for(const p of g.players){p.auto=p.ai||auto.has(p.playerId);const actions=inputs.get(p.playerId)??[];if(p.alive&&!p.auto)for(const a of actions){if(a.action==='move'){p.route=path542(g,p,a.x,a.y);p.move={x:a.x,y:a.y}}if(a.action==='stop'){p.route=[];p.move=null}if(a.action==='bomb')place542(g,p);if(a.action==='kick')kick542(g,p)}inputs.delete(p.playerId);if(!p.alive)continue;if(p.auto)bot(g,p);move(g,p,C.step/1000);if(!floor542(g,p.x,p.y))damage(g,p,null,p.x,p.y,true);for(const item of g.items)if(item.available<=g.elapsed&&item.i===index542(p.x,p.y)&&p.alive&&!p.shield){p.shield=true;item.collected=true;event(g,'shield',{seat:p.seat,x:p.x,y:p.y})}}
 g.items=g.items.filter(i=>!i.collected);for(const b of g.bombs){b.pass=b.pass.filter(seat=>{const p=g.players[seat];return p.alive&&Math.hypot(p.x-b.x,p.y-b.y)<.83});if(b.dx||b.dy){const nx=b.x+b.dx*.4,ny=b.y+b.dy*.4;if(solid542(g,nx+b.dx*.35,ny+b.dy*.35,{bombs:false})||g.bombs.some(q=>q.id!==b.id&&Math.hypot(q.x-nx,q.y-ny)<.75)){const p=cell542(index542(b.x,b.y));b.x=p.x;b.y=p.y;b.dx=b.dy=0}else{b.x=nx;b.y=ny}if(!floor542(g,b.x,b.y))b.explodeAt=g.elapsed}}
 const queue=g.bombs.filter(b=>b.explodeAt<=g.elapsed),done=new Set();while(queue.length){const b=queue.shift();if(done.has(b.id)||!g.bombs.some(q=>q.id===b.id))continue;done.add(b.id);explode(g,b,queue)}for(const b of g.blasts)for(const p of g.players)if(b.cells.includes(index542(p.x,p.y)))damage(g,p,b.owner,p.x,p.y);
 if(g.players.filter(p=>p.alive).length<=1||g.elapsed>=C.roundTime)roundEnd(g,now);
}
export function advanceBomb542(g,now,inputs=new Map(),auto=new Set()){if(['lobby','result'].includes(g.phase))return false;const target=Math.min(now,g.lastAt+1000);while(g.lastAt+C.step<=target){g.lastAt+=C.step;if(g.phase==='countdown'){inputs.clear();if(g.lastAt>=g.roundAt){g.phase='play';g.phaseAt=g.lastAt;event(g,'go')}}else if(g.phase==='intermission'){inputs.clear();if(g.lastAt>=g.phaseAt+C.breakTime)setup(g,g.lastAt)}else if(g.phase==='play')step(g,g.lastAt,inputs,auto);else break}if(now-g.lastAt>1000){const paused=now-g.lastAt;g.roundAt+=paused;g.startAt+=paused;g.endAt+=paused;g.phaseAt+=paused;g.lastAt=now}g.serverAt=now;g.updatedAt=now;g.revision++;return true}
export function publicBomb542(g,selfId){return{id:g.id,code:g.code,game:'bomb',rules542:1,partyId462:g.partyId462,hostId:g.hostId,phase:g.phase,phaseAt:g.phaseAt,revision:g.revision,serverAt:g.serverAt,roundAt:g.roundAt,startAt:g.startAt,endAt:g.endAt,elapsed:g.elapsed,round:g.round,ring:g.ring,members:g.members.map(({playerId,name,choice,color499,departed})=>({playerId,name,choice,color499,departed})),players:g.players.map(({botAt,route,move,lastSeq,...p})=>({...p,...(p.playerId===selfId?{lastSeq,destination:route.at(-1)??null}:{})})),board:g.board,cracks:g.cracks,items:g.items,bombs:g.bombs.map(({pass,...b})=>b),blasts:g.blasts,events:g.events,roundWinners:g.roundWinners,results:g.results,winnerIds:g.winnerIds??[]}}
export const signature542=g=>!g?null:['lobby','result'].includes(g.phase)?g:{id:g.id,phase:'play',players:g.players.map(p=>[p.playerId,p.speciesId,p.color499])};
