import {BOMB542 as C,clamp542} from './Rules542.js';
import {renderer542,resize542,paint542,world542} from './Renderer542.js';
import {unlock542,sound542} from './Audio542.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {playerColor499} from '../party/PartyColors499.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.bombUI542??={seq:0,sound:true,seen:0,limit:24,search:''};
const me=c=>c.state?.bomb?.players.find(p=>p.playerId===c.transport.selfId),clock=c=>Date.now()+(c.offset??0),color=p=>playerColor499(p).hex;
const pic=(c,p)=>{const species=p.speciesId??p.choice?.speciesId,i=['slime','wolf','goblin','skeleton'].indexOf(species);return i<0?c.sgMonster463?.(species)??'':`<span class="sg-monster bb-avatar542" role="img" aria-label="${['スライム','ウルフ','ゴブリン','スケルトン'][i]}" style="background-position:${i%2*100}% ${Math.floor(i/2)*100}%"></span>`};
const head=c=>`<header class="bb-head542"><button data-party-action462="browse" aria-label="パーティーへ">‹</button><div><small>ABYSS · BOMB RELAY</small><b>魔王城の爆弾リレー！</b></div><button data-bb-action="sound">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),party=c.state.party,pm=party?.members.find(p=>p.playerId===c.transport.selfId),member=g.members.find(p=>p.playerId===c.transport.selfId),host=g.hostId===c.transport.selfId,list=c.roster().filter(p=>!u.search||(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??'').includes(u.search));return`<section class="bb542 bb-lobby542">${head(c)}<div class="bb-cover542"><span>その爆弾、お返しします。</span><h1>逃げる？<br>いや、蹴り返せ。</h1><p>導火線は止まらない。<br>最後の１秒が、いちばん面白い。</p></div><div class="bb-body542"><div class="bb-facts542"><span>４人バトル</span><span>30秒 × ３回</span><span>空席はAI</span></div><h2>魔王城、ただいま大炎上。</h2><div class="bb-rules542"><article><em>01</em><div><b>指を滑らせて、逃げろ。</b><p>画面の空いている場所を押し、指を滑らせた方向へ移動。離すと停止。短いタップは目的地へ移動。もう片方の指で爆弾やキック！柱の陰なら十字の爆風を避けられる！</p></div></article><article><em>02</em><div><b>置く。蹴る。お返しする。</b><p>爆弾は2.5秒で爆発、同時に２個まで。近くの爆弾は「けり返す」で自分と反対方向へ。重なっているときは向いている方向へ！</p><p>蹴っても残り時間はそのまま。蹴るたび爆風が伸びる（最大４マス）。最後に蹴った人の攻撃になるよ。</p></div></article><article><em>03</em><div><b>最後の床まで、あきらめるな。</b><p>♡２個。18秒・24秒で外周が崩壊。「崩れる！」が出たら逃げよう。穴は盾でも防げない！ 箱の中のシールドは１発だけ防ぐ。</p><p>撃破＋１点、蹴った爆弾で撃破なら＋２点！ ラウンド勝利は＋３点。時間切れは生存者の残り♡で決着。同数なら同時勝利！ 次の回は全員復活。</p></div></article></div><h2>爆弾を託す相棒</h2><input name="bombSearch542" placeholder="相棒の名前で探す" aria-label="相棒を探す" value="${esc(u.search)}"><div class="bb-roster542">${list.slice(0,u.limit).map(p=>`<button data-bb-monster="${esc(p.id)}" aria-pressed="${member?.choice?.id===p.id}">${pic(c,{speciesId:p.raceSpeciesId??p.speciesId})}<small>${esc(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??p.speciesId)}</small></button>`).join('')}</div>${list.length>u.limit?'<button data-bb-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="bb-error542" role="alert">${esc(c.error)}</p><button class="bb-gold542 bb-wide542" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="bb-gold542 bb-wide542" data-bb-action="start" ${!c.ready()||party.members.some(p=>!p.ready||!p.connected||p.atHome)?'disabled':''}>導火線に、火をつけろ！</button>`:'<p>全員の準備ができたら、部屋主が開始します。</p>'}<p class="bb-note542">能力差なし・全員同じ速さ。切断・ホーム滞在時はAIが代わりに操作します。総得点 → 勝利数 → 撃破数で順位決定。同じなら同順位。</p></div></section>`}
function play(c,g){return`<section class="bb542 bb-play542">${head(c)}<div class="bb-players542">${g.players.map(p=>`<article data-bb-seat="${p.seat}" style="--player:${color(p)}"><span>${pic(c,p)}</span><b>${p.playerId===c.transport.selfId?'▼ あなた':esc(p.name)}</b><strong data-bb-score="${p.seat}">0<small>点</small></strong><small data-bb-hp="${p.seat}">♥ ♥</small></article>`).join('')}</div><div class="bb-round542"><span data-bb-round>ROUND 1 / 3</span><div data-bb-dots><i></i><i></i><i></i></div><strong data-bb-time>30<small>秒</small></strong></div><div class="bb-stage542" data-bb-stage><canvas data-bb-canvas tabindex="0" role="img" aria-label="魔王城の対戦フィールド。スライドで方向移動、短い床タップは目的地移動。爆弾を置くボタンとけり返すボタンで攻撃。矢印キーで移動、スペースで爆弾、Kでけり返す。"></canvas><div class="bb-arena-label542"><small>THE LAST BATTLEMENT</small><b data-bb-danger>柱の陰へ。爆風は十字。</b></div><div class="bb-pawns542">${g.players.map(p=>`<div class="bb-pawn542" data-bb-pawn="${p.seat}" style="--player:${color(p)}"><span>${pic(c,p)}</span><b>${p.playerId===c.transport.selfId?'YOU':esc(p.name)}</b></div>`).join('')}</div><div class="bb-overlay542" data-bb-overlay><small data-bb-overlaylabel>火花、散る。</small><strong data-bb-overlaytitle>3</strong><span data-bb-overlaysub>スライド移動 → 置く → キックで＋２点を狙え</span></div><div class="bb-notice542" data-bb-notice aria-live="polite" hidden></div><div class="bb-network542" data-bb-network hidden>再接続中… AIが引き継いでいるよ</div></div><footer class="bb-controls542"><div class="bb-help542"><span data-bb-help>指をスライドで移動 · 離すと停止</span><button data-bb-control="stop" aria-label="移動を止める">■ 止まる</button></div><div class="bb-buttons542"><button class="bb-place542" data-bb-control="bomb"><b>● 爆弾を置く</b><small data-bb-stock>あと２個 · 2.5秒で爆発</small></button><button class="bb-kick542" data-bb-control="kick"><b>↗ けり返す！</b><small data-bb-kickhint>近くの爆弾をお返し</small></button></div></footer></section>`}
function result(c,g){const wins=g.results.filter(r=>r.rank===1);return`<section class="bb542 bb-result542">${head(c)}<div class="bb-result-hero542"><small>BOMB RELAY · CHAMPION</small><h1>${g.winnerIds.includes(c.transport.selfId)?'お返し、大成功！':'火花の決着！'}</h1><div class="bb-winners542">${wins.map(r=>{const p=g.players[r.seat];return`<div style="--player:${color(p)}">${pic(c,p)}<b>${esc(p.name)}</b><strong>${p.score}<small>点</small></strong></div>`}).join('')}</div><p>最後に笑うのは、蹴り返したやつ。</p></div><div class="bb-body542">${resultActions490(c)}<div class="bb-results542">${g.results.map(r=>{const p=g.players[r.seat];return`<article style="--player:${color(p)}"><strong>${r.rank}</strong><span>${pic(c,p)}</span><div><b>${esc(r.name)}</b><small>${r.wins}勝 · ${r.kos}撃破 · ${r.kicks}回お返し</small></div><b>${r.score}<small>点</small></b></article>`}).join('')}</div><p class="bb-note542">総得点 → ラウンド勝利数 → 撃破数で順位決定。同じなら同順位です。</p></div></section>`}
export function bombView542(c){const g=c.state.bomb,u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,search:'',limit:24,previous:null,destination:null,notice:null});return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
export function bombReceive542(c){const p=me(c),g=c.state?.bomb;if(!g)return;const u=ui(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.round!==g.round){u.round=g.round;u.steer545=null;u.stick545=null;u.keys545?.clear();u.destination=null;u.previous=null}if(!p?.alive||g.phase!=='play'){u.destination=null;u.pointer=null;u.steer545=null;u.stick545=null;u.keys545?.clear()}if(u.destination&&p&&((p.lastSeq??0)>=(u.destinationSeq??Infinity)&&!p.destination||Math.hypot(p.x-u.destination.x,p.y-u.destination.y)<.1))u.destination=null;u.receivedAt=performance.now()}
export function bombFrame542(c,m){const g=c.state?.bomb;if(m.selfId!==c.transport.selfId||!g||m.bomb?.id!==g.id||m.bomb.serverAt<g.serverAt)return;ui(c).previous=g;c.offset=m.serverNow-Date.now();c.state.bomb=m.bomb;bombReceive542(c);if((g.phase==='result')!==(m.bomb.phase==='result'))c.render()}
function send(c,action,extra={}){const g=c.state?.bomb;if(g?.phase!=='play'||!me(c)?.alive||!c.ready())return false;return c.raw('bombInput542',{gameId:g.id,seq:++ui(c).seq,action,...extra})}
const put=(e,s)=>{if(e&&e.textContent!==String(s))e.textContent=String(s)};
function paint(c){const u=ui(c),g=c.state.bomb,p=me(c),n=u.nodes,at=clock(c),data=paint542(u.renderer,g,c.transport.selfId,u,at);if(!data)return;const {elapsed,next,nearest}=data,left=Math.max(0,Math.ceil((C.roundTime-elapsed)/1000));put(n.round,`ROUND ${g.round} / 3`);put(n.time,left+'秒');n.time.classList.toggle('is-urgent',left<=6);[...n.dots.children].forEach((e,i)=>e.classList.toggle('is-on',i<g.round));
 put(n.danger,next&&next-elapsed<=4500?`あと${Math.max(1,Math.ceil((next-elapsed)/1000))}秒で外周崩壊！ 中央へ`:'柱の陰へ。爆風は十字。');n.danger.classList.toggle('is-danger',next&&next-elapsed<=4500);const stock=2-g.bombs.filter(b=>b.planter===p?.seat).length;put(n.stock,`あと${stock}個 · 2.5秒で爆発`);put(n.kickhint,nearest?`残り ${Math.max(0,(nearest.explodeAt-elapsed)/1000).toFixed(1)}秒！`:'近くの爆弾をお返し');n.bomb.disabled=!p?.alive||g.phase!=='play'||stock<=0||!c.ready();n.kick.disabled=!p?.alive||g.phase!=='play'||!nearest||!c.ready();n.stop.disabled=!p?.alive||g.phase!=='play';n.kick.classList.toggle('is-ready',!!nearest);put(n.help,!p?'観戦中':!p.alive?'次のラウンドで全員復活！':p.shield?'盾あり · 爆風を１回防ぐ（穴は危険）':'指をスライドで移動 · 離すと停止');
 for(const player of g.players){const point=u.renderer.points.find(q=>q.seat===player.seat),node=u.pawns[player.seat];if(point){node.hidden=!point.visible;node.style.transform=`translate(${point.x}px,${point.y}px) scale(${point.scale})`;node.style.opacity=point.opacity;node.style.zIndex=String(Math.round(point.y+1000));node.style.setProperty('--size',Math.max(20,u.renderer.s*.84)+'px')}put(u.scores[player.seat],player.score+'点');put(u.hp[player.seat],player.alive?'♥ '.repeat(player.hp)+'♡ '.repeat(2-player.hp):'次の回へ');u.cards[player.seat].classList.toggle('is-out',!player.alive)}
 n.overlay.hidden=g.phase==='play';if(g.phase==='countdown'){put(n.overlaylabel,`ROUND ${g.round} · 全員、同じ条件。`);put(n.overlaytitle,Math.max(1,Math.ceil((g.roundAt-at)/1000)));put(n.overlaysub,'スライド移動 → 置く → キックで＋２点を狙え')}if(g.phase==='intermission'){put(n.overlaylabel,'ROUND CLEAR');put(n.overlaytitle,g.roundWinners.length?'＋３点':'引き分け');put(n.overlaysub,g.roundWinners.length?g.roundWinners.map(s=>g.players[s].name).join(' ＆ ')+' の勝利！':'全員落下！ 次は取り返そう。')}n.network.hidden=c.connected();
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(Math.abs(elapsed-e.at)>1400)continue;sound542(u,e.type);if(e.type==='out'&&e.seat===p?.seat)u.notice={text:'ドカーン！ 次の回で取り返そう！',until:at+2000};if(e.type==='shield'&&e.seat===p?.seat)u.notice={text:'シールド獲得！ 爆風を１回防ぐ',until:at+1700};if(e.type==='out'&&e.owner===p?.seat)u.notice={text:e.relay?'リレー撃破！ ＋２点！':'撃破！ ＋１点',until:at+1700};if(e.type==='kick'&&e.seat===p?.seat)u.notice={text:e.relay>1?'お返し返し！ 爆風がさらに伸びた！':'ナイスキック！ 導火線はそのまま！',until:at+1300}}
 put(n.notice,u.notice&&at<u.notice.until?u.notice.text:'');n.notice.hidden=!n.notice.textContent;
}
export function bombBefore542(c){const u=c.bombUI542;if(!u)return;u.cleanup?.();u.cleanup=null;if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.root=null;u.renderer=null}
export function bombDispose542(c){bombBefore542(c);c.bombUI542?.audio?.close()?.catch(()=>{});if(c.bombUI542)c.bombUI542.audio=null}
export function bombAfter542(c){const root=c.root?.querySelector('.bb-play542');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const q=k=>root.querySelector(`[data-bb-${k}]`);u.nodes=Object.fromEntries(['stage','canvas','round','time','dots','danger','stock','kickhint','help','overlay','overlaylabel','overlaytitle','overlaysub','notice','network'].map(k=>[k,q(k)]));for(const k of ['bomb','kick','stop'])u.nodes[k]=root.querySelector(`[data-bb-control="${k}"]`);u.pawns=[...root.querySelectorAll('[data-bb-pawn]')];u.cards=[...root.querySelectorAll('[data-bb-seat]')];u.scores=[...root.querySelectorAll('[data-bb-score]')];u.hp=[...root.querySelectorAll('[data-bb-hp]')];u.renderer=renderer542(u.nodes.canvas);const abort=new AbortController(),on=(e,k,fn)=>e.addEventListener(k,fn,{signal:abort.signal}),resize=()=>resize542(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const unlockZoom=lockPlayZoom498(root);let lastMove=0;
 const aim=e=>{const r=u.nodes.canvas.getBoundingClientRect(),p=world542(u.renderer,e.clientX-r.left,e.clientY-r.top);if(p.x<0||p.y<0||p.x>=C.cols||p.y>=C.rows)return;const goal={x:Math.floor(p.x)+.5,y:Math.floor(p.y)+.5};if(u.destination?.x===goal.x&&u.destination?.y===goal.y)return;if(send(c,'move',goal)){u.destination=goal;u.destinationSeq=u.seq}};
 let gesture=null;
 const stopSteer=()=>{gesture=null;u.pointer=null;u.steer545=null;u.stick545=null;u.keys545?.clear();send(c,'steer',{dir:-1})};
 const steer=e=>{if(!gesture||e.pointerId!==u.pointer)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y,d=Math.hypot(dx,dy);if(d<11&&!gesture.drag)return;gesture.drag=true;const dir=Math.abs(dx)>Math.abs(dy)?dx>0?1:3:dy>0?2:0;u.destination=null;u.stick545={x:gesture.x-gesture.box.left,y:gesture.y-gesture.box.top,dx:dx/Math.max(d,30)*25,dy:dy/Math.max(d,30)*25};if(u.steer545!==dir){u.steer545=dir;send(c,'steer',{dir})}};
 on(u.nodes.canvas,'pointerdown',e=>{if(e.button!==0||u.pointer!=null||!me(c)?.alive)return;e.preventDefault();u.nodes.canvas.focus({preventScroll:true});unlock542(u);u.pointer=e.pointerId;gesture={x:e.clientX,y:e.clientY,box:u.nodes.canvas.getBoundingClientRect(),drag:false};u.nodes.canvas.setPointerCapture(e.pointerId)});
 on(u.nodes.canvas,'pointermove',e=>{if(e.pointerId!==u.pointer)return;e.preventDefault();steer(e)});
 on(u.nodes.canvas,'pointerup',e=>{if(e.pointerId!==u.pointer)return;e.preventDefault();if(gesture?.drag)stopSteer();else{aim(e);gesture=null;u.pointer=null;u.stick545=null}});
 on(u.nodes.canvas,'pointercancel',stopSteer);on(u.nodes.canvas,'lostpointercapture',()=>{if(u.pointer!=null)stopSteer()});on(u.nodes.canvas,'contextmenu',e=>e.preventDefault());
 const steeringTimer=setInterval(()=>{if(u.steer545!=null)send(c,'steer',{dir:u.steer545})},140);
 on(window,'keyup',e=>{if(u.keys545?.delete(e.key)){e.preventDefault();if(u.keys545.size){u.steer545=[...u.keys545.values()].at(-1);send(c,'steer',{dir:u.steer545})}else stopSteer()}});
 for(const kind of ['bomb','kick','stop']){const b=u.nodes[kind];on(b,'pointerdown',e=>{if(e.button!==0||b.disabled)return;e.preventDefault();unlock542(u);send(c,kind);u.controlAt=Date.now();if(kind==='stop'){stopSteer();u.destination=null}});on(b,'click',e=>{if(e.detail===0){unlock542(u);send(c,kind);if(kind==='stop'){stopSteer();u.destination=null}}})}
 on(window,'blur',()=>{stopSteer();u.pointer=null;u.destination=null;send(c,'stop')});const tick=()=>{u.raf=null;if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick)};on(document,'visibilitychange',()=>{if(document.hidden){stopSteer();u.pointer=null;u.destination=null;send(c,'stop');if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{})}else{c.refresh?.();if(u.raf==null)tick()}});u.cleanup=()=>{if(u.steer545!=null)stopSteer();clearInterval(steeringTimer);abort.abort();observer.disconnect();unlockZoom();u.pointer=null;u.destination=null};bombReceive542(c);tick();
}
export function bombClick542(c,b){if(!c.state?.bomb||!Object.keys(b.dataset).some(k=>k.startsWith('bb')))return false;const u=ui(c),g=c.state.bomb,d=b.dataset;unlock542(u);if(d.bbMonster)c.raw('bomb542',{gameId:g.id,kind:'select',monsterId:d.bbMonster});if(d.bbAction==='start')c.raw('bomb542',{gameId:g.id,kind:'start'});if(d.bbAction==='more'){u.limit+=24;c.render()}if(d.bbAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock542(u)}return true}
export function bombInput542(c,e){if(e.name!=='bombSearch542')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function bombKey542(c,e){if(!c.root?.querySelector('.bb-play542')||/INPUT|TEXTAREA/.test(e.target?.tagName))return false;const p=me(c),u=ui(c),arrows={ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3,w:0,d:1,s:2,a:3};if(arrows[e.key]!=null&&p){e.preventDefault();u.keys545??=new Map();u.keys545.set(e.key,arrows[e.key]);u.steer545=arrows[e.key];send(c,'steer',{dir:u.steer545});u.destination=null;return true}if(e.code==='Space'||e.code==='KeyK'||e.key==='Escape'){e.preventDefault();if(!e.repeat){unlock542(u);send(c,e.code==='Space'?'bomb':e.code==='KeyK'?'kick':'stop');if(e.key==='Escape'){u.steer545=null;u.keys545?.clear()}}return true}return false}
