import {RELAY563 as C,canPass563} from './Relay563.js';
import {esc563 as esc,color563 as color,put563 as put,clock563 as clock,avatar563,header563,lobby563,result563,scoreCards563} from '../party/Arcade563.js';
import {unlock542,sound542} from './Audio542.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const ui=c=>c.bombUI542??={seq:0,sound:true,seen:0,limit:24,search:''},me=c=>c.state?.bomb?.players.find(p=>p.playerId===c.transport.selfId);
const options={prefix:'bb',title:'魔王城の爆弾リレー！',sub:'PASS THE BOMB',cover:new URL('../../assets/bomb542/cover.webp',import.meta.url).href,hero:'こっちに<br>渡すなー！',rule:'相手をタップして渡す。持ったまま０秒でドカン。',detail:'導火線は、渡しても戻らない。受け取ったら一瞬待って、お返し！ 爆発を免れるたび１点。３回勝負で、最後まで残った人ほど高得点。',search:'bombSearch542'};
const slots=(g,self)=>{const own=g.players.findIndex(p=>p.playerId===self),base=own<0?0:own;return g.players.map(p=>(p.seat-base+4)%4);};
function play(c,g){const order=slots(g,c.transport.selfId);return `<section class="arc563 arc-play563 br-play563">${header563(c,ui(c),'bb',options.title,options.sub)}${scoreCards563(c,g)}<div class="arc-mission563"><div><small data-bb-round>ROUND 1 / 3</small><b data-bb-mission>持ったまま０秒で、ドカン！</b></div><strong data-bb-time>—</strong></div><div class="br-stage563" data-bb-stage><div class="br-arena563" aria-hidden="true"></div><div class="br-fuse563"><i data-bb-fuse></i></div><div class="br-center563"><small>渡しても導火線は戻らない</small><b data-bb-center>相手をタップ！</b></div>${g.players.map(p=>`<button class="br-player563" data-bb-target="${p.seat}" data-slot="${order[p.seat]}" style="--player:${color(p)}" aria-label="${esc(p.name)}に爆弾を渡す"><span class="br-pedestal563">${avatar563(c,p)}</span><b>${p.playerId===c.transport.selfId?'あなた':esc(p.name)}</b><small data-bb-label="${p.seat}">${p.playerId===c.transport.selfId?'YOU':'渡す'}</small><i class="br-lock563" data-bb-lock="${p.seat}"></i></button>`).join('')}<div class="br-bomb563" data-bb-bomb aria-hidden="true"><i></i><span></span></div><div class="br-explosion563" data-bb-explosion hidden><i></i><b>ドカーン！</b></div><div class="arc-count563" data-bb-count hidden></div><div class="br-roundwin563" data-bb-win role="status" hidden></div><div class="arc-network563" data-bb-network hidden>再接続中 · AIが引き継いでいます</div></div><footer class="br-controls563"><b data-bb-help>相手をタップして渡す！</b><p data-bb-tip>床の移動操作なし。渡したい相手を１回タップ。</p></footer></section>`;}
export function bombView542(c){const g=c.state.bomb,u=ui(c);if(g.id!==u.id)Object.assign(u,{id:g.id,seq:0,seen:0,limit:24,search:'',pending:null});return g.phase==='lobby'?lobby563(c,g,u,options):g.phase==='result'?result563(c,g,u,{...options,caption:g.winnerIds.includes(c.transport.selfId)?'お返し、大成功！':'爆弾リレー、決着！',stats:p=>`${p.wins}勝 · ${p.passes}回お返し`}):play(c,g);}
export function bombReceive542(c){const g=c.state?.bomb;if(!g)return;const u=ui(c),p=me(c);u.seq=Math.max(u.seq,p?.lastSeq??0);if(u.pending&&(g.bomb?.id!==u.pending.bombId||g.bomb?.holder!==p?.seat||(p?.appliedSeq563??p?.lastSeq)>=u.pending.seq||clock(c)-u.pending.at>1200))u.pending=null;}
export function bombFrame542(c,m){const g=c.state?.bomb,n=m.bomb;if(m.selfId!==c.transport.selfId||!g||n?.id!==g.id||n.serverAt<g.serverAt)return;c.offset=m.serverNow-Date.now();c.state.bomb=n;bombReceive542(c);if((g.phase==='result')!==(n.phase==='result'))c.render();}
function pass(c,target){const g=c.state.bomb,p=me(c),u=ui(c),at=clock(c);if(!c.ready()||u.pending||!canPass563(g,p,at)||target===p.seat||!g.players[target]?.alive)return false;const seq=++u.seq;unlock542(u);if(c.raw('bombInput542',{gameId:g.id,round:g.round,bombId:g.bomb.id,seq,action:'pass',target})===false)return false;u.pending={seq,bombId:g.bomb.id,at};return true;}
function paint(c){const u=ui(c),g=c.state.bomb,p=me(c),n=u.nodes,at=clock(c);if(u.pending&&at-u.pending.at>1200)u.pending=null;const b=g.bomb,holding=b?.holder===p?.seat,left=b?Math.max(0,(b.explodeAt-at)/1000):0,ready=canPass563(g,p,at)&&!u.pending&&c.ready();n.stage.classList.toggle('is-mine',!!holding);n.stage.classList.toggle('is-urgent',!!b&&left<2);put(n.round,`ROUND ${g.round} / 3`);put(n.time,b?left.toFixed(1):'—');n.time.classList.toggle('is-hot',!!b&&left<3);n.fuse.style.transform=`scaleX(${b?Math.max(0,(b.explodeAt-at)/b.fuse):0})`;put(n.mission,g.phase==='intermission'?'生き残り！ 次の回は全員復活':holding?'あなたが爆弾を持っている！':'持ったまま０秒で、ドカン！');
 const lock=p?Math.max(0,(p.canPassAt-at)/1000):0,tooLate=!!b&&at>=b.explodeAt-C.travel;
 put(n.help,!p?.alive?'次の回で、全員復活！':g.phase==='countdown'?'相手をタップして爆弾を渡す':!b?'生き残りに＋１点！':u.pending?'渡しています…':holding?(ready?'渡す相手をタップ！':tooLate?'危ない！':'受け取り中… '+lock.toFixed(1)+'秒'):`${g.players[b.holder].name} が持っている`);
 put(n.tip,holding?(ready?'誰にお返しする？ 相手を１回タップ。':'受け取り直後は、短い待ち時間があります。'):'導火線は止まらない。来たらすぐに、お返し！');put(n.center,!b?'':holding?'相手をタップ！':'次は誰へ？');
 for(const q of g.players){const el=u.targets[q.seat],holder=b?.holder===q.seat;el.disabled=!ready||q.seat===p?.seat||!q.alive;el.classList.toggle('is-holder',holder);el.classList.toggle('is-out',!q.alive);el.classList.toggle('is-target',ready&&q.seat!==p?.seat&&q.alive);put(u.labels[q.seat],!q.alive?'次の回へ':holder?'爆弾！':q.seat===p?.seat?'YOU':ready?'タップして渡す':'');u.locks[q.seat].style.transform=`scaleX(${holder?Math.max(0,Math.min(1,(q.canPassAt-at)/(C.hold+C.travel))):0})`;put(u.scores[q.seat],q.score+'点');put(u.statuses[q.seat],!q.alive?'脱落':holder?'爆弾を所持':`${q.wins}勝`);}
 const position=seat=>{const el=u.targets[seat];return {x:el.offsetLeft+el.offsetWidth/2,y:el.offsetTop+el.offsetHeight*.34};};n.bomb.hidden=!b;if(b){let pos=position(b.holder);if(g.flight&&at<g.flight.until){const from=position(g.flight.from),to=position(g.flight.to),t=Math.max(0,Math.min(1,(at-g.flight.at)/C.travel));pos={x:from.x+(to.x-from.x)*t,y:from.y+(to.y-from.y)*t-Math.sin(t*Math.PI)*45};}n.bomb.style.left=pos.x+'px';n.bomb.style.top=pos.y+'px';n.bomb.classList.toggle('is-hot',left<2);}
 const explosion=g.explosion,blast=explosion&&at>=explosion.at&&at-explosion.at<1000;n.explosion.hidden=!blast;if(blast){const pos=position(explosion.seat);n.explosion.style.left=pos.x+'px';n.explosion.style.top=pos.y+'px';}n.count.hidden=g.phase!=='countdown';if(!n.count.hidden)put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000)));n.win.hidden=g.phase!=='intermission';if(!n.win.hidden)put(n.win,`${g.players[g.roundWinners[0]]?.name??''} の生き残り！`);n.network.hidden=c.connected();
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(Math.abs(at-e.at)>1200)continue;sound542(u,e.type==='pass'?'kick':e.type==='light'?'go':e.type);}
 if(b&&holding){const beat=Math.floor(left*(left<2?4:2));if(beat!==u.beat){u.beat=beat;sound542(u,'place');}}
}
export function bombBefore542(c){const u=c.bombUI542;if(!u)return;u.cleanup?.();u.cleanup=null;cancelAnimationFrame(u.raf);u.raf=null;u.root=null;}
export function bombDispose542(c){bombBefore542(c);c.bombUI542?.audio?.close()?.catch(()=>{});if(c.bombUI542)c.bombUI542.audio=null;}
export function bombAfter542(c){const root=c.root?.querySelector('.br-play563');if(!root)return;const u=ui(c);u.root=root;u.nodes=Object.fromEntries(['stage','round','mission','time','fuse','center','bomb','explosion','count','win','network','help','tip'].map(k=>[k,root.querySelector(`[data-bb-${k}]`)]));u.targets=[...root.querySelectorAll('[data-bb-target]')];u.labels=[...root.querySelectorAll('[data-bb-label]')];u.locks=[...root.querySelectorAll('[data-bb-lock]')];u.scores=[...root.querySelectorAll('[data-arc-score]')];u.statuses=[...root.querySelectorAll('[data-arc-status]')];const abort=new AbortController(),on=(e,k,fn)=>e.addEventListener(k,fn,{signal:abort.signal}),zoom=lockPlayZoom498(root);for(const b of u.targets)on(b,'pointerdown',e=>{if(e.button!==0||b.disabled)return;e.preventDefault();pass(c,Number(b.dataset.bbTarget));});const tick=()=>{u.raf=null;if(!u.root||document.hidden)return;paint(c);u.raf=requestAnimationFrame(tick);};on(document,'visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{});}else{c.refresh?.();if(u.raf==null)tick();}});u.cleanup=()=>{abort.abort();zoom();};bombReceive542(c);tick();}
export function bombClick542(c,b){const d=b.dataset;if(!c.state?.bomb||!Object.keys(d).some(k=>k.startsWith('bb')))return false;const u=ui(c),g=c.state.bomb;unlock542(u);if(d.bbTarget!=null)pass(c,Number(d.bbTarget));if(d.bbMonster)c.raw('bomb542',{gameId:g.id,kind:'select',monsterId:d.bbMonster});if(d.bbAction==='start')c.raw('bomb542',{gameId:g.id,kind:'start'});if(d.bbAction==='more'){u.limit+=24;c.render();}if(d.bbAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock542(u);}return true;}
export function bombInput542(c,e){if(e.name!=='bombSearch542')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true;}
export function bombKey542(c,e){if(!c.root?.querySelector('.br-play563')||/INPUT|TEXTAREA/.test(e.target?.tagName))return false;const seat=Number(e.key)-1;if(Number.isInteger(seat)&&seat>=0&&seat<4){e.preventDefault();if(!e.repeat)pass(c,seat);return true;}return false;}
