import * as T from '../../src/tetra/Rules539.js';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile,chmod} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {brotliDecompressSync} from 'node:zlib';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE);
const server=spawn(process.execPath,['--import',fileURLToPath(new URL('../build539/catalog-fixture.mjs',import.meta.url)),fileURLToPath(new URL('./qa-server.mjs',import.meta.url))],{stdio:['ignore','pipe','pipe']});server.stderr.on('data',d=>process.stderr.write(d));
await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(String(d).includes('ready'))resolve()});server.on('exit',n=>reject(Error('server exited '+n)))});
await writeFile(process.env.CHROMIUM_PATH,brotliDecompressSync(await readFile(process.env.CHROMIUM_BROTLI)));await chmod(process.env.CHROMIUM_PATH,0o755);
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const base='http://127.0.0.1:8541',out=fileURLToPath(new URL('../../docs/build541',import.meta.url)),errors=[],missing=[],results=[];await mkdir(out,{recursive:true});
const api=async(path,data={})=>{const r=await fetch(base+'/qa/'+path,{method:'POST',body:JSON.stringify(data)});if(!r.ok)throw Error(await r.text());return r.json()};
const check=(x,msg)=>{if(!x)throw Error(msg)};
async function open(width=390,height=844,self='p0'){const p=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)missing.push(new URL(r.url()).pathname)});await p.goto(base+'/preview.html?self='+self);await p.waitForFunction(()=>window.qaReady);await p.evaluate(()=>document.fonts.ready);return p}
async function sync(p,ms=50){await p.waitForTimeout(40);await api('advance',{ms});await p.waitForTimeout(100)}
async function start(p,kind,selector,humans=[p]){for(const q of humans)await q.locator('[data-party-action462="ready"]').click();await p.locator(selector).click();await p.waitForFunction(k=>c.state[k].phase!=='lobby',kind)}
async function shot(p,name){await p.screenshot({path:out+'/'+name+'.png'});}
async function dragTo(p,target,{capture=false}={}){const g=await api('state'),a=g.players[0],b=await p.locator('[data-tt-canvas]').boundingBox(),max=Math.min(125,Math.max(95,b.width*.30)),dx=(target.x-a.x)/520*max,dy=(target.y-a.y)/520*max,x=b.x+b.width*.5,y=b.y+b.height*.6;
 await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x-dx,y-dy,{steps:6});await sync(p,100);if(capture)await shot(p,'tetra541-drag');await p.mouse.up();await sync(p,50);check(!!(await api('state')).players[0].flight,'slingshot release launches');await sync(p,900);
}
try{
 await api('reset');const p=await open();await start(p,'tetra','[data-tt-action="start"]');await api('disableAI');await sync(p,4100);let g=await api('state');const mid=g.course.pads.find(t=>t.kind==='stable'&&t.section===1&&g.course.pads.some(q=>q.kind==='stable'&&q.y<t.y&&Math.hypot(q.x-t.x,q.y-t.y)>530&&Math.hypot(q.x-t.x,q.y-t.y)<690));await api('place',{seat:0,padId:mid.id,checkpoint:1,flow:3});await sync(p);await p.waitForTimeout(450);await shot(p,'tetra541-boost');
 g=await api('state');const a=g.players[0],target=g.course.pads.filter(t=>Math.hypot(t.x-a.x,t.y-a.y)>530&&Math.hypot(t.x-a.x,t.y-a.y)<690&&t.y<a.y&&t.kind==='stable').sort((a,b)=>a.y-b.y)[0];check(target,'long boost target');const box=await p.locator('[data-tt-canvas]').boundingBox(),max=Math.min(125,Math.max(95,box.width*.30)),x=box.x+box.width*.5,y=box.y+box.height*.63;await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x-(target.x-a.x)/700*max,y-(target.y-a.y)/700*max,{steps:5});await sync(p);await p.waitForTimeout(500);await shot(p,'tetra541-boost-aim');const preview=await p.evaluate(()=>{const r=c.tetraUI539.renderer;return{x:(r.preview.tx-r.cameraX)*r.scale,y:(r.preview.ty-r.cameraY)*r.scale,w:r.width,h:r.height}});check(preview.x>0&&preview.x<preview.w&&preview.y>0&&preview.y<preview.h,'long-jump landing remains on screen');await p.mouse.up();await sync(p);check((await api('state')).players[0].flight?.boosted,'boosted pointer release');await p.close();
 await api('reset',{kind:'hide',humans:2});const hunter=await open(),friend=await open(390,844,'p1');await hunter.locator('[data-hd-role="hunter"]').click();await start(hunter,'hide','[data-hd-action="start"]',[hunter,friend]);await api('disableAI');await sync(hunter,20500);await api('heist',{seat:1,seal:0,hunterAway:true});await sync(friend,1600);await friend.waitForTimeout(300);await shot(friend,'hide541-mission');await friend.locator('[data-hd-action="ability541"]').click();await sync(friend,50);await shot(friend,'hide541-decoy');check((await api('state')).players[1].abilityReady541>0,'decoy smoke rendered');await friend.locator('[data-hd-action="map"]').click();await shot(friend,'hide541-estate');await hunter.close();await friend.close();
 await api('reset',{kind:'canal'});const cn=await open();await start(cn,'canal','[data-cn-action="start"]');await sync(cn,4800);await api('canalSetup');await sync(cn);const seq=(await api('state')).players[0].lastSeq,field=await cn.locator('[data-cn-stage496]').boundingBox(),cdp=await cn.context().newCDPSession(cn);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:field.x+100,y:field.y+200,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:field.x+200,y:field.y+250,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await sync(cn,100);check((await api('state')).players[0].lastSeq===seq,'canal touch cancel does not submit');await cn.locator('[data-cn-action="burst"]').click();await sync(cn,1500);check((await api('state')).megaCount===1,'three AI join player net');await shot(cn,'canal541-four-net');await cdp.detach();await cn.close();
 check(!errors.length,errors.join('\n'));check(!missing.length,missing.join('\n'));await writeFile(out+'/visual-results.json',JSON.stringify({boostedPointer:true,decoySmoke:true,canalTouchCancel:true,soloPlusThreeAI:true,errors,missing},null,2));console.log('Visual scenarios passed');
}finally{await browser.close();server.kill()}
