import {createRequire} from 'node:module';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {createServer} from './preview.mjs';
const {chromium}=createRequire(import.meta.url)('playwright'),server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
const report={browser:'Chromium mobile touch. Production minigame views, physics, artwork and CSS; isolated party/catalogue fixture. iPhone hardware not tested.',checks:[],sizes:[],errors:[],failed:[]};
try{browser=await chromium.launch({executablePath:process.env.QA_CHROMIUM,headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:740},isMobile:true,hasTouch:true});page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.failed.push(r.url());});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>document.fonts.ready);const cdp=await page.context().newCDPSession(page);
 const touch=async(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'||type==='touchCancel'?[]:[{x,y,id:0,radiusX:4,radiusY:4,force:1}]});
 for(const size of [{width:390,height:740},{width:320,height:568},{width:740,height:390}]){await page.setViewportSize(size);for(const key of ['ricochet','bomb','tetra','hide']){await page.evaluate(k=>load(k),key);await page.waitForTimeout(170);const d=await page.evaluate(()=>({screen:innerWidth,scroll:document.documentElement.scrollWidth,stage:[...document.querySelectorAll('[data-rc-stage],[data-bb-stage],[data-tt-stage],[data-hd-stage]')].map(e=>({w:e.clientWidth,h:e.clientHeight,bottom:e.getBoundingClientRect().bottom}))[0]}));assert(d.scroll<=size.width,key+' overflow');assert(d.stage.h>=120,key+' stage too small');assert(d.stage.bottom<=size.height+1,key+' stage clipped');report.sizes.push({key,...size,...d});if(size.width===390)await page.screenshot({path:'docs/build563/'+key+'-mobile.png'});}}
 report.checks.push('Four production play screens fit390/320px portrait and740px landscape.');await page.setViewportSize({width:390,height:740});
 await page.evaluate(()=>{load('ricochet');freeze();});await page.waitForTimeout(100);await touch('touchStart',195,480);await touch('touchMove',155,580);await touch('touchEnd');assert.equal(await page.evaluate(()=>rawGame.players[0].shots555),1);assert(await page.evaluate(()=>rawGame.players[0].vy>0));await page.evaluate(()=>sync());report.checks.push('Real touch drag/release launches one shot in correct world direction.');
 await page.evaluate(()=>{load('ricochet');freeze();});await touch('touchStart',195,480);await touch('touchMove',155,580);await touch('touchCancel');assert.equal(await page.evaluate(()=>rawGame.players[0].shots555),0);assert.equal(await page.evaluate(()=>c.ricochetUI550.pull),null);report.checks.push('Touch cancellation clears pull without firing.');
 await page.evaluate(()=>{load('bomb');freeze();rawGame.bomb.holder=0;rawGame.players[0].canPassAt=rawGame.lastAt-1;sync();});await page.waitForTimeout(80);const target=page.locator('[data-bb-target="1"]');assert(!(await target.isDisabled()));await target.tap();assert.equal(await page.evaluate(()=>rawGame.bomb.holder),1);assert.equal(await page.evaluate(()=>rawGame.bomb.passes),1);await page.evaluate(()=>{c.root.querySelector('[data-bb-target="1"]').click();sync();});assert.equal(await page.evaluate(()=>rawGame.bomb.passes),1);report.checks.push('Large opponent touch target passes once; duplicate click cannot pass twice.');
 await page.evaluate(()=>{rawGame.bomb.holder=0;rawGame.players[0].canPassAt=Date.now()+1000;sync();});await page.waitForTimeout(50);assert(await target.isDisabled());report.checks.push('Receive lock visibly disables pass targets.');
 await page.evaluate(()=>{load('tetra');freeze();});await page.waitForTimeout(150);const dest=await page.evaluate(async()=>{const T=await import('/src/tetra/Rules539.js'),r=c.tetraUI539.renderer,p=rawGame.players[0],box=document.querySelector('[data-tt-canvas]').getBoundingClientRect();for(const pad of rawGame.course.pads){const x=(pad.x-r.cameraX)*r.scale,y=(pad.y-r.cameraY)*r.scale;if(y>130&&y<r.height-130&&x>35&&x<r.width-35&&T.tapAim563(rawGame,p,pad.x,pad.y))return{x:box.x+x,y:box.y+y,id:pad.id};}return null;});assert(dest);await page.touchscreen.tap(dest.x,dest.y);await page.evaluate(()=>advance(60));assert(await page.evaluate(()=>!!rawGame.players[0].flight));report.checks.push('Tapping a lit foothold produces an authoritative jump without a drag.');
 await page.evaluate(()=>{load('hide','play','hider');freeze();});await page.waitForTimeout(100);assert(await page.locator('[data-hd-tools]').isHidden());await page.locator('[data-hd-action="next563"]').tap();assert(await page.evaluate(()=>sent.some(m=>m.target)));await page.waitForTimeout(80);assert(await page.evaluate(()=>c.hideUI536.renderer.guidePath563.length>0));await page.locator('[data-hd-action="map"]').tap();await page.locator('[data-hd-routechoices]').waitFor({state:'visible',timeout:3000});assert.equal(await page.locator('[data-hd-seal559]').count(),5);await page.locator('[data-hd-action="map"]').tap();await page.locator('[data-hd-action="more563"]').tap();await page.locator('[data-hd-tools]').waitFor({state:'visible',timeout:3000});report.checks.push('Hider primary objective starts navigation; route visible; five alternatives and disguise controls accessible.');
 await page.evaluate(()=>{load('hide','play','hunter');freeze();});await page.waitForTimeout(100);const obj=await page.evaluate(()=>{const cam=c.hideUI536.renderer.camera,box=document.querySelector('[data-hd-canvas]').getBoundingClientRect();return c.state.hide.objects.filter(o=>rawGame.objects.some(q=>q.id===o.id)&&!o.checked).map(o=>({id:o.id,x:box.x+(o.x-cam.x)*cam.scale,y:box.y+(o.y-30-cam.y)*cam.scale})).find(o=>o.x>25&&o.x<innerWidth-25&&o.y>box.top+125&&o.y<box.bottom-100);});assert(obj);await page.touchscreen.tap(obj.x,obj.y);assert(await page.evaluate(id=>sent.some(m=>m.inspect563===id),obj.id));await page.evaluate(()=>advance(5000));assert(await page.evaluate(id=>rawGame.objects.find(o=>o.id===id).checked,obj.id));report.checks.push('Hunter furniture tap approaches and investigates automatically once.');
 for(const key of ['ricochet','bomb','tetra','hide']){await page.evaluate(k=>load(k,'lobby'),key);await page.waitForTimeout(40);assert.equal(await page.locator('h1').count(),1);await page.evaluate(k=>{load(k);viewResult();},key);await page.waitForTimeout(60);assert.equal(await page.locator('[data-party-result490="again"]').count(),1);assert.equal(await page.locator('[data-party-result490="list"]').count(),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'docs/build563/'+key+'-result.png'});}
 report.checks.push('All four lobbies/results render; replay and game-list buttons available.');assert.deepEqual(report.errors,[]);assert.deepEqual([...new Set(report.failed)],[]);
}finally{await browser?.close();await new Promise(r=>server.close(r));await writeFile('docs/build563/browser.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}
