import http from 'node:http';import {readFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';
const root=resolve(new URL('../../',import.meta.url).pathname);const css=['build550-ricochet','build542-bomb','build539-tetra','build541-trio','build536-hide','build545-minigames','build559-hide','build563-arcade'];
export const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${process.env.QA_FONT?"@font-face{font-family:'Noto Sans JP';src:url('/qa-font.ttf')}":''}body{margin:0;background:#0b261f;color:#f3e0b3;font-family:'Noto Sans JP',sans-serif}button,input{font:inherit}.sg-monster{display:inline-block;width:40px;height:40px;background-image:url('/assets/bomb542/players.webp');background-size:200% 200%;background-repeat:no-repeat}button{cursor:pointer}</style>${css.map(s=>'<link rel="stylesheet" href="/src/Styles/'+s+'.css">').join('')}<main id="root"></main><script type="module">
import {fixture,specs} from '/tools/build563/fixture.mjs';
import * as pin from '/src/ricochet550/View550.js';import * as bomb from '/src/bomb/View542.js';import * as tetra from '/src/tetra/View539.js';import * as hide from '/src/hide/View536.js';
const modules={ricochet:pin,bomb,tetra,hide},suffix={ricochet:550,bomb:542,tetra:539,hide:536};window.c={root:document.querySelector('#root'),state:{},transport:{selfId:'p0'},ready:()=>true,connected:()=>true,roster:()=>[],sgSpeciesName463:x=>x,sgMonster463:sp=>{const i=['slime','wolf','goblin','skeleton'].indexOf(sp);return '<span class="sg-monster" style="background-position:'+(i%2*100)+'% '+(Math.floor(Math.max(0,i)/2)*100)+'%"></span>'},refresh:()=>{}};
window.c.raw=(op,m)=>{window.sent.push({...m,op});const g=window.rawGame,p=g.players[0];if(key==='ricochet'||key==='bomb')specs[key].input(g,p,m);else if(key==='tetra'){const actions=inputs.get('p0')??[];actions.push({...m,at:g.elapsed});inputs.set('p0',actions);}else {const old=inputs.get('p0')??{};inputs.set('p0',{...old,...m,kind:m.prop??old.kind,receivedAt:Date.now(),...(Object.hasOwn(m,'target')?{inspect563:null}: {})});}return true;};
let key='ricochet',module=pin,number=550,inputs=[],timer;
const call=name=>module[key+name+number]?.(c);c.render=()=>{call('Before');c.root.innerHTML=module[key+'View'+number](c);call('After');};
c.root.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.disabled)module[key+'Click'+number](c,b)});c.root.addEventListener('keydown',e=>module[key+'Key'+number](c,e));
window.load=(which='ricochet',state='play',role='hider')=>{clearInterval(timer);call('Before');c.offset=0;key=which;module=modules[key];number=suffix[key];window.sent=[];const spec=specs[key],g=fixture(key,Date.now()-(key==='hide'?20000:4000),role,true);window.rawGame=g;inputs=spec.queue();for(let t=g.lastAt??g.simAt;t<=Date.now();t+=20)spec.advance(g,t,inputs);g.phase=state;window.c.state={party:{hostId:'p0',members:g.members.map(p=>({...p,ready:true,connected:true}))},[key]:spec.public(g,'p0')};c.render();timer=setInterval(()=>{spec.advance(g,Date.now(),inputs);const old=c.state[key];c.state[key]=spec.public(g,'p0');call('Receive');if((old.phase==='result')!==(c.state[key].phase==='result'))c.render();},50);};
window.advance=ms=>{const end=(rawGame.lastAt??rawGame.simAt)+ms;for(let t=(rawGame.lastAt??rawGame.simAt)+20;t<=end;t+=20)specs[key].advance(rawGame,t,inputs);c.offset=(rawGame.serverAt??Date.now())-Date.now();sync();};window.freeze=()=>clearInterval(timer);window.sync=()=>{c.state[key]=specs[key].public(rawGame,'p0');call('Receive');};window.viewResult=()=>{freeze();const g=rawGame;g.phase='result';g.results=g.players.map((p,i)=>({rank:i+1,playerId:p.playerId,seat:i,name:p.name,score:p.score,falls:0,jumps:0,landings:0,progress:15,finishedAt:null,won:i===0}));g.winnerIds=['p0'];g.winningSide='hiders';g.reason='escape';g.results[0].won=true;sync();c.render();};load(new URLSearchParams(location.search).get('game')??'ricochet');window.ready=true;
</script></html>`;
export function createServer(){return http.createServer(async(req,res)=>{try{const p=new URL(req.url,'http://local').pathname;if(p==='/'){res.setHeader('Content-Type','text/html');return res.end(html);}if(p==='/favicon.ico'){res.writeHead(204);return res.end();}if(p==='/src/party/PartyView462.js'){res.setHeader('Content-Type','text/javascript');return res.end('export const partySeats462=()=>"";');}const file=p==='/qa-font.ttf'?process.env.QA_FONT:resolve(root,p.slice(1));if(p!=='/qa-font.ttf'&&!file.startsWith(root+'/'))throw Error('bad path');const bytes=await readFile(file);res.setHeader('Content-Type',{'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.ttf':'font/ttf'}[extname(file)]??'application/octet-stream');res.end(bytes);}catch(e){res.writeHead(404);res.end(String(e));}});}
if(process.argv.includes('--serve')){const server=createServer();server.listen(8563,'127.0.0.1',()=>console.log('http://127.0.0.1:8563'));}
