import{createServer}from'node:http';import{readFile,writeFile,mkdir}from'node:fs/promises';import{resolve,extname}from'node:path';import{fileURLToPath}from'node:url';
import{speciesSource,heroSource,visualSource,monsterSource}from'./catalog-fixture.mjs';
const{chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const game=fileURLToPath(new URL('../../',import.meta.url)),base=process.env.BASELINE_DIR??resolve(game,'../base'),font=process.env.QA_FONT_DIR,out=resolve(game,'docs/build529');await mkdir(out,{recursive:true});
const fixtures={'/src/data/species.js':speciesSource,'/src/data/endgameCharacters.js':heroSource,'/src/ui/MonsterVisual.js':visualSource,'/src/models/Monster.js':monsterSource};
const server=createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost'),path=decodeURIComponent(url.pathname),old=url.searchParams.get('version')==='base';if(path==='/preview.html'){const source=await readFile(resolve(old?base:game,'index.html'),'utf8'),styles=[...source.matchAll(/href="((?:\.\/)?src\/Styles\/[^"?]+)/g)].map(m=>m[1]);res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="ja"><meta charset="utf-8"><base href="/'+(old?'base':'game')+'/"><meta name="viewport" content="width=device-width,initial-scale=1">'+(font?'<link rel="stylesheet" href="/font/400.css">':'')+styles.map(s=>'<link rel="stylesheet" href="'+s+'">').join('')+'<style>*{box-sizing:border-box}html,body{margin:0;background:#09291f;color:#fff5d1;font-family:sans-serif}button,input{font:inherit}.qa-portrait{display:inline-flex;align-items:center;justify-content:center;font-size:32px}'+(font?'*{font-family:"Noto Sans JP",sans-serif!important}':'')+'</style><main id="app"></main><script type="module" src="/game/tools/build529/preview.mjs"></script></html>');return}const prefix=path.split('/')[1],root=prefix==='base'?base:prefix==='font'?font:game,relative=path.replace(/^\/(game|base|font)/,'');try{const target=resolve(root,'.'+relative);if(!target.startsWith(resolve(root)+'/'))throw Error();const data=await readFile(target);res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml'})[extname(target)]??'application/octet-stream');res.end(data)}catch{if(fixtures[relative]){res.setHeader('Content-Type','text/javascript');res.end(fixtures[relative])}else{res.statusCode=404;res.end('missing')}}});await new Promise(r=>server.listen(8529,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const errors=[],results=[];
try{
for(const [version,width,height]of [['base',390,700],['game',390,700],['game',320,568],['game',430,800]]){
 const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1});page.on('pageerror',e=>errors.push({version,error:e.message}));
 await page.goto('http://127.0.0.1:8529/preview.html?version='+version);await page.waitForFunction(()=>window.qaReady);await page.waitForTimeout(500);
 const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');
 await page.evaluate(()=>{window.measures={sizeReads:0,draws:0};for(const key of ['clientWidth','clientHeight']){const d=Object.getOwnPropertyDescriptor(Element.prototype,key);Object.defineProperty(Element.prototype,key,{configurable:true,get(){if(this.classList?.contains('world-viewport461'))measures.sizeReads++;return d.get.call(this)}})}const plane=document.querySelector('[data-world-plane461]');window.obs=new MutationObserver(records=>{if(records.some(r=>r.target===plane&&r.attributeName==='style'))measures.draws++});obs.observe(plane,{attributes:true});});
 const before=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));await page.waitForTimeout(3000);const after=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));
 const metrics=await page.evaluate(()=>({...measures,runnerCount:document.querySelectorAll('[data-race-runner]').length}));const entry={version,width,height,...metrics,layoutCount:after.LayoutCount-before.LayoutCount,layoutMs:1000*(after.LayoutDuration-before.LayoutDuration),scriptMs:1000*(after.ScriptDuration-before.ScriptDuration)};results.push(entry);
 if(version==='game'){
  await page.locator('[data-race-action="boost456"]').tap();await page.waitForTimeout(100);if(!(await page.evaluate(()=>sent.some(p=>p.m.op==='boost'&&p.m.raceFrames529===1))))throw Error('boost did not send new protocol');
  await page.locator('[data-race-camera461="overview"]').tap();await page.waitForTimeout(150);if(await page.locator('[data-race-camera461="overview"]').getAttribute('aria-pressed')!=='true')throw Error('overview control');
  await page.locator('[data-race-camera461="follow"]').tap();await page.waitForTimeout(150);
  const fit=await page.evaluate(()=>{const a=document.querySelector('.world-viewport461').getBoundingClientRect();return [...document.querySelectorAll('[data-race-runner]')].map(e=>{const b=e.getBoundingClientRect();return{left:b.left>=a.left-1,right:b.right<=a.right+1,top:b.top>=a.top-1,bottom:b.bottom<=a.bottom+1}})});if(fit.some(f=>Object.values(f).some(v=>!v)))throw Error('runner cropped '+width+JSON.stringify(fit));
  if(width===390)await page.screenshot({path:out+'/race-follow.png',fullPage:true});
  await page.evaluate(()=>setDisconnected(true));if(!(await page.locator('[data-race-action="boost456"]').isDisabled()))throw Error('disconnected boost enabled');await page.evaluate(()=>setDisconnected(false));
  await page.evaluate(()=>{setPlaying(false);showTower()});await page.waitForTimeout(300);if(!(await page.locator('[data-tw-super517]').getAttribute('aria-label')).includes('10秒'))throw Error('cooldown label');
  const slid=await page.evaluate(()=>squash());if(!slid.alive||slid.x>=3.8)throw Error('shallow edge did not slide');
  await page.locator('[data-tw-control517="superJump"]').tap();await page.waitForTimeout(120);const cooldown=await page.locator('[data-tw-cooldown517]').textContent();if(!cooldown.includes('10'))throw Error('cooldown display '+cooldown);
  if(width===390)await page.screenshot({path:out+'/tower-super.png'});
  await page.evaluate(()=>{showRace(500);setPlaying(true)});await page.waitForTimeout(300);await page.setViewportSize({width:height,height:width});await page.waitForTimeout(200);const size=await page.locator('.world-viewport461').evaluate(e=>[e.clientWidth,e.clientHeight]);entry.rotatedSize=size;
 }
 await page.evaluate(()=>disposeQA());const count=await page.evaluate(()=>measures.draws);await page.waitForTimeout(100);if((await page.evaluate(()=>measures.draws))!==count)throw Error('animation survived disposal');await page.close();
}
if(errors.length)throw Error(JSON.stringify(errors));await writeFile(out+'/browser-results.json',JSON.stringify({engine:'Chromium 153 mobile emulation; local production client/simulation, QA-only missing catalog/portrait/EXP stubs',results,errors},null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close();server.close()}
