// Local UI fixture uses the production view and public engine output; never loaded by index.html.
import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';import fs from'node:fs';import assert from'node:assert/strict';
import{spawn}from'node:child_process';
const server=spawn(process.execPath,['tools/build463/isolated-preview.mjs'],{env:{...process.env,SG_FONT_DIR:'/workspace/scratch/f53cec25ebda/qa-deps/node_modules/@fontsource/noto-sans-jp'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{if(String(b).includes('Isolated preview ready'))resolve()});server.stderr.on('data',b=>reject(Error(String(b))))});
const browser=await chromium.launch({executablePath:'/workspace/scratch/f53cec25ebda/qa-deps/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[];
try{
 const page=await browser.newPage({viewport:{width:393,height:852},isMobile:true,hasTouch:true});page.on('pageerror',e=>errors.push(e.stack));await page.goto('http://127.0.0.1:18451/?name=p4');await page.waitForFunction(()=>window.qa451?.client.ready());await page.evaluate(()=>document.fonts.ready);
 await page.evaluate(async()=>{const E=await import('/src/sugoroku/Engine463.js'),c=qa451.client;window.E464=E;qa451.transport.ws.onmessage=()=>{};c.refresh=()=>{};c.connected=()=>true;const g=E.makeLobby463({id:'p4',seed:3,members:[{playerId:'p4',name:'あなた'},{playerId:'rival',name:'月影の狼'},{playerId:'slime',name:'火花のスライム'},{playerId:'goblin',name:'いたずら悪魔'}]});E.start463(g,Date.now());g.step='pre';g.players.forEach((p,i)=>{p.choice={speciesId:['slime','wolf','ember_slime','goblin'][i]};p.pos=''+(10+i*2);p.trail=Array.from({length:11+i*2},(_,n)=>''+n)});const p=g.players[0];g.discard.push(...p.hand);p.hand=[];for(const id of ['yori-0','rion-6','guard','treasure','curse-heavy']){const uid=Object.keys(g.cards).find(u=>g.cards[u]===id);if(!uid)continue;g.deck=g.deck.filter(x=>x!==uid);g.discard=g.discard.filter(x=>x!==uid);g.players.forEach(x=>x.hand=x.hand.filter(x=>x!==uid));p.hand.push(uid)}window.g464=g;window.show464=()=>{c.state.sugoroku=E.public463(g,'p4');c.state.party={id:'party464',code:'SHOW64',hostId:'p4',members:g.members};c.partyBrowse462=false;c.render()};show464();});
 await page.waitForTimeout(450);await page.screenshot({path:'docs/build464/hand-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('.sg-hand').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight+2));assert.equal(await page.locator('.sg-hand .is-usable').count(),2);assert.ok(await page.locator('.sg-tile-effect464').filter({hasText:'2マス戻る'}).count()>0);
 await page.locator('.sg-hand .is-unavailable').first().click();await page.screenshot({path:'docs/build464/card-detail-mobile.png',fullPage:true});assert.ok(await page.locator('.sg-inspect .sg-muted').isVisible());await page.locator('[data-sg-action="close"]').click();
 await page.evaluate(()=>{E464.present464(g464,'card',{actorId:'rival',cardId:'rion-6'});show464()});await page.waitForTimeout(200);await page.screenshot({path:'docs/build464/card-back-mobile.png',fullPage:true});await page.waitForTimeout(750);await page.screenshot({path:'docs/build464/card-flip-mobile.png',fullPage:true});
 const before=await page.evaluate(()=>qa451.client.sgFX464.active.start);await page.evaluate(()=>show464());assert.equal(await page.evaluate(()=>qa451.client.sgFX464.active.start),before);
 await page.evaluate(()=>{E464.present464(g464,'effect',{actorId:'rival',targetIds:['p4'],effectType:'move',n:-2,harmful:true});show464()});await page.waitForFunction(()=>document.querySelector('.sg-presentation464')?.dataset.kind==='effect');assert.ok(await page.locator('.sg-seat.sg-target464').count());await page.screenshot({path:'docs/build464/target-mobile.png',fullPage:true});
 await page.waitForTimeout(950);await page.evaluate(()=>{E464.present464(g464,'dice',{actorId:'p4',dice:[2,5,3],transformed:[2,5,3],total:12});show464()});await page.waitForTimeout(1100);await page.screenshot({path:'docs/build464/dice-mobile.png',fullPage:true});assert.equal(await page.locator('.sg-die464').count(),3);assert.match(await page.locator('.sg-dice-total464').textContent(),/12/);
 await page.waitForTimeout(900);
 await page.evaluate(()=>{E464.present464(g464,'card',{actorId:'rival',cardId:'rion-6'});g464.pending={id:999,playerId:'p4',kind:'defense',prompt:'蔦の小突きに対応',options:[{value:'accept',label:'防御せず受ける'}],data:{effect:{actor:'rival',target:'p4',cardId:'rion-6'}}};show464()});assert.equal(await page.locator('.sg-modal-choice').count(),0);await page.waitForSelector('.sg-modal-choice');assert.ok(await page.locator('.sg-incoming464').isVisible());await page.screenshot({path:'docs/build464/defense-mobile.png',fullPage:true});await page.evaluate(()=>{g464.pending=null;qa451.client.sgUI463.modal=null;show464()});
 await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>show464());await page.screenshot({path:'docs/build464/desktop.png',fullPage:true});
 await page.setViewportSize({width:320,height:667});await page.evaluate(()=>show464());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.waitForTimeout(500);assert.ok(await page.locator('.sg-token.is-current').evaluate(el=>{const r=el.getBoundingClientRect(),v=document.querySelector('.sg-viewport').getBoundingClientRect();return r.left<v.right&&r.right>v.left&&r.top<v.bottom&&r.bottom>v.top}));await page.screenshot({path:'docs/build464/narrow-mobile.png',fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{qa451.client.sgFX464=null;show464();E464.present464(g464,'card',{actorId:'rival',cardId:'rion-6'});show464()});await page.waitForTimeout(100);assert.equal(await page.locator('.sg-flip-inner464').evaluate(el=>getComputedStyle(el).animationName),'none');
 await page.waitForTimeout(1500);await page.evaluate(()=>{qa451.client.sgFX464=null;show464()});assert.equal(await page.locator('.sg-presentation464 [class]').count(),0);
 assert.deepEqual(errors,[]);fs.writeFileSync('docs/build464/visual-results.json',JSON.stringify({checks:['393px / 320px mobile and 1280px desktop without horizontal overflow','readable tile effects','playable hand glow / inspectable dim cards','card back then front; rerender preserves animation clock','explicit target seat highlighted','three server-provided dice and corrected total','defense choice waits for reveal without auto-accepting','reduced motion and no history replay on first snapshot'],errors,scope:'Production View/Engine in a local UI fixture; not physical iPhone Safari.'},null,2));console.log('visual checks passed');
}finally{await browser.close();server.kill()}
