import {partySeats462} from './PartyView462.js';
import {resultActions490} from './PartyResults490.js';
import {playerColor499} from './PartyColors499.js';
export const esc563=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const color563=p=>playerColor499(p).hex;
export const put563=(e,t)=>{if(e&&e.textContent!==String(t))e.textContent=String(t)};
export const clock563=c=>Date.now()+(c.offset??0);
export function avatar563(c,p){const sp=p.speciesId??p.choice?.speciesId??'slime',i=['slime','wolf','goblin','skeleton'].indexOf(sp);return i<0?c.sgMonster463?.(sp)??'':`<span class="sg-monster arc-avatar563" role="img" aria-label="${['スライム','ウルフ','ゴブリン','スケルトン'][i]}" style="background-position:${i%2*100}% ${Math.floor(i/2)*100}%"></span>`;}
export function header563(c,u,prefix,title,sub){return `<header class="arc-head563"><button data-party-action462="browse" aria-label="パーティーへ">‹</button><div><small>${sub}</small><b>${title}</b></div><button data-${prefix}-action="sound" aria-label="効果音切り替え">音 ${u.sound?'ON':'OFF'}</button></header>`;}
export const scoreCards563=(c,g)=>`<div class="arc-scores563">${g.players.map(p=>`<article data-arc-card="${p.seat}" style="--player:${color563(p)}"><div>${avatar563(c,p)}<b>${p.playerId===c.transport.selfId?'あなた':esc563(p.name)}</b></div><strong data-arc-score="${p.seat}">${p.score}<small>点</small></strong><span data-arc-status="${p.seat}"></span></article>`).join('')}</div>`;
export function lobby563(c,g,u,{prefix,title,sub,cover,hero,rule,detail,search}){const pm=c.state.party?.members.find(p=>p.playerId===c.transport.selfId),member=g.members.find(p=>p.playerId===c.transport.selfId),host=g.hostId===c.transport.selfId,list=c.roster().filter(p=>!u.search||(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??p.speciesId).includes(u.search));return `<section class="arc563 arc-lobby563">${header563(c,u,prefix,title,sub)}<div class="arc-cover563" style="--cover:url('${cover}')"><small>４人対戦 · 空席はAI</small><h1>${hero}</h1><p>${rule}</p></div><div class="arc-body563"><p class="arc-rule563">${detail}</p>${g.migrationNote?`<p>${esc563(g.migrationNote)}</p>`:''}${prefix==='rc'?`<div class="arc-options563"><b>勝負の長さ</b>${[90,150].map(s=>`<button data-rc-duration="${s}" aria-pressed="${g.duration555===s*1000}" ${host?'':'disabled'}>${s}秒</button>`).join('')}</div>`:''}<h2>今日の相棒</h2><input name="${search}" placeholder="相棒を探す" aria-label="相棒を探す" value="${esc563(u.search)}"><div class="arc-roster563">${list.slice(0,u.limit).map(p=>`<button data-${prefix}-monster="${esc563(p.id)}" aria-pressed="${member?.choice?.id===p.id}">${avatar563(c,{speciesId:p.raceSpeciesId??p.speciesId})}<small>${esc563(c.sgSpeciesName463?.(p.raceSpeciesId??p.speciesId)??p.speciesId)}</small></button>`).join('')}</div>${list.length>u.limit?`<button data-${prefix}-action="more">もっと見る</button>`:''}${partySeats462(c)}<p role="alert">${esc563(c.error)}</p><button class="arc-gold563 arc-wide563" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="arc-gold563 arc-wide563" data-${prefix}-action="start" ${!c.ready()||c.state.party?.members.some(p=>!p.ready||!p.connected||p.atHome)?'disabled':''}>勝負、スタート！</button>`:'<p>部屋主のスタートを待っています。</p>'}<p class="arc-note563">相棒による能力差はありません。離席・切断中はAIが引き継ぎます。同点は同順位。</p></div></section>`;}
export function result563(c,g,u,{prefix,title,sub,cover,caption,stats}){return `<section class="arc563 arc-result563">${header563(c,u,prefix,title,sub)}<div class="arc-cover563 arc-finale563" style="--cover:url('${cover}')"><small>CHAMPION</small><h1>${caption}</h1><div class="arc-champions563">${g.results.filter(r=>r.rank===1).map(r=>{const p=g.players[r.seat];return `<div style="--player:${color563(p)}">${avatar563(c,p)}<b>${esc563(p.name)}</b><strong>${p.score}<small>点</small></strong></div>`}).join('')}</div></div><div class="arc-body563">${resultActions490(c)}<div class="arc-results563">${g.results.map(r=>{const p=g.players[r.seat];return `<article style="--player:${color563(p)}"><em>${r.rank}</em>${avatar563(c,p)}<div><b>${esc563(p.name)}</b><small>${stats(p)}</small></div><strong>${p.score}<small>点</small></strong></article>`}).join('')}</div><p class="arc-note563">合計得点で順位決定。同点は同順位です。</p></div></section>`;}
