import{PARTY_GAMES462}from'./PartyGames462.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const isPartyHub462=c=>(!c.state?.room&&!c.state?.sugoroku)||!!c.partyBrowse462;
export const spectator462=c=>!!c.state?.party&&!!c.state?.room&&!c.state.room.members.some(m=>m.playerId===c.transport.selfId&&!m.departed);
export function partySeats462(c){const p=c.state?.party;if(!p)return'';return`<div class="party-seats462">${Array.from({length:4},(_,i)=>{const m=p.members[i];return`<div class="${m?.playerId===c.transport.selfId?'is-self':''}"><span class="seat-avatar462">${m?esc(m.name.slice(0,1)):'＋'}</span><span><b>${esc(m?.name??'参加募集中')}</b><small>${!m?'合言葉で集合':!m.connected?'再接続待ち':m.atHome?'ホーム滞在中':m.spectating?'観戦中 · 次から参加':m.ready?'準備OK':p.game?'準備中':'ゲーム選択中'}${m?.playerId===p.hostId?' · 部屋主':''}</small></span></div>`}).join('')}</div>`}
export function partyHub462(c){const p=c.state?.party,r=c.state?.room??c.state?.sugoroku,host=p?.hostId===c.transport.selfId,game=PARTY_GAMES462.find(x=>x.id===c.selectedGame462),ready=c.ready(),locked=r&&!['lobby','result'].includes(r.phase);return`<section class="party-hub462 race451-screen race458"><header><button data-race-action="back">‹ ホーム</button><div><small>ABYSS GAME LOUNGE</small><b>パーティー</b></div><span class="party-connected462">${c.connected()?'● 接続中':'○ 接続待ち'}</span></header>${!ready?`<p class="race-status451">${esc(c.connectionMessage())}<button data-race-action="refresh">接続を確認</button></p>`:''}${c.error||c.rewardError?`<p class="race-status451 is-error" role="alert">${esc(c.error||c.rewardError)}</p>`:''}${p?`<section class="party-room462"><div class="party-code462"><span><small>ずっと同じ合言葉</small><b>${esc(p.code)}</b></span><button data-party-action462="copy">コピー</button><button data-party-action462="invite">招待リンク</button></div>${partySeats462(c)}<p>ホームへ戻っても、このパーティーのまま。</p>${r?`<button class="race-primary451" data-party-action462="resume">${locked?'開催中のゲームへ':r.phase==='result'?'ゲーム結果を見る':'準備に戻る'}</button>`:''}</section>`:`<div class="party-intro462"><small>集まって、何度でも。</small><h1>今日は、何で遊ぶ？</h1><p>ひとりならAIと。友達とは同じ部屋のまま。</p></div>`}<div class="party-section462"><small>MINI GAMES</small><h2>ゲームを選ぼう</h2>${p&&!host?'<p>部屋主が次のゲームを選びます。</p>':''}</div><div class="party-games462">${PARTY_GAMES462.map(g=>`<button class="game-cover462" data-party-game462="${g.id}" ${p&&(!host||locked)||!ready?'disabled':''}><img src="${g.image}" alt="${esc(g.name)}" width="1536" height="1024"><span class="game-people462">${g.players}</span><span class="game-caption462"><small>${g.tag}</small><strong>${g.name}</strong><span>${g.description}</span><b>${p?locked?'ゲーム開催中':r?'同じメンバーで次へ':'このゲームで遊ぶ':'選んで遊ぶ'} <i>▶</i></b></span></button>`).join('')}</div>${!p?`<section class="party-entry462"><h2>${game?esc(game.name)+'で遊ぶ':'友達と集合しよう'}</h2><button class="race-primary451" data-party-action462="create" ${ready?'':'disabled'}>部屋を作る <small>ひとりでも遊べる</small></button><label for="party-code462">合言葉で参加</label><div><input id="party-code462" name="roomCode" value="${esc(c.draft.code)}" placeholder="合言葉 6文字" maxlength="6" autocapitalize="characters" autocomplete="off" spellcheck="false"><button data-party-action462="join" ${ready?'':'disabled'}>参加</button></div></section>`:`<button class="party-leave462" data-party-action462="leave">パーティーから退出</button>`}<p class="party-foot462">遊べるゲームは、ここに追加されていくよ。</p></section>`}
export function partyDecorate462(c,html){const p=c.state?.party,r=c.state?.room;if(!p||!r)return html;const host=p.hostId===c.transport.selfId,me=p.members.find(m=>m.playerId===c.transport.selfId),spectator=spectator462(c);html=html.replace('</header>',`</header><div class="party-navigation462"><button data-party-action462="browse">‹ パーティー</button><small>${esc(p.code)} · ${p.members.length}/4人${spectator?' · 観戦中':''}</small></div>`);if(spectator){html=html.replace('race451-screen ','race451-screen is-spectator462 ');html=html.replace('<div class="race-control456">','<div class="race-control456 spectator-hidden462">');html=html.replace('育成報酬を保存中…','観戦参加 · 次のゲームから出走できます')}
 if(r.phase==='lobby')html=html.replace('<div class="dock-buttons458">',`<div class="party-preparation462">${partySeats462(c)}<button data-party-action462="ready" aria-pressed="${!!me?.ready}" ${!r.members.find(x=>x.playerId===c.transport.selfId)?.choice||!c.ready()?'disabled':''}>${me?.ready?'✓ 準備OK · 取り消す':'準備OK'}</button></div><div class="dock-buttons458">`);
 if(r.phase==='result'||r.phase==='lobby')html=html.replace(/<small class="action-feedback458"/,`${host?'<button class="party-switch462" data-party-action462="lounge">別のゲームを選ぶ</button>':'<button class="party-switch462" data-party-action462="browse">パーティーを見る</button>'}<small class="action-feedback458"`);return html;
}
export function updateParty462(c){const p=c.state?.party,r=c.state?.room;if(!p||!r)return;const button=c.root?.querySelector('[data-race-action="start"]');if(button)button.disabled=button.disabled||p.members.some(m=>!m.ready||!m.connected||m.atHome);if(spectator462(c)){const own=c.root.querySelector('[data-own-place457]');if(own)own.textContent='観戦中 · 次のレースから参加';for(const b of c.root.querySelectorAll('[data-race-action="bet"],[data-race-action="pass"],[data-race-action="boost456"]'))b.disabled=true}}
export function partyClick462(c,b){const action=b.dataset.partyAction462,game=b.dataset.partyGame462;if(!action&&!game)return false;c.error='';if(action==='browse'){c.partyBrowse462=true;c.expanded460=false;c.render();return true}if(action==='resume'){c.partyBrowse462=false;c.render();return true}
 const p=c.state?.party;
 if(action==='copy'||action==='invite'){const value=action==='copy'?p?.code:(()=>{const u=new URL(location.href);u.searchParams.set('party462',p.code);return u.href})();if(value){if(navigator.clipboard)navigator.clipboard.writeText(value).then(()=>c.toast('コピーしたよ'),()=>c.toast(value));else c.toast(value)}return true}
 if(!c.ready()){c.error='接続を確認してから操作してね';c.render();return true}
 if(game){if(game==='sugoroku'&&c.state.rulesVersion<10){c.error='カードすごろくにはサーバーのBuild469更新・再起動が必要です';c.render();return true}if(!p){c.selectedGame462=game;c.render();c.root.querySelector('.party-entry462')?.scrollIntoView({block:'nearest',behavior:'smooth'})}else{c.partyBrowse462=false;c.raw('partyGame462',{game})}return true}
 if(action==='create'){c.raw('partyCreate462',{displayName:c.displayName(),roster:c.roster(),game:c.selectedGame462});return true}
 if(action==='join'){c.raw('partyJoin462',{code:c.draft.code.trim(),displayName:c.displayName(),roster:c.roster()});return true}
 if(action==='ready'){c.raw('partyReady462',{ready:!p?.members.find(m=>m.playerId===c.transport.selfId)?.ready});return true}
 if(action==='lounge'){c.raw('partyLounge462');return true}
 if(action==='leave'){c.raw('partyLeave462');return true}return true;
}
