import{openColor500,colorAttrs499,colorDialog499,colorClick499,colorKey499,colorAfter499,colorReceive499,colorError499,colorPoll499}from'./PartyColorUI499.js';
// Membership actions decorate the existing seat elements without changing their layout.
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const room=c=>c.state?.cart??c.state?.bomb??c.state?.tetra??c.state?.hide??c.state?.fishing??c.state?.sumo??c.state?.tower??c.state?.quiz??c.state?.luck??c.state?.gorilla??c.state?.room??c.state?.sugoroku??c.state?.cabbage??c.state?.canal;
const host=c=>c.state?.party?.hostId===c.transport.selfId;
const idle=c=>!room(c)||['lobby','result'].includes(room(c).phase);
export function memberAttrs485(c,m){if(m&&m.playerId===c.transport.selfId)return colorAttrs499(c,m);return m&&host(c)&&m.playerId!==c.transport.selfId?` data-party-member485="${esc(m.playerId)}" role="button" tabindex="0" aria-haspopup="dialog" aria-label="${esc(m.name)}の参加者メニューを開く"`:''}
function selected(c){const u=c.partyMember485,p=c.state?.party,m=p?.members.find(m=>m.playerId===u?.playerId);if(!u)return null;if(!host(c)||p?.id!==u.partyId||!m||(m.seatToken485??null)!==u.seatToken485){c.partyMemberRestore485=u.playerId;c.partyMember485=null;return null}return m}
export function memberDialog485(c){const colors=colorDialog499(c);if(colors)return colors;const m=selected(c),u=c.partyMember485;if(!m||!u)return'';const r=room(c),choice=r?.members?.find(x=>x.playerId===m.playerId)?.choice,species=m.portrait476?.speciesId??choice?.speciesId,can=c.state.partyMemberActions485===1,playing=!idle(c),pending=!!u.pendingAt,fee=r?.game==='sugoroku'||!!c.state.sugoroku;
 const note=!can?'退場機能を使うにはサーバーをBuild485へ更新・再起動してください。':playing?'対戦中は退場させられません。ゲーム終了後に操作できます。':'このプレイヤーを部屋から退場させます。空いた席は、次の開始時にAIが入ります。';
 return`<div class="party-member-backdrop485" data-party-backdrop485><section class="party-member-dialog485" role="dialog" aria-modal="true" aria-labelledby="party-member-title485" aria-describedby="party-member-note485" tabindex="-1"><header><span>参加者メニュー</span><button data-party-member-action485="close" aria-label="閉じる">×</button></header><div class="party-member-person485"><span>${species&&c.sgMonster463?c.sgMonster463(species):esc(m.name.slice(0,1))}</span><div><h2 id="party-member-title485">${esc(m.name)}</h2><small>${!m.connected?'オフライン · 再接続待ち':m.atHome?'ホーム滞在中':'オンライン'}</small></div></div><p id="party-member-note485">${note}</p>${fee&&!playing?'<small class="party-member-refund485">支払い済みの開始前参加費は返金されます。</small>':''}${u.error?`<p class="party-member-error485" role="alert">${esc(u.error)}</p>`:''}<button class="party-color-save499" data-party-member-action485="color" ${pending||playing?'disabled':''}>イメージカラーを変更</button><footer><button data-party-member-action485="close">キャンセル</button><button class="party-member-remove485" data-party-member-action485="remove" ${pending||playing||!can||!c.ready()?'disabled':''}>${pending?'退場処理中…':'退場させる'}</button></footer></section></div>`;
}
function close(c){c.partyMemberRestore485=c.partyMember485?.playerId;c.partyMember485=null;c.render()}
export function memberClick485(c,event){if(colorClick499(c,event))return true;const target=event.target,action=target.closest?.('[data-party-member-action485]');if(action&&c.root?.contains(action)){if(action.disabled)return true;if(action.dataset.partyMemberAction485==='close'){close(c);return true}const m=selected(c),u=c.partyMember485;if(!m||!u)return true;if(action.dataset.partyMemberAction485==='color'){if(!u.pendingAt&&idle(c))openColor500(c,m);return true}if(!idle(c)||!c.ready()||c.state.partyMemberActions485!==1||u.pendingAt)return true;u.pendingAt=Date.now();u.error='';c.error='';const sent=c.raw('partyKick485',{partyId:u.partyId,gameId:room(c)?.id??null,playerId:m.playerId,seatToken485:u.seatToken485});if(sent===false){u.pendingAt=0;u.error='接続を確認してから、もう一度操作してね。'}c.render();return true}
 if(target.matches?.('[data-party-backdrop485]')){close(c);return true}
 const seat=target.closest?.('[data-party-member485]');if(!seat||!c.root?.contains(seat))return false;const p=c.state?.party,m=p?.members.find(x=>x.playerId===seat.dataset.partyMember485);if(!m||!host(c)||m.playerId===c.transport.selfId)return true;c.error='';c.partyMember485={partyId:p.id,playerId:m.playerId,seatToken485:m.seatToken485??null,pendingAt:0,error:''};c.render();return true;
}
export function memberKey485(c,e){if(colorKey499(c,e))return true;const dialog=c.root?.querySelector('[data-party-backdrop485]');if(dialog){if(e.key==='Escape'){e.preventDefault();close(c)}else if(e.key==='Tab'){const buttons=[...dialog.querySelectorAll('button:not(:disabled)')],first=buttons[0],last=buttons.at(-1),active=globalThis.document?.activeElement;if(e.shiftKey&&(active===first||!dialog.contains(active))){e.preventDefault();last?.focus()}else if(!e.shiftKey&&(active===last||!dialog.contains(active))){e.preventDefault();first?.focus()}}return true}if(['Enter',' '].includes(e.key)&&e.target.closest?.('[data-party-member485]')){e.preventDefault();return memberClick485(c,e)}return false}
export function memberBefore485(c){const a=globalThis.document?.activeElement;c.memberFocus485=c.root?.contains(a)?a?.dataset?.partyMemberAction485:null}
export function memberAfter485(c){if(colorAfter499(c))return;const overlay=c.root?.querySelector('[data-party-backdrop485]');if(overlay)for(const node of c.root?.children??[])if(node!==overlay)node.inert=true;if(overlay){const focus=c.memberFocus485==='remove'?'remove':'close';(overlay.querySelector(`[data-party-member-action485="${focus}"]:not(:disabled)`)??overlay.querySelector('button'))?.focus({preventScroll:true});return}if(c.partyMemberRestore485){const id=c.partyMemberRestore485;c.partyMemberRestore485=null;([...c.root.querySelectorAll('[data-party-member485],[data-party-color-open499]')].find(x=>(x.dataset.partyMember485??x.dataset.partyColorOpen499)===id)??c.root.querySelector('[data-party-action462="resume"],[data-party-action462="ready"]'))?.focus({preventScroll:true})}}
export function memberReceive485(c){colorReceive499(c);const u=c.partyMember485;if(u?.pendingAt&&c.state?.party?.id===u.partyId&&!c.state.party.members.some(m=>m.playerId===u.playerId)){c.partyMemberRestore485=u.playerId;c.partyMember485=null;c.toast('退場しました。空いた席はAIで始められます。')}}
export function memberError485(c,message){colorError499(c,message);if(message.op==='partyKick485'&&c.partyMember485){c.partyMember485.pendingAt=0;c.partyMember485.error=message.message}}
export function memberPoll485(c){colorPoll499(c);const u=c.partyMember485;if(u?.pendingAt&&Date.now()-u.pendingAt>6000){u.pendingAt=0;u.error='受付を確認できませんでした。接続を確認して、もう一度押してね。';c.render()}}
