import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile,chmod} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const server=spawn(process.execPath,['--import',fileURLToPath(new URL('./catalog-fixture.mjs',import.meta.url)),fileURLToPath(new URL('./qa-server.mjs',import.meta.url))],{stdio:['ignore','pipe','pipe']});server.stderr.on('data',d=>process.stderr.write(d));await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(String(d).includes('listening'))resolve()});server.on('exit',code=>reject(Error('server exit '+code)))});
if(process.env.CHROMIUM_BROTLI){const {brotliDecompressSync}=await import('node:zlib');await writeFile(process.env.CHROMIUM_PATH,brotliDecompressSync(await readFile(process.env.CHROMIUM_BROTLI)));await chmod(process.env.CHROMIUM_PATH,0o755)}
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const base='http://127.0.0.1:8539',out=process.env.QA_OUT_DIR??fileURLToPath(new URL('../../docs/build539',import.meta.url)),doc=fileURLToPath(new URL('../../docs/build539',import.meta.url)),errors=[],baseAssetsMissing=[],results=[];await mkdir(out,{recursive:true});
const api=async(path,data={})=>{const r=await fetch(base+'/qa/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});return r.json()};
const check=(x,msg)=>{if(!x)throw Error(msg)};
async function open(width,height,self='p0'){const p=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1});p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400){if(new URL(r.url()).pathname==='/assets/cabbage484/kitchen.png')baseAssetsMissing.push('Historical checkout omits cabbage kitchen art');else errors.push(r.status()+' '+r.url())}});await p.goto(base+'/preview.html?self='+self);await p.waitForFunction(()=>window.qaReady);await p.evaluate(()=>document.fonts.ready);return p}
async function sync(p,ms=50){await p.waitForTimeout(35);await api('advance',{ms});await p.waitForTimeout(100)}
async function start(p){await p.locator('[data-party-action462="ready"]').click();await p.locator('[data-tt-action="start"]').click();await p.waitForFunction(()=>c.state.tetra.phase==='countdown')}
async function world(p,x,y){const b=await p.locator('[data-tt-canvas]').boundingBox(),r=await p.evaluate(()=>({scale:c.tetraUI539.renderer.scale,y:c.tetraUI539.renderer.cameraY}));return{x:b.x+x*r.scale,y:b.y+(y-r.y)*r.scale}}
async function jump(p,id,{shot=false}={}){const g=await api('state'),a=g.players[Number(new URL(p.url()).searchParams.get('self')?.slice(1)??0)],pad=g.course.pads[id],target=await world(p,pad.x,pad.y),hold=Math.round((Math.hypot(pad.x-a.x,pad.y-a.y)-85)/350*1150/50)*50;await p.mouse.move(target.x,target.y);await p.mouse.down();await sync(p,Math.max(100,hold));if(shot)await p.screenshot({path:out+'/tetra539-charge.png'});await p.mouse.up();await sync(p,50);check(await p.evaluate(()=>!!c.state.tetra.players.find(p=>p.playerId===c.transport.selfId).flight),'release launches '+JSON.stringify(await p.evaluate(()=>window.qaSent.slice(-4))));if(shot){await sync(p,250);await p.screenshot({path:out+'/tetra539-jump.png'})}await sync(p,950);check((await api('state')).players[a.seat].padId===id,'land intended pad '+id);}
try{
 for(const [width,height] of [[320,568],[390,844],[430,932]]){
  console.log('viewport',width,height);await api('reset');const p=await open(width,height);if(width===390)await p.screenshot({path:out+'/tetra539-lobby.png',fullPage:true});
  await start(p);if(width===390){await p.waitForTimeout(180);await p.screenshot({path:out+'/tetra539-countdown.png'})}await api('disableAI');await sync(p,4100);await p.waitForFunction(()=>c.tetraUI539.renderer.pads.complete&&c.tetraUI539.renderer.ocean.complete);
  const fit=await p.evaluate(()=>({width:document.body.scrollWidth,height:document.body.scrollHeight,stage:document.querySelector('[data-tt-stage]').getBoundingClientRect().toJSON(),jump:document.querySelector('[data-tt-jump]').getBoundingClientRect().toJSON(),scale:visualViewport.scale}));check(fit.width<=width,'no horizontal overflow');check(fit.jump.bottom<=height,'jump button visible');check(fit.stage.height>=220,'usable play area');
  let g=await api('state');const first=g.course.safeRoutes[0][1];await jump(p,first,{shot:width===390});
  // A canceled pointer never releases a jump, including browser gesture cancellation.
  const j=await p.locator('[data-tt-jump]').boundingBox();await p.mouse.move(j.x+j.width/2,j.y+j.height/2);await p.mouse.down();await sync(p,350);await p.locator('[data-tt-jump]').dispatchEvent('pointercancel',{pointerId:1});await p.mouse.up();await sync(p,100);check((await api('state')).players[0].chargeAt===null,'pointercancel clears charge');check(!(await api('state')).players[0].flight,'cancel never jumps');
  if(width===390){await p.mouse.move(j.x+j.width/2,j.y+j.height/2);await p.mouse.down();await sync(p,250);await p.reload();await p.waitForFunction(()=>window.qaReady);await sync(p,100);check((await api('state')).players[0].chargeAt===null,'reload cancels orphaned charge');await p.mouse.up();}
  // Missing a platform gives a splash and returns to the checkpoint without losing the race.
  await api('place',{seat:0,padId:first});await sync(p,100);const bad=await world(p,g.course.pads[first].x-350,g.course.pads[first].y);await p.mouse.move(bad.x,bad.y);await p.mouse.down();await sync(p,950);await p.mouse.up();await sync(p,950);check((await api('state')).players[0].fallAt!==null,'miss causes fall');if(width===390)await p.screenshot({path:out+'/tetra539-splash.png'});await sync(p,1700);check((await api('state')).players[0].padId===0,'respawn at start');
  // Touch and mouse input both route through pointer capture; double taps cannot zoom.
  await p.locator('[data-tt-jump]').dblclick();await sync(p,100);check(await p.evaluate(()=>visualViewport.scale)===1,'no double-tap zoom');
  const cdp=await p.context().newCDPSession(p),touch=await p.locator('[data-tt-jump]').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touch.x+touch.width/2,y:touch.y+touch.height/2}]});await sync(p,300);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await sync(p,100);check((await api('state')).players[0].chargeAt===null,'real touch cancellation');await cdp.detach();
  if(width===390){
   await api('place',{seat:0,padId:g.course.safeRoutes[0][6]});await sync(p,100);await jump(p,g.course.safeRoutes[0][7]);await jump(p,g.course.checkpoints[1]);check((await api('state')).players[0].checkpoint===1,'checkpoint earned by actual landing');await p.screenshot({path:out+'/tetra539-checkpoint.png'});
   g=await api('state');const low=g.course.shortRoutes[1][2];await api('place',{seat:0,padId:low,checkpoint:1});await sync(p,50);g=await api('state');const at=16000*Math.ceil((g.elapsed+3050)/16000);await sync(p,at-2800-g.elapsed);check(await p.locator('[data-tt-wave]').evaluate(e=>e.classList.contains('is-danger')),'wave warning');await p.screenshot({path:out+'/tetra539-warning.png'});await sync(p,2850);check((await api('state')).players[0].fallAt!==null,'wave knocks player off low pad');await p.screenshot({path:out+'/tetra539-wave.png'});await sync(p,1700);check((await api('state')).players[0].padId===g.course.checkpoints[1],'wave recovery uses earned checkpoint');
  }
  await sync(p,155000);await p.waitForSelector('.tt-result539');check(await p.locator('.tt-results539 article').count()===4,'4 result rows');check(await p.evaluate(()=>!document.querySelector('meta[name="viewport"]').content.includes('user-scalable=no')),'restore zoom');if(width===390)await p.screenshot({path:out+'/tetra539-result.png',fullPage:true});await p.locator('[data-party-result490="again"]').click();await p.waitForSelector('.tt-lobby539');await start(p);await api('disableAI');await sync(p,155000);await p.waitForSelector('.tt-result539');await p.locator('[data-party-result490="list"]').click();await p.waitForSelector('[data-party-game462="tetra"]');results.push({width,height,fit,chargeRelease:true,landing:true,pointerCancel:true,touchCancel:true,splashRespawn:true,timeout:true,replay:true,returnToList:true,zoomRestored:true});await p.close();
 }
 console.log('four real WebSocket clients');await api('reset',{humans:4});const pages=[];for(let i=0;i<4;i++)pages.push(await open(390,844,'p'+i));for(const p of pages)await p.locator('[data-party-action462="ready"]').click();await pages[0].locator('[data-tt-action="start"]').click();await pages[0].waitForFunction(()=>c.state.tetra.phase==='countdown');await sync(pages[0],4100);
 await api('run',{running:true});await pages[0].waitForTimeout(450);await api('run',{running:false});check(await pages[0].evaluate(()=>c.state.tetra.course.pads.length)===37,'course retained through frames');
 const g=await api('state');for(let i=0;i<4;i++){await api('place',{seat:i,padId:g.course.safeRoutes[2][7],checkpoint:2});await sync(pages[i],100);await jump(pages[i],g.course.checkpoints[3]);}
 for(const p of pages)await p.waitForSelector('.tt-result539');const outcome=await pages[0].evaluate(()=>c.state.tetra.results);check(outcome.every(r=>r.finishedAt!==null),'4 human goals');for(const p of pages)check(JSON.stringify(await p.evaluate(()=>c.state.tetra.results))===JSON.stringify(outcome),'identical results across clients');await pages[0].screenshot({path:out+'/tetra539-victory.png',fullPage:true});results.push({fourWebSocketClients:true,courseRetained:true,fourHumanGoals:true,identicalResults:true});for(const p of pages)await p.close();
 check(!errors.length,errors.join('\n'));const report={engine:await browser.version(),viewportEmulation:'Chromium mobile touch; not physical iPhone Safari',baseCharacterCatalog:'QA-only character placeholders for missing original modules. Production game view, canvas, generated artwork, rules and online coordinator are used unchanged.',results,errors,baseAssetsMissing:[...new Set(baseAssetsMissing)]};await writeFile(doc+'/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(e){const p=browser.contexts()[0]?.pages()[0];if(p){await p.screenshot({path:out+'/tetra539-debug.png'});console.log('debug',await p.evaluate(()=>({error:c.error,phase:c.state.tetra?.phase,player:c.state.tetra?.players[0],ui:{charge:c.tetraUI539?.chargeStart,pending:c.tetraUI539?.pendingRelease,angle:c.tetraUI539?.angle}})))}console.log('errors',errors);throw e}finally{await browser.close();server.kill()}
