import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {createHash} from 'node:crypto';
import {SPECIES} from '../../src/data/species.js';import {SKILLS} from '../../src/data/skills.js';
import {allSpeciesSkills,allLearnedSkills,maxMp,effectiveSkillMpCost} from '../../src/battle/SkillSystem.js';
import {createMonster,calculatedStats} from '../../src/models/Monster.js';
import {createFloorBossChallengeEncounter} from '../../src/core/FloorBossChallengeSystem.js';import {balanceTeamBattleEnemies} from '../../src/core/TeamBattleBalanceSystem.js';
import * as floor from '../../src/data/floorBosses.js';import * as end from '../../src/core/EndgameSystem.js';
import * as chapter from '../../src/chapterTwo/ChapterTwoSystem.js';import * as elite from '../../src/chapterTwo/ChapterTwoElite393.js';
import * as campaign from '../../src/core/Campaign100System.js';import * as pool from '../../src/core/EncounterPoolSystem.js';
import * as hero from '../../src/core/CampaignHeroEncounterSystem.js';import * as heroLoadout from '../../src/core/CampaignHeroLoadoutSystem.js';
import * as post from '../../src/core/Postgame361System.js';import * as memory from '../../src/core/RoyalMemory379.js';
import {COOP_BOSS_CATALOG} from '../../online-server/src/CoopBossCatalog.js';import {WEEKLY_RAID_BOSSES,WEEKLY_RAID_MODIFIERS} from '../../online-server/src/WeeklyRaidCatalog.js';
import {coopTechniqueRecipes} from '../../online-server/src/CoopTechniqueCatalog.js';
const root=path.resolve(new URL('../../',import.meta.url).pathname),out=root+'/docs/build414/';fs.mkdirSync(out,{recursive:true});
const write=(name,data)=>fs.writeFileSync(out+name,JSON.stringify(data,null,2));
const players=Object.values(SPECIES).map(s=>{const skills=allSpeciesSkills(s.id);const levels=[1,100,1000,5000,10000].map(level=>{const m=createMonster(s.id,{level,rank:1,plus:0});return {level:m.level,stats:calculatedStats(m),maxMp:maxMp(m),costs:skills.map(k=>({id:k.id,cost:effectiveSkillMpCost(m,k),unlocked:m.level>=(k.unlock?.value??1)}))}});return {...s,resolvedSkills:skills,benchmarks:levels,fieldUnlock:pool.campaignEncounterUnlockFloor(s)};});
write('characters.json',{scope:'species and resolved native skills; rank1 plus0 no equipment baseline, not recommended build',species:players,legacySkills:SKILLS});
const source=fs.readFileSync(root+'/src/main.js','utf8'),imports={};
const selected=['applyEnemyMultiplier','prepareEnemyEntry','hydrateEndgameEnemy','applyEnemyMagicCircleProfile','applyFloorBossSignatureProfile','makeBattleEnemy','milestoneBossEntry','floorBossEnemy','normalizedElement'];
const functions=selected.map(name=>{const start=source.indexOf('function '+name+'(');if(start<0)throw Error(name);const rest=source.slice(start),next=rest.slice(1).search(/\n(?:async )?function /);return next<0?rest:rest.slice(0,next+1)}).join('\n');
// Import actual declaration bindings needed by the extracted production factories.
const wanted=['SPECIES','createEnemyBattleState','endgameCharacter','endgameFactionStatMultiplier','applyEliteModifiers','enemyHiddenProfileForFloor','equipmentStatMultiplier','applyCampaignEndgameBalance','applyCampaignHeroLoadout','CAMPAIGN_HERO_PROFILES','canonicalAttribute','equipmentHolderRateForFloor','equipmentSlotsForFloor','rollEnemyEquipmentRarity','enemyEquipmentLevelForFloor','createEquipment','campaignEndgameCircle','rollEnemyMagicCircle','CAMPAIGN_MAX_FLOOR','campaignFloorToLegacyFloor','ENDGAME_BOSSES','WORLD_MAX_FLOOR','bossLevelForFloor','milestoneBossIdsForFloor','floorBossDefinitionById','floorBossDefinitionForFloor','FLOOR_BOSS_CATALOG'];
for(const match of source.matchAll(/import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]/g)){const bindings=match[1].split(',').map(s=>s.trim().split(/\s+as\s+/));if(!bindings.some(([a,b])=>wanted.includes(b??a)))continue;const mod=await import(path.resolve(root+'/src',match[2].split('?')[0]));for(const[a,b]of bindings)if(wanted.includes(b??a))imports[b??a]=mod[a];}
for(const k of wanted)if(!(k in imports))throw Error('Missing production import '+k);
const slot=source.match(/const ENEMY_EQUIPMENT_SUBSLOTS=Object.freeze\(\[[\s\S]*?\]\);/)[0];
let seed=414;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const old=Math.random;Math.random=random;
const state={player:{currentFloor:1,maxFloor:100},monsters:[],party:[]};const ctx=vm.createContext({...imports,Math,Date,console,save:{state}});vm.runInContext(slot+'\n'+functions,ctx);
const clean=e=>JSON.parse(JSON.stringify(e,(k,v)=>['id'].includes(k)?v:typeof v==='function'?undefined:v));
const campaignBosses=[];for(let f=1;f<=100;f++){state.player.currentFloor=f;const ids=campaign.campaignMilestoneBossIds(f);for(const id of ids.length?ids:[null]){const entry=ctx.floorBossEnemy(id);const unit=ctx.makeBattleEnemy(entry);campaignBosses.push({floor:f,id:unit.campaignBossId,unit:clean(unit),candidateSupports:pool.eligibleCampaignEncounterSpecies(Object.values(SPECIES),f).map(s=>s.id)});}}
write('campaign-bosses.json',{scope:'production entry and enemy factory, seed414 equipment roll; all leader variants, supports represented by eligible pool, not all random combinations',bosses:campaignBosses});
write('floor-boss-definitions.json',floor.FLOOR_BOSS_CATALOG);write('endgame-characters.json',end.ENDGAME_BOSSES);write('floor-boss-skills.json',floor.FLOOR_BOSS_CATALOG.map(b=>({id:b.id,actions:b.actionIds.map(id=>floor.floorBossActionInfo('floorBoss:'+id)),contractSkills:allLearnedSkills({speciesId:b.speciesId,floorBossCatalogId:b.id,level:10000})})));
const trials=[];state.player.currentFloor=100;for(let i=1;i<=112;i++){const s={player:{currentFloor:100,maxFloor:100},monsters:[],party:[]};end.normalizeEndgameState(s).trials.loop=1;const e=end.createEndgameTrialEncounter(s,i);trials.push({...e,enemies:e.enemies.map(x=>clean(ctx.makeBattleEnemy(x)))});}write('corridor.json',{scope:'first loop native factory; no battle simulation',trials});
const manual=[];for(const id of Object.keys(end.ENDGAME_BOSSES))for(const tier of end.ENDGAME_CHALLENGE_TIERS){const s={player:{currentFloor:100,maxFloor:100},monsters:[],party:[]};const e=end.applyPreludeToEncounter(end.createEmergencyEncounter(s,id),tier);manual.push({boss:id,tier,units:e.enemies.map(x=>clean(ctx.makeBattleEnemy(x)))});}write('manual-trials.json',{scope:'floor100 reference; chosen tier, actual factory, seed414; raw emergency base depends on entry floor',manual});
const chapters=[];for(const [id,definition] of Object.entries(chapter.ENCOUNTERS)){const runs=definition.elite393?[1,2,3].map(n=>({area:definition.area,eliteTier393:n,challengeTier:0})):Array.from({length:6},(_,n)=>({area:definition.area??0,challengeTier:n}));for(const run of runs){const entries=chapter.chapterTwoEnemyEntries(id,run);const units=entries.map((e,i)=>{const u=ctx.makeBattleEnemy(e,i);chapter.tuneChapterTwoEnemy(u,id,i,run);if(u.chapterTwoTactics382)ctx.applyEnemyMagicCircleProfile(u,u.enemyMagicCircle);return clean(u)});chapters.push({id,run,units});}}
write('chapter-two.json',{scope:'61 definitions, challenge tiers0..5 and elite1..3; roaming resolver may redirect definitions',areas:chapter.CHAPTER_TWO_AREAS,definitions:chapter.ENCOUNTERS,eliteTiers:elite.CHAPTER_TWO_ELITE_TIERS393,cases:chapters});
const heroes=[];for(const id of hero.CAMPAIGN_HERO_IDS)for(const stage of [0,...Array.from({length:memory.MEMORY_MAX_STAGE},(_,i)=>i+1)]){const level=stage?memory.memoryLevel(stage):hero.CAMPAIGN_HERO_FINAL_LEVEL;const u={campaignHeroId:id,level};heroLoadout.applyCampaignHeroLoadout(u);post.tuneFinalHero(u,{count:4,stage:stage?1:0});heroes.push({id,stage,unit:clean(u)});}write('heroes.json',{scope:'4-member final battle plus19 memory stages; hero resonance and fortitude are dynamic, not simulated',profiles:hero.CAMPAIGN_HERO_PROFILES,cases:heroes});
write('online.json',{scope:'repository server code; deployed server state not inspected',coop:COOP_BOSS_CATALOG,raid:WEEKLY_RAID_BOSSES,modifiers:WEEKLY_RAID_MODIFIERS,techniques:coopTechniqueRecipes()});
const discovery=Object.fromEntries(floor.FLOOR_BOSS_CATALOG.map(b=>[b.id,true]));
const rematches=floor.FLOOR_BOSS_CATALOG.map(b=>{const s={floorBossChallenges:{discovered:discovery}};const e=createFloorBossChallengeEncounter(s,b.id);return{id:b.id,units:e.enemies.map(x=>clean(ctx.makeBattleEnemy(x)))}});
write('floor-rematches.json',rematches);
const referenceIds=['fire_dragon','frost_dragon','angelic_orb','dark_knight'].filter(id=>SPECIES[id]);const referenceParty=referenceIds.map(id=>createMonster(id,{level:1000,rank:1,plus:0}));
const teams=[];for(let stage=1;stage<=90;stage++){const s={player:{currentFloor:100,maxFloor:100},monsters:referenceParty,party:referenceParty.map(m=>m.id),floorBossChallenges:{discovered:discovery}};const en=end.normalizeEndgameState(s);en.teamBattle.stage=stage;const entries=end.createTeamBattleEncounter(s);const units=entries.map(e=>ctx.makeBattleEnemy(e));balanceTeamBattleEnemies(units,referenceParty.map(calculatedStats),stage);teams.push({stage,referenceIds,referenceLevel:1000,units:units.map(clean)});}
write('team-trials.json',{scope:'first90 stages fixed four-unit Lv1000 reference, not win-rate',cases:teams});
Math.random=old;
const summary={species:players.length,skills:players.reduce((n,s)=>n+s.resolvedSkills.length,0),floorBosses:floor.FLOOR_BOSS_CATALOG.length,campaignLeaderVariants:campaignBosses.length,corridor:trials.length,manual:manual.length,chapterDefinitions:Object.keys(chapter.ENCOUNTERS).length,chapterCases:chapters.length,heroCases:heroes.length,rematches:rematches.length,teamStages:teams.length,coop:COOP_BOSS_CATALOG.length,raid:WEEKLY_RAID_BOSSES.length};write('summary.json',summary);console.log(summary);
