import {gatesOpen559,exits559} from './Heist541.js';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function objectiveDeck559(g){const h=g.heist541;return `<div class="hd-goals559" data-hd-goals><div class="hd-seals559" data-hd-seals>${(h?.seals??[]).map(s=>`<button data-hd-goal559="seal:${s.id}" data-hd-seal559="${s.id}" aria-label="封印${s.id+1} ${escape(s.name)}へ向かう"><i class="hd-relic559" aria-hidden="true"></i><span><b>${s.id+1} ${escape(s.short??s.name)}</b><small data-seal-status>未解除</small></span><em data-seal-progress></em></button>`).join('')}</div><div class="hd-exits559" data-hd-exits hidden>${exits559(h).map(e=>`<button data-hd-goal559="gate:${e.id}"><i class="hd-relic559 is-gate" aria-hidden="true"></i><span><b>${escape(e.name)}</b><small>この門へ向かう</small></span><strong>→</strong></button>`).join('')}</div></div>`}
export const channelPanel559=()=>'<div class="hd-channel559" data-hd-channel hidden><div><i class="hd-relic559" aria-hidden="true"></i><b data-hd-channelname></b><strong data-hd-channelvalue></strong></div><div class="hd-channeltrack559"><i data-hd-channelbar></i></div><small data-hd-channelhint></small></div>';
const put=(e,s)=>{if(e&&e.textContent!==String(s))e.textContent=String(s)};
export function paintObjectives559(u,g,p){const h=g.heist541;if(!h)return;const n=u.nodes,open=gatesOpen559(h);n.seals.hidden=open;n.exits.hidden=!open;
 for(const b of u.sealNodes559){const s=h.seals.find(s=>s.id===Number(b.dataset.hdSeal559));if(!s)continue;const alarm=!s.done&&s.alarmUntil>g.elapsed;b.classList.toggle('is-done',s.done);b.classList.toggle('is-alarm',alarm);b.disabled=s.done||!p?.alive||p.hunter&&g.phase==='hiding';put(b.querySelector('[data-seal-status]'),s.done?'解除済':alarm?'反応あり':s.progress?'解除途中':'未解除');b.querySelector('[data-seal-progress]').style.transform=`scaleX(${s.done?1:Math.min(1,(s.progress??0)/(h.sealMs??8000))})`;}
 const active=p?.interacting541;n.channel.hidden=!active;if(!active)return;const seal=h.seals.find(s=>s.id===active.seal),percent=Math.min(100,Math.floor(active.value*100));n.channel.classList.toggle('is-exposed',!!active.exposed);put(n.channelname,active.type==='seal'?`${seal?.short??'封印'}を解除中`:'仲間を救出中');put(n.channelvalue,percent+'%');n.channelbar.style.transform=`scaleX(${active.value})`;put(n.channelhint,active.type!=='seal'?'止まったまま救出':active.exposed?'部屋に音が響いている！':active.team?'協力中 · 最短６秒で解除':'１人８秒 · ３秒から音が響く');
}
export function goal559(g,key){const h=g.heist541;if(!h)return null;const [kind,id]=key.split(':');return kind==='gate'&&gatesOpen559(h)?exits559(h).find(e=>e.id===id):kind==='seal'&&!gatesOpen559(h)?h.seals.find(s=>s.id===Number(id)&&!s.done):null}
