import {setupHeist541,ability541,tickHeist541,goalHeist541,publicHeist541} from './Heist541.js';
import {alarmTarget559} from './Tactics559.js';
// Authoritative Build538 rules, shared by the server and verification. No DOM dependencies.
import {makeMap537,furniture537,free537,line537,path537,nav537,nearest537} from './Map537.js';
export const HIDE536=Object.freeze({width:4800,height:4400,prepare:20000,duration:180000,step:50,shots:3,charge:10000,stamina:15000,recovery:3000,recoverDelay:600,resume:4500,range:235,sight:560,hiderSight:950,hunterSpeed:260,hiderSpeed:230,shakeEvery:30000,shakeLife:2400});
export const PROPS536=Object.freeze(['宝箱','樽','木箱','ロープ','瓶','壺','やかん','麻袋','魚かご','腰かけ','ランタン','ヤシの鉢']);
export const clamp536=(v,a,b)=>Math.max(a,Math.min(b,v));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),copy=x=>structuredClone(x);
function rng(g){let x=g.seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;g.seed=x>>>0||537;return g.seed/4294967296}
const token=g=>Math.floor(rng(g)*0xffffffff).toString(36).padStart(7,'0');
const event=(g,type,extra={})=>{g.events.push({id:++g.eventSeq,type,at:g.elapsed,...extra});g.events=g.events.slice(-32)};
const hunter=g=>g.players[g.hunterSeat];
export const shaking537=g=>g.phase==='play'&&g.elapsed>=HIDE536.shakeEvery&&g.elapsed%HIDE536.shakeEvery<HIDE536.shakeLife;
const sees=(g,p,o)=>!!p&&distance(p,o)<=(p.hunter?HIDE536.sight:HIDE536.hiderSight)&&line537(g.map,p,o);
export function makeHide536({id,code,partyId,hostId,members,now=0}){return{id,code,partyId462:partyId,hostId,game:'hide',rulesVersion:7,phase:'lobby',revision:0,createdAt:now,updatedAt:now,lastAt:now,serverAt:now,role:'random',members:copy(members),players:[],objects:[],events:[],eventSeq:0,results:[],winnerIds:[]}}
export function startHide536(g,now,seed=537){
 g.seed=seed||537;g.rulesVersion=7;g.map=makeMap537(seed);g.map.hunter={...nearest537(g.map,{x:g.map.spawn.x,y:g.map.spawn.y+700})};g.players=g.members.filter(m=>!m.departed).map((m,i)=>({playerId:m.playerId,name:m.name,seat:i,ai:!!m.ai,speciesId:m.choice?.speciesId??'slime',color499:m.color499??['blue','green','pink','orange'][i]}));
 while(g.players.length<4){const i=g.players.length;g.players.push({playerId:'AI-'+g.id+'-'+i,name:['キャプテン','コソコソ','ふわり','コトコト'][i],seat:i,ai:true,speciesId:['slime','wolf','goblin','skeleton'][i],color499:g.aiColors500?.[i]??['blue','green','pink','orange'][i]})}
 const host=g.players.findIndex(p=>p.playerId===g.hostId),others=g.players.filter(p=>p.seat!==host);
 g.hunterSeat=g.role==='hunter'?host:g.role==='hider'?others[Math.floor(rng(g)*others.length)].seat:Math.floor(rng(g)*4);
 Object.assign(g,{phase:'hiding',startAt:now+HIDE536.prepare,endAt:now+HIDE536.prepare+HIDE536.duration,lastAt:now,serverAt:now,elapsed:-HIDE536.prepare,shots:HIDE536.shots,shotReadyAt:0,rechargeAt:0,events:[],eventSeq:0,shakeRound:0,results:[],winnerIds:[]});
 g.objects=furniture537(g.map,seed).map(o=>({...o,id:token(g)}));
 for(const p of g.players){const isHunter=p.seat===g.hunterSeat,origin=isHunter?g.map.hunter:g.map.spawn,pos=nearest537(g.map,{x:origin.x+(p.seat-1)*85,y:origin.y+(!isHunter?70:0)}),first=Math.floor(rng(g)*12),second=(first+1+Math.floor(rng(g)*11))%12;Object.assign(p,{x:pos.x,y:pos.y,hunter:isHunter,alive:true,objectId:token(g),choices:[first,second],kind:first,lastSeq:0,moving:false,face:-Math.PI/2,catches:0,distance:0,stamina:HIDE536.stamina,exhausted:false,restMs:0,auto:p.ai,route:[],goal:null,brain:{next:-HIDE536.prepare,memory:{},suspects:{}}})}
 setupHeist541(g);g.updatedAt=now;g.revision++;return g;
}
export function objects536(g,viewerId){const self=g.players.find(p=>p.playerId===viewerId),isHunter=self?.hunter||!self;if(!g.map||g.phase==='hiding'&&isHunter)return[];const viewer=self??hunter(g);return[
 ...(g.decoys541??[]).filter(o=>!o.checked&&o.until>g.elapsed).map(o=>({id:o.id,x:o.x,y:o.y,kind:o.kind,checked:false})),
 ...g.objects.map(o=>({id:o.id,x:o.x,y:o.y,kind:o.kind,checked:o.checked})),
 ...g.players.filter(p=>!p.hunter&&p.alive).map(p=>({id:p.objectId,x:p.x,y:p.y,kind:p.kind,checked:false,...(!isHunter?{owner:p.playerId,seat:p.seat,moving:p.moving}:{}),...(shaking537(g)?{shaking:true}:{})}))
 ].filter(o=>o.owner===viewerId||sees(g,viewer,o)).sort((a,b)=>a.id.localeCompare(b.id))}
export function finishHide536(g,side,reason){if(g.phase==='result')return;g.phase='result';g.winningSide=side;g.reason=reason;g.winnerIds=g.players.filter(p=>(side==='hunter')===p.hunter).map(p=>p.playerId);g.finaleUntil=g.lastAt+2800;g.results=g.players.map(p=>({playerId:p.playerId,name:p.name,seat:p.seat,hunter:p.hunter,escaped:!!p.escaped541,survived:!p.hunter&&p.alive,exit:p.escapeGate559??null,seals:p.seals541??0,rescues:p.rescues559??0,catches:p.catches,won:g.winnerIds.includes(p.playerId),rank:g.winnerIds.includes(p.playerId)?1:2}));event(g,'finish',{side,reason});g.updatedAt=g.lastAt;g.revision++}
export function attackHide536(g,p,id){if(g.phase!=='play'||!p?.hunter||g.shots<=0||g.elapsed<g.shotReadyAt)return false;const o=objects536(g,p.playerId).find(o=>o.id===id);if(!o||o.checked||distance(p,o)>HIDE536.range)return false;if(g.shots===HIDE536.shots)g.rechargeAt=g.elapsed+HIDE536.charge;g.shots--;g.shotReadyAt=g.elapsed+700;p.face=Math.atan2(o.y-p.y,o.x-p.x);const target=g.players.find(t=>!t.hunter&&t.alive&&t.objectId===id);if(target){target.alive=false;target.moving=false;target.caughtAt=g.elapsed;p.catches++;event(g,'catch',{x:o.x,y:o.y,seat:target.seat,name:target.name});if(g.players.every(t=>t.hunter||!t.alive))finishHide536(g,'hunter','caught')}else{const item=g.objects.find(t=>t.id===id)??g.decoys541?.find(t=>t.id===id);if(item)item.checked=true;event(g,'miss',{x:o.x,y:o.y})}return true}
// One deliberate furniture tap approaches a visible object, then investigates once.
// Losing sight, a new movement command or a completed check cancels the reservation.
export function inspectMove563(g,p,input){p.inspect563=null;if(!input.inspect563||!p.hunter||!p.alive||g.phase!=='play')return;const o=objects536(g,p.playerId).find(o=>o.id===input.inspect563&&!o.checked);if(!o){delete input.inspect563;input.target=null;return;}p.inspect563=o.id;input.steer=null;if(distance(p,o)<=HIDE536.range-5){input.target=null;if(g.shots>0&&g.elapsed>=g.shotReadyAt){input.attack=o.id;delete input.inspect563;p.inspect563=null;}}else input.target={x:o.x,y:o.y};}
function move(g,p,input,dt){p.moving=false;if(!p.alive||p.hunter&&g.phase==='hiding')return;let budget=(p.hunter?HIDE536.hunterSpeed:HIDE536.hiderSpeed*(p.exhausted?.5:1))*dt;
 if(input.steer&&g.lastAt-(input.receivedAt??g.lastAt)<700){p.route=[];p.goal=null;const d=Math.hypot(input.steer.x,input.steer.y);if(d<.05)return;const dx=input.steer.x/Math.max(1,d)*budget,dy=input.steer.y/Math.max(1,d)*budget,old={x:p.x,y:p.y};if(free537(g.map,p.x+dx,p.y+dy)){p.x+=dx;p.y+=dy}else if(free537(g.map,p.x+dx,p.y)){p.x+=dx}else if(free537(g.map,p.x,p.y+dy)){p.y+=dy}const moved=distance(p,old);p.moving=moved>.1;p.distance+=moved;if(p.moving)p.face=Math.atan2(p.y-old.y,p.x-old.x);return}
 const target=input.target;if(!target){p.route=[];p.goal=null;return}if(!p.goal||distance(p.goal,target)>1){p.goal={...target};p.route=path537(g.map,p,target)}
 while(budget>0&&p.route.length){const q=p.route[0],d=distance(p,q);if(d<.01){p.route.shift();continue}const step=Math.min(d,budget),dx=(q.x-p.x)/d*step,dy=(q.y-p.y)/d*step;if(!free537(g.map,p.x+dx,p.y+dy)){p.route=[];p.goal=null;break}p.x+=dx;p.y+=dy;p.face=Math.atan2(dy,dx);p.distance+=step;p.moving=true;budget-=step;if(d<=step+.01)p.route.shift()}
}
function ai(g,p){const b=p.brain,input={};if(!p.hunter&&g.phase==='play'&&(p.stamina<5000||b.resting)&&!sees(g,p,hunter(g))){b.resting=p.stamina<HIDE536.stamina;return{target:null}}b.resting=false;if(g.elapsed<b.next)return{target:b.target};b.next=g.elapsed+330+rng(g)*180;
 if(p.hunter){if(g.phase!=='play')return{};if(g.elapsed>=(p.abilityReady541??0))input.ability541=true;const view=objects536(g,p.playerId);for(const o of view){const old=b.memory[o.id];if(!o.checked&&(o.shaking||old&&g.elapsed-old.at<900&&distance(old,o)>8))b.suspects[o.id]=g.elapsed+3600;b.memory[o.id]={x:o.x,y:o.y,at:g.elapsed}}
 const suspect=view.filter(o=>!o.checked&&b.suspects[o.id]>g.elapsed).sort((a,b)=>distance(a,p)-distance(b,p))[0]??alarmTarget559(g,p,view);
 if(suspect){if(b.pursuit!==suspect.id){b.pursuit=suspect.id;b.attackAfter=g.elapsed+750+rng(g)*750}b.target={x:suspect.x,y:suspect.y};b.lastSeen=g.elapsed;if(distance(p,suspect)<=HIDE536.range&&g.elapsed>=b.attackAfter){input.attack=suspect.id;b.attackAfter=g.elapsed+1000}}
 else{b.pursuit=null;const room=goalHeist541(g,p);b.target=room?{x:room.x,y:room.y}:{x:g.map.rooms[0].cx,y:g.map.rooms[0].cy};}
 if(!suspect&&g.elapsed>45000&&g.shots===HIDE536.shots&&rng(g)<.025){const close=view.filter(o=>!o.checked&&distance(o,p)<HIDE536.range);if(close.length)input.attack=close[Math.floor(rng(g)*close.length)].id}
 }else{const h=hunter(g),near=g.phase==='play'&&sees(g,p,h)&&distance(p,h)<620,danger=near&&(p.moving||shaking537(g)||distance(p,h)<230||b.fleeUntil>g.elapsed);
 if(danger){if(g.elapsed>=(p.abilityReady541??0))input.ability541=true;if(!b.target||distance(p,b.target)<65||g.elapsed>(b.rethink??0)){let best,score=-1;for(const q of nav537(g.map).filter((q,i)=>i%13===0&&distance(q,p)>300&&distance(q,p)<800)){const route=path537(g.map,p,q);if(!route.length)continue;const first=route[0],value=distance(q,h)+Math.min(distance(first,h),distance(p,h))*1.5+(line537(g.map,h,q)?0:400)+rng(g)*80;if(value>score){score=value;best=q}}b.target=best;b.rethink=g.elapsed+1600;b.fleeUntil=g.elapsed+2600}}
 else{const objective=goalHeist541(g,p);b.target=objective?{x:objective.x,y:objective.y}:null;}
 }
 return{...input,target:b.target};
}
export function advanceHide536(g,now,inputs=new Map(),auto=new Set()){if(!['hiding','play'].includes(g.phase)||!g.map)return;const steps=Math.min(200,Math.floor((now-g.lastAt)/HIDE536.step));for(let n=0;n<steps&&g.phase!=='result';n++){g.lastAt+=HIDE536.step;g.elapsed=g.lastAt-g.startAt;if(g.phase==='hiding'&&g.elapsed>=0){g.phase='play';event(g,'begin');g.revision++}if(g.phase==='play'&&g.shots<HIDE536.shots&&g.rechargeAt&&g.elapsed>=g.rechargeAt){g.shots++;g.rechargeAt=g.shots<HIDE536.shots?g.rechargeAt+HIDE536.charge:0}const round=Math.floor(Math.max(0,g.elapsed)/HIDE536.shakeEvery);if(round>g.shakeRound){g.shakeRound=round;event(g,'shake')}
 for(const p of g.players){p.auto=p.ai||auto.has(p.playerId);const input=p.auto?ai(g,p):inputs.get(p.playerId)??{};inspectMove563(g,p,input);if(!p.hunter&&p.alive&&p.choices.includes(input.kind))p.kind=input.kind;move(g,p,input,HIDE536.step/1000);if(!p.hunter&&p.alive){if(p.moving){p.restMs=0;if(g.phase==='play'){p.stamina=Math.max(0,p.stamina-HIDE536.step);if(p.stamina===0)p.exhausted=true}}else{p.restMs+=HIDE536.step;if(p.restMs>=HIDE536.recoverDelay)p.stamina=Math.min(HIDE536.stamina,p.stamina+HIDE536.recovery*HIDE536.step/1000);if(p.stamina>=HIDE536.resume)p.exhausted=false}}if(input.ability541)ability541(g,p,()=>token(g));if(input.attack)attackHide536(g,p,input.attack);if(!p.auto){delete input.attack;delete input.kind;delete input.ability541}if(g.phase==='result')break}tickHeist541(g,HIDE536.step,finishHide536);if(g.phase==='play'&&g.elapsed>=HIDE536.duration)finishHide536(g,'hunter','locked')}
 if(now>=g.endAt&&g.phase!=='result'){g.lastAt=now;g.elapsed=HIDE536.duration;finishHide536(g,'hunter','locked')}g.serverAt=now;g.updatedAt=now;
}
export function publicHide536(g,viewerId,{frame=false}={}){const self=g.players.find(p=>p.playerId===viewerId),isHunter=self?.hunter||!self,ended=g.phase==='result';return{id:g.id,code:g.code,game:'hide',rulesVersion:g.rulesVersion??7,hostId:g.hostId,phase:g.phase,revision:g.revision,role:g.role,migrationNote:g.migrationNote,serverAt:g.serverAt??g.lastAt,startAt:g.startAt,endAt:g.endAt,elapsed:g.elapsed,hunterSeat:g.hunterSeat,heist541:publicHeist541(g,isHunter),shots:g.shots,rechargeAt:g.rechargeAt,shotReadyAt:g.shotReadyAt,finaleUntil:g.finaleUntil,...(!frame&&g.map?{map:copy(g.map)}:{}),
 members:g.members.map(m=>({playerId:m.playerId,name:m.name,choice:m.choice?{id:m.choice.id,speciesId:m.choice.speciesId}:null,departed:!!m.departed})),players:g.players.map(p=>({playerId:p.playerId,name:p.name,seat:p.seat,hunter:p.hunter,alive:p.alive,ai:p.ai,auto:p.auto,color499:p.color499,speciesId:p.speciesId,catches:p.catches,...(ended||p.playerId===viewerId||!isHunter&&(!p.hunter||sees(g,self,p))?{x:p.x,y:p.y,face:p.face,moving:p.moving}:{}),...(ended?{kind:p.kind}:{}),...(p.playerId===viewerId?{objectId:p.objectId,kind:p.kind,choices:[...(p.choices??[p.kind])],stamina:p.stamina,exhausted:p.exhausted,restMs:p.restMs,lastSeq:p.lastSeq,inspect563:p.inspect563??null,abilityReady541:p.abilityReady541,sense541:p.sense541,interacting541:p.interacting541,rescued541:p.rescued541}: {})})),objects:objects536(g,viewerId),events:g.events.filter(e=>(!e.viewer||e.viewer===viewerId)&&!(g.phase==='hiding'&&isHunter)&&(!Number.isFinite(e.x)||e.type==='catch'||sees(g,self,e))).map(e=>({...e})),results:copy(g.results),winningSide:g.winningSide,reason:g.reason,winnerIds:[...g.winnerIds]}}
export const signature536=g=>!g?null:g.phase==='lobby'?g:{id:g.id,phase:g.phase==='result'?'result':'play',members:g.members,results:g.phase==='result'?g.results:null};
