import {gatesOpen559,exits559} from './Heist541.js';
import {objectiveDeck559,channelPanel559,paintObjectives559,goal559} from './Objectives559.js';
import {HIDE536,PROPS536,clamp536,shaking537} from './Rules536.js';
import {renderer536,resize536,paint536,worldPoint537} from './Renderer536.js';
import {unlock536,sound536} from './Audio536.js';
import {partySeats462} from '../party/PartyView462.js';
import {resultActions490} from '../party/PartyResults490.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.hideUI536??={seq:0,sound:true,seen:0,limit:24,search:'',targetId:null,destination:null};
const me=(c,g=c.state?.hide)=>g?.players.find(p=>p.playerId===c.transport.selfId);
const clock=c=>Date.now()+(c.offset??0);
const portrait=(c,p)=>c.sgMonster463?.(p.speciesId??p.choice?.speciesId)??'';
export const propArt536=(kind,extra='')=>`<i class="hd-prop536 ${extra}" style="--hd-col:${kind%4};--hd-row:${Math.floor(kind/4)}" aria-hidden="true"></i>`;
const head=c=>`<header class="hd-head536"><button data-party-action462="browse" aria-label="パーティーへ">‹</button><div><small>ABYSS · THE HIDDEN MANOR</small><b>魔王のかくれんぼ</b></div><button data-hd-action="sound" aria-label="音の切り替え">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
function lobby(c,g){const u=ui(c),party=c.state.party,member=g.members.find(m=>m.playerId===c.transport.selfId),pm=party?.members.find(m=>m.playerId===c.transport.selfId),host=g.hostId===c.transport.selfId,roster=c.roster().filter(m=>!u.search||(c.sgSpeciesName463?.(m.raceSpeciesId??m.speciesId)??'').includes(u.search));
 return`<section class="hd536 hd-lobby536">${head(c)}<div class="hd-cover536"><span>鬼１人 × 化ける３人</span><h1>化けて潜入。<br>仲間と、脱出。</h1><p>封印を解け！ 魔王のかくれんぼ</p></div><div class="hd-body536"><div class="hd-facts536"><span>準備20秒＋180秒</span><span>空席はAI</span><span>鬼１人 × 隠れる３人</span></div><div class="hd-rules536"><article><b>♛ 鬼の遊び方</b><p>解除の音がした部屋を探そう。全員捕獲か180秒以内の脱出阻止で勝利！ 攻撃は最大３回、10秒で１回補充。「気配」で近くの敵を探せるよ。</p></article><article><b>✧ 隠れる側の遊び方</b><p>５つの封印から好きな３つを解除。開いた西門・東門のどちらかから１人脱出すれば勝ち！ 身代わりで鬼をまき、庭の檻では仲間を１度だけ救出できる。</p></article></div><p class="hd-note536">館の部屋、庭、森がひと続きの広いフィールド。床タップで目的地へ、指を滑らせると行き先を更新。仲間同士は地図と目印で位置を共有できるよ。変身は下の２択から、移動中でもいつでも切り替えられるよ。封印は１人８秒、２人以上なら６秒。３秒作業すると部屋に音が響く。救出は約３秒。30秒ごとに体が揺れるよ！ 15秒の連続移動で半速に。止まってスタミナを回復しよう。</p>${host?`<h2>部屋主の役割</h2><div class="hd-roles536">${[['random','おまかせ'],['hunter','自分が鬼'],['hider','自分が隠れる']].map(([id,name])=>`<button data-hd-role="${id}" aria-pressed="${g.role===id}">${name}</button>`).join('')}</div>`:`<p>役割設定：${{random:'おまかせ',hunter:'部屋主が鬼',hider:'部屋主が隠れる'}[g.role]}</p>`}<h2>一緒に化ける相棒</h2><input name="hideSearch536" placeholder="魔物の名前で探す" aria-label="魔物を探す" value="${esc(u.search)}"><div class="hd-roster536">${roster.slice(0,u.limit).map(m=>`<button data-hd-monster="${esc(m.id)}" aria-pressed="${member?.choice?.id===m.id}">${portrait(c,{speciesId:m.raceSpeciesId??m.speciesId})}<small>${esc(c.sgSpeciesName463?.(m.raceSpeciesId??m.speciesId)??m.speciesId)}</small></button>`).join('')}</div>${roster.length>u.limit?'<button data-hd-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="hd-error536" role="alert">${esc(c.error||g.migrationNote)}</p><button class="hd-gold536 hd-wide536" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="hd-gold536 hd-wide536" data-hd-action="start" ${!c.ready()||party.members.some(m=>!m.ready||!m.connected||m.atHome)?'disabled':''}>迷いの館と庭園へ！</button>`:'<p>部屋主が開始すると、かくれんぼが始まるよ。</p>'}<small class="hd-note536">通信が切れた場合やホーム滞在中はAIが引き継ぐよ。捕まった後も仲間を見守れます。</small></div></section>`;
}
function play(c,g){const p=me(c),hunt=p?.hunter||!p;return`<section class="hd536 hd-play536 ${hunt?'is-hunter':'is-hider'}">${head(c)}<div class="hd-hud536"><div><small>あなたの役割</small><strong>${!p?'観戦中':hunt?'♛ 探す鬼':'✧ 隠れる側'}</strong></div><div class="hd-time536"><small data-hd-timelabel>残り時間</small><strong data-hd-time>3:00</strong></div><div><small>${hunt?'残りの攻撃':'逃げている仲間'}</small><strong data-hd-counter>${hunt?'3 / 3':'３ / ３'}</strong></div></div><div class="hd-players536">${g.players.map(p=>`<div data-hd-seat="${p.seat}"><span class="hd-seatportrait536">${portrait(c,p)}</span><span><b>${esc(p.name)}</b><small data-hd-seatstatus="${p.seat}">${p.hunter?'鬼':'隠れています'}</small></span></div>`).join('')}</div><div class="hd-stage536" data-hd-stage><canvas data-hd-canvas role="img" aria-label="迷いの館と庭園。床をタップして移動。指を滑らせても移動先を変えられます。鬼は置き物を選んで調べられます。"></canvas><div class="hd-stage-label536"><span data-hd-area>迷いの館と庭園</span><small>床タップで移動 · 指で行き先を更新</small></div><button class="hd-map537" data-hd-action="map" data-hd-map aria-label="館と庭の地図" aria-pressed="false">⌖ 地図</button><div class="hd-shake537" data-hd-shake><span>次のふるふる</span><b data-hd-shaketime>30秒</b></div><div class="hd-notice536" data-hd-notice aria-live="polite"></div>${channelPanel559()}<div class="hd-count536" data-hd-count><span data-hd-countlabel></span><strong data-hd-countnumber></strong><small data-hd-counthelp></small></div><div class="hd-caught536" data-hd-caught hidden><b>見つかっちゃった…！</b><span>庭の檻で救出を待とう（１人１度）。仲間１人が脱出すればチーム勝利！</span></div><div class="hd-network536" data-hd-network hidden>再接続中… AIが引き継いでいるよ</div></div><footer class="hd-deck536"><div class="hd-mission541"><b data-hd-mission>封印 0 / 3</b><span data-hd-objective>５か所から好きな３つを解除</span></div>${objectiveDeck559(g)}<div class="hd-instruction536"><b data-hd-status></b><small data-hd-tip></small></div>${hunt?`<div class="hd-charge538"><span data-hd-charges>● ● ●</span><small data-hd-recharge>攻撃チャージ MAX</small></div><div class="hd-controls536"><button class="hd-ability536" data-hd-action="stop">■ 止まる</button><button class="hd-gold536 hd-investigate536" data-hd-action="attack" data-hd-attack><b>✦ 調べる</b><small data-hd-attackhint>置き物を選ぼう</small></button></div><p class="hd-bottom536">鬼１人 × 隠れる３人。移動しながら調べられるよ。近くの置き物を狙おう！</p>`:`<div class="hd-choice537"><div class="hd-disguises536">${(p?.choices??[]).map(i=>`<button data-hd-prop="${i}" aria-label="${PROPS536[i]}に変身" aria-pressed="${p?.kind===i}">${propArt536(i)}<span>${PROPS536[i]}</span><em>選ぶ</em></button>`).join('')}</div><button class="hd-ability536 hd-stop537" data-hd-action="stop">■<span>止まる</span></button></div><div class="hd-stamina538"><div><span>スタミナ</span><b data-hd-staminalabel>100%</b></div><div class="hd-staminatrack538"><i data-hd-staminabar></i></div><small data-hd-staminatip>止まると回復 · 仲間の位置は地図で確認</small></div>`}<button class="hd-skill541" data-hd-action="ability541" data-hd-skill><b data-hd-skillname></b><small data-hd-skillhint></small></button></footer></section>`}
function result(c,g){const won=g.winnerIds.includes(c.transport.selfId),hunter=g.winningSide==='hunter',reason={caught:'家具に隠れた３人を全員発見！',time:'180秒、魔王の目をかいくぐった！',shots:'魔王の攻撃が尽きた！ 見事に逃げ切り。',locked:'180秒、脱出を阻止！ 生存だけでは脱出成功にならない。',escape:'５つの封印から３つを解除。仲間が門を突破！'}[g.reason];return`<section class="hd536 hd-result536">${head(c)}<div class="hd-result-hero536"><small>迷いの館と庭園 · 決着</small><div class="hd-result-badge536">${won?'VICTORY':'GAME SET'}</div><h1>${hunter?'魔王の勝利！':'脱出、大成功！'}</h1><p>${reason}</p><div class="hd-result559"><span>封印 <b>${g.heist541?.seals.filter(s=>s.done).length??0} / 3</b></span><span>決着 <b>${Math.floor(g.elapsed/1000)}秒</b></span></div><div class="hd-winners536">${hunter?'<img class="hd-kingart536" src="./assets/hide536/hunter.webp" alt="勝利した魔王">':g.players.filter(p=>!p.hunter).map(p=>`<div>${propArt536(p.kind??0)}<span>${esc(p.name)}</span></div>`).join('')}</div><span class="hd-ribbon536">${hunter?esc(g.players[g.hunterSeat].name)+' が館を守った！':'隠れる３人チームの勝利'}</span></div><div class="hd-body536">${resultActions490(c)}<div class="hd-standings536">${g.results.map(r=>`<article class="${r.won?'is-winner':''}"><strong>${r.won?'♛':'·'}</strong><span class="hd-seatportrait536">${portrait(c,g.players[r.seat])}</span><div><b>${esc(r.name)}</b><small>${r.hunter?'鬼 · '+r.catches+'人を発見':r.escaped?'隠れる側 · '+(r.exit==='west'?'西門':r.exit==='east'?'東門':'庭門')+'から脱出':r.survived?'隠れる側 · '+(r.won?'脱出を援護':'生存・脱出できず'):'隠れる側 · '+(r.won?'捕獲・仲間が脱出':'捕獲されました')}</small></div><span>${r.won?'勝利':'健闘'}</span></article>`).join('')}</div><p class="hd-note536">鬼の残り攻撃 ${g.shots}回 · ${Math.min(180,Math.floor(g.elapsed/1000))}秒で決着</p></div></section>`}
export function hideView536(c){const g=c.state.hide,u=ui(c);if(u.gameId!==g.id){Object.assign(u,{gameId:g.id,seq:0,seen:0,limit:24,search:'',targetId:null,destination:null,notice:null,mapOpen:false,steering:null})}return g.phase==='lobby'?lobby(c,g):g.phase==='result'?result(c,g):play(c,g)}
export function hideReceive536(c){const g=c.state?.hide;if(!g)return;const u=ui(c);if(u.mapId540===g.id&&u.map540&&g.map?.version===u.map540.version)g.map=u.map540;else if(g.map){u.mapId540=g.id;u.map540=g.map}u.seq=Math.max(u.seq,me(c)?.lastSeq??0)}
export function hideFrame536(c,m){if(m.selfId!==c.transport.selfId||!c.state?.hide||m.hide?.id!==c.state.hide.id||m.hide.serverAt<c.state.hide.serverAt)return;const old=c.state.hide;c.offset=m.serverNow-Date.now();c.state.hide={...m.hide,map:m.hide.map??old.map};hideReceive536(c);if((old.phase==='result')!==(m.hide.phase==='result'))c.render()}
function send(c,payload){const g=c.state?.hide;if(!g||!['hiding','play'].includes(g.phase)||!me(c)?.alive||!c.ready())return false;return c.raw('hideInput536',{gameId:g.id,kind:'input',seq:++ui(c).seq,...payload})}
const put=(e,s)=>{if(e&&e.textContent!==String(s))e.textContent=String(s)};
function paint(c){const u=ui(c),g=c.state.hide,n=u.nodes,p=me(c),hunt=p?.hunter||!p,at=clock(c),elapsed=g.phase==='hiding'?Math.min(0,at-g.startAt):g.elapsed+Math.min(180,Math.max(0,at-g.serverAt)),left=Math.max(0,Math.ceil((HIDE536.duration-elapsed)/1000)),alive=g.players.filter(p=>!p.hunter&&p.alive).length,shaking=shaking537(g),next=30-Math.floor(Math.max(0,elapsed)/1000)%30;
 paint536(u.renderer,g,c.transport.selfId,u,at,u.reduced);put(n.time,g.phase==='hiding'?Math.max(0,Math.ceil((g.startAt-at)/1000)):`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`);put(n.timelabel,g.phase==='hiding'?'隠れる準備':'残り時間');n.time.classList.toggle('is-danger',left<=15&&g.phase==='play');put(n.counter,hunt?g.shots+' / 3':alive+' / ３');n.count.hidden=g.phase!=='hiding';n.count.classList.toggle('is-blind',hunt);put(n.countlabel,hunt?'まだ、見ちゃダメ。':'２択で変身！ 隠れ場所を探そう');put(n.countnumber,Math.max(0,Math.ceil((g.startAt-at)/1000)));put(n.counthelp,hunt?'３人が館や庭のどこかに隠れています…':'開始後も自由に動けるよ');n.network.hidden=c.connected();n.caught.hidden=!p||p.hunter||p.alive;
 const area=g.map?.rooms.find(r=>p&&p.x>=r.x&&p.x<r.x+r.w&&p.y>=r.y&&p.y<r.y+r.h);put(n.area,area?.name??g.map?.zones?.find(z=>p&&p.x>=z.x&&p.x<z.x+z.w&&p.y>=z.y&&p.y<z.y+z.h)?.name??'木漏れ日の庭');put(n.shaketime,shaking?'ふるふる！':next+'秒');n.shake.classList.toggle('is-danger',shaking||next<=5);n.shake.hidden=g.phase==='hiding'||u.mapOpen;n.map.setAttribute('aria-pressed',String(!!u.mapOpen));put(n.map,u.mapOpen?'× 閉じる':'⌖ 地図');
 for(const player of g.players){const el=u.seats[player.seat];el.classList.toggle('is-caught',!player.alive);put(u.seatStatus[player.seat],player.hunter?'鬼 · '+player.catches+'人発見':player.alive?(player.auto?'隠れ中 · AI':'隠れ中'):'捕まった')}
 for(const e of g.events){if(e.id<=u.seen)continue;u.seen=e.id;if(elapsed-e.at>1600)continue;sound536(u,e.type==='shake'?'noise':e.type);if(e.type==='alarm559')u.notice={text:`${e.name}で解除の音！`,until:at+3000,alarm:true};if(e.type==='gates559')u.notice={text:hunt?'西門・東門が開いた！ 脱出を阻止！':'２つの門が開いた！ 好きな門へ！',until:at+3500};if(e.type==='seal541')u.notice={text:e.name+'の封印を解除！',until:at+2300};if(e.type==='rescue541')u.notice={text:e.name+'を救出！',until:at+2300};if(e.type==='begin')u.notice={text:hunt?'館と庭から３人を探せ！':'鬼が動き出した！',until:at+2100};if(e.type==='catch')u.notice={text:e.name+' が見つかった！',until:at+2200};if(e.type==='shake')u.notice={text:hunt?'ふるふるタイム！ 近くをよく見て！':'体がふるふる…！ 近くに鬼はいない？',until:at+2300}}
 n.notice.classList.toggle('is-alarm559',!!u.notice?.alarm);put(n.notice,u.notice&&at<u.notice.until?u.notice.text:'');n.notice.hidden=!n.notice.textContent;
 const live=g.phase==='play'&&c.ready()&&!!p&&p.alive;
 const seals=g.heist541?.seals??[],count=seals.filter(s=>s.done).length,open=gatesOpen559(g.heist541),cool=Math.max(0,Math.ceil(((p?.abilityReady541??0)-g.elapsed)/1000));
 put(n.mission,`封印 ${count} / 3`);paintObjectives559(u,g,p);put(n.objective,p?.interacting541?`${p.interacting541.type==='seal'?'解除中':'救出中'} ${Math.round(p.interacting541.value*100)}%`:open?(hunt?'西門・東門からの脱出を阻止':'西門か東門へ · １人脱出で勝ち'):hunt?'反応が出た部屋を探そう':'５か所から３つ · １人８秒／協力６秒');
 n.skill.disabled=!live||cool>0;put(n.skillname,(hunt?'⌖ 気配を探る':'✧ 身代わり')+(cool>0?` · ${cool}秒`:''));put(n.skillhint,hunt&&p?.sense541?.until>g.elapsed?['近くに気配なし','この辺りに気配あり','すぐ近くに気配！'][p.sense541.level]:hunt?'距離の気配だけ届く · 20秒で再使用':'今の家具を残して変身 · 18秒で再使用');
 if(hunt){let selected=g.objects.find(o=>o.id===u.targetId);if(!selected||selected.checked||p&&Math.hypot(selected.x-p.x,selected.y-p.y)>HIDE536.range){selected=g.objects.filter(o=>!o.checked&&p&&Math.hypot(o.x-p.x,o.y-p.y)<=HIDE536.range).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]??selected;u.targetId=selected?.id??null}const near=selected&&p&&Math.hypot(selected.x-p.x,selected.y-p.y)<=HIDE536.range;n.attack.disabled=!live||g.shots<=0||!selected||!near||selected.checked||g.elapsed<g.shotReadyAt;put(n.charges,'● '.repeat(g.shots)+'○ '.repeat(HIDE536.shots-g.shots));put(n.recharge,g.shots===HIDE536.shots?'攻撃チャージ MAX':Math.max(0,Math.ceil((g.rechargeAt-g.elapsed)/1000))+'秒で１回補充');put(n.attackhint,g.shots===0?'チャージを待とう':!selected?'置き物を選ぼう':selected.checked?'調査済み':!near?'近づいてから調べよう':'攻撃を１回消費');put(n.status,!p?'観戦中':selected?selected.checked?'これは普通の置き物だった':PROPS536[selected.kind]+'を選択中':'怪しい置き物をタップ');put(n.tip,selected&&!near?'床タップで近づこう。攻撃は10秒で補充':'狭い視界の中で、動きと揺れを探そう！')}
 else if(p){const stamina=Math.max(0,p.stamina??HIDE536.stamina)/HIDE536.stamina;n.staminabar.style.transform=`scaleX(${stamina})`;n.staminabar.classList.toggle('is-danger',p.exhausted||stamina<.25);put(n.staminalabel,p.exhausted?'息切れ · 速度½':Math.round(stamina*100)+'%');put(n.staminatip,g.phase==='hiding'?'準備中はスタミナを消費しないよ':p.exhausted?'止まって回復！ 30%まで戻ると通常速度':p.moving?'約15秒の連続移動で息切れ':'休憩中 · 止まるとスタミナ回復');put(n.status,!p.alive?'仲間を応援しよう！':g.phase==='hiding'?'どっちに化けて隠れる？':shaking?'揺れてる…！ 見られていない？':PROPS536[p.kind]+'に変身中');put(n.tip,!p.alive?'仲間の救出か、２つの門からの脱出を待とう':g.phase==='hiding'?'変身を選んだら、自分で自然な場所を探そう':open?'西門か東門へ！ 鬼が守る門は避けよう':'封印を選んで分担。部屋に音が響く前に判断！');for(const b of u.props){const chosen=Number(b.dataset.hdProp)===p.kind;b.setAttribute('aria-pressed',String(chosen));b.disabled=!p.alive||!c.ready()||!['hiding','play'].includes(g.phase);put(b.querySelector('em'),chosen?'✓ 変身中':'タップで変身')}}
}
export function hideBefore536(c){const u=c.hideUI536;if(!u)return;if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.cleanup?.();u.cleanup=null;u.root=null;u.renderer=null}
export function hideDispose536(c){hideBefore536(c);const u=c.hideUI536;if(u?.audio){u.audio.close()?.catch(()=>{});u.audio=null}}
export function hideAfter536(c){const root=c.root?.querySelector('.hd-play536');if(!root)return;const u=ui(c);u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const q=k=>root.querySelector(`[data-hd-${k}]`);u.nodes=Object.fromEntries(['stage','canvas','time','timelabel','counter','notice','count','countlabel','countnumber','counthelp','caught','network','attack','attackhint','status','tip','area','shake','shaketime','map','charges','recharge','staminalabel','staminabar','staminatip','mission','objective','skill','skillname','skillhint','seals','exits','channel','channelname','channelvalue','channelbar','channelhint'].map(k=>[k,q(k)]));u.seats=[...root.querySelectorAll('[data-hd-seat]')];u.seatStatus=[...root.querySelectorAll('[data-hd-seatstatus]')];u.props=[...root.querySelectorAll('[data-hd-prop]')];u.sealNodes559=[...root.querySelectorAll('[data-hd-seal559]')];u.renderer=renderer536(u.nodes.canvas);u.keys=new Set();
 const abort=new AbortController(),on=(el,name,fn,options={})=>el.addEventListener(name,fn,{...options,signal:abort.signal}),resize=()=>resize536(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const unlockZoom=lockPlayZoom498(root);
 let pointer=null,startPoint=null,lastMove=0;const moveAt=(e,select=false)=>{const g=c.state.hide,p=me(c);if(!p?.alive||p.hunter&&g.phase==='hiding'||!c.ready())return;const b=u.nodes.canvas.getBoundingClientRect(),q=worldPoint537(u.renderer,e.clientX-b.left,e.clientY-b.top),target={x:clamp536(q.x,0,HIDE536.width),y:clamp536(q.y,0,HIDE536.height)};let goal=target;u.steering=null;
 if(p.hunter&&select&&!u.mapOpen){const o=g.objects.map(o=>({o,d:Math.hypot(o.x-target.x,(o.y-30)-target.y)})).filter(x=>x.d<65).sort((a,b)=>a.d-b.d)[0]?.o;u.targetId=o?.id??null;if(o){const dx=p.x-o.x,dy=p.y-o.y,d=Math.hypot(dx,dy);if(d<=HIDE536.range){sound536(u,'select');return}goal={x:o.x+dx/d*(HIDE536.range-35),y:o.y+dy/d*(HIDE536.range-35)};sound536(u,'select')}}u.destination=goal;send(c,{target:goal});};
 on(u.nodes.attack??root,'pointerdown',e=>{if(!e.target.closest?.('[data-hd-attack]'))return;e.preventDefault();if(!u.nodes.attack.disabled){unlock536(u);send(c,{attack:u.targetId});u.attackPointerAt540=Date.now()}});
 on(u.nodes.canvas,'pointerdown',e=>{if(pointer!==null)return;e.preventDefault();unlock536(u);pointer=e.pointerId;startPoint={x:e.clientX,y:e.clientY};lastMove=Date.now();u.nodes.canvas.setPointerCapture(pointer);moveAt(e,true)});
 on(u.nodes.canvas,'pointermove',e=>{if(e.pointerId!==pointer||!startPoint||Math.hypot(e.clientX-startPoint.x,e.clientY-startPoint.y)<7||Date.now()-lastMove<85)return;e.preventDefault();lastMove=Date.now();moveAt(e)});
 on(u.nodes.canvas,'pointerup',e=>{if(e.pointerId!==pointer)return;if(startPoint&&Math.hypot(e.clientX-startPoint.x,e.clientY-startPoint.y)>=7)moveAt(e);pointer=null;startPoint=null;u.mapOpen=false});
 const stop=()=>{pointer=null;startPoint=null;u.steering=null;u.keys.clear();send(c,{target:null})};on(u.nodes.canvas,'pointercancel',stop);on(u.nodes.canvas,'lostpointercapture',()=>{pointer=null;startPoint=null});on(document,'keyup',e=>{if(u.keys.delete(e.key.toLowerCase())){e.preventDefault();keySteer(c)}});on(window,'blur',stop);const interval=setInterval(()=>{if(u.steering)send(c,{steer:u.steering})},140);
 let painted=-Infinity;const tick=(stamp=performance.now())=>{u.raf=null;if(!u.root||document.hidden)return;if(stamp-painted>=1000/60-1){painted=stamp;paint(c)}u.raf=requestAnimationFrame(tick)};on(document,'visibilitychange',()=>{if(document.hidden){stop();send(c,{target:null});if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{})}else{c.refresh?.();tick()}});
 u.cleanup=()=>{if(u.steering)stop();clearInterval(interval);abort.abort();observer.disconnect();unlockZoom()};hideReceive536(c);tick();
}
export function hideClick536(c,b){const d=b.dataset,g=c.state?.hide;if(!g||!Object.keys(d).some(k=>k.startsWith('hd')))return false;const u=ui(c);unlock536(u);if(d.hdRole)c.raw('hide536',{gameId:g.id,kind:'role',role:d.hdRole});if(d.hdMonster)c.raw('hide536',{gameId:g.id,kind:'select',monsterId:d.hdMonster});if(d.hdProp!==undefined)send(c,{prop:Number(d.hdProp)});if(d.hdGoal559&&me(c)?.alive){const goal=goal559(g,d.hdGoal559);if(goal){u.mapOpen=false;u.steering=null;u.keys?.clear();u.destination={x:goal.x,y:goal.y};send(c,{target:u.destination})}}if(d.hdAction==='more'){u.limit+=24;c.render()}if(d.hdAction==='start')c.raw('hide536',{gameId:g.id,kind:'start'});if(d.hdAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock536(u)}if(d.hdAction==='attack'&&u.targetId&&Date.now()-(u.attackPointerAt540??0)>500)send(c,{attack:u.targetId});if(d.hdAction==='ability541')send(c,{ability541:true});if(d.hdAction==='stop'){u.steering=null;u.keys?.clear();u.destination=null;send(c,{target:null})}if(d.hdAction==='map'){u.mapOpen=!u.mapOpen;u.steering=null;u.keys?.clear();send(c,{target:null})}return true}
export function hideInput536(c,e){if(!c.state?.hide||e.name!=='hideSearch536')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
function keySteer(c){const u=ui(c),k=u.keys??new Set(),x=Number(k.has('d')||k.has('arrowright'))-Number(k.has('a')||k.has('arrowleft')),y=Number(k.has('s')||k.has('arrowdown'))-Number(k.has('w')||k.has('arrowup')),length=Math.hypot(x,y)||1;u.steering=x||y?{x:x/length,y:y/length}:null;u.destination=null;send(c,{steer:u.steering??{x:0,y:0}})}
export function hideKey536(c,e){if(!c.state?.hide||!['hiding','play'].includes(c.state.hide.phase)||!me(c)?.alive||!c.root?.querySelector('.hd-play536')||e.target.closest?.('input'))return false;const k=e.key.toLowerCase();if(['arrowleft','a','arrowright','d','arrowup','w','arrowdown','s'].includes(k)){e.preventDefault();ui(c).keys??=new Set();ui(c).keys.add(k);keySteer(c);return true}if(e.key===' '){e.preventDefault();send(c,me(c).hunter?{attack:ui(c).targetId}:{target:null});return true}return false}
