import {SUMO523 as C,body523,nextShrink523,radius523,dashDistance527} from './Rules523.js';
import {playerColor499} from '../party/PartyColors499.js';
const TAU=Math.PI*2,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const assets=new Map();
function asset(path){if(assets.has(path))return assets.get(path);const img=typeof Image==='function'?new Image():null;if(img)img.src=new URL('../../assets/sumo527/'+path,import.meta.url).href;assets.set(path,img);return img}
const ready=i=>i?.complete&&i.naturalWidth>0;
export function createRenderer523(canvas){return{canvas,ctx:canvas.getContext('2d',{alpha:false}),bg:asset('abyss.webp'),texture:asset('arena.webp'),width:0,height:0,camera:{x:0,y:0,zoom:1.18},lastAt:0}}
export function project523(r,x,y){return{x:r.cx+(x-r.camera.x)*r.scale,y:r.cy+(y-r.camera.y)*r.scale*.78}}
export function unproject527(r,x,y){return{x:(x-r.cx)/r.scale+r.camera.x,y:(y-r.cy)/(r.scale*.78)+r.camera.y}}
export function resize523(r,w,h,dpr=1){const d=Math.min(1.5,dpr);if(r.key===[w,h,d].join(':'))return;r.key=[w,h,d].join(':');Object.assign(r,{width:w,height:h,dpr:d,cx:w/2,cy:Math.max(100,(h-110)*.5),baseScale:Math.max(6,Math.min((w-24)/18,(h-130)/14.04))});r.scale=r.baseScale*r.camera.zoom;r.canvas.width=Math.round(w*d);r.canvas.height=Math.round(h*d)}
function ellipse(c,x,y,rx,ry){c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,TAU)}
function ringPath(c,outer,inner,a=0,b=TAU){c.beginPath();c.arc(0,0,outer,a,b);c.arc(0,0,inner,b,a,true);c.closePath()}
function imageCover(c,img,w,h,ox=0,oy=0){const s=Math.max(w/img.width,h/img.height);c.drawImage(img,(w-img.width*s)/2+ox,(h-img.height*s)/2+oy,img.width*s,img.height*s)}
function floorImage(c,r){if(ready(r.texture)){const i=r.texture;const pad=.021;c.drawImage(i,i.width*pad,i.height*pad,i.width*(1-pad*2),i.height*(1-pad*2),-9,-9,18,18)}else{c.fillStyle='#30463d';c.fillRect(-9,-9,18,18);c.strokeStyle='#9e9463';c.lineWidth=.03;for(const R of[3,4.95,6.3,7.65,9]){c.beginPath();c.arc(0,0,R,0,TAU);c.stroke()}}}
function world(c,r,fn){const o=project523(r,0,0);c.save();c.translate(o.x,o.y);c.scale(r.scale,r.scale*.78);fn();c.restore()}
function camera(r,g,poses,at,reduced){const elapsed=g.phase==='result'?g.elapsed:Math.max(0,at-g.startAt),warning=nextShrink523(elapsed)-elapsed<C.warning,collapse=g.events.some(e=>e.type==='collapse'&&elapsed-e.at>=0&&elapsed-e.at<1800),self=poses.find(p=>p.playerId===r.selfId),focus=self?.alive?self:poses.find(p=>p.alive),dt=clamp((at-(r.lastAt||at))/1000,0,.06);r.lastAt=at;
 const overview=warning||collapse||g.phase!=='play',z=overview?1:1.2,tx=overview?0:Math.sign(focus?.x??0)*Math.max(0,Math.abs(focus?.x??0)-1.65)*.58,ty=overview?0:Math.sign(focus?.y??0)*Math.max(0,Math.abs(focus?.y??0)-1.5)*.5,f=reduced?1:1-Math.exp(-dt*4.5);r.camera.x+=(tx-r.camera.x)*f;r.camera.y+=(ty-r.camera.y)*f;r.camera.zoom+=(z-r.camera.zoom)*f;r.scale=r.baseScale*r.camera.zoom}
function background(c,r,at,reduced){const w=r.width,h=r.height;c.fillStyle='#061a19';c.fillRect(0,0,w,h);if(ready(r.bg))imageCover(c,r.bg,w,h,-r.camera.x*1.7,-r.camera.y*1.5);const shade=c.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#02130f25');shade.addColorStop(.5,'#06272508');shade.addColorStop(1,'#02130fde');c.fillStyle=shade;c.fillRect(0,0,w,h);if(reduced)return;
 for(let i=0;i<4;i++){const x=w*(.15+i*.28)+Math.sin(at/7000+i)*25,y=h*(.18+i*.21),mist=c.createRadialGradient(x,y,0,x,y,w*.43);mist.addColorStop(0,'#7adab70b');mist.addColorStop(1,'#7adab700');c.fillStyle=mist;c.fillRect(x-w*.43,y-w*.43,w*.86,w*.86)}
}
function arena(c,r,g,elapsed,at,reduced){const R=g.radius,o=project523(r,0,0),s=r.scale;
 c.fillStyle='#001a1699';ellipse(c,o.x,o.y+28,R*s*1.03,R*s*.78);c.fill();
 const edge=c.createLinearGradient(0,o.y,0,o.y+24);edge.addColorStop(0,'#806f43');edge.addColorStop(.2,'#c5a565');edge.addColorStop(.35,'#263831');edge.addColorStop(1,'#091713');c.fillStyle=edge;ellipse(c,o.x,o.y+16,R*s,R*s*.78);c.fill();
 world(c,r,()=>{c.save();c.beginPath();c.arc(0,0,R,0,TAU);c.clip();floorImage(c,r);c.restore();c.strokeStyle='#e1c484';c.lineWidth=.065;c.beginPath();c.arc(0,0,R-.035,0,TAU);c.stroke();if(R<9){c.strokeStyle='#080f0dd9';c.lineWidth=.07;for(let i=0;i<35;i++){const a=i/35*TAU,x=Math.cos(a)*R,y=Math.sin(a)*R;c.beginPath();c.moveTo(x,y);c.lineTo(x-Math.cos(a+.2)*(.06+i%4*.04),y-Math.sin(a+.2)*(.06+i%4*.04));c.stroke()}}
 const until=nextShrink523(elapsed)-elapsed;
 if(until<=C.warning){const safe=radius523(nextShrink523(elapsed)),q=1-until/C.warning,pulse=reduced?.15:.13+Math.sin(at/(200-100*q))*.045;c.save();ringPath(c,R,safe);c.clip();c.fillStyle=`rgba(255,102,35,${pulse+q*.08})`;c.fillRect(-R,-R,R*2,R*2);c.lineWidth=.035+q*.045;c.strokeStyle='#ffe0a8';c.shadowColor='#ff6e25';c.shadowBlur=8;
 c.beginPath();for(let i=0;i<=180;i++){const a=i/180*TAU,rr=safe+.025+Math.sin(i*2.7)*.055;const x=Math.cos(a)*rr,y=Math.sin(a)*rr;if(i)c.lineTo(x,y);else c.moveTo(x,y)}c.stroke();
 for(let i=0;i<22;i++){const a=i/22*TAU;c.beginPath();for(let j=0;j<6;j++){const rad=safe+(R-safe)*j/5,aa=a+Math.sin(i*4+j*2)*.018,x=Math.cos(aa)*rad,y=Math.sin(aa)*rad;if(j)c.lineTo(x,y);else c.moveTo(x,y)}c.stroke();if(!reduced){const rr=safe+(R-safe)*(.3+(i%3)*.22),jit=Math.sin(at/25+i)*q*.04;c.fillStyle='#eedbb0';c.fillRect(Math.cos(a)*rr+jit,Math.sin(a)*rr-.1-q*.14,.07,.08)}}c.shadowBlur=0;c.restore();
 // Inward chevrons identify the safe side without words or dependence on hue.
 c.strokeStyle='#fff1b6';c.lineWidth=.07;for(let i=0;i<10;i++){const a=i/10*TAU;c.save();c.rotate(a);c.beginPath();c.moveTo(safe-.32,-.14);c.lineTo(safe-.55,0);c.lineTo(safe-.32,.14);c.stroke();c.restore()}}
 });
 // Actual annular stone slabs fall, leaving the centre texture at its original scale.
 for(const e of g.events){if(e.type!=='collapse')continue;const age=elapsed-e.at;if(age<0||age>1800)continue;const t=age/1800;world(c,r,()=>{for(let i=0;i<20;i++){const a=i/20*TAU,local=clamp(t-(i%4)*.025,0,1),drift=local*.8,fall=local*local*10;c.save();c.globalAlpha=1-local;c.translate(Math.cos(a)*drift,Math.sin(a)*drift+fall);c.translate(Math.cos(a)*(e.from+e.to)/2,Math.sin(a)*(e.from+e.to)/2);c.rotate(reduced?0:Math.sin(i*3)*local*.5);c.translate(-Math.cos(a)*(e.from+e.to)/2,-Math.sin(a)*(e.from+e.to)/2);ringPath(c,e.from,e.to,a+.012,a+TAU/20-.012);c.clip();floorImage(c,r);c.restore()}})}
}
function gem(c,r,v,at,reduced){const p=project523(r,v.x,v.y),q=(v.value===3?4.3:3.1)*r.camera.zoom,bob=reduced?0:Math.sin(at/290+v.id)*1.4;c.fillStyle=v.value===3?'#eab74525':'#60ffd929';ellipse(c,p.x,p.y+2,q*1.7,q*.48);c.fill();c.save();c.translate(p.x,p.y-5+bob);c.shadowColor=v.value===3?'#ffd564':'#4affd9';c.shadowBlur=6;c.fillStyle=v.value===3?'#efc575':'#6deccc';c.beginPath();c.moveTo(0,-q*1.7);c.lineTo(q,0);c.lineTo(0,q*1.7);c.lineTo(-q,0);c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#fff5c9';c.beginPath();c.moveTo(0,-q*1.7);c.lineTo(0,q);c.lineTo(-q,0);c.closePath();c.fill();c.restore()}
function magnetIcon(c,x,y,size,angle=0){c.save();c.translate(x,y);c.rotate(angle);c.lineWidth=size*.3;c.strokeStyle='#e8c480';c.shadowColor='#67ffe0';c.shadowBlur=7;c.beginPath();c.moveTo(-size*.43,-size*.36);c.lineTo(-size*.43,size*.2);c.bezierCurveTo(-size*.43,size*.78,size*.43,size*.78,size*.43,size*.2);c.lineTo(size*.43,-size*.36);c.stroke();c.shadowBlur=0;c.fillStyle='#b3ffee';c.fillRect(-size*.6,-size*.55,size*.34,size*.28);c.fillRect(size*.26,-size*.55,size*.34,size*.28);c.restore()}
function arrow(c,from,to,color,width=2){const a=Math.atan2(to.y-from.y,to.x-from.x);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.beginPath();c.moveTo(from.x,from.y);c.lineTo(to.x,to.y);c.stroke();c.beginPath();c.moveTo(to.x-Math.cos(a-.5)*10,to.y-Math.sin(a-.5)*10);c.lineTo(to.x,to.y);c.lineTo(to.x-Math.cos(a+.5)*10,to.y-Math.sin(a+.5)*10);c.stroke();c.lineCap='butt'}
function players(c,r,g,poses,elapsed,at,reduced){for(const p of poses){if(!p.alive)continue;const pos=project523(r,p.x,p.y),rad=body523(p)*r.scale,color=playerColor499(p).hex;c.fillStyle='#0008';ellipse(c,pos.x,pos.y+2,rad*1.1,rad*.45);c.fill();c.strokeStyle=color;c.lineWidth=2;ellipse(c,pos.x,pos.y,rad*1.2,rad*.56);c.stroke();
 if(p.power>=12){c.save();c.globalAlpha=.15+.18*p.power/C.maxPower;c.strokeStyle=color;c.lineWidth=1;ellipse(c,pos.x,pos.y,rad*1.45,rad*.72);c.stroke();if(!reduced)for(let i=0;i<5;i++){const a=at/600+i*TAU/5;c.fillStyle=color;c.fillRect(pos.x+Math.cos(a)*rad*1.3,pos.y+Math.sin(a)*rad*.6-(at/15+i*9)%25,2,2)}c.restore()}
 if(p.magnetUntil>elapsed){const seconds=(p.magnetUntil-elapsed)/C.magnetDuration,rr=C.magnetRadius*r.scale*(seconds<.25?.7+seconds*1.2:1);c.save();c.strokeStyle='#a8ffed';c.lineWidth=1.4;c.globalAlpha=.3;c.setLineDash([4,5]);ellipse(c,pos.x,pos.y,rr,rr*.78);c.stroke();c.setLineDash([]);c.globalAlpha=.7;for(let i=0;i<3;i++){const a=at/600+i*TAU/3,x=pos.x+Math.cos(a)*rad*1.5,y=pos.y+Math.sin(a)*rad*.8;c.beginPath();c.arc(x,y,2,0,TAU);c.fillStyle='#d7fff5';c.fill()}c.restore();magnetIcon(c,pos.x,pos.y-rad*3,10)}
 if(p.charging){const q=p.charge/C.charge,aim=project523(r,p.x+p.fx*dashDistance527(p),p.y+p.fy*dashDistance527(p));c.save();c.globalAlpha=.26;c.strokeStyle=color;c.lineWidth=rad*1.3;c.beginPath();c.moveTo(pos.x,pos.y);c.lineTo(aim.x,aim.y);c.stroke();c.globalAlpha=.92;arrow(c,pos,aim,q>=1?'#fff0ad':color,2.3);c.strokeStyle=q>=1?'#fff0ae':color;c.lineWidth=2.5;c.beginPath();c.ellipse(pos.x,pos.y,rad*(1.3+q*.3),rad*(.65+q*.15),0,-Math.PI/2,-Math.PI/2+TAU*q);c.stroke();c.restore()}
 if(p.attackUntil>elapsed){for(let i=3;i>=1;i--){c.save();c.globalAlpha=.12*(4-i);const back=project523(r,p.x-p.dx*i*.55,p.y-p.dy*i*.55);c.strokeStyle=color;c.lineWidth=rad*(1.3-i*.2);c.beginPath();c.moveTo(back.x,back.y);c.lineTo(pos.x,pos.y);c.stroke();c.restore()}}
 if(p.braceUntil>elapsed){c.strokeStyle='#ffedaf';c.lineWidth=3;c.beginPath();c.arc(pos.x,pos.y-12,rad*1.6,Math.PI,TAU);c.stroke()}
 const speed=Math.hypot(p.vx,p.vy,p.kx,p.ky);if(speed>1&&!reduced){c.fillStyle='#d7cba13a';for(let i=0;i<3;i++){const age=((at/300+i*.3)%1);ellipse(c,pos.x-(p.vx+p.kx)*age*2.2+Math.sin(i+at/900)*3,pos.y-(p.vy+p.ky)*age*1.7,1+age*4,.5+age*2);c.fill()}}
 // Off-screen opponents remain visible even when the camera follows the player.
 const margin=20,limitY=r.height-128;if(pos.x<margin||pos.x>r.width-margin||pos.y<margin||pos.y>limitY){const x=clamp(pos.x,margin,r.width-margin),y=clamp(pos.y,margin,limitY),ang=Math.atan2(pos.y-y,pos.x-x);c.save();c.translate(x,y);c.rotate(ang);c.fillStyle=color;c.strokeStyle='#03130d';c.lineWidth=2;c.beginPath();c.moveTo(8,0);c.lineTo(-5,-6);c.lineTo(-5,6);c.closePath();c.fill();c.stroke();c.restore()}
 }}
export function paint523(r,g,poses,at,reduced=false){if(!r.width)return;camera(r,g,poses,at,reduced);const c=r.ctx,elapsed=g.phase==='result'?g.elapsed:Math.max(0,at-g.startAt);c.setTransform(r.dpr,0,0,r.dpr,0,0);background(c,r,at,reduced);arena(c,r,g,elapsed,at,reduced);
 if(r.destination&&g.phase==='play'){const p=project523(r,r.destination.x,r.destination.y);c.strokeStyle='#fff0b899';c.lineWidth=1;ellipse(c,p.x,p.y,8,5);c.stroke();c.fillStyle='#ffdf96';ellipse(c,p.x,p.y,2,1.5);c.fill()}
 for(const v of g.crystals)gem(c,r,v,at,reduced);
 for(const v of g.pickups??[]){const p=project523(r,v.x,v.y),age=elapsed-v.born;if(age<1500){const beam=c.createLinearGradient(0,p.y-110,0,p.y);beam.addColorStop(0,'#baffea00');beam.addColorStop(1,'#baffea88');c.fillStyle=beam;c.fillRect(p.x-8,p.y-110,16,110)}c.strokeStyle='#b3ffeaaa';c.lineWidth=1;ellipse(c,p.x,p.y,14,7);c.stroke();magnetIcon(c,p.x,p.y-13,18,reduced?0:Math.sin(at/550)*.14)}
 players(c,r,g,poses,elapsed,at,reduced);
 for(const e of g.events){const age=elapsed-e.at;if(age<0||age>1100)continue;const t=age/1100,p=project523(r,e.x??0,e.y??0);c.save();c.globalAlpha=1-t;if(['hit','grow','brace','magnet'].includes(e.type)){c.strokeStyle=e.type==='magnet'?'#a2ffe1':e.type==='grow'?'#99edcd':'#ffe4a0';c.lineWidth=3*(1-t)+.5;ellipse(c,p.x,p.y,8+t*r.scale*2.6,4+t*r.scale*1.45);c.stroke();if(e.type==='hit'&&!reduced)for(let i=0;i<12;i++){const a=i*TAU/12;c.strokeStyle=i%2?'#ffbb68':'#fff4c5';c.beginPath();c.moveTo(p.x+Math.cos(a)*t*30,p.y+Math.sin(a)*t*22);c.lineTo(p.x+Math.cos(a)*(t*45+3),p.y+Math.sin(a)*(t*32+3));c.stroke()}if(e.type==='grow'){c.font='bold 11px system-ui';c.fillStyle='#ecffe5';c.textAlign='center';c.fillText('LEVEL UP',p.x,p.y-42-t*15)}}c.restore()}
 if(!reduced){c.fillStyle='#c8f3b95a';for(let i=0;i<14;i++)c.fillRect((i*67+at/180)%r.width,r.height-(i*91+at/100)%r.height,1.3,1.3)}
}
