import {SUMO523 as C,motion523,body523,nextShrink523,level535,chargeCap535,chargeRatio535,might535} from './Rules523.js';
import {createRenderer523,resize523,paint523,project523,unproject527} from './Renderer523.js';
import {receiveMotion522,motionTime522,remotePose522,followPose522,style522,class522,prop522,variable522} from '../tower/Presentation522.js';
import {bindControls523} from './Controls523.js';
import {unlock523,cue523} from './Audio523.js';
import {playerColor499} from '../party/PartyColors499.js';
import {partySeats462} from '../party/PartyView462.js';
import {result535} from './Results535.js';
import {lockPlayZoom498} from '../cabbage/Zoom498.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui=c=>c.sumoUI523??={sound:true,limit:24,search:'',seq:0,input:{x:0,y:0},sent:[],lastSend:0,seen:0,positions:{}};
const me=(c,g=c.state?.sumo)=>g?.players.find(p=>p.playerId===c.transport.selfId);
const clock=c=>c.state?.sumo?.phase==='play'&&ui(c).timeline522?motionTime522(ui(c),performance.now()):Date.now()+(c.offset??0);
const pic=(c,p)=>c.sgMonster463?.(p.speciesId??p.choice?.speciesId)??'';
const title=c=>`<header class="sm-head523"><button data-party-action462="browse" aria-label="パーティーへ戻る">‹</button><div><small>ABYSS · BEAST CLASH</small><b>魔獣ぶっとばし相撲</b></div><button data-sm-action="sound">音 ${ui(c).sound?'ON':'OFF'}</button></header>`;
const put=(e,s)=>{if(e&&e.textContent!==String(s))e.textContent=String(s)};
function lobby(c,g){const u=ui(c),party=c.state.party,member=g.members.find(p=>p.playerId===c.transport.selfId),pm=party.members.find(p=>p.playerId===c.transport.selfId),host=party.hostId===c.transport.selfId,list=c.roster().filter(m=>!u.search||c.sgSpeciesName463(m.raceSpeciesId??m.speciesId).includes(u.search));return`<section class="sm523 sm-lobby523">${title(c)}<div class="sm-cover523"><small>育てて、溜めて、ぶっとばせ。</small><h1>最後に立つのは、<br>いちばん重い一撃。</h1></div><div class="sm-body523"><div class="sm-facts523"><b>４人乱戦</b><b>最大150秒</b><b>場外で脱落</b></div><p>結晶を拾うほど巨大化！ 溜めた体当たりで、相手を土俵の外へ。40・75・105・130秒で外周が４段階に崩壊。最後の１人が勝ち！</p><p>地面をタップして移動。下中央のボタンを長押しで溜め、離して突進。溜め中も別の指で地面をタップすると狙いを変えられる。溜め中は移動が遅くなる。被弾しても溜めは継続。MAXになると金色のオーラが輝く！ レベルアップでチャージの上限威力も大きく育つ。磁石で８秒間、周りの結晶を吸引。鉄靴を拾うと次の体当たりを一度防ぐ。土俵際の救済も１試合に一度だけ。崩れた床では耐えられない！</p><small>空席はAIが参加。所持キャラのレベルによる能力差はなし。同時に全員落ちると引き分け。時間切れで複数残った場合は中央に近い人が勝ち。</small><h2>相棒を選ぼう</h2><input name="sumoSearch523" aria-label="魔物を探す" placeholder="魔物の名前で探す" value="${esc(u.search)}"><div class="sm-roster523">${list.slice(0,u.limit).map(m=>`<button data-sm-monster="${esc(m.id)}" aria-pressed="${member?.choice?.id===m.id}">${pic(c,{speciesId:m.raceSpeciesId??m.speciesId})}<small>${esc(c.sgSpeciesName463(m.raceSpeciesId??m.speciesId))}</small></button>`).join('')}</div>${list.length>u.limit?'<button data-sm-action="more">もっと見る</button>':''}${partySeats462(c)}<p class="sm-error523">${esc(c.error)}</p><button class="sm-gold523" data-party-action462="ready" ${!c.ready()||!member?.choice?'disabled':''}>${pm?.ready?'✓ 準備OK · 取り消す':'この相棒で準備OK'}</button>${host?`<button class="sm-gold523" data-sm-action="start" ${party.members.some(m=>!m.ready||!m.connected||m.atHome)||!c.ready()?'disabled':''}>いざ、土俵へ！</button>`:'<p>部屋主が開始すると、対戦が始まるよ。</p>'}</div></section>`}
function play(c,g){return`<section class="sm523 sm-play523 sm527 sm535">${title(c)}<div class="sm-score523"><span><small>SURVIVORS</small><b data-sm-alive>４人</b></span><strong data-sm-time>2:30</strong><span class="sm-rounds527"><small>ARENA</small><span data-sm-phase class="sm-phases527">${[0,1,2,3].map(i=>`<i data-sm-ring="${i}"></i>`).join('')}</span></span></div><div class="sm-seats523">${g.players.map(p=>`<div data-sm-seat="${p.seat}" style="--sm-color:${playerColor499(p).hex}">${pic(c,p)}<span><b>${esc(p.name)}</b><small data-sm-status="${p.seat}">Lv.1</small></span></div>`).join('')}</div><div class="sm-stage523" data-sm-stage><div class="sm-world523" data-sm-world><canvas data-sm-canvas aria-label="タップした地面へ移動。光る亀裂が広がった外周は崩れるので中央へ"></canvas>${g.players.map(p=>`<div class="sm-pawn523 ${p.playerId===c.transport.selfId?'is-self':''}" data-sm-pawn="${p.seat}" style="--sm-color:${playerColor499(p).hex}"><span><b>${p.playerId===c.transport.selfId?'▼ あなた':esc(p.name)}</b><small data-sm-headlevel="${p.seat}">Lv.1</small></span><div class="sm-sprite523">${pic(c,p)}</div><i class="sm-maxflare535" aria-hidden="true"></i></div>`).join('')}</div><div class="sm-notice523" data-sm-notice></div><div class="sm-count523" data-sm-count></div><div class="sm-network523" data-sm-network hidden>再接続中… AIが引き継ぐよ</div><div class="sm-finale523" data-sm-finale hidden><small>BEAST CLASH</small><h1 data-sm-winner></h1><p data-sm-ending></p></div></div><div class="sm-controls523"><div class="sm-power523"><small>GROWTH</small><strong data-sm-level>Lv.1</strong><span data-sm-power>結晶 0</span><div><i data-sm-meter></i></div><small data-sm-hint>拾って強くなる</small></div><button class="sm-shot523" data-sm-shot aria-label="長押しで溜め、離して体当たり"><i data-sm-charge></i><svg viewBox="0 0 48 40" aria-hidden="true"><path d="M5 12h15M2 20h14M7 28h13M24 5l17 15-17 15M17 20h22"/></svg><b data-sm-shotlabel>溜める</b><small data-sm-shothelp>離して体当たり</small><em data-sm-chargepower>威力上限 ×1.0</em></button><div class="sm-skills527"><span class="sm-brace527" data-sm-brace aria-label="踏ん張りの鉄靴"><i class="sm-item535 is-brace" aria-hidden="true"></i><small data-sm-bracelabel>鉄靴を探そう</small></span><span class="sm-magnet527" data-sm-magnet><i class="sm-item535" aria-hidden="true"></i><small data-sm-magnetlabel>磁石を探そう</small></span><small class="sm-edge535" data-sm-edge>縁の救済 ×1</small></div></div><p class="sm-controlnote523" data-sm-help>地面をタップで移動 · 長押し → 離して突進</p></section>`}
const result=(c,g)=>result535(c,g,title(c),pic);
export function sumoView523(c){const g=c.state.sumo,u=ui(c);if(u.gameId!==g.id){Object.assign(u,{gameId:g.id,seq:0,input:{x:0,y:0},sent:[],seen:0,lastSend:0,positions:{},timeline522:null,limit:24,search:'',ack:{x:0,y:0},pred:null,notice:null})}return g.phase==='lobby'?lobby(c,g):g.phase==='result'&&clock(c)>=g.finaleUntil?result(c,g):play(c,g)}
export function sumoReceive523(c){const g=c.state?.sumo;if(!g)return;const u=ui(c),p=me(c,g);receiveMotion522(u,g,performance.now());u.seq=Math.max(u.seq,p?.lastSeq??0);for(const input of u.sent)if(input.seq<=(p?.lastSeq??0))u.ack={x:input.x,y:input.y,mode:input.mode,tx:input.tx,ty:input.ty};u.sent=u.sent.filter(v=>v.seq>(p?.lastSeq??0));if(p?.alive&&g.phase==='play'){u.pred={...g,players:g.players.map(v=>({...v})),events:[],eventSeq:0};u.predAt=g.serverAt;u.predSeen=new Set()}}
export function sumoFrame523(c,m){if(m.selfId!==c.transport.selfId||!c.state?.sumo||m.sumo?.id!==c.state.sumo.id||m.sumo.serverAt<c.state.sumo.serverAt)return;const phase=c.state.sumo.phase;c.offset=m.serverNow-Date.now();c.state.sumo=m.sumo;sumoReceive523(c);if(phase!==m.sumo.phase&&(phase==='result'||m.sumo.phase==='result'))c.render()}
function send(c,force=false){const u=ui(c),g=c.state?.sumo,p=me(c,g),at=clock(c);if(g?.phase!=='play'||!p?.alive||!c.ready()||!force&&at-u.lastSend<80)return;const packet={gameId:g.id,kind:'move',seq:++u.seq,...u.input};if(c.raw('sumoInput523',packet)){u.sent.push({...packet,at});u.sent=u.sent.slice(-32);u.lastSend=at}u.input.press=false;u.input.release=false;u.input.cancel=false}
export function sumoBefore523(c){const u=c.sumoUI523;if(!u)return;if(u.scrollRaf!=null)cancelAnimationFrame(u.scrollRaf);u.scrollRaf=null;const lobby=c.root?.querySelector('.sm-lobby523');if(lobby&&c.state?.sumo?.phase==='lobby'){u.scroll={id:c.state.sumo.id,root:c.root,top:c.root.scrollTop,windowY:globalThis.scrollY??0,roster:lobby.querySelector('.sm-roster523')?.scrollTop??0,ancestors:[]};for(let e=c.root.parentElement;e;e=e.parentElement)u.scroll.ancestors.push([e,e.scrollTop])}else u.scroll=null;if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.cleanup?.();u.cleanup=null;u.root=null;u.renderer=null}
export function sumoDispose523(c){sumoBefore523(c);const u=c.sumoUI523;if(u?.scrollRaf!=null)cancelAnimationFrame(u.scrollRaf);if(u?.audio){u.audio.close()?.catch(()=>{});u.audio=null}}
export function sumoAfter523(c){const u=ui(c),g=c.state?.sumo;if(!g)return;const lobby=c.root?.querySelector('.sm-lobby523'),saved=u.scroll;if(lobby&&saved?.id===g.id&&saved.root===c.root){const apply=()=>{if(c.state?.sumo?.id!==saved.id||c.root?.querySelector('.sm-lobby523')!==lobby)return;c.root.scrollTop=saved.top;for(const[e,top]of saved.ancestors??[])e.scrollTop=top;const list=lobby.querySelector('.sm-roster523');if(list)list.scrollTop=saved.roster;if(globalThis.scrollY!==saved.windowY)globalThis.scrollTo?.(globalThis.scrollX??0,saved.windowY)};apply();u.scrollRaf=requestAnimationFrame(apply)}
 const root=c.root?.querySelector('.sm-play523');if(!root)return;u.root=root;u.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const q=k=>root.querySelector(`[data-sm-${k}]`);u.nodes=Object.fromEntries(['stage','canvas','world','alive','time','phase','notice','count','network','finale','winner','ending','level','power','meter','hint','shot','charge','shotlabel','shothelp','help','brace','bracelabel','magnet','magnetlabel','edge','chargepower'].map(k=>[k,q(k)]));u.pawns=g.players.map(p=>root.querySelector(`[data-sm-pawn="${p.seat}"]`));u.sprites=u.pawns.map(p=>p.querySelector('.sm-sprite523'));u.headLevels=g.players.map(p=>root.querySelector(`[data-sm-headlevel="${p.seat}"]`));u.status=g.players.map(p=>root.querySelector(`[data-sm-status="${p.seat}"]`));u.seats=g.players.map(p=>root.querySelector(`[data-sm-seat="${p.seat}"]`));u.rings=[...root.querySelectorAll('[data-sm-ring]')];u.renderer=createRenderer523(u.nodes.canvas);u.renderer.selfId=c.transport.selfId;
 const abort=new AbortController(),on=(el,name,fn,options={})=>el?.addEventListener(name,fn,{...options,signal:abort.signal});u.controls=bindControls523(root,on,u.input,()=>send(c,!!(u.input.press||u.input.release||u.input.cancel)),()=>c.state?.sumo?.phase==='play'&&me(c)?.alive&&c.ready(),()=>unlock523(u),(x,y)=>{const pos=unproject527(u.renderer,x,y),player=me(c),dist=Math.hypot(pos.x,pos.y),limit=Math.max(.4,(c.state.sumo.radius??9)-body523(player??{power:0})-.12);if(dist>limit){pos.x*=limit/dist;pos.y*=limit/dist}return pos});
 const resize=()=>{resize523(u.renderer,u.nodes.stage.clientWidth,u.nodes.stage.clientHeight,devicePixelRatio||1);u.controls.resize()};resize();const observer=new ResizeObserver(resize);observer.observe(u.nodes.stage);const unlockZoom=lockPlayZoom498(root);
 const tick=()=>{if(!u.root||document.hidden)return;u.raf=null;paint(c);if(u.root&&!document.hidden)u.raf=requestAnimationFrame(tick)};
 on(document,'visibilitychange',()=>{if(document.hidden){u.controls.clear();if(u.raf!=null)cancelAnimationFrame(u.raf);u.raf=null;u.audio?.suspend()?.catch(()=>{})}else{u.lastPaint=null;u.timeline522=null;c.refresh?.();if(u.raf==null)tick()}});
 u.cleanup=()=>{u.controls.clear();abort.abort();observer.disconnect();unlockZoom();u.controls=null};u.lastPaint=null;sumoReceive523(c);tick();
}
function paint(c){const u=ui(c),g=c.state.sumo,n=u.nodes,r=u.renderer,p=me(c,g),now=performance.now(),at=clock(c),dt=Math.min(.05,(now-(u.lastPaint??now))/1000),elapsed=g.phase==='result'?g.elapsed:Math.max(0,at-g.startAt);u.lastPaint=now;if(at-u.lastSend>=100)send(c);
 if(u.pred&&p?.alive&&g.phase==='play'){const pp=u.pred.players.find(v=>v.playerId===p.playerId),target=Math.min(at,g.serverAt+220);let loops=0;while(u.predAt+C.step<=target&&loops++<16){u.predAt+=C.step;u.pred.elapsed=u.predAt-g.startAt;const input={...(u.ack??{x:0,y:0})};for(const cmd of u.sent)if(cmd.at<=u.predAt){input.x=cmd.x;input.y=cmd.y;input.mode=cmd.mode;input.tx=cmd.tx;input.ty=cmd.ty;if(!u.predSeen.has(cmd.seq)){for(const k of['press','release','cancel'])input[k]||=cmd[k];u.predSeen.add(cmd.seq)}}motion523(u.pred,pp,input)}}
 const poses=g.players.map(player=>{const target=player.playerId===p?.playerId&&u.pred&&player.alive&&g.phase==='play'?u.pred.players.find(v=>v.playerId===player.playerId):remotePose522(u,player,at),pos=u.positions[player.seat]??={x:target.x,y:target.y};followPose522(pos,target,dt);return{...target,...pos,alive:player.alive}});
 r.destination=u.input.mode==='target'?{x:u.input.tx,y:u.input.ty}:null;
 const heavy=g.events.find(e=>e.type==='hit'&&e.power>=.8&&elapsed-e.at>=0&&elapsed-e.at<65);
 if(!u.reduced&&heavy&&u.lastPoses){for(let i=0;i<poses.length;i++){poses[i].x=u.lastPoses[i].x;poses[i].y=u.lastPoses[i].y}}else u.lastPoses=poses.map(v=>({...v}));
 paint523(r,g,poses,at,u.reduced);let shake=0;
 for(const player of poses){const node=u.pawns[player.seat],isWinner=g.winnerIds?.includes(player.playerId),ending=g.phase==='result',age=ending?Math.max(0,at-(g.finaleUntil-C.finale)):0,deadAge=player.alive?0:Math.max(0,elapsed-player.outAt),size=r.scale*2.25*(1+.5*Math.min(C.maxPower,player.power)/C.maxPower),pos=project523(r,player.x,player.y);let x=pos.x,y=pos.y,opacity=1,scale=1,rotation=0;
 if(!player.alive){const t=Math.min(1,(deadAge+(ending?age:0))/1100);x+=player.outVX*r.scale*t*.28;y+=player.outVY*r.scale*.78*t*.28+t*t*100;scale=1-t*.65;opacity=1-t;rotation=t*160}
 if(ending&&isWinner){const t=Math.min(1,age/1300),ease=1-(1-t)**3;x+=(r.cx-x)*ease;y+=(r.cy+12-y)*ease;scale=1+ease*.65;rotation=0}
 style522(node,'width',size+'px');style522(node,'height',size+'px');style522(node,'transform',`translate3d(${x-size/2}px,${y-size}px,0) scale(${scale}) rotate(${rotation}deg)`);style522(node,'opacity',String(opacity));style522(node,'zIndex',String(10+Math.round(y)));
 const attack=elapsed<player.attackUntil,squash=player.charging?1-.10*(chargeRatio535(player)):1,bob=player.alive&&!attack&&!u.reduced?Math.sin(at/80+player.seat)*Math.min(1.5,Math.hypot(player.vx,player.vy)):0;
 style522(u.sprites[player.seat],'transform',`translateY(${bob}px) scale(${player.fx<0?-1:1},${squash})`);class522(node,'is-grown',player.power>=16);class522(node,'is-elder',player.power>=32);class522(node,'is-bracing',player.braceUntil>elapsed);class522(node,'is-charging',player.charging);class522(node,'is-full',player.charging&&chargeRatio535(player)>=1);class522(node,'is-attacking',attack);variable522(node,'--sm-charge535',String(player.charging?chargeRatio535(player):0));put(u.headLevels[player.seat],'Lv.'+level535(player));class522(u.seats[player.seat],'is-out',!player.alive);put(u.status[player.seat],player.alive?`Lv.${1+Math.floor(player.power/4)}${player.auto?' · AI':''}`:'場外');
 }
 for(const e of g.events){const age=elapsed-e.at;if(e.type==='collapse'&&age>=0&&age<450&&!u.reduced)shake=Math.sin(age*.14)*(1-age/450)*3;if(e.type==='hit'&&e.power>=.8&&age>=0&&age<180&&!u.reduced)shake=Math.sin(age*.3)*(1-age/180)*4;if(e.id<=u.seen)continue;u.seen=e.id;if(age>700)continue;cue523(u,e.type);if(e.type==='guardBreak'&&e.playerId===p?.playerId)u.notice={text:'鉄靴で耐えた！',until:at+900};if(e.type==='anchor'&&e.playerId===p?.playerId)u.notice={text:'次の一撃を防ぐ！',until:at+900};if(e.type==='brace'&&e.playerId===p?.playerId)u.notice={text:'踏ん張った！',until:at+900};if(e.type==='out'){const who=g.players.find(p=>p.playerId===e.playerId);u.notice={text:who.name+'、場外！',until:at+1500}}if(e.type==='hit'&&e.side&&e.playerId===p?.playerId)u.notice={text:'横から強烈な一撃！',until:at+850}}
 style522(n.world,'transform',`translateY(${shake}px)`);put(n.notice,u.notice&&at<u.notice.until?u.notice.text:'');prop522(n.network,'hidden',c.connected());prop522(n.count,'hidden',g.phase!=='countdown');put(n.count,Math.max(1,Math.ceil((g.startAt-at)/1000)));const left=Math.max(0,Math.ceil((C.duration-elapsed)/1000));put(n.time,`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`);put(n.alive,g.players.filter(p=>p.alive).length+'人');u.rings.forEach((e,i)=>{class522(e,'is-gone',elapsed>=[40000,75000,105000,130000][i]);class522(e,'is-warning',[40000,75000,105000,130000][i]-elapsed>0&&[40000,75000,105000,130000][i]-elapsed<C.warning)});
 const self=poses.find(v=>v.playerId===p?.playerId),cool=Math.max(0,(self?.coolUntil??0)-elapsed,(self?.stunUntil??0)-elapsed),charge=self?.charging?chargeRatio535(self):0;prop522(n.shot,'disabled',!p?.alive||g.phase!=='play'||cool>0&&!self?.charging);put(n.shotlabel,!p?.alive?'観戦中':charge>=1?'最大解放！':charge>0?'溜め中':cool>0?'構え直す':'溜める');put(n.shothelp,cool>0&&!self?.charging?`${(cool/1000).toFixed(1)}秒`:charge>0?'離してぶっとばせ！':'離して体当たり');style522(n.charge,'transform',`scaleY(${Math.round(charge*100)/100})`);variable522(n.shot,'--sm-charge527',Math.round(charge*100)+'%');class522(n.shot,'is-full',charge>=1);const magnet=Math.max(0,(self?.magnetUntil??0)-elapsed);class522(n.magnet,'is-active',magnet>0);put(n.magnetlabel,magnet>0?'吸引 '+(magnet/1000).toFixed(1)+'秒':'磁石を探そう');class522(n.brace,'is-active',!!self?.anchor535);class522(n.brace,'is-used',!self?.anchor535);put(n.bracelabel,self?.anchor535?'一撃を防ぐ ×1':'鉄靴を探そう');put(n.edge,self?.braceUsed?'縁の救済 使用済み':'縁の救済 ×1');put(n.chargepower,'威力上限 ×'+might535(self??{power:0}).toFixed(1));put(n.level,'Lv.'+(1+Math.floor((self?.power??0)/4)));put(n.power,'結晶 '+(self?.collected??0));style522(n.meter,'transform',`scaleX(${(self?.power??0)/C.maxPower})`);put(n.hint,self?.power>=C.maxPower?'最大まで成長！':'拾って強くなる');put(n.help,p&&!p.alive?'場外！ 最後まで勝負を見届けよう':'地面をタップで移動 · 長押し → 離して突進');
 if(g.phase==='result'){const age=at-(g.finaleUntil-C.finale);prop522(n.finale,'hidden',age<1300);put(n.winner,g.winnerIds.length?'勝負あり！':'相打ち！');put(n.ending,g.winnerIds.map(id=>g.players.find(p=>p.playerId===id).name).join('・')+(g.winnerIds.length?' が土俵の覇者！':'全員が場外へ！'));if(at>=g.finaleUntil)c.render()}
}
export function sumoClick523(c,b){const d=b.dataset,g=c.state?.sumo;if(!g||!Object.keys(d).some(k=>k.startsWith('sm')))return false;const u=ui(c);unlock523(u);if(d.smMonster)c.raw('sumo523',{gameId:g.id,kind:'select',monsterId:d.smMonster});if(d.smAction==='more'){u.limit+=24;c.render()}if(d.smAction==='sound'){u.sound=!u.sound;b.textContent='音 '+(u.sound?'ON':'OFF');if(!u.sound)u.audio?.suspend()?.catch(()=>{});else unlock523(u)}if(d.smAction==='start')c.raw('sumo523',{gameId:g.id,kind:'start'});return true}
export function sumoInput523(c,e){if(!c.state?.sumo||e.name!=='sumoSearch523')return false;ui(c).search=e.value;ui(c).limit=24;c.render();return true}
export function sumoKey523(c,e){return ui(c).controls?.keydown(e)??false}
