import {createRequire} from 'node:module';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {createServer} from './preview.mjs';
const {chromium}=createRequire(import.meta.url)('playwright'),server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));
const report={hardwareIPhone:false,scope:'Production bomb view, rules and touch; outside roster isolated',sizes:[],checks:[],errors:[],failed:[]};let browser;
try{browser=await chromium.launch({headless:true,executablePath:process.env.QA_CHROMIUM??'/tmp/chromium',args:['--no-sandbox']});report.browserVersion=browser.version();const page=await browser.newPage({viewport:{width:390,height:740},isMobile:true,hasTouch:true,deviceScaleFactor:2});page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.failed.push(r.url());});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>document.fonts.ready);
for(const size of [{width:390,height:740},{width:320,height:568},{width:740,height:390}]){await page.setViewportSize(size);for(const self of [0,1,2,3]){await page.evaluate(id=>{load(3,id);freeze();rawGame.bombs.forEach(b=>{b.holder=id;b.readyAt=rawGame.lastAt-1;});sync();},self);await page.waitForTimeout(60);const bounds=await page.evaluate(()=>{const r=x=>document.querySelector(x).getBoundingClientRect().toJSON();return{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,stage:r('[data-bb-stage]'),footer:r('.br-controls563'),own:document.querySelector('[data-slot="0"]').dataset.bbTarget,chips:document.querySelectorAll('[data-bb-select]').length,bombs:document.querySelectorAll('[data-bb-live]').length};});assert(bounds.width<=size.width);assert(bounds.height<=size.height);assert(bounds.footer.bottom<=size.height+1);assert(bounds.stage.height>=120);assert.equal(Number(bounds.own),self);assert.equal(bounds.chips,3);assert.equal(bounds.bombs,3);const selected=await page.locator('[data-bb-select]').nth(1).getAttribute('data-bb-select');await page.locator('[data-bb-select]').nth(1).tap();await page.locator('[data-bb-target="'+((self+1)%4)+'"]').tap();await page.waitForTimeout(50);const send=await page.evaluate(()=>sent.filter(m=>m.op==='bombInput542'));assert.equal(send.length,1);assert.equal(send[0].bombId,Number(selected));assert.equal(send[0].target,(self+1)%4);report.sizes.push({size,self,...bounds});}}
await page.setViewportSize({width:390,height:740});await page.evaluate(()=>demo(false));await page.waitForTimeout(100);await page.screenshot({path:'docs/build569/visible.png'});await page.evaluate(()=>advance(6000));await page.waitForTimeout(80);assert.equal(await page.locator('[data-bb-time]').textContent(),'？');assert.equal(await page.locator('[data-bb-chip]').first().textContent(),'秘密');assert(!await page.evaluate(()=>JSON.stringify(c.state.bomb).includes('explodeAt')));await page.screenshot({path:'docs/build569/hidden.png'});report.checks.push('3 bomb selection and pass on all seats/sizes','hidden digits and no deadline in state');
await page.evaluate(()=>{c.connected=()=>false;sync();});await page.waitForTimeout(60);assert(await page.locator('[data-bb-network]').isVisible());assert.equal(await page.locator('.is-target').count(),0);report.checks.push('disconnect disables passing');
await page.evaluate(()=>{c.connected=()=>true;demo();rawGame.bombs[0].explodeAt=rawGame.lastAt+20;advance(20);});await page.waitForTimeout(80);assert(await page.locator('[data-bb-mission]').textContent().then(t=>t.includes('次の回')||t.includes('爆発')));assert.equal(await page.locator('[data-bb-live]').count(),2);report.checks.push('exploded holder loses all round points and redistributes other bombs');
await page.evaluate(()=>{load(1,0,'lobby');});await page.waitForTimeout(70);assert(await page.locator('body').innerText().then(t=>t.includes('0.1秒')&&t.includes('１→２→３')));await page.screenshot({path:'docs/build569/lobby.png'});await page.evaluate(()=>{load(3);freeze();rawGame.players.forEach(p=>p.ai=true);for(let i=0;i<1500&&rawGame.phase!=='result';i++)rules.advanceRelay569(rawGame,rawGame.lastAt+20);c.offset=rawGame.lastAt-Date.now();sync();c.render();});await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>c.state.bomb.phase),'result');report.checks.push('lobby rules and result');await page.screenshot({path:'docs/build569/result.png'});
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>demo(true));await page.waitForTimeout(60);assert.equal(await page.locator('.br-bomb569').first().evaluate(e=>getComputedStyle(e).animationName),'none');report.checks.push('reduced motion');assert.deepEqual(report.errors,[]);assert.deepEqual(report.failed,[]);
}finally{await browser?.close();await new Promise(r=>server.close(r));await writeFile('docs/build569/chromium-browser.json',JSON.stringify(report,null,2)+'\n');}console.log(JSON.stringify(report));
