import fs from 'node:fs';import assert from 'node:assert/strict';import{spawn}from'node:child_process';import path from 'node:path';
const{chromium}=await import(process.env.PLAYWRIGHT_MODULE??'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const server=spawn(process.execPath,['tools/build438/preview-server.mjs'],{stdio:['ignore','pipe','inherit']});let browser;const errors=[],missing=new Set(),checks=[],metrics={};
try{
 await new Promise((r,j)=>{const t=setTimeout(()=>j(Error('server timeout')),20000);server.stdout.on('data',b=>{if(String(b).includes('Preview http')){clearTimeout(t);r();}});server.on('exit',c=>j(Error('server exit '+c)));});
 const fonts=path.resolve('../browser432/fonts');browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE??path.resolve('../browser432/chromium'),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,FONTCONFIG_FILE:fonts+'/local.conf',FONTCONFIG_PATH:fonts}});
 const page=await browser.newPage({viewport:{width:393,height:720},isMobile:true,reducedMotion:'reduce'});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.routeWebSocket('**/*',s=>s.close());page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()===404)missing.add(new URL(r.url()).pathname)});await page.goto('http://127.0.0.1:8438');await page.waitForFunction(()=>window.ready438);
 const shot=async name=>page.screenshot({path:`docs/build438/${name}.png`});
 for(const size of [{width:393,height:720},{width:375,height:540},{width:430,height:760},{width:1280,height:800}]){
  await page.setViewportSize(size);
  for(const kind of ['equipment','skills','monsters','memory','notices','idle','power','shop','ranking','rank','lobby']){
   await page.evaluate(k=>qa438[k](),kind);await page.waitForTimeout(140);await page.evaluate(()=>document.fonts.ready);
   const layout=await page.evaluate(k=>{
    const css=[...document.styleSheets].find(s=>s.href?.includes('build438-polish'));
    const equipment='.equipment-paper-doll,.selected-equipment-identity,.selected-equipment-power,.selected-equipment-stats';
    const selector=k==='equipment'?equipment:'.v2-screen-hud,.v2-bottom-nav,.game-modal-card,.monster-species-card,.memory-archive-hub>button,.idle-v2-reward-grid>article,.power-ranking-row,.raid-boss-panel432,.world-my-rank429,.world-my-reward429';
    const geo=()=>[...document.querySelectorAll(selector)].map(e=>{const r=e.getBoundingClientRect();return {c:e.className,x:r.x,y:r.y,w:r.width,h:r.height};});
    const after=geo(),show=document.querySelector('.equipment-showcase438');
    if(k==='equipment'){show.before(show.querySelector('.equipment-paper-doll-portrait'),show.querySelector('.equipment-magic-circle-button'));show.remove();}
    css.disabled=true;const before=geo();css.disabled=false;
    return{before,after,moved:after.flatMap((r,i)=>['x','y','w','h'].some(key=>Math.abs(r[key]-before[i]?.[key])>.15)?[{before:before[i],after:r}]:[]),overflow:document.documentElement.scrollWidth>innerWidth+1};
   },kind);metrics[kind+'-'+size.width]=layout;assert.deepEqual(layout.moved,[],kind+' geometry '+size.width);assert.equal(layout.overflow,false,kind+' page overflow');checks.push(`${kind}: geometry preserved at ${size.width}`);
   if(kind==='equipment')await page.evaluate(()=>qa438.equipment());
   if(size.width===393)await shot(kind+'-393');
  }
  await page.evaluate(()=>qa438.equipment());
  const fit=await page.locator('.equipment-paper-doll-portrait').evaluate(e=>{const r=e.getBoundingClientRect(),s=e.firstElementChild.getBoundingClientRect();return{s:{x:s.x,y:s.y,w:s.width,h:s.height},inside:s.left>=r.left&&s.right<=r.right&&s.top>=r.top&&s.bottom<=r.bottom};});assert.ok(fit.inside);checks.push('equipment sprite entirely inside its frame at '+size.width);
  await page.evaluate(()=>qa438.skills());await page.locator('[data-skill-slot="0"]').click();
  assert.equal(await page.locator('.skill-picker-card.current').count(),1);assert.equal(await page.locator('.skill-picker-card.used-elsewhere438:disabled').count(),3);
  const badges=await page.locator('.skill-slot-state438').evaluateAll(es=>es.map(e=>{const r=document.createRange();r.selectNodeContents(e);return{text:e.textContent,lines:r.getClientRects().length,over:e.scrollWidth>e.clientWidth+1};}));assert.ok(badges.every(b=>b.lines===1&&!b.over));assert.ok(badges.some(b=>b.text==='SLOT 2に設定中'));metrics['badges-'+size.width]=badges;checks.push('current and other-slot skill badges fit horizontally at '+size.width);if(size.width===393)await shot('skill-picker-393');
  for(const online of [true,false]){await page.evaluate(o=>qa438.raid(true,o),online);await page.waitForTimeout(100);const bars=await page.locator('.side-unit-card .bar-label').evaluateAll(es=>es.map(e=>{const r=document.createRange();r.selectNodeContents(e);return{text:e.textContent,font:parseFloat(getComputedStyle(e).fontSize),w:e.clientWidth,tw:r.getBoundingClientRect().width};}));assert.ok(bars.length>=10);assert.ok(bars.every(b=>b.font<=6.5&&b.tw<=b.w+.5));metrics[`vitals-${size.width}-${online}`]=bars;assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));checks.push(`${online?'online':'offline'} exact HP/MP fit at ${size.width}`);if(size.width===393&&online)await shot('raid-393');}
 }
 await page.setViewportSize({width:393,height:720});await page.evaluate(()=>qa438.equipment());await page.locator('#toggleEquipmentEdit').click();await page.locator('.equipment-manage-panel').scrollIntoViewIfNeeded();await shot('equipment-manage-393');assert.match(await page.locator('#toggleEquipmentEdit').innerText(),/完了/);checks.push('equipment organize opens the existing management actions');
 await page.evaluate(()=>qa438.skills());const original=await page.evaluate(()=>[...qa438.state().monsters[0].equippedSkills]);await page.locator('[data-skill-slot="0"]').click();await page.locator('.used-elsewhere438').first().evaluate(e=>e.click());assert.deepEqual(await page.evaluate(()=>qa438.state().monsters[0].equippedSkills),original);checks.push('other-slot skill cannot be accidentally moved');
 await page.locator('[data-skill-picker-filter="buff"]').click();assert.equal(await page.locator('.skill-picker-card:visible').count(),1);await page.locator('[data-modal-dismiss]').click();await page.locator('[data-skill-slot="1"]').click();await page.locator('[data-skill-remove]').click();await page.locator('[data-skill-slot="0"]').click();const free=page.locator(`[data-skill-pick="${original[1]}"]`);assert.equal(await free.isDisabled(),false);await free.click();const changed=await page.evaluate(()=>qa438.state().monsters[0].equippedSkills);assert.deepEqual(changed,[original[1],null,original[2],original[3]]);checks.push('filters and explicit remove / assign affect only the selected skill slot');
 await page.evaluate(()=>qa438.navigation());assert.ok(await page.locator('.raid-boss-panel432').isVisible());assert.equal(await page.locator('.raid-result437').count(),0);await page.evaluate(()=>nav438.receive({type:'worldRaidState',state:{...structuredClone(nav438.state),revision:nav438.state.revision+1}}));assert.equal(await page.locator('.raid-result437').count(),0);checks.push('Home entry and delayed stale ended snapshots show the lobby');
 await page.evaluate(()=>qa438.navigation(true));assert.ok(await page.locator('.battle-screen').isVisible());
 for(const expected of [2,4,16,32,.5,1]){await page.locator('[data-online-speed-cycle="raid"]').click();const sent=await page.evaluate(()=>navSent438.at(-1));assert.equal(sent.type,'worldRaidSpeed');assert.equal(sent.speed,expected);await page.evaluate(speed=>{const s=structuredClone(nav438.state);s.attempt.raid.speed=speed;s.revision++;nav438.receive({type:'worldRaidState',state:s});},expected);assert.match(await page.locator('[data-online-speed-cycle="raid"]').innerText(),new RegExp(String(expected).replace('.','\\.')));}
 checks.push('raid speed button displays the full six-step cycle');
 await page.evaluate(()=>{const s=structuredClone(nav438.state);s.revision++;s.attempt.status='ended';s.attempt.report={rounds:99,result:'limit',damage:1071408};nav438.receive({type:'worldRaidState',state:s});});assert.ok(await page.locator('.raid-result437').isVisible());await shot('result-393');await page.locator('[data-modal-primary]').click();assert.ok(await page.locator('.raid-boss-panel432').isVisible());checks.push('active attempt resumes and its fresh result returns directly to the lobby');
 await page.evaluate(()=>{nav438.unmount();nav438.mount(document.querySelector('#app'));});assert.equal(await page.locator('.raid-result437').count(),0);checks.push('reopening raid after a finished result does not reopen that result');
 await page.evaluate(()=>qa438.rank());for(const i of [1,2,3]){const r=await page.locator('.podium-'+i).evaluate(e=>{const r=e.getBoundingClientRect(),b=e.querySelector('.power-ranking-position').getBoundingClientRect();return{x:(b.x+b.width/2-r.x-e.clientLeft)/e.clientWidth,y:(b.y+b.height/2-r.y-e.clientTop)/e.clientHeight};});assert.ok(Math.abs(r.x-.13)<.01&&Math.abs(r.y-.56)<.01);}checks.push('gold, silver and bronze numerals are centered in the frame medallions');
 for(const n of ['frame','button','archive','raid'])assert.ok(await page.evaluate(async n=>{const i=new Image();i.src='/assets/ui/build438/'+n+'.webp';await i.decode();return i.naturalWidth>1000;},n));checks.push('four original full-resolution generated materials decode');assert.deepEqual(errors,[]);assert.deepEqual([...missing],[]);
}finally{fs.writeFileSync('docs/build438/browser-result.json',JSON.stringify({checks,errors,missing:[...missing],metrics},null,2));await browser?.close();server.kill();console.log(JSON.stringify({checks:checks.length,errors,missing:[...missing]}));}
