import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{tmpdir}from'node:os';
const{chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const dir=fs.mkdtempSync(path.join(tmpdir(),'race451-ws-')),env={...process.env,HOST:'127.0.0.1',PORT:'18871'};
for(const[name,file]of Object.entries({FRIEND_STATE_FILE:'friends',GUILD_STATE_FILE:'guilds',POWER_RANKING_STATE_FILE:'rankings',SETTLEMENT_STATE_FILE:'settlements',WORLD_RAID_STATE_FILE:'raids',RACE_STATE_FILE:'race'}))env[name]=path.join(dir,file+'.json');
const processes=[];let browser;const errors=[],checks=[];
function launch(file,cwd,env,ready){const proc=spawn(process.execPath,[file],{cwd,env,stdio:['ignore','pipe','pipe']});processes.push(proc);return new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('startup timeout '+out)),15000);proc.stdout.on('data',b=>{out+=b;if(out.includes(ready)){clearTimeout(timer);resolve(proc)}});proc.stderr.on('data',b=>out+=b);proc.on('exit',c=>{if(c){clearTimeout(timer);reject(Error(out))}})})}
try{
 await launch('server.js',path.resolve('online-server'),env,'Local:');await launch('tools/build451/preview-server.mjs',process.cwd(),process.env,'Preview451 ready');
 const executable=path.resolve('../browser445-133/chromium');fs.chmodSync(executable,0o755);browser=await chromium.launch({executablePath:executable,args:['--no-sandbox','--disable-dev-shm-usage'],env:{...process.env,LD_LIBRARY_PATH:path.dirname(executable),FONTCONFIG_FILE:process.env.RACE_QA_FONTCONFIG||process.env.FONTCONFIG_FILE}});
 const pages=[];for(const name of['えなみ','りおん','より','ひで']){const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true});await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await context.routeWebSocket('**/*',route=>new URL(route.url()).hostname==='127.0.0.1'?route.connectToServer():route.close());const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE',e.message)});await page.goto('http://127.0.0.1:18451/?name='+encodeURIComponent(name));await page.waitForFunction(()=>window.qa451?.client.ready(),{},{timeout:20000});pages.push(page)}

 const host=pages[0];await host.locator('[data-race-action="create"]').click();await host.waitForFunction(()=>qa451.client.state?.room?.code);await host.locator('[data-race-monster]').first().click();await host.locator('[data-race-action="start"]').click();await host.waitForFunction(()=>qa451.client.state.room?.phase==='parade');
 await host.evaluate(()=>{const c=qa451.client;clearInterval(c.retryClock);c.raw=()=>false;const r=c.state.room;r.phase='race';r.finishMs=Array.from({length:8},(_,i)=>21000+i*600);r.startAt=Date.now()+c.offset-7000;c.render();c.root.scrollTop=0;window.scrollTo(0,0)});
 for(const size of[{width:320,height:640},{width:393,height:852},{width:709,height:900}]){await host.setViewportSize(size);await host.waitForTimeout(250);assert.equal(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await host.locator('.race-tickets451').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight+1));const art=await host.locator('.race-runner451 .race-art451 img').first().evaluate(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,loaded:e.complete&&e.naturalWidth>0}));assert.ok(art.height>20);assert.equal(art.loaded,true);checks.push({size,art,ticketsVisible:true})}
 await host.setViewportSize({width:393,height:852});await host.screenshot({path:'docs/build451/race.png',fullPage:true});assert.deepEqual(errors,[]);fs.writeFileSync('docs/build451/layout-results.json',JSON.stringify({checks,errors,fixture:'rendered race snapshot; money and live flow tested separately'},null,2));console.log(JSON.stringify({checks,errors}));

}finally{await browser?.close();for(const p of processes)p.kill();fs.rmSync(dir,{recursive:true,force:true})}
