import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright'),output='docs/build434';
const server=spawn(process.execPath,['tools/build434/preview-server.mjs'],{stdio:['ignore','pipe','inherit']});let browser;const errors=[],missing=new Set(),checks=[];
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Preview timeout')),10000);server.stdout.on('data',b=>{if(b.toString().includes('Preview http')){clearTimeout(timer);resolve();}});server.on('error',reject);});
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:393,height:720},isMobile:true,hasTouch:true,deviceScaleFactor:1});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.routeWebSocket('**/*',ws=>ws.close());page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('response',r=>{if(r.status()===404)missing.add(new URL(r.url()).pathname);});
 await page.goto('http://127.0.0.1:8434');await page.waitForFunction(()=>window.ready434);await page.waitForTimeout(700);
 const shot=async name=>page.screenshot({path:path.join(output,name+'.png')});await shot('royal-room');
 for(const [i,name] of ['えなみ','より','ひで','りおん'].entries()){
  for(const label of [false,true]){const p=await page.evaluate(({i,label})=>qa434.point(i,label),{i,label});await page.touchscreen.tap(p.x,p.y);await page.waitForSelector('.royal-hero434-modal');assert.equal(await page.locator('.royal-hero434-modal h2').textContent(),name);if(!label){await page.locator('[data-royal-talk434]').click();assert.match(await page.locator('[data-royal-gift434]').textContent(),/×3/);await shot('hero-'+i);}await page.locator('[data-modal-primary]').click();}checks.push('body and name select '+name);
 }
 for(const size of [{width:375,height:540},{width:1280,height:800}]){await page.setViewportSize(size);await page.evaluate(()=>qa434.hero('myth_enami'));const m=await page.locator('.game-modal-body').evaluate(el=>{el.scrollTop=el.scrollHeight;return{top:el.scrollTop,max:el.scrollHeight-el.clientHeight,touch:getComputedStyle(el).touchAction,width:document.documentElement.scrollWidth,view:innerWidth};});assert.ok(m.width<=m.view+1);if(size.height===540){assert.ok(m.max>0);assert.ok(m.top>0);assert.equal(m.touch,'pan-y');await shot('short-screen-scroll');}await page.locator('[data-modal-primary]').click();checks.push({size,scroll:m});}
 await page.setViewportSize({width:393,height:720});await page.evaluate(()=>qa434.field());await page.waitForTimeout(400);const p=await page.evaluate(()=>qa434.point(0));await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+45,p.y+25,{steps:5});await page.mouse.up();assert.equal(await page.locator('.game-modal').count(),0);checks.push('drag on hero pans without opening dialogue');
 await page.evaluate(()=>qa434.field({x:9,y:9}));await page.waitForTimeout(400);const goal=await page.evaluate(()=>{const g=qa434.game,c=g.canvas,r=c.getBoundingClientRect(),p=g.camera.world(4.5*88,9.5*88);return{x:r.left+p.x*r.width/c.width,y:r.top+p.y*r.height/c.height};});await page.touchscreen.tap(goal.x,goal.y);await page.waitForSelector('.royal-hero434-modal');assert.equal(await page.locator('.royal-hero434-modal h2').textContent(),'より');await page.locator('[data-modal-primary]').click();checks.push('walking contact opens the nearest actual hero');
 await page.evaluate(()=>qa434.hero('myth_hide'));await page.locator('[data-royal-party434]').click();await page.waitForSelector('.departure-dialog');assert.match(await page.locator('.departure-dialog').textContent(),/勇者一行/);await shot('group-rematch');await page.locator('[data-modal-dismiss]').click();checks.push('group rematch selector retained');
 const throne=await page.evaluate(()=>{const g=qa434.game,r=g.canvas.getBoundingClientRect(),p=g.camera.world(10.5*88,7*88);return{x:r.left+p.x*r.width/g.canvas.width,y:r.top+(p.y+15)*r.height/g.canvas.height};});await page.touchscreen.tap(throne.x,throne.y);assert.equal((await page.evaluate(()=>qa434.stories)).length,1);assert.equal(await page.locator('.game-modal').count(),0);checks.push('throne only invokes ending replay');
 await page.evaluate(()=>qa434.hero('myth_enami'));await page.locator('[data-royal-solo434]').click();await page.waitForSelector('.battle-screen');await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>qa434.battle.enemies.length),1);assert.equal(await page.evaluate(()=>qa434.battle.enemies[0].campaignHeroId),'myth_enami');await shot('personal-battle');checks.push('selected hero in native 4 vs 1 battle screen');
 await page.evaluate(()=>qa434.finish(true));await page.waitForSelector('.battle-contribution-modal');await shot('contribution');await page.locator('[data-modal-primary]').click();await page.waitForSelector('.royal-hero434-reward');assert.match(await page.locator('.royal-hero434-reward').textContent(),/創世のゲームパッド/);await shot('first-victory');await page.locator('[data-modal-primary]').click();checks.push('contribution then selected hero first victory reward');
 assert.equal(errors.length,0,JSON.stringify(errors));fs.writeFileSync(path.join(output,'browser-result.json'),JSON.stringify({checks,errors,missing:[...missing],realSafari:false,productionContacted:false},null,2));console.log(JSON.stringify({checks:checks.length,errors,missing:[...missing]}));
}finally{await browser?.close();server.kill();}
