import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {speciesSource,heroSource,visualSource,monsterSource} from '../build529/catalog-fixture.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const game=fileURLToPath(new URL('../../',import.meta.url)),out=resolve(game,'docs/build535');await mkdir(out,{recursive:true});
const font=process.env.QA_FONT_DIR,fixtures={'/src/data/species.js':speciesSource,'/src/data/endgameCharacters.js':heroSource,'/src/ui/MonsterVisual.js':visualSource,'/src/models/Monster.js':monsterSource};
const server=createServer(async(req,res)=>{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(path==='/preview.html'){const css=['build523-sumo','build527-sumo','build535-sumo'];res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'+css.map(s=>'<link rel="stylesheet" href="/src/Styles/'+s+'.css">').join('')+(font?'<link rel="stylesheet" href="/font/400.css">':'')+'<style>*{box-sizing:border-box}html,body{margin:0;background:#09291f;color:#fff5d1;font-family:sans-serif}button,input{font:inherit}.qa-portrait{font-size:30px}'+(font?'*{font-family:"Noto Sans JP",sans-serif!important}':'')+'</style><main id="app"></main><script type="module" src="/tools/build535/preview.mjs"></script></html>');return}const isFont=path.startsWith('/font/'),root=isFont?font:game,relative=isFont?path.slice(5):path;try{const target=resolve(root,'.'+relative);if(!target.startsWith(resolve(root)+'/'))throw Error();const data=await readFile(target);res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml'})[extname(target)]??'application/octet-stream');res.end(data)}catch{if(fixtures[path]){res.setHeader('Content-Type','text/javascript');res.end(fixtures[path])}else{res.statusCode=404;res.end('missing '+path)}}});await new Promise(r=>server.listen(8535,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const errors=[],results=[];
try{for(const [width,height]of [[320,568],[390,700],[430,800]]){
 const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1});page.on('pageerror',e=>{errors.push(e.message);console.error('pageerror:',e.message)});page.on('response',r=>{if(r.status()>=400){errors.push(r.status()+' '+r.url());console.error('resource:',r.status(),r.url())}});
 await page.goto('http://127.0.0.1:8535/preview.html');await page.waitForFunction(()=>window.qaReady);await page.evaluate(()=>document.fonts.ready);
 const fit=await page.evaluate(()=>{const r=document.querySelector('[data-sm-shot]').getBoundingClientRect();return{width:document.body.scrollWidth,button:{x:r.x,y:r.y,w:r.width,h:r.height,bottom:r.bottom},headLevels:document.querySelectorAll('[data-sm-headlevel]').length,brackets:document.querySelectorAll('.sm-growth527').length}});
 if(fit.width>width||fit.button.bottom>height+1||fit.headLevels!==4||fit.brackets)throw Error('layout '+JSON.stringify(fit));
 const button=page.locator('[data-sm-shot]');await page.mouse.move(fit.button.x+fit.button.w/2,fit.button.y+fit.button.h/2);await page.mouse.down();await page.evaluate(()=>elapseQA(600));
 const before=await page.evaluate(()=>stateQA().players[0].charge);const hit=await page.evaluate(()=>hitQA());if(!hit.charging||hit.charge<before||hit.stun<=0)throw Error('charge lost on hit');await page.waitForTimeout(100);if(await button.isDisabled())throw Error('held charge button disabled by hit');
 await page.mouse.up();await page.evaluate(()=>elapseQA(20));if((await page.evaluate(()=>stateQA().players[0].attackSerial))!==1)throw Error('release during stun failed');
 await page.evaluate(()=>startQA());if(await page.evaluate(()=>pickupQA())!==1)throw Error('brace pickup');await page.evaluate(()=>hitQA());if(await page.evaluate(()=>stateQA().players[0].anchor535)!==0)throw Error('brace not consumed');if(await page.evaluate(()=>stateQA().players[0].blocks535)!==1)throw Error('block stat');
 for(const name of ['charge','warning','collapse']){await page.evaluate(name=>sceneQA(name),name);await page.waitForTimeout(180);if(name==='charge'){if(!(await page.locator('[data-sm-headlevel="3"]').textContent()).includes('13'))throw Error('head level');if(await page.locator('.sm-pawn523.is-full').count()<1)throw Error('MAX class')}if(width===390)await page.screenshot({path:out+'/'+name+'.png'})}
 await page.evaluate(()=>resultQA());await page.waitForTimeout(100);const standings=await page.locator('.sm-standing535').count();if(standings!==4)throw Error('results missing');if(!(await page.locator('.sm-result-title535 h1').textContent()).includes('覇者'))throw Error('winner title');await page.locator('[data-party-result490="list"]').scrollIntoViewIfNeeded();if(!await page.locator('[data-party-result490="again"]').isVisible())throw Error('replay unreachable');if(await page.evaluate(()=>document.body.scrollWidth)>width)throw Error('result overflow');if(width===390){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:out+'/result.png',fullPage:true})}
 await page.evaluate(()=>resultQA(true));if(!(await page.locator('.sm-result-title535 h1').textContent()).includes('相打ち'))throw Error('draw');
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>sceneQA('charge'));await page.waitForTimeout(100);if(await page.locator('.sm-maxflare535').first().isVisible())throw Error('reduced motion flash');
 const art=await page.evaluate(async()=>Promise.all(['items','victory'].map(async n=>{const i=new Image();i.src='/assets/sumo535/'+n+'.webp';await i.decode();return[n,i.naturalWidth,i.naturalHeight]})));
 results.push({width,height,fit,heldChargeAfterHit:true,releaseDuringStun:true,singleUseBoots:true,standings,art,reducedMotion:true});await page.evaluate(()=>disposeQA());await page.close();
 }if(errors.length)throw Error(errors.join('\n'));await writeFile(out+'/browser-results.json',JSON.stringify({engine:'Chromium mobile emulation; production sumo rules/view/input/renderer, QA-only absent base character data',results,errors},null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close();server.close()}
