import {course589} from '../../src/runners587/Courses589.js';
import {makeRunners587,startRunners587,advanceRunners587,publicRunners587} from '../../src/runners587/Rules587.js';
import {runnersView587,runnersAfter587,runnersBefore587,runnersReceive587,runnersFrame587,runnersClick587,runnersKey587} from '../../src/runners587/View587.js';
const species=['slime','goblin','wolf','skeleton'].slice(0,Number(new URLSearchParams(location.search).get('people')||4)),members=species.map((speciesId,i)=>({playerId:'p'+i,name:['えなみ','りおん','より','ひで'][i],owned:[{id:'m'+i,speciesId}],choice:{id:'m'+i,speciesId},connected:true,ready:true,ai:false}));
const params=new URLSearchParams(location.search),now=Date.now();
let g=makeRunners587({id:'preview591',code:'TEST',partyId:'party',hostId:'p0',members,now});g.courseId=params.get('course')||'forest';
const queue=new Map(),c={root:document.querySelector('#app'),state:{party:{id:'party',code:'TEST',hostId:'p0',members,game:'runners'},runners:publicRunners587(g,'p0')},transport:{selfId:'p0'},offset:0,error:'',ready:()=>true,connected:()=>true,roster:()=>members.map(p=>p.choice),sgSpeciesName463:s=>s,refresh(){},raw(op,m){if(op==='runnersInput587'){const list=queue.get('p0')??[];list.push({...m,at:Date.now()+35});queue.set('p0',list);return true;}if(m.kind==='course'){g.courseId=m.courseId;c.state.runners=publicRunners587(g,'p0');c.render();}if(m.kind==='start')start();return true;},render(){runnersBefore587(c);c.root.innerHTML=runnersView587(c);runnersAfter587(c);}};
function start(){startRunners587(g,Date.now(),594);c.state.runners=publicRunners587(g,'p0');c.render();}
c.root.addEventListener('click',e=>{const b=e.target.closest('button');if(b)runnersClick587(c,b);});c.root.addEventListener('keydown',e=>runnersKey587(c,e));
let frozen=false,lastFrame=0;function tick(){const time=Date.now();if(!frozen){advanceRunners587(g,time,queue);if(time-lastFrame>=50){lastFrame=time;const frame={type:'runnersFrame587',selfId:'p0',serverNow:time,runners:publicRunners587(g,'p0')};runnersFrame587(c,frame);}}requestAnimationFrame(tick);}
window.preview591={c,course:()=>course589(g),get g(){return g;},start,freeze(v){frozen=v;},showLobby(){runnersBefore587(c);g=makeRunners587({id:'preview591-'+Date.now(),code:'TEST',partyId:'party',hostId:'p0',members,now:Date.now()});c.state.runners=publicRunners587(g,'p0');c.render();},setCourse(id){g.courseId=id;},setPosition(x,y=300){Object.assign(g.players[0],{x,y,vx:0,vy:0,furthest:x});c.state.runners=publicRunners587(g,'p0');runnersReceive587(c);c.runnersUI587.renderer.snap=true;}};
if(params.get('play')==='1')start();else c.render();tick();
