import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{tmpdir}from'node:os';
const{chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const dir=fs.mkdtempSync(path.join(tmpdir(),'party462-ws-')),env={...process.env,HOST:'127.0.0.1',PORT:'18871'};for(const[name,file]of Object.entries({FRIEND_STATE_FILE:'friends',GUILD_STATE_FILE:'guilds',POWER_RANKING_STATE_FILE:'rankings',SETTLEMENT_STATE_FILE:'settlements',WORLD_RAID_STATE_FILE:'raids',RACE_STATE_FILE:'race'}))env[name]=path.join(dir,file+'.json');
const processes=[],errors=[],checks=[];let browser;function launch(file,cwd,env,ready){const proc=spawn(process.execPath,[file],{cwd,env,stdio:['ignore','pipe','pipe']});processes.push(proc);return new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('startup timeout '+out)),15000);proc.stdout.on('data',b=>{out+=b;if(out.includes(ready)){clearTimeout(timer);resolve(proc)}});proc.stderr.on('data',b=>out+=b);proc.on('exit',c=>{if(c){clearTimeout(timer);reject(Error(out))}})})}
try{
 await launch('server.js',path.resolve('online-server'),env,'Local:');await launch('tools/build462/preview-server.mjs',process.cwd(),{...process.env,RACE_QA_ASSETS:path.resolve('../qa459/asset-cache')},'Preview462 ready');
 const executable=path.resolve('../browser459/chromium');browser=await chromium.launch({executablePath:executable,args:['--no-sandbox','--disable-dev-shm-usage'],env:{...process.env,LD_LIBRARY_PATH:path.dirname(executable)}});
 async function tab(name){const context=await browser.newContext({viewport:{width:393,height:800},isMobile:true,hasTouch:true});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.routeWebSocket('**/*',r=>new URL(r.url()).hostname==='127.0.0.1'?r.connectToServer():r.close());const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:18451/?name='+encodeURIComponent(name));await p.waitForFunction(()=>qa451.client.ready());await p.evaluate(()=>document.fonts.ready);return p}
 const host=await tab('えなみ'),guest=await tab('友達'),late=await tab('途中参加');
 await host.screenshot({path:'docs/build462/catalog.png'});assert.equal(await host.locator('.game-cover462').count(),1);assert.ok(await host.locator('.game-cover462 img').evaluate(e=>e.complete&&e.naturalWidth>1000));
 await host.locator('[data-party-game462=race]').click();await host.locator('[data-party-action462=create]').click();await host.waitForFunction(()=>qa451.client.state.room?.phase==='lobby');const code=await host.evaluate(()=>qa451.client.state.party.code),partyId=await host.evaluate(()=>qa451.client.state.party.id);
 await guest.locator('input[name=roomCode]').fill(code);await guest.locator('[data-party-action462=join]').click();await guest.waitForFunction(()=>qa451.client.state.party?.members.length===2);await host.waitForFunction(()=>qa451.client.state.party?.members.length===2);
 await host.locator('[data-race-distance459="500"]').click();await host.locator('[data-race-monster]').first().click();await guest.locator('[data-race-monster]').nth(1).click();await host.locator('[data-party-action462=ready]').click();assert.ok(await host.locator('[data-race-action=start]').isDisabled());await guest.locator('[data-party-action462=ready]').click();await host.waitForFunction(()=>qa451.client.state.party.members.every(m=>m.ready));
 await guest.locator('[data-race-action=back]').click();await host.waitForFunction(()=>qa451.client.state.party.members.some(m=>m.atHome));assert.ok(await host.locator('[data-race-action=start]').isDisabled());await guest.evaluate(()=>qa451.client.mount(document.querySelector('#app')));await guest.waitForFunction(()=>!qa451.client.state.party.members.find(m=>m.playerId===qa451.transport.selfId).atHome);await guest.locator('[data-party-action462=ready]').click();await host.waitForFunction(()=>qa451.client.state.party.members.every(m=>m.ready));checks.push('same party survives home/remount; every human must explicitly ready');
 await host.screenshot({path:'docs/build462/preparation.png'});await host.locator('[data-race-action=start]').click();await host.waitForFunction(()=>qa451.client.state.room.phase==='parade');await guest.waitForFunction(()=>qa451.client.state.room.phase==='parade');
 await late.locator('input[name=roomCode]').fill(code);await late.locator('[data-party-action462=join]').click();await late.waitForFunction(()=>qa451.client.state.party?.members.length===3);assert.equal(await late.locator('.is-spectator462').count(),1);assert.ok(await late.locator('[data-prediction-tab=bet]').isHidden());assert.ok(await late.locator('[data-race-action=bet]').isDisabled());checks.push('late join is read-only spectator; ticket and boost cannot be purchased');
 for(const p of[host,guest]){await p.locator('[data-prediction-tab=bet]').click();await p.locator('[data-race-action=pass]').click()}
 await host.waitForFunction(()=>qa451.client.state.room.phase==='race',{},{timeout:35000});await host.evaluate(()=>qa451.client.root.scrollTop=0);await host.locator('[data-race-camera461=overview]').click();await host.waitForTimeout(150);const straight=await host.locator('.world-viewport461').boundingBox();assert.ok(straight.height<85);await host.screenshot({path:'docs/build462/straight-overview.png'});await host.locator('[data-race-camera461=follow]').click();await host.waitForTimeout(200);const follow=await host.locator('.world-viewport461').boundingBox();assert.ok(follow.height>300);await host.screenshot({path:'docs/build462/straight-follow.png'});checks.push('straight overview collapses blank margins; follow restores full viewport');
 let button=await host.locator('[data-race-action=boost456]').boundingBox();for(let i=0;i<5;i++)await host.touchscreen.tap(button.x+button.width/2,button.y+button.height/2);await host.waitForFunction(()=>qa451.client.state.room.live456.runners.find((x,i)=>qa451.client.state.room.racers[i].ownerId===qa451.transport.selfId).boosts===5);assert.match(await host.locator('[data-boost-left]').innerText(),/0 \/ 5/);
 await host.waitForFunction(()=>qa451.client.state.room.phase==='result',{},{timeout:60000});await host.locator('[data-party-action462=lounge]').click();await host.waitForFunction(()=>!qa451.client.state.room);await guest.waitForFunction(()=>!qa451.client.state.room);assert.equal(await host.evaluate(()=>qa451.client.state.party.id),partyId);await host.screenshot({path:'docs/build462/lounge.png'});checks.push('result → catalogue keeps code, party and all three humans');
 await host.locator('[data-party-game462=race]').click();await host.waitForFunction(()=>qa451.client.state.room?.phase==='lobby');await late.waitForFunction(()=>qa451.client.state.room?.phase==='lobby');assert.equal(await late.locator('.is-spectator462').count(),0);await host.locator('[data-race-distance459="3000"]').click();
 for(const p of[host,guest,late]){await p.waitForFunction(()=>qa451.client.state.room?.track459.distance===3000);await p.locator('[data-race-monster]').first().click();await p.locator('[data-party-action462=ready]').click()}
 await host.waitForFunction(()=>qa451.client.state.party.members.every(m=>m.ready));await host.locator('[data-race-action=start]').click();await host.waitForFunction(()=>qa451.client.state.room.phase==='parade');for(const p of[host,guest,late]){await p.waitForFunction(()=>qa451.client.state.room.phase==='parade');await p.locator('[data-prediction-tab=bet]').click();await p.locator('[data-race-action=pass]').click()}
 await host.waitForFunction(()=>qa451.client.state.room.phase==='race',{},{timeout:35000});await host.evaluate(()=>qa451.client.root.scrollTop=0);await host.locator('[data-race-camera461=overview]').click();await host.waitForTimeout(150);const oval=await host.locator('.world-viewport461').boundingBox();assert.ok(oval.height<290);await host.screenshot({path:'docs/build462/oval-overview.png'});await host.locator('[data-race-camera461=follow]').click();await host.waitForTimeout(150);
 button=await host.locator('[data-race-action=boost456]').boundingBox();for(let i=0;i<20;i++)await host.touchscreen.tap(button.x+button.width/2,button.y+button.height/2);await host.waitForFunction(()=>qa451.client.state.room.live456.runners.find((x,i)=>qa451.client.state.room.racers[i].ownerId===qa451.transport.selfId).boosts===20);assert.match(await host.locator('[data-boost-left]').innerText(),/0 \/ 20/);await host.screenshot({path:'docs/build462/twenty-commands.png'});checks.push('3000m accepts 20 fast taps once each with correct UI; spectator participates next game');
 await guest.evaluate(()=>qa451.transport.ws.close());await guest.waitForFunction(()=>qa451.transport.connectionReady&&qa451.transport.ws.readyState===1,{},{timeout:25000});await guest.waitForFunction(id=>qa451.client.state.party.id===id,partyId);checks.push('socket reconnect resumes same party and active race');
 for(const width of[320,709]){await host.setViewportSize({width,height:800});await host.waitForTimeout(100);assert.ok(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
 // Direct rendering of the reported chapter-two sprite, using its native atlas.
 await host.evaluate(async()=>{const{monsterVisual}=await import('/src/ui/MonsterVisual.js');const el=document.createElement('section');el.className='race458';el.id='sprite-probe462';el.style='position:fixed;inset:0;background:#21172c;z-index:9999;display:grid;place-items:center';el.innerHTML='<div style="width:250px;height:250px">'+monsterVisual('ch2_lumea','◆',{className:'race-art451'})+'</div>';document.body.append(el)});await host.waitForTimeout(1500);await host.screenshot({path:'docs/build462/lumea-native.png'});const atlasUrl=await host.locator('#sprite-probe462 image').getAttribute('href');const atlasStatus=await host.evaluate(async url=>(await fetch(url)).status,atlasUrl);assert.equal(atlasStatus,200);await host.evaluate(()=>document.querySelector('#sprite-probe462').remove());
 assert.deepEqual(errors,[]);fs.writeFileSync('docs/build462/browser-results.json',JSON.stringify({checks,errors,overview:{straight:straight.height,oval:oval.height},limitations:'Chromium mobile touch; physical Safari untested.'},null,2));console.log(JSON.stringify({checks,errors}));
} catch(e){fs.writeFileSync('docs/build462/browser-errors.json',JSON.stringify({message:e.message,errors},null,2));throw e}finally{await browser?.close();for(const p of processes)p.kill();fs.rmSync(dir,{recursive:true,force:true})}
